window.BANKX = window.BANKX || {};
BANKX["acycles"] = {
  notes: [
    { h: "Comparing life cycles", t: "All these animals start as an egg, and only the adult can reproduce. In a 3-stage life cycle (cockroach, grasshopper, chicken) the young resembles the adult. In a 4-stage insect life cycle (butterfly, mosquito, housefly, mealworm beetle) the larva does not resemble the adult and there is a pupa stage. No animal has both a pupa stage and a young that resembles the adult. The frog has 4 stages but no pupa.", kw: ["all start as an egg", "only the adult reproduces", "young resembles the adult", "larva does not resemble the adult", "no pupa in the frog"] },
    { h: "Reading life cycle graphs", t: "On a graph of the length of a larva, the line rises because the larva feeds a lot and grows. When the line becomes flat and the animal stops feeding and hardly moves, it has most likely become a pupa. A bar graph of days spent in each stage lets you add up the total time from egg to adult.", kw: ["larva feeds and grows", "flat line: stopped growing", "pupa does not feed", "add up the days"] },
    { h: "Mosquito numbers and control", t: "More stagnant water (e.g. after heavy rain, choked roof gutters, uncovered pails) means more places for mosquitoes to lay eggs, so the number of mosquitoes rises a week or two later. Removing stagnant water, adding oil, or keeping fish such as guppies that eat the larvae stops larvae from developing into adults. Killing only the adults is not enough, because the larvae and pupae in the water will become new adults.", kw: ["stagnant water", "places to lay eggs", "larvae develop into adults", "killing only the adults is not enough"] }
  ],
  traps: [
    "A flat line for the pupa on a graph means the pupa is dead -> The pupa is alive; it does not feed or grow in size, but it changes inside.",
    "Mosquitoes breed in any water, even fast-flowing water -> They lay eggs in STAGNANT (still) water.",
    "Spraying to kill adult mosquitoes is enough -> Larvae and pupae in stagnant water will still become new adults; remove stagnant water too."
  ],
  mcq: [
    { q: "The diagram shows the life cycle of a housefly. What is the stage marked ‘?’ called?", o: ["Nymph", "Maggot", "Tadpole", "Chick"], a: 1, why: "The larva of the housefly is called a maggot. A nymph is the young of the cockroach or grasshopper, which have no pupa stage.", lvl: 1, fig: { type: "cycle", stages: ["Egg", "?", "Pupa", "Adult"] } },
    { q: "The diagram shows the life cycle of a chicken. What is the stage marked ‘?’", o: ["Chick", "Nymph", "Larva", "Pupa"], a: 0, why: "A chicken’s egg hatches into a chick, which grows into an adult. Nymph, larva and pupa are insect stages.", lvl: 1, fig: { type: "cycle", stages: ["Egg", "?", "Adult"] } },
    { q: "Where does a housefly usually lay its eggs?", o: ["On the underside of leaves", "On the surface of stagnant water", "On rotting food or rubbish", "Inside flowers"], a: 2, why: "Houseflies lay eggs on rotting food or rubbish, which the maggots feed on. Mosquitoes lay eggs on stagnant water; butterflies lay eggs on leaves.", lvl: 1 },
    { q: "Where does a frog lay its eggs?", o: ["In soil", "On leaves", "In a nest of twigs", "In water"], a: 3, why: "Frogs lay their eggs in water, because the tadpoles that hatch live in water and breathe through gills.", lvl: 1 },
    { q: "Study the graph of the length of a mealworm (larva). By how much did its length increase from Day 5 to Day 15?", o: ["9 mm", "17 mm", "11 mm", "22 mm"], a: 2, why: "Day 15 length (17 mm) minus Day 5 length (6 mm) = 11 mm. 17 mm is just the Day 15 reading, not the increase.", lvl: 2, fig: { type: "line", title: "Length of a mealworm", xl: "Day", yl: "Length (mm)", pts: [["0", 2], ["5", 6], ["10", 11], ["15", 17], ["20", 22]] } },
    { q: "The graph shows how many days a butterfly spent in each stage. How many days did the stage that does NOT feed last?", o: ["4 days", "14 days", "12 days", "10 days"], a: 3, why: "The pupa does not feed, and it lasted 10 days. 14 days is the larva, which feeds a lot.", lvl: 2, fig: { type: "bar", title: "Days in each stage of a butterfly", xl: "Stage", yl: "Number of days", bars: [["Egg", 4], ["Larva", 14], ["Pupa", 10], ["Adult", 12]] } },
    { q: "Study the Venn diagram. Which animal could be X?", o: ["Mealworm beetle", "Grasshopper", "Frog", "Mosquito"], a: 0, why: "X has a pupa stage but its young does not live in water, like the mealworm beetle. The mosquito would be in the overlap; the frog has no pupa; the grasshopper has neither.", lvl: 2, fig: { type: "venn", a: "Has a pupa stage", b: "Young lives in water", onlyA: ["butterfly", "housefly", "X"], both: ["mosquito"], onlyB: ["frog"], neither: ["cockroach", "chicken"] } },
    { q: "Study the flowchart. In which group is the frog?", o: ["A", "B", "C", "D"], a: 3, why: "The frog has no pupa stage, and its young (tadpole) does not look like the adult, so it is in D. C would be animals like the cockroach or chicken.", lvl: 2, fig: { type: "flow", root: "Animals", node: { q: "Has a pupa stage?", yes: { q: "Young lives in water?", yes: "A", no: "B" }, no: { q: "Young looks like adult?", yes: "C", no: "D" } } } },
    { q: "The diagram shows the life cycle of a mosquito. Which describes stage P?", o: ["It lives in water, does not feed and comes to the surface to breathe.", "It lives on land, feeds on blood and flies from place to place.", "It resembles the adult but has no wings and feeds on plant juices.", "It lives in water, breathes through gills and has a long tail."], a: 0, why: "P is the pupa (tumbler). It lives in water, does not feed and comes up to breathe air. ‘Resembles the adult’ describes a nymph; gills and a tail describe a tadpole.", lvl: 2, fig: { type: "cycle", stages: ["Egg", "Larva", "P", "Adult"] } },
    { q: "The graph shows the number of adult mosquitoes caught each week in an HDB estate. Residents started removing stagnant water at the end of Week 3. What does the graph show?", o: ["Removing stagnant water had no effect on the number of mosquitoes.", "The number of mosquitoes kept increasing even after Week 3.", "The number of mosquitoes decreased after stagnant water was removed.", "Mosquitoes breed only in Week 3, when the number was highest."], a: 2, why: "The number rose to 48 by Week 3 and then fell to 8 by Week 6, after the stagnant water was removed.", lvl: 2, fig: { type: "line", title: "Adult mosquitoes caught", xl: "Week", yl: "Number of mosquitoes", pts: [["1", 40], ["2", 45], ["3", 48], ["4", 30], ["5", 15], ["6", 8]] } },
    { q: "Which pair of young animals do NOT resemble their adults?", o: ["Nymph and chick", "Caterpillar and maggot", "Nymph and caterpillar", "Chick and maggot"], a: 1, why: "The caterpillar (butterfly larva) and maggot (housefly larva) are both larvae, which do not look like the adults. The nymph and chick both resemble their adults.", lvl: 2 },
    { q: "An NEA officer counted mosquito larvae in water found in four places. Study the graph. Which statement is correct?", o: ["Turned-over pails give mosquitoes the most places to lay eggs.", "Covering a water tank does not stop mosquitoes from breeding.", "Mosquitoes breed only in roof gutters, not in flower vases.", "Uncovered stagnant water gives mosquitoes a place to lay eggs."], a: 3, why: "Larvae were found only in the flower vase and choked gutter, which held uncovered stagnant water. None were in the turned-over pail or the covered tank.", lvl: 2, fig: { type: "bar", title: "Mosquito larvae found", xl: "Place", yl: "Number of larvae", bars: [["Flower vase", 12], ["Turned-over pail", 0], ["Choked gutter", 25], ["Covered tank", 0]] } },
    { q: "Study the graph of the length of an insect. From Day 12 to Day 20 it did not feed and hardly moved. Which stage was it most likely in from Day 12 to Day 20?", o: ["Pupa", "Egg", "Larva", "Adult"], a: 0, why: "The pupa does not feed and does not grow, so the length stays the same. A larva feeds and grows, so its length would still increase.", lvl: 3, fig: { type: "line", title: "Length of an insect", xl: "Day", yl: "Length (mm)", pts: [["0", 1], ["4", 5], ["8", 12], ["12", 20], ["16", 20], ["20", 20]] } },
    { q: "Sam wants to find out if a layer of oil on water kills mosquito larvae. Which two set-ups should he compare?", o: ["A and C", "B and C", "A and B", "A, B and C"], a: 2, why: "A and B differ only in the oil layer. A and C differ in the type of water, the number of larvae AND the oil, so it is not a fair test.", lvl: 3, fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Pond water", "20 larvae", "Thin layer of oil"] }, { label: "B", icon: "beaker", lines: ["Pond water", "20 larvae", "No oil"] }, { label: "C", icon: "beaker", lines: ["Tap water", "10 larvae", "No oil"] } ] } },
    { q: "The diagram shows a life cycle with 3 stages. Which animals could it belong to?\nA: Cockroach\nB: Chicken\nC: Mealworm beetle\nD: Grasshopper", o: ["A and D only", "A, B and D only", "B and C only", "A, B, C and D"], a: 1, why: "The cockroach, chicken and grasshopper all have 3 stages. The mealworm beetle has 4 stages (egg, larva, pupa, adult).", lvl: 3, fig: { type: "cycle", stages: ["Egg", "X", "Adult"] } },
    { q: "Study the graph. Heavy rain fell in Week 2 and left many puddles and pails of water. Which best explains the change in the number of mosquitoes?", o: ["The rain washed away the mosquito eggs, so fewer adults appeared in the following weeks.", "Stagnant water gave mosquitoes places to lay eggs, and the larvae became adults a week or two later.", "Mosquitoes only come out when it rains, so more of them were caught in the rainy week.", "The rain made the adult mosquitoes grow bigger, so they were easier to catch and count."], a: 1, why: "More stagnant water means more eggs laid; the eggs take time to develop through larva and pupa into adults, so the rise appears in Weeks 3 to 5.", lvl: 3, fig: { type: "line", title: "Adult mosquitoes caught", xl: "Week", yl: "Number of mosquitoes", pts: [["1", 20], ["2", 22], ["3", 35], ["4", 60], ["5", 75]] } },
    { q: "The graph shows the number of days a mosquito spends in each stage before becoming an adult. Mdm Lim wants to stop mosquitoes breeding in her vase. How often should she change the water?", o: ["Every 14 days", "Every 12 days", "Every 11 days", "Every 7 days"], a: 3, why: "Egg + larva + pupa = 2 + 7 + 2 = 11 days. She must change the water before 11 days pass, so every 7 days works; at 11 days adults may already have come out.", lvl: 3, fig: { type: "bar", title: "Days in each stage", xl: "Stage", yl: "Number of days", bars: [["Egg", 2], ["Larva", 7], ["Pupa", 2]] } },
    { q: "Which statements are true?\nA: Both the housefly and the mosquito have a pupa stage.\nB: Both the grasshopper nymph and the caterpillar moult.\nC: Both the chick and the cockroach nymph resemble their adults.\nD: Both the tadpole and the mosquito larva breathe through gills.", o: ["A and B only", "B and D only", "A, B and C only", "A, B, C and D"], a: 2, why: "A, B and C are true. D is false: the mosquito larva comes up to the water surface to breathe air through a breathing tube.", lvl: 3 },
    { q: "Study the Venn diagram. Why is the overlapping region empty?", o: ["An animal with a pupa stage has a larva that does not look like the adult.", "Only insects whose young live in water, like mosquitoes, have a pupa stage.", "Animals with a pupa stage give birth to live young instead of laying eggs.", "The frog was left out of the diagram by mistake, so the region is empty."], a: 0, why: "Insects with a pupa stage have a larva that looks very different from the adult, so no animal can be in both circles. The frog is in ‘neither’.", lvl: 3, fig: { type: "venn", a: "Young resembles adult", b: "Has a pupa stage", onlyA: ["cockroach", "grasshopper", "chicken"], both: [], onlyB: ["butterfly", "mosquito", "housefly"], neither: ["frog"] } },
    { q: "Stage P of an insect resembles the adult, has no wings and feeds on leaves. Which insect is it, and what will P become next?", o: ["Butterfly; pupa", "Grasshopper; adult", "Grasshopper; pupa", "Mosquito; adult"], a: 1, why: "P is a grasshopper nymph (resembles adult, no wings, eats leaves). A nymph becomes an adult directly — there is no pupa stage.", lvl: 3 }
  ],
  tf: [
    { s: "Mosquitoes lay their eggs in fast-flowing water such as a canal after a storm.", a: false, why: "They lay eggs on still (stagnant) water." },
    { s: "The housefly has four stages in its life cycle.", a: true, why: "Egg, larva (maggot), pupa, adult." },
    { s: "Every animal with four stages in its life cycle has a pupa stage.", a: false, why: "The frog has four stages but no pupa." },
    { s: "The pupa of a mealworm beetle feeds on bran.", a: false, why: "Only the larva (mealworm) feeds; the pupa does not feed." },
    { s: "Killing adult mosquitoes alone is enough; there is no need to remove stagnant water.", a: false, why: "Larvae and pupae in the water will become new adults." },
    { s: "The cockroach and the grasshopper both have a nymph stage.", a: true, why: "Both go through egg, nymph and adult." },
    { s: "A chick hatches from an egg and looks similar to the adult chicken.", a: true, why: "The chicken has a 3-stage life cycle; the young resembles the adult." },
    { s: "A butterfly larva grows longer, but its pupa stays about the same size.", a: true, why: "The pupa does not feed or grow; changes happen inside it." }
  ],
  oe: [
    { q: "The diagram shows the life cycle of a mosquito. (a) Name stage P. (b) Name stage Q. (c) Where do stages P and Q live? (d) Explain how turning over pails helps to stop mosquitoes from breeding.", marks: 4, kw: [["larva", "wriggler"], ["pupa", "tumbler"], ["water"], ["stagnant", "lay eggs", "lay their eggs"]], model: "(a) P is the larva (wriggler). (b) Q is the pupa (tumbler). (c) They live in water. (d) Turning over pails means no stagnant water collects in them, so mosquitoes have no place to lay their eggs.", fig: { type: "cycle", stages: ["Egg", "P", "Q", "Adult"] } },
    { q: "Study the graph of the length of an insect. (a) What was its length on Day 6? (b) From Day 9, the length stayed the same. Which stage was it most likely in? (c) Give one reason for your answer in (b).", marks: 3, kw: [["11"], ["pupa"], ["does not feed", "not feed", "doesn't feed", "doesn't eat", "not eat", "stop feeding", "stopped feeding", "not grow", "doesn't grow", "stopped growing"]], model: "(a) 11 mm. (b) The pupa stage. (c) The pupa does not feed, so it does not grow and its length stays the same.", fig: { type: "line", title: "Length of an insect", xl: "Day", yl: "Length (mm)", pts: [["0", 2], ["3", 6], ["6", 11], ["9", 16], ["12", 16], ["15", 16]] } },
    { q: "The graph shows the number of days a butterfly spent in each stage before becoming an adult. (a) How many days after the egg was laid did the adult come out? (b) Which stage damages crops? (c) For how many days did this stage damage the crops?", marks: 3, kw: [["30"], ["larva", "caterpillar"], ["15"]], model: "(a) 30 days (5 + 15 + 10). (b) The larva (caterpillar) stage, because it eats leaves. (c) 15 days.", fig: { type: "bar", title: "Days in each stage of a butterfly", xl: "Stage", yl: "Number of days", bars: [["Egg", 5], ["Larva", 15], ["Pupa", 10]] } },
    { q: "Study the Venn diagram. (a) Why is the mosquito placed in the overlapping region? (b) Name the young of the frog that lives in water. (c) State one difference between the life cycles of the frog and the mosquito.", marks: 3, kw: [["larva"], ["tadpole"], ["pupa"]], model: "(a) The mosquito has a larva stage and its larva lives in water. (b) The tadpole. (c) The mosquito has a pupa stage, but the frog does not have a pupa stage.", fig: { type: "venn", a: "Has a larva stage", b: "Young lives in water", onlyA: ["butterfly", "housefly"], both: ["mosquito"], onlyB: ["frog"], neither: ["cockroach", "chicken"] } },
    { q: "Study the graph. Residents cleared choked roof gutters and removed stagnant water at the end of Week 3. Explain why the number of adult mosquitoes decreased.", marks: 2, kw: [["stagnant"], ["lay eggs", "lay their eggs", "larva", "larvae"]], model: "Without stagnant water, mosquitoes had no place to lay their eggs, and no larvae could develop into new adults, so fewer adults were caught.", fig: { type: "line", title: "Adult mosquitoes caught", xl: "Week", yl: "Number of mosquitoes", pts: [["1", 40], ["2", 45], ["3", 48], ["4", 30], ["5", 15], ["6", 8]] } },
    { q: "Jia Hui keeps mealworm beetles in a container of bran. (a) Which stage eats the bran and moults? (b) Name the stage that comes after it. (c) She wants fewer mealworms next month. Explain why she should remove the adult beetles.", marks: 3, kw: [["larva", "larvae"], ["pupa"], ["lay eggs", "lays eggs", "reproduce"]], model: "(a) The larva (mealworm). (b) The pupa. (c) The adult beetles lay eggs that hatch into more mealworms. Removing them means fewer eggs are laid." },
    { q: "Mdm Ho said the housefly and the cockroach have the same life cycle because they are both insects. Is she correct? Explain.", marks: 2, kw: [["not correct", "incorrect", "wrong", "not right"], ["pupa", "4 stages", "four stages", "3 stages", "three stages", "nymph"]], model: "She is not correct. The housefly has 4 stages (egg, larva, pupa, adult), but the cockroach has only 3 stages (egg, nymph, adult) and no pupa." },
    { q: "Guppies are sometimes kept in ponds because they eat mosquito larvae. Explain how this helps to reduce the number of adult mosquitoes.", marks: 2, kw: [["larva", "larvae"], ["pupa", "adult", "develop", "become"]], model: "The guppies eat the mosquito larvae, so fewer larvae are left to develop into pupae and then adult mosquitoes." }
  ],
  doc: [
    { q: "State one difference between the life cycle of a butterfly and a grasshopper.", marks: 1, answers: ["The butterfly can fly but the grasshopper hops.", "The butterfly is prettier.", "The butterfly has a pupa stage but the grasshopper does not."], best: 2, why: "Answer 3 compares the LIFE CYCLES (pupa stage). Answer 1 compares how adults move, not their life cycles. Answer 2 is an opinion, not science." },
    { q: "Explain why a layer of oil on stagnant water kills mosquito larvae.", marks: 2, answers: ["The oil stops the larvae from getting air at the water surface, so they cannot breathe and die.", "The oil is poisonous.", "The larvae cannot swim in oil."], best: 0, why: "Answer 1 links the oil layer to the larvae not getting air at the surface. Answer 2 gives no scientific reason. Answer 3 is wrong — the problem is air, not swimming." },
    { q: "A pupa does not move or feed. Is it alive? Explain.", marks: 2, answers: ["No, because it does not move or eat.", "Yes, it is alive because changes are happening inside it as it develops into an adult.", "Yes, because it is a pupa."], best: 1, why: "Answer 2 says it is alive AND gives the reason (it is developing into an adult). Answer 1 is the common misconception. Answer 3 repeats the question without a reason." },
    { q: "Explain why a nymph moults several times.", marks: 2, answers: ["To change into a pupa.", "Because it is growing.", "Its outer skin cannot stretch, so it sheds its skin to grow bigger."], best: 2, why: "Answer 3 has both ideas: the skin does not stretch, and shedding lets it grow bigger. Answer 2 is too vague (no mention of the skin). Answer 1 is wrong — a nymph has no pupa stage." },
    { q: "How does a tadpole breathe, and how is this different from an adult frog?", marks: 2, answers: ["A tadpole breathes through gills; an adult frog breathes through lungs and its moist skin.", "Both breathe through their noses.", "A tadpole breathes through lungs; an adult frog breathes through gills."], best: 0, why: "Answer 1 is correct for both stages. Answer 3 has it the wrong way round. Answer 2 is vague and wrong for the tadpole." }
  ]
};
