window.BANKV = window.BANKV || {};
BANKV["acycles"] = {
  flash: [
    { f: "Define: life cycle", b: "The series of stages an animal goes through as it grows and develops into an adult. The adult reproduces, so the cycle starts again." },
    { f: "Stages in the life cycle of a cockroach or grasshopper", b: "Egg → nymph → adult (3 stages). There is no larva and no pupa stage." },
    { f: "Stages in the life cycle of a butterfly", b: "Egg → larva (caterpillar) → pupa (chrysalis) → adult (4 stages)." },
    { f: "Stages in the life cycle of a frog", b: "Egg → tadpole → froglet → adult frog. It has 4 stages but NO pupa stage." },
    { f: "Nymph or larva: how do you tell them apart?", b: "A nymph resembles the adult but is smaller and has no wings. A larva does not resemble the adult at all." },
    { f: "Define: moulting", b: "Shedding the outer skin so that the young insect can grow bigger. It happens in the larva and nymph stages; adult insects do not moult." },
    { f: "Why does a caterpillar need to moult?", b: "Its outer skin cannot stretch, so it sheds the old skin to grow bigger." },
    { f: "What does the larva stage mainly do?", b: "It feeds a lot and grows bigger, moulting several times as it grows." },
    { f: "Is a pupa alive? What happens in the pupa stage?", b: "Yes. The pupa does not feed, but its body changes greatly inside as it develops into the adult." },
    { f: "Which stage of an insect can reproduce?", b: "Only the adult. It lays eggs, so the life cycle starts again." },
    { f: "Why does a mosquito lay its eggs in stagnant water?", b: "Its larvae and pupae live in water, so they need stagnant water to develop into adults." },
    { f: "How do mosquito larvae and pupae breathe?", b: "They come up to the water surface to breathe air through breathing tubes." },
    { f: "Why does a layer of oil on stagnant water kill mosquito larvae and pupae?", b: "The oil layer stops them from getting air at the water surface, so they cannot breathe and die before becoming adults." },
    { f: "Why does a butterfly lay its eggs on the leaves of certain plants?", b: "So that the caterpillars have food to eat as soon as they hatch." },
    { f: "Tadpole vs adult frog: how do they breathe and where do they live?", b: "Tadpole: lives in water, has a tail, breathes through gills. Adult frog: no tail, breathes through lungs and moist skin, can live on land." }
  ],
  mcq: [
    { q: "At the butterfly garden in Changi Airport, visitors can see chrysalises hanging from twigs. Which stage of the butterfly is a chrysalis?", o: ["Egg", "Larva", "Pupa", "Adult"], a: 2, lvl: 1,
      why: "The chrysalis is the pupa of the butterfly. The larva is the caterpillar, which comes before it." },
    { q: "The diagram shows the life cycle of a dragonfly. Its young lives in water and has no wings. What is the stage marked ‘?’ called?", o: ["Larva", "Nymph", "Pupa", "Tadpole"], a: 1, lvl: 1,
      why: "A 3-stage insect life cycle is egg, nymph and adult. A larva and pupa belong to 4-stage life cycles, and a tadpole is the young of a frog.",
      fig: { type: "cycle", stages: ["Egg", "?", "Adult"] } },
    { q: "What does the larva stage of a butterfly mainly do?", o: ["It feeds a lot and grows bigger.", "It lays eggs so more young hatch.", "It stays still and does not feed.", "It sucks nectar from flowers."], a: 0, lvl: 1,
      why: "The larva (caterpillar) eats leaves and grows, moulting several times. The pupa stays still and does not feed; the adult sucks nectar and lays eggs." },
    { q: "Which statement about an adult insect is correct?", o: ["It moults many times to grow its wings.", "It cannot lay eggs until it has moulted.", "It grows bigger each time it feeds.", "It is fully grown and does not moult."], a: 3, lvl: 1,
      why: "An adult insect is fully grown, so it does not moult or grow bigger. Moulting happens only in the larva and nymph stages." },
    { q: "A lime butterfly lays its eggs on the leaves of a lime plant. What is the most likely reason?", o: ["So that the adults can feed on the leaves", "So that the caterpillars have food when they hatch", "So that the pupae can feed on the leaves", "So that the eggs can take in water from the leaves"], a: 1, lvl: 2,
      why: "The caterpillars that hatch eat the leaves, so the eggs are laid on their food plant. The adult sucks nectar and the pupa does not feed." },
    { q: "NEA asks HDB residents to do the ‘Mozzie Wipeout’. Which of these actions help to stop mosquitoes from breeding?\nA: Breaking up hardened soil in flower pots\nB: Leaving water in the plates under flower pots\nC: Clearing fallen leaves from roof gutters\nD: Covering water storage containers tightly", o: ["A and C only", "B and D only", "A, C and D only", "A, B, C and D"], a: 2, lvl: 2,
      why: "A, C and D stop stagnant water from collecting or keep mosquitoes away from it (rainwater pools on top of hardened soil and in choked gutters). B leaves stagnant water where mosquitoes can lay eggs." },
    { q: "At a hawker centre, leftover food was left in an uncovered bin for a few days. Which would most likely be found in the food?", o: ["Tadpoles feeding on the food", "Tumblers floating on the food", "Caterpillars feeding on the food", "Maggots feeding on the food"], a: 3, lvl: 2,
      why: "Houseflies lay eggs on rotting food, and the larvae (maggots) feed on it. Tumblers are mosquito pupae in water, tadpoles live in ponds and caterpillars eat leaves." },
    { q: "Mei put a caterpillar that had just become a pupa into a box with fresh lime leaves. What will most likely happen to the leaves over the next 5 days?", o: ["They will not be eaten, as the pupa does not feed.", "They will be eaten fast, as the pupa needs food to change.", "They will be eaten slowly, as the pupa feeds less than a larva.", "They will be eaten, then the pupa will moult into an adult."], a: 0, lvl: 2,
      why: "The pupa does not feed at all, although big changes happen inside it. Only the larva eats the leaves." },
    { q: "Jia Le kept a tadpole in a tank at school and recorded what he saw. Study the table. In which week was it first a froglet?", o: ["Week 1", "Week 4", "Week 6", "Week 9"], a: 2, lvl: 2,
      why: "A froglet has four legs and a short tail, which Jia Le first saw in Week 6. In Week 4 it was still a tadpole with back legs only, and in Week 9 it was an adult frog.",
      tbl: [["Week", "What Jia Le saw"], ["1", "Long tail, no legs, lives in water"], ["4", "Back legs only, long tail"], ["6", "Four legs and a short tail"], ["9", "No tail, climbs out onto a rock"]] },
    { q: "Jun wants to find out if the amount of food affects how fast tadpoles grow legs. Study the set-ups. Which two set-ups should he compare?", o: ["B and C", "A and B", "B and D", "A and C"], a: 1, lvl: 2,
      why: "A and B differ only in the amount of water plants (food). B and C differ in the number of tadpoles, B and D in the place, and A and C in two variables.",
      fig: { type: "setups", items: [
        { label: "A", icon: "jar", lines: ["10 tadpoles", "5 g of water plants", "Shady place"] },
        { label: "B", icon: "jar", lines: ["10 tadpoles", "20 g of water plants", "Shady place"] },
        { label: "C", icon: "jar", lines: ["5 tadpoles", "20 g of water plants", "Shady place"] },
        { label: "D", icon: "jar", lines: ["10 tadpoles", "20 g of water plants", "Sunny place"] } ] } },
    { q: "Which statement about the life cycle of a frog is NOT correct?", o: ["The tadpole breathes through gills in water.", "The froglet has four legs and a short tail.", "The tadpole becomes a pupa, then a froglet.", "The adult frog breathes through lungs and skin."], a: 2, lvl: 2,
      why: "The frog has no pupa stage: the tadpole grows legs and becomes a froglet directly. The other three statements are correct." },
    { q: "At Dragonfly Lake in Gardens by the Bay, dragonflies lay their eggs in the water. Their young live in the water until they become adults. Which stages of the dragonfly can be found living in the lake water?", o: ["Egg, larva and pupa", "Nymph and pupa only", "Egg, nymph and adult", "Egg and nymph only"], a: 3, lvl: 3,
      why: "The dragonfly has 3 stages: egg, nymph and adult. The eggs and nymphs are in the water, but the adult flies about. It has no larva or pupa." },
    { q: "An NEA officer scooped water from a choked roof gutter of an HDB block and counted the mosquitoes at each stage. Study the graph. How many of the mosquitoes counted were at a stage that feeds?", o: ["12", "45", "57", "87"], a: 1, lvl: 3,
      why: "Only the larvae feed, so the answer is 45. 57 wrongly adds the 12 pupae, which do not feed, and 87 adds the eggs as well.",
      fig: { type: "bar", title: "Mosquitoes found in a gutter", xl: "Stage", yl: "Number found", bars: [["Eggs", 30], ["Larvae", 45], ["Pupae", 12]] } },
    { q: "In which pair of animals does the young feed on a DIFFERENT kind of food from the adult in BOTH animals?", o: ["Butterfly and frog", "Grasshopper and chicken", "Ladybird and cockroach", "Cockroach and grasshopper"], a: 0, lvl: 3,
      why: "The caterpillar eats leaves but the butterfly sucks nectar; the tadpole eats water plants but the adult frog eats insects. In the other animals, the young and adult eat the same kind of food." },
    { q: "Which statements are true for ALL insects with a 4-stage life cycle (egg, larva, pupa, adult)?\nA: The larva moults as it grows.\nB: The pupa does not feed.\nC: The larva lives in water.\nD: Only the adult can lay eggs.", o: ["A and B only", "A, B and D only", "B, C and D only", "A, B, C and D"], a: 1, lvl: 3,
      why: "A, B and D are true for every 4-stage insect. C is true only for some, such as the mosquito; the caterpillar and mealworm do not live in water." },
    { q: "The Venn diagram groups some stages of insect life cycles. Which stage could be X?", o: ["Housefly pupa", "Adult grasshopper", "Mosquito larva", "Grasshopper egg"], a: 2, lvl: 3,
      why: "X both feeds and moults, so it must be a larva or nymph, such as the mosquito larva. An adult grasshopper feeds but does not moult; a pupa and an egg do neither.",
      fig: { type: "venn", a: "Feeds", b: "Moults", onlyA: ["adult butterfly", "adult housefly"], both: ["caterpillar", "X"], onlyB: [], neither: ["egg", "pupa"] } },
    { q: "Study the flowchart of stages in insect life cycles. Which shows the groups for the mosquito pupa and the cockroach nymph, in that order?", o: ["A and B", "C and A", "D and B", "C and B"], a: 3, lvl: 3,
      why: "The mosquito pupa does not feed and lives in water, so it is in C. The cockroach nymph feeds and has no wings, so it is in B.",
      fig: { type: "flow", root: "Stages", node: { q: "Does it feed?", yes: { q: "Has wings?", yes: "A", no: "B" }, no: { q: "Lives in water?", yes: "C", no: "D" } } } },
    { q: "Ali kept 5 caterpillars in a box and gave them fresh lime leaves every day. He counted the leaves they ate each day. Up to Day 14 he saw no winged insects in the box. Study the graph. Which is the best conclusion?", o: ["They ate more as they grew, then became pupae and stopped feeding.", "They ran out of leaves on Day 10, so all of them died of hunger.", "The adults came out on Day 10 and fed only on nectar after that.", "They moulted on Day 10 and became nymphs that did not feed."], a: 0, lvl: 4,
      why: "Feeding rose as the larvae grew, then stopped on Day 10. Fresh leaves were given daily, so they did not run out, and no winged adults appeared, so they had become pupae, which do not feed. Butterflies have no nymph.",
      fig: { type: "line", title: "Leaves eaten by caterpillars", xl: "Day", yl: "Number of leaves eaten", pts: [["2", 3], ["4", 5], ["6", 8], ["8", 12], ["10", 0], ["12", 0], ["14", 0]] } },
    { q: "Two school ponds were the same in every way, except that Pond B had dragonfly nymphs living in it. A teacher counted the mosquito larvae in each pond. Study the graph. Compared with Pond A, what will most likely happen to the number of adult mosquitoes around Pond B in the next few weeks?", o: ["Fewer, as fewer larvae survive to become pupae and adults.", "More, as the nymphs leave more food for the larvae to eat.", "The same, as dragonfly nymphs eat only adult mosquitoes.", "More, as adult dragonflies chase mosquitoes towards Pond B."], a: 0, lvl: 4,
      why: "Pond B had far fewer larvae, so the nymphs are likely eating them. Fewer larvae survive to become pupae and then adults, so fewer adult mosquitoes will appear. The nymphs live in water, so they eat larvae, not flying adults.",
      fig: { type: "bar", title: "Mosquito larvae in each pond", xl: "Pond", yl: "Number of larvae", bars: [["A: no nymphs", 80], ["B: with nymphs", 15]] } },
    { q: "The table shows how long a mosquito spends in each stage before becoming an adult. Eggs were laid in a pond on Day 0. On Day 9, Mr Lim poured a thin layer of oil on the pond. Will this stop these mosquitoes from becoming adults?", o: ["No; they are already adults and have flown away.", "No; they are pupae, which do not need air to live.", "Yes; they are larvae, which need air at the surface.", "Yes; they are pupae, which also need air at the surface."], a: 3, lvl: 4,
      why: "The eggs hatch on Day 2, the larvae become pupae on Day 8 and the adults come out on Day 11. On Day 9 they are pupae, which also come up to the surface to breathe air, so the oil stops them.",
      tbl: [["Stage", "Number of days"], ["Egg", "2"], ["Larva", "6"], ["Pupa", "3"]] }
  ],
  oe: [
    { q: "A butterfly garden grows many lime plants as well as flowering plants. (a) Which stage of the butterfly feeds on the lime leaves? (b) Why does the garden also need flowering plants for the butterflies? (c) Explain why the butterflies lay their eggs on the lime plants.", marks: 3,
      kw: [["larva", "larvae", "caterpillar"], ["nectar"], ["have food", "food to eat", "food when", "food as soon", "food once", "when they hatch", "once they hatch", "after they hatch"]],
      model: "(a) The larva (caterpillar). (b) The adult butterflies suck nectar from the flowers. (c) So that the caterpillars have food to eat as soon as they hatch from the eggs." },
    { q: "Siti left three pails outdoors for 2 weeks during the rainy season. Study the results. (a) Explain why there were no larvae in Pail B. (b) Explain why there were no larvae in Pail C. (c) Her brother says it is enough to spray insecticide at the adult mosquitoes near Pail A. Explain why he is wrong.", marks: 3,
      tbl: [["Pail", "How it was left", "Mosquito larvae after 2 weeks"], ["A", "Upright, no lid", "35"], ["B", "Upright, covered with a lid", "0"], ["C", "Turned upside down", "0"]],
      kw: [["lid", "cover", "reach", "get to the water", "get into"], ["no water", "no stagnant", "not collect", "cannot collect", "could not collect", "did not collect", "didn't collect", "empty"], ["still develop", "still become", "still grow", "will become", "will develop", "develop into", "grow into"]],
      model: "(a) The lid stopped mosquitoes from reaching the water to lay their eggs. (b) No water could collect in the pail, so there was no stagnant water for mosquitoes to lay eggs in. (c) Spraying kills only the adults. The larvae and pupae in the water of Pail A will still develop into new adult mosquitoes." },
    { q: "The diagram shows the life cycle of a dragonfly. (a) Name stage P. (b) Give one reason why the young of the dragonfly is not called a larva. (c) Dragonfly nymphs live in ponds and eat mosquito larvae. Explain how this helps to reduce the number of adult mosquitoes.", marks: 4,
      fig: { type: "cycle", stages: ["Egg", "P", "Adult"] },
      kw: [["nymph"], ["no pupa", "not have a pupa", "doesn't have a pupa", "without a pupa", "3 stages", "three stages", "resembl", "looks like the adult"], ["fewer", "less"], ["develop into", "grow into", "become pupa", "become adult", "into pupae", "into adults"]],
      model: "(a) P is the nymph. (b) The dragonfly has no pupa stage; it has only 3 stages: egg, nymph and adult. (c) Fewer mosquito larvae are left to develop into pupae and then into adults, so fewer adult mosquitoes come out." },
    { q: "Mr Tan sells mealworms (larvae) at his pet shop as food for pet birds. He kept 20 mealworms in a box of bran at 25 °C and another 20 mealworms in a box of bran at 30 °C. After 4 weeks, he counted the stages in each box. Study the results. (a) Which variable did he change? (b) At which temperature did the mealworms develop faster? Use the results to explain your answer. (c) Mr Tan wants his mealworms to stay as larvae for as long as possible. At which temperature should he keep them?", marks: 4, x: 1,
      tbl: [["Box", "Temperature", "Larvae", "Pupae", "Adult beetles"], ["A", "25 °C", "16", "4", "0"], ["B", "30 °C", "5", "10", "5"]],
      kw: [["temperature"], ["30"], ["more pupae", "more adult", "fewer larvae", "less larvae", "10 pupae", "5 adult"], ["25"]],
      model: "(a) The temperature. (b) At 30 °C. After 4 weeks, Box B had more pupae and more adult beetles, and fewer larvae, than Box A. (c) At 25 °C, because the mealworms take longer to become pupae there, so they stay as larvae for longer." }
  ],
  tf: [
    { s: "The froglet is the pupa stage of the frog.", a: false, why: "The frog has no pupa stage. A froglet moves about actively, while a pupa stays still and does not feed." },
    { s: "A caterpillar grows its wings bit by bit while it keeps eating leaves.", a: false, why: "The caterpillar has no wings. The big changes happen inside the pupa, which does not feed." },
    { s: "A mosquito pupa can move about in the water even though it does not feed.", a: true, why: "The tumbler tumbles in the water and comes up to breathe, but it does not feed." },
    { s: "All insects have a pupa stage in their life cycles.", a: false, why: "The cockroach, grasshopper and dragonfly go through egg, nymph and adult, with no pupa." },
    { s: "The young of a dragonfly lives in water.", a: true, why: "Dragonflies lay eggs in water, and the nymphs live there until they become flying adults." },
    { s: "A butterfly lays its eggs on any plant that it lands on.", a: false, why: "It lays its eggs on the plants its caterpillars feed on, so they have food when they hatch." },
    { s: "A tadpole and an adult frog feed on the same kind of food.", a: false, why: "Tadpoles feed on water plants, while adult frogs eat insects." },
    { s: "A cockroach nymph and an adult cockroach eat the same kind of food.", a: true, why: "In a 3-stage insect life cycle, the nymph usually feeds on the same food as the adult." },
    { s: "Rainwater that collects on hardened soil in a flower pot can become a breeding place for mosquitoes.", a: true, why: "The water cannot soak in, so it stays as stagnant water where mosquitoes can lay eggs." },
    { s: "The larva is the stage of the butterfly that grows the most in size.", a: true, why: "The larva feeds a lot and moults several times as it grows; the pupa and adult do not grow bigger." }
  ],
  sort: [
    { title: "Does this stage feed?", groups: ["Feeds", "Does not feed"], items: [["caterpillar", 0], ["mosquito larva (wriggler)", 0], ["grasshopper nymph", 0], ["adult butterfly", 0], ["tadpole", 0], ["maggot", 0], ["mosquito pupa (tumbler)", 1], ["butterfly pupa (chrysalis)", 1], ["mealworm beetle pupa", 1]] }
  ]
};
