window.BANKZ = window.BANKZ || {};
BANKZ["animals"] = {
  lessons: [
    {
      h: "Stating a similarity or a difference",
      concept: "A difference must describe the SAME characteristic for BOTH animals, joined with ‘but’ or ‘while’, e.g. ‘The bird has feathers, but the cat has fur.’ Writing about only one animal (‘The cat has fur.’) usually earns no mark. A similarity must be true for both animals, e.g. ‘Both breathe through lungs.’ Use characteristics that are used for classifying (body covering, how they breathe, how they reproduce), not size or colour.",
      example: {
        q: "The smooth-coated otter and the estuarine crocodile both live in and around the rivers of Singapore, and both swim well. (a) State one similarity in how they breathe. (b) State one difference between their body coverings.",
        marks: 2,
        think: [
          "Step 1: Name the group of each animal first. The otter is a mammal and the crocodile is a reptile.",
          "Step 2: For (a), think of what is true for BOTH. Mammals and reptiles both breathe through lungs, even when they swim. Start with ‘Both…’.",
          "Step 3: For (b), pick ONE characteristic (body covering) and describe it for each animal: the otter has fur, the crocodile has dry, scaly skin.",
          "Step 4: Join the two halves with ‘but’. Do not compare different things, such as the otter’s fur and the crocodile’s long tail."
        ],
        answer: "(a) Both of them breathe through lungs. (b) The otter has fur, but the crocodile has dry, scaly skin."
      },
      tip: "For a difference, write both halves about the same characteristic: ‘X has ___, but Y has ___.’",
      try: {
        q: "Which is a correctly stated difference between a frog and a lizard?",
        o: ["The frog has moist skin, but the lizard has dry, scaly skin.", "The frog has moist skin, and it lays its eggs in water.", "The frog has moist skin, but the lizard has a long tail.", "The lizard has dry, scaly skin, and it lays eggs on land."],
        a: 0,
        why: "The first option describes the same characteristic (skin) for both animals. The second and fourth describe only one animal, and the third compares two different characteristics (skin and tail)."
      }
    }
  ],
  mcq: [
    { q: "The whale shark is the biggest fish in the sea. Which characteristic shows that it is a fish and NOT a whale?", o: ["It breathes through gills.", "It lives in the open sea.", "It has a very big body.", "It swims by moving its tail."], a: 0, why: "Gills are a characteristic of fish; a whale breathes through lungs. Misconception: the word ‘whale’ in its name does not make it a mammal, and living in the sea or being big is true of both whales and fish.", lvl: 1 },
    { q: "How many pairs of feelers does an insect have?", o: ["2", "3", "1", "0"], a: 2, why: "Insects have 1 pair of feelers (antennae). 3 is the number of pairs of legs, not feelers.", lvl: 1 },
    { q: "The table shows the body covering of four animals, P, Q, R and S. Which animal is a bird?", o: ["P", "Q", "R", "S"], a: 1, why: "Only birds have feathers, so Q is the bird. Fur belongs to mammals, dry scales to reptiles and moist skin to amphibians.", lvl: 1, tbl: [["Animal", "Body covering"], ["P", "Fur"], ["Q", "Feathers"], ["R", "Dry scales"], ["S", "Moist skin"]] },
    { q: "Which of these small animals is an insect?", o: ["Woodlouse", "Tick", "Prawn", "Silverfish"], a: 3, why: "The silverfish has 3 body parts, 6 legs and 1 pair of feelers, so it is an insect even though it has no wings. Misconception: the word ‘fish’ in its name does not make it a fish. The tick has 8 legs, and the woodlouse and prawn have more than 6 legs.", lvl: 2 },
    { q: "Study the Venn diagram. Which animal could be X?", o: ["Housefly", "Ostrich", "Sparrow", "Dugong"], a: 0, why: "X can fly but has no feathers, like the bat. The housefly fits. The ostrich has feathers but cannot fly, the sparrow can fly and has feathers, and the dugong does neither.", lvl: 2, fig: { type: "venn", a: "Can fly", b: "Has feathers", onlyA: ["bat", "X"], both: ["hornbill", "pigeon"], onlyB: ["penguin"], neither: ["otter"] } },
    { q: "Study the classification key. Which animal ends at D?", o: ["Stingray", "Hornbill", "Otter", "Toad"], a: 3, why: "The toad has no fur, no feathers and no fins, so it ends at D. The otter (fur) ends at A, the hornbill (feathers) at B and the stingray (fins) at C.", lvl: 2, fig: { type: "flow", root: "Animals", node: { q: "Has fur or hair?", yes: "A", no: { q: "Has feathers?", yes: "B", no: { q: "Has fins?", yes: "C", no: "D" } } } } },
    { q: "The table describes how four animals, W, X, Y and Z, reproduce. Which animal is most likely an amphibian?", o: ["W", "X", "Y", "Z"], a: 3, why: "Amphibians lay eggs without shells in water, so Z is the amphibian. W (hard shell) is like a bird, X (leathery shell) is like a reptile, and Y does not lay eggs.", lvl: 2, tbl: [["Animal", "How it reproduces"], ["W", "Lays eggs with hard shells in a nest"], ["X", "Lays eggs with leathery shells in sand"], ["Y", "Gives birth to young alive"], ["Z", "Lays eggs with no shells in water"]] },
    { q: "A monitor lizard is often seen swimming in the canals and ponds of Singapore. How does it breathe?", o: ["Through gills, taking air from the water", "Through lungs, coming up to breathe air", "Through moist skin, like an adult frog", "Through gills when young, lungs when adult"], a: 1, why: "The monitor lizard is a reptile, and all reptiles breathe through lungs, so it comes up to breathe air. Misconception: animals that swim in water do not all breathe through gills.", lvl: 2 },
    { q: "Lina lifted some flowerpots and counted the small animals under them. She grouped them by their number of legs, as shown in the bar graph. At most, how many of these animals could be adult insects?", o: ["9", "13", "15", "26"], a: 0, why: "Only animals with 6 legs can be adult insects, so at most 9. Adding the 4 animals with 8 legs (like spiders) gives 13, which is wrong because insects never have 8 legs.", lvl: 2, fig: { type: "bar", title: "Animals under the flowerpots", xl: "Number of legs", yl: "Number of animals", bars: [["0", 7], ["6", 9], ["8", 4], ["14", 6]] } },
    { q: "The colugo lives in the forests of Bukit Timah. It glides from tree to tree and feeds its young on milk. Which of these animals are mammals?\nA: Dugong (sea cow)\nB: Flying fox\nC: Colugo\nD: Whale shark", o: ["A and B only", "A and C only", "A, B and C only", "B, C and D only"], a: 2, why: "The dugong, the flying fox (a large bat) and the colugo all feed their young on milk, so they are mammals. The whale shark breathes through gills, so it is a fish, not a mammal.", lvl: 3 },
    { q: "The stingray has gills and fins. It gives birth to young alive. Which statements about the stingray are correct?\nA: It is a fish.\nB: It is a mammal because it gives birth to young alive.\nC: It breathes through gills all its life.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Gills and fins show the stingray is a fish, and a fish breathes through gills all its life. Misconception: giving birth to young alive does not make an animal a mammal; the guppy and stingray are fish that do this.", lvl: 3 },
    { q: "Study the classification key for animals at an aquarium. The stingray gives birth to young alive, but the clownfish lays eggs. Which statement is correct?", o: ["The stingray ends at Q.", "The clownfish ends at P.", "The penguin ends at S.", "The dugong ends at S."], a: 3, why: "The dugong does not breathe through gills and has no feathers, so it ends at S. The stingray ends at P, the clownfish at Q and the penguin at R.", lvl: 3, fig: { type: "flow", root: "Sea animals", node: { q: "Breathes through gills?", yes: { q: "Gives birth to young alive?", yes: "P", no: "Q" }, no: { q: "Has feathers?", yes: "R", no: "S" } } } },
    { q: "Which of these can be used to tell ALL reptiles apart from ALL amphibians?\nA: Reptiles have dry, scaly skin, but amphibians have moist skin without scales.\nB: Reptiles have four legs, but amphibians have no legs.\nC: Reptiles live on land, but amphibians live in water.", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 0, why: "Only A is true for every reptile and amphibian. Misconception: not all reptiles have legs (the snake has none), and frogs have four legs. C fails because turtles and crocodiles live in water and adult frogs also live on land.", lvl: 3 },
    { q: "Which statements are true for BOTH the flying fox and the hornbill?\nA: Both can fly.\nB: Both lay eggs.\nC: Both breathe through lungs.\nD: Both have feathers.", o: ["A and B only", "B, C and D only", "A and C only", "A, B and C only"], a: 2, why: "Both can fly and both breathe through lungs. The flying fox is a bat, a mammal that has fur and gives birth to young alive, so B and D are true only for the hornbill.", lvl: 3 },
    { q: "Which pair of animals belong to the SAME animal group?", o: ["Flying fox and hornbill", "Flying lizard and colugo", "Dragonfly and flying fox", "Flying fish and stingray"], a: 3, why: "The flying fish and the stingray both have gills and fins, so both are fish. Misconception: animals that fly or glide do not belong to the same group. The flying fox and colugo are mammals, the hornbill is a bird, the flying lizard is a reptile and the dragonfly is an insect.", lvl: 3 },
    { q: "Study the Venn diagram. P, Q and R are three different animals. Which set of animals fits the diagram?", o: ["P: goldfish, Q: pangolin, R: frog", "P: pangolin, Q: guppy, R: toad", "P: snake, Q: whale, R: frog", "P: frog, Q: guppy, R: dolphin"], a: 0, why: "The goldfish has scales and lays eggs (P), the pangolin has scales and gives birth to young alive (Q), and the frog has neither (R). The pangolin cannot be P, the whale has no scales, and the frog has no scales so it cannot be P.", lvl: 3, fig: { type: "venn", a: "Has scales", b: "Gives birth to young alive", onlyA: ["crocodile", "P"], both: ["Q"], onlyB: ["otter"], neither: ["R"] } },
    { q: "Study the key. The stingray gives birth to young alive. Which question could be Question X?", o: ["Can it swim?", "Does it lay eggs?", "Does it have legs?", "Does it breathe through lungs?"], a: 1, why: "The penguin and platypus lay eggs, but the stingray and otter do not, so ‘Does it lay eggs?’ works. All four can swim, and the otter has legs and breathes through lungs, so it would go down the wrong arrow for the other questions.", lvl: 4, fig: { type: "flow", root: "Animals", node: { q: "Question X", yes: { q: "Has feathers?", yes: "Penguin", no: "Platypus" }, no: { q: "Has gills?", yes: "Stingray", no: "Otter" } } } },
    { q: "Study the Venn diagram. The stingray gives birth to young alive. How many animals have been placed WRONGLY?", o: ["1", "2", "3", "4"], a: 2, why: "Three are wrong. The stingray should be in the overlap, the dolphin breathes through lungs so it belongs in ‘Gives birth to young alive’ only, and the platypus lays eggs so it belongs outside both circles. The other five are placed correctly.", lvl: 4, fig: { type: "venn", a: "Breathes through gills", b: "Gives birth to young alive", onlyA: ["goldfish", "stingray"], both: ["guppy", "dolphin"], onlyB: ["otter", "platypus"], neither: ["hornbill", "adult frog"] } },
    { q: "Study the key. Which statements are correct?\nA: The platypus ends at A.\nB: The otter and the dolphin both end at B.\nC: The penguin ends at C.\nD: The adult toad ends at D.", o: ["A and B only", "A, B and C only", "B, C and D only", "A, B, C and D"], a: 1, why: "The platypus feeds its young on milk and lays eggs (A). The otter and dolphin feed their young on milk and do not lay eggs (B). The penguin has feathers (C). The adult toad breathes through lungs and moist skin, not gills, so it ends at E, not D.", lvl: 4, fig: { type: "flow", root: "Animals", node: { q: "Feeds young on milk?", yes: { q: "Lays eggs?", yes: "A", no: "B" }, no: { q: "Has feathers?", yes: "C", no: { q: "Has gills as an adult?", yes: "D", no: "E" } } } } },
    { q: "A jar holds only insects and spiders. There are 10 animals with 72 legs altogether. How many spiders are in the jar?", o: ["4", "5", "6", "8"], a: 2, why: "If all 10 were insects, there would be 10 × 6 = 60 legs. Each spider has 2 more legs than an insect, and there are 12 extra legs, so there are 6 spiders. Check: 6 × 8 + 4 × 6 = 48 + 24 = 72.", lvl: 4 }
  ],
  oe: [
    { q: "Ahmad placed 20 ants in the middle of a tray. One half of the tray had dry soil and the other half had damp soil. The tray was kept in the shade. After 15 minutes, he counted the ants on each side. His results are shown in the table. (a) What was the variable that Ahmad changed? (b) What can he conclude from his results? (c) Why did he use 20 ants instead of only 1 ant? (d) State one characteristic that shows the ant is an insect.", marks: 4, kw: [["damp", "moist", "wet", "amount of water", "water in the soil"], ["prefer damp", "prefer moist", "prefer wet", "prefer the damp", "like damp", "to the damp", "towards the damp", "damp soil", "moist soil"], ["reliable", "accurate", "chance"], ["6 legs", "six legs", "3 pairs", "three pairs", "3 body parts", "three body parts", "feeler", "antenna"]], model: "(a) Whether the soil was damp or dry. (b) Ants prefer damp soil, as more ants moved to the damp soil. (c) Using more ants makes the results more reliable, since one ant might move to a side by chance. (d) The ant has 6 legs and 3 body parts.", tbl: [["Side of the tray", "Number of ants after 15 minutes"], ["Dry soil", "4"], ["Damp soil", "16"]] },
    { q: "Rui counted small animals in two areas of the school garden. He spent 10 minutes in each area. His results are shown in the table. (a) How many insects did he find in Area P? (b) Rui wrote that he found 26 insects in Area P. Name the animal he wrongly counted as an insect, and give a reason why it is not an insect. (c) Why did Rui spend the same amount of time counting in each area?", marks: 4, x: 1, kw: [["24", "twenty-four", "twenty four"], ["spider"], ["8 legs", "eight legs", "4 pairs", "four pairs", "2 body parts", "two body parts"], ["fair", "compare"]], model: "(a) 24 insects. (b) The spider. It has 8 legs and 2 body parts, but insects have 6 legs and 3 body parts. (c) To make it a fair test, so that the numbers in the two areas can be compared.", tbl: [["Animal", "Area P (sunny, with flowers)", "Area Q (shady, with dead leaves)"], ["Butterfly", "8", "1"], ["Bee", "6", "0"], ["Spider", "2", "5"], ["Ant", "10", "12"], ["Snail", "0", "4"]] },
    { q: "Nora watched four animals in a large tank at an aquarium for 30 minutes. She counted the number of times each animal came up to the surface to breathe air. Her results are shown in the bar graph. (a) Which animal breathes through gills? (b) Explain why the dolphin had to come up to the surface. (c) Suggest one way Nora could make her results more reliable. (d) Nora’s friend says the sea turtle is a fish because it lives in water. Which group does the sea turtle belong to?", marks: 4, kw: [["stingray"], ["lung"], ["repeat", "more times", "again", "another day", "more days", "other days"], ["reptile"]], model: "(a) The stingray. (b) The dolphin breathes through lungs, so it must come up to the surface to breathe in air. (c) She could repeat the observation on a few more days and compare the results. (d) The sea turtle is a reptile.", fig: { type: "bar", title: "Times each animal came up in 30 minutes", xl: "Animal", yl: "Number of times", bars: [["Dolphin", 12], ["Dugong", 6], ["Sea turtle", 4], ["Stingray", 0]] } },
    { q: "Ben wanted to find out which nesting material sparrows prefer. He hung 20 pieces of each material near a tree in his HDB estate and counted the pieces taken by sparrows over 3 days. His results are shown in the table. (a) What was the variable that Ben changed? (b) Which material did the sparrows prefer? (c) State one thing Ben kept the same to make it a fair test. (d) The sparrows carried the materials in their beaks. State one other characteristic that shows the sparrow is a bird.", marks: 4, kw: [["type of material", "kind of material", "material used", "different material"], ["grass"], ["same number", "20 pieces", "same amount", "same place", "same tree", "same number of days", "3 days"], ["feather", "hard shell", "hard-shelled"]], model: "(a) The type of material. (b) Dry grass. (c) He hung the same number of pieces, 20, of each material. (d) The sparrow has feathers, and it lays eggs with hard shells.", tbl: [["Material", "Number of pieces taken by sparrows"], ["Twigs", "14"], ["Dry grass", "18"], ["Plastic strips", "3"], ["Paper strips", "5"]] },
    { q: "Study the classification key. (a) The flying fox and the dugong both end at X. Which animal group do all the animals at X belong to? (b) The flying lizard glides from tree to tree like a bird. At which letter does it end? Give a reason. (c) Tom placed the whale shark at X because of its name. Explain where it should really be placed.", marks: 4, x: 1, kw: [["mammal"], ["z"], ["lung", "no gills", "not breathe through gill", "not have gill", "doesn't breathe through gill", "doesn't have gill"], ["gill"]], model: "(a) Mammals. (b) Z. The flying lizard is a reptile and it breathes through lungs. (c) The whale shark is a fish, so it should be placed at Y because it breathes through gills.", fig: { type: "flow", root: "Animals", node: { q: "Has feathers?", yes: "W", no: { q: "Feeds young on milk?", yes: "X", no: { q: "Breathes through gills?", yes: "Y", no: "Z" } } } } },
    { q: "The dugong and the whale shark can both be found in the seas around Singapore. (a) State one similarity between them. (b) State one difference in how they breathe. (c) State one difference in how they feed their young.", marks: 4, kw: [["swim", "live in", "sea", "water"], ["gill"], ["lung"], ["milk"]], model: "(a) Both of them live in the sea and can swim. (b) The whale shark breathes through gills, but the dugong breathes through lungs. (c) The dugong feeds its young on milk, but the whale shark does not feed its young on milk." }
  ],
  tf: [
    { s: "The whale shark is a mammal.", a: false, why: "It breathes through gills and has fins, so it is a fish; its name does not decide its group." },
    { s: "A silverfish is an insect.", a: true, why: "It has 6 legs, 3 body parts and 1 pair of feelers, even though it has no wings." },
    { s: "A flying fox is a bird because it has wings and can fly.", a: false, why: "A flying fox is a bat: it has fur and feeds its young on milk, so it is a mammal." },
    { s: "The dugong is a mammal even though it lives in the sea all its life.", a: true, why: "It breathes through lungs and feeds its young on milk." },
    { s: "Every animal that gives birth to young alive is a mammal.", a: false, why: "The guppy and the stingray give birth to young alive, but they are fish." },
    { s: "The flying lizard is a reptile even though it can glide.", a: true, why: "It has dry, scaly skin and breathes through lungs; how it moves does not decide its group." },
    { s: "A tick is an insect because it is small and crawls.", a: false, why: "A tick has 8 legs, so it is not an insect; size and movement do not decide the group." },
    { s: "The otter and the dolphin belong to the same animal group.", a: true, why: "Both are mammals: they breathe through lungs and feed their young on milk." },
    { s: "A toad is a reptile because its skin is rough and bumpy.", a: false, why: "A toad is an amphibian: it has moist skin without scales and lays its eggs in water." },
    { s: "Birds and most reptiles both lay eggs with shells.", a: true, why: "Birds lay eggs with hard shells; most reptiles lay eggs with leathery shells." }
  ],
  doc: [
    { q: "State one difference between the body of a spider and the body of an ant.", marks: 1, answers: ["The spider has 8 legs.", "The spider has 8 legs, but the ant has 6 legs.", "The spider is bigger and hairier than the ant."], best: 1, why: "Answer 2 describes the same characteristic (number of legs) for BOTH animals. Answer 1 only describes the spider, so it is not a complete difference. Answer 3 uses size and hairiness, which vary between spiders and ants and are not used to classify them." },
    { q: "The dugong lives in the sea all its life. Explain why it is a mammal and not a fish.", marks: 2, answers: ["It is very big and swims slowly, so it is not a fish.", "It lives in the sea, but it is a mammal.", "It breathes through lungs and feeds its young on milk, but fish breathe through gills."], best: 2, why: "Answer 3 gives mammal characteristics (lungs, milk) and compares with fish (gills). Answer 1 uses size and movement, which do not decide the group. Answer 2 only repeats the question and gives no characteristic." }
  ]
};
