window.BANKV = window.BANKV || {};
BANKV["animals"] = {
  flash: [
    { f: "Characteristics of mammals", b: "Have hair or fur; most give birth to young alive; ALL feed their young on milk; breathe through lungs." },
    { f: "Characteristics of birds", b: "Have feathers, a beak, two legs and a pair of wings; lay eggs with hard shells; breathe through lungs." },
    { f: "Characteristics of fish", b: "Live in water; have fins to swim and gills to breathe; most have scales; most lay eggs." },
    { f: "Characteristics of amphibians", b: "Moist, smooth skin without scales; lay eggs in water; young (tadpoles) breathe through gills; adults breathe through lungs and moist skin." },
    { f: "Characteristics of reptiles", b: "Dry, scaly skin; most lay eggs with tough, leathery shells on land; breathe through lungs." },
    { f: "Characteristics of insects", b: "3 body parts (head, thorax and abdomen), 3 pairs of legs (6 legs) and 1 pair of feelers; most have wings." },
    { f: "Which characteristics are found in only ONE animal group?", b: "Feathers are found only in birds. Hair or fur and feeding young on milk are found only in mammals." },
    { f: "Why is a whale a mammal and not a fish?", b: "It breathes through lungs, not gills, and it gives birth to young alive and feeds its young on milk." },
    { f: "Why is the platypus a mammal even though it lays eggs?", b: "It has fur and it feeds its young on milk." },
    { f: "Why is a spider not an insect?", b: "A spider has 8 legs, 2 body parts and no feelers, but an insect has 6 legs, 3 body parts and 1 pair of feelers." },
    { f: "Why must a dolphin come up to the surface of the water?", b: "It breathes through lungs, not gills, so it must come to the surface to breathe in air." },
    { f: "Why do frogs need to live near water?", b: "They lay their eggs in water, their young (tadpoles) live in water, and they must keep their skin moist to breathe through it." },
    { f: "Why is ‘Can it fly?’ a poor question for a classification key?", b: "Animals from different groups can move in the same way, e.g. birds, bats (mammals) and insects can all fly." },
    { f: "Why is the guppy a fish even though it gives birth to young alive?", b: "It has gills to breathe and fins to swim, which are characteristics of fish." },
    { f: "How do you state a difference between two animals?", b: "Describe the SAME characteristic for BOTH animals, joined by ‘but’, e.g. ‘The cat has fur, but the eagle has feathers.’" }
  ],
  mcq: [
    { q: "At a hawker centre, Wei Ming’s family ordered frog porridge. Which animal group does the frog belong to?", o: ["Reptiles", "Fish", "Amphibians", "Mammals"], a: 2, why: "The frog has moist, smooth skin and lays its eggs in water, so it is an amphibian. It is not a reptile, because reptiles have dry, scaly skin.", lvl: 1 },
    { q: "Which of these small animals is an insect?", o: ["Scorpion", "Praying mantis", "Earthworm", "Millipede"], a: 1, why: "The praying mantis has 3 body parts, 6 legs and 1 pair of feelers. The scorpion has 8 legs, the earthworm has no legs and the millipede has many legs.", lvl: 1 },
    { q: "Which of these animals breathes through lungs?", o: ["Tilapia", "Tadpole", "Arowana", "Tortoise"], a: 3, why: "The tortoise is a reptile, and all reptiles breathe through lungs. The tilapia and arowana are fish and the tadpole is a young amphibian, so they breathe through gills.", lvl: 1 },
    { q: "The kangaroo carries its baby in a pouch. Which characteristic shows that the kangaroo is a mammal?", o: ["It feeds its young on milk.", "It has a long, strong tail.", "It hops on its back legs.", "It lives in dry grassland."], a: 0, why: "Feeding young on milk is a characteristic found only in mammals. A tail, hopping and where it lives are not used to classify animals.", lvl: 1 },
    { q: "Study the Venn diagram. The arowana is a fish with large scales. Where should the arowana be placed?", o: ["Only in the ‘Has scales’ circle", "In the overlap of both circles", "Only in the ‘Breathes through gills’ circle", "Outside both circles"], a: 1, why: "The arowana has scales AND breathes through gills, so it goes in the overlap, like the tilapia. The python has scales but breathes through lungs, so it is in ‘Has scales’ only.", lvl: 2, fig: { type: "venn", a: "Has scales", b: "Breathes through gills", onlyA: ["python"], both: ["tilapia"], onlyB: ["tadpole"], neither: ["owl"] } },
    { q: "Study the classification key used at the Singapore Zoo. Which animal ends at D?", o: ["Komodo dragon", "Emu", "Tree frog", "Mousedeer"], a: 2, why: "The tree frog has no fur and no feathers but has moist skin, so it ends at D. The Komodo dragon (dry, scaly skin) ends at E, the emu (feathers) at C and the mousedeer (fur, young born alive) at B.", lvl: 2, fig: { type: "flow", root: "Animals", node: { q: "Has fur or hair?", yes: { q: "Lays eggs?", yes: "A", no: "B" }, no: { q: "Has feathers?", yes: "C", no: { q: "Has moist skin?", yes: "D", no: "E" } } } } },
    { q: "Siti recorded the animals she saw on a walk at MacRitchie Reservoir in the bar graph. How many of the animals she saw were reptiles?", o: ["4", "5", "9", "18"], a: 2, why: "Monitor lizards and terrapins both have dry, scaly skin and breathe through lungs, so they are reptiles: 4 + 5 = 9. Macaques are mammals and kingfishers are birds. 18 is the total of all the animals.", lvl: 2, fig: { type: "bar", title: "Animals seen at MacRitchie Reservoir", xl: "Animal", yl: "Number of animals", bars: [["Macaques", 6], ["Monitor lizards", 4], ["Kingfishers", 3], ["Terrapins", 5]] } },
    { q: "A house gecko is often seen on the walls of HDB flats. Which statement about the house gecko is NOT true?", o: ["It has dry, scaly skin.", "It breathes through lungs.", "It lays eggs on land.", "Its young breathe through gills."], a: 3, why: "The gecko is a reptile, and reptiles breathe through lungs all their lives, even when young. Young that breathe through gills are found in fish and amphibians.", lvl: 2 },
    { q: "Mrs Tan bought these animals at a wet market. Which of them are NOT fish?\nA: Crab\nB: Prawn\nC: Ikan bilis\nD: Pomfret", o: ["A and B only", "C and D only", "A, B and C only", "B and D only"], a: 0, why: "The crab and prawn have many legs and no fins or scales, so they are not fish. Ikan bilis and pomfret are fish: they have fins, scales and gills. Being sold at the fish section does not make an animal a fish.", lvl: 2 },
    { q: "Mr Lim watched a large aquarium tank with a manatee, a grouper and a sea turtle for one hour. Predict which animal(s) he will NOT see coming up to the surface to breathe air.", o: ["Manatee only", "Grouper only", "Sea turtle and grouper only", "Manatee and sea turtle only"], a: 1, why: "The grouper is a fish, so it breathes underwater through its gills. The manatee (a mammal) and the sea turtle (a reptile) breathe through lungs, so they must come up for air.", lvl: 2 },
    { q: "Mei wants to find out whether ants prefer sugar or salt. She prepared the four plates shown and left them in the school garden. Which two set-ups should she compare?", o: ["A and B", "A and D", "B and C", "C and D"], a: 0, why: "A and B differ only in the type of food (sugar or salt); the amount and the place are the same. A and D differ in amount and place, B and C have the same food, and C and D differ in food and amount.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["5 g of sugar", "In the shade"] }, { label: "B", icon: "plate", lines: ["5 g of salt", "In the shade"] }, { label: "C", icon: "plate", lines: ["5 g of salt", "In the sun"] }, { label: "D", icon: "plate", lines: ["10 g of sugar", "In the sun"] }] } },
    { q: "The emu is a large bird that cannot fly. Which statements about the emu are true?\nA: It has feathers.\nB: It has wings.\nC: It can fly.\nD: It lays eggs with hard shells.", o: ["A and D only", "B, C and D only", "A, B and D only", "A, B, C and D"], a: 2, why: "The emu has feathers, a pair of small wings, and lays eggs with hard shells, so it is a bird. C is false: having wings does not mean an animal can fly.", lvl: 3 },
    { q: "Study the classification key. Which question could be Question X?", o: ["Can it fly?", "Does it lay eggs?", "Does it have wings?", "Does it have 6 legs?"], a: 3, why: "The cicada has 6 legs but the pigeon has 2, so ‘Does it have 6 legs?’ separates them and ‘Yes’ leads to the cicada. Both can fly, both lay eggs and both have wings, so the other questions would not separate them.", lvl: 3, fig: { type: "flow", root: "Animals", node: { q: "Has wings?", yes: { q: "Question X", yes: "Cicada", no: "Pigeon" }, no: { q: "Has 8 legs?", yes: "Scorpion", no: "Earthworm" } } } },
    { q: "Ms Tan’s class listed some animals they saw at Gardens by the Bay and the group each pupil wrote down. Which TWO animals were grouped wrongly?", o: ["Spider and fruit bat", "Koi and otter", "Changeable lizard and spider", "Dragonfly and fruit bat"], a: 0, why: "The spider has 8 legs and 2 body parts, so it is not an insect. The fruit bat has fur and feeds its young on milk, so it is a mammal, not a bird. The koi, lizard, otter and dragonfly are grouped correctly.", lvl: 3, tbl: [["Animal", "Group written"], ["Koi", "Fish"], ["Changeable lizard", "Reptile"], ["Spider", "Insect"], ["Otter", "Mammal"], ["Dragonfly", "Insect"], ["Fruit bat", "Bird"]] },
    { q: "Which pair of animals belong to DIFFERENT animal groups?", o: ["Kingfisher and emu", "Python and terrapin", "Mousedeer and dolphin", "Newt and lizard"], a: 3, why: "The newt is an amphibian (moist, smooth skin) but the lizard is a reptile (dry, scaly skin). The kingfisher and emu are birds, the python and terrapin are reptiles, and the mousedeer and dolphin are mammals.", lvl: 3 },
    { q: "The table shows information about four adult animals, A, B, C and D. Which two animals MUST belong to the same group?", o: ["A and B", "A and D", "B and C", "B and D"], a: 1, why: "A and D both breathe through gills as adults, so both are fish (D gives birth to young alive, like the guppy). B breathes through lungs and C has moist skin and lays eggs in water, so neither can be a fish.", lvl: 3, tbl: [["Animal", "Body covering", "Breathes through", "How it reproduces"], ["A", "Scales", "Gills", "Lays eggs"], ["B", "Scales", "Lungs", "Gives birth to young alive"], ["C", "Moist skin", "Lungs and skin", "Lays eggs in water"], ["D", "Scales", "Gills", "Gives birth to young alive"]] },
    { q: "In the school canteen, the stalls sell chicken rice, fish soup, frog porridge, sambal stingray and mutton soup. Mutton comes from goats or sheep. How many DIFFERENT animal groups do these animals come from?", o: ["2", "3", "4", "5"], a: 2, why: "Chicken is a bird, the fish and the stingray are both fish, the frog is an amphibian, and goats and sheep are mammals. That makes 4 groups, not 5, because two of the animals are fish.", lvl: 3 },
    { q: "Study the classification key. A catfish has no scales. Which statements are correct?\nA: The adult newt ends at R.\nB: The catfish ends at T.\nC: The emu and the fruit bat both end at Q.\nD: The terrapin ends at S.", o: ["A and B only", "A and C only", "B and D only", "A, B and C only"], a: 0, why: "The adult newt has lungs, moist skin and no feathers (R). The catfish has gills and no scales (T). C is wrong because the fruit bat has no feathers, so it ends at R. D is wrong because the terrapin breathes through lungs and has dry, scaly skin, so it ends at P.", lvl: 4, fig: { type: "flow", root: "Animals", node: { q: "Has lungs as an adult?", yes: { q: "Has dry, scaly skin?", yes: "P", no: { q: "Has feathers?", yes: "Q", no: "R" } }, no: { q: "Has scales?", yes: "S", no: "T" } } } },
    { q: "Animal X has these characteristics: its young breathe through gills, it has no scales, and it lays its eggs in water. A catfish is a fish with no scales. Which of these could be animal X?\nA: Toad\nB: Newt\nC: Catfish", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "The toad and newt are amphibians that fit all three clues. The catfish fits too: its young breathe through gills, it has no scales and it lays eggs in water. The clues do not say how the ADULT breathes, so they cannot tell an amphibian from this fish.", lvl: 4 },
    { q: "Wen used her key for six animals: emu, kangaroo, echidna, python, newt and tilapia. Two of the animals ended at the same letter. Which question could she add at that letter to separate them?", o: ["Does it breathe through lungs?", "Does it have dry, scaly skin?", "Does it lay eggs?", "Does it have a tail?"], a: 1, why: "The python and the newt both end at E. Only dry, scaly skin separates them: the python has it but the newt has moist skin. Both breathe through lungs, both lay eggs and both have a tail.", lvl: 4, fig: { type: "flow", root: "Animals", node: { q: "Has feathers?", yes: "A", no: { q: "Feeds young on milk?", yes: { q: "Lays eggs?", yes: "B", no: "C" }, no: { q: "Has gills as an adult?", yes: "D", no: "E" } } } } }
  ],
  oe: [
    { q: "Mr Goh’s class saw four animals, W, X, Y and Z, at Bishan-Ang Mo Kio Park and recorded their characteristics in the table. (a) Which animal is an amphibian? (b) Which animal could be the smooth-coated otter? Give one reason from the table. (c) Ali says Y is an amphibian because it lays eggs. Explain why he is wrong.", marks: 4, kw: [["z"], ["w"], ["fur", "young alive", "give birth", "gives birth"], ["dry", "scaly", "scales", "leathery"]], model: "(a) Z. (b) W, because it has fur. It also gives birth to young alive. (c) Laying eggs is found in many animal groups. Y has dry, scaly skin and lays eggs with leathery shells, so it is a reptile, not an amphibian.", tbl: [["Animal", "Body covering", "How it breathes", "How it reproduces"], ["W", "Fur", "Lungs", "Gives birth to young alive"], ["X", "Feathers", "Lungs", "Lays eggs with hard shells"], ["Y", "Dry scales", "Lungs", "Lays eggs with leathery shells"], ["Z", "Moist skin", "Lungs and skin", "Lays eggs in water"]] },
    { q: "Wei searched the leaf litter in his school garden and recorded the small animals he found in the bar graph. (a) How many insects did he find altogether? (b) Wei says, ‘The millipede is an insect because it has legs and a pair of feelers.’ Explain why he is wrong. (c) Wei later found 2 more animals, each with 6 legs, 3 body parts and no wings. Should he add them to his insect count? Explain.", marks: 4, kw: [["18", "eighteen"], ["many legs", "more than 6", "more than six", "lots of legs", "too many legs", "more legs"], ["yes", "should add", "add them"], ["6 legs", "six legs", "3 body parts", "three body parts", "3 pairs", "three pairs"]], model: "(a) 18 insects. (b) The millipede has many legs, more than 6 legs, so it is not an insect. Insects have exactly 6 legs. (c) Yes, he should add them. They have 6 legs and 3 body parts, so they are insects. Not all insects have wings.", fig: { type: "bar", title: "Animals in the leaf litter", xl: "Animal", yl: "Number of animals", bars: [["Ants", 14], ["Spiders", 5], ["Millipedes", 3], ["Earthworms", 6], ["Beetles", 4]] } },
    { q: "At Jurong Lake Gardens, Ravi saw a red junglefowl (a wild chicken) and a frog near a pond. (a) Which animal group does the frog belong to? (b) State one difference between the body covering of the frog and that of the junglefowl. (c) Both animals lay eggs. State one difference between their eggs.", marks: 4, kw: [["amphibian"], ["moist", "smooth"], ["feather"], ["hard", "on land", "jelly"]], model: "(a) The frog is an amphibian. (b) The frog has moist, smooth skin, but the junglefowl has feathers. (c) The junglefowl lays eggs with hard shells, but the frog lays eggs without shells, covered in jelly, in water." },
    { q: "Study the Venn diagram of some animals at a wildlife park in Singapore. (a) The manatee is placed in ‘Lives in water’ only. What does this tell you about how it reproduces? (b) Which animal group does the manatee belong to? (c) Ravi says the arowana and the terrapin must belong to the same animal group because they are in the same region. Using how each animal breathes, explain why he is wrong.", marks: 4, x: 1, kw: [["young alive", "give birth", "gives birth", "not lay", "doesn't lay", "does not lay"], ["mammal"], ["lung"], ["gill"]], model: "(a) The manatee does not lay eggs. It gives birth to young alive. (b) It is a mammal. (c) The terrapin breathes through lungs, so it is a reptile, but the arowana breathes through gills, so it is a fish. They belong to different groups.", fig: { type: "venn", a: "Lives in water", b: "Lays eggs", onlyA: ["manatee"], both: ["arowana", "terrapin"], onlyB: ["hornbill"], neither: ["mousedeer"] } }
  ],
  tf: [
    { s: "A kangaroo is a mammal even though it carries its young in a pouch.", a: true, why: "It has fur and feeds its young on milk; the pouch does not change its group." },
    { s: "Birds are the only animals that have wings.", a: false, why: "Insects such as butterflies and mammals such as bats also have wings. Only birds have FEATHERS." },
    { s: "A sea cucumber is a fish because it lives in the sea.", a: false, why: "A sea cucumber has no fins and no scales, so it is not a fish; living in the sea does not decide the group." },
    { s: "All animals with scales lay eggs.", a: false, why: "The pangolin (a mammal) and the guppy (a fish) have scales but give birth to young alive." },
    { s: "The python and the terrapin belong to the same animal group.", a: true, why: "Both are reptiles: they have dry, scaly skin and breathe through lungs." },
    { s: "Animals that live in water breathe through gills, and animals that live on land breathe through lungs.", a: false, why: "The manatee, dolphin and terrapin live in water but breathe through lungs." },
    { s: "Young toads breathe through gills.", a: true, why: "Toad tadpoles live in water and breathe through gills; adult toads breathe through lungs and moist skin." },
    { s: "A scorpion is an insect because it has a hard body and a tail.", a: false, why: "A scorpion has 8 legs and 2 body parts, so it is not an insect." },
    { s: "A butterfly and a fruit bat both have wings, but they belong to different animal groups.", a: true, why: "The butterfly is an insect (6 legs, 3 body parts); the fruit bat is a mammal (fur, feeds young on milk)." },
    { s: "Penguins and whales both breathe through lungs, even though they spend a lot of time in water.", a: true, why: "Birds and mammals breathe through lungs, so both must come to the surface for air." }
  ],
  sort: [
    { title: "Sort these animals into their correct groups", groups: ["Mammal", "Bird", "Reptile", "Amphibian"], items: [["mousedeer", 0], ["kangaroo", 0], ["manatee", 0], ["emu", 1], ["kingfisher", 1], ["owl", 1], ["python", 2], ["terrapin", 2], ["newt", 3], ["tree frog", 3]] }
  ]
};
