window.BANKX = window.BANKX || {};
BANKX["animals"] = {
  notes: [
    { h: "Using a classification key", t: "Start at the top and answer each yes/no question about ONE characteristic, then follow the arrow until you reach a letter. A good key question uses a characteristic that sorts animals into their proper groups, e.g. ‘Does it have feathers?’. A poor question is ‘Can it fly?’, because bats, insects and birds can all fly.", kw: ["start at the top", "yes or no", "one characteristic", "follow the arrow"] },
    { h: "Reading a Venn diagram", t: "Each circle shows one characteristic. The overlap holds animals that have BOTH characteristics, and the space outside the circles holds animals with NEITHER. Check each animal against each circle separately, e.g. a bat can fly AND is a mammal, so it goes in the overlap of ‘Can fly’ and ‘Is a mammal’.", kw: ["overlap", "both characteristics", "outside the circles", "neither"] },
    { h: "More tricky animals", t: "A snake has no legs but is a reptile (dry scaly skin, lungs). A worker ant has no wings but is an insect (6 legs, 3 body parts). A salamander looks like a lizard but is an amphibian (moist smooth skin). Starfish and jellyfish are not fish: they have no fins and no scales. A seahorse is a fish, and a sea lion is a mammal. The kiwi cannot fly but is a bird.", kw: ["snake is a reptile", "worker ant is an insect", "salamander is an amphibian", "starfish is not a fish"] }
  ],
  traps: [
    "A worker ant has no wings, so it is not an insect -> It has 6 legs and 3 body parts, so it is an insect. Not all insects have wings.",
    "A starfish or jellyfish is a fish because it lives in the sea -> They have no fins and no scales, so they are not fish.",
    "A salamander is a reptile because it looks like a lizard -> It has moist, smooth skin and lays eggs in water, so it is an amphibian."
  ],
  mcq: [
    { q: "Study the classification chart. Which letter represents the ostrich?", o: ["A", "B", "C", "It cannot be placed on the chart"], a: 0, why: "The ostrich has feathers, so it goes to A. It cannot fly, but the chart does not ask about flying.", lvl: 1, fig: { type: "flow", root: "Animals", node: { q: "Has feathers?", yes: "A", no: { q: "Has fur or hair?", yes: "B", no: "C" } } } },
    { q: "Which of these sea animals is NOT a fish?", o: ["Seahorse", "Starfish", "Eel", "Guppy"], a: 1, why: "The starfish has no fins and no scales, so it is not a fish. The seahorse, eel and guppy all have gills and fins.", lvl: 1 },
    { q: "Study the Venn diagram. Which animal has wings but does NOT have 6 legs?", o: ["Bee", "Worker ant", "Sparrow", "Spider"], a: 2, why: "The sparrow is only in the ‘Has wings’ circle. The bee is in the overlap, the worker ant has 6 legs but no wings, and the spider is outside both circles.", lvl: 1, fig: { type: "venn", a: "Has 6 legs", b: "Has wings", onlyA: ["worker ant"], both: ["bee", "butterfly"], onlyB: ["sparrow", "bat"], neither: ["spider"] } },
    { q: "A salamander has a long tail and four legs like a lizard. It has moist, smooth skin and lays its eggs in water. Which group does it belong to?", o: ["Reptiles", "Fish", "Insects", "Amphibians"], a: 3, why: "Moist, smooth skin and laying eggs in water are characteristics of amphibians. Lizards are reptiles with dry, scaly skin.", lvl: 1 },
    { q: "Study the classification chart. Which pair of animals would BOTH end at S?", o: ["Whale and adult frog", "Snake and gecko", "Shark and eel", "Turtle and bat"], a: 0, why: "The whale and the adult frog do not breathe through gills and do not have dry, scaly skin, so both reach S. The snake, gecko and turtle go to R; the shark and eel go to P.", lvl: 2, fig: { type: "flow", root: "Animals", node: { q: "Breathes through gills?", yes: { q: "Has fins?", yes: "P", no: "Q" }, no: { q: "Has dry, scaly skin?", yes: "R", no: "S" } } } },
    { q: "Study the Venn diagram. Which animal could be X?", o: ["Bat", "Penguin", "Platypus", "Whale"], a: 2, why: "X lays eggs AND has fur. The platypus lays eggs and has fur. The bat and whale have fur but give birth to young alive; the penguin lays eggs but has feathers.", lvl: 2, fig: { type: "venn", a: "Lays eggs", b: "Has fur or hair", onlyA: ["crocodile", "sparrow"], both: ["X"], onlyB: ["cat", "monkey"], neither: ["guppy"] } },
    { q: "A mosquito has only ONE pair of wings, while a bee has two pairs. Which statement about the mosquito is correct?", o: ["It is not an insect because it has fewer wings.", "It is a bird because it can fly.", "It is an insect because it has 3 body parts and 6 legs.", "It is an insect because it can fly."], a: 2, why: "3 body parts and 6 legs make it an insect. The number of wings, or being able to fly, does not decide whether an animal is an insect.", lvl: 2 },
    { q: "Which of these animals breathe through lungs throughout their WHOLE life?\nA: Frog\nB: Crocodile\nC: Whale\nD: Goldfish", o: ["A and B only", "C and D only", "A, B and C only", "B and C only"], a: 3, why: "Crocodiles and whales breathe through lungs from birth. A young frog (tadpole) breathes through gills, and a goldfish always breathes through gills.", lvl: 2 },
    { q: "Study the classification chart. Which animal is matched with the correct letter?", o: ["Housefly - K", "Worker ant - K", "Spider - M", "Millipede - L"], a: 1, why: "The worker ant has 6 legs but no wings, so it reaches K. The housefly goes to J, the spider (8 legs) to L, and the millipede (many legs) to M.", lvl: 2, fig: { type: "flow", root: "Small animals", node: { q: "Has 6 legs?", yes: { q: "Has wings?", yes: "J", no: "K" }, no: { q: "Has 8 legs?", yes: "L", no: "M" } } } },
    { q: "The bar graph shows the number of legs of four animals, W, X, Y and Z. Based ONLY on the graph, which animals are definitely NOT insects?", o: ["W, Y and Z only", "W and Y only", "X only", "Y and Z only"], a: 0, why: "All insects have 6 legs, so W (8), Y (10) and Z (0) cannot be insects. X has 6 legs, but we would still need to check its body parts to be sure.", lvl: 2, fig: { type: "bar", title: "Number of legs", xl: "Animal", yl: "Number of legs", bars: [["W", 8], ["X", 6], ["Y", 10], ["Z", 0]] } },
    { q: "At the Singapore Zoo, sea lions swim with flippers and catch fish. Which characteristic shows that the sea lion is a mammal?", o: ["It swims very well.", "It lives near the sea.", "It eats fish.", "It feeds its young on milk."], a: 3, why: "Feeding young on milk is a characteristic of mammals. Swimming, living near the sea and eating fish are shared by animals from other groups.", lvl: 2 },
    { q: "Study the Venn diagram. Where should the whale be placed?", o: ["Only in the ‘Lives in water’ circle", "In the overlap of both circles", "Only in the ‘Breathes through gills’ circle", "Outside both circles"], a: 0, why: "The whale lives in water but breathes through lungs, not gills, like the dolphin and turtle.", lvl: 2, fig: { type: "venn", a: "Lives in water", b: "Breathes through gills", onlyA: ["dolphin", "turtle"], both: ["shark", "guppy"], onlyB: [], neither: ["eagle", "gecko"] } },
    { q: "Study the classification chart. Which statement is correct?", o: ["The platypus ends at D.", "The guppy ends at B.", "The pangolin ends at B.", "The penguin ends at D."], a: 2, why: "The pangolin has no feathers but feeds its young on milk, so it reaches B. The platypus also reaches B, the guppy reaches C and the penguin reaches A.", lvl: 3, fig: { type: "flow", root: "Animals", node: { q: "Has feathers?", yes: "A", no: { q: "Feeds young on milk?", yes: "B", no: { q: "Has gills as an adult?", yes: "C", no: "D" } } } } },
    { q: "Study the classification chart. Which question could be Question X?", o: ["Can it fly?", "Does it breathe through lungs?", "Does it have wings?", "Does it have feathers?"], a: 3, why: "The eagle has feathers and the bat has fur, so ‘Does it have feathers?’ separates them. Both can fly, both have wings and both breathe through lungs.", lvl: 3, fig: { type: "flow", root: "Animals", node: { q: "Can it fly?", yes: { q: "Question X", yes: "Eagle", no: "Bat" }, no: { q: "Has gills?", yes: "Shark", no: "Dolphin" } } } },
    { q: "Study the Venn diagram. P, Q, R and S are four different animals. Which statement is correct?", o: ["P could be a pangolin.", "Q could be a snake.", "R could be a goldfish.", "S could be an adult frog."], a: 1, why: "A snake has scales and breathes through lungs, so it fits Q. A pangolin also has lungs (Q, not P), a goldfish has gills (P, not R) and an adult frog has lungs (R, not S).", lvl: 3, fig: { type: "venn", a: "Has scales", b: "Breathes through lungs", onlyA: ["P"], both: ["Q"], onlyB: ["R"], neither: ["S"] } },
    { q: "Which one of these statements about animal groups is NOT true?", o: ["All insects have 3 body parts.", "All amphibians have moist skin.", "All reptiles have legs.", "All birds have beaks."], a: 2, why: "The snake is a reptile but has no legs. The other three statements are true.", lvl: 3 },
    { q: "Study the Venn diagram. Which animal has been placed WRONGLY?", o: ["Cat", "Guppy", "Goldfish", "Platypus"], a: 3, why: "The platypus lays eggs, so it should not be in the ‘Gives birth to young alive’ circle. The guppy gives birth to young alive and has gills, so it is correctly in the overlap.", lvl: 3, fig: { type: "venn", a: "Gives birth to young alive", b: "Breathes through gills", onlyA: ["cat", "platypus"], both: ["guppy"], onlyB: ["goldfish"], neither: ["eagle"] } },
    { q: "Animal Q has scales, lays eggs and breathes through lungs. Which of these could be animal Q?\nA: Snake\nB: Crocodile\nC: Pangolin", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "The snake and crocodile are reptiles that have scales, lay eggs and breathe through lungs. The pangolin has scales and lungs but gives birth to young alive.", lvl: 3 },
    { q: "Which of these could be used to separate ALL birds from ALL mammals?\nA: Birds have feathers; mammals have hair or fur.\nB: Birds lay eggs; mammals give birth to young alive.\nC: Birds can fly; mammals cannot fly.", o: ["A only", "A and B only", "A, B and C", "B and C only"], a: 0, why: "Only A works for every animal. B fails for the platypus, which lays eggs, and C fails for the bat, which flies, and the penguin, which cannot fly.", lvl: 3 },
    { q: "Mary made the classification chart shown. How many of these animals would she place in the WRONG group?\nbat, whale, sparrow, dog", o: ["1", "2", "3", "4"], a: 1, why: "The bat would go to ‘Bird’ and the whale to ‘Fish’, but both are mammals. The sparrow (bird) and dog (mammal) are placed correctly. Her chart uses movement and habitat, which are poor ways to classify.", lvl: 3, fig: { type: "flow", root: "Animals", node: { q: "Can it fly?", yes: "Bird", no: { q: "Lives in water?", yes: "Fish", no: "Mammal" } } } }
  ],
  tf: [
    { s: "A snake is a reptile even though it has no legs.", a: true, why: "It has dry, scaly skin and breathes through lungs." },
    { s: "Worker ants have no wings, so they are not insects.", a: false, why: "They have 6 legs and 3 body parts; not all insects have wings." },
    { s: "A starfish is a fish because it lives in the sea.", a: false, why: "A starfish has no fins and no scales, so it is not a fish." },
    { s: "A salamander is a reptile because it looks like a lizard.", a: false, why: "It has moist, smooth skin and lays eggs in water, so it is an amphibian." },
    { s: "A sea lion is a mammal.", a: true, why: "It has fur and feeds its young on milk." },
    { s: "All insects have wings.", a: false, why: "Worker ants and silverfish are insects without wings." },
    { s: "Scales can be found on fish, reptiles and even a mammal.", a: true, why: "The pangolin is a mammal with scales, so scales alone cannot decide the group." },
    { s: "The kiwi cannot fly, so it is not a bird.", a: false, why: "The kiwi has feathers and a beak, so it is a bird." }
  ],
  oe: [
    { q: "Study the classification chart. (a) Which group do all the animals at A belong to? (b) A penguin cannot fly. Where should it be placed on the chart? Explain why. (c) A spider ends at D. Explain why it does not end at C.", marks: 3, kw: [["mammal"], ["feather"], ["8 legs", "eight legs", "4 pairs", "four pairs"]], model: "(a) They are all mammals. (b) The penguin should be placed at B because it has feathers. (c) A spider has 8 legs, not 6 legs, so it goes to D and not to C.", fig: { type: "flow", root: "Animals", node: { q: "Has fur or hair?", yes: "A", no: { q: "Has feathers?", yes: "B", no: { q: "Has 6 legs?", yes: "C", no: "D" } } } } },
    { q: "Study the Venn diagram. (a) Explain why the bat is placed in the overlap of both circles. (b) Explain why the penguin is placed outside both circles.", marks: 4, kw: [["can fly", "able to fly", "flies"], ["fur", "hair", "milk"], ["cannot fly", "can’t fly", "can't fly", "does not fly", "not able to fly", "unable to fly"], ["bird", "feather"]], model: "(a) The bat can fly, and it is a mammal because it has fur and feeds its young on milk. (b) The penguin cannot fly, and it is a bird with feathers, not a mammal.", fig: { type: "venn", a: "Can fly", b: "Is a mammal", onlyA: ["eagle", "butterfly"], both: ["bat"], onlyB: ["whale", "cat"], neither: ["penguin"] } },
    { q: "Siti made the chart shown to classify animals into birds, fish and mammals. (a) She placed the bat in ‘Group 1’ with the sparrow. Explain why ‘Can it fly?’ is not a good question to use. (b) Suggest a better question to replace ‘Can it fly?’ so that only birds go to Group 1. (c) Which group would the whale be placed in using her chart, and which animal group does the whale really belong to?", marks: 4, kw: [["different group", "same way", "bat is a mammal", "not all"], ["feather"], ["group 2"], ["whale is a mammal", "really a mammal", "actually a mammal", "whale is really", "but a mammal", "mammal because", "whale belongs to the mammal", "whale belongs to mammal"]], model: "(a) Animals from different groups can move in the same way. The bat is a mammal but it can fly like the sparrow, which is a bird. (b) ‘Does it have feathers?’ (c) The whale would be placed in Group 2, but it is really a mammal because it breathes through lungs and feeds its young on milk.", fig: { type: "flow", root: "Animals", node: { q: "Can it fly?", yes: "Group 1", no: { q: "Lives in water?", yes: "Group 2", no: "Group 3" } } } },
    { q: "Study the Venn diagram. John says, ‘The worker ant is not an insect because it has no wings.’ Is John correct? Explain your answer.", marks: 2, kw: [["not correct", "wrong", "incorrect", "is an insect"], ["6 legs", "six legs", "3 body parts", "three body parts", "3 pairs", "three pairs"]], model: "John is not correct. The worker ant is an insect because it has 6 legs and 3 body parts. Not all insects have wings.", fig: { type: "venn", a: "Has 6 legs", b: "Has wings", onlyA: ["worker ant"], both: ["beetle", "dragonfly"], onlyB: ["pigeon"], neither: ["spider", "snail"] } },
    { q: "A salamander and a gecko look alike. (a) Which group does each animal belong to? (b) State one difference between their skin. (c) Where does the salamander lay its eggs?", marks: 4, kw: [["amphibian"], ["reptile"], ["moist", "smooth"], ["water"]], model: "(a) The salamander is an amphibian and the gecko is a reptile. (b) The salamander has moist, smooth skin, but the gecko has dry, scaly skin. (c) The salamander lays its eggs in water." },
    { q: "A starfish lives in the sea. Explain why it is not a fish.", marks: 2, kw: [["no fins", "no fin", "not have fins", "not have any fins", "doesn't have fins", "doesn't have any fins", "without fins", "not have fins or", "not have fins and"], ["no scales", "no scale", "not have scales", "doesn't have scales", "without scales", "fins or scales", "fins and scales"]], model: "Fish have fins and most have scales. A starfish has no fins and no scales, so it is not a fish." },
    { q: "A snake has no legs. Explain why it is still classified as a reptile.", marks: 2, kw: [["dry", "scaly", "scales"], ["lung"]], model: "The snake has dry, scaly skin and it breathes through lungs, which are characteristics of reptiles. Having no legs does not change its group." },
    { q: "(a) Other than its pair of feelers, state two characteristics that show a mosquito is an insect. (b) A centipede also has a pair of feelers. Explain why it is NOT an insect.", marks: 3, kw: [["6 legs", "six legs", "3 pairs", "three pairs"], ["3 body parts", "three body parts", "3 parts", "three parts", "head, thorax", "thorax"], ["many legs", "more than 6", "more than six", "too many legs", "lots of legs"]], model: "(a) A mosquito has 6 legs (3 pairs of legs) and 3 body parts: head, thorax and abdomen. (b) A centipede has many legs, more than 6 legs, so it is not an insect." }
  ],
  doc: [
    { q: "Explain why a bat is not a bird.", marks: 2, answers: ["Because it is a mammal.", "The bat has fur and not feathers, and it feeds its young on milk, so it is a mammal.", "The bat can fly but it is not a bird."], best: 1, why: "Answer 2 gives the group AND two characteristics (fur instead of feathers, milk). Answer 1 names the group without any reason. Answer 3 just repeats the question and gives no characteristic." },
    { q: "Explain why a worker ant is an insect even though it has no wings.", marks: 2, answers: ["It has 3 body parts and 6 legs, which are characteristics of insects. Not all insects have wings.", "Because it is small and crawls on the ground.", "It is an insect because it is an ant."], best: 0, why: "Answer 1 uses the insect characteristics (3 body parts, 6 legs). Answer 2 uses size and movement, which do not decide the group. Answer 3 goes round in a circle and gives no evidence." },
    { q: "Explain why a salamander is an amphibian.", marks: 2, answers: ["It lives near water.", "It looks like a lizard but it is not a lizard.", "It has moist, smooth skin and it lays its eggs in water."], best: 2, why: "Answer 3 gives two amphibian characteristics. Answer 1 uses habitat, which many animals share. Answer 2 says what it is not, without saying what makes it an amphibian." },
    { q: "Explain why a snake is a reptile.", marks: 2, answers: ["It has no legs and slithers on the ground.", "It has dry, scaly skin and it breathes through lungs.", "It has scales."], best: 1, why: "Answer 2 gives two reptile characteristics, including DRY scaly skin. Answer 1 describes movement, not a characteristic of the group. Answer 3 is too vague, as fish and the pangolin also have scales." },
    { q: "Explain why a starfish is not a fish.", marks: 2, answers: ["It has five arms.", "It is not a fish because it lives in the sea.", "It is not a fish because it has no fins and no scales, which fish have."], best: 2, why: "Answer 3 compares it with the characteristics of fish. Answer 1 describes the starfish but does not link it to fish. Answer 2 gives the wrong reason, since fish also live in the sea." }
  ]
};
