window.BANKX = window.BANKX || {};
BANKX["fungi"] = {
  notes: [
    { h: "Reading mould-growth graphs", t: "On a line graph of mould area against days, a steeper line means the mould is growing faster. A flat line means the area is not increasing, so the mould is not growing (or has already covered all the food). Always compare set-ups on the SAME day, and quote numbers with units, e.g. ‘18 cm² on Day 5’.", kw: ["steeper line", "growing faster", "flat line", "same day", "units"] },
    { h: "Planning a mould experiment", t: "Change only one variable (e.g. temperature) and keep everything else the same: type and size of bread, amount of water, container and number of days. Measure the amount of mould the same way each time, e.g. the area covered by mould in cm². Keep mouldy food in sealed bags and never smell it, because spores can be breathed in and make us sick.", kw: ["change only one variable", "keep everything else the same", "area covered by mould", "sealed bags", "spores can be breathed in"] },
    { h: "Which condition does each method remove?", t: "Fridge and freezer: take away warmth, so growth slows. Drying and salting (ikan bilis, salted fish): take away water. Airtight containers, vacuum packs and cans: keep out air and new spores or bacteria. Cooking food well kills many harmful bacteria. Each method works by removing a condition that fungi and bacteria need to grow.", kw: ["take away warmth", "take away water", "keep out air", "spores", "kills many harmful bacteria"] }
  ],
  traps: [
    "A flat line on a mould graph means the mould is growing steadily -> a flat line means the area is NOT increasing, so the mould is not growing (or has covered the whole food).",
    "Sealing bread in an airtight bag removes the mould spores on it -> it only keeps out new spores and air; spores already on the bread can still grow.",
    "The set-up with no mould is a failed experiment -> it is the one we compare with; it shows what happens when a condition (e.g. water) is taken away."
  ],
  mcq: [
    { q: "Study the two set-ups. Which variable is being changed?", o: ["The temperature", "The amount of water", "The type of bread", "The amount of light"], a: 1, why: "Both dishes are in the same warm cupboard with the same bread; only the water is different. Temperature, bread and light are kept the same.", lvl: 1, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["White bread", "5 ml of water added", "Warm dark cupboard"] }, { label: "B", icon: "dish", lines: ["White bread", "No water added", "Warm dark cupboard"] }] } },
    { q: "Which way of keeping food works mainly by taking away WATER?", o: ["Freezing it", "Keeping it in the fridge", "Drying it in the sun", "Putting it in an airtight box"], a: 2, why: "Drying removes water, which mould and bacteria need. Freezing and the fridge take away warmth; an airtight box keeps out air and spores.", lvl: 1 },
    { q: "Study the bar graph. Where did the most mould grow after 5 days?", o: ["Freezer", "Fridge", "Both places had the same amount", "Kitchen table"], a: 3, why: "The kitchen table (warm) had the tallest bar, 15 cm². The freezer had no mould and the fridge had only a little, because the cold slows down mould growth.", lvl: 1, fig: { type: "bar", title: "Mould on bread after 5 days", xl: "Where the bread was kept", yl: "Area of mould (cm²)", bars: [["Freezer", 0], ["Fridge", 3], ["Kitchen table", 15]] } },
    { q: "Tempeh is made by growing a mould on cooked soybeans. What does this show?", o: ["Some fungi are useful in making food.", "All moulds are harmful to people.", "Mould can make its own food like plants.", "Soybeans are a kind of fungus too."], a: 0, why: "The mould used for tempeh is a useful fungus. Some moulds spoil food, but not all moulds are harmful.", lvl: 1 },
    { q: "Study the line graph of mould growing on bread at 30 °C. By how much did the area of mould increase from Day 2 to Day 4?", o: ["4 cm²", "12 cm²", "16 cm²", "20 cm²"], a: 1, why: "On Day 2 the area was 4 cm² and on Day 4 it was 16 cm², so it increased by 16 - 4 = 12 cm². 16 cm² is the reading on Day 4, not the increase.", lvl: 2, fig: { type: "line", title: "Mould on bread at 30 °C", xl: "Day", yl: "Area of mould (cm²)", pts: [["0", 0], ["1", 1], ["2", 4], ["3", 9], ["4", 16], ["5", 22]] } },
    { q: "Study the set-ups. Jun wants to find out if light affects the growth of mould. Which two set-ups should he compare?", o: ["A and C", "B and C", "A and B", "A, B and C"], a: 2, why: "A and B differ only in light; both are moist and at 30 °C. C is dry, so comparing it with A or B changes the water too.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Moist bread", "In the dark", "30 °C"] }, { label: "B", icon: "jar", lines: ["Moist bread", "In the light", "30 °C"] }, { label: "C", icon: "jar", lines: ["Dry bread", "In the light", "30 °C"] }] } },
    { q: "The bar graph shows the mould on four foods kept on the same kitchen counter for 4 days. Why did the crackers have no mould?", o: ["Crackers are not food for mould, so no mould could feed on them.", "The crackers were dry, so there was too little water for mould to grow.", "The crackers were kept in the dark, where mould cannot grow.", "The crackers were colder than the other foods, so mould could not grow."], a: 1, why: "Mould needs moisture. The dry crackers and salted fish had very little water. All the foods were kept in the same place, so light and temperature were the same.", lvl: 2, fig: { type: "bar", title: "Mould after 4 days", xl: "Food", yl: "Area of mould (cm²)", bars: [["Bread", 20], ["Cooked rice", 15], ["Crackers", 0], ["Salted fish", 1]] } },
    { q: "Vacuum-packed food has the air sucked out of the packet before it is sealed. How does this help the food to keep longer?", o: ["It makes the food so cold that mould cannot grow.", "It adds water to the food so that it stays fresh.", "It kills all the spores and bacteria inside the food.", "It removes the air that mould and bacteria need to grow."], a: 3, why: "Mould and bacteria need air. Removing the air and sealing the pack slows their growth. It does not make the food cold.", lvl: 2 },
    { q: "Study the bar graph. It shows how many days it took for mould to first appear on bread kept at different temperatures. What does the graph show?", o: ["The warmer the place, the sooner mould appeared.", "The colder the place, the sooner mould appeared.", "Temperature does not affect mould growth.", "Mould cannot grow at 5 °C."], a: 0, why: "At 30 °C mould appeared after 3 days, but at 5 °C it took 12 days. Mould did grow at 5 °C, only more slowly.", lvl: 2, fig: { type: "bar", title: "Days before mould first appeared", xl: "Temperature", yl: "Number of days", bars: [["5 °C", 12], ["15 °C", 7], ["30 °C", 3]] } },
    { q: "In his mould experiment, Ben sealed each slice of bread in a clear plastic bag and did not open the bags. Why?", o: ["So that he could observe the mould without letting the spores escape.", "So that the mould on the bread would get more light to grow.", "To stop the bread from getting any air, so no mould could grow.", "To make the bread grow mould much faster than it normally would."], a: 0, why: "Clear sealed bags let him see the mould safely without spores escaping into the air, where they could be breathed in.", lvl: 2 },
    { q: "Study the set-ups. Both bowls have the same amount of dough and yeast. What will most likely be observed after 1 hour?", o: ["The dough in B will rise more than the dough in A.", "Both doughs will rise by the same amount.", "The dough in A will rise more than the dough in B.", "Neither dough will rise."], a: 2, why: "Yeast is a living fungus that is more active in warmth, so the warm dough in A rises more. The cold fridge slows the yeast down.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Dough with yeast", "Warm kitchen", "30 °C"] }, { label: "B", icon: "beaker", lines: ["Dough with yeast", "In the fridge", "5 °C"] }] } },
    { q: "Which of the following will NOT slow down the growth of mould on a loaf of bread?", o: ["Keeping it in the freezer", "Keeping it in a warm, humid kitchen", "Keeping it in the fridge", "Toasting it dry and storing it in an airtight tin"], a: 1, why: "A warm, humid kitchen gives mould the warmth and moisture it needs. The other methods take away warmth, water or air.", lvl: 2 },
    { q: "Study the line graph for bread kept at 30 °C. The table shows results for identical bread kept at 10 °C. Which statement is correct?", o: ["Both slices grew mould at the same rate over the four days.", "The slice at 10 °C had no mould at all by the end of Day 4.", "Mould needs a cold place, such as 10 °C, to grow well on bread.", "Mould on the slice at 30 °C grew faster than on the slice at 10 °C."], a: 3, why: "On Day 4 the 30 °C slice had 16 cm² of mould but the 10 °C slice had only 3 cm². The 10 °C slice did grow some mould, just more slowly.", lvl: 3, fig: { type: "line", title: "Bread at 30 °C", xl: "Day", yl: "Area of mould (cm²)", pts: [["0", 0], ["1", 1], ["2", 4], ["3", 9], ["4", 16]] }, tbl: [["Day", "0", "1", "2", "3", "4"], ["Area of mould at 10 °C (cm²)", "0", "0", "1", "2", "3"]] },
    { q: "Study the line graph. The slice of bread had an area of 20 cm². Why did the area of mould stop increasing after Day 4?", o: ["The mould died because it was in the light.", "The whole slice was already covered with mould.", "The temperature suddenly dropped.", "Mould can only grow for 4 days."], a: 1, why: "By Day 4 the mould covered all 20 cm² of the slice, so there was no more bread for it to spread onto. The line becomes flat.", lvl: 3, fig: { type: "line", title: "Mould on a 20 cm² slice", xl: "Day", yl: "Area of mould (cm²)", pts: [["0", 0], ["1", 2], ["2", 6], ["3", 12], ["4", 20], ["5", 20], ["6", 20]] } },
    { q: "Study the set-ups. Priya wants to find out if the type of bread affects mould growth. Why is her experiment NOT a fair test?", o: ["She used only two set-ups instead of three or more.", "Both set-ups are kept together in the same cupboard.", "She changed both the type of bread and the water.", "She did not use any light to help the mould grow."], a: 2, why: "Both the type of bread and the water are different, so she cannot tell which one caused any difference. Keeping them in the same cupboard is correct.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["White bread", "Water added", "Kitchen cupboard"] }, { label: "B", icon: "plate", lines: ["Wholemeal bread", "No water added", "Kitchen cupboard"] }] } },
    { q: "Ms Tan added different amounts of water to four identical slices of bread kept in the same place. Study the bar graph. Which conclusion is correct?", o: ["Mould needs light to grow.", "The amount of water does not affect mould growth.", "The less water added, the more mould grew.", "The more water added, the more mould grew."], a: 3, why: "As the water increased from 0 ml to 15 ml, the area of mould increased from 0 to 18 cm². Light was not tested.", lvl: 3, fig: { type: "bar", title: "Mould after 5 days", xl: "Amount of water added", yl: "Area of mould (cm²)", bars: [["0 ml", 0], ["5 ml", 6], ["10 ml", 14], ["15 ml", 18]] } },
    { q: "Study the four set-ups. Which statements are correct?\nP: A will most likely have the most mould after 5 days.\nQ: C and D can be compared to find out if temperature affects mould growth.\nR: A and B cannot be compared to find out if temperature affects mould growth.", o: ["P only", "P and Q only", "Q and R only", "P and R only"], a: 3, why: "A is warm, moist and open to the air, so it grows the most mould (P). A and B differ in both temperature and container, so they cannot be compared (R is true). C and D also differ in two things, so Q is false.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist bread", "Open dish", "30 °C"] }, { label: "B", icon: "box", lines: ["Moist bread", "Airtight box", "5 °C"] }, { label: "C", icon: "dish", lines: ["Dry bread", "Open dish", "5 °C"] }, { label: "D", icon: "box", lines: ["Dry bread", "Airtight box", "30 °C"] }] } },
    { q: "Which statements about fungi and bacteria are true?\nA: Both are living things.\nB: Some of both kinds are decomposers.\nC: Both can only be seen with a microscope.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Both are living and some of each break down dead matter. C is false: mushrooms and patches of mould can be seen with our eyes, though bacteria need a microscope.", lvl: 3 },
    { q: "Study the set-ups. Wei wants to find out if AIR affects the growth of mould. Which two set-ups should he compare?", o: ["A and B", "B and C", "A and C", "He cannot use any of these set-ups."], a: 0, why: "A and B are both moist bread in a bag at 25 °C; only the air is different. B and C differ in water, and A and C differ in both air and water.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Moist bread", "Bag with air inside", "25 °C"] }, { label: "B", icon: "box", lines: ["Moist bread", "Air sucked out of bag", "25 °C"] }, { label: "C", icon: "box", lines: ["Dry bread", "Air sucked out of bag", "25 °C"] }] } },
    { q: "A loaf of bread was kept in the fridge from Day 0 to Day 4 and then moved to a warm kitchen table. Study the line graph. Which statement best explains the results?", o: ["The fridge killed the mould, and new mould grew on the table.", "Mould only grows after 4 days.", "The cold slowed down the mould, and it grew quickly once the bread was warm.", "Mould grows faster in the cold."], a: 2, why: "There was almost no mould while the bread was cold, but the area rose quickly after Day 4 in the warmth. Cold only slows mould; it does not kill it.", lvl: 3, fig: { type: "line", title: "Mould on bread", xl: "Day", yl: "Area of mould (cm²)", pts: [["0", 0], ["2", 0], ["4", 1], ["6", 8], ["8", 18]] } }
  ],
  tf: [
    { s: "On a mould-growth line graph, a steeper part of the line shows the mould is growing faster.", a: true, why: "More area is added in the same number of days." },
    { s: "Bread mould grows faster at 5 °C than at 30 °C.", a: false, why: "Cold slows mould growth; it grows faster in warm conditions." },
    { s: "Tempeh is made with the help of a fungus.", a: true, why: "A useful mould is grown on soybeans to make tempeh." },
    { s: "Cooking food well can kill many harmful bacteria.", a: true, why: "Heat from thorough cooking kills many harmful bacteria." },
    { s: "Sealing bread in an airtight bag removes all the mould spores already on it.", a: false, why: "It only keeps out new spores and air; spores already on the bread can still grow." },
    { s: "We should smell mouldy bread closely to check how bad it is.", a: false, why: "Spores can be breathed in and make us sick; keep mouldy food sealed." },
    { s: "Bread dough with yeast rises more slowly in the fridge than in a warm kitchen.", a: true, why: "Yeast is a living fungus that is less active in the cold." },
    { s: "Dried anchovies (ikan bilis) grow mould faster than cooked rice kept in the same place.", a: false, why: "Ikan bilis is dry, and mould needs moisture; moist cooked rice spoils faster." }
  ],
  oe: [
    { q: "Study the line graph of mould on bread kept at 30 °C. (a) Describe how the area of mould changed over the 5 days. (b) The same experiment was repeated with identical bread at 5 °C. Would the area of mould on Day 5 be more or less than 20 cm²? Explain.", marks: 3, kw: [["increase", "more and more", "bigger"], ["less", "smaller"], ["cold", "low temperature", "slow"]], model: "(a) The area of mould increased as the number of days increased, from 0 cm² to 20 cm². (b) It would be less than 20 cm², because the cold (low temperature) slows down the growth of mould.", fig: { type: "line", title: "Mould on bread at 30 °C", xl: "Day", yl: "Area of mould (cm²)", pts: [["0", 0], ["1", 1], ["2", 3], ["3", 8], ["4", 14], ["5", 20]] } },
    { q: "Study the three set-ups. The bread is the same type and size in each. (a) Which two set-ups should be compared to find out if water affects mould growth? (b) Which set-up will most likely have the most mould after 5 days? Give two reasons. (c) State one other thing that must be kept the same.", marks: 4, kw: [["a and c", "c and a"], ["warm"], ["moist", "damp", "water"], ["number of days", "amount of time", "same time", "type of container", "same dish", "same type of dish", "size of bread", "same bread", "type of bread", "temperature", "same place", "air"]], model: "(a) A and C. (b) A, because it is warm and the bread is moist. (c) The bread must be kept for the same number of days in the same type of dish.", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist bread", "Warm cupboard"] }, { label: "B", icon: "dish", lines: ["Moist bread", "In the fridge"] }, { label: "C", icon: "dish", lines: ["Dry bread", "Warm cupboard"] }] } },
    { q: "Four foods were left on the same kitchen counter for 5 days. Study the bar graph. (a) Explain why the dried ikan bilis and the crackers had no mould. (b) Suggest one way to keep cooked rice from spoiling so quickly, and explain how it works.", marks: 3, kw: [["dry", "little water", "no water", "moisture"], ["fridge", "refrigerat", "freez", "airtight", "sealed container", "cover"], ["slow", "cold", "low temperature", "keep out", "keeps out", "cannot enter", "spores cannot"]], model: "(a) The ikan bilis and crackers are dry, with very little water (moisture), and mould needs water to grow. (b) Keep the cooked rice in the fridge. The cold (low temperature) slows down the growth of mould and bacteria.", fig: { type: "bar", title: "Mould after 5 days", xl: "Food", yl: "Area of mould (cm²)", bars: [["Bread", 18], ["Cooked rice", 14], ["Dried ikan bilis", 0], ["Crackers", 0]] } },
    { q: "Study the bar graph. It shows how many days it took for mould to first appear on identical slices of bread kept at different temperatures. State the relationship between the temperature and the number of days before mould appeared.", marks: 2, kw: [["higher", "warmer", "increase"], ["fewer days", "sooner", "earlier", "less time", "shorter", "faster"]], model: "The higher the temperature, the fewer days it took for mould to appear. Mould appeared sooner when the bread was warmer.", fig: { type: "bar", title: "Days before mould first appeared", xl: "Temperature", yl: "Number of days", bars: [["5 °C", 12], ["15 °C", 7], ["25 °C", 4], ["30 °C", 3]] } },
    { q: "Pupils put fruit peels and dead leaves into a compost bin in the school garden. After a few weeks, the peels had turned into dark, crumbly compost. (a) Name two kinds of living things that caused this. (b) What did these living things do to the peels? (c) Why is the compost useful to the school garden?", marks: 4, kw: [["fungi", "fungus", "mould", "mushroom"], ["bacteria"], ["break down", "broke down", "decompos", "decay", "rot"], ["soil", "plants grow", "help plants", "helps plants", "nutrient", "fertilis", "fertiliz"]], model: "(a) Fungi and bacteria. (b) They are decomposers that broke down the dead peels and leaves. (c) The broken-down substances return to the soil, which helps the plants in the garden grow." },
    { q: "Explain why pupils are told never to open the sealed bags of mouldy bread in a class experiment.", marks: 2, kw: [["spore"], ["breathe", "sick", "ill", "harm", "allerg"]], model: "Mould spores could escape into the air. If we breathe in the spores, they may make us sick." },
    { q: "Canned food can be kept for a long time without spoiling. Explain why.", marks: 2, kw: [["air", "sealed", "airtight"], ["spore", "bacteria", "cannot enter", "cannot get in"]], model: "The can is sealed and airtight, so air cannot get in. Mould spores and bacteria cannot enter the can, so they cannot grow on the food." },
    { q: "Aisha forgot a sandwich in her school bag during a hot, humid week. When she found it, it was covered with fuzzy green patches. (a) Where did the mould most likely come from? (b) State two conditions in her bag that helped the mould to grow.", marks: 3, kw: [["spore"], ["warm", "hot"], ["moist", "damp", "humid", "water"]], model: "(a) Mould spores in the air landed on the sandwich and grew into mould. (b) The bag was warm, and the sandwich and air were moist (humid)." }
  ],
  doc: [
    { q: "Explain why bread kept in the fridge grows mould more slowly than bread kept on the table.", marks: 2, answers: ["Because the fridge is cold.", "The low temperature in the fridge slows down the growth of mould.", "Because mould does not like the fridge."], best: 1, why: "Answer 2 gives the condition (low temperature) AND its effect (slows down mould growth). Answer 1 states the condition but not what it does to the mould. Answer 3 is too vague and gives no scientific reason." },
    { q: "No mould grew on the dry bread in Set-up C. Explain why.", marks: 2, answers: ["Mould needs water to grow. The dry bread had no water, so mould could not grow.", "Because it was dry.", "Because the bread was not wet, so it was clean."], best: 0, why: "Answer 1 links the evidence (dry bread) to what mould needs (water). Answer 2 only repeats the evidence with no reasoning. Answer 3 gives a wrong idea: dry bread still has spores on it." },
    { q: "Tom never touched the bread in Set-up A, but mould still grew on it. Explain how.", marks: 2, answers: ["Tom did not touch it but it still grew.", "The bread went bad by itself.", "Mould spores in the air landed on the bread and grew into mould."], best: 2, why: "Answer 3 uses the keywords spores and air. Answer 1 repeats the question. Answer 2 wrongly suggests the mould came from the bread itself." },
    { q: "Why should only one variable be changed in a mould experiment?", marks: 2, answers: ["Because it is not fair.", "If two things are changed, we cannot tell which one caused the difference in the amount of mould.", "Because the teacher said so."], best: 1, why: "Answer 2 explains WHY: we would not know which change caused the result. Answer 1 is a claim with no reason. Answer 3 is not a scientific reason." },
    { q: "Explain why biscuits are kept in an airtight container.", marks: 2, answers: ["An airtight container keeps out air, moisture and mould spores, so mould cannot grow easily on the biscuits.", "To keep them nice.", "So that ants cannot eat them."], best: 0, why: "Answer 1 names what is kept out and links it to mould growth. Answer 2 is too vague. Answer 3 is a true benefit but does not use the science of mould and bacteria." }
  ]
};
