window.BANKZ = window.BANKZ || {};
BANKZ["fungi"] = {
  lessons: [
    {
      h: "Making results reliable and measuring mould fairly",
      concept: "One slice of bread in each set-up is not enough: that one slice might have had more spores on it by chance. To make results more reliable, repeat the experiment (or use several identical slices in each set-up) and compare the results. To compare fairly, measure the mould the same way every time, e.g. count the number of days before mould first appears, or measure the area of mould on the same day for every slice.",
      example: {
        q: "Nora wanted to find out if temperature affects the growth of mould. She used one slice of moist bread in each set-up and looked at them after 5 days. (a) Suggest one way to make her results more reliable. (b) Suggest one way she could measure the growth of mould in each set-up.",
        fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["1 slice moist bread", "Kitchen table", "30 °C"] }, { label: "B", icon: "plate", lines: ["1 slice moist bread", "Fridge", "5 °C"] }] },
        marks: 2,
        think: [
          "Step 1: Spot the weakness. Only ONE slice in each set-up means a chance result could fool her.",
          "Step 2: For (a), say what to do AND how: repeat the experiment, or use more identical slices in each set-up, then compare.",
          "Step 3: For (b), give something she can count or measure, not just ‘look at it’: the number of days before mould first appears, or the area of mould on the same day.",
          "Step 4: Check your answer does not change a second variable (e.g. do not say ‘use a bigger slice in A’)."
        ],
        answer: "(a) Repeat the experiment with a few more identical slices of moist bread in each set-up and compare the results. (b) Count the number of days before mould first appears on the bread in each set-up (or measure the area of mould on each slice on Day 5)."
      },
      tip: "‘Repeat the experiment’ makes results more reliable; ‘change only one variable’ makes it fair. Do not mix up the two.",
      try: {
        q: "Ahmad put one slice of moist bread in a warm cupboard and one in the fridge. Which change would make his results more reliable?",
        o: ["Use a different type of bread in each of the two places.", "Repeat it with more identical slices in each place and compare.", "Keep both slices in the fridge for the whole of the 10 days.", "Look at the two slices only once, at the end of the 10 days."],
        a: 1,
        why: "Repeating with more identical slices shows whether the result happens every time. Using different bread adds a second variable, keeping both in the fridge removes the variable being tested, and looking only once gives less information."
      }
    }
  ],
  mcq: [
    { q: "Which of these living things can only be seen with a microscope?", o: ["A mushroom", "Bacteria", "Bread mould", "A fern"], a: 1, why: "Bacteria are too small to be seen with our eyes or a magnifying glass. Mushrooms, ferns and patches of bread mould can all be seen with our eyes.", lvl: 1 },
    { q: "Which of the following grows from a spore?", o: ["A mushroom", "A sunflower", "A mango tree", "A chick"], a: 0, why: "Fungi such as mushrooms reproduce by spores. Sunflowers and mango trees grow from seeds, and a chick hatches from an egg.", lvl: 1 },
    { q: "Which of the following is NOT a fungus?", o: ["Mushroom", "Yeast", "Bread mould", "Bacteria"], a: 3, why: "Mushrooms, yeast and moulds are fungi. Bacteria are a separate group of living things that can only be seen with a microscope.", lvl: 1 },
    { q: "Siti looked at bread mould with a magnifying glass. She saw tiny black dots on top of thin threads. What do the black dots most likely contain?", o: ["Seeds", "Eggs", "Spores", "Bacteria"], a: 2, why: "Mould reproduces by spores, which are held in the tiny black dots at the tips of the threads. Fungi do not make seeds or lay eggs, and bacteria cannot be seen with a magnifying glass.", lvl: 2 },
    { q: "Ravi says, ‘The mould on this bread is not alive because it does not move.’ Which observation best shows that the mould is a living thing?", o: ["The patch is green and fuzzy in colour.", "The mould makes the bread smell bad.", "The patch grows bigger over a few days.", "The mould is found on top of the bread."], a: 2, why: "Misconception: all living things must move from place to place. Growing is a characteristic of living things; the mould grows bigger. Colour, smell and where it is found do not show it is living.", lvl: 2 },
    { q: "Study the Venn diagram. Which living thing could be X?", o: ["A moss", "Yeast", "A mushroom", "A chicken"], a: 0, why: "X can make its own food AND reproduces by spores, so it is a plant that has spores, like a moss or a fern. Yeast and mushrooms cannot make their own food, and a chicken does neither.", lvl: 2, fig: { type: "venn", a: "Makes its own food", b: "Reproduces by spores", onlyA: ["hibiscus"], both: ["X"], onlyB: ["bread mould"], neither: ["cat"] } },
    { q: "Study the classification key. Which of the following correctly matches P, Q and R?", o: ["P: mushroom, Q: bacteria, R: fern", "P: fern, Q: mushroom, R: bacteria", "P: bacteria, Q: fern, R: mushroom", "P: fern, Q: bacteria, R: mushroom"], a: 3, why: "Only the fern makes its own food (P). Bacteria and mushrooms cannot; bacteria can only be seen with a microscope (Q), while a mushroom can be seen with our eyes (R).", lvl: 2, fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "P", no: { q: "Seen only with microscope?", yes: "Q", no: "R" } } } },
    { q: "Which of the following help mould to grow on bread?\nA: Warmth\nB: Moisture\nC: Light", o: ["A only", "B and C only", "A, B and C", "A and B only"], a: 3, why: "Misconception: mould needs light like a plant does. Mould grows well where it is warm and moist (with food and air) and grows just as well in the dark, so C is wrong.", lvl: 2 },
    { q: "A plate of cooked chicken rice was left uncovered at a hawker stall for many hours on a hot day. Why could it be unsafe to eat?", o: ["Harmful bacteria can grow quickly on warm food left out.", "The chicken rice slowly makes its own bacteria from inside.", "The heat of the day turns the rice itself into mould.", "Sunlight makes the rice give off harmful spores into the air."], a: 0, why: "Misconception: germs come from the food itself. Bacteria from the air, dust and flies land on the food and grow quickly when it is warm, which can cause food poisoning.", lvl: 2 },
    { q: "Study the line graph of mould growing on a slice of bread. Between which two days did the mould grow the fastest?", o: ["Day 1 to Day 2", "Day 2 to Day 3", "Day 3 to Day 4", "Day 5 to Day 6"], a: 2, why: "The increases are 1, 3, 6 and 1 cm². The biggest increase (6 cm², from 4 to 10) is from Day 3 to Day 4, where the line is steepest, even though the line is highest on Day 6.", lvl: 3, fig: { type: "line", xl: "Day", yl: "Area of mould (cm²)", pts: [["0", 0], ["1", 0], ["2", 1], ["3", 4], ["4", 10], ["5", 13], ["6", 14]] } },
    { q: "Study the set-ups. Which statements are correct?\nA: P and Q can be compared to find out if air affects mould growth.\nB: Q and S can be compared to find out if temperature affects mould growth.\nC: P and R can be compared to find out if water affects mould growth.", o: ["A only", "A and B only", "A and C only", "B and C only"], a: 2, why: "P and Q differ only in the container (air); P and R differ only in moist or dry bread (water). Q and S differ in BOTH the container and the temperature, so B is not a fair comparison.", lvl: 3, fig: { type: "setups", items: [{ label: "P", icon: "dish", lines: ["Moist bread", "Open dish", "30 °C"] }, { label: "Q", icon: "box", lines: ["Moist bread", "Airtight box", "30 °C"] }, { label: "R", icon: "dish", lines: ["Dry bread", "Open dish", "30 °C"] }, { label: "S", icon: "dish", lines: ["Moist bread", "Open dish", "10 °C"] }] } },
    { q: "Identical slices of moist bread were kept in three places. The table shows when mould first appeared. Which conclusion is correct?", o: ["The fridge killed the mould spores that were on the bread.", "Mould cannot grow at all when the temperature is low.", "The higher the temperature, the longer mould took to appear.", "The lower the temperature, the longer mould took to appear."], a: 3, why: "Misconception: the fridge kills mould. Mould still appeared in the fridge, only later (Day 12), so low temperature slows mould down but does not kill it or stop it.", lvl: 3, tbl: [["Place", "Temperature", "Day mould first appeared"], ["Kitchen table", "30 °C", "3"], ["Air-conditioned room", "22 °C", "5"], ["Fridge", "5 °C", "12"]] },
    { q: "Which statements about yeast are correct?\nA: It is a living thing.\nB: It can make its own food.\nC: It is used to make bread dough rise.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Yeast is a living fungus used to make bread dough rise. Like all fungi, it cannot make its own food, so B is wrong.", lvl: 3 },
    { q: "Each pot started with 100 g of dead leaves on soil and was kept at 30 °C for 4 weeks. Before the start, the soil in one pot was heated in an oven. The garden soil and the heated soil were then watered equally; the dry garden soil was not watered. Study the bar graph. Why did the leaves on the heated soil hardly break down?", o: ["The heating killed the fungi and bacteria in the soil.", "The heated soil let in more light to fall on the leaves.", "The heating made the dead leaves able to make food.", "The heated soil had no air at all left inside it."], a: 0, why: "Fungi and bacteria in the soil are decomposers that break down dead leaves. Heating killed them, so the leaves stayed. The heated soil was watered like the garden soil, and light does not break down leaves.", lvl: 3, fig: { type: "bar", xl: "Soil", yl: "Mass of leaves left (g)", bars: [["Garden soil", 20], ["Dry garden soil", 80], ["Heated soil", 95]] } },
    { q: "Which of the following would most likely happen if there were no decomposers?\nA: Dead leaves and dead animals would pile up.\nB: Materials in dead things would not be returned to the soil.\nC: Plants would grow faster because there is more dead matter.", o: ["A only", "A and B only", "B and C only", "A and C only"], a: 1, why: "Decomposers such as fungi and bacteria break down dead matter and return materials to the soil. Without them, dead things would pile up and the soil would not get these materials back, so plants would not grow better.", lvl: 3 },
    { q: "Which of the following are ways that fungi are useful to people?\nA: Some mushrooms can be eaten as food.\nB: Some moulds are used to make medicine.\nC: Mould on bread helps the bread stay fresh for longer.", o: ["A only", "B only", "A and B only", "A, B and C"], a: 2, why: "Some mushrooms are food and some moulds are used to make medicine. Mould on bread spoils it; it does not keep it fresh.", lvl: 3 },
    { q: "Three bowls had the same amount of bread dough with yeast. Study the bar graph of how much each dough rose in 1 hour. Why did the dough kept at 70 °C not rise?", o: ["The high temperature made the yeast turn into mould.", "Yeast needs light, and that bowl was kept in the dark.", "The yeast grew too fast and used up all the dough.", "The yeast was killed by the very high temperature."], a: 3, why: "Yeast is a living thing: warmth helps it (30 °C rose most) and cold slows it (5 °C), but a very high temperature kills it. Yeast does not need light, and it does not turn into mould.", lvl: 4, fig: { type: "bar", xl: "Temperature", yl: "Rise in height (cm)", bars: [["5 °C", 1], ["30 °C", 5], ["70 °C", 0]] } },
    { q: "The table shows the area of mould on identical slices of bread kept at two temperatures. Which statements are correct?\nA: At both temperatures, the area of mould increased every 2 days.\nB: On Day 4, the area of mould at 30 °C was more than twice the area at 20 °C.\nC: At 20 °C, the mould grew more from Day 4 to Day 6 than from Day 0 to Day 4.", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 1, why: "A is true: both rows increase every time. B is true: 9 cm² is more than twice 4 cm² (8 cm²). C is false: at 20 °C the mould grew 4 cm² from Day 4 to Day 6 and also 4 cm² from Day 0 to Day 4, which is the same.", lvl: 4, tbl: [["Day", "0", "2", "4", "6"], ["Area at 30 °C (cm²)", "0", "3", "9", "16"], ["Area at 20 °C (cm²)", "0", "1", "4", "8"]] },
    { q: "Study the set-ups. After 5 days, both slices had mould, but Q had less. Ali said, ‘Mould grew in Q, so mould does not need air.’ Which is the best reason why his conclusion is wrong?", o: ["Mould grew in Q only because the box kept the light out.", "Mould in Q grew from the bread itself and not from spores.", "The spores in Q came from the plastic of the airtight box.", "The box in Q still had some air trapped inside with the bread."], a: 3, why: "Misconception: an airtight box has no air in it. It only stops fresh air from getting in; the air sealed inside with the bread was enough for some mould to grow. Mould does not need light, and it grows from spores, not from the bread or the box.", lvl: 4, fig: { type: "setups", items: [{ label: "P", icon: "dish", lines: ["Moist bread", "Open dish", "30 °C"] }, { label: "Q", icon: "box", lines: ["Moist bread", "Airtight box", "30 °C"] }] } },
    { q: "Study the classification key. Which statements are correct?\nA: W could be a moss.\nB: X could be a mushroom.\nC: Z could be bacteria.", o: ["A only", "B and C only", "A and B only", "A, B and C"], a: 2, why: "A moss reproduces by spores and makes its own food (W). A mushroom reproduces by spores but cannot make its own food (X). Bacteria can only be seen with a microscope, so they belong in Y, not Z.", lvl: 4, fig: { type: "flow", root: "Living things", node: { q: "Reproduces by spores?", yes: { q: "Makes its own food?", yes: "W", no: "X" }, no: { q: "Seen only with microscope?", yes: "Y", no: "Z" } } } }
  ],
  oe: [
    { q: "Kai wanted to find out how temperature affects the growth of mould on orange peel. He put one piece of moist orange peel in each set-up and checked them after 7 days. (a) State the aim of his experiment. (b) In which set-up would the most mould grow? Give a reason. (c) Suggest one way to make his results more reliable.", marks: 3, kw: [["temperature"], ["warm", "30", "higher"], ["repeat", "more pieces", "more peel", "several"]], model: "(a) To find out if temperature affects the growth of mould on orange peel. (b) Set-up C, because it is the warmest (30 °C) and mould grows faster at a higher temperature. (c) Repeat the experiment using more pieces of identical orange peel in each set-up and compare the results.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Moist orange peel", "Fridge", "5 °C"] }, { label: "B", icon: "jar", lines: ["Moist orange peel", "Air-con room", "20 °C"] }, { label: "C", icon: "jar", lines: ["Moist orange peel", "Kitchen", "30 °C"] }] } },
    { q: "Yeast gives off a gas that can blow up a balloon. Mr Tan set up four identical bottles, each with a balloon over the mouth, and measured the width of each balloon after 1 hour. (a) Which two bottles show that yeast needs sugar as food? (b) Explain why balloon C was smaller than balloon A. (c) What does bottle D show?", marks: 3, kw: [["a and b", "b and a"], ["cold", "low temperature"], ["no yeast", "without yeast", "yeast is needed", "needs yeast", "need yeast"]], model: "(a) A and B. (b) The water in C was cold, and the low temperature slows down the yeast, so it gave off less gas. (c) Yeast is needed for the balloon to blow up, because D had no yeast and its balloon stayed flat.", tbl: [["Bottle", "A", "B", "C", "D"], ["Contents", "Warm water, sugar, yeast", "Warm water, yeast", "Cold water, sugar, yeast", "Warm water, sugar"], ["Width of balloon (cm)", "12", "2", "4", "0"]], x: 1 },
    { q: "Mushrooms are grown on a farm in Kranji. They are grown in a dark, cool and damp shed, on bags of sawdust. (a) Vegetables need light to grow well, but mushrooms can be grown in the dark. Explain why. (b) Where do the mushrooms get their food from? (c) Explain why the shed is kept damp.", marks: 3, kw: [["own food", "fungi", "fungus", "cannot make", "not make", "can't make", "don't make"], ["sawdust"], ["water", "moist"]], model: "(a) Mushrooms are fungi. They cannot make their own food, so they do not need light as plants do. (b) They feed on the sawdust, which is dead and decaying matter. (c) Mushrooms need water to grow, and the damp shed keeps them moist.", },
    { q: "Pupils left identical slices of moist bread in open dishes in three places in school for 5 days. Study the bar graph. (a) State the relationship between the temperature and the area of mould. (b) The canteen is also more humid than the other places. Explain why this may make the experiment NOT a fair test. (c) Predict the area of mould on a slice kept in a room at 26 °C for 5 days. Explain your prediction.", marks: 3, kw: [["higher the temperature", "warmer", "hotter"], ["humid", "damp", "moist", "water"], ["between", "more than 6", "less than 15", "bigger than 6", "smaller than 15"]], model: "(a) The higher the temperature, the larger the area of mould. (b) The canteen is more humid (damp), so the amount of moisture is also different; two variables are changed and we cannot tell which one caused the extra mould. (c) Between 6 cm² and 15 cm², because 26 °C is between 22 °C and 30 °C, and the higher the temperature, the larger the area of mould.", fig: { type: "bar", xl: "Place (temperature)", yl: "Area of mould after 5 days (cm²)", bars: [["Fridge (5 °C)", 1], ["Library (22 °C)", 6], ["Canteen (30 °C)", 15]] }, x: 1 },
    { q: "Mei wants to find out if the type of food affects how fast mould grows. Study her set-ups. (a) Which variable is she changing? (b) State two things she must keep the same to make it a fair test. (c) Suggest how she can tell on which food mould grows the fastest.", marks: 4, kw: [["type", "kind"], ["same amount of food", "same amount of each", "same amount of bread", "same size", "same mass", "same weight", "same quantity"], ["same place", "same temperature", "same container", "same amount of water", "same dish"], ["number of days", "how many days", "which day", "first appear", "area"]], model: "(a) The type of food. (b) The same size (amount) of each food, and the same place and temperature for all three. (c) Check every day and record the number of days before mould first appears on each food; the one where mould appears first grows mould the fastest.", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Bread", "Open dish", "Kitchen, 30 °C"] }, { label: "B", icon: "dish", lines: ["Cooked rice", "Open dish", "Kitchen, 30 °C"] }, { label: "C", icon: "dish", lines: ["Banana", "Open dish", "Kitchen, 30 °C"] }] } },
    { q: "At a hawker centre: (a) Explain why cooked food on display should be kept covered. (b) Explain why leftover food should be kept in the fridge. (c) Not all bacteria are harmful. Give one way bacteria are useful.", marks: 3, kw: [["bacteria", "spore", "germ", "flies"], ["slow"], ["yoghurt", "yogurt", "cheese", "decompos", "break down"]], model: "(a) The cover keeps out dust, flies, mould spores and harmful bacteria that could land on the food and grow. (b) The low temperature in the fridge slows down the growth of bacteria and mould, so the food keeps longer. (c) Some bacteria are used to make yoghurt and cheese." }
  ],
  tf: [
    { s: "Bread mould is made up of many tiny threads.", a: true, why: "Seen under a magnifying glass, mould is a mass of thin threads, with tiny spore cases on top." },
    { s: "Mould is a kind of plant because it grows on food.", a: false, why: "Misconception: anything that grows is a plant. Mould is a fungus; it cannot make its own food and feeds on the food it grows on." },
    { s: "A mushroom can be seen without a microscope, but a single bacterium cannot.", a: true, why: "Bacteria are so tiny that they can only be seen with a microscope." },
    { s: "Mould grows only on food that has been touched by dirty hands.", a: false, why: "Mould spores are carried by the air, so they can land on food that no one has touched." },
    { s: "Warmth helps yeast to make bread dough rise faster.", a: true, why: "Yeast is a living thing that is more active when it is warm; cold slows it down." },
    { s: "Bacteria are too small to be living things.", a: false, why: "Size does not decide whether something is living. Bacteria are living things; they just need a microscope to be seen." },
    { s: "Dead leaves would pile up if there were no decomposers.", a: true, why: "Fungi and bacteria break down dead leaves; without them, dead matter would not be broken down." },
    { s: "Yoghurt is safe to eat because it contains no bacteria at all.", a: false, why: "Misconception: all bacteria are harmful. Yoghurt is made with the help of useful bacteria." },
    { s: "Some moulds are used to make medicine.", a: true, why: "Some moulds are useful; certain medicines are made from them." },
    { s: "A living thing that reproduces by spores must be a fungus.", a: false, why: "Ferns and mosses are plants that also reproduce by spores." }
  ],
  doc: [
    { q: "Why is yeast added to bread dough?", marks: 2, answers: ["To make the bread taste nice.", "Yeast is a bacteria that makes the bread.", "Yeast makes the dough rise, so the bread is soft and fluffy."], best: 2, why: "Answer 3 states what yeast does (makes the dough rise) and the result. Answer 1 is vague and gives no science. Answer 2 is wrong: yeast is a fungus, not a bacterium, and it does not say what yeast does." },
    { q: "Explain why dead leaves on the forest floor at MacRitchie do not pile up higher every year.", marks: 2, answers: ["Decomposers such as fungi and bacteria break down the dead leaves.", "Because the leaves disappear after some time.", "Because the wind blows the leaves away."], best: 0, why: "Answer 1 names the decomposers (fungi and bacteria) and what they do (break down the leaves). Answer 2 just repeats the observation with no reason. Answer 3 gives a wrong cause; wind only moves leaves around the forest floor, it does not get rid of them." }
  ]
};
