window.BANKU = window.BANKU || {};
BANKU["fungi"] = {
  glossary: [
    { t: "Fungi", d: "A group of living things, such as mushrooms, moulds and yeast, that cannot make their own food and reproduce by spores." },
    { t: "Bacteria", d: "Very tiny living things that can only be seen with a microscope. They are found almost everywhere, e.g. in air, soil, water and on our bodies." },
    { t: "Spore", d: "A very tiny, light part released by a fungus and carried by the air. It grows into a new fungus when it lands somewhere warm and damp with food." },
    { t: "Mould", d: "A fungus that grows as fuzzy patches of thin threads on food and damp materials, e.g. bread mould. It spoils food and reproduces by spores." },
    { t: "Yeast", d: "A fungus used to make bread. It feeds on sugar and gives off a gas that makes bread dough rise." },
    { t: "Mushroom", d: "A fungus with a stalk and a cap that often grows on rotting wood or damp soil. It feeds on dead or decaying matter; some mushrooms can be eaten, but some are poisonous." },
    { t: "Decomposer", d: "A living thing that feeds on dead plants and animals and breaks them down into simpler substances that return to the soil, e.g. some fungi and bacteria." },
    { t: "Decay", d: "The breaking down of dead plants and animals by decomposers such as fungi and bacteria. It is also called rotting." },
    { t: "Microscope", d: "An instrument that makes very tiny things, such as bacteria, look much bigger so that we can see them." },
    { t: "Food spoilage", d: "The change that makes food unsafe or unpleasant to eat when mould or bacteria grow on it, e.g. mouldy bread or sour milk." },
    { t: "Airtight container", d: "A container sealed so that air, moisture, mould spores and bacteria cannot get in. It slows down the spoiling of the food inside." },
    { t: "Fair test", d: "An experiment in which only one variable is changed and all other variables are kept the same, so we know what caused the result." }
  ],
  lessons: [
    {
      h: "Writing the missing question in a classification key",
      concept: "A classification key sorts living things using questions about characteristics that can be answered yes or no. To find a missing question, list the living things on its YES side and on its NO side, then find one characteristic that ALL the YES ones have and NONE of the NO ones have. Use characteristics such as ‘Can it make its own food?’, ‘Does it reproduce by spores?’ or ‘Can it be seen only with a microscope?’, not size, colour or where it lives.",
      example: {
        q: "Study the classification key. (a) Write a suitable question for P. (b) A moss is added to the key. Which living thing in the key would it be grouped with?",
        fig: { type: "flow", root: "Living things", node: { q: "Question P", yes: { q: "Reproduces by spores?", yes: "fern", no: "hibiscus" }, no: { q: "Seen only with microscope?", yes: "bacteria", no: "mushroom" } } },
        marks: 2,
        think: [
          "Step 1: List both sides of P. YES side: fern and hibiscus. NO side: bacteria and mushroom.",
          "Step 2: Ask what the fern and hibiscus both have that the bacteria and mushroom do not: they are plants, so they can make their own food.",
          "Step 3: Check the question does not repeat one already used lower down (spores, microscope) and can be answered yes or no. ‘Does it have green leaves?’ would also work.",
          "Step 4: For (b), answer the key’s questions for a moss: it makes its own food (YES at P) and reproduces by spores (YES), so it ends where the fern is."
        ],
        answer: "(a) Can it make its own food? (b) The fern, because a moss can make its own food and reproduces by spores, just like the fern."
      },
      tip: "A key question must split the group in two: every YES item has the feature and every NO item does not.",
      try: {
        q: "Study the classification key. Which question could be Question Q?",
        fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "rice plant", no: { q: "Question Q", yes: "bread mould", no: "cat" } } },
        o: ["Does it need water to live?", "Does it reproduce by spores?", "Is it a living thing?", "Can it make its own food?"],
        a: 1,
        why: "Bread mould reproduces by spores but a cat does not, so this question splits them. Both need water and both are living, so those questions do not split them, and ‘Can it make its own food?’ has already been used: both answer no."
      }
    },
    {
      h: "Explaining the purpose of a control set-up",
      concept: "In many experiments, one set-up is kept WITHOUT the thing being tested, e.g. no salt, no yeast or no vinegar. This is the control. It is used for comparison: because it is the same as the other set-up except for one variable, any difference in the results must be caused by that variable. A full-mark answer says the set-up is for comparison AND names the one variable being tested.",
      example: {
        q: "Aminah wanted to find out if vinegar affects the growth of mould on cucumber, as vinegar is used in achar. She soaked identical cucumber slices in vinegar (A) or in water (B) for 1 hour, then kept both in open dishes in the same warm kitchen. (a) What is the purpose of set-up B? (b) Mould appeared on B after 3 days but not on A after 7 days. What can she conclude?",
        fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Cucumber slices", "Soaked in vinegar", "Open dish", "Kitchen, 30 °C"] }, { label: "B", icon: "dish", lines: ["Cucumber slices", "Soaked in water", "Open dish", "Kitchen, 30 °C"] }] },
        marks: 2,
        think: [
          "Step 1: Spot the one difference between A and B: vinegar or water. Everything else (cucumber, dish, place) is the same.",
          "Step 2: B has no vinegar, so it is the control. Say what it is for: comparison with A.",
          "Step 3: Link it to the variable: because only the vinegar is different, any difference in mould must be caused by the vinegar.",
          "Step 4: For (b), state the effect of the variable on mould, not just the results: vinegar slows down the growth of mould."
        ],
        answer: "(a) B is for comparison with A. The only difference is the vinegar, so she can tell whether vinegar affects the growth of mould. (b) Vinegar slows down the growth of mould on cucumber."
      },
      tip: "Purpose of a control: ‘for comparison, to show that the difference is caused by ___ (the variable tested)’.",
      try: {
        q: "Jun put dough, sugar and yeast in Bowl X, and dough and sugar with NO yeast in Bowl Y. Both bowls were kept in the same warm place. What is the purpose of Bowl Y?",
        o: ["To show that the dough rises because of the yeast", "To show that sugar is needed for the dough to rise", "To show that warmth makes the yeast more active", "To give the yeast in Bowl X more space to grow"],
        a: 0,
        why: "X and Y differ only in the yeast, so Y is the control that shows the rise in X is caused by the yeast. Both bowls had sugar and were equally warm, so they cannot show the effect of sugar or warmth."
      }
    }
  ],
  flash: [
    { f: "What does bread mould look like?", b: "Fuzzy patches of many thin threads, often black, green or white. The tiny dots at the tips of the threads hold spores." },
    { f: "Why can mushrooms be grown in the dark?", b: "They cannot make their own food, so they do not need light. They feed on dead or decaying matter, e.g. sawdust or rotting logs." },
    { f: "How does yeast make bread dough rise?", b: "Yeast is a living fungus. It feeds on sugar in the dough and gives off a gas; the gas bubbles make the dough rise." },
    { f: "Why should meat and eggs be cooked well?", b: "Heat from cooking kills many harmful bacteria in the food, so we are less likely to get food poisoning." },
    { f: "How can we make the results of a mould experiment more reliable?", b: "Repeat the experiment, or use several identical slices in each set-up, and compare the results." },
    { f: "Two ways to measure the growth of mould", b: "Measure the area of mould (cm²) on the same day for every set-up, or count the number of days before mould first appears." },
    { f: "What does a steep part of a mould-growth line graph show?", b: "The mould is growing fast: the area of mould increases a lot in a short time. A flat part shows the area is not increasing." },
    { f: "Is dried yeast in a packet living or non-living?", b: "Living. It is not active while dry and cool, but becomes active again when given water, warmth and food (sugar)." },
    { f: "Why can mould grow on leather shoes in a damp cupboard?", b: "Leather comes from a once-living animal, so mould can feed on it. The damp cupboard gives the moisture mould needs." },
    { f: "Name two foods made with the help of useful moulds", b: "Tempeh (a mould is grown on cooked soybeans) and some cheeses, such as blue cheese." },
    { f: "How do bacteria cause tooth decay?", b: "Bacteria in the mouth feed on sugar left on the teeth and make substances that damage the teeth. Brushing after meals removes the sugar." },
    { f: "One similarity and one difference between fungi and bacteria", b: "Both are living things and some of each are decomposers. Bacteria can only be seen with a microscope, but mushrooms and mould patches can be seen with our eyes." }
  ],
  mcq: [
    { q: "The fuzzy green patch on a rotting orange is mould. To which group of living things does mould belong?", o: ["Plants", "Fungi", "Bacteria", "Animals"], a: 1, why: "Mould is a fungus: it cannot make its own food and reproduces by spores. Bacteria are a different group that can only be seen with a microscope.", lvl: 1 },
    { q: "Pupils pressed four objects onto identical dishes of jelly-like food for bacteria. The dishes were kept in the same warm place for 3 days. Each spot is a group of many bacteria. Study the bar graph. Which object most likely had the most bacteria on it?", o: ["Door handle", "Washed hand", "Phone screen", "Clean cotton bud"], a: 2, why: "The phone screen has the tallest bar (40 spots), so it had the most bacteria. The washed hand had only 5 spots and the clean cotton bud had none.", lvl: 1, fig: { type: "bar", title: "Spots after 3 days", xl: "Object pressed on dish", yl: "Number of spots", bars: [["Door handle", 25], ["Washed hand", 5], ["Phone screen", 40], ["Clean cotton bud", 0]] } },
    { q: "Which of these foods is made with the help of yeast?", o: ["Yoghurt", "Salted fish", "Tempeh", "Bread"], a: 3, why: "Yeast, a fungus, makes bread dough rise. Yoghurt is made with the help of bacteria, tempeh with the help of a mould, and salted fish keeps because the salt removes water.", lvl: 1 },
    { q: "At a wet market, a fishmonger keeps fresh fish on crushed ice. How does this help the fish to stay fresh for longer?", o: ["The cold slows down the growth of bacteria.", "The ice kills all the bacteria on the fish.", "The ice keeps out the air that bacteria need.", "The melting ice washes all the bacteria away."], a: 0, why: "The low temperature slows down the growth of bacteria, so the fish spoils more slowly. Cold does not kill all the bacteria, and the fish is still open to the air.", lvl: 1 },
    { q: "Which of the following are characteristics of fungi?\nA: They reproduce by spores.\nB: They cannot make their own food.\nC: They have green leaves.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Fungi reproduce by spores and cannot make their own food. They have no green leaves, which is one reason they are not plants.", lvl: 2 },
    { q: "Study the Venn diagram. Which living thing could X be?", o: ["Bacteria used to make cheese", "Mould on a leather bag", "A moss plant", "Yeast"], a: 3, why: "X is a fungus AND helps to make food, so it is yeast, which makes bread dough rise. Cheese bacteria are not fungi, mould on a bag does not help make food, and a moss is a plant.", lvl: 2, fig: { type: "venn", a: "Is a fungus", b: "Helps make food", onlyA: ["bread mould"], both: ["X"], onlyB: ["yoghurt bacteria"], neither: ["fern"] } },
    { q: "Which of the following does NOT help to prevent food poisoning at a school canteen?", o: ["Washing hands with soap before cooking", "Cooking chicken until it is well done", "Leaving cooked food uncovered on the counter", "Keeping raw meat in the fridge until it is used"], a: 2, why: "Uncovered food lets dust, flies and bacteria land on it, and bacteria then grow on the warm food. The other habits remove, kill or slow down harmful bacteria.", lvl: 2 },
    { q: "Bread dough with yeast was kept in a warm kitchen. Study the line graph. By how much did the height of the dough increase from 15 min to 45 min?", o: ["5 cm", "4 cm", "9 cm", "6 cm"], a: 1, why: "At 15 min the dough was 5 cm high and at 45 min it was 9 cm high, so it increased by 9 - 5 = 4 cm. 5 cm and 9 cm are readings, not the increase.", lvl: 2, fig: { type: "line", title: "Dough with yeast", xl: "Time (min)", yl: "Height of dough (cm)", pts: [["0", 4], ["15", 5], ["30", 7], ["45", 9], ["60", 10]] } },
    { q: "Bala wants to find out if covering cooked food affects how soon it spoils. Study the table. Which two set-ups should he compare?", o: ["P and R", "Q and R", "P and S", "P and Q"], a: 3, why: "P and Q differ only in whether the rice is covered. P and R differ in the cover and the place, Q and R differ in the place, and P and S differ in the type of food.", lvl: 2, tbl: [["Set-up", "Food", "Covered?", "Where kept"], ["P", "Cooked rice", "Yes", "Table, 30 °C"], ["Q", "Cooked rice", "No", "Table, 30 °C"], ["R", "Cooked rice", "No", "Fridge, 5 °C"], ["S", "Fried noodles", "Yes", "Table, 30 °C"]] },
    { q: "Black mould often grows between the tiles of a bathroom in an HDB flat. Which is the best way to slow down its growth?", o: ["Open the window after a shower so the bathroom dries", "Switch off the lights so that the bathroom stays dark", "Keep the door and window shut so the bathroom is warm", "Splash water on the tiles every day to wash spores off"], a: 0, why: "Mould needs moisture, so letting the bathroom dry out slows its growth. Mould does not need light, and warmth and extra water help it grow.", lvl: 2 },
    { q: "Which statement about mould spores is correct?", o: ["They are tiny seeds that grow into new plants.", "They can only grow on food kept in the light.", "They are tiny and light, and carried by the air.", "They are made by bacteria so they can reproduce."], a: 2, why: "Spores are tiny and light, so the air carries them onto food. They are not seeds, moulds are fungi not plants, they do not need light, and they are made by fungi, not bacteria.", lvl: 2 },
    { q: "Study the set-ups. The slices of bread were the same type and size. Which shows the set-ups in order, from the MOST mould to the LEAST mould after 7 days?", o: ["A, B, C", "C, A, B", "B, C, A", "A, C, B"], a: 3, why: "A is moist and warm, so it grows the most mould. C is moist but cooler, so mould grows more slowly. B is dry and sealed, so there is very little water and no new spores can get in, so it has the least.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist bread", "Open dish", "Kitchen, 30 °C"] }, { label: "B", icon: "box", lines: ["Bread toasted dry", "Airtight box", "Kitchen, 30 °C"] }, { label: "C", icon: "dish", lines: ["Moist bread", "Open dish", "Air-con room, 22 °C"] }] } },
    { q: "A mushroom farm in Kranji grew mushrooms on identical bags of sawdust in three sheds at the same temperature for 4 weeks. Study the bar graph. Which statements are supported by the results?\nP: Mushrooms do not need light to grow well.\nQ: Mushrooms need water to grow well.\nR: Mushrooms grow better in the light than in the dark.", o: ["P only", "P and Q only", "Q and R only", "P, Q and R"], a: 1, why: "The dark and bright damp sheds gave about the same mass (500 g and 490 g), so light is not needed (P), and R is wrong. The dark, dry shed gave only 40 g, so water is needed (Q).", lvl: 3, fig: { type: "bar", title: "Mushrooms after 4 weeks", xl: "Shed", yl: "Mass of mushrooms (g)", bars: [["Dark, damp", 500], ["Bright, damp", 490], ["Dark, dry", 40]] } },
    { q: "A wooden fence post at Pasir Ris Park has its bottom part buried in damp soil. After a few years, the buried part had rotted away but the part above the ground had not. Which is the best explanation?", o: ["Fungi and bacteria in the damp soil broke down the wood.", "Sunlight on the part above the ground made it stronger.", "The heavy soil slowly crushed the buried part of the wood.", "Roots of nearby plants fed on the buried part of the post."], a: 0, why: "Wood comes from a once-living tree. Decomposers in the soil had the moisture they need to break it down; the dry part above ground rotted much more slowly. Plants make their own food, so roots do not feed on wood.", lvl: 3 },
    { q: "Ken wants to find out if temperature affects how soon fresh milk turns sour. Which of the following must he keep the same?\nA: The type of milk\nB: The amount of milk\nC: The temperature\nD: The type of container", o: ["A and B only", "C and D only", "A, B and D only", "A, B, C and D"], a: 2, why: "Temperature is the variable he changes, so it cannot be kept the same. The type and amount of milk and the container must all be kept the same for a fair test.", lvl: 3 },
    { q: "Four identical dishes of jelly-like food for bacteria were used. Three were opened for 1 hour in different places; one was never opened. All were then closed and kept in the same warm room for 3 days. Study the table. Which statements are supported by the results?\nP: There are bacteria in the air.\nQ: The unopened dish shows that the spots came from the air in each place.\nR: There are no bacteria in the air of the library.", o: ["P only", "Q and R only", "P and R only", "P and Q only"], a: 3, why: "Spots grew only on the dishes opened to the air, and none on the unopened dish, so P and Q are supported. R is wrong: the library dish still had 8 spots.", lvl: 3, tbl: [["Dish", "Spots after 3 days"], ["Opened in the canteen", "30"], ["Opened in a classroom", "12"], ["Opened in the library", "8"], ["Never opened", "0"]] },
    { q: "A packet of instant noodles can be kept in a cupboard for months, but cooked noodles spoil in a day or two. Which is the best reason?", o: ["The packet noodles are dry, so mould and bacteria cannot grow well.", "The packet noodles are kept dark, and bacteria grow only in light.", "The cooked noodles make their own bacteria from the hot water.", "The cooked noodles are warm, so spores are pulled towards them."], a: 0, why: "Mould and bacteria need water to grow, and the packet noodles are dry. Bacteria do not need light, they do not come from the food or water itself, and spores are carried by the air, not pulled by warmth.", lvl: 3 },
    { q: "A balloon was stretched over a bottle of warm water, sugar and yeast. Study the line graph. Which is the best reason why the balloon stopped getting bigger after 40 minutes?", o: ["The yeast had used up most of the sugar, its food.", "The yeast needed light, but the bottle was dark.", "The warm water had turned the yeast into mould.", "The yeast no longer needed any food after 40 min."], a: 0, why: "The yeast feeds on sugar and gives off gas that blows up the balloon. Once most of the sugar was used up, little more gas was given off, so the line became flat. Yeast does not need light and all living things need food.", lvl: 4, fig: { type: "line", title: "Balloon on yeast bottle", xl: "Time (min)", yl: "Width of balloon (cm)", pts: [["0", 0], ["10", 3], ["20", 7], ["30", 10], ["40", 12], ["50", 12], ["60", 12]] } },
    { q: "A packet of dried yeast says, ‘Store in a cool, dry place.’ When the yeast is added to warm sugar water, it becomes active and bubbles. Which statements are correct?\nA: The dried yeast in the packet is a living thing.\nB: Keeping it cool and dry slows the yeast down, so it keeps longer.\nC: The warm sugar water gives the yeast water, warmth and food.\nD: Boiling water would make the yeast bubble the fastest.", o: ["A and C only", "B and D only", "A, B and C only", "A, B, C and D"], a: 2, why: "Dried yeast is living but inactive; cool, dry storage keeps it that way, and warm sugar water gives it what it needs to become active. D is wrong: a very high temperature kills the yeast.", lvl: 4 },
    { q: "Dina kept identical slices of moist bread at 30 °C and at 5 °C, and repeated the experiment three times. The table shows the number of days before mould first appeared. What should she do next?", o: ["Conclude that mould grows faster at 5 °C than at 30 °C.", "Repeat Trial 3 at 30 °C, as it does not match the others.", "Use only Trial 3, as it is the most recent of the results.", "Conclude that temperature does not affect mould growth."], a: 1, why: "Trials 1 and 2 at 30 °C both took 3 days, so 9 days in Trial 3 is most likely an error and should be repeated. All the other results show mould appears sooner at 30 °C, so temperature does affect it.", lvl: 4, tbl: [["Temperature", "Trial 1", "Trial 2", "Trial 3"], ["30 °C", "3 days", "3 days", "9 days"], ["5 °C", "11 days", "12 days", "12 days"]] }
  ],
  oe: [
    { q: "Mdm Lee tried to make yoghurt. She set up three jars with the same amount of fresh milk and left them for 8 hours. Study the table. (a) Name the living things in the spoonful of yoghurt that turned the milk in Jar A into yoghurt. [1] (b) Which two jars show that these living things are needed to make yoghurt? [1] (c) Explain why the milk in Jar C stayed runny. [1]", marks: 3, kw: [["bacteria", "bacterium"], ["a and b", "b and a", "jar a and jar b", "jars a and b", "jar b and jar a", "jars b and a"], ["cold", "low temperature", "slow"]], model: "(a) Bacteria. (b) A and B. (c) The low temperature (cold) in the fridge slows down the growth of the bacteria, so the milk did not turn into yoghurt.", tbl: [["Jar", "A", "B", "C"], ["Spoonful of yoghurt added?", "Yes", "No", "Yes"], ["Kept at", "40 °C", "40 °C", "5 °C (fridge)"], ["After 8 hours", "Thick yoghurt", "Still runny", "Still runny"]] },
    { q: "Siti put identical slices of fresh moist bread in four identical closed boxes at 30 °C. A mouldy orange was placed in Boxes 1 to 3 at different distances from the bread. Box 4 had no mouldy orange. Study the bar graph. (a) State the relationship between the distance from the mouldy orange and the number of days before mould appeared. [1] (b) Explain why mould appeared sooner on bread nearer the mouldy orange. [1] (c) Box 4 had no mouldy orange, yet mould appeared on Day 7. Explain why. [1]", marks: 3, kw: [["the nearer", "the closer", "the shorter the distance", "the further", "the farther", "the greater the distance", "the longer the distance", "the more the distance", "the smaller the distance", "as the distance", "when the distance", "if the distance"], ["more spores", "many spores", "spores from the orange", "spores from the mouldy", "more of the spores", "spores reach", "spores can reach", "spores to reach"], ["already", "on the bread before", "in the box before", "inside the box before", "before it was closed", "before the box was closed", "spores from the air", "spores in the air"]], model: "(a) The nearer the bread is to the mouldy orange, the fewer days it takes for mould to appear. (b) The mouldy orange gives off many spores into the air in the box, and more spores land on the bread that is nearer, so mould grows on it sooner. (c) Mould spores from the air were already on the bread or inside the box before it was closed, and they grew into mould.", fig: { type: "bar", title: "Days before mould appeared", xl: "Distance of bread from mouldy orange", yl: "Number of days", bars: [["5 cm", 2], ["20 cm", 3], ["50 cm", 5], ["No orange", 7]] }, x: 1 },
    { q: "Athlete’s foot is an itchy skin problem between the toes. It is common in people who wear wet shoes and socks for a long time. (a) To which group of living things does the cause of athlete’s foot belong? [1] (b) Explain why wearing wet shoes for a long time helps it to grow on the feet. [1] (c) Suggest one way to prevent athlete’s foot. [1]", marks: 3, kw: [["fung"], ["need water", "needs water", "water to grow", "moist", "damp"], ["dry", "clean socks", "change socks", "change your socks", "change the socks", "air out", "airing", "antifungal"]], model: "(a) Fungi. (b) Fungi need moisture (water) to grow, and the wet shoes keep the skin warm and damp, so the fungus grows well. (c) Dry the feet well after bathing and wear clean, dry socks and shoes." },
    { q: "Wei wanted to find out if air affects the growth of mould on cooked rice. Study the set-ups. (a) Which two set-ups should he compare? [1] (b) Which set-up will most likely have the most mould after 5 days? Give a reason. [2] (c) Explain why B and C can NOT be used to find out if air affects mould growth. [1]", marks: 4, kw: [["a and b", "b and a", "set-ups a and b", "set-up a and set-up b", "jar a and jar b"], ["set up a", "set-up a", "jar a", "a because", "a as", "a since"], ["air"], ["temperature", "both have no air", "both had no air", "no air in both", "neither"]], model: "(a) A and B. (b) Set-up A, because it has air and it is warm (30 °C); mould needs air and warmth to grow well. (c) B and C both have no air; only the temperature is different, so they can only show whether temperature affects mould growth.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Moist cooked rice", "Sealed jar with air", "30 °C"] }, { label: "B", icon: "jar", lines: ["Moist cooked rice", "Air pumped out of jar", "30 °C"] }, { label: "C", icon: "jar", lines: ["Moist cooked rice", "Air pumped out of jar", "5 °C"] }] } }
  ],
  tf: [
    { s: "Mushrooms need sunlight to grow, just like green plants.", a: false, why: "Mushrooms cannot make their own food, so they do not need light; they can be grown in dark sheds." },
    { s: "Bacteria are a kind of fungus.", a: false, why: "Bacteria and fungi are two different groups of living things; bacteria can only be seen with a microscope." },
    { s: "Spores are tiny seeds made by fungi.", a: false, why: "Spores are not seeds. Seeds are made by flowering plants; fungi reproduce by spores." },
    { s: "Food kept in a dark cupboard will not spoil because bacteria need light to grow.", a: false, why: "Bacteria and mould do not need light; food in a dark cupboard can still spoil." },
    { s: "All moulds are harmful because they spoil food.", a: false, why: "Some moulds are useful, e.g. in making tempeh, some cheeses and some medicines." },
    { s: "A fungus is a living thing even though it does not move from place to place.", a: true, why: "Fungi grow, reproduce by spores and need food, water and air, so they are living." },
    { s: "Moist cooked rice spoils faster than dry uncooked rice kept in the same place.", a: true, why: "Mould and bacteria need water to grow; dry uncooked rice has very little water." },
    { s: "Boiling milk kills many of the bacteria in it.", a: true, why: "Heating food to a high temperature kills many bacteria, so boiled milk keeps a little longer." },
    { s: "Mould needs air to grow.", a: true, why: "Mould needs air, water, food and warmth to grow well; this is why vacuum packs slow its growth." },
    { s: "Cooked food left out for many hours can make people sick even if it looks and smells normal.", a: true, why: "Harmful bacteria are too small to see and can grow on warm food without changing how it looks or smells." }
  ]
};
