window.BANKV = window.BANKV || {};
BANKV["fungi"] = {
  flash: [
    { f: "Define: decomposer", b: "A living thing, such as some fungi and bacteria, that breaks down dead plants and animals into simpler substances, which return to the soil." },
    { f: "Name three kinds of fungi", b: "Mushrooms, moulds (e.g. bread mould) and yeast." },
    { f: "How do fungi reproduce?", b: "By spores. Spores are tiny and light and are carried by the air. A spore that lands on food in warm, damp conditions grows into a new fungus." },
    { f: "Why is a mushroom NOT a plant?", b: "It has no green leaves and cannot make its own food; it feeds on dead or decaying matter. (Not ‘because of spores’: ferns and mosses also reproduce by spores.)" },
    { f: "How do fungi get their food?", b: "They cannot make their own food. They feed on dead or decaying matter (e.g. rotting logs, stale bread) or on other living things." },
    { f: "Four conditions mould needs to grow well", b: "Warmth, moisture (water), food and air. Mould does not need light." },
    { f: "How can we see bacteria?", b: "Only with a microscope. They are too small to be seen with the naked eye or a magnifying glass." },
    { f: "Where are bacteria found?", b: "Almost everywhere: in air, soil and water, on our hands and in our mouths." },
    { f: "Useful effects of fungi", b: "Yeast makes bread dough rise; some mushrooms are eaten as food; some moulds are used to make medicine; fungi are decomposers that break down dead matter." },
    { f: "Useful effects of bacteria", b: "Bacteria are used to make yoghurt and cheese, and they are decomposers that break down dead plants and animals." },
    { f: "Harmful effects of fungi and bacteria", b: "Bacteria cause food poisoning, tooth decay and diseases. Moulds spoil food, some mushrooms are poisonous and some fungi cause athlete’s foot." },
    { f: "Why does keeping food in the fridge make it last longer?", b: "The low temperature slows down the growth of mould and bacteria. It does not kill them." },
    { f: "Why do drying and salting make food keep longer?", b: "They remove water (moisture) from the food. Mould and bacteria need water to grow, so their growth is slowed down." },
    { f: "Why does a sealed can of food keep for a long time?", b: "The food is heated to kill the bacteria and mould in it, and the can is sealed airtight, so no new air, spores or bacteria can get in." },
    { f: "Why change only ONE variable in a mould experiment?", b: "So that we know that this one change caused the difference in the amount of mould. All other variables are kept the same (fair test)." }
  ],
  mcq: [
    { q: "Fungi and bacteria are living things. Which of these is true of BOTH of them?", o: ["They need food, water and air to live.", "They make their own food from sunlight.", "They can only be seen with a microscope.", "They reproduce only by making seeds."], a: 0, why: "Like all living things, fungi and bacteria need food, water and air. Neither can make its own food, mushrooms can be seen with our eyes, and neither makes seeds.", lvl: 1 },
    { q: "Four foods were left on the same kitchen counter in an HDB flat. The bar graph shows the number of days before mould first appeared on each food. Which food took the longest to grow mould?", o: ["Cooked rice", "Kaya bun", "Cut papaya", "Dried mango"], a: 3, why: "The dried mango has the tallest bar (15 days). It has very little water, and mould needs moisture to grow. Cooked rice had mould soonest, after only 2 days.", lvl: 1, fig: { type: "bar", title: "Days before mould appeared", xl: "Food", yl: "Number of days", bars: [["Kaya bun", 3], ["Cooked rice", 2], ["Cut papaya", 4], ["Dried mango", 15]] } },
    { q: "Where are bacteria found?", o: ["Only in dirty drains and rubbish bins", "In air, soil, water and on our bodies", "Only in rotting food and raw meat", "Only inside people who are sick"], a: 1, why: "Bacteria are found almost everywhere, including on clean-looking hands and in our mouths. They are not found only in dirty places or sick people.", lvl: 1 },
    { q: "Which of these is a HARMFUL effect of fungi?", o: ["Breaking down fallen leaves in a park", "Making bread dough rise in a bakery", "Spoiling leather shoes in a damp cupboard", "Being cooked as food in mushroom soup"], a: 2, why: "Mould growing on leather shoes spoils them. Breaking down dead leaves, making dough rise and being eaten as food are useful effects of fungi.", lvl: 1 },
    { q: "A packet of seaweed snacks contains a small packet of silica gel, which takes in moisture. How does this help the snacks to keep longer?", o: ["It keeps the snacks dry, so mould cannot grow well.", "It keeps the snacks cold, so mould cannot grow well.", "It kills all the mould spores inside the packet.", "It adds air to the packet, so the snacks stay crisp."], a: 0, why: "Silica gel takes in moisture, so the snacks stay dry, and mould needs water to grow. It does not make the snacks cold, add air or kill spores.", lvl: 2 },
    { q: "Study the Venn diagram. Which living thing could X be?", o: ["A moss", "Bacteria in soil", "Mould on an orange", "A hibiscus plant"], a: 1, why: "X is a decomposer AND can only be seen with a microscope, so it is bacteria in the soil. Mould on an orange is a decomposer but can be seen with our eyes; moss and hibiscus are plants that make their own food.", lvl: 2, fig: { type: "venn", a: "Decomposer", b: "Seen only with microscope", onlyA: ["mushroom", "bread mould"], both: ["X"], onlyB: [], neither: ["fern", "cat"] } },
    { q: "Three bowls had the same amount of bread dough and yeast and were kept in the same warm place. Different amounts of sugar were added. Study the bar graph. Which conclusion is correct?", o: ["The more sugar added, the less the dough rose.", "The more sugar added, the more the dough rose.", "Sugar does not affect how much the dough rises.", "Dough rises only when no sugar is added to it."], a: 1, why: "As the sugar increased from 0 g to 10 g, the rise increased from 1 cm to 5 cm. Yeast is a living thing that uses sugar as food, so it was more active with more sugar.", lvl: 2, fig: { type: "bar", title: "Dough after 1 hour", xl: "Amount of sugar added", yl: "Rise in height (cm)", bars: [["0 g", 1], ["5 g", 3], ["10 g", 5]] } },
    { q: "After a party at the void deck, there was some nasi lemak left over. Which is the best way to keep it from spoiling quickly?", o: ["Leave it uncovered on the table to cool overnight.", "Cover it and leave it in a warm corner of the kitchen.", "Sprinkle water on it so that it stays moist and soft.", "Cover it and keep it in the fridge as soon as possible."], a: 3, why: "Covering keeps out flies, dust, spores and bacteria, and the low temperature in the fridge slows down the growth of bacteria and mould. Warmth and moisture help them grow faster.", lvl: 2 },
    { q: "During the rainy season, Mrs Goh found mould on the leather bags in a closed wardrobe in her HDB flat. Which of these would help to slow down the growth of mould on the bags?\nA: Putting a dehumidifier or moisture absorber in the wardrobe\nB: Wiping the bags dry and airing them out on a sunny day\nC: Wrapping the damp bags in plastic and closing the wardrobe tightly\nD: Spraying the bags with water and hanging them back while still wet", o: ["A only", "A and B only", "A, B and C only", "B, C and D only"], a: 1, why: "A and B take away moisture, which mould needs. C traps the moisture around the damp bags and D adds water, so both help mould to grow.", lvl: 3 },
    { q: "Study the set-ups. Both boxes are sealed and kept in the same warm place. On which slice of fresh bread will mould most likely appear sooner, and why?", o: ["B, because it has more air around it in the box.", "B, because mould grows best when bread is alone.", "A, because spores from the mouldy bread land on it.", "A, because mouldy bread makes the box much colder."], a: 2, why: "The mouldy bread releases many spores into box A, and some land on the fresh bread and grow. Both boxes are at 30 °C, so temperature is not the reason.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Fresh moist bread", "Next to mouldy bread", "Sealed box, 30 °C"] }, { label: "B", icon: "box", lines: ["Fresh moist bread", "No mouldy bread", "Sealed box, 30 °C"] }] } },
    { q: "Jia Hui wants to find out if cutting a fruit affects how soon mould grows on it. Study the table. Which two set-ups should she compare?", o: ["P and Q", "Q and R", "Q and S", "P and S"], a: 0, why: "P and Q are both papaya in the kitchen; only whole or cut is different. Q and R differ in the type of fruit, Q and S in the place, and P and S in two things.", lvl: 2, tbl: [["Set-up", "Fruit", "Whole or cut", "Where kept"], ["P", "Papaya", "Whole", "Kitchen, 30 °C"], ["Q", "Papaya", "Cut", "Kitchen, 30 °C"], ["R", "Banana", "Cut", "Kitchen, 30 °C"], ["S", "Papaya", "Cut", "Fridge, 5 °C"]] },
    { q: "Pupils put 100 g of dead leaves into a compost bin in the school garden and weighed what was left every week. Study the line graph. Which statement is correct?", o: ["The leaves broke down by the same amount every week.", "The leaves broke down fastest from Week 1 to Week 2.", "All of the leaves had broken down by Week 5.", "The leaves broke down fastest from Week 4 to Week 5."], a: 1, why: "The mass fell by 20, 25, 20, 10 and 5 g each week. The biggest drop (25 g, from 80 g to 55 g) was from Week 1 to Week 2. 20 g was still left on Week 5.", lvl: 3, fig: { type: "line", title: "Leaves in the compost bin", xl: "Week", yl: "Mass of leaves left (g)", pts: [["0", 100], ["1", 80], ["2", 55], ["3", 35], ["4", 25], ["5", 20]] } },
    { q: "Which statement about decomposers is NOT true?", o: ["They break down dead plants and animals.", "They include some fungi and bacteria.", "They return substances to the soil.", "They make their own food using sunlight."], a: 3, why: "Decomposers cannot make their own food; they feed on the dead matter they break down. The other three statements are true.", lvl: 2 },
    { q: "A jar of kaya says, ‘Refrigerate after opening.’ The unopened jar can be kept in a cupboard for months. Which statement best explains this?", o: ["Opening the jar lets light in, and mould needs light to grow.", "The kaya starts to make its own mould once the jar is opened.", "Once opened, spores and bacteria can get in; cold slows their growth.", "The fridge kills all the mould and bacteria that get into the jar."], a: 2, why: "The sealed jar kept out spores and bacteria. After opening, they can get in, and the low temperature of the fridge slows down their growth. The fridge does not kill them, and mould does not need light.", lvl: 3 },
    { q: "Identical slices of moist bread were kept as shown in the table. Which statements are correct?\nP: B and C can be compared to find out if temperature affects mould growth.\nQ: The sealed bag in the fridge slowed down mould growth but did not stop it.\nR: A and C can be compared to find out if a sealed bag affects mould growth.", o: ["P only", "Q and R only", "P and R only", "P and Q only"], a: 3, why: "B and C are both in sealed bags and differ only in temperature (P). Mould still appeared in C, only later, on Day 14 (Q). A and C differ in both the container and the temperature, so R is not a fair comparison.", lvl: 3, tbl: [["Set-up", "How it was kept", "Place", "Days before mould appeared"], ["A", "Open plate", "Table, 30 °C", "3"], ["B", "Sealed plastic bag", "Table, 30 °C", "6"], ["C", "Sealed plastic bag", "Fridge, 5 °C", "14"], ["D", "Open plate", "Fridge, 5 °C", "10"]] },
    { q: "Study the set-ups. Each jar has the same amount of chicken soup and is kept at 30 °C. The soup turns cloudy and smelly when bacteria grow in it. In which jar will the soup most likely stay clear the longest?", o: ["A, because boiling killed most bacteria and the lid kept new ones out.", "B, because boiling killed most bacteria and the air kept it fresh.", "C, because soup that is not heated has no bacteria that can grow.", "A and B equally, because both soups were boiled at the start."], a: 0, why: "Boiling kills most of the bacteria, and closing the lid at once stops new bacteria from the air getting in. In B, bacteria from the air can land in the open soup and grow.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Soup boiled", "Lid closed at once", "30 °C"] }, { label: "B", icon: "jar", lines: ["Soup boiled", "Left open", "30 °C"] }, { label: "C", icon: "jar", lines: ["Soup not boiled", "Left open", "30 °C"] }] } },
    { q: "A hawker kept washed wooden chopsticks in a closed drawer before they were dry. A week later, there were black spots on them. Which is the best explanation?", o: ["The wet wood itself turned into black mould in the dark drawer.", "The drawer was dark, and mould grows only where there is no light.", "Mould spores landed on the damp wood and grew by feeding on it.", "Dirt from the drawer slowly stained the wet chopsticks black."], a: 2, why: "Spores from the air landed on the damp chopsticks; the moisture and the wood (food) let them grow into mould. Mould comes from spores, not from the wood itself, and it does not need darkness.", lvl: 3 },
    { q: "Three dishes of jelly-like food for bacteria were set up. Each spot that grows is a group of many bacteria. Study the table. Which statements are supported by the results?\nP: Bacteria from the finger grew more at 30 °C than at 5 °C.\nQ: Dish 3 shows that most of the spots in Dish 1 came from the finger.\nR: The cold in Dish 2 killed all the bacteria from the finger.", o: ["P only", "Q and R only", "P and Q only", "P, Q and R"], a: 2, why: "Dishes 1 and 2 differ only in temperature: 35 spots at 30 °C but 2 at 5 °C (P). The untouched Dish 3 had only 1 spot, so the spots in Dish 1 came mostly from the finger (Q). R is false: 2 spots still grew in the cold.", lvl: 4, tbl: [["Dish", "Touched by unwashed finger?", "Kept at", "Spots after 3 days"], ["1", "Yes", "30 °C", "35"], ["2", "Yes", "5 °C", "2"], ["3", "No", "30 °C", "1"]] },
    { q: "Study the set-ups. Each jar has 50 g of dead leaves and is kept at 30 °C for 4 weeks. Which statements are correct?\nP: A and C can be compared to find out if the living things in the soil are needed to break down the leaves.\nQ: A and B can be compared to find out if air affects how fast the leaves break down.\nR: C and D can be compared to find out if water affects how fast the leaves break down.", o: ["P only", "Q only", "P, Q and R", "P and Q only"], a: 3, why: "A and C differ only in the soil (heating kills the decomposers in it), so P is true. A and B differ only in air (Q). C and D differ in both the soil and the water, so R is not a fair comparison.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Garden soil", "Moist", "Open jar"] }, { label: "B", icon: "jar", lines: ["Garden soil", "Moist", "Airtight jar"] }, { label: "C", icon: "jar", lines: ["Soil heated in oven", "Moist", "Open jar"] }, { label: "D", icon: "jar", lines: ["Garden soil", "Dry", "Open jar"] }] } },
    { q: "Milk turns sour when bacteria grow in it. Identical cartons of fresh milk were kept as shown in the table. Which statements are supported by the results?\nP: W and X show that opening the carton made the milk turn sour sooner.\nQ: X and Y show that the cold slows down the growth of bacteria in milk.\nR: X and Z show that the fridge matters more than keeping the carton closed.", o: ["P and Q only", "P only", "Q and R only", "P, Q and R"], a: 0, why: "W and X differ only in opening (14 days vs 5 days), and X and Y differ only in the place (5 days vs 1 day), so P and Q are supported. X and Z differ in BOTH opening and place, so they cannot be compared fairly.", lvl: 4, tbl: [["Carton", "Opened?", "Kept in", "Days before milk turned sour"], ["W", "No", "Fridge", "14"], ["X", "Yes", "Fridge", "5"], ["Y", "Yes", "Kitchen table", "1"], ["Z", "No", "Kitchen table", "2"]] }
  ],
  oe: [
    { q: "Pupils pressed an unwashed finger, a finger washed with water only, and a finger washed with soap and water onto three identical dishes of jelly-like food for bacteria. The dishes were kept in the same warm place for 3 days. Each spot is a group of many bacteria. Study the bar graph. (a) Which way of washing removed the most bacteria? (b) Explain why we should wash our hands with soap before eating at the school canteen. (c) Ravi says, ‘Soap and water killed all the bacteria on the finger.’ Use the graph to explain why he is wrong.", marks: 3, kw: [["soap"], ["harmful", "sick", "ill", "disease", "food poisoning", "germ"], ["still", "6 spots", "some bacteria", "some spots", "6"]], model: "(a) Washing with soap and water, because its dish had the fewest spots (6). (b) Soap and water remove harmful bacteria from our hands, which could get onto our food and make us sick. (c) The dish for that finger still had 6 spots, so some bacteria were left on the finger.", fig: { type: "bar", title: "Spots after 3 days", xl: "Finger", yl: "Number of spots", bars: [["Not washed", 38], ["Water only", 20], ["Soap and water", 6]] } },
    { q: "Kumar put identical slices of moist bread into three identical jars kept at 30 °C. Study the set-ups and the results. (a) Silica gel takes in moisture. Explain why the bread in Jar B had the least mould. (b) Which two jars should be compared to find out if silica gel affects the growth of mould? (c) Kumar said, ‘Jar A was closed, so the mould must have come from the bread itself.’ Explain why he is wrong.", marks: 4, kw: [["drier", "dry", "less water", "less moisture", "took in", "takes in", "absorb", "removes"], ["need water", "needs water", "need moisture", "needs moisture", "water to grow", "moisture to grow"], ["a and b", "b and a"], ["spore"]], model: "(a) The silica gel takes in moisture, so the bread in B is drier. Mould needs water (moisture) to grow, so less mould grew. (b) A and B. (c) Mould spores from the air were already on the bread or inside the jar before the lid was closed, and they grew into mould.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Moist bread", "Lid closed", "30 °C"] }, { label: "B", icon: "jar", lines: ["Moist bread", "Silica gel packet", "Lid closed", "30 °C"] }, { label: "C", icon: "jar", lines: ["Moist bread", "Lid open", "30 °C"] }] }, tbl: [["Jar", "A", "B", "C"], ["Area of mould after 5 days (cm²)", "8", "2", "12"]] },
    { q: "Tempeh is made by growing a useful mould on cooked soybeans. The soybeans are wrapped in banana leaves with small holes poked in them, and kept in a warm place for 2 days. (a) Why are the wrapped soybeans kept in a warm place? (b) Why are small holes poked in the wrapping? (c) The tempeh maker does not dry the soybeans completely before wrapping them. Explain why.", marks: 3, kw: [["faster", "quickly", "warmth", "needs warm", "need warm", "grows best", "grow best", "grows well", "grow well", "grow better", "grows better"], ["air"], ["water", "moist"]], model: "(a) Mould grows faster (grows best) when it is warm. (b) The holes let air in, and the mould needs air to grow. (c) The mould needs water (moisture) to grow, so the soybeans are kept moist.", x: 1 },
    { q: "Ali found a bracket fungus growing on the trunk of a living tree at Bukit Timah. (a) Ali says it is a plant because it grows on a tree. Give one correct reason why it is NOT a plant. (b) How does the bracket fungus get its food? (c) How does the bracket fungus reproduce?", marks: 3, kw: [["cannot make", "can't make", "unable to make", "does not make", "doesn't make", "no green leaves", "not have green leaves", "no leaves", "not have leaves"], ["feeds on", "feed on", "eats","gets food from", "get food from", "gets its food from", "takes food from", "feeding on"], ["spore"]], model: "(a) It cannot make its own food and it has no green leaves. (b) It feeds on the living tree, getting its food from another living thing. (c) It reproduces by spores." }
  ],
  tf: [
    { s: "Mould can grow on leather shoes and wooden furniture, not only on food.", a: true, why: "Leather and wood come from once-living things, so mould can feed on them when they are damp." },
    { s: "Spores are so tiny and light that they can be carried by the air.", a: true, why: "This is how mould reaches food that no one has touched." },
    { s: "Bacteria are too small to cause any harm to people.", a: false, why: "Size does not matter: some bacteria cause food poisoning, tooth decay and diseases." },
    { s: "Washing hands with water alone removes all the bacteria on them.", a: false, why: "Water alone removes only some bacteria; soap and water remove many more, but not every single one." },
    { s: "Some fungi can grow on a living tree as well as on a dead log.", a: true, why: "Some fungi feed on other living things, while others feed on dead or decaying matter." },
    { s: "The mould that grows on bread is a type of bacteria.", a: false, why: "Mould is a fungus. Bacteria are a different group that can only be seen with a microscope." },
    { s: "A slice of bread that looks clean may already have mould spores on it.", a: true, why: "Spores are too tiny to see; they only show up as mould after they grow." },
    { s: "Food taken out of the fridge has no bacteria on it at all.", a: false, why: "Cold only slows down the growth of bacteria; it does not kill them." },
    { s: "Decomposers help to return substances from dead things to the soil.", a: true, why: "Fungi and bacteria break down dead matter, and the simpler substances return to the soil." },
    { s: "Fungi do not need water because they get everything they need from the food they grow on.", a: false, why: "Fungi need water to grow; this is why dry food such as crackers and ikan bilis grows mould very slowly." }
  ],
  sort: [
    { title: "Which condition does each method mainly take away from mould and bacteria?", groups: ["Takes away warmth", "Takes away water", "Keeps out air and spores"], items: [["keeping kaya in the fridge", 0], ["freezing fish", 0], ["putting drinks in an ice box at a hawker stall", 0], ["drying ikan bilis in the sun", 1], ["salting fish", 1], ["a silica gel packet in a snack packet", 1], ["keeping biscuits in an airtight tin", 2], ["vacuum-packing bak kwa", 2], ["sealing sardines in a can", 2]] }
  ]
};
