window.BANKX = window.BANKX || {};
BANKX["living"] = {
  notes: [
    { h: "One clue is not enough", t: "To decide that something is living, we need evidence of ALL the characteristics: it needs air, food and water, grows, reproduces and responds to changes. A sugar crystal can get bigger and a robot can respond to sound, but neither can reproduce, so both are non-living. When a question asks ‘Is this enough evidence?’, check whether only ONE characteristic has been shown.", kw: ["all the characteristics", "only one characteristic", "not enough evidence"] },
    { h: "Showing growth by measuring", t: "Scientists show that a living thing grows by measuring it (height, length, mass or area) at regular times, e.g. every 2 days, and recording the results in a table or graph. A line that keeps going up shows the living thing is growing. In a fair test, only ONE thing is changed and everything else is kept the same.", kw: ["measure", "at regular times", "line goes up", "fair test", "only one thing changed"] },
    { h: "Grow, reproduce or respond?", t: "GROW: the SAME living thing gets bigger or changes as it gets older (a tadpole becomes a frog, a seedling gets taller). REPRODUCE: NEW young of its own kind are produced (a cat gives birth to kittens, more mushrooms appear on a log). RESPOND: the living thing reacts to a change around it (a boy shivers in the cold, a shoot bends towards light).", kw: ["same living thing gets bigger", "new young of its own kind", "reacts to a change"] }
  ],
  traps: [
    "‘A tadpole turning into a frog is reproduction’ -> it is growth; the same animal changes as it gets older. Reproduction produces NEW young.",
    "‘More mushrooms on the log means the mushroom grew’ -> more NEW mushrooms of the same kind means the mushrooms reproduced.",
    "‘The graph shows it gets bigger, so it is living’ -> getting bigger is only one clue; a crystal also gets bigger. We need evidence of ALL the characteristics."
  ],
  mcq: [
    { q: "The line graph shows the height of a chilli seedling measured every 2 days. Which characteristic of living things does the graph show?", o: ["Living things need water", "Living things grow", "Living things reproduce", "Living things respond to changes"], a: 1, why: "The height increases over time, so the seedling is growing. The graph does not show new young being produced, so it does not show reproduction.", lvl: 1, fig: { type: "line", title: "Chilli seedling", xl: "Day", yl: "Height of seedling (cm)", pts: [["0", 0], ["2", 1], ["4", 2], ["6", 4], ["8", 6]] } },
    { q: "A caterpillar spends most of its day eating leaves. This shows that living things need ______.", o: ["air", "water", "food", "sunlight"], a: 2, why: "Eating leaves shows the caterpillar needs food. Animals do not need sunlight to make food, because they cannot make their own food.", lvl: 1 },
    { q: "Study the classification chart. Which of these would be placed at C?", o: ["Hibiscus", "Grasshopper", "Mushroom", "Plastic cup"], a: 3, why: "C is for things that are not living. A plastic cup was never living. Hibiscus goes to A, and the grasshopper and mushroom go to B because they cannot make their own food.", lvl: 1, fig: { type: "flow", root: "Things", node: { q: "Is it living?", yes: { q: "Makes its own food?", yes: "A", no: "B" }, no: "C" } } },
    { q: "A tadpole slowly changes into a frog. Which characteristic of living things does this show?", o: ["Living things grow", "Living things reproduce", "Living things respond to changes", "Living things need air"], a: 0, why: "The same animal changes as it gets older, so it is growing. Reproducing would be the frog producing NEW young (laying eggs).", lvl: 1 },
    { q: "Study the Venn diagram. Which of these could be X?", o: ["Toy robot dog", "Pile of beach sand", "Bird’s nest fern", "Campfire flame"], a: 2, why: "X is living but cannot move from place to place, like a fern. A robot moves and is non-living; sand and fire are non-living, so they cannot be in the ‘Living’ circle.", lvl: 2, fig: { type: "venn", a: "Living", b: "Can move", onlyA: ["X"], both: ["dog", "snail"], onlyB: ["car", "cloud"], neither: ["rock"] } },
    { q: "Study the set-ups. Both dishes were placed on the same table. After 5 days, only the seeds in A had germinated. What is the best conclusion?", o: ["Seeds do not need air to germinate", "The seeds in B were non-living", "Seeds need light to germinate", "Seeds need water to germinate and grow"], a: 3, why: "The only difference between A and B is water, so the result shows seeds need water to germinate. Both dishes had the same light, so light cannot be the reason.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["10 green bean seeds", "Moist cotton wool", "On a table"] }, { label: "B", icon: "dish", lines: ["10 green bean seeds", "Dry cotton wool", "On a table"] }] } },
    { q: "The bar graph shows the area of a patch of mould on a slice of bread. Between which two days did the area of the mould increase the most?", o: ["Day 1 and Day 2", "Day 3 and Day 4", "The increase was the same every day", "Day 2 and Day 3"], a: 3, why: "The area went up by 3 (Day 1 to 2), by 6 (Day 2 to 3) and by 3 (Day 3 to 4). The biggest increase was between Day 2 and Day 3.", lvl: 2, fig: { type: "bar", title: "Mould on a slice of bread", xl: "Day", yl: "Area of mould (square cm)", bars: [["Day 1", 2], ["Day 2", 5], ["Day 3", 11], ["Day 4", 14]] } },
    { q: "Study the classification chart of living things. Which is correctly matched?", o: ["P: mushroom", "Q: bread mould", "R: bacteria", "S: fern"], a: 1, why: "Bread mould cannot make its own food, can be seen without a microscope and reproduces by spores, so it is at Q. A mushroom is also at Q, bacteria are at S (need a microscope) and a fern is at P.", lvl: 2, fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "P", no: { q: "Seen without microscope?", yes: { q: "Reproduces by spores?", yes: "Q", no: "R" }, no: "S" } } } },
    { q: "Which observation is the best evidence that a green bean seed is a living thing?", o: ["It is hard and brown, with a smooth seed coat", "It can roll across a table when it is pushed gently", "It germinates and grows into a young plant when watered", "It is found inside a pod that grew on a bean plant"], a: 2, why: "Growing into a young plant shows the seed can grow, a characteristic of living things. Rolling is moving, which even non-living things like marbles can do.", lvl: 2 },
    { q: "Which of the following shows a living thing responding to a change in temperature?", o: ["A boy shivers in a cold air-conditioned room", "A candle melts on a hot day", "Butter becomes soft outside the fridge", "A puddle dries up in the sun"], a: 0, why: "The boy is living and his body reacts to the cold. Candles, butter and puddles are non-living; they change, but they do not respond like living things.", lvl: 2 },
    { q: "Study the Venn diagram. Which of these could be X?", o: ["Bread mould", "Balsam", "Frog", "Pine tree"], a: 0, why: "X reproduces by spores but is not a plant, so it is a fungus like bread mould. Balsam and pine trees are plants that reproduce by seeds, and a frog does not reproduce by spores.", lvl: 2, fig: { type: "venn", a: "Plants", b: "Reproduce by spores", onlyA: ["hibiscus", "rice"], both: ["fern", "moss"], onlyB: ["mushroom", "X"], neither: ["cat"] } },
    { q: "Study the line graph of the height of a balsam plant. By how much did the plant grow from Day 4 to Day 8?", o: ["3 cm", "6 cm", "9 cm", "12 cm"], a: 1, why: "On Day 4 the plant was 3 cm tall and on Day 8 it was 9 cm tall, so it grew 9 − 3 = 6 cm. 9 cm is its height on Day 8, not how much it grew.", lvl: 2, fig: { type: "line", title: "Balsam plant", xl: "Day", yl: "Height of plant (cm)", pts: [["0", 0], ["2", 1], ["4", 3], ["6", 6], ["8", 9], ["10", 11]] } },
    { q: "Lina placed a small object X in a jar of liquid and measured its length every 2 days. She concluded that X is a living thing. Study the graph. Which is the best comment on her conclusion?", o: ["She is correct because X grew longer, and only living things can get bigger over time", "She is correct because X got bigger every 2 days, which shows X is growing steadily", "The graph is not enough; she must also show X has the other characteristics, e.g. reproducing", "She is wrong because living things never get bigger when they are kept in a jar of liquid"], a: 2, why: "Non-living things such as crystals can also get bigger. To be sure X is living, Lina must show ALL the characteristics, such as reproducing and responding to changes.", lvl: 3, fig: { type: "line", title: "Object X", xl: "Day", yl: "Length of X (mm)", pts: [["1", 2], ["3", 4], ["5", 6], ["7", 8]] } },
    { q: "Wei Ming wants to find out if seeds need water to germinate. Which two set-ups should he compare?", o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ ONLY in water, so it is a fair test. C and D differ in water AND temperature, so we cannot tell which one caused the result.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist cotton wool", "In the light", "25 °C"] }, { label: "B", icon: "dish", lines: ["Dry cotton wool", "In the light", "25 °C"] }, { label: "C", icon: "dish", lines: ["Moist cotton wool", "In the dark", "25 °C"] }, { label: "D", icon: "dish", lines: ["Dry cotton wool", "In the dark", "10 °C"] }] } },
    { q: "Study the Venn diagram. Which statement is correct?", o: ["Everything that moves from place to place is living", "All the things in the ‘Grows’ circle are living things", "The mango tree is placed wrongly because trees can move from place to place", "A dried leaf should be placed in the overlap"], a: 1, why: "Only living things grow, so everything in the ‘Grows’ circle is living. The car and cloud move but are non-living, and a dried leaf cannot grow or move by itself.", lvl: 3, fig: { type: "venn", a: "Grows", b: "Moves place to place", onlyA: ["mango tree", "moss"], both: ["cat", "snail"], onlyB: ["car", "cloud"], neither: ["rock", "glass"] } },
    { q: "Which of the following show living things reproducing?\nA: Spores from a mushroom grow into new mushrooms.\nB: A seedling grows taller.\nC: A cat gives birth to kittens.\nD: A caterpillar turns into a pupa.", o: ["A only", "C only", "A and C only", "A, C and D only"], a: 2, why: "A and C both produce NEW young of their own kind. B and D show the same living thing growing and changing as it gets older.", lvl: 3 },
    { q: "Study the classification chart. Which pair is correctly placed?", o: ["K: bread mould, M: paper", "J: mushroom, N: glass", "L: bacteria, M: stone", "J: moss, N: leather belt"], a: 0, why: "Bread mould is living, cannot make its own food and can be seen without a microscope (K). Paper comes from trees, so it was once living (M). A mushroom goes to K, a stone to N and a leather belt to M.", lvl: 3, fig: { type: "flow", root: "Things", node: { q: "Is it living?", yes: { q: "Makes its own food?", yes: "J", no: { q: "Seen without microscope?", yes: "K", no: "L" } }, no: { q: "Was it once living?", yes: "M", no: "N" } } } },
    { q: "Ravi counted the mushrooms on a fallen log at Pulau Ubin every week. Study the bar graph. Which characteristic of living things does it MOST likely show?", o: ["Mushrooms grow", "Mushrooms need water", "Mushrooms respond to changes", "Mushrooms reproduce"], a: 3, why: "The NUMBER of mushrooms increased, so new mushrooms of the same kind were produced: they reproduce. Growing would show the SAME mushroom getting bigger, which a count does not measure.", lvl: 3, fig: { type: "bar", title: "Mushrooms on a log", xl: "Week", yl: "Number of mushrooms", bars: [["Week 1", 2], ["Week 2", 5], ["Week 3", 9]] } },
    { q: "Which statement about a seed is NOT true?", o: ["It contains stored food for the young plant", "It contains a young plant inside its seed coat", "It needs water, air and warmth to germinate", "It is non-living until it starts to germinate"], a: 3, why: "A seed is living all the time, even before it germinates. It contains a young plant and stored food, and it needs water to germinate.", lvl: 3 },
    { q: "Sally left a sweet potato in her kitchen. After two weeks, small shoots and roots grew out of it. Which statement is correct?", o: ["It is non-living because it has been dug out of the soil", "It is living because it can grow shoots and roots", "It is a seed because it grew shoots", "It was never living"], a: 1, why: "Growing shoots and roots shows the sweet potato can grow, so it is a living part of a plant. It is not a seed, and being dug up does not make it non-living.", lvl: 3 }
  ],
  tf: [
    { s: "A seed uses the food stored inside it when it germinates.", a: true, why: "A seed cannot make food until it has green leaves, so it uses its stored food." },
    { s: "A shoot that grows taller and bends towards a window shows both growing and responding to changes.", a: true, why: "Getting taller is growth; bending towards light is a response." },
    { s: "Moulds are plants because they grow on food.", a: false, why: "Moulds are fungi; they cannot make their own food." },
    { s: "A tadpole changing into a frog is an example of reproduction.", a: false, why: "It is growth: the same animal changes as it gets older." },
    { s: "Cork and cotton wool were once living.", a: true, why: "Cork comes from the bark of a tree and cotton wool comes from the cotton plant." },
    { s: "Yeast is a type of bacteria.", a: false, why: "Yeast is a fungus." },
    { s: "To show that something is living, it is enough to show one characteristic of living things.", a: false, why: "A living thing must show ALL the characteristics; a robot can respond but is non-living." },
    { s: "More mushrooms appearing on a log over a few weeks shows that mushrooms reproduce.", a: true, why: "New mushrooms of the same kind are being produced." }
  ],
  oe: [
    { q: "Study the set-ups. After 5 days, the seeds in A germinated but the seeds in B did not.\n(a) Which characteristic of living things do the seeds in A show?\n(b) What does the experiment show that seeds need to germinate?\n(c) Why were both dishes placed on the same table?", marks: 3, kw: [["grow"], ["water"], ["fair", "only one", "one thing", "same conditions"]], model: "(a) The seeds in A grow. (b) Seeds need water to germinate. (c) So that it is a fair test: only one thing (water) is changed and all the other conditions are kept the same.", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Green bean seeds", "Moist cotton wool", "On a table"] }, { label: "B", icon: "dish", lines: ["Green bean seeds", "Dry cotton wool", "On a table"] }] } },
    { q: "Study the line graph of the height of a green bean plant.\n(a) What was the height of the plant on Day 6?\n(b) Which characteristic of living things does the graph show?\n(c) Is this graph alone enough to show that the green bean plant is living? Explain.", marks: 3, kw: [["6 cm", "6cm", "six"], ["grow"], ["not enough", "only one", "reproduce"]], model: "(a) The plant was 6 cm tall on Day 6. (b) It shows that living things grow. (c) No, it is not enough. The graph shows only one characteristic. We must also show that the plant can reproduce, responds to changes and needs air, food and water.", fig: { type: "line", title: "Green bean plant", xl: "Day", yl: "Height of plant (cm)", pts: [["0", 0], ["3", 2], ["6", 6], ["9", 11], ["12", 15]] } },
    { q: "Jun put 2 guppies in a tank. The bar graph shows the number of guppies in the tank each month.\n(a) Which characteristic of living things does the graph show?\n(b) Between which two months did the number of guppies increase the most?", marks: 2, kw: [["reproduc", "young", "give birth", "gave birth"], ["month 2 and month 3", "2 and 3", "month 3"]], model: "(a) It shows that living things reproduce: the guppies gave birth to young of their own kind. (b) Between Month 2 and Month 3.", fig: { type: "bar", title: "Guppies in a tank", xl: "Month", yl: "Number of guppies", bars: [["Month 1", 2], ["Month 2", 10], ["Month 3", 25]] } },
    { q: "Study the classification chart of living things.\n(a) Which group of living things does A represent?\n(b) Which group of living things does C represent?\n(c) Which group of living things does D represent?", marks: 3, kw: [["plant"], ["animal"], ["bacteri"]], model: "(a) A represents plants, because they make their own food. (b) C represents animals. (c) D represents bacteria, because they can only be seen with a microscope.", fig: { type: "flow", root: "Living things", node: { q: "Seen without microscope?", yes: { q: "Makes its own food?", yes: "A", no: { q: "Reproduces by spores?", yes: "B", no: "C" } }, no: "D" } } },
    { q: "Study the Venn diagram.\n(a) Explain why the car is outside the ‘Living’ circle even though it can move.\n(b) Explain why the fern is not in the ‘Can move’ circle.", marks: 2, kw: [["cannot grow", "cannot reproduce", "not grow", "not reproduce", "can't grow", "can't reproduce", "doesn't grow", "doesn't reproduce"], ["one place", "does not move", "cannot move", "stays", "not move from place"]], model: "(a) The car cannot grow or reproduce, so it is non-living. (b) The fern stays in one place; it does not move from place to place.", fig: { type: "venn", a: "Living", b: "Can move", onlyA: ["fern", "mango tree"], both: ["dog", "snail"], onlyB: ["car", "cloud"], neither: ["rock"] } },
    { q: "Nurul kept a pet hamster and wrote down some observations. State the characteristic of living things shown by each observation.\n(a) Its mass increased from 30 g to 90 g in two months.\n(b) It gave birth to 5 young hamsters.\n(c) It ran into its little house when there was a loud noise.", marks: 3, kw: [["grow"], ["reproduc"], ["respond"]], model: "(a) Living things grow. (b) Living things reproduce (produce young of their own kind). (c) Living things respond to changes." },
    { q: "Sally left a sweet potato in her kitchen. After two weeks, shoots and roots grew out of it.\n(a) Which characteristic of living things does this show?\n(b) Her brother bought a packet of sweet potato chips. Are the chips living, once living or never living?\n(c) Explain your answer to (b).", marks: 3, kw: [["grow"], ["once living", "once-living", "was living"], ["from a plant", "part of a plant", "came from", "made from", "cannot grow"]], model: "(a) Living things grow. (b) The chips are non-living but once living. (c) They were made from a sweet potato, which was part of a living plant, but the chips cannot grow or reproduce now." },
    { q: "Tom hung a string in a jar of sugar water. After 2 weeks, a sugar crystal on the string had become bigger. Tom said the crystal is living because it grows. Do you agree? Explain.", marks: 2, kw: [["disagree", "do not agree", "don’t agree", "not agree", "non-living", "not living"], ["reproduce", "all the characteristics", "all characteristics", "respond", "only one"]], model: "No, I do not agree. The crystal is non-living. It only gets bigger by adding sugar on the outside; it cannot reproduce or respond to changes, so it does not have all the characteristics of living things." }
  ],
  doc: [
    { q: "Explain why a seed is a living thing.", marks: 2, answers: ["It is small and brown and it is inside a fruit.", "Because it can grow.", "It can germinate and grow into a new plant when it is given water, air and warmth."], best: 2, why: "Answer 3 names the characteristic (grow) AND what it grows into (a new plant) under the right conditions. Answer 2 says ‘grow’ but is too short: it does not say what the seed grows into. Answer 1 only describes what the seed looks like, which does not show it is living." },
    { q: "A cloud moves across the sky. Explain why a cloud is non-living.", marks: 2, answers: ["It cannot grow or reproduce young of its own kind. Moving is not a characteristic of all living things.", "Because it is in the sky.", "Because it does not move by itself."], best: 0, why: "Answer 1 gives characteristics of living things that the cloud does NOT have and explains why moving is not a test. Answer 2 gives a place, not a reason. Answer 3 uses moving as the test, which is wrong because plants are living but do not move from place to place." },
    { q: "Explain why a mushroom is not a plant.", marks: 2, answers: ["Mushrooms are fungi because they reproduce by spores.", "Mushrooms are fungi because they cannot make their own food.", "Mushrooms do not have flowers."], best: 1, why: "Answer 2 gives the group AND the key reason: plants make their own food but mushrooms cannot. Answer 1 is not a good reason, because ferns and mosses also reproduce by spores and they ARE plants. Answer 3 is wrong for the same reason: ferns and mosses have no flowers either." },
    { q: "The shoot of a plant on a windowsill bent towards the window. Which characteristic of living things does this show? Explain.", marks: 2, answers: ["It shows that living things grow.", "It shows that living things respond to changes: the shoot bent towards the light coming from the window.", "The plant moved to the window."], best: 1, why: "Answer 2 names the correct characteristic (respond to changes) and links it to the evidence (bending towards the light). Answer 1 names the wrong characteristic: bending is a response, not growth. Answer 3 is wrong because the plant stays in one place; only the shoot bends." },
    { q: "Lina says that a wooden ruler is living because it came from a tree. Is she right? Explain.", marks: 2, answers: ["She is right because wood comes from trees and trees are living.", "She is wrong because the ruler is hard.", "She is wrong. The ruler was once living, but now it cannot grow, reproduce or respond to changes, so it is non-living."], best: 2, why: "Answer 3 says she is wrong, uses the term ‘once living’ AND gives characteristics the ruler no longer has. Answer 1 mixes up ‘once living’ with ‘living’. Answer 2 gives the right verdict but a wrong reason: being hard has nothing to do with being living." }
  ]
};
