window.BANKU = window.BANKU || {};
BANKU["living"] = {
  glossary: [
    { t: "Characteristics of living things", d: "What all living things have in common: they need air, food and water, they grow, they reproduce and they respond to changes." },
    { t: "Non-living thing", d: "A thing that does not have all the characteristics of living things. It does not grow, reproduce or respond to changes like living things do." },
    { t: "Once-living thing", d: "A non-living thing that came from, or was part of, a living thing, e.g. paper, a dried leaf or a leather belt. It cannot grow or reproduce now." },
    { t: "Never-living thing", d: "A thing that was never part of a living thing and did not come from one, e.g. rock, sand, glass, metal and plastic." },
    { t: "Growth", d: "An increase in the size, height or mass of the same living thing, together with the changes it goes through as it gets older." },
    { t: "Reproduction", d: "The way living things produce young of their own kind, so that their kind does not die out." },
    { t: "Response", d: "The way a living thing reacts to a change around it, such as touch, light, sound or a change in temperature." },
    { t: "Fungi", d: "A group of living things, such as mushrooms, moulds and yeast, that cannot make their own food and reproduce by spores." },
    { t: "Bacteria", d: "A group of very tiny living things that cannot be seen with the naked eye, only with a microscope. Some are useful, e.g. in making yoghurt." },
    { t: "Spores", d: "Tiny parts released by fungi, ferns and mosses. Each spore can grow into a new living thing of the same kind." },
    { t: "Germination", d: "The process in which a seed starts to grow into a young plant when it is given water, air and warmth." },
    { t: "Classification key", d: "A chart of yes/no questions about characteristics. Answering each question in turn sorts things into groups step by step." }
  ],
  lessons: [
    {
      h: "Reading a growth graph: height or change?",
      concept: "Growth graphs cost marks when pupils read a value when the question asks for a change. The HEIGHT on a day is read straight off the graph. The CHANGE (how much it grew) is the later value minus the earlier value. ‘Grew the most’ means the biggest change between two readings, where the line is steepest.",
      example: {
        q: "Hui Min measured the height of a chilli padi plant on her HDB corridor every week.\n(a) What was the height of the plant in Week 3? [1]\n(b) By how much did the plant grow from Week 1 to Week 3? [1]\n(c) Between which two weeks did the plant grow the most? [1]",
        fig: { type: "line", title: "Chilli padi plant", xl: "Week", yl: "Height of plant (cm)", pts: [["0", 2], ["1", 4], ["2", 7], ["3", 11], ["4", 13]] },
        marks: 3,
        think: [
          "Step 1: For (a), read straight up from Week 3 to the line, then across to the axis: 11 cm. This is a value, so no subtraction is needed.",
          "Step 2: For (b), ‘by how much did it grow’ asks for a change: 11 cm − 4 cm = 7 cm. Writing 11 cm here is the most common mistake.",
          "Step 3: For (c), work out every weekly change: 2, 3, 4 and 2 cm. The biggest is 4 cm, between Week 2 and Week 3, where the line is steepest.",
          "Step 4: Always write the unit (cm) and name BOTH weeks in (c)."
        ],
        answer: "(a) 11 cm. (b) It grew 11 − 4 = 7 cm. (c) Between Week 2 and Week 3 (it grew 4 cm)."
      },
      tip: "Value = read it off. Change = later value − earlier value. ‘The most’ = the biggest change, where the line is steepest.",
      try: { q: "Study the bar graph of the mass of a kitten. By how much did its mass increase from Week 2 to Week 4?", fig: { type: "bar", title: "Mass of a kitten", xl: "Week", yl: "Mass of kitten (g)", bars: [["Week 1", 300], ["Week 2", 450], ["Week 3", 650], ["Week 4", 800]] }, o: ["800 g", "150 g", "200 g", "350 g"], a: 3, why: "800 g − 450 g = 350 g. 800 g is the mass in Week 4, not the increase; 150 g and 200 g are the increases for single weeks only." }
    },
    {
      h: "Drawing a conclusion the results support",
      concept: "A conclusion must come from the results and must not say more than the results show. Look for the pattern in the table, then check every row before writing ‘the more…, the more…’. Words like ‘all’, ‘always’, ‘never’ and ‘kills’ are usually wrong unless every result agrees.",
      example: {
        q: "Ali placed 20 green bean seeds on cotton wool in each of four dishes. He added a different amount of water to each dish and kept all the dishes in the same place. The table shows his results after 5 days.\n(a) Do seeds need water to germinate? Use the results to explain. [1]\n(b) Ali concluded, “The more water given, the more seeds germinate.” Explain why the results do not fully support his conclusion. [1]",
        tbl: [["Amount of water added (ml)", "Number of seeds that germinated (out of 20)"], ["0", "0"], ["5", "12"], ["10", "18"], ["20", "18"]],
        marks: 2,
        think: [
          "Step 1: For (a), compare 0 ml with the rest: no seeds germinated without water, but seeds germinated when water was added. So seeds need water.",
          "Step 2: Quote the data as evidence. A claim with numbers scores better than a claim alone.",
          "Step 3: For (b), check EVERY row of Ali’s pattern: 0 to 5 to 10 ml gave more seeds, but 10 ml and 20 ml both gave 18 seeds.",
          "Step 4: So ‘the more water, the more seeds’ is true only up to 10 ml. Point to the rows that break the pattern."
        ],
        answer: "(a) Yes. No seeds germinated when no water was added, but 12 to 18 seeds germinated when water was added. (b) When the water was increased from 10 ml to 20 ml, the number of seeds that germinated stayed the same (18), so more water did not always give more germinated seeds."
      },
      tip: "Before writing ‘the more…, the more…’, check every row. Quote the numbers that support (or break) the pattern.",
      try: { q: "Ravi put 10 woodlice in the middle of a tray. One half was damp and the other half was dry. He counted the woodlice in each half after 10 minutes and did this three times. Which conclusion is supported by his results?", tbl: [["Try", "Woodlice in damp half", "Woodlice in dry half"], ["1", "9", "1"], ["2", "8", "2"], ["3", "10", "0"]], o: ["Woodlice prefer damp places to dry places", "Woodlice cannot stay alive in dry places", "All woodlice always move to damp places", "Woodlice need bright light to stay alive"], a: 0, why: "Most woodlice went to the damp half every time, so they prefer damp places. Some woodlice were in the dry half in Tries 1 and 2, so ‘all … always’ is wrong. The tray did not test survival or light." }
    }
  ],
  flash: [
    { f: "Grow or reproduce? A tadpole becomes a frog.", b: "Grow. The same animal changes as it gets older. No new young are produced." },
    { f: "Grow or reproduce? More mushrooms appear on a log each week.", b: "Reproduce. New mushrooms of the same kind are produced. Growth would be the SAME mushroom getting bigger." },
    { f: "Is a dead cockroach once living or never living?", b: "Once living. It was living before it died, but now it cannot grow, reproduce or respond to changes." },
    { f: "Why does food kept in a fridge stay fresh for longer?", b: "Bacteria and fungi such as mould grow and reproduce more slowly at a low temperature, so the food spoils more slowly." },
    { f: "Name three kinds of fungi", b: "Mushrooms, moulds (e.g. bread mould) and yeast." },
    { f: "Which plants reproduce by spores?", b: "Ferns and mosses. They are still plants because they can make their own food." },
    { f: "Name one useful fungus and one use of bacteria", b: "Yeast (a fungus) is used to make bread. Some bacteria are used to make yoghurt." },
    { f: "What does a seed need to germinate?", b: "Water, air and warmth. It uses the food stored inside it to start growing." },
    { f: "What makes an experiment a fair test?", b: "Only one variable is changed at a time. All the other variables are kept the same, so we know what caused the result." },
    { f: "How can you make the results of an experiment more reliable?", b: "Use more living things in each set-up (e.g. 10 seeds, not 1) and repeat the experiment a few times." },
    { f: "How can you show that a plant grows?", b: "Measure its height at regular times, e.g. every 2 days, and record it in a table or graph. The height increases over time." },
    { f: "Do non-living things ever change?", b: "Yes, e.g. ice melts and iron rusts. But they do not grow, reproduce or respond to changes like living things." }
  ],
  mcq: [
    { q: "Which of these is a living thing?", o: ["Rust on an iron gate", "A burning candle", "Mould on an old orange", "A growing sugar crystal"], a: 2, why: "Mould is a fungus: it needs air, food and water, grows and reproduces by spores. Rust, a candle flame and a sugar crystal can change or get bigger, but they cannot reproduce.", lvl: 1 },
    { q: "Yeast is used by bakeries to make bread dough rise. Yeast is a type of ______.", o: ["bacterium", "fungus", "plant", "animal"], a: 1, why: "Yeast is a fungus, like mushrooms and moulds. It cannot make its own food, so it is not a plant, and it is not a bacterium.", lvl: 1 },
    { q: "Which of these was once living?", o: ["Pebble", "Glass bead", "Steel nail", "Seashell"], a: 3, why: "A seashell was part of a living animal (a sea snail or clam). Pebbles, glass and steel were never part of a living thing.", lvl: 1 },
    { q: "Ferns and mosses are plants that reproduce by ______.", o: ["spores", "seeds", "giving birth", "laying eggs"], a: 0, why: "Ferns and mosses do not have flowers or seeds; they reproduce by spores. They are still plants because they make their own food.", lvl: 1 },
    { q: "Study the classification chart. Which of these would be placed at C?", fig: { type: "flow", root: "Living things", node: { q: "Reproduces by spores?", yes: { q: "Makes its own food?", yes: "A", no: "B" }, no: { q: "Seen without microscope?", yes: "C", no: "D" } } }, o: ["Mushroom", "Moss", "Fern", "Cat"], a: 3, why: "A cat does not reproduce by spores and can be seen without a microscope, so it ends at C. Moss and ferns reproduce by spores and make their own food (A); a mushroom reproduces by spores but cannot make its own food (B).", lvl: 2 },
    { q: "Which observation does NOT show that Mei’s pet cat is a living thing?", o: ["It gave birth to four kittens", "It has soft fur all over its body", "Its mass increased as it got older", "It ran away when a dog barked"], a: 1, why: "Having fur is not a characteristic of living things (a toy cat can have fur too). Giving birth shows reproduction, gaining mass shows growth and running away shows responding to changes.", lvl: 2 },
    { q: "In Singapore’s humid weather, mould often grows on leather shoes kept in a cupboard. Which is the best way to stop mould from growing on them?", o: ["Keep them in a dark cupboard", "Wrap them in a damp cloth", "Keep them in a dry, airy place", "Keep them in a closed plastic bag"], a: 2, why: "Mould is a living thing that needs water (moisture) to grow, so a dry place slows it down. Mould grows well in the dark, and a damp cloth or a closed bag keeps the shoes moist.", lvl: 2 },
    { q: "Mrs Lim’s HDB flat has these things.\nA: a rattan chair\nB: a ceramic bowl\nC: a woollen sweater\nD: a duster made of chicken feathers\nWhich of these were made from things that were once living?", o: ["A, C and D only", "A and C only", "B and D only", "A, B, C and D"], a: 0, why: "Rattan comes from a plant, wool comes from sheep and feathers come from chickens, so A, C and D were once living. A ceramic bowl is made from clay, which was never living.", lvl: 2 },
    { q: "Study the set-ups. Each slice of bread was left for 5 days. Which slice is most likely to have the largest patch of mould?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Moist bread", "In a cupboard", "28 °C"] }, { label: "B", icon: "plate", lines: ["Dry bread", "In a cupboard", "28 °C"] }, { label: "C", icon: "plate", lines: ["Moist bread", "In a fridge", "5 °C"] }] }, o: ["Slice A", "Slice B", "Slice C", "All will be the same"], a: 0, why: "Mould needs water and grows well when it is warm. Slice A is both moist and warm. Slice B is dry, and slice C is cold, so mould grows slowly or not at all on them.", lvl: 2 },
    { q: "Study the Venn diagram of some living things. Which of these could be X?", fig: { type: "venn", a: "Moves place to place", b: "Reproduces by spores", onlyA: ["cat", "sparrow"], both: [], onlyB: ["mushroom", "fern"], neither: ["X"] }, o: ["Moss", "Grasshopper", "Rambutan tree", "Bread mould"], a: 2, why: "X stays in one place and does not reproduce by spores. A rambutan tree reproduces by seeds and does not move from place to place. Moss and bread mould reproduce by spores, and a grasshopper moves.", lvl: 2 },
    { q: "Which statements about fungi and bacteria are correct?\nA: Yeast, a fungus, is used to make bread.\nB: Some bacteria are used to make yoghurt.\nC: All bacteria cause diseases.\nD: The mushrooms we eat are fungi.", o: ["A and B only", "B and C only", "A, B and C only", "A, B and D only"], a: 3, why: "A, B and D are true. C is wrong: some bacteria cause diseases, but others are useful, such as those used to make yoghurt.", lvl: 2 },
    { q: "Jun wants to find out if light affects the growth of balsam seedlings. Study the table. Which two pots should he compare?", tbl: [["Pot", "Place", "Water each day", "Soil"], ["P", "Near a window", "50 ml", "Garden soil"], ["Q", "Near a window", "100 ml", "Garden soil"], ["R", "Dark cupboard", "50 ml", "Garden soil"], ["S", "Dark cupboard", "100 ml", "Sand"]], o: ["P and Q", "P and R", "Q and S", "R and S"], a: 1, why: "P and R differ ONLY in light (window or dark cupboard). P and Q differ in water; Q and S, and R and S, differ in more than one thing, so they are not fair.", lvl: 3 },
    { q: "Mrs Goh keeps milk in the fridge. A scientist counted the bacteria in two glasses of the same milk, one in a warm kitchen and one in a fridge.\nA: The bacteria in both glasses reproduced.\nB: Bacteria reproduce faster in warm milk than in cold milk.\nC: The cold fridge killed all the bacteria.\nWhich statements are supported by the results?", tbl: [["Hour", "Bacteria in kitchen milk (30 °C)", "Bacteria in fridge milk (5 °C)"], ["0", "100", "100"], ["2", "400", "110"], ["4", "1600", "120"], ["6", "6400", "130"]], o: ["A and B only", "A only", "B and C only", "A, B and C"], a: 0, why: "The number of bacteria went up in BOTH glasses, so both reproduced (A), but far faster in the warm kitchen (B). C is wrong: the bacteria in the fridge still increased slowly, so they were not killed.", lvl: 3 },
    { q: "Which of these is NOT good evidence that a green bean seed is a living thing?", o: ["It germinates and grows into a seedling", "It swells up when it is soaked in water", "It uses its stored food to grow a root", "Its seedling grows into a plant with seeds"], a: 1, why: "A sponge or a dried bean curd stick also swells in water, so swelling does not show the seed is living. Germinating, growing a root and becoming a plant that makes seeds show growth and reproduction.", lvl: 3 },
    { q: "Study the classification chart. Which list contains ONLY things that belong at C?", fig: { type: "flow", root: "Things", node: { q: "Is it living now?", yes: { q: "Makes its own food?", yes: "A", no: "B" }, no: { q: "Came from a living thing?", yes: "C", no: "D" } } }, o: ["dry seed, paper, cotton cloth", "paper, sand, woollen scarf", "paper, cooked rice, seashell", "glass, woollen scarf, feather"], a: 2, why: "Paper (from trees), cooked rice (from rice plants) and a seashell (from a sea animal) are non-living but came from living things. A dry seed is still living, so it does not belong at C, and sand and glass never came from a living thing (D).", lvl: 3 },
    { q: "Study the line graph of the height of a rice seedling. Which statement is correct?", fig: { type: "line", title: "Rice seedling", xl: "Day", yl: "Height of seedling (cm)", pts: [["0", 1], ["2", 3], ["4", 6], ["6", 8], ["8", 9]] }, o: ["It was 9 cm tall on Day 6", "It grew the same amount every 2 days", "It grew 9 cm from Day 0 to Day 8", "It grew the most from Day 2 to Day 4"], a: 3, why: "The increases are 2, 3, 2 and 1 cm, so the biggest (3 cm) is from Day 2 to Day 4. It was 8 cm on Day 6, and it grew 9 − 1 = 8 cm in total, not 9 cm.", lvl: 3 },
    { q: "Study the classification chart. A mushroom and a cat both end at G. Which question could be added at G to separate them?", fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: { q: "Reproduces by spores?", yes: "E", no: "F" }, no: { q: "Seen without microscope?", yes: "G", no: "H" } } }, o: ["Does it reproduce by spores?", "Does it need air and water?", "Can it make its own food?", "Does it grow as it gets older?"], a: 0, why: "A mushroom reproduces by spores but a cat does not, so this question splits them. Both need air and water, both grow, and neither can make its own food, so the other questions give the same answer for both.", lvl: 3 },
    { q: "Study how some living things were grouped.\nP: Every member of Group A reproduces by spores.\nQ: Every member of Group B cannot make its own food.\nR: Every member of Group A stays in one place and does not move from place to place.\nWhich statements are correct?", tbl: [["Group A", "Group B"], ["fern", "cat"], ["moss", "rambutan tree"], ["mushroom", "otter"], ["bread mould", "hibiscus"]], o: ["P only", "P and Q only", "P and R only", "P, Q and R"], a: 2, why: "Ferns, mosses, mushrooms and bread mould all reproduce by spores (P) and none of them moves from place to place (R). Q is wrong because the rambutan tree and hibiscus in Group B are plants that make their own food.", lvl: 4 },
    { q: "Wei placed green bean seeds on moist cotton wool in three dishes and recorded the results after 5 days. He said, “Dish R shows that seeds cannot germinate at 25 °C.” Which is the best response?", tbl: [["Dish", "Temperature (°C)", "Number of seeds used", "Seeds that germinated"], ["P", "25", "10", "9"], ["Q", "5", "10", "0"], ["R", "25", "1", "0"]], o: ["He is right, as the seed in R did not germinate at all", "He is right, as seeds only germinate in cold places", "He is wrong, as seeds need light and not warmth", "He is wrong, as R had one seed but 9 of 10 grew in P"], a: 3, why: "Dish R used only one seed, which may have been damaged, so its result is not reliable. Dish P had the same temperature with 10 seeds, and 9 germinated. No seeds germinated in the cold dish Q, so seeds need warmth.", lvl: 4 },
    { q: "Ravi watched mushrooms on a fallen log at Pulau Ubin and measured the same mushroom, M, each week.\nA: The mushrooms reproduced.\nB: Mushroom M grew.\nC: Every mushroom on the log grew taller each week.\nWhich statements are supported by the table?", tbl: [["Week", "Number of mushrooms on the log", "Height of mushroom M (cm)"], ["1", "3", "2"], ["2", "7", "4"], ["3", "12", "5"]], o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "The number of mushrooms increased, so new ones were produced (A), and the same mushroom M got taller (B). Only M was measured, so the table says nothing about the height of every mushroom (C).", lvl: 4 }
  ],
  oe: [
    { q: "Aisha kept three slices of moist bread in different places for 5 days and measured the area of mould on each slice.\n(a) What was Aisha trying to find out? [1]\n(b) What is the relationship between the temperature and the area of mould? [1]\n(c) Use the results to explain why bread kept in a fridge stays fresh for longer. [1]\n(d) Mould is not a plant. To which group of living things does it belong? [1]", fig: { type: "bar", title: "Mould on bread after 5 days", xl: "Place (temperature)", yl: "Area of mould (square cm)", bars: [["Fridge (5 °C)", 1], ["Air-con room (22 °C)", 6], ["Kitchen (30 °C)", 12]] }, marks: 4, kw: [["temperature", "how warm", "warmth"], ["higher the temperature", "the warmer", "the hotter", "the higher"], ["slow", "less mould", "smaller", "low temperature"], ["fung"]], model: "(a) She wanted to find out if temperature affects how much mould grows on bread. (b) The higher the temperature, the larger the area of mould. (c) Mould grows more slowly at a low temperature, so less mould grows on bread in the cold fridge. (d) Fungi." },
    { q: "Siew Ling saw a green patch of moss on the wall of her HDB corridor and recorded her observations.\n(a) Which characteristic of living things is shown by the change in the area of the patch? [1]\n(b) Which characteristic of living things is shown by the new patches? [1]\n(c) Moss stays in one place and is green. To which group of living things does it belong? Give a reason. [2]", tbl: [["Week", "Area of first patch (square cm)", "Number of new patches nearby"], ["1", "4", "0"], ["2", "6", "1"], ["3", "9", "3"]], marks: 4, kw: [["grow"], ["reproduc", "young", "new moss"], ["plant"], ["own food", "make food", "makes food", "make their food"]], model: "(a) Living things grow. (b) Living things reproduce: new moss plants of its own kind were produced. (c) Moss is a plant, because it can make its own food." },
    { q: "At a beach in Sentosa, Mei picked up an empty seashell. Nearby, a hermit crab was living in another shell.\n(a) Is the empty seashell living, once living or never living? [1]\n(b) Explain your answer to (a). [1]\n(c) The hermit crab pulled into its shell when Mei touched it. Which characteristic of living things does this show? [1]", marks: 3, kw: [["once living", "once-living", "once alive", "was living", "was alive"], ["part of", "came from", "from a living", "from an animal", "from a sea"], ["respond", "react"]], model: "(a) It is once living. (b) The shell was part of a living sea animal, but it cannot grow or reproduce now. (c) Living things respond to changes." },
    { q: "Jun wanted to find out if seeds need light to germinate. Study his set-ups.\n(a) His teacher said this is not a fair test. Explain why. [1]\n(b) Suggest one change to set-up B to make it a fair test. [1]\n(c) After the change, the seeds in both A and B germinated. What can Jun conclude? [1]\n(d) Why did Jun use 10 seeds in each set-up instead of 1? [1]", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["10 green bean seeds", "Moist cotton wool", "Clear box (light)", "28 °C"] }, { label: "B", icon: "dish", lines: ["10 green bean seeds", "Dry cotton wool", "Black box (dark)", "28 °C"] }] }, marks: 4, x: 1, kw: [["two things", "2 things", "more than one", "two variables", "water and light", "light and water"], ["moist cotton wool", "wet cotton wool", "damp", "add water"], ["do not need light", "don't need light", "does not need light", "without light", "not need light", "germinate in the dark", "light is not needed"], ["reliable", "by chance", "damaged"]], model: "(a) He changed two things: the cotton wool in B was dry and B was also kept in the dark, so we cannot tell which one caused the result. (b) Use moist cotton wool in B, the same as in A. (c) Seeds do not need light to germinate. (d) To make the results more reliable, in case one seed is damaged and does not germinate by chance." }
  ],
  tf: [
    { s: "An empty seashell found on a beach was once living.", a: true, why: "It was part of a living sea animal, but it cannot grow or reproduce now." },
    { s: "Ferns are fungi because they reproduce by spores.", a: false, why: "Ferns are plants: they make their own food. Reproducing by spores does not make them fungi." },
    { s: "Mould grows more slowly on bread kept in a cold fridge than on bread kept in a warm cupboard.", a: true, why: "Mould grows faster when it is warm, which is why we keep bread and other food in the fridge." },
    { s: "A plant responds to changes only when it is touched.", a: false, why: "Plants also respond to other changes, e.g. a shoot bends towards light." },
    { s: "Seeds need light to germinate.", a: false, why: "Green bean seeds germinate in a dark cupboard. Seeds need water, air and warmth to germinate." },
    { s: "Wool and feathers came from living things.", a: true, why: "Wool comes from sheep and feathers come from birds, so they were once living." },
    { s: "A tree that has stopped getting taller is no longer a living thing.", a: false, why: "It still needs air, food and water, responds to changes and can reproduce, so it is still living." },
    { s: "Repeating an experiment a few times makes the results more reliable.", a: true, why: "If the results are similar each time, we can be surer they did not happen by chance." },
    { s: "Dried mushrooms sold in a packet at the supermarket are still living things.", a: false, why: "They were once living, but they can no longer grow or reproduce, so they are non-living now." },
    { s: "Yeast, which is used to make bread, is a living thing.", a: true, why: "Yeast is a fungus; it needs food, water and air, grows and reproduces." }
  ]
};
