window.BANKV = window.BANKV || {};
BANKV["living"] = {
  flash: [
    { f: "Define: a living thing", b: "A thing that needs air, food and water, grows, reproduces and responds to changes. It must show ALL these characteristics." },
    { f: "Define: reproduce", b: "To produce young of their own kind, e.g. a cat gives birth to kittens, a plant produces seeds, a mushroom produces spores." },
    { f: "Define: grow", b: "To increase in size and change as they get older, e.g. a seedling grows into a plant, a tadpole grows into a frog." },
    { f: "Define: respond to changes", b: "To react to changes around them, e.g. a snail withdraws into its shell when touched; a plant’s shoot bends towards light." },
    { f: "Why is a seed a living thing?", b: "It contains a young plant and stored food. When given water, air and warmth, it germinates and grows into a new plant." },
    { f: "Why is moving NOT a test for living things?", b: "Not all living things move from place to place (e.g. plants), and some non-living things move (e.g. cars, clouds)." },
    { f: "Once living vs never living", b: "Once living: came from or was part of a living thing (wood, paper, dried leaf, leather). Never living: rock, glass, metal, plastic, sand." },
    { f: "Name the four groups of living things", b: "Plants, animals, fungi and bacteria." },
    { f: "How are plants different from animals and fungi?", b: "Plants can make their own food. Animals and fungi cannot make their own food." },
    { f: "How do fungi such as mushrooms and moulds reproduce?", b: "Fungi reproduce by spores." },
    { f: "How can we see bacteria?", b: "Bacteria are so small that they can only be seen with a microscope. They are still living things." },
    { f: "Why is fire non-living even though it needs air?", b: "Fire does not have ALL the characteristics of living things, e.g. it cannot reproduce young of its own kind." },
    { f: "Do plants need food?", b: "Yes. All living things need food. Plants make their own food." },
    { f: "How does a mushroom on a rotting log get its food?", b: "It cannot make its own food. It gets food from the dead or decaying matter it grows on, e.g. the rotting log." },
    { f: "How do you use a classification key?", b: "Answer each yes/no question in turn and follow the arrow. A thing belongs to a group only if it fits EVERY question on the way." }
  ],
  mcq: [
    { q: "Which of the following can reproduce?", o: ["A paper crane", "A toy robot", "A hibiscus plant", "A rain cloud"], a: 2, why: "A hibiscus plant is living and produces seeds that grow into new hibiscus plants. The other three are non-living and cannot produce young of their own kind.", lvl: 1 },
    { q: "Which of these living things can make its own food?", o: ["Bread mould", "Fern", "Earthworm", "Mushroom"], a: 1, why: "A fern is a plant, and plants make their own food. Bread mould and mushrooms are fungi and an earthworm is an animal; none of them can make its own food.", lvl: 1 },
    { q: "At a pet shop, the guppies in a tank swim away and hide when a net is put into the water. Which characteristic of living things does this show?", o: ["They need air to stay alive", "They grow as they get older", "They reproduce young of their kind", "They respond to changes"], a: 3, why: "The guppies react to the net (a change around them), so they are responding to changes. Nothing here shows them growing or producing young.", lvl: 1 },
    { q: "Which of these was NEVER living?", o: ["Glass window", "Silk scarf", "Newspaper", "Bamboo pole"], a: 0, why: "Glass is made from sand, which was never living. Silk comes from silkworms, newspaper from trees and bamboo is a plant, so they were once living.", lvl: 1 },
    { q: "Priya counted the leaves on the money plant along her HDB corridor every week. Study the bar graph. Which statement is correct?", o: ["The plant had 15 leaves in Week 3", "The number of leaves increased by 9 from Week 1 to Week 4", "The plant stopped growing after Week 3", "The number of leaves increased by the same amount each week"], a: 1, why: "15 − 6 = 9. The plant had 11 leaves (not 15) in Week 3, it kept gaining leaves in Week 4, and the increases were 2, 3 and 4, not the same.", lvl: 2, fig: { type: "bar", title: "Leaves on Priya’s money plant", xl: "Week", yl: "Number of leaves", bars: [["Week 1", 6], ["Week 2", 8], ["Week 3", 11], ["Week 4", 15]] } },
    { q: "Study the Venn diagram of some living things at Gardens by the Bay. Which living thing could be placed at ‘?’?", o: ["Bracket fungus", "Rose", "Bread mould", "Staghorn fern"], a: 3, why: "‘?’ must make its own food AND reproduce by spores. A fern is a plant that reproduces by spores. Fungi reproduce by spores but cannot make their own food; a rose makes its own food but reproduces by seeds.", lvl: 2, fig: { type: "venn", a: "Makes its own food", b: "Reproduces by spores", onlyA: ["orchid", "sunflower"], both: ["?"], onlyB: ["mushroom"], neither: ["butterfly"] } },
    { q: "Which of the following is NOT a correct reason why the plastic flower on a table in the school canteen is non-living?", o: ["It does not move from place to place", "It does not need water to stay fresh", "It does not grow bigger over time", "It cannot produce seeds to reproduce"], a: 0, why: "Many living things, such as plants, do not move from place to place, so this is not a reason. Not needing water, not growing and not reproducing are all correct reasons.", lvl: 2 },
    { q: "At a hawker centre, Ali saw these things.\nA: wooden chopsticks\nB: a stainless steel spoon\nC: a paper napkin\nD: a glass cup\nWhich of these were once living?", o: ["A and B only", "B and D only", "A and C only", "A, C and D only"], a: 2, why: "Wood and paper come from trees, so they were once living. Steel and glass were never living.", lvl: 2 },
    { q: "Study the classification chart. Mr Tan has a durian tree in his garden and is wearing a cotton T-shirt. Where should the durian tree and the cotton T-shirt be placed?", o: ["Durian tree at A, T-shirt at C", "Durian tree at A, T-shirt at D", "Durian tree at B, T-shirt at C", "Durian tree at B, T-shirt at D"], a: 0, why: "The durian tree is living and makes its own food, so it is at A. Cotton comes from the cotton plant, so the T-shirt is non-living but once living, which is C.", lvl: 2, fig: { type: "flow", root: "Things", node: { q: "Is it living?", yes: { q: "Makes its own food?", yes: "A", no: "B" }, no: { q: "Was it once living?", yes: "C", no: "D" } } } },
    { q: "A family of otters lives near Bishan Park. Study the line graph of the number of otters in the family. Which statement is correct?", o: ["Each otter grew bigger every year", "The number increased because otters reproduce", "The number did not change from 2023 to 2024", "The otters stopped reproducing after 2023"], a: 1, why: "The number of otters rose from 2 to 12 because the otters produced young. The graph shows numbers, not size, and the number rose from 5 to 9 between 2023 and 2024.", lvl: 2, fig: { type: "line", title: "Otters in one family", xl: "Year", yl: "Number of otters", pts: [["2021", 2], ["2022", 5], ["2023", 5], ["2024", 9], ["2025", 12]] } },
    { q: "Which of these is the best reason why a mushroom is NOT a plant?", o: ["It grows on dead logs", "It has no flowers", "It reproduces by spores", "It cannot make its own food"], a: 3, why: "Plants make their own food; a mushroom cannot, so it is a fungus. Ferns and mosses also have no flowers and reproduce by spores, yet they are plants.", lvl: 2 },
    { q: "Mrs Lee wants to find out if mould needs light to grow on bread. Study the set-ups. Which two set-ups should she compare?", o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "A and B both use moist bread at 28 °C and differ only in light (clear box or black box). A and C differ in moisture, B and D differ in temperature, and C and D differ in more than one thing, so they are not fair.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Moist bread", "Clear box (light)", "28 °C"] }, { label: "B", icon: "box", lines: ["Moist bread", "Black box (dark)", "28 °C"] }, { label: "C", icon: "box", lines: ["Dry bread", "Clear box (light)", "28 °C"] }, { label: "D", icon: "box", lines: ["Moist bread", "Black box (dark)", "In a fridge (5 °C)"] }] } },
    { q: "Which statements about a mimosa (touch-me-not) plant are correct?\nA: It is living only because its leaves fold when touched.\nB: Its leaves folding when touched shows that it responds to changes.\nC: It needs air, food and water.\nD: It cannot respond to changes because it cannot move from place to place.", o: ["A and B only", "B and C only", "A, B and C only", "B, C and D only"], a: 1, why: "B and C are true. A is wrong because one characteristic alone does not make a thing living; it must show ALL of them. D is wrong because plants respond to changes without moving from place to place.", lvl: 3 },
    { q: "The table shows some characteristics of things P, Q, R and S. Which of these could be bacteria, a fern and a rock, in that order?", o: ["R, P and S", "Q, P and S", "R, Q and S", "S, P and R"], a: 0, why: "Bacteria are living, cannot be seen without a microscope (R). A fern is living and makes its own food (P). A rock does not need water or grow (S). Q could be an animal or a fungus.", lvl: 3, tbl: [["Thing", "Needs water", "Grows", "Makes its own food", "Seen without a microscope"], ["P", "Yes", "Yes", "Yes", "Yes"], ["Q", "Yes", "Yes", "No", "Yes"], ["R", "Yes", "Yes", "No", "No"], ["S", "No", "No", "No", "Yes"]] },
    { q: "Study the classification chart. Which statement is correct?", o: ["A rock belongs to Y", "A mushroom belongs to W", "A fern belongs to X", "An otter belongs to Y"], a: 3, why: "An otter is living and does not reproduce by spores, so it is at Y. A rock is non-living (Z), a mushroom reproduces by spores but cannot make its own food (X), and a fern makes its own food (W).", lvl: 3, fig: { type: "flow", root: "Things", node: { q: "Is it living?", yes: { q: "Reproduces by spores?", yes: { q: "Makes its own food?", yes: "W", no: "X" }, no: "Y" }, no: "Z" } } },
    { q: "Which pair contains two living things that BOTH cannot make their own food?", o: ["Bacteria and fern", "Moss and yeast", "Mushroom and earthworm", "Hibiscus and bread mould"], a: 2, why: "A mushroom is a fungus and an earthworm is an animal; neither makes its own food. Fern, moss and hibiscus are plants, which make their own food.", lvl: 3 },
    { q: "Study the Venn diagram. Which of these could be X?", o: ["Seashell", "Paper bag", "Plastic cup", "Sand castle"], a: 1, why: "X must be once living AND made by people. A paper bag is made by people from wood. A seashell was once living but not made by people; a plastic cup and a sand castle are made by people but were never living.", lvl: 3, fig: { type: "venn", a: "Was once living", b: "Made by people", onlyA: ["dried leaf"], both: ["X"], onlyB: ["glass bottle"], neither: ["rock"] } },
    { q: "Jia Hui observed three things, P, Q and R, for 4 weeks. Based ONLY on the table, which conclusion is correct?", o: ["P is non-living because it did not change", "R is non-living because it did not reproduce", "R is living because it became longer", "Q showed growth, reproduction and response"], a: 3, why: "Q became longer, new ones like it appeared and it moved when touched. P could be a dry seed, and R could be a young plant or a growing crystal, so we cannot decide about P or R from this data.", lvl: 4, tbl: [["Thing", "Length in Week 1 (cm)", "Length in Week 4 (cm)", "New ones like it appeared?", "Moved when touched?"], ["P", "3", "3", "No", "No"], ["Q", "2", "6", "Yes", "Yes"], ["R", "1", "5", "No", "No"]] },
    { q: "Mei said, “Something that does not move, does not eat and does not change for many months must be non-living.” Which of these is the best example to show that Mei is WRONG?", o: ["A rock in a garden", "A plastic flower", "A dry seed in a packet", "A dead leaf"], a: 2, why: "A dry seed shows none of these changes for months, yet it is living: it uses stored food and grows into a new plant when given water, air and warmth. The rock, plastic flower and dead leaf really are non-living, so they agree with Mei.", lvl: 4 },
    { q: "Darren measured the mass of his pet hamster every week. Study the graph. He said, “My hamster stopped growing in Week 4 because its mass went down.” Which is the best response?", o: ["Wrong, its mass rose overall, so it is still growing", "Right, a fall in mass shows it has stopped growing", "Right, it lost mass because it gave birth in Week 4", "Wrong, its mass went up steadily every single week"], a: 0, why: "The mass rose from 30 g to 66 g, higher than ever by Week 5. A small drop for one week (e.g. it ate less) does not mean it stopped growing. The mass did fall once, so ‘every single week’ is wrong.", lvl: 4, fig: { type: "line", title: "Mass of Darren’s hamster", xl: "Week", yl: "Mass (g)", pts: [["1", 30], ["2", 42], ["3", 55], ["4", 52], ["5", 66]] } }
  ],
  oe: [
    { q: "Study the Venn diagram of some things P, Q, R, S and T.\n(a) Name a living thing that could be Q.\n(b) R is a living thing. To which group of living things does R belong?\n(c) S is a cat and T is a rock. Explain why both S and T are outside the two circles, even though only the cat is living.", marks: 3, kw: [["fern", "moss"], ["fung", "mushroom", "mould"], ["spore", "own food"]], model: "(a) A fern. (b) R belongs to the fungi group. (c) Both the cat and the rock cannot make their own food, and they do not reproduce by spores.", fig: { type: "venn", a: "Makes its own food", b: "Reproduces by spores", onlyA: ["P"], both: ["Q"], onlyB: ["R"], neither: ["S", "T"] } },
    { q: "Wei wanted to find out if mould grows faster on moist bread than on dry bread. Study his set-ups.\n(a) His teacher said this is not a fair test. Explain why.\n(b) Suggest one change to set-up B to make it a fair test.\n(c) After 5 days, the patch of mould on the bread in A became bigger each day. Which characteristic of living things does this show?", marks: 3, kw: [["temperature", "fridge", "warm", "cold", "two things", "two variables", "more than one"], ["28", "out of the fridge", "same temperature", "same place", "room temperature", "same as a"], ["grow"]], model: "(a) Wei changed two things: the bread in B was dry and it was also kept in a fridge at a lower temperature. (b) Keep set-up B in a box at 28 °C, the same as A. (c) It shows that the mould grows.", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["White bread", "Sprinkled with water", "In a box at 28 °C"] }, { label: "B", icon: "plate", lines: ["White bread", "Kept dry", "In a fridge at 5 °C"] }] } },
    { q: "Mr Lim grows a durian tree in his garden.\n(a) The tree produces durians with seeds that can grow into new durian trees. Which characteristic of living things does this show?\n(b) The shoots of a young durian plant next to a wall bend towards the open side where there is more light. Which characteristic of living things does this show?\n(c) Years later, the tree was cut down and its wood was made into a bench. Is the bench living, once living or never living? Explain.", marks: 3, kw: [["reproduc", "young of its own kind", "offspring"], ["respond", "react"], ["once living", "once alive", "was living", "was alive", "came from a living", "from a tree", "from the tree", "from the durian tree"]], model: "(a) The tree reproduces. (b) The plant responds to changes. (c) The bench is once living, because the wood came from the durian tree, which was living. The bench itself cannot grow or reproduce now." },
    { q: "Study the classification chart.\n(a) Suggest a suitable question for Question X.\n(b) To which group of living things do the fern and the durian tree belong?\n(c) Bread mould is to be added to the chart. Next to which living thing should it be placed?\n(d) Ali said the mushroom and the otter should be in the same group because both cannot make their own food and both can be seen without a microscope. State one difference between them that explains why the chart separates them.", marks: 4, x: 1, kw: [["microscope"], ["plant"], ["mushroom"], ["spore", "fung", "animal"]], model: "(a) Can it only be seen with a microscope? (b) They are plants. (c) It should be placed next to the mushroom. (d) The mushroom reproduces by spores, but the otter does not; the mushroom is a fungus while the otter is an animal.", fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "fern, durian tree", no: { q: "Question X", yes: "bacteria", no: { q: "Reproduces by spores?", yes: "mushroom", no: "otter" } } } } }
  ],
  tf: [
    { s: "A mushroom cannot make its own food, so it gets food from what it grows on.", a: true, why: "e.g. a mushroom on a rotting log gets its food from the dead, decaying wood." },
    { s: "Paper was once living, so it can still grow if it is kept moist.", a: false, why: "Paper came from trees, but it is non-living now; it cannot grow or reproduce." },
    { s: "A thing does not need to move from place to place to be living.", a: true, why: "Plants stay in one place, yet they grow, reproduce and respond to changes." },
    { s: "Bacteria are a type of very tiny animal.", a: false, why: "Bacteria are a separate group of living things, not animals." },
    { s: "A rain tree, a guppy, a mushroom and bacteria can all reproduce.", a: true, why: "All living things reproduce: plants by seeds, guppies give birth, fungi by spores, bacteria by making more bacteria." },
    { s: "A dead leaf blown along by the wind is responding to a change.", a: false, why: "A dead leaf is non-living; the wind moves it, it does not respond." },
    { s: "Some fungi and some bacteria are useful to people.", a: true, why: "Yeast (a fungus) is used to make bread, and some bacteria are used to make yoghurt." },
    { s: "Every living thing can make its own food.", a: false, why: "Plants make their own food, but animals and fungi cannot. They must get food from other things." },
    { s: "Mould can grow on bread, fruit and leather shoes kept in a damp cupboard.", a: true, why: "Mould is a fungus that grows on food and other materials in damp, warm places." },
    { s: "A plant no longer needs water once it is fully grown.", a: false, why: "All living things need water for as long as they are alive." }
  ],
  sort: [
    { title: "Sort these observations by the characteristic of living things they show", groups: ["Grows", "Reproduces", "Responds to changes"], items: [["A rambutan seedling becomes 10 cm taller", 0], ["A kitten’s mass doubles in 2 months", 0], ["A tadpole changes into a frog", 0], ["A cat gives birth to kittens", 1], ["Spores from a mushroom grow into new mushrooms", 1], ["A hen lays eggs that hatch into chicks", 1], ["A snail withdraws into its shell when touched", 2], ["A boy pulls his hand away from a hot pan", 2], ["A shoot bends towards a window", 2], ["A cat runs away when a dog barks", 2]] }
  ]
};
