window.BANKZ = window.BANKZ || {};
BANKZ["living"] = {
  lessons: [
    {
      h: "Naming the characteristic used to classify",
      concept: "Many questions show two groups and ask, ‘What characteristic was used to classify these things?’ The answer must be ONE characteristic that is true for EVERY member of one group and NOT true for any member of the other group. State it clearly, such as ‘whether they reproduce by spores or by seeds’, not a vague word like ‘type’ or ‘size’. Check the members one by one before you write.",
      example: {
        q: "Study how some living things were classified.\n(a) What characteristic was used to classify them into Group X and Group Y?\n(b) In which group should a bird’s nest fern be placed?",
        tbl: [["Group X", "Group Y"], ["fern", "hibiscus"], ["moss", "rice plant"], ["mushroom", "mango tree"], ["bread mould", "chilli padi plant"]],
        marks: 2,
        think: [
          "Step 1: Look for what ALL of Group X share. Ferns, moss, mushrooms and bread mould all reproduce by spores.",
          "Step 2: Check that NO member of Group Y shares it. Hibiscus, rice, mango and chilli padi all reproduce by seeds. (Group X also has no flowers while Group Y has, so ‘whether they bear flowers’ is also accepted.)",
          "Step 3: Reject answers that fail even one member. ‘Cannot make its own food’ fails, because the fern and moss in Group X DO make their own food.",
          "Step 4: A bird’s nest fern is a fern, so it reproduces by spores and belongs in Group X."
        ],
        answer: "(a) Whether they reproduce by spores or by seeds: Group X reproduce by spores and Group Y reproduce by seeds. (b) Group X."
      },
      tip: "Test your characteristic on EVERY member of BOTH groups. One member that does not fit means it is the wrong characteristic.",
      try: { q: "Study the two groups. Which characteristic was used to classify them?", tbl: [["Group P", "Group Q"], ["mushroom", "hibiscus"], ["cat", "fern"], ["bread mould", "moss"], ["grasshopper", "rice plant"]], o: ["Whether they reproduce by spores", "Whether they can make their own food", "Whether they can move from place to place", "Whether they can be seen without a microscope"], a: 1, why: "Every member of Q is a plant that makes its own food, and nothing in P can. ‘Spores’ fails because the mushroom and mould in P and the fern and moss in Q all use spores. ‘Moving’ fails because mushrooms and mould in P do not move, and all eight can be seen without a microscope." }
    }
  ],
  mcq: [
    { q: "The iron gate at the void deck of an HDB block has a patch of rust. The patch becomes bigger every week. Is the rust a living thing?", o: ["Yes, because the patch grows bigger every week", "Yes, because it spreads from place to place on the gate", "No, because it cannot reproduce or respond to changes", "No, because it is only found on things made of metal"], a: 2, why: "Misconception: ‘getting bigger means growing’. The rust only gets bigger as more of the iron turns into rust; it cannot reproduce young of its own kind or respond to changes, so it is non-living. Being found on metal is not the reason.", lvl: 1 },
    { q: "An otter at Marina Bay gave birth to four pups. Which characteristic of living things does this show?", o: ["Living things grow", "Living things need food", "Living things respond to changes", "Living things reproduce"], a: 3, why: "Giving birth to young of its own kind is reproducing. The pups getting bigger later would show growth.", lvl: 1 },
    { q: "Study the classification chart. Which of these could be W?", fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "Plants", no: { q: "Seen without microscope?", yes: "W", no: "Bacteria" } } }, o: ["Mushroom", "Moss", "Fern", "Pandan plant"], a: 0, why: "W cannot make its own food and can be seen without a microscope, so it could be a fungus such as a mushroom (or an animal). Moss, ferns and pandan are plants because they make their own food.", lvl: 1 },
    { q: "Siti made three statements about plants.\nA: Plants need food.\nB: Plants need air.\nC: Plants move from place to place to look for water.\nWhich statements are correct?", o: ["A only", "B only", "A and B only", "B and C only"], a: 2, why: "Misconception: ‘plants do not need food because they make it’. Plants DO need food; they make their own food. Like all living things, plants also need air. Plants stay in one place, so C is wrong.", lvl: 2 },
    { q: "Kaya is made from these ingredients.\nA: coconut milk\nB: eggs\nC: sugar (made from sugarcane)\nD: salt\nWhich of these ingredients came from living things?", o: ["A and B only", "A and C only", "A, B and C only", "A, B, C and D"], a: 2, why: "Coconut milk comes from the coconut tree, eggs come from hens and sugar is made from the sugarcane plant. Salt comes from sea water or rocks and was never living.", lvl: 2 },
    { q: "Ali compared a real money plant and a plastic money plant for 4 weeks and recorded his results in the table. Which row of his table is WRONG?", tbl: [["Characteristic", "Real money plant", "Plastic money plant"], ["Needs water", "Yes", "No"], ["Becomes taller", "Yes", "No"], ["Can produce young plants", "Yes", "No"], ["Needs air", "No", "No"]], o: ["Needs water", "Becomes taller", "Can produce young plants", "Needs air"], a: 3, why: "Misconception: ‘plants do not need air’. The real money plant is living, so it needs air as well as food and water. The plastic plant was never living, so all its answers are ‘No’.", lvl: 2 },
    { q: "Study the line graph of the mass of a puppy. Between which two months did its mass increase the most?", fig: { type: "line", title: "Mass of a puppy", xl: "Month", yl: "Mass of puppy (kg)", pts: [["0", 1], ["1", 2], ["2", 5], ["3", 7], ["4", 8]] }, o: ["Month 0 and Month 1", "Month 1 and Month 2", "Month 2 and Month 3", "Month 3 and Month 4"], a: 1, why: "The increases are 1 kg, 3 kg, 2 kg and 1 kg. The biggest increase (3 kg) is between Month 1 and Month 2, where the line is steepest.", lvl: 2 },
    { q: "Which of these shows a living thing responding to a change?", o: ["A sunflower seedling grows two new leaves in a week", "A snail lays a group of eggs in the damp soil", "A sugar crystal becomes bigger in a jar of sugar water", "A woodlouse hurries into a dark gap when its log is lifted"], a: 3, why: "The woodlouse reacts to a change (light and dryness when the log is lifted). The seedling shows growth, the snail shows reproduction and the crystal is non-living.", lvl: 2 },
    { q: "A cockroach was sprayed with insect spray and died. How should the dead cockroach be classified?", o: ["Non-living, but it was once living", "Non-living, and it was never living", "Living, because it still has all its body parts", "Living, because it can still be moved around"], a: 0, why: "Misconception: ‘dead things were never living’. The cockroach was living before, so it is once living. Now it cannot grow, reproduce or respond, so it is non-living.", lvl: 2 },
    { q: "Aini placed 20 green bean seeds on moist cotton wool at each of four temperatures. The table shows her results after 5 days.\nA: Seeds need warmth to germinate.\nB: The most seeds germinated at 25 °C.\nC: The higher the temperature, the more seeds germinated.\nWhich conclusions are supported by the results?", tbl: [["Temperature (°C)", "Number of seeds that germinated (out of 20)"], ["5", "0"], ["15", "9"], ["25", "18"], ["35", "14"]], o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "No seeds germinated at 5 °C, so seeds need warmth (A). 18 is the largest number, at 25 °C (B). C is wrong: fewer seeds germinated at 35 °C than at 25 °C.", lvl: 3 },
    { q: "Zhi Hao wants to find out if the amount of water given each day affects the growth of a balsam seedling. Study his set-ups.\nA: the size of the pot\nB: the amount of water given each day\nC: the place where each pot is kept\nWhich of these should he keep the SAME?", fig: { type: "setups", items: [{ label: "P", icon: "pot", lines: ["Balsam seedling", "50 ml water a day", "Near a window"] }, { label: "Q", icon: "pot", lines: ["Balsam seedling", "100 ml water a day", "Near a window"] }] }, o: ["A only", "B only", "A and C only", "A, B and C"], a: 2, why: "The amount of water (B) is the one thing he changes. Everything else, such as the size of the pot and the place, must be kept the same so that it is a fair test.", lvl: 3 },
    { q: "A mushroom is growing on a fallen tree trunk at Bukit Timah. How does the mushroom get the food it needs?", o: ["It takes in food from the tree trunk", "It makes its own food using sunlight", "It does not need any food at all", "It takes in food from the air"], a: 0, why: "Misconception: ‘fungi make their own food like plants’ or ‘fungi do not need food’. Mushrooms are fungi: they cannot make their own food, so they take in food from what they grow on, such as a dead tree trunk.", lvl: 3 },
    { q: "Scientists found an unknown thing Z in a pond and recorded three observations.\nA: Z became bigger over two weeks.\nB: Z produced small Zs, which later became bigger.\nC: Z moved when it was poked with a stick.\nWhich observations could ALSO be shown by a non-living thing?", o: ["A only", "C only", "A and C only", "A, B and C"], a: 2, why: "A non-living thing can get bigger (a crystal or a snowball) and can move when pushed (a ball), so A and C are not good evidence. Only living things reproduce young of their own kind (B).", lvl: 3 },
    { q: "Study the classification chart of some plants. Which question could be Question Q?", fig: { type: "flow", root: "Plants", node: { q: "Question Q", yes: "fern, moss", no: "hibiscus, rice" } }, o: ["Does it make its own food?", "Does it reproduce by spores?", "Does it have green leaves?", "Does it need water to live?"], a: 1, why: "Ferns and mosses reproduce by spores, while hibiscus and rice reproduce by seeds. All four plants make their own food, have green leaves and need water, so those questions cannot separate them.", lvl: 3 },
    { q: "Study the set-ups. Water that has been boiled and cooled has very little air in it, and the oil stops air from entering. After 5 days, only the seeds in P germinated. What does this show?", fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["10 green bean seeds", "Moist cotton wool", "Open jar", "25 °C"] }, { label: "Q", icon: "jar", lines: ["10 green bean seeds", "In boiled cooled water", "Layer of oil on top", "25 °C"] }] }, o: ["Seeds need water to germinate", "Seeds need light to germinate", "Seeds need warmth to germinate", "Seeds need air to germinate"], a: 3, why: "The seeds in Q had plenty of water and the same temperature, but very little air, so they did not germinate. This shows seeds need air. Both jars were at 25 °C, so warmth was not the difference.", lvl: 3 },
    { q: "Siti measured the height of a balsam plant every 2 days. She went on holiday after Day 6 and nobody watered the plant. Study the graph. Which is the best explanation for the results from Day 6 to Day 10?", fig: { type: "line", title: "Balsam plant", xl: "Day", yl: "Height of plant (cm)", pts: [["0", 2], ["2", 4], ["4", 7], ["6", 10], ["8", 10], ["10", 10]] }, o: ["The plant stopped growing because it did not get the water it needs", "The plant became non-living on Day 6 because it reached its full height", "The plant had reproduced on Day 6, so it did not need to grow any taller", "The plant stopped growing because it could no longer respond to light"], a: 0, why: "Living things need water to grow. Without water after Day 6, the height stayed the same. The graph does not show the plant reproducing, and a plant does not become non-living just because it stops getting taller.", lvl: 3 },
    { q: "Study the Venn diagram drawn by a pupil. She made one mistake. Which statement is correct?", fig: { type: "venn", a: "Came from living thing", b: "Is living now", onlyA: ["paper", "cooked rice"], both: ["kitten", "green bean seed"], onlyB: ["fire"], neither: ["glass", "sand"] }, o: ["Fire should be in the overlap, because it needs air and can spread and grow", "Cooked rice should be in the overlap, because rice comes from a living plant", "The green bean seed should be in ‘Came from living thing’ only, as it is dry", "Fire should be outside both circles; nothing can go in ‘Is living now’ only"], a: 3, why: "Fire is non-living and did not come from a living thing, so it belongs outside both circles. Every living thing came from a living thing of its own kind (a kitten from a cat, a seed from a plant), so the ‘Is living now’ only region must stay empty. Cooked rice cannot grow, and a dry seed is still living.", lvl: 4 },
    { q: "Mei saw a white, fuzzy patch on a slice of bread. Her brother said it was just dust. Which set of observations is the BEST evidence that the patch is a living thing?", o: ["The patch is soft and white, and the bread under it smells bad", "The patch gets bigger each day, and new patches appear nearby", "The patch moves slightly when Mei blows gently on the bread", "The patch is on food, and dust is not usually found on food"], a: 1, why: "Getting bigger each day shows growth and new patches appearing shows reproduction: two characteristics that dust cannot show. Moving when blown, or smelling bad, could happen to non-living things too.", lvl: 4 },
    { q: "Ken used the set-ups to find out if seeds need warmth to germinate. His teacher said his results may not be reliable.\nA: Use 10 seeds in each dish instead of 1.\nB: Repeat the experiment a few more times.\nC: Put more cotton wool in dish P than in dish Q.\nWhich changes would make his results more reliable?", fig: { type: "setups", items: [{ label: "P", icon: "dish", lines: ["1 green bean seed", "Moist cotton wool", "25 °C"] }, { label: "Q", icon: "dish", lines: ["1 green bean seed", "Moist cotton wool", "5 °C"] }] }, o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "With only one seed, it might not germinate because it was damaged, not because of the temperature. Using more seeds (A) and repeating the experiment (B) make the results more reliable. C would make the test unfair, because two things would then be different.", lvl: 4 },
    { q: "Mr Tan counted the bacteria in drops of milk taken from the same glass every hour, using a microscope. Study the graph.\nA: The bacteria reproduced.\nB: Each bacterium grew to twice its size every hour.\nC: The number of bacteria doubled every hour.\nWhich statements are supported by the graph?", fig: { type: "line", title: "Bacteria in milk", xl: "Hour", yl: "Number of bacteria", pts: [["0", 10], ["1", 20], ["2", 40], ["3", 80]] }, o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Misconception: ‘more of them means they grew’. The NUMBER of bacteria went up, so new bacteria were produced: they reproduced (A), and the number doubled from 10 to 20 to 40 to 80 (C). The graph counts bacteria; it does not measure their size, so B is not supported.", lvl: 4 }
  ],
  oe: [
    { q: "Raju placed 10 earthworms in the middle of a tray. One half of the tray was covered with black paper (dark). The other half was under a cool LED light (bright). He counted the earthworms in each half after 10 minutes and did this 3 times.\n(a) Which characteristic of living things does the experiment show?\n(b) What can Raju conclude from his results?\n(c) Why did he do the experiment 3 times?", tbl: [["Try", "Earthworms in dark half", "Earthworms in bright half"], ["1", "9", "1"], ["2", "8", "2"], ["3", "10", "0"]], marks: 3, kw: [["respond", "react"], ["dark", "away from light", "away from the light", "away from bright"], ["reliable", "accurate", "sure", "by chance", "luck"]], model: "(a) Living things respond to changes. (b) Earthworms move to the dark, away from bright light: most of the earthworms were in the dark half each time. (c) To make sure the results are reliable and did not happen by chance.", x: 1 },
    { q: "Zhi Hao grew four balsam seedlings, each 2 cm tall at the start, in the same type of pot and soil near the same window. He gave each seedling a different amount of water every day. The bar graph shows their heights after 3 weeks.\n(a) What was Zhi Hao trying to find out?\n(b) What is the relationship between the amount of water and the height of the seedling?\n(c) State one thing he kept the same to make it a fair test.\n(d) What does the seedling given 0 ml of water show about living things?", fig: { type: "bar", title: "Balsam seedlings after 3 weeks", xl: "Water given each day", yl: "Height of seedling (cm)", bars: [["0 ml", 2], ["30 ml", 9], ["60 ml", 14], ["90 ml", 17]] }, marks: 4, kw: [["amount of water", "how much water", "volume of water"], ["taller", "the higher", "greater the height", "grew more", "grows more"], ["pot", "soil", "window", "place", "light", "starting height", "same type"], ["need water", "needs water", "water to grow", "water to live", "water to survive"]], model: "(a) He wanted to find out if the amount of water given each day affects the growth (height) of the balsam seedlings. (b) The more water given each day, the taller the seedling grew. (c) The type of pot and soil (or the place near the window). (d) Living things need water to grow: the seedling given no water did not grow taller at all.", x: 1 },
    { q: "Mei placed 20 red bean seeds on moist cotton wool in each of four dishes. She kept each dish at a different temperature and counted the seeds that germinated after 5 days.\n(a) What was Mei trying to find out?\n(b) At which temperature did the most seeds germinate?\n(c) Why did she use the same number of seeds and the same amount of water in each dish?", fig: { type: "bar", title: "Red bean seeds", xl: "Temperature", yl: "Number of seeds germinated", bars: [["10 °C", 2], ["20 °C", 11], ["30 °C", 19], ["40 °C", 6]] }, marks: 3, kw: [["temperature", "warm"], ["30"], ["fair", "only one", "one thing"]], model: "(a) She wanted to find out if temperature affects the number of seeds that germinate. (b) 30 °C. (c) So that it is a fair test: only the temperature is changed and everything else is kept the same." },
    { q: "Lina observed three things, K, L and M, for 4 weeks and recorded her observations in the table.\n(a) Which thing, K, L or M, is a living thing?\n(b) Explain why K is non-living even though it became bigger.\n(c) Name a non-living thing that could behave like M.", tbl: [["Thing", "Became bigger", "Produced young of its own kind", "Moved when touched", "Needed food and water"], ["K", "Yes", "No", "No", "No"], ["L", "Yes", "Yes", "Yes", "Yes"], ["M", "No", "No", "Yes", "No"]], marks: 3, kw: [["l"], ["reproduce", "young", "respond"], ["robot", "toy", "machine", "ball", "car", "swing", "door"]], model: "(a) L. (b) K cannot reproduce young of its own kind and it does not respond to changes, so it does not have all the characteristics of living things; it could be a crystal. (c) A robot toy that moves when it is touched." },
    { q: "Study how some living things were grouped.\n(a) What characteristic was used to put them into Group X and Group Y?\n(b) In which group should bread mould be placed?\n(c) State one characteristic that the mushroom does NOT share with the other members of Group X.", tbl: [["Group X", "Group Y"], ["fern", "hibiscus"], ["moss", "mango tree"], ["mushroom", "rice plant"]], marks: 3, kw: [["spores", "seeds", "flower"], ["x"], ["own food", "make food", "fungi", "fungus", "leaves", "green"]], model: "(a) Whether they reproduce by spores or by seeds: Group X reproduce by spores and Group Y by seeds. (b) Group X. (c) Whether it can make its own food: the fern and moss make their own food but the mushroom cannot, because it is a fungus." },
    { q: "Siti said, “A plant does not need food because it never eats anything.”\n(a) Is Siti correct? Explain.\n(b) How does a plant get the food it needs?\n(c) How does a mushroom growing on a dead log get the food it needs?", marks: 3, kw: [["not correct", "incorrect", "wrong", "disagree", "need food", "needs food"], ["own food", "make food", "makes food"], ["takes in food", "take in food", "absorb", "from the log", "from what it grows", "feeds on", "from the dead"]], model: "(a) No, she is not correct. A plant needs food, like all living things. (b) A plant makes its own food. (c) The mushroom cannot make its own food, so it takes in food from what it grows on, the dead log." }
  ],
  tf: [
    { s: "Plants need food even though they can make their own food.", a: true, why: "All living things need food; plants make theirs instead of eating." },
    { s: "A dead cockroach was never living.", a: false, why: "It was living before it died, so it is once living (and non-living now)." },
    { s: "Rust that spreads on an iron gate is growing like a living thing.", a: false, why: "Rust only gets bigger as more iron turns into rust; it cannot reproduce or respond, so it is non-living." },
    { s: "Seeds need air to germinate.", a: true, why: "Seeds covered by boiled, cooled water with a layer of oil on top (very little air) do not germinate." },
    { s: "Mushrooms make their own food using sunlight, just like plants.", a: false, why: "Mushrooms are fungi; they cannot make their own food and take in food from what they grow on." },
    { s: "An increase in the number of bacteria in milk shows that bacteria reproduce.", a: true, why: "More bacteria means new bacteria of the same kind were produced." },
    { s: "Non-living things never change.", a: false, why: "Non-living things can change, e.g. ice melts and iron rusts, but they do not grow, reproduce or respond like living things." },
    { s: "Using more seeds in each set-up makes the results of an experiment more reliable.", a: true, why: "With more seeds, one damaged seed will not change the conclusion." },
    { s: "Plants do not need air because they do not breathe like animals.", a: false, why: "All living things, including plants, need air." },
    { s: "Sugar, paper and cotton all came from living things.", a: true, why: "Sugar comes from sugarcane, paper from trees and cotton from the cotton plant." }
  ],
  doc: [
    { q: "A cockroach died after it was sprayed with insect spray. Is the dead cockroach once living or never living? Explain.", marks: 2, answers: ["Never living, because it is dead now and cannot move.", "Once living. It was a living thing before it died, but now it cannot grow, reproduce or respond to changes.", "Once living, because it is an insect."], best: 1, why: "Answer 2 gives the correct group AND both halves of the reason: it was living before, but it has lost the characteristics of living things now. Answer 1 mixes up ‘non-living’ with ‘never living’, and uses moving as the test. Answer 3 has the right group but the reason does not explain anything: a living insect is not ‘once living’." },
    { q: "Wei put 2 snails in an aquarium. A month later, there were 30 snails. Which characteristic of living things does this show? Explain.", marks: 2, answers: ["Living things reproduce: the snails produced young of their own kind, so the number of snails increased.", "Living things grow, because there are more snails in the aquarium now.", "The snails moved into the aquarium from outside."], best: 0, why: "Answer 1 names the correct characteristic and links it to the evidence (more snails of the same kind). Answer 2 names the wrong characteristic: growing is the SAME snail getting bigger, but a bigger NUMBER means reproduction. Answer 3 makes up a reason that is not in the question and names no characteristic." }
  ]
};
