window.BANKV = window.BANKV || {};
BANKV["magnets"] = {
  flash: [
    { f: "Define: magnetic material", b: "A material that is attracted by a magnet, such as iron, steel, nickel and cobalt." },
    { f: "Name the four magnetic materials", b: "Iron, steel, nickel and cobalt." },
    { f: "Name three metals that are NOT magnetic", b: "Aluminium, copper and brass (gold and silver are not magnetic either)." },
    { f: "Where is the magnetic force of a magnet strongest?", b: "At the poles – the two ends of a bar magnet." },
    { f: "What happens when like poles meet? Unlike poles?", b: "Like poles (N and N, or S and S) repel. Unlike poles (N and S) attract." },
    { f: "How does a freely suspended bar magnet come to rest?", b: "It points in the north-south direction, with its N pole pointing to the north." },
    { f: "The only sure test that an object is a magnet", b: "Repulsion: only a magnet can repel another magnet. Attraction also happens with magnetic materials that are not magnets." },
    { f: "Why can a magnet attract a paper clip through a sheet of paper?", b: "Magnetic force can pass through non-magnetic materials such as paper, plastic, glass and water." },
    { f: "Stroke method: the three rules", b: "Stroke with the same pole, in one direction only, and lift the magnet away from the bar at the end of each stroke." },
    { f: "Stroke method: which pole forms at the end where each stroke finishes?", b: "The opposite pole to the stroking pole (stroke with N and that end becomes S)." },
    { f: "What is an electromagnet?", b: "A coil of insulated wire wound around an iron nail that becomes a magnet when electric current flows through the coil." },
    { f: "Two ways to make an electromagnet stronger", b: "Use more coils of wire, or use more batteries." },
    { f: "Three ways a magnet can lose its magnetism", b: "Dropping it many times, heating it strongly or hammering it." },
    { f: "Two ways to compare the strength of magnets", b: "Count the number of paper clips each magnet attracts, or find the greatest distance from which each magnet attracts a paper clip." },
    { f: "Why does a ring magnet float above another ring magnet on a rod?", b: "The facing poles are like poles, so they repel and push the top ring up." }
  ],
  mcq: [
    { q: "A material that is attracted by a magnet is called a ______ material.", o: ["magnetic", "non-magnetic", "flexible", "waterproof"], a: 0, why: "Magnetic materials, such as iron, steel, nickel and cobalt, are attracted by magnets. Non-magnetic materials are not.", lvl: 1 },
    { q: "A coil of insulated wire is wound around an iron nail and connected to a battery. The nail becomes a magnet. What is this kind of magnet called?", o: ["Bar magnet", "Ring magnet", "Electromagnet", "Horseshoe magnet"], a: 2, why: "A nail that becomes a magnet when electric current flows through a coil of wire around it is an electromagnet.", lvl: 1 },
    { q: "A bar magnet hangs freely from a string. When it comes to rest, which part of it points to the north?", o: ["The S pole", "Either pole, at random", "The middle of the magnet", "The N pole"], a: 3, why: "A freely suspended magnet comes to rest pointing north-south, and it is always the N pole that points to the north.", lvl: 1 },
    { q: "At a hawker centre, many steel bottle caps have fallen under the tables. Which tool will pick them up most quickly?", o: ["A plastic dustpan", "A wet sponge", "A magnet on a long stick", "A wooden chopstick"], a: 2, why: "Steel is a magnetic material, so the magnet attracts the bottle caps. Plastic, sponge and wood do not attract steel.", lvl: 1 },
    { q: "Pairs of magnets are brought together with the ends shown in the table facing each other. Which pairs will repel?", o: ["A and D only", "B and C only", "A and B only", "C and D only"], a: 1, why: "B (S facing S) and C (N facing N) have like poles facing, so they repel. A and D have unlike poles facing, so they attract.", lvl: 2, tbl: [["Pair", "End of first magnet", "End of second magnet"], ["A", "N", "S"], ["B", "S", "S"], ["C", "N", "N"], ["D", "S", "N"]] },
    { q: "Ms Lee, a teacher at a school in Tampines, has a name badge with a small magnet on its back. She holds it in place with a second magnet on the inside of her blouse. Why does this work?", o: ["The magnetic force passes through the fabric.", "The fabric of the blouse is a magnetic material.", "Like poles of the two magnets are facing.", "The badge is lighter than the fabric."], a: 0, why: "Fabric is non-magnetic, and magnetic force passes through non-magnetic materials, so the two magnets attract through the blouse. Like poles would repel.", lvl: 2 },
    { q: "During a walk at MacRitchie Reservoir, Ravi uses a compass to find north. Why should he keep the compass away from his steel water bottle?", o: ["The steel attracts the needle, so it may not point north.", "The steel makes the needle lose all its magnetism forever.", "The steel repels both ends of the needle, so it keeps spinning.", "The steel blocks the magnetic force, so the needle cannot move."], a: 0, why: "The compass needle is a small magnet, so it is attracted to the steel bottle and may turn away from north. Steel is only attracted; it cannot repel the needle.", lvl: 2 },
    { q: "Four magnets were tested by hanging a chain of paper clips from each one. Study the graph. Which two magnets are about equally strong?", o: ["X and Z", "W and X", "W and Y", "Y and Z"], a: 2, why: "W and Y each held a chain of 4 paper clips, so they are about equally strong. Z, with 9 clips, is the strongest.", lvl: 2, fig: { type: "bar", xl: "Magnet", yl: "Number of paper clips in the chain", bars: [["W", 4], ["X", 7], ["Y", 4], ["Z", 9]] } },
    { q: "Study the classification chart. In which group should Mr Lim’s brass HDB flat key be placed?", o: ["P", "Q", "R", "It can be in P or Q"], a: 1, why: "Brass is a metal, but it is not attracted by a magnet, so the key goes to Q. Group P is for magnetic metals such as iron and steel.", lvl: 2, fig: { type: "flow", root: "Objects", node: { q: "Is it a metal?", yes: { q: "Attracted by a magnet?", yes: "P", no: "Q" }, no: "R" } } },
    { q: "Mei’s electromagnet has 20 coils of wire around an iron nail and uses 2 batteries. Which changes will make it attract FEWER paper clips?\nA: Remove one battery.\nB: Use only 10 coils of wire.\nC: Replace the iron nail with a wooden rod.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "Fewer batteries and fewer coils both make an electromagnet weaker. Wood is non-magnetic, so a wooden rod does not become a magnet like the iron nail does.", lvl: 2 },
    { q: "Two ring magnets are on a wooden rod as shown. B floats above A, and the top face of B is an N pole. What is the pole on the top face of A?", o: ["N", "S", "It cannot be told", "A has no pole on its top face"], a: 1, why: "B’s top face is N, so its bottom face is S. B floats, so like poles face each other, and A’s top face is also S.", lvl: 2, fig: { type: "rings", rings: [{ label: "A", top: "?" }, { label: "B", top: "N" }], gaps: [true] } },
    { q: "Siti wants to find out whether the distance between a magnet and a steel paper clip affects whether the clip is attracted. Which two set-ups should she compare?", o: ["B and C", "A and B", "A and C", "C and D"], a: 1, why: "A and B use the same magnet and the same steel clip; only the distance changes. B and C differ in the magnet, and the other pairs change more than one thing.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Magnet X", "Steel paper clip", "2 cm away"] }, { label: "B", icon: "plate", lines: ["Magnet X", "Steel paper clip", "5 cm away"] }, { label: "C", icon: "plate", lines: ["Magnet Y", "Steel paper clip", "5 cm away"] }, { label: "D", icon: "plate", lines: ["Magnet Y", "Nickel paper clip", "2 cm away"] }] } },
    { q: "Magnets A, B and C are placed in a row as shown. A repels B, and B attracts C. Which statement is NOT true?", o: ["The left end of B is an S pole.", "The right end of B is an N pole.", "The left end of C is an N pole.", "The right end of C is an N pole."], a: 2, why: "A’s right end is S and repels B, so B is S on the left and N on the right. B’s N attracts C, so C’s left end is S (not N) and its right end is N.", lvl: 3, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }, { label: "C", poles: "??" }], between: ["repel", "attract"] } },
    { q: "At a food factory in Jurong, breakfast cereal moves along a belt under a strong magnet before it is packed. Which of these could the magnet remove from the cereal?\nA: Small bits of steel wire\nB: Small bits of aluminium foil\nC: Tiny pieces of iron", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Steel and iron are magnetic, so they are pulled out. Misconception: that all metals are attracted – aluminium is a metal but it is non-magnetic.", lvl: 3 },
    { q: "A compass was placed on a table. Each magnet was moved slowly towards it, and the distance at which the needle first moved was recorded. Which shows the magnets in order from strongest to weakest?", o: ["Q, R, P", "R, P, Q", "P, Q, R", "P, R, Q"], a: 3, why: "A stronger magnet moves the needle from further away. P (12 cm) is the strongest, then R (9 cm), then Q (6 cm).", lvl: 3, tbl: [["Magnet", "Distance when needle first moved (cm)"], ["P", "12"], ["Q", "6"], ["R", "9"]] },
    { q: "Which of these statements are correct?\nA: A magnet can attract a steel paper clip through a sheet of aluminium foil.\nB: The magnetic force of a bar magnet is strongest in its middle.\nC: A ring magnet has both an N pole and an S pole.", o: ["A only", "B only", "A and B only", "A and C only"], a: 3, why: "Aluminium is non-magnetic, so the force passes through it (A), and every magnet has both poles (C). The force is strongest at the poles, not the middle, so B is wrong.", lvl: 3 },
    { q: "Four ring magnets are on a wooden rod as shown. A and B touch, C floats above B, and D touches C. The top face of D is an S pole. Which rings have an N pole on their top face?", o: ["A and B only", "B and D only", "A and C only", "C and D only"], a: 0, why: "D’s bottom is N, and D touches C, so C’s top is S and its bottom is N. C floats, so B’s top is N and its bottom is S. B touches A, so A’s top is N.", lvl: 3, fig: { type: "rings", rings: [{ label: "A", top: "?" }, { label: "B", top: "?" }, { label: "C", top: "?" }, { label: "D", top: "S" }], gaps: [false, true, false] } },
    { q: "Bar magnet M hangs freely and points north-south. Siti brings rod X near the end of M that points north, and that end swings away. She then brings rod Y near the same end, and it swings towards Y. Which conclusion is correct?", o: ["X is a magnet, but Y may or may not be a magnet.", "X and Y are both magnets with opposite poles.", "Y is a magnet, but X is made of iron or steel.", "X is a magnet, and Y is definitely not a magnet."], a: 0, why: "Only a magnet can repel a magnet, so X is a magnet. Y attracted M’s N pole, which happens with an S pole of a magnet OR with a magnetic material, so we cannot tell.", lvl: 4 },
    { q: "Compass 1 is placed at the left end of bar magnet M as shown, and the N pole of its needle turns to point at M. Compass 2 is then placed at the right end of M. Which is correct?", o: ["M’s left end is N, and compass 2’s N pole points at M.", "M’s left end is S, and compass 2’s N pole points at M.", "M’s left end is N, and compass 2’s S pole points at M.", "M’s left end is S, and compass 2’s S pole points at M."], a: 3, why: "The needle’s N pole is attracted to M’s left end, so that end is S (unlike poles attract). M’s right end is then N, so compass 2’s S pole points at it.", lvl: 4, fig: { type: "magnets", items: [{ label: "Compass 1", poles: "??" }, { label: "M", poles: "??" }], between: ["?"] } },
    { q: "Four magnets were tested by hanging a chain of paper clips from each. Study the results. Which conclusion is best supported?", o: ["Q and R are equally strong, as both held 4 clips.", "Q is weaker than P, as it held fewer clips.", "P and S are equally strong, and both are stronger than R.", "R is the weakest magnet of all four magnets tested."], a: 2, why: "P, R and S used the same small clips, so they can be compared: P and S (6) beat R (4). Q used large clips, so it cannot be compared fairly with the others.", lvl: 4, tbl: [["Magnet", "Paper clips used", "Longest chain held"], ["P", "small steel", "6"], ["Q", "large steel", "4"], ["R", "small steel", "4"], ["S", "small steel", "6"]] }
  ],
  oe: [
    { q: "At a school carnival, a magnetic fishing game has toy fish with a small clip on each one. The rod has a magnet at its end. Study the table. (a) Which fish can be caught with the rod? (b) Explain why fish 2 cannot be caught. (c) The magnet catches a fish only when it almost touches the clip. Suggest one change to the magnet so that fish can be caught from further away.", marks: 3, kw: [["1 and 3", "1 and fish 3", "3 and 1", "3 and fish 1", "steel and nickel", "nickel and steel"], ["not magnetic", "non-magnetic", "not a magnetic", "not attracted", "isn't magnetic"], ["stronger"]], model: "(a) Fish 1 and 3, because steel and nickel are magnetic materials. (b) Copper is a metal, but it is not a magnetic material, so the clip on fish 2 is not attracted by the magnet. (c) Use a stronger magnet, because a stronger magnet can attract the clip from a greater distance.", tbl: [["Fish", "Material of clip"], ["1", "steel"], ["2", "copper"], ["3", "nickel"], ["4", "aluminium"]] },
    { q: "Three ring magnets are on a wooden rod as shown. All three rings touch. The top face of A is an S pole. (a) What is the pole on the top face of C? Write the word in full. (b) Which ONE ring should be turned upside down so that only the top ring floats and A and B still touch? (c) Explain your answer to (b).", marks: 4, x: 1, kw: [["south"], ["c", "ring c", "c only", "only c", "turn c", "flip c", "magnet c"], ["like poles", "same pole", "same poles"], ["repel", "push"]], model: "(a) South. A’s top face is S, so B’s bottom face is N and its top face is S. C touches B, so C’s bottom face is N and its top face is S. (b) Ring C. (c) When C is turned over, its bottom face becomes S, which faces the S top face of B. These are like poles, and like poles repel, so C is pushed up and floats while A and B stay touching. (Turning B would make both B and C float.)", fig: { type: "rings", rings: [{ label: "A", top: "S" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [false, false] } },
    { q: "Jia Hui used the N pole of the same magnet to stroke two identical steel pins, P and Q, 30 times each. She stroked pin P from end X to end Y each time, lifting the magnet away after every stroke. She rubbed pin Q back and forth along its length. She then counted the paper clips each pin could pick up. (a) Which pin became a magnet? (b) Explain why the other pin did not become a magnet. (c) Which end of pin P became the S pole?", marks: 3, kw: [["pin p", "p"], ["opposite direction", "undo", "cancel", "both direction", "two direction", "different direction", "both ways", "two ways", "not in one direction", "not one direction"], ["y"]], model: "(a) Pin P, because it picked up 6 paper clips. (b) Pin Q was not stroked in one direction only. It was stroked in the opposite direction on every other stroke, so each stroke undid the one before and it did not become a magnet. (c) End Y, because the end where each stroke finishes becomes the opposite pole to the stroking pole (N).", tbl: [["Pin", "How it was stroked", "Number of paper clips picked up"], ["P", "One direction, magnet lifted away", "6"], ["Q", "Back and forth", "0"]] },
    { q: "Mr Tan’s HDB flat has a magnetic door stopper. A magnet is fixed to the wall, and a small plate is fixed to the door, so the door stays open. (a) Suggest a material for the plate. (b) Mr Tan replaced the plate with an aluminium one, and the door was no longer held open. Explain why. (c) After the magnet fell off the wall and onto the floor many times, it held the steel plate only weakly. Explain why.", marks: 3, kw: [["steel", "iron", "nickel", "cobalt"], ["not magnetic", "non-magnetic", "not a magnetic", "not attracted", "isn't magnetic"], ["lost", "lose", "magnetism"]], model: "(a) Steel, which is a magnetic material, so it is attracted by the magnet. (b) Aluminium is a metal, but it is not a magnetic material, so the aluminium plate is not attracted by the magnet. (c) Dropping the magnet many times made it lose some of its magnetism, so it became a weaker magnet." }
  ],
  tf: [
    { s: "A magnet attracts all shiny objects.", a: false, why: "Shininess does not matter; only magnetic materials (iron, steel, nickel, cobalt) are attracted. Shiny aluminium foil is not." },
    { s: "A horseshoe magnet has an N pole and an S pole.", a: true, why: "Every magnet, whatever its shape, has both an N pole and an S pole; a horseshoe’s poles are at its two ends." },
    { s: "An object that is not attracted by a magnet must be a non-metal.", a: false, why: "Copper, aluminium and brass are metals that are not attracted by magnets." },
    { s: "A steel needle stroked with a magnet in one direction can be used as a compass needle.", a: true, why: "The needle becomes a magnet, so if it can turn freely it points north-south." },
    { s: "A strong enough magnet can attract an aluminium can.", a: false, why: "Aluminium is non-magnetic, so no magnet attracts it, however strong." },
    { s: "A stronger magnet can attract a paper clip from a greater distance.", a: true, why: "That is why the greatest distance of attraction is a way to compare magnet strength." },
    { s: "A ring magnet has only one pole, on its outer edge.", a: false, why: "A ring magnet has two poles, one on each flat face." },
    { s: "A steel bar magnet that has lost its magnetism can be made into a magnet again by stroking it.", a: true, why: "Steel is a magnetic material, so stroking it in one direction with one pole magnetises it again." },
    { s: "A compass needle placed near a bar magnet will still point to the north.", a: false, why: "The bar magnet attracts and repels the needle’s poles, turning it away from north." },
    { s: "Iron filings sprinkled around a bar magnet gather mostly at its two ends.", a: true, why: "The magnetic force is strongest at the poles, which are at the ends." }
  ],
  sort: [
    { title: "Which property of magnets does each use depend on?", groups: ["Attracts magnetic materials", "Like poles repel", "Points north-south when free"], items: [["magnetic catch keeping a cabinet door shut", 0], ["magnet sweeper picking up steel nails at a building site", 0], ["magnet removing iron bits from cereal at a factory", 0], ["whiteboard magnets holding up a poster", 0], ["ring magnets floating on a rod in a toy", 1], ["toy cars that push each other away without touching", 1], ["compass used on a hike at Bukit Timah", 2], ["magnetised needle on a floating cork used to find north", 2], ["hanging bar magnet used to find directions", 2]] }
  ]
};
