window.BANKZ = window.BANKZ || {};
BANKZ["magnets"] = {
  lessons: [
    {
      h: "Electromagnet experiments: variables and ‘the more…, the more…’",
      concept: "In an experiment, the changed variable is the one thing you change on purpose, the measured variable is what you count or measure, and every other variable is kept the same so that the test is fair. When you describe a relationship, name BOTH variables and say which way each one goes: ‘The more coils of wire, the more paper clips the electromagnet attracted.’ Writing only ‘it increased’ or ‘the magnet got stronger’ loses the mark.",
      example: {
        q: "Wei Ming wound different numbers of coils of wire around the same iron nail and connected it to the same battery each time. He counted the paper clips it attracted. Study his results. (a) State the variable he changed and the variable he measured. (b) What is the relationship between the number of coils and the number of paper clips attracted?",
        tbl: [["Number of coils", "Number of paper clips attracted"], ["10", "3"], ["20", "6"], ["30", "9"], ["40", "12"]],
        marks: 2,
        think: [
          "Step 1: The changed variable is what Wei Ming changed on purpose: the number of coils of wire.",
          "Step 2: The measured variable is what he counted: the number of paper clips attracted.",
          "Step 3: Look at the trend. As the coils go up (10, 20, 30, 40), the clips also go up (3, 6, 9, 12).",
          "Step 4: Write it as ‘The more …, the more …’, naming both variables."
        ],
        answer: "(a) He changed the number of coils of wire around the nail and measured the number of paper clips attracted. (b) The more coils of wire around the iron nail, the more paper clips the electromagnet attracted."
      },
      tip: "Check your sentence has TWO variables and TWO directions: ‘The more [changed], the more/fewer [measured].’",
      try: {
        q: "Aisha used the same iron nail and 20 coils of wire, but changed the number of batteries. Study her results. Which statement best describes the relationship?",
        tbl: [["Number of batteries", "Number of paper clips attracted"], ["1", "4"], ["2", "8"], ["3", "11"]],
        o: ["The electromagnet attracted more paper clips as time went on.", "The number of paper clips went up, so the magnet was strong.", "The more batteries used, the more paper clips were attracted.", "The more paper clips used, the more batteries were needed."],
        a: 2,
        why: "It names the changed variable (batteries) and the measured variable (paper clips) and gives the direction of both. The others mention time, give only one variable, or swap the two variables round."
      }
    }
  ],
  mcq: [
    { q: "Rina says the N pole of a bar magnet is stronger than its S pole. Which statement is correct?", o: ["The N pole is stronger than the S pole.", "The S pole is stronger than the N pole.", "Both poles are equally strong.", "The middle is stronger than both poles."], a: 2, why: "Misconception: that N is the ‘stronger’ pole. Both poles of a magnet are equally strong, so about the same number of clips cling to each end. The middle is the weakest part.", lvl: 1 },
    { q: "Magnet A is held still on a table. Ali slowly pushes magnet B towards it, as shown. What will Ali feel as the magnets get close?", o: ["A pull towards magnet A", "A push away from magnet A", "No push or pull at all", "A pull first, then a push"], a: 1, why: "The S pole of A faces the S pole of B. Like poles repel, so Ali feels B being pushed away from A.", lvl: 1, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "SN" }], between: ["?"] } },
    { q: "In a magnetic fishing game, a small ring is fixed to each toy fish so that the magnet on the rod can pick it up. The ring should be made of ______.", o: ["copper", "aluminium", "brass", "nickel"], a: 3, why: "Nickel is a magnetic material. Copper, aluminium and brass are metals, but they are not attracted by magnets.", lvl: 1 },
    { q: "Which of these statements about a compass are correct?\nA: The compass needle is a small magnet.\nB: Away from other magnets, the N pole of the needle points to the north.\nC: When a bar magnet is placed near the compass, the needle may not point to the north.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "The needle is a small magnet, so it points north-south on its own (A, B). A nearby magnet attracts and repels its poles, so it can turn the needle away from north (C).", lvl: 2 },
    { q: "Study the Venn diagram. Which object has been placed in the WRONG part?", o: ["copper wire", "steel pin", "brass key", "glass marble"], a: 2, why: "Brass is a metal, but it is not attracted by a magnet, so it belongs in ‘Metal’ only. The steel pin is a magnetic metal and is placed correctly.", lvl: 2, fig: { type: "venn", a: "Metal", b: "Attracted by a magnet", onlyA: ["copper wire", "aluminium foil"], both: ["steel pin", "iron nail", "brass key"], onlyB: [], neither: ["glass marble", "rubber band"] } },
    { q: "Tom made an electromagnet with the same iron nail and 20 coils of wire. He changed the number of batteries. Study the graph. Which conclusion is correct?", o: ["The more batteries used, the more paper clips were attracted.", "The more batteries used, the fewer paper clips were attracted.", "The number of batteries did not change the number of clips.", "The more coils of wire used, the more paper clips were attracted."], a: 0, why: "The clips went up from 3 to 7 to 10 as batteries were added. The number of coils was kept at 20, so the graph tells us nothing about coils.", lvl: 2, fig: { type: "bar", xl: "Number of batteries", yl: "Number of paper clips attracted", bars: [["1 battery", 3], ["2 batteries", 7], ["3 batteries", 10]] } },
    { q: "Which of these can make a magnet lose some of its magnetism?\nA: Dropping it many times\nB: Heating it strongly\nC: Keeping it in a glass of water\nD: Hammering it", o: ["A and B only", "A, B and D only", "B, C and D only", "A, B, C and D"], a: 1, why: "Dropping, heating and hammering can weaken a magnet. Misconception: that water ‘washes away’ magnetism – water is non-magnetic and does not weaken a magnet.", lvl: 2 },
    { q: "A magnet is fixed on each of two toy cars, as shown. Car A is pushed slowly towards car B. What will happen to car B?", o: ["It moves away from car A.", "It moves towards car A.", "It stays still until A hits it.", "It sticks to the front of car A."], a: 0, why: "The N pole on car A faces the N pole on car B. Like poles repel, so B is pushed away before the cars touch.", lvl: 2, fig: { type: "magnets", items: [{ label: "Car A", poles: "SN" }, { label: "Car B", poles: "NS" }], between: ["?"] } },
    { q: "A steel paper clip has fallen to the bottom of a glass of water. Which is the best way to get it out without wetting your fingers?", o: ["Slide a magnet up the outside of the glass.", "Stir the water quickly with a wooden spoon.", "Hold a copper rod against the outside of the glass.", "Put a plastic ruler into the water beside the clip."], a: 0, why: "Magnetic force passes through non-magnetic glass and water, so the clip follows the magnet up the side. Copper and plastic are non-magnetic and cannot attract the clip.", lvl: 2 },
    { q: "One end of each object P, Q and R was brought near the N pole and then the S pole of a bar magnet. Study the results. Which statements are correct?\nA: P is a magnet.\nB: Q is a magnet.\nC: R could be made of copper.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "P was repelled, and only a magnet can repel a magnet. Misconception: that being attracted proves Q is a magnet – Q was attracted by BOTH poles, so it is a magnetic material, not a magnet. R is not attracted at all, so it could be copper.", lvl: 3, tbl: [["Object", "Near N pole", "Near S pole"], ["P", "attracted", "repelled"], ["Q", "attracted", "attracted"], ["R", "no effect", "no effect"]] },
    { q: "Jun stroked a steel bar with the same pole of a magnet, always in one direction. After every 10 strokes, he counted the paper clips the bar could pick up. Study the graph. Which statements are correct?\nA: Before stroking, the steel bar was not a magnet.\nB: The more times the bar was stroked, the more clips it picked up.\nC: A copper bar stroked in the same way would give the same results.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "At 0 strokes the bar picked up no clips, so it was not a magnet (A). The clips rose as the strokes increased (B). Copper is non-magnetic, so it cannot be made into a magnet (C is wrong).", lvl: 3, fig: { type: "line", xl: "Number of strokes", yl: "Number of paper clips picked up", pts: [["0", 0], ["10", 2], ["20", 5], ["30", 8], ["40", 11]] } },
    { q: "Three ring magnets are placed on a wooden rod as shown. B touches A, and C floats above B. Which ONE ring should be turned upside down so that all three rings float apart?", o: ["Ring A", "Ring B", "Ring C", "No single ring can do this"], a: 0, why: "A’s top is N, so B’s bottom is S and its top is N; C’s bottom is N. Turning A over makes its top S, which repels B’s S bottom, and B and C still repel. Turning B makes B and C attract; turning C also makes them attract.", lvl: 3, fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [false, true] } },
    { q: "A bar magnet with its N pole at the left end was broken into two pieces, P (left piece) and Q (right piece). The pieces are placed as shown, with the broken ends facing each other. What will happen?", o: ["P and Q attract, because the broken ends are unlike poles.", "P and Q repel, because the broken ends are like poles.", "Nothing happens, because the broken ends have no poles.", "P and Q repel, because each piece has only one pole."], a: 0, why: "Misconception: that each piece keeps only one pole. Each piece becomes a new magnet: P is N on the left and S at the broken end; Q is N at the broken end and S on the right. S faces N, so they attract.", lvl: 3, fig: { type: "magnets", items: [{ label: "P", poles: "??" }, { label: "Q", poles: "??" }], between: ["?"] } },
    { q: "Mei wound insulated wire around a soft iron nail and connected it to a battery. The nail picked up 8 paper clips. When she disconnected the battery, all the clips dropped. Which statements are correct?\nA: The iron nail was a magnet only while the current was flowing.\nB: Iron is a non-magnetic material.\nC: Using more batteries would make the nail pick up more clips.", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 2, why: "Soft iron is a magnet only while current flows (A), and more batteries make an electromagnet stronger (C). Iron is a magnetic material, so B is wrong.", lvl: 3 },
    { q: "Siti wants to find out whether the thickness of a sheet placed between a magnet and some paper clips affects the number of clips attracted. Which two set-ups should she compare?", o: ["B and C", "A and D", "A and B", "C and D"], a: 2, why: "A and B differ only in thickness (2 mm and 6 mm); the magnet and the material are the same. B and C differ in material, A and D differ in the magnet, and C and D differ in more than one thing.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Bar magnet", "Cardboard sheet", "2 mm thick"] }, { label: "B", icon: "plate", lines: ["Bar magnet", "Cardboard sheet", "6 mm thick"] }, { label: "C", icon: "plate", lines: ["Bar magnet", "Plastic sheet", "6 mm thick"] }, { label: "D", icon: "plate", lines: ["Ring magnet", "Cardboard sheet", "2 mm thick"] }] } },
    { q: "A compass is placed to the right of bar magnet M as shown. Which end of the compass needle will point towards M?", o: ["Its S pole, because like poles attract", "Its N pole, because like poles attract", "Its S pole, because unlike poles attract", "Its N pole, because unlike poles attract"], a: 3, why: "Misconception: that the needle’s N end points to a magnet’s N pole. The right end of M is an S pole, and unlike poles attract, so the needle’s N pole turns towards M.", lvl: 3, fig: { type: "magnets", items: [{ label: "M", poles: "NS" }, { label: "Compass needle", poles: "??" }], between: ["?"] } },
    { q: "A is a magnet. X is an iron rod that is not a magnet. B is a magnet whose poles are not labelled. X is attracted to A and also to B, as shown. What is the pole at the left end of B?", o: ["N pole", "S pole", "It cannot be told", "B has no pole there"], a: 2, why: "Misconception: that attraction tells you the pole. Iron is attracted by EITHER pole of a magnet, so B’s left end could be N or S. Every magnet has a pole at each end, so it does have a pole there.", lvl: 4, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "X", kind: "bar", text: "iron" }, { label: "B", poles: "??" }], between: ["attract", "attract"] } },
    { q: "Four ring magnets W, X, Y and Z are placed on a wooden rod as shown. The top face of W is an S pole. X floats above W, Y touches X, and Z floats above Y. Which statements are correct?\nA: The top face of X is an N pole.\nB: The top faces of X and Y are the same pole.\nC: The top face of Z is an N pole.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "X floats, so X’s bottom is S and its top is N. Y touches X, so Y’s bottom is S and its top is N. Z floats above Y, so Z’s bottom is N and its top is S. Statements A and B are true; C is false.", lvl: 4, fig: { type: "rings", rings: [{ label: "W", top: "S" }, { label: "X", top: "?" }, { label: "Y", top: "?" }, { label: "Z", top: "?" }], gaps: [true, false, true] } },
    { q: "Four electromagnets were made with the same iron nail. Study the results. Which conclusion is correct?", o: ["Only the number of coils affected the strength of the electromagnet.", "Q and R show the effect of batteries, since R has more batteries.", "S was the strongest only because it had the most coils of wire.", "More coils and more batteries both made the electromagnet stronger."], a: 3, why: "P and Q (same batteries) show more coils attract more clips; P and R (same coils) show more batteries attract more clips. Q and R differ in both coils and batteries, so they cannot be compared fairly.", lvl: 4, tbl: [["Set-up", "Coils", "Batteries", "Clips attracted"], ["P", "10", "1", "4"], ["Q", "20", "1", "8"], ["R", "10", "2", "7"], ["S", "20", "2", "14"]] },
    { q: "Bars X and Y look exactly the same. One is a magnet and the other is a plain steel bar. With no other objects, how can you tell which one is the magnet?", o: ["Bring an end of X near an end of Y. If they attract, both are magnets.", "Bring an end of X near an end of Y. If they attract, Y must be the magnet.", "Place X on top of Y. If X stays there without falling, X is the magnet.", "Touch an end of X to the middle of Y. If they attract strongly, X is the magnet."], a: 3, why: "A magnet is strongest at its poles and weakest in the middle. If X is the magnet, its pole strongly attracts the steel middle of Y. If Y is the magnet, its weak middle hardly attracts X. End-to-end attraction happens whichever bar is the magnet.", lvl: 4 }
  ],
  oe: [
    { q: "Aini placed plastic sheets of the same size between a magnet and a pile of steel paper clips. She changed the number of sheets and counted the clips attracted each time. Study the graph. (a) What is the variable she changed? (b) What is the relationship between the number of plastic sheets and the number of paper clips attracted? (c) Explain why fewer clips were attracted when more sheets were used.", marks: 3, kw: [["number of plastic", "number of sheet", "how many sheet", "how many plastic"], ["fewer", "less"], ["further", "farther", "distance", "away from", "far"]], model: "(a) The number of plastic sheets between the magnet and the paper clips. (b) The more plastic sheets there are, the fewer paper clips are attracted. (c) More sheets keep the paper clips further away from the magnet, so the magnetic force on the clips is weaker. The magnetic force still passes through the plastic.", fig: { type: "line", xl: "Number of plastic sheets", yl: "Number of paper clips attracted", pts: [["0", 15], ["2", 12], ["4", 8], ["6", 5], ["8", 3]] } },
    { q: "Sam wants to find out if the number of batteries affects the strength of an electromagnet. He sets up the three electromagnets shown. (a) Which two set-ups should he use? (b) Explain why he should not use set-up C. (c) State what he should measure to compare the strength of the electromagnets. (d) State one other thing, not shown in the diagram, that he must keep the same.", marks: 4, x: 1, kw: [["a and b", "b and a"], ["coil", "steel nail", "type of nail", "kind of nail", "more than one"], ["paper clip", "clips", "pins"], ["same size", "same type", "same kind", "same wire", "same length", "same distance", "same paper clip", "same height"]], model: "(a) A and B. (b) Set-up C has a different number of coils and a different nail as well as a different number of batteries, so more than one variable is changed and he cannot tell which one caused the result. (c) The number of paper clips each electromagnet attracts. (d) He must use paper clips of the same size and type.", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["20 coils", "1 battery", "Iron nail"] }, { label: "B", icon: "box", lines: ["20 coils", "2 batteries", "Iron nail"] }, { label: "C", icon: "box", lines: ["30 coils", "2 batteries", "Steel nail"] }] } },
    { q: "Three ring magnets are placed on a wooden rod as shown. The top face of C is an N pole. B floats above A, and C touches B. (a) What is the pole on the top face of A? Write the word in full. (b) Explain why B floats above A. (c) Ring B is removed, and C is put back on the rod directly above A, the same way up as before. Predict whether C will float above A or touch A.", marks: 3, x: 1, kw: [["south"], ["like poles", "same pole", "same poles"], ["c will float", "c floats", "c would float", "it will float", "it floats", "will float", "would float"]], model: "(a) South. C’s bottom face is S, and C touches B, so B’s top face is N and B’s bottom face is S. (b) B’s bottom face (S) faces A’s top face (S). These are like poles, and like poles repel, so B is pushed up and floats. (c) C will float above A, because C’s bottom face is S, the same pole as A’s top face, so they repel.", fig: { type: "rings", rings: [{ label: "A", top: "?" }, { label: "B", top: "?" }, { label: "C", top: "N" }], gaps: [true, false] } },
    { q: "Priya brought one end of each object J, K and L near the N pole and then the S pole of a bar magnet. Study her results. (a) Which object is a magnet? (b) Explain how the results show this. (c) Name one material that J could be made of. (d) Priya says K must be made of plastic. Explain why she may be wrong.", marks: 4, kw: [["l"], ["repel", "pushed away", "push away", "pushes away"], ["iron", "steel", "nickel", "cobalt"], ["metal", "aluminium", "copper", "brass", "gold", "silver", "wood", "glass", "rubber"]], model: "(a) L. (b) L was repelled by the N pole, and only a magnet can repel another magnet. J was attracted by both poles, so it is not a magnet. (c) Iron or steel. (d) K could be made of any material that is not magnetic, such as wood, or a metal like aluminium or copper, which is not attracted by a magnet.", tbl: [["Object", "Near N pole", "Near S pole"], ["J", "attracted", "attracted"], ["K", "no effect", "no effect"], ["L", "repelled", "attracted"]] },
    { q: "Ravi stroked a steel bar with the N pole of a magnet, always in one direction. After every 10 strokes, he counted how many paper clips the bar could pick up. Study the graph. (a) Describe how the number of clips changed from 10 to 30 strokes. (b) What happened to the number of clips after 30 strokes? (c) State one thing he must keep the same so that the test is fair.", marks: 3, kw: [["the more", "increase", "went up", "more paper clips", "more clips"], ["stayed", "stay", "did not change", "didn't change", "remained", "remain", "no change", "constant"], ["same magnet", "same pole", "same steel bar", "same bar", "same paper clip", "same size", "same type", "same direction", "same kind"]], model: "(a) The more times the bar was stroked, the more paper clips it picked up, from 3 clips to 9 clips. (b) After 30 strokes, the number of clips stayed at 9, so stroking it more times did not make it a stronger magnet. (c) He must use the same magnet and paper clips of the same size and type.", fig: { type: "bar", xl: "Number of strokes", yl: "Number of paper clips picked up", bars: [["10", 3], ["20", 6], ["30", 9], ["40", 9], ["50", 9]] } },
    { q: "A crane at a scrapyard uses a large electromagnet to lift old cars and drop them onto a pile. (a) Explain why an electromagnet is used instead of a permanent magnet. (b) Some loose aluminium parts fall off while a car is being lifted. Explain why. (c) Suggest one way to make the electromagnet lift heavier loads.", marks: 3, kw: [["switch", "turned off", "turn off", "current"], ["not magnetic", "non-magnetic", "not a magnetic", "not attracted", "isn't magnetic"], ["more coil", "more batter", "more turns", "more wire", "stronger current", "more loops"]], model: "(a) The electromagnet can be switched off. When the current stops, it loses its magnetism and drops the car where it is needed. (b) Aluminium is not a magnetic material, so the aluminium parts are not attracted by the electromagnet and fall off. (c) Use more coils of wire or more batteries." }
  ],
  tf: [
    { s: "The N pole of a magnet is stronger than its S pole.", a: false, why: "Both poles of a magnet are equally strong." },
    { s: "A compass needle is a small magnet.", a: true, why: "That is why it points north-south and is affected by nearby magnets." },
    { s: "The N pole of a compass needle always turns towards the N pole of a nearby bar magnet.", a: false, why: "Like poles repel; the needle’s N pole turns towards the magnet’s S pole." },
    { s: "A soft iron nail in an electromagnet loses its magnetism when the current is switched off.", a: true, why: "Soft iron is only a temporary magnet; it drops its paper clips when the current stops." },
    { s: "A thin sheet of aluminium placed between a magnet and a paper clip stops the magnetic force.", a: false, why: "Aluminium is a metal, but it is non-magnetic, so magnetic force passes through it." },
    { s: "The further a paper clip is from a magnet, the weaker the magnetic force on it.", a: true, why: "Magnetic force becomes weaker with distance, so far-away clips are not attracted." },
    { s: "A magnet can attract a brass key because brass is a metal.", a: false, why: "Brass is a metal but it is not magnetic, so it is not attracted." },
    { s: "Using more batteries makes an electromagnet stronger.", a: true, why: "More batteries (or more coils) make it attract more paper clips." },
    { s: "A magnet attracts an iron nail only when they are touching.", a: false, why: "Magnetic force acts over a distance; the nail is pulled before it touches." },
    { s: "Two magnets can repel each other through a sheet of cardboard.", a: true, why: "Magnetic force passes through non-magnetic materials like cardboard." }
  ],
  doc: [
    { q: "Wei Ming found that his electromagnet attracted more paper clips when he used more coils of wire. Write a conclusion for his experiment.", marks: 2, answers: ["The electromagnet became stronger.", "The more coils of wire around the nail, the more paper clips the electromagnet attracted.", "More coils."], best: 1, why: "Answer 2 names both variables (coils and paper clips) and the direction of each. Answer 1 gives only one idea and does not say what caused it. Answer 3 names the changed variable but not what happened to the clips." },
    { q: "Bar magnet P pushes rod Q away. Is Q a magnet? Explain.", marks: 2, answers: ["Yes. Q is a magnet because it was repelled, and only a magnet can repel another magnet.", "Yes, because Q is made of metal.", "No, because Q did not stick to P."], best: 0, why: "Answer 1 gives the claim and the reason: repulsion happens only between magnets. Answer 2 is wrong because being metal does not make something a magnet. Answer 3 gets the claim wrong – not sticking here means it was repelled, which proves Q IS a magnet." }
  ]
};
