window.BANKX = window.BANKX || {};
BANKX["magnets"] = {
  notes: [
    { h: "Reading ring magnets on a rod", t: "A gap between two ring magnets means the facing faces are like poles, which repel. Rings that touch have unlike poles facing, which attract. The bottom face of a ring is always the opposite pole to its top face. Start from a ring whose pole you know and work up or down one ring at a time. The lowest gap is usually the smallest, because the bottom pair must hold up the weight of all the rings above it.", kw: ["gap means like poles", "touching means unlike poles", "bottom face is the opposite pole"] },
    { h: "Working out poles in a row of magnets", t: "Each bar magnet has opposite poles at its two ends. If you know one end, you know the other. When two magnets repel, their facing ends are the same pole; when they attract, the facing ends are opposite poles. A rod of iron or steel that is not a magnet is attracted by BOTH poles and never repels, so only repulsion tells you an object is a magnet.", kw: ["opposite poles at its two ends", "facing ends", "never repels"] },
    { h: "Magnet strength experiments", t: "To compare magnets, change only the magnet, keep the paper clips (size and type) and the method the same, and measure the number of clips attracted or the greatest distance at which a clip is attracted. A paper clip hanging on a magnet becomes a temporary magnet and can hold another clip, so a stronger magnet holds a longer chain. Repeating the test and checking the results are similar makes them more reliable.", kw: ["change only the magnet", "temporary magnet", "more reliable"] }
  ],
  traps: [
    "If two objects attract, both must be magnets -> A magnet also attracts a magnetic material such as an iron nail; only one of them needs to be a magnet.",
    "A ring magnet has its poles on its inside and outside edges -> Its poles are on its two flat faces (top and bottom).",
    "Flipping one ring on a rod only changes the gap above it -> Flipping a ring changes BOTH its top and bottom faces, so the gaps above and below it both change."
  ],
  mcq: [
    { q: "The diagram shows two bar magnets. What will happen when they are pushed close together?", o: ["They attract.", "They repel.", "Nothing happens.", "They repel, then attract."], a: 0, why: "The S pole of A faces the N pole of B. Unlike poles attract.", lvl: 1, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "NS" }], between: ["?"] } },
    { q: "The diagram shows two ring magnets on a wooden rod. Ring B floats above ring A. Which pole is on the bottom face of B?", o: ["S", "N", "Both N and S", "It has no pole"], a: 1, why: "B floats, so like poles face each other. A’s top face is N, so B’s bottom face is also N (its top face is S).", lvl: 1, fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "S" }], gaps: [true] } },
    { q: "A bar magnet was dipped into paper clips. The graph shows how many clips stuck to each part of it. Which statement explains the results?", o: ["The magnet is strongest in the middle, between X and Y.", "End X and end Y are both N poles, so both attract clips.", "The magnetic force is strongest at the poles (the ends).", "The middle of the magnet is made of plastic, not iron."], a: 2, why: "Most clips stuck at the two ends, where the poles are. One end must be N and the other S, because every magnet has both poles.", lvl: 1, fig: { type: "bar", title: "Paper clips on a bar magnet", xl: "Part of magnet", yl: "Number of paper clips", bars: [["End X", 10], ["Middle", 1], ["End Y", 10]] } },
    { q: "Which magnet has its N and S poles on its two flat faces?", o: ["Bar magnet", "Horseshoe magnet", "U-shaped magnet", "Ring magnet"], a: 3, why: "A ring magnet’s poles are on its top and bottom faces. Bar, horseshoe and U-shaped magnets have their poles at their two ends.", lvl: 1 },
    { q: "In the diagram, A and B repel, and B and C repel. What are the poles of magnet B, from left to right?", o: ["N, S", "S, N", "N, N", "S, S"], a: 1, why: "A’s right end is S and repels B, so B’s left end is S and its right end is N. B’s N then faces C’s N, so they repel too. A magnet cannot have two N or two S ends.", lvl: 2, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }, { label: "C", poles: "NS" }], between: ["repel", "repel"] } },
    { q: "X is an iron rod that is not a magnet. It is brought near magnet A as shown, and then turned around so its other end faces A. What happens?", o: ["Repels, then attracts", "Attracts, then repels", "Attracts both times", "Repels both times"], a: 2, why: "Iron is a magnetic material, so a magnet attracts either end of it. It never repels because X is not a magnet.", lvl: 2, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "X", kind: "bar", text: "iron" }], between: ["?"] } },
    { q: "Four magnets were dipped into the same box of paper clips. Magnet A is the biggest and magnet D is the smallest. Study the graph. Which statement is correct?", o: ["A bigger magnet is not always a stronger magnet.", "The biggest magnet is always the strongest one.", "Magnet C is stronger than magnet A and magnet D.", "All the magnets are equally strong, whatever their size."], a: 0, why: "D is the smallest but attracted the most clips (12), while the biggest, A, attracted only 6. C (4) is weaker than A.", lvl: 2, fig: { type: "bar", xl: "Magnet", yl: "Number of paper clips attracted", bars: [["A", 6], ["B", 9], ["C", 4], ["D", 12]] } },
    { q: "Three ring magnets are placed on a wooden rod as shown. B floats above A, and C touches B. What is the pole on the top face of C?", o: ["N", "Cannot tell", "S", "Both N and S"], a: 2, why: "A’s top is N, so B’s bottom is N (repel) and B’s top is S. C touches B, so C’s bottom is N (unlike poles attract) and C’s top is S.", lvl: 2, fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, false] } },
    { q: "A sheet of each material, all 2 mm thick, was placed in turn between a magnet and a pile of paper clips. Study the graph. Which conclusion is correct?", o: ["Glass blocks magnetic force, so fewer clips were attracted through it.", "Magnetic force passes through these non-magnetic materials equally well.", "Wood is a magnetic material, so it attracted the most paper clips.", "The magnet became weaker after each test, so fewer clips were attracted."], a: 1, why: "The same number of clips (7) was attracted each time, so the type of non-magnetic material made no difference. Only the thickness (distance) would change the result.", lvl: 2, fig: { type: "bar", xl: "Material between magnet and clips", yl: "Number of paper clips attracted", bars: [["Paper", 7], ["Plastic", 7], ["Glass", 7], ["Wood", 7]] } },
    { q: "Steel bar X was stroked many times from its left end to its right end with the S pole of a magnet. It is then placed next to magnet B as shown. What will happen?", o: ["X and B attract.", "X and B repel.", "Nothing happens because X is steel.", "X attracts B, then repels it."], a: 1, why: "The end where the strokes finish becomes the opposite pole to the stroking pole, so X’s right end becomes N. It faces B’s N pole, and like poles repel.", lvl: 3, fig: { type: "magnets", items: [{ label: "X", poles: "??" }, { label: "B", poles: "NS" }], between: ["?"] } },
    { q: "Magnet A attracts magnet B as shown. Which pole is at the right end of A?", o: ["N", "Both N and S", "It has no pole", "S"], a: 3, why: "A’s right end faces B’s N pole and they attract, so it must be the unlike pole, S.", lvl: 2, fig: { type: "magnets", items: [{ label: "A", poles: "??" }, { label: "B", poles: "NS" }], between: ["attract"] } },
    { q: "Two ring magnets are stuck together on a rod as shown. Ring B is taken off, turned upside down and put back. What will happen?", o: ["B floats above A.", "B stays stuck to A.", "A floats above B.", "B falls off the rod."], a: 0, why: "Now B’s S face points down and faces A’s S top face. Like poles repel, so B floats.", lvl: 2, fig: { type: "rings", rings: [{ label: "A", top: "S" }, { label: "B", top: "S" }], gaps: [false] } },
    { q: "Study the Venn diagram. Where should a cobalt disc be placed?", o: ["In the ‘Metal’ circle only", "Where the two circles overlap", "In ‘Attracted by a magnet’ only", "Outside both of the circles"], a: 1, why: "Cobalt is a metal AND a magnetic material, like iron, steel and nickel. Aluminium, copper and gold are metals that are not attracted.", lvl: 2, fig: { type: "venn", a: "Metal", b: "Attracted by a magnet", onlyA: ["aluminium can", "copper wire", "gold ring"], both: ["iron nail", "steel pin", "nickel coin"], onlyB: [], neither: ["plastic ruler", "wooden pencil"] } },
    { q: "Four ring magnets are placed on a wooden rod as shown. B floats above A, C floats above B, and D touches C. What are the poles on the top faces of B, C and D?", o: ["S, N, S", "N, S, S", "S, S, N", "S, N, N"], a: 3, why: "A top N → B bottom N, B top S. B top S → C bottom S, C top N. C top N attracts D’s bottom S, so D’s top is N.", lvl: 3, fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }, { label: "D", top: "?" }], gaps: [true, true, false] } },
    { q: "Three identical ring magnets float on a rod as shown. The gap between A and B is smaller than the gap between B and C. Why?", o: ["A is a weaker magnet than B, so it repels less.", "C is lighter than B, so it is pushed up higher.", "The repulsion between A and B holds up both B and C.", "The rod is magnetic near the bottom, pulling B down."], a: 2, why: "The magnets are identical, so the lower pair must push up two rings (B and C) while the upper pair holds up only C. More weight pushes the lower rings closer.", lvl: 3, fig: { type: "rings", rings: [{ label: "A", top: "S" }, { label: "B", top: "N" }, { label: "C", top: "S" }], gaps: [true, true] } },
    { q: "B and C are magnets whose poles are not labelled. A attracts B, and B repels C. Which end of C is an N pole?", o: ["Cannot tell", "Both ends", "The left end", "The right end"], a: 3, why: "A’s S attracts B’s left end, so B is N on the left and S on the right. B’s S repels C’s left end, so C’s left is S and its right end is N.", lvl: 3, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }, { label: "C", poles: "??" }], between: ["attract", "repel"] } },
    { q: "Rod X looks like a plain metal rod. When it is brought near magnet A as shown, X is pushed away. Which is correct?", o: ["X is a magnet, and its left end is an S pole.", "X is made of iron but is not a magnet.", "X is a magnet, and its left end is an N pole.", "X is made of a non-magnetic material."], a: 0, why: "Only a magnet can repel a magnet, so X is a magnet. Its left end repels A’s S pole, so it is also S.", lvl: 3, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "X", kind: "bar", text: "rod X" }], between: ["repel"] } },
    { q: "An electromagnet was made with different numbers of coils of wire around the same iron nail and the same battery. Study the graph. Predict how many paper clips it will attract with 40 coils.", o: ["Fewer than 5", "About 9", "About 14", "More than 14"], a: 3, why: "The more coils, the more paper clips were attracted, so 40 coils should attract more than the 14 clips at 30 coils.", lvl: 3, fig: { type: "bar", xl: "Number of coils", yl: "Number of paper clips attracted", bars: [["10 coils", 5], ["20 coils", 9], ["30 coils", 14]] } },
    { q: "A pin was moved slowly towards four magnets. The graph shows the greatest distance at which each magnet attracted the pin. Which statement is NOT true?", o: ["Q and S are equally strong.", "P is the weakest magnet.", "R is stronger than Q.", "S is stronger than R."], a: 2, why: "Q attracted the pin from 7 cm but R only from 5 cm, so Q is stronger than R. A greater distance means a stronger magnet.", lvl: 3, fig: { type: "bar", xl: "Magnet", yl: "Greatest distance pin was attracted (cm)", bars: [["P", 3], ["Q", 7], ["R", 5], ["S", 7]] } },
    { q: "Which of these observations show that object K is a magnet?\nA: K picks up a steel paper clip.\nB: K pushes away the N pole of a compass needle.\nC: K is attracted to the S pole of a bar magnet.\nD: One end of K repels the S pole of a bar magnet.", o: ["A, B and D only", "B and D only", "C and D only", "A, B, C and D"], a: 0, why: "Only a magnet can attract a paper clip on its own (A) or repel another magnet (B, D). Being attracted TO a magnet (C) also happens with any magnetic material, so C does not prove K is a magnet.", lvl: 3 }
  ],
  tf: [
    { s: "The poles of a ring magnet are on its two flat faces.", a: true, why: "One flat face is N and the other is S." },
    { s: "Two iron nails that are not magnets can repel each other.", a: false, why: "Only magnets can repel; iron nails that are not magnets do not attract or repel each other." },
    { s: "If ring magnet B floats above ring magnet A, the faces facing each other are unlike poles.", a: false, why: "Floating means repelling, so the facing faces are like poles." },
    { s: "A steel paper clip hanging from a magnet can attract another paper clip.", a: true, why: "The clip becomes a temporary magnet while it touches the magnet." },
    { s: "When a steel bar is stroked with the N pole of a magnet, the end where each stroke finishes becomes an S pole.", a: true, why: "The finishing end becomes the opposite pole to the stroking pole." },
    { s: "A sheet of glass between a magnet and a paper clip stops the magnetic force completely.", a: false, why: "Magnetic force passes through non-magnetic materials like glass." },
    { s: "If two objects attract each other, both of them must be magnets.", a: false, why: "A magnet also attracts a magnetic material, like an iron nail, that is not a magnet." },
    { s: "Only a magnet can repel another magnet.", a: true, why: "That is why repulsion is the sure test for a magnet." }
  ],
  oe: [
    { q: "Three ring magnets are placed on a wooden rod as shown. B floats above A, and C floats above B. (a) Is the TOP face of C a north pole or a south pole? Write the word in full. (b) Explain how you worked out your answer to (a). (c) Ring C is taken off, turned upside down and put back. Predict what will happen to C.", marks: 3, kw: [["north"], ["like poles", "same pole", "same poles", "repel"], ["stick", "touch", "attract", "fall onto", "falls onto", "rest on", "rests on"]], model: "(a) North. (b) A’s top face is N, and B floats, so B’s bottom face is N (like poles repel) and its top face is S. C floats, so C’s bottom face is also S and its top face is N. (c) C will fall onto B and stick to it, because C’s N face now points down towards B’s S face, and unlike poles attract.", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, true] } },
    { q: "Hui Min dipped three magnets into the same box of paper clips. (a) Which magnet is the strongest? (b) Explain using the graph. (c) How can she make her results more reliable?", marks: 3, kw: [["blue"], ["most paper clips", "most clips", "13", "greatest number"], ["repeat", "again", "more times"]], model: "(a) The blue magnet. (b) It attracted the most paper clips (13). (c) She can repeat the experiment a few more times and check that the results are similar.", fig: { type: "bar", xl: "Magnet", yl: "Number of paper clips attracted", bars: [["Red magnet", 6], ["Blue magnet", 13], ["Green magnet", 9]] } },
    { q: "Rod P is attracted to the N pole of magnet M, as shown. Siti says, ‘P must be a magnet.’ (a) Is she right? (b) Explain your answer. (c) What should she do next to find out for sure?", marks: 3, kw: [["not right", "not correct", "wrong", "may not", "not necessarily", "not sure"], ["magnetic material", "iron", "steel"], ["s pole", "other pole", "repel"]], model: "(a) She is not right – P may not be a magnet. (b) A magnet also attracts a magnetic material such as iron or steel, so P could just be an iron rod. (c) She should bring the same end of P near the S pole of M. If it is repelled, P is a magnet.", fig: { type: "magnets", items: [{ label: "P", kind: "bar", text: "rod P" }, { label: "M", poles: "NS" }], between: ["attract"] } },
    { q: "Ali held a magnet at different distances above a pile of paper clips. Study the graph. (a) What is the relationship between the distance and the number of paper clips attracted? (b) Predict how many clips will be attracted at 6 cm. (c) State one thing he must keep the same.", marks: 3, kw: [["fewer", "less"], ["0", "none", "no paper clip", "zero"], ["same magnet", "same paper clip", "same type", "same size", "same kind"]], model: "(a) The further the magnet is from the paper clips, the fewer paper clips it attracts. (b) About 0 – no paper clips. (c) He must use the same magnet and the same type and size of paper clips.", fig: { type: "line", xl: "Distance from paper clips (cm)", yl: "Number of paper clips attracted", pts: [["1", 12], ["2", 8], ["3", 5], ["4", 3], ["5", 1]] } },
    { q: "Ahmad made a sewing needle into a magnet by stroking it many times from the eye to the tip with the N pole of a magnet. (a) Which end of the needle becomes the S pole? (b) Suggest one way to make the needle a stronger magnet. (c) Why must he lift the magnet away from the needle at the end of each stroke?", marks: 3, kw: [["tip", "point"], ["more strokes", "more times", "stroke more", "stronger magnet"], ["undo", "opposite", "cancel", "weaken", "backward", "back along"]], model: "(a) The tip, where each stroke finishes. (b) Stroke it more times with the same pole, or use a stronger magnet. (c) If he rubbed the magnet back along the needle, it would stroke in the opposite direction and weaken or undo the magnetising.", },
    { q: "Two ring magnets are on a rod as shown, with B floating above A. Mei turns B upside down and puts it back. Predict what happens and explain.", marks: 2, kw: [["stick", "touch", "attract", "fall onto", "falls onto"], ["unlike", "opposite", "different pole"]], model: "B will fall onto A and stick to it. After turning, B’s N face points down and faces A’s S face. Unlike poles attract.", fig: { type: "rings", rings: [{ label: "A", top: "S" }, { label: "B", top: "N" }], gaps: [true] } },
    { q: "A tray has a mixture of steel pins, copper pins and plastic beads. (a) How can you remove only the steel pins? (b) Explain why the copper pins are left behind.", marks: 2, kw: [["magnet"], ["not magnetic", "non-magnetic", "not a magnetic", "isn't magnetic", "not attracted", "isn't attracted"]], model: "(a) Move a magnet over the mixture; the steel pins are attracted and lifted out. (b) Copper is a metal that is not magnetic, so the copper pins are not attracted to the magnet." },
    { q: "A magnet holds a chain of four paper clips, one below the other. (a) Why does the second paper clip stay hanging on the first one? (b) Predict what happens when the top clip is gently pulled off the magnet.", marks: 2, kw: [["temporary magnet", "becomes a magnet", "become a magnet", "turns into a magnet", "acts as a magnet", "acts like a magnet", "magnetis", "magnetiz", "becomes magnetic"], ["fall", "drop", "come apart", "not attract"]], model: "(a) The first paper clip becomes a temporary magnet while it touches the magnet, so it attracts the second clip. (b) The clips lose their magnetism and fall apart, dropping off one another." }
  ],
  doc: [
    { q: "Ring magnet B floats above ring magnet A on a pencil. Explain why.", marks: 2, answers: ["B is very light, so it floats.", "The magnets repel.", "The facing poles of A and B are like poles. Like poles repel, so B is pushed up and floats."], best: 2, why: "Answer 3 says which poles face each other (like poles) AND that they repel. Answer 1 gives a wrong reason. Answer 2 says ‘repel’ but not why – it is missing ‘like poles’." },
    { q: "Describe how to find out for sure whether a metal rod is a magnet.", marks: 2, answers: ["Bring one end of the rod near the N pole, then the S pole, of a magnet. If that end is repelled by one pole, the rod is a magnet.", "Put the rod near a magnet. If it is attracted, it is a magnet.", "Put paper clips near it to see if it is metal."], best: 0, why: "Answer 1 tests with both poles and uses repulsion, the only sure test. Answer 2 uses attraction, which also happens with iron that is not a magnet. Answer 3 tests the wrong idea – being metal does not make it a magnet." },
    { q: "Explain why a magnet does not attract an aluminium drink can.", marks: 2, answers: ["The can is not metal.", "Aluminium is a metal, but it is not a magnetic material, so it is not attracted by magnets.", "The magnet is too weak."], best: 1, why: "Answer 2 names aluminium as a non-magnetic material. Answer 1 is wrong – aluminium IS a metal. Answer 3 guesses a reason without the key idea of magnetic materials." },
    { q: "Magnet D attracted 15 paper clips, more than magnets A, B and C. Which magnet is the strongest? Explain.", marks: 2, answers: ["Magnet D, because it attracted the most paper clips (15).", "Magnet D, because it is the best.", "Magnet D."], best: 0, why: "Answer 1 gives the claim and the evidence from the results. Answer 2 gives a vague reason with no evidence. Answer 3 gives only the claim, so it scores at most 1 mark." },
    { q: "In a magnet strength experiment, why must the same type and size of paper clips be used?", marks: 2, answers: ["So that there are enough clips.", "Because paper clips are magnetic.", "To make it a fair test, so that only the magnet is changed and bigger clips do not change the number attracted."], best: 2, why: "Answer 3 says fair test and explains that only the magnet is changed. Answer 1 gives no scientific reason. Answer 2 is true but does not explain why the clips must be the same." }
  ]
};
