window.BANKU = window.BANKU || {};
BANKU["magnets"] = {
  glossary: [
    { t: "Magnet", d: "An object that attracts magnetic materials such as iron and steel. It has an N pole and an S pole and can attract or repel another magnet." },
    { t: "Magnetic material", d: "Any material that a magnet can attract. Iron, steel, nickel and cobalt are magnetic materials." },
    { t: "Non-magnetic material", d: "A material that is not attracted by a magnet, such as plastic, wood, glass, rubber, aluminium and copper." },
    { t: "Poles of a magnet", d: "The two parts of a magnet, the N pole and the S pole, where its magnetic force is strongest. On a bar magnet they are at the two ends." },
    { t: "Attract", d: "To pull towards. Unlike poles of two magnets attract each other, and a magnet attracts magnetic materials." },
    { t: "Repel", d: "To push away. Like poles of two magnets repel each other. Only a magnet can repel another magnet." },
    { t: "Magnetic force", d: "The pull or push of a magnet. It can act without touching, can pass through non-magnetic materials, and becomes weaker as the distance from the magnet increases." },
    { t: "Compass", d: "An instrument with a small magnetic needle that comes to rest pointing in the north-south direction. It is used to find direction." },
    { t: "Freely suspended magnet", d: "A magnet hung so that it can turn freely. It comes to rest pointing in the north-south direction, with its N pole pointing to the north." },
    { t: "Electromagnet", d: "A magnet made when an electric current flows through a coil of insulated wire wound around a piece of iron, such as an iron nail. It can be switched on and off." },
    { t: "Stroke method", d: "A way to make a magnet: stroke a steel bar many times with the same pole of a magnet, in one direction only, lifting the magnet away after each stroke." },
    { t: "Strength of a magnet", d: "How strong its magnetic force is. A stronger magnet attracts more paper clips, or attracts a paper clip from a greater distance." }
  ],
  lessons: [
    {
      h: "Working out poles along a row of bar magnets",
      concept: "Each bar magnet has opposite poles at its two ends, so once you know one end you know the other. When two magnets repel, their facing ends are like poles; when two magnets attract, their facing ends are unlike poles. Start from the magnet whose poles you know and work across one gap at a time, flipping to the opposite pole inside each magnet.",
      example: {
        q: "Magnets A, B and C are placed in a row as shown. A attracts B, and B repels C. (a) What pole is at the right end of B? (b) What pole is at the left end of C? Explain your answers.",
        fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }, { label: "C", poles: "??" }], between: ["attract", "repel"] },
        marks: 2,
        think: [
          "Step 1: Start with what you know: the right end of A is an S pole.",
          "Step 2: A attracts B, so the facing ends are unlike poles. The left end of B is N, so the right end of B is S.",
          "Step 3: B repels C, so the facing ends are like poles. The right end of B is S, so the left end of C is also S.",
          "Step 4: In the answer, give the reason (attract = unlike poles, repel = like poles) for each gap."
        ],
        answer: "(a) S pole. A’s right end is S. A attracts B, so unlike poles face each other and B’s left end is N, which makes its right end S. (b) S pole. B repels C, so like poles face each other: C’s left end is S, the same as B’s right end."
      },
      tip: "Write the pole on each end as you go (A: N S, B: N S …) so you never forget that the two ends of one magnet are opposite.",
      try: {
        q: "Magnets A, B and C are placed in a row as shown. A repels B, and B attracts C. What are the poles of A and of C, from left to right?",
        fig: { type: "magnets", items: [{ label: "A", poles: "??" }, { label: "B", poles: "SN" }, { label: "C", poles: "??" }], between: ["repel", "attract"] },
        o: ["A: S, N   C: N, S", "A: N, S   C: N, S", "A: N, S   C: S, N", "A: S, N   C: S, N"],
        a: 2,
        why: "B’s left end is S. A repels B, so A’s right end is also S and its left end is N (A: N, S). B’s right end is N. B attracts C, so C’s left end is S and its right end is N (C: S, N)."
      }
    },
    {
      h: "Using a compass to find the poles of a magnet",
      concept: "A compass needle is a small magnet. Away from other magnets, its N pole points north. Near a bar magnet, the needle’s N pole is attracted to the magnet’s S pole and pushed away from its N pole. So the end of a magnet that the needle’s N pole points to is an S pole, and the end that the needle’s S pole points to is an N pole.",
      example: {
        q: "The labels on Jun’s bar magnet have worn off. He places a compass near end X of the magnet, and the N pole of the compass needle points towards X. (a) What pole is end X? (b) Explain your answer.",
        marks: 2,
        think: [
          "Step 1: Remember that the compass needle is itself a small magnet with an N pole and an S pole.",
          "Step 2: The needle’s N pole turns towards X, so X attracts the needle’s N pole.",
          "Step 3: Unlike poles attract, so X must be the opposite pole to N, which is an S pole."
        ],
        answer: "(a) X is an S pole. (b) The compass needle is a small magnet. Its N pole is attracted to end X. Unlike poles attract, so X is an S pole."
      },
      tip: "The needle’s N pole points TO a magnet’s S pole – never write ‘the N pole points to the N pole’.",
      try: {
        q: "A compass is placed near end Y of a bar magnet whose poles are not labelled, and the S pole of the needle points towards Y. The compass is then moved to the other end, Z. Which is correct?",
        o: ["Y is an N pole, and the needle’s N pole will point to Z.", "Y is an S pole, and the needle’s N pole will point to Z.", "Y is an N pole, and the needle’s S pole will point to Z.", "Y is an S pole, and the needle’s S pole will point to Z."],
        a: 0,
        why: "The needle’s S pole is attracted to Y, so Y is the unlike pole, N. The other end, Z, must be an S pole, so it attracts the needle’s N pole."
      }
    }
  ],
  flash: [
    { f: "Why does a fridge door seal contain a magnetic strip?", b: "The magnetic strip attracts the steel body of the fridge, so the door stays tightly shut and the cold air does not escape." },
    { f: "Why does a scrapyard crane use an electromagnet instead of a permanent magnet?", b: "An electromagnet can be switched off, so the crane can release (drop) the iron and steel objects where it wants them." },
    { f: "What happens when a bar magnet is broken into two pieces?", b: "Each piece becomes a new, smaller magnet with both an N pole and an S pole." },
    { f: "Where are the poles of a ring magnet?", b: "On its two flat faces – one face is the N pole and the opposite face is the S pole." },
    { f: "Floating ring magnets: why is the lowest gap usually the smallest?", b: "The weight of all the rings above presses down on the lowest floating ring, pushing it closer to the ring below. The closer the like poles, the stronger they repel, so it can hold up this weight." },
    { f: "An iron rod is brought near the N pole, then the S pole, of a magnet. What happens?", b: "It is attracted by both poles. It never repels, because iron is a magnetic material but not a magnet." },
    { f: "How does distance affect the magnetic force on an object?", b: "The greater the distance between the magnet and the object, the weaker the magnetic force on the object." },
    { f: "Why can a paper clip hanging from a magnet hold up another paper clip?", b: "The steel clip touching the magnet becomes a temporary magnet, so it can attract the next clip." },
    { f: "An iron nail electromagnet is holding up paper clips. What happens when the switch is opened?", b: "The current stops flowing through the coil, so the iron nail loses its magnetism and the paper clips drop off." },
    { f: "Why must a compass be kept away from magnets and steel objects?", b: "The compass needle is a small magnet. It is attracted by magnets and steel objects nearby, so it will not point north-south correctly." },
    { f: "Which pole of a compass needle points towards the S pole of a bar magnet?", b: "The N pole of the needle, because unlike poles attract." },
    { f: "Must a magnet touch an object to attract it?", b: "No. A magnet can attract a magnetic material, or attract or repel another magnet, from a distance without touching it." }
  ],
  mcq: [
    { q: "Mdm Tan is tidying the kitchen of her HDB flat. Which of these items will a magnet attract?", o: ["A copper kettle", "An aluminium tray", "An iron wok", "A glass bowl"], a: 2, why: "Iron is a magnetic material. Copper and aluminium are metals but are non-magnetic, and glass is non-magnetic.", lvl: 1 },
    { q: "Which part of a compass is a small magnet?", o: ["The needle", "The plastic case", "The glass cover", "The direction card"], a: 0, why: "The compass needle is a small magnet, so it turns to point north-south. The case, cover and card are not magnets.", lvl: 1 },
    { q: "A magnet pulls a steel paper clip towards it before they touch. This shows that magnetic force ______.", o: ["needs air to pass through", "can act from a distance", "only acts on shiny objects", "is strongest in the middle"], a: 1, why: "The clip moves before it touches the magnet, so the magnetic force acts from a distance. It also acts through water and other non-magnetic materials, not only air.", lvl: 1 },
    { q: "Which of these is needed to make an iron nail into a magnet by the electrical method?", o: ["A long string and a stand", "A plastic comb and a dry cloth", "A hammer and a heavy wooden block", "Insulated wire and a battery"], a: 3, why: "In the electrical method, insulated wire is wound around the nail and connected to a battery. When current flows, the nail becomes an electromagnet.", lvl: 1 },
    { q: "Two ring magnets are on a wooden rod as shown. B touches A, and the top face of A is an S pole. What is the pole on the top face of B?", o: ["N pole", "Both N and S", "S pole", "It cannot be told"], a: 2, why: "B touches A, so they attract and unlike poles face each other: B’s bottom face is N. The top face of a ring is opposite to its bottom face, so B’s top face is S.", lvl: 2, fig: { type: "rings", rings: [{ label: "A", top: "S" }, { label: "B", top: "?" }], gaps: [false] } },
    { q: "Ravi tested some objects from his pencil case with a magnet and recorded his results. One result must be a mistake. Which object’s result is wrong?", o: ["Ruler", "Eraser", "Sharpener blade", "Pencil"], a: 0, why: "Aluminium is a non-magnetic metal, so the aluminium ruler cannot be attracted. The other results are correct: steel is magnetic, and rubber and wood are not.", lvl: 2, tbl: [["Object", "Material", "Attracted by magnet?"], ["Eraser", "Rubber", "No"], ["Sharpener blade", "Steel", "Yes"], ["Ruler", "Aluminium", "Yes"], ["Pencil", "Wood", "No"]] },
    { q: "Mr Lim wants to use magnets to put up notices in the school staff room. On which surface will the magnets NOT stay?", o: ["A steel whiteboard", "A steel cupboard door", "A steel filing cabinet", "A glass window pane"], a: 3, why: "Glass is non-magnetic, so the magnets are not attracted to it and will fall off. Steel is a magnetic material, so the magnets stick to the other three.", lvl: 2 },
    { q: "Magnets A and B attract each other as shown. Ali turns magnet B around so that its other end faces A. What will happen?", o: ["They still attract.", "Nothing happens.", "They attract more strongly.", "They repel."], a: 3, why: "A’s right end is S. They attract, so B’s left end is N and its right end is S. After turning B around, its S end faces A’s S end. Like poles repel.", lvl: 2, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }], between: ["attract"] } },
    { q: "Jia Hui wants to find out whether the type of material of a sheet placed between a magnet and some paper clips affects the number of clips attracted. The same kind of paper clips is used in every set-up. Which two set-ups should she use?", o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ only in the type of material; the thickness and the magnet are the same. A and C, and B and D, change the thickness, and D also uses a different magnet.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Plastic sheet", "2 mm thick", "Magnet P"] }, { label: "B", icon: "plate", lines: ["Glass sheet", "2 mm thick", "Magnet P"] }, { label: "C", icon: "plate", lines: ["Plastic sheet", "5 mm thick", "Magnet P"] }, { label: "D", icon: "plate", lines: ["Glass sheet", "5 mm thick", "Magnet Q"] }] } },
    { q: "Uncle Ahmad is fixing an air-conditioner in an HDB flat. He uses a screwdriver with a magnetic tip. Why is this useful?", o: ["It holds the steel screws so they do not fall.", "It makes the steel screws turn faster.", "It makes brass screws stick to the tip too.", "It makes the steel screws harder to bend."], a: 0, why: "Steel is a magnetic material, so the magnetic tip attracts and holds the screws. Brass is non-magnetic, so brass screws would not stick.", lvl: 2 },
    { q: "A magnetic catch keeps a kitchen cabinet door in an HDB flat shut. A magnet is fixed to the cabinet and a steel plate to the wooden door. After many months of the door being slammed hard, it keeps swinging open. What is the most likely reason?", o: ["The steel plate has turned into a magnet.", "The magnet has become weaker after many hard knocks.", "The paint on the plate blocks the magnetic force.", "The wooden door blocks the magnetic force."], a: 1, why: "Hard knocks, like dropping or hammering, can make a magnet lose some magnetism, so it attracts the plate less strongly. Paint and wood are non-magnetic and do not block magnetic force.", lvl: 2 },
    { q: "A bar magnet is cut into three pieces. Which of these statements are correct?\nA: Each piece has an N pole and an S pole.\nB: The middle piece is not a magnet.\nC: Each piece can attract a steel pin.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Every piece of a broken magnet, including the middle piece, becomes a new magnet with an N and an S pole, so A and C are correct. B is wrong.", lvl: 3 },
    { q: "Four ring magnets are on a wooden rod as shown. B floats above A, C touches B, and D floats above C. The top face of C is an S pole. Which two rings have an N pole on their top face?", o: ["A and B", "B and C", "B and D", "A and D"], a: 3, why: "C’s bottom is N. C touches B, so B’s top is S and its bottom is N. B floats above A, so A’s top is also N. D floats above C, so D’s bottom is S and its top is N. So A and D.", lvl: 3, fig: { type: "rings", rings: [{ label: "A", top: "?" }, { label: "B", top: "?" }, { label: "C", top: "S" }, { label: "D", top: "?" }], gaps: [true, false, true] } },
    { q: "Which of these is NOT a correct step when making a magnet by the stroke method?", o: ["Use the same pole of the magnet for every stroke.", "Lift the magnet away at the end of each stroke.", "Stroke the bar both ways to make it faster.", "Stroke the bar many times, not just once or twice."], a: 2, why: "The bar must be stroked in ONE direction only. Stroking back and forth undoes the magnetism. The other three are correct steps.", lvl: 3 },
    { q: "Aini placed different numbers of plastic sheets between a magnet and a pile of steel paper clips and counted the clips attracted. She made a mistake in one reading. Which reading is most likely to be wrong?", o: ["1 sheet", "2 sheets", "3 sheets", "4 sheets"], a: 2, why: "More sheets put the clips further from the magnet, so fewer clips should be attracted each time. 13 clips with 3 sheets is more than with 1 or 2 sheets, which breaks the pattern (about 6 is expected).", lvl: 3, tbl: [["Number of plastic sheets", "Number of clips attracted"], ["0", "15"], ["1", "12"], ["2", "9"], ["3", "13"], ["4", "3"]] },
    { q: "A, B and C are magnets. A attracts B, and B attracts C, as shown. Magnet B is taken out, turned around and put back. What will happen?", o: ["B attracts both A and C.", "B repels both A and C.", "B repels A but attracts C.", "B attracts A but repels C."], a: 1, why: "A’s right end is N, so B’s left end is S and its right end is N; C’s left end is S. After turning, B’s N faces A’s N and B’s S faces C’s S. Like poles repel on both sides.", lvl: 3, fig: { type: "magnets", items: [{ label: "A", poles: "SN" }, { label: "B", poles: "??" }, { label: "C", poles: "??" }], between: ["attract", "attract"] } },
    { q: "Four electromagnets were made with the same iron nail. Which two set-ups show whether the number of batteries affects the strength of the electromagnet?", o: ["A and B", "C and D", "B and C", "A and D"], a: 2, why: "B and C have the same number of coils (20) and differ only in the number of batteries. Every other pair changes the number of coils, so it is not a fair test.", lvl: 3, tbl: [["Set-up", "Number of coils", "Number of batteries", "Clips attracted"], ["A", "10", "1", "5"], ["B", "20", "1", "9"], ["C", "20", "2", "15"], ["D", "30", "2", "18"]] },
    { q: "Three ring magnets A, B and C float apart on a wooden rod as shown. None of the poles are labelled. Mei lifts C off, slides B off, and then puts C back on the rod the same way up as before. What will happen?", o: ["C floats above A.", "C floats higher above A than it did above B.", "It cannot be told because the poles are not labelled.", "C sticks to A."], a: 3, why: "A’s top face is the same pole as B’s bottom face (they repel), and B’s top face is the same pole as C’s bottom face. B’s two faces are opposite, so A’s top and C’s bottom are unlike poles. They attract, so C sticks to A.", lvl: 4, fig: { type: "rings", rings: [{ label: "A", top: "?" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, true] } },
    { q: "P, Q, R and S are four bars. Each one is either a magnet or a plain iron bar. P attracts Q, Q repels R, and R attracts S, as shown. Which bars MUST be magnets?", o: ["Q and R only", "P, Q and R only", "Q, R and S only", "P, Q, R and S"], a: 0, why: "Only a magnet can repel a magnet, so Q and R must both be magnets. P and S are only attracted, so each could be a magnet or a plain iron bar.", lvl: 4, fig: { type: "magnets", items: [{ label: "P", kind: "bar", text: "?" }, { label: "Q", kind: "bar", text: "?" }, { label: "R", kind: "bar", text: "?" }, { label: "S", kind: "bar", text: "?" }], between: ["attract", "repel", "attract"] } },
    { q: "Steel bar PQ was stroked many times from end P to end Q with the S pole of a magnet. It was then hung freely from a string, away from other magnets. Which is correct?", o: ["P points north, and P repels the N pole of a compass needle.", "Q points north, and P attracts the N pole of a compass needle.", "Q points north, and P repels the N pole of a compass needle.", "P points north, and P attracts the N pole of a compass needle."], a: 1, why: "Each stroke ends at Q, so Q becomes the opposite pole to S, an N pole, and P is an S pole. The N pole of a freely hung magnet points north, so Q points north. P (S) attracts the needle’s N pole.", lvl: 4 }
  ],
  oe: [
    { q: "Magnet A and magnet B are placed as shown, and they repel each other. (a) What is the pole at the left end of magnet B? Write the word in full. [1] (b) Explain your answer to (a). [1] (c) Magnet B is replaced by an iron bar of the same size. Predict what happens when the iron bar is pushed towards A, and explain why. [2]", marks: 4, kw: [["south"], ["like poles", "same poles", "same pole"], ["attract", "pulled", "pull"], ["magnetic material", "not a magnet", "iron is magnetic"]], model: "(a) South. (b) The right end of A is an S pole. A and B repel, and like poles repel, so the left end of B is also an S pole. (c) The iron bar will be attracted to A. Iron is a magnetic material but it is not a magnet, so it is attracted by either pole of A and cannot repel it.", fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }], between: ["repel"] } },
    { q: "Mrs Goh tested four fridge magnets, P, Q, R and S. For each one, she found the greatest number of sheets of paper it could hold up on the same steel fridge door. Study her results. (a) Which magnet is the strongest? [1] (b) Explain your answer using the results. [1] (c) State one thing about the sheets of paper that she must keep the same for a fair test. [1] (d) Her new fridge has an aluminium door. Explain why none of the magnets stick to it. [1]", marks: 4, kw: [["q"], ["most sheets", "most paper", "the most", "greatest number", "largest number", "highest number"], ["size", "type", "thickness", "kind"], ["non magnetic", "not a magnetic", "not magnetic", "not attracted"]], model: "(a) Q. (b) Magnet Q held up the most sheets of paper (11), so it has the strongest magnetic force. (c) The size, type and thickness of the paper must be the same. (d) Aluminium is a non-magnetic material, so it is not attracted by the magnets.", tbl: [["Fridge magnet", "Greatest number of sheets held"], ["P", "4"], ["Q", "11"], ["R", "7"], ["S", "2"]] },
    { q: "Three ring magnets A, B and C float apart on a wooden rod as shown. The top face of A is an N pole. (a) What is the pole on the top face of C? Write the word in full. [1] (b) Mei lifts C off, slides B off, and puts C back on the rod the same way up. Predict what happens to C and explain why. [2] (c) Suggest what Mei should do so that C floats above A. [1]", marks: 4, x: 1, kw: [["north"], ["stick", "touch", "rests on", "attract", "pulled down", "no gap"], ["unlike poles", "opposite poles", "different poles"], ["upside down", "turn c over", "turn it over", "flip", "other way up", "turn c around", "turn it around"]], model: "(a) North. (b) C will move down and stick to A. The bottom face of C is an S pole and the top face of A is an N pole, so unlike poles face each other and attract. (c) Turn C upside down before putting it back on the rod.", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, true] } },
    { q: "Hui Min wanted to make a steel nail into a magnet. She rubbed the N pole of a magnet back and forth along the nail 5 times without lifting the magnet. The nail could not pick up any pins. (a) State two mistakes in her method. [2] (b) She then stroked the nail correctly, from its head to its tip, with the N pole. Which end of the nail becomes the N pole? [1] (c) How can she use a bar magnet to show for sure that the nail is now a magnet? [1]", marks: 4, kw: [["one direction", "same direction", "back and forth", "not in one direction", "not stroke in one", "both directions", "both ways"], ["lift", "not lift", "without lift", "more times", "many times", "too few", "only 5"], ["head"], ["repel", "push away", "pushed away", "pushes away"]], model: "(a) She rubbed back and forth instead of stroking in one direction only. She should have lifted the magnet away after each stroke and stroked many more times than 5. (b) The head. Each stroke ends at the tip, so the tip becomes an S pole and the head becomes an N pole. (c) Bring one end of the nail near the N pole and then the S pole of a bar magnet. If that end is repelled by one of the poles, the nail is a magnet." }
  ],
  tf: [
    { s: "A U-shaped magnet is strongest at the bend in the middle.", a: false, why: "Like every magnet, it is strongest at its two poles, which are the two ends of the U." },
    { s: "A magnet can attract another magnet as well as a piece of iron.", a: true, why: "A magnet attracts the unlike pole of another magnet and also attracts magnetic materials such as iron." },
    { s: "A plastic ruler can be made into a magnet by stroking it many times with a magnet.", a: false, why: "Plastic is non-magnetic. Only magnetic materials such as steel can be made into magnets." },
    { s: "A scrapyard crane drops the steel objects it is holding when the current to its electromagnet is switched off.", a: true, why: "The electromagnet loses its magnetism when the current stops, so it no longer attracts the steel objects." },
    { s: "Every object that a magnet attracts is made of iron.", a: false, why: "A magnet also attracts objects made of steel, nickel and cobalt, as well as other magnets." },
    { s: "A steel bar can be made into a magnet by placing it inside a coil of insulated wire connected to a battery.", a: true, why: "This is the electrical method. The current in the coil magnetises the steel, and steel keeps some magnetism afterwards." },
    { s: "If magnet M attracts rod R, turning R around will always make them repel.", a: false, why: "R may be a magnetic material such as iron, which is attracted by both poles and never repels. Only a magnet would be repelled." },
    { s: "A magnet can make another magnet move without touching it.", a: true, why: "Magnetic force acts from a distance, so a magnet can attract or repel another magnet without touching it." },
    { s: "Heating a magnet strongly makes it a stronger magnet.", a: false, why: "Strong heating makes a magnet lose some or all of its magnetism." },
    { s: "A magnet held under a thin wooden table top can move a steel paper clip lying on top of the table.", a: true, why: "Magnetic force can pass through non-magnetic materials such as wood, so the clip is still attracted." }
  ]
};
