window.BANKU = window.BANKU || {};
BANKU["materials"] = {
  glossary: [
    { t: "Material", d: "The substance used to make an object, e.g. wood, metal, plastic, glass, ceramic, rubber, fabric or paper." },
    { t: "Property of a material", d: "A feature that tells us what a material is like or how it behaves, e.g. strong, hard, flexible, waterproof or transparent." },
    { t: "Strength", d: "How well a material can hold a heavy load or withstand a force without breaking." },
    { t: "Hardness", d: "How difficult it is to scratch or dent a material. A harder material can scratch a softer material." },
    { t: "Flexibility", d: "The ability of a material to bend without breaking." },
    { t: "Waterproof", d: "Describes a material that does not let water pass through it or soak into it, e.g. plastic, rubber, glass and metal." },
    { t: "Absorbent", d: "Able to soak up and hold water, e.g. sponge, cotton cloth and paper towel." },
    { t: "Transparent", d: "Allows most light to pass through, so objects behind it can be seen clearly." },
    { t: "Translucent", d: "Allows some light to pass through, so objects behind it look blurred." },
    { t: "Opaque", d: "Allows no light to pass through, so objects behind it cannot be seen." },
    { t: "Scratch test", d: "A test for hardness: two materials are rubbed against each other, and the material that leaves a mark on the other is the harder one." },
    { t: "Fair test", d: "An experiment in which only one variable is changed and all other variables are kept the same, so any difference in the results is caused by that one variable." }
  ],
  lessons: [
    {
      h: "Planning a test: change, keep, measure, decide",
      concept: "When a question says ‘Describe how you would find out which material is the most …’, a full-mark plan has four parts. Say what you CHANGE (only the type of material), what you KEEP THE SAME (size, thickness, amount of water, weights, time), what you MEASURE (the result), and how you DECIDE which material is best from that result. Missing any one part usually costs a mark.",
      example: {
        q: "Ali has three types of cloth. Describe how he can carry out a fair test to find out which cloth is the most waterproof.",
        marks: 3,
        think: [
          "Step 1: CHANGE – only the type of cloth is different in each set-up.",
          "Step 2: KEEP THE SAME – give real details: the same size of each piece, stretched over the same kind of cup, with the same amount of water (e.g. 50 ml) poured on each.",
          "Step 3: MEASURE – the amount of water that drips through each cloth into the cup after the same time.",
          "Step 4: DECIDE – the cloth that lets the least water drip through is the most waterproof. Without this sentence, the plan has no way to reach a conclusion."
        ],
        answer: "Ali cuts the three cloths into pieces of the same size and stretches each piece over a cup. He pours the same amount of water (50 ml) onto each cloth. After 1 minute, he measures the amount of water that has dripped into each cup. The cloth that lets the least water drip through is the most waterproof."
      },
      tip: "Plan = Change one, Keep the rest, Measure, Decide. Write one sentence for each part.",
      try: {
        q: "Mei wants to find out which of three types of string is the strongest. Which plan is the best?",
        o: ["Use strings of different lengths, add weights one at a time, and count the weights each one holds before it snaps.", "Use strings of the same length and thickness, hang one heavy weight on each, and see whether each string bends.", "Use strings of the same length and thickness, add weights one at a time, and count the weights each holds before it snaps.", "Use strings of the same length and thickness, pull each one by hand, and choose the string that feels the strongest."],
        a: 2,
        why: "This plan keeps length and thickness the same, changes only the type of string, and measures a clear result (weights held before snapping). Different lengths make the test unfair, bending shows flexibility not strength, and ‘feels the strongest’ is not a measurement."
      }
    },
    {
      h: "Reliable results: repeat the test, spot the odd result",
      concept: "One result can be wrong because of a mistake, such as misreading a measuring cylinder or using a strip that was already torn. Repeating the test (e.g. three times) and getting similar results makes the results reliable. A result that is very different from the others for the same material is most likely a mistake and should be checked by repeating that test. Remember: keeping other variables the same makes a test FAIR; repeating it makes the results RELIABLE.",
      example: {
        q: "Siti tested three brands of paper towel of the same size. Each piece was dipped in 100 ml of water, and she measured the water absorbed. She did the test three times for each brand. (a) Why did she repeat the test three times? (b) Which result is most likely a mistake? (c) Which brand is most likely the most absorbent?",
        tbl: [["Brand", "Test 1 (ml)", "Test 2 (ml)", "Test 3 (ml)"], ["A", "30", "32", "31"], ["B", "45", "18", "44"], ["C", "38", "39", "38"]],
        marks: 3,
        think: [
          "Step 1: Repeating is about trust, not fairness. Similar results from repeated tests mean the results are reliable.",
          "Step 2: Read across each row. A and C give close results each time. Brand B gives 45 and 44, but 18 in Test 2, which is far from the other two.",
          "Step 3: The odd result (B, Test 2) should be checked by repeating that test, not used to decide the answer.",
          "Step 4: Using the results that agree, B absorbed about 44–45 ml, more than A (about 31 ml) or C (about 38 ml)."
        ],
        answer: "(a) To make her results reliable: if the results for each brand are similar, she can trust them. (b) Brand B, Test 2 (18 ml), because it is very different from B’s other results of 45 ml and 44 ml. (c) Brand B, because in the results that agree it absorbed the most water (about 45 ml)."
      },
      tip: "Fair = keep the other variables the same. Reliable = repeat and get similar results. Do not mix them up.",
      try: {
        q: "Ravi tested strings X, Y and Z of the same length and thickness, once each. X held 7 weights, Y held 8 and Z held 4. His teacher says his results may not be reliable. What should Ravi do?",
        o: ["Change the type of weights for each string that he tests", "Repeat the test two more times for each string and compare", "Use a thicker piece of string X so that it holds more weights", "Test only string Y again, because it held the most weights"],
        a: 1,
        why: "Repeating the test for every string shows whether the results are similar each time, so they can be trusted. X and Y are very close, so one test is not enough to decide. Changing the weights or the thickness makes the test unfair, and testing only Y cannot check X and Z."
      }
    }
  ],
  flash: [
    { f: "How do you test which material is the strongest?", b: "Hang strips of the same size and add weights one at a time. The strip that holds the most weights before it breaks is the strongest." },
    { f: "How do you test which material is the most flexible?", b: "Clamp strips of the same size to a table and hang the same weight at each free end. The strip that bends the most without breaking is the most flexible." },
    { f: "How do you test which material is the most waterproof?", b: "Stretch the same size of each material over a cup and pour the same amount of water on each. The one that lets the least water drip through is the most waterproof." },
    { f: "How do you test which material lets the most light through?", b: "Place each material between a torch and a light sensor at the same distance. The material that gives the highest light reading lets the most light pass through." },
    { f: "Why is an umbrella made of more than one material?", b: "Each part needs a different property: the canopy is waterproof, so rain cannot pass through, and the metal frame is strong, so it holds the canopy open without breaking." },
    { f: "Why is cotton NOT suitable for a raincoat?", b: "Cotton absorbs water and is not waterproof, so the rain would soak through and the wearer would get wet." },
    { f: "Why is a mop head made of cotton strands or sponge?", b: "Cotton and sponge are absorbent, so the mop head can soak up water and spills from the floor." },
    { f: "Can a material that absorbs water still float?", b: "Yes. A dry kitchen sponge absorbs water, yet it floats. Absorbing water and floating are different properties." },
    { f: "Is coloured glass always opaque?", b: "No. A green glass bottle is coloured, but it lets most light pass through and we can see clearly through it, so it is transparent." },
    { f: "Why are rubber gloves used for washing dishes?", b: "Rubber is waterproof, so water cannot pass through and the hands stay dry, and it is flexible, so the fingers can bend easily." },
    { f: "Strength test: what is changed, kept the same and measured?", b: "Changed: the type of material. Kept the same: the length, width and thickness of the strips and the mass of each weight. Measured: the number of weights held before breaking." },
    { f: "Why do we repeat an experiment?", b: "To make the results reliable. If the repeated results are similar, we can trust them; a result that is very different is likely a mistake and should be checked." }
  ],
  mcq: [
    { q: "Which of these is NOT a material?", o: ["Glass", "Rubber", "Spoon", "Wood"], a: 2, why: "A spoon is an object; it can be made of materials such as metal, plastic or wood. Glass, rubber and wood are materials.", lvl: 1 },
    { q: "Which group contains only opaque materials?", o: ["Wood, steel and cardboard", "Clear glass, wood and steel", "Tracing paper, cardboard and wood", "Frosted glass, steel and wood"], a: 0, why: "Wood, steel and cardboard let no light through. Clear glass is transparent, and tracing paper and frosted glass are translucent, so each other group has a material that lets light through.", lvl: 1 },
    { q: "Siti can bend and twist a rubber band without breaking it. This shows that rubber is ______.", o: ["hard", "transparent", "absorbent", "flexible"], a: 3, why: "Bending without breaking means the material is flexible. It says nothing about hardness, light or water.", lvl: 1 },
    { q: "Which of these objects will sink in a basin of water?", o: ["A cork stopper", "A steel key", "A wooden chopstick", "A ping-pong ball"], a: 1, why: "A solid steel key sinks. Cork, wood and a plastic ping-pong ball all float.", lvl: 1 },
    { q: "A drinks-stall auntie at a hawker centre wears rubber gloves to wash cups. Which two properties of rubber make the gloves suitable?", o: ["Hard and transparent", "Absorbent and flexible", "Waterproof and hard", "Waterproof and flexible"], a: 3, why: "Rubber is waterproof, so her hands stay dry, and flexible, so her fingers can bend. Rubber is not transparent, not absorbent and not hard.", lvl: 2 },
    { q: "Drops of water were added one at a time to four pieces of paper towel of the same size until each piece could not absorb any more. The graph shows the number of drops each piece absorbed. Which paper towel is the most suitable for wiping up spilt drinks in the school canteen?", o: ["A", "B", "C", "D"], a: 1, why: "B absorbed the most drops (32), so it is the most absorbent. Here the tallest bar is best because the graph shows water absorbed; C absorbed the fewest drops.", lvl: 2, fig: { type: "bar", xl: "Paper towel", yl: "Number of drops absorbed", bars: [["A", 15], ["B", 32], ["C", 8], ["D", 24]] } },
    { q: "Which of these objects are made of more than one material?\nA: a wooden pencil with a rubber eraser at one end\nB: a glass marble\nC: an umbrella\nD: a rubber band", o: ["A and B only", "B and D only", "A and C only", "A, C and D only"], a: 2, why: "The pencil has wood and rubber, and the umbrella has a waterproof canopy and a metal frame. The glass marble and the rubber band are each made of one material.", lvl: 2 },
    { q: "Mei placed each sheet in turn between a torch and a white screen, as shown. Predict which sheet will give a dim, blurred patch of light on the screen.", o: ["A", "B", "C", "D"], a: 1, why: "Tracing paper is translucent, so only some light reaches the screen. Clear plastic lets most light through (a bright patch), while cardboard and aluminium foil are opaque (no patch at all).", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Clear plastic sheet", "Torch 30 cm away"] }, { label: "B", icon: "box", lines: ["Tracing paper", "Torch 30 cm away"] }, { label: "C", icon: "box", lines: ["Cardboard", "Torch 30 cm away"] }, { label: "D", icon: "box", lines: ["Aluminium foil", "Torch 30 cm away"] }] } },
    { q: "At a kopitiam, takeaway kopi is often poured into a plastic bag. Why is plastic suitable?", o: ["It is waterproof, so the kopi does not leak out.", "It is absorbent, so it soaks up spilt kopi.", "It is opaque, so no light can reach the kopi.", "It is hard, so it cannot be scratched easily."], a: 0, why: "The bag must hold the drink, so it must be waterproof. A plastic bag does not absorb water, is often see-through, and is not hard.", lvl: 2 },
    { q: "Rubber slippers are often worn at public swimming pools. Which of these is NOT a reason why rubber is suitable?", o: ["It is flexible.", "It is waterproof.", "It is transparent.", "It is strong."], a: 2, why: "Rubber is opaque, not transparent, and seeing through a slipper would not help anyway. Rubber bends as we walk, keeps water out and does not break easily.", lvl: 2 },
    { q: "Siti wants to find out whether the type of plastic affects how far a strip bends when the same weight is hung at its end. Which two strips should she compare?", o: ["P and S", "Q and R", "R and S", "P and Q"], a: 3, why: "P and Q differ only in the type of plastic; length and thickness are the same. P and S are the same plastic, Q and R differ in length, and R and S differ in three things.", lvl: 2, tbl: [["Strip", "Type of plastic", "Length (cm)", "Thickness (mm)"], ["P", "A", "20", "1"], ["Q", "B", "20", "1"], ["R", "B", "25", "1"], ["S", "A", "20", "2"]] },
    { q: "Jun clamped a plastic strip to a table and hung 10 g weights at its free end, one at a time. The graph shows how far the end bent down. Which statement is correct?", o: ["With 5 weights, the end would bend down 12 cm.", "With 3 weights, the end bent down 8 cm.", "Each extra weight made the end bend 2 cm more.", "The end bent the same distance for every weight."], a: 2, why: "The readings go 0, 2, 4, 6, 8 cm, so each weight adds 2 cm. Following the pattern, 5 weights would give 10 cm, not 12 cm, and 3 weights gave 6 cm, not 8 cm.", lvl: 3, fig: { type: "line", xl: "Number of 10 g weights", yl: "Distance end bent down (cm)", pts: [["0", 0], ["1", 2], ["2", 4], ["3", 6], ["4", 8]] } },
    { q: "Pieces of three materials of the same size were tested. Study the table. Which statements are correct?\nA: K could be clear plastic.\nB: L could be a cotton towel.\nC: M is transparent.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "K absorbed no water and let almost all light through, like clear plastic (A). L absorbed water and let no light through, like a cotton towel (B). M let only some light through, so it is translucent, not transparent (C is wrong).", lvl: 3, tbl: [["Material", "Water absorbed (ml)", "Light reading (units)"], ["No material", "-", "100"], ["K", "0", "95"], ["L", "40", "0"], ["M", "0", "45"]] },
    { q: "Four materials were used to scratch one another. Study the results. Which conclusion is NOT correct?", o: ["E is harder than H.", "F is softer than E.", "H cannot scratch F.", "G is harder than F."], a: 3, why: "F left a mark on G, so F is harder than G, not the other way round. E scratched F, and F scratched H, so E is harder than H; H is softer than F, so it cannot scratch F.", lvl: 3, tbl: [["Material used to scratch", "Materials it left a mark on"], ["E", "F"], ["F", "G and H"], ["G", "H"], ["H", "none"]] },
    { q: "Four cloths of the same size were each dipped into a beaker containing 100 ml of water and then taken out. The graph shows the water ABSORBED by each cloth. Which statement is NOT true?", o: ["R left the least water in its beaker.", "Q and S absorbed the same amount of water.", "P left 70 ml of water in its beaker.", "R absorbed 25 ml less water than Q."], a: 0, why: "R absorbed 50 ml, so it left 50 ml; Q and S each absorbed 75 ml and left only 25 ml, the least. P absorbed 30 ml, so it left 70 ml, and 75 − 50 = 25 ml.", lvl: 3, fig: { type: "bar", xl: "Cloth", yl: "Water absorbed (ml)", bars: [["P", 30], ["Q", 75], ["R", 50], ["S", 75]] } },
    { q: "Study the Venn diagram. Which set of objects could be K, L, M and N?", o: ["K: cling wrap, L: rubber glove, M: frosted glass, N: wooden block", "K: rubber glove, L: frosted glass, M: cling wrap, N: wooden block", "K: rubber glove, L: cling wrap, M: frosted glass, N: wooden block", "K: rubber glove, L: cling wrap, M: wooden block, N: frosted glass"], a: 2, why: "A rubber glove bends but blocks light (K); cling wrap bends and lets light through (L); frosted glass lets some light through but cannot bend (M); a wooden block does neither (N). Frosted glass is translucent, so it still counts as letting light through.", lvl: 3, fig: { type: "venn", a: "Flexible", b: "Lets light through", onlyA: ["K"], both: ["L"], onlyB: ["M"], neither: ["N"] } },
    { q: "Ravi tested three brands of paper towel for the school canteen, once each. He says Brand B is the most absorbent. What should he do to make his conclusion more reliable?", o: ["Use a bigger piece of Brand C, as it absorbed the least", "Repeat the test a few more times for each brand", "Use less water for Brand A so it is tested fairly", "Choose Brand B now, as its result is the highest"], a: 1, why: "The results are very close (40 to 42 ml), so one test is not enough to be sure. Repeating the test and getting similar results makes them reliable. Changing the size or the water would make the test unfair.", lvl: 3, tbl: [["Brand", "Water absorbed (ml)"], ["A", "41"], ["B", "42"], ["C", "40"]] },
    { q: "Two different sponges of the same size were each put into a container with 200 ml of water. The water left was measured every minute. Which statements are correct?\nA: In the first minute, P absorbed more water than Q.\nB: In total, Q absorbed more water than P.\nC: Both sponges stopped absorbing water at the same time.", o: ["A only", "B and C only", "A and C only", "A and B only"], a: 3, why: "In the first minute P absorbed 50 ml but Q only 30 ml (A). In total P absorbed 90 ml and Q 100 ml (B). P’s reading stopped changing after 3 minutes but Q’s after 4 minutes, so C is wrong.", lvl: 4, tbl: [["Time (min)", "Water left with sponge P (ml)", "Water left with sponge Q (ml)"], ["0", "200", "200"], ["1", "150", "170"], ["2", "120", "140"], ["3", "110", "110"], ["4", "110", "100"], ["5", "110", "100"]] },
    { q: "Material X was put through three tests. Study the results. Which material could X be?", o: ["Frosted plastic sheet", "Clear plastic sheet", "Frosted glass", "Thin rubber sheet"], a: 0, why: "A reading of 40 means only some light passed through (translucent); no water was absorbed (waterproof); and it bent without breaking (flexible). Clear plastic lets most light through, frosted glass cannot bend, and rubber lets no light through.", lvl: 4, tbl: [["Test", "Result for material X"], ["Light sensor reading (no material: 100 units)", "40 units"], ["Water left after dipping X in 100 ml of water", "100 ml"], ["Same-size strip with 100 g weight at its end", "Bent 4 cm, did not break"]] },
    { q: "Mei wants to find out whether wetting newspaper makes it weaker. All the strips are the same length. Which two strips should she compare, and which result would show that wet newspaper is weaker?", o: ["P and Q; Q holds fewer weights than P", "P and Q; Q holds more weights than P", "Q and R; R holds fewer weights than Q", "P and S; S holds fewer weights than P"], a: 0, why: "P and Q are both newspaper of the same width and differ only in being dry or wet. If the wet strip Q holds fewer weights before tearing, wet newspaper is weaker. Q and R differ in the type of paper, and P and S differ in both wetness and width.", lvl: 4, tbl: [["Strip", "Type of paper", "Dry or wet", "Width (cm)"], ["P", "Newspaper", "Dry", "3"], ["Q", "Newspaper", "Wet", "3"], ["R", "Drawing paper", "Wet", "3"], ["S", "Newspaper", "Wet", "5"]] }
  ],
  oe: [
    { q: "Ben shone a torch through layers of tracing paper onto a light sensor, adding one layer at a time. The graph shows the light readings. With no tracing paper, the reading was 100 units. (a) What happens to the light reading as more layers are added? [1] (b) Is one layer of tracing paper transparent, translucent or opaque? [1] (c) Explain your answer to (b) using the graph. [1] (d) State one variable Ben must keep the same. [1]", marks: 4, x: 1, kw: [["decrease", "less", "lower", "drops", "goes down", "falls", "smaller"], ["translucent"], ["some light", "part of the light", "not all", "70"], ["distance", "same torch", "same light sensor", "same sensor", "same brightness", "same type of tracing paper", "same size"]], model: "(a) The light reading decreases as more layers are added. (b) Translucent. (c) With one layer, the reading was 70 units, which is less than 100 units but more than 0, so some light passes through but not all of it. (d) The distance between the torch and the light sensor.", fig: { type: "line", xl: "Number of layers of tracing paper", yl: "Light reading (units)", pts: [["0", 100], ["1", 70], ["2", 50], ["3", 35], ["4", 25]] } },
    { q: "Mei stretched four fabrics of the same size over four cups and poured 50 ml of water onto each. The table shows the water that dripped into each cup. (a) Which fabric is the most suitable for a school bag that keeps books dry in the rain? [1] (b) Explain your answer using the results. [1] (c) State one other property the school bag material should have, and explain why. [1]", marks: 3, kw: [["nylon"], ["no water", "0 ml", "0ml", "none", "did not let", "least water", "zero"], ["strong", "tear", "flexible", "bend"]], model: "(a) Nylon. (b) No water (0 ml) dripped through the nylon, so it does not let water pass through and the books stay dry. (c) It should be strong, so it can hold heavy books without tearing.", tbl: [["Fabric", "Water that dripped into cup (ml)"], ["Canvas", "12"], ["Nylon", "0"], ["Cotton", "30"], ["Felt", "20"]] },
    { q: "Kickboards used during swimming lessons at public pools in Singapore are made of foam. (a) Which property of foam makes it suitable for a kickboard? [1] (b) Explain why a kickboard made of steel would NOT be suitable. [1] (c) State one other property the kickboard material should have, and explain why. [1]", marks: 3, kw: [["float"], ["sink", "not float"], ["strong", "break", "waterproof", "not absorb", "not soak", "flexible"]], model: "(a) Foam floats on water, so it helps to hold the swimmer up. (b) Steel sinks in water, so the kickboard would not hold the swimmer up. (c) It must be strong, so it does not break when a child leans on it." },
    { q: "Siti tested four materials of the same size for a shower screen in an HDB bathroom. The screen must let some light through but stop people seeing in clearly, keep the water in, and not break easily. (a) Which material is the most suitable? [1] (b) Explain why J is not suitable. [1] (c) Explain why L is not suitable. [1] (d) Is M transparent, translucent or opaque? [1]", marks: 4, kw: [["k"], ["transparent", "most light", "see clearly", "see through", "broke", "break"], ["water through", "not waterproof", "20", "dripped", "lets water", "let water", "leak"], ["opaque"]], model: "(a) Material K. (b) J is transparent (95 units), so people could see in clearly, and it broke when bent. (c) L let 20 ml of water drip through, so it is not waterproof and water would leak out. (d) M is opaque, as it lets no light through (0 units).", tbl: [["Material", "Light reading (no material: 100 units)", "Water that dripped through (ml)", "Broke when bent?"], ["J", "95", "0", "Yes"], ["K", "45", "0", "No"], ["L", "50", "20", "No"], ["M", "0", "0", "No"]] }
  ],
  tf: [
    { s: "Glass is always transparent.", a: false, why: "Frosted glass is translucent: it lets only some light through, so things behind it look blurred." },
    { s: "Wet paper is stronger than the same paper when it is dry.", a: false, why: "Paper becomes weaker when it is wet and tears more easily." },
    { s: "Fabric can be made waterproof by coating it with plastic.", a: true, why: "The plastic layer stops water from passing through, as in many raincoats and umbrellas." },
    { s: "If two strips of the same size hold the same number of the same weights before breaking, they are equally strong.", a: true, why: "In a fair test, the number of weights held before breaking shows strength, so equal results mean equal strength." },
    { s: "In a strength test, the variable measured is the type of material.", a: false, why: "The type of material is the variable changed; the number of weights held before breaking is measured." },
    { s: "Repeating an experiment helps to make the results reliable.", a: true, why: "If the repeated results are similar, we can trust them, and a mistake is easier to spot." },
    { s: "All types of paper are opaque.", a: false, why: "Tracing paper is translucent; it lets some light pass through." },
    { s: "An object that floats in water must be made of wood.", a: false, why: "Cork, foam and a plastic ping-pong ball also float." },
    { s: "Plastic can be made transparent, translucent or opaque.", a: true, why: "Clear plastic bags, frosted plastic sheets and black rubbish bags are all made of plastic." },
    { s: "A cup can be made of glass, ceramic, plastic or paper.", a: true, why: "The same kind of object can be made of different materials, chosen for their properties." }
  ]
};
