window.BANKV = window.BANKV || {};
BANKV["materials"] = {
  flash: [
    { f: "Define: material", b: "A material is what an object is made of, e.g. wood, metal, plastic, glass, rubber, fabric, ceramic or paper." },
    { f: "Define: a strong material", b: "A strong material can hold a heavy load or withstand a force without breaking easily." },
    { f: "Define: a flexible material", b: "A flexible material can bend without breaking." },
    { f: "Define: waterproof", b: "A waterproof material does not let water pass through it and does not absorb water, e.g. plastic, rubber, glass, metal." },
    { f: "Define: absorbent", b: "An absorbent material soaks up (absorbs) water, e.g. sponge, cotton cloth, paper towel, tissue paper." },
    { f: "Define: transparent", b: "A transparent material lets most light pass through, so we can see clearly through it, e.g. clear glass, clear plastic." },
    { f: "Define: translucent", b: "A translucent material lets some light pass through, so things behind it look blurred, e.g. frosted glass, tracing paper." },
    { f: "Define: opaque", b: "An opaque material lets no light pass through, so we cannot see through it, e.g. wood, metal, cardboard." },
    { f: "Define: hard (and the scratch-test rule)", b: "A hard material is difficult to scratch or dent. A harder material can scratch a softer material; if A scratches B, A is harder than B." },
    { f: "Is a hard material always strong?", b: "No. Hard means difficult to scratch; strong means it does not break easily under a load. Glass and ceramic are hard but break easily when dropped." },
    { f: "Do heavy objects always sink?", b: "No. Whether an object floats or sinks depends on its material, not only on how heavy it is. A big wooden log floats; a small iron nail sinks." },
    { f: "Why are windows made of clear glass?", b: "Glass is transparent, so it lets most light pass through: light enters the room and we can see out clearly." },
    { f: "Why are car tyres made of rubber?", b: "Rubber is strong, so it can hold the weight of the car without breaking, and flexible, so it can bend without breaking." },
    { f: "A cloth leaves the LEAST water in the beaker. What does this show?", b: "It absorbed the MOST water, so it is the most absorbent material. Less water left = more water absorbed." },
    { f: "How do you make a materials test fair?", b: "Change only one variable (the type of material), keep all other variables the same (size, thickness, amount of water, time) and measure one result." }
  ],
  mcq: [
    { q: "The glass domes at Gardens by the Bay let sunlight in so that the plants inside can grow. Which property of glass allows this?", o: ["It is waterproof.", "It is hard.", "It is transparent.", "It is flexible."], a: 2, why: "Transparent glass lets most light pass through, so sunlight reaches the plants. Glass is also waterproof and hard, but those properties do not let light in.", lvl: 1 },
    { q: "Which material is the most suitable for the lenses of a pair of swimming goggles?", o: ["Cardboard", "Clear plastic", "Cotton cloth", "Wood"], a: 1, why: "The lenses must let most light through and keep water out, so clear plastic (transparent and waterproof) is best. Cardboard and wood are opaque, and cotton absorbs water.", lvl: 1 },
    { q: "Jun hung weights one at a time on a strip of material until the strip broke. Which property of the material was he testing?", o: ["Flexibility", "Hardness", "Transparency", "Strength"], a: 3, why: "The number of weights a strip holds before it breaks shows how strong it is. Hardness is tested by scratching, not by hanging weights.", lvl: 1 },
    { q: "Siti held a sheet of frosted plastic in front of her eyes and looked through it at her friend across the classroom. What would she most likely see?", o: ["Her friend, clearly and sharply", "Nothing at all, as it is dark", "Her friend, but upside down", "A blurred shape of her friend"], a: 3, why: "Frosted plastic is translucent: it lets some light through, so she sees a blurred shape. It is not transparent, so she cannot see clearly, and not opaque, so some light does pass through.", lvl: 1 },
    { q: "Strips of four materials of the same size were bent back and forth until each one cracked. The graph shows how many bends each strip took before it cracked. Which material is the most suitable for the hinge of a lunch box lid that is opened and closed many times a day?", o: ["Card", "Plastic P", "Plastic Q", "Thin wood"], a: 1, why: "Plastic P could be bent the most times (50) without cracking, so it is the best for a hinge that bends many times a day. Thin wood cracked after only 2 bends.", lvl: 2, fig: { type: "bar", title: "Bending test", xl: "Material", yl: "Number of bends before cracking", bars: [["Card", 12], ["Plastic P", 50], ["Plastic Q", 30], ["Thin wood", 2]] } },
    { q: "At a busy hawker centre, many stalls serve noodles in plastic bowls instead of ceramic bowls. Which is the best reason?", o: ["Plastic bowls do not break easily when dropped.", "Plastic bowls let light pass through them.", "Plastic bowls absorb the soup that spills.", "Plastic bowls are harder than ceramic bowls."], a: 0, why: "Ceramic is hard but breaks easily when dropped, while plastic bowls do not break easily. Plastic bowls are not harder than ceramic and do not absorb soup.", lvl: 2 },
    { q: "Which of these is NOT a property of a dry cotton towel?", o: ["It is absorbent.", "It is flexible.", "It is opaque.", "It is waterproof."], a: 3, why: "A cotton towel soaks up water, so it is absorbent, not waterproof. It also bends easily (flexible) and lets no light through (opaque).", lvl: 2 },
    { q: "The windows of an MRT train must let passengers see the stations clearly and keep the rain out. Which material is the most suitable?", o: ["Frosted glass", "Steel sheet", "Clear glass", "Cotton canvas"], a: 2, why: "Clear glass is transparent and waterproof. Frosted glass is translucent, so the view would be blurred; steel is opaque; cotton canvas absorbs water.", lvl: 2 },
    { q: "Which of these objects must be made of a flexible material to do their job?\nA: a hair band\nB: a swimming cap\nC: a chopping board\nD: a window pane", o: ["A and B only", "A and C only", "B and D only", "A, B and D only"], a: 0, why: "A hair band and a swimming cap must bend and stretch around the head. A chopping board and a window pane must stay stiff; they are not meant to bend.", lvl: 2 },
    { q: "Four brands of paper straws of the same size were put into cups of bubble tea. The table shows how long each straw took to become soggy and bend over. Which brand is the most suitable for a drink that takes a long time to finish?", o: ["A", "B", "C", "D"], a: 2, why: "Straw C stayed firm the longest (40 minutes), so it soaks up the drink the most slowly. Straw D became soggy after only 5 minutes.", lvl: 2, tbl: [["Brand of paper straw", "Time before it became soggy (min)"], ["A", "10"], ["B", "25"], ["C", "40"], ["D", "5"]] },
    { q: "Kayakers at MacRitchie Reservoir wear life jackets filled with foam. Why is foam used?", o: ["It floats on water, so it helps keep the kayaker afloat.", "It is transparent, so others can see the kayaker easily.", "It absorbs lots of water, so it becomes heavier in water.", "It is hard, so it cannot be scratched by the paddle."], a: 0, why: "The foam floats, so it holds the kayaker up in the water. It is not transparent, and a life jacket that soaked up water would not help.", lvl: 2 },
    { q: "Ben wants to find out whether the number of layers of tracing paper affects how much light passes through. He shone a torch through each set-up onto a light sensor. Which two set-ups should he compare?", o: ["P and S", "Q and R", "P and Q", "R and S"], a: 2, why: "P and Q are the same material at the same distance and differ only in the number of layers. Q and R differ in distance, P and S differ in material, and R and S differ in three things.", lvl: 3, tbl: [["Set-up", "Material", "Number of layers", "Distance from torch (cm)"], ["P", "Tracing paper", "1", "20"], ["Q", "Tracing paper", "3", "20"], ["R", "Tracing paper", "3", "30"], ["S", "Wax paper", "1", "20"]] },
    { q: "Study the classification chart. Which object has been placed WRONGLY?", o: ["Dry kitchen sponge at A", "Ping-pong ball at B", "Glass marble at C", "Steel key at C"], a: 3, why: "A steel key sinks and lets no light through, so it belongs at D, not C. A dry sponge floats and absorbs water (A), a ping-pong ball floats and does not absorb water (B), and a glass marble sinks and lets light through (C).", lvl: 3, fig: { type: "flow", root: "Objects", node: { q: "Floats on water?", yes: { q: "Absorbs water?", yes: "A", no: "B" }, no: { q: "Lets light through?", yes: "C", no: "D" } } } },
    { q: "Mei dipped the end of a paper towel strip into coloured water. She measured how high the water had risen up the strip every minute. Study the graph. Which statement is correct?", o: ["The water rose by the same height every minute.", "The water stopped rising after 3 minutes.", "The water rose the most between minute 2 and 3.", "The water reached 6 cm after 2 minutes."], a: 1, why: "The height stays at 6 cm from 3 to 5 minutes, so the water stopped rising after 3 minutes. It rose 3 cm, then 2 cm, then 1 cm, so not the same each minute, and it was only 5 cm at 2 minutes.", lvl: 3, fig: { type: "line", xl: "Time (min)", yl: "Height water rose (cm)", pts: [["0", 0], ["1", 3], ["2", 5], ["3", 6], ["4", 6], ["5", 6]] } },
    { q: "Which of these statements are correct?\nA: A material that floats is always waterproof.\nB: A transparent material can also be flexible.\nC: An opaque material can also be waterproof.", o: ["A only", "B only", "B and C only", "A, B and C"], a: 2, why: "B is correct (cling wrap is transparent and flexible) and C is correct (rubber is opaque and waterproof). A is wrong: a dry sponge floats but absorbs water.", lvl: 3 },
    { q: "Ravi stretched four materials of the same size over four cups and poured 50 ml of water onto each. Predict in which cups NO water will be collected.", o: ["C and D only", "A and B only", "C only", "B and D only"], a: 0, why: "Plastic sheet and aluminium foil are both waterproof, so no water passes through them. Paper towel and felt absorb water and let some of it through. Aluminium foil is a metal, but it is still waterproof.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Paper towel", "10 cm x 10 cm", "50 ml water poured"] }, { label: "B", icon: "jar", lines: ["Felt", "10 cm x 10 cm", "50 ml water poured"] }, { label: "C", icon: "jar", lines: ["Plastic sheet", "10 cm x 10 cm", "50 ml water poured"] }, { label: "D", icon: "jar", lines: ["Aluminium foil", "10 cm x 10 cm", "50 ml water poured"] }] } },
    { q: "Study the Venn diagram. Which set of objects could be P, Q, R and S?", o: ["P: dry sponge, Q: cork, R: copper wire, S: glass marble", "P: cork, Q: dry sponge, R: glass marble, S: copper wire", "P: glass marble, Q: dry sponge, R: copper wire, S: cork", "P: cork, Q: dry sponge, R: copper wire, S: glass marble"], a: 3, why: "Cork floats but is not flexible (P); a dry sponge floats and bends (Q); thin copper wire bends but sinks (R); a glass marble sinks and cannot bend (S). The other options swap at least two objects.", lvl: 3, fig: { type: "venn", a: "Floats on water", b: "Flexible", onlyA: ["P"], both: ["Q"], onlyB: ["R"], neither: ["S"] } },
    { q: "Ben poured water onto four materials of the same size stretched over cups. The table shows his results. Which conclusion can he make FOR SURE?", o: ["Q is more waterproof than R.", "P is more waterproof than Q.", "S is the most waterproof material.", "R is more waterproof than S."], a: 1, why: "Only P and Q, and R and S, had the same amount of water poured, so only those pairs are fair. P let less water through than Q, so P is more waterproof. S let less through than R, so the last option is wrong, and S cannot be fairly compared with P or Q.", lvl: 4, tbl: [["Material", "Water poured (ml)", "Water that dripped through (ml)"], ["P", "50", "10"], ["Q", "50", "25"], ["R", "100", "20"], ["S", "100", "15"]] },
    { q: "Strips of four materials of the same size were tested. Jun hung 50 g weights one at a time on strips A, B and C, but he used 100 g weights for strip D. The graph shows the number of weights each strip held before it broke. Which strip is the strongest?", o: ["Strip B, as it held the most weights", "Strip D, as it held the greatest total mass", "Strip A, as it held more weights than C", "Strips B and D are equally strong"], a: 1, why: "Count the total mass, not the number of weights: B held 9 x 50 g = 450 g, but D held 5 x 100 g = 500 g. So D held the heaviest load before breaking. B is the trap because its bar is the tallest.", lvl: 4, fig: { type: "bar", xl: "Strip", yl: "Number of weights held before breaking", bars: [["A", 6], ["B", 9], ["C", 4], ["D", 5]] } },
    { q: "Ali put four objects into a basin of water. Study the table. Which of these statements are correct?\nA: W and X show that a wooden object floats whether it is heavy or light.\nB: X and Y show that the material affects whether an object floats.\nC: W and Y show that heavy objects float and light objects sink.\nD: X and Z show that light objects always sink.", o: ["A and B only", "A and C only", "B and D only", "A, B and C only"], a: 0, why: "W and X are both wood and both float, though one is far heavier (A). X and Y have the same mass but different materials, and only one floats (B). C is wrong: W and Y differ in material, so the pair cannot show anything about mass. D is wrong: X is light but floats.", lvl: 4, tbl: [["Object", "Material", "Mass (g)", "Float or sink?"], ["W", "Wood", "400", "Floats"], ["X", "Wood", "20", "Floats"], ["Y", "Steel", "20", "Sinks"], ["Z", "Glass", "5", "Sinks"]] }
  ],
  oe: [
    { q: "Mei put a dry sponge into a container with 200 ml of water. She took it out at different times and measured the water left in the container. The graph shows her results. (a) How much water did the sponge absorb in total? (b) After how many minutes did the sponge stop absorbing water? (c) Explain how the graph shows this. (d) Mei thinks a bigger sponge of the same type will absorb more water. State one thing she must keep the same when she tests this.", marks: 4, x: 1, kw: [["100", "100ml"], ["3 minutes", "three minutes", "3 min", "after 3"], ["stayed the same", "stays the same", "remained the same", "did not change", "does not change", "no change", "no more water", "no longer", "flat"], ["same type", "same kind", "same amount of water", "same volume of water", "same time", "only the size"]], model: "(a) It absorbed 200 - 100 = 100 ml of water. (b) After 3 minutes. (c) From 3 minutes onwards, the water left stayed the same at 100 ml, so no more water was absorbed. (d) She must use the same type of sponge and the same amount of water, so that only the size of the sponge is changed.", fig: { type: "line", xl: "Time (min)", yl: "Water left in container (ml)", pts: [["0", 200], ["1", 140], ["2", 110], ["3", 100], ["4", 100], ["5", 100]] } },
    { q: "The platform screen doors at an MRT station have glass panels, steel frames and rubber strips along the edges where the doors meet. Explain why (a) the panels are made of glass, (b) the frames are made of steel, (c) the strips at the edges are made of rubber.", marks: 3, kw: [["transparent", "see through", "see the train", "see clearly"], ["strong", "not break", "does not break"], ["flexible", "bend", "squash", "press"]], model: "(a) Glass is transparent, so passengers can see through the doors and watch the train arrive. (b) Steel is strong, so the frame does not break easily and can hold the heavy glass panels. (c) Rubber is flexible, so the strips can bend and press together when the doors close, sealing the gap without cracking." },
    { q: "Ben wants to find out whether the type of material affects whether a cube floats or sinks. He prepared the set-ups shown. (a) Which set-up makes his test unfair? (b) What change should he make to that set-up? (c) Predict which cubes will sink.", marks: 3, kw: [["set up c", "setup c", "set-up c", "the cork cube", "c is", "c should", "c makes", "cork cube is"], ["same size", "4 cm", "bigger", "same as the others"], ["steel and glass", "glass and steel", "steel cube and glass", "glass cube and steel", "b and d", "d and b"]], model: "(a) Set-up C, because the cork cube is smaller than the other cubes. (b) He should use a cork cube of the same size as the others, a 4 cm cube, so that only the type of material is different. (c) The steel and glass cubes (B and D) will sink.", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Wooden cube", "4 cm x 4 cm x 4 cm", "Basin of tap water"] }, { label: "B", icon: "dish", lines: ["Steel cube", "4 cm x 4 cm x 4 cm", "Basin of tap water"] }, { label: "C", icon: "dish", lines: ["Cork cube", "2 cm x 2 cm x 2 cm", "Basin of tap water"] }, { label: "D", icon: "dish", lines: ["Glass cube", "4 cm x 4 cm x 4 cm", "Basin of tap water"] }] } },
    { q: "Study the classification chart. (a) State two properties of a material that ends up at C. (b) Name an object that could end up at C. (c) Name an object that could end up at B.", marks: 4, kw: [["not flexible", "cannot bend", "does not bend", "doesn’t bend", "can’t bend", "rigid", "stiff"], ["float"], ["wood", "cork"], ["rubber", "plastic", "raincoat", "aluminium foil", "foil", "balloon", "cling wrap", "swimming cap", "shower cap"]], model: "(a) It is not flexible, and it floats on water. (b) A wooden chopping board. (c) A rubber glove.", fig: { type: "flow", root: "Materials", node: { q: "Is it flexible?", yes: { q: "Absorbs water?", yes: "A", no: "B" }, no: { q: "Floats on water?", yes: "C", no: "D" } } } }
  ],
  tf: [
    { s: "Opaque materials are always hard.", a: false, why: "Cotton cloth and cardboard are opaque, but they are easy to dent or scratch." },
    { s: "A clear plastic bag is both transparent and flexible.", a: true, why: "It lets most light through and can bend without breaking." },
    { s: "Thin materials are always flexible.", a: false, why: "A thin glass slide is not flexible; it cracks if you try to bend it." },
    { s: "A glass aquarium is made of a material that is transparent and waterproof.", a: true, why: "We can see the fish clearly, and the glass keeps the water in." },
    { s: "The more weights a strip holds before breaking, the more flexible it is.", a: false, why: "That test shows strength. Flexibility is shown by how far a material bends without breaking." },
    { s: "When strips of the same size carry the same weight, the strip that bends the most without breaking is the most flexible.", a: true, why: "Bending more without breaking means the material is more flexible." },
    { s: "Waterproof materials are always transparent.", a: false, why: "Rubber and steel are waterproof but opaque." },
    { s: "Glazed ceramic tiles are used on bathroom walls because they are waterproof.", a: true, why: "Glazed ceramic does not absorb water or let it pass through." },
    { s: "A material that absorbs water must also be flexible.", a: false, why: "Chalk and an unglazed clay pot absorb water but cannot bend." },
    { s: "A cork floats because of the material it is made of, not because it is small.", a: true, why: "A large block of cork also floats; whether an object floats depends on its material." }
  ],
  sort: [
    { title: "Sort these objects: do they float or sink in water?", groups: ["Floats", "Sinks"], items: [["cork stopper", 0], ["wooden chopsticks", 0], ["ping-pong ball", 0], ["dry kitchen sponge", 0], ["wooden ice-cream stick", 0], ["glass marble", 1], ["steel key", 1], ["stone", 1], ["copper coin", 1], ["ceramic spoon", 1]] }
  ]
};
