window.BANKX = window.BANKX || {};
BANKX["materials"] = {
  notes: [
    { h: "The best material has ALL the needed properties", t: "When an object must do several jobs, the material chosen must have every property the job needs, not just one. A toddler’s water bottle must let you see the water (transparent), keep water in (waterproof) and not break when dropped, so clear plastic is better than glass. If a material fails even one of the needed properties, it is not the most suitable.", kw: ["has all the properties", "not just one", "most suitable"] },
    { h: "Read what the bar graph measures", t: "Before choosing the ‘best’ bar, read the axis label. For ‘water absorbed’, the tallest bar is the most absorbent. For ‘water left in the beaker’ or ‘water that dripped through’, the shortest bar means most absorbed or most waterproof. For ‘weights held before breaking’, the tallest bar is the strongest. For ‘how far it bent’, the tallest bar is the most flexible.", kw: ["read the axis label", "tallest bar", "shortest bar"] },
    { h: "Designing a fair material test", t: "To test waterproofness, stretch the same size of each material over a cup, pour the same amount of water on each and measure how much water drips into the cup. To test float or sink, use blocks of the same size in the same basin of water. In every test, change only the type of material, keep everything else the same, and measure one result.", kw: ["same size", "same amount of water", "change only the type of material", "measure"] }
  ],
  traps: [
    "The tallest bar is always the best material -> Read the axis: for ‘water left’ or ‘water that dripped through’, the SHORTEST bar is the most absorbent or most waterproof.",
    "Flexible means stretchy -> Flexible means it can bend without breaking; paper bends but does not stretch.",
    "A material only needs one suitable property -> It must have ALL the properties the use needs, e.g. a window must be transparent, waterproof and strong."
  ],
  mcq: [
    { q: "Which of these materials is flexible?", o: ["Glass", "Ceramic", "Rubber", "Chalk"], a: 2, why: "Rubber bends without breaking. Glass, ceramic and chalk crack or break when you try to bend them.", lvl: 1 },
    { q: "Study the classification chart. Which material could be B?", o: ["Clear glass", "Cardboard", "Clear plastic", "Frosted glass"], a: 1, why: "B does not let light through, so it is opaque, like cardboard. Clear glass, clear plastic and frosted glass all let some or most light through.", lvl: 1, fig: { type: "flow", root: "Materials", node: { q: "Lets light through?", yes: "A", no: "B" } } },
    { q: "Which of these materials is opaque?", o: ["Aluminium foil", "Clear glass", "Tracing paper", "Clear plastic sheet"], a: 0, why: "Aluminium foil lets no light through. Tracing paper is translucent – it lets some light through, so it is not opaque.", lvl: 1 },
    { q: "Strings of the same length and thickness were tested by adding weights until each broke. Study the graph. Which string is the strongest?", o: ["Cotton", "Wool", "Jute", "Nylon"], a: 3, why: "Nylon held the most weights (11) before breaking. Wool held the fewest, so it is the weakest.", lvl: 1, fig: { type: "bar", title: "Strength of strings", xl: "Type of string", yl: "Number of weights held before breaking", bars: [["Cotton", 4], ["Nylon", 11], ["Wool", 3], ["Jute", 7]] } },
    { q: "Pieces of cloth of the same size were dipped in water. The graph shows how much water each piece absorbed. Which cloth is the most suitable for making a mop head?", o: ["P", "Q", "R", "S"], a: 1, why: "A mop must soak up water, and cloth Q absorbed the most water (60 ml). Cloth S absorbed the least, so it is the least suitable.", lvl: 2, fig: { type: "bar", title: "Water absorbed by cloths", xl: "Cloth", yl: "Water absorbed (ml)", bars: [["P", 25], ["Q", 60], ["R", 40], ["S", 10]] } },
    { q: "Four materials of the same size were stretched over four cups. 50 ml of water was poured onto each material. The graph shows how much water dripped into each cup. Which material is the most suitable for a shower curtain?", o: ["W", "X", "Z", "Y"], a: 3, why: "No water dripped through Y, so it is waterproof. Here the SHORTEST bar is best – Z let the most water through.", lvl: 2, fig: { type: "bar", xl: "Material", yl: "Water that dripped into cup (ml)", bars: [["W", 30], ["X", 15], ["Y", 0], ["Z", 45]] } },
    { q: "Study the classification chart. Which object could be Q?", o: ["Rubber glove", "Glass jar", "Cotton T-shirt", "Ceramic plate"], a: 2, why: "Q is flexible but not waterproof, like a cotton T-shirt. A rubber glove is flexible and waterproof (P), a glass jar lets light through (R) and a ceramic plate is opaque and not flexible (S).", lvl: 2, fig: { type: "flow", root: "Objects", node: { q: "Is it flexible?", yes: { q: "Is it waterproof?", yes: "P", no: "Q" }, no: { q: "Lets light through?", yes: "R", no: "S" } } } },
    { q: "Which part of an object is correctly matched with the reason for its material?", o: ["Glass lenses of spectacles – transparent, so we can see through them", "Rubber tyres of a bicycle – transparent, so we can see the road", "Metal frame of a bicycle – absorbs water well", "Cotton cover of a bicycle seat – waterproof"], a: 0, why: "Glass lenses must let light through so we see clearly. Rubber is opaque, metal does not absorb water, and cotton absorbs water, so it is not waterproof.", lvl: 2 },
    { q: "A water bottle for a toddler must let the parent see how much water is left, keep the water in and not break when dropped. Which material is the most suitable?", o: ["Glass", "Ceramic", "Aluminium", "Clear plastic"], a: 3, why: "Clear plastic is transparent, waterproof and does not break easily when dropped. Glass is transparent but breaks easily; ceramic and aluminium are opaque.", lvl: 2 },
    { q: "Strips of four materials of the same size were clamped to a table and the same weight was hung at each end. The graph shows how far each end bent down. Which material is the most suitable for a ruler that should not bend easily?", o: ["Rubber", "Wood", "Thin plastic", "Cardboard"], a: 1, why: "Wood bent the least (1 cm), so it is the least flexible and keeps a ruler straight. Rubber bent the most, so it is the most flexible.", lvl: 2, fig: { type: "bar", title: "Bending test", xl: "Material", yl: "How far the end bent down (cm)", bars: [["Rubber", 9], ["Thin plastic", 6], ["Wood", 1], ["Cardboard", 4]] } },
    { q: "Mei set up the experiment shown. What is she trying to find out?", o: ["Whether the size of a block affects whether it floats or sinks", "Whether the type of material affects whether a block floats or sinks", "Whether the amount of water affects whether a block floats or sinks", "Whether cold water makes blocks sink"], a: 1, why: "Only the material of the block is different; the size of the block and the water are the same. So she is testing the type of material.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Wooden block", "3 cm cube", "Tap water"] }, { label: "B", icon: "beaker", lines: ["Iron block", "3 cm cube", "Tap water"] }, { label: "C", icon: "beaker", lines: ["Plastic block", "3 cm cube", "Tap water"] }] } },
    { q: "A torch was shone through four materials onto a light sensor. Study the graph. Which material is the most suitable for a bathroom window that lets light in but stops people seeing in clearly?", o: ["S", "R", "Q", "P"], a: 2, why: "Q let only some light through, so it is translucent. P and S let most light through (transparent), so people could see in; R let no light through (opaque), so the bathroom would be dark.", lvl: 2, fig: { type: "bar", xl: "Material", yl: "Light reading (units)", bars: [["P", 92], ["Q", 48], ["R", 0], ["S", 85]] } },
    { q: "Ravi sorted some objects in the Venn diagram. Which object has been placed in the WRONG region?", o: ["Glass jar", "Cotton T-shirt", "Ceramic tile", "Chalk"], a: 2, why: "A ceramic tile is waterproof but NOT flexible – it cracks when bent – so it belongs in ‘Waterproof’ only. Chalk absorbs water and is not flexible, so it is correctly outside both circles.", lvl: 3, fig: { type: "venn", a: "Waterproof", b: "Flexible", onlyA: ["glass jar", "steel spoon"], both: ["rubber glove", "plastic bag", "ceramic tile"], onlyB: ["cotton T-shirt"], neither: ["chalk"] } },
    { q: "Siti wants to find out whether the type of cloth affects how much water it absorbs. Which two set-ups should she compare?", o: ["A and B", "A and D", "B and C", "C and D"], a: 0, why: "A and B differ only in the type of cloth. B and C differ in size, and A and D differ in the amount of water, so they are not fair comparisons of cloth type.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Cotton cloth", "10 cm x 10 cm", "100 ml water"] }, { label: "B", icon: "beaker", lines: ["Nylon cloth", "10 cm x 10 cm", "100 ml water"] }, { label: "C", icon: "beaker", lines: ["Nylon cloth", "20 cm x 20 cm", "100 ml water"] }, { label: "D", icon: "beaker", lines: ["Cotton cloth", "10 cm x 10 cm", "50 ml water"] }] } },
    { q: "Three sponges of the same size were each put into a beaker with 200 ml of water, then taken out. The graph shows the water LEFT in each beaker. Which statement is correct?", o: ["Sponge P absorbed the most water.", "Sponge R absorbed 90 ml of water.", "Sponge Q absorbed the least water.", "Sponge Q absorbed 160 ml of water."], a: 3, why: "Water absorbed = 200 ml minus water left. Q absorbed 200 − 40 = 160 ml, the most. P absorbed only 50 ml, the least, and R absorbed 110 ml, not 90 ml.", lvl: 3, fig: { type: "bar", xl: "Sponge", yl: "Water left in beaker (ml)", bars: [["P", 150], ["Q", 40], ["R", 90]] } },
    { q: "Study the classification chart. Which set of materials is correct?", o: ["A: clear glass, B: tracing paper, C: cork, D: iron nail", "A: tracing paper, B: clear glass, C: cork, D: iron nail", "A: clear glass, B: tracing paper, C: iron nail, D: cork", "A: clear glass, B: cork, C: tracing paper, D: iron nail"], a: 0, why: "Clear glass lets most light through (A); tracing paper lets only some through (B). Cork and iron are opaque; cork floats (C) and iron sinks (D).", lvl: 3, fig: { type: "flow", root: "Materials", node: { q: "Lets light through?", yes: { q: "Lets most light through?", yes: "A", no: "B" }, no: { q: "Floats on water?", yes: "C", no: "D" } } } },
    { q: "Four paper strips of the same size were tested by adding weights until each strip tore. Based on the graph, which statement is NOT true?", o: ["B and D are equally strong.", "A is the weakest strip.", "B held 6 more weights than A.", "C is stronger than D."], a: 3, why: "C held 7 weights but D held 10, so D is stronger than C. B and D both held 10, A held the fewest (4), and 10 − 4 = 6.", lvl: 3, fig: { type: "bar", title: "Strength of paper strips", xl: "Strip", yl: "Number of weights held before tearing", bars: [["A", 4], ["B", 10], ["C", 7], ["D", 10]] } },
    { q: "The lid of a water bottle has a rubber ring inside it. Why is rubber used for this ring?", o: ["It is flexible and waterproof, so it seals the gap and stops leaks.", "It is transparent, so we can see the water level inside the bottle.", "It absorbs any water that leaks, so the outside of the bottle stays dry.", "It is hard, so it cannot be scratched when the lid is screwed on."], a: 0, why: "The ring must squeeze into the gap (flexible) and not let water through (waterproof). Rubber is opaque and does not absorb water.", lvl: 3 },
    { q: "Ben says, ‘Heavy objects sink and light objects float.’ He weighed four objects and put them in water. The wooden block and the cork floated; the iron nail and the glass marble sank. Study the graph. Which conclusion is correct?", o: ["Ben is correct because the iron nail and the glass marble sank.", "Floating depends on the material, not only on how heavy the object is.", "All objects lighter than 10 g sink, whatever they are made of.", "Only heavy objects float, and all the light objects sink."], a: 1, why: "The wooden block is the heaviest yet it floats, while the light nail and marble sink. So Ben is wrong – the material matters.", lvl: 3, fig: { type: "bar", xl: "Object", yl: "Mass (g)", bars: [["Wooden block", 120], ["Iron nail", 5], ["Cork", 4], ["Glass marble", 6]] } },
    { q: "Mei is choosing a material for a tent that must keep rain out and fold into a small bag. She did a waterproof test with 50 ml of water on each material. Based on the graph, what should she do next to choose between X and Y?", o: ["Repeat the waterproof test on Z using more water to be sure", "Choose Z because its bar is the tallest, so it is the best", "Test same-size strips of X and Y to see which bends more easily", "Choose X because it comes first and is also waterproof"], a: 2, why: "X and Y are both waterproof (0 ml dripped through), so the graph cannot tell them apart. The tent must also fold, so she should compare how flexible X and Y are. Z let water through, so it is unsuitable.", lvl: 3, fig: { type: "bar", xl: "Material", yl: "Water that dripped through (ml)", bars: [["X", 0], ["Y", 0], ["Z", 30]] } }
  ],
  tf: [
    { s: "A flexible material can always stretch.", a: false, why: "Flexible means it can bend without breaking; paper bends but does not stretch." },
    { s: "Tracing paper is translucent.", a: true, why: "It lets some light through, so things behind it look blurred." },
    { s: "In a waterproof test, a material that lets no water drip through is waterproof.", a: true, why: "Waterproof materials do not let water pass through." },
    { s: "Aluminium foil is opaque.", a: true, why: "Aluminium foil lets no light pass through." },
    { s: "The best material for an object needs to have only one suitable property.", a: false, why: "It must have all the properties the use needs." },
    { s: "Cotton cloth is suitable for the outer cover of a tent because it absorbs rain.", a: false, why: "A tent cover must be waterproof; cotton absorbs water and lets it through." },
    { s: "A bicycle is made of more than one material.", a: true, why: "It has a metal frame, rubber tyres and often a plastic or fabric seat cover." },
    { s: "Glass is strong because it is hard.", a: false, why: "Glass is hard (difficult to scratch) but breaks easily; hardness and strength are different." }
  ],
  oe: [
    { q: "Four materials of the same size were stretched over cups, and 50 ml of water was poured onto each. The graph shows the water that dripped into each cup. (a) Which material is the most waterproof? (b) Explain your answer using the graph. (c) Suggest one object that could be made from this material.", marks: 3, kw: [["plastic"], ["no water", "0 ml", "zero", "none", "did not let", "least water"], ["raincoat", "umbrella", "tent", "shower curtain", "apron", "boot", "bag", "table cloth"]], model: "(a) The plastic sheet. (b) No water (0 ml) dripped through it, so it does not let water pass through. (c) A raincoat.", fig: { type: "bar", xl: "Material", yl: "Water that dripped into cup (ml)", bars: [["Cotton", 35], ["Plastic sheet", 0], ["Paper towel", 40], ["Felt", 20]] } },
    { q: "Mei set up the experiment shown to compare three sponges. After 1 minute, she took each sponge out. (a) State the variable she changed. (b) State one variable she kept the same. (c) State what she should measure.", marks: 3, kw: [["type of sponge", "kind of sponge", "sponge type", "type of material", "kind of material", "different sponge"], ["size", "amount of water", "volume of water", "100 ml", "5 cm", "time", "1 minute"], ["water left", "water absorbed", "how much water", "amount of water left", "volume of water left", "amount of water absorbed", "volume of water absorbed"]], model: "(a) The type of sponge. (b) The size of the sponge (a 5 cm cube). (c) The amount of water left in each beaker, which shows how much water each sponge absorbed.", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Kitchen sponge", "5 cm cube", "100 ml water"] }, { label: "B", icon: "beaker", lines: ["Car-wash sponge", "5 cm cube", "100 ml water"] }, { label: "C", icon: "beaker", lines: ["Bath sponge", "5 cm cube", "100 ml water"] }] } },
    { q: "Study the classification chart. Material X ends up at R. (a) State one property of X from the first question. (b) State one property of X from the second question. (c) Name an object that could be made of material X.", marks: 3, kw: [["not flexible", "cannot bend", "does not bend", "can’t bend", "doesn’t bend", "rigid", "stiff"], ["lets light", "light through", "light pass", "transparent", "translucent"], ["glass", "window", "cup", "bottle", "jar", "aquarium", "tank"]], model: "(a) X is not flexible – it does not bend easily. (b) X lets light through (it is transparent or translucent). (c) A glass window.", fig: { type: "flow", root: "Materials", node: { q: "Is it flexible?", yes: { q: "Is it waterproof?", yes: "P", no: "Q" }, no: { q: "Lets light through?", yes: "R", no: "S" } } } },
    { q: "Jun tested four threads of the same length and thickness by hanging weights on them until each one snapped. (a) Which thread is the most suitable for flying a kite on a windy day at Marina Barrage? (b) Explain using the graph. (c) Why must all the threads be of the same length and thickness?", marks: 3, kw: [["nylon"], ["most weights", "held the most", "greatest number", "14"], ["fair", "only one variable", "only the type", "thicker"]], model: "(a) Nylon. (b) Nylon held the most weights (14) before it snapped, so it is the strongest. (c) To make it a fair test, so that only the type of thread is changed and a thicker or shorter thread does not hold more weights just because of its size.", fig: { type: "bar", title: "Strength of threads", xl: "Thread", yl: "Number of weights held before snapping", bars: [["Cotton", 6], ["Wool", 3], ["Nylon", 14], ["Silk", 9]] } },
    { q: "A school water bottle has a clear plastic body, a rubber ring inside the lid and a fabric strap. Explain why (a) the body is made of clear plastic, (b) the ring is made of rubber, (c) the strap is made of fabric.", marks: 3, kw: [["transparent", "see"], ["leak", "presses tightly", "seal", "tight", "waterproof"], ["flexible", "bend", "strong", "tear", "soft", "comfortable", "shoulder"]], model: "(a) Clear plastic is transparent, so we can see how much water is left, and it does not break easily when dropped. (b) Rubber is flexible and waterproof, so it presses tightly into the lid and stops water from leaking. (c) Fabric is flexible and strong, so the strap can bend over the shoulder without breaking." },
    { q: "Ben says that heavy objects sink. He drops a large wooden block (200 g) and a small steel paper clip (1 g) into a basin of water. (a) Predict what will happen to the block and to the paper clip. (b) Is Ben correct? (c) Explain your answer to (b).", marks: 3, kw: [["block will float", "block floats", "block would float", "wooden block float", "wood floats", "wood will float", "clip will sink", "clip sinks", "clip would sink"], ["not correct", "incorrect", "wrong", "not right"], ["material", "not only", "depends", "heavier block floats", "heavy block floats", "lighter clip sinks", "light clip sinks"]], model: "(a) The wooden block will float and the paper clip will sink. (b) Ben is not correct. (c) The heavier block floats but the lighter clip sinks, so whether an object floats depends on its material, not only on how heavy it is." },
    { q: "Kopi at a hawker centre is served in a ceramic cup, but takeaway kopi comes in a cup made of paper coated with plastic. (a) Why is the paper coated with plastic? (b) Give one reason why the coated paper cup is more suitable than a ceramic cup for takeaway.", marks: 2, kw: [["waterproof", "not absorb", "not soak", "leak", "soggy"], ["break", "light"]], model: "(a) The plastic coating is waterproof, so the paper does not absorb the kopi and the cup does not leak. (b) The paper cup is light and does not break easily if it is dropped, unlike a ceramic cup." },
    { q: "Uncle Tan is choosing a material for a tent to use at East Coast Park. It must keep the rain out and fold into a small bag. (a) State two properties the material must have. (b) Explain why cotton cloth is not suitable.", marks: 3, kw: [["waterproof"], ["flexible", "fold", "bend"], ["absorb", "soak", "wet", "not waterproof"]], model: "(a) The material must be waterproof, so rain cannot pass through, and flexible, so it can bend and fold into a bag. (b) Cotton absorbs water, so the rain would soak through and the people inside would get wet." }
  ],
  doc: [
    { q: "Why are the windows of a classroom made of glass?", marks: 2, answers: ["Glass is transparent, so it lets most light into the classroom and we can see outside.", "Because glass is nice and shiny.", "Glass is hard."], best: 0, why: "Answer 1 names the property (transparent) and explains the use (light enters, we can see out). Answer 2 gives no scientific property. Answer 3 gives a true property but not the one that explains why a window needs glass." },
    { q: "Three cloths were put in beakers of 100 ml of water. Water left: A 70 ml, B 30 ml, C 55 ml. Which cloth is the most absorbent? Explain.", marks: 2, answers: ["Cloth A, because it had the most water left.", "Cloth B, because it had the least water left in the beaker, so it absorbed the most water.", "Cloth B, because it is the best."], best: 1, why: "Answer 2 uses the evidence (least water left) and the reasoning (so it absorbed the most). Answer 1 reads the result the wrong way round. Answer 3 gets the right cloth but gives no evidence from the results." },
    { q: "When testing the strength of paper strips, why must all the strips be the same size?", marks: 2, answers: ["So that it looks neat.", "So that the strips can hold weights.", "To make it a fair test, so that only the type of paper affects how many weights each strip holds."], best: 2, why: "Answer 3 says fair test AND explains that only the type of paper is being changed. Answer 1 gives no scientific reason. Answer 2 is true for any strip and does not explain fairness." },
    { q: "Why is a raincoat made of plastic and not cotton?", marks: 2, answers: ["Plastic is waterproof so rain cannot pass through, but cotton absorbs water, so we would get wet.", "Plastic is waterproof so it keeps us dry.", "Cotton is not good for rain."], best: 0, why: "Answer 1 explains both materials: plastic is waterproof and cotton absorbs water. Answer 2 only explains plastic and says nothing about cotton. Answer 3 is too vague – it names no property." },
    { q: "A pair of scissors has metal blades and plastic handles. Explain why each material is used.", marks: 2, answers: ["Metal is strong.", "The metal blades are strong and hard, so they can cut without breaking. The plastic handles are light and comfortable to hold.", "The scissors are made of two materials so they are better."], best: 1, why: "Answer 2 explains both parts with a property and a reason. Answer 1 only explains the blades and gives no reason. Answer 3 repeats the question without any properties." }
  ]
};
