window.BANKZ = window.BANKZ || {};
BANKZ["materials"] = {
  lessons: [
    {
      h: "Aim, variables and conclusion from one experiment",
      concept: "Many Booklet B questions give you an experiment and ask for its aim, its variables and a conclusion. The aim links the two key variables: ‘To find out whether/how [the variable changed] affects [the variable measured]’. The variable changed is the one that is different in each set-up; the variable measured is the result you read off the table or graph. The conclusion answers the aim, using the results as evidence.",
      example: {
        q: "Siti clamped strips of plastic P, Q and R to the edge of a table. Each strip was 20 cm long, 2 cm wide and 1 mm thick, and the same 100 g weight was hung at the free end of each strip. She measured how far each end bent down. (a) What is the aim of her experiment? (b) State the variable she changed and the variable she measured. (c) What can she conclude from the results?",
        tbl: [["Plastic", "Distance the end bent down (cm)"], ["P", "3"], ["Q", "8"], ["R", "5"]],
        marks: 3,
        think: [
          "Step 1: Find what is different in each set-up. Length, width, thickness and the weight are all the same; only the type of plastic is different. That is the variable changed.",
          "Step 2: Find what she recorded: the distance each end bent down. That is the variable measured, and it tells us how flexible each plastic is.",
          "Step 3: Build the aim from the two variables: ‘To find out whether the type of plastic affects how far it bends (how flexible it is).’",
          "Step 4: For the conclusion, answer the aim and quote the evidence: the strip that bent the most is the most flexible."
        ],
        answer: "(a) To find out whether the type of plastic affects how flexible it is (how far it bends). (b) Changed: the type of plastic. Measured: the distance the end of each strip bent down. (c) Plastic Q is the most flexible because it bent down the most (8 cm), and plastic P is the least flexible because it bent down the least (3 cm)."
      },
      tip: "Aim = ‘To find out whether [variable changed] affects [variable measured]’. Never write just ‘to find out about plastics’.",
      try: {
        q: "Ali put pieces of cotton, nylon and wool of the same size into beakers each containing 100 ml of water. After 1 minute he took them out and measured the water left in each beaker. Which is the best aim for his experiment?",
        o: ["To find out whether the amount of water affects the type of cloth", "To find out which beaker holds the most water after one minute", "To find out whether the type of cloth affects how much water it absorbs", "To find out whether the size of the cloth affects how much water it absorbs"],
        a: 2,
        why: "Only the type of cloth was different, and the water left shows how much water each cloth absorbed, so the aim links these two. The size of the cloth was kept the same, so it cannot be part of the aim, and ‘which beaker holds the most water’ does not mention the cloth at all."
      }
    }
  ],
  mcq: [
    { q: "A material that is difficult to scratch or dent is described as ______.", o: ["hard", "strong", "flexible", "waterproof"], a: 0, why: "Misconception: hard and strong are not the same. Hard means difficult to scratch or dent; strong means it can hold a heavy load without breaking.", lvl: 1 },
    { q: "Which of these are made of opaque materials?\nA: cardboard box\nB: tracing paper\nC: steel lid\nD: clear plastic cup", o: ["A and B only", "B and D only", "A and C only", "A, B and C only"], a: 2, why: "Cardboard and steel let no light through, so they are opaque. Tracing paper lets some light through (translucent) and the clear plastic cup lets most light through (transparent).", lvl: 1 },
    { q: "Study the Venn diagram. Which object could be X?", o: ["Steel spoon", "Clear glass", "Ceramic tile", "Cotton sock"], a: 3, why: "X must both absorb water and be flexible. A cotton sock soaks up water and bends easily. The steel spoon, clear glass and ceramic tile do not absorb water and are not flexible.", lvl: 1, fig: { type: "venn", a: "Absorbs water", b: "Flexible", onlyA: ["chalk"], both: ["X"], onlyB: ["rubber band", "plastic bag"], neither: ["glass marble"] } },
    { q: "Four cloths of the same size were stretched over cups. Water was dripped onto each cloth, one drop at a time, until water started to drip into the cup. The graph shows the number of drops needed for each cloth. Which cloth is the best at keeping water out?", o: ["P", "Q", "R", "S"], a: 3, why: "S needed the most drops (40) before any water passed through, so it kept water out the longest. Q let water through after only 3 drops, so it is the worst at keeping water out.", lvl: 2, fig: { type: "bar", xl: "Cloth", yl: "Number of drops before water passed through", bars: [["P", 12], ["Q", 3], ["R", 20], ["S", 40]] } },
    { q: "Which of these are correctly matched with a reason?\nA: Rubber gloves – flexible, so the fingers can bend\nB: A glass fish tank – transparent, so we can see the fish\nC: A wooden chopping board – flexible, so it bends when we cut on it", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "A and B are correct. A chopping board must NOT bend; thick wood is used because it is strong and does not break easily, not because it is flexible.", lvl: 2 },
    { q: "Study the classification chart. Which object could be S?", o: ["Glass marble", "Rubber band", "Paper towel", "Plastic bag"], a: 0, why: "S does not absorb water and is not flexible, like a glass marble. The rubber band and plastic bag are flexible (R), and the paper towel absorbs water, so it goes down the ‘yes’ side.", lvl: 2, fig: { type: "flow", root: "Objects", node: { q: "Absorbs water?", yes: { q: "Floats on water?", yes: "P", no: "Q" }, no: { q: "Is it flexible?", yes: "R", no: "S" } } } },
    { q: "Siti held up a green glass bottle. Most light passed through it, and she could see her fingers clearly through the glass. The green glass is ______.", o: ["opaque", "transparent", "translucent", "flexible"], a: 1, why: "Misconception: a coloured material is not always translucent or opaque. Most light passes through and she can see clearly, so the green glass is transparent.", lvl: 2 },
    { q: "Jun set up the experiment shown to compare the strength of three types of paper. He hung 20 g weights one at a time on each strip. What should he measure?", o: ["The type of paper used for each strip", "The size of each paper strip at the start", "The mass of each weight hung on the strip", "The number of weights held before each strip tears"], a: 3, why: "The number of weights each strip holds before it tears shows how strong it is. The type of paper is what he changes, and the size and the mass of each weight are kept the same.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Newspaper strip", "20 cm x 3 cm", "20 g weights"] }, { label: "B", icon: "box", lines: ["Drawing paper strip", "20 cm x 3 cm", "20 g weights"] }, { label: "C", icon: "box", lines: ["Crepe paper strip", "20 cm x 3 cm", "20 g weights"] }] } },
    { q: "Mei cut a wooden block that floats into one big piece and one small piece. She put both pieces into a basin of water. What will happen?", o: ["Both pieces will float.", "Both pieces will sink.", "Only the big piece will float.", "Only the small piece will float."], a: 0, why: "Misconception: cutting an object into smaller pieces does not change whether it floats. Both pieces are still wood, and wood floats.", lvl: 2 },
    { q: "Four cloths of the same size were each soaked in a beaker containing 150 ml of water and then taken out. Which cloth absorbed MORE than half of the water?", o: ["P", "Q", "R", "S"], a: 2, why: "Half of 150 ml is 75 ml. R absorbed 150 − 60 = 90 ml, which is more than half. S absorbed 70 ml, P 60 ml and Q only 35 ml. Misconception: Q has the most water left, which means it absorbed the LEAST.", lvl: 3, tbl: [["Cloth", "Water left in beaker (ml)"], ["P", "90"], ["Q", "115"], ["R", "60"], ["S", "80"]] },
    { q: "Which of these statements are correct?\nA: A harder material can scratch a softer material.\nB: If X can scratch Y, then Y can also scratch X.\nC: Glass is hard, but it breaks easily when dropped.", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 2, why: "A and C are correct. B is a misconception: if X scratches Y, X is harder, so the softer Y cannot scratch X.", lvl: 3 },
    { q: "Ali wants to find out which material is the most waterproof. He stretched each material over a cup and poured water onto it. Which set-up should he remove so that the remaining set-ups make a fair test?", o: ["A", "B", "C", "D"], a: 3, why: "In D, more water (80 ml) was poured than in the others (50 ml), so more water might drip through just because more was poured. A, B and C differ only in the type of material.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Plastic sheet", "10 cm x 10 cm", "50 ml water poured"] }, { label: "B", icon: "jar", lines: ["Cotton cloth", "10 cm x 10 cm", "50 ml water poured"] }, { label: "C", icon: "jar", lines: ["Felt", "10 cm x 10 cm", "50 ml water poured"] }, { label: "D", icon: "jar", lines: ["Paper towel", "10 cm x 10 cm", "80 ml water poured"] }] } },
    { q: "Blocks of four materials of the same size were placed on the floor. The same steel ball was dropped onto each block from the same height. The graph shows how deep the dent on each block was. Which material is the hardest?", o: ["P", "Q", "R", "S"], a: 1, why: "A hard material is difficult to dent, so the shallowest dent (Q, 1 mm) shows the hardest material. Misconception: the tallest bar is not always the best – S has the deepest dent, so it is the softest.", lvl: 3, fig: { type: "bar", xl: "Material", yl: "Depth of dent (mm)", bars: [["P", 6], ["Q", 1], ["R", 4], ["S", 9]] } },
    { q: "Siti tried to scratch four materials with her fingernail, a copper coin and a steel nail. Study the results. Arrange the materials from the hardest to the softest.", o: ["J, M, K, L", "L, M, K, J", "K, L, M, J", "L, K, M, J"], a: 3, why: "L could not be scratched even by the steel nail, so it is the hardest. K was scratched only by the nail, M by the coin and the nail, and J by all three, so J is the softest.", lvl: 3, tbl: [["Material", "Scratched by fingernail?", "Scratched by copper coin?", "Scratched by steel nail?"], ["J", "Yes", "Yes", "Yes"], ["K", "No", "No", "Yes"], ["L", "No", "No", "No"], ["M", "No", "Yes", "Yes"]] },
    { q: "Ravi wants to find out which type of paper is the strongest. Which of these must he keep the same?\nA: the length of each strip\nB: the width of each strip\nC: the type of paper", o: ["A only", "C only", "A and B only", "A, B and C"], a: 2, why: "Length and width must be kept the same so the test is fair. The type of paper is the variable he changes, so it cannot be kept the same.", lvl: 3 },
    { q: "Three cloths of the same size were each dipped into a beaker containing 100 ml of water and then taken out. The graph shows the water left in each beaker. Which statements are correct?\nA: Cloths P and R absorbed the same amount of water.\nB: Cloth Q absorbed 70 ml of water.\nC: Cloth Q is the least suitable for making a mop.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "P and R both left 40 ml, so each absorbed 60 ml (A is correct). Q left 70 ml, so it absorbed only 30 ml, not 70 ml (B is wrong); it absorbed the least, so it is the least suitable for a mop (C is correct).", lvl: 3, fig: { type: "bar", xl: "Cloth", yl: "Water left in beaker (ml)", bars: [["P", 40], ["Q", 70], ["R", 40]] } },
    { q: "The top of a chopping block at a hawker stall must not be scratched by a steel knife and must not break when dropped. Four materials were tested. Which material is the most suitable?", o: ["W", "X", "Y", "Z"], a: 0, why: "Y scratched the knife, so Y is harder than the knife; W scratched Y, so W is even harder, and the knife cannot scratch W. W also did not break. Y is hard enough but broke, while the knife scratched X, and Z is softer than X.", lvl: 4, tbl: [["Material", "Scratch test result", "Broke when dropped?"], ["W", "W scratched Y", "No"], ["X", "The knife scratched X", "No"], ["Y", "Y scratched the knife", "Yes"], ["Z", "X scratched Z", "No"]] },
    { q: "Study the classification chart. Which of these objects would end up at C?\nW: glazed ceramic tile\nX: rubber glove\nY: cardboard box\nZ: frosted glass", o: ["W and X only", "W only", "X and Z only", "W, X and Z only"], a: 0, why: "C is for materials that let no light through and are waterproof: the ceramic tile and the rubber glove. Cardboard absorbs water (D). Frosted glass is translucent, so it DOES let some light through and goes down the ‘yes’ side (B), even though you cannot see clearly through it.", lvl: 4, fig: { type: "flow", root: "Materials", node: { q: "Lets light through?", yes: { q: "Is it flexible?", yes: "A", no: "B" }, no: { q: "Is it waterproof?", yes: "C", no: "D" } } } },
    { q: "Sponges of the same length and width were put into the same amount of water. Mei wants to find out whether the THICKNESS of a sponge affects how much water it absorbs. Which two sponges should she compare, and what do they show?", o: ["B and C: the thicker sponge absorbed more water.", "C and D: the thicker sponge absorbed more water.", "A and B: the thicker sponge absorbed more water.", "B and D: thickness does not affect how much it absorbs."], a: 2, why: "A and B are the same type (X) and differ only in thickness, and the thicker one (B) absorbed more. B and C have the same thickness; C and D, and B and D, differ in both type and thickness, so they are not fair.", lvl: 4, tbl: [["Sponge", "Type of sponge", "Thickness (cm)", "Water absorbed (ml)"], ["A", "X", "1", "30"], ["B", "X", "2", "55"], ["C", "Y", "2", "40"], ["D", "Z", "3", "50"]] },
    { q: "Strips of the same length and thickness were tested by adding weights until each strip broke. Which conclusion is supported by a FAIR comparison?", o: ["Cotton is stronger than nylon, because S held more weights than Q.", "Nylon is stronger than cotton, because Q held more weights than P.", "Wider strips are weaker, because S held fewer weights than R.", "Width does not affect strength, because Q and S held similar numbers."], a: 1, why: "P and Q have the same width and differ only in material, and nylon (Q) held more. S and Q differ in both material and width, so they cannot be compared fairly. S and R have the same width, so they cannot show anything about width.", lvl: 4, tbl: [["Strip", "Material", "Width (cm)", "Weights held before breaking"], ["P", "Cotton", "2", "6"], ["Q", "Nylon", "2", "10"], ["R", "Nylon", "4", "18"], ["S", "Cotton", "4", "11"]] }
  ],
  oe: [
    { q: "Mei dipped the bottom end of strips of three brands of paper towel into a dish of coloured water. The strips were the same size. After 5 minutes, she measured how high the water had risen up each strip. (a) Which paper towel absorbs water the best? (b) Explain your answer using the graph. (c) State one variable, other than the size of the strips, that she must keep the same.", marks: 3, kw: [["brand b", "b is", "b absorbs", "b soaked", "b rose"], ["highest", "rose the most", "risen the most", "11", "tallest"], ["time", "5 minutes", "five minutes", "same amount of water", "same volume of water", "same depth", "same dish", "same coloured water"]], model: "(a) Brand B. (b) The water rose the highest up the Brand B strip (11 cm), so it soaked up the most water. (c) The time the strips were left in the water (5 minutes).", fig: { type: "bar", xl: "Paper towel", yl: "Height water rose (cm)", bars: [["Brand A", 4], ["Brand B", 11], ["Brand C", 7]] } },
    { q: "Siti shone a torch at a screen. She placed sheets of a material between the torch and the screen, adding one sheet at a time, until no light could be seen on the screen. The sheets were all the same size. (a) Which material is opaque? (b) Explain your answer to (a) using the results. (c) Which material lets the most light pass through? (d) State one other variable she must keep the same.", marks: 4, x: 1, kw: [["cardboard"], ["one sheet", "1 sheet", "first sheet", "single sheet", "only one"], ["clear plastic"], ["distance", "same torch", "same brightness", "same screen"]], model: "(a) Cardboard. (b) Only one sheet of cardboard was needed to stop all the light, so it lets no light pass through. (c) The clear plastic sheet, because even 20 sheets did not stop all the light. (d) The distance between the torch and the screen, or using the same torch.", tbl: [["Material", "Number of sheets needed to block all light"], ["Tracing paper", "9"], ["Cotton cloth", "4"], ["Cardboard", "1"], ["Clear plastic sheet", "more than 20"]] },
    { q: "Ravi wants to find out which type of plastic is the strongest for making shopping bags. He made three bags of the same size from three types of plastic and added 1 kg packets of rice to each bag until it tore. (a) Explain why his test is not fair. (b) Suggest how he can make the test fair. (c) How will he know which plastic is the strongest?", marks: 3, kw: [["thicker", "different thickness", "thickness is different"], ["same thickness"], ["most rice", "most packets", "most kg", "most weight", "heaviest", "greatest number", "most number"]], model: "(a) Bag B is thicker than bags A and C, so it may hold more rice just because it is thicker. (b) He should use bags of the same thickness, so that only the type of plastic is different. (c) The bag that holds the most rice (the greatest number of packets) before it tears is made of the strongest plastic.", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Plastic type A", "0.02 mm thick", "Add 1 kg rice each time"] }, { label: "B", icon: "box", lines: ["Plastic type B", "0.05 mm thick", "Add 1 kg rice each time"] }, { label: "C", icon: "box", lines: ["Plastic type C", "0.02 mm thick", "Add 1 kg rice each time"] }] } },
    { q: "Four materials of the same size were tested. In the waterproof test, 50 ml of water was poured onto each material stretched over a cup. In the strength test, weights were added until each material tore. A picnic mat for the Botanic Gardens must stop the wet grass from wetting the users and must not tear easily. (a) Which material is the most suitable? (b) Explain why S is not suitable, even though it is the strongest. (c) Explain why P is not suitable, even though it is waterproof.", marks: 3, kw: [["r"], ["let water", "lets water", "water through", "not waterproof", "10 ml", "dripped"]
, ["tear", "weak", "not strong", "only 3", "fewest"]], model: "(a) Material R. (b) S let 10 ml of water drip through, so it is not waterproof and the users would get wet. (c) P held only 3 weights before it tore, so it is weak and would tear easily.", tbl: [["Material", "Water that dripped through (ml)", "Weights held before tearing"], ["P", "0", "3"], ["Q", "25", "14"], ["R", "0", "12"], ["S", "10", "16"]] },
    { q: "Material Q left a scratch on a piece of glass. Wei Ming says, ‘Q is harder than glass, so Q will not break when it is dropped.’ (a) What does the scratch test tell us about Q? (b) Is Wei Ming’s claim correct? (c) Explain your answer to (b). (d) Suggest a simple test to find out whether Q breaks easily.", marks: 4, x: 1, kw: [["harder than glass", "q is harder", "glass is softer"], ["not correct", "incorrect", "wrong", "not right"], ["different", "not the same", "glass is hard", "glass itself is hard"], ["drop"]], model: "(a) Q is harder than glass, because a harder material can scratch a softer one. (b) His claim is not correct. (c) Being hard is different from being strong: glass itself is hard, but it breaks easily when dropped. (d) Drop Q and a piece of glass of the same size from the same height onto the floor and see whether Q breaks." },
    { q: "A pair of canvas school shoes has rubber soles and a cotton canvas top. (a) Explain why rubber is suitable for the soles. (b) Pupils’ feet get wet when they walk in heavy rain in these shoes. Explain why, using a property of cotton canvas. (c) Glass and ceramic are waterproof. Explain why they are NOT used for the soles.", marks: 3, kw: [["flexible", "bend", "waterproof"], ["absorb", "soak", "not waterproof", "let water", "lets water"], ["break", "crack", "not flexible", "cannot bend", "shatter"]], model: "(a) Rubber is flexible, so the sole can bend as the pupil walks, and it is waterproof. (b) Cotton canvas absorbs water, so the rain soaks through to the feet. (c) Glass and ceramic are not flexible and break easily, so the soles would crack when the pupil walks." }
  ],
  tf: [
    { s: "A material that is coloured cannot be transparent.", a: false, why: "A green glass bottle is coloured but still lets most light through, so we can see clearly through it." },
    { s: "A softer material can scratch a harder material if you press hard enough.", a: false, why: "Only a harder material can scratch a softer one, however hard you press." },
    { s: "Cutting a floating wooden block into small pieces makes the pieces sink.", a: false, why: "The small pieces are still wood, and wood floats whatever the size of the piece." },
    { s: "A thin sheet of aluminium foil is flexible.", a: true, why: "Although it is a metal, a thin sheet of foil can bend without breaking." },
    { s: "A material that absorbs water can still float.", a: true, why: "A dry kitchen sponge absorbs water and it floats; absorbing and floating are different properties." },
    { s: "Waterproof materials always float.", a: false, why: "Glass and steel are waterproof, but a glass marble and a steel spoon sink." },
    { s: "In a scratch test, the material that is left with a mark on it is the softer material.", a: true, why: "The harder material makes the scratch; the softer material gets scratched." },
    { s: "A material must be hard to be strong.", a: false, why: "Rubber is strong enough for car tyres, yet it is not hard – it is easy to dent." },
    { s: "A translucent material lets more light pass through than an opaque material.", a: true, why: "Translucent materials let some light through; opaque materials let no light through." },
    { s: "The aim of an experiment should name the variable changed and the variable measured.", a: true, why: "For example: ‘To find out whether the type of cloth affects how much water it absorbs.’" }
  ],
  doc: [
    { q: "Ravi tested the strength of three types of paper by hanging weights on strips of each paper until they tore. Explain why all the strips must be of the same length and width.", marks: 2, answers: ["A wider strip may hold more weights just because it is wider, so keeping the size the same means only the type of paper affects how many weights it holds.", "So that the strips look neat and are easy to compare with each other.", "So that it is a fair test."], best: 0, why: "Answer 1 explains how size could affect the result and links it to the variable being tested. Answer 3 only names ‘fair test’ without saying why, so it gets at most part of the marks. Answer 2 gives a reason that has nothing to do with the results." },
    { q: "Mei put pieces of cotton, nylon and wool of the same size into beakers each containing 100 ml of water, and then measured the water left. State the aim of her experiment.", marks: 1, answers: ["To find out about cloths and water.", "To find out whether the type of cloth affects how much water it absorbs.", "To see which beaker has the most water left at the end."], best: 1, why: "Answer 2 names the variable changed (type of cloth) and what is measured (how much water it absorbs). Answer 1 is too vague – it names neither variable. Answer 3 talks about the beaker, not the property of the cloth being tested." }
  ]
};
