window.BANK = window.BANK || {};
BANK["mixed"] = {
  notes: [
    { h: "How to crack a crossover question", t: "Integrated questions mix two or more topics in one story, e.g. a life cycle investigation where the container material matters. First spot every topic hiding in the question. Then answer each part with the keywords from its own topic: a materials part needs a property (transparent, waterproof, strong), a life cycle part needs a stage (egg, larva, pupa, adult) and a magnets part needs magnetic or non-magnetic.", kw: ["identify each topic", "use the keyword of each topic", "property", "stage"] },
    { h: "Living or non-living, then classify", t: "Living things need air, food and water, grow, reproduce and respond to changes. A moving toy car or a burning candle is still non-living because it cannot grow or reproduce. Once something is non-living, we classify it by its material properties, e.g. attracted by a magnet or not, transparent or opaque, flexible or not.", kw: ["need air, food and water", "grow", "reproduce", "material properties"] },
    { h: "Choosing a container for a life cycle study", t: "A container for living things must let air in (small holes or a netting lid) but keep the animal from escaping. A transparent material such as glass or clear plastic lets us observe every stage without opening it. A waterproof container is needed for water animals like tadpoles and mosquito larvae.", kw: ["small holes to let air in", "transparent so we can observe", "waterproof", "cannot escape"] },
    { h: "Mould and materials", t: "Fungi such as mould need air, water, food and warmth to grow. An absorbent material such as wood soaks up water and stays damp, and tiny bits of food get trapped in its cuts, so mould grows easily on it. A waterproof material such as plastic does not absorb water, so it dries faster when wiped. Any board left wet with food on it can still grow mould.", kw: ["fungi need water", "absorbs water and stays damp", "waterproof so it dries quickly", "food"] },
    { h: "Magnets meet materials", t: "Magnets attract magnetic materials: iron, steel, nickel and cobalt. Aluminium, copper, plastic, glass, wood, paper and rubber are non-magnetic. A recycling plant uses a strong magnet to pull steel cans out of a mixture, but it cannot separate aluminium cans from plastic bottles because both are non-magnetic.", kw: ["magnetic materials", "iron, steel, nickel, cobalt", "aluminium is non-magnetic", "not all metals"] },
    { h: "Mosquitoes, water and nets", t: "A mosquito has four stages: egg, larva, pupa and adult. The eggs, larvae and pupae all live in stagnant (still) water; only the adult flies. Removing stagnant water stops the young stages from developing into adults. A good mosquito net has holes smaller than a mosquito but still lets air through, and is strong and flexible.", kw: ["lays eggs in stagnant water", "larvae and pupae live in water", "holes too small for mosquitoes", "lets air through"] },
    { h: "Seeds, spores and fungi in a garden", t: "Flowering plants such as balsam and chilli padi grow from seeds. Ferns and mosses are non-flowering plants that reproduce by spores, often found as brown dots under fern leaves. Mushrooms and bread mould also reproduce by spores but they are fungi, not plants: they cannot make their own food and get food from dead or decaying matter.", kw: ["seeds", "spores", "fungi are not plants", "cannot make their own food"] },
    { h: "Fair tests in any topic", t: "In a fair test, change only one variable, keep all other variables the same, and measure one result. To test the material of a board, only the material changes; the amount of water, food, place and time stay the same. Using several animals, seeds or pieces of bread in each set-up makes the result more reliable.", kw: ["change only one variable", "keep the other variables the same", "measure", "more reliable"] }
  ],
  traps: [
    "Mushrooms reproduce by spores so they are plants -> mushrooms are fungi; they cannot make their own food.",
    "All metals are attracted by magnets -> only iron, steel, nickel and cobalt are; aluminium and copper are not.",
    "If a magnet attracts an object, the object is a magnet -> it may just be a magnetic material; only repelling proves it is a magnet.",
    "Mosquito pupae live on land like butterfly pupae -> mosquito eggs, larvae and pupae all live in water.",
    "Plastic boards never grow mould -> any board left wet with bits of food can grow mould; plastic just dries faster.",
    "A container with no holes keeps animals safe -> living things need air, so the container needs small air holes.",
    "A toy that moves is living -> it cannot grow or reproduce, so it is non-living.",
    "Glass is used for an observation tank because it is strong -> the key property is that glass is transparent (and waterproof)."
  ],
  mcq: [
    { q: "Which of the following is NOT a living thing?", o: ["Yeast", "Mould on bread", "A plastic plant", "A mealworm"], a: 2, why: "A plastic plant cannot grow or reproduce. Yeast and mould are fungi and a mealworm is an insect larva, so they are all living.", lvl: 1 },
    { q: "Where does a mosquito usually lay its eggs?", o: ["On the surface of stagnant water", "On the underside of plant leaves", "Deep inside the soil in the garden", "On dry sand in sunny places"], a: 0, why: "Mosquitoes lay eggs on still (stagnant) water, where the larvae and pupae will live. That is why we remove stagnant water to stop mosquitoes breeding.", lvl: 1 },
    { q: "At a recycling plant, a large magnet hangs over a conveyor belt. Which item will it pick up?", o: ["An aluminium drink can", "A glass bottle", "A newspaper", "A steel food can"], a: 3, why: "Steel is a magnetic material. Aluminium is a metal but it is non-magnetic, so the magnet will not pick up the drink can.", lvl: 1 },
    { q: "A fern and a mushroom are alike because both ______.", o: ["make their own food", "reproduce by spores", "have flowers", "reproduce from seeds"], a: 1, why: "Both reproduce by spores. Only the fern can make its own food; the mushroom is a fungus and cannot.", lvl: 1 },
    { q: "Mould grows fastest on a slice of bread that is ______.", o: ["dry and kept in the fridge", "moist and kept in a warm place", "wrapped tightly and kept in the freezer", "toasted until hard and dry"], a: 1, why: "Mould is a fungus that needs water, air, food and warmth. Moist bread in a warm place gives it all of these.", lvl: 1 },
    { q: "Siti keeps mealworms in a plastic box of oats. Which stage of the mealworm beetle does not feed and hardly moves?", o: ["Larva", "Adult", "Larva and adult", "Pupa"], a: 3, why: "The pupa does not feed and hardly moves while it changes into an adult. The larva and the adult both eat the oats.", lvl: 1 },
    { q: "Which property of glass makes it suitable for a terrarium in which pupils observe small plants?", o: ["It is transparent.", "It is flexible.", "It is absorbent.", "It is magnetic."], a: 0, why: "Glass is transparent, so the plants can be seen clearly from outside. Glass is not flexible, not absorbent and not magnetic.", lvl: 1 },
    { q: "Which of these reproduce by spores?\nA: fern   B: mushroom   C: moss   D: balsam", o: ["A and B only", "B and C only", "A, B and C only", "A, B, C and D"], a: 2, why: "Ferns, mosses and mushrooms all reproduce by spores. Balsam is a flowering plant that reproduces by seeds.", lvl: 1 },

    { q: "Study the flowchart. Which set of things correctly matches A, B, C and D?", fig: { type: "flow", root: "Things", node: { q: "Is it living?", yes: { q: "Grows from a spore?", yes: "A", no: "B" }, no: { q: "Attracted by magnet?", yes: "C", no: "D" } } }, o: ["A: mango tree, B: mushroom, C: steel paper clip, D: glass marble", "A: fern, B: bread mould, C: iron nail, D: rubber band", "A: mushroom, B: sunflower, C: aluminium can, D: steel pin", "A: mushroom, B: mango tree, C: steel paper clip, D: glass marble"], a: 3, why: "A mushroom grows from a spore, a mango tree grows from a seed, steel is magnetic and glass is not. Bread mould grows from a spore so it cannot be B, and aluminium is non-magnetic so it cannot be C.", lvl: 2 },
    { q: "Dev washed four chopping boards and left them in the kitchen for 5 days. The graph shows the number of mould patches on each. Which conclusion is supported by the graph?", fig: { type: "bar", title: "Mould patches after 5 days", xl: "Chopping board", yl: "Number of mould patches", bars: [["Wood, left wet", 14], ["Plastic, left wet", 6], ["Wood, dried", 3], ["Plastic, dried", 1]] }, o: ["Mould grows only on wooden boards, not on plastic ones.", "Drying a board reduces mould growth on both materials.", "Plastic boards never grow mould, even when left wet.", "Wood is waterproof, so mould grows more on wooden boards."], a: 1, why: "For both wood and plastic, the dried board had fewer patches than the wet one. Plastic boards did grow some mould, and wood is absorbent, not waterproof.", lvl: 2 },
    { q: "The diagram shows the life cycle of a mosquito. Which statement about stage P is correct?", fig: { type: "cycle", stages: ["Egg", "P", "Pupa", "Adult"] }, o: ["It lives in water and moves about to feed.", "It lives on land and can fly.", "It does not feed and is found in soil.", "It looks like a small adult."], a: 0, why: "Stage P is the larva (wriggler). It lives in water and feeds actively. Only the adult flies, and the larva looks very different from the adult.", lvl: 2 },
    { q: "Bar magnet A is brought near rod X and they attract, as shown. What could rod X be?\n1: an iron rod   2: a steel rod   3: a bar magnet   4: an aluminium rod", fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "X", kind: "bar", text: "?" }], between: ["attract"] }, o: ["1 only", "1 and 2 only", "1, 2 and 3 only", "1, 2, 3 and 4"], a: 2, why: "A magnet attracts iron, steel and the opposite pole of another magnet. Aluminium is non-magnetic, so it would not be attracted.", lvl: 2 },
    { q: "Rui wants to find out if mealworm larvae prefer dark or bright places. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Dark", "Oats", "10 larvae"] }, { label: "B", icon: "box", lines: ["Bright", "Oats", "10 larvae"] }, { label: "C", icon: "box", lines: ["Bright", "No food", "10 larvae"] }, { label: "D", icon: "box", lines: ["Dark", "Oats", "5 larvae"] }] }, o: ["A and D", "B and C", "A and B", "C and D"], a: 2, why: "A and B differ only in light. A and D differ in the number of larvae; B and C differ in food.", lvl: 2 },
    { q: "Study the table. Which material is the most suitable for a mosquito net over a bed?", tbl: [["Material", "Size of holes", "Strength"], ["W", "Very small", "Strong"], ["X", "Large", "Strong"], ["Y", "Very small", "Weak"], ["Z", "No holes", "Strong"]], o: ["W", "X", "Y", "Z"], a: 0, why: "W has holes too small for mosquitoes but still lets air through, and it is strong so it will not tear easily. Z has no holes, so air cannot pass through and the sleeper would feel stuffy.", lvl: 2 },
    { q: "Study the Venn diagram. Which statement about it is correct?", fig: { type: "venn", a: "Reproduces by spores", b: "Makes its own food", onlyA: ["mushroom", "bread mould"], both: ["fern", "moss"], onlyB: ["hibiscus", "rice plant"], neither: ["cat", "housefly"] }, o: ["All the living things that make their own food grow from seeds.", "Mushrooms are placed wrongly because they are plants.", "The cat is placed wrongly because it is a living thing.", "Every living thing shown that makes its own food is a plant."], a: 3, why: "Hibiscus, rice plant, fern and moss are all plants. Ferns and moss grow from spores, not seeds, and the outside region can hold living things too.", lvl: 2 },
    { q: "A bean seed germinated in a clear plastic cup. The graph shows the height of the seedling. Between which days did it grow the fastest?", fig: { type: "line", xl: "Day", yl: "Height of seedling (cm)", pts: [["0", 0], ["2", 1], ["4", 3], ["6", 8], ["8", 11], ["10", 12]] }, o: ["Day 0 to Day 2", "Day 4 to Day 6", "Day 6 to Day 8", "Day 8 to Day 10"], a: 1, why: "From Day 4 to Day 6 the height rose by 5 cm, the biggest increase. The line is also steepest there.", lvl: 2 },
    { q: "Mei sprinkled the same amount of water on two slices of bread. She sealed one in a clear glass jar and one in a metal tin with a lid, and kept both on the same shelf. After 5 days, both slices had the same amount of mould. What can she conclude?", o: ["Mould needs light to grow.", "Mould grows only in glass containers.", "Mould cannot grow in the dark.", "Mould can grow with or without light."], a: 3, why: "Glass is transparent, so light entered the jar, but the metal tin is opaque, so the bread inside was in the dark. Mould grew equally in both, so light is not needed.", lvl: 3 },
    { q: "Which animal is an insect and has a life cycle with only three stages?", o: ["Butterfly", "Frog", "Cockroach", "Chicken"], a: 2, why: "A cockroach is an insect with egg, nymph and adult stages. A butterfly is an insect but has four stages; a frog has four stages and a chicken has three, but neither is an insect.", lvl: 2 },
    { q: "Ali’s pencil case has a fabric flap that snaps shut onto a small magnet. Inside the flap is a thin piece of material. What is this piece most likely made of?", o: ["Steel", "Aluminium", "Plastic", "Copper"], a: 0, why: "The flap sticks to the magnet, so the piece must be a magnetic material such as steel. Aluminium and copper are metals but are non-magnetic.", lvl: 2 },
    { q: "Which of these is NOT true of both a mushroom and a mealworm?", o: ["They need air, food and water.", "They can make their own food.", "They grow.", "They reproduce."], a: 1, why: "Neither can make its own food: the mushroom feeds on dead or decaying matter and the mealworm eats grains. Both are living, so the other three are true of both.", lvl: 2 },
    { q: "Aisha keeps tadpoles in a glass tank of pond water. What should she add as the tadpoles develop into young frogs?", o: ["A rock above the water line so they can climb out", "More water, filling the tank right to the top", "A waterproof lid with no holes to keep them in", "A black cover so the tank is always dark and cool"], a: 0, why: "Young frogs leave the water and need a place to climb out. A lid with no holes would stop fresh air from getting in.", lvl: 2 },

    { q: "Three ring magnets are placed on a wooden rod as shown. Ring A has its N pole facing up. Which shows the poles on the upper faces of rings B and C?", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, false] }, o: ["B: N, C: N", "B: N, C: S", "B: S, C: N", "B: S, C: S"], a: 3, why: "B floats, so its bottom is N (like poles repel) and its top is S. C touches B, so C’s bottom is N (unlike poles attract) and its top is S.", lvl: 3 },
    { q: "Which statement is NOT true?", o: ["A fern and a moss both reproduce by spores, not seeds.", "Mushrooms are plants because they grow in soil and make spores.", "Bread mould needs water to grow, so damp bread grows mould faster.", "A seed contains a young plant and stored food."], a: 1, why: "Mushrooms are fungi, not plants. They cannot make their own food, even though they grow in soil and reproduce by spores.", lvl: 3 },
    { q: "A recycling plant tested four magnets by counting the steel paper clips each could hold. Which statement is supported by the graph?", fig: { type: "bar", xl: "Magnet", yl: "Number of paper clips held", bars: [["A (large)", 8], ["B (small)", 15], ["C (medium)", 4], ["D (small)", 11]] }, o: ["The bigger the magnet, the more paper clips it can hold.", "Magnet C is the strongest of the four magnets tested.", "The strength of a magnet cannot be judged by its size.", "All the small magnets held more than 12 paper clips each."], a: 2, why: "Small magnet B held the most clips, while large magnet A held fewer, so size does not tell us strength. D is small but held only 11.", lvl: 3 },
    { q: "Hui Min wants to find out if the material of a chopping board affects how much mould grows on it. Which two set-ups should she compare?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Wooden board", "Wiped with wet cloth", "Warm kitchen"] }, { label: "B", icon: "plate", lines: ["Plastic board", "Wiped with wet cloth", "Warm kitchen"] }, { label: "C", icon: "plate", lines: ["Plastic board", "Dried with towel", "Warm kitchen"] }, { label: "D", icon: "plate", lines: ["Wooden board", "Dried with towel", "In a fridge"] }] }, o: ["A and C", "A and B", "B and C", "C and D"], a: 1, why: "A and B differ only in the material. A and C differ in both material and wetness, so it would not be a fair test.", lvl: 3 },
    { q: "Rina wants a container in which she can watch mealworm beetles go through every stage of their life cycle. She will punch small air holes in the lid. Study the table. Which material is the best for the container?", tbl: [["Material", "Transparent?", "Waterproof?", "Breaks easily?"], ["P", "Yes", "Yes", "No"], ["Q", "Yes", "Yes", "Yes"], ["R", "No", "Yes", "No"], ["S", "Yes", "No", "No"]], o: ["P", "Q", "R", "S"], a: 0, why: "P is transparent, so she can see every stage, and it is waterproof and does not break easily. R is opaque, Q breaks easily, and S would get soggy from moist food like carrot pieces.", lvl: 3 },
    { q: "Study the flowchart for classifying some objects. Which object could be S?", fig: { type: "flow", root: "Objects", node: { q: "Attracted by magnet?", yes: "P", no: { q: "Transparent?", yes: "Q", no: { q: "Flexible?", yes: "R", no: "S" } } } }, o: ["Rubber band", "Glass marble", "Ceramic mug", "Steel paper clip"], a: 2, why: "A ceramic mug is non-magnetic, opaque and not flexible. A rubber band is flexible (R), a glass marble is transparent (Q) and a steel clip is magnetic (P).", lvl: 3 },
    { q: "The diagram shows the life cycle of a mealworm beetle. Which statements are correct?\nA: The larva and the adult look different.\nB: Stage P does not feed.\nC: The larva moults (sheds its skin) as it grows.", fig: { type: "cycle", stages: ["Egg", "Larva", "P", "Adult"] }, o: ["A and B only", "B and C only", "A and C only", "A, B and C"], a: 3, why: "P is the pupa, which does not feed. The worm-like larva looks very different from the adult beetle, and it moults several times as it grows.", lvl: 3 },
    { q: "Zara counted the mosquito larvae in a pail of rainwater left in the garden. Study the graph. Which is the most likely reason the number of larvae fell after Day 6?", fig: { type: "line", xl: "Day", yl: "Number of larvae", pts: [["0", 0], ["2", 20], ["4", 45], ["6", 45], ["8", 10], ["10", 5]] }, o: ["The larvae had no air in the water.", "The eggs had not hatched yet.", "The larvae were laying eggs.", "Many larvae had changed into pupae."], a: 3, why: "Larvae change into pupae, which are then no longer counted as larvae. Larvae cannot lay eggs; only adults do.", lvl: 3 },
    { q: "Magnet Q is placed between rods P and R. P and R are each either a magnet or a steel bar. P repels Q and R attracts Q. Which statement is definitely correct?", fig: { type: "magnets", items: [{ label: "P", kind: "bar", text: "?" }, { label: "Q", poles: "NS" }, { label: "R", kind: "bar", text: "?" }], between: ["repel", "attract"] }, o: ["P is a magnet; R may be a magnet or steel.", "P and R are both magnets.", "P is steel; R is a magnet.", "R is a magnet because it attracts Q."], a: 0, why: "Only a magnet can repel another magnet, so P must be a magnet. Attraction happens with a magnet or a magnetic material, so R could be either.", lvl: 3 }
  ],
  tf: [
    { s: "A mushroom is a non-flowering plant because it reproduces by spores.", a: false, why: "A mushroom is a fungus, not a plant; it cannot make its own food." },
    { s: "Both a steel can and an iron nail are attracted by a magnet.", a: true, why: "Steel and iron are magnetic materials." },
    { s: "All metals are attracted by magnets.", a: false, why: "Aluminium and copper are metals but they are non-magnetic." },
    { s: "Pouring away water collected in flower-pot plates helps stop mosquitoes completing their life cycle.", a: true, why: "The eggs, larvae and pupae need stagnant water; without it they cannot develop into adults." },
    { s: "A mosquito pupa lives on land.", a: false, why: "Mosquito pupae live in water, just like the larvae." },
    { s: "Mould grows easily on a damp wooden chopping board because wood absorbs water and traps bits of food.", a: true, why: "Mould needs water and food, and absorbent wood stays damp." },
    { s: "A plastic chopping board can never grow mould.", a: false, why: "If it is left wet with bits of food, mould can grow on plastic too." },
    { s: "A fern grows from a spore while a balsam plant grows from a seed.", a: true, why: "Ferns are non-flowering plants with spores; balsam is a flowering plant with seeds." },
    { s: "A battery-powered toy robot is a living thing because it can move.", a: false, why: "It cannot grow or reproduce, so it is non-living." },
    { s: "A glass tank suits tadpoles because glass is waterproof and transparent.", a: true, why: "It holds water and lets us see the tadpoles clearly." },
    { s: "In a fair test comparing mould on bread in light and in the dark, the type of bread can be different.", a: false, why: "Only light should change; the type of bread must be kept the same." },
    { s: "Bacteria are too small to be seen with our eyes alone.", a: true, why: "Bacteria can only be seen with a microscope." },
    { s: "A chick and a caterpillar both look like their adults when they hatch.", a: false, why: "A chick looks like a hen, but a caterpillar looks very different from a butterfly." },
    { s: "A magnet can be used to separate steel paper clips from plastic beads.", a: true, why: "Steel is magnetic; plastic is not." },
    { s: "Mealworms in an airtight box with no holes will grow into adults as long as they have food.", a: false, why: "They also need air; without air holes they will die." },
    { s: "Yeast, mushrooms and bread mould are all fungi.", a: true, why: "All three are fungi; none of them can make its own food." }
  ],
  sort: [
    { title: "Sort these into living things with spores, living things with seeds, and non-living things.", groups: ["Living: reproduces by spores", "Living: reproduces by seeds", "Non-living"], items: [["fern", 0], ["moss", 0], ["mushroom", 0], ["bread mould", 0], ["chilli padi plant", 1], ["durian tree", 1], ["rice plant", 1], ["iron nail", 2], ["plastic flower", 2], ["steel spoon", 2]] },
    { title: "At a recycling plant, a magnet hangs over the conveyor belt. Sort the items.", groups: ["Picked up by the magnet", "Stays on the belt"], items: [["steel food can", 0], ["steel bottle cap", 0], ["iron nail", 0], ["steel paper clip", 0], ["aluminium drink can", 1], ["glass jar", 1], ["plastic bottle", 1], ["newspaper", 1], ["copper wire", 1], ["aluminium foil tray", 1]] },
    { title: "Sort the young stages by where they live.", groups: ["Young stage lives in water", "Young stage lives on land"], items: [["mosquito larva", 0], ["mosquito pupa", 0], ["frog tadpole", 0], ["dragonfly nymph", 0], ["butterfly caterpillar", 1], ["mealworm larva", 1], ["chick", 1], ["cockroach nymph", 1], ["grasshopper nymph", 1]] }
  ],
  oe: [
    { q: "Lina set up two glass jars as shown to study the life cycle of the mealworm beetle. After 2 weeks, all the larvae in jar B had died, but those in jar A were alive.\n(a) Explain why the larvae in jar B died. [1]\n(b) State the property of glass that makes it suitable for this study. [1]\n(c) Why did Lina put 10 larvae in each jar instead of only 1? [1]", marks: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Glass jar, holes in lid", "Oats", "10 larvae"] }, { label: "B", icon: "jar", lines: ["Glass jar, no holes", "Oats", "10 larvae"] }] }, kw: [["air"], ["transparent", "see through", "see clearly"], ["reliable", "by chance", "more accurate"]], model: "(a) Jar B had no holes, so fresh air could not enter. The larvae need air to stay alive, so they died. (b) Glass is transparent, so she can see the larvae clearly without opening the jar. (c) Using 10 larvae makes the result more reliable, because one larva might die or behave differently by chance." },
    { q: "Mr Tan wants a net to hang over his baby’s cot to keep mosquitoes out. Study the table.\n(a) Which material should he choose? Give two reasons based on the table. [2]\n(b) The NEA reminds residents to pour away water collected in pails and flower-pot plates. Using what you know about the mosquito’s life cycle, explain why. [2]", marks: 4, tbl: [["Material", "Holes", "Strength"], ["Nylon netting", "Very small", "Strong"], ["Cotton lace", "Large", "Strong"], ["Plastic sheet", "No holes", "Strong"], ["Tissue paper", "No holes", "Weak"]], kw: [["small holes", "holes are very small", "very small", "cannot pass", "cannot get through", "cannot get in", "can’t get in"], ["strong", "not tear", "won’t tear"], ["lay", "laid"], ["larva", "larvae", "pupa", "pupae"]], model: "(a) Nylon netting. Its holes are very small, so mosquitoes cannot pass through, but air can still pass through so the baby stays cool. It is also strong, so it will not tear easily. (b) Mosquitoes lay their eggs in stagnant water, and the larvae and pupae also live in the water. If the water is poured away, the young stages cannot develop into adult mosquitoes." },
    { q: "At a recycling plant, a magnet lifts some cans off a mixed pile of steel cans, aluminium cans and plastic bottles.\n(a) Name the material of the cans that are lifted and state the property that makes the magnet lift them. [2]\n(b) The manager tested three magnets by counting the steel paper clips each could hold. Study the graph. Which magnet should he use to lift heavy cans? Explain. [2]", marks: 4, fig: { type: "bar", xl: "Magnet", yl: "Number of paper clips held", bars: [["Red", 25], ["Blue", 9], ["Green", 14]] }, kw: [["steel", "iron"], ["magnetic"], ["red"], ["more paper clips", "most paper clips", "stronger", "strongest", "more clips", "most clips"]], model: "(a) The lifted cans are made of steel. Steel is a magnetic material, so it is attracted by the magnet. Aluminium and plastic are non-magnetic. (b) The Red magnet. It held the most paper clips, so it is the strongest magnet and can lift heavier cans." },
    { q: "Jun washed a wooden chopping board and a plastic chopping board of the same size, left them both wet on the kitchen counter, and checked them after 5 days. Board A had many more mould patches than board B.\n(a) What variable did Jun change in this experiment? [1]\n(b) Explain why more mould grew on board A. [2]\n(c) Suggest one way to stop mould from growing on chopping boards. [1]", marks: 4, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Wooden board", "Washed, left wet", "Kitchen counter", "5 days"] }, { label: "B", icon: "plate", lines: ["Plastic board", "Washed, left wet", "Kitchen counter", "5 days"] }] }, kw: [["material", "type of board", "type of chopping board", "kind of board", "wood or plastic"], ["absorb", "soak"], ["stayed damp", "stays damp", "remain damp", "damp", "moist", "needs water", "need water", "mould needs water", "fungi need water", "fungus needs water"], ["dry"]], model: "(a) The material of the chopping board. (b) Wood absorbs water, so the wooden board stayed damp for a long time. Mould is a fungus that needs water to grow, so more mould grew on it. Plastic is waterproof and does not soak up water. (c) Dry the board completely with a clean towel after washing it." },
    { q: "Study the flowchart. A, B, C and D are a mushroom, a fern, a steel spoon and a rubber glove.\n(a) Which one is B? Explain your answer. [2]\n(b) Which one is C? [1]\n(c) Ken wants to add a battery-powered toy car to the ‘living’ branch because it moves. Explain why he is wrong. [1]", marks: 4, fig: { type: "flow", root: "Things", node: { q: "Is it living?", yes: { q: "Makes its own food?", yes: "A", no: "B" }, no: { q: "Attracted by magnet?", yes: "C", no: "D" } } }, kw: [["mushroom"], ["cannot make", "does not make", "feeds on", "gets its food"], ["spoon"], ["grow", "reproduce"]], model: "(a) B is the mushroom. It is living but it cannot make its own food; it feeds on dead or decaying matter. (b) C is the steel spoon, because steel is attracted by a magnet. (c) The toy car cannot grow or reproduce and does not need food, air and water, so it is non-living even though it moves." },
    { q: "Pupils recorded some living things found in the school garden in the Venn diagram. They also noticed brown dots under the leaves of the fern and mushrooms growing on a rotting log.\n(a) What do the brown dots under the fern leaves contain? [1]\n(b) Explain why the mushroom is not placed in the overlapping part. [1]\n(c) Using both headings, explain why the snail is placed outside both circles. [2]", marks: 4, fig: { type: "venn", a: "Reproduces by spores", b: "Makes its own food", onlyA: ["mushroom", "bread mould"], both: ["fern", "moss"], onlyB: ["balsam", "mango tree"], neither: ["snail"] }, kw: [["spore"], ["cannot make", "does not make", "not make"], ["not by spores", "not reproduce by spore", "doesn’t reproduce by spore", "no spores", "not spores", "lays eggs", "lay eggs", "laying eggs", "eggs"], ["eat", "feed", "snail cannot make", "snail does not make", "snail can’t make", "and cannot make", "and does not make", "also cannot make", "it cannot make its own food", "it also cannot"]], model: "(a) They contain spores, which can grow into new fern plants. (b) The mushroom is a fungus. It reproduces by spores but it cannot make its own food, so it is only in the spores circle. (c) The snail reproduces by laying eggs, not by spores, and it cannot make its own food; it has to eat plants." },
    { q: "Jia placed 5 green bean seeds on moist cotton wool in each container shown. Both containers were closed and kept in the same room. After 3 days, the seeds in both containers had germinated.\n(a) What can Jia conclude about light and germination? [1]\n(b) Why did she use 5 seeds in each container? [1]\n(c) She left the seedlings for another week. The seedlings in the tin became pale and weak, while those in the glass dish were green and healthy. Explain why. [1]", marks: 3, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Clear glass dish, lid", "Moist cotton wool", "5 seeds", "Same room"] }, { label: "B", icon: "box", lines: ["Metal tin with lid", "Moist cotton wool", "5 seeds", "Same room"] }] }, kw: [["not need light", "don’t need light", "doesn’t need light", "light is not needed", "not needed", "without light", "germinate in the dark", "germinated in the dark"], ["reliable", "by chance", "more accurate"], ["make food", "make their own food", "make its own food", "grow well", "did not get light", "didn’t get light", "light could not", "light cannot", "light reached", "got light", "get light"]], model: "(a) Seeds do not need light to germinate, because the seeds in the dark metal tin also germinated. (b) Using 5 seeds makes the result more reliable, in case some seeds do not germinate by chance. (c) Glass is transparent, so light reached those seedlings, but the metal tin is opaque. Young plants need light to make their own food and grow well." },
    { q: "Omar kept a mealworm in a plastic box with small holes in the lid and measured its body length every 2 weeks. Study the graph.\n(a) Describe how the length changed from Week 0 to Week 8. [1]\n(b) At Week 10, the animal was shorter and did not move or feed. Name the stage it was in. [1]\n(c) Why were there small holes in the lid? [1]", marks: 3, fig: { type: "line", xl: "Week", yl: "Body length (mm)", pts: [["0", 3], ["2", 8], ["4", 15], ["6", 22], ["8", 25], ["10", 16]] }, kw: [["increase", "longer", "grew"], ["pupa"], ["air"]], model: "(a) The length increased from 3 mm to 25 mm; the larva grew longer. (b) It was a pupa. (c) The holes let air into the box, because the mealworm needs air to live." },
    { q: "Three ring magnets are placed on a plastic rod as shown. Ring A has its S pole facing up.\n(a) Explain why ring C floats above ring B. [1]\n(b) Explain why a plastic rod is used instead of a steel rod. [1]\n(c) Ring B is taken out, turned upside down and put back in the same place. Describe what will happen to ring B and ring C. [2]", marks: 4, fig: { type: "rings", rings: [{ label: "A", top: "S" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [false, true] }, kw: [["like poles", "same poles", "repel"], ["magnetic", "non-magnetic", "not attracted"], ["b will float", "b floats", "float above a", "floats above a"], ["c will touch", "c touches", "c will rest", "c rests", "c will stick", "c sticks", "c will be attracted", "c is attracted", "c will fall", "c falls", "c will drop", "c drops", "c will move down", "c moves down", "c will come down"]], model: "(a) The poles facing each other on B and C are like poles, so they repel. (b) Plastic is non-magnetic, so the rings are not attracted to the rod and can slide freely. Steel is magnetic and the rings would stick to it. (c) Ring B will float above ring A because like poles now face each other and repel. Ring C will be attracted and rest on ring B, touching it." },
    { q: "Aisha keeps tadpoles in a glass tank of pond water with a netting cover.\n(a) State one property of glass that makes it suitable for the tank. [1]\n(b) When the tadpoles grow legs, her teacher tells her to put a large rock sticking out of the water. Explain why. [1]\n(c) Why does she use a netting cover instead of a solid plastic lid? [1]", marks: 3, kw: [["transparent", "see through", "waterproof"], ["out of the water", "climb", "land"], ["air"]], model: "(a) Glass is transparent, so she can observe the tadpoles, and it is waterproof, so it can hold water. (b) The young frogs need to climb out of the water onto land, so the rock gives them a place to rest out of the water. (c) The netting lets air pass through into the tank but stops the young frogs from escaping." },
    { q: "Mrs Lee kept three slices of the same bread in different ways and recorded the number of days before mould first appeared. Study the graph.\n(a) Explain why the bread in the fridge took the longest time to grow mould. [1]\n(b) Why did the toasted bread take longer to grow mould than the bread on the table? [1]\n(c) Besides fungi, name one other group of living things that can make food go bad. [1]", marks: 3, fig: { type: "bar", xl: "How bread was kept", yl: "Days before mould appeared", bars: [["On table", 3], ["Toasted, on table", 6], ["In fridge", 10]] }, kw: [["cold", "low temperature", "cool", "not warm"], ["dry", "less water", "less moisture", "little water"], ["bacteria"]], model: "(a) The fridge is cold. Mould grows best in a warm place, so it grew more slowly in the cold. (b) Toasting made the bread dry and it had less water. Mould needs water to grow. (c) Bacteria." },
    { q: "Rahim wants to find out whether the type of material affects how much mould grows on it. He cuts same-sized pieces of paper, cotton cloth and plastic, sprinkles each with the same amount of water and rubs a little bread on each.\n(a) What variable is he changing? [1]\n(b) State one variable he must keep the same. [1]\n(c) Predict which material will have the least mould. Explain your prediction. [2]", marks: 4, kw: [["type of material", "kind of material", "the material used", "material of each piece", "different material"], ["amount of water", "amount of bread", "size", "temperature", "place", "number of days"], ["plastic"], ["absorb", "waterproof", "soak"]], model: "(a) The type of material. (b) The amount of water on each piece (also the size of each piece, the amount of bread, the place and the number of days). (c) Plastic. Plastic is waterproof and does not absorb water, so the water dries up quickly and mould gets less water. Paper and cotton cloth absorb water and stay damp." }
  ],
  doc: [
    { q: "Why should we change the water in a flower vase every few days?", marks: 2, answers: ["Because the water becomes dirty.", "Mosquitoes lay eggs in stagnant water. Changing the water every few days removes the eggs and larvae before they can develop into adult mosquitoes.", "So that the mosquitoes will die."], best: 1, why: "Answer 2 links the life cycle (eggs laid in stagnant water) to the result (young stages cannot become adults). Answer 1 is too vague and never mentions mosquitoes; answer 3 says what happens without explaining how or which stage." },
    { q: "Explain why a plastic chopping board is less likely than a wooden one to grow mould after washing.", marks: 2, answers: ["Plastic is waterproof and does not absorb water, so it dries quickly. Mould needs water to grow, so less mould grows on it.", "Plastic is stronger than wood.", "Mould does not like plastic."], best: 0, why: "Answer 1 gives the right property (waterproof, does not absorb water) and links it to what mould needs (water). Answer 2 uses the wrong property, and answer 3 is vague with no science reason." },
    { q: "A magnet attracts object X. Ben says X must be a magnet. Is he right? Explain.", marks: 2, answers: ["Yes, because only magnets attract other things.", "No, because X is made of iron.", "No. A magnet also attracts magnetic materials such as iron and steel, so X could just be a magnetic material. Only repelling shows that X is a magnet."], best: 2, why: "Answer 3 explains that attraction happens with magnetic materials too and gives the correct test (repulsion). Answer 1 is wrong science; answer 2 claims X is iron without evidence, since X could also be steel or a magnet." },
    { q: "A mushroom and a fern both reproduce by spores. Explain why a mushroom is not a plant.", marks: 2, answers: ["Because the mushroom has no leaves.", "Because a mushroom is small.", "A mushroom is a fungus. It cannot make its own food and gets its food from dead or decaying matter, while plants make their own food."], best: 2, why: "Answer 3 names the group (fungus) and gives the key difference: it cannot make its own food. Answer 1 describes an appearance without the key idea, and answer 2 is irrelevant because size does not decide the group." },
    { q: "Why did Ali punch small holes in the lid of the container for his mealworms?", marks: 2, answers: ["So that air can enter the container. Mealworms are living things and need air to survive.", "So that the mealworms can get out.", "So they can breathe."], best: 0, why: "Answer 1 names air and explains why the mealworms need it. Answer 2 is the wrong way round, because the holes are small to stop them escaping. Answer 3 is on the right idea but never mentions air entering the container, so it would get at most 1 mark." },
    { q: "Siti wants to watch the roots of a bean seedling grow. Why is a clear plastic cup better than a paper cup?", marks: 2, answers: ["Because paper is weak.", "The clear plastic cup is transparent, so she can see the roots growing through it. The paper cup is opaque, so she cannot see the roots.", "Because the plastic cup is nicer to look at."], best: 1, why: "Answer 2 names the property (transparent) and links it to seeing the roots, and it compares with the opaque paper cup. Answer 1 uses a property that does not explain seeing the roots, and answer 3 has no science reason." }
  ]
};
