window.BANKV = window.BANKV || {};
BANKV["mixed"] = {
  flash: [
    { f: "Define: magnetic material", b: "A material that is attracted by a magnet: iron, steel, nickel and cobalt. Aluminium and copper are metals but are non-magnetic." },
    { f: "Why is a mushroom NOT a plant?", b: "It is a fungus. It cannot make its own food and gets its food from dead or decaying matter. (It reproduces by spores.)" },
    { f: "Stages of a mosquito’s life cycle and where each lives", b: "Egg, larva and pupa live in stagnant (still) water; only the adult lives out of the water and can fly." },
    { f: "Why does removing stagnant water reduce mosquitoes?", b: "Mosquitoes lay eggs in stagnant water. Without it, no eggs are laid and the larvae and pupae cannot develop into adults." },
    { f: "The only test that proves an object is a magnet", b: "Repulsion: if it repels a magnet, it is a magnet. Attraction alone is not proof, as it may just be a magnetic material." },
    { f: "Characteristics of ALL living things", b: "They need air, food and water; they grow; they reproduce; they respond to changes around them." },
    { f: "Why does mould grow more on a damp wooden board than a plastic one?", b: "Wood absorbs water and stays damp, and mould needs water to grow. Plastic is waterproof and does not absorb water, so it dries quickly." },
    { f: "Define: transparent", b: "Allows most light to pass through, so we can see clearly through it, e.g. clear glass." },
    { f: "Seeds or spores: which plants use each?", b: "Flowering plants (e.g. balsam, chilli padi) reproduce by seeds. Non-flowering plants such as ferns and mosses reproduce by spores." },
    { f: "What does a seed need to germinate?", b: "Water, air and warmth (a suitable temperature). Light is not needed for germination." },
    { f: "Why can a fridge magnet hold a sheet of paper on a steel fridge door?", b: "Magnetic force can pass through non-magnetic materials such as paper, and steel is a magnetic material, so the magnet is attracted to the door." },
    { f: "Define: fair test", b: "Change only one variable, keep all the other variables the same, and measure one result." },
    { f: "Why use many seeds or animals in each set-up?", b: "To make the results more reliable, in case one seed does not germinate or one animal behaves differently by chance." },
    { f: "How does a pupa differ from a larva?", b: "A larva feeds actively and grows. A pupa does not feed and usually moves very little while it develops into an adult." },
    { f: "Why is a bat a mammal and not a bird?", b: "It has fur, gives birth to young alive and feeds its young on milk. Birds have feathers and lay eggs." }
  ],
  mcq: [
    { q: "The school canteen gives out spoons made of four different materials. Which spoon is waterproof AND attracted by a magnet?", o: ["Wooden spoon", "Plastic spoon", "Steel spoon", "Aluminium spoon"], a: 2, why: "Steel does not absorb water and is a magnetic material. Wood absorbs water, and plastic and aluminium are waterproof but non-magnetic.", lvl: 1 },
    { q: "Which group contains ONLY living things?", o: ["Yeast, fern and guppy", "Robot, fern and guppy", "Yeast, cloud and moss", "Fire, mushroom and ant"], a: 0, why: "Yeast is a fungus, a fern is a plant and a guppy is a fish, so all three grow and reproduce. A robot, a cloud and fire cannot reproduce, so they are non-living.", lvl: 1 },
    { q: "The diagram shows the life cycle of a flowering plant. What is stage X?", fig: { type: "cycle", stages: ["Seed", "X", "Adult plant"] }, o: ["Spore", "Pupa", "Fruit", "Seedling"], a: 3, why: "A seed germinates into a seedling, which grows into an adult plant. Spores are for non-flowering plants and fungi, a pupa is an animal stage, and the fruit comes after the adult plant flowers.", lvl: 1 },
    { q: "Which animal is a mammal?", o: ["Dolphin", "Penguin", "Shark", "Turtle"], a: 0, why: "A dolphin gives birth to young alive and feeds them on milk, even though it lives in the sea. A penguin is a bird, a shark is a fish and a turtle is a reptile.", lvl: 1 },
    { q: "Mrs Lim uses yeast to make bread dough rise. Yeast is a kind of ______.", o: ["bacterium", "plant", "animal", "fungus"], a: 3, why: "Yeast is a fungus, like mushrooms and mould. It is not a bacterium, and it cannot make its own food, so it is not a plant.", lvl: 1 },
    { q: "Raincoats sold at a pasar malam stall are made of plastic. Which property of plastic makes it suitable for a raincoat?", o: ["It is magnetic.", "It is waterproof.", "It is absorbent.", "It is transparent."], a: 1, why: "Plastic does not let water pass through, so the wearer stays dry. Some plastic is transparent, but that is not why it keeps rain out, and plastic is neither magnetic nor absorbent.", lvl: 1 },

    { q: "Kelvin placed 20 green bean seeds on moist cotton wool in each of four places and counted how many germinated after 4 days. Which statement is supported by the graph?", fig: { type: "bar", title: "Seeds germinated after 4 days", xl: "Place", yl: "Number of seeds germinated", bars: [["Fridge, 5 °C", 0], ["Air-con room, 24 °C", 16], ["Bright kitchen, 30 °C", 18], ["Dark cupboard, 30 °C", 18]] }, o: ["Seeds need light to germinate.", "The colder the place, the more seeds germinated.", "Seeds germinated as well in the dark as in the light.", "No seeds germinated in the air-con room."], a: 2, why: "The bright kitchen and the dark cupboard were both at 30 °C and both had 18 seeds germinated, so light made no difference. The colder fridge had the fewest, not the most, and 16 seeds germinated in the air-con room.", lvl: 2 },
    { q: "Study the classification key. Which animal could be S?", fig: { type: "flow", root: "Animals", node: { q: "Has feathers?", yes: "P", no: { q: "Has fur or hair?", yes: "Q", no: { q: "Has 6 legs?", yes: "R", no: "S" } } } }, o: ["Sparrow", "Cat", "Ant", "Guppy"], a: 3, why: "A guppy has no feathers, no fur and no legs, so it ends at S. A sparrow has feathers (P), a cat has fur (Q) and an ant has 6 legs (R).", lvl: 2 },
    { q: "Which of these are true of BOTH a mosquito and a frog?\nA: The young stages live in water.\nB: The adult can live out of the water.\nC: There is a pupa stage.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Mosquito larvae and pupae and frog tadpoles live in water, and both adults can live out of the water. Only the mosquito has a pupa stage; a frog goes egg, tadpole, young frog, adult.", lvl: 2 },
    { q: "Magnets X, Y and Z are placed in a row as shown. The poles of Y are not labelled. X and Y repel. What will happen between Y and Z?", fig: { type: "magnets", items: [{ label: "X", poles: "SN" }, { label: "Y", poles: "??" }, { label: "Z", poles: "NS" }], between: ["repel", "?"] }, o: ["They will attract, because unlike poles face each other.", "They will repel, because like poles face each other.", "They will attract, because like poles face each other.", "They will repel, because unlike poles face each other."], a: 0, why: "X’s N pole faces Y and they repel, so Y’s left end is N and its right end is S. Y’s S pole then faces Z’s N pole: unlike poles attract.", lvl: 2 },
    { q: "Residents of an HDB estate want to stop mosquitoes from breeding along their corridor. Which action does NOT help?", o: ["Turning pails over after use", "Pouring away water in pot plates", "Clearing leaves that block gutters", "Adding pot plates filled with water"], a: 3, why: "Pot plates filled with water give mosquitoes stagnant water in which to lay eggs. The other three actions remove stagnant water, so the young stages cannot develop.", lvl: 2 },
    { q: "Lim wants to find out if the number of strokes affects how strong a magnet a nail becomes when it is stroked with a magnet. Study the table. Which two set-ups should he compare?", tbl: [["Set-up", "Nail", "Number of strokes", "Magnet used"], ["P", "Steel", "20", "Magnet A"], ["Q", "Steel", "40", "Magnet A"], ["R", "Iron", "40", "Magnet B"], ["S", "Steel", "40", "Magnet B"]], o: ["Q and S", "P and S", "P and Q", "R and S"], a: 2, why: "P and Q differ only in the number of strokes. Q and S differ in the magnet used, R and S in the material of the nail, and P and S in two things.", lvl: 2 },
    { q: "Study the Venn diagram. Where should an aluminium drink can be placed?", fig: { type: "venn", a: "Waterproof", b: "Transparent", onlyA: ["rubber glove", "steel spoon"], both: ["glass jar", "clear plastic bag"], onlyB: [], neither: ["paper towel", "cotton shirt"] }, o: ["With the glass jar and clear plastic bag", "With the paper towel and cotton shirt", "With the rubber glove and steel spoon", "In the ‘Transparent’ circle only"], a: 2, why: "Aluminium does not let water through but we cannot see through it, so it is waterproof and opaque, like the rubber glove and steel spoon. Whether it is magnetic does not matter in this diagram.", lvl: 2 },
    { q: "Nora counted the steel paper clips a magnet attracted when it was held at different distances from the clips. Study the graph. About how many clips would it most likely attract at 2.5 cm?", fig: { type: "line", xl: "Distance from clips (cm)", yl: "Number of clips attracted", pts: [["0", 20], ["1", 14], ["2", 8], ["3", 4], ["4", 1], ["5", 0]] }, o: ["About 2", "About 10", "About 13", "About 6"], a: 3, why: "At 2 cm it attracted 8 clips and at 3 cm it attracted 4, so at 2.5 cm it would attract between 4 and 8, about 6. The further the magnet, the weaker its pull on the clips.", lvl: 2 },
    { q: "In the Cloud Forest at Gardens by the Bay, a guide points to a fern growing on a tree trunk. Which statement about the fern is correct?", o: ["It makes its own food and reproduces by seeds.", "It makes its own food and reproduces by spores.", "It cannot make its own food and reproduces by spores.", "It cannot make its own food and reproduces by seeds."], a: 1, why: "A fern is a non-flowering plant: like all plants it makes its own food, and it reproduces by spores. Growing on a tree trunk does not make it a fungus.", lvl: 2 },
    { q: "Which is NOT true of ALL insects?", o: ["They have wings.", "They have six legs.", "They have three body parts.", "They have a pair of feelers."], a: 0, why: "All insects have six legs, three body parts and a pair of feelers, but not all have wings; worker ants, for example, have none. Many flying animals, such as birds and bats, are not insects.", lvl: 2 },
    { q: "Why does the school canteen keep cut fruit in a refrigerator?", o: ["The cold kills all the fungi and bacteria on it.", "The cold slows down the growth of fungi and bacteria.", "There is no air in the fridge, so nothing can grow.", "The light in the fridge stops mould from growing."], a: 1, why: "Fungi and bacteria that spoil food grow slowly in the cold. The cold does not kill them all, so food still goes bad after some time, and a fridge does contain air.", lvl: 2 },

    { q: "Which statement about bread mould and bacteria is NOT true?", o: ["Both are living things that need food and water.", "Both can cause food to spoil.", "Neither of them is a plant or an animal.", "A single bacterium can be seen without a microscope."], a: 3, why: "Bacteria are far too small to be seen with our eyes alone; we need a microscope. Mould is a fungus, so neither is a plant or an animal; both are living and both can spoil food.", lvl: 3 },
    { q: "A hawker needs a material for takeaway bags of soup. The bag must hold the soup without leaking, must not tear easily, and should let customers see the food inside. Study the table. Which material is the most suitable?", tbl: [["Material", "Waterproof?", "Tears easily?", "Transparent?"], ["K", "Yes", "Yes", "Yes"], ["L", "Yes", "No", "No"], ["M", "Yes", "No", "Yes"], ["N", "No", "No", "Yes"]], o: ["K", "L", "M", "N"], a: 2, why: "Only M meets all three needs: waterproof, does not tear easily and transparent. K tears easily, L is opaque, and N is not waterproof, so the soup would leak.", lvl: 3 },
    { q: "The diagram shows the life cycle of animal Y. Which animals could be Y?\nA: cockroach   B: grasshopper   C: dragonfly   D: housefly", fig: { type: "cycle", stages: ["Egg", "Nymph", "Adult"] }, o: ["A and B only", "A, B and C only", "B and D only", "A, B, C and D"], a: 1, why: "Cockroaches, grasshoppers and dragonflies have three stages: egg, nymph and adult. A housefly has four stages (egg, larva, pupa, adult), so it cannot be Y.", lvl: 3 },
    { q: "Mosquito larvae must swim up to the water surface to take in air. NEA officers sometimes spread a thin layer of oil on the stagnant water in drains. What is most likely to happen?", o: ["The larvae cannot get air, so fewer become adults.", "The oil gives the larvae food, so more become adults.", "The adult mosquitoes can no longer fly over drains.", "The eggs in the water hatch straight into adults."], a: 0, why: "The oil layer stops the larvae from reaching the air at the surface, so many die before becoming adults. Mosquito eggs hatch into larvae, never straight into adults.", lvl: 3 },
    { q: "Study the table. Which conclusions can be made from a FAIR comparison?\nA: Seeds need water to germinate.\nB: Seeds do not need light to germinate.\nC: Seeds germinate better at 25 °C than at 5 °C.", tbl: [["Set-up", "Water", "Light", "Temperature", "Seeds germinated (out of 10)"], ["P", "Yes", "Light", "25 °C", "9"], ["Q", "No", "Light", "25 °C", "0"], ["R", "Yes", "Dark", "25 °C", "9"], ["S", "No", "Dark", "5 °C", "0"]], o: ["A and B only", "A only", "B and C only", "A, B and C"], a: 0, why: "P and Q differ only in water (A), and P and R differ only in light (B). S is the only set-up at 5 °C, and it differs from R in both water and temperature, so C cannot be concluded fairly.", lvl: 3 },
    { q: "Study the classification key. Which statements are correct?\n1: An aluminium can belongs to group B.\n2: A thin steel wire belongs to group A.\n3: A cotton towel belongs to group D.", fig: { type: "flow", root: "Objects", node: { q: "Attracted by magnet?", yes: { q: "Flexible?", yes: "A", no: "B" }, no: { q: "Waterproof?", yes: "C", no: "D" } } }, o: ["1 and 2 only", "2 and 3 only", "1 and 3 only", "1, 2 and 3"], a: 1, why: "Thin steel wire is magnetic and bends without breaking (A), and cotton absorbs water (D). Aluminium is a metal but non-magnetic, so the can goes to C, not B.", lvl: 3 },
    { q: "At the Night Safari, a guide says a bat is a mammal, not a bird. Which characteristics show that a bat is a mammal?\nA: It can fly.\nB: It has fur.\nC: It gives birth to young alive.\nD: It feeds its young on milk.", o: ["A and B only", "A, C and D only", "B, C and D only", "A, B, C and D"], a: 2, why: "Fur, giving birth to young alive and feeding young on milk are characteristics of mammals. Flying does not show this, as birds and insects can fly too.", lvl: 3 },
    { q: "Pupils counted the animals they saw in the school garden. Which statement is supported by the graph?", fig: { type: "bar", title: "Animals seen in the school garden", xl: "Group", yl: "Number of animals", bars: [["Insects", 14], ["Birds", 5], ["Mammals", 2], ["Reptiles", 3]] }, o: ["There were more birds than mammals and reptiles together.", "More than half of the animals counted had fur.", "Exactly half of the animals counted had six legs.", "There were more insects than all the other groups together."], a: 3, why: "Insects (14) outnumber birds, mammals and reptiles together (5 + 2 + 3 = 10). Birds (5) only equal mammals and reptiles together, only the 2 mammals have fur, and 14 out of 24 is more than half.", lvl: 3 },
    { q: "In a forest at Bukit Timah, Sam saw P, a mushroom on a log; Q, a fern; and R, a young mango seedling. Which statements are correct?\nA: P and Q both reproduce by spores.\nB: Q and R both make their own food.\nC: P and R both grew from seeds.", o: ["B only", "A and C only", "A and B only", "A, B and C"], a: 2, why: "The mushroom and the fern both reproduce by spores (A), and the fern and the mango seedling are plants that make their own food (B). The mushroom grew from a spore, not a seed, so C is wrong.", lvl: 3 },

    { q: "Magnets P and R are placed on either side of rod Q as shown. Both ends of Q attract the magnets. Which statements are correct?\nA: Q is made of a magnetic material.\nB: Q is a magnet.\nC: Q could be made of aluminium.", fig: { type: "magnets", items: [{ label: "P", poles: "NS" }, { label: "Q", kind: "bar", text: "?" }, { label: "R", poles: "SN" }], between: ["attract", "attract"] }, o: ["A only", "B only", "A and C only", "A and B only"], a: 0, why: "Both S poles attract Q. If Q were a magnet, both of its ends would have to be N poles, which is impossible, so Q is not a magnet. It is attracted, so it is a magnetic material, and aluminium is non-magnetic.", lvl: 4 },
    { q: "Study the table. Which animals could be a penguin and a bat?", tbl: [["Animal", "Has feathers?", "Can fly?", "Lays eggs?", "Feeds young on milk?"], ["W", "No", "Yes", "No", "Yes"], ["X", "Yes", "Yes", "Yes", "No"], ["Y", "Yes", "No", "Yes", "No"], ["Z", "No", "No", "Yes", "No"]], o: ["Penguin: X, bat: W", "Penguin: Y, bat: W", "Penguin: Y, bat: Z", "Penguin: Z, bat: X"], a: 1, why: "A penguin is a bird that has feathers and lays eggs but cannot fly (Y). A bat is a mammal that can fly and feeds its young on milk (W). X can fly so it is not a penguin, and Z has no feathers and lays eggs, so it is neither.", lvl: 4 },
    { q: "Ahmad kept 30 mosquito eggs in a tank of water with a fine net cover and counted each stage. No mosquito escaped and nothing was added. Study the table. How many of the 30 did NOT survive to Day 10?", tbl: [["Day", "Eggs", "Larvae", "Pupae", "Adults"], ["0", "30", "0", "0", "0"], ["2", "0", "28", "0", "0"], ["7", "0", "10", "16", "0"], ["10", "0", "0", "4", "22"]], o: ["2", "6", "4", "8"], a: 2, why: "On Day 10 there were 4 pupae + 22 adults = 26 alive, so 30 − 26 = 4 did not survive. Choosing 2 only counts the losses up to Day 2; 2 more were lost by Day 7 (10 + 16 = 26).", lvl: 4 },
    { q: "Study the classification key. Which statements are correct?\nA: Bacteria belong to group S.\nB: A mushroom belongs to group R.\nC: A fern belongs to group P because it has green leaves.\nD: A cat belongs to group R.", fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: { q: "Has flowers?", yes: "P", no: "Q" }, no: { q: "Seen without microscope?", yes: "R", no: "S" } } }, o: ["A and B only", "A, B and D only", "B, C and D only", "A, B, C and D"], a: 1, why: "Bacteria cannot make food and need a microscope to be seen (S). A mushroom and a cat cannot make food but can be seen with our eyes (R). A fern makes its own food but has no flowers, so it is Q; green leaves do not decide the group.", lvl: 4 }
  ],
  oe: [
    {
      q: "Pupils recorded three animals seen at the Night Safari. All three animals have wings. Study the table.\n(a) Which animal is a mammal? Give one piece of evidence from the table. [2]\n(b) To which group of animals does animal Q belong? [1]\n(c) Explain why ‘Has wings?’ would NOT be a useful question for separating these three animals in a classification key. [1]",
      tbl: [["Animal", "Body covering", "Number of legs", "How young are produced"], ["P", "Feathers", "2", "Lays eggs"], ["Q", "Hard outer covering", "6", "Lays eggs"], ["R", "Fur", "2", "Gives birth to young alive"]],
      marks: 4,
      kw: [["r"], ["fur", "young alive", "gives birth", "give birth"], ["insect"], ["all have", "all of them", "all three", "every one", "each of them", "they all"]],
      model: "(a) Animal R. It has fur and it gives birth to young alive, which are characteristics of mammals. (b) Q is an insect, because it has six legs and a hard outer covering. (c) They all have wings, so the answer would be ‘yes’ for every one of them and the question would not separate them."
    },
    {
      q: "Hana stroked a steel nail with a bar magnet and counted the steel paper clips the nail could then pick up. She used a new, identical steel nail for each number of strokes. Study the graph.\n(a) What variable did Hana change? [1]\n(b) Describe how the number of clips changed from 0 to 30 strokes. [1]\n(c) After 40 strokes, one end of the nail repelled the N pole of a bar magnet. What does this show? [1]\n(d) Explain why an aluminium nail cannot be made into a magnet in this way. [1]",
      fig: { type: "bar", title: "Clips picked up by the stroked nail", xl: "Number of strokes", yl: "Number of clips picked up", bars: [["0", 0], ["10", 3], ["20", 6], ["30", 9], ["40", 9]] },
      marks: 4,
      kw: [["number of strokes", "number of times", "how many times", "how many strokes"], ["more strokes", "the more", "increase"], ["become a magnet", "became a magnet", "is a magnet", "is now a magnet", "turned into a magnet", "was a magnet", "made into a magnet"], ["non-magnetic", "not magnetic", "not a magnetic", "not attracted"]],
      model: "(a) The number of strokes. (b) The more strokes, the more paper clips the nail picked up: the number increased from 0 to 9. (c) The nail had become a magnet, because only a magnet can repel another magnet. (d) Aluminium is a non-magnetic material, so it is not attracted by a magnet and cannot be made into a magnet."
    },
    {
      q: "Ali put 20 mealworm larvae in the middle of a tray. One half of the tray had damp bran and the other half had dry bran. After 1 hour, he counted the larvae on each side. Study the table.\n(a) What was Ali trying to find out? [1]\n(b) Why did he place all the larvae in the middle of the tray at the start? [1]\n(c) Suggest one way to make his results more reliable. [1]\n(d) Weeks later, some larvae stopped feeding and moving, and changed shape. Name the stage they were in. [1]",
      tbl: [["Side of tray", "Number of larvae after 1 hour"], ["Damp bran", "4"], ["Dry bran", "16"]],
      marks: 4,
      kw: [["damp or dry", "dry or damp", "moist or dry", "dry or moist", "wet or dry", "dry or wet", "damp bran or dry", "dry bran or damp", "moist bran or dry", "dry bran or moist", "moisture", "dampness"], ["same distance", "equal chance", "equally", "fair", "free to choose", "could choose", "can choose"], ["repeat", "more larvae", "more times", "again"], ["pupa", "pupae"]],
      model: "(a) Whether mealworm larvae prefer damp or dry bran. (b) So that every larva was the same distance from both sides and could choose either side, making the test fair. (c) Repeat the experiment a few more times, or use more larvae, and compare the results. (d) The pupa stage."
    },
    {
      q: "A hawker kept four bowls of the same cooked rice in different ways and recorded how many days passed before each bowl of rice went bad. Study the table.\n(a) Which two bowls should be compared to find out if temperature affects how fast cooked rice goes bad? [1]\n(b) Explain why the rice kept in the fridge took longer to go bad. [2]\n(c) What does comparing bowls A and B show? [1]",
      tbl: [["Bowl", "Covered?", "Where kept", "Days before rice went bad"], ["A", "No", "Counter, 30 °C", "1"], ["B", "Yes", "Counter, 30 °C", "1"], ["C", "Yes", "Fridge, 5 °C", "5"], ["D", "No", "Fridge, 5 °C", "4"]],
      marks: 4,
      kw: [["b and c", "c and b", "a and d", "d and a", "b and bowl c", "c and bowl b", "a and bowl d", "d and bowl a"], ["cold", "low temperature", "cool"], ["slow", "grow less", "less quickly", "grow more slowly"], ["no difference", "did not affect", "does not affect", "not affect", "did not make", "same number of days", "same time", "didn’t affect", "no effect"]],
      model: "(a) Bowls B and C (or bowls A and D). (b) The fridge is cold. The low temperature slows down the growth of the bacteria and fungi that make food go bad, so the rice took longer to go bad. (c) Covering the rice made no difference to how fast it went bad on the counter, as both bowls went bad in 1 day."
    },
    {
      q: "Rods X, Y and Z look the same. One is a magnet, one is made of steel and one is made of aluminium. Kim did four tests. Study the table.\n(a) Which rod is the magnet? Explain how you know. [2]\n(b) Which rod is made of aluminium? Explain how you know. [2]",
      tbl: [["Test", "Result"], ["X brought near Y", "Attract"], ["X brought near Z", "Nothing happens"], ["Y brought near Z", "Nothing happens"], ["N pole of a bar magnet brought near one end of X", "Repel"]],
      marks: 4,
      kw: [["x"], ["repel", "like poles"], ["z"], ["non-magnetic", "not attracted", "not magnetic", "nothing happen", "no effect"]],
      model: "(a) X. X was repelled by the N pole of the bar magnet, and only a magnet can repel another magnet. (b) Z. Z was not attracted by magnet X, so it is non-magnetic. Y was attracted by X, so Y is the steel rod and Z must be the aluminium rod."
    },
    {
      q: "Kai put 20 mealworm larvae in a box of oats with small air holes in the lid, and counted the larvae every 2 weeks. No mealworms escaped and none were added. Study the graph.\n(a) Explain why the number of larvae fell from Week 2 to Week 8. [1]\n(b) Explain why the number of larvae rose again after Week 10. [2]\n(c) Kai’s friend said that the larvae had died between Week 2 and Week 8. What could Kai look for in the box to show that his friend is wrong? [1]",
      fig: { type: "line", title: "Mealworm larvae in the box", xl: "Week", yl: "Number of larvae", pts: [["0", 20], ["2", 20], ["4", 12], ["6", 2], ["8", 0], ["10", 0], ["12", 15]] },
      marks: 4,
      kw: [["into pupae", "into pupa", "became pupa", "become pupa", "pupate", "pupa stage"], ["adult"], ["lay eggs", "laid eggs", "laying eggs", "lays eggs", "hatch"], ["look for pupae", "pupae in the box", "find pupae", "see pupae", "count the pupae", "number of pupae", "check for pupae", "look for adult", "look for beetle"]],
      model: "(a) The larvae changed into pupae, so fewer larvae were left. (b) The pupae developed into adult beetles. The adults laid eggs, and the eggs hatched into new larvae. (c) He could look for pupae in the box (and later, adult beetles). Living pupae show that the larvae had changed into pupae, not died.",
      x: 1
    }
  ],
  tf: [
    { s: "A bat is a bird because it has wings and can fly.", a: false, why: "A bat is a mammal: it has fur, gives birth to young alive and feeds its young on milk." },
    { s: "A whale is a mammal even though it lives in the sea.", a: true, why: "It gives birth to young alive and feeds them on milk." },
    { s: "Yeast is a kind of bacteria.", a: false, why: "Yeast is a fungus, like mushrooms and bread mould." },
    { s: "Seeds need light to germinate.", a: false, why: "Seeds need water, air and warmth; they can germinate in the dark." },
    { s: "A magnet can attract a steel paper clip through a thin plastic file.", a: true, why: "Magnetic force can pass through non-magnetic materials such as plastic." },
    { s: "Every insect has wings.", a: false, why: "Insects have six legs, three body parts and a pair of feelers, but some, such as worker ants, have no wings." },
    { s: "The adult is the only stage of a mosquito’s life cycle that does not live in water.", a: true, why: "The eggs, larvae and pupae all live in stagnant water." },
    { s: "A steel nail stroked many times in one direction with a magnet can become a magnet.", a: true, why: "Steel is a magnetic material, so it can be made into a magnet by the stroke method." },
    { s: "All bacteria are harmful to people.", a: false, why: "Some bacteria are useful, e.g. those used to make yoghurt; others cause food to spoil or cause diseases." },
    { s: "Ferns and mosses make their own food even though they have no flowers.", a: true, why: "They are non-flowering plants; like all plants they make their own food." }
  ],
  sort: [
    { title: "Sort these living things into their groups.", groups: ["Fungi", "Bacteria", "Plants", "Animals"], items: [["mushroom", 0], ["yeast", 0], ["bread mould", 0], ["bacteria used to make yoghurt", 1], ["bacteria that make milk go sour", 1], ["fern", 2], ["moss", 2], ["guppy", 3], ["mealworm", 3], ["bat", 3]] }
  ]
};
