window.BANKZ = window.BANKZ || {};
BANKZ["mixed"] = {
  lessons: [
    {
      h: "How to write the aim and the conclusion of an experiment",
      concept: "The aim and the conclusion both link the SAME two things: the variable that was changed and the result that was measured. An aim says ‘To find out if/how [changed variable] affects [measured result]’. A conclusion states the pattern in the results: ‘The more/less [changed variable], the more/less [measured result]’, or which one gave the most. A conclusion only describes what the results show; it does not add a reason or a result that was not tested.",
      example: {
        q: "Mira placed 10 green bean seeds on cotton wool in each of four identical dishes in the same cupboard. She added a different amount of water to each dish every day. Study the table.\n(a) State the aim of her experiment. [1]\n(b) What can she conclude from her results? [1]",
        tbl: [["Dish", "Water added each day (ml)", "Seeds germinated after 5 days"], ["A", "0", "0"], ["B", "5", "4"], ["C", "10", "8"], ["D", "15", "9"]],
        marks: 2,
        think: [
          "Step 1: Find the changed variable: only the amount of water added each day is different in the four dishes.",
          "Step 2: Find the measured result: the number of seeds that germinated after 5 days.",
          "Step 3: Put them into the aim sentence: ‘To find out if the amount of water affects the number of seeds that germinate.’ Naming only ‘water’ or only ‘germination’ loses the mark.",
          "Step 4: For the conclusion, read the pattern: as the water goes up (0, 5, 10, 15 ml), the seeds germinated go up (0, 4, 8, 9). State it with both variables, and do not claim things not tested, such as ‘seeds need light’."
        ],
        answer: "(a) To find out if the amount of water added affects the number of green bean seeds that germinate. (b) The more water added to the cotton wool each day (from 0 to 15 ml), the more seeds germinated."
      },
      tip: "Aim and conclusion must both name the changed variable AND the measured result, in full.",
      try: {
        q: "Zi Xuan added different numbers of drops of water to identical slices of bread and kept them in the same cupboard. Study the table. Which is the best conclusion?",
        tbl: [["Drops of water", "Days before mould appeared"], ["0", "No mould after 10 days"], ["5", "6"], ["10", "4"], ["15", "3"]],
        o: ["The more water added to the bread, the sooner mould appeared on it.", "Mould needs exactly 15 drops of water to grow well on bread.", "The more water added to the bread, the longer mould took to appear.", "Bread with water added always grows mould in 3 days or less."],
        a: 0,
        why: "As the drops went up (5, 10, 15), the days before mould appeared went down (6, 4, 3), so mould appeared sooner. The data do not show that exactly 15 drops are needed, and the slice with 5 drops took 6 days, not 3 or less."
      }
    }
  ],
  mcq: [
    { q: "Which pair are BOTH living things?", o: ["A seed and a mushroom", "A seed and a magnet", "A rock and a fern", "A robot and a guppy"], a: 0, why: "A seed is alive: it can germinate and grow into a new plant, and a mushroom is a fungus. A magnet, a rock and a robot cannot grow or reproduce, so each wrong pair has a non-living thing.", lvl: 1 },
    { q: "Which object is BOTH transparent and non-magnetic?", o: ["A steel spoon", "A wooden block", "A glass marble", "An iron nail"], a: 2, why: "Glass lets light pass through and is not attracted by a magnet. Steel and iron are magnetic, and wood is opaque.", lvl: 1 },
    { q: "The diagram shows the life cycle of a chicken. What is the missing stage?", fig: { type: "cycle", stages: ["Egg", "?", "Adult"] }, o: ["Pupa", "Larva", "Nymph", "Chick"], a: 3, why: "A chicken has three stages: egg, chick and adult. Larva and pupa belong to animals such as butterflies, and nymphs to insects such as cockroaches.", lvl: 1 },

    { q: "Kumar saw these at a pond in Pasir Ris Park: a guppy, a water lily with flowers, some mosquito larvae and an iron nail at the bottom. Which statements are correct?\nA: The guppy and the mosquito larvae both respond to changes.\nB: The water lily reproduces by spores.\nC: The iron nail can be picked up by a magnet.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "All living things respond to changes (A), and iron is magnetic even under water (C). The water lily has flowers, so it is a flowering plant that reproduces by seeds, not spores.", lvl: 2 },
    { q: "NEA officers checked containers of rainwater around an HDB estate. Study the graph. Which statement is supported by the graph?", fig: { type: "bar", title: "Mosquito larvae found", xl: "Container", yl: "Number of larvae", bars: [["Flower-pot plate", 25], ["Covered pail", 0], ["Open drink can", 12], ["Covered tank", 0]] }, o: ["Mosquitoes laid their eggs in covered and open containers alike.", "Larvae cannot live in the water collected in flower-pot plates.", "Open containers of still water had larvae, but covered ones had none.", "The open drink can had more larvae than any other container."], a: 2, why: "Both open containers had larvae and both covered ones had none, because mosquitoes could not reach the covered water to lay eggs. The flower-pot plate (25), not the drink can (12), had the most larvae.", lvl: 2 },
    { q: "Study the classification key. Which animal belongs in group R?", fig: { type: "flow", root: "Animals", node: { q: "Has a pupa stage?", yes: "P", no: { q: "Young look like adult?", yes: "Q", no: "R" } } }, o: ["Frog", "Mosquito", "Cockroach", "Chicken"], a: 0, why: "A frog has no pupa stage and its young (tadpoles) look very different from the adult, so it is R. A mosquito has a pupa (P), while a cockroach nymph and a chick look like their adults (Q).", lvl: 2 },
    { q: "Wen wants to find out if the thickness of a plastic sheet affects the number of steel paper clips a magnet can attract through it. Which two set-ups should she compare?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Magnet X", "Cardboard, 2 mm", "Steel clips"] }, { label: "B", icon: "plate", lines: ["Magnet X", "Plastic, 2 mm", "Steel clips"] }, { label: "C", icon: "plate", lines: ["Magnet X", "Plastic, 5 mm", "Steel clips"] }, { label: "D", icon: "plate", lines: ["Magnet Y", "Plastic, 5 mm", "Steel clips"] }] }, o: ["A and B", "B and C", "C and D", "A and D"], a: 1, why: "B and C use the same magnet and material and differ only in thickness. A and B differ in material, C and D differ in the magnet, and A and D differ in three things.", lvl: 2 },
    { q: "A packet of dry green bean seeds has been kept in a drawer for 3 months. Which statement about the seeds is correct?", o: ["They are living, as they can germinate when given water, air and warmth.", "They are non-living, as they have not grown at all for 3 months.", "They are non-living until they are planted in soil and watered.", "They are living only if the packet is kept in a bright place."], a: 0, why: "Misconception: ‘not growing now means non-living’. A dry seed contains a living young plant that starts growing once it gets water, air and warmth. Seeds do not need light or soil to be alive.", lvl: 2 },
    { q: "Pupils tested object X. Study the table. What could X be?", tbl: [["Test", "Result"], ["Is it attracted by a magnet?", "Yes"], ["Can light pass through it?", "No"], ["Does it bend easily without breaking?", "Yes"]], o: ["A glass rod", "A thin steel wire", "A strip of aluminium foil", "A rubber band"], a: 1, why: "Only thin steel wire is magnetic, opaque and flexible. Aluminium foil and a rubber band bend easily but are non-magnetic, and a glass rod is non-magnetic, transparent and breaks.", lvl: 2 },

    { q: "Which statements about the life cycles of a mosquito and a butterfly are correct?\nA: Both have four stages in their life cycles.\nB: The pupae of both live in water.\nC: The larvae of both feed actively and grow.", o: ["A only", "B and C only", "A, B and C", "A and C only"], a: 3, why: "Both have egg, larva, pupa and adult, and both larvae feed and grow. Misconception in B: only the mosquito pupa lives in water; a butterfly pupa hangs from a leaf or stem on land.", lvl: 3 },
    { q: "Four ring magnets are placed on a wooden rod as shown. Ring A has its N pole facing up. Ring D is lifted off, turned upside down and put back on the rod. What will happen?", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }, { label: "D", top: "?" }], gaps: [true, false, true] }, o: ["D will float higher above C than it did before.", "D will rest on C, and B still floats above A.", "C will be pushed up and float above ring B.", "D will rest on C, and B will now rest on A."], a: 1, why: "B floats, so its bottom is N and top is S; C touches B, so C’s bottom is N and top is S; D floats, so its bottom is S. Turned over, D’s bottom becomes N, which attracts C’s top S, so D rests on C. Nothing changes between A and B.", lvl: 3 },
    { q: "Aisha kept frog eggs in a glass tank of pond water and counted the tadpoles every 2 weeks. None of the tadpoles died. Study the graph. Which statement best explains the change after Week 6?", fig: { type: "line", title: "Tadpoles in the tank", xl: "Week", yl: "Number of tadpoles", pts: [["0", 0], ["2", 30], ["4", 30], ["6", 30], ["8", 18], ["10", 4]] }, o: ["Many tadpoles developed into pupae inside the tank.", "The frogs in the tank laid eggs that became tadpoles.", "Many tadpoles developed into young frogs in the tank.", "The tadpoles got too little air in the water to grow."], a: 2, why: "A frog has three stages: egg, tadpole and adult. As tadpoles grew legs and lost their tails, they became young frogs and were no longer counted as tadpoles. Misconception: a frog has no pupa stage. New eggs would make the number rise, not fall, and none of the tadpoles died.", lvl: 3 },
    { q: "Study the Venn diagram. Which statements are correct?\nA: Object X could be a copper wire.\nB: Object X could be a nickel rod.\nC: A plastic ruler should go outside both circles.", fig: { type: "venn", a: "Attracted by a magnet", b: "Is a metal", onlyA: [], both: ["iron nail", "steel spoon"], onlyB: ["aluminium can", "X"], neither: ["glass jar", "rubber band"] }, o: ["A and B only", "B and C only", "A and C only", "A, B and C"], a: 2, why: "X is a metal that is not attracted by a magnet, so it could be copper (A). Nickel is magnetic, so a nickel rod belongs in the overlap, not with X. Plastic is neither a metal nor magnetic (C).", lvl: 3 },
    { q: "Aina placed sheets of cardboard between a magnet and a pile of steel paper clips, and counted the clips attracted. Study the table. Which statement best explains her results?", tbl: [["Number of cardboard sheets", "Number of clips attracted"], ["0", "12"], ["1", "10"], ["2", "8"], ["3", "6"], ["4", "4"]], o: ["Cardboard is a magnetic material, so each sheet takes away some force.", "Magnetic force cannot pass through cardboard, so fewer clips were attracted.", "Each sheet made the magnet itself weaker, so it could hold fewer clips.", "Magnetic force passes through cardboard, but is weaker further from the magnet."], a: 3, why: "Clips were still attracted through 4 sheets, so the force passes through cardboard; more sheets put the clips further away, where the force is weaker. Misconception: the magnet itself does not become weaker, and cardboard is non-magnetic.", lvl: 3 },
    { q: "Study the classification key. Which statements are correct?\nA: Glass would be in group P.\nB: Aluminium would be in group Q.\nC: Paper would be in group R.", fig: { type: "flow", root: "Materials", node: { q: "Attracted by magnet?", yes: "S", no: { q: "Waterproof?", yes: { q: "Transparent?", yes: "P", no: "Q" }, no: "R" } } }, o: ["A, B and C", "A only", "A and B only", "B and C only"], a: 0, why: "Glass is non-magnetic, waterproof and transparent (P). Aluminium is a metal but non-magnetic, and it is waterproof and opaque (Q), not S. Paper absorbs water, so it is not waterproof (R).", lvl: 3 },
    { q: "A candle flame needs air, can grow bigger and moves about. Which fact best shows that a burning candle is non-living?", o: ["It cannot move from place to place on its own.", "It burns faster when it gets more fresh air.", "It cannot reproduce to make new candles.", "It gives out heat and light while it burns."], a: 2, why: "Living things reproduce; a candle can never make new candles. Misconception: not moving from place to place does not make something non-living, since plants cannot do that either.", lvl: 3 },

    { q: "Study the table. Which conclusions can be made from a FAIR comparison?\nA: Seeds need water to germinate.\nB: Seeds germinate better in a warm place than in a cold place.\nC: Seeds germinate better on cotton wool than on a plastic sheet.", tbl: [["Set-up", "Placed on", "Water", "Place", "Seeds germinated (out of 10)"], ["P", "Cotton wool", "20 ml", "Cupboard", "9"], ["Q", "Cotton wool", "None", "Cupboard", "0"], ["R", "Plastic sheet", "10 ml", "Fridge", "0"], ["S", "Cotton wool", "20 ml", "Fridge", "1"]], o: ["A and C only", "A only", "A, B and C", "A and B only"], a: 3, why: "P and Q differ only in water (A), and P and S differ only in place, warm cupboard or cold fridge (B). R differs from every other set-up in more than one variable (material, water and place), so C cannot be concluded fairly.", lvl: 4 },
    { q: "Rods P, Q and R look the same. Each is either a magnet or a steel bar. P repels Q, and Q attracts R, as shown. R is then turned around so that its other end faces Q, and R still attracts Q. What can be concluded?", fig: { type: "magnets", items: [{ label: "P", kind: "bar", text: "?" }, { label: "Q", kind: "bar", text: "?" }, { label: "R", kind: "bar", text: "?" }], between: ["repel", "attract"] }, o: ["P and Q are magnets; R is also a magnet.", "P and Q are magnets; R is a steel bar.", "P is a magnet; Q and R are steel bars.", "Only Q is a magnet; P and R are steel bars."], a: 1, why: "Only two magnets can repel, so P and Q are magnets. If R were a magnet, turning it around would put its other pole facing Q and one of the two ways would repel; since both ends attract, R is a magnetic material (steel), not a magnet.", lvl: 4 },
    { q: "Study the classification key. Which statements are correct?\n1: A mango tree belongs to group W.\n2: A moss belongs to group W because it is green.\n3: A mushroom belongs to group Y.\n4: A butterfly belongs to group Y because it lays tiny eggs.", fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: { q: "Is it a flowering plant?", yes: "W", no: "X" }, no: { q: "Reproduces by spores?", yes: "Y", no: "Z" } } }, o: ["1 and 3 only", "1, 3 and 4 only", "2 and 4 only", "1, 2, 3 and 4"], a: 0, why: "A mango tree makes food and flowers (W), and a mushroom cannot make food and makes spores (Y). Moss is green but non-flowering, so it goes to X; a butterfly lays eggs, not spores, so it goes to Z. Being green or laying tiny eggs does not decide the group.", lvl: 4 },
    { q: "Mei weighed a silkworm every 6 days after it hatched. On Day 24, it spun a cocoon around itself. Study the graph. Which statements are correct?\nA: The silkworm gained mass fastest from Day 18 to Day 24.\nB: Its mass did not increase after Day 24 because it no longer fed.\nC: On Day 24, the silkworm became an adult moth.", fig: { type: "line", title: "Mass of a silkworm", xl: "Day", yl: "Mass (g)", pts: [["0", 0], ["6", 0.2], ["12", 0.8], ["18", 2], ["24", 4], ["30", 2], ["36", 1.8]] }, o: ["A only", "B and C only", "A, B and C", "A and B only"], a: 3, why: "The gains are 0.2 g, 0.6 g, 1.2 g and 2 g, so the fastest gain is from Day 18 to Day 24 (A). Inside the cocoon the silkworm is a pupa, which does not feed, so its mass stopped increasing (B). C is wrong: the silkworm (the larva) became a pupa on Day 24, not an adult moth.", lvl: 4 }
  ],
  oe: [
    {
      q: "Dinesh placed 10 green bean seeds on each of three materials. Each day he added the same number of drops of water to each, and kept them in the same room. Study the table.\n(a) State the aim of his experiment. [1]\n(b) Explain why only a few seeds germinated on the plastic sheet. [2]\n(c) State one variable he kept the same in this experiment. [1]",
      tbl: [["Material", "Seeds germinated after 5 days"], ["Cotton wool", "9"], ["Sponge", "8"], ["Plastic sheet", "2"]],
      marks: 4,
      kw: [["type of material", "material affects", "materials affect", "material the seeds", "material used"], ["not absorb", "doesn’t absorb", "waterproof", "cannot hold water", "not hold water"], ["need water", "needs water", "water to germinate"], ["number of seeds", "type of seed", "kind of seed", "green bean", "amount of water", "drops of water", "same room", "place", "temperature", "size"]],
      model: "(a) To find out if the type of material the seeds are placed on affects the number of seeds that germinate. (b) Plastic is waterproof and does not absorb water, so the water did not stay around the seeds and they were not kept moist. Seeds need water to germinate, so only a few germinated. (c) The number of seeds on each material (or the type of seed, or the size of each piece)."
    },
    {
      q: "Jun wanted to find out which materials magnetic force can pass through. He placed a 2 mm sheet of each material between the same magnet and a pile of steel paper clips, and counted the clips attracted. He also did one test with no sheet. Study the graph.\n(a) State the variable Jun changed. [1]\n(b) What can he conclude about magnetic force and these materials? [1]\n(c) Why did he do one test with no sheet? [1]\n(d) Can a magnet hold a paper poster onto a steel whiteboard? Explain. [1]",
      fig: { type: "bar", title: "Clips attracted through each sheet", xl: "Sheet between magnet and clips", yl: "Number of clips", bars: [["No sheet", 10], ["Paper", 10], ["Plastic", 10], ["Glass", 10]] },
      marks: 4,
      kw: [["type of material", "kind of material", "material of the sheet"], ["pass through", "passes through", "go through", "goes through", "act through", "acts through"], ["compare", "comparison"], ["magnetic material", "steel is magnetic", "steel is a magnetic", "attracted to the steel", "attracted to steel", "attracts the steel", "attract the steel"]],
      model: "(a) The type of material of the sheet. (b) Magnetic force can pass through paper, plastic and glass, because the same number of clips (10) was attracted as with no sheet. (c) To compare the results with the sheets against the result with no sheet. (d) Yes. Magnetic force can pass through paper, and steel is a magnetic material, so the magnet is attracted to the steel board and holds the poster."
    },
    {
      q: "Lina put 50 mosquito larvae in a tank of pond water with a fine net cover, and counted the number of pupae each day. Study the graph.\n(a) Explain why the number of pupae increased from Day 1 to Day 4. [1]\n(b) Explain why the number of pupae decreased after Day 4. [1]\n(c) Give two reasons why a fine net cover was used instead of leaving the tank open or using a solid lid. [2]",
      fig: { type: "line", title: "Number of mosquito pupae", xl: "Day", yl: "Number of pupae", pts: [["0", 0], ["1", 0], ["2", 5], ["3", 20], ["4", 35], ["5", 20], ["6", 5]] },
      marks: 4,
      kw: [["larvae became", "larvae changed", "larvae turned", "larvae developed", "larvae grew into", "larva became", "larva changed", "larva turned", "larva develop", "larva grew into", "became pupae", "changed into pupae", "turned into pupae"], ["adult"], ["escap", "fly out", "fly away", "flying out"], ["air"]],
      model: "(a) More and more larvae changed into pupae. (b) The pupae developed into adult mosquitoes, so there were fewer pupae left. (c) The very small holes stop the adult mosquitoes from escaping out of the tank, and they still let air through, so the animals get the air they need to stay alive.",
      x: 1
    },
    {
      q: "Bee Lian set up A and B as shown to find out if seeds need air to germinate. Both were kept in the same warm room.\n(a) What is the variable changed in this experiment? [1]\n(b) Predict which set-up will have germinated seeds after 5 days, and explain. [2]\n(c) Why was the water in B boiled and cooled, and covered with a layer of oil? [1]",
      fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist cotton wool", "10 seeds", "Open to the air"] }, { label: "B", icon: "beaker", lines: ["Boiled, cooled water", "Layer of oil on top", "10 seeds under water"] }] },
      marks: 4,
      kw: [["presence of air", "whether there is air", "amount of air", "whether the seeds get air", "air or no air"], ["a will", "only a", "seeds in a", "set-up a", "a has", "in a germinat"], ["need air", "needs air", "air to germinate"], ["remove", "stop air", "stops air", "keep air out", "keeps air out", "prevent air"]],
      model: "(a) The presence of air (whether the seeds get air or not). (b) Only the seeds in A will germinate. Seeds need air to germinate, and the seeds in B had no air because they were under water. (c) Boiling removes the air in the water, and the layer of oil stops air from entering the water again.",
      x: 1
    },
    {
      q: "Wei Ming compared a real mynah with a toy mynah that can flap its wings and sing when switched on.\n(a) After a year, the toy is the same size, but a young real mynah has become bigger. Which characteristic of living things does this show? [1]\n(b) The real mynah lays eggs to make more mynahs. Which characteristic of living things does this show? [1]\n(c) Name the stage of the mynah’s life cycle that hatches from the egg. [1]\n(d) The toy’s wings are made of a material that can bend without breaking. Name this property. [1]",
      marks: 4,
      kw: [["grow"], ["reproduc"], ["chick", "young bird", "baby bird"], ["flexib"]],
      model: "(a) Living things grow. (b) Living things reproduce. (c) A chick (young bird). (d) The material is flexible."
    },
    {
      q: "Anya grew a balsam plant from a seed and measured its height every 2 weeks. Flowers first appeared in Week 8. Study the graph.\n(a) Describe how the height of the plant changed from Week 0 to Week 12. [1]\n(b) Name the stage of the life cycle the plant was in when flowers first appeared. [1]\n(c) What develops from the flowers that helps the balsam to reproduce? [1]\n(d) A fern in the same garden never has flowers. How does a fern reproduce? [1]",
      fig: { type: "line", title: "Height of a balsam plant", xl: "Week", yl: "Height (cm)", pts: [["0", 0], ["2", 3], ["4", 9], ["6", 16], ["8", 22], ["10", 24], ["12", 24]] },
      marks: 4,
      kw: [["increase", "grew taller", "got taller", "became taller"], ["adult"], ["fruit", "seed"], ["spore"]],
      model: "(a) The height increased from 0 cm to 24 cm up to Week 10, then stayed the same at 24 cm until Week 12. (b) The adult plant stage. (c) Fruits, which contain seeds that can grow into new balsam plants. (d) A fern reproduces by spores."
    }
  ],
  tf: [
    { s: "A seed kept dry in a packet is non-living because it is not growing.", a: false, why: "The seed is living; it will germinate and grow when it gets water, air and warmth." },
    { s: "Magnetic force can pass through a thin sheet of cardboard.", a: true, why: "Cardboard is non-magnetic, and a magnet can still attract steel clips through it." },
    { s: "Covering a pail of water with a fine net stops air from reaching the water, so larvae inside will die.", a: false, why: "A fine net still lets air through; it works by stopping adult mosquitoes reaching the water to lay eggs." },
    { s: "Neither a mushroom nor a mosquito larva can make its own food.", a: true, why: "A mushroom is a fungus and a larva is an animal; neither can make its own food." },
    { s: "Moss reproduces by seeds because it is a green plant.", a: false, why: "Moss is a non-flowering plant; it reproduces by spores. Being green does not mean it has seeds." },
    { s: "A thin steel wire is flexible and is attracted by a magnet.", a: true, why: "Thin steel wire bends without breaking, and steel is a magnetic material." },
    { s: "A burning candle is living because its flame needs air and can grow bigger.", a: false, why: "A candle cannot reproduce, so it is non-living even though its flame needs air." },
    { s: "The young stages of both a frog and a mosquito live in water.", a: true, why: "Tadpoles live in water, and so do mosquito larvae and pupae." },
    { s: "If a magnet attracts fewer clips through 4 sheets of paper than through 1 sheet, the magnet has become weaker.", a: false, why: "The magnet is just as strong; the clips are further away, where its force is weaker." },
    { s: "In a fair test on seed germination, each set-up should have the same number and type of seeds.", a: true, why: "Only the variable being tested should change; everything else is kept the same." }
  ],
  doc: [
    { q: "Rui placed green bean seeds on dry cotton wool and on moist cotton wool in the same room. Only the seeds on the moist cotton wool germinated. Explain why.", marks: 2, answers: ["Because the dry cotton wool was not good for the seeds.", "Seeds need water to germinate. The moist cotton wool had absorbed water and kept the seeds moist, but the dry cotton wool gave the seeds no water.", "The seeds on the dry cotton wool were dead."], best: 1, why: "Answer 2 states what seeds need (water) and links it to what each cotton wool gave the seeds. Answer 1 is too vague and never mentions water, and answer 3 is a guess with no evidence: dry seeds are still living." },
    { q: "Karen covered a pail of rainwater with a fine net. After two weeks she found no mosquito larvae in it, although an open pail nearby had many. Explain why.", marks: 2, answers: ["The net has very small holes, so adult mosquitoes could not reach the water to lay eggs. Without eggs, no larvae could hatch in the pail.", "The net killed the larvae in the water.", "Mosquitoes do not like nets, so they flew away."], best: 0, why: "Answer 1 names the property (very small holes) and links it to the life cycle (no eggs laid, so no larvae). Answer 2 is wrong because the net does not kill larvae and still lets air through, and answer 3 gives no science reason." }
  ]
};
