window.BANKV = window.BANKV || {};
BANKV["pcycles"] = {
  flash: [
    { f: "Define: germination", b: "Germination is when a seed starts to grow into a young plant. The seed takes in water and swells, the seed coat splits and the root grows out first." },
    { f: "Three conditions a seed needs to germinate", b: "Water, air and warmth (a suitable temperature)." },
    { f: "Two things a seed does NOT need to germinate", b: "Light and soil. Seeds can germinate in the dark on wet cotton wool." },
    { f: "Function of the seed leaves", b: "Seed leaves store food and provide food to the young plant until its green leaves can make food." },
    { f: "Why do the seed leaves shrivel and drop off?", b: "The food stored in the seed leaves is used up by the growing young plant." },
    { f: "Function of the seed coat", b: "The seed coat protects the seed. It splits open when the seed germinates." },
    { f: "Stages in the life cycle of a flowering plant", b: "Seed → germinating seed → seedling → young plant → adult plant. The adult plant bears flowers, which develop into fruits containing seeds." },
    { f: "What do the flowers of a plant develop into?", b: "Flowers develop into fruits, and the fruits contain seeds that can germinate and grow into new plants." },
    { f: "Define: life span", b: "Life span is how long a plant lives. Different plants have different life spans, e.g. a balsam plant lives a few months, a mango tree many years." },
    { f: "How does a seedling kept in the dark look?", b: "It grows tall, thin and weak with yellowish (pale) leaves, because a seedling needs light to grow well." },
    { f: "How do you prepare a set-up with NO air for seeds?", b: "Boil the water to remove the air, cool it, put in the seeds, then add a layer of oil on top to prevent air from entering the water again." },
    { f: "Why do seeds in a refrigerator not germinate?", b: "It is too cold. The seeds do not get the warmth (suitable temperature) they need to germinate." },
    { f: "Why use many seeds in each set-up instead of one?", b: "Some seeds may be dead or damaged and will not germinate, so using many seeds makes the results more reliable." },
    { f: "What makes an experiment a fair test?", b: "Change only one variable and keep all other variables the same, so that the result is caused only by the variable that was changed." },
    { f: "How do ferns and mosses reproduce?", b: "They reproduce from spores. Ferns and mosses do not have flowers or seeds." }
  ],
  mcq: [
    { q: "The diagram shows an adult chilli padi plant. Which labelled part contains the seeds that can start a new life cycle?", o: ["P", "Q", "R", "S"], a: 2, lvl: 1,
      why: "R is the fruit. The flower (S) develops into the fruit, and the fruit contains the seeds. P is the stem and Q is a leaf; neither contains seeds.",
      fig: { type: "plant", mark: { stem: "P", leaf: "Q", fruit: "R", flower: "S" } } },
    { q: "Which of the following describes a green bean plant at the SEEDLING stage?", o: ["A seed that has swelled and split", "A small plant with seed leaves", "A tall plant with many flowers", "A dry seed kept inside a fruit"], a: 1, lvl: 1,
      why: "A seedling is a small plant with a root, a shoot and seed leaves that give it food. A swollen, split seed is still a germinating seed, and only the adult plant bears flowers." },
    { q: "What happens to the seed coat of a green bean seed when the seed germinates?", o: ["It splits open.", "It becomes the root.", "It turns into a leaf.", "It grows thicker."], a: 0, lvl: 1,
      why: "The seed swells as it takes in water, so the seed coat splits open and the root grows out. The seed coat only protects the seed; it does not become the root or a leaf." },
    { q: "In the Cloud Forest at Gardens by the Bay, Faye saw ferns with rows of tiny brown dots under their leaves. The ferns had no flowers. What do the brown dots most likely hold?", o: ["Seeds", "Fruits", "Flower buds", "Spores"], a: 3, lvl: 1,
      why: "Ferns do not have flowers, fruits or seeds. They reproduce from spores, which are found in the brown dots under their leaves." },
    { q: "Bean sprouts (tau gay) sold at hawker centres are young mung bean seedlings. Why are they long and pale instead of short and green?", o: ["They were grown without light.", "They were given too much water.", "They were grown without any air.", "They were kept in a cold room."], a: 0, lvl: 2,
      why: "Bean sprouts are grown in the dark. A seedling without light grows tall and thin with yellowish (pale) leaves. Without air or warmth, the seeds would not have germinated at all." },
    { q: "Ravi took some soft, cooked green beans from the green bean soup sold in his school canteen. He placed them on wet cotton wool at room temperature. None of them germinated after a week. What is the most likely reason?", o: ["The beans needed soil to germinate.", "The beans needed light to germinate.", "The beans were killed by the cooking.", "The beans had too little water."], a: 2, lvl: 2,
      why: "The beans had water, air and warmth, so the conditions were right. Cooking had killed the seeds, so they could not germinate. Soil and light are not needed for germination." },
    { q: "Mr Goh sowed chilli padi seeds in a pot along his HDB corridor. Which is the correct order of what he would observe?\nP: White flowers appear.\nQ: Green chillies appear.\nR: Two seed leaves appear.\nS: A root grows out of the seed.", o: ["R, S, P, Q", "S, R, P, Q", "S, R, Q, P", "S, P, R, Q"], a: 1, lvl: 2,
      why: "The root grows out first when the seed germinates (S). The seedling then shows its seed leaves (R). The adult plant bears flowers (P), and the flowers develop into fruits, the chillies (Q)." },
    { q: "In an experiment, seeds of four plants were placed on wet cotton wool at room temperature. Study the graph. Which statement is correct?", o: ["Balsam seeds took the longest to germinate.", "Chilli seeds took twice as long as balsam seeds.", "Papaya seeds took 12 days more than balsam seeds.", "Chilli seeds took four times as long as bean seeds."], a: 3, lvl: 2,
      why: "Chilli padi took 8 days and green bean took 2 days, and 8 is four times 2. Papaya (14 days) took the longest, chilli (8) is not twice balsam (5), and papaya took 14 − 5 = 9 days more than balsam, not 12.",
      fig: { type: "bar", title: "Days taken to germinate", xl: "Type of seed", yl: "Number of days", bars: [["Green bean", 2], ["Balsam", 5], ["Chilli padi", 8], ["Papaya", 14]] } },
    { q: "Lina wants to find out if the material the seeds are placed on affects the number of green bean seeds that germinate. Study the set-ups. Which two set-ups should she compare?", o: ["A and B", "B and C", "A and D", "C and D"], a: 0, lvl: 2,
      why: "A and B differ only in the material (cotton wool or sand). B and C have the same material and differ only in temperature, while A and D differ in the number of seeds as well as the material.",
      fig: { type: "setups", items: [
        { label: "A", icon: "dish", lines: ["Wet cotton wool", "10 seeds", "Room temperature"] },
        { label: "B", icon: "dish", lines: ["Wet sand", "10 seeds", "Room temperature"] },
        { label: "C", icon: "dish", lines: ["Wet sand", "10 seeds", "In a refrigerator"] },
        { label: "D", icon: "dish", lines: ["Wet tissue paper", "5 seeds", "Room temperature"] } ] } },
    { q: "Which of the following does NOT happen when a green bean seed germinates?", o: ["The seed takes in water and swells.", "The seed coat splits open.", "The shoot grows out before the root.", "The root grows downwards."], a: 2, lvl: 2,
      why: "The root grows out of the seed first, and only then does the shoot grow out and upwards. Taking in water, swelling and the seed coat splitting all happen during germination." },
    { q: "Study the Venn diagram. Which plant could be X?", o: ["Balsam plant", "Rambutan tree", "Maidenhair fern", "Padi plant"], a: 1, lvl: 2,
      why: "X must grow from seeds AND live for many years. A rambutan tree does both. Balsam and padi plants live only a few months, and a maidenhair fern grows from spores, not seeds.",
      fig: { type: "venn", a: "Grows from seeds", b: "Lives many years", onlyA: ["balsam", "padi"], both: ["mango", "X"], onlyB: ["bird’s nest fern"], neither: [] } },
    { q: "Study the set-ups of green bean seeds. Which of the following statements are correct?\nA: The seeds in P and Q will germinate.\nB: The seeds in R will germinate because they get light.\nC: Comparing Q and R shows that seeds need water to germinate.", o: ["A only", "A and B only", "A and C only", "B and C only"], a: 0, lvl: 3,
      why: "P (the closed jar still has air) and Q both have water, air and warmth, so A is correct. R has no water, so B is wrong. Q and R differ in both water AND light, so C is not a fair comparison.",
      fig: { type: "setups", items: [
        { label: "P", icon: "jar", lines: ["Wet cotton wool", "Lid closed", "Room temperature"] },
        { label: "Q", icon: "pot", lines: ["Wet soil", "Dark cupboard", "Room temperature"] },
        { label: "R", icon: "pot", lines: ["Dry soil", "Near a window", "Room temperature"] } ] } },
    { q: "Ming recorded the height of a bean seedling and the mass of its seed leaves. Study the table. Which statements are best supported by the results and what you know?\nA: As the seedling grew taller, its seed leaves became lighter.\nB: The seed leaves became lighter because they dried up in the sun.\nC: The seedling used the food stored in its seed leaves to grow.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, lvl: 3,
      why: "The height rose from 0 to 9 cm while the seed leaves fell from 4.0 g to 0.6 g, so A is supported. The seed leaves became lighter because the young plant used their stored food (C), not because they dried in the sun.",
      tbl: [["Day", "Height of seedling (cm)", "Mass of seed leaves (g)"], ["0", "0", "4.0"], ["3", "2", "3.0"], ["6", "5", "1.8"], ["9", "9", "0.6"]] },
    { q: "Sam wants to find out if temperature affects the number of days green bean seeds take to germinate. Study the table. Which two set-ups should he compare?", o: ["J and K", "K and L", "J and L", "L and M"], a: 2, lvl: 3,
      why: "J and L differ only in temperature: same type of seed and both wet. J and K also differ in the type of seed, K and L differ only in the type of seed, and L and M differ in water, not temperature.",
      tbl: [["Set-up", "Type of seed", "Temperature (°C)", "Cotton wool"], ["J", "Green bean", "25", "Wet"], ["K", "Red bean", "30", "Wet"], ["L", "Green bean", "30", "Wet"], ["M", "Green bean", "30", "Dry"]] },
    { q: "Nadia measured the height of the shoot of a germinating green bean seed each day. Study the graph. Why was the height 0 cm from Day 0 to Day 2?", o: ["The seed was dead at first.", "The seed had no light yet.", "The seed leaves had dropped off.", "The root grew out before the shoot."], a: 3, lvl: 3,
      why: "When a seed germinates, the root grows out first and the shoot appears later. The seed was not dead, because it grew afterwards, and light is not needed for germination.",
      fig: { type: "line", title: "Height of the shoot", xl: "Day", yl: "Height (cm)", pts: [["0", 0], ["1", 0], ["2", 0], ["3", 1], ["4", 3], ["5", 6]] } },
    { q: "Which of the following are true of ALL flowering plants?\nA: Their life cycle starts from a seed.\nB: They bear flowers and fruits at the adult stage.\nC: Their seed leaves stay on for their whole life.\nD: They live for many years.", o: ["A and B only", "A and C only", "B and D only", "A, B and D only"], a: 0, lvl: 3,
      why: "All flowering plants start from a seed and bear flowers and fruits only as adults. Seed leaves shrivel and drop off once their food is used up, and some flowering plants, like balsam, live only a few months." },
    { q: "Rina soaked 10 green bean seeds in water overnight. The next day, she placed them and 10 dry green bean seeds of the same kind on wet cotton wool in the same place. The soaked seeds germinated one day earlier. What is the best explanation?", o: ["The soaked seeds had been given extra food.", "The soaked seeds had been kept in the dark.", "The soaked seeds had their seed coats removed.", "The soaked seeds had taken in water already."], a: 3, lvl: 3,
      why: "A seed takes in water and swells before its seed coat splits. The soaked seeds had already done this, so they germinated sooner. Water is not food, and the seed coats were not removed." },
    { q: "Study the set-ups. Only the seeds in P and S germinated. Which conclusions can be drawn from these four set-ups?\nA: Seeds need air to germinate.\nB: Seeds need warmth to germinate.\nC: Seeds do not need light to germinate.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 3, lvl: 4,
      why: "P and Q differ only in air, so A. R and S are both in tap water and both dark, since a closed refrigerator is dark inside, so they differ only in temperature: B. P and S differ only in light and both germinated: C.",
      fig: { type: "setups", items: [
        { label: "P", icon: "beaker", lines: ["Tap water", "Near a window", "Room temperature"] },
        { label: "Q", icon: "beaker", lines: ["Boiled, cooled water", "Layer of oil on top", "Near a window", "Room temperature"] },
        { label: "R", icon: "beaker", lines: ["Tap water", "In a refrigerator"] },
        { label: "S", icon: "beaker", lines: ["Tap water", "Dark cupboard", "Room temperature"] } ] } },
    { q: "A hawker grows bean sprouts in a dark room and waters them every day. He sells them after 4 days. If he left some in the dark room for 3 weeks, still watering them daily, what would most likely happen?", o: ["They would keep growing longer as long as they were watered.", "They would turn green and become adult plants in the dark.", "They would stop growing and die once their stored food ran out.", "They would grow flowers since they would be older by then."], a: 2, lvl: 4,
      why: "In the dark, the seedlings grow only with the food stored in their seed leaves. Once it is used up, they cannot make food without light, so they die. Water is not food, and they cannot become green, flowering adults in the dark." },
    { q: "Seeds of plants P, Q, R and S were all sown on the same day. Study the table. Which plant bore its first flowers the earliest?", o: ["P", "Q", "R", "S"], a: 1, lvl: 4,
      why: "Add the two times for each plant: P 3 + 40 = 43, Q 10 + 25 = 35, R 6 + 32 = 38 and S 2 + 45 = 47 days. Q germinated the slowest but flowered first. S is the trap: it germinated fastest but flowered last.",
      tbl: [["Plant", "Days to germinate", "Days from germinating to first flowers", "Life span (days)"], ["P", "3", "40", "90"], ["Q", "10", "25", "60"], ["R", "6", "32", "120"], ["S", "2", "45", "100"]] }
  ],
  oe: [
    { q: "Mr Lim grows bean sprouts for his hawker stall. He tested mung bean seeds in three set-ups, as shown. (a) In which set-ups will the seeds germinate? (b) Explain why the seeds in C will not germinate. (c) Mr Lim wants long, pale bean sprouts like those sold at his stall. Which set-up should he use? Explain why.", marks: 3,
      kw: [["a and b", "b and a", "a, b"], ["no water", "dry", "lack of water", "without water", "not get water", "not have water", "not have any water"], ["dark", "no light", "without light", "not get light", "not get any light"]],
      model: "(a) A and B. (b) The cloth in C is dry, so the seeds have no water, and seeds need water to germinate. (c) Set-up A. In the dark, the seedlings grow tall and thin with yellowish (pale) leaves.",
      fig: { type: "setups", items: [
        { label: "A", icon: "plate", lines: ["Wet cloth", "Dark room", "Room temperature"] },
        { label: "B", icon: "plate", lines: ["Wet cloth", "Near a window", "Room temperature"] },
        { label: "C", icon: "plate", lines: ["Dry cloth", "Dark room", "Room temperature"] } ] } },
    { q: "Mr Goh grew a chilli padi plant from a seed along his HDB corridor and recorded what he saw. Study the table. (a) From the table, in which week can we first tell that the plant had become an adult plant? (b) Explain why the seed leaves had dropped off by Week 5. (c) What did the chillies develop from? (d) Mr Goh wants to grow more chilli padi plants. Which part of the ripe chillies should he sow?", marks: 4,
      kw: [["9", "nine"], ["used up", "ran out", "run out", "no more food", "finished"], ["flower"], ["seeds", "the seed inside", "seed in the"]],
      model: "(a) Week 9, because only an adult plant bears flowers. (b) The food stored in the seed leaves was used up by the growing young plant. (c) The chillies developed from the flowers. (d) He should sow the seeds inside the ripe chillies, because seeds can germinate and grow into new plants.",
      tbl: [["Week", "What Mr Goh observed"], ["1", "The seed coat split and a root grew out."], ["2", "Two seed leaves opened above the soil."], ["5", "The seed leaves had dropped off."], ["9", "The first flowers appeared."], ["12", "The first chillies appeared."]] },
    { q: "Ken soaked green bean seeds in water for different lengths of time. Then he placed 10 seeds from each group on wet cotton wool at room temperature and recorded how many days they took to germinate. Study the graph. (a) Which variable did Ken change? (b) What can he conclude from the results? (c) Explain why soaking the seeds made them germinate in fewer days.", marks: 3,
      kw: [["length of time", "time soaked", "time the seeds", "soaking time", "how long", "number of hours", "duration"], ["fewer days", "less days", "less time", "faster", "quicker", "shorter time", "sooner"], ["took in water", "taken in water", "absorbed water", "absorb water", "take in water", "swell", "seed coat split"]],
      model: "(a) The length of time the seeds were soaked in water. (b) The longer the seeds were soaked, up to 12 hours, the fewer days they took to germinate. Soaking for 24 hours gave the same result as 12 hours. (c) The soaked seeds had already taken in water and begun to swell, so their seed coats split open earlier.",
      fig: { type: "bar", title: "Days taken to germinate", xl: "Time soaked", yl: "Number of days", bars: [["0 hours", 4], ["6 hours", 3], ["12 hours", 2], ["24 hours", 2]] } },
    { q: "Zara wanted to find out if a seedling needs light to grow well. She used three similar bean seedlings in pots of soil at room temperature, as shown. (a) Which two set-ups should she compare? (b) Describe how the leaves of the seedling in Q would look after 10 days, compared with those in P. (c) After 3 weeks, the seedling in Q had died, but the seedling in P was still alive. Explain why the seedling in Q died. Give two ideas.", marks: 4, x: 1,
      kw: [["p and q", "q and p"], ["yellow", "pale"], ["used up", "ran out", "run out", "finished"], ["make food", "make its own food", "make its food"]],
      model: "(a) P and Q, because only the light is different. (b) The leaves of Q would be yellowish (pale), while those of P would be green. (c) The seedling in Q used up the food stored in its seed leaves. In the dark, its leaves could not make food, so it died.",
      fig: { type: "setups", items: [
        { label: "P", icon: "pot", lines: ["Watered daily", "Near a window"] },
        { label: "Q", icon: "pot", lines: ["Watered daily", "In a closed box"] },
        { label: "R", icon: "pot", lines: ["Not watered", "In a closed box"] } ] } }
  ],
  tf: [
    { s: "Bean sprouts sold at hawker centres are pale because they were grown in the dark.", a: true, why: "Seedlings grown without light become tall and thin with yellowish (pale) leaves." },
    { s: "Cooked green beans from green bean soup will germinate if they are placed on wet cotton wool.", a: false, why: "Misconception: any seed with water will germinate. Cooking kills the seeds, so they cannot germinate." },
    { s: "A plant with a longer life span goes through more stages in its life cycle.", a: false, why: "Misconception: life span and life cycle are the same. A mango tree and a balsam plant go through the same stages; only the time taken differs." },
    { s: "A young seedling grows using food stored inside the seed.", a: true, why: "The seed leaves store food for the seedling until its green leaves can make food." },
    { s: "A plant must be an adult plant before it can bear fruits.", a: true, why: "Only the adult plant bears flowers, and the flowers develop into fruits." },
    { s: "A taller seedling is always a healthier seedling.", a: false, why: "Misconception: taller means healthier. A seedling in the dark grows taller but is thin and weak with yellowish leaves." },
    { s: "Soaking seeds in water before sowing can help them germinate sooner.", a: true, why: "The seeds take in water and swell, so their seed coats split open sooner." },
    { s: "Fruits develop from the leaves of a plant.", a: false, why: "Misconception: any part can become a fruit. Fruits develop from flowers." },
    { s: "The moss growing on a damp wall grows from tiny seeds.", a: false, why: "Misconception: all plants grow from seeds. Mosses have no flowers or seeds; they reproduce from spores." },
    { s: "Different kinds of seeds can take different numbers of days to germinate.", a: true, why: "For example, green bean seeds germinate within a few days, while some other seeds take a few weeks." }
  ],
  sort: [
    { title: "Sort these into the stage of a green bean plant’s life cycle at which they happen", groups: ["Germinating seed", "Seedling", "Adult plant"], items: [["the seed takes in water and swells", 0], ["the seed coat splits", 0], ["the root grows out of the seed", 0], ["seed leaves open above the soil", 1], ["a small plant with a root, shoot and seed leaves", 1], ["flowers appear", 2], ["fruits form", 2], ["new seeds are produced in the fruits", 2]] }
  ]
};
