window.BANKZ = window.BANKZ || {};
BANKZ["plants"] = {
  lessons: [
    {
      h: "Planning a fair test with plants",
      concept: "In a plant experiment, change only ONE thing (the changed variable), measure or observe ONE result (the measured variable), and keep everything else the same so the test is fair. Things to keep the same usually include the type and size of plant, the amount of water, the amount of light, the type of soil and the size of pot. Using more than one plant in each set-up makes the results more reliable.",
      example: {
        q: "Mei Ling wants to find out if bird’s nest ferns grow better in damp soil or in dry soil. She sets up A and B as shown.\n(a) What should she change?\n(b) What should she observe or measure?\n(c) State one thing she must keep the same, and explain why.",
        fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["Bird’s nest fern", "Damp soil", "Shady corridor"] }, { label: "B", icon: "pot", lines: ["Bird’s nest fern", "Dry soil", "Shady corridor"] }] },
        marks: 3,
        think: [
          "Step 1: Find the changed variable from the aim: damp soil or dry soil, so she changes the amount of water in the soil.",
          "Step 2: Decide what shows ‘grows better’: something she can count or measure, e.g. the number of new leaves after 3 weeks.",
          "Step 3: Keep the other things the same, e.g. the amount of light (both in the same shady corridor), so that only the water in the soil can cause any difference."
        ],
        answer: "(a) The amount of water in the soil. (b) The number of new leaves on each fern after 3 weeks. (c) The amount of light, so that it is a fair test and only the amount of water is changed."
      },
      tip: "For ‘why keep it the same’, write: ‘so that only ___ is changed and it is a fair test’. Name the changed variable in the blank.",
      try: { q: "Jia Hui wants to find out if balsam plants grow taller in sunlight than in shade. Which should she CHANGE in her experiment?", o: ["The type of plant used", "The amount of light", "The amount of water given", "The size of the pot"], a: 1, why: "The aim compares sunlight and shade, so only the amount of light is changed. The type of plant, the amount of water and the pot size must be kept the same for a fair test." }
    }
  ],
  mcq: [
    { q: "Study the diagram of a plant. Which part holds the plant firmly in the soil and takes in water?", o: ["A", "B", "C", "D"], a: 2, why: "The roots (C) hold the plant firmly in the soil and take in water. A is the stem, which holds the plant up.", lvl: 1, fig: { type: "plant", mark: { stem: "A", leaf: "B", roots: "C", flower: "D" } } },
    { q: "Which of these is a non-flowering plant often seen growing on tree trunks in Singapore’s parks?", o: ["Bougainvillea", "Lotus", "Kangkong", "Staghorn fern"], a: 3, why: "The staghorn fern is a non-flowering plant that grows on tree trunks. Bougainvillea, lotus and kangkong are flowering plants.", lvl: 1 },
    { q: "Duckweed is a very tiny plant that floats on ponds. It produces tiny flowers. How should it be classified?", o: ["A non-flowering water plant", "A flowering water plant", "A flowering land plant", "A non-flowering land plant"], a: 1, why: "Duckweed floats on water and produces flowers, so it is a flowering water plant. Misconception: tiny plants are not always non-flowering; size does not decide the group.", lvl: 1 },
    { q: "Which of the following are water plants?\nA: Lotus\nB: Water hyacinth\nC: Cactus\nD: Hydrilla", o: ["A and B only", "B, C and D only", "A, B and D only", "A, B, C and D"], a: 2, why: "Lotus, water hyacinth and hydrilla all grow in water. A cactus grows on dry land.", lvl: 2 },
    { q: "A P3 class counted the plants in a park in Ang Mo Kio. Study the bar graph. How many of the plants they counted reproduce by seeds?", o: ["8", "14", "28", "20"], a: 3, why: "All flowering plants reproduce by seeds: 14 + 6 = 20. Ferns and mosses (5 + 3 = 8) reproduce by spores. 28 is the total of everything counted.", lvl: 2, fig: { type: "bar", title: "Plants counted in the park", xl: "Type of plant", yl: "Number of plants", bars: [["Flowering land plants", 14], ["Flowering water plants", 6], ["Ferns", 5], ["Mosses", 3]] } },
    { q: "Ravi hung masses on stems of four plants, P, Q, R and S, until each stem bent. The stems were of the same length and thickness. Which two plants most likely have woody stems?", o: ["P and R", "Q and S", "P and Q", "R and S"], a: 1, why: "Woody stems are hard and strong, so they need the heaviest masses to bend them. Q and S needed the most mass, while P and R bent easily like soft, non-woody stems.", lvl: 2, tbl: [["Plant", "Mass needed to bend the stem (g)"], ["P", "60"], ["Q", "900"], ["R", "80"], ["S", "1200"]] },
    { q: "Cheng Hao says, “Only trees have woody stems.” Which plant shows that he is wrong?", o: ["Hibiscus", "Rambutan tree", "Balsam", "Durian tree"], a: 0, why: "Hibiscus is a shrub, not a tree, yet it has a hard, woody stem. Misconception: woody stems are not found only in trees. The rambutan and durian are trees, and balsam has a non-woody stem.", lvl: 2 },
    { q: "Mei saw rows of brown dots under many leaves of a fern at her HDB corridor. She thought the fern was sick. What are the brown dots?", o: ["Tiny flowers that will make seeds", "Dead patches where the leaf is drying", "Spore cases that release spores", "Seeds that will fall to the ground"], a: 2, why: "The brown dots are spore cases, which release spores so the fern can reproduce. Misconception: they are a normal part of a healthy fern, not a sign of sickness. Ferns never have flowers or seeds.", lvl: 2 },
    { q: "Nurul counted the duckweed plants in a tank of pond water every 3 days. Study the line graph. Which characteristic of living things does the graph show?", o: ["They can reproduce", "They need air to live", "They respond to changes", "They make their own food"], a: 0, why: "The number of duckweed plants kept increasing, which shows that duckweed can reproduce. The other statements are true of plants, but the graph does not show them.", lvl: 2, fig: { type: "line", title: "Duckweed in a tank", xl: "Day", yl: "Number of duckweed plants", pts: [["0", 4], ["3", 7], ["6", 12], ["9", 20], ["12", 31]] } },
    { q: "Which of these observations show that a bird’s nest fern is a living thing?\nA: It grows new leaves.\nB: It releases spores that can grow into new ferns.\nC: It is green in colour.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Growing (A) and reproducing (B) are characteristics of living things. Being green (C) is not: a green plastic plant is not alive. Misconception: colour does not show that something is living.", lvl: 3 },
    { q: "Mrs Tan wants to find out if bird’s nest ferns grow better in the shade than in the sun. Study the set-ups. Which two should she compare?", o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ only in light (shady or sunny). A and C differ in water, B and D differ in water and pot size, and C and D differ in light and pot size, so they are not fair tests for this aim.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["Fern, 20 cm pot", "Watered daily", "Shady corridor"] }, { label: "B", icon: "pot", lines: ["Fern, 20 cm pot", "Watered daily", "Sunny rooftop"] }, { label: "C", icon: "pot", lines: ["Fern, 20 cm pot", "Not watered", "Shady corridor"] }, { label: "D", icon: "pot", lines: ["Fern, 40 cm pot", "Not watered", "Sunny rooftop"] }] } },
    { q: "Which of these statements are correct?\nA: Ferns and mosses are both non-flowering plants.\nB: Pine trees and ferns both reproduce by spores.\nC: Mosses and pine trees can both make their own food.", o: ["A only", "B and C only", "A and C only", "A, B and C"], a: 2, why: "Ferns and mosses never produce flowers (A), and all plants, including mosses and pine trees, make their own food (C). B is wrong: pine trees reproduce by seeds in cones.", lvl: 3 },
    { q: "Which of these statements are correct?\nA: A very tall plant can be a non-flowering plant.\nB: A very tiny plant can be a flowering plant.\nC: Flowering plants are always bigger than ferns.", o: ["A and C only", "B and C only", "A, B and C", "A and B only"], a: 3, why: "A pine tree is tall but non-flowering (A), and duckweed is tiny but flowering (B). Misconception: size does not decide the group, so C is wrong; tree ferns can be taller than many flowering plants.", lvl: 3 },
    { q: "Study the classification key. Which plant belongs at R?", o: ["Rice", "Moss", "Pine tree", "Hibiscus"], a: 2, why: "A pine tree reproduces by seeds, but its seeds are in cones, not in fruits, so it is at R. Rice (Q) and hibiscus (P) have seeds in fruits, and moss reproduces by spores (S).", lvl: 3, fig: { type: "flow", root: "Plants", node: { q: "Reproduces by seeds?", yes: { q: "Seeds inside fruits?", yes: { q: "Has a woody stem?", yes: "P", no: "Q" }, no: "R" }, no: "S" } } },
    { q: "Study the table of plants J, K, L and M. Which statements are correct?\nA: J and L both reproduce by seeds.\nB: K is a non-flowering plant.\nC: M is a flowering plant because it has a woody stem.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "J and L produce flowers, so both reproduce by seeds (A). K has no flowers and reproduces by spores (B). C is wrong: a woody stem does not show that a plant flowers, and M has no flowers.", lvl: 3, tbl: [["Plant", "Produces flowers", "Reproduces by spores", "Woody stem"], ["J", "Yes", "No", "Yes"], ["K", "No", "Yes", "No"], ["L", "Yes", "No", "No"], ["M", "No", "No", "Yes"]] },
    { q: "Study the Venn diagram. A pupil wants to add a bougainvillea, a kangkong plant, a bird’s nest fern and a lotus. Which of them should be placed in the overlap?", o: ["Kangkong and lotus only", "Bougainvillea and lotus only", "Bird’s nest fern only", "Bougainvillea only"], a: 3, why: "Only the bougainvillea both reproduces by seeds and has a woody stem. Kangkong and lotus have seeds but soft stems, and the fern reproduces by spores and has no woody stem.", lvl: 3, fig: { type: "venn", a: "Reproduces by seeds", b: "Has a woody stem", onlyA: ["rice", "balsam"], both: ["rambutan", "pine tree"], onlyB: [], neither: ["moss"] } },
    { q: "Ravi wants to find out which of four plants has the strongest stem by hanging masses on the stems until they bend. Which of these must he keep the same?\nA: The length of each stem\nB: The thickness of each stem\nC: The type of plant", o: ["A only", "B and C only", "A, B and C", "A and B only"], a: 3, why: "The type of plant is what he changes, so C cannot be kept the same. Length and thickness also affect how easily a stem bends, so they must be kept the same for a fair test.", lvl: 4 },
    { q: "Study the bar graph of the mass needed to bend stems of the same length and thickness. Which conclusions can be made from the results only?\nA: Plant X has a stronger stem than plant W.\nB: Plant X is a flowering plant.\nC: Plant Z has a stronger stem than plant Y.", o: ["A and C only", "A and B only", "B and C only", "A, B and C"], a: 0, why: "X needed more mass than W, and Z needed more than Y, so A and C are supported. Stem strength does not tell us whether a plant flowers (a pine tree has a woody stem but no flowers), so B cannot be concluded.", lvl: 4, fig: { type: "bar", title: "Mass needed to bend the stem", xl: "Plant", yl: "Mass (g)", bars: [["W", 100], ["X", 1500], ["Y", 70], ["Z", 400]] } },
    { q: "Plant Z does not produce flowers. It reproduces by seeds and has a woody stem. Which statement about plant Z MUST be true?", o: ["It is a tree taller than a hibiscus", "Its seeds are not found in fruits", "It has spore cases under its leaves", "It grows only in damp, shady places"], a: 1, why: "Fruits develop from flowers, so a plant with no flowers cannot have fruits; its seeds must be elsewhere, e.g. in cones. Its height is not certain, spore cases belong to ferns, and nothing tells us where it grows.", lvl: 4 },
    { q: "Pupils counted patches of moss at four places around their school. Study the table. Which conclusion is best supported by the results?", o: ["Moss grows best where it is both damp and shady", "Moss needs only shade, not water, to grow well", "Moss can grow only in places that are damp", "Moss grows better in sunny places than in shade"], a: 0, why: "The most moss (15) was at the damp, shady drain. The dry, shady wall had only 2 patches, so shade alone is not enough, and the dry wall still had some moss, so ‘only where it is damp’ is too strong.", lvl: 4, tbl: [["Place", "Damp?", "Shady?", "Patches of moss"], ["Drain wall", "Yes", "Yes", "15"], ["Car park wall", "No", "Yes", "2"], ["Rooftop ledge", "Yes", "No", "3"], ["Field fence", "No", "No", "0"]] }
  ],
  oe: [
    { q: "Ravi hung masses on the stems of four plants until each stem bent. The stems were cut to the same length. His results are shown in the table.\n(a) What was Ravi trying to find out?\n(b) Besides length, state one other thing about the stems he should keep the same.\n(c) Which two plants have woody stems?\n(d) Use the results to explain your answer in (c).", marks: 4, x: 1, kw: [["strong", "harder to bend", "hardest to bend", "most mass", "heaviest mass"], ["thick", "age", "old"], ["hibiscus and bougainvillea", "bougainvillea and hibiscus", "hibiscus and the bougainvillea", "bougainvillea and the hibiscus", "hibiscus bougainvillea", "bougainvillea hibiscus"], ["more mass", "heavier", "most mass", "larger mass", "more weight", "greater mass", "much more"]], model: "(a) He wanted to find out which plant has the strongest stem, the one that is hardest to bend. (b) The thickness of the stems. (c) The hibiscus and bougainvillea. (d) Their stems needed much more mass (heavier masses) to bend than the balsam and spinach, because woody stems are hard and strong.", tbl: [["Plant", "Mass needed to bend the stem (g)"], ["Balsam", "90"], ["Hibiscus", "1400"], ["Spinach", "50"], ["Bougainvillea", "1800"]] },
    { q: "Mrs Tan set up A and B as shown. After 3 weeks, the fern in A had green leaves, but most leaves of the fern in B had turned yellow and dry.\n(a) What was the changed variable?\n(b) State one thing that was kept the same.\n(c) What can she conclude about where ferns grow well?\n(d) Suggest one way to make her results more reliable.", marks: 4, x: 1, kw: [["light", "sun", "shade", "shady", "place", "location"], ["water", "type of fern", "size of pot", "pot size", "soil", "size of the fern", "same pot"], ["shad"], ["more ferns", "more plants", "repeat", "several", "a few ferns", "many ferns", "more than one"]], model: "(a) The amount of light (shade or sun). (b) The amount of water given each day. (c) Ferns grow well in shady places. (d) Use more ferns in each set-up, or repeat the experiment.", fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["Bird’s nest fern", "Watered daily", "Shady corridor"] }, { label: "B", icon: "pot", lines: ["Bird’s nest fern", "Watered daily", "Sunny rooftop"] }] } },
    { q: "Jia Hui placed pot A of young balsam plants inside a box with a hole on one side. Pot B was placed on a table in an open, bright room. Both were watered the same amount.\n(a) Predict what the shoots in A will look like after a week.\n(b) Which characteristic of living things does this show?\n(c) Why did she set up pot B as well?", marks: 3, kw: [["towards the hole", "towards the light", "to the light", "to the hole", "toward the light", "toward the hole"], ["respond"], ["compar", "control"]], model: "(a) The shoots in A will bend towards the hole, where the light comes in. (b) Living things respond to changes around them. (c) Pot B is for comparison, to show what the shoots look like when light is not coming from one side only.", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Balsam plants", "In a box", "Hole on one side"] }, { label: "B", icon: "pot", lines: ["Balsam plants", "No box", "Open, bright room"] }] } },
    { q: "Nurul counted the duckweed plants in a tank of pond water every 3 days. Study the line graph.\n(a) How many duckweed plants were there on Day 9?\n(b) Describe how the number of duckweed plants changed.\n(c) Which characteristic of living things does this show?", marks: 3, kw: [["20", "twenty"], ["increase", "went up", "more and more", "grew in number"], ["reproduce"]], model: "(a) There were 20 duckweed plants on Day 9. (b) The number of duckweed plants increased from 4 to 31 over 12 days. (c) Living things can reproduce.", fig: { type: "line", title: "Duckweed in a tank", xl: "Day", yl: "Number of duckweed plants", pts: [["0", 4], ["3", 7], ["6", 12], ["9", 20], ["12", 31]] } },
    { q: "Study the classification key.\n(a) Suggest a suitable question for Question 1.\n(b) Suggest a suitable question for Question 2.\n(c) A pupil used the key for a pine tree and it ended up with the moss. Explain why a pine tree should NOT be grouped with a moss.", marks: 3, kw: [["flower"], ["under", "spore case", "brown dot", "root", "big leaves", "large leaves", "bigger leaves", "larger leaves"], ["seed", "cone"]], model: "(a) Does it produce flowers? (b) Does it have spore cases under its leaves? (c) A pine tree reproduces by seeds found in cones, but a moss reproduces by spores.", fig: { type: "flow", root: "Plants", node: { q: "Question 1", yes: { q: "Grows in water?", yes: "lotus", no: "hibiscus" }, no: { q: "Question 2", yes: "fern", no: "moss" } } } },
    { q: "At Gardens by the Bay, Lina saw a tree fern that was much taller than her. It had no flowers.\n(a) Is the tree fern a flowering or non-flowering plant?\n(b) How does it reproduce?\n(c) Lina’s friend says, “It is so tall that it must be a flowering plant.” Explain why he is wrong.", marks: 3, kw: [["non-flowering", "non flowering"], ["spore"], ["size", "how tall", "how big", "height", "tall"]], model: "(a) It is a non-flowering plant. (b) It reproduces by spores, found in spore cases under its leaves. (c) Size or height does not decide the group. A plant is flowering only if it produces flowers, and the tree fern never produces flowers, however tall it grows." }
  ],
  tf: [
    { s: "A hibiscus plant has a woody stem even though it is not a tree.", a: true, why: "Hibiscus is a shrub with a hard, woody stem." },
    { s: "Brown dots under a fern leaf show that the fern is sick.", a: false, why: "They are spore cases, a normal part of a healthy fern." },
    { s: "A very tall plant must be a flowering plant.", a: false, why: "Pine trees and tree ferns are tall but non-flowering." },
    { s: "Duckweed is a flowering plant even though it is very tiny.", a: true, why: "Size does not decide the group; duckweed produces tiny flowers." },
    { s: "Plants that live under water do not need light.", a: false, why: "All plants, including hydrilla, need light to make food." },
    { s: "Staghorn ferns can grow on the trunks of trees.", a: true, why: "They are non-flowering plants often seen on tree trunks in Singapore." },
    { s: "A plant with no fruits on it now must be a non-flowering plant.", a: false, why: "Many flowering plants bear fruits only at certain times of the year." },
    { s: "A shoot bending towards a window shows that plants respond to changes.", a: true, why: "The shoot responds to light coming from one side." },
    { s: "Hydrilla is a non-flowering plant because it lives under water.", a: false, why: "Hydrilla produces small flowers; living in water does not make a plant non-flowering." },
    { s: "In a fair test comparing the stems of different plants, only the type of plant should be changed.", a: true, why: "Length and thickness of the stems must be kept the same." }
  ],
  doc: [
    { q: "Ravi tested how strong the stems of four plants were. Why did he use stems of the same length?", marks: 2, answers: ["To make it fair.", "Because the stems were long.", "So that only the type of plant is changed, making it a fair test."], best: 2, why: "Answer 3 names what is changed (only the type of plant) AND says it is a fair test. Answer 1 says ‘fair’ but does not say what is being changed, so it scores at most 1 mark. Answer 2 does not explain anything about a fair test." },
    { q: "A tree fern is taller than a hibiscus plant. Explain why the tree fern is a non-flowering plant.", marks: 2, answers: ["It never produces flowers and it reproduces by spores.", "It is taller than the hibiscus.", "It has green leaves."], best: 0, why: "Answer 1 gives the key reason (it never produces flowers) and supports it (it reproduces by spores). Answer 2 uses size, which does not decide whether a plant flowers. Answer 3 is true of flowering plants too, so it does not explain anything." }
  ]
};
