window.BANKV = window.BANKV || {};
BANKV["plants"] = {
  flash: [
    { f: "Define: flowering plant", b: "A plant that produces flowers at some point in its life. Its flowers develop into fruits, which contain seeds." },
    { f: "Define: non-flowering plant", b: "A plant that never produces flowers, e.g. fern, moss, pine tree." },
    { f: "How does a fern reproduce, and where are these structures found?", b: "By spores. The spores are in spore cases (brown dots) on the underside of its leaves." },
    { f: "Where are the spores of a moss found?", b: "In spore capsules at the tips of thin stalks." },
    { f: "Why is a mushroom NOT a plant?", b: "It is a fungus. It has no green leaves and cannot make its own food." },
    { f: "What do the flowers of a flowering plant develop into?", b: "Flowers develop into fruits, and the fruits contain seeds that can grow into new plants." },
    { f: "Why is a pine tree non-flowering even though it has seeds?", b: "It never produces flowers. Its seeds are found in cones, not in fruits." },
    { f: "No flowers are seen on a plant. What is the best evidence that it is still a flowering plant?", b: "It has fruits. Fruits develop from flowers, so the plant must have produced flowers before." },
    { f: "Why is grass a flowering plant even though we seldom see its flowers?", b: "Grass does produce flowers, so it is a flowering plant. Its flowers are small and not colourful, so they are hard to see." },
    { f: "Function of the roots", b: "Roots hold the plant firmly in the soil and take in water from the soil." },
    { f: "Function of the stem", b: "The stem holds the plant upright and supports its leaves, flowers and fruits." },
    { f: "Function of green leaves", b: "Green leaves make food for the plant." },
    { f: "Woody stem vs non-woody stem", b: "Woody: hard, thick and strong (e.g. rambutan tree, hibiscus). Non-woody: soft, green and bends easily (e.g. balsam, kangkong)." },
    { f: "Three kinds of water plants, with examples", b: "Float freely (water hyacinth, duckweed); rooted in mud with floating leaves (water lily); live under water (hydrilla)." },
    { f: "What is true of ALL plants, flowering or non-flowering?", b: "They are living things that need air, water and light, and they can make their own food." }
  ],
  mcq: [
    { q: "Study the diagram of a balsam plant. Which part develops into a fruit that contains seeds?", o: ["P", "Q", "R", "S"], a: 3, why: "S is the flower, and flowers develop into fruits that contain seeds. P is the roots, Q is a leaf and R is the stem; none of these become fruits.", lvl: 1, fig: { type: "plant", mark: { roots: "P", leaf: "Q", stem: "R", flower: "S" } } },
    { q: "Which part of a plant makes food for the plant?", o: ["Green leaves", "Roots", "Stem", "Fruits"], a: 0, why: "Green leaves make food for the plant. Roots hold the plant and take in water, the stem holds the plant upright, and fruits contain seeds.", lvl: 1 },
    { q: "Which water plant has its roots in the mud at the bottom of a pond, with leaves that float on the water surface?", o: ["Hydrilla", "Duckweed", "Water lily", "Water hyacinth"], a: 2, why: "The water lily is rooted in the mud and its leaves float on the surface. Duckweed and water hyacinth float freely, and hydrilla lives under the water.", lvl: 1 },
    { q: "On a nature walk at MacRitchie Reservoir Park, Aisha saw a plant with large green leaves. Rows of brown dots were on the underside of each leaf. What is the plant most likely to be?", o: ["A fern", "A moss", "A hibiscus", "A mushroom"], a: 0, why: "Brown dots under the leaves are spore cases, which ferns have. A moss is tiny with spore capsules on stalks, a hibiscus has flowers, and a mushroom has no green leaves.", lvl: 1 },
    { q: "Study the bar graph of the plants in a school eco-garden. How many more plants with non-woody stems than plants with woody stems are there?", o: ["8", "14", "3", "6"], a: 3, why: "Balsam and spinach have non-woody stems: 8 + 6 = 14. Hibiscus and bougainvillea have woody stems: 5 + 3 = 8. So there are 14 − 8 = 6 more.", lvl: 2, fig: { type: "bar", title: "Plants in the school eco-garden", xl: "Plant", yl: "Number of plants", bars: [["Hibiscus", 5], ["Balsam", 8], ["Spinach", 6], ["Bougainvillea", 3]] } },
    { q: "Which statement about water plants is NOT true?", o: ["Some water plants float freely on the water surface", "Some water plants live completely under water", "Water plants cannot make their own food", "Some water plants produce flowers"], a: 2, why: "Water plants are plants, so they make their own food just like land plants. Water hyacinth floats freely, hydrilla lives under water and the lotus produces flowers.", lvl: 2 },
    { q: "Mdm Lim tried to pull a weed out of the planter at her HDB block. It was hard to pull out, and it came out with soil stuck to its long roots. Which job of the roots does this show?", o: ["They hold the plant firmly in the soil", "They make food for the plant", "They develop into fruits and seeds", "They hold the leaves up towards the light"], a: 0, why: "The weed was hard to pull out because its roots hold it firmly in the soil. Green leaves make food, flowers develop into fruits, and the stem holds the leaves up.", lvl: 2 },
    { q: "Which of the following are true of a durian tree?\nA: It has a woody stem.\nB: It reproduces by seeds.\nC: It flowers only at certain times of the year.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 3, why: "A durian tree has a hard, woody stem (A). It is a flowering plant whose fruits contain seeds (B), and it flowers only at certain times of the year (C). All three are true.", lvl: 2 },
    { q: "Study the classification chart. Where should a water hyacinth be placed?", o: ["P", "Q", "R", "S"], a: 2, why: "A water hyacinth is a flowering plant, so it reproduces by seeds, not spores (No). It floats on water (Yes), so it is at R.", lvl: 2, fig: { type: "flow", root: "Plants", node: { q: "Reproduces by spores?", yes: { q: "Spore cases under leaves?", yes: "P", no: "Q" }, no: { q: "Grows in water?", yes: "R", no: "S" } } } },
    { q: "The Cloud Forest dome at Gardens by the Bay is kept cool, damp and misty. Many ferns and mosses grow well inside. Which statement best explains this?", o: ["Ferns and mosses produce more flowers in mist", "Ferns and mosses cannot make their own food", "Ferns and mosses grow best in hot, dry air", "Ferns and mosses grow well in damp places"], a: 3, why: "Ferns and mosses grow well in damp, moist places. They never produce flowers, they are green plants that make their own food, and they do not grow well in hot, dry air.", lvl: 2 },
    { q: "Pupils cut open four fruits bought from the school canteen and counted the seeds. Study the table. What is true of ALL four fruits?", o: ["They all developed from flowers", "They all have many seeds inside", "They all came from non-flowering plants", "They all have only one seed inside"], a: 0, why: "Every fruit develops from a flower, so all four came from flowering plants. The table shows that some have one seed and some have many, so the other choices do not fit all four.", lvl: 2, tbl: [["Fruit", "Number of seeds"], ["Papaya", "more than 100"], ["Rambutan", "1"], ["Chilli", "about 40"], ["Mango", "1"]] },
    { q: "Ben wants to find out if water hyacinths grow better in a sunny spot or in a shady spot. Study the set-ups. Which two should he compare?", o: ["A and B", "A and C", "B and C", "C and D"], a: 1, why: "A and C differ only in the amount of light (sunny or shady). A and B differ in both the water and the light, B and C differ in the water, and C and D differ in the number of plants.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["3 water hyacinths", "Pond water", "Sunny spot"] }, { label: "B", icon: "jar", lines: ["3 water hyacinths", "Tap water", "Shady spot"] }, { label: "C", icon: "jar", lines: ["3 water hyacinths", "Pond water", "Shady spot"] }, { label: "D", icon: "jar", lines: ["6 water hyacinths", "Pond water", "Shady spot"] }] } },
    { q: "Study the Venn diagram. Which pair of plants could be X and Y?", o: ["X: bougainvillea, Y: fern", "X: fern, Y: lotus", "X: rice, Y: durian tree", "X: kangkong, Y: moss"], a: 3, why: "X must produce flowers but have a non-woody stem, like kangkong. Y must have neither, like a moss. Bougainvillea and durian trees are woody and flowering (overlap), a fern does not flower, and a lotus flowers.", lvl: 3, fig: { type: "venn", a: "Has a woody stem", b: "Produces flowers", onlyA: ["pine tree"], both: ["hibiscus", "rambutan"], onlyB: ["balsam", "X"], neither: ["Y"] } },
    { q: "Which of these observations would show that a plant is a NON-flowering plant?\nA: It has spore cases under its leaves.\nB: No flowers were seen on it during a one-day visit.\nC: It has spore capsules at the tips of thin stalks.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Spore cases under leaves (a fern) and spore capsules on stalks (a moss) show plants that reproduce by spores and never flower. B is the common misconception: many flowering plants, like mango trees, flower only at certain times.", lvl: 3 },
    { q: "Hana recorded the number of flowers and fruits on a plant in her HDB corridor garden each week. Study the table. Which statement is supported by the results?", o: ["The plant became non-flowering in Week 6", "The flowers developed into fruits over the weeks", "The fruits developed into flowers from Week 3", "The plant had the most fruits in Week 3"], a: 1, why: "As the number of flowers fell after Week 3, the number of fruits rose, because flowers develop into fruits. Having no flowers in Week 6 does not make it non-flowering, and the most fruits (10) were in Week 6.", lvl: 3, tbl: [["Week", "Number of flowers", "Number of fruits"], ["1", "0", "0"], ["2", "4", "0"], ["3", "9", "2"], ["4", "5", "6"], ["5", "1", "9"], ["6", "0", "10"]] },
    { q: "Some water plants were grouped.\nGroup 1: water lily, lotus, water hyacinth, duckweed\nGroup 2: hydrilla\nWhich heading is most suitable for Group 2?", o: ["Reproduces by spores", "Does not produce flowers", "Lives completely under water", "Has a woody stem"], a: 2, why: "Hydrilla lives under the water, while all the Group 1 plants have leaves on the water surface. Hydrilla is a flowering plant with small flowers, so it reproduces by seeds, and it has a soft stem.", lvl: 3 },
    { q: "Study the classification chart. Which of these statements are correct?\nA: A pine tree and a hibiscus are both at W.\nB: Grass and kangkong are both at X.\nC: A moss and a fern are both at Z.", o: ["B only", "A and B only", "B and C only", "A, B and C"], a: 2, why: "Grass and kangkong are flowering plants with non-woody stems (X). Mosses and ferns are non-flowering and reproduce by spores (Z). A is wrong: a pine tree does not produce flowers, so it is at Y, not W.", lvl: 3, fig: { type: "flow", root: "Plants", node: { q: "Produces flowers?", yes: { q: "Has a woody stem?", yes: "W", no: "X" }, no: { q: "Reproduces by seeds?", yes: "Y", no: "Z" } } } },
    { q: "Study the table of living things P, Q, R and S. Which of these statements are correct?\nA: P could be a lotus.\nB: Q and S are both non-flowering plants.\nC: R and S could both be plants.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "P makes its own food, produces flowers and grows in water, like a lotus (A). Q and S make their own food but have no flowers, so both are non-flowering plants (B). R cannot make its own food, so it is not a plant (likely a fungus), and C is wrong.", lvl: 4, tbl: [["", "Makes its own food", "Produces flowers", "Reproduces by", "Grows in"], ["P", "Yes", "Yes", "Seeds", "Water"], ["Q", "Yes", "No", "Seeds", "Land"], ["R", "No", "No", "Spores", "Land"], ["S", "Yes", "No", "Spores", "Land"]] },
    { q: "A P3 class counted living things at Bishan-Ang Mo Kio Park. Study the bar graph. How many of the living things counted are non-flowering PLANTS?", o: ["13", "10", "20", "15"], a: 0, why: "Pine trees (3), ferns (6) and mosses (4) are non-flowering plants: 3 + 6 + 4 = 13. Leaving out the pine trees gives 10, and adding the mushrooms gives 20, but mushrooms are fungi, not plants.", lvl: 4, fig: { type: "bar", title: "Living things counted in the park", xl: "Type", yl: "Number counted", bars: [["Flowering plants", 12], ["Pine trees", 3], ["Ferns", 6], ["Mosses", 4], ["Mushrooms", 7]] } },
    { q: "Plant W produces flowers. Which of the following MUST be true about plant W?\nA: It reproduces by seeds.\nB: It grows on land.\nC: It can make its own food.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Its flowers develop into fruits with seeds, so it reproduces by seeds (A), and all plants make their own food (C). B need not be true: the water lily and lotus are flowering plants that grow in water.", lvl: 4 }
  ],
  oe: [
    { q: "Study the diagram of a plant.\n(a) Name part B.\n(b) State one job of part B.\n(c) Part A takes in water from the soil. State one other job of part A.\n(d) Part D will develop into a fruit. What is found inside the fruit that can grow into a new plant?", marks: 4, kw: [["stem"], ["upright", "support", "holds the plant up", "hold the plant up", "holds up", "hold up"], ["firmly", "anchor", "in place", "grip"], ["seed"]], model: "(a) B is the stem. (b) It holds the plant upright and supports the leaves and flowers. (c) Part A, the roots, holds the plant firmly in the soil. (d) Seeds are found inside the fruit.", fig: { type: "plant", mark: { roots: "A", stem: "B", leaf: "C", flower: "D" } } },
    { q: "Pupils put 3 water hyacinth plants into each of two tanks with the same amount of pond water. Tank A was placed in a sunny spot and Tank B in a shady spot. Their results are shown in the table.\n(a) What was the changed variable?\n(b) State one thing that was kept the same.\n(c) By how many plants did the number of water hyacinths in Tank A increase?\n(d) Ravi says that water hyacinth is a non-flowering plant because it floats on water. Explain why he is wrong.", marks: 4, x: 1, kw: [["light", "sun", "shade", "shady", "place", "location"], ["pond water", "amount of water", "type of water", "3 plants", "three plants", "same number", "starting number", "size of tank", "tank size", "type of plant"], ["12", "twelve"], ["produces flowers", "produce flowers", "has flowers", "have flowers", "purple flowers", "bears flowers", "it flowers"]], model: "(a) The amount of light (sunny or shady spot). (b) The amount of pond water in each tank. (c) It increased by 12 plants, from 3 to 15. (d) Water hyacinth produces flowers, so it is a flowering plant. Where a plant grows does not decide whether it flowers.", tbl: [["Tank", "Place", "Number of plants at start", "Number of plants after 4 weeks"], ["A", "Sunny spot", "3", "15"], ["B", "Shady spot", "3", "6"]] },
    { q: "Study the classification chart.\n(a) Name one plant that belongs at K.\n(b) A bird’s nest fern belongs at L. Where on the fern are its spores found?\n(c) Name one plant that belongs at M.", marks: 3, kw: [["pine", "conifer"], ["underside", "under the leaves", "under its leaves", "spore case", "brown dot", "back of the leaves", "below the leaves"], ["balsam", "spinach", "kangkong", "grass", "rice", "lotus", "water lily", "duckweed", "hydrilla", "water hyacinth", "sunflower", "lady", "tomato", "water lettuce"]], model: "(a) A pine tree: it has a woody stem but does not produce flowers. (b) In spore cases on the underside of its leaves. (c) A balsam plant: it has a non-woody stem and reproduces by seeds, not spores.", fig: { type: "flow", root: "Plants", node: { q: "Has a woody stem?", yes: { q: "Produces flowers?", yes: "J", no: "K" }, no: { q: "Reproduces by spores?", yes: "L", no: "M" } } } },
    { q: "At a hawker centre, Jun ate sambal kangkong and fried rice with tomatoes and chilli.\n(a) Tomatoes and chillies are fruits. Which part of the plant did they develop from?\n(b) Name the structures inside a tomato that can grow into new plants.\n(c) Kangkong has a soft, green stem that bends easily. What type of stem is this?", marks: 3, kw: [["flower"], ["seed"], ["non-woody", "non woody", "not woody", "soft stem"]], model: "(a) They developed from the flowers of the plants. (b) The seeds. (c) It is a non-woody stem." }
  ],
  tf: [
    { s: "A tomato is not a fruit because it does not taste sweet.", a: false, why: "A tomato develops from a flower and contains seeds, so it is a fruit; taste does not matter." },
    { s: "Roots make food for the plant.", a: false, why: "Green leaves make food; roots hold the plant firmly in the soil and take in water." },
    { s: "Water hyacinth has no roots because it floats on the water.", a: false, why: "Its roots hang down in the water beneath the floating plant." },
    { s: "All plants with woody stems are flowering plants.", a: false, why: "A pine tree has a woody stem but never produces flowers." },
    { s: "A flowering plant has flowers on it all year round.", a: false, why: "Many flowering plants, such as mango and durian trees, flower only at certain times of the year." },
    { s: "A water lily has roots in the mud at the bottom of the pond.", a: true, why: "It is rooted in the mud, and its leaves float on the water surface." },
    { s: "The rice grains we eat come from the flowers of the rice plant.", a: true, why: "Rice flowers are small and dull, and they develop into the grains." },
    { s: "A pine tree has a woody stem but does not produce flowers.", a: true, why: "It is a non-flowering plant whose seeds are in cones." },
    { s: "A moss never produces fruits.", a: true, why: "Fruits develop from flowers, and mosses never produce flowers." },
    { s: "Ferns and flowering plants both have roots, stems and leaves.", a: true, why: "Ferns have roots, stems and leaves, but no flowers or fruits." }
  ],
  sort: [
    { title: "Sort these living things by how they reproduce", groups: ["Plant: reproduces by seeds", "Plant: reproduces by spores", "Not a plant (fungus)"], items: [["hibiscus", 0], ["pine tree", 0], ["rice", 0], ["lotus", 0], ["bird’s nest fern", 1], ["moss", 1], ["staghorn fern", 1], ["mushroom", 2], ["bread mould", 2]] }
  ]
};
