window.BANKX = window.BANKX || {};
BANKX["plants"] = {
  notes: [
    { h: "Ferns vs mosses", t: "Both are non-flowering green plants that make their own food, reproduce by spores and grow well in damp, shady places. A fern is bigger, with roots, stems and leaves, and its spore cases are brown dots on the underside of its leaves. A moss is very small and its spores are in spore capsules at the tips of thin stalks.", kw: ["both reproduce by spores", "spore cases on the underside of leaves", "spore capsules on thin stalks", "damp, shady places"] },
    { h: "Seeds vs spores", t: "Seeds are formed inside fruits (in flowering plants) or in cones (pine trees). A seed contains a young plant and stored food. Spores are much smaller, like fine dust, and are formed in spore cases (ferns) or spore capsules (mosses). Spores are NOT tiny seeds.", kw: ["seeds inside fruits", "seeds in cones", "spores are like fine dust", "spores are not seeds"] },
    { h: "Classifying plants with keys and Venn diagrams", t: "Choose ONE characteristic at each step, e.g. ‘Produces flowers?’, ‘Reproduces by seeds?’, ‘Has a woody stem?’, ‘Grows in water?’. In a Venn diagram, a plant can be in the overlap when it has both characteristics, e.g. a water lily is a flowering plant AND a water plant. A region can be empty, e.g. no plant produces flowers but does not reproduce by seeds.", kw: ["one characteristic at each step", "overlap", "both characteristics", "region can be empty"] }
  ],
  traps: [
    "‘Spores are just very small seeds’ -> spores are not seeds; seeds form in fruits or cones, spores form in spore cases or capsules.",
    "‘Big plants are flowering and small plants are non-flowering’ -> size does not tell us; duckweed is a tiny flowering plant and some ferns grow very large.",
    "‘A fruit must be sweet to be a fruit’ -> chilli, lady’s finger and cucumber are fruits too, because they develop from flowers and contain seeds."
  ],
  mcq: [
    { q: "Study the Venn diagram. Which plants are BOTH flowering plants and water plants?", o: ["Hibiscus and durian tree", "Fern and moss", "Water lily and lotus", "Hibiscus and lotus"], a: 2, why: "The water lily and lotus are in the overlap, so they have both characteristics. Hibiscus is a flowering land plant, so it is only in the ‘Produces flowers’ circle.", lvl: 1, fig: { type: "venn", a: "Produces flowers", b: "Grows in water", onlyA: ["hibiscus", "durian tree"], both: ["water lily", "lotus"], onlyB: [], neither: ["fern", "moss"] } },
    { q: "A fern releases tiny, dust-like ______ from the brown dots under its leaves.", o: ["spores", "seeds", "fruits", "flowers"], a: 0, why: "The brown dots are spore cases, which release spores. Ferns never produce seeds, fruits or flowers.", lvl: 1 },
    { q: "Study the classification chart. Which plant could be Q?", o: ["Lotus", "Moss", "Hibiscus", "Hydrilla"], a: 2, why: "Q is a flowering plant that does not grow in water, like hibiscus. Lotus and hydrilla are water plants (P) and moss does not produce flowers (R).", lvl: 1, fig: { type: "flow", root: "Plants", node: { q: "Produces flowers?", yes: { q: "Grows in water?", yes: "P", no: "Q" }, no: "R" } } },
    { q: "Which of the following is a fruit that contains seeds?", o: ["Kangkong leaf", "Fern leaf", "Moss capsule", "Lady’s finger"], a: 3, why: "Lady’s finger develops from a flower and has seeds inside, so it is a fruit. A moss capsule contains spores, not seeds.", lvl: 1 },
    { q: "Study the Venn diagram. Why is the pine tree in the ‘Reproduces by seeds’ circle only?", o: ["It reproduces by spores found in its cones", "It has seeds in cones but does not produce flowers", "It produces flowers but does not make seeds", "It cannot make its own food like other green plants"], a: 1, why: "A pine tree reproduces by seeds, which are found in cones, but it never produces flowers. It is a green plant, so it can make its own food.", lvl: 2, fig: { type: "venn", a: "Reproduces by seeds", b: "Produces flowers", onlyA: ["pine tree"], both: ["rambutan", "rice", "hibiscus"], onlyB: [], neither: ["fern", "moss"] } },
    { q: "Which pair of plants BOTH reproduce by seeds?", o: ["Fern and rice", "Moss and pine tree", "Fern and moss", "Pine tree and rice"], a: 3, why: "Rice is a flowering plant and the pine tree has seeds in cones, so both reproduce by seeds. Ferns and mosses reproduce by spores.", lvl: 2 },
    { q: "Study the classification chart. Which is correctly matched?", o: ["W: moss, Z: balsam", "X: moss, Y: hibiscus", "X: fern, Z: rice", "W: fern, Z: rambutan tree"], a: 1, why: "Moss reproduces by spores but has no spore cases under its leaves (X). Hibiscus reproduces by seeds and has a woody stem (Y). A fern is at W and a rambutan tree is at Y.", lvl: 2, fig: { type: "flow", root: "Plants", node: { q: "Reproduces by spores?", yes: { q: "Spore cases under leaves?", yes: "W", no: "X" }, no: { q: "Has a woody stem?", yes: "Y", no: "Z" } } } },
    { q: "Which of these parts will you NOT find on a moss plant?", o: ["Green leaf-like parts", "Thin stalks", "Flowers", "Spore capsules"], a: 2, why: "Mosses are non-flowering plants, so they never have flowers. They have tiny green leaf-like parts and thin stalks with spore capsules at the tips.", lvl: 2 },
    { q: "Which of the following is a correct difference between seeds and spores?", o: ["Seeds form in fruits or cones, while spores form in spore cases or capsules", "Spores are much bigger than seeds, so they are easy to see by eye", "Seeds are made by ferns and mosses, while spores come from flowers", "Spores are found inside fruits, while seeds form in spore cases"], a: 0, why: "Seeds come from fruits (flowering plants) or cones (pine trees). Spores are much smaller and come from spore cases or capsules of ferns and mosses.", lvl: 2 },
    { q: "Which statement about mosses is correct?", o: ["They have large, colourful flowers on their long stems", "They grow best in hot, dry places in full sun", "They are fungi that grow on damp, rotting logs", "They are green plants that can make their own food"], a: 3, why: "Mosses are green non-flowering plants that make their own food. They grow in damp, shady places, and they are plants, not fungi.", lvl: 2 },
    { q: "The line graph shows the number of fruits on a chilli padi plant. There were no fruits in Week 1 and Week 2. What must the plant have produced before the fruits appeared?", o: ["Spores", "Flowers", "Cones", "Spore capsules"], a: 1, why: "In flowering plants, flowers develop into fruits. So the chilli plant must have produced flowers first. Spores and cones are not produced by chilli plants.", lvl: 2, fig: { type: "line", title: "Chilli padi plant", xl: "Week", yl: "Number of fruits", pts: [["1", 0], ["2", 0], ["3", 2], ["4", 5], ["5", 9], ["6", 12]] } },
    { q: "Which group contains ONLY non-flowering plants?", o: ["Moss, rice plant, staghorn fern", "Pine tree, hibiscus, bird’s nest fern", "Bird’s nest fern, moss, pine tree", "Mushroom, moss, maidenhair fern"], a: 2, why: "Ferns, mosses and pine trees never produce flowers. Rice and hibiscus are flowering plants, and a mushroom is a fungus, not a plant.", lvl: 2 },
    { q: "Study the Venn diagram. Why is the region for ‘Produces flowers’ only (outside ‘Reproduces by seeds’) empty?", o: ["All plants that produce flowers also reproduce by seeds", "No plants produce flowers, so nothing belongs there", "Plants with flowers reproduce by spores, not seeds", "The pupil forgot to put the rambutan in that empty region"], a: 0, why: "Flowers develop into fruits with seeds, so every flowering plant reproduces by seeds and belongs in the overlap. The rambutan is correctly in the overlap.", lvl: 3, fig: { type: "venn", a: "Reproduces by seeds", b: "Produces flowers", onlyA: ["pine tree"], both: ["rambutan", "rice", "hibiscus"], onlyB: [], neither: ["fern", "moss"] } },
    { q: "Hui Min recorded what she found in the school garden. Study the bar graph. How many non-flowering PLANTS did she find?", o: ["3", "5", "8", "12"], a: 2, why: "Ferns (5) and mosses (3) are non-flowering plants: 5 + 3 = 8. Mushrooms are fungi, not plants, so 12 is wrong.", lvl: 3, fig: { type: "bar", title: "Things found in the school garden", xl: "Type", yl: "Number found", bars: [["Flowering plants", 18], ["Ferns", 5], ["Mosses", 3], ["Mushrooms", 4]] } },
    { q: "Study the classification chart. A pupil placed four plants on it. Which plant has been placed WRONGLY?", o: ["Rambutan tree at A", "Water lily at B", "Balsam at C", "Bird’s nest fern at D"], a: 3, why: "A fern has no flowers and reproduces by spores, not seeds, so it belongs at E. The rambutan (woody), water lily (non-woody, in water) and balsam (non-woody, on land) are correct.", lvl: 3, fig: { type: "flow", root: "Plants", node: { q: "Produces flowers?", yes: { q: "Has a woody stem?", yes: "A", no: { q: "Grows in water?", yes: "B", no: "C" } }, no: { q: "Reproduces by seeds?", yes: "D", no: "E" } } } },
    { q: "Study the Venn diagram. Which statement is correct?", o: ["Everything in the ‘Reproduces by spores’ circle is a plant", "Only the things in the ‘Makes its own food’ circle are plants", "The pine tree should be in the overlap because it has no flowers", "The mushroom should be in the overlap because it grows on logs"], a: 1, why: "Plants make their own food, so all the plants are in that circle. The mushroom and bread mould reproduce by spores but are fungi. The pine tree reproduces by seeds, so it is not in the spores circle.", lvl: 3, fig: { type: "venn", a: "Reproduces by spores", b: "Makes its own food", onlyA: ["mushroom", "bread mould"], both: ["fern", "moss"], onlyB: ["hibiscus", "pine tree"], neither: ["cat"] } },
    { q: "Kiran found a green plant growing on a tree trunk. He made these observations.\nA: It has brown dots on the underside of its leaves.\nB: It had no flowers all year.\nC: It grows on a tree trunk.\nD: It has green leaves.\nWhich observation(s) best show that it is a fern and NOT a moss?", o: ["A only", "A and B only", "B and C only", "A, B and D only"], a: 0, why: "Only ferns have spore cases (brown dots) under their leaves. Mosses also have no flowers, can grow on tree trunks and are green, so B, C and D do not tell the two apart.", lvl: 3 },
    { q: "Ahmad wants to find out if moss needs water to stay green and healthy. Which two set-ups should he compare?", o: ["A and C", "B and C", "A, B and C", "A and B"], a: 3, why: "A and B differ ONLY in watering, so it is a fair test. A and C differ in both water and light, and B and C differ in light, not water.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Moss on a brick", "Watered daily", "Shady corner"] }, { label: "B", icon: "plate", lines: ["Moss on a brick", "Not watered", "Shady corner"] }, { label: "C", icon: "plate", lines: ["Moss on a brick", "Not watered", "Sunny spot"] }] } },
    { q: "Which of the following statements about plants is NOT true?", o: ["A plant that reproduces by spores can also produce flowers", "Some non-flowering plants reproduce by seeds", "Some plants that reproduce by spores grow on tree trunks", "Both flowering and non-flowering plants can make their own food"], a: 0, why: "Plants that reproduce by spores (ferns, mosses) never produce flowers. Pine trees are non-flowering with seeds, staghorn ferns and mosses grow on tree trunks, and all plants make their own food.", lvl: 3 },
    { q: "A mystery plant floats on the surface of a pond. It produces purple flowers and reproduces by seeds. Which plant could it be?", o: ["Hydrilla", "Water hyacinth", "Moss", "Bird’s nest fern"], a: 1, why: "Water hyacinth is a floating flowering water plant. Hydrilla lives under the water, and moss and ferns are non-flowering land plants.", lvl: 3 }
  ],
  tf: [
    { s: "Spores are much smaller than seeds.", a: true, why: "Spores are like fine dust; seeds can be seen and held easily." },
    { s: "A plant that reproduces by spores never produces flowers.", a: true, why: "Ferns and mosses are non-flowering plants." },
    { s: "Water hyacinth is a flowering plant.", a: true, why: "It is a floating water plant with purple flowers." },
    { s: "A plant can be both a water plant and a flowering plant.", a: true, why: "e.g. the water lily and the lotus." },
    { s: "Ferns grow best in hot, dry, sunny places.", a: false, why: "Ferns grow best in damp, shady places." },
    { s: "Seeds are only found in plants with colourful flowers.", a: false, why: "Grass and rice have dull flowers but produce seeds, and pine trees have seeds in cones." },
    { s: "Mosses produce seeds in the capsules at the tips of their stalks.", a: false, why: "The capsules contain spores, not seeds." },
    { s: "Only plants reproduce by spores.", a: false, why: "Fungi such as mushrooms and bread mould also reproduce by spores." }
  ],
  oe: [
    { q: "Study the Venn diagram.\n(a) Name one plant that could be X.\n(b) The fern and moss are outside both circles. State how they reproduce.\n(c) In which region should a pine tree be placed?", marks: 3, kw: [["lily", "lotus", "hyacinth", "hydrilla", "duckweed", "water lettuce"], ["spore"], ["outside", "neither", "not in any", "not in either", "none of the circles"]], model: "(a) X could be a water lily. (b) They reproduce by spores. (c) The pine tree should be placed outside both circles, because it does not produce flowers and it grows on land.", fig: { type: "venn", a: "Produces flowers", b: "Grows in water", onlyA: ["hibiscus", "balsam"], both: ["X"], onlyB: [], neither: ["fern", "moss"] } },
    { q: "Study the classification chart.\n(a) Name a plant that belongs to B.\n(b) Name a plant that belongs to C.\n(c) Plants at D also reproduce by spores. Where are their spores found?", marks: 3, kw: [["pine", "conifer"], ["fern"], ["capsule", "stalk"]], model: "(a) A pine tree belongs to B: it has no flowers but reproduces by seeds. (b) A bird’s nest fern belongs to C. (c) The plants at D are mosses; their spores are found in spore capsules at the tips of thin stalks, not under the leaves.", fig: { type: "flow", root: "Plants", node: { q: "Produces flowers?", yes: "A", no: { q: "Reproduces by seeds?", yes: "B", no: { q: "Spore cases under leaves?", yes: "C", no: "D" } } } } },
    { q: "Study the line graph of the number of fruits on a lady’s finger plant.\n(a) How many fruits were there in Week 4?\n(b) Which part of the plant developed into the fruits?\n(c) What is found inside each fruit that can grow into a new plant?", marks: 3, kw: [["7", "seven"], ["flower"], ["seed"]], model: "(a) There were 7 fruits in Week 4. (b) The flowers developed into the fruits. (c) Seeds are found inside each fruit.", fig: { type: "line", title: "Lady’s finger plant", xl: "Week", yl: "Number of fruits", pts: [["1", 0], ["2", 1], ["3", 4], ["4", 7], ["5", 10]] } },
    { q: "Ahmad set up the experiment shown. After 2 weeks, the moss in A was green and healthy but the moss in B had dried up and turned brown.\n(a) What did Ahmad want to find out?\n(b) Why were both bricks placed in the same shady corner?\n(c) Based on the results, what kind of places do mosses grow well in?", marks: 3, kw: [["water"], ["fair", "only one", "one thing"], ["damp", "wet", "moist"]], model: "(a) He wanted to find out whether moss needs water to stay green and healthy. (b) To make it a fair test: only one thing (water) is changed. (c) Mosses grow well in damp, shady places.", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Moss on a brick", "Sprayed with water", "every day", "Shady corner"] }, { label: "B", icon: "plate", lines: ["Moss on a brick", "Not watered", "Shady corner"] }] } },
    { q: "State two differences between a bird’s nest fern and a moss.", marks: 2, kw: [["underside", "under its leaves", "under the leaves", "spore case"], ["capsule", "stalk", "smaller", "small", "tiny", "bigger", "larger"]], model: "The fern has spore cases on the underside of its leaves, but the moss has its spores in capsules at the tips of thin stalks. The fern is also much bigger, while the moss is very small." },
    { q: "Plant K floats on a pond at the Singapore Botanic Gardens. It has purple flowers.\n(a) Is K a land plant or a water plant?\n(b) How does K reproduce?\n(c) Which part of K develops into fruits?\n(d) Give one reason why K is NOT a fern.", marks: 4, kw: [["water plant", "water"], ["seed"], ["flower"], ["fern never", "ferns never", "fern does not", "ferns do not", "fern doesn't", "ferns don't", "fern has no", "ferns have no", "fern cannot", "ferns reproduce by spore", "fern reproduces by spore", "it has flowers", "k has flowers", "it produces flowers", "k produces flowers", "not spores", "no spore"]], model: "(a) K is a water plant. (b) K reproduces by seeds. (c) Its flowers develop into fruits. (d) K produces flowers, but a fern never produces flowers and reproduces by spores." },
    { q: "A pine tree and a rambutan tree both reproduce by seeds.\n(a) Where are the seeds of the pine tree found?\n(b) Where are the seeds of the rambutan tree found?\n(c) Explain why only the rambutan tree is a flowering plant.", marks: 3, kw: [["cone"], ["fruit"], ["flower"]], model: "(a) Pine seeds are found in cones. (b) Rambutan seeds are found inside the fruits. (c) The rambutan tree produces flowers which develop into fruits, but the pine tree never produces flowers." },
    { q: "Sam says, “Spores are just tiny seeds.” Is he right? Explain.", marks: 2, kw: [["not right", "wrong", "incorrect", "not correct", "disagree"], ["spore case", "capsule", "fruit", "cone", "not seeds", "different"]], model: "No, he is wrong. Spores are not seeds. Spores are formed in spore cases or capsules of ferns and mosses, while seeds are formed inside fruits or cones." }
  ],
  doc: [
    { q: "How is a bird’s nest fern different from a hibiscus plant in the way it reproduces?", marks: 2, answers: ["The fern has no flowers.", "The fern reproduces by spores, but the hibiscus reproduces by seeds.", "The fern reproduces by spores."], best: 1, why: "Answer 2 compares BOTH plants: spores for the fern and seeds for the hibiscus. Answer 3 only describes the fern, so it is not a full comparison. Answer 1 talks about flowers, not about how the plant reproduces, so it does not answer the question." },
    { q: "Explain why a moss is classified as a plant and not a fungus.", marks: 2, answers: ["Because it is green and can make its own food, but fungi cannot make their own food.", "Because it reproduces by spores.", "Because it grows on walls."], best: 0, why: "Answer 1 gives the key difference: plants make their own food and fungi cannot. Answer 2 is not a reason, because fungi also reproduce by spores. Answer 3 describes where it grows, which does not decide its group." },
    { q: "A water lily grows in a pond. Is it a flowering or non-flowering plant? Explain.", marks: 2, answers: ["It is non-flowering because it lives in water.", "It is flowering.", "It is a flowering plant because it produces flowers, which develop into fruits with seeds."], best: 2, why: "Answer 3 gives the correct group AND the reason (it produces flowers). Answer 2 is correct but gives no explanation, so it scores at most 1 mark. Answer 1 is wrong: many water plants, like the lotus and water hyacinth, produce flowers." },
    { q: "Where are the spores of a fern found, and what do they look like?", marks: 2, answers: ["Under the leaves.", "In spore cases, which look like brown dots on the underside of the leaves.", "In the flowers of the fern."], best: 1, why: "Answer 2 names the structure (spore cases), where they are (underside of the leaves) AND what they look like (brown dots). Answer 1 gives the place only and misses what they look like. Answer 3 is wrong: ferns never have flowers." },
    { q: "A pine tree has seeds. Explain why it is still a non-flowering plant.", marks: 2, answers: ["It never produces flowers; its seeds are found in cones, not in fruits.", "Because it is a tall tree.", "Because it has seeds."], best: 0, why: "Answer 1 states that it never produces flowers AND explains where the seeds come from (cones, not fruits). Answer 2 gives a reason that has nothing to do with flowers. Answer 3 is the wrong way round: having seeds is why pupils think it IS flowering." }
  ]
};
