window.BANKV = window.BANKV || {};
BANKV["skills"] = {
  flash: [
    { f: "Define: fair test", b: "A test in which only ONE variable is changed and all other variables are kept the same, so we can tell what caused the result." },
    { f: "What is the variable changed?", b: "The one variable that is changed on purpose to see how it affects the result." },
    { f: "What is the variable measured?", b: "The result that is counted, measured or observed. It may change because of the variable changed." },
    { f: "Purpose of a control set-up", b: "For comparison, to show that the result is caused by the variable being tested." },
    { f: "How do you make results more reliable?", b: "Repeat the experiment a few times (or use more samples, e.g. more seeds) and check that the results are similar." },
    { f: "Observation vs inference", b: "An observation is what you see, hear, smell, touch or measure. An inference is an explanation based on observations." },
    { f: "What is a prediction?", b: "A statement of what will happen, based on a pattern in the data or on what you already know." },
    { f: "How do you write the aim of an experiment?", b: "To find out if / how [the variable changed] affects [the variable measured]." },
    { f: "Why must only one variable be changed in a fair test?", b: "If more than one variable is changed, we cannot tell which variable caused the difference in the results." },
    { f: "Apparatus and unit for: temperature, time, volume of a liquid", b: "Thermometer (°C); stopwatch (seconds or minutes); measuring cylinder (ml)." },
    { f: "How do you describe a trend?", b: "As [the variable changed] increases, [the variable measured] increases / decreases. Quote the first and last values with units." },
    { f: "What must a conclusion be based on?", b: "Only on the data collected, about the things that were tested. It answers the aim." },
    { f: "What does a flat part of a line graph show?", b: "The variable measured stayed the same (did not change) during that time." },
    { f: "What does CER stand for?", b: "Claim (answer the question), Evidence (quote the data with units and a comparison word), Reasoning (the science idea that explains it)." },
    { f: "What should you do with a result that does not fit the pattern?", b: "Check it and repeat that reading before using it to draw a conclusion." }
  ],
  mcq: [
    { q: "Which of these readings is a measurement of TIME?", o: ["25 °C", "25 ml", "25 s", "25 cm"], a: 2, why: "s (seconds) is a unit of time, measured with a stopwatch. °C is for temperature, ml is for volume and cm is for length.", lvl: 1 },
    { q: "At Gardens by the Bay, Lily watched a bird with a long, thin beak poking its beak into some flowers. Which statement is an INFERENCE?", o: ["The bird has a long, thin beak.", "The bird visited five red flowers.", "The bird is drinking nectar from the flowers.", "The bird has green feathers on its back."], a: 2, why: "Lily cannot see any nectar; she is explaining what the bird is doing from what she saw, so it is an inference. The other three are observations made by looking.", lvl: 1 },
    { q: "Siew Ling wants to find out if the type of soil affects how fast water drains through it. What is the variable CHANGED?", o: ["Type of soil", "Amount of water poured", "Time taken for water to drain", "Size of the funnel"], a: 0, why: "She changes the type of soil on purpose. The time taken for the water to drain is the variable measured; the amount of water and the size of the funnel are kept the same.", lvl: 1 },
    { q: "Mrs Tan’s class measured the height of a balsam plant every day for 10 days. Which is the most suitable way to show how the height changed over the 10 days?", o: ["Bar graph", "Line graph", "Venn diagram", "Classification key"], a: 1, why: "A line graph shows how something changes over time, so the trend in height is easy to see. A Venn diagram and a key are used to group things, not to show change.", lvl: 1 },
    { q: "The school canteen vendor wants a tablecloth that keeps the tables dry when drinks are spilled. She poured the same amount of water onto same-sized pieces of four materials and measured the water that passed through. Study the bar graph. Which material should she choose?", o: ["Cotton", "Nylon", "Linen", "Vinyl"], a: 3, why: "No water (0 ml) passed through vinyl, so it is waterproof and will keep the table dry; nylon let 3 ml through. Here the SHORTEST bar is the best, because the bars show the water that passed through.", lvl: 2, fig: { type: "bar", title: "Water that passed through", xl: "Material", yl: "Water passed through (ml)", bars: [["Cotton", 18], ["Nylon", 3], ["Linen", 12], ["Vinyl", 0]] } },
    { q: "Wen dipped the end of a strip of paper towel into coloured water. She measured how high the water had risen up the strip every minute. Study the table. Predict the missing value.", o: ["8 cm", "9 cm", "10 cm", "11 cm"], a: 1, why: "The height goes up by 2 cm every minute: 3, 5, 7, 9, 11. So at 4 minutes it is 9 cm.", lvl: 2, tbl: [["Time (min)", "Height of water on strip (cm)"], ["1", "3"], ["2", "5"], ["3", "7"], ["4", "?"], ["5", "11"]] },
    { q: "Ahmad wants to find out which brand of kitchen paper towel absorbs the most water. Which of these is NOT a variable that he should keep the same?", o: ["Size of each paper towel", "Amount of water in each bowl", "Time each towel is left in the water", "Brand of the paper towel"], a: 3, why: "The brand is the variable changed, so it must be different. The size, the amount of water and the time must all be kept the same for a fair test.", lvl: 2 },
    { q: "Study the classification key. Which of these belongs to Group Q?", o: ["Mushroom", "Bird’s nest fern", "Sparrow", "Rain tree"], a: 0, why: "A mushroom cannot make its own food and reproduces by spores, so it is in Q. A fern also reproduces by spores, but it makes its own food, so it goes to P at the first question.", lvl: 2, fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "P", no: { q: "Reproduces by spores?", yes: "Q", no: "R" } } } },
    { q: "Mei wants to find out if light affects the growth of mould on bread. Study the set-ups. Which two set-ups should she compare?", o: ["A and B", "A and C", "A and D", "C and D"], a: 2, why: "A and D differ only in light (dark box vs bright room). A and B also differ in moisture, A and C also differ in the type of bread, and C and D differ only in the type of bread, not in light.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["White bread", "Moist", "In a dark box"] }, { label: "B", icon: "plate", lines: ["White bread", "Dry", "In a bright room"] }, { label: "C", icon: "plate", lines: ["Wholemeal bread", "Moist", "In a bright room"] }, { label: "D", icon: "plate", lines: ["White bread", "Moist", "In a bright room"] }] } },
    { q: "Study the line graph of a bean seedling’s height. How many days did it take for the seedling to grow from 3 cm to 10 cm?", o: ["2 days", "4 days", "6 days", "8 days"], a: 1, why: "The seedling was 3 cm tall on Day 4 and 10 cm tall on Day 8, so it took 8 − 4 = 4 days. Day 8 is when it reached 10 cm, not how long it took.", lvl: 2, fig: { type: "line", title: "Height of a bean seedling", xl: "Day", yl: "Height (cm)", pts: [["0", 0], ["2", 1], ["4", 3], ["6", 6], ["8", 10], ["10", 15]] } },
    { q: "A canteen vendor wants to find out which brand of cling wrap keeps cut papaya fresh for the longest time. Which of these must she keep the same?\nA: Size of the papaya pieces\nB: Brand of cling wrap\nC: Place where the papaya is kept", o: ["A only", "A and B only", "A and C only", "B and C only"], a: 2, why: "The brand of cling wrap is the variable changed, so it must be different. The size of the papaya pieces and the place where they are kept must be the same for a fair test.", lvl: 2 },
    { q: "At the school butterfly garden, Ryan counted how many times butterflies landed on flowers of each colour in 1 hour. Study the bar graph. Which statement is NOT supported by the data?", o: ["Red flowers had the most landings.", "Yellow and purple flowers had the same number of landings.", "Red flowers had more than four times as many landings as white flowers.", "Butterflies do not land on white flowers at all."], a: 3, why: "Butterflies landed on white flowers 3 times, so ‘do not land at all’ is wrong. 14 is the most, yellow and purple both had 9, and 14 is more than 4 × 3 = 12.", lvl: 3, fig: { type: "bar", title: "Butterfly landings in 1 hour", xl: "Colour of flower", yl: "Number of landings", bars: [["Red", 14], ["Yellow", 9], ["White", 3], ["Purple", 9]] } },
    { q: "Kumar placed different sheets between a magnet and a tray of steel paper clips and counted the clips attracted. Study the table. Which statements are correct?\nA: P and Q can be compared to find out if the material of the sheet affects the number of clips attracted.\nB: Q and R can be compared to find out if the thickness of the sheet affects the number of clips attracted.\nC: Q and S can be compared to find out if the material of the sheet affects the number of clips attracted.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "P and Q differ only in material, and Q and R differ only in thickness, so A and B are correct. Q and S differ in material AND in the magnet used, so C is not a fair comparison.", lvl: 3, tbl: [["Set-up", "Material of sheet", "Thickness of sheet", "Magnet used"], ["P", "Glass", "2 mm", "X"], ["Q", "Plastic", "2 mm", "X"], ["R", "Plastic", "4 mm", "X"], ["S", "Wood", "2 mm", "Y"]] },
    { q: "Study the classification key. Which statement is correct?", o: ["W and X are both insects.", "Y is an insect with 8 legs.", "Z could be a spider.", "X must have wings."], a: 0, why: "W and X both have 6 legs, so both are insects (some insects, such as worker ants, have no wings). Y has 8 legs, so it is not an insect; a spider goes to Y, not Z; and X has no wings.", lvl: 3, fig: { type: "flow", root: "Animals", node: { q: "Has 6 legs?", yes: { q: "Has wings?", yes: "W", no: "X" }, no: { q: "Has 8 legs?", yes: "Y", no: "Z" } } } },
    { q: "Mdm Siti wants to make a bag for carrying fish and vegetables home from the wet market. The bag must be strong and waterproof. She tested same-sized pieces of four materials. Study the table. Which material is the MOST suitable?", o: ["Thick plastic", "Cotton cloth", "Thin plastic", "Paper"], a: 0, why: "Thick plastic is strong (it held 7 kg) and waterproof (0 ml passed through). Cotton cloth is the strongest but let 30 ml of water through, and thin plastic is waterproof but tears easily.", lvl: 3, tbl: [["Material", "Mass held before tearing (kg)", "Water that passed through (ml)"], ["Paper", "1", "20"], ["Cotton cloth", "8", "30"], ["Thin plastic", "2", "0"], ["Thick plastic", "7", "0"]] },
    { q: "Four pupils each tested a magnet three times by counting the paper clips it attracted. Study the table. Whose results are the MOST reliable?", o: ["Ben", "Amy", "Cal", "Dee"], a: 0, why: "Ben’s three results are very close to each other (12, 12 and 13), so they are the most reliable. The other pupils’ results are very different each time, so something may have gone wrong.", lvl: 3, tbl: [["Pupil", "Try 1", "Try 2", "Try 3"], ["Ben", "12", "12", "13"], ["Amy", "10", "18", "4"], ["Cal", "5", "15", "9"], ["Dee", "20", "8", "14"]] },
    { q: "Kelly put a dry sponge in a tray of water and measured the total volume of water it had absorbed every minute. Study the graph. Which statement is correct?", o: ["The sponge absorbed the same amount of water every minute.", "The sponge absorbed 35 ml of water from Minute 1 to Minute 2.", "The sponge was still absorbing water from Minute 4 to Minute 5.", "The sponge absorbed the most water in the first minute."], a: 3, why: "In each minute it absorbed 20, 15, 10, 5 and then 0 ml, so the most was in the first minute. 35 ml is the total at Minute 2 (only 15 ml was absorbed from Minute 1 to 2), and the flat line shows no more water was absorbed from Minute 4 to 5.", lvl: 3, fig: { type: "line", title: "Water absorbed by a sponge", xl: "Time (min)", yl: "Total water absorbed (ml)", pts: [["0", 0], ["1", 20], ["2", 35], ["3", 45], ["4", 50], ["5", 50]] } },
    { q: "Rani wants to make a key with exactly TWO yes/no questions. She will ask both questions about every animal, so that each animal ends up in a different group. Study the table. Which pair of questions should she use?", o: ["Has legs? and Has wings?", "Has 6 legs? and Has 8 legs?", "Has wings? and Has 2 legs?", "Has 6 legs? and Has wings?"], a: 3, why: "Beetle (6 legs, wings), worker ant (6 legs, no wings), sparrow (not 6 legs, wings) and spider (not 6 legs, no wings) all give different answers. ‘Has legs?’ is yes for all four, ‘Has 6 legs? and Has 8 legs?’ cannot separate the beetle and the ant, and ‘Has wings? and Has 2 legs?’ cannot separate the ant and the spider.", lvl: 4, tbl: [["Animal", "Number of legs", "Has wings?"], ["Beetle", "6", "Yes"], ["Worker ant", "6", "No"], ["Sparrow", "2", "Yes"], ["Spider", "8", "No"]] },
    { q: "Identical slices of moist bread were kept at different temperatures for 10 days. Study the table. Which statement is supported by the data?", o: ["The higher the temperature, the sooner mould appeared.", "Of the temperatures tested, mould appeared soonest at 30 °C.", "Mould can never grow on bread above a temperature of 40 °C.", "Mould appeared later at 40 °C than it did at 10 °C."], a: 1, why: "3 days at 30 °C is the shortest time of all the temperatures tested. Mould appeared later at 40 °C (6 days) than at 30 °C, so ‘the higher, the sooner’ is wrong; 6 days at 40 °C is sooner than 9 days at 10 °C; and only 50 °C was tested above 40 °C, and only for 10 days.", lvl: 4, tbl: [["Temperature (°C)", "Days before mould appeared"], ["10", "9"], ["20", "5"], ["30", "3"], ["40", "6"], ["50", "No mould after 10 days"]] },
    { q: "Mdm Lee runs a drinks stall at a hawker centre and wants a cloth to wipe up spills. She dipped same-sized pieces of four cloths, each into its own beaker of 200 ml of water, and measured the water LEFT in each beaker. Study the bar graph. Which statements are correct?\nA: Cloth Q is the most suitable for wiping up spills.\nB: Cloth R absorbed the most water, as its bar is the tallest.\nC: Cloth Q absorbed three times as much water as cloth R.", o: ["A only", "A and B only", "A and C only", "B and C only"], a: 2, why: "Water absorbed = 200 ml − water left: P 80 ml, Q 150 ml, R 50 ml, S 100 ml. Q absorbed the most (A), and 150 ml is three times 50 ml (C). R’s tall bar means a lot of water was LEFT, so R absorbed the least.", lvl: 4, fig: { type: "bar", title: "Water left in the beaker", xl: "Cloth", yl: "Water left (ml)", bars: [["P", 120], ["Q", 50], ["R", 150], ["S", 100]] } }
  ],
  oe: [
    {
      q: "Faizal dipped the end of a strip of paper towel into coloured water. He recorded how high the water had risen up the strip every minute. Study the line graph.\n(a) Describe how the height of the water changed from Minute 0 to Minute 4. [1]\n(b) What happened to the height of the water from Minute 4 to Minute 5? [1]\n(c) Faizal now wants to find out if the type of paper affects how high the water rises. State TWO variables he must keep the same: one about the paper strips and one about the coloured water. [2]",
      fig: { type: "line", title: "Height of water on a paper strip", xl: "Time (min)", yl: "Height of water (cm)", pts: [["0", 0], ["1", 4], ["2", 7], ["3", 9], ["4", 10], ["5", 10]] },
      marks: 4,
      kw: [["increas", "rose", "went up", "got higher", "became higher"], ["stayed the same", "stays the same", "remained the same", "did not change", "didn’t change", "no change", "stayed at 10", "constant"], ["size", "width", "length"], ["amount", "volume", "depth", "deep", "temperature"]],
      model: "(a) The height of the water increased from 0 cm to 10 cm. (b) The height of the water stayed the same at 10 cm. (c) Paper strips: the size (length and width) of each strip. Coloured water: the amount (depth) of coloured water each strip is dipped into."
    },
    {
      q: "Jia Wen wants to choose the strongest magnet to hold papers on her fridge door at home. She tested each magnet 3 times by counting how many sheets of paper it could hold on the door before the sheets slipped. Study the table.\n(a) Which magnet has a result that should be checked again? [1]\n(b) Explain your answer to (a). [1]\n(c) Why did she test each magnet 3 times? [1]\n(d) State one variable she must keep the same. [1]",
      tbl: [["Magnet", "Try 1", "Try 2", "Try 3"], ["K", "6", "7", "6"], ["L", "12", "3", "11"], ["M", "9", "9", "10"]],
      marks: 4,
      kw: [["l"], ["3 sheets", "only 3", "very different", "different from", "does not fit", "doesn’t fit", "much fewer", "much less", "much lower", "far fewer", "odd one"], ["reliable"], ["type of paper", "size of paper", "size of the paper", "size of each sheet", "same paper", "same type of paper", "same fridge", "same door", "same part", "same spot", "thickness of paper"]],
      model: "(a) Magnet L. (b) In Try 2, Magnet L held only 3 sheets, which is very different from its other results (12 and 11 sheets). (c) To check that the results are similar each time, so that the results are more reliable. (d) The type of paper used (or the size of each sheet, or using the same fridge door)."
    },
    {
      q: "Ali wanted to find out if the type of soil affects how many green bean seeds germinate. Study his set-ups.\n(a) Apart from the type of soil, name the TWO variables that are different in set-up C. [2]\n(b) Ali’s friend said, ‘These set-ups show that seeds need soil to germinate.’ Explain why this conclusion cannot be drawn from Ali’s set-ups. [1]\n(c) Why should Ali use 10 seeds in each pot instead of just 1 seed? [1]",
      fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["10 green bean seeds", "Garden soil", "20 ml water daily", "Near a window"] }, { label: "B", icon: "pot", lines: ["10 green bean seeds", "Sand", "20 ml water daily", "Near a window"] }, { label: "C", icon: "pot", lines: ["5 green bean seeds", "Clay", "40 ml water daily", "Near a window"] }] },
      marks: 4,
      x: 1,
      kw: [["number of seeds", "5 seeds", "fewer seeds", "5 green bean"], ["amount of water", "40 ml", "more water", "volume of water"], ["without soil", "no soil", "all the set-ups had", "all set-ups had", "every set-up had", "all of them had", "all had soil", "all pots had", "every pot had", "all the pots had"], ["reliable", "faulty", "dead seed"]],
      model: "(a) The number of seeds (5 seeds instead of 10) and the amount of water given each day (40 ml instead of 20 ml). (b) Every set-up had soil and there was no set-up without soil to compare with, so Ali cannot tell whether seeds can germinate without soil. (c) Some seeds may be faulty and not germinate, so using more seeds makes the results more reliable."
    },
    {
      q: "The town council wants a material for the side screen of a bus stop. The screen must keep rain off the commuters and let them see the bus coming. Same-sized pieces of four materials were tested. Study the table.\n(a) Which material is the most suitable? [1]\n(b) Use the data to explain your answer to (a). [2]\n(c) Explain why netting is not suitable. [1]",
      tbl: [["Material", "Water that passed through (ml)", "Can you see through it?"], ["Canvas", "2", "No"], ["Clear plastic", "0", "Yes"], ["Netting", "40", "Yes"], ["Metal sheet", "0", "No"]],
      marks: 4,
      kw: [["clear plastic"], ["0 ml", "no water", "none of the water"], ["see through", "transparent", "can see"], ["40 ml", "lets water", "let water", "allows water", "not waterproof"]],
      model: "(a) Clear plastic. (b) 0 ml of water passed through clear plastic, so it is waterproof and will keep the rain off the commuters. It is also transparent, so the commuters can see through it to watch for the bus. (c) 40 ml of water passed through the netting, so it is not waterproof and the commuters would get wet."
    }
  ],
  tf: [
    { s: "A conclusion should answer the aim of the experiment.", a: true, why: "The aim asks a question; the conclusion uses the data to answer it." },
    { s: "A result that does not fit the pattern can simply be crossed out without repeating the test.", a: false, why: "An odd result should be checked by repeating that reading, not just removed." },
    { s: "In a fair test, the variable measured should be kept the same in every set-up.", a: false, why: "The variable measured is the result; it is what we expect may be different. The other variables are kept the same." },
    { s: "A bar graph is suitable when the variable changed is a type or kind, such as the type of material.", a: true, why: "Each type gets its own bar, so the results are easy to compare." },
    { s: "If the line on a line graph goes down, the variable measured is decreasing.", a: true, why: "A line going down shows a decrease; going up shows an increase." },
    { s: "Saying ‘it looks like there is more mould’ is as good as counting the mould spots.", a: false, why: "Counting or measuring gives accurate data that can be compared fairly." },
    { s: "A hand lens can be used to count the legs of a small ant.", a: true, why: "A hand lens makes small things look bigger, so small details can be seen." },
    { s: "The time each material is left in the water does not matter, as long as the type of material is changed.", a: false, why: "The time must be kept the same; otherwise two variables are changed." },
    { s: "A control set-up is set up in the same way as the other set-ups, except for the variable being tested.", a: true, why: "It is used for comparison, so only the variable being tested is different." },
    { s: "If two magnets each attract 8 paper clips in one try, they must be exactly equally strong.", a: false, why: "One try is not enough; the test should be repeated to make the results reliable." }
  ],
  sort: [
    { title: "Does each step make the test FAIR or the results more RELIABLE?", groups: ["Makes the test fair", "Makes the results more reliable"], items: [["changing only one variable", 0], ["using the same type of paper clips for every magnet", 0], ["using same-sized pieces of each material", 0], ["keeping all the set-ups in the same place", 0], ["repeating the experiment three times", 1], ["using 10 seeds in each dish instead of 1", 1], ["testing three magnets of each kind", 1], ["checking that repeated results are similar", 1]] }
  ]
};
