window.BANKX = window.BANKX || {};
BANKX["skills"] = {
  notes: [
    { h: "Reading line graphs", t: "A line graph shows how something changes over time or as another variable changes. A line going up shows an increase, a line going down shows a decrease, and a flat line shows no change. A steeper part of the line means a faster change. To estimate a value between two points, read it off the line; be careful when predicting beyond the data that was tested.", kw: ["increase", "decrease", "stays the same", "steeper means faster"] },
    { h: "Choosing set-ups to compare", t: "To test one variable, compare only the set-ups that are the same in every way EXCEPT that one variable. If two set-ups differ in two or more things (e.g. amount of water AND number of seeds), they cannot be compared fairly, because we cannot tell which difference caused the result.", kw: ["only one variable is different", "all other variables kept the same"] },
    { h: "Writing answers precisely", t: "Name variables in full: ‘the type of material’, ‘the number of paper clips attracted’, not ‘the stuff’ or ‘the clips’. When comparing, use comparison words such as ‘more than’, ‘less than’, ‘fewer than’ or ‘the most’, and quote the data with units (e.g. ‘60 ml, more than the towel’s 45 ml’). A claim without a reason or without data seldom gets full marks.", kw: ["more than", "less than", "quote the data", "name the variable in full"] }
  ],
  traps: [
    "A flat part of a line graph means the line is broken -> A flat part means the value did NOT change during that time.",
    "Answering ‘Which is better?’ with just a name, e.g. ‘Sponge.’ -> Give the claim, quote the data with a comparison word (more/less than), then explain.",
    "Any two set-ups can be compared if you look carefully -> Only compare set-ups that differ in ONE variable; otherwise you cannot tell what caused the result."
  ],
  mcq: [
    { q: "Study the bar graph. Which magnet is the strongest?", o: ["Magnet P", "Magnet Q", "Magnet R", "Magnet S"], a: 1, why: "Magnet Q attracted the most paper clips (15), so it is the strongest. Magnet R attracted the fewest (5), so it is the weakest.", lvl: 1, fig: { type: "bar", title: "Paper clips attracted by magnets", xl: "Magnet", yl: "Number of paper clips", bars: [["P", 8], ["Q", 15], ["R", 5], ["S", 11]] } },
    { q: "Mei used a weighing scale to find the mass of a pineapple. Which unit should she use?", o: ["g", "ml", "cm", "°C"], a: 0, why: "Mass is measured in grams (g). ml is for volume, cm for length and °C for temperature.", lvl: 1 },
    { q: "Study the Venn diagram. Which animal can fly but does NOT have feathers?", o: ["Penguin", "Eagle", "Snail", "Bat"], a: 3, why: "The bat is in the ‘Can fly’ circle only, so it can fly but has no feathers. The penguin has feathers but cannot fly; the eagle has both features.", lvl: 1, fig: { type: "venn", a: "Can fly", b: "Has feathers", onlyA: ["bat", "butterfly"], both: ["pigeon", "eagle"], onlyB: ["penguin", "ostrich"], neither: ["cat", "snail"] } },
    { q: "Which of these is an observation made using the sense of touch?", o: ["The cloth is made of cotton.", "The cloth will dry quickly in the sun.", "The cloth feels rough.", "The cloth is red."], a: 2, why: "‘Feels rough’ is observed by touching. ‘Red’ is observed by sight, while ‘made of cotton’ and ‘will dry quickly’ are inferences or predictions, not direct observations.", lvl: 1 },
    { q: "Study the line graph. By how much did the plant grow from Day 2 to Day 6?", o: ["6 cm", "4 cm", "10 cm", "3 cm"], a: 0, why: "The plant was 4 cm tall on Day 2 and 10 cm tall on Day 6, so it grew 10 − 4 = 6 cm. 10 cm is its height on Day 6, not how much it grew.", lvl: 2, fig: { type: "line", title: "Height of a balsam plant", xl: "Day", yl: "Height of plant (cm)", pts: [["0", 2], ["2", 4], ["4", 7], ["6", 10], ["8", 12], ["10", 13]] } },
    { q: "The diagram shows three set-ups. Which two set-ups should be compared to find out if seeds need water to germinate?", o: ["A and C", "B and C", "A, B and C", "A and B"], a: 3, why: "A and B differ only in whether the cotton wool is moist or dry; everything else is the same. B and C differ only in place (temperature), not water, and A and C differ in both water and place.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["5 green bean seeds", "Dry cotton wool", "Near a window"] }, { label: "B", icon: "dish", lines: ["5 green bean seeds", "Moist cotton wool", "Near a window"] }, { label: "C", icon: "dish", lines: ["5 green bean seeds", "Moist cotton wool", "In a refrigerator"] }] } },
    { q: "Study the classification chart. In which group does an aluminium drink can belong?", o: ["A", "B", "C", "D"], a: 1, why: "Aluminium is a metal but it is NOT attracted by a magnet, so it goes to B. Group A is for magnetic metals such as iron and steel.", lvl: 2, fig: { type: "flow", root: "Objects", node: { q: "Is it made of metal?", yes: { q: "Attracted by a magnet?", yes: "A", no: "B" }, no: { q: "Is it waterproof?", yes: "C", no: "D" } } } },
    { q: "Same-sized pieces of four materials were dipped into water. Study the bar graph. How much MORE water did the sponge absorb than the paper?", o: ["25 ml", "60 ml", "85 ml", "35 ml"], a: 3, why: "Sponge 60 ml − paper 25 ml = 35 ml more. 60 ml is only the sponge’s value, and 85 ml is the two values added.", lvl: 2, fig: { type: "bar", title: "Water absorbed by materials", xl: "Material", yl: "Volume of water absorbed (ml)", bars: [["Towel", 45], ["Paper", 25], ["Plastic", 0], ["Sponge", 60]] } },
    { q: "Siti stroked three identical steel nails with the same bar magnet as shown. She then dipped each nail into a box of pins. What is the variable MEASURED?", o: ["The number of pins picked up by each nail", "The number of times each nail was stroked", "The size of the iron nails", "The type of magnet used"], a: 0, why: "Siti counts the pins each nail picks up; that is the result she measures. The number of strokes is the variable she CHANGES; nail size and magnet are kept the same.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Steel nail", "Same bar magnet", "Stroked 10 times"] }, { label: "B", icon: "plate", lines: ["Steel nail", "Same bar magnet", "Stroked 20 times"] }, { label: "C", icon: "plate", lines: ["Steel nail", "Same bar magnet", "Stroked 30 times"] }] } },
    { q: "Study the line graph of a caterpillar’s length. What was its length on Day 4 most likely to be?", o: ["12 mm", "20 mm", "16 mm", "24 mm"], a: 2, why: "Day 4 is halfway between Day 3 (12 mm) and Day 5 (20 mm), so the length was most likely about 16 mm. 12 mm and 20 mm are the Day 3 and Day 5 values.", lvl: 2, fig: { type: "line", title: "Length of a caterpillar", xl: "Day", yl: "Length (mm)", pts: [["1", 5], ["3", 12], ["5", 20], ["7", 28], ["9", 28]] } },
    { q: "Study the Venn diagram. Which statement is correct?", o: ["Glass is both waterproof and transparent.", "Rubber is both waterproof and transparent.", "Cotton is waterproof but not transparent.", "Aluminium is transparent but not waterproof."], a: 0, why: "Glass is in the overlap, so it has both properties. Rubber and aluminium are waterproof only (not transparent); cotton is outside both circles, so it is neither waterproof nor transparent.", lvl: 2, fig: { type: "venn", a: "Waterproof", b: "Transparent", onlyA: ["rubber", "aluminium"], both: ["glass", "clear plastic"], onlyB: [], neither: ["cotton", "paper"] } },
    { q: "Ali measured how far away a magnet could attract a paper clip. Which reading is written correctly?", o: ["3", "3 cm", "3 ml", "3 g"], a: 1, why: "Distance is a length, so it needs the unit cm. A number without a unit (3) loses marks; ml is for volume and g is for mass.", lvl: 2 },
    { q: "Siti stroked a steel nail with a magnet and counted the pins it could pick up after every 10 strokes. Study the graph. Which statement best describes the trend?", o: ["As the number of strokes increased, the number of pins always increased.", "As the number of strokes increased, the number of pins increased and then stayed the same.", "The number of pins decreased after 40 strokes.", "The number of strokes did not affect the number of pins."], a: 1, why: "The pins increased from 0 to 10 up to 40 strokes, then stayed at 10 from 40 to 50 strokes (flat line). ‘Always increased’ ignores the flat part.", lvl: 3, fig: { type: "line", title: "Pins picked up by a nail", xl: "Number of strokes", yl: "Number of pins", pts: [["0", 0], ["10", 3], ["20", 6], ["30", 9], ["40", 10], ["50", 10]] } },
    { q: "Three identical slices of bread were each kept in a different place. Study the bar graph. Which conclusion is supported by the data?", o: ["Mould appeared soonest on the bread on the kitchen counter.", "Mould cannot grow on bread kept in a refrigerator.", "Bread kept in the cupboard will never grow any mould at all.", "Mould grows best in the dark, such as in a cupboard."], a: 0, why: "The kitchen counter bar is the shortest (4 days), so mould appeared soonest there. Mould DID appear in the refrigerator (after 12 days), and light was not the only thing tested, so the other statements go beyond the data.", lvl: 3, fig: { type: "bar", title: "Time for mould to appear", xl: "Place where bread was kept", yl: "Days before mould appeared", bars: [["Kitchen counter", 4], ["Cupboard", 5], ["Refrigerator", 12]] } },
    { q: "Hana wants to find out if salt stops mould from growing on bread. Set-up X is shown in the diagram. Which set-up is the CONTROL for X?", o: ["B", "C", "A", "B and C"], a: 2, why: "A is the same as X in every way except that it has no salt, so it shows what happens without salt. B also changes the moisture, and C still has salt and changes the place.", lvl: 3, fig: { type: "setups", items: [{ label: "X", icon: "jar", lines: ["Bread with salt", "Moist", "Warm cupboard"] }, { label: "A", icon: "jar", lines: ["Bread, no salt", "Moist", "Warm cupboard"] }, { label: "B", icon: "jar", lines: ["Bread, no salt", "Dry", "Warm cupboard"] }, { label: "C", icon: "jar", lines: ["Bread with salt", "Moist", "Refrigerator"] }] } },
    { q: "Ken wanted to find out if the type of material affects how much water it absorbs. Study his set-ups. Apart from the type of material, which variable was NOT kept the same, making his test unfair?", o: ["Type of material", "Size of material", "Time left in water", "Amount of water"], a: 3, why: "C was given 80 ml of water while A and B had 50 ml. Type of material is the variable he meant to change; size and time are the same in all set-ups.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Cotton cloth", "10 cm x 10 cm", "50 ml of water", "Left for 5 min"] }, { label: "B", icon: "dish", lines: ["Paper", "10 cm x 10 cm", "50 ml of water", "Left for 5 min"] }, { label: "C", icon: "dish", lines: ["Sponge", "10 cm x 10 cm", "80 ml of water", "Left for 5 min"] }] } },
    { q: "A pupil drew this Venn diagram. Which animal has been placed in the WRONG region?", o: ["Bee", "Bat", "Spider", "Snail"], a: 2, why: "A spider has 8 legs, not 6, so it should be outside the ‘Has 6 legs’ circle (in ‘neither’, as it has no wings). A bee has 6 legs and wings, and a bat has wings but no 6 legs.", lvl: 3, fig: { type: "venn", a: "Has 6 legs", b: "Has wings", onlyA: ["ant", "spider"], both: ["butterfly", "bee"], onlyB: ["bat", "sparrow"], neither: ["snail"] } },
    { q: "Study the classification key. Animal R has legs. Which of these could animal R be?", o: ["Spider", "Grasshopper", "Earthworm", "Millipede"], a: 3, why: "R has legs but NOT 6 legs and NOT 8 legs, so it is the millipede (many legs). The grasshopper (6 legs) is P, the spider (8 legs) is Q and the earthworm (no legs) is S.", lvl: 3, fig: { type: "flow", root: "Animals", node: { q: "Does it have legs?", yes: { q: "Has 6 legs?", yes: "P", no: { q: "Has 8 legs?", yes: "Q", no: "R" } }, no: "S" } } },
    { q: "Amir counted the paper clips attracted by the same magnet in three tries. What should he do next?", o: ["Take 25 as his answer since it is the biggest", "Add the three numbers and report 48 paper clips", "Check what went wrong in Try 3 and repeat the experiment", "Conclude that the magnet is getting stronger"], a: 2, why: "Try 3 is very different from Tries 1 and 2, so something probably went wrong. He should check and repeat so that his results are reliable. Adding or picking the biggest number does not fix an odd result.", lvl: 3, tbl: [["Try", "Number of paper clips"], ["1", "12"], ["2", "11"], ["3", "25"]] },
    { q: "Study the graph. Which statement is NOT supported by the data?", o: ["The number of pins decreased as the distance increased.", "The number of pins decreased by the same amount for every 1 cm.", "At 2 cm, the magnet attracted more than twice as many pins as at 4 cm.", "The biggest drop in the number of pins was from 1 cm to 2 cm."], a: 1, why: "The drops were 4, 3, 2 and 1 pins, so they were NOT the same for every 1 cm. At 2 cm there were 8 pins, more than twice the 3 pins at 4 cm, and the biggest drop (4) was from 1 cm to 2 cm.", lvl: 3, fig: { type: "line", title: "Pins attracted at different distances", xl: "Distance from magnet (cm)", yl: "Number of pins", pts: [["1", 12], ["2", 8], ["3", 5], ["4", 3], ["5", 2]] } }
  ],
  tf: [
    { s: "On a line graph, a steeper part of the line shows a faster change.", a: true, why: "Steeper means a bigger change in the same amount of time." },
    { s: "If a bar graph shows that a sponge absorbed the most water, we can conclude that sponge absorbs more water than every material in the world.", a: false, why: "We can only conclude about the materials that were tested." },
    { s: "A flat part of a line graph shows that the value did not change during that time.", a: true, why: "A horizontal line means the value stayed the same." },
    { s: "Writing ‘the stuff’ is an acceptable way to name the variable changed.", a: false, why: "Name the variable in full, e.g. ‘the type of material’." },
    { s: "In a Venn diagram, the things in the overlapping part have both features.", a: true, why: "The overlap belongs to both circles." },
    { s: "A control set-up is always the set-up that has nothing in it.", a: false, why: "A control set-up is the same as the others except that the variable being tested is not changed or not added; it is used for comparison." },
    { s: "In a classification key, each object should end up in only one group.", a: true, why: "Each yes/no question sends the object one way until it reaches one group." },
    { s: "Results that are very different each time the experiment is repeated are reliable.", a: false, why: "Results are reliable when they are similar each time the experiment is repeated." }
  ],
  oe: [
    { q: "Same-sized pieces of four materials were dipped into the same amount of water for 1 minute. Study the bar graph. (a) Which material is the most suitable for making the head of a kitchen mop? (b) Use the data to explain your answer. Use a comparison word. (c) State one variable that must be kept the same for a fair test.", marks: 4, kw: [["sponge"], ["60"], ["more than", "the most", "most water"], ["size", "amount of water", "time"]], model: "(a) Sponge. (b) The sponge absorbed 60 ml of water, which is more than the towel (45 ml), cotton (30 ml) and plastic (0 ml), so it can absorb the most water to dry the floor. (c) The size of each piece of material (or the amount of water, or the time each piece is dipped).", fig: { type: "bar", title: "Water absorbed by materials", xl: "Material", yl: "Volume of water absorbed (ml)", bars: [["Towel", 45], ["Cotton", 30], ["Plastic", 0], ["Sponge", 60]] } },
    { q: "Lina measured the length of a caterpillar every 2 days. Study the line graph. (a) Describe how the length changed from Day 1 to Day 7. (b) The length stayed the same from Day 7 to Day 11. Suggest what had happened to the caterpillar and why its length no longer changed.", marks: 3, kw: [["increase", "got longer", "became longer", "grew longer", "gets longer", "grew"], ["pupa"], ["not eat", "not feed", "does not grow", "doesn’t eat", "doesn’t feed", "stops eating", "stopped eating", "stops feeding", "stopped feeding", "no food"]], model: "(a) The length increased from 5 mm to 28 mm. (b) The caterpillar had most likely become a pupa. A pupa does not eat, so it does not grow any longer.", fig: { type: "line", title: "Length of a caterpillar", xl: "Day", yl: "Length (mm)", pts: [["1", 5], ["3", 12], ["5", 20], ["7", 28], ["9", 28], ["11", 28]] } },
    { q: "Study the three set-ups. (a) Which two set-ups should be compared to find out if seeds need water to germinate? (b) Explain your answer to (a). (c) Mrs Tan says A and C cannot be compared fairly to find out if temperature affects germination. Explain fully why.", marks: 4, kw: [["a and b", "b and a"], ["only the water", "only water", "only the amount of water", "only the moisture", "only difference", "only one variable", "only one thing", "differ only", "water is different", "water is the only"], ["number of seeds", "10 seeds", "5 seeds"], ["two variables", "2 variables", "more than one"]], model: "(a) A and B. (b) Only the amount of water is different; all other variables are kept the same. (c) The number of seeds is different (10 seeds and 5 seeds) as well as the temperature, so two variables were changed and we cannot tell which one caused the result.", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["10 red bean seeds", "Moist cotton wool", "Room temperature"] }, { label: "B", icon: "dish", lines: ["10 red bean seeds", "Dry cotton wool", "Room temperature"] }, { label: "C", icon: "dish", lines: ["5 red bean seeds", "Moist cotton wool", "In a refrigerator"] }] } },
    { q: "Study the classification key. A steel spoon and an aluminium spoon are both metals, but they end up in different groups. Explain why.", marks: 2, kw: [["steel is attracted", "steel spoon is attracted", "magnetic"], ["aluminium is not", "aluminium spoon is not", "non-magnetic", "not magnetic"]], model: "The steel spoon is attracted by a magnet (it is magnetic), so it goes to P. The aluminium spoon is not attracted by a magnet (it is non-magnetic), so it goes to Q.", fig: { type: "flow", root: "Objects", node: { q: "Is it made of metal?", yes: { q: "Attracted by a magnet?", yes: "P", no: "Q" }, no: { q: "Does it float?", yes: "R", no: "S" } } } },
    { q: "Study the Venn diagram. (a) A green turtle lives in the sea and lays eggs. In which part of the diagram should it be placed? (b) Ravi says the whale should be in the overlap because it lives in water like the goldfish. Explain why he is wrong.", marks: 2, kw: [["overlap", "both circles", "in both", "middle", "intersect"], ["give birth", "young alive", "not lay eggs", "doesn’t lay eggs"]], model: "(a) In the overlap, where both circles meet, because it lives in water and lays eggs. (b) A whale does not lay eggs; it gives birth to young alive, so it only belongs in the ‘Lives in water’ circle.", fig: { type: "venn", a: "Lives in water", b: "Lays eggs", onlyA: ["whale", "dolphin"], both: ["goldfish", "guppy"], onlyB: ["chicken", "snake"], neither: ["cat"] } },
    { q: "Ben planted 10 seeds and counted how many had germinated every 2 days. Study the line graph. (a) How many seeds germinated between Day 2 and Day 4? (b) Predict the number of seeds that will have germinated by Day 12 and explain your prediction.", marks: 3, kw: [["5", "five"], ["10", "ten"], ["all", "no more seeds", "already germinated"]], model: "(a) 5 seeds (6 − 1 = 5). (b) 10 seeds. All 10 seeds had already germinated by Day 8, and there are no more seeds left to germinate, so the number will stay at 10.", fig: { type: "line", title: "Seeds germinated", xl: "Day", yl: "Number of seeds germinated", pts: [["0", 0], ["2", 1], ["4", 6], ["6", 9], ["8", 10], ["10", 10]] } },
    { q: "Wei tested one magnet of each shape once. Study the bar graph. He concluded, ‘Horseshoe magnets are always stronger than bar magnets.’ Explain why his conclusion is not acceptable.", marks: 2, kw: [["only one", "only tested one", "once"], ["more magnets", "other magnets", "other horseshoe", "other bar", "many magnets", "more than one magnet", "every horseshoe", "all horseshoe", "not all", "not always", "cannot show", "can't show", "cannot tell", "can't tell", "not enough", "repeat", "more times"]], model: "He tested only one magnet of each shape, and only once. The results only show that this horseshoe magnet attracted more paper clips (14) than this bar magnet (10); they cannot show that every horseshoe magnet is always stronger than every bar magnet.", fig: { type: "bar", title: "Paper clips attracted", xl: "Shape of magnet", yl: "Number of paper clips", bars: [["Bar", 10], ["Horseshoe", 14], ["Ring", 6]] } },
    { q: "Shu Fen saw a potted plant along her HDB corridor. Its leaves were drooping and the soil was dry. (a) Write one observation. (b) Write one inference.", marks: 2, kw: [["droop", "dry soil", "soil is dry", "soil was dry"], ["not watered", "not been watered", "hasn't been watered", "wasn't watered", "did not water", "didn't water", "forgot to water", "lack of water", "needs water", "need water", "no water", "not enough water"]], model: "(a) Observation: the leaves are drooping and the soil is dry. (b) Inference: the plant has not been watered for some time, so it does not have enough water." }
  ],
  doc: [
    { q: "Cloth A absorbed 40 ml of water, Cloth B absorbed 15 ml and Cloth C absorbed 25 ml. Which cloth is the most suitable for making a bath towel? Explain your answer.", marks: 2, answers: ["Cloth A.", "Cloth A, because it absorbed 40 ml of water, which is more than Cloth B (15 ml) and Cloth C (25 ml), so it can dry the body better.", "Cloth A, because it is a good cloth."], best: 1, why: "Answer 2 gives the claim, quotes the data, uses the comparison word ‘more than’ and links it to drying the body. Answer 1 is a claim with no reason. Answer 3 gives a vague reason (‘a good cloth’) with no data and no comparison." },
    { q: "Ali wanted to find out if the type of material affects how much water it absorbs. What is the variable changed?", marks: 1, answers: ["The type of material used.", "The stuff.", "The water."], best: 0, why: "Answer 1 names the variable in full. ‘The stuff’ is too vague to score, and ‘the water’ is wrong: the amount of water is kept the same and the water absorbed is what is measured." },
    { q: "Magnet X attracted 12 paper clips and Magnet Y attracted 7 paper clips. Which magnet is stronger? Explain your answer.", marks: 2, answers: ["Magnet X, because it attracted a lot of paper clips.", "Magnet X is strong.", "Magnet X, because it attracted more paper clips than Magnet Y (12 compared to 7)."], best: 2, why: "Answer 3 uses a comparison (‘more … than Magnet Y’) and quotes the data. Answer 1 says ‘a lot’ without comparing to Y. Answer 2 only repeats the claim with no reason, and ‘strong’ is not a comparison (‘stronger’)." },
    { q: "Mould appeared on bread after 3 days at 30 °C and after 9 days at 10 °C. What can you conclude from the results?", marks: 2, answers: ["Mould likes bread.", "Mould appeared sooner at the higher temperature: after 3 days at 30 °C compared to 9 days at 10 °C.", "Mould grows faster when it is hot because it is hot."], best: 1, why: "Answer 2 links the two variables (temperature and time taken) and refers to the data. Answer 1 does not use the results at all. Answer 3 gives a reason that just repeats itself and quotes no data." },
    { q: "Siti stroked steel nails different numbers of times and dipped each nail into a box of pins. What is the variable measured?", marks: 1, answers: ["The pins.", "How many times she stroked the nails.", "The number of pins picked up by each nail."], best: 2, why: "Answer 3 states exactly what is measured. ‘The pins’ is too vague (what about the pins?). Answer 2 is the variable CHANGED, not measured — the wrong way round." },
    { q: "No water (0 ml) passed through plastic, but 30 ml of water passed through cloth. Which material is more suitable for a cover to keep school books dry in the rain? Explain your answer.", marks: 2, answers: ["Plastic, because no water (0 ml) passed through it while 30 ml passed through the cloth, so plastic is waterproof and will keep the books dry.", "Plastic, because plastic is nice.", "Plastic."], best: 0, why: "Answer 1 gives the claim, the evidence from the data with a comparison, and the reasoning (waterproof, keeps books dry). Answer 2’s reason is not scientific. Answer 3 is a claim with no reason." },
    { q: "Bala used 50 ml of water for the cloth and 80 ml of water for the sponge. Why is his experiment not a fair test?", marks: 2, answers: ["Because it is not fair.", "Because he used different things.", "Because the amount of water was not kept the same, so two variables were changed and he cannot tell which one caused the result."], best: 2, why: "Answer 3 names the variable (the amount of water) and explains why that matters. Answer 1 repeats the question. Answer 2 is too vague: ‘different things’ does not say which variable was not kept the same." },
    { q: "A plant was 9 cm tall on Day 4 and 12 cm tall on Day 6. It grew 3 cm every 2 days. Predict its height on Day 8 and explain your prediction.", marks: 2, answers: ["It will be taller.", "15 cm, because the plant grew 3 cm every 2 days, so 12 cm + 3 cm = 15 cm.", "15."], best: 1, why: "Answer 2 gives a value with a unit and explains it using the pattern in the data. Answer 1 gives no value. Answer 3 has no unit and no reason." }
  ]
};
