window.LB = window.LB || {};
LB["p4-digest"] = {
  notes: [
    { h: "What is digestion?", t: "Digestion is the process of breaking down food into simpler substances that can be absorbed by the body. Food we eat is made of large, complex substances that cannot pass into the blood. After digestion, the simpler substances are absorbed into the bloodstream and carried to all parts of the body. The body uses digested food for energy, growth and repair.", kw: ["breaking down food into simpler substances", "absorbed by the body", "bloodstream"] },
    { h: "The digestive system", t: "The digestive system is made up of the mouth, gullet, stomach, small intestine, large intestine and anus. Food passes through them in this order: mouth → gullet → stomach → small intestine → large intestine → anus. Together these organs digest food, absorb digested food and water, and remove undigested food.", kw: ["digestive system", "in this order"] },
    { h: "Mouth: digestion begins", t: "Digestion begins in the mouth. The teeth chew and break food into smaller pieces, so it is easier to swallow and digestive juices can act on it more easily. Saliva is a digestive juice made in the mouth; it moistens the food and starts to break down food such as starch into simpler substances (sugar).", kw: ["digestion begins in the mouth", "teeth", "saliva", "digestive juice"] },
    { h: "Gullet: carries food only", t: "The gullet is a long muscular tube that joins the mouth to the stomach. It carries food from the mouth to the stomach: the muscles in its wall squeeze the food along. No digestion takes place in the gullet and nothing is absorbed there.", kw: ["carries food", "mouth to the stomach", "no digestion"] },
    { h: "Stomach: churns and digests", t: "The stomach is a muscular, bag-like organ. Its muscular walls churn the food and mix it with digestive juices produced by the stomach. Digestion continues here and the food becomes partly digested. Digested food is not absorbed in the stomach.", kw: ["churn", "digestive juices", "partly digested"] },
    { h: "Small intestine: digestion completed", t: "The small intestine is a long, coiled tube and the longest part of the digestive system. Digestive juices in the small intestine complete the digestion of food. The digested food is then absorbed through the walls of the small intestine into the bloodstream.", kw: ["complete the digestion", "absorbed through the walls", "into the bloodstream"] },
    { h: "Large intestine: water absorbed", t: "The large intestine is wider but shorter than the small intestine. No digestion takes place here. Water is absorbed from the undigested food in the large intestine, so the undigested food becomes more solid.", kw: ["water is absorbed", "undigested food", "no digestion"] },
    { h: "Anus: undigested food leaves", t: "The undigested food that is left is called faeces. It is removed from the body through the anus. No digestion or absorption takes place at the anus.", kw: ["undigested food", "removed from the body", "anus"] },
    { h: "Digestive juices", t: "Digestive juices break down food into simpler substances. They are found in the mouth (saliva), the stomach and the small intestine. The gullet and the large intestine do not produce digestive juices.", kw: ["digestive juices break down food into simpler substances", "mouth", "stomach", "small intestine"] },
    { h: "Digest, absorb or neither?", t: "Digestion takes place in the mouth, stomach and small intestine. Digested food is absorbed in the small intestine, and water is absorbed in the large intestine. The small intestine is the only organ where both digestion and absorption of digested food take place. The gullet and anus neither digest nor absorb; they only let food pass through.", kw: ["mouth, stomach and small intestine", "small intestine", "large intestine", "neither"] },
    { h: "Organs work together as a system", t: "An organ system is a group of organs that work together to carry out a function. The digestive system also works with other systems. For example, digested food absorbed into the blood is carried to all parts of the body by the circulatory system, and muscles help to chew food and move it along the gut.", kw: ["group of organs", "work together", "carried to all parts of the body"] },
    { h: "Saliva and starch experiment", t: "Starch can be tested with iodine solution: iodine turns blue-black when starch is present and stays brown when there is no starch. When starch solution is mixed with saliva and left for some time, iodine stays brown, so the saliva has broken down the starch. A set-up with water instead of saliva stays blue-black; it is the control that shows the change is caused by the saliva. This is also why bread or plain biscuit tastes sweet after chewing for a while.", kw: ["iodine", "blue-black", "saliva has broken down the starch", "control"] }
  ],
  traps: [
    "Digestion starts in the stomach -> Digestion begins in the mouth, where teeth chew food and saliva starts to break it down.",
    "The gullet digests food -> The gullet only carries food from the mouth to the stomach; no digestion takes place there.",
    "Digested food is absorbed in the stomach -> Digestion is only completed in the small intestine, and digested food is absorbed into the bloodstream there.",
    "The large intestine absorbs digested food -> The large intestine absorbs WATER from the undigested food.",
    "Digestion ends in the stomach -> The stomach only partly digests food; digestion is completed in the small intestine.",
    "The small intestine is small, so it is short -> It is narrow but it is the LONGEST part of the digestive system.",
    "Chewing is all the digestion the mouth does -> The mouth also makes saliva, a digestive juice that starts breaking down food such as starch.",
    "‘Food is broken down’ is enough -> Write ‘digestive juices break down food into simpler substances that can be absorbed into the bloodstream’."
  ],
  lessons: [
    {
      h: "Naming organs and their exact functions",
      concept: "Many marks are lost by naming the right organ but giving a vague function. Learn one precise keyword sentence for each organ: mouth – teeth chew, saliva starts digestion; gullet – carries food to the stomach, no digestion; stomach – churns food and mixes it with digestive juices; small intestine – digestion completed, digested food absorbed into the bloodstream; large intestine – water absorbed; anus – undigested food removed.",
      example: {
        q: "The diagram shows the human digestive system. (a) Name part Q. (b) State two things that happen to food in Q.",
        fig: { type: "organs", system: "digestive", mark: { stomach: "Q", gullet: "P", small_intestine: "R" } },
        marks: 3,
        think: [
          "Step 1: Q is the bag-like organ between the gullet (P) and the small intestine (R), so Q is the stomach.",
          "Step 2: Recall the stomach’s job in keyword form: its muscular walls churn the food.",
          "Step 3: The second idea is chemical: the stomach produces digestive juices that break down food into simpler substances.",
          "Step 4: Do NOT write that digested food is absorbed here – that is the small intestine."
        ],
        answer: "(a) Stomach. (b) The muscular walls of the stomach churn the food. The stomach produces digestive juices that break down the food into simpler substances, so the food is partly digested."
      },
      tip: "For every organ, give the ACTION word: chew, carry, churn, complete digestion, absorb digested food, absorb water, remove.",
      try: {
        q: "The diagram shows the human digestive system. Which of the following correctly describes part K?",
        fig: { type: "organs", system: "digestive", mark: { gullet: "K" } },
        o: ["It churns food and mixes it with digestive juices.", "It absorbs water from undigested food.", "It carries food from the mouth to the stomach.", "It completes digestion of food."],
        a: 2,
        why: "K is the gullet, a muscular tube that carries food from the mouth to the stomach. No digestion takes place in it, so options about churning, absorbing or completing digestion describe other organs."
      }
    },
    {
      h: "Digestion vs absorption: which organ does what?",
      concept: "Digestion (breaking down food) happens in the mouth, stomach and small intestine – the organs with digestive juices. Absorption happens in the small intestine (digested food into the bloodstream) and the large intestine (water). Only the small intestine does both. The gullet and anus do neither. Combination-option MCQs test exactly this table.",
      example: {
        q: "Study the diagram. In which labelled part(s) does absorption take place but NOT digestion? Explain.",
        fig: { type: "organs", system: "digestive", mark: { mouth: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } },
        marks: 2,
        think: [
          "Step 1: Mark digestion: A (mouth), B (stomach) and C (small intestine) all have digestive juices.",
          "Step 2: Mark absorption: C absorbs digested food; D absorbs water.",
          "Step 3: The part with absorption but no digestion is D only – the large intestine."
        ],
        answer: "D (the large intestine) only. Water is absorbed from the undigested food in D, but no digestion takes place there because it has no digestive juices."
      },
      tip: "Draw a quick 2-column table (digest? absorb?) in the margin before choosing a combination option.",
      try: {
        q: "Study the diagram. In which labelled parts does digestion take place?",
        fig: { type: "organs", system: "digestive", mark: { mouth: "W", gullet: "X", small_intestine: "Y", large_intestine: "Z" } },
        o: ["X and Z only", "W and Y only", "W, X and Y only", "W, Y and Z only"],
        a: 1,
        why: "Digestion takes place in the mouth (W) and the small intestine (Y), where there are digestive juices. The gullet (X) only carries food and the large intestine (Z) only absorbs water."
      }
    },
    {
      h: "Explaining the saliva–starch experiment",
      concept: "In the classic experiment, starch solution is mixed with saliva in one test tube and with water in another. After some time iodine is added: blue-black means starch is still present; brown means no starch. You must be able to state the conclusion, explain why the water set-up (control) is needed, and name what is kept the same.",
      example: {
        q: "Jun Wei set up test tubes A and B and left them for 20 minutes. He then added iodine solution. A stayed brown and B turned blue-black. (a) What can he conclude? (b) Why did he need test tube B?",
        fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["5 mL starch solution", "2 mL saliva", "Left for 20 min"] }, { label: "B", icon: "beaker", lines: ["5 mL starch solution", "2 mL water", "Left for 20 min"] }] },
        marks: 2,
        think: [
          "Step 1: Read the result: brown in A means there is no starch left; blue-black in B means starch is still there.",
          "Step 2: The only difference between A and B is saliva vs water, so the saliva caused the starch to disappear.",
          "Step 3: B is the control: it shows that the starch is NOT broken down by water or by just being left, so the change in A is due to the saliva."
        ],
        answer: "(a) Saliva breaks down starch (into simpler substances). (b) B is a control to show that the starch was broken down because of the saliva and not by water or by being left for 20 minutes."
      },
      tip: "Always link the colour to starch: ‘stayed brown, so no starch was present’ – never just ‘it stayed brown’.",
      try: {
        q: "Iodine solution was added to test tubes A and B after 20 minutes. Which result is expected?",
        fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Starch solution", "Saliva", "Left for 20 min"] }, { label: "B", icon: "beaker", lines: ["Starch solution", "Water", "Left for 20 min"] }] },
        o: ["A: blue-black; B: brown", "A: brown; B: brown", "A: blue-black; B: blue-black", "A: brown; B: blue-black"],
        a: 3,
        why: "Saliva breaks down the starch in A, so no starch is left and iodine stays brown. Water does not break down starch, so B still has starch and turns blue-black."
      }
    },
    {
      h: "Using the full keyword sentence",
      concept: "Markers look for ‘digestive juices break down food into simpler substances’ and ‘digested food is absorbed into the bloodstream’. Answers such as ‘food is broken down’, ‘food goes to the body’ or ‘the stomach helps digestion’ usually lose the mark. Say WHAT does the breaking down (digestive juices), WHAT it becomes (simpler substances) and WHERE it goes (bloodstream).",
      example: {
        q: "Explain why food must be digested before the body can use it.",
        marks: 2,
        think: [
          "Step 1: Say what digestion does: digestive juices break down food into simpler substances.",
          "Step 2: Link to absorption: only simpler substances can be absorbed through the wall of the small intestine into the bloodstream.",
          "Step 3: Link to use: the blood carries the digested food to all parts of the body."
        ],
        answer: "Food must be broken down by digestive juices into simpler substances so that it can be absorbed into the bloodstream in the small intestine and carried to all parts of the body."
      },
      tip: "Check your answer for the three W’s: What breaks it down, What it becomes, Where it goes.",
      try: {
        q: "Which answer would score full marks for ‘State the function of the small intestine’?",
        o: ["It helps us to digest the food that we eat so our body can use it.", "Digestion is completed there and digested food is absorbed into the bloodstream.", "It absorbs water from undigested food and passes the waste to the anus.", "Food passes through it on its way from the stomach to the large intestine."],
        a: 1,
        why: "Only this answer gives both key ideas: digestion is completed and digested food is absorbed into the bloodstream. ‘Helps us digest’ is vague, water absorption is the large intestine’s main job, and passing food along is not a function."
      }
    },
    {
      h: "Predicting what happens when an organ does not work well",
      concept: "Reasoning questions describe a problem (surgery, illness, an unusual result) and ask for the effect. Use each organ’s function: if the small intestine absorbs less, less digested food reaches the blood and the person may lose weight; if the large intestine absorbs less water, the faeces become watery; if there is no saliva, food is harder to swallow but can still be digested later in the stomach and small intestine.",
      example: {
        q: "After an illness, Mr Tan’s large intestine could not work properly. His faeces became very watery. Explain why.",
        marks: 2,
        think: [
          "Step 1: Identify the normal function of the large intestine: water is absorbed from the undigested food.",
          "Step 2: If it does not work properly, less water is absorbed.",
          "Step 3: So more water stays in the undigested food, which leaves the body through the anus as watery faeces."
        ],
        answer: "The large intestine absorbs water from undigested food. Since it was not working properly, less water was absorbed, so more water remained in the undigested food and the faeces were watery."
      },
      tip: "State the organ’s normal function first, then say what ‘less’ of it causes.",
      try: {
        q: "Part of a patient’s small intestine was removed in an operation. Which is the most likely effect?",
        o: ["Less digested food is absorbed into her bloodstream.", "She can no longer swallow food down her gullet.", "Her stomach can no longer churn food properly.", "Her faeces will contain much less water than before."],
        a: 0,
        why: "Digested food is absorbed through the walls of the small intestine, so a shorter small intestine absorbs less digested food. Swallowing and churning happen in other organs, and water in faeces depends mainly on the large intestine."
      }
    }
  ],
  mcq: [
    { q: "What is digestion?", o: ["The process of breaking down food into simpler substances that the body can absorb", "The process of moving food along the gut from the mouth all the way to the anus", "The process of removing undigested food from the body through the anus as faeces", "The process of taking in food and drink through the mouth before it is swallowed"], a: 0, why: "Digestion is breaking down food into simpler substances that can be absorbed. Moving food along, taking it in and removing waste are not digestion itself.", lvl: 1 },
    { q: "In which order does food pass through the digestive system?", o: ["Mouth → stomach → gullet → small intestine → large intestine → anus", "Mouth → gullet → stomach → large intestine → small intestine → anus", "Mouth → gullet → stomach → small intestine → large intestine → anus", "Mouth → gullet → small intestine → stomach → large intestine → anus"], a: 2, why: "Food goes from the mouth down the gullet to the stomach, then the small intestine, the large intestine and out through the anus. The small intestine comes BEFORE the large intestine.", lvl: 1 },
    { q: "The diagram shows the human digestive system. What is part X?", fig: { type: "organs", system: "digestive", mark: { gullet: "X" } }, o: ["Stomach", "Gullet", "Windpipe", "Small intestine"], a: 1, why: "X is the tube joining the mouth to the stomach – the gullet. The windpipe carries air to the lungs and is not part of the digestive system.", lvl: 1 },
    { q: "The diagram shows the human digestive system. In which labelled part is digested food absorbed into the bloodstream?", fig: { type: "organs", system: "digestive", mark: { gullet: "A", stomach: "B", large_intestine: "C", small_intestine: "D" } }, o: ["A", "B", "C", "D"], a: 3, why: "D is the small intestine; digested food is absorbed through its walls into the bloodstream. C, the large intestine, absorbs water, not digested food.", lvl: 1 },
    { q: "The diagram shows the human digestive system. Which labelled part absorbs water from undigested food?", fig: { type: "organs", system: "digestive", mark: { large_intestine: "A", stomach: "B", small_intestine: "C", gullet: "D" } }, o: ["A", "B", "C", "D"], a: 0, why: "A is the large intestine, where water is absorbed from undigested food, making it more solid before it leaves through the anus.", lvl: 1 },
    { q: "The digestive juice produced in the mouth is called", o: ["blood", "sweat", "saliva", "iodine"], a: 2, why: "Saliva is the digestive juice in the mouth. It moistens food and starts to break it down.", lvl: 1 },
    { q: "The diagram shows the human digestive system. Name part K.", fig: { type: "organs", system: "digestive", mark: { stomach: "K" } }, o: ["Small intestine", "Large intestine", "Stomach", "Gullet"], a: 2, why: "K is the stomach, the muscular bag-like organ between the gullet and the small intestine. Its walls churn food and mix it with digestive juices.", lvl: 1 },
    { q: "Through which part does undigested food leave the body?", o: ["Mouth", "Anus", "Large intestine", "Small intestine"], a: 1, why: "Undigested food (faeces) is removed from the body through the anus. The large intestine absorbs water from it first.", lvl: 1 },

    { q: "The diagram shows the human digestive system. In which labelled parts does digestion take place?", fig: { type: "organs", system: "digestive", mark: { mouth: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } }, o: ["A and B only", "B and C only", "A, B and C only", "A, B, C and D"], a: 2, why: "Digestion takes place in the mouth (A), stomach (B) and small intestine (C), where digestive juices are present. The large intestine (D) only absorbs water.", lvl: 2 },
    { q: "Which organ has no digestion AND no absorption taking place in it?", o: ["Gullet", "Stomach", "Small intestine", "Large intestine"], a: 0, why: "The gullet only carries food from the mouth to the stomach. The stomach digests, the small intestine digests and absorbs, and the large intestine absorbs water.", lvl: 2 },
    { q: "Why is it important to chew food well before swallowing?", o: ["Chewing breaks food into smaller pieces so it is easier to swallow and for digestive juices to act on.", "Chewing lets digested food be absorbed into the blood through the lining of the mouth.", "Chewing removes water from the food so that it becomes dry and easier to push down the gullet.", "Chewing completes the digestion of food, so the stomach and small intestine have less work to do."], a: 0, why: "Teeth break food into smaller pieces, making swallowing easier and helping digestive juices work. Chewing does not remove water – saliva moistens the food. Absorption and complete digestion happen in the small intestine.", lvl: 2 },
    { q: "What happens to digested food after it is absorbed in the small intestine?", o: ["It goes into the large intestine to be digested again.", "It is carried by the blood to all parts of the body.", "It leaves the body through the anus.", "It goes back to the stomach."], a: 1, why: "Digested food is absorbed into the bloodstream and carried to all parts of the body. Only undigested food moves on to the large intestine and anus.", lvl: 2 },
    { q: "Which statement about the stomach is NOT true?", o: ["Its muscular walls churn and mix the food with digestive juices.", "It produces digestive juices that break down food.", "Food is partly digested in it before moving to the small intestine.", "Digested food is absorbed into the blood through its walls."], a: 3, why: "Digested food is absorbed in the small intestine, not the stomach. The other three statements correctly describe the stomach.", lvl: 2 },
    { q: "The diagram shows the human digestive system. Which correctly describes parts M and N?", fig: { type: "organs", system: "digestive", mark: { small_intestine: "M", large_intestine: "N" } }, tbl: [["Option", "M", "N"], ["1", "Absorbs water", "Completes digestion"], ["2", "Completes digestion and absorbs digested food", "Absorbs water"], ["3", "Churns food", "Absorbs digested food"], ["4", "Carries food only", "Removes undigested food"]], o: ["1", "2", "3", "4"], a: 1, why: "M is the small intestine, where digestion is completed and digested food is absorbed. N is the large intestine, where water is absorbed.", lvl: 2 },
    { q: "In which of the following organs are digestive juices found?", o: ["Mouth and stomach only", "Stomach and small intestine only", "Mouth, gullet and stomach only", "Mouth, stomach and small intestine only"], a: 3, why: "Digestive juices are found in the mouth (saliva), the stomach and the small intestine. The gullet produces no digestive juice.", lvl: 2 },
    { q: "Which of the following best describes an organ system?", o: ["A group of organs working together to carry out a function", "A single organ that does many different jobs in the body", "All the food that the body digests and absorbs in a day", "A long tube that food passes through from mouth to anus"], a: 0, why: "An organ system is a group of organs that work together to carry out a function, such as the digestive system digesting food.", lvl: 2 },
    { q: "Nurul chewed a piece of plain bread for three minutes without swallowing. It began to taste sweet. Why?", o: ["Saliva broke down the starch in the bread into sugar.", "The teeth turned the bread into sugar.", "The bread absorbed water from the mouth.", "The bread was digested completely in the mouth."], a: 0, why: "Saliva is a digestive juice that breaks down starch into sugar, a simpler substance, so the bread tastes sweeter. Teeth only break food into smaller pieces, and digestion is only completed in the small intestine.", lvl: 2 },
    { q: "Why must food be digested before it can be used by the body?", o: ["Only simpler substances can be absorbed into the bloodstream.", "Undigested food is too heavy to reach the stomach.", "Digestion adds water to the food.", "Digestion makes food move faster through the gullet."], a: 0, why: "Food must be broken down into simpler substances before it can be absorbed through the walls of the small intestine into the bloodstream.", lvl: 2 },
    { q: "The diagram shows the human digestive system. Which statement about part G is correct?", fig: { type: "organs", system: "digestive", mark: { gullet: "G", stomach: "H" } }, o: ["G carries food to H and no digestion takes place in G.", "G produces saliva to start the digestion of food.", "G absorbs digested food into the bloodstream.", "G churns food and mixes it with digestive juices."], a: 0, why: "G is the gullet, which carries food to the stomach (H). No digestion or absorption happens in the gullet.", lvl: 2 },
    { q: "Digested food is absorbed into the blood in the small intestine. Which body system then carries it to all parts of the body?", o: ["Skeletal system", "Muscular system", "Circulatory system", "Digestive system"], a: 2, why: "Blood flows through the circulatory system, which carries digested food to all parts of the body. This shows organ systems working together.", lvl: 2 },
    { q: "The graph shows how long a meal stays in some organs of an adult. About how long does the meal take from entering the stomach to leaving the small intestine?", fig: { type: "bar", title: "Time food stays in each organ", xl: "Organ", yl: "Time (hours)", bars: [["Stomach", 3], ["Small intestine", 5], ["Large intestine", 20]] }, o: ["3 hours", "5 hours", "20 hours", "8 hours"], a: 3, why: "The meal stays about 3 hours in the stomach and 5 hours in the small intestine: 3 + 5 = 8 hours.", lvl: 2 },
    { q: "The diagram shows the human digestive system. In which labelled part is digestion COMPLETED?", fig: { type: "organs", system: "digestive", mark: { stomach: "P", small_intestine: "Q", large_intestine: "R", anus: "S" } }, o: ["P", "Q", "R", "S"], a: 1, why: "Q is the small intestine, where digestive juices complete digestion. The stomach (P) only partly digests food.", lvl: 2 },

    { q: "Study the diagram. In which labelled parts is a substance absorbed into the body?", fig: { type: "organs", system: "digestive", mark: { gullet: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } }, o: ["C only", "B and C only", "C and D only", "B, C and D only"], a: 2, why: "Digested food is absorbed in the small intestine (C) and water is absorbed in the large intestine (D). The gullet (A) and stomach (B) do not absorb.", lvl: 3 },
    { q: "Mei Ling set up test tubes A and B and left them for 20 minutes. Iodine turns blue-black when starch is present. After adding iodine, A stayed brown and B turned blue-black. What can she conclude?", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Starch solution", "Saliva", "Left for 20 min"] }, { label: "B", icon: "beaker", lines: ["Starch solution", "Water", "Left for 20 min"] }] }, o: ["Water breaks down starch.", "Saliva contains starch.", "Saliva breaks down starch.", "Starch breaks down on its own after 20 minutes."], a: 2, why: "Brown in A shows no starch was left; blue-black in B shows starch remained. The only difference is saliva, so saliva broke down the starch. B rules out water and time alone.", lvl: 3 },
    { q: "Read the statements. P: Digestion begins in the mouth. Q: The gullet produces a digestive juice. R: Digestion is completed in the small intestine. S: The large intestine digests the remaining food. Which statements are correct?", o: ["P and Q only", "P and R only", "Q and S only", "P, R and S only"], a: 1, why: "Digestion begins in the mouth (P) and is completed in the small intestine (R). The gullet has no digestive juice and the large intestine does not digest food; it absorbs water.", lvl: 3 },
    { q: "Mrs Lim had a large part of her small intestine removed. Which is most likely to happen?", o: ["She will not be able to swallow her food properly.", "Food will not be churned with digestive juices.", "She will not be able to produce saliva in her mouth.", "Less digested food will be absorbed into her bloodstream."], a: 3, why: "Digested food is absorbed through the walls of the small intestine. With less small intestine, less digested food can be absorbed. Swallowing, churning and saliva involve other organs.", lvl: 3 },
    { q: "Ahmad has watery faeces. Which organ is most likely not doing its job well?", o: ["Large intestine, because it is not absorbing enough water", "Stomach, because it is not churning the food enough", "Gullet, because it is not carrying food to the stomach", "Mouth, because the teeth are not chewing food well"], a: 0, why: "The large intestine absorbs water from undigested food. If it absorbs too little, more water stays in the faeces.", lvl: 3 },
    { q: "Starch solution was mixed with saliva. Every 2 minutes a drop was tested to find the amount of starch left. Study the graph. Which statement is supported by the graph?", fig: { type: "line", xl: "Time (min)", yl: "Amount of starch left (units)", pts: [["0", 10], ["2", 7], ["4", 4], ["6", 2], ["8", 0], ["10", 0]] }, o: ["The amount of starch increased as saliva was added.", "All the starch had been broken down by the 8th minute.", "The saliva stopped working after 2 minutes.", "Half the starch was left at 8 minutes."], a: 1, why: "The starch left falls steadily and reaches 0 at 8 minutes, so saliva had broken it all down by then. It kept falling after 2 minutes, so saliva did not stop working.", lvl: 3 },
    { q: "The diagram shows the human digestive system. Food still reaches the stomach through part P even when an astronaut is floating upside down in space. Why?", fig: { type: "organs", system: "digestive", mark: { gullet: "P", stomach: "Q" } }, o: ["Food falls down P to Q because it is heavier than air.", "The muscles in the wall of P squeeze the food along to Q.", "Digestive juices in P push the food along towards Q.", "Q sucks the food in from P like a drink through a straw."], a: 1, why: "P is the gullet. Muscles in its wall squeeze the food along towards the stomach (Q), so food moves even without help from gravity. The gullet has no digestive juices.", lvl: 3 },
    { q: "The table gives information about two organs, X and Y, of the digestive system. What are X and Y?", tbl: [["Organ", "Digestion takes place?", "Digested food absorbed?", "Main organ where water is absorbed?"], ["X", "Yes", "Yes", "No"], ["Y", "No", "No", "Yes"]], o: ["X: stomach; Y: large intestine", "X: small intestine; Y: gullet", "X: small intestine; Y: large intestine", "X: large intestine; Y: small intestine"], a: 2, why: "Only the small intestine both digests and absorbs digested food (X). The large intestine does not digest but is the main organ where water is absorbed (Y).", lvl: 3 },
    { q: "Why is it useful that the small intestine is very long?", o: ["It gives more time for water to be removed from the undigested food.", "It lets food be churned for longer so that it is broken into smaller pieces.", "It stores undigested food until the body is ready to remove it.", "It allows more time to complete digestion and absorb digested food."], a: 3, why: "A long small intestine lets digestion be completed and more digested food be absorbed into the bloodstream. Removing water is the large intestine’s job, churning is the stomach’s, and undigested food is stored at the end of the large intestine.", lvl: 3 },
    { q: "Which of the following is NOT a function of saliva?", o: ["It moistens food.", "It makes food easier to swallow.", "It starts to break down food into simpler substances.", "It absorbs digested food into the blood."], a: 3, why: "Absorption of digested food happens in the small intestine. Saliva moistens food, eases swallowing and starts digestion.", lvl: 3 },
    { q: "Study the diagram. In which labelled parts is food chewed or churned?", fig: { type: "organs", system: "digestive", mark: { mouth: "A", stomach: "B", large_intestine: "C" } }, o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "The teeth in the mouth (A) chew food and the muscular stomach (B) churns it. The large intestine (C) absorbs water and does not chew or churn food.", lvl: 3 },
    { q: "Kumar sorted organs into a Venn diagram. One organ has been placed wrongly. Which one?", fig: { type: "venn", a: "Digestion takes place", b: "Absorption takes place", onlyA: ["mouth", "gullet", "stomach"], both: ["small intestine"], onlyB: ["large intestine"], neither: ["anus"] }, o: ["Mouth", "Small intestine", "Large intestine", "Gullet"], a: 3, why: "No digestion takes place in the gullet – it only carries food – so it belongs in ‘neither’ with the anus. All the other organs are placed correctly.", lvl: 3 },

    { q: "Four set-ups were left for different times, then iodine was added (blue-black = starch present, brown = no starch). Results: A brown, B blue-black, C blue-black, D brown. Which conclusion is supported by ALL the results?", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Starch solution", "Saliva", "Left for 20 min"] }, { label: "B", icon: "beaker", lines: ["Starch solution", "Water", "Left for 20 min"] }, { label: "C", icon: "beaker", lines: ["Starch solution", "Saliva", "Left for 1 min"] }, { label: "D", icon: "beaker", lines: ["Water", "Saliva", "Left for 20 min"] }] }, o: ["Water breaks down starch if it is left long enough.", "Saliva contains starch.", "Saliva breaks down starch, but it needs time to do so.", "Saliva breaks down starch immediately."], a: 2, why: "A vs B shows saliva, not water, removes the starch. A vs C shows that 1 minute was not enough time, so saliva needs time. D (brown) shows saliva itself contains no starch.", lvl: 4 },
    { q: "A tiny camera capsule was swallowed. Its four photos were: 1 – food being churned with digestive juices; 2 – a narrow tube squeezing food along with no digestive juices; 3 – undigested food becoming drier and more solid; 4 – digestion being completed as digested food passes into the blood. In which order were the photos taken?", o: ["1, 2, 4, 3", "2, 1, 3, 4", "2, 4, 1, 3", "2, 1, 4, 3"], a: 3, why: "Photo 2 is the gullet, 1 is the stomach, 4 is the small intestine and 3 is the large intestine, where water is absorbed. Food passes gullet → stomach → small intestine → large intestine.", lvl: 4 },
    { q: "Patient P eats well but has very watery faeces. Patient Q eats well but keeps losing weight, and food is digested normally. Which is the most likely explanation?", tbl: [["Option", "Patient P", "Patient Q"], ["1", "Stomach does not churn food", "Large intestine absorbs too little water"], ["2", "Large intestine absorbs too little water", "Small intestine absorbs too little digested food"], ["3", "Small intestine absorbs too little digested food", "Gullet does not carry food"], ["4", "Gullet does not carry food", "Mouth produces too little saliva"]], o: ["1", "2", "3", "4"], a: 1, why: "Watery faeces point to too little water being absorbed in the large intestine. Food is digested normally but Q loses weight, so too little digested food is reaching the blood – the small intestine’s absorption is the problem.", lvl: 4 },
    { q: "Hui Ling mixed the same amount of starch solution with different volumes of saliva and timed how long until iodine no longer turned blue-black. Which statement is supported by the results?", tbl: [["Volume of saliva (mL)", "Time until no starch was left (min)"], ["1", "12"], ["2", "6"], ["3", "4"]], o: ["With more saliva, the starch was broken down in a shorter time.", "With 1 mL of saliva, the starch was never broken down.", "Saliva breaks down starch only when there is more than 2 mL of it.", "The volume of saliva does not affect how fast starch is broken down."], a: 0, why: "As the volume of saliva increased from 1 to 3 mL, the time needed fell from 12 to 4 minutes. All three volumes broke down the starch in the end, so the other options contradict the table.", lvl: 4 },
    { q: "Some people cannot produce saliva. Which is most likely true for such a person?", o: ["None of the food eaten can be digested, because digestion must begin in the mouth.", "Digested food cannot be absorbed into the blood, because saliva carries it there.", "Food is harder to swallow but can still be digested in the stomach and small intestine.", "The large intestine will digest the food instead, because the mouth cannot start it."], a: 2, why: "Saliva moistens food and starts digestion, so food is harder to swallow. The stomach and small intestine still have digestive juices, so digestion can still be completed. The large intestine never digests food.", lvl: 4 },
    { q: "Which statements are true? W: Every organ that food passes through digests the food. X: An organ can absorb a substance without digesting food. Y: Digestion is completed before food reaches the large intestine. Z: The gullet and the anus are parts of the digestive system even though neither digests nor absorbs.", o: ["W and X only", "X and Y only", "W, Y and Z only", "X, Y and Z only"], a: 3, why: "X is true (the large intestine absorbs water without digesting), Y is true (digestion is completed in the small intestine) and Z is true (both are organs that food passes through). W is false because the gullet, large intestine and anus do not digest.", lvl: 4 }
  ],
  tf: [
    { s: "Digestion begins in the stomach.", a: false, why: "Digestion begins in the mouth, where teeth chew food and saliva starts to break it down." },
    { s: "Saliva is a digestive juice.", a: true, why: "Saliva starts to break down food such as starch into simpler substances." },
    { s: "The gullet produces digestive juices that digest food.", a: false, why: "The gullet only carries food from the mouth to the stomach; no digestion takes place there." },
    { s: "The muscular walls of the stomach churn food and mix it with digestive juices.", a: true, why: "Churning mixes the food with the stomach’s digestive juices so that digestion continues." },
    { s: "Digested food is absorbed into the bloodstream through the walls of the stomach.", a: false, why: "Digested food is absorbed through the walls of the small intestine." },
    { s: "Digestion is completed in the small intestine.", a: true, why: "Digestive juices in the small intestine complete the digestion of food." },
    { s: "The large intestine absorbs digested food.", a: false, why: "The large intestine absorbs water from undigested food; digested food is absorbed in the small intestine." },
    { s: "The small intestine is longer than the large intestine.", a: true, why: "The small intestine is narrower but much longer; it is the longest part of the digestive system." },
    { s: "Undigested food leaves the body through the anus.", a: true, why: "After water is absorbed in the large intestine, the undigested food is removed through the anus." },
    { s: "Food passes through the large intestine before the small intestine.", a: false, why: "The order is stomach → small intestine → large intestine → anus." },
    { s: "Digestion breaks down food into simpler substances that can be absorbed by the body.", a: true, why: "This is the meaning of digestion." },
    { s: "Chewing food completes its digestion.", a: false, why: "Chewing only breaks food into smaller pieces; digestion is completed in the small intestine." },
    { s: "The small intestine is the only organ where both digestion and absorption of digested food take place.", a: true, why: "The mouth and stomach digest but do not absorb; the large intestine absorbs water but does not digest." },
    { s: "Digestive juices are produced in the mouth, stomach and large intestine.", a: false, why: "Digestive juices are found in the mouth, stomach and small intestine, not the large intestine." },
    { s: "The blood carries digested food to all parts of the body.", a: true, why: "Digested food absorbed in the small intestine enters the bloodstream and is carried around the body." },
    { s: "Food is completely digested in the stomach.", a: false, why: "Food is only partly digested in the stomach; digestion is completed in the small intestine." },
    { s: "An organ system is a group of organs working together to carry out a function.", a: true, why: "For example, the digestive system’s organs work together to digest food and absorb digested food." },
    { s: "If iodine solution stays brown when added to a mixture, starch is present.", a: false, why: "Iodine turns blue-black when starch is present; staying brown means no starch." },
    { s: "Water is absorbed from undigested food in the large intestine.", a: true, why: "This makes the undigested food more solid before it leaves the body." },
    { s: "The anus is not part of the digestive system because no digestion takes place there.", a: false, why: "The anus is part of the digestive system; it removes undigested food even though it does not digest." }
  ],
  sort: [
    { title: "Is it part of the human digestive system?", groups: ["Part of the digestive system", "Not part of the digestive system"], items: [["mouth", 0], ["gullet", 0], ["stomach", 0], ["small intestine", 0], ["large intestine", 0], ["anus", 0], ["windpipe", 1], ["lungs", 1], ["heart", 1], ["nose", 1]] },
    { title: "Which organ does this job?", groups: ["Mouth", "Stomach", "Small intestine", "Large intestine"], items: [["teeth chew food into smaller pieces", 0], ["saliva starts digestion", 0], ["muscular walls churn food", 1], ["food is partly digested", 1], ["digestion is completed", 2], ["digested food is absorbed into the bloodstream", 2], ["water is absorbed from undigested food", 3], ["undigested food becomes more solid", 3]] },
    { title: "Digestion, absorption, both or neither?", groups: ["Digestion only", "Absorption only", "Both digestion and absorption", "Neither"], items: [["mouth", 0], ["stomach", 0], ["organ where teeth chew food", 0], ["large intestine", 1], ["small intestine", 2], ["organ where digestion is completed", 2], ["gullet", 3], ["anus", 3], ["tube that squeezes food down to the stomach", 3]] }
  ],
  oe: [
    { q: "What is digestion?", marks: 2, kw: [["break down food", "breaks down food", "breaking down food", "broken down"], ["simpler substance", "simple substance", "absorbed"]], model: "Digestion is the process of breaking down food into simpler substances that can be absorbed by the body." },
    { q: "Explain why no digestion takes place in the gullet.", marks: 1, kw: [["no digestive juice", "does not produce digestive juice", "does not have digestive juice", "not have any digestive juice", "only carries food", "only carry food"]], model: "The gullet has no digestive juices; it only carries food from the mouth to the stomach." },
    { q: "Study the diagram of the human digestive system. (a) Name part B. (b) State one function of part B. (c) Name the organ where water is absorbed from undigested food.", fig: { type: "organs", system: "digestive", mark: { mouth: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } }, marks: 3, kw: [["stomach"], ["churn", "digestive juice"], ["large intestine"]], model: "(a) Stomach. (b) Its muscular walls churn the food and mix it with digestive juices that break down the food into simpler substances. (c) The large intestine (D)." },
    { q: "Study the diagram. (a) Name part R. (b) Describe TWO things that happen to food in R. (c) Where does the digested food go after leaving R?", fig: { type: "organs", system: "digestive", mark: { stomach: "Q", small_intestine: "R", large_intestine: "S" } }, marks: 4, kw: [["small intestine"], ["digestion is completed", "completes digestion", "complete the digestion", "completes the digestion", "digestion completed"], ["absorbed", "absorb"], ["blood", "all parts of the body"]], model: "(a) Small intestine. (b) Digestive juices complete the digestion of food into simpler substances. The digested food is absorbed through the walls of R. (c) It goes into the bloodstream and is carried to all parts of the body." },
    { q: "Siti chewed a plain cracker for three minutes without swallowing. (a) How would the taste change? (b) Explain why. (c) Besides saliva, what else in the mouth helps to digest the cracker, and how?", marks: 3, kw: [["sweet"], ["saliva", "digestive juice"], ["teeth", "chew"]], model: "(a) It would taste sweet (sweeter). (b) Saliva is a digestive juice that breaks down the starch in the cracker into sugar, a simpler substance. (c) The teeth chew the cracker and break it into smaller pieces so that saliva can act on it more easily." },
    { q: "Wei Jie set up two test tubes and left them for 20 minutes before adding iodine solution. Iodine turns blue-black when starch is present. (a) Predict the colour in each test tube. (b) What conclusion can he make? (c) Why was test tube Y needed?", fig: { type: "setups", items: [{ label: "X", icon: "beaker", lines: ["5 mL starch solution", "2 mL saliva", "Left for 20 min"] }, { label: "Y", icon: "beaker", lines: ["5 mL starch solution", "2 mL water", "Left for 20 min"] }] }, marks: 4, kw: [["brown"], ["blue-black", "blue black", "dark blue"], ["saliva breaks down starch", "saliva broke down the starch", "saliva has broken down", "saliva digests starch", "saliva digested"], ["control", "due to the saliva", "because of the saliva", "caused by the saliva", "not by water", "not the water"]], model: "(a) X stays brown; Y turns blue-black. (b) Saliva breaks down starch (into simpler substances). (c) Y is a control to show that the starch was broken down because of the saliva and not by water or by being left for 20 minutes." },
    { q: "In the experiment in the diagram, state two variables that must be kept the same in both test tubes to make it a fair test.", fig: { type: "setups", items: [{ label: "X", icon: "beaker", lines: ["5 mL starch solution", "2 mL saliva", "Left for 20 min"] }, { label: "Y", icon: "beaker", lines: ["5 mL starch solution", "2 mL water", "Left for 20 min"] }] }, marks: 2, kw: [["amount of starch", "volume of starch", "starch solution"], ["time", "20 min", "amount of liquid", "2 ml", "temperature"]], model: "The amount of starch solution (5 mL) and the time left (20 minutes) must be kept the same. The amount of liquid added (2 mL) and the temperature should also be the same." },
    { q: "Mr Ong’s large intestine did not work properly after an illness. (a) State the normal function of the large intestine. (b) Explain how this would affect his faeces.", marks: 3, kw: [["absorb water", "absorbs water", "water is absorbed"], ["less water", "not enough water", "less of the water"], ["watery", "more water", "soft", "runny"]], model: "(a) The large intestine absorbs water from undigested food. (b) Less water would be absorbed, so more water stays in the undigested food and his faeces would be watery." },
    { q: "Study the diagram. (a) Which labelled part(s) digest food but do NOT absorb? (b) Which labelled part(s) neither digest nor absorb? (c) Which labelled part both digests and absorbs? Name the organs.", fig: { type: "organs", system: "digestive", mark: { mouth: "J", gullet: "K", stomach: "L", small_intestine: "M", large_intestine: "N" } }, marks: 3, kw: [["mouth and stomach", "stomach and mouth", "j and l", "l and j"], ["gullet"], ["small intestine"]], model: "(a) The mouth and stomach (J and L). (b) The gullet (K). (c) The small intestine (M)." },
    { q: "Part T in the diagram is very long. Explain why this is useful.", fig: { type: "organs", system: "digestive", mark: { small_intestine: "T" } }, marks: 2, kw: [["complete"], ["absorb"]], model: "A long small intestine gives more time for digestive juices to complete the digestion of food, and more time and space for digested food to be absorbed into the bloodstream, so more digested food is absorbed." },
    { q: "The digestive system works with other systems in the body. (a) What is an organ system? (b) Describe how the digestive system and the blood work together so that the muscles in your legs can use the food you eat.", marks: 3, kw: [["group of organs"], ["absorbed", "absorb"], ["carried", "carries", "transport"]], model: "(a) An organ system is a group of organs that work together to carry out a function. (b) The digestive system breaks down food into simpler substances, and the digested food is absorbed into the blood in the small intestine. The blood then carries the digested food to all parts of the body, including the leg muscles." },
    { q: "Some people cannot produce saliva. (a) State one way their eating would be affected. (b) Explain why their food can still be digested.", marks: 2, x: 1, kw: [["swallow", "dry", "moist"], ["stomach", "small intestine"]], model: "(a) Food would be dry and harder to swallow. (b) The stomach and small intestine still produce digestive juices, so food can still be broken down into simpler substances and digestion completed in the small intestine." },
    { q: "A camera capsule was swallowed and took photos inside the digestive system. Photo 1: a narrow tube squeezing food, with no digestive juices. Photo 2: undigested food becoming drier. Photo 3: food being churned with digestive juices. Photo 4: digested food passing through the walls into the blood. (a) Arrange the photos in the order they were taken. (b) Name the organ in Photo 2 and explain why the food becomes drier. (c) Why was no digestion seen in Photo 1?", marks: 4, x: 1, kw: [["1, 3, 4, 2", "1 3 4 2", "1,3,4,2", "1-3-4-2", "1342", "1 then 3", "1, 3, 4 and 2", "1 → 3"], ["large intestine"], ["water is absorbed", "absorbs water", "water absorbed", "absorb water"], ["gullet", "no digestive juice", "only carries food"]], model: "(a) 1, 3, 4, 2. (b) The large intestine; water is absorbed from the undigested food, so it becomes drier and more solid. (c) Photo 1 shows the gullet, which has no digestive juices and only carries food to the stomach." },
    { q: "Hui Ling mixed 5 mL of starch solution with different volumes of saliva and recorded how long it took until iodine no longer turned blue-black. (a) What was she trying to find out? (b) What pattern do the results show? (c) Predict the time for 4 mL of saliva and explain.", tbl: [["Volume of saliva (mL)", "Time until no starch was left (min)"], ["1", "12"], ["2", "6"], ["3", "4"]], marks: 3, x: 1, kw: [["volume of saliva", "amount of saliva"], ["shorter", "less time", "faster", "quicker"], ["less than 4", "fewer than 4", "under 4", "about 3", "3 min", "3 to", "2 to 3", "between 2 and 3"]], model: "(a) How the volume of saliva affects the time taken for starch to be broken down. (b) The greater the volume of saliva, the shorter the time taken for the starch to be broken down. (c) Less than 4 minutes (about 3 minutes), because more saliva breaks down the starch faster." }
  ],
  doc: [
    { q: "State the function of the small intestine.", marks: 2, answers: ["It digests food.", "Digestion is completed in the small intestine and the digested food is absorbed into the bloodstream.", "It absorbs food and water."], best: 1, why: "Answer 2 gives both key ideas: digestion is completed AND digested food is absorbed into the bloodstream. Answer 1 is only half and vague. Answer 3 says ‘food’ instead of ‘digested food’ and misses that digestion is completed there." },
    { q: "Explain why no digestion takes place in the gullet.", marks: 1, answers: ["Food moves too fast.", "The gullet is a tube.", "The gullet has no digestive juices; it only carries food to the stomach."], best: 2, why: "Answer 3 gives the real reason – no digestive juices – and states the gullet’s function. Answer 1 is a guess, and Answer 2 describes its shape but not why there is no digestion." },
    { q: "In an experiment, iodine stayed brown in the test tube with starch and saliva. What does this show?", marks: 2, answers: ["No starch was left, so the saliva had broken down the starch.", "The iodine did not work.", "The saliva is brown."], best: 0, why: "Answer 1 links the colour to starch (no starch left) and states the conclusion. Answer 2 wrongly blames the iodine, and Answer 3 misreads the colour as coming from the saliva." },
    { q: "What happens to food in the stomach?", marks: 2, answers: ["It is digested.", "It is absorbed into the blood.", "The muscular walls churn the food and mix it with digestive juices, so the food is partly digested."], best: 2, why: "Answer 3 has both marks: churning and digestive juices. Answer 1 is too vague, and Answer 2 is wrong – digested food is absorbed in the small intestine, not the stomach." },
    { q: "Explain why the faeces of a person whose large intestine does not work well may be watery.", marks: 2, answers: ["The person drank too much water.", "The large intestine absorbs water from undigested food. Less water is absorbed, so the faeces contain more water.", "The large intestine does not digest food."], best: 1, why: "Answer 2 gives the function (absorbs water) and links it to the effect (less water absorbed, more water in faeces). Answer 1 ignores the large intestine, and Answer 3 gives a true fact that does not explain watery faeces." }
  ]
};
