window.LBY = window.LBY || {};
LBY["p4-heat"] = {
  lessons: [
    {
      h: "Fair, reliable and accurate: improving a heat experiment",
      concept: "Three different words, three different fixes. A FAIR test changes only one variable and keeps all the others the same. RELIABLE results come from repeating the experiment (at least three times) and taking the average, so one odd reading does not decide the result. ACCURATE readings come from good measuring: a datalogger with a temperature sensor, or a thermometer read at eye level after the liquid stops moving, taken at exactly the same time for every set-up. When a question asks you to ‘make the results more reliable’, the answer is to repeat and average – not to change the variables.",
      example: {
        q: "Kai wrapped identical ice cubes in cotton, felt and newspaper and timed how long each took to melt. He did the experiment only once. Study his results. (a) Why might his results not be reliable? (b) Suggest how he can make his results more reliable.",
        tbl: [["Wrapping material", "Time for ice to melt (min)"], ["Cotton", "34"], ["Felt", "47"], ["Newspaper", "41"]],
        marks: 2,
        think: [
          "Step 1: Check if the test was fair first – only the wrapping material was changed, so it is fair.",
          "Step 2: Notice the problem: each material was tested only once, so one mistake (e.g. starting the stopwatch late) could change the result.",
          "Step 3: The fix for reliability is to repeat the experiment at least two more times and take the average time for each material."
        ],
        answer: "(a) He did the experiment only once, so a mistake in one reading could give a wrong result. (b) Repeat the experiment at least two more times for each material and calculate the average time taken for the ice to melt."
      },
      tip: "Reliable = repeat + average. Fair = change one variable only. Do not mix them up.",
      try: {
        q: "Rani tested which cup keeps water hot longer. She did each test once. Which change would make her results more reliable?",
        o: ["Repeat each test three times and find the average.", "Use a different amount of water in each cup.", "Start the water at a different temperature each time.", "Check the reading after a different time for each cup."],
        a: 0,
        why: "Repeating and averaging makes the results reliable. The other three changes add a second changed variable, so the test would no longer be fair."
      }
    }
  ],
  mcq: [
    { q: "Ms Lim wants to record the temperature of a pond at Bishan Park every hour for a whole day, without staying there. What should she use?", o: ["A datalogger with a temperature sensor", "A laboratory thermometer on a string", "A measuring cylinder full of pond water", "A stopwatch and an electronic balance"], a: 0, why: "A datalogger with a temperature sensor records readings automatically at set times, so no one needs to be there. A thermometer must be read by a person each time.", lvl: 1 },
    { q: "The table shows the temperatures at four places at noon. Which place was the coolest?", o: ["The open field", "The void deck", "The library", "The car park"], a: 2, why: "The library had the lowest temperature, 24 °C, so it was the coolest. The car park, at 36 °C, was the hottest.", lvl: 1, tbl: [["Place", "Temperature at noon (°C)"], ["Open field", "34"], ["Void deck", "30"], ["Library", "24"], ["Car park", "36"]] },
    { q: "Which material is most suitable for the base of a cooking pot, so that food is heated quickly?", o: ["Clay", "Glass", "Wood", "Aluminium"], a: 3, why: "Aluminium is a metal and a good conductor of heat, so heat flows quickly from the flame to the food. Clay, glass and wood are poor conductors of heat.", lvl: 1 },
    { q: "Which of these statements are correct?\nA: Heat is a form of energy.\nB: Temperature is measured in degrees Celsius (°C).\nC: An object at a higher temperature always has more heat than one at a lower temperature.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Misconception: that a higher temperature always means more heat. A swimming pool at 30 °C holds far more heat than a cup of tea at 80 °C, because it has much more water. A and B are correct.", lvl: 2 },
    { q: "Jamal put his left hand in ice water and his right hand in warm water for one minute. He then put both hands into the same basin of tap water. The tap water felt warm to his left hand but cool to his right hand. What does this show?", o: ["The tap water in the basin was at two different temperatures.", "Heat flowed from the tap water into both of his hands.", "Our sense of touch is not reliable for telling temperature.", "Coldness flowed from his left hand into the tap water."], a: 2, why: "Misconception: that how hot or cold something feels shows its temperature. The tap water was at one temperature, but his cold left hand gained heat from it (felt warm) while his warm right hand lost heat to it (felt cool). Use a thermometer to measure temperature.", lvl: 2 },
    { q: "A beaker of hot water was left on a table. The graph shows the temperature of the water. Which statement is correct?", o: ["The water lost heat fastest in the first 5 minutes.", "The water stopped losing heat after 10 minutes.", "The water lost heat at the same rate throughout.", "The water gained heat from the air after 25 minutes."], a: 0, why: "The temperature fell by 22 °C in the first 5 minutes but by less and less after that. It stopped falling at 25 minutes, when the water reached the temperature of the room (30 °C), so there was no more heat flow.", lvl: 2, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 80], ["5", 58], ["10", 45], ["15", 37], ["20", 32], ["25", 30], ["30", 30]] } },
    { q: "Ken capped an empty plastic bottle in his hot car. After he carried it into his air-conditioned home, the bottle became slightly squashed. Why?", o: ["The plastic lost heat and expanded.", "Cold air from the room entered the bottle.", "The air inside gained heat and expanded.", "The air inside lost heat and contracted."], a: 3, why: "The air sealed in the bottle lost heat to the cooler room and contracted, so it took up less space and the bottle was squashed. The bottle was capped, so no air entered it.", lvl: 2 },
    { q: "Ice cubes were added to a glass of warm lime juice. Which statement describes what happened?", o: ["Heat flowed from the ice to the juice, so the juice cooled.", "Coldness flowed from the ice to the juice, so the juice cooled.", "Heat flowed from the juice to the ice, so the ice melted and the juice cooled.", "Heat flowed from the juice to the ice, so the ice melted and the juice warmed."], a: 2, why: "Misconception: that ‘coldness’ flows from ice. The juice is hotter, so heat flows from the juice to the ice. The juice loses heat and cools; the ice gains heat and melts.", lvl: 2 },
    { q: "Which of these changes would make ice in a styrofoam cooler box last longer?\nA: Using a box with thicker styrofoam walls\nB: Keeping the box in the shade instead of in the Sun\nC: Opening the lid often to check the ice", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Thicker styrofoam (a poor conductor of heat) reduces the heat gained, and a cooler place in the shade means less heat flows into the box. Opening the lid lets warmer air in, so the ice gains more heat.", lvl: 2 },
    { q: "Nurul held an upside-down flask with its glass tube dipped in water, as shown. Bubbles came out of the tube. Which statements are correct?\nA: The air in the flask gained heat from her hands.\nB: The air in the flask expanded.\nC: The mass of the air in the flask increased.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "The air in the flask gained heat from her warmer hands and expanded, pushing some air out as bubbles. Its volume increased, but its mass did not – C is wrong.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Flask turned upside down", "Tube dipped in water", "Held with both hands", "Bubbles seen"] }] } },
    { q: "Equal volumes of water at 80 °C were poured into cups P and Q, of the same size and thickness but made of different materials, in the same room. The table shows the temperature of the water. Which statement is correct?", o: ["P is made of a better conductor of heat than Q.", "Q is made of a better conductor of heat than P.", "The water in P lost heat faster than the water in Q.", "The water in both cups lost heat at the same rate."], a: 1, why: "The water in Q dropped faster (to 42 °C, compared with 58 °C in P), so heat flowed out through Q faster: Q is the better conductor of heat.", lvl: 3, tbl: [["Time (min)", "Cup P (°C)", "Cup Q (°C)"], ["0", "80", "80"], ["5", "71", "62"], ["10", "64", "50"], ["15", "58", "42"]] },
    { q: "Which of these are caused by a substance expanding?\nA: The liquid in a thermometer rises in warm water.\nB: Butter melts in a hot frying pan.\nC: Gaps between concrete slabs narrow on a hot day.\nD: Steam forms above a pot of boiling soup.", o: ["A only", "A and C only", "B and D only", "A, C and D only"], a: 1, why: "In A and C, the liquid and the concrete gain heat and expand. B (melting) and D (boiling) are changes of state, not expansion.", lvl: 3 },
    { q: "Identical ice cubes were put into equal amounts of water at different starting temperatures. The graph shows how long each took to melt. How long would an ice cube most likely take to melt in water at 30 °C?", o: ["About 3 min", "About 4 min", "About 7 min", "About 10 min"], a: 2, why: "30 °C lies between 20 °C (9 min) and 40 °C (5 min), so the time should lie between 5 and 9 min: about 7 min.", lvl: 3, fig: { type: "bar", xl: "Starting temperature of water (°C)", yl: "Time for ice to melt (min)", bars: [["20", 9], ["40", 5], ["60", 3], ["80", 2]] } },
    { q: "Ahmad turned up the flame under a pot of water that was already boiling. What happened to the temperature of the water?", o: ["It rose above 100 °C, as more heat was gained.", "It fell below 100 °C, as more steam escaped.", "It rose and fell, as the flame kept changing.", "It stayed at 100 °C, but more steam formed."], a: 3, why: "Misconception: that a bigger flame makes boiling water hotter. While water boils, the heat gained is used to change it into steam, so the temperature stays at 100 °C; the water just boils away faster.", lvl: 3 },
    { q: "Study the classification chart. Which letter represents ‘the liquid in a thermometer falling when it is put into cold water’?", o: ["A", "B", "C", "D"], a: 3, why: "The thermometer liquid loses heat to the cold water and contracts. It loses heat but stays a liquid, so it does not change state: D.", lvl: 3, fig: { type: "flow", root: "Changes", node: { q: "Gains heat?", yes: { q: "Changes state?", yes: "A", no: "B" }, no: { q: "Changes state?", yes: "C", no: "D" } } } },
    { q: "A datalogger recorded the air temperature in Wen’s bedroom one night. The air-conditioner was switched on once and switched off once. At about what time was it switched off?", o: ["9 p.m.", "11 p.m.", "1 a.m.", "3 a.m."], a: 2, why: "The temperature fell from 9 p.m. (air-con on) and stayed at 23 °C until 1 a.m. After 1 a.m. it rose, as the room gained heat from the warmer surroundings again, so the air-con was switched off at about 1 a.m.", lvl: 3, fig: { type: "line", xl: "Time", yl: "Temperature of air (°C)", pts: [["8pm", 31], ["9pm", 31], ["10pm", 25], ["11pm", 23], ["12am", 23], ["1am", 23], ["2am", 27], ["3am", 29]] } },
    { q: "Mei poured the water in A and B together into a styrofoam cup and stirred. What is the temperature of the mixture most likely to be, just after mixing?", o: ["About 20 °C", "About 35 °C", "About 50 °C", "About 65 °C"], a: 1, why: "Heat flows from the hot water to the cold water until they are at the same temperature. There is three times as much cold water, so the mixture ends up much nearer 20 °C than 80 °C – about 35 °C, not the halfway 50 °C.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["100 ml water", "80 °C"] }, { label: "B", icon: "beaker", lines: ["300 ml water", "20 °C"] }] } },
    { q: "Ali poured hot water into cups X and Y, made of different materials, in a room at 30 °C. He concluded that Y is the better insulator of heat. Why can he NOT draw this conclusion from his results?", o: ["The starting temperatures were different, so the test was not fair.", "The water in Y ended cooler, so Y must be the poorer insulator.", "The water in X lost more heat, so X must be the better insulator.", "The room was not at 0 °C, so the water could not cool properly."], a: 0, why: "The water in X started 20 °C hotter, so it was further from room temperature and would lose heat faster in any cup. Only the material should be changed; the starting temperature must be the same.", lvl: 4, tbl: [["Cup", "Start (°C)", "After 20 min (°C)", "Drop (°C)"], ["X", "90", "60", "30"], ["Y", "70", "50", "20"]] },
    { q: "Rods P, Q, R and S of the same size are made of different materials. A wax bead was stuck at one end of each rod and the other end was put in hot water. Study the results. Which statements are correct?\nA: R is the best conductor of heat.\nB: Q is the most suitable for making the handle of a frying pan.\nC: Heat flowed along S faster than along P.", o: ["A and B only", "A only", "B and C only", "A, B and C"], a: 0, why: "The bead on R dropped first, so heat flowed along R fastest (A). The bead on Q never dropped, so Q is the poorest conductor of heat and best for a handle (B). The bead on S took longer than on P, so heat flowed along S more slowly (C is wrong).", lvl: 4, tbl: [["Rod", "Time for wax bead to drop"], ["P", "40 s"], ["Q", "Did not drop after 10 min"], ["R", "25 s"], ["S", "90 s"]] },
    { q: "A beaker of crushed ice and water was left in a room. The graph shows its temperature. Which statements are correct?\nA: From 0 to 20 min, the mixture was gaining heat.\nB: At about 20 min, all the ice had melted.\nC: The room temperature was about 30 °C.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "Misconception: that a flat part means no heat is gained. The mixture gained heat from the warmer air from the start, but the heat was used to melt the ice, so it stayed at 0 °C until about 20 min. It then warmed up until it reached room temperature, 30 °C.", lvl: 4, fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 0], ["10", 0], ["20", 0], ["30", 12], ["40", 21], ["50", 27], ["60", 30], ["70", 30]] } }
  ],
  tf: [
    { s: "Heat can flow only through solids, not through liquids or gases.", a: false, why: "Heat flows from a hotter place to a colder place through solids, liquids and gases – for example, from hot soup into the cooler air around it." },
    { s: "Melting ice is gaining heat even though its temperature stays at 0 °C.", a: true, why: "The heat gained is used to change the ice into water, so the temperature does not rise until all the ice has melted." },
    { s: "Once water starts to boil, it stops gaining heat from the flame.", a: false, why: "Boiling water keeps gaining heat from the flame; the heat is used to change the water into steam, so its temperature stays at 100 °C." },
    { s: "A thicker layer of styrofoam lets more heat flow into a cooler box.", a: false, why: "Styrofoam is a poor conductor of heat; a thicker layer reduces the heat flowing in even more." },
    { s: "When you hold a cold can of drink, heat flows from your hand to the can.", a: true, why: "Your hand is hotter than the can, so heat flows from your hand to the can." },
    { s: "Rubbing your hands together quickly produces heat.", a: true, why: "Rubbing surfaces together produces heat, so your hands become warmer." },
    { s: "With the same flame, water in a metal pot heats up faster than water in a clay pot of the same size.", a: true, why: "Metal is a good conductor of heat, so heat flows from the flame to the water faster than through clay." },
    { s: "On a copper rod heated at one end, the parts furthest from the flame get hot first.", a: false, why: "Heat is conducted along the rod from the heated end, so the parts nearest the flame get hot first." },
    { s: "Heat always flows from an object with more heat to an object with less heat.", a: false, why: "Heat flows from the object at a higher temperature to the one at a lower temperature, whatever the amount of heat each has." },
    { s: "Doing an experiment three times and taking the average makes the results more reliable.", a: true, why: "Repeating reduces the effect of a single mistake in one reading." }
  ],
  oe: [
    { q: "Wei poured 150 ml of water at 80 °C into cups made of materials P, Q and R, and measured the temperature of the water after 20 minutes. His results are shown in the table. (a) State the aim of his experiment. (b) Which material is best for making a cup to keep drinks hot? (c) Explain your answer to (b) using the results. (d) Wei did each test only once. How can he make his results more reliable?", marks: 4, kw: [["which material", "type of material", "material of the cup", "material of each cup", "material that keeps", "materials keep", "which cup", "cup that keeps", "cup keeps"], ["q"], ["highest", "smallest drop", "least heat", "lost the least", "dropped the least", "drop the least", "hottest"], ["repeat", "again", "average", "more times", "three times"]], model: "(a) To find out which material keeps water hot the longest. (b) Q. (c) The water in cup Q had the highest temperature after 20 minutes, so it lost the least heat. Q is the poorest conductor of heat. (d) Repeat the experiment two more times and take the average temperature for each cup.", tbl: [["Material of cup", "Temperature at start (°C)", "Temperature after 20 min (°C)"], ["P", "80", "52"], ["Q", "80", "66"], ["R", "80", "58"]] },
    { q: "A flask was filled with coloured water and closed with a stopper that had a glass tube through it. The flask was placed in a basin of hot water, as shown in A. (a) What happened to the water level in the glass tube? (b) Explain why, in terms of heat. (c) The flask was then moved into a basin of ice water, as shown in B. Explain what happened to the water level in the tube.", marks: 4, kw: [["rose", "rise", "went up", "goes up", "moved up", "moves up", "higher"], ["gain"], ["expand"], ["contract"]], model: "(a) The water level in the tube rose. (b) The coloured water gained heat from the hot water and expanded, so it moved up the tube. (c) The coloured water lost heat to the ice water and contracted, so the water level in the tube fell.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Flask of coloured water", "Glass tube in stopper", "In hot water"] }, { label: "B", icon: "jar", lines: ["Same flask", "In ice water"] }] } },
    { q: "Wax beads were stuck along a copper rod at different distances from one end. That end was heated, and the time for each bead to melt was recorded, as shown in the graph. (a) Describe the relationship between the distance of a bead from the heated end and the time it took to melt. (b) A bead was also stuck 12 cm from the heated end. Predict the time it took to melt. (c) The experiment was repeated with a glass rod of the same size. How would the times change? (d) Explain your answer to (c).", marks: 4, kw: [["further", "farther", "greater the distance", "more the distance", "longer the distance", "distance increases"], ["more than 62", "longer than 62", "over 62", "above 62", "after 62", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99"], ["take longer", "took longer", "takes longer", "take a longer", "longer time", "more time", "slower", "more slowly"], ["poor conductor", "poorer conductor", "worse conductor", "insulator"]], model: "(a) The further the bead from the heated end, the longer it took to melt. (b) More than 62 seconds (about 80 seconds). (c) Each bead would take a longer time to melt. (d) Glass is a poor conductor of heat, so heat is conducted along the glass rod more slowly than along the copper rod.", fig: { type: "line", xl: "Distance from heated end (cm)", yl: "Time for wax to melt (s)", pts: [["2", 8], ["4", 18], ["6", 30], ["8", 45], ["10", 62]] } },
    { q: "Identical beakers, each with 200 ml of water at 80 °C, were placed in water baths at 10 °C, 20 °C, 30 °C and 40 °C. The graph shows the drop in temperature of the water in each beaker after 10 minutes. (a) What was the variable that was changed? (b) Describe the relationship shown by the graph. (c) Explain this relationship in terms of heat flow.", marks: 3, kw: [["temperature of the water bath", "temperature of the water in the bath", "temperature of the bath", "water bath temperature", "temperature of the surrounding", "temperature of the water around"], ["lower the temperature", "colder the", "cooler the", "the lower", "higher the temperature", "the higher", "bigger the drop", "greater the drop", "smaller the drop"], ["difference"]], model: "(a) The temperature of the water bath. (b) The lower the temperature of the water bath, the bigger the drop in temperature of the water in the beaker. (c) The colder the water bath, the bigger the difference in temperature between the hot water and the water bath, so heat flows from the hot water to the water bath faster.", fig: { type: "bar", xl: "Temperature of water bath (°C)", yl: "Drop in temperature after 10 min (°C)", bars: [["10", 42], ["20", 34], ["30", 26], ["40", 18]] }, x: 1 },
    { q: "At a hawker centre, Jia Hui took a can of drink out of an ice box. After a few minutes, the outside of the can was covered with water droplets. (a) Where did the water in the droplets come from? (b) Explain how the droplets formed. (c) Name this change of state.", marks: 3, kw: [["water vapour"], ["loses heat", "lose heat", "lost heat", "losing heat"], ["condens"]], model: "(a) From the water vapour in the surrounding air. (b) The water vapour in the warmer air touched the cold can, lost heat to it and changed into tiny water droplets. (c) Condensation." },
    { q: "Two copper blocks, one of 50 g and one of 500 g, were heated to 90 °C. Each was dropped into a beaker with 200 ml of water at 25 °C, as shown. (a) In which beaker will the water reach the higher temperature? (b) Explain why, even though both blocks started at the same temperature. (c) When does heat stop flowing between each block and its water?", marks: 3, kw: [["500 g", "500g", "bigger block", "larger block", "heavier block", "beaker b"], ["more heat"], ["same temperature"]], model: "(a) Beaker B, with the 500 g block. (b) The 500 g block has more heat than the 50 g block at the same temperature, so it gives more heat to the water. (c) Heat stops flowing when the block and the water reach the same temperature.", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["200 ml water at 25 °C", "50 g copper block", "Block at 90 °C"] }, { label: "B", icon: "beaker", lines: ["200 ml water at 25 °C", "500 g copper block", "Block at 90 °C"] }] }, x: 1 }
  ],
  doc: [
    { q: "A beaker of crushed ice and water was left in a room at 30 °C. Its temperature stayed at 0 °C for 20 minutes. Explain why.", marks: 2, answers: ["The ice kept giving out coldness, so the water stayed at 0 °C.", "The mixture gained heat from the warmer air, but the heat was used to melt the ice, so the temperature stayed at 0 °C until all the ice had melted.", "The mixture did not gain any heat until all the ice had melted."], best: 1, why: "Answer 2 gives the heat gain from the warmer air AND what the heat was used for (melting the ice). Answer 1 treats ‘coldness’ as something that flows. Answer 3 is wrong – the mixture gains heat all the time; the flat part does not mean no heat is gained." },
    { q: "A sealed packet of crisps left in a hot car became puffed up. Explain why.", marks: 2, answers: ["The air inside the packet gained heat from the hot car and expanded, so it took up more space and puffed up the packet.", "The packet got bigger because it was hot.", "Hot air from the car went into the packet."], best: 0, why: "Answer 1 names what gained heat (the air inside) and the effect (expanded, took up more space). Answer 2 is too vague – no heat gain or expansion. Answer 3 is wrong – the packet is sealed, so no air can enter." }
  ]
};
