window.LBU = window.LBU || {};
LBU["p4-heat"] = {
  glossary: [
    { t: "Heat", d: "A form of energy that flows from a place or object at a higher temperature to one at a lower temperature." },
    { t: "Temperature", d: "The degree of hotness or coldness of an object or place, shown in degrees Celsius (°C) on a thermometer or a temperature sensor." },
    { t: "Thermometer", d: "An instrument for measuring temperature. Its liquid gains heat and expands up the tube, or loses heat and contracts down the tube." },
    { t: "Datalogger with temperature sensor", d: "A device that takes temperature readings automatically at set time intervals over a long period and can show them as a table or a graph." },
    { t: "Source of heat", d: "Anything that gives out heat, e.g. the Sun (our main source of heat), burning fuels such as gas, electrical appliances such as irons, and our bodies." },
    { t: "Heat flow", d: "The movement of heat between two things at different temperatures, always from the hotter one to the colder one, until their temperatures are equal." },
    { t: "Room temperature", d: "The temperature of the air in a room. A hot or cold object left there loses or gains heat until it reaches room temperature, then heat stops flowing." },
    { t: "Good conductor of heat", d: "A material through which heat flows easily and quickly. Most metals, such as copper, aluminium, iron and steel, are good conductors of heat." },
    { t: "Poor conductor of heat (insulator)", d: "A material through which heat does not flow easily, so it reduces heat gain or heat loss, e.g. wood, plastic, rubber, styrofoam, cloth and air." },
    { t: "Expansion", d: "An increase in the volume of a substance when it gains heat. Its mass stays the same." },
    { t: "Contraction", d: "A decrease in the volume of a substance when it loses heat. Its mass stays the same." },
    { t: "Change of state", d: "A change from one state to another: melting, boiling or evaporation when a substance gains heat, and condensation or freezing when it loses heat." }
  ],
  lessons: [
    {
      h: "Describing a trend in heat data, then explaining it",
      concept: "A ‘describe the relationship’ question needs BOTH variables named and the direction of change: ‘The greater the [changed variable], the more/less the [measured variable].’ Answers such as ‘it increases’ or ‘the time gets longer’ lose the mark because they do not say what the change depends on. If the next part says ‘explain’, add the heat reason: what gains or loses heat, from where, and why that changes the result.",
      example: {
        q: "Siti put ice cubes of different masses on identical plates in the same room and timed how long each took to melt completely. Study the graph. (a) Describe the relationship between the mass of the ice cube and the time it took to melt. (b) Explain this relationship.",
        fig: { type: "bar", xl: "Mass of ice cube (g)", yl: "Time to melt completely (min)", bars: [["10", 12], ["20", 23], ["30", 35], ["40", 46]] },
        marks: 2,
        think: [
          "Step 1: Name the two variables: the changed variable is the mass of the ice cube; the measured variable is the time taken to melt completely.",
          "Step 2: Read the pattern: as the mass goes up from 10 g to 40 g, the time goes up from 12 min to 46 min.",
          "Step 3: Write ONE sentence with both variables: ‘The greater the mass of the ice cube, the longer it took to melt completely.’",
          "Step 4: Explain with heat: a bigger ice cube needs more heat to melt completely. It gains heat from the warmer surrounding air, so it takes longer to gain enough heat."
        ],
        answer: "(a) The greater the mass of the ice cube, the longer the time it took to melt completely. (b) A bigger ice cube needs more heat to melt completely. It gains heat from the warmer surrounding air, so it takes a longer time to gain enough heat to melt."
      },
      tip: "Two variables, one sentence: ‘The more …, the more/less …’ – then add the heat reason.",
      try: {
        q: "Hana added different numbers of identical ice cubes to cups, each holding 200 ml of water at 50 °C. She recorded the temperature of the water after all the ice had melted. Which statement correctly describes the relationship shown in the graph?",
        fig: { type: "bar", xl: "Number of ice cubes added", yl: "Final temperature of water (°C)", bars: [["1", 40], ["2", 33], ["3", 27], ["4", 22]] },
        o: ["The more ice cubes added, the higher the final temperature of the water.", "The fewer ice cubes added, the lower the final temperature of the water.", "The more ice cubes added, the lower the final temperature of the water.", "The number of ice cubes does not affect the final temperature of the water."],
        a: 2,
        why: "As the number of ice cubes goes up from 1 to 4, the final temperature falls from 40 °C to 22 °C. More ice gains more heat from the water, so the water loses more heat. The other statements reverse the pattern or deny it."
      }
    },
    {
      h: "Predicting the final temperature when hot meets cold",
      concept: "When a hotter and a colder thing touch or are mixed, heat flows from the hotter one to the colder one until both are at the same temperature. So the final temperature always lies BETWEEN the two starting temperatures – the hot one never ends up colder than the cold one. Equal amounts of water end up about halfway. Unequal amounts end up nearer the starting temperature of the LARGER amount, because the larger amount’s temperature changes less. Afterwards, the mixture gains or loses heat until it reaches room temperature.",
      example: {
        q: "Mdm Lee poured 3 litres of hot water at 70 °C into a plastic tub containing 1 litre of water at 30 °C to bathe her baby. (a) State the direction of heat flow. (b) Predict whether the final temperature of the water will be nearer 70 °C or 30 °C. (c) Explain your prediction.",
        marks: 3,
        think: [
          "Step 1: Find the hotter water: the water at 70 °C is hotter, so heat flows from the hot water to the cooler water.",
          "Step 2: Set the limits: the final temperature must lie between 30 °C and 70 °C.",
          "Step 3: Compare the amounts: there is three times as much hot water as cooler water.",
          "Step 4: The larger amount changes temperature less, so the hot water cools only a little while the small amount of cooler water warms up a lot. The mixture ends nearer 70 °C (about 60 °C)."
        ],
        answer: "(a) Heat flows from the hot water to the cooler water. (b) Nearer 70 °C (about 60 °C). (c) The hot water loses heat and the cooler water gains heat until they are at the same temperature. There is more hot water, so its temperature drops only a little, and the final temperature is nearer 70 °C."
      },
      tip: "Final temperature: always between the two, and nearer the larger amount.",
      try: {
        q: "Each pair of water samples in the table was mixed in a styrofoam cup. Which mixture will have the highest temperature just after mixing?",
        tbl: [["Pair", "Hot water", "Cold water"], ["P", "100 ml at 80 °C", "100 ml at 20 °C"], ["Q", "300 ml at 80 °C", "100 ml at 20 °C"], ["R", "100 ml at 80 °C", "300 ml at 20 °C"], ["S", "200 ml at 60 °C", "200 ml at 40 °C"]],
        o: ["P", "Q", "R", "S"],
        a: 1,
        why: "P and S have equal amounts, so each ends about halfway (50 °C). R has more cold water, so it ends nearer 20 °C (about 35 °C). Q has three times as much hot water, so it ends nearest 80 °C (about 65 °C)."
      }
    }
  ],
  flash: [
    { f: "Why is the base of a cooking pot made of metal?", b: "Metal is a good conductor of heat, so heat flows quickly from the flame through the base to the food, and the food cooks faster." },
    { f: "Why are bottled drinks not filled right to the top?", b: "On a hot day the drink gains heat and expands. The space at the top gives it room to expand, so the bottle does not leak or burst." },
    { f: "How does a styrofoam cooler box keep drinks cold?", b: "Styrofoam is a poor conductor of heat, so it reduces the heat gained by the drinks from the warmer surroundings. It does not produce coldness." },
    { f: "Why does a dented ping-pong ball pop back into shape in hot water?", b: "The air inside the ball gains heat from the hot water and expands, pushing the dented part outwards." },
    { f: "Three things that make a hot drink lose heat faster", b: "A bigger difference in temperature between the drink and its surroundings, more of its surface exposed to the air, and a container made of a good conductor of heat." },
    { f: "Why is our sense of touch not reliable for measuring temperature?", b: "How hot or cold something feels depends on how fast heat flows to or from our hand, e.g. metal feels colder than wood at the same temperature. Use a thermometer." },
    { f: "How does a vacuum flask keep a hot drink hot?", b: "The plastic stopper, a poor conductor of heat, and the vacuum between the double walls reduce the heat lost from the drink to the cooler surroundings." },
    { f: "Why does a stuck metal lid loosen under hot running water?", b: "The metal lid gains heat from the hot water and expands, so it becomes loose and is easier to open." },
    { f: "On a cooling curve, what does a steeper drop show?", b: "The object is losing heat faster. When two containers are compared, the steeper curve belongs to the better conductor of heat (the poorer insulator)." },
    { f: "Why are overhead wires hung slightly loose?", b: "On cold days the wires lose heat and contract. If they were hung tight, they could snap. On hot days they gain heat, expand and sag more." },
    { f: "Fair test on insulators: what do you change and what do you keep the same?", b: "Change only the type of material. Keep the same amount of water, starting temperature, size and thickness of material, place, and time of measuring." },
    { f: "Hot and cold water are mixed. What is the final temperature?", b: "Heat flows from the hot water to the cold water until both are at the same temperature: between the two starting temperatures, nearer that of the larger amount." }
  ],
  mcq: [
    { q: "Mr Tan stirs a pot of hot curry with ladles of the same size made of different materials. Which ladle’s handle will become hot the fastest?", o: ["Wooden ladle", "Plastic ladle", "Steel ladle", "Bamboo ladle"], a: 2, why: "Steel is a metal and a good conductor of heat, so heat is conducted from the hot curry up the handle fastest. Wood, plastic and bamboo are poor conductors of heat.", lvl: 1 },
    { q: "What do we call a material that does NOT allow heat to flow through it easily?", o: ["A poor conductor of heat", "A good conductor of heat", "A source of heat", "A magnetic material"], a: 0, why: "A poor conductor of heat (an insulator) does not let heat flow through it easily. A good conductor lets heat flow easily, and a source of heat gives out heat.", lvl: 1 },
    { q: "When reading a thermometer, where should Aisha’s eye be?", o: ["Above the top of the liquid", "Level with the top of the liquid", "Below the top of the liquid", "Level with the bulb of the thermometer"], a: 1, why: "The eye must be level with the top of the liquid column. Looking from above or below gives a wrong reading, and the bulb is not where the reading is taken.", lvl: 1 },
    { q: "A tray of water was put in a freezer and turned into ice. What happened to the water?", o: ["It gained heat and melted.", "It gained heat and froze.", "It lost heat and melted.", "It lost heat and froze."], a: 3, why: "The water lost heat to the colder air in the freezer and changed from a liquid to a solid: it froze. Melting needs heat to be gained.", lvl: 1 },
    { q: "Raj wants to find out if the material of a lid affects how fast hot soup in a bowl cools. Which two set-ups should he compare?", o: ["P and R", "P and Q", "Q and R", "P and S"], a: 1, why: "P and Q differ only in the material of the lid. P and R differ in both lid material and amount of soup, Q and R only in the amount of soup, and P and S only in the starting temperature.", lvl: 2, fig: { type: "setups", items: [{ label: "P", icon: "dish", lines: ["Plastic lid", "300 ml soup", "Starts at 80 °C"] }, { label: "Q", icon: "dish", lines: ["Metal lid", "300 ml soup", "Starts at 80 °C"] }, { label: "R", icon: "dish", lines: ["Metal lid", "200 ml soup", "Starts at 80 °C"] }, { label: "S", icon: "dish", lines: ["Plastic lid", "300 ml soup", "Starts at 60 °C"] }] } },
    { q: "Which of these is NOT an example of something losing heat?", o: ["Steam turning into droplets on a cold lid", "A cup of kopi cooling on a kopitiam table", "Ice cream melting on a plate at the void deck", "Water in an ice-cube tray turning into ice"], a: 2, why: "Melting ice cream GAINS heat from the warmer air. The steam loses heat and condenses, the kopi loses heat to the air, and the water loses heat and freezes.", lvl: 2 },
    { q: "Jun pumped his bicycle tyres very hard in the morning, then left his bicycle in the hot Sun at the park connector. In the afternoon, one tyre burst. Why?", o: ["The rubber of the tyre gained heat and contracted.", "The air inside the tyre lost heat and contracted.", "Hot air from outside leaked into the tyre.", "The air inside the tyre gained heat and expanded."], a: 3, why: "The air sealed inside the tyre gained heat from the Sun and expanded. The tyre was already very hard, so it had no room for the air to expand and it burst. No air can leak in through a sealed tyre.", lvl: 2 },
    { q: "At a hawker centre, Mei put a cup of hot Milo and a cup of iced Milo on the same table. The table shows their temperatures. What was the temperature of the surrounding air most likely to be?", o: ["28 °C", "38 °C", "31 °C", "42 °C"], a: 2, why: "Both drinks stopped changing at 31 °C: the hot Milo stopped losing heat and the iced Milo stopped gaining heat, because both had reached the temperature of the surrounding air.", lvl: 2, tbl: [["Time (min)", "Hot Milo (°C)", "Iced Milo (°C)"], ["0", "80", "5"], ["15", "52", "17"], ["30", "38", "24"], ["45", "32", "28"], ["60", "31", "30"], ["75", "31", "31"]] },
    { q: "Which of these would make a bowl of hot soup lose heat MORE SLOWLY?", o: ["Covering it and wrapping it in a cloth", "Pouring it onto a wide, flat plate", "Placing it in front of a fan", "Pouring it into a thin metal bowl"], a: 0, why: "The cover stops the hot surface being exposed to the air, and the cloth traps air; cloth and air are poor conductors of heat, so less heat is lost. A wide plate exposes more surface, a fan carries heat away faster, and metal is a good conductor of heat.", lvl: 2 },
    { q: "Study the classification chart. Which letter represents a wooden spatula used to stir hot curry?", o: ["A", "B", "C", "D"], a: 3, why: "Wood is a poor conductor of heat, so the spatula goes down the ‘No’ branch. It is not used to keep food cold, so it is D.", lvl: 2, fig: { type: "flow", root: "Kitchen items", node: { q: "Good conductor of heat?", yes: { q: "Used to heat food?", yes: "A", no: "B" }, no: { q: "Keeps food cold?", yes: "C", no: "D" } } } },
    { q: "Lina left a cup of hot kopi at 80 °C and a cup of iced kopi at 5 °C on a table in a room at 30 °C. Which statements are correct?\nA: The hot kopi loses heat to the surrounding air.\nB: The iced kopi gains heat from the surrounding air.\nC: After a long time, both cups of kopi will be at about 30 °C.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "Heat flows from the hot kopi to the cooler air (A) and from the warmer air to the iced kopi (B). Each keeps changing until it reaches room temperature, 30 °C (C).", lvl: 2 },
    { q: "Equal amounts of water at 30 °C were heated in pots W, X, Y and Z, of the same size and thickness but made of different materials, over identical flames for 5 minutes. The graph shows the results. Which material is best for a pot to cook food quickly, and which is best for a container to keep cooked food warm?", o: ["Y for cooking, and X for keeping food warm", "X for cooking, and Y for keeping food warm", "X for cooking, and Z for keeping food warm", "W for cooking, and Y for keeping food warm"], a: 1, why: "The water in X became the hottest, so heat flowed through X fastest: X is the best conductor of heat, good for cooking. Heat flowed through Y most slowly, so Y is the poorest conductor and best for reducing heat lost from cooked food.", lvl: 3, fig: { type: "bar", xl: "Pot", yl: "Temperature after 5 min (°C)", bars: [["W", 52], ["X", 70], ["Y", 38], ["Z", 61]] } },
    { q: "An electric rice cooker has an aluminium inner pot, a plastic outer body and a layer of air between them. Which statements are correct?\nA: The aluminium pot lets heat flow quickly to the rice.\nB: The plastic body reduces the heat flowing to a hand that touches it.\nC: The layer of air is a good conductor that helps the rice cook faster.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Aluminium is a good conductor of heat, so heat flows quickly to the rice (A). Plastic is a poor conductor of heat, so less heat reaches the hand (B). Air is a poor conductor of heat; the air layer reduces heat flow to the outer body, so C is wrong.", lvl: 3 },
    { q: "A thermometer reading 30 °C was taken from a table and dipped into a basin of water that had been in the same room overnight. The reading stayed at 30 °C. Why?", o: ["The water and the thermometer were at the same temperature, so no heat flowed.", "Heat flowed from the water to the liquid, but the liquid did not expand.", "The thermometer liquid only moves when it is put in very hot or very cold water.", "Water is a poor conductor of heat, so heat could not flow into the bulb."], a: 0, why: "After a night in the same room, the water was at room temperature, the same as the thermometer. Heat flows only when there is a difference in temperature, so the liquid neither gained nor lost heat.", lvl: 3 },
    { q: "A datalogger recorded the temperature of the air inside a closed styrofoam cooler box of cold drinks at a school carnival. At one point, the lid was opened and left open. Between which two times was the lid most likely opened?", o: ["8 a.m. and 9 a.m.", "10 a.m. and 11 a.m.", "11 a.m. and 12 noon", "1 p.m. and 2 p.m."], a: 2, why: "Until 11 a.m. the temperature stayed at about 4–5 °C, as the closed styrofoam box reduced the heat gained. Between 11 a.m. and 12 noon it began to rise quickly, because warmer air came in and much more heat was gained from the surroundings.", lvl: 3, fig: { type: "line", xl: "Time of day", yl: "Temperature inside box (°C)", pts: [["8am", 4], ["9am", 4], ["10am", 5], ["11am", 5], ["12nn", 13], ["1pm", 19], ["2pm", 23]] } },
    { q: "Which of these does NOT show that a gas expands when it gains heat?", o: ["A dented ping-pong ball pops out in hot water.", "A balloon over a flask inflates in hot water.", "A bicycle tyre becomes firmer in the hot Sun.", "The liquid in a thermometer rises in warm water."], a: 3, why: "The thermometer shows a LIQUID expanding. In the other three, the air (a gas) inside the ball, flask and tyre gains heat and expands.", lvl: 3 },
    { q: "Nadia wants to find out if the starting temperature of water affects how long an ice cube takes to melt in it. Which two set-ups should she use?", o: ["P and S", "P and Q", "Q and S", "R and S"], a: 0, why: "P and S differ only in the starting temperature of the water. P and Q also differ in the amount of water, Q and S differ only in the amount of water, and R and S differ only in the mass of the ice cube.", lvl: 3, tbl: [["Set-up", "Amount of water (ml)", "Starting temperature (°C)", "Mass of ice cube (g)"], ["P", "200", "40", "10"], ["Q", "100", "60", "10"], ["R", "200", "60", "20"], ["S", "200", "60", "10"]] },
    { q: "Hot water at 80 °C was poured into cups X and Y, of the same size but made of different materials, in a room at 30 °C. The table shows the results. The test was then repeated with iced water at 5 °C in each cup. After 20 minutes, what are the temperatures of the iced water most likely to be?", o: ["X: 18 °C, Y: 9 °C", "X: 9 °C, Y: 18 °C", "X: 5 °C, Y: 18 °C", "X: 9 °C, Y: 34 °C"], a: 1, why: "X let less heat out of the hot water, so X is the poorer conductor of heat and will also let less heat INTO the iced water: X’s water warms up less. Some heat still flows in, so X cannot stay at 5 °C, and neither cup can rise above room temperature, 30 °C.", lvl: 4, tbl: [["Cup", "Start (°C)", "After 20 min (°C)"], ["X", "80", "71"], ["Y", "80", "52"]] },
    { q: "Water in a beaker was heated over a flame. At 6 minutes, one change was made. The graph shows the temperature of the water. What change was most likely made at 6 minutes?", o: ["The flame was turned off.", "The flame was made bigger.", "A lump of ice was added.", "Boiling water was added."], a: 2, why: "The temperature dropped sharply and then rose again. The water lost heat to the ice, which melted; the flame then heated the water again. Turning off the flame would give a slow fall with no rise after, and a bigger flame or boiling water (hotter than 75 °C) would not cause a drop.", lvl: 4, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 30], ["2", 45], ["4", 60], ["6", 75], ["8", 40], ["10", 48], ["12", 60]] } },
    { q: "Metal block X at 70 °C and metal block Y at 10 °C were placed touching each other inside a closed styrofoam box. The graph shows the temperature of X. Which statement is correct at 30 minutes?", o: ["Y is at 40 °C, and heat no longer flows between X and Y.", "Y is at 10 °C, and heat no longer flows between X and Y.", "Y is at 40 °C, and heat is still flowing from X to Y.", "Y is at 70 °C, as all the heat from X has flowed into Y."], a: 0, why: "X stopped cooling at 40 °C from 25 min, so X and Y had reached the same temperature: Y is also at 40 °C and heat stops flowing between them. Y cannot stay at 10 °C or become hotter than X.", lvl: 4, fig: { type: "line", xl: "Time (min)", yl: "Temperature of X (°C)", pts: [["0", 70], ["5", 55], ["10", 47], ["15", 43], ["20", 41], ["25", 40], ["30", 40]] } }
  ],
  oe: [
    { q: "Jia Wei built two identical model huts with metal roofs. Hut A had a bare metal roof. Hut B had the same metal roof lined underneath with a layer of styrofoam. Both huts were placed under identical lamps, which were switched off at 30 minutes. A temperature sensor recorded the air inside each hut, as shown in the table. (a) Which hut stayed cooler inside while the lamps were on? [1] (b) Explain your answer to (a) in terms of heat flow. [1] (c) In which hut did the air lose heat faster from 30 to 40 minutes? [1] (d) State one variable Jia Wei must keep the same for a fair test. [1]", marks: 4, kw: [["hut b", "lined", "with styrofoam", "the styrofoam hut"], ["poor conductor", "insulator", "reduce", "less heat", "slows", "more slowly"], ["hut a", "bare", "without styrofoam", "unlined", "not lined"], ["distance", "same lamp", "same type of lamp", "same power", "same size", "size of the hut", "same starting", "same initial", "starting temperature", "same metal", "same roof", "same place", "same thickness"]], model: "(a) Hut B, the hut with the styrofoam layer. (b) Styrofoam is a poor conductor of heat, so it reduces the heat flowing from the hot metal roof to the air inside the hut. (c) Hut A, the hut with the bare roof – its air temperature dropped by 7 °C, compared with 2 °C in hut B. (d) The distance between each lamp and its hut.", tbl: [["Time (min)", "Air in hut A (°C)", "Air in hut B (°C)"], ["0", "30", "30"], ["10", "36", "32"], ["20", "40", "34"], ["30", "42", "35"], ["40", "35", "33"]], x: 1 },
    { q: "At closing time, a hawker switched off the stoves under a large pot (10 litres) and a small pot (2 litres) of the same soup. Both pots were made of the same metal, and the soup in both was at 90 °C. The air in the hawker centre stayed at about 28 °C. The table shows the temperature of the soup. (a) By how many degrees did the soup in the large pot cool in the first 60 minutes? [1] (b) At 0 minutes, both pots of soup were at the same temperature. Explain why the large pot had more heat. [1] (c) Predict the temperature of the soup in both pots the next morning, and give a reason. [1]", marks: 3, kw: [["22"], ["more soup", "more water", "larger amount", "bigger amount", "greater amount", "more liquid", "larger volume", "bigger volume"], ["28", "room temperature"]], model: "(a) 22 °C (from 90 °C to 68 °C). (b) The large pot had more soup, so it had more heat even though both were at 90 °C. (c) Both would be at about 28 °C, the same temperature as the surrounding air, because the soup stops losing heat when it reaches room temperature.", tbl: [["Time (min)", "Large pot (°C)", "Small pot (°C)"], ["0", "90", "90"], ["30", "78", "62"], ["60", "68", "45"], ["90", "60", "37"]] },
    { q: "Mei wanted to find out if the colour of a can affects how fast cold water in it warms up. She set up cans A, B and C as shown and left them side by side in the Sun in the school garden. After 30 minutes, the water was at 27 °C in A, 19 °C in B and 15 °C in C. (a) What variable did Mei change? [1] (b) State one variable she kept the same. [1] (c) Which colour of can is best for keeping a cold drink cold in the Sun? [1] (d) Explain, in terms of heat, why the temperature of the water in all three cans rose. [1]", marks: 4, kw: [["colour", "color"], ["amount of water", "volume of water", "same amount", "same volume", "starting temperature", "initial temperature", "same starting", "same initial", "size of the can", "same size", "material of the can", "same material", "same place", "same spot", "same time"], ["silver", "can c"], ["gain", "absorb", "took in heat", "takes in heat"]], model: "(a) The colour of the can. (b) The amount of water in each can (200 ml). (c) Silver (can C), as its water had the lowest temperature after 30 minutes. (d) The cold water gained heat from the Sun and the warmer surrounding air, so its temperature rose.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Black metal can", "200 ml water", "Starts at 5 °C"] }, { label: "B", icon: "jar", lines: ["White metal can", "200 ml water", "Starts at 5 °C"] }, { label: "C", icon: "jar", lines: ["Silver metal can", "200 ml water", "Starts at 5 °C"] }] } },
    { q: "At a buffet, curry chicken is kept hot in a stainless steel tray that sits in a larger tray of hot water. A small flame heats the hot water from below. (a) Describe the path of heat flow from the flame to the curry. [1] (b) Why is the curry tray made of stainless steel? [1] (c) The serving ladle has a steel bowl and a plastic handle. Explain why the handle is made of plastic. [1]", marks: 3, kw: [["flame to", "water to the tray", "water to the steel", "through the tray", "through the steel", "through the metal"], ["good conductor", "conducts heat well", "conduct heat well", "heat flows easily", "heat flow easily", "heat to flow easily", "lets heat flow"], ["poor conductor", "insulator", "does not conduct", "does not let heat", "doesn't let heat"]], model: "(a) Heat flows from the flame to the hot water, then through the stainless steel tray to the curry. (b) Stainless steel is a good conductor of heat, so heat flows easily from the hot water to the curry and keeps it hot. (c) Plastic is a poor conductor of heat, so heat from the hot curry and the steel bowl does not flow easily to the server’s hand." }
  ],
  tf: [
    { s: "An object can gain heat only by touching something hotter.", a: false, why: "Heat from the Sun reaches and warms the Earth without the Sun touching it." },
    { s: "A thermometer should be read only after the liquid in it stops moving.", a: true, why: "While the liquid is still moving, it is still gaining or losing heat, so the reading is not yet the final temperature." },
    { s: "When a metal ring is heated, the hole in it becomes smaller.", a: false, why: "The whole ring gains heat and expands, so the hole becomes bigger, not smaller." },
    { s: "When steam condenses on a cool bathroom mirror, the mirror gains heat.", a: true, why: "The steam is hotter than the mirror, so heat flows from the steam to the mirror; the steam loses heat and condenses." },
    { s: "Fanning a bowl of hot soup cools it faster because the fan blows coldness into the soup.", a: false, why: "There is no flow of coldness. The moving air carries heat away from the soup faster, so the soup loses heat faster." },
    { s: "A can of drink at 5 °C placed in a freezer at −18 °C will lose heat.", a: true, why: "The air in the freezer is colder than the drink, so heat flows from the drink to the air even though the drink is already cold." },
    { s: "Water droplets forming on the outside of a glass of iced drink show that the glass is losing heat.", a: false, why: "The water vapour in the air loses heat to the cold glass and condenses; the glass gains heat." },
    { s: "The metal handle of a pot on a stove can become too hot to hold because heat is conducted from the pot along the handle.", a: true, why: "Metal is a good conductor of heat, so heat flows easily from the hot pot along the handle." },
    { s: "A thermometer in a cup of water at room temperature shows no reading because no heat is flowing.", a: false, why: "A thermometer still shows the temperature of the water (room temperature); no heat flow only means the reading stays steady." },
    { s: "Two objects of different materials that touch for a long time end up at the same temperature.", a: true, why: "Heat flows from the hotter one to the colder one until both are at the same temperature, whatever they are made of." }
  ]
};
