window.LBZ = window.LBZ || {};
LBZ["p4-heat"] = {
  flash: [
    { f: "Define: heat", b: "Heat is a form of energy. It flows from a hotter place or object to a colder one." },
    { f: "Define: temperature", b: "Temperature is a measure of how hot or cold something is. It is measured in degrees Celsius (°C) using a thermometer." },
    { f: "In which direction does heat flow, and when does it stop?", b: "Heat flows from a hotter object or place to a colder one. It stops flowing when both reach the same temperature." },
    { f: "Three effects of heat gain or heat loss", b: "A change in temperature, expansion or contraction, and a change of state." },
    { f: "What happens to most substances when they gain heat? When they lose heat?", b: "They gain heat and expand; they lose heat and contract. The volume changes but the mass stays the same." },
    { f: "Define: good conductor of heat", b: "A material that allows heat to flow through it easily, e.g. most metals such as copper, aluminium, iron and steel." },
    { f: "Define: poor conductor of heat", b: "A material that does not allow heat to flow through it easily, e.g. wood, plastic, rubber, glass, styrofoam and air." },
    { f: "Why does a metal spoon feel colder than a plastic spoon in the same drawer?", b: "Both are at the same temperature. Metal is a good conductor of heat, so it conducts heat away from the hand faster. The hand loses heat faster." },
    { f: "Why are gaps left between sections of railway tracks?", b: "On hot days, the metal tracks gain heat and expand. The gaps give them space to expand so that they do not bend." },
    { f: "How does a woollen sweater keep us warm?", b: "Wool traps air. Wool and air are poor conductors of heat, so they reduce the heat lost from our body to the cooler surroundings." },
    { f: "Why do water droplets form on the outside of a cold can of drink?", b: "Water vapour in the warmer surrounding air loses heat to the cold can and condenses into water droplets on its surface." },
    { f: "Why does the liquid in a thermometer rise in hot water?", b: "The liquid gains heat from the hot water and expands, so it moves up the tube." },
    { f: "On a cooling curve, what does the flat part at the end show?", b: "The object has reached room temperature, the same temperature as its surroundings, so heat stops flowing." },
    { f: "Why does boiling water stay at 100 °C even though it is still being heated?", b: "The heat gained is used to change the water into steam, so its temperature stays the same while it boils." },
    { f: "A big pot and a small cup of boiling water: which has more heat?", b: "Both are at the same temperature (100 °C), but the big pot has more heat because it has more water." }
  ],
  mcq: [
    { q: "Which of these materials is a poor conductor of heat?", o: ["Aluminium", "Rubber", "Iron", "Copper"], a: 1, why: "Rubber is a poor conductor of heat. Aluminium, iron and copper are metals, which are good conductors of heat.", lvl: 1 },
    { q: "At a hawker stall, the cook fries noodles in an iron wok over a gas flame. Why is the wok made of iron?", o: ["Iron produces its own heat when placed over the flame.", "Iron is a poor conductor of heat, so food stays hot longer.", "Iron keeps heat away from the food so it does not burn.", "Iron is a good conductor of heat, so heat flows quickly to the food."], a: 3, why: "Iron is a metal and a good conductor of heat, so heat flows quickly from the flame through the wok to the food. The iron does not produce heat itself – the burning gas does.", lvl: 1 },
    { q: "A beaker contains a mixture of melting ice and water. What is the most likely temperature of the mixture?", o: ["0 °C", "10 °C", "37 °C", "100 °C"], a: 0, why: "Ice melts at 0 °C, and the mixture stays at 0 °C while the ice is melting. 37 °C is body temperature and 100 °C is the boiling point of water.", lvl: 1 },
    { q: "Ravi recorded the temperature of the air in the school garden during one day. The graph shows his results. At what time was the air the warmest?", o: ["10 a.m.", "12 noon", "2 p.m.", "4 p.m."], a: 2, why: "The highest point on the graph is at 2 p.m. (33 °C), so the air was warmest then.", lvl: 1, fig: { type: "line", xl: "Time of day", yl: "Temperature of air (°C)", pts: [["8am", 27], ["10am", 29], ["12nn", 32], ["2pm", 33], ["4pm", 31], ["6pm", 29]] } },
    { q: "Which of these are sources of heat?\nA: A lit gas stove\nB: An ice cube\nC: A switched-on iron\nD: The human body", o: ["A and C only", "B and D only", "A, C and D only", "A, B, C and D"], a: 2, why: "Burning gas, electrical appliances and our bodies all give off heat. An ice cube does not give off heat to us – it gains heat from warmer things around it.", lvl: 2 },
    { q: "At a hawker centre, claypot rice is served in the clay pot it was cooked in. It stays hot longer than the same rice served in a thin steel bowl. Why?", o: ["Clay is a poor conductor of heat, so the rice loses heat more slowly.", "Clay is a good conductor of heat, so the rice gains heat from the air.", "Clay produces its own heat, so it keeps on warming the rice.", "Clay stops coldness in the air from flowing into the rice."], a: 0, why: "Clay is a poor conductor of heat, so less heat flows from the hot rice through the pot to the cooler air. Steel is a good conductor, so rice in the steel bowl loses heat faster. ‘Coldness’ does not flow.", lvl: 2 },
    { q: "Water in a beaker was heated over a flame. The table shows its temperature. During which period did the temperature of the water rise the most?", o: ["0 to 2 min", "2 to 4 min", "4 to 6 min", "6 to 8 min"], a: 1, why: "The rises were 12 °C (0–2 min), 15 °C (2–4 min), 8 °C (4–6 min) and 5 °C (6–8 min). The biggest rise was from 2 to 4 min.", lvl: 2, tbl: [["Time (min)", "Temperature of water (°C)"], ["0", "28"], ["2", "40"], ["4", "55"], ["6", "63"], ["8", "68"]] },
    { q: "A steel ruler was left in the hot sun until it became much hotter. Which statement about the ruler is correct?", o: ["It becomes slightly shorter, and its mass stays the same.", "It becomes slightly longer, and its mass increases.", "It stays exactly the same length and mass.", "It becomes slightly longer, and its mass stays the same."], a: 3, why: "The steel gains heat and expands, so the ruler becomes slightly longer. Expansion increases the volume, but the mass stays the same.", lvl: 2 },
    { q: "Hui Min wants to find out if the thickness of the walls of a box affects how long ice lasts in it. Which two set-ups should she compare?", o: ["P and Q", "P and S", "Q and R", "R and S"], a: 0, why: "P and Q differ only in the thickness of the walls. P and S differ in material, Q and R in the amount of ice, and R and S in three variables.", lvl: 2, fig: { type: "setups", items: [{ label: "P", icon: "box", lines: ["Styrofoam box", "1 cm thick walls", "50 g ice", "In the shade"] }, { label: "Q", icon: "box", lines: ["Styrofoam box", "3 cm thick walls", "50 g ice", "In the shade"] }, { label: "R", icon: "box", lines: ["Styrofoam box", "3 cm thick walls", "100 g ice", "In the shade"] }, { label: "S", icon: "box", lines: ["Plastic box", "1 cm thick walls", "50 g ice", "In the shade"] }] } },
    { q: "At a dim sum stall, water droplets form on the inside of the steamer lid. What happens to the steam to form these droplets?", o: ["The steam gains heat and condenses.", "The steam loses heat and condenses.", "The steam loses heat and freezes.", "The steam gains heat and boils."], a: 1, why: "The hot steam touches the cooler lid, loses heat to it and condenses into water droplets. Freezing would turn water into ice, and gaining heat would not turn steam into water.", lvl: 2 },
    { q: "Which of these is NOT a use of a poor conductor of heat?", o: ["A wooden handle on a frying pan", "A styrofoam box for keeping fish cold", "A woollen blanket on a cold night", "A copper base on a cooking pot"], a: 3, why: "Copper is a good conductor of heat; it is used for the base so heat flows quickly to the food. Wood, styrofoam and wool are poor conductors used to reduce heat flow.", lvl: 2 },
    { q: "In the afternoon, Mrs Lee switched on the air-conditioner in her HDB bedroom. The air in the room cooled to 24 °C, while the air outside was at 33 °C. Which statement about the glass window is correct?", o: ["Heat flows through the glass from the outside air into the room.", "Heat flows through the glass from the room to the outside air.", "Coldness flows through the glass from the room to the outside air.", "No heat flows through the glass, as glass is a poor conductor of heat."], a: 0, why: "Heat flows from the hotter outside air (33 °C) to the cooler room (24 °C). Glass is a poor conductor of heat, so it slows the flow, but some heat still passes through. ‘Coldness’ does not flow.", lvl: 3 },
    { q: "Identical ice cubes were wrapped in different materials of different thicknesses and left in the same room. The table shows how long each took to melt. Which conclusion is supported by the results?", o: ["Felt is a better insulator than cotton, and thicker wrapping makes ice last longer.", "Cotton is a better insulator than felt, and thicker wrapping makes ice last longer.", "Felt is a better insulator than cotton, but thickness does not affect the result.", "Thin felt is a better insulator of heat than thick cotton."], a: 0, why: "At the same thickness, felt kept ice longer than cotton (40 vs 30 min at 1 cm, 60 vs 45 min at 2 cm), and 2 cm always beat 1 cm of the same material. But 1 cm of felt (40 min) did worse than 2 cm of cotton (45 min).", lvl: 3, tbl: [["Set-up", "Material", "Thickness", "Time to melt (min)"], ["A", "Cotton", "1 cm", "30"], ["B", "Cotton", "2 cm", "45"], ["C", "Felt", "1 cm", "40"], ["D", "Felt", "2 cm", "60"]] },
    { q: "Ahmad boiled different amounts of tap water, all starting at 30 °C, in the same electric kettle. The graph shows how long each took to boil. Predict the time taken to boil 1250 ml of water.", o: ["About 13 min", "About 15 min", "About 18 min", "About 24 min"], a: 1, why: "Each extra 250 ml of water took 3 more minutes, because more water needs more heat to reach 100 °C. So 1250 ml takes about 12 + 3 = 15 min.", lvl: 3, fig: { type: "bar", xl: "Amount of water (ml)", yl: "Time taken to boil (min)", bars: [["250", 3], ["500", 6], ["750", 9], ["1000", 12]] } },
    { q: "At a school canteen, equal amounts of hot soup at 80 °C were put into bowls A, B, C and D, of the same size and thickness. In which bowl will the soup cool the fastest?", o: ["A", "B", "C", "D"], a: 2, why: "Metal is a good conductor of heat, so heat flows out through the metal bowl faster. The 22 °C room gives a bigger difference in temperature than the 32 °C one, so heat flows out faster still. C has both.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Plastic bowl", "Hot soup at 80 °C", "Room at 32 °C"] }, { label: "B", icon: "dish", lines: ["Metal bowl", "Hot soup at 80 °C", "Room at 32 °C"] }, { label: "C", icon: "dish", lines: ["Metal bowl", "Hot soup at 80 °C", "Room at 22 °C"] }, { label: "D", icon: "dish", lines: ["Plastic bowl", "Hot soup at 80 °C", "Room at 22 °C"] }] } },
    { q: "A beaker of water at room temperature was put into a basin of ice water. Later, it was taken out and left on the table. The graph shows the temperature of the water. Which describes what happened?", o: ["The water gained heat from the ice water until 15 min, then lost heat to the air.", "Coldness flowed into the water until 15 min, then flowed back out to the air.", "The water lost heat to the ice water until 15 min, then gained heat from the air.", "The water lost heat until 15 min, then stopped losing heat and stayed the same."], a: 2, why: "Until about 15 min the temperature fell, so the water was losing heat to the colder ice water. After it was taken out, its temperature rose towards room temperature (30 °C), so it was gaining heat from the warmer air.", lvl: 3, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 30], ["5", 18], ["10", 10], ["15", 7], ["20", 14], ["25", 20], ["30", 25], ["35", 28]] } },
    { q: "At a wet market, a fishmonger keeps fish on a thick layer of crushed ice. Which statements are correct?\nA: The ice gains heat from the fish and from the warmer air.\nB: The fish loses heat to the ice, so it stays cool.\nC: While the ice is melting, its temperature stays at about 0 °C.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 3, why: "The ice is colder than the fish and the air, so it gains heat from both (A), and the fish loses heat to the ice (B). While ice melts, the heat gained is used to melt it, so it stays at about 0 °C (C).", lvl: 3 },
    { q: "Equal amounts of hot water were poured into cups P and Q, of the same size but made of different materials, in the same room. The table shows the temperature of the water. Which statements are correct?\nA: Q is made of a better insulator of heat than P.\nB: At 50 min, the water in Q was still losing heat.\nC: If left for a long time, the water in Q will cool to about 31 °C.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "Q’s water cooled more slowly, so Q is the better insulator (A). P’s water levelled off at 31 °C, so the room is at 31 °C. Q’s water (41 °C) is still hotter than the room, so it is still losing heat (B) and will stop at about 31 °C (C).", lvl: 4, tbl: [["Time (min)", "Cup P (°C)", "Cup Q (°C)"], ["0", "90", "90"], ["10", "62", "75"], ["20", "45", "63"], ["30", "36", "53"], ["40", "31", "46"], ["50", "31", "41"]] },
    { q: "Beakers A and B, both starting at 30 °C, were heated over identical flames for 3 minutes. The water in A reached 70 °C. What is the temperature of the water in B most likely to be?", o: ["About 35 °C", "About 50 °C", "About 70 °C", "About 110 °C"], a: 1, why: "Identical flames for the same time give about the same amount of heat. B has twice as much water, so its rise is about half of A’s 40 °C rise: 30 + 20 = 50 °C. Water cannot go above 100 °C while it is liquid in an open beaker.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["100 ml water", "Starts at 30 °C", "Ends at 70 °C"] }, { label: "B", icon: "beaker", lines: ["200 ml water", "Starts at 30 °C", "Ends at ?"] }] } },
    { q: "To fit an iron rim tightly onto a wooden cart wheel, a worker makes the rim slightly smaller than the wheel. He heats the rim, slips it on, then pours cold water over it. Why does this work?", o: ["Heating makes the rim lose mass so it slides on, and cooling puts the mass back.", "Heating makes the wood contract so the rim fits, and cooling makes the wood expand.", "Heating makes the rim expand so it fits over, and cooling makes it contract and grip.", "Heating makes the rim softer so it stretches, and cooling makes it hard again."], a: 2, why: "The iron rim gains heat and expands, so its hole becomes big enough to fit over the wheel. The cold water makes it lose heat and contract, so it grips the wheel tightly. Its mass never changes.", lvl: 4 }
  ],
  tf: [
    { s: "A woollen blanket keeps us warm by producing heat.", a: false, why: "Wool does not produce heat. It traps air, and wool and air are poor conductors of heat, so it reduces the heat lost from our body." },
    { s: "An ice cube at 0 °C has no heat at all.", a: false, why: "Something at 0 °C still has heat; ice at 0 °C can even give heat to something colder, such as food at −18 °C in a freezer." },
    { s: "When a hot object touches a cold object, the cold object ends up at the hot object’s starting temperature.", a: false, why: "Heat flows until both are at the same temperature, which lies between their two starting temperatures." },
    { s: "The water droplets on the outside of a cold can of drink come from the drink leaking through the can.", a: false, why: "They come from water vapour in the surrounding air, which loses heat to the cold can and condenses." },
    { s: "The bigger the difference in temperature between hot water and the air around it, the more slowly the water loses heat.", a: false, why: "A bigger difference in temperature makes heat flow faster, so the water loses heat more quickly." },
    { s: "Hot water left in a fridge loses heat until it is at the same temperature as the air inside the fridge.", a: true, why: "Heat flows from the hotter water to the colder air in the fridge until both are at the same temperature." },
    { s: "Steam at 100 °C and boiling water at 100 °C are at the same temperature.", a: true, why: "Both read 100 °C on a thermometer, even though one is a gas and the other a liquid." },
    { s: "When heated, air expands more than a solid such as a metal does.", a: true, why: "Gases such as air expand the most when they gain heat; solids expand only a little." },
    { s: "Our body gives off heat to the surrounding air when the air is cooler than our body.", a: true, why: "Heat flows from our warmer body to the cooler surrounding air." },
    { s: "A metal pot handle covered with rubber is safer to hold because rubber is a poor conductor of heat.", a: true, why: "Rubber does not let heat flow through it easily, so less heat flows from the hot pot to the hand." }
  ],
  sort: [
    { title: "Is each material used here because it is a GOOD or a POOR conductor of heat?", groups: ["Good conductor of heat", "Poor conductor of heat"], items: [["copper base of a cooking pot", 0], ["iron wok at a hawker stall", 0], ["aluminium baking tray", 0], ["metal ice-cube tray, so water freezes quickly", 0], ["wooden spatula for stirring", 1], ["styrofoam cup for takeaway kopi", 1], ["cork mat under a hot claypot", 1], ["thick cloth oven glove", 1], ["plastic handle of an electric kettle", 1]] }
  ],
  oe: [
    { q: "A steel section of a railway track is 100 m long at 20 °C. The graph shows how much longer it becomes at higher temperatures. (a) Describe the relationship shown by the graph. (b) Predict the increase in length at 35 °C. (c) The section was laid on a day when it was at 20 °C. On a sunny afternoon, the steel reaches 60 °C. What is the smallest gap that must be left at its end? (d) Explain what would happen to the track that afternoon if no gap was left.", marks: 4, kw: [["higher the temperature", "temperature increases", "temperature rises", "hotter the", "higher temperature", "temperature is higher", "greater the increase", "the longer"], ["18"], ["48"], ["bend", "buckle", "curve", "warp", "out of shape"]], model: "(a) The higher the temperature of the steel, the greater the increase in its length. (b) About 18 mm. (c) 48 mm. (d) The steel would gain heat and expand by 48 mm, but there would be no space for it to expand into, so it would push against the next section and bend.", fig: { type: "line", xl: "Temperature of steel (°C)", yl: "Increase in length (mm)", pts: [["20", 0], ["30", 12], ["40", 24], ["50", 36], ["60", 48]] }, x: 1 },
    { q: "A canteen drinks vendor wanted to know which container keeps ice from melting for longer. Identical ice cubes were put into a metal tin and a styrofoam cup of the same size, both with lids, in the canteen. The time for the ice to melt completely was recorded three times, as shown in the table. (a) Calculate the average time for the ice in the styrofoam cup. (b) Which container keeps ice for longer? (c) Explain your answer to (b) in terms of heat flow. (d) Why was the experiment done three times?", marks: 4, kw: [["41"], ["styrofoam"], ["reduce", "less heat", "more slowly", "slower", "slows"], ["reliable"]], model: "(a) (41 + 39 + 43) ÷ 3 = 41 minutes. (b) The styrofoam cup. (c) Styrofoam is a poor conductor of heat, so it reduces the heat gained by the ice from the warmer surroundings. The ice gains heat more slowly and takes longer to melt. (d) To make the results more reliable, so that one wrong reading does not decide the result.", tbl: [["Container", "Trial 1 (min)", "Trial 2 (min)", "Trial 3 (min)"], ["Metal tin", "12", "13", "11"], ["Styrofoam cup", "41", "39", "43"]] },
    { q: "At a hawker centre, a drinks uncle ‘pulls’ hot teh tarik by pouring it from one mug into another from a height, so that it cools faster. (a) State the direction of heat flow as the teh cools. (b) Explain why pulling the teh makes it cool faster than leaving it in the mug. (c) Ming leaves another cup of hot teh on the table for two hours. Will it keep cooling until it is colder than the air? Explain.", marks: 3, kw: [["from the teh", "from the hot teh", "from the tea", "from the hot tea", "from teh", "from tea", "from hot teh", "from hot tea", "teh to", "tea to", "loses heat to"], ["surface", "exposed", "contact with the air", "more air"], ["room temperature", "same temperature"]], model: "(a) Heat flows from the hot teh to the cooler surrounding air. (b) As the teh is poured from a height, more of its surface is exposed to the cooler air, so it loses heat to the air faster. (c) No. It stops cooling when it reaches room temperature, the same temperature as the surrounding air, because heat then stops flowing." },
    { q: "Ravi and Ali heated identical beakers of water over identical flames. Ravi’s thermometer bulb touched the bottom of his beaker (A). Ali held his thermometer bulb in the middle of the water (B). (a) Whose reading is likely to be higher? (b) Explain why. (c) State one other thing a pupil must do when reading a thermometer to get an accurate reading.", marks: 3, kw: [["ravi", "set-up a", "beaker a"], ["hotter than the water", "bottom of the beaker is hotter", "beaker is hotter", "base is hotter", "glass is hotter", "heated directly", "directly heated", "nearer the flame", "closer to the flame", "closest to the flame"], ["eye level", "stops moving", "stop moving", "stopped moving", "stays still", "steady"]], model: "(a) Ravi’s reading (A). (b) The bottom of the beaker is heated directly by the flame, so it is hotter than the water. The bulb gains heat from the hot glass as well as from the water. (c) Read the scale with his eye level with the top of the liquid, after the liquid stops moving.", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Water over a flame", "Bulb touching bottom"] }, { label: "B", icon: "beaker", lines: ["Water over a flame", "Bulb in middle of water"] }] } }
  ]
};
