window.LB = window.LB || {};
LB["p4-heat"] = {
  notes: [
    { h: "Heat is a form of energy", t: "Heat is a form of energy. When an object gains heat, it becomes hotter; when it loses heat, it becomes colder. We cannot see heat, but we can feel it and observe and measure its effects.", kw: ["heat is a form of energy", "gains heat", "loses heat"] },
    { h: "Temperature", t: "Temperature is a measure of how hot or cold something is. It is measured in degrees Celsius (°C) using a thermometer. Heat and temperature are not the same: heat is a form of energy, while temperature tells us how hot or cold an object is.", kw: ["temperature", "degrees celsius", "thermometer"] },
    { h: "Measuring temperature", t: "The liquid in a thermometer gains heat and expands up the tube, or loses heat and contracts down the tube; read it with your eye level with the top of the liquid. A datalogger with a temperature sensor records the temperature automatically over a period of time and can show the results as a graph. Our sense of touch is not reliable for telling temperature.", kw: ["temperature sensor", "datalogger", "sense of touch is not reliable"] },
    { h: "Heat flows from hotter to colder", t: "Heat always flows from a hotter place or object to a colder one. The hotter object loses heat and its temperature drops; the colder object gains heat and its temperature rises. Heat stops flowing between them when both reach the same temperature.", kw: ["from a hotter", "to a colder", "same temperature"] },
    { h: "Heat gain and heat loss around us", t: "A bowl of hot laksa loses heat to the cooler surrounding air until it reaches room temperature, then it stops cooling. A cold drink gains heat from the warmer surrounding air until it reaches room temperature. When you hold an ice cube, your hand loses heat to the ice – coldness does not flow.", kw: ["surrounding air", "room temperature"] },
    { h: "Sources of heat", t: "The Sun is our main source of heat. Heat is also produced by burning (for example gas in a stove, a candle, wood), by electrical appliances such as irons, kettles and ovens, and when we rub our hands together. Our bodies also give off heat.", kw: ["the sun", "burning", "electrical appliances"] },
    { h: "Effect of heat: change in temperature", t: "When an object gains heat, its temperature increases; when it loses heat, its temperature decreases. The longer water is heated with the same flame, the more heat it gains and the higher its temperature rises. With the same amount of heat, a smaller amount of water shows a bigger rise in temperature than a larger amount.", kw: ["temperature increases", "temperature decreases"] },
    { h: "Expansion and contraction", t: "Most solids, liquids and gases expand when they gain heat and contract when they lose heat. When something expands, its volume increases but its mass stays the same. Gases like air expand the most when heated.", kw: ["gains heat and expands", "loses heat and contracts"] },
    { h: "Expansion and contraction in daily life", t: "Gaps are left between railway tracks and between parts of a bridge so the metal can expand on hot days without bending. Telephone and electrical wires sag more on hot days (they expand) and are tighter on cold days (they contract), so they are put up slightly loose. A tight metal cap on a glass bottle loosens in hot water because the metal cap gains heat and expands; a dented ping-pong ball pops out in hot water because the air inside gains heat and expands.", kw: ["gaps", "sag", "expands"] },
    { h: "Change of state", t: "Gaining heat can change a solid into a liquid (melting, e.g. ice melts) and a liquid into a gas (boiling or evaporation, e.g. water becomes steam). Losing heat can change a gas into a liquid (condensation, e.g. steam becomes water droplets on a cold lid) and a liquid into a solid (freezing, e.g. water becomes ice).", kw: ["melt", "boil", "condense", "freeze"] },
    { h: "Good and poor conductors of heat", t: "A good conductor of heat lets heat flow through it easily; most metals such as copper, aluminium, iron and steel are good conductors of heat. A poor conductor of heat does not let heat flow through it easily, e.g. plastic, wood, rubber, glass, cloth, styrofoam and air. Pots have metal bases so heat is conducted quickly to the food, but plastic or wooden handles so heat does not flow easily to our hands. A metal object feels colder than a wooden one at the same temperature because metal conducts heat away from our hand faster.", kw: ["good conductor of heat", "poor conductor of heat", "conducts heat away"] },
    { h: "Keeping things hot or cold", t: "Poor conductors of heat (insulators) reduce heat gain and heat loss. A flask has a plastic stopper and a vacuum between its double walls to reduce heat flow, so it keeps hot drinks hot and cold drinks cold. Styrofoam cooler boxes reduce heat gained from the warmer surroundings, and woollen clothes trap air, a poor conductor of heat, to reduce heat lost from our bodies.", kw: ["poor conductor", "trapped air", "reduce heat"] }
  ],
  traps: [
    "‘Coldness flows from the ice into my hand’ -> there is no flow of coldness; heat flows from the hand to the ice, so the hand loses heat and feels cold.",
    "‘The metal chair is colder than the wooden chair’ -> in the same room both are at the same temperature; metal only FEELS colder because it conducts heat away from your hand faster.",
    "‘Heat and temperature are the same thing’ -> heat is a form of energy; temperature is how hot or cold something is, measured in °C.",
    "‘Wrapping ice in a woollen cloth makes it melt faster because wool is warm’ -> wool is a poor conductor of heat, so it reduces the heat the ice gains and the ice melts more slowly.",
    "‘Hot soup left on the table keeps cooling until it is ice-cold’ -> it only cools until it reaches room temperature, then heat stops flowing.",
    "‘A cooler box makes things cold’ -> it does not produce coldness; it only reduces the heat gained from the warmer surroundings.",
    "‘A steeper cooling curve means a better insulator’ -> a steeper drop means heat is lost faster, so the container is a poorer insulator (a better conductor).",
    "‘When an object expands, it becomes heavier’ -> its volume increases but its mass stays the same."
  ],
  lessons: [
    {
      h: "Explaining heat flow the marker’s way",
      concept: "Every heat-flow answer needs three things: WHICH object is hotter, the DIRECTION heat flows (from the hotter object to the colder one), and the RESULT (one gains heat and its temperature rises; the other loses heat and its temperature drops, until both are at the same temperature). Never write that ‘cold’ or ‘coldness’ flows – only heat flows.",
      example: {
        q: "Ben held an ice cube in his palm. After a while, his palm felt cold and the ice cube started to melt. Explain both observations.",
        marks: 2,
        think: [
          "Step 1: Decide which is hotter: Ben’s palm (about 37 °C) is hotter than the ice cube.",
          "Step 2: State the direction: heat flows from his palm to the ice cube.",
          "Step 3: Link each observation: the palm loses heat, so it feels cold; the ice gains heat, so it melts."
        ],
        answer: "Ben’s palm was hotter than the ice cube, so heat flowed from his palm to the ice cube. His palm lost heat, so it felt cold. The ice cube gained heat and melted."
      },
      tip: "Use the pair ‘X loses heat to Y’ / ‘Y gains heat from X’ – it forces you to give the direction.",
      try: {
        q: "A cup of hot milk at 80 °C is placed in a basin of water at 25 °C. Which statement best describes what happens?",
        o: ["Heat flows from the water to the milk until the milk is at 25 °C.", "Heat flows from the milk to the water until both are at the same temperature.", "Coldness flows from the water into the milk until the milk is at 25 °C.", "Heat flows from the milk to the water until the milk is colder than the water."],
        a: 1,
        why: "The milk is hotter, so heat flows from the milk to the water. It stops when both reach the same temperature – the milk never becomes colder than the water, and ‘coldness’ does not flow."
      }
    },
    {
      h: "Reading cooling curves",
      concept: "On a temperature–time graph, a steeper drop means heat is being lost faster. A cooling curve drops fastest at the start, when the object is much hotter than its surroundings, then flattens out. It levels off at room temperature, because the object and the air are now at the same temperature and heat stops flowing – it never drops below room temperature on its own. The container whose water shows the smallest drop in the same time is the best insulator (poorest conductor of heat).",
      example: {
        q: "Hot water was left in a beaker in a classroom. The graph shows its temperature. (a) What was the temperature of the classroom? (b) Explain why the temperature of the water stopped falling.",
        fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 85], ["5", 63], ["10", 49], ["15", 40], ["20", 35], ["25", 31], ["30", 30], ["35", 30]] },
        marks: 2,
        think: [
          "Step 1: Find where the line becomes flat – from 30 min it stays at 30 °C.",
          "Step 2: Water stops cooling only when it reaches the temperature of the surroundings, so the room was about 30 °C.",
          "Step 3: Explain with heat flow: once the water and the surrounding air are at the same temperature, there is no more heat flow from the water to the air."
        ],
        answer: "(a) About 30 °C. (b) The water had reached the same temperature as the surrounding air, so heat no longer flowed from the water to the air."
      },
      tip: "The flat part of a cooling curve = room temperature. The steepest part = fastest heat loss.",
      try: {
        q: "Hot water at 90 °C was poured into four cups made of different materials W, X, Y and Z. The graph shows the drop in temperature of the water after 20 minutes. Which material is the best for making a cup to keep drinks hot?",
        fig: { type: "bar", xl: "Material of cup", yl: "Drop in temperature after 20 min (°C)", bars: [["W", 30], ["X", 12], ["Y", 22], ["Z", 6]] },
        o: ["W", "X", "Y", "Z"],
        a: 3,
        why: "The water in cup Z had the smallest drop in temperature, so Z let the least heat flow out: Z is the poorest conductor of heat. W, with the biggest drop, is the best conductor and the worst choice."
      }
    },
    {
      h: "Why metal feels colder",
      concept: "Objects left in the same place for a long time are all at the same temperature (room temperature), whatever they are made of. Metal feels colder than wood or plastic because metal is a good conductor of heat: it conducts heat away from your hand faster, so your hand loses heat faster and feels colder. Always say BOTH ideas – same temperature, and faster heat loss from the hand.",
      example: {
        q: "Mei touched a metal railing and a wooden bench at the void deck. Both had been in the shade all day. The metal railing felt colder. Explain why.",
        marks: 2,
        think: [
          "Step 1: Both have been in the same place all day, so they are at the same temperature.",
          "Step 2: Metal is a good conductor of heat; wood is a poor conductor of heat.",
          "Step 3: Heat flows from her hand faster into the metal, so her hand loses heat faster and the metal feels colder."
        ],
        answer: "Both the railing and the bench were at the same temperature. Metal is a good conductor of heat, so it conducts heat away from her hand faster than wood, which is a poor conductor of heat. Her hand loses heat faster, so the metal railing feels colder."
      },
      tip: "‘Feels colder’ is about how fast your hand LOSES heat, not about the object’s temperature.",
      try: {
        q: "A steel spoon and a plastic spoon have been in the same drawer overnight. The steel spoon feels colder. Which statement explains this?",
        o: ["The steel spoon is at a lower temperature than the plastic spoon.", "Coldness flows from the steel spoon into the hand.", "The plastic spoon gives out heat to the hand.", "The steel spoon conducts heat away from the hand faster than the plastic spoon."],
        a: 3,
        why: "Both spoons are at the same temperature. Steel is a good conductor of heat, so heat flows from the hand into it faster and the hand loses heat faster. There is no ‘coldness’ flow, and plastic does not give out heat."
      }
    },
    {
      h: "Explaining expansion and contraction",
      concept: "A full expansion answer names the object or substance, says whether it GAINS or LOSES heat, says whether it EXPANDS or CONTRACTS, and links this to what is seen. For example: ‘The metal cap gains heat from the hot water and expands, so it becomes loose.’ Remember that the mass does not change – only the volume.",
      example: {
        q: "Small gaps are left between sections of railway tracks. (a) Explain why the gaps are needed. (b) Predict what happens to the gaps on a cold night.",
        marks: 3,
        think: [
          "Step 1: Railway tracks are metal. On a hot day they gain heat and expand.",
          "Step 2: The gaps give the tracks space to expand, so they do not push against each other and bend.",
          "Step 3: On a cold night the tracks lose heat and contract, so the gaps become wider."
        ],
        answer: "(a) On hot days, the metal tracks gain heat and expand. The gaps give them space to expand so that the tracks do not bend. (b) The tracks lose heat and contract, so the gaps become wider."
      },
      tip: "Gain heat → expand; lose heat → contract. Say which one AND what it causes.",
      try: {
        q: "Telephone wires are hung between two poles. At which time will the wires sag the most?",
        o: ["At 3 a.m. on a cool night", "At 2 p.m. on a hot sunny day", "At 7 a.m. on a cool rainy morning", "The wires sag the same amount all day"],
        a: 1,
        why: "On a hot afternoon the wires gain the most heat and expand, so they become longer and sag more. At night and on cool mornings they lose heat and contract, so they are tighter."
      }
    },
    {
      h: "Planning a fair test on conductors and insulators",
      concept: "To find out which material is the best insulator, change ONLY the material. Keep everything else the same: the amount of water, the starting temperature, the size and thickness of the wrapping or container, and where it is placed. Measure the temperature at the same time intervals (a datalogger with a temperature sensor is ideal). The material whose water has the smallest drop in temperature (hot water) or smallest rise (cold water) is the best insulator.",
      example: {
        q: "Ravi wanted to find out which material, cotton or felt, keeps water hot longer. He set up A and B as shown. (a) What variable did he change? (b) State one variable he kept the same. (c) How will he know which material keeps water hot longer?",
        fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Wrapped in cotton", "200 ml water", "Starts at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Wrapped in felt", "200 ml water", "Starts at 80 °C"] }] },
        marks: 3,
        think: [
          "Step 1: Compare A and B line by line – only the wrapping material is different.",
          "Step 2: The amount of water (200 ml) and the starting temperature (80 °C) are the same.",
          "Step 3: After the same time, the water with the higher temperature (smaller drop) was wrapped in the better material."
        ],
        answer: "(a) The type of material used to wrap the beaker. (b) The amount of water (200 ml) or its starting temperature (80 °C). (c) He measures the temperature of the water in both beakers after the same amount of time. The beaker whose water has the higher temperature (smaller drop) is wrapped in the material that keeps water hot longer."
      },
      tip: "Before choosing two set-ups, cross out any pair that differs in more than one line.",
      try: {
        q: "Lina wants to find out if the material of a cup affects how fast hot water cools. Which two set-ups should she compare?",
        fig: { type: "setups", items: [{ label: "P", icon: "beaker", lines: ["Metal cup", "150 ml water", "Starts at 70 °C"] }, { label: "Q", icon: "beaker", lines: ["Glass cup", "100 ml water", "Starts at 70 °C"] }, { label: "R", icon: "beaker", lines: ["Glass cup", "150 ml water", "Starts at 70 °C"] }, { label: "S", icon: "beaker", lines: ["Metal cup", "150 ml water", "Starts at 90 °C"] }] },
        o: ["P and S", "Q and R", "P and Q", "P and R"],
        a: 3,
        why: "P and R differ only in the material of the cup. P and S differ in starting temperature, Q and R in amount of water, and P and Q in both material and amount of water."
      }
    }
  ],
  mcq: [
    { q: "Which of the following best describes heat?", o: ["A form of energy", "A measure of how hot or cold something is", "A type of matter", "A kind of gas"], a: 0, why: "Heat is a form of energy. Temperature, not heat, is the measure of how hot or cold something is.", lvl: 1 },
    { q: "Which instrument should Amir use to measure the temperature of a cup of water?", o: ["Measuring cylinder", "Thermometer", "Electronic balance", "Stopwatch"], a: 1, why: "A thermometer measures temperature. A measuring cylinder measures volume, a balance measures mass and a stopwatch measures time.", lvl: 1 },
    { q: "What is the main source of heat for the Earth?", o: ["The Moon", "Electric heaters", "The Sun", "Burning wood"], a: 2, why: "The Sun is our main source of heat. Heaters and burning also give heat, but only for small areas; the Moon does not produce heat.", lvl: 1 },
    { q: "In which unit is temperature measured?", o: ["gram (g)", "centimetre (cm)", "millilitre (ml)", "degree Celsius (°C)"], a: 3, why: "Temperature is measured in degrees Celsius (°C). Grams measure mass, centimetres length and millilitres volume.", lvl: 1 },
    { q: "Which material is a good conductor of heat?", o: ["Rubber", "Copper", "Wood", "Styrofoam"], a: 1, why: "Copper is a metal and conducts heat well. Rubber, wood and styrofoam are poor conductors of heat.", lvl: 1 },
    { q: "When most substances gain heat, they …", o: ["contract", "lose mass", "expand", "gain mass"], a: 2, why: "Most substances expand when they gain heat. Their mass stays the same; only their volume increases.", lvl: 1 },
    { q: "Why are the handles of cooking pots usually made of plastic?", o: ["Plastic is a good conductor of heat.", "Plastic keeps the pot cold.", "Plastic is stronger than metal.", "Plastic is a poor conductor of heat."], a: 3, why: "Plastic is a poor conductor of heat, so heat from the hot pot does not flow easily to the hand. It does not keep the pot cold.", lvl: 1 },
    { q: "The graph shows the temperatures of four things. Which is the hottest?", o: ["Cup of kopi", "Classroom", "Fridge", "Ice water"], a: 0, why: "The cup of kopi has the tallest bar (70 °C), so it has the highest temperature.", lvl: 1, fig: { type: "bar", xl: "Thing", yl: "Temperature (°C)", bars: [["Classroom", 30], ["Fridge", 5], ["Cup of kopi", 70], ["Ice water", 0]] } },
    { q: "Siti places an ice cube on her palm. Which statement is correct?", o: ["Heat flows from the ice cube to her palm.", "Coldness flows from the ice cube to her palm.", "Heat flows from her palm to the ice cube.", "No heat flows because the ice cube is a solid."], a: 2, why: "Her palm is hotter than the ice, so heat flows from her palm to the ice. ‘Coldness’ does not flow.", lvl: 2 },
    { q: "A beaker of hot water was left on a table in a room. The graph shows its temperature. What was most likely the temperature of the room?", o: ["0 °C", "30 °C", "43 °C", "90 °C"], a: 1, why: "The water stops cooling at 30 °C, when it reaches the temperature of the surrounding air. It cannot cool below room temperature on its own.", lvl: 2, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 90], ["10", 60], ["20", 43], ["30", 34], ["40", 30], ["50", 30]] } },
    { q: "The metal cap of a glass bottle is stuck. Which is the best way to loosen it?", o: ["Put the bottle in the freezer.", "Put the cap in ice water.", "Wrap the cap in a woollen cloth.", "Hold the cap under hot running water."], a: 3, why: "The metal cap gains heat from the hot water and expands, so it becomes loose. Cooling the cap makes it contract and fit even more tightly.", lvl: 2 },
    { q: "Four rods of the same size were each placed in a beaker of hot water at the same temperature, with a small piece of butter stuck on the top end of each. On which rod will the butter melt first?", o: ["A", "B", "C", "D"], a: 0, why: "Steel is a metal and a good conductor of heat, so heat is conducted up rod A fastest. Wood, plastic and glass are poor conductors of heat.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Steel rod", "Butter at top end"] }, { label: "B", icon: "beaker", lines: ["Wooden rod", "Butter at top end"] }, { label: "C", icon: "beaker", lines: ["Plastic rod", "Butter at top end"] }, { label: "D", icon: "beaker", lines: ["Glass rod", "Butter at top end"] }] } },
    { q: "A metal railing and a wooden bench have been in the same shady spot all day. The metal railing feels colder to touch. Why?", o: ["The metal railing is at a lower temperature than the bench.", "Metal conducts heat away from the hand faster than wood.", "The wooden bench gives heat to the hand, but metal does not.", "Metal lets coldness flow into the hand faster than wood."], a: 1, why: "Both are at the same temperature. Metal is a good conductor of heat, so the hand loses heat faster to it and it feels colder.", lvl: 2 },
    { q: "Identical ice cubes were wrapped in equal-sized pieces of materials P, Q, R and S. The graph shows how long each ice cube took to melt completely. Which material is the most suitable for making a cooler box?", o: ["P", "Q", "R", "S"], a: 2, why: "The ice wrapped in R took the longest to melt, so R let the least heat flow from the surroundings to the ice. R is the poorest conductor of heat.", lvl: 2, fig: { type: "bar", xl: "Material", yl: "Time for ice to melt (min)", bars: [["P", 20], ["Q", 30], ["R", 60], ["S", 45]] } },
    { q: "Which change takes place when a substance LOSES heat?", o: ["Water turns into ice.", "Ice melts into water.", "Water boils into steam.", "Butter melts in a hot pan."], a: 0, why: "Water freezes into ice when it loses heat. Melting and boiling need a substance to gain heat.", lvl: 2 },
    { q: "Mei put a dented ping-pong ball into hot water and the dent popped out. Why?", o: ["The hot water pressed on the outside of the ball and pushed the dent out.", "The air inside the ball lost heat and contracted, pulling the dent out.", "Hot water entered the ball through the dent and filled it back up.", "The air inside the ball gained heat and expanded, pushing the dent out."], a: 3, why: "The air inside gains heat from the hot water and expands, pushing the dented shell outwards. Losing heat would make the air contract.", lvl: 2 },
    { q: "Study the Venn diagram. Which statement is correct?", o: ["All good conductors of heat are attracted by a magnet.", "Copper is a poor conductor of heat.", "Some good conductors of heat are not attracted by a magnet.", "Plastic is a good conductor of heat."], a: 2, why: "Copper and aluminium are good conductors of heat but are not attracted by a magnet, so only SOME good conductors are magnetic.", lvl: 2, fig: { type: "venn", a: "Good conductor of heat", b: "Attracted by magnet", onlyA: ["copper", "aluminium"], both: ["iron", "steel"], onlyB: [], neither: ["wood", "plastic"] } },
    { q: "Why might a scientist use a datalogger with a temperature sensor instead of a thermometer?", o: ["It makes the water heat up faster so the experiment takes less time.", "It can record the temperature automatically over a long period of time.", "It gives off heat to the water so the temperature stays steady.", "It measures the mass of the water as well as its temperature."], a: 1, why: "A datalogger records readings automatically at regular times and can show them as a graph. It does not heat the water or measure mass.", lvl: 2 },
    { q: "A glass of cold water from the fridge was left on a table. The graph shows its temperature. Which describes what happened between 0 and 40 minutes?", o: ["It gained heat from the surrounding air.", "It lost heat to the surrounding air.", "Its temperature decreased.", "It gave coldness to the surrounding air."], a: 0, why: "The temperature rose, so the water gained heat from the warmer surrounding air. Its temperature increased, not decreased.", lvl: 2, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 5], ["10", 15], ["20", 22], ["30", 27], ["40", 29], ["50", 29]] } },
    { q: "Three identical ice cubes were placed on plates in the same room. Which ice cube will take the longest to melt?", o: ["A", "B", "C", "All will melt at the same time"], a: 2, why: "Wool is a poor conductor of heat and traps air, so it reduces the heat the ice gains from the surroundings. The ice in C melts most slowly.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Ice cube", "Not wrapped"] }, { label: "B", icon: "plate", lines: ["Ice cube", "Wrapped in", "aluminium foil"] }, { label: "C", icon: "plate", lines: ["Ice cube", "Wrapped in a thick", "woollen cloth"] }] } },
    { q: "Study the cooling curve of a cup of hot water. During which period did the water lose heat the fastest?", o: ["10 to 15 min", "20 to 25 min", "25 to 30 min", "0 to 5 min"], a: 3, why: "From 0 to 5 min the temperature fell by 20 °C, the steepest drop. The drop gets smaller as the water gets closer to room temperature.", lvl: 2, fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 80], ["5", 60], ["10", 48], ["15", 40], ["20", 35], ["25", 32], ["30", 31]] } },
    { q: "Study the classification chart. Which material could be B?", o: ["Iron", "Copper", "Wood", "Glass"], a: 1, why: "B is a good conductor of heat that is not attracted by a magnet: copper. Iron would be A; wood and glass are poor conductors of heat.", lvl: 2, fig: { type: "flow", root: "Materials", node: { q: "Good conductor of heat?", yes: { q: "Attracted by magnet?", yes: "A", no: "B" }, no: { q: "Is it transparent?", yes: "C", no: "D" } } } },
    { q: "Hot water at 90 °C was poured into cups made of materials K, L and M. The graph shows the drop in temperature after 10 minutes. Which statement is correct?", o: ["K is the best insulator of heat of the three materials.", "L is the best conductor of heat of the three materials.", "M loses heat more slowly than L, so M is a better insulator.", "K is the best conductor of heat of the three materials."], a: 3, why: "The water in K lost the most heat (largest drop), so K conducts heat best. L, with the smallest drop, is the best insulator, and M loses heat faster than L.", lvl: 3, fig: { type: "bar", xl: "Material of cup", yl: "Drop in temperature (°C)", bars: [["K", 25], ["L", 8], ["M", 15]] } },
    { q: "Ken wants to find out if the material of a cup affects how fast hot water cools. Which two set-ups should he compare?", o: ["A and B", "A and D", "B and C", "C and D"], a: 0, why: "A and B differ only in the material. A and D differ in starting temperature, B and C in amount of water, and C and D in three variables.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Metal cup", "100 ml water", "Starts at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Plastic cup", "100 ml water", "Starts at 80 °C"] }, { label: "C", icon: "beaker", lines: ["Plastic cup", "200 ml water", "Starts at 80 °C"] }, { label: "D", icon: "beaker", lines: ["Metal cup", "100 ml water", "Starts at 60 °C"] }] } },
    { q: "Which of the following is NOT an example of expansion or contraction?", o: ["Gaps between railway tracks become smaller on a hot day.", "Telephone wires sag on a hot afternoon.", "Wet clothes dry in the sun.", "A dented ping-pong ball pops back into shape in hot water."], a: 2, why: "Wet clothes dry because the water evaporates – a change of state, not expansion. The other three are caused by materials gaining heat and expanding.", lvl: 3 },
    { q: "Beakers A and B were heated over identical flames for 3 minutes. Which statement is most likely correct?", o: ["The temperature of the water in A rises more.", "The temperature of the water in B rises more.", "The temperatures in A and B rise by the same amount.", "The temperatures do not change, because the water is already warm."], a: 0, why: "Both beakers get about the same amount of heat, but A has less water, so its temperature rises more. The larger amount in B needs more heat for the same rise.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["100 ml water", "Starts at 30 °C", "Same flame"] }, { label: "B", icon: "beaker", lines: ["300 ml water", "Starts at 30 °C", "Same flame"] }] } },
    { q: "A datalogger recorded the temperature of a liquid that was heated and then taken off the heat. At what time was the heat source most likely removed?", o: ["4 min", "6 min", "8 min", "12 min"], a: 1, why: "The temperature rose until 6 min and fell after that, so the liquid stopped gaining heat at 6 min. At 8 min it was already cooling.", lvl: 3, fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 30], ["2", 45], ["4", 60], ["6", 75], ["8", 70], ["10", 62], ["12", 55]] } },
    { q: "Small gaps are left between sections of a steel bridge. What happens to these gaps on a very hot afternoon?", o: ["They become wider.", "They stay the same size.", "They fill with rainwater.", "They become narrower."], a: 3, why: "The steel sections gain heat and expand, so they take up more space and the gaps become narrower. On cold nights the sections contract and the gaps widen.", lvl: 3 },
    { q: "Workers put up telephone wires slightly loose instead of pulling them tight. Why?", o: ["Loose wires carry telephone signals faster than tight wires do.", "On hot days, the wires contract, and wires that are too tight could snap.", "On cold days, the wires contract, and wires that are too tight could snap.", "On cold days, the wires lose mass and become too thin to hold."], a: 2, why: "On cold days the wires lose heat and contract (become shorter). If they were already tight, they could snap. Wires expand, not contract, on hot days, and their mass does not change.", lvl: 3 },
    { q: "A balloon was stretched over the mouth of an empty glass flask. The flask was put into hot water and the balloon became inflated. The flask was then moved into ice water, as shown in B. What will most likely happen?", o: ["The balloon will inflate even more as the air inside expands.", "The balloon will go flat and may be pulled into the mouth of the flask.", "The balloon will burst because the cold makes the rubber brittle.", "Nothing will change, as the balloon stays the same size once inflated."], a: 1, why: "In ice water, the air in the flask loses heat and contracts, so it takes up less space and the balloon goes flat and may be pulled inwards.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Flask with balloon", "In hot water", "Balloon inflates"] }, { label: "B", icon: "beaker", lines: ["Same flask", "Moved to ice water", "Balloon: ?"] }] } },
    { q: "Water at 90 °C was poured into containers W, X, Y and Z, made of different materials. The room was at 30 °C. The graph shows the temperatures after 30 minutes. Which statement is correct?", o: ["W is best for keeping soup hot, and Z is made of the best conductor of heat.", "Z is best for keeping soup hot, and W is made of the best conductor of heat.", "W is best for keeping soup hot, and X is made of the best conductor of heat.", "Y is made of the best insulator of heat, so it is best for keeping soup hot."], a: 0, why: "W’s water stayed hottest (least heat lost), so W is the best insulator. Z’s water was coolest (most heat lost), so Z is the best conductor of heat.", lvl: 3, fig: { type: "bar", xl: "Container", yl: "Temperature after 30 min (°C)", bars: [["W", 70], ["X", 45], ["Y", 58], ["Z", 38]] } },
    { q: "An iron block and a wooden block were left overnight in a room at 28 °C. Mei measured them with a thermometer and then touched them. Which statement is correct?", o: ["The iron is at a lower temperature than the wood, so the iron feels colder.", "Both are at 28 °C, but the iron feels colder as it conducts heat from her hand faster.", "Both are at 28 °C, but the wood feels colder as it conducts heat from her hand faster.", "The wood is at a higher temperature than the iron, because wood keeps heat in."], a: 1, why: "After a night in the same room, both blocks are at room temperature. Iron is a good conductor of heat, so her hand loses heat faster to it and it feels colder – touch is not a reliable measure of temperature.", lvl: 3 },
    { q: "A metal block at 60 °C was placed in water at 30 °C in a covered styrofoam cup. After some time, what are the most likely temperatures?", o: ["The block is still at 60 °C, while the water has warmed up to 45 °C.", "The block has cooled to 30 °C, while the water has warmed up to 60 °C.", "The block and water are at the same temperature, between 30 °C and 60 °C.", "The block has become colder than the water, which is now above 30 °C."], a: 2, why: "Heat flows from the hotter block to the colder water until both reach the same temperature, which lies between 30 °C and 60 °C. The block cannot end up colder than the water.", lvl: 3 },
    { q: "The steel lid of a glass jar is stuck. Ali pours hot water over the lid only. Siti puts the whole jar in the freezer. Whose method will help to open the jar?", o: ["Siti only", "Both Ali and Siti", "Neither of them", "Ali only"], a: 3, why: "The steel lid gains heat from the hot water and expands, so it loosens. In the freezer the lid loses heat and contracts, making it even tighter.", lvl: 3 },
    { q: "A metal ball can just pass through a metal ring. After the ball was heated, it could no longer pass through. Which action would MOST likely let the hot ball pass through the ring again?", o: ["Heat the ring as well.", "Cool the ring in ice water.", "Heat the ball for a longer time.", "Wrap the ball in a woollen cloth."], a: 0, why: "Heating the ring makes the whole ring expand, including its hole, so the hole becomes bigger. Cooling the ring would make the hole smaller, and heating the ball more makes it even bigger.", lvl: 4 },
    { q: "In a room at 30 °C, a can of drink at 5 °C and a cup of tea at 80 °C were each wrapped in a thick woollen cloth. Identical ones were left unwrapped. After 20 minutes, how do the wrapped ones compare with the unwrapped ones?", o: ["The wrapped drink is colder and the wrapped tea is hotter.", "The wrapped drink is warmer and the wrapped tea is hotter.", "The wrapped drink is colder and the wrapped tea is cooler.", "There is no difference, because wool does not produce heat."], a: 0, why: "Wool is a poor conductor of heat, so it reduces the heat the cold drink GAINS and the heat the hot tea LOSES. The wrapped drink stays colder and the wrapped tea stays hotter.", lvl: 4 },
    { q: "A beaker of hot water was left on a table in a room at 30 °C. At 20 minutes, something was done to the beaker. Study the graph. What was most likely done?", o: ["The beaker was wrapped in a woollen cloth.", "More hot water was added.", "The water reached room temperature.", "The beaker was placed in a basin of ice water."], a: 3, why: "After 20 min the water cooled faster and dropped below 30 °C, which is only possible if it was put in colder surroundings. Wrapping would slow the cooling, and adding hot water would raise the temperature.", lvl: 4, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 80], ["5", 62], ["10", 50], ["15", 43], ["20", 40], ["25", 24], ["30", 14], ["35", 10]] } },
    { q: "A cup of water at 90 °C is left in a room at 30 °C. Its temperature drops by 12 °C in the first 5 minutes. What is the most likely drop in temperature in the NEXT 5 minutes?", o: ["More than 12 °C", "Exactly 12 °C", "0 °C, because it has stopped cooling", "Less than 12 °C"], a: 3, why: "Water cools fastest when it is much hotter than its surroundings. After the first 5 min it is closer to room temperature, so it loses heat more slowly and drops by less than 12 °C.", lvl: 4 },
    { q: "The water in beakers A and B was poured together into a styrofoam cup and stirred. What is the temperature of the mixture most likely to be, just after mixing?", o: ["20 °C", "45 °C", "70 °C", "90 °C"], a: 1, why: "Heat flows from the hot water to the cold water until they are at the same temperature. With equal amounts, the mixture ends up about halfway, near 45 °C – it cannot be hotter than 70 °C or colder than 20 °C.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["100 ml water", "70 °C"] }, { label: "B", icon: "beaker", lines: ["100 ml water", "20 °C"] }] } },
    { q: "Two identical ice cubes were placed on trays of the same size and thickness, as shown, in a room at 30 °C. Which ice cube melts completely first, and why?", o: ["A, because the metal tray is at a higher temperature than the plastic tray.", "B, because plastic is a poor conductor and so traps heat under the ice.", "A, because the metal tray conducts heat from the surroundings to the ice faster.", "Both at the same time, because both trays are at the same room temperature."], a: 2, why: "Metal is a good conductor of heat, so heat from the surroundings flows through the metal tray to the ice faster, and ice A melts first. Both trays are at room temperature – the metal tray is not hotter, it simply conducts heat faster than plastic.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Ice cube", "On a metal tray", "Room at 30 °C"] }, { label: "B", icon: "plate", lines: ["Ice cube", "On a plastic tray", "Room at 30 °C"] }] } }
  ],
  tf: [
    { s: "Heat is a form of energy.", a: true, why: "Heat is a form of energy that flows from hotter to colder places." },
    { s: "Heat and temperature mean the same thing.", a: false, why: "Heat is a form of energy; temperature is a measure of how hot or cold something is." },
    { s: "When you hold an ice cube, coldness flows from the ice into your hand.", a: false, why: "Heat flows from your hand to the ice; there is no flow of coldness." },
    { s: "Heat flows from a hotter object to a colder object.", a: true, why: "Heat always flows from a hotter place or object to a colder one." },
    { s: "A cup of hot tea left on a table will keep cooling until it reaches 0 °C.", a: false, why: "It stops cooling when it reaches room temperature." },
    { s: "A metal chair feels colder than a wooden chair in the same room because the metal is at a lower temperature.", a: false, why: "Both are at the same temperature; metal conducts heat away from your body faster." },
    { s: "Most metals are good conductors of heat.", a: true, why: "Metals such as copper, aluminium and steel let heat flow through them easily." },
    { s: "Wrapping an ice cube in a woollen cloth makes it melt faster because wool is warm.", a: false, why: "Wool is a poor conductor of heat, so it reduces heat gain and the ice melts more slowly." },
    { s: "A cooler box keeps drinks cold by reducing the heat they gain from the warmer surroundings.", a: true, why: "Styrofoam is a poor conductor of heat, so less heat flows into the box." },
    { s: "Gaps are left between sections of railway tracks so that the tracks can expand on hot days without bending.", a: true, why: "The metal tracks gain heat and expand; the gaps give them space." },
    { s: "Telephone wires sag more on a cold night than on a hot afternoon.", a: false, why: "Wires expand and sag more on a hot afternoon; they contract and tighten on a cold night." },
    { s: "When an object expands, its mass increases.", a: false, why: "Only its volume increases; its mass stays the same." },
    { s: "A datalogger with a temperature sensor can record changes in temperature over a period of time.", a: true, why: "It takes readings automatically and can display them as a graph." },
    { s: "Air is a poor conductor of heat.", a: true, why: "That is why trapped air in wool and styrofoam helps to reduce heat flow." },
    { s: "Our sense of touch is a reliable way to measure temperature.", a: false, why: "Touch can be misleading (metal feels colder than wood at the same temperature); use a thermometer." },
    { s: "When steam loses heat, it condenses into water.", a: true, why: "Losing heat changes a gas into a liquid – condensation." },
    { s: "A steeper cooling curve shows that the container is a better insulator of heat.", a: false, why: "A steeper drop means heat is lost faster, so the container is a poorer insulator." },
    { s: "The liquid in a thermometer rises because it gains heat and expands.", a: true, why: "The liquid expands up the narrow tube when it gains heat." },
    { s: "A plastic spoon in hot soup becomes hot at the handle faster than a metal spoon.", a: false, why: "Metal is a good conductor of heat, so the metal spoon’s handle gets hot faster." },
    { s: "Heat stops flowing between two objects that touch once they reach the same temperature.", a: true, why: "Heat flows only when there is a difference in temperature." }
  ],
  sort: [
    { title: "Sort these materials into good and poor conductors of heat.", groups: ["Good conductor of heat", "Poor conductor of heat"], items: [["copper", 0], ["steel", 0], ["aluminium", 0], ["iron", 0], ["wood", 1], ["plastic", 1], ["rubber", 1], ["glass", 1], ["styrofoam", 1], ["woollen cloth", 1]] },
    { title: "In each example, does the thing named first GAIN or LOSE heat?", groups: ["Gains heat", "Loses heat"], items: [["ice cream melting in the sun", 0], ["hot soup cooling on the table", 1], ["water boiling in a kettle", 0], ["a puddle drying up after rain", 0], ["water turning into ice in a freezer", 1], ["steam turning into droplets on a cold lid", 1], ["liquid rising in a thermometer", 0], ["a cold drink warming up on the table", 0], ["your hand holding an ice cube", 1]] },
    { title: "Is each example caused by expansion or contraction?", groups: ["Expansion", "Contraction"], items: [["telephone wires sagging on a hot day", 0], ["gaps between railway tracks closing on a hot day", 0], ["a metal cap loosening in hot water", 0], ["thermometer liquid falling in ice water", 1], ["a balloon shrinking in the freezer", 1], ["a dented ping-pong ball popping out in hot water", 0], ["bridge gaps widening on a cold night", 1], ["telephone wires becoming tight on a cold morning", 1]] }
  ],
  oe: [
    { q: "A beaker of hot water was left in a room. The graph shows its temperature. (a) What was the room temperature? (b) Explain why the temperature of the water stopped falling. (c) The experiment is repeated with the beaker wrapped in a thick woollen cloth. How would the temperature of the water change in the first 30 minutes compared with before?", marks: 3, kw: [["28"], ["same temperature"], ["slower", "more slowly", "less quickly", "less steep", "smaller drop", "drop less", "drops less", "fall less", "falls less", "decrease less", "decreases less"]], model: "(a) About 28 °C. (b) The water had reached the same temperature as the surrounding air, so heat stopped flowing from the water to the air. (c) The temperature would drop more slowly, because wool is a poor conductor of heat and reduces the heat lost by the water.", fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 90], ["10", 58], ["20", 42], ["30", 34], ["40", 30], ["50", 28], ["60", 28]] } },
    { q: "Hot soup at 90 °C was poured into a red, a blue and a green bowl, each made of a different material. The graph shows the temperature of the soup after 15 minutes. (a) Which material is best for making a bowl to keep soup hot? (b) Explain your answer using the graph. (c) State one variable that must be kept the same for a fair test.", marks: 3, kw: [["blue"], ["highest", "smallest drop", "least heat", "hottest", "dropped the least", "lost the least", "slowest"], ["same amount", "same volume", "same starting", "same initial", "same size", "same thickness", "same shape", "same place", "same room", "same type of soup"]], model: "(a) The material of the blue bowl. (b) The soup in the blue bowl had the highest temperature after 15 minutes, so it lost the least heat. That material is the poorest conductor of heat. (c) The same amount of soup must be used in each bowl.", fig: { type: "bar", xl: "Bowl", yl: "Temperature after 15 min (°C)", bars: [["Red", 52], ["Blue", 74], ["Green", 61]] } },
    { q: "Jun wanted to find out which material keeps ice from melting for the longest time. (a) What is the variable he changed? (b) What should he measure? (c) Set-up C is not suitable. Explain why.", marks: 3, kw: [["type of material", "material used", "kind of material", "wrapping material", "material of"], ["time", "how long"], ["bigger", "larger", "more ice", "size", "not the same", "different"]], model: "(a) The type of material used to wrap the ice. (b) The time taken for each ice cube to melt completely. (c) Set-up C uses a bigger ice cube, so the size of the ice is different and it is not a fair test.", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["10 g ice cube", "Wrapped in cotton", "Room at 30 °C"] }, { label: "B", icon: "plate", lines: ["10 g ice cube", "Wrapped in felt", "Room at 30 °C"] }, { label: "C", icon: "plate", lines: ["30 g ice cube", "Wrapped in wool", "Room at 30 °C"] }] } },
    { q: "Farah touched a metal railing and a wooden bench at a bus stop. Both had been in the shade all day. The metal railing felt colder. Explain why.", marks: 2, kw: [["same temperature"], ["conducts heat away", "conduct heat away", "conducts heat from", "conduct heat from", "loses heat faster", "lose heat faster", "lost heat faster", "heat away from her hand faster", "heat flows faster", "heat flowed faster"]], model: "Both were at the same temperature. Metal is a good conductor of heat, so it conducts heat away from her hand faster than wood. Her hand loses heat faster, so the metal feels colder." },
    { q: "Small gaps are left between the sections of railway tracks. (a) Explain why these gaps are needed. (b) What might happen to the tracks on a very hot day if there were no gaps?", marks: 2, kw: [["expand"], ["bend", "buckle", "curve", "warp", "out of shape"]], model: "(a) On hot days, the metal tracks gain heat and expand; the gaps give them space to expand. (b) The tracks would push against each other and bend, which could cause a train accident." },
    { q: "The metal cap of a glass bottle of sauce is stuck. (a) Suggest a simple way to loosen the cap. (b) Explain how your method works.", marks: 2, kw: [["hot water", "hot running water", "warm water"], ["expand"]], model: "(a) Hold the metal cap under hot running water. (b) The metal cap gains heat and expands, so it becomes loose and is easier to open." },
    { q: "A flask keeps hot drinks hot. It has a plastic stopper and double glass walls with a vacuum between them. (a) Why is the stopper made of plastic? (b) How does the flask keep the drink hot? (c) Can the same flask keep a cold drink cold on a hot day? Explain.", marks: 3, kw: [["poor conductor"], ["reduce", "less heat", "slows", "slow down"], ["heat gain", "gaining heat", "gains heat", "gain heat", "heat gained", "gains less heat", "gain less heat"]], model: "(a) Plastic is a poor conductor of heat, so little heat flows out through the stopper. (b) The stopper and the vacuum reduce the heat lost from the hot drink to the surroundings. (c) Yes. The flask also reduces heat flow into the flask, so the cold drink gains heat from the warmer surroundings very slowly and stays cold." },
    { q: "A liquid was heated, and at one point the heat source was removed. A datalogger recorded its temperature, as shown in the graph. (a) At what time was the heat source removed? (b) How do you know? (c) Predict the temperature of the liquid after it has been left for a very long time. Give a reason.", marks: 3, kw: [["9"], ["decrease", "drop", "fall", "went down", "goes down", "start to cool", "started to cool", "loses heat", "lose heat", "losing heat"], ["28"]], model: "(a) At 9 minutes. (b) The temperature rose until 9 minutes and started to drop after that, so the liquid was losing heat instead of gaining heat. (c) About 28 °C, the room temperature, which was the temperature of the liquid at the start. The liquid stops cooling when it reaches the same temperature as its surroundings.", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 28], ["3", 40], ["6", 52], ["9", 64], ["12", 58], ["15", 53], ["18", 49]] } },
    { q: "Two identical ice cubes were placed on trays of the same size and thickness in a room at 30 °C, as shown. (a) Which ice cube will melt completely first? (b) Explain your answer. (c) Siti says, ‘The metal tray feels colder, so the ice on it will melt more slowly.’ Which tray would you use to stop a block of ice from melting quickly at a party?", marks: 3, kw: [["metal", "cube a", "tray a"], ["good conductor", "conducts heat", "conduct heat", "heat is conducted", "conducted"], ["plastic", "tray b"]], model: "(a) A, the ice cube on the metal tray. (b) Metal is a good conductor of heat, so heat from the surroundings is conducted through the metal tray to the ice faster. (c) The plastic tray B, because plastic is a poor conductor of heat and reduces the heat gained by the ice.", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Ice cube", "On a metal tray"] }, { label: "B", icon: "plate", lines: ["Ice cube", "On a plastic tray"] }] }, x: 1 },
    { q: "At a picnic, Hana wrapped a cold can of drink in a thick woollen scarf. Her friend said, ‘That will make your drink warm, because wool keeps us warm!’ (a) Is her friend right? (b) Explain what the woollen scarf does. (c) Describe how the scarf affects the drink.", marks: 3, kw: [["not right", "wrong", "not correct", "incorrect"], ["poor conductor", "traps air", "trapped air", "trap air"], ["heat gain", "gaining heat", "gains heat", "gain heat", "heat gained", "gains less heat", "gain less heat"]], model: "(a) Her friend is not right. (b) Wool does not produce heat. It traps air and is a poor conductor of heat, so it reduces heat flow. (c) The scarf reduces the heat the drink gains from the warmer surroundings, so the drink gains heat more slowly and stays cold for longer.", x: 1 },
    { q: "Four rods (red, blue, green and yellow) made of different materials, of the same length and thickness, were heated at one end. A pin was stuck with wax to the other end of each rod. The graph shows the time taken for each pin to drop. (a) Which rod is the best conductor of heat? (b) Which rod would be most suitable for making the handle of a frying pan? (c) Explain your answer to (b).", marks: 3, kw: [["blue"], ["green"], ["poor conductor", "longest", "most time", "slowest", "least heat"]], model: "(a) The blue rod. (b) The green rod. (c) The pin on the green rod took the longest time to drop, so heat flowed through it most slowly. It is the poorest conductor of heat, so less heat will flow from the hot pan to the hand.", fig: { type: "bar", xl: "Rod", yl: "Time for pin to drop (s)", bars: [["Red", 60], ["Blue", 25], ["Green", 240], ["Yellow", 110]] } },
    { q: "Telephone wires are hung between poles. (a) Why do the wires sag more on a hot afternoon? (b) Why do workers put up the wires slightly loose instead of pulling them tight?", marks: 2, kw: [["expand"], ["contract", "snap", "break"]], model: "(a) On a hot afternoon, the wires gain heat and expand, so they become longer and sag more. (b) On cold days the wires lose heat and contract. If they were put up tight, they could snap." },
    { q: "A balloon was stretched over the mouth of an empty flask. The flask was placed in hot water, as shown in A, and the balloon became inflated. (a) Explain why the balloon became inflated. (b) The flask was then moved into ice water, as shown in B. Predict what would happen to the balloon and explain why.", marks: 3, kw: [["gains heat", "gain heat", "gained heat"], ["expand"], ["contract"]], model: "(a) The air inside the flask gains heat from the hot water and expands, so it pushes into the balloon and inflates it. (b) The balloon goes flat. The air inside the flask loses heat to the ice water and contracts, so it takes up less space.", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Flask with balloon", "In hot water"] }, { label: "B", icon: "beaker", lines: ["Same flask", "In ice water"] }] } },
    { q: "Mei poured 100 ml of water at 80 °C and 100 ml of water at 20 °C into a styrofoam cup and stirred. (a) Predict the temperature of the mixture just after mixing. (b) Explain what happened in terms of heat flow. (c) The mixture is then left in a room at 30 °C for two hours. What will its temperature be?", marks: 3, kw: [["50"], ["from the hot", "from the hotter", "hot water lost", "hot water loses", "hotter water lost", "hotter water loses"], ["30", "room temperature"]], model: "(a) About 50 °C. (b) Heat flowed from the hot water to the cold water until they were at the same temperature. The hot water lost heat and the cold water gained heat, so the mixture ended up between 20 °C and 80 °C. (c) About 30 °C – the mixture loses heat to the cooler surrounding air until it reaches room temperature.", x: 1 }
  ],
  doc: [
    { q: "Ben held an ice cube and his hand felt cold. Explain why.", marks: 2, answers: ["Coldness from the ice cube flowed into my hand.", "My hand was hotter than the ice cube, so heat flowed from my hand to the ice cube. My hand lost heat, so it felt cold.", "Because the ice cube is very cold."], best: 1, why: "Answer 2 gives the direction of heat flow (hand to ice) and the result (hand loses heat). Answer 1 has the flow backwards – coldness does not flow. Answer 3 only repeats the question without any heat flow." },
    { q: "Why are the handles of cooking pots made of plastic?", marks: 2, answers: ["Plastic is a poor conductor of heat, so heat from the hot pot does not flow easily to the hand. The handle is safe to hold.", "Because plastic is not hot.", "Plastic is a good insulator, so it keeps the pot hot."], best: 0, why: "Answer 1 states the property (poor conductor of heat) and links it to the hand. Answer 2 is vague and has no science keyword. Answer 3 gives a wrong purpose – the handle is there to protect the hand, not to keep the pot hot." },
    { q: "Explain why gaps are left between sections of railway tracks.", marks: 2, answers: ["So that the train can go faster.", "The tracks expand.", "On hot days, the metal tracks gain heat and expand. The gaps give them space to expand so they do not bend."], best: 2, why: "Answer 3 says the tracks gain heat and expand AND why the gaps matter (so they do not bend). Answer 2 is too short – it misses when and why the gaps are needed. Answer 1 is not scientific." },
    { q: "A metal spoon and a wooden spoon are in the same drawer. Explain why the metal spoon feels colder.", marks: 2, answers: ["The metal spoon is colder than the wooden spoon.", "Both spoons are at the same temperature, but metal is a good conductor of heat, so it conducts heat away from my hand faster. My hand loses heat faster.", "Metal is a good conductor of heat."], best: 1, why: "Answer 2 has both ideas: same temperature, and heat is conducted away from the hand faster. Answer 1 is wrong – both are at the same temperature. Answer 3 gives the property but does not link it to the hand losing heat." },
    { q: "Explain how a styrofoam cooler box keeps drinks cold.", marks: 2, answers: ["Styrofoam is a poor conductor of heat, so it reduces the heat gained by the drinks from the warmer surroundings. The drinks stay cold longer.", "Styrofoam keeps the cold in.", "Styrofoam is a poor conductor of heat."], best: 0, why: "Answer 1 names the property and explains the heat flow (less heat gained from the surroundings). Answer 2 treats ‘cold’ as something that flows. Answer 3 gives the property but not how it keeps the drinks cold." }
  ]
};
