window.LB = window.LB || {};
LB["p4-light"] = {
  notes: [
    { h: "Sources of light", t: "A source of light is an object that gives out its own light. Examples are the Sun, other stars, a lit bulb, a torch that is switched on, a burning candle, fire and a firefly. Light is a form of energy.", kw: ["source of light", "gives out its own light", "form of energy"] },
    { h: "Not a source of light", t: "Objects such as the Moon, a mirror, a reflective strip on a safety vest and a shiny spoon do not give out their own light. They only reflect light that falls on them. The Moon shines at night because it reflects light from the Sun.", kw: ["does not give out its own light", "reflects light from the Sun", "the Moon is not a source of light"] },
    { h: "How we see things", t: "We see a source of light when the light it gives out enters our eyes. We see other objects when light from a source falls on them, is reflected by them and the reflected light enters our eyes. Our eyes receive light; they do not give out light.", kw: ["light enters our eyes", "reflected light enters our eyes", "reflected by the object"] },
    { h: "Darkness", t: "In a completely dark room there is no light. No light can be reflected by the objects into our eyes, so we cannot see them even with our eyes open. This is why a torch is needed in a dark cupboard.", kw: ["no light", "no light is reflected into our eyes"] },
    { h: "Light travels in straight lines", t: "Light travels in straight lines. We can see a torch through holes in three cards only when the holes are in a straight line. Because light cannot bend around an object, shadows are formed and we cannot see around a corner.", kw: ["light travels in straight lines", "holes in a straight line"] },
    { h: "Reflection", t: "Reflection is the bouncing back of light when it hits a surface. All objects we can see reflect some light. Smooth, shiny surfaces such as mirrors, polished steel and still water reflect light well, while dull, rough or dark surfaces reflect less light.", kw: ["reflection", "smooth, shiny surfaces reflect light well", "reflect less light"] },
    { h: "Using mirrors: the periscope", t: "A periscope has two mirrors placed parallel to each other, each tilted at 45°. Light from an object enters the top opening, is reflected by the top mirror down to the bottom mirror, which reflects it into the viewer’s eyes. It lets us see over walls or crowds. Car side mirrors and the convex mirrors at blind corners of HDB car parks also use reflection.", kw: ["reflected by the top mirror", "reflected by the bottom mirror", "enters the eyes"] },
    { h: "Transparent, translucent, opaque", t: "A transparent material allows most light to pass through (clear glass, clear plastic, clean water). A translucent material allows some light to pass through (frosted glass, tracing paper, a thin plastic file). An opaque material does not allow light to pass through (wood, metal, cardboard, a brick wall).", kw: ["allows most light to pass through", "allows some light to pass through", "does not allow light to pass through"] },
    { h: "Measuring light with a light sensor", t: "A light sensor (connected to a datalogger) measures the amount of light reaching it. The higher the reading, the more light passes through the material placed in front of it. For a fair test, keep the torch, its distance from the sensor, the thickness and size of the material the same, and do it in a dark room so that only the torch light is measured.", kw: ["light sensor", "higher reading, more light passes through", "same distance", "dark room"] },
    { h: "How shadows are formed", t: "A shadow is formed when light is blocked by an opaque or translucent object. Light travels in straight lines, so it cannot reach the area behind the object. An opaque object blocks all the light and forms a dark shadow; a translucent object blocks some light and forms a lighter shadow; a transparent object does not form a clear shadow.", kw: ["light is blocked", "opaque object", "light travels in straight lines", "lighter shadow"] },
    { h: "Size and shape of shadows", t: "When an object is moved closer to the light source, it blocks more light and its shadow becomes bigger. When the object is moved closer to the screen (further from the light source), the shadow becomes smaller and sharper. The shape of the shadow follows the outline of the object and can change when the object is turned (a cup looks like a circle from the top but a trapezium-like shape from the side).", kw: ["closer to the light source, bigger shadow", "closer to the screen, smaller shadow", "outline of the object", "turned"] },
    { h: "Shadows through the day", t: "The position of the Sun in the sky changes during the day: it rises in the east and sets in the west. A shadow always forms on the side of the object opposite the Sun, so a morning shadow points west and an evening shadow points east. Shadows are longest when the Sun is low (morning and evening) and shortest around noon when the Sun is high in the sky.", kw: ["opposite side from the Sun", "longest in the morning and evening", "shortest around noon", "Sun is high in the sky"] }
  ],
  traps: [
    "The Moon is a source of light -> the Moon only reflects light from the Sun; it does not give out its own light.",
    "A mirror gives out light -> a mirror only reflects light; it is not a source of light.",
    "We see because our eyes send out light -> we see when light from a source, or light reflected by an object, ENTERS our eyes.",
    "Saying only ‘the object is dark’ for a shadow -> say ‘the opaque object blocks light’ and ‘light travels in straight lines’.",
    "Translucent objects do not form shadows -> they block some light and form a lighter (fainter) shadow.",
    "Moving the object closer to the torch makes the shadow smaller -> it makes the shadow BIGGER, because the object blocks more light.",
    "A higher light sensor reading means the material blocks more light -> a higher reading means MORE light passes through.",
    "The morning shadow points east -> the Sun is in the east in the morning, so the shadow points WEST, away from the Sun."
  ],
  lessons: [
    {
      h: "Explaining how we see an object",
      concept: "Full marks need the whole path of the light: light from a SOURCE falls on the object, the object REFLECTS the light, and the reflected light ENTERS the eyes. If the object is itself a source of light, the light it gives out enters the eyes directly. Missing ‘reflected’ or ‘enters the eyes’ usually costs a mark.",
      example: {
        q: "Wei Ming is reading a storybook under a lamp. Explain how he is able to see the book.",
        marks: 2,
        think: [
          "Step 1: Is the book a source of light? No, it does not give out its own light.",
          "Step 2: So light must come from a source: the lamp gives out light that falls on the book.",
          "Step 3: The book reflects the light, and the reflected light travels in a straight line into Wei Ming’s eyes."
        ],
        answer: "Light from the lamp falls on the book. The book reflects the light and the reflected light enters Wei Ming’s eyes, so he can see the book."
      },
      tip: "Write the path as a chain: source -> object (reflects) -> eyes (enters). Never write that the eyes ‘look at’ or ‘shine on’ the object.",
      try: {
        q: "Aisyah can see the Moon on a clear night. Which shows the correct path of the light that lets her see it?",
        o: ["Eyes -> Moon", "Moon -> Sun -> eyes", "Sun -> Moon -> eyes", "Moon -> eyes only, because the Moon gives out light"],
        a: 2,
        why: "The Sun is the source of light. The Moon reflects the Sun’s light, and the reflected light enters Aisyah’s eyes. The Moon does not give out its own light, and eyes do not send out light."
      }
    },
    {
      h: "Explaining how a shadow is formed",
      concept: "A shadow answer needs two ideas: the object is OPAQUE (or translucent) so it BLOCKS light, and light TRAVELS IN STRAIGHT LINES so it cannot bend around the object to reach the area behind it. A translucent object only blocks some light, so its shadow is lighter.",
      example: {
        q: "Meiling shone a torch at a wooden block placed in front of a screen. A dark shadow appeared on the screen. Explain how the shadow was formed.",
        marks: 2,
        think: [
          "Step 1: Name the material type: wood is opaque, so it does not allow light to pass through.",
          "Step 2: So the block blocks the light from the torch.",
          "Step 3: Light travels in straight lines and cannot bend around the block, so the area on the screen behind the block receives no light."
        ],
        answer: "The wooden block is opaque and blocks the light from the torch. Light travels in straight lines, so it cannot bend around the block to reach the area of the screen behind it. A dark shadow is formed there."
      },
      tip: "Two keywords, two marks: ‘blocks light’ + ‘travels in straight lines’. ‘The block is in the way’ alone is too vague.",
      try: {
        q: "A sheet of tracing paper forms a faint shadow on a screen, but a cardboard sheet of the same size forms a dark one. Why?",
        o: ["Tracing paper reflects all the light back towards the torch", "Tracing paper allows some light to pass through, so it blocks less light", "Cardboard gives out a dark colour that makes its shadow darker", "Light bends around tracing paper but not around cardboard"],
        a: 1,
        why: "Tracing paper is translucent: it allows some light to pass through, so less light is blocked and the shadow is lighter. Cardboard is opaque and blocks all the light. Light does not bend around either sheet."
      }
    },
    {
      h: "Reading light sensor results",
      concept: "A light sensor measures how much light reaches it. The material in front of it with the HIGHEST reading allows the most light through (most transparent); a reading of 0 in a dark room means no light passed through (opaque). Always choose the material by matching its reading to what the job needs, and quote the reading as evidence.",
      example: {
        q: "Ravi placed four materials, one at a time, between a torch and a light sensor in a dark room. Study the graph. Which material is most suitable for making blinds that keep a bedroom dark in the afternoon? Explain using the results.",
        fig: { type: "bar", title: "Light reaching the sensor", xl: "Material", yl: "Light sensor reading (units)", bars: [["P", 640], ["Q", 15], ["R", 0], ["S", 310]] },
        marks: 2,
        think: [
          "Step 1: What does the job need? The blinds should allow as little light through as possible.",
          "Step 2: Lowest reading = least light passing through. R has a reading of 0.",
          "Step 3: So R did not allow light to pass through: it is opaque. Give the claim (R) and the evidence (reading of 0)."
        ],
        answer: "Material R. The light sensor reading for R was 0, the lowest, so R did not allow any light to pass through. Blinds made of R will block the sunlight and keep the bedroom dark."
      },
      tip: "Higher reading = MORE light passed through. Say this link in words, then quote the number.",
      try: {
        q: "Using the same graph, which material allows some light, but not most light, to pass through, and is best for a toilet window that lets light in but stops people seeing clearly inside?",
        fig: { type: "bar", title: "Light reaching the sensor", xl: "Material", yl: "Light sensor reading (units)", bars: [["P", 640], ["Q", 15], ["R", 0], ["S", 310]] },
        o: ["P", "Q", "R", "S"],
        a: 3,
        why: "S lets through a moderate amount of light (310 units), so it is translucent and lets daylight in while people cannot see clearly through it. P lets most light through (transparent), so people could see in. Q lets too little light in to brighten the toilet, and R lets none through."
      }
    },
    {
      h: "Shadow size and distance",
      concept: "With the light source and screen fixed, moving the object CLOSER to the light source makes it block more light, so the shadow gets BIGGER. Moving it closer to the screen makes the shadow SMALLER. In a graph, describe the trend with both variables: ‘As the distance between X and Y increases, the height of the shadow decreases.’",
      example: {
        q: "A torch and a screen were kept 60 cm apart. A card was placed at different distances from the torch and the height of its shadow was measured. Study the graph. Describe the relationship shown and explain why the shadow changes in this way.",
        fig: { type: "line", title: "Height of shadow", xl: "Distance of card from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 60], ["20", 30], ["30", 20], ["40", 15], ["50", 12]] },
        marks: 2,
        think: [
          "Step 1: Read the trend: as distance goes up from 10 cm to 50 cm, shadow height falls from 60 cm to 12 cm.",
          "Step 2: State it with both variables named.",
          "Step 3: Explain: nearer the torch, the card blocks more of the light spreading out from the torch, so a bigger area of the screen gets no light."
        ],
        answer: "As the distance between the card and the torch increases, the height of the shadow decreases. When the card is closer to the torch, it blocks more light, so the shadow is bigger."
      },
      tip: "Always name both variables and the direction of change. ‘It gets smaller’ without saying what changes costs the mark.",
      try: {
        q: "Using the graph, what was the height of the shadow when the card was 30 cm from the torch?",
        fig: { type: "line", title: "Height of shadow", xl: "Distance of card from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 60], ["20", 30], ["30", 20], ["40", 15], ["50", 12]] },
        o: ["20 cm", "30 cm", "15 cm", "60 cm"],
        a: 0,
        why: "Find 30 cm on the horizontal axis and read up to the line: the shadow was 20 cm tall. 30 cm is the reading at 20 cm from the torch."
      }
    },
    {
      h: "Shadows through the day",
      concept: "The Sun rises in the east, is high in the sky around noon, and sets in the west. A shadow is always on the side of the object AWAY from the Sun. A low Sun (morning, evening) gives a long shadow; a high Sun (around noon) gives the shortest shadow. Use shadow length to work out the Sun’s position, and shadow direction to work out where the Sun is.",
      example: {
        q: "Nurul measured the length of the shadow of a lamp post in her school field at different times of the day. Study the graph. At about what time was the Sun highest in the sky? In which direction did the shadow point at 9 a.m.? Explain.",
        fig: { type: "bar", title: "Shadow of a lamp post", xl: "Time of day", yl: "Length of shadow (m)", bars: [["9 a.m.", 7], ["11 a.m.", 3], ["1 p.m.", 1], ["3 p.m.", 3], ["5 p.m.", 7]] },
        marks: 3,
        think: [
          "Step 1: Shortest shadow = Sun highest. The shortest bar is at 1 p.m. (1 m).",
          "Step 2: At 9 a.m. the Sun is in the east, low in the sky.",
          "Step 3: The shadow forms on the side away from the Sun, so it points west, and it is long because the Sun is low."
        ],
        answer: "At about 1 p.m., because the shadow was the shortest then. At 9 a.m. the shadow pointed west, because the Sun was in the east and the shadow forms on the side of the lamp post opposite the Sun."
      },
      tip: "Short shadow = high Sun; long shadow = low Sun. Shadow direction is always opposite to the Sun.",
      try: {
        q: "At 5 p.m. the shadow of the lamp post in the graph points east. Where is the Sun?",
        fig: { type: "bar", title: "Shadow of a lamp post", xl: "Time of day", yl: "Length of shadow (m)", bars: [["9 a.m.", 7], ["11 a.m.", 3], ["1 p.m.", 1], ["3 p.m.", 3], ["5 p.m.", 7]] },
        o: ["High in the sky in the east", "Directly above the lamp post", "Low in the sky in the east", "Low in the sky in the west"],
        a: 3,
        why: "The shadow points east, so the Sun is on the opposite side, the west. The shadow is long (7 m), so the Sun is low in the sky."
      }
    }
  ],
  mcq: [
    { q: "Which one of the following is a source of light?", o: ["The Moon", "A mirror", "A burning candle", "A polished steel spoon"], a: 2, why: "A burning candle gives out its own light. The Moon, a mirror and a shiny spoon only reflect light that falls on them.", lvl: 1 },
    { q: "Why can we see the Moon at night?", o: ["It reflects light from the Sun.", "It gives out its own light.", "It is very hot.", "Our eyes give out light that shines on it."], a: 0, why: "The Moon is not a source of light. It reflects light from the Sun, and this reflected light enters our eyes.", lvl: 1 },
    { q: "Which material is opaque?", o: ["Clear glass", "Tracing paper", "Frosted glass", "Cardboard"], a: 3, why: "Cardboard does not allow light to pass through, so it is opaque. Clear glass is transparent; tracing paper and frosted glass are translucent.", lvl: 1 },
    { q: "A shadow is formed when ______.", o: ["light is reflected by a mirror", "light is blocked by an object", "light passes through clear glass", "an object gives out light"], a: 1, why: "A shadow forms when an opaque or translucent object blocks light, so light cannot reach the area behind it.", lvl: 1 },
    { q: "Which object is used to see over a wall and uses two mirrors?", o: ["A magnifying glass", "A torch", "A periscope", "A light sensor"], a: 2, why: "A periscope has two mirrors that reflect light from above the wall down into the viewer’s eyes.", lvl: 1 },
    { q: "Which statement about light is correct?", o: ["Light travels in straight lines.", "Light bends around opaque objects.", "Light only travels in the day.", "Light can only travel through air."], a: 0, why: "Light travels in straight lines. That is why it cannot bend around an opaque object, and a shadow forms. Light also travels through water, glass and space.", lvl: 1 },
    { q: "Frosted glass on a bathroom window is an example of a ______ material.", o: ["transparent", "opaque", "magnetic", "translucent"], a: 3, why: "Frosted glass allows some light to pass through but we cannot see clearly through it, so it is translucent.", lvl: 1 },
    { q: "Which of these does NOT give out its own light?", o: ["A firefly glowing in the dark at night", "A reflective strip on a safety vest", "The Sun shining in the daytime sky", "A torch that is switched on"], a: 1, why: "A reflective strip only reflects light (for example from car headlights). The firefly, Sun and lit torch give out their own light.", lvl: 1 },

    { q: "Jun Hao placed three materials, one at a time, between a torch and a light sensor in a dark room. Study the graph. Which material is most suitable for a shower-room window that lets in light but stops people from seeing clearly inside?", fig: { type: "bar", title: "Light sensor readings", xl: "Material", yl: "Light sensor reading (units)", bars: [["P", 0], ["Q", 900], ["R", 420]] }, o: ["P, because it allows no light through", "Q, because it allows the most light through", "R, because it allows some light through", "P and Q, because they have the extreme readings"], a: 2, why: "R lets some light through (translucent), so light enters but people cannot see clearly inside. Q lets most light through (transparent), so people could see in. P is opaque and lets no light in.", lvl: 2 },
    { q: "Study the graph of light sensor readings for four curtain materials tested with the same torch in a dark room. Which material would keep a room the darkest?", fig: { type: "bar", title: "Light passing through curtain materials", xl: "Material", yl: "Light sensor reading (units)", bars: [["W", 250], ["X", 60], ["Y", 480], ["Z", 5]] }, o: ["W", "X", "Y", "Z"], a: 3, why: "Z has the lowest reading (5 units), so it allows the least light to pass through. A lower reading means less light reached the sensor.", lvl: 2 },
    { q: "Mei set up three cards with a small hole in each between a torch and her eye, as described in the diagram. The torch bulb and her eye are both 10 cm above the table. In which set-up can she see the torch light through all three holes?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Card 1 hole: 10 cm high", "Card 2 hole: 10 cm high", "Card 3 hole: 12 cm high"] }, { label: "B", icon: "box", lines: ["Card 1 hole: 10 cm high", "Card 2 hole: 10 cm high", "Card 3 hole: 10 cm high"] }, { label: "C", icon: "box", lines: ["Card 1 hole: 10 cm high", "Card 2 hole: 8 cm high", "Card 3 hole: 10 cm high"] }] }, o: ["A only", "B only", "C only", "A and C only"], a: 1, why: "Light travels in straight lines, so the torch, all three holes and the eye must be in a straight line. Only in B are all the holes at the same height as the eye; in A and C one card blocks the light.", lvl: 2 },
    { q: "Ali is in a room with no windows. When the light is switched off, he cannot see the book in front of him. Why?", o: ["His eyes need to be closer to the book.", "The book has become transparent.", "No light is reflected from the book into his eyes.", "The book absorbs all the light from his eyes."], a: 2, why: "With no light in the room, no light falls on the book, so no light is reflected into Ali’s eyes. Eyes receive light; they do not give it out.", lvl: 2 },
    { q: "A torch shone at a toy placed in front of a screen. The torch was moved further and further away from the toy, while the toy and screen stayed in place. Study the graph. What happened to the shadow?", fig: { type: "line", title: "Shadow of the toy", xl: "Distance of torch from toy (cm)", yl: "Height of shadow (cm)", pts: [["10", 36], ["20", 24], ["30", 20], ["40", 18], ["50", 17]] }, o: ["It became shorter.", "It became taller.", "It stayed the same height.", "It became taller, then shorter."], a: 0, why: "The graph falls from 36 cm to 17 cm: as the distance between the torch and the toy increases, the shadow becomes shorter.", lvl: 2 },
    { q: "At 9 a.m. in Singapore, the Sun is low in the eastern sky. In which direction does the shadow of a flagpole point?", o: ["West", "East", "North", "There is no shadow"], a: 0, why: "A shadow forms on the side of the object opposite the Sun. The Sun is in the east, so the shadow points west.", lvl: 2 },
    { q: "At which time of the day is the shadow of a tree in a school field likely to be the shortest?", o: ["Around noon", "7.30 a.m.", "5 p.m.", "6.45 p.m."], a: 0, why: "Around noon the Sun is highest in the sky, so the tree blocks light over the smallest area and the shadow is shortest. Early morning and evening shadows are long.", lvl: 2 },
    { q: "A metal washer is a flat ring with a hole in the middle. It is held facing a torch in front of a screen. What does its shadow look like?", o: ["A solid dark circle with no light in it", "A thin dark line across the screen", "A dark square with a bright hole in the middle", "A dark ring with a bright circle in the middle"], a: 3, why: "The metal ring blocks light, but light travels straight through the hole, so the centre of the shadow is lit. The shadow follows the outline of the washer.", lvl: 2 },
    { q: "Four sheets of the same size, E, F, G and H, were tested one at a time with a torch and a light sensor in a dark room. Study the graph. Which sheet will form the darkest shadow when held in front of a torch?", fig: { type: "bar", title: "Light sensor readings", xl: "Sheet", yl: "Light sensor reading (units)", bars: [["E", 520], ["F", 0], ["G", 180], ["H", 890]] }, o: ["F", "E", "G", "H"], a: 0, why: "F let no light reach the sensor, so it is opaque and blocks all the light: its shadow is darkest. E and G let some light through (lighter shadows) and H lets most light through.", lvl: 2 },
    { q: "Which of these uses the reflection of light to help people?", o: ["A side mirror on a car", "A glass window in a house", "A light bulb in a lamp", "A wooden door of a room"], a: 0, why: "A side mirror reflects light from vehicles behind into the driver’s eyes. A bulb gives out light; a glass window lets light pass through; a door blocks light.", lvl: 2 },
    { q: "Which describes how the two mirrors are placed in a simple periscope?", o: ["Both facing upwards, side by side", "Back to back in the middle of the tube", "One at the top facing the sky and one at the bottom facing the ground", "Parallel to each other, each tilted at 45°, facing each other"], a: 3, why: "The two mirrors are parallel, each at 45°, with their shiny sides facing each other, so light is reflected down the tube by the top mirror and then into the eye by the bottom mirror.", lvl: 2 },
    { q: "Study the flowchart. Which object could be A?", fig: { type: "flow", root: "Objects", node: { q: "Gives out its own light?", yes: "A", no: { q: "Lets light through?", yes: { q: "Lets most light through?", yes: "B", no: "C" }, no: "D" } } }, o: ["The Moon", "A lit bulb", "A mirror", "A clear glass cup"], a: 1, why: "A must give out its own light, so it is a source of light: a lit bulb. The Moon and a mirror only reflect light; a glass cup lets light through.", lvl: 2 },
    { q: "Study the set-ups. Kai wants to find out if the distance between an object and a torch affects the size of its shadow. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Square card", "Torch 10 cm from card", "Screen 40 cm from card"] }, { label: "B", icon: "box", lines: ["Square card", "Torch 25 cm from card", "Screen 40 cm from card"] }, { label: "C", icon: "box", lines: ["Round card", "Torch 25 cm from card", "Screen 30 cm from card"] }] }, o: ["A and B", "A and C", "B and C", "A, B and C"], a: 0, why: "A and B differ only in the distance between the torch and the card. C has a different card and a different screen distance, so comparing it would not be a fair test.", lvl: 2 },
    { q: "Priya can see her face clearly in a new steel spoon but not in a wooden spoon. This is because the steel spoon ______.", o: ["gives out its own light that shines on her face", "is transparent and lets light pass straight through it", "absorbs all the light that falls on its surface", "has a smooth, shiny surface that reflects light well"], a: 3, why: "Smooth, shiny surfaces reflect light well, so a clear image is seen. The wooden spoon is dull and rough and reflects less light evenly. Neither spoon is a light source.", lvl: 2 },

    { q: "Which of the following statements are correct?\nA: The Moon reflects light from the Sun.\nB: A mirror is a source of light.\nC: We see a book because light reflected by it enters our eyes.\nD: Light can bend around an opaque object.", o: ["A and B only", "A and C only", "B and D only", "A, C and D only"], a: 1, why: "A and C are correct. A mirror only reflects light (B is wrong), and light travels in straight lines so it does not bend around opaque objects (D is wrong).", lvl: 3 },
    { q: "Hui Min placed different numbers of sheets of tracing paper between a torch and a light sensor. Study the graph. What is the most likely reading for 5 sheets?", fig: { type: "bar", title: "Light passing through tracing paper", xl: "Number of sheets", yl: "Light sensor reading (units)", bars: [["1", 600], ["2", 380], ["3", 200], ["4", 90]] }, o: ["120 units", "90 units", "250 units", "50 units"], a: 3, why: "Each extra sheet blocks more light, so the reading keeps falling and must be lower than 90 units. Only 50 units fits the trend; 90, 120 and 250 are not lower than the reading for 4 sheets.", lvl: 3 },
    { q: "Study the set-ups used to compare how much light passes through three fabrics. What must Farah change so that her experiment is a fair test?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Cotton, 1 layer", "Torch 20 cm from sensor", "Dark room"] }, { label: "B", icon: "box", lines: ["Silk, 1 layer", "Torch 20 cm from sensor", "Dark room"] }, { label: "C", icon: "box", lines: ["Denim, 1 layer", "Torch 30 cm from sensor", "Dark room"] }] }, o: ["Use 2 layers of silk in B", "Do all three in a bright room", "Put the torch 20 cm from the sensor in C", "Use a different torch for each fabric"], a: 2, why: "Only the type of fabric should change. In C the torch is further away, so less light would reach the sensor even without the fabric. The distance must be the same (20 cm) for all.", lvl: 3 },
    { q: "A torch and a screen are 80 cm apart. A card is moved between them and the height of its shadow is recorded. Study the graph. At what distance from the torch was the shadow 16 cm tall?", fig: { type: "line", title: "Shadow of a card", xl: "Distance of card from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 64], ["20", 32], ["40", 16], ["60", 11], ["70", 9]] }, o: ["20 cm", "60 cm", "10 cm", "40 cm"], a: 3, why: "Read across from 16 cm on the vertical axis to the line and down: 40 cm. The card was further from the torch, so it blocked less light and its shadow was smaller than at 20 cm (32 cm).", lvl: 3 },
    { q: "Study the set-up. Ben wants a bigger shadow of his toy dinosaur on the wall, but he must NOT move the torch or the wall. What should he do?", fig: { type: "setups", items: [{ label: "Torch", icon: "box", lines: ["Fixed in place"] }, { label: "Toy", icon: "box", lines: ["Toy dinosaur", "30 cm from torch"] }, { label: "Wall", icon: "box", lines: ["60 cm from torch", "Fixed in place"] }] }, o: ["Move the toy closer to the wall", "Move the toy closer to the torch", "Turn off the room light", "Use a smaller toy dinosaur"], a: 1, why: "Moving the toy closer to the torch makes it block more of the light spreading from the torch, so the shadow becomes bigger. Moving it closer to the wall makes the shadow smaller.", lvl: 3 },
    { q: "A solid cone is held in front of a torch and turned in different ways. Which shadow could it NOT form?", o: ["A circle", "A square", "A triangle", "A triangle joined to a rounded base"], a: 1, why: "Seen from the base end the cone gives a circle; from the side a triangle; when tilted, a triangle with a rounded bottom. A cone has no outline with four straight sides, so it cannot form a square shadow.", lvl: 3 },
    { q: "The graph shows the length of the shadow of a pole at different times. At which time was the Sun highest in the sky?", fig: { type: "bar", title: "Shadow of a pole", xl: "Time of day", yl: "Length of shadow (cm)", bars: [["8 a.m.", 210], ["10 a.m.", 95], ["12.30 p.m.", 20], ["4 p.m.", 140]] }, o: ["8 a.m.", "10 a.m.", "12.30 p.m.", "4 p.m."], a: 2, why: "The shortest shadow (20 cm) is formed when the Sun is highest in the sky. The long shadows at 8 a.m. and 4 p.m. show the Sun was low.", lvl: 3 },
    { q: "Why does a sheet of translucent plastic form a lighter shadow than a sheet of aluminium of the same size?", o: ["The plastic reflects all the light back towards the torch.", "The plastic allows some light to pass through, so it blocks less light.", "Light travels faster through plastic, so the shadow is lighter.", "The aluminium gives out a dark light that makes its shadow darker."], a: 1, why: "Translucent plastic allows some light through, so part of its shadow area still receives light. Aluminium is opaque and blocks all the light, forming a dark shadow.", lvl: 3 },
    { q: "Zack’s periscope has had its TOP mirror removed. He holds it up behind a wall and looks into the bottom opening. What will he see?", o: ["The objects behind the wall, but upside down, as only one mirror reflects light", "The objects behind the wall clearly, as the bottom mirror still reflects light", "The objects on the ground next to him, reflected up by the bottom mirror", "Only the inside of the tube, as nothing reflects light from beyond the wall down to him"], a: 3, why: "Without the top mirror, light from objects beyond the wall is not reflected down the tube, so no light from them reaches the bottom mirror and his eyes. He sees only the dim inside of the tube and its top opening.", lvl: 3 },
    { q: "Study the flowchart. Which pair of objects could be C and D?", fig: { type: "flow", root: "Objects", node: { q: "Gives out its own light?", yes: "A", no: { q: "Lets light through?", yes: { q: "Lets most light through?", yes: "B", no: "C" }, no: "D" } } }, o: ["C: clear glass, D: frosted glass", "C: tracing paper, D: steel lid", "C: steel lid, D: tracing paper", "C: candle flame, D: wooden plank"], a: 1, why: "C lets some but not most light through (translucent: tracing paper). D lets no light through (opaque: steel lid). Clear glass would be B, and a candle flame gives out its own light, so it would be A.", lvl: 3 },
    { q: "At 4 p.m., Harith’s shadow falls towards the east on an open field. To look towards the Sun, which way should he face?", o: ["East", "North", "West", "Straight up"], a: 2, why: "The shadow is on the side opposite the Sun. The shadow points east, so the Sun is in the west, which fits the afternoon Sun moving towards where it sets.", lvl: 3 },
    { q: "Lina stands in a corridor and cannot see her friend who is standing just around the corner of a concrete wall. Which best explains this?", o: ["Her friend is not a source of light, so no light at all comes from her friend.", "Light reflected by her friend travels in straight lines and is blocked by the wall.", "Concrete gives out no light, so the corner of the wall stays dark.", "Her eyes cannot give out enough light to reach around to her friend."], a: 1, why: "Light reflected by her friend travels in straight lines and cannot bend around the corner. The opaque wall blocks it, so it does not enter Lina’s eyes.", lvl: 3 },

    { q: "An opaque card is placed between a torch and a screen. Which changes would make its shadow bigger?\nA: Move the torch closer to the card\nB: Move the screen further from the card\nC: Move the card closer to the screen\nD: Move the torch further from the card", o: ["A and B only", "A and C only", "B and D only", "A, B and C only"], a: 0, why: "The shadow grows when the card is relatively nearer the torch than the screen: bringing the torch closer (A) or moving the screen further back (B) both do this. C and D make the card relatively closer to the screen, so the shadow becomes smaller.", lvl: 4 },
    { q: "In a dark room, Sam shines a torch at a sheet of X and records the light sensor reading behind it. Study the graph. Which conclusion is correct?", fig: { type: "bar", title: "Light sensor readings", xl: "What was placed in front of the sensor", yl: "Light sensor reading (units)", bars: [["Nothing", 800], ["1 sheet of X", 760], ["2 sheets of X", 720], ["1 sheet of Y", 0]] }, o: ["X is translucent because 2 sheets let less light through than 1 sheet.", "Y is transparent because its reading is the lowest.", "X is transparent because it allows most of the light to pass through.", "X gives out light because its reading is high."], a: 2, why: "One sheet of X still lets 760 of the 800 units through, so X allows most light to pass through: it is transparent. Any material, even a transparent one, lets a little less through when doubled, so that does not make X translucent. Y lets no light through, so it is opaque.", lvl: 4 },
    { q: "Alone, sheet P gives a light sensor reading of 500 units and sheet Q gives 300 units (same torch, same distance, dark room). What is the most likely reading when P and Q are stacked together in front of the sensor?", o: ["800 units, the total of both", "400 units, the average of both", "Lower than 300 units", "Exactly 300 units, because Q decides the reading"], a: 2, why: "Light that passes through one sheet must then pass through the other, and each sheet blocks some light. So less light gets through than through either sheet alone: lower than 300 units. Readings are not added or averaged.", lvl: 4 },
    { q: "In a dark room, a torch beam shines at a white wall. Tom stands at the side of the room. He sees a bright spot on the wall but cannot see the beam travelling through the air. Why?", o: ["Light travels straight to the wall; only light that the wall reflects enters Tom’s eyes.", "The wall is a source of light, so it gives out light but the torch beam does not.", "The torch light stops in mid-air before it reaches Tom, so he cannot see it.", "Tom’s eyes give out light that lights up only the wall and not the air in between."], a: 0, why: "The beam travels in a straight line from the torch to the wall and none of it heads towards Tom. The wall reflects light in many directions, including into Tom’s eyes, so he sees the bright spot only.", lvl: 4 },
    { q: "The graph shows the length of the shadow of a lamp post during one day. The shadow lengths at 11 a.m. and 3 p.m. are the same. Which statement is correct?", fig: { type: "line", title: "Shadow of a lamp post", xl: "Time", yl: "Length of shadow (m)", pts: [["9 a.m.", 5.2], ["11 a.m.", 1.8], ["1 p.m.", 0.3], ["3 p.m.", 1.8], ["5 p.m.", 5.2]] }, o: ["At both times the Sun was in the same place in the sky, so the shadows matched.", "At both times the shadow pointed in the same direction, as it was just as long.", "The Sun was brighter at 11 a.m. than at 3 p.m., which made the shadow the same length.", "The Sun was about equally high at both times, but the shadows pointed opposite ways."], a: 3, why: "Equal shadow lengths mean the Sun was about equally high. In the morning the Sun is in the east (shadow points west) and in the afternoon it is in the west (shadow points east), so the shadows point in opposite directions.", lvl: 4 },
    { q: "A torch and a screen are 60 cm apart. A card 5 cm tall is moved away from the torch towards the screen. Study the graph. What will the height of the shadow be when the card is pressed flat against the screen?", fig: { type: "line", title: "Shadow of a 5 cm card", xl: "Distance of card from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 30], ["20", 15], ["30", 10], ["40", 7.5], ["50", 6]] }, o: ["0 cm", "3 cm", "5 cm", "6 cm"], a: 2, why: "The shadow gets smaller as the card nears the screen, but it can never be smaller than the card. When the card touches the screen it blocks light from exactly the area it covers, so the shadow is 5 cm tall. The trend (6 cm at 50 cm) fits this.", lvl: 4 }
  ],
  tf: [
    { s: "The Moon is a source of light.", a: false, why: "The Moon does not give out its own light; it reflects light from the Sun." },
    { s: "A burning candle is a source of light.", a: true, why: "A candle flame gives out its own light." },
    { s: "We can see objects because our eyes send out light.", a: false, why: "We see when light from a source, or light reflected by an object, enters our eyes." },
    { s: "Light travels in straight lines.", a: true, why: "This is why shadows form and why we cannot see around corners." },
    { s: "A mirror is a source of light because it looks bright.", a: false, why: "A mirror only reflects light; it does not give out its own light." },
    { s: "Smooth, shiny surfaces reflect light better than dull, rough surfaces.", a: true, why: "Mirrors and polished metals reflect light well; dull surfaces reflect less." },
    { s: "Translucent objects do not form shadows.", a: false, why: "They block some light and form lighter shadows." },
    { s: "An opaque object does not allow light to pass through.", a: true, why: "It blocks the light completely and forms a dark shadow." },
    { s: "A higher light sensor reading means that less light passed through the material.", a: false, why: "A higher reading means more light reached the sensor, so more light passed through." },
    { s: "Moving an object closer to a torch makes its shadow bigger.", a: true, why: "Closer to the light source, the object blocks more light." },
    { s: "Moving an object closer to the screen makes its shadow bigger.", a: false, why: "The shadow becomes smaller (and sharper) as the object nears the screen." },
    { s: "The shadow of a tree in the morning points towards the east.", a: false, why: "The morning Sun is in the east, so the shadow points west, away from the Sun." },
    { s: "Shadows are shortest around noon when the Sun is high in the sky.", a: true, why: "A high Sun lights the object from above, so only a small area behind it is shaded." },
    { s: "In a completely dark room, we can still see a white wall because white reflects light.", a: false, why: "With no light at all, there is nothing for the wall to reflect into our eyes." },
    { s: "A periscope uses two mirrors to reflect light into the viewer’s eyes.", a: true, why: "The top mirror reflects light down to the bottom mirror, which reflects it into the eyes." },
    { s: "The shape of a shadow can change when the object is turned.", a: true, why: "The shadow follows the outline of the object facing the light, e.g. a can gives a circle end-on and a rectangle side-on." },
    { s: "Clear glass allows most light to pass through.", a: true, why: "Clear glass is transparent." },
    { s: "A shadow always forms on the same side of the object as the light source.", a: false, why: "It forms on the side opposite the light source, where light is blocked." },
    { s: "The reflective strips on a school bag give out light at night.", a: false, why: "They only reflect light from sources such as car headlights back towards drivers’ eyes." },
    { s: "Frosted glass is opaque.", a: false, why: "Frosted glass allows some light to pass through, so it is translucent." }
  ],
  sort: [
    { title: "Sort these into sources of light and not sources of light.", groups: ["Source of light", "Not a source of light"], items: [["the Sun", 0], ["a lit light bulb", 0], ["a campfire", 0], ["a glowing firefly", 0], ["the Moon", 1], ["a mirror", 1], ["a reflective safety vest", 1], ["a shiny steel pot", 1], ["a switched-on torch", 0], ["a switched-off torch", 1]] },
    { title: "Sort these materials by how much light passes through them.", groups: ["Transparent", "Translucent", "Opaque"], items: [["clear glass", 0], ["clear plastic bottle", 0], ["frosted glass", 1], ["tracing paper", 1], ["waxed paper", 1], ["wooden plank", 2], ["aluminium foil", 2], ["cardboard box", 2], ["clean water", 0]] },
    { title: "An opaque card is between a torch and a screen. Sort each change by its effect on the shadow.", groups: ["Shadow becomes bigger", "Shadow becomes smaller"], items: [["move the card closer to the torch", 0], ["move the card closer to the screen", 1], ["move the torch closer to the card", 0], ["move the torch further from the card", 1], ["move the screen further from the card", 0], ["move the screen closer to the card", 1], ["use a bigger card", 0], ["use a smaller card", 1]] }
  ],
  oe: [
    { q: "Siti is reading a book in the living room with the lights switched on. Explain how she is able to see the book.", marks: 2, kw: [["reflect"], ["enter"]], model: "Light from the lamp falls on the book and is reflected by the book. The reflected light enters Siti’s eyes, so she can see the book." },
    { q: "Explain why the Moon is not a source of light even though it looks bright at night.", marks: 1, kw: [["reflect"]], model: "The Moon does not give out its own light. It reflects light from the Sun." },
    { q: "Study the diagram. Rahim set up three cards with a hole in each between a lit torch and his eye.\n(a) What must Rahim do so that he can see the torch light through all three holes?\n(b) What does this show about light?\n(c) Rahim then moves card B 2 cm sideways, out of line with the other cards. Explain why he can no longer see the torch light.", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Card A with a hole", "Nearest the torch"] }, { label: "B", icon: "box", lines: ["Card B with a hole", "In the middle"] }, { label: "C", icon: "box", lines: ["Card C with a hole", "Nearest his eye"] }] }, marks: 3, kw: [["straight line", "in line", "line up", "aligned", "same line"], ["travels in straight", "travel in straight", "straight lines"], ["block"]], model: "(a) He must arrange the cards so that the torch, the three holes and his eye are in a straight line. (b) Light travels in straight lines. (c) The hole in card B is no longer in line with the others, so card B blocks the light and it cannot reach his eye." },
    { q: "Devi tested four materials, one at a time, with a torch and a light sensor in a dark room. Study the graph.\n(a) Which material is opaque? Give a reason.\n(b) Which material would be most suitable for the windscreen of a car? Explain.\n(c) State one variable that Devi must keep the same to make it a fair test.", fig: { type: "bar", title: "Light sensor readings", xl: "Material", yl: "Light sensor reading (units)", bars: [["J", 350], ["K", 0], ["L", 880], ["M", 120]] }, marks: 3, kw: [["k because", "k as", "k since", "is k", "material k"], ["l because", "l as", "l since", "is l", "material l"], ["distance", "thickness", "same torch", "size of", "same size", "thick"]], model: "(a) K, because its reading was 0, so it did not allow any light to pass through. (b) L, because it had the highest reading and allows the most light to pass through, so the driver can see the road clearly. (c) The distance between the torch and the light sensor." },
    { q: "A torch and a screen were kept 60 cm apart. Aini placed an opaque card at different distances from the torch and measured the height of its shadow. Study the graph.\n(a) Describe the relationship between the distance of the card from the torch and the height of the shadow.\n(b) What was the height of the shadow when the card was 20 cm from the torch?\n(c) Explain how the shadow is formed.\n(d) Why must the torch and the screen be kept in the same positions throughout?", fig: { type: "line", title: "Height of shadow", xl: "Distance of card from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 60], ["20", 30], ["30", 20], ["40", 15], ["50", 12]] }, marks: 4, kw: [["decrease", "smaller", "shorter"], ["30", "30cm"], ["block"], ["fair"]], model: "(a) As the distance of the card from the torch increases, the height of the shadow decreases. (b) 30 cm. (c) The opaque card blocks the light from the torch. Light travels in straight lines, so it cannot reach the area of the screen behind the card. (d) To make it a fair test, so that only the distance between the card and the torch is changed." },
    { q: "Nurul measured the shadow of a flagpole in her school at different times of the day. Study the graph.\n(a) At which time was the Sun highest in the sky? Explain.\n(b) Explain why the shadow at 8 a.m. was long.\n(c) In which direction did the shadow point at 8 a.m.?", fig: { type: "bar", title: "Shadow of a flagpole", xl: "Time of day", yl: "Length of shadow (m)", bars: [["8 a.m.", 9], ["10 a.m.", 4], ["1 p.m.", 1], ["4 p.m.", 5]] }, marks: 3, kw: [["shortest"], ["low"], ["west"]], model: "(a) At 1 p.m., because the shadow was the shortest then. (b) At 8 a.m. the Sun was low in the sky, so the flagpole blocked light over a long area of the ground. (c) West, because the Sun was in the east and the shadow forms on the side opposite the Sun." },
    { q: "Jia Hui uses a periscope to watch a parade over the heads of a crowd.\n(a) Describe how light from the parade reaches her eyes through the periscope.\n(b) Why could she not see the parade without it?", marks: 3, kw: [["top mirror", "upper mirror"], ["bottom mirror", "lower mirror"], ["straight"]], model: "(a) Light from the parade enters the top of the periscope and is reflected by the top mirror down to the bottom mirror. The bottom mirror reflects the light into her eyes. (b) Light travels in straight lines, so light from the parade is blocked by the people in front of her and cannot reach her eyes." },
    { q: "Hakim shone a torch at a sheet of tracing paper and then at a piece of cardboard of the same size. The shadow of the tracing paper was lighter. Explain why.", marks: 2, kw: [["some light", "part of the light"], ["all the light", "all light", "all of the light"]], model: "Tracing paper is translucent and allows some light to pass through, so less light is blocked. The cardboard is opaque and blocks all the light, so its shadow is darker." },
    { q: "Study the set-ups. Irfan wants to find out if the distance between an object and the screen affects the size of its shadow.\n(a) Which two set-ups should he compare? Explain.\n(b) Predict which of your two set-ups will give the bigger shadow and explain why.\n(c) Why is set-up Z not suitable for this investigation?", fig: { type: "setups", items: [{ label: "X", icon: "box", lines: ["Wooden cube", "Torch 60 cm from screen", "Cube 20 cm from screen"] }, { label: "Y", icon: "box", lines: ["Wooden cube", "Torch 60 cm from screen", "Cube 40 cm from screen"] }, { label: "Z", icon: "box", lines: ["Glass cube", "Torch 60 cm from screen", "Cube 40 cm from screen"] }] }, marks: 3, kw: [["x and y", "y and x"], ["closer to the torch", "nearer the torch", "near the torch", "closer to torch", "nearer to the torch", "blocks more"], ["transparent", "glass", "different object", "different material"]], x: 1, model: "(a) X and Y, because only the distance between the cube and the screen is different; the torch distance and the object are the same. (b) Y, because its cube is 40 cm from the screen, so it is closer to the torch and blocks more light. (c) Z uses a glass cube, a different material; glass is transparent, so it will not form a clear shadow and it is not a fair test." },
    { q: "Explain why wearing a vest with reflective strips helps a cyclist to be seen by drivers at night.", marks: 2, kw: [["reflect"], ["eyes"]], model: "The strips reflect light from the car headlights well. The reflected light enters the drivers’ eyes, so they can see the cyclist." },
    { q: "Kelvin held an empty drink can in front of a torch.\n(a) When the side of the can faced the torch, the shadow was a rectangle. How should he hold the can to get a circular shadow?\n(b) Explain why the shadow changed shape.\n(c) He wants to make the circular shadow larger without moving the torch or the screen. What should he do?", marks: 3, kw: [["end", "top", "base", "bottom", "upright", "flat"], ["outline", "shape of the part", "shape of the side", "side facing", "part facing", "faces the torch", "facing the torch"], ["closer to the torch", "nearer the torch", "nearer to the torch", "towards the torch", "near the torch"]], x: 1, model: "(a) Hold the can so that its top (end) faces the torch. (b) The shadow follows the outline of the part of the can facing the torch; from the end the outline is a circle, but from the side it is a rectangle. (c) Move the can closer to the torch, so it blocks more light." },
    { q: "Ben went into a storeroom with no windows and closed the door. The room was completely dark. Explain why he could not see his red shirt.", marks: 2, kw: [["no light"], ["eyes"]], model: "There was no light in the room, so no light fell on the shirt and no light was reflected from the shirt into Ben’s eyes." },
    { q: "Mr Tan placed different numbers of sheets of plastic film between a torch and a light sensor in a dark room. Study the graph.\n(a) Describe the relationship between the number of sheets and the light sensor reading.\n(b) Explain this relationship.\n(c) Predict the reading for 5 sheets.\n(d) Mr Tan wants film for a bus window that lets in some light but cuts down glare. How many sheets would you choose from the graph, and why not 0?", fig: { type: "bar", title: "Light through plastic film", xl: "Number of sheets", yl: "Light sensor reading (units)", bars: [["0", 900], ["1", 650], ["2", 450], ["3", 300], ["4", 200]] }, marks: 4, kw: [["decrease", "lower", "less"], ["block"], ["100", "120", "130", "140", "150", "less than 200", "lower than 200", "below 200"], ["glare", "too much light", "too bright", "most light"]], x: 1, model: "(a) As the number of sheets increases, the light sensor reading decreases. (b) Each sheet blocks some light, so more sheets block more light and less light reaches the sensor. (c) About 140 units, less than 200 units. (d) 2 or 3 sheets, because they still let some light in; with 0 sheets most light passes through and causes too much glare." },
    { q: "A hawker centre wants a roof for its outdoor seating area that gives shade but still lets some daylight in. Study the table of light sensor readings taken under three roof materials at noon.\n(a) Which material is most suitable? Explain using the results.\n(b) Explain why material C is not suitable.\n(c) Why were all the readings taken at the same time of day?", tbl: [["Roof material", "A", "B", "C"], ["Light sensor reading (units)", "0", "380", "950"]], marks: 3, kw: [["b because", "b as", "b since", "material b"], ["most light", "too much light", "too bright", "no shade", "transparent"], ["fair", "same amount of sunlight", "same amount of light", "sunlight changes", "position of the sun"]], model: "(a) B, because its reading of 380 units shows it allows some light to pass through, so it gives shade but still lets some daylight in. (b) C has the highest reading, so it allows most light to pass through; it is transparent and gives little shade. (c) To make it a fair test, because the amount of sunlight changes during the day." }
  ],
  doc: [
    { q: "Explain how Aiman can see a mango on the kitchen table during the day.", marks: 2, answers: ["Aiman looks at the mango with his eyes.", "Light from the Sun is reflected by the mango and the reflected light enters Aiman’s eyes.", "The mango gives out light that goes into his eyes."], best: 1, why: "Answer 2 gives the whole path: a source (the Sun), the mango reflects the light, and the reflected light enters his eyes. Answer 1 only repeats the question. Answer 3 is wrong: a mango is not a source of light." },
    { q: "Explain how the shadow of a wooden chair is formed on the floor.", marks: 2, answers: ["The chair is opaque and blocks the light. Light travels in straight lines, so it cannot reach the floor behind the chair.", "The chair is dark so it makes a dark patch.", "The chair blocks the light."], best: 0, why: "Answer 1 has both keywords: opaque object blocks light, and light travels in straight lines. Answer 3 has only one idea (1 mark). Answer 2 gives a wrong reason: colour does not decide whether a shadow forms." },
    { q: "A light sensor gave a reading of 820 units behind material X and 40 units behind material Y. Which material allows more light to pass through? Explain.", marks: 2, answers: ["Y, because it blocks the light better.", "X, because it is the better material.", "X, because its reading of 820 units is higher, so more light passed through it and reached the sensor."], best: 2, why: "Answer 3 gives the claim and uses the readings as evidence with the link ‘higher reading = more light through’. Answer 1 reads the graph the wrong way round. Answer 2 has the right claim but a vague reason with no evidence." },
    { q: "Explain why the shadow of a lamp post is shorter at noon than at 5 p.m.", marks: 2, answers: ["At noon the Sun is high in the sky, so the post blocks light over a small area. At 5 p.m. the Sun is low, so the shadow is longer.", "At noon it is hotter, so the shadow shrinks.", "The Sun moves."], best: 0, why: "Answer 1 links the position of the Sun (high vs low) to the length of the shadow. Answer 2 gives a wrong reason: heat does not change a shadow. Answer 3 is too vague and does not say how the Sun’s position affects the shadow." },
    { q: "Why does a translucent plastic file form a lighter shadow than a book?", marks: 2, answers: ["Because the file is lighter in weight.", "The file allows some light to pass through, so it blocks less light than the opaque book, which blocks all the light.", "The file is see-through."], best: 1, why: "Answer 2 explains that the translucent file lets some light through while the opaque book blocks all light. Answer 1 confuses ‘light’ (weight) with light energy. Answer 3 is vague and would describe a transparent object, which gives no clear shadow." }
  ]
};
