window.LBU = window.LBU || {};
LBU["p4-light"] = {
  glossary: [
    { t: "Source of light", d: "Something that gives out light of its own, such as the Sun, other stars, a lit bulb, a burning candle or a glowing firefly." },
    { t: "Light energy", d: "Light is a form of energy given out by a source of light. We need light to see. It can travel through air, water, clear glass and even empty space." },
    { t: "Light travels in straight lines", d: "Light moves in straight paths and cannot bend around an object. This is why shadows are formed and why we cannot see around a corner." },
    { t: "Reflection", d: "When light hits a surface and bounces back off it. Mirrors and other smooth, shiny surfaces reflect light well; dull, rough or dark surfaces reflect less light." },
    { t: "Mirror", d: "A smooth, shiny, opaque object that reflects most of the light falling on it. It is not a source of light; it only reflects light." },
    { t: "Transparent material", d: "A material that allows most light to pass through it, so objects behind it can be seen clearly, e.g. clear glass, cling wrap and clean water." },
    { t: "Translucent material", d: "A material that allows some light to pass through it, so objects behind it look blurred, e.g. frosted glass, tracing paper and greaseproof paper." },
    { t: "Opaque material", d: "A material that does not allow light to pass through it. It blocks all the light and forms a dark shadow, e.g. wood, metal, cardboard and brick." },
    { t: "Shadow", d: "A dark area formed when an object blocks light. Light travels in straight lines, so it cannot reach the area behind the object." },
    { t: "Light sensor", d: "A device, used with a datalogger, that measures the amount of light reaching it. The higher the reading, the more light has reached the sensor." },
    { t: "Periscope", d: "A tube with two parallel mirrors, each at 45°. Light from an object is reflected by the top mirror to the bottom mirror and then into the eyes." },
    { t: "Fair test", d: "An experiment in which only one variable is changed and all the others are kept the same, e.g. same torch, same distance from the sensor, in a dark room." }
  ],
  lessons: [
    {
      h: "Predicting the shape and darkness of a shadow",
      concept: "Work out a shadow part by part. The shadow follows the OUTLINE of the side of the object facing the light. Opaque parts block all the light and give dark areas; translucent parts block some light and give lighter areas; transparent parts allow most light through and give hardly any shadow. Holes and gaps let light travel straight through, so those parts of the shadow are bright.",
      example: {
        q: "Aminah cut a star-shaped hole in the middle of a square piece of cardboard and taped tracing paper over the hole. She held the card facing a torch, in front of a screen.\n(a) Describe the shadow formed on the screen. [1]\n(b) Explain why the star part of the shadow looks different from the rest of the shadow. [2]",
        marks: 3,
        think: [
          "Step 1: Find the outline facing the torch: a square, so the shadow is a square.",
          "Step 2: Cardboard is opaque, so it blocks all the light: the square is dark.",
          "Step 3: The star hole is covered by tracing paper, which is translucent. It allows some light to pass through, so the star is lighter, but not fully bright.",
          "Step 4: Use both keywords for (b): the cardboard BLOCKS all light; the tracing paper lets SOME light through."
        ],
        answer: "(a) A dark square shadow with a lighter star shape in the middle. (b) The cardboard is opaque and blocks all the light, so the square part is dark. The tracing paper over the star is translucent and allows some light to pass through, so the star part receives some light and is lighter."
      },
      tip: "Go part by part: opaque = dark, translucent = lighter, transparent or a hole = (almost) no shadow. The colour of the object never matters.",
      try: {
        q: "A clear plastic cup has a strip of black paper wrapped around its middle and a steel spoon standing inside it. The cup is held side-on to a torch. Which best describes its shadow?",
        o: ["A faint cup shape with a dark band and a dark spoon shape", "A dark cup shape with a dark band but no spoon shape", "A faint cup shape with a dark band but no spoon shape", "A dark cup shape with a faint band and a faint spoon"],
        a: 0,
        why: "The clear plastic is transparent, so the cup gives only a faint outline. The black paper and the steel spoon are opaque and block light, so both form dark shapes. The spoon is not hidden: light passes through the clear cup and is blocked by the spoon."
      }
    },
    {
      h: "Explaining how a periscope lets you see",
      concept: "A periscope answer must trace the light from the OBJECT to the EYES: light from the object enters the top opening, is REFLECTED by the top mirror down the tube to the bottom mirror, and is REFLECTED by the bottom mirror into the eyes. The mirrors are parallel, each at 45°, with their shiny sides facing each other. If any mirror is missing, turned or replaced by an opaque or dull material, the light no longer reaches the eyes.",
      example: {
        q: "Raju made a periscope to watch a football match over a fence.\n(a) Describe how light from the players reaches his eyes. [2]\n(b) Raju replaced the bottom mirror with a piece of cardboard. Explain why he could no longer see the players clearly. [1]",
        marks: 3,
        think: [
          "Step 1: Start from the players, not the eyes: light from the players enters the top opening.",
          "Step 2: The top mirror reflects the light down the tube to the bottom mirror (1 mark).",
          "Step 3: The bottom mirror reflects the light into Raju’s eyes (1 mark).",
          "Step 4: Cardboard is dull and rough and does not reflect light well, so very little light from the players is reflected into his eyes."
        ],
        answer: "(a) Light from the players enters the top of the periscope and is reflected by the top mirror down to the bottom mirror. The bottom mirror reflects the light into Raju’s eyes. (b) The cardboard does not reflect light well, so very little of the light from the players is reflected into his eyes."
      },
      tip: "Name BOTH mirrors and use ‘reflected’ twice. Always end with ‘into the eyes’, never ‘the eyes look through the mirrors’.",
      try: {
        q: "Which shows the correct path of light through a periscope?",
        o: ["Eyes -> bottom mirror -> top mirror -> object", "Object -> bottom mirror -> top mirror -> eyes", "Object -> top mirror -> bottom mirror -> eyes", "Top mirror -> object -> bottom mirror -> eyes"],
        a: 2,
        why: "Light starts from the object, enters the top opening, is reflected by the top mirror down to the bottom mirror, and is then reflected into the eyes. Eyes do not send out light, and the light meets the top mirror first."
      }
    }
  ],
  flash: [
    { f: "Name three surfaces that reflect light well.", b: "Smooth, shiny surfaces, e.g. a mirror, polished steel, aluminium foil and still water." },
    { f: "Same lamp: why does a room with white walls look brighter than one with dark walls?", b: "White walls reflect more light than dark walls, so more reflected light falls on the objects and enters our eyes." },
    { f: "How does a periscope let us see over a wall?", b: "Light from the object is reflected by the top mirror down to the bottom mirror, which reflects it into our eyes. The mirrors are parallel, each at 45°." },
    { f: "Object moved closer to the screen (torch fixed): effect on its shadow?", b: "The shadow becomes smaller, because the object is further from the torch and blocks less light." },
    { f: "A lamp is raised higher above an object: effect on its shadow on the table?", b: "The shadow becomes shorter, because the light shines down more steeply and the object blocks light over a smaller area." },
    { f: "Two lamps shine on one opaque vase. How many shadows are formed?", b: "Two. The vase blocks light from each lamp, so a shadow forms on the side of the vase away from each lamp." },
    { f: "Does a red opaque ball form a red shadow?", b: "No. A shadow is a dark area where light is blocked; the colour of the object does not change it." },
    { f: "How can you make light sensor results more reliable?", b: "Repeat the test (e.g. 3 times) for each material and find the average reading." },
    { f: "Why keep the torch at the same distance from the light sensor in every test?", b: "The amount of light reaching the sensor changes with distance, so keeping it the same means only the material affects the reading." },
    { f: "Why does a shadow change direction during the day?", b: "The position of the Sun in the sky changes from east to west, and the shadow always forms on the side of the object away from the Sun." },
    { f: "Why can we see a torch beam in mist or in a dusty room?", b: "Tiny water droplets or dust in the beam reflect some of its light into our eyes." },
    { f: "Why does the shadow of a metal washer have a bright centre?", b: "The metal ring blocks light, but light travels in straight lines through the hole, so the centre of the shadow still receives light." }
  ],
  mcq: [
    { q: "During the Mid-Autumn Festival, Mei Ling’s paper lantern glows softly, but she cannot see the candle inside it clearly. The paper of the lantern is ______.", o: ["transparent", "translucent", "opaque", "a source of light"], a: 1, why: "The paper allows some light to pass through, so the lantern glows, but the candle looks blurred: the paper is translucent. Transparent paper would let her see the candle clearly, and opaque paper would let no light through. The candle, not the paper, gives out the light.", lvl: 1 },
    { q: "Which of these is a natural source of light?", o: ["A table lamp", "A street lamp", "The Sun", "A car headlight"], a: 2, why: "The Sun gives out its own light and is not made by people, so it is a natural source of light. A table lamp, a street lamp and a car headlight are sources of light made by people.", lvl: 1 },
    { q: "A light sensor connected to a datalogger measures ______.", o: ["the amount of light that reaches it", "how hot the torch has become", "the size of a shadow on a screen", "the colour of the material tested"], a: 0, why: "A light sensor measures the amount of light reaching it. The higher the reading, the more light has reached it. It does not measure heat, shadow size or colour.", lvl: 1 },
    { q: "Mrs Lee tested four materials for a blackout curtain, one at a time, with a torch and a light sensor in a dark room. Study the table. Which material is opaque?", tbl: [["Material", "K", "L", "M", "N"], ["Light sensor reading (units)", "540", "75", "860", "0"]], o: ["K", "L", "M", "N"], a: 3, why: "N gave a reading of 0, so no light passed through it: it is opaque. L lets very little light through, but its reading is above 0, so it is not opaque.", lvl: 1 },

    { q: "On a dark road with no street lamps, the reflective road studs seem to glow brightly when car headlights shine on them. Why can drivers see them?", o: ["They give out their own light when cars pass", "They let headlight beams pass straight through them", "They store sunlight in the day and give it out at night", "They reflect light from the headlights into drivers’ eyes"], a: 3, why: "Reflective road studs are not sources of light. They reflect light from the headlights back, and the reflected light enters the drivers’ eyes. With no headlights, they cannot be seen.", lvl: 2 },
    { q: "Which of these does NOT make use of the reflection of light?", o: ["A periscope used to see over a wall", "A rear-view mirror in a taxi", "A frosted glass shower-room door", "A reflective strip on a school bag"], a: 2, why: "A frosted glass door is translucent: it is used because it lets some light pass through while giving privacy. The periscope, rear-view mirror and reflective strip all work by reflecting light into people’s eyes.", lvl: 2 },
    { q: "Study the set-ups. Hana wants to find out if the height of a torch above a table affects the length of a peg’s shadow. Which two set-ups should she compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Peg 5 cm tall", "Torch 20 cm high", "Torch 30 cm to the side"] }, { label: "B", icon: "box", lines: ["Peg 5 cm tall", "Torch 40 cm high", "Torch 30 cm to the side"] }, { label: "C", icon: "box", lines: ["Peg 8 cm tall", "Torch 40 cm high", "Torch 30 cm to the side"] }, { label: "D", icon: "box", lines: ["Peg 5 cm tall", "Torch 40 cm high", "Torch 50 cm to the side"] }] }, o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "A and B differ only in the height of the torch. A and C also differ in peg height, B and D differ in the sideways distance, and C and D differ in both peg height and sideways distance.", lvl: 2 },
    { q: "The roof of a bus stop is made of a translucent plastic sheet. Which statement about the roof is correct?", o: ["It lets most light through, so it gives no shade.", "It lets some light through, so it gives some shade.", "It lets no light through, so the bus stop is dark.", "It gives out light, so the bus stop is bright."], a: 1, why: "A translucent sheet allows some light to pass through and blocks the rest, so it gives some shade while the bus stop stays bright. Letting most light through describes a transparent sheet, and letting none through describes an opaque one.", lvl: 2 },
    { q: "At a wayang kulit show, a puppeteer holds a leather puppet between an oil lamp and a cloth screen. The lamp and screen stay in place. Study the graph. He wants a shadow at least twice as tall as the shadow he gets at 40 cm from the lamp. What is the furthest from the lamp he can hold the puppet?", fig: { type: "line", title: "Shadow of a puppet", xl: "Distance of puppet from lamp (cm)", yl: "Height of shadow (cm)", pts: [["10", 90], ["20", 45], ["30", 30], ["40", 22.5], ["50", 18]] }, o: ["10 cm", "20 cm", "30 cm", "50 cm"], a: 1, why: "At 40 cm the shadow is 22.5 cm, so he needs at least 45 cm. The graph shows 45 cm at 20 cm from the lamp; any further away (30 cm gives 30 cm) and the shadow is too short. 10 cm also works but is not the furthest.", lvl: 2 },
    { q: "Cards P, Q, R and S were placed, one at a time, at the same spot between a torch and a screen. The torch and screen were not moved. Study the graph. Which card is the tallest?", fig: { type: "bar", title: "Shadows of four cards", xl: "Card", yl: "Height of shadow (cm)", bars: [["P", 18], ["Q", 21], ["R", 12], ["S", 27]] }, o: ["P", "Q", "R", "S"], a: 3, why: "The torch, card position and screen were the same each time, so the only difference is the card. The tallest card blocks the most light and forms the tallest shadow: S (27 cm).", lvl: 2 },
    { q: "Lights are kept on all day inside the KPE tunnel. Why do drivers need these lights to see the road and the tunnel walls clearly?", o: ["The road reflects the lamps’ light into drivers’ eyes", "The lamps make the road give out its own light", "The lamps help drivers’ eyes give out more light", "The lamps stop the walls and road forming shadows"], a: 0, why: "The road and walls are not sources of light. Light from the lamps falls on them and is reflected into the drivers’ eyes. Eyes do not give out light.", lvl: 2 },

    { q: "In an MRT train in a dark tunnel, Daniel sees a clear reflection of himself in the window. When the train comes out into bright daylight, his reflection is very hard to see. Why?", o: ["The glass reflects light only when the train is in the dark tunnel.", "In daylight, much more light passes through the glass from outside.", "In the tunnel, the window glass gives out its own light.", "In daylight, the window glass becomes translucent."], a: 1, why: "Clear glass always reflects some light from the bright carriage. In the dark tunnel, little light comes in from outside, so the reflection is easy to see. In daylight, much more light passes through the transparent glass from outside and enters his eyes, so the faint reflection is hard to see.", lvl: 3 },
    { q: "In a dark room, Ali shines a torch at a mirror. The light from the mirror lands on a toy on the floor, and Ali can see the toy. Which shows the path of the light that lets him see the toy?", o: ["Torch -> mirror -> toy -> Ali’s eyes", "Torch -> toy -> mirror -> Ali’s eyes", "Ali’s eyes -> mirror -> toy -> torch", "Mirror -> torch -> toy -> Ali’s eyes"], a: 0, why: "The torch is the source. Its light is reflected by the mirror onto the toy, the toy reflects the light, and the reflected light enters Ali’s eyes. Eyes do not send out light, and the mirror is not a source.", lvl: 3 },
    { q: "Mrs Rahman wants a film for her west-facing HDB window that blocks more than half of the light that plain glass lets through, but still lets some light in. Each film was stuck on the same glass and tested with a torch and a light sensor in a dark room. Study the table. Which film should she choose?", tbl: [["Glass tested", "Plain", "Film P", "Film Q", "Film R", "Film S"], ["Light sensor reading (units)", "800", "720", "500", "0", "300"]], o: ["P", "Q", "R", "S"], a: 3, why: "Half of 800 units is 400 units, so the film must give a reading below 400 but above 0. Only S (300 units) fits. P and Q let through more than half the light, and R lets no light in.", lvl: 3 },
    { q: "Study the set-ups. The same card is used in each. In which set-up is the shadow on the screen the biggest?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Torch 20 cm from card", "Screen 40 cm from card"] }, { label: "B", icon: "box", lines: ["Torch 40 cm from card", "Screen 40 cm from card"] }, { label: "C", icon: "box", lines: ["Torch 20 cm from card", "Screen 80 cm from card"] }] }, o: ["A", "B", "C", "A and C are the same size"], a: 2, why: "Compare A and B: same screen distance, but the torch is closer in A, so A’s shadow is bigger than B’s. Compare A and C: same torch distance, but the screen is further away in C, so C’s shadow is bigger than A’s. C is the biggest.", lvl: 3 },
    { q: "At 3 p.m., Mei’s shadow on the school field points towards the school gate. Which statements are correct?\nA: The Sun is in the west.\nB: The gate is to the east of Mei.\nC: If Mei stands in the same spot at 9 a.m., her shadow will point away from the gate.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "In the afternoon the Sun is in the west (A), so the shadow points east, towards the gate: the gate is east of Mei (B). At 9 a.m. the Sun is in the east, so her shadow points west, away from the gate (C).", lvl: 3 },
    { q: "Ben tested four sheets with a torch and a light sensor in a dark room, and also looked at the shadow each one formed. With no sheet, the reading was 900 units. Study the table. Which statements are correct?\nA: P is opaque.\nB: R is translucent.\nC: Q is suitable for a blackout curtain.", tbl: [["Sheet", "P", "Q", "R", "S"], ["Light sensor reading (units)", "0", "870", "350", "610"], ["Shadow formed", "Dark", "Almost none", "Lighter", "Lighter"]], o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "P lets no light through and forms a dark shadow, so it is opaque (A). R lets some light through and forms a lighter shadow, so it is translucent (B). Q lets most light through (870 of 900 units), so it is transparent and would not keep a room dark (C is wrong).", lvl: 3 },

    { q: "Joy tested four papers with the same torch and light sensor in a dark room, but she placed the torch at different distances. Study the table. Which conclusions can she fairly draw?\nA: Paper W lets more light through than paper X.\nB: Paper X lets more light through than paper Y.\nC: Paper Y lets more light through than paper Z.\nD: Paper Z lets the least light through of all four.", tbl: [["Paper", "W", "X", "Y", "Z"], ["Distance of torch from sensor (cm)", "20", "20", "30", "30"], ["Light sensor reading (units)", "400", "250", "200", "90"]], o: ["A and C only", "A, B and C only", "A, C and D only", "B and D only"], a: 0, why: "Only papers tested at the same distance can be compared fairly: W with X (statement A) and Y with Z (statement C). Y and Z were tested further away, where less light reaches the sensor anyway, so they cannot be fairly compared with W or X (statements B and D cannot be concluded).", lvl: 4 },
    { q: "An object forms a circular shadow when it is held one way in front of a torch, and a square shadow when it is turned. Which object could it be?", o: ["A tennis ball, 6 cm wide", "A cube box with 6 cm sides", "A can 6 cm tall and 6 cm wide", "A cone 6 cm tall and 6 cm wide"], a: 2, why: "End-on, the can’s outline is a circle; side-on, it is a 6 cm by 6 cm square. A ball always gives a circle, a cube never gives a circle, and a cone gives a circle or a triangle but never a square.", lvl: 4 },
    { q: "Study the set-up. Two identical torches, side by side, shine on the same opaque card. Two shadows form on the screen and partly overlap. Which part of the screen is the darkest?", fig: { type: "setups", items: [{ label: "Torches", icon: "box", lines: ["Two identical torches", "Side by side", "50 cm from card"] }, { label: "Card", icon: "box", lines: ["Opaque card", "Between torch and screen"] }, { label: "Screen", icon: "box", lines: ["Two shadows", "Overlap in the middle"] }] }, o: ["Where the two shadows overlap, as no torch light reaches it", "Where only one shadow falls, as one torch’s light is blocked", "Outside both shadows, as the card reflects light away from it", "All shadow parts are equally dark, as the same card is used"], a: 0, why: "Where the shadows overlap, the card blocks the light from BOTH torches, so no light reaches it. Where only one shadow falls, light from the other torch still reaches that area, so it is lighter. Outside both shadows, light from both torches arrives.", lvl: 4 }
  ],
  oe: [
    { q: "At a wayang kulit show, the oil lamp and the puppets are behind a cloth screen, and the audience sits on the other side. Before the show, three cloths were tested one at a time with a torch and a light sensor in a dark room. With no cloth, the reading was 900 units. Study the table.\n(a) Which cloth is most suitable for the screen? Explain using the results. [2]\n(b) Explain how the shadow of a puppet is formed on the screen. [1]\n(c) Explain why the audience would see nothing on the screen if cloth X were used. [1]", tbl: [["Cloth", "X", "Y", "Z"], ["Light sensor reading (units)", "0", "380", "860"]], marks: 4, kw: [["y"], ["some light", "some of the light", "translucent"], ["block"], ["0", "zero", "any light", "does not allow", "does not let", "no light pass", "no light to pass", "no light through", "opaque"]], model: "(a) Cloth Y. Its reading of 380 units shows that it allows some light to pass through: it is translucent, so the screen glows but the audience cannot see the lamp and puppeteers clearly. (b) The puppet blocks the light from the lamp. Light travels in straight lines, so the part of the screen behind the puppet receives no light and looks dark. (c) Cloth X has a reading of 0, so it does not allow any light to pass through and no light from the lamp reaches the audience’s side." },
    { q: "Ravi shone the same torch at four surfaces, one at a time, in a dark room. A light sensor, kept at the same distance and angle each time, measured the light reflected by each surface. Study the graph.\n(a) Which surface reflected the most light? [1]\n(b) Explain why the black cloth gave the lowest reading. [1]\n(c) State one other variable Ravi must keep the same to make it a fair test. [1]\n(d) Using the results, explain why a jogger at night should wear white rather than black clothes. [1]", fig: { type: "bar", title: "Light reflected by surfaces", xl: "Surface", yl: "Light sensor reading (units)", bars: [["Mirror", 820], ["Aluminium foil", 640], ["White paper", 300], ["Black cloth", 40]] }, marks: 4, kw: [["mirror"], ["least light", "less light", "little light", "reflects the least", "reflected the least"], ["distance", "size", "angle of the torch", "torch angle", "position of the torch"], ["reflect more", "reflects more", "reflected more", "more light"]], model: "(a) The mirror. (b) The black cloth is dark and dull, so it reflects the least light and very little reflected light reached the sensor. (c) The distance between the torch and the surface. (d) White surfaces reflect more light than black ones: white paper gave 300 units but black cloth only 40 units. More light from car headlights is reflected by white clothes into drivers’ eyes, so they can see the jogger." },
    { q: "Lina tested three sheets with the same torch and a light sensor in a dark room. Study her table.\n(a) Lina concluded that sheet Q lets less light through than sheet P. Explain why her conclusion may be wrong. [1]\n(b) What should she change so that P and Q can be compared fairly? [1]\n(c) Which sheet is opaque? Use the results to explain. [1]\n(d) Predict how the reading for Q will change after your change in (b). Explain. [1]", tbl: [["Sheet", "P", "Q", "R"], ["Distance of torch from sensor (cm)", "20", "40", "20"], ["Light sensor reading (units)", "300", "120", "0"]], marks: 4, x: 1, kw: [["further", "farther", "different distance", "distances are different", "unfair", "not a fair"], ["same distance", "same as for p", "same as p", "to 20", "at 20"], ["sheet r", "r because", "r as", "r since", "is r", "r has", "r had", "r gave"], ["increase", "higher", "go up", "rise", "bigger", "greater"]], model: "(a) The torch was further from the sensor for Q (40 cm) than for P, so less light reached the sensor even without a sheet; it was not a fair test. (b) Place the torch 20 cm from the sensor for Q, the same distance as for P. (c) Sheet R, because its reading was 0, so no light passed through it. (d) The reading for Q will increase, because the torch is closer, so more light reaches the sensor." },
    { q: "Mrs Lim’s HDB flat has a dark corner where she keeps a pot of ferns. She fixes a mirror so that sunlight coming in through the window falls on it and lights up the corner.\n(a) Explain how the mirror helps her to see the ferns clearly. [2]\n(b) Explain why sunlight from the window cannot reach the corner directly. [1]\n(c) She replaces the mirror with a piece of dark brown wood of the same size. Explain why the corner becomes darker. [1]", marks: 4, kw: [["onto the fern", "on to the fern", "on the fern", "to the fern", "towards the fern", "onto the plant", "on the plant", "to the plant", "into the corner", "onto the corner"], ["eye"], ["straight"], ["less light", "reflects less", "little light", "not reflect as much", "absorb"]], model: "(a) The mirror reflects the sunlight onto the ferns. The ferns reflect this light, and the reflected light enters Mrs Lim’s eyes, so she can see them clearly. (b) Light travels in straight lines, so it cannot bend around the wall to reach the corner. (c) The dark, dull wood reflects less light than the smooth, shiny mirror, so less light falls on the ferns and is reflected into her eyes." }
  ],
  tf: [
    { s: "Light can pass through a transparent object only if the object is made of glass.", a: false, why: "Clear plastic, cling wrap and clean water are also transparent and allow most light to pass through." },
    { s: "Shadows are longer in the early morning because the Sun is bigger at that time.", a: false, why: "The Sun does not change size. It is low in the sky in the morning, so an object blocks light over a longer area of the ground." },
    { s: "In a completely dark room, every object forms a shadow.", a: false, why: "A shadow forms only when an object blocks light. With no light at all, there is no light to block, so no shadow is formed." },
    { s: "A periscope works because light bends around the corners inside the tube.", a: false, why: "Light travels in straight lines. The two mirrors reflect the light, changing its direction so that it reaches the eyes." },
    { s: "An opaque object cannot be seen because it does not let light pass through it.", a: false, why: "We see an opaque object because it reflects some light into our eyes. Blocking light only means it forms a dark shadow." },
    { s: "At the same time of day, two equally tall poles standing on flat open ground have shadows of about the same length.", a: true, why: "The Sun is at the same height in the sky for both poles, so they block light over the same length of ground." },
    { s: "The still water of MacRitchie Reservoir can act like a mirror and show a reflection of the trees around it.", a: true, why: "Still water has a smooth surface, so it reflects light well and evenly, giving a clear reflection." },
    { s: "The Moon can sometimes be seen in the daytime sky because it reflects light from the Sun.", a: true, why: "The Moon reflects sunlight whenever sunlight falls on it, so it can be seen in the day as well as at night." },
    { s: "Sunglasses with darker lenses let less light into the eyes than sunglasses with lighter lenses.", a: true, why: "Darker lenses block more light, so a light sensor placed behind them would give a lower reading." },
    { s: "Light from a burning candle spreads out in all directions.", a: true, why: "Its light travels outwards in straight lines in every direction, so people all around the candle can see it." }
  ]
};
