window.LBZ = window.LBZ || {};
LBZ["p4-light"] = {
  flash: [
    { f: "Define: source of light", b: "An object that gives out its own light, e.g. the Sun, a burning candle, a switched-on torch, a firefly." },
    { f: "Is the Moon a source of light? Why?", b: "No. The Moon does not give out its own light. It reflects light from the Sun." },
    { f: "How do we see an object that is not a source of light?", b: "Light from a source falls on the object. The object reflects the light, and the reflected light enters our eyes." },
    { f: "Why can we not see anything in a completely dark room?", b: "There is no light, so no light is reflected by the objects into our eyes." },
    { f: "Define: reflection", b: "The bouncing back of light when it hits a surface. Smooth, shiny surfaces reflect light well." },
    { f: "Define: transparent material", b: "A material that allows most light to pass through, e.g. clear glass, clear plastic. We can see clearly through it." },
    { f: "Define: translucent material", b: "A material that allows some light to pass through, e.g. frosted glass, tracing paper. It forms a lighter shadow." },
    { f: "Define: opaque material", b: "A material that does not allow light to pass through, e.g. wood, metal, cardboard. It forms a dark shadow." },
    { f: "How is a shadow formed?", b: "An opaque object blocks light. Light travels in straight lines, so it cannot bend around the object to reach the area behind it." },
    { f: "Why can we not see a friend standing around a corner?", b: "Light travels in straight lines. Light reflected by the friend is blocked by the wall, so it cannot enter our eyes." },
    { f: "Object moved closer to the light source (screen fixed): effect on its shadow?", b: "The shadow becomes bigger, because the object blocks more light." },
    { f: "What does a higher light sensor reading show?", b: "More light reached the sensor, so more light passed through the material." },
    { f: "Why do a light sensor experiment in a dark room?", b: "So that only light from the torch reaches the sensor. Light from other sources would change the readings." },
    { f: "Why is a shadow shortest around noon?", b: "The Sun is high in the sky, so the object blocks light over only a small area of the ground." },
    { f: "Which way does a shadow point at 8 a.m. in Singapore? Why?", b: "West. The Sun is in the east, and a shadow forms on the side of the object away from the Sun." }
  ],
  mcq: [
    { q: "The bouncing back of light when it hits a surface is called ______.", o: ["reflection", "a shadow", "a light source", "transparency"], a: 0, why: "Reflection is the bouncing back of light from a surface. A shadow is an area where light is blocked, and transparency describes light passing through a material.", lvl: 1 },
    { q: "A drinks stall in the school canteen wants lids for its cups that let pupils see the drink inside clearly. Which lid is most suitable?", o: ["Frosted plastic lid", "Clear plastic lid", "Aluminium lid", "Waxed paper lid"], a: 1, why: "Clear plastic is transparent and allows most light to pass through, so the drink can be seen clearly. Frosted plastic and waxed paper are translucent (blurry view), and aluminium is opaque.", lvl: 1 },
    { q: "Which of these is NOT needed for a shadow to be formed on a wall?", o: ["A source of light", "An object that blocks light", "A wall for the shadow to fall on", "A mirror to reflect the light"], a: 3, why: "A shadow on a wall needs a light source, an object that blocks the light, and the wall behind it. No mirror is needed.", lvl: 1 },
    { q: "Why is a shadow darker than the area around it?", o: ["The object gives out darkness onto the area", "The area reflects the colour of the object", "Light from the source cannot reach that area", "The area absorbs all the light around it"], a: 2, why: "The object blocks the light, and light travels in straight lines, so it cannot reach the area behind the object. Objects do not give out darkness.", lvl: 1 },

    { q: "Study the flowchart of objects in an HDB lift lobby. Which object could be Y?", fig: { type: "flow", root: "Objects in a lift lobby", node: { q: "Gives out its own light?", yes: "W", no: { q: "Lets light through?", yes: "X", no: { q: "Reflects light well?", yes: "Y", no: "Z" } } } }, o: ["A rough brick wall", "A sheet of frosted glass", "A polished steel lift door", "A lit lamp in the lobby"], a: 2, why: "Y gives out no light, lets no light through and reflects light well: a smooth, shiny, opaque steel door. A brick wall reflects light poorly (Z), frosted glass lets light through (X) and a lit lamp is a source (W).", lvl: 2 },
    { q: "The platform screen doors at many MRT stations are made of clear glass. Why is clear glass used?", o: ["It lets some light through, so commuters see only a blur", "It lets most light through, so commuters can see the train", "It lets no light through, so the platform stays cool", "It gives out its own light, so the platform stays bright"], a: 1, why: "Clear glass is transparent: it allows most light to pass through, so commuters can see the train arriving. It is not translucent or opaque, and it is not a source of light.", lvl: 2 },
    { q: "Study the set-ups. Ming first held a cardboard sheet in front of a torch and a dark shadow formed on the screen. He then put a frosted glass sheet of the same size in the same place. What will he observe?", fig: { type: "setups", items: [{ label: "Before", icon: "box", lines: ["Cardboard sheet", "Torch 20 cm away", "Dark shadow formed"] }, { label: "After", icon: "box", lines: ["Frosted glass sheet", "Same size and place", "Shadow: ?"] }] }, o: ["No shadow is formed at all", "A lighter shadow of the same shape", "A darker shadow of the same shape", "A lighter shadow that is much bigger"], a: 1, why: "Frosted glass is translucent: it blocks some light and lets some through, so its shadow is lighter. The sheet has the same size and position, so the shadow has the same shape and size.", lvl: 2 },
    { q: "Study the set-ups. Ivan wants to find out if the type of material affects how dark a shadow is. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Tracing paper", "10 cm by 10 cm", "Torch 20 cm away"] }, { label: "B", icon: "box", lines: ["Cardboard", "10 cm by 10 cm", "Torch 20 cm away"] }, { label: "C", icon: "box", lines: ["Cardboard", "5 cm by 5 cm", "Torch 20 cm away"] }, { label: "D", icon: "box", lines: ["Tracing paper", "10 cm by 10 cm", "Torch 30 cm away"] }] }, o: ["A and B", "A and C", "B and C", "A and D"], a: 0, why: "A and B differ only in the type of material. A and C differ in material and size; B and C, and A and D, use the same material, so they cannot test it.", lvl: 2 },
    { q: "Wen held a badminton racket in front of a lamp with its strings facing the lamp. What did its shadow on the wall look like?", o: ["A solid dark oval shape with a handle", "A dark frame and handle with a criss-cross net", "A dark handle only, with no oval frame", "A faint oval shape with a dark handle"], a: 1, why: "The frame, handle and strings are opaque and block light, but light travels straight through the gaps between the strings. So the shadow shows a dark frame and handle with a criss-cross pattern.", lvl: 2 },
    { q: "An object always forms a circular shadow, whichever way it is turned in front of a torch. Which object could it be?", o: ["A drink can", "An ice-cream cone", "A coin", "A tennis ball"], a: 3, why: "A ball has a circular outline from every direction. A can gives a rectangle from the side, a cone gives a triangle, and a coin seen edge-on gives a thin rectangle.", lvl: 2 },
    { q: "Ken placed sheets A, B, C and D, one at a time, between a torch and a light sensor in a dark room. Study the graph. Which statement is NOT correct?", fig: { type: "bar", title: "Light sensor readings", xl: "What was in front of the sensor", yl: "Light sensor reading (units)", bars: [["No sheet", 800], ["A", 780], ["B", 400], ["C", 0], ["D", 50]] }, o: ["A allows most light to pass through.", "B allows some light to pass through.", "C does not allow light to pass through.", "D allows more light to pass through than B."], a: 3, why: "D’s reading (50 units) is lower than B’s (400 units), so D lets LESS light through than B. A lets 780 of 800 units through (most light), B lets some through and C lets none through.", lvl: 2 },

    { q: "At a cinema, a projector shines a film onto a large white screen. Which statements are correct?\nA: The projector is a source of light.\nB: The screen gives out its own light.\nC: Light reflected by the screen enters the viewers’ eyes.", o: ["A only", "B and C only", "A and C only", "A, B and C"], a: 2, why: "The projector gives out light (A). The screen only reflects the projector’s light (B is wrong), and this reflected light enters the viewers’ eyes so they see the film (C).", lvl: 3 },
    { q: "A torch and a screen were 60 cm apart. Ali moved a card away from the torch and recorded the height of its shadow. One reading was recorded wrongly. Study the table. Which one?", tbl: [["Distance of card from torch (cm)", "10", "20", "30", "40", "50"], ["Height of shadow (cm)", "48", "24", "16", "20", "9.6"]], o: ["20 cm", "30 cm", "40 cm", "50 cm"], a: 2, why: "As the card moves away from the torch it blocks less light, so the shadow should keep getting smaller. At 40 cm the shadow (20 cm) is taller than at 30 cm (16 cm), which does not fit; it should be between 16 cm and 9.6 cm.", lvl: 3 },
    { q: "Ravi measured the light passing through one sheet of paper with a torch and a light sensor in a dark room. Which changes would make the reading HIGHER?\nA: Move the torch closer to the sensor.\nB: Use two sheets of the paper instead of one.\nC: Switch on the room lights.", o: ["A and C only", "A and B only", "B and C only", "A, B and C"], a: 0, why: "A closer torch sends more light to the sensor (A), and room lights add extra light that reaches the sensor (C). A second sheet blocks more light, so B lowers the reading.", lvl: 3 },
    { q: "Mdm Lim stands between a lamp and the translucent curtain of her HDB flat at night. Her neighbour in the dark corridor outside sees her shadow on the curtain. Why?", o: ["She blocks the lamp’s light, while the rest of the curtain lets some light through", "The curtain reflects the corridor light, which makes her shape appear on it", "The curtain is opaque, so it blocks all the light from the lamp in the room", "Her body gives out a dark light that passes through the curtain to the corridor"], a: 0, why: "Mdm Lim is opaque and blocks the lamp’s light, so that part of the curtain is dark. The translucent curtain lets some light through elsewhere, so it glows around her shadow. If the curtain were opaque, no shadow would be seen from outside.", lvl: 3 },
    { q: "Which of these is NOT evidence that light travels in straight lines?", o: ["Shadows form behind opaque objects", "We cannot see around a corner", "Torch beams look straight in mist", "A mirror reflects light very well"], a: 3, why: "Shadows, not seeing around corners and straight beams in mist all show that light cannot bend around objects. How well a mirror reflects light shows its surface is smooth and shiny, not that light travels in straight lines.", lvl: 3 },
    { q: "Tom tested one and two layers of papers P and Q with a torch and a light sensor in a dark room. Study the graph. Which conclusion is correct?", fig: { type: "bar", title: "Light through papers P and Q", xl: "Paper used", yl: "Light sensor reading (units)", bars: [["P, 1 layer", 600], ["P, 2 layers", 400], ["Q, 1 layer", 300], ["Q, 2 layers", 100]] }, o: ["Two layers of P let less light through than one layer of Q.", "One layer of Q lets less light through than two layers of P.", "Q allows more light to pass through than P does.", "Q is opaque, since its readings are the lowest."], a: 1, why: "One layer of Q (300 units) lets less light through than two layers of P (400 units). Q lets less light through than P at each number of layers, and Q is not opaque because its readings are above 0.", lvl: 3 },

    { q: "At 10 a.m., pupils measured the shadows of sticks of different heights standing on flat ground in the school field. Study the graph. At the same time, the shadow of the school flagpole was 4 m long. How tall is the flagpole?", fig: { type: "line", title: "Shadows of sticks at 10 a.m.", xl: "Height of stick (m)", yl: "Length of shadow (m)", pts: [["0.5", 0.4], ["1", 0.8], ["1.5", 1.2], ["2", 1.6]] }, o: ["3.2 m", "4 m", "5 m", "6.4 m"], a: 2, why: "At the same time the Sun is at the same height, so each shadow is 0.8 times the stick’s height (1 m gives 0.8 m). A 4 m shadow comes from a 5 m pole, since 5 x 0.8 = 4. 3.2 m wrongly multiplies the shadow by 0.8.", lvl: 4 },
    { q: "At night, Hafiz walks along a straight path towards a lit street lamp. His shadow falls behind him. What happens to the length of his shadow as he walks towards the lamp post?", o: ["It becomes longer, as he is closer to the light source", "It stays the same length, as he is the same height", "It becomes longer, then disappears under the lamp", "It becomes shorter, as the light falls on him more steeply"], a: 3, why: "The lamp is high above him. As he gets nearer, its light comes down more steeply, so he blocks light over a shorter stretch of ground. ‘Closer to the source, bigger shadow’ is for a shadow on a screen behind the object, not a shadow on the ground under a high lamp.", lvl: 4 },
    { q: "Sheets were placed, one set at a time, between a torch and a light sensor in a dark room. Study the table. Which statements are correct?\nA: X is transparent.\nB: A second sheet of Y blocked more light than a second sheet of X did.\nC: Two sheets of Z would give a reading above 0.\nD: Y is opaque, since two sheets of it gave a low reading.", tbl: [["In front of the sensor", "Reading (units)"], ["Nothing", "900"], ["1 sheet of X", "860"], ["2 sheets of X", "820"], ["1 sheet of Y", "350"], ["2 sheets of Y", "120"], ["1 sheet of Z", "0"]], o: ["A and B only", "A and C only", "B and D only", "A, B and C only"], a: 0, why: "X lets 860 of 900 units through, so it is transparent (A). The second sheet of Y cut the reading by 230 units but the second sheet of X by only 40 (B). One sheet of Z already lets no light through, so two sheets also give 0 (C is wrong), and Y still lets 120 units through, so it is not opaque (D is wrong).", lvl: 4 }
  ],
  oe: [
    { q: "Siew Ling placed a light sensor on a screen, in the shadow area behind sheets of the same size. She used the same torch at the same distance in a dark room. Study the graph.\n(a) Which sheet formed the darkest shadow? Explain using the results. (2 marks)\n(b) Explain why the reading behind the tracing paper was not 0.\n(c) Explain why there was hardly any shadow behind the clear plastic.", fig: { type: "bar", title: "Light reaching the sensor in the shadow", xl: "Sheet in front of the torch", yl: "Light sensor reading (units)", bars: [["No sheet", 750], ["Cardboard", 0], ["Tracing paper", 250], ["Clear plastic", 700]] }, marks: 4, kw: [["cardboard"], ["0", "zero", "no light", "lowest"], ["some light", "some of the light", "part of the light"], ["most light", "most of the light", "transparent"]], model: "(a) The cardboard. The reading in its shadow was 0, the lowest, so no light reached that area: the cardboard is opaque and blocked all the light. (b) Tracing paper is translucent, so it allows some light to pass through to the shadow area. (c) Clear plastic is transparent and allows most light to pass through, so the area behind it still received almost as much light as with no sheet." },
    { q: "Darren went into a storeroom with no windows and shut the door. It was completely dark.\n(a) Why could he not see the boxes in the room?\n(b) He switched on a torch and pointed it only at the white ceiling. He could now see the boxes on the floor, even though the torch was not pointed at them. Explain how. (2 marks)\n(c) Explain why this would work less well if the ceiling were painted black.", marks: 4, kw: [["no light"], ["ceiling reflect", "white ceiling reflect", "reflected by the ceiling", "reflected off the ceiling", "reflected from the ceiling", "reflected by the white ceiling", "reflected off the white ceiling", "reflected from the white ceiling"], ["eye"], ["less light", "reflects less", "reflect less", "little light", "absorb"]], x: 1, model: "(a) There was no light in the room, so no light was reflected from the boxes into his eyes. (b) The white ceiling reflected the torch light onto the boxes. The boxes reflected this light, and the reflected light entered Darren’s eyes. (c) A black ceiling reflects less light, so less light would fall on the boxes and be reflected into his eyes." },
    { q: "The Flower Dome at Gardens by the Bay has a roof made of glass panels.\n(a) Why is glass used for the roof?\n(b) On very sunny days, large sails inside the dome are opened below the glass to cut down the sunlight reaching the plants. Should the sails be made of a transparent, translucent or opaque material? Explain. (2 marks)\n(c) Explain how the sails form shade for the plants under them.", marks: 4, kw: [["most light", "most of the light", "most sunlight", "most of the sunlight", "transparent"], ["translucent"], ["some light", "some sunlight", "some of the light", "some of the sunlight"], ["block"]], model: "(a) Glass is transparent and allows most of the sunlight to pass through, so the plants get the light they need. (b) Translucent, because it allows some light to pass through, so the plants still get some sunlight but less than before. (c) The sails block part of the sunlight, and light travels in straight lines, so less sunlight reaches the area under them." },
    { q: "Study the set-up. An opaque bottle stands on a table between two lit lamps, P and Q, in a dark room.\n(a) How many shadows of the bottle are formed?\n(b) Which side of the bottle has the longer shadow? Explain. (2 marks)\n(c) Lamp Q is raised even higher. What happens to the shadow on the left of the bottle?", fig: { type: "setups", items: [{ label: "Lamp P", icon: "box", lines: ["Left of the bottle", "Low: 30 cm high"] }, { label: "Bottle", icon: "jar", lines: ["Opaque bottle", "20 cm tall"] }, { label: "Lamp Q", icon: "box", lines: ["Right of the bottle", "High: 80 cm high"] }] }, marks: 4, kw: [["two", "2"], ["right"], ["low"], ["shorter", "smaller"]], model: "(a) Two shadows, because the bottle blocks light from each lamp. (b) The shadow on the right side. It is formed by lamp P, which is lower, so its light shines on the bottle at a low angle and the bottle blocks light over a long area of the table. (c) The shadow on the left becomes shorter, because lamp Q shines down on the bottle more steeply and the bottle blocks light over a smaller area." }
  ],
  tf: [
    { s: "All sources of light give out a lot of heat.", a: false, why: "A firefly gives out light but almost no heat, so a source of light need not be hot." },
    { s: "The Sun is the main natural source of light for the Earth.", a: true, why: "The Sun gives out its own light, which travels through space to the Earth." },
    { s: "A shadow shows the colours and patterns on the side of the object facing the light.", a: false, why: "A shadow is only a dark area where light is blocked; it shows the outline of the object, not its colours or patterns." },
    { s: "We can see a lit bulb because the light it gives out enters our eyes.", a: true, why: "A lit bulb is a source of light, so its own light travels straight into our eyes." },
    { s: "A switched-off TV screen is a source of light.", a: false, why: "When it is switched off it gives out no light; we see it only by the light it reflects." },
    { s: "Light can pass through clean water.", a: true, why: "Clean water is transparent, which is why we can see fish in a clear aquarium." },
    { s: "Moving an object closer to the screen and away from the torch makes its shadow on the screen bigger.", a: false, why: "Further from the torch, the object blocks less of the light, so its shadow on the screen becomes smaller." },
    { s: "A mirror can be used to reflect light from a torch onto a wall.", a: true, why: "The smooth, shiny mirror reflects the torch light, which travels in a straight line to the wall." },
    { s: "We can see clearly through a translucent material.", a: false, why: "A translucent material allows only some light through, so things behind it look blurred." },
    { s: "Tinted car windows let less light into the car than clear windows.", a: true, why: "The tint blocks some of the light, so a light sensor would give a lower reading behind it." }
  ],
  sort: [
    { title: "Each object is held in front of a torch. Sort them by the shadow they form.", groups: ["Dark shadow", "Lighter shadow", "No clear shadow"], items: [["steel ruler", 0], ["wooden block", 0], ["ceramic tile", 0], ["tracing paper", 1], ["frosted plastic file", 1], ["greaseproof paper", 1], ["clear glass slide", 2], ["clear plastic ruler", 2], ["cling wrap", 2]] }
  ]
};
