window.LBY = window.LBY || {};
LBY["p4-light"] = {
  lessons: [
    {
      h: "Improving a light experiment and making results reliable",
      concept: "Booklet B often asks you to ‘suggest one improvement’. Two answers score almost every time. (1) RELIABILITY: repeat the test (for example 3 times) for each material and find the average reading, so that one odd reading does not change the result much. (2) FAIR TEST / ACCURACY: remove anything else that could change the readings, such as light from a window or room lights (do it in a dark room), a torch that is moved (keep the same distance) or pieces of different size or thickness. Always give the improvement AND the reason for it.",
      example: {
        q: "Kumar tested how much light passes through three fabrics. He tested each fabric only once, at a table next to an open window in the afternoon. Study his results.\n(a) Suggest one way to make his results more reliable.\n(b) Suggest one other improvement and explain why it is needed.",
        tbl: [["Fabric", "Light sensor reading (units)"], ["Cotton", "420"], ["Silk", "610"], ["Denim", "90"]],
        marks: 2,
        think: [
          "Step 1: ‘Reliable’ means the result can be trusted. One test can give an odd reading, so repeat each test and average.",
          "Step 2: Look for anything besides the fabric that could change the reading: sunlight from the open window.",
          "Step 3: Sunlight also reaches the sensor and changes during the afternoon, so the readings would not measure only the torch light.",
          "Step 4: Write the improvement and the reason: do the experiment in a dark room so only light from the torch reaches the sensor."
        ],
        answer: "(a) Repeat the test three times for each fabric and find the average reading. (b) Do the experiment in a dark room, away from the window, so that only light from the torch reaches the light sensor. Sunlight from the window would also reach the sensor and it changes during the afternoon, so it would change the readings."
      },
      tip: "‘Repeat and take the average’ = more reliable. ‘Dark room / same distance / same size’ = fairer. Always add ‘so that…’.",
      try: {
        q: "Which change will make Kumar’s results more reliable?",
        o: ["Repeat each test three times and find the average", "Test each fabric once, but more quickly", "Use a brighter torch for the thicker fabrics", "Test each fabric in a different room"],
        a: 0,
        why: "Repeating each test and averaging means one odd reading does not decide the result. Testing faster changes nothing, and using a different torch or room for some fabrics makes the test unfair."
      }
    }
  ],
  mcq: [
    { q: "Which of these materials allows the MOST light to pass through?", o: ["Greaseproof paper", "Frosted plastic", "Clear cling wrap", "Aluminium foil"], a: 2, why: "Clear cling wrap is transparent and allows most light to pass through. Greaseproof paper and frosted plastic are translucent (some light), and aluminium foil is opaque (no light).", lvl: 1 },
    { q: "Mr Koh tested four sunglasses lenses, one at a time, with a torch and a light sensor in a dark room. Study the table. Which lens lets the LEAST light through?", tbl: [["Lens", "W", "X", "Y", "Z"], ["Light sensor reading (units)", "210", "95", "330", "140"]], o: ["W", "X", "Y", "Z"], a: 1, why: "The lower the reading, the less light passed through the lens. X has the lowest reading (95 units). Y, with the highest reading, lets the most light through.", lvl: 1 },
    { q: "Which object reflects light but is NOT a source of light?", o: ["A lit candle", "A campfire", "A glowing firefly", "A bicycle reflector"], a: 3, why: "A bicycle reflector only reflects light, for example from car headlights. A lit candle, a campfire and a glowing firefly give out their own light.", lvl: 1 },

    { q: "Sara shone a torch at a card in front of a screen. Without moving the torch, the card or the screen, she switched the torch to a brighter setting. What happens to the size of the shadow?", o: ["It becomes bigger.", "It becomes smaller.", "It stays the same size.", "It disappears."], a: 2, why: "Misconception: a brighter light makes a bigger shadow. The size of the shadow depends on the positions of the torch, card and screen, which did not change. The screen around the shadow just becomes brighter.", lvl: 2 },
    { q: "Hui Ling added different numbers of drops of milk to the same volume of water in identical clear cups. She shone the same torch through each cup onto a light sensor in a dark room. Study the graph. Which conclusion is correct?", fig: { type: "line", title: "Light passing through milky water", xl: "Number of drops of milk", yl: "Light sensor reading (units)", pts: [["0", 800], ["2", 520], ["4", 330], ["6", 200], ["8", 120]] }, o: ["The more drops of milk added, the less light passed through.", "The more drops of milk added, the more light passed through.", "The water became opaque once 2 drops of milk were added.", "The number of drops of milk did not affect the light."], a: 0, why: "The reading falls from 800 to 120 units as more milk is added, so less light passes through. The water is not opaque, because every reading is above 0.", lvl: 2 },
    { q: "At a night show at Gardens by the Bay, the beams from the spotlights look like long, straight rods of light in the mist. This shows that light ______.", o: ["bends around objects", "travels in straight lines", "is given out by the mist", "can only travel at night"], a: 1, why: "Each beam is straight because light travels in straight lines. The mist does not give out light; it only lets us see the path of the beam. Light travels in the day too.", lvl: 2 },
    { q: "At night, a driver finds it harder to see a pedestrian wearing black clothes than one wearing white clothes. Why?", o: ["Dark clothes give out darkness that hides the person", "White clothes give out their own light in headlights", "Dark clothes reflect less light into the driver’s eyes", "Dark clothes let the headlight beams pass through them"], a: 2, why: "Misconception: dark objects ‘give out darkness’. Dark clothes reflect less of the headlight’s light, so less reflected light enters the driver’s eyes. White clothes are not a source of light, and cloth is opaque.", lvl: 2 },
    { q: "Study the Venn diagram. Which object has been placed in the WRONG part?", fig: { type: "venn", a: "Opaque", b: "Smooth and shiny", onlyA: ["wooden block", "cardboard"], both: ["mirror", "steel spoon"], onlyB: [], neither: ["tracing paper", "aluminium foil"] }, o: ["wooden block", "mirror", "tracing paper", "aluminium foil"], a: 3, why: "Aluminium foil does not let light through and is smooth and shiny, so it belongs in the overlap with the mirror. Tracing paper is translucent and dull, so ‘neither’ is correct for it.", lvl: 2 },
    { q: "Study the set-ups. Leon wants to find out if the size of an object affects the size of its shadow. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Small square card", "Torch 20 cm from card", "Screen 30 cm from card"] }, { label: "B", icon: "box", lines: ["Big square card", "Torch 20 cm from card", "Screen 30 cm from card"] }, { label: "C", icon: "box", lines: ["Big round card", "Torch 20 cm from card", "Screen 30 cm from card"] }, { label: "D", icon: "box", lines: ["Big square card", "Torch 30 cm from card", "Screen 30 cm from card"] }] }, o: ["A and B", "B and C", "B and D", "A and C"], a: 0, why: "A and B differ only in the size of the card. B and C differ in shape, B and D differ in torch distance, and A and C differ in both size and shape.", lvl: 2 },

    { q: "Which statements about an opaque wooden block are correct?\nA: It does not allow light to pass through.\nB: It forms a dark shadow when light shines on it.\nC: It reflects some of the light that falls on it.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "Misconception: opaque objects reflect no light. We can see the block only because it reflects some light into our eyes (C). It blocks all light (A), so it forms a dark shadow (B).", lvl: 3 },
    { q: "In a lift lobby, Ali looks into a large mirror on the wall and sees his friend standing behind him. Which statements are correct?\nA: Light from his friend is reflected by the mirror.\nB: The mirror gives out light that falls on his friend.\nC: The reflected light enters Ali’s eyes.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Light from his friend travels to the mirror, is reflected (A) and the reflected light enters Ali’s eyes (C). A mirror is not a source of light, so B is wrong.", lvl: 3 },
    { q: "Jia Ying recorded the shadow of a pole in an open field in Singapore on a sunny day. One row of her table was recorded WRONGLY. Which row?", tbl: [["Time", "Length of shadow (m)", "Direction of shadow"], ["8 a.m.", "6.0", "West"], ["10 a.m.", "3.0", "East"], ["12.30 p.m.", "0.4", "Almost none"], ["3 p.m.", "2.5", "East"], ["5 p.m.", "5.5", "East"]], o: ["8 a.m.", "10 a.m.", "3 p.m.", "5 p.m."], a: 1, why: "At 10 a.m. the Sun is still in the east, so the shadow must point west, away from the Sun. The 8 a.m. row points west, and the afternoon rows point east because the Sun is then in the west.", lvl: 3 },
    { q: "Kumar kept a torch, a stand and a screen in the same positions. He placed square cards of different heights on the stand and measured the height of each shadow. Study the graph. What is the most likely shadow height for a 5 cm card?", fig: { type: "line", title: "Shadows of different cards", xl: "Height of card (cm)", yl: "Height of shadow (cm)", pts: [["2", 6], ["4", 12], ["6", 18], ["8", 24]] }, o: ["5 cm", "12 cm", "15 cm", "18 cm"], a: 2, why: "Misconception: a shadow is always the same size as the object. Here each shadow is 3 times the card’s height (2 to 6, 4 to 12), so a 5 cm card gives about 15 cm, between the 4 cm and 6 cm results.", lvl: 3 },
    { q: "The same clear cup was placed between a torch and a light sensor in a dark room, first empty and then filled with different drinks. Study the table. Which statements are correct?\nA: The cup and the water both allow most light to pass through.\nB: Milk allows the least light to pass through.\nC: Barley water is opaque.", tbl: [["In the cup", "Nothing", "Water", "Barley water", "Milk"], ["Light sensor reading (units)", "850", "790", "450", "20"]], o: ["A only", "B only", "A and B only", "A, B and C"], a: 2, why: "The empty cup (850) and the cup with water (790) let most light through, so both are transparent (A). Milk has the lowest reading (B). Barley water still lets 450 units through, so it is not opaque (C is wrong).", lvl: 3 },
    { q: "In a dusty storeroom, sunlight coming through a small gap in the roof is seen as a bright beam from the side. In a clean room with no dust, the same beam cannot be seen from the side. Why?", o: ["Dust in the beam reflects some light into our eyes.", "Dust gives out its own light when sunlight hits it.", "Light travels in straight lines only through dust.", "Dust makes the sunlight bend around towards us."], a: 0, why: "Misconception: that we can see light travelling past us even when none of it enters our eyes. We see the beam only when dust reflects some of its light into our eyes. Dust is not a source of light, and light travels in straight lines with or without dust.", lvl: 3 },
    { q: "Study the flowchart. In which groups should a switched-OFF torch, clear cling wrap and greaseproof paper be placed?", fig: { type: "flow", root: "Objects", node: { q: "Gives out its own light?", yes: "P", no: { q: "Lets most light through?", yes: "Q", no: { q: "Lets some light through?", yes: "R", no: "S" } } } }, o: ["Torch S, cling wrap Q, paper R", "Torch P, cling wrap Q, paper R", "Torch S, cling wrap R, paper Q", "Torch P, cling wrap R, paper S"], a: 0, why: "A switched-off torch gives out no light and is opaque, so it is S. Clear cling wrap is transparent (Q) and greaseproof paper is translucent (R). Only a switched-ON torch would be P.", lvl: 3 },

    { q: "Which statements about a clear glass window are correct?\nA: It allows most light to pass through.\nB: It allows all the light to pass through.\nC: It reflects some of the light that falls on it.", o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Misconception: transparent means ALL light passes through. Clear glass allows most light through (A), not all (B is wrong). It also reflects some light, which is why we can faintly see reflections in a window, especially at night (C).", lvl: 4 },
    { q: "The graph shows the length of the shadow of a flagpole in Singapore on one sunny day. Which statement is correct?", fig: { type: "line", title: "Shadow of a flagpole", xl: "Time", yl: "Length of shadow (m)", pts: [["8 a.m.", 6], ["10 a.m.", 2.5], ["12 p.m.", 0.5], ["2 p.m.", 2], ["4 p.m.", 4.5]] }, o: ["The shadows at 10 a.m. and 2 p.m. pointed the same way.", "The shadow at 4 p.m. pointed towards the west.", "The Sun was lower in the sky at 2 p.m. than at 4 p.m.", "The Sun was lower in the sky at 8 a.m. than at 4 p.m."], a: 3, why: "A longer shadow means a lower Sun: 6 m at 8 a.m. is longer than 4.5 m at 4 p.m. At 10 a.m. the shadow points west and at 2 p.m. east; at 4 p.m. it points east; and the Sun was higher at 2 p.m. (shorter shadow).", lvl: 4 },
    { q: "Hana tested one sheet of tracing paper three times with the same torch, light sensor and distance in a dark room. Study her results. What should she do?", tbl: [["Trial", "1", "2", "3"], ["Light sensor reading (units)", "372", "368", "290"]], o: ["Repeat the trial that gave 290 units, as it does not fit the others", "Use 290 units as her result, as it is the lowest of the readings", "Add up all three readings and use 1030 units as her result", "Give up, as three different readings show the test cannot work"], a: 0, why: "Trials 1 and 2 agree closely, but 290 units is far off, perhaps because the torch or paper moved. She should repeat that trial and then average the readings that agree. Readings are not added up, and the lowest reading is not automatically correct.", lvl: 4 },
    { q: "Study the set-ups. Arun wants to find out if the number of layers of cloth affects how much light passes through. Which statements are correct?\nA: P and Q can be compared in a fair test.\nB: R should use cotton instead of silk.\nC: If R used 3 layers of cotton, it should give the lowest reading.", fig: { type: "setups", items: [{ label: "P", icon: "box", lines: ["1 layer of cotton", "Torch 20 cm from sensor", "Dark room"] }, { label: "Q", icon: "box", lines: ["2 layers of cotton", "Torch 20 cm from sensor", "Dark room"] }, { label: "R", icon: "box", lines: ["3 layers of silk", "Torch 20 cm from sensor", "Dark room"] }] }, o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "P and Q differ only in the number of layers (A). R changes the type of cloth as well, so it must use cotton (B). Each extra layer blocks more light, so 3 layers of cotton should give the lowest reading (C).", lvl: 4 }
  ],
  tf: [
    { s: "Shadows can be formed only in sunlight.", a: false, why: "A shadow forms whenever an opaque object blocks light from any light source, such as a torch, a lamp or a candle." },
    { s: "A mirror does not form a shadow because it reflects light.", a: false, why: "A mirror is opaque. It reflects light back, but it does not let light pass through, so it still forms a shadow behind it." },
    { s: "Adding more layers of tracing paper lets more light pass through.", a: false, why: "Each layer blocks some light, so the more layers there are, the less light passes through." },
    { s: "Only smooth, shiny objects reflect light.", a: false, why: "All objects that we see reflect some light into our eyes. Smooth, shiny surfaces simply reflect light better than dull, rough ones." },
    { s: "The shadow of an object is always the same size as the object.", a: false, why: "The shadow is bigger when the object is closer to the light source, and only about the same size when the object is right next to the screen." },
    { s: "A drop of cooking oil on brown paper lets more light pass through that part of the paper.", a: true, why: "The oily spot becomes more translucent, so it looks brighter when held up to a window." },
    { s: "Muddy water allows less light to pass through than clear water.", a: true, why: "The soil particles block some of the light." },
    { s: "We cannot see a candle flame through a bent hose because light cannot travel around the bend.", a: true, why: "Light travels in straight lines, so the opaque walls of the hose block it." },
    { s: "The shadow of a stick moves during the day because the position of the Sun in the sky changes.", a: true, why: "The shadow is always on the side away from the Sun, so it moves as the Sun’s position changes from east to west." },
    { s: "If we can see an object that is not a source of light, it must be reflecting light into our eyes.", a: true, why: "Objects that do not give out their own light are seen only by the light they reflect into our eyes." }
  ],
  oe: [
    { q: "Lin stirred different numbers of spoonfuls of soil into 200 ml of water in identical glass beakers. She shone the same torch through each beaker onto a light sensor in a dark room. Study the table.\n(a) Describe the relationship between the amount of soil and the light sensor reading.\n(b) Explain this relationship.\n(c) Suggest one way to make her results more reliable.\n(d) Why did she use 200 ml of water in every beaker?", tbl: [["Spoonfuls of soil", "0", "1", "2", "3", "4"], ["Light sensor reading (units)", "820", "560", "370", "230", "140"]], marks: 4, kw: [["decrease", "lower", "fewer", "less light", "smaller", "drop", "fall"], ["block"], ["repeat", "more times", "average"], ["fair", "only the amount of soil", "only one variable"]], x: 1, model: "(a) As the amount of soil increases, the light sensor reading decreases. (b) The soil particles block light, so the more soil there is, the more light is blocked and the less light passes through the water to the sensor. (c) Repeat the experiment three times for each amount of soil and find the average reading. (d) To make it a fair test, so that only the amount of soil is changed." },
    { q: "Farhan put different numbers of drops of cooking oil on pieces of the same brown paper. He placed each piece, one at a time, between a torch and a light sensor in a dark room. Study the graph.\n(a) What variable did he change?\n(b) What can he conclude from the results?\n(c) He wants paper for a lantern that gives a soft glow but does not let people see the candle inside clearly. Should he use paper with 0 drops or 6 drops of oil? Explain using the results.", fig: { type: "bar", title: "Light passing through oiled paper", xl: "Paper used", yl: "Light sensor reading (units)", bars: [["No paper", 900], ["0 drops", 40], ["2 drops", 180], ["4 drops", 310], ["6 drops", 420]] }, marks: 3, kw: [["number of drops", "drops of oil", "amount of oil", "amount of cooking oil"], ["more drops", "more oil"], ["translucent", "some light", "some of the light"]], model: "(a) The number of drops of oil on the paper. (b) The more drops of oil on the paper, the more light passed through it. (c) 6 drops. Its reading of 420 units is higher than 40 units, so more light passes through to give a glow, but it is lower than 900 units, so it is translucent and lets only some light through; people cannot see the candle clearly." },
    { q: "Study the set-ups. Nadia looked at a lit candle through a rubber hose.\n(a) In which set-up could she see the flame?\n(b) Explain why she could not see the flame in the other set-up.\n(c) What does this experiment show about light?", fig: { type: "setups", items: [{ label: "P", icon: "box", lines: ["Straight rubber hose", "Candle at one end", "Eye at the other end"] }, { label: "Q", icon: "box", lines: ["Hose bent into a U", "Candle at one end", "Eye at the other end"] }] }, marks: 3, kw: [["p"], ["block"], ["travels in straight", "travel in straight", "straight line"]], model: "(a) Set-up P. (b) In set-up Q, light from the flame cannot follow the bend. The opaque walls of the hose block the light, so it cannot enter her eyes. (c) Light travels in straight lines." },
    { q: "Pupils in a Singapore school stood a stick upright in an open field on a sunny day and recorded its shadow. Study the table.\n(a) Explain why the direction of the shadow changed during the day.\n(b) Explain why the shadow was shortest at 12.30 p.m.\n(c) The next afternoon was very cloudy and the pupils could not see a clear shadow. Explain why.", tbl: [["Time", "Length of shadow (cm)", "Direction of shadow"], ["9 a.m.", "80", "West"], ["11 a.m.", "30", "West"], ["12.30 p.m.", "5", "Almost none"], ["3 p.m.", "55", "East"], ["5 p.m.", "110", "East"]], marks: 3, kw: [["position of the sun", "sun move", "sun change", "sun's position", "sun’s position", "sun was in the east", "sun is in the east", "sun was in the west", "sun is in the west"], ["high", "overhead"], ["clouds block", "cloud block", "clouds covered", "covered the sun", "blocked by the clouds", "blocked by clouds", "little sunlight", "no sunlight", "not enough sunlight"]], model: "(a) The position of the Sun in the sky changed. In the morning the Sun was in the east, so the shadow pointed west; in the afternoon the Sun was in the west, so the shadow pointed east. (b) At 12.30 p.m. the Sun was high in the sky, so the stick blocked light over only a small area of the ground. (c) The clouds blocked the sunlight, so very little sunlight reached the stick and no clear shadow was formed." },
    { q: "A large curved mirror is fixed at a blind corner of an HDB multi-storey car park.\n(a) Explain how a driver is able to see a car coming around the corner in the mirror. (2 marks)\n(b) Explain why the driver cannot see that car directly without the mirror.\n(c) After many months the mirror became dusty and dull. Why did drivers find it harder to see cars in it?", marks: 4, kw: [["reflect"], ["eye"], ["straight"], ["less light", "reflects less", "does not reflect as much", "poorly"]], model: "(a) Light from the car travels to the mirror and is reflected by the smooth, shiny mirror. The reflected light enters the driver’s eyes. (b) Light travels in straight lines, so light from the car is blocked by the wall at the corner and cannot reach the driver’s eyes. (c) A dusty, dull surface does not reflect light as well, so less light from the car is reflected into the driver’s eyes." },
    { q: "Priya thinks that a brighter torch makes a bigger shadow. She kept a torch, a card and a screen in the same positions and changed only the brightness setting of the torch. Study her results.\n(a) Was Priya right? Explain using the results.\n(b) Why did she keep the torch, the card and the screen in the same positions?\n(c) Without using a different card, suggest how she could make the shadow bigger. Explain.", tbl: [["Brightness setting", "Low", "Medium", "High"], ["Height of shadow (cm)", "12", "12", "12"]], marks: 3, kw: [["stayed the same", "remained the same", "same height", "same size", "no change", "did not change", "stayed at 12", "12 cm at all", "did not affect"], ["fair", "only the brightness", "only one variable"], ["closer to the torch", "nearer the torch", "nearer to the torch", "towards the torch", "torch closer", "torch nearer", "screen further", "screen away"]], x: 1, model: "(a) No. The height of the shadow stayed the same, 12 cm, at all three brightness settings, so the brightness of the torch did not affect the size of the shadow. (b) To make it a fair test, so that only the brightness of the torch was changed. (c) Move the card closer to the torch, so that it blocks more light and the shadow becomes bigger." }
  ],
  doc: [
    { q: "Explain why a lampshade made of tracing paper gives a softer light than a bare bulb.", marks: 2, answers: ["Because tracing paper is very thin.", "The tracing paper makes the bulb less hot, so it is softer.", "Tracing paper is translucent, so it allows only some of the light from the bulb to pass through, and less light reaches our eyes."], best: 2, why: "Answer 3 names the property (translucent) and links it to the effect (only some light passes through, so the light is softer). Answer 1 gives a fact about the paper without saying what it does to light. Answer 2 is about heat, not light." },
    { q: "Hana tested each material only once with a torch and a light sensor. Suggest one way to make her results more reliable and explain why.", marks: 2, answers: ["Repeat the test three times for each material and find the average reading, so that one odd reading does not affect the result much.", "Do the experiment more carefully.", "Use a different torch for each material so that it is fair."], best: 0, why: "Answer 1 gives a clear improvement (repeat and average) and the reason. Answer 2 is too vague: it does not say what to do. Answer 3 is wrong: using different torches makes the test unfair." }
  ]
};
