window.LBX = window.LBX || {};
LBX["p4-mixed"] = {
  notes: [
    { h: "Shadow size, position and length", t: "A shadow forms on the side of the object away from the light source, because light travels in straight lines and the opaque object blocks it. The nearer the object is to the light source, the bigger its shadow; moving it towards the screen makes the shadow smaller. Outdoors, shadows are long when the Sun is low (morning, late afternoon) and shortest at about noon, when the Sun is highest.", kw: ["nearer the light source", "bigger shadow", "opposite side", "Sun is low"] },
    { h: "What is matter and what is not", t: "Matter is anything that has mass and occupies space: solids, liquids and gases, and every living thing. Light, heat, sound and shadows are NOT matter, because they have no mass and do not occupy space. Air occupies space: a tissue at the bottom of an upside-down cup pushed into water stays dry because the trapped air keeps the water out.", kw: ["has mass and occupies space", "not matter", "air occupies space", "living things are matter"] },
    { h: "Following water through a plant and a human", t: "In a plant, the roots absorb water and mineral salts from the soil, the stem carries the water up to the leaves, and the leaves use it to make food. A wilting plant becomes firm again after watering as water travels root → stem → leaves. In a human, water taken in passes along the digestive system, and the large intestine absorbs water from the undigested food.", kw: ["roots absorb water", "stem carries water", "leaves make food", "large intestine absorbs water"] }
  ],
  traps: [
    "A Styrofoam box keeps the cold in -> There is no ‘cold’ that flows; Styrofoam is a poor conductor of heat, so heat from the surroundings flows INTO the box slowly.",
    "Moving an object nearer the screen makes its shadow bigger -> Moving it nearer the LIGHT SOURCE makes the shadow bigger.",
    "Light, heat and shadows are matter -> They have no mass and do not occupy space, so they are not matter."
  ],
  lessons: [
    {
      h: "Reading a shadow-size graph",
      concept: "In shadow experiments the light source and screen usually stay fixed while the object moves. Read the graph as a trend: nearer the light source → the object blocks more of the light spreading out from the source → bigger shadow. Explain the shadow itself with two ideas: light travels in straight lines, and the opaque object blocks the light.",
      example: {
        q: "A 4 cm tall toy was placed at different distances from a torch, and the height of its shadow on a screen was measured. Study the graph.\n(a) Describe how the shadow height changes as the toy moves away from the torch. [1]\n(b) Explain how the shadow is formed. [2]",
        fig: { type: "line", title: "Shadow of a toy", xl: "Distance of toy from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 24], ["20", 12], ["30", 8], ["40", 6]] },
        marks: 3,
        think: [
          "Step 1: Read the trend: 24 cm at 10 cm, falling to 6 cm at 40 cm.",
          "Step 2: So as the toy moves further from the torch, its shadow becomes smaller.",
          "Step 3: Shadow formation needs two ideas: light travels in straight lines, and the opaque toy blocks the light.",
          "Step 4: One idea per mark; do not just copy numbers without a trend."
        ],
        answer: "(a) As the toy moves further away from the torch, the height of its shadow decreases. (b) Light travels in straight lines. The toy is opaque and blocks the light, so an area behind it on the screen receives no light and a shadow forms."
      },
      tip: "Nearer the light = bigger shadow. Straight lines + blocks light = how the shadow forms.",
      try: {
        q: "Rina wants the shadow of her puppet on the wall to be bigger. The torch and wall stay where they are. What should she do?",
        o: ["Move the puppet nearer to the torch", "Move the puppet nearer to the wall", "Turn the puppet so it faces the wall", "Hold the puppet higher up in the air"],
        a: 0,
        why: "The nearer the puppet is to the light source, the more light it blocks, so the shadow is bigger. Moving it towards the wall makes the shadow smaller."
      }
    },
    {
      h: "Explaining ‘keeping things cold’ with heat flow",
      concept: "Markers do not accept ‘keeps the cold in’. Heat only flows from a hotter place to a colder one. Ice melts because it GAINS heat from the warmer surroundings. A poor conductor of heat (Styrofoam, cloth, air) around the ice slows down this heat flow, so the ice gains heat slowly and melts more slowly.",
      example: {
        q: "At a drinks stall, ice is kept in a Styrofoam box instead of a metal tin. Explain why the ice lasts longer in the Styrofoam box. [2]",
        marks: 2,
        think: [
          "Step 1: Which way does heat flow? From the warmer surroundings into the colder ice.",
          "Step 2: Property of the material: Styrofoam is a poor conductor of heat; metal is a good conductor.",
          "Step 3: Effect: heat flows into the Styrofoam box slowly, so the ice gains heat slowly and melts slowly.",
          "Step 4: Avoid the word ‘cold’ as something that moves."
        ],
        answer: "Styrofoam is a poor conductor of heat, so heat from the surroundings flows into the box slowly. The ice gains heat more slowly and melts more slowly than in a metal tin."
      },
      tip: "Heat flows IN to cold things. Poor conductor = heat flows in slowly.",
      try: {
        q: "Which statement correctly explains why a packet of ice cream stays frozen longer when wrapped in newspaper?",
        o: ["Newspaper is a poor conductor of heat, so the ice cream gains heat slowly.", "Newspaper is a good conductor of heat, so heat leaves the ice cream quickly.", "Newspaper stops the coldness in the ice cream from flowing out to the air.", "Newspaper is opaque, so no heat at all can flow into the ice cream packet."],
        a: 0,
        why: "Heat flows from the warm surroundings into the ice cream. Newspaper conducts heat poorly, so the ice cream gains heat slowly. ‘Coldness’ does not flow, and some heat still gets in."
      }
    }
  ],
  mcq: [
    { q: "Study the diagram. After food leaves part B, which part does it enter next?", o: ["A", "B", "C", "D"], a: 2, why: "B is the stomach. Food then passes into C, the small intestine, and later into D, the large intestine. A is the gullet, which comes before the stomach.", lvl: 1, fig: { type: "organs", system: "digestive", mark: { gullet: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } } },
    { q: "Which of these is a light source?", o: ["A lit candle", "A mirror", "The Moon", "A glass window"], a: 0, why: "A lit candle gives out its own light. A mirror and the Moon only reflect light, and a glass window lets light pass through.", lvl: 1 },
    { q: "Which of these is NOT matter?", o: ["Air in a tyre", "Light from a torch", "Steam from a kettle", "Water in a cup"], a: 1, why: "Light has no mass and does not occupy space, so it is not matter. Air and steam are gases and water is a liquid; all are matter.", lvl: 1 },
    { q: "Study the diagram. Which part carries water from the roots to the leaves?", o: ["P", "R", "S", "Q"], a: 3, why: "Q is the stem, which carries water and mineral salts from the roots (P) up to the leaves (R) and flower (S).", lvl: 1, fig: { type: "plant", mark: { roots: "P", stem: "Q", leaf: "R", flower: "S" } } },
    { q: "Oven gloves are made of thick cloth. This is because cloth is…", o: ["a good conductor of heat", "a poor conductor of heat", "attracted by a magnet", "transparent to light"], a: 1, why: "Cloth is a poor conductor of heat, so heat from a hot tray flows slowly to the hand. A good conductor would let the hand get burnt.", lvl: 1 },

    { q: "Identical ice cubes were wrapped in different materials and left on a table. Study the graph. Which material is the poorest conductor of heat?", o: ["Aluminium foil", "Cloth", "Styrofoam", "No wrapping"], a: 2, why: "The ice wrapped in Styrofoam took the longest to melt (80 min), so heat from the surroundings flowed through Styrofoam the most slowly.", lvl: 2, fig: { type: "bar", title: "Time for ice cube to melt completely", xl: "Wrapping", yl: "Time (min)", bars: [["No wrapping", 20], ["Aluminium foil", 25], ["Cloth", 55], ["Styrofoam", 80]] } },
    { q: "Farid has a 1 kg bag of rice and a 1 kg bag of feathers. Which statement is correct?", o: ["Both have the same mass, but the feathers occupy more space.", "The rice has more mass because it is a heavier material.", "The feathers have more mass because they take up more space.", "Both occupy the same space because they have the same mass."], a: 0, why: "Both have a mass of 1 kg. The feathers take up much more space (a larger volume), so having the same mass does not mean occupying the same space.", lvl: 2 },
    { q: "Study the classification chart. Which of these would be placed at B?", o: ["Steam", "A marble", "Air in a ball", "Honey"], a: 3, why: "B has no definite shape but a definite volume, so it is a liquid: honey. A marble is a solid (A); steam and air are gases (C).", lvl: 2, fig: { type: "flow", root: "Matter", node: { q: "Definite shape?", yes: "A", no: { q: "Definite volume?", yes: "B", no: "C" } } } },
    { q: "Sam chewed a plain cracker for a long time, and it began to taste slightly sweet. What does this show?", o: ["Digestion begins in the mouth, where a digestive juice breaks down food.", "Digestion begins in the stomach, where food is first broken down.", "The cracker is absorbed into the bloodstream while still in the mouth.", "The teeth turn the cracker into sugar just by grinding it into bits."], a: 0, why: "Saliva, a digestive juice in the mouth, starts breaking down the cracker into simpler substances, one of which tastes sweet. Chewing alone only breaks food into smaller pieces.", lvl: 2 },
    { q: "A potted plant had drooping leaves. Wei Ling watered the soil, and a few hours later the leaves were firm again. Study the diagram. In which order did the water pass through the labelled parts?", o: ["R → Q → P", "Q → P → R", "P → Q → R", "P → R → Q"], a: 2, why: "The roots (P) absorb water from the soil, the stem (Q) carries it up, and it reaches the leaves (R).", lvl: 2, fig: { type: "plant", mark: { roots: "P", stem: "Q", leaf: "R" } } },
    { q: "Ali stood around a corner and used a mirror to see his friend. Which statement explains how he saw his friend?", o: ["Light from Ali’s eyes travelled to the mirror and on to his friend.", "Light from his friend was reflected by the mirror into Ali’s eyes.", "The mirror gave out its own light, which lit up his friend’s face.", "Light bent around the corner of the wall and then reached Ali’s eyes."], a: 1, why: "We see an object when light from it enters our eyes. Light from the friend travelled in a straight line to the mirror, which reflected it into Ali’s eyes. Eyes do not give out light, and a mirror is not a light source.", lvl: 2 },
    { q: "Study the set-ups. A dry tissue was stuck to the base of a cup, and the cup was pushed straight down, upside down, into water. In A, the tissue stayed dry. Why?", o: ["The tissue was stuck on too firmly for the water to reach it.", "The water lost heat to the cup, so it could not rise inside.", "Water is a liquid, so it has no definite volume to fill the cup.", "Air trapped in the cup occupied space and kept the water out."], a: 3, why: "The cup was full of air, and air occupies space, so the water could not fill the cup. Water does have a definite volume; it is its shape that is not definite.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Cup pushed upside down", "Dry tissue at the base", "Tissue stays dry"] }, { label: "B", icon: "beaker", lines: ["Cup with hole in base", "Dry tissue at the base", "Result: ?"] }] } },
    { q: "Study the life cycle. Which animal has this life cycle?", o: ["Mosquito", "Cockroach", "Butterfly", "Mealworm beetle"], a: 1, why: "The cockroach has a three-stage life cycle: egg, nymph, adult. The mosquito, butterfly and mealworm beetle all have a pupa stage (four stages).", lvl: 2, fig: { type: "cycle", stages: ["Egg", "Nymph", "Adult"] } },

    { q: "In the late afternoon, the Sun is low in the western sky. Which describes the shadow of a lamp post at that time?", o: ["It points towards the east and is long.", "It points towards the west and is long.", "It points towards the east and is short.", "It points towards the west and is short."], a: 0, why: "A shadow forms on the side away from the light source, so with the Sun in the west it points east. A low Sun gives a long shadow.", lvl: 3 },
    { q: "Mei held an ice cube in her palm. Which statements are correct?\nA: Heat flowed from her hand to the ice.\nB: The ice gained heat and melted.\nC: Coldness flowed from the ice into her hand.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Heat flows from the warmer hand to the colder ice, so the ice gains heat and melts. Her hand feels cold because it LOSES heat; ‘coldness’ does not flow.", lvl: 3 },
    { q: "Study the set-ups. Jun wants to find out if covering a cup with a lid affects how fast hot water in it cools. Which two set-ups should he compare?", o: ["A and B", "A and C", "B and C", "C and D"], a: 2, why: "B and C differ only in the lid. A and B differ in material and lid, A and C differ in material, and C and D differ in the volume of water.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["Metal cup, no lid", "200 ml water at 80 °C"] }, { label: "B", icon: "pot", lines: ["Styrofoam cup, lid", "200 ml water at 80 °C"] }, { label: "C", icon: "pot", lines: ["Styrofoam cup, no lid", "200 ml water at 80 °C"] }, { label: "D", icon: "pot", lines: ["Styrofoam cup, no lid", "100 ml water at 80 °C"] }] } },
    { q: "Study the diagram. Which statements are correct?\nA: Digestive juices break down food in P and R.\nB: No digestion takes place in Q.\nC: Digested food is absorbed into the bloodstream in S.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "P (mouth) and R (stomach) have digestive juices, and Q (gullet) only moves food. S is the large intestine, which absorbs water, not digested food; that happens in the small intestine.", lvl: 3, fig: { type: "organs", system: "digestive", mark: { mouth: "P", gullet: "Q", stomach: "R", large_intestine: "S" } } },
    { q: "A cold can drink from the fridge was left on a table. Study the graph of its temperature. Which is the best explanation for the graph after 40 minutes?", o: ["The drink began to lose heat to the air, so it stayed at 27 °C.", "The can became a poor conductor of heat after 40 minutes.", "Coldness stopped flowing out of the drink into the room.", "The drink reached room temperature, so it stopped gaining heat."], a: 3, why: "The drink gained heat from the warmer air until it reached room temperature (27 °C). With no temperature difference, there is no more heat flow, so the temperature stays the same.", lvl: 3, fig: { type: "line", title: "Temperature of a can drink", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 6], ["10", 14], ["20", 20], ["30", 25], ["40", 27], ["50", 27], ["60", 27]] } },
    { q: "Study the table. A magnet was used to pull pieces of one material out of a mixture of W, X, Y and Z. Which material was removed, and which of the others is best for a window that people can see through clearly?", o: ["Y; W", "X; Z", "X; W", "Y; Z"], a: 2, why: "Only X is attracted by a magnet. Of the rest, W lets most light pass through (transparent), so objects behind it are seen clearly. Z is translucent, so objects look blurred.", lvl: 3, tbl: [["Material", "Light passing through", "Conducts heat", "Attracted by a magnet"], ["W", "Most", "Poorly", "No"], ["X", "None", "Well", "Yes"], ["Y", "None", "Well", "No"], ["Z", "Some", "Poorly", "No"]] },
    { q: "Study the Venn diagram. Which organism should replace the ‘?’ in the overlap?", o: ["Rose", "Fern", "Yeast", "Mango tree"], a: 1, why: "A fern is a plant that makes its own food and reproduces by spores. Roses and mango trees make food but reproduce by seeds; yeast is a fungus and cannot make its own food.", lvl: 3, fig: { type: "venn", a: "Makes its own food", b: "Reproduces by spores", onlyA: ["hibiscus"], both: ["?"], onlyB: ["mushroom", "bread mould"], neither: ["cat"] } },

    { q: "A 5 cm tall toy was moved between a torch and a screen that was 60 cm from the torch. Study the graph. Which change would make the shadow closest to 5 cm tall?", o: ["Move the toy to 5 cm from the torch", "Move the toy back to 30 cm from the torch", "Move the toy until it touches the screen", "Use a brighter torch with the toy at 10 cm"], a: 2, why: "The shadow shrinks as the toy moves away from the torch (6 cm at 50 cm), so at the screen it is about the toy’s own height. Moving it nearer the torch makes it bigger, and brightness does not change the size.", lvl: 4, fig: { type: "line", title: "Shadow of a 5 cm toy", xl: "Distance of toy from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 30], ["20", 15], ["30", 10], ["40", 7.5], ["50", 6]] } },
    { q: "Study the diagram. In a patient, part C is not working well and absorbs very little water. What is most likely to be observed?", o: ["Food cannot be broken down in part A.", "Digested food is not absorbed into the blood.", "Food cannot be swallowed down to part A.", "Undigested food leaving the body is watery."], a: 3, why: "C is the large intestine, which absorbs water from undigested food. If little water is absorbed, the waste leaving through the anus is watery. The stomach (A) and small intestine (B) still work.", lvl: 4, fig: { type: "organs", system: "digestive", mark: { stomach: "A", small_intestine: "B", large_intestine: "C" } } },
    { q: "A steel ball just passes through a steel ring at room temperature. After the ball is heated, it no longer passes through. What could be done so that the hot ball passes through again?", o: ["Cool the ring so that it contracts", "Heat the ball further so it expands", "Place the ring and ball on a magnet", "Heat the ring so that it expands"], a: 3, why: "The hot ball has expanded. Heating the ring makes it gain heat and expand too, so its hole becomes bigger. Cooling the ring makes the hole smaller; a magnet does not change their sizes.", lvl: 4 },
    { q: "Rods of the same length and thickness had one end in hot water. Study the table. Which statements are supported?\nA: Copper conducts heat better than steel.\nB: Aluminium is a poorer conductor of heat than glass.\nC: Glass is a poor conductor of heat.\nD: Steel conducts heat faster than aluminium because it is magnetic.", o: ["A and C only", "A and D only", "A, C and D only", "B, C and D only"], a: 0, why: "Copper melted the wax fastest (40 s) and steel slower (90 s), so A is supported; glass did not melt it at all, so C is supported. Aluminium (55 s) beat both steel and glass, so B and D are wrong; magnetism has nothing to do with conducting heat.", lvl: 4, tbl: [["Rod", "Time for wax at far end to melt"], ["Copper", "40 s"], ["Aluminium", "55 s"], ["Steel", "90 s"], ["Glass", "Not melted after 10 min"]] }
  ],
  tf: [
    { s: "Light is matter because it can fill a room.", a: false, why: "Light has no mass and does not occupy space, so it is not matter." },
    { s: "An object placed nearer a light source casts a bigger shadow.", a: true, why: "It blocks more of the light spreading out from the source." },
    { s: "A Styrofoam cooler box keeps the coldness in.", a: false, why: "Styrofoam is a poor conductor of heat, so heat from the surroundings flows in slowly." },
    { s: "A mirror is a light source.", a: false, why: "A mirror only reflects light; it does not give out its own light." },
    { s: "Digestion of food is completed in the small intestine.", a: true, why: "Food is broken down in the mouth and stomach, and digestion is completed in the small intestine." },
    { s: "Water absorbed by the roots is carried up the stem to the leaves.", a: true, why: "The stem carries water and mineral salts from the roots to other parts of the plant." },
    { s: "Mosquito larvae live in water.", a: true, why: "Eggs are laid in water, and the larvae and pupae develop there." },
    { s: "A sealed balloon left in the hot sun gets bigger, but the mass of air inside stays the same.", a: true, why: "The air gains heat and expands; no air enters or leaves." },
    { s: "A mushroom makes its own food like a plant.", a: false, why: "A mushroom is a fungus; it cannot make its own food and gets it from other things." },
    { s: "A steel spoon and an aluminium spoon are both attracted by a magnet.", a: false, why: "Steel is magnetic but aluminium is not, although both are good conductors of heat." }
  ],
  sort: [
    {
      title: "Sort these into matter and not matter.",
      groups: ["Matter", "Not matter"],
      items: [["Air in a balloon", 0], ["Steam from a kettle", 0], ["A mushroom", 0], ["Orange juice", 0], ["Sand", 0], ["Light from the Sun", 1], ["A shadow", 1], ["Heat from a stove", 1]]
    }
  ],
  oe: [
    { q: "An ice seller covers a large block of ice with a thick cloth sack. The block lasts longer than an uncovered block.\n(a) Explain why the covered ice lasts longer. [2]\n(b) The seller says, ‘The sack keeps the cold in.’ Correct his statement. [1]", marks: 3, kw: [["poor conductor"], ["slowly", "slower", "more slowly"], ["heat flows in", "heat flows to", "heat from the surroundings flows", "heat, not cold", "cold does not flow"]], model: "(a) The cloth sack is a poor conductor of heat, so heat from the surroundings is conducted to the ice slowly. The ice gains heat more slowly and melts more slowly. (b) Cold does not flow. Heat flows into the ice from the warmer surroundings, and the sack only slows it down." },
    { q: "A 3 cm tall puppet was placed at different distances from a lamp, and the height of its shadow on a wall was measured. Study the graph.\n(a) Describe how the shadow height changes as the puppet moves further from the lamp. [1]\n(b) Predict whether the shadow would be more or less than 6 cm tall if the puppet were 40 cm from the lamp. [1]\n(c) Explain how the shadow is formed. [2]", marks: 4, kw: [["decrease", "smaller", "shorter", "gets less"], ["less than 6", "smaller than 6", "shorter than 6", "below 6", "under 6"], ["straight line"], ["block", "opaque"]], model: "(a) As the puppet moves further from the lamp, the shadow height decreases. (b) Less than 6 cm. (c) Light travels in straight lines. The puppet is opaque and blocks the light, so an area of the wall behind it receives no light.", fig: { type: "line", title: "Shadow of a 3 cm puppet", xl: "Distance of puppet from lamp (cm)", yl: "Height of shadow (cm)", pts: [["10", 18], ["15", 12], ["20", 9], ["30", 6]] }, x: 1 },
    { q: "Study the life cycle of a mosquito.\n(a) Name stage X. [1]\n(b) Residents are told to turn over pails and clear stagnant water from flower pot plates. Explain how this reduces the number of mosquitoes. [2]", marks: 3, kw: [["pupa"], ["eggs are laid", "lay eggs", "lay their eggs", "eggs in water"], ["larva", "larvae", "cannot develop", "cannot grow"]], model: "(a) Pupa. (b) Mosquitoes lay eggs in stagnant water, and the larvae and pupae live and develop in water. Without stagnant water, the eggs cannot be laid there and the young cannot develop into adults.", fig: { type: "cycle", stages: ["Egg", "Larva", "X", "Adult"] } },
    { q: "Hui Min ate a slice of wholemeal bread. Study the diagram of her digestive system.\n(a) Name part C, where digested food is absorbed into the bloodstream. [1]\n(b) What does part D do to the undigested food? [1]\n(c) The bread was made from wheat grains. Which part of the wheat plant made the food stored in the grains? [1]", marks: 3, kw: [["small intestine"], ["water"], ["leaves", "leaf"]], model: "(a) The small intestine. (b) Part D, the large intestine, absorbs water from the undigested food. (c) The leaves, which make food for the plant.", fig: { type: "organs", system: "digestive", mark: { mouth: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } } },
    { q: "Spoons of the same size made of different materials were placed in the same pot of hot curry, and a bead of butter was put on the top end of each. Study the graph.\n(a) Which spoon is best for stirring the hot curry without burning the hand? [1]\n(b) Explain your answer. [2]", marks: 3, kw: [["wood"], ["poor conductor"], ["slowly", "slow", "longest"]], model: "(a) The wooden spoon. (b) The butter on it took the longest time to melt, so wood is a poor conductor of heat. Heat is conducted slowly from the curry to the hand, so the hand does not get burnt.", fig: { type: "bar", title: "Time for butter to melt", xl: "Material of spoon", yl: "Time (s)", bars: [["Steel", 60], ["Aluminium", 35], ["Plastic", 400], ["Wood", 600]] } },
    { q: "Study the set-up. A funnel was fitted tightly into the mouth of an empty bottle, and the gap was sealed with plasticine. When water was poured into the funnel, very little water flowed into the bottle.\n(a) Explain why very little water entered the bottle. [2]\n(b) A small hole was then made in the plasticine, and the water flowed in easily. Explain why. [1]", marks: 3, kw: [["occupies space", "occupy space", "takes up space"], ["no space", "no room", "keeps the water", "kept the water"], ["escape", "out through the hole", "pushed out"]], model: "(a) The bottle was filled with air, and air occupies space. The trapped air had no space to go, so it kept the water out. (b) The air could escape out through the hole, so the water could take up the space it left.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Funnel in bottle", "Gap sealed", "Little water enters"] }, { label: "B", icon: "jar", lines: ["Funnel in bottle", "Small hole in seal", "Water flows in"] }] } },
    { q: "Two glass tumblers are stuck, one inside the other. Aunty Lim stands the outer tumbler in hot water and pours cold water into the inner tumbler, and they come apart easily.\n(a) Explain why standing the outer tumbler in hot water helps. [2]\n(b) Explain why pouring cold water into the inner tumbler also helps. [1]", marks: 3, kw: [["gain", "gains heat", "gained heat"], ["expand"], ["contract"]], model: "(a) The outer tumbler gains heat from the hot water and expands, so it becomes slightly bigger around the inner tumbler. (b) The inner tumbler loses heat to the cold water and contracts, so it becomes slightly smaller and loosens.", x: 1 },
    { q: "A book is not a light source, yet Ahmad can see it on the table in a lit room. Explain how he sees the book. [2]", marks: 2, kw: [["reflect"], ["eye"]], model: "Light from the lamp falls on the book, and the book reflects the light. The reflected light travels in straight lines and enters Ahmad’s eyes, so he sees the book." }
  ],
  doc: [
    { q: "A cold can drink taken from the fridge becomes warmer after it is left on the table. Explain why. [2]", marks: 2, answers: ["The coldness of the drink flows out into the air.", "The drink gains heat from the warmer surrounding air, so its temperature rises.", "The can is made of metal, which is a good conductor."], best: 1, why: "Answer 2 gives the direction of heat flow (from the warmer air into the drink) and the effect (temperature rises). Answer 1 wrongly makes ‘coldness’ flow, and answer 3 names a property but never says heat is gained by the drink." },
    { q: "Why must food be digested before the body can use it? [2]", marks: 2, answers: ["So that food can go to the stomach.", "So that we get energy.", "Food must be broken down into simpler substances so that it can be absorbed into the bloodstream."], best: 2, why: "Answer 3 has both ideas: broken down into simpler substances, and absorbed into the bloodstream. Answer 1 is wrong, and answer 2 is too vague: it does not explain why digestion is needed." },
    { q: "Explain how we see a tree on a sunny day. [2]", marks: 2, answers: ["Light from the Sun is reflected by the tree into our eyes.", "Our eyes send out light to the tree.", "The tree gives out light, so we can see it."], best: 0, why: "Answer 1 says the tree reflects light and that the light enters our eyes. Answer 2 has the direction wrong, and answer 3 wrongly treats the tree as a light source." }
  ]
};
