window.LB = window.LB || {};
LB["p4-matter"] = {
  notes: [
    { h: "What is matter?", t: "Matter is anything that has mass and occupies space. Solids, liquids and gases are all matter, even when we cannot see them, like the air in an ‘empty’ bottle. To decide if something is matter, ask two questions: does it have mass, and does it take up space?", kw: ["has mass and occupies space", "takes up space"] },
    { h: "Mass", t: "Mass is the amount of matter in an object. It is measured in grams (g) or kilograms (kg), and 1 kg = 1000 g. We measure mass with an electronic balance.", kw: ["mass", "electronic balance", "grams (g)", "kilograms (kg)"] },
    { h: "Volume", t: "Volume is the amount of space that matter occupies. It is measured in cubic centimetres (cm³), millilitres (ml) or litres (l). 1 ml = 1 cm³ and 1 l = 1000 ml.", kw: ["volume", "amount of space", "cm³", "ml"] },
    { h: "Three states of matter", t: "Matter exists in three states: solid, liquid and gas. The states differ in whether they have a definite shape, whether they have a definite volume and whether they can be compressed. Learn the three properties as a table and you can identify any state from its properties.", kw: ["solid", "liquid", "gas", "definite shape", "definite volume", "compressed"] },
    { h: "Solids", t: "A solid has a definite shape and a definite volume. It cannot be compressed. A stone, a coin or an eraser keeps its shape and volume wherever you put it.", kw: ["definite shape", "definite volume", "cannot be compressed"] },
    { h: "Liquids", t: "A liquid has no definite shape but has a definite volume. It takes the shape of the part of the container it fills, but its volume stays the same when it is poured into another container. A liquid cannot be compressed.", kw: ["no definite shape", "definite volume", "takes the shape of its container", "cannot be compressed"] },
    { h: "Gases", t: "A gas has no definite shape and no definite volume. It takes the shape and volume of its container, spreading out to fill the whole space available. A gas can be compressed.", kw: ["no definite shape", "no definite volume", "takes the shape and volume of its container", "can be compressed"] },
    { h: "Compressing matter", t: "To compress something means to squeeze it into a smaller volume. Gases can be compressed; solids and liquids cannot. That is why the plunger of a sealed syringe of air can be pushed in, but the plunger of a sealed syringe of water cannot.", kw: ["compress", "smaller volume", "gases can be compressed"] },
    { h: "Air has mass", t: "Air is a gas, so it has mass. A football weighs more on an electronic balance after more air is pumped into it, because the extra air adds mass. Air in a rigid container can be compressed, so more air (more mass) can be squeezed into the same space.", kw: ["air has mass", "mass increases"] },
    { h: "Air occupies space", t: "Air occupies space, so an ‘empty’ cup or bottle is really full of air. A cup pushed straight down into water keeps a tissue at its base dry, because the trapped air occupies space and stops water from entering. A balloon cannot be blown up inside a sealed bottle unless there is a hole to let the air in the bottle escape.", kw: ["air occupies space", "trapped air", "escape"] },
    { h: "Measuring volume", t: "The volume of a liquid is measured with a measuring cylinder; read it with your eye level with the bottom of the curved water surface. The volume of an irregular solid is found by displacement: volume of solid = water level with the solid − water level without it. The solid must be completely under the water and the water must not overflow.", kw: ["measuring cylinder", "displacement", "completely under the water", "final reading minus initial reading"] },
    { h: "Things that are not matter", t: "Light, heat, sound, shadows, thoughts, feelings and dreams are not matter. They have no mass and do not occupy space. Being able to see, feel or hear something does not make it matter.", kw: ["not matter", "no mass", "do not occupy space"] }
  ],
  traps: [
    "‘Air has no mass because we cannot see it’ → air has mass; a ball gains mass when more air is pumped in.",
    "‘An empty bottle has nothing in it’ → it is full of air, and the air occupies space.",
    "‘Sand takes the shape of its container, so it is a liquid’ → each grain has a definite shape and volume, so sand is a solid.",
    "‘A sponge can be squeezed, so solids can be compressed’ → the air in the holes is pushed out; the solid itself is not compressed.",
    "‘A liquid has no definite volume because it changes shape’ → a liquid changes shape but keeps its volume.",
    "‘Light and heat are matter because we can see or feel them’ → they have no mass and do not occupy space.",
    "Volume of a stone by displacement is the RISE in water level (final − initial), not the final reading.",
    "Pumping more air into a rigid tank increases the mass of air, but the volume of air stays equal to the volume of the tank."
  ],
  lessons: [
    {
      h: "Identifying a state from its properties",
      concept: "Every state of matter has a fixed set of three properties. A solid has a definite shape and a definite volume and cannot be compressed. A liquid has no definite shape but has a definite volume and cannot be compressed. A gas has no definite shape and no definite volume and can be compressed. Match the evidence in the question to these properties, and always state the property as your reason.",
      example: {
        q: "Substance K was poured from a 100 ml beaker into a 250 ml flask. It took the shape of the bottom of the flask and its volume stayed at 80 ml. It could not be compressed. State the state of K and explain your answer.",
        marks: 2,
        think: [
          "Step 1: It took the shape of the flask, so K has no definite shape. It is not a solid.",
          "Step 2: Its volume stayed at 80 ml in a bigger container, so K has a definite volume. A gas would have spread out to fill the whole flask, so it is not a gas.",
          "Step 3: No definite shape + definite volume + cannot be compressed = liquid. Give the two properties as the reason."
        ],
        answer: "K is a liquid. It has no definite shape because it took the shape of the flask, but it has a definite volume because its volume stayed at 80 ml in the bigger flask."
      },
      tip: "Name the property, not the behaviour alone: ‘definite volume’ scores; ‘it can flow’ does not.",
      try: {
        q: "Substance M fills the whole of any container it is put in, and it can be squeezed into a smaller space. What is M?",
        o: ["A solid, because it has a definite volume", "A liquid, because it takes the shape of its container", "A liquid, because it cannot be compressed", "A gas, because it has no definite volume and can be compressed"],
        a: 3,
        why: "Filling the whole container means M has no definite volume, and being squeezed into a smaller space means it can be compressed. Only a gas has both properties; a liquid takes the shape of the container but keeps its own volume."
      }
    },
    {
      h: "Explaining ‘air occupies space’ experiments",
      concept: "In the inverted-cup, balloon-in-bottle and funnel-in-flask experiments, the key idea is the same: the container is already full of air, and air occupies space. If the air is trapped and cannot escape, water (or a balloon) cannot take its place. Once the air has a way out (a hole, a straw, tilting the cup), it escapes and water or the balloon can fill the space.",
      example: {
        q: "A tissue was stuffed into the base of a dry cup. The cup was turned upside down and pushed straight down into a basin of water. Afterwards, the tissue was dry. Explain why.",
        fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Cup upside down", "Tissue at the base", "Pushed straight down", "Tissue stays dry"] } ] },
        marks: 2,
        think: [
          "Step 1: The ‘empty’ cup is actually full of air.",
          "Step 2: Pushed straight down, the air is trapped and cannot escape.",
          "Step 3: Air occupies space, so it stops the water from entering the cup to reach the tissue. Say BOTH ideas: air occupies space AND water cannot enter."
        ],
        answer: "The cup was filled with air, which was trapped when the cup was pushed straight down. Air occupies space, so the water could not enter the cup to wet the tissue."
      },
      tip: "‘Air has mass’ is true but does not explain these experiments; the keyword is ‘air occupies space’.",
      try: {
        q: "A balloon is placed in the mouth of a bottle with no hole and cannot be blown up much. Which change will let the balloon be blown up the most?",
        o: ["Using a bigger, stretchier balloon", "Making a hole in the side of the bottle", "Blowing much harder into the balloon", "Using a bottle made of glass instead"],
        a: 1,
        why: "The bottle is full of air that occupies space and cannot escape. A hole lets the air in the bottle escape, making space for the balloon to expand. The other changes still leave the air trapped."
      }
    },
    {
      h: "Compressing air and water in syringes",
      concept: "Gases can be compressed but solids and liquids cannot. In a syringe with its nozzle sealed, a plunger over air can be pushed in some way, because air is squeezed into a smaller volume; it cannot be pushed all the way in, because the air still occupies space. A plunger over water cannot be pushed in at all. When released, the compressed air pushes the plunger back out.",
      example: {
        q: "Syringe P contains 50 cm³ of air and syringe Q contains 50 cm³ of water. Both nozzles are sealed. (a) In which syringe can the plunger be pushed in? (b) Explain why the plunger of that syringe cannot be pushed all the way to 0 cm³.",
        fig: { type: "setups", items: [ { label: "P", icon: "jar", lines: ["50 cm³ of air", "Nozzle sealed"] }, { label: "Q", icon: "jar", lines: ["50 cm³ of water", "Nozzle sealed"] } ] },
        marks: 2,
        think: [
          "Step 1: Air is a gas; gases can be compressed. Water is a liquid; liquids cannot be compressed.",
          "Step 2: So only P’s plunger can be pushed in.",
          "Step 3: The air is squeezed into a smaller volume but it is still there: air occupies space, so the plunger stops before 0."
        ],
        answer: "(a) Syringe P. (b) The air in P can be compressed into a smaller volume, but air still occupies space, so the plunger cannot be pushed all the way to 0 cm³."
      },
      tip: "Pushing the plunger in changes the VOLUME of the air, not its mass: no air leaves a sealed syringe.",
      try: {
        q: "A sealed syringe contains 60 cm³ of air. The plunger is pushed in until the reading is 35 cm³ and held there. Which is correct about the air inside?",
        o: ["Its mass decreased because some air was squashed away.", "Its volume stayed at 60 cm³ because gases have a definite volume.", "Its mass stayed the same but its volume decreased.", "Its mass and volume both decreased."],
        a: 2,
        why: "The nozzle is sealed, so no air leaves and the mass stays the same. The air was compressed into a smaller space, so its volume decreased from 60 cm³ to 35 cm³."
      }
    },
    {
      h: "Finding volume by displacement",
      concept: "An irregular solid that sinks can be measured by displacement. Record the water level, put the solid in so it is completely under water, record the new level, and subtract: volume of solid = final reading − initial reading. Since 1 ml = 1 cm³, a rise of 18 ml means the solid has a volume of 18 cm³. For several identical objects, divide the rise by the number of objects.",
      example: {
        q: "A measuring cylinder contained 45 ml of water. Four identical marbles were dropped in and all sank. The water level rose to 65 ml. Find the volume of one marble. Show your working.",
        marks: 2,
        think: [
          "Step 1: Rise in water level = 65 ml − 45 ml = 20 ml. This is the volume of all four marbles.",
          "Step 2: One marble = 20 ÷ 4 = 5 cm³.",
          "Step 3: Check the unit: volume in cm³ (or ml), never in g."
        ],
        answer: "Rise in water level = 65 ml − 45 ml = 20 ml, so the four marbles have a volume of 20 cm³. One marble = 20 cm³ ÷ 4 = 5 cm³."
      },
      tip: "Write ‘final − initial’ every time, and give the answer in cm³, not g.",
      try: {
        q: "A cylinder had 30 ml of water. A stone was put in and the level rose to 52 ml, but the top of the stone was still above the water. What can you conclude?",
        o: ["The stone’s volume is exactly 22 cm³.", "The stone’s volume is 52 cm³.", "The stone’s volume is more than 22 cm³.", "The stone’s volume is less than 22 cm³."],
        a: 2,
        why: "Only the part of the stone under the water pushed the water up by 22 ml. The part above the water also occupies space, so the whole stone is more than 22 cm³. More water was needed to cover it completely."
      }
    },
    {
      h: "Mass and volume of a gas in a container",
      concept: "A gas takes the shape and volume of its container, so the volume of air in a closed container is the space not taken up by anything else. Pumping more air into a rigid container increases the mass of air inside, but the volume of air stays the same, because the extra air is compressed into the same space. In a container partly filled with water, volume of air = volume of container − volume of water.",
      example: {
        q: "A rigid 2 l bottle contains 500 ml of water and some air. It is sealed with a valve and more air is pumped in. State the volume of air in the bottle before and after pumping, and what happens to the mass of the bottle and its contents.",
        fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Rigid 2 l bottle", "500 ml of water", "Rest is air"] }, { label: "B", icon: "jar", lines: ["Same bottle", "More air pumped in", "Water still 500 ml"] } ] },
        marks: 3,
        think: [
          "Step 1: Air fills the space not taken up by water: 2000 ml − 500 ml = 1500 ml.",
          "Step 2: After pumping, the water still takes up 500 ml and the bottle is rigid, so the air still has only 1500 ml of space. Its volume is still 1500 ml; it has been compressed.",
          "Step 3: More air was added, and air has mass, so the total mass increases."
        ],
        answer: "Before pumping, the volume of air is 2000 ml − 500 ml = 1500 ml. After pumping, it is still 1500 ml, because the air takes the volume of the space left in the rigid bottle and the extra air is compressed. The mass increases, because more air was added and air has mass."
      },
      tip: "More gas in the same container = more MASS, same VOLUME.",
      try: {
        q: "A rigid tank of volume 12 l is full of air. More air is pumped in. What is the volume of air in the tank now?",
        o: ["12 l", "More than 12 l", "Less than 12 l", "It cannot be told because gases have no volume"],
        a: 0,
        why: "A gas takes the volume of its container. The tank is rigid and still 12 l, so the air occupies 12 l; the extra air has been compressed into the same space, increasing only the mass."
      }
    }
  ],
  mcq: [
    { q: "Which one of the following is matter?", o: ["Light", "A shadow", "Air", "Sound"], a: 2, lvl: 1, why: "Air has mass and occupies space, so it is matter. Light, shadows and sound have no mass and do not occupy space." },
    { q: "Matter is anything that…", o: ["has mass and occupies space", "can be seen and touched", "has a definite shape", "can be felt or heard"], a: 0, lvl: 1, why: "This is the definition of matter. Air cannot be seen but is matter; liquids and gases have no definite shape but are matter." },
    { q: "Which instrument is used to measure the mass of a stone?", o: ["Measuring cylinder", "Electronic balance", "Ruler", "Thermometer"], a: 1, lvl: 1, why: "An electronic balance measures mass in g or kg. A measuring cylinder measures volume." },
    { q: "Which state of matter has a definite volume but no definite shape?", o: ["Solid", "Gas", "Both solid and gas", "Liquid"], a: 3, lvl: 1, why: "A liquid takes the shape of its container but keeps its volume. A solid has a definite shape; a gas has no definite volume." },
    { q: "Which one of these is a unit of volume?", o: ["ml", "g", "kg", "cm"], a: 0, lvl: 1, why: "Millilitres (ml) measure volume. g and kg are units of mass, and cm is a unit of length." },
    { q: "The diagram shows two syringes with their nozzles sealed. In which syringe(s) can the plunger be pushed in?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Syringe of air", "Nozzle sealed"] }, { label: "B", icon: "jar", lines: ["Syringe of water", "Nozzle sealed"] } ] }, o: ["B only", "Neither A nor B", "A only", "Both A and B"], a: 2, lvl: 1, why: "Air is a gas and can be compressed, so plunger A can be pushed in. Water is a liquid and cannot be compressed, so plunger B cannot move." },
    { q: "1 kg is the same as…", o: ["10 g", "100 g", "10 000 g", "1000 g"], a: 3, lvl: 1, why: "1 kilogram = 1000 grams." },
    { q: "Which one of the following is NOT matter?", o: ["Water vapour", "Heat", "Sand", "Orange juice"], a: 1, lvl: 1, why: "Heat is a form of energy: it has no mass and does not occupy space. Water vapour is a gas, sand is a solid and juice is a liquid, so all three are matter." },

    { q: "The diagram shows a measuring cylinder before and after a stone was put in. The stone sank completely. What is the volume of the stone?", fig: { type: "setups", items: [ { label: "1", icon: "beaker", lines: ["Water only", "Reading: 40 ml"] }, { label: "2", icon: "beaker", lines: ["Water + stone", "Reading: 65 ml"] } ] }, o: ["25 cm³", "40 cm³", "65 cm³", "105 cm³"], a: 0, lvl: 2, why: "Volume of stone = 65 ml − 40 ml = 25 ml = 25 cm³. 65 cm³ is the total of water and stone, not the stone alone." },
    { q: "Sheila measured the mass of a football as she pumped air into it. Study the graph. What does it show?", fig: { type: "bar", xl: "Number of pumps", yl: "Mass of football (g)", bars: [["0 pumps", 400], ["10 pumps", 406], ["20 pumps", 412]] }, o: ["Air has mass.", "Air takes the shape of the ball.", "Air has no definite volume.", "The ball has a definite shape."], a: 0, lvl: 2, why: "The mass of the ball increased as more air was pumped in, so the air added mass. The graph shows mass, not shape or volume." },
    { q: "A tissue was stuffed into the base of a cup. The cup was turned upside down and pushed straight down into water, as shown. The tissue stayed dry. Why?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Cup upside down", "Tissue at the base", "Pushed straight down"] } ] }, o: ["The tissue paper is waterproof, so it cannot absorb water.", "Air has mass, so it is heavier than the water below it.", "Water has no definite shape, so it cannot flow into the cup.", "The air in the cup occupies space, so water cannot enter."], a: 3, lvl: 2, why: "The trapped air occupies space and stops the water from entering. Air does have mass, but it is not heavier than water, and its mass does not explain why water stays out." },
    { q: "The diagram shows a 1 l bottle with 400 ml of water in it. What is the volume of air in the bottle?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["1 l bottle", "400 ml of water", "Rest is air"] } ] }, o: ["400 ml", "1000 ml", "600 ml", "1400 ml"], a: 2, lvl: 2, why: "Air fills the space not taken up by the water: 1000 ml − 400 ml = 600 ml." },
    { q: "Which statement is true of solids, liquids AND gases?", o: ["They have a definite volume.", "They can be compressed.", "They take the shape of their container.", "They have mass and occupy space."], a: 3, lvl: 2, why: "All matter has mass and occupies space. Gases have no definite volume, only gases can be compressed, and solids keep their own shape." },
    { q: "Study the classification chart. Which correctly shows P, Q and R?", fig: { type: "flow", root: "Matter", node: { q: "Has a definite shape?", yes: "P", no: { q: "Has a definite volume?", yes: "Q", no: "R" } } }, o: ["P: pencil, Q: milk, R: oxygen", "P: milk, Q: pencil, R: oxygen", "P: oxygen, Q: milk, R: pencil", "P: pencil, Q: oxygen, R: milk"], a: 0, lvl: 2, why: "Only a solid (pencil) has a definite shape. Of the rest, a liquid (milk) has a definite volume and a gas (oxygen) does not." },
    { q: "Sand can be poured and takes the shape of its container. Which is the best classification of sand?", o: ["A liquid, because it can be poured from one cup to another", "A gas, because it takes the shape of any container it is in", "A solid, because each grain has a definite shape and volume", "A liquid, because it has no definite shape of its own"], a: 2, lvl: 2, why: "Sand is made of many tiny solid grains. Each grain keeps its own shape and volume; the pile only looks like it flows." },
    { q: "The diagram shows two readings on an electronic balance. What is the mass of the water?", fig: { type: "setups", items: [ { label: "1", icon: "beaker", lines: ["Empty beaker", "120 g"] }, { label: "2", icon: "beaker", lines: ["Beaker + water", "370 g"] } ] }, o: ["120 g", "250 g", "370 g", "490 g"], a: 1, lvl: 2, why: "Mass of water = 370 g − 120 g = 250 g. 370 g includes the beaker." },
    { q: "The plunger of a syringe of air with a sealed nozzle is pushed in and then let go. What happens to the plunger?", o: ["It stays where it is.", "It moves further in.", "It moves back out.", "It falls off the syringe."], a: 2, lvl: 2, why: "The air was compressed into a smaller space. When the plunger is released, the compressed air pushes it back out." },
    { q: "A balloon is fitted into the mouth of each bottle, as shown, and Tom tries to blow up each balloon. Which balloon can be blown up more, and why?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Bottle with no hole", "Balloon in mouth"] }, { label: "B", icon: "jar", lines: ["Bottle with a hole", "Balloon in mouth"] } ] }, o: ["A, because the air in bottle A has no mass and can be pushed aside", "B, because the air in B can escape through the hole to make space", "Both equally, because the bottles are the same size and shape", "Neither, because a balloon can never be blown up inside any bottle"], a: 1, lvl: 2, why: "Both bottles are full of air that occupies space. Only in B can the air escape through the hole, so the balloon can expand into the space." },
    { q: "How should Ali read the water level in a measuring cylinder?", o: ["Look down from above at the top of the curved surface", "With his eye level with the bottom of the curved water surface", "With his eye below the water surface, looking up", "From any angle, as long as the cylinder is on a flat table"], a: 1, lvl: 2, why: "Reading at eye level with the bottom of the curved surface gives the correct reading. Looking from above or below gives a wrong reading." },
    { q: "Which states of matter take the shape of their container?", o: ["Solids only", "Liquids only", "Liquids and gases", "Solids, liquids and gases"], a: 2, lvl: 2, why: "Liquids and gases have no definite shape, so they take the shape of their container. Solids keep their own shape." },
    { q: "An object has a volume of 30 cm³. This is the same as…", o: ["3 ml", "300 ml", "30 l", "30 ml"], a: 3, lvl: 2, why: "1 cm³ = 1 ml, so 30 cm³ = 30 ml." },
    { q: "Study the Venn diagram. Which correctly identifies W, X and Y?", fig: { type: "venn", a: "Definite shape", b: "Definite volume", onlyA: [], both: ["W"], onlyB: ["X"], neither: ["Y"] }, o: ["W: juice, X: rubber band, Y: air", "W: syrup, X: eraser, Y: helium", "W: air, X: syrup, Y: eraser", "W: eraser, X: syrup, Y: helium"], a: 3, lvl: 2, why: "W has both properties, so it is a solid (eraser). X has only a definite volume, so it is a liquid (syrup). Y has neither, so it is a gas (helium)." },

    { q: "Water was poured into the funnel as shown, but only a little entered the flask. Which change will allow the water to flow into the flask easily?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Funnel in flask", "Sealed with plasticine", "Water stays in funnel"] } ] }, o: ["Make a small hole in the plasticine.", "Pour the water in more quickly.", "Use a funnel made of glass.", "Use coloured water."], a: 0, lvl: 3, why: "The flask is full of trapped air that occupies space. A hole lets the air escape, so water can flow in to take up the space. The other changes leave the air trapped." },
    { q: "Three syringes with sealed nozzles were set up as shown. The same force was used to push each plunger. Which plunger moved in the furthest?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["40 cm³ of air"] }, { label: "B", icon: "jar", lines: ["40 cm³ of water"] }, { label: "C", icon: "jar", lines: ["20 cm³ of air", "20 cm³ of water"] } ] }, o: ["A", "B", "C", "A and C moved in by the same distance"], a: 0, lvl: 3, why: "Only air can be compressed. B has no air, so it does not move. A has twice as much air as C, so it can be squeezed in more; the water in C cannot be compressed." },
    { q: "Jun filled a displacement can with water and lowered a stone in. The water that flowed out of the spout was less than the actual volume of the stone. What is the most likely reason?", o: ["The stone was too heavy, so it pushed less water out.", "The can was not filled up to the spout before the stone went in.", "The stone sank to the bottom of the can too quickly.", "Water has a definite volume, so it cannot be squashed."], a: 1, lvl: 3, why: "If the water was below the spout, part of the water pushed up by the stone only filled the can up to the spout and did not flow out. Sinking to the bottom is needed for the method to work." },
    { q: "Identical marbles were added to a measuring cylinder of water. Study the graph. What is the volume of ONE marble?", fig: { type: "line", xl: "Number of marbles", yl: "Water level (ml)", pts: [["0", 50], ["2", 56], ["4", 62], ["6", 68]] }, o: ["6 cm³", "3 cm³", "12 cm³", "50 cm³"], a: 1, lvl: 3, why: "Every 2 marbles raise the level by 6 ml, so one marble has a volume of 6 ÷ 2 = 3 cm³. 6 cm³ is the volume of two marbles." },
    { q: "More air is pumped into a rigid steel tank that is already full of air. What happens to the air in the tank?", o: ["Both its mass and volume increase.", "Its mass stays the same; its volume increases.", "Its mass increases; its volume stays the same.", "Both its mass and volume stay the same."], a: 2, lvl: 3, why: "More air means more mass. The tank is rigid, so the air still takes the volume of the tank; the extra air has been compressed into the same space." },
    { q: "A dry kitchen sponge becomes much smaller when squeezed. Which is the best explanation?", o: ["The solid material of the sponge is compressed.", "The sponge loses mass when it is squeezed.", "The sponge becomes a liquid when squeezed.", "The air in the holes of the sponge is pushed out."], a: 3, lvl: 3, why: "A sponge has many holes filled with air. Squeezing pushes the air out of the holes; the solid material itself is not compressed." },
    { q: "Which statements about air are correct?\nA: Air has mass.\nB: Air occupies space.\nC: Air has a definite volume.\nD: Air can be compressed.", o: ["A and B only", "B and D only", "A, B and D only", "A, B, C and D"], a: 2, lvl: 3, why: "Air is a gas: it has mass, occupies space and can be compressed. A gas has no definite volume, so C is wrong." },
    { q: "The table shows the properties of substances X, Y and Z. Which correctly identifies them?", tbl: [["Substance", "Definite shape", "Definite volume", "Can be compressed"], ["X", "No", "Yes", "No"], ["Y", "No", "No", "Yes"], ["Z", "Yes", "Yes", "No"]], o: ["X: solid, Y: gas, Z: liquid", "X: gas, Y: liquid, Z: solid", "X: liquid, Y: gas, Z: solid", "X: liquid, Y: solid, Z: gas"], a: 2, lvl: 3, why: "X has a definite volume only (liquid). Y has neither definite shape nor volume and can be compressed (gas). Z has both and cannot be compressed (solid)." },
    { q: "An open 250 ml bottle had 100 ml of water in it. Another 50 ml of water was poured in. What is the volume of air in the bottle now?", o: ["50 ml", "100 ml", "150 ml", "250 ml"], a: 1, lvl: 3, why: "The water now takes up 150 ml, so air fills the remaining 250 − 150 = 100 ml. Some air left the open bottle as the water came in." },
    { q: "Two blown-up balloons were hung at the ends of a stick so that it balanced. The left balloon was then popped, as described in the diagram. What conclusion can be made?", fig: { type: "setups", items: [ { label: "1", icon: "box", lines: ["Before:", "2 blown-up balloons", "Stick is balanced"] }, { label: "2", icon: "box", lines: ["After:", "Left balloon popped", "Right side goes down"] } ] }, o: ["Air occupies space.", "Air can be compressed.", "Rubber has no mass.", "Air has mass."], a: 3, lvl: 3, why: "When the air left the popped balloon, that side became lighter and the side with the full balloon went down. This shows air has mass. The rubber was still there, so it is the air that was lost." },
    { q: "Which group contains ONLY matter?", o: ["Air, water, shadow", "Heat, stone, oil", "Light, sound, rain", "Sand, oxygen, milk"], a: 3, lvl: 3, why: "Sand (solid), milk (liquid) and oxygen (gas) all have mass and occupy space. Each other group contains a non-matter: shadow, heat, or light and sound." },
    { q: "Two cups with tissue at the base were pushed straight down into water. The tissue in cup B became wet. Which explains why?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Cup with no hole", "Tissue stays dry"] }, { label: "B", icon: "beaker", lines: ["Small hole in base", "Tissue gets wet"] } ] }, o: ["Air escaped through the hole, so water could enter the cup.", "Water entered through the hole at the top of the cup.", "The tissue absorbed the air in the cup, leaving space for water.", "Air has no mass, so it cannot stop water from entering."], a: 0, lvl: 3, why: "The hole let the trapped air escape, so water entered the cup from below and reached the tissue. The water came in from the open end at the bottom of the cup, not through the hole." },

    { q: "Mei wanted to find the volume of a cork, which floats. She used a metal sinker and recorded three readings, as shown. What is the volume of the cork?", fig: { type: "setups", items: [ { label: "1", icon: "beaker", lines: ["Water only", "50 ml"] }, { label: "2", icon: "beaker", lines: ["Water + sinker", "58 ml"] }, { label: "3", icon: "beaker", lines: ["Sinker tied to cork", "Both under water", "73 ml"] } ] }, o: ["8 cm³", "15 cm³", "23 cm³", "73 cm³"], a: 1, lvl: 4, why: "The sinker alone is 58 − 50 = 8 cm³. Sinker + cork is 73 − 50 = 23 cm³, so the cork is 23 − 8 = 15 cm³ (or 73 − 58). The sinker holds the cork fully under water." },
    { q: "A sealed syringe contained 60 cm³ of air. The plunger was pushed in until the reading was 40 cm³. No air leaked out. Which is correct about the air in the syringe?", o: ["Its mass stayed the same; its volume decreased.", "Its mass decreased; its volume decreased.", "Its mass stayed the same; its volume stayed the same.", "Its mass increased; its volume decreased."], a: 0, lvl: 4, why: "No air left, so the amount of air and its mass did not change. The air was compressed into a smaller space, so its volume fell from 60 to 40 cm³." },
    { q: "A rigid 5 l container holds 2 l of water and some air. It is sealed and more air is pumped in. The water level does not change. What is the volume of air and what happened to its mass?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Rigid 5 l container", "2 l of water", "Air pumped in"] } ] }, o: ["3 l; mass of air increased", "5 l; mass of air stayed the same", "3 l; mass of air stayed the same", "5 l; mass of air increased"], a: 0, lvl: 4, why: "The air can only fill the space not taken by the water: 5 − 2 = 3 l, and it stays 3 l because the container is rigid. More air was added, so its mass increased." },
    { q: "Raj put a tall stone into a measuring cylinder with 30 ml of water. The level rose to 50 ml, but the top of the stone stuck out of the water. Which statements are correct?\nA: The volume of the stone is 20 cm³.\nB: The volume of the stone is more than 20 cm³.\nC: To find the volume, he should start with enough water to cover the stone completely.", o: ["A only", "A and C only", "B and C only", "B only"], a: 2, lvl: 4, why: "Only the part of the stone under the water pushed up 20 ml, so the whole stone is more than 20 cm³ (B) and A is wrong. Starting with enough water to cover it completely would give the true volume (C)." },
    { q: "A bicycle tyre is already fully blown up and does not get any bigger when more air is pumped in. Which statements are correct after more air is pumped in?\nA: The mass of the air in the tyre increases.\nB: The volume of the air in the tyre stays the same.\nC: The air in the tyre has been compressed.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, lvl: 4, why: "More air adds mass (A). The tyre does not get bigger, so the air still fills the same space (B). More air squeezed into the same space means it has been compressed (C)." },
    { q: "Water collects in the funnel and does not flow into the sealed flask shown. Which changes will let the water flow into the flask?\nA: Make a hole in the plasticine.\nB: Push a straw through the plasticine so one end is inside the flask and the other is outside.\nC: Pour the water in faster.\nD: Use a funnel with a longer stem.", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Funnel in flask", "Plasticine seal", "Water stays in funnel"] } ] }, o: ["A only", "A and B only", "A, B and C only", "C and D only"], a: 1, lvl: 4, why: "The trapped air occupies space. A hole (A) or a straw (B) gives the air a way to escape, so water can take its place. Pouring faster or a longer stem still leaves the air trapped." }
  ],
  tf: [
    { s: "Air has mass.", a: true, why: "A football gains mass when more air is pumped into it." },
    { s: "Air has no mass because we cannot see it.", a: false, why: "Being invisible does not mean having no mass; air is matter and has mass." },
    { s: "A liquid has a definite volume.", a: true, why: "A liquid keeps its volume even when poured into a different container." },
    { s: "A gas has a definite volume.", a: false, why: "A gas has no definite volume; it takes the volume of its container." },
    { s: "Solids can be compressed easily.", a: false, why: "Solids cannot be compressed; they have a definite volume." },
    { s: "Gases can be compressed.", a: true, why: "A gas can be squeezed into a smaller volume, e.g. air in a sealed syringe." },
    { s: "Light is matter because we can see it.", a: false, why: "Light has no mass and does not occupy space, so it is not matter." },
    { s: "Sound is not matter.", a: true, why: "Sound has no mass and does not occupy space." },
    { s: "A shadow occupies space.", a: false, why: "A shadow is not matter; it has no mass and does not occupy space." },
    { s: "Sand takes the shape of its container, so sand is a liquid.", a: false, why: "Sand is a solid: each grain has a definite shape and a definite volume." },
    { s: "1 ml is the same as 1 cm³.", a: true, why: "1 millilitre = 1 cubic centimetre." },
    { s: "A gas takes the shape and volume of its container.", a: true, why: "A gas spreads out to fill the whole space it is in." },
    { s: "A sponge becomes smaller when squeezed because the solid is compressed.", a: false, why: "The air in the holes of the sponge is pushed out; the solid itself is not compressed." },
    { s: "An electronic balance is used to measure volume.", a: false, why: "An electronic balance measures mass. Volume is measured with a measuring cylinder." },
    { s: "The volume of an irregular stone can be found by displacement of water.", a: true, why: "Volume of stone = water level with the stone − water level without it." },
    { s: "A liquid takes the shape of its container.", a: true, why: "A liquid has no definite shape, so it takes the shape of the part of the container it fills." },
    { s: "A cup with nothing visible in it is actually filled with air.", a: true, why: "Air occupies the space in an ‘empty’ cup." },
    { s: "When more air is pumped into a football, the mass of the ball stays the same.", a: false, why: "Air has mass, so the ball’s mass increases." },
    { s: "Heat is matter because it can be felt.", a: false, why: "Heat has no mass and does not occupy space." },
    { s: "The water in a sealed syringe can be pushed into a smaller volume.", a: false, why: "Liquids cannot be compressed, so the plunger will not move in." }
  ],
  sort: [
    { title: "Sort these into matter and not matter.", groups: ["Matter", "Not matter"], items: [["air", 0], ["sound", 1], ["water vapour", 0], ["shadow", 1], ["sand", 0], ["light", 1], ["milk", 0], ["heat", 1], ["thoughts", 1], ["oxygen", 0]] },
    { title: "Sort these into solids, liquids and gases.", groups: ["Solid", "Liquid", "Gas"], items: [["eraser", 0], ["cooking oil", 1], ["oxygen", 2], ["sand", 0], ["honey", 1], ["carbon dioxide", 2], ["coin", 0], ["soya sauce", 1], ["water vapour", 2], ["sugar", 0]] },
    { title: "Which state does each description fit? (Each fits only one state.)", groups: ["Solid", "Liquid", "Gas"], items: [["keeps its shape in any container", 0], ["takes the shape of the container but keeps its volume", 1], ["fills the whole of any container", 2], ["can be squeezed into a smaller volume", 2], ["has a definite shape and a definite volume", 0], ["can be poured, and 200 ml stays 200 ml in any container", 1], ["no definite shape and no definite volume", 2], ["cannot be compressed, has a fixed shape", 0], ["no definite shape but has a definite volume", 1]] }
  ],
  oe: [
    { q: "Explain why air is considered matter.", marks: 2, kw: [["mass"], ["occupies space", "occupy space", "takes up space", "take up space"]], model: "Air is matter because it has mass and occupies space." },
    { q: "A tissue was stuffed into the base of a cup. The cup was turned upside down and pushed straight down into a basin of water, as shown.\n(a) What happened to the tissue? (1 mark)\n(b) Explain your answer to (a). (2 marks)\n(c) The cup was then tilted while still under water. What would you see coming out of the cup? (1 mark)", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Cup upside down", "Tissue at the base", "Pushed straight down"] } ] }, marks: 4, kw: [["dry", "not wet"], ["occupies space", "occupy space", "takes up space", "take up space"], ["stop", "prevent", "could not enter", "cannot enter", "unable to enter", "not able to enter"], ["bubble", "escape"]], model: "(a) The tissue stayed dry. (b) The cup was full of air, and air occupies space. The air trapped in the cup stopped the water from entering the cup to reach the tissue. (c) Air bubbles would come out, as the air escapes and water enters the cup." },
    { q: "Two syringes with sealed nozzles were set up as shown. Ben pushed each plunger.\n(a) The plunger of syringe A could be pushed in. What property of air does this show? (1 mark)\n(b) Explain why the plunger of syringe B could not be pushed in. (1 mark)\n(c) Ben released the plunger of syringe A. What happened to it? (1 mark)", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["50 cm³ of air", "Nozzle sealed"] }, { label: "B", icon: "jar", lines: ["50 cm³ of water", "Nozzle sealed"] } ] }, marks: 3, kw: [["compress"], ["cannot be compress", "can not be compress", "can't be compress", "cannot be squeezed", "not be compress"], ["back out", "moves back", "moved back", "pushed back", "returns", "returned", "moves out", "moved out"]], model: "(a) Air can be compressed. (b) Water is a liquid and cannot be compressed. (c) The plunger moved back out, because the compressed air pushed it back." },
    { q: "A balloon was fitted into the mouth of each bottle as shown. Lina could hardly blow up the balloon in bottle P, but could blow up the balloon in bottle Q easily.\n(a) Explain why the balloon in bottle P could hardly be blown up. (2 marks)\n(b) Explain why the balloon in bottle Q could be blown up easily. (1 mark)", fig: { type: "setups", items: [ { label: "P", icon: "jar", lines: ["Bottle with no hole", "Balloon in mouth"] }, { label: "Q", icon: "jar", lines: ["Hole in the side", "Balloon in mouth"] } ] }, marks: 3, kw: [["occupies space", "occupy space", "takes up space", "take up space"], ["cannot escape", "could not escape", "can't escape", "couldn't escape", "trapped", "no way out"], ["hole"]], model: "(a) Bottle P is full of air, which occupies space. The air is trapped and cannot escape, so there is no space for the balloon to expand. (b) In bottle Q, the air can escape through the hole, making space for the balloon to expand." },
    { q: "Siti used a measuring cylinder to find the volume of a stone, as shown.\n(a) What is the volume of the stone? (1 mark)\n(b) Explain why the water level rose when the stone was put in. (1 mark)\n(c) Why must the stone be completely under the water? (1 mark)", fig: { type: "setups", items: [ { label: "1", icon: "beaker", lines: ["Water only", "Reading: 50 ml"] }, { label: "2", icon: "beaker", lines: ["Water + stone", "Reading: 72 ml"] } ] }, marks: 3, kw: [["22"], ["occupies space", "occupy space", "takes up space", "take up space", "pushes", "pushed", "displace"], ["whole stone", "entire stone", "all of the stone", "less", "smaller"]], model: "(a) 72 ml − 50 ml = 22 cm³. (b) The stone occupies space, so it pushed the water up. (c) If part of the stone is above the water, the rise in water level only shows the volume of the part under the water, which is less than the volume of the whole stone." },
    { q: "Hakim measured the mass of a basketball after pumping different numbers of pumps of air into it. The results are shown in the graph.\n(a) What happened to the mass of the ball as more air was pumped in? (1 mark)\n(b) What does this show about air? (1 mark)\n(c) The size of the ball hardly changed, yet more air fitted inside. What property of air allows this? (1 mark)", fig: { type: "bar", xl: "Number of pumps", yl: "Mass of basketball (g)", bars: [["0", 600], ["5", 603], ["10", 606], ["15", 609]] }, marks: 3, kw: [["increase", "went up", "goes up", "more mass", "heavier"], ["air has mass", "has mass"], ["compress"]], model: "(a) The mass of the ball increased. (b) Air has mass. (c) Air can be compressed, so more air is squeezed into the same space in the ball." },
    { q: "Liquid X was poured from a tall narrow glass into a wide bowl. Its volume stayed at 200 ml, but its shape changed. State the state of matter of X and give a reason based on your observation.", marks: 2, kw: [["liquid"], ["definite volume", "volume stayed", "volume stays", "same volume", "volume remained"]], model: "X is a liquid because it has a definite volume: its volume stayed at 200 ml, although it took the shape of the bowl." },
    { q: "Mei says, “A shadow is matter because I can see it.” Do you agree? Explain your answer.", marks: 2, kw: [["no mass", "not have mass", "doesn't have mass", "without mass", "not have any mass"], ["not occupy space", "not take up space", "doesn't occupy", "doesn't take up", "no space"]], model: "I disagree. A shadow is not matter because it has no mass and does not occupy space." },
    { q: "An open 500 ml bottle contains 150 ml of water, as shown.\n(a) What is the volume of air in the bottle? (1 mark)\n(b) Another 100 ml of water is poured in. What is the volume of air in the bottle now? (1 mark)\n(c) What property of gases do your answers show? (1 mark)", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["500 ml bottle", "150 ml of water", "Open top"] } ] }, marks: 3, kw: [["350"], ["250"], ["no definite volume", "volume of its container", "volume of the container", "shape and volume", "fills", "takes up all the space", "space available"]], model: "(a) 500 ml − 150 ml = 350 ml. (b) 500 ml − 250 ml = 250 ml. (c) A gas has no definite volume; air fills the space available in its container that is not taken up by the water." },
    { q: "Two flasks were set up as shown and the same amount of water was poured into each funnel.\n(a) What would you observe in flask A? (1 mark)\n(b) Explain your answer to (a). (2 marks)\n(c) Explain why water flowed easily into flask B. (1 mark)", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Funnel in flask", "Plasticine seal"] }, { label: "B", icon: "jar", lines: ["Funnel in flask", "Plasticine seal", "Straw through seal"] } ] }, marks: 4, kw: [["collect", "stay", "little", "slowly", "remain"], ["occupies space", "occupy space", "takes up space", "take up space"], ["cannot escape", "could not escape", "can't escape", "couldn't escape", "trapped", "no way out"], ["straw"]], model: "(a) The water would collect in the funnel and very little would flow into flask A. (b) Flask A is full of air, which occupies space. The air is trapped and cannot escape, so the water cannot enter to take its place. (c) In flask B, the air can escape out through the straw, so water can flow in to take up the space.", x: 1 },
    { q: "Ravi wants to find the volume of a piece of cork, which floats on water. His readings are shown in the table.\n(a) What is the volume of the metal sinker? (1 mark)\n(b) What is the volume of the cork? (1 mark)\n(c) Why did Ravi tie the cork to the sinker? (2 marks)", tbl: [["Set-up", "Water level (ml)"], ["Water only", "40"], ["Water + metal sinker", "52"], ["Water + sinker tied to cork, both under water", "70"]], marks: 4, kw: [["12"], ["18"], ["float"], ["completely under", "fully under", "whole cork", "entire cork", "all of the cork", "submerge"]], model: "(a) 52 ml − 40 ml = 12 cm³. (b) 70 ml − 52 ml = 18 cm³. (c) The cork floats, so on its own part of it would stay above the water. The sinker keeps the cork completely under the water, so the rise in water level shows the volume of the whole cork.", x: 1 },
    { q: "A scuba diver’s rigid steel tank has a volume of 12 l. Air is pumped into the tank until it holds many times more air than it did before.\n(a) What happens to the mass of the tank as air is pumped in? (1 mark)\n(b) What is the volume of air in the tank after pumping? Explain. (2 marks)\n(c) Why is it possible to put so much air into the tank? (1 mark)", marks: 4, kw: [["increase", "heavier", "more mass", "goes up"], ["12"], ["volume of the tank", "volume of its container", "volume of the container", "shape and volume", "fills", "no definite volume"], ["compress"]], model: "(a) The mass of the tank increases, because air has mass. (b) 12 l. A gas takes the shape and volume of its container, so the air fills the whole tank. (c) Air can be compressed, so a large amount of air can be squeezed into the same space.", x: 1 },
    { q: "Why can a tank of cooking gas store a large amount of gas in a small space?", marks: 2, kw: [["compress"], ["small", "less space", "same space"]], model: "Gas can be compressed, so a large amount of gas can be squeezed into a small space in the tank." },
    { q: "Ravi squeezed a dry sponge and it became much smaller. He said, “This shows that solids can be compressed.” Explain why Ravi is wrong.", marks: 2, kw: [["holes", "spaces", "pores", "air in the sponge"], ["pushed out", "squeezed out", "escape", "forced out", "comes out", "leave"]], model: "The sponge has many holes filled with air. When it is squeezed, the air in the holes is pushed out, so the sponge becomes smaller. The solid material of the sponge is not compressed." }
  ],
  doc: [
    { q: "Explain why air is considered matter.", marks: 2, answers: ["Air is matter because it is everywhere around us.", "Air is matter because it has mass and occupies space.", "Air is matter because we can feel it when the wind blows."], best: 1, why: "Answer 2 gives both parts of the definition: mass AND occupies space. Answer 1 is not a property of matter at all. Answer 3 uses ‘can feel it’, which is also true of heat, which is not matter." },
    { q: "A cup with tissue at its base was turned upside down and pushed straight down into water. Explain why the tissue stayed dry.", marks: 2, answers: ["The tissue is dry because the cup protects it.", "Air has mass, so water cannot go in.", "The air trapped in the cup occupies space, so water cannot enter the cup to wet the tissue."], best: 2, why: "Answer 3 names air, the keyword ‘occupies space’ and the result. Answer 1 is too vague and does not mention air. Answer 2 uses the wrong property: mass does not keep the water out." },
    { q: "Substance X has no definite shape but has a definite volume. State its state and explain.", marks: 2, answers: ["X is a liquid because it has a definite volume but takes the shape of its container.", "X is a liquid because it can flow.", "X is a liquid because it has no definite shape."], best: 0, why: "Answer 1 gives both properties that separate a liquid from a solid and a gas. Answer 2 uses ‘flow’, which is not a property markers accept. Answer 3 gives only one property, and a gas also has no definite shape." },
    { q: "A measuring cylinder had 30 ml of water. A stone was put in and the level rose to 48 ml. What is the volume of the stone? Explain how you got it.", marks: 2, answers: ["The volume is 48 ml because the reading is 48 ml.", "The volume of the stone is 18 cm³, because it pushed the water up by 48 − 30 = 18 ml.", "The stone’s volume is 18 g."], best: 1, why: "Answer 2 subtracts the initial reading and uses a volume unit. Answer 1 takes the final reading, which includes the water. Answer 3 has the right number but the wrong unit: g is a unit of mass." },
    { q: "The nozzle of a syringe of air was sealed. Explain why the plunger could be pushed in, but not all the way in.", marks: 2, answers: ["Air can be compressed, so the plunger can be pushed in. But air occupies space, so the plunger cannot be pushed all the way in.", "Air can be compressed, so the plunger can be pushed in.", "Air is light, so the plunger moves in easily until it gets stuck."], best: 0, why: "Answer 1 explains both parts: ‘compressed’ for moving in and ‘occupies space’ for stopping. Answer 2 only explains the first part. Answer 3 uses ‘light’, which is not a property of matter, and ‘gets stuck’ explains nothing." }
  ]
};
