window.LB = window.LB || {};
LB["p4-mixed"] = {
  notes: [
    { h: "Materials and heat conduction", t: "Metals such as copper, aluminium, iron and steel are good conductors of heat: heat flows through them quickly. Wood, plastic, rubber, glass, Styrofoam and air are poor conductors of heat: heat flows through them slowly. So a cooking pot is made of metal to conduct heat quickly to the food, while its handle is made of plastic or wood to conduct heat slowly to the hand.", kw: ["good conductor of heat", "poor conductor of heat", "conducts heat quickly", "conducts heat slowly"] },
    { h: "Materials and light", t: "A transparent material (clear glass, clear plastic) allows most light to pass through. A translucent material (frosted glass, tracing paper) allows some light to pass through, so objects behind it look blurred. An opaque material (wood, cardboard, metal) does not allow light to pass through. Choose by use: frosted glass for bathroom windows lets light in but gives privacy.", kw: ["transparent", "translucent", "opaque", "allows some light to pass through"] },
    { h: "Light, shadows and materials", t: "Light travels in straight lines. A shadow forms when an object blocks light. An opaque object forms a dark shadow; a translucent object forms a faint shadow; a transparent object forms almost no shadow. We see an object when light from it, or reflected by it, enters our eyes.", kw: ["light travels in straight lines", "blocks light", "shadow", "reflected"] },
    { h: "Heat and expansion", t: "Most solids, liquids and gases expand when they gain heat and contract when they lose heat. Gaps are left between railway tracks and on bridges so the metal can expand on hot days without bending. A dented ping pong ball pops back in hot water because the air inside gains heat and expands. The mass does not change when something expands or contracts.", kw: ["gains heat and expands", "loses heat and contracts", "mass stays the same"] },
    { h: "States of matter", t: "Matter is anything that has mass and occupies space. A solid has a definite shape and a definite volume. A liquid has a definite volume but no definite shape; it takes the shape of its container. A gas has no definite shape and no definite volume, and it can be compressed. Air is matter: it has mass and occupies space.", kw: ["has mass and occupies space", "definite shape", "definite volume", "can be compressed"] },
    { h: "Heat flow and temperature", t: "Heat is a form of energy. It flows from a hotter object or place to a colder one until both are at the same temperature. Temperature, measured in °C with a thermometer, tells how hot or cold something is. Gaining heat can make a solid melt, like chocolate left in a hot car; losing heat makes hot soup cool down.", kw: ["heat flows from a hotter to a colder", "same temperature", "gains heat", "loses heat"] },
    { h: "Plant parts through the life cycle", t: "When a seed germinates, the root grows out first, followed by the shoot. Until it has leaves, the seedling uses food stored in its seed leaves. Roots then absorb water and mineral salts and hold the plant firmly in the soil; the stem holds the plant upright; leaves make food. The adult plant flowers, and flowers develop into fruits containing seeds.", kw: ["root grows out first", "seed leaves", "absorb water and mineral salts", "leaves make food"] },
    { h: "The stem carries water and food", t: "The stem carries water and mineral salts from the roots to the leaves and other parts of the plant. It also carries food made in the leaves to other parts, such as the roots, flowers and fruits. A white flower or a leafy shoot placed in red-coloured water turns red, showing that water travels up the stem.", kw: ["stem carries water", "carries food made in the leaves", "red-coloured water"] },
    { h: "Digestion and the needs of living things", t: "All living things need food for energy and to grow. Plants make their own food in their leaves, but humans must eat food and digest it. Digestive juices in the mouth, stomach and small intestine break down food into simpler substances. Digested food is absorbed into the bloodstream in the small intestine and carried to all parts of the body.", kw: ["need food", "break down food into simpler substances", "absorbed into the bloodstream", "small intestine"] },
    { h: "The digestive organs in order", t: "Food passes through the mouth, gullet, stomach, small intestine and large intestine, and undigested food leaves through the anus. The gullet only moves food to the stomach; no digestion takes place there. The large intestine absorbs water from undigested food.", kw: ["mouth", "gullet", "stomach", "small intestine", "large intestine", "anus", "absorbs water"] },
    { h: "Magnets meet other properties", t: "Only magnetic materials (iron, steel, nickel, cobalt) are attracted by magnets. Aluminium and copper are metals and good conductors of heat, but they are not magnetic. At a recycling plant, a magnet separates steel cans from aluminium cans. Several properties together, such as magnetic, opaque and good conductor, can pin down one material.", kw: ["magnetic materials", "iron", "steel", "not magnetic"] },
    { h: "Answering crossover questions", t: "A crossover question tests two topics at once, so answer each part with the correct topic’s keywords. For example, ‘Why is a Styrofoam cup better for hot kopi?’ needs a material property (poor conductor of heat) and a heat idea (heat is lost slowly). Answer each part separately and use the part labels.", kw: ["each part", "keywords from both topics", "claim and reason"] }
  ],
  traps: [
    "When a ball of air expands, the air gains mass -> Expansion changes the volume, not the mass.",
    "A thermometer measures heat -> It measures temperature (how hot or cold); heat is a form of energy that flows.",
    "All metals are attracted by magnets -> Only iron, steel, nickel and cobalt are; aluminium and copper are not, although they are good heat conductors.",
    "Translucent objects form no shadow -> They block some light and form a faint shadow; only transparent objects form almost no shadow.",
    "The gullet digests food -> The gullet only moves food to the stomach; digestion happens in the mouth, stomach and small intestine.",
    "The stem only holds the plant upright -> it also carries water and mineral salts from the roots, and food made in the leaves, to other parts of the plant.",
    "Cold flows into a drink from the ice -> Heat flows from the warmer drink to the colder ice.",
    "A seedling gets its first food from the soil -> It uses food stored in the seed leaves until its leaves can make food."
  ],
  lessons: [
    {
      h: "Choosing a material using two properties",
      concept: "Crossover items often ask why different parts of one object are made of different materials. Give the property AND how it helps in that use. For heat: good conductor → heat flows quickly (pot base); poor conductor → heat flows slowly (handle, cup). If the question also involves another property, such as strength or waterproof, add it as a separate point.",
      example: {
        q: "A frying pan has a steel base and a plastic handle.\n(a) Why is the base made of steel? [1]\n(b) Why is the handle made of plastic? [2]",
        marks: 3,
        think: [
          "Step 1: Base: it must pass heat from the stove to the food. Steel is a metal, a good conductor of heat.",
          "Step 2: Handle: it must stop the hand from getting burnt. Plastic is a poor conductor of heat.",
          "Step 3: For each property, say what it does in this use: heat flows quickly to the food; heat flows slowly to the hand.",
          "Step 4: Two marks for (b) means two ideas: the property and its effect on the hand."
        ],
        answer: "(a) Steel is a good conductor of heat, so heat from the stove flows quickly to the food. (b) Plastic is a poor conductor of heat, so heat is conducted slowly from the hot pan to the hand, and the hand does not get burnt."
      },
      tip: "Property + effect in THIS use. ‘Plastic is a poor conductor’ alone is half the answer.",
      try: {
        q: "Which material is most suitable for a cup that keeps hot soup warm for a long time?",
        o: ["Copper", "Aluminium", "Styrofoam", "Steel"],
        a: 2,
        why: "Styrofoam is a poor conductor of heat, so the soup loses heat to the surroundings slowly. The three metals are good conductors of heat."
      }
    },
    {
      h: "Explaining expansion and contraction",
      concept: "Use a three-link chain: the object or the air inside it GAINS heat (or loses heat), so it EXPANDS (or contracts), so something visible happens. Name WHAT expands: in a dented ping pong ball it is the air inside, not the plastic. Expansion does not change mass.",
      example: {
        q: "Study the set-ups. A dented ping pong ball was put into cold water, and then into hot water, where the dent popped out. Explain why. [2]",
        fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Dented ping pong ball", "Cold water", "Dent stays"] }, { label: "B", icon: "beaker", lines: ["Dented ping pong ball", "Hot water", "Dent pops out"] }] },
        marks: 2,
        think: [
          "Step 1: Where does heat flow? From the hot water to the ball and the air inside.",
          "Step 2: What expands? The air inside the ball gains heat and expands.",
          "Step 3: Effect: the expanding air pushes the dented part outwards.",
          "Step 4: Check that you named the air and used both keywords: gains heat, expands."
        ],
        answer: "The air inside the ball gained heat from the hot water and expanded. The expanding air pushed the dent outwards."
      },
      tip: "Gains heat → expands → pushes. Loses heat → contracts. Always name what gains or loses heat.",
      try: {
        q: "A sealed syringe of air is put into hot water, and its plunger moves out. Which statement about the air inside is correct?",
        o: ["Its mass increases because it has gained heat.", "It loses heat and contracts, and its mass stays the same.", "Its volume and mass both stay the same as it gains heat.", "It gains heat and expands, but its mass stays the same."],
        a: 3,
        why: "The air gains heat and expands, pushing the plunger out. No air is added, so its mass stays the same."
      }
    },
    {
      h: "Light, materials and shadows together",
      concept: "Link the material to the amount of light that passes through and to the shadow. Opaque: no light passes through, dark shadow. Translucent: some light passes through, faint shadow, objects behind look blurred. Transparent: most light passes through, almost no shadow. Light sensor: a higher reading means more light passes through.",
      example: {
        q: "Study the graph of light sensor readings behind four sheets. (a) Which sheet forms the darkest shadow? (b) Which sheet is best for a bathroom window? Explain. [3]",
        fig: { type: "bar", title: "Light passing through sheets", xl: "Sheet", yl: "Light sensor reading (lux)", bars: [["Clear glass", 900], ["Frosted glass", 420], ["Cardboard", 0]] },
        marks: 3,
        think: [
          "Step 1: Darkest shadow = least light through = lowest reading: cardboard, 0 lux.",
          "Step 2: A bathroom window must let light in but stop people seeing in clearly, so it should be translucent.",
          "Step 3: Frosted glass (420 lux) lets some light through, less than clear glass but more than cardboard.",
          "Step 4: Write the claim and the reasons."
        ],
        answer: "(a) Cardboard, because it gave a reading of 0 lux, so it is opaque and blocks all the light. (b) Frosted glass. It is translucent: it allows some light to pass through, so the bathroom is bright, but people outside cannot see in clearly."
      },
      tip: "Lowest reading = darkest shadow. Middle reading = translucent = privacy with light.",
      try: {
        q: "Which object would form a faint shadow on a screen?",
        o: ["A clear glass plate", "A sheet of tracing paper", "A wooden block", "A steel ruler"],
        a: 1,
        why: "Tracing paper is translucent, so it blocks some light and forms a faint shadow. Wood and steel are opaque (dark shadows); clear glass is transparent (almost no shadow)."
      }
    },
    {
      h: "Plant parts across the life cycle",
      concept: "Match each part to what the plant needs at that stage. Germinating seed: needs water, air and warmth; the root grows out first and absorbs water. Seedling: uses food stored in the seed leaves until its leaves can make food. Adult: roots absorb water and hold the plant, stem holds it upright and transports water and food, leaves make food, flowers develop into fruits with seeds.",
      example: {
        q: "Study the life cycle. (a) Which part grows out first when the seed germinates? (b) State one function of this part. (c) Before its leaves grow, where does the seedling get its food? [3]",
        fig: { type: "cycle", stages: ["Seed", "Seedling", "Young plant", "Adult plant"] },
        marks: 3,
        think: [
          "Step 1: At germination, the root always comes out first, then the shoot.",
          "Step 2: The root absorbs water for the seedling, and holds it in the soil.",
          "Step 3: With no leaves yet, it cannot make food; it uses the food stored in its seed leaves.",
          "Step 4: One idea per mark."
        ],
        answer: "(a) The root. (b) It absorbs water from the soil (or holds the seedling firmly in the soil). (c) From the food stored in its seed leaves."
      },
      tip: "Root first. Seed leaves feed the seedling. Leaves make food later.",
      try: {
        q: "A caterpillar ate most of the leaves of a young plant. Which process of the plant is most directly affected?",
        fig: { type: "plant", mark: { roots: "A", stem: "B", leaf: "C", flower: "D" } },
        o: ["Making food", "Absorbing water", "Holding the plant upright", "Holding the plant in the soil"],
        a: 0,
        why: "Leaves (C) make food for the plant, so losing them reduces food-making. Roots absorb water and hold the plant in the soil; the stem holds it upright."
      }
    },
    {
      h: "Following food from the plate to the body",
      concept: "Digestion links to the needs of living things: the body needs food for energy and to grow, but food must first be broken down. Say it in order: digestive juices break down food into simpler substances (mouth, stomach, small intestine); digested food is absorbed into the bloodstream in the small intestine and carried to all parts of the body; the large intestine absorbs water; undigested food leaves through the anus.",
      example: {
        q: "Study the diagram. (a) Name part X and state what happens to digested food there. (b) What does part W do? [3]",
        fig: { type: "organs", system: "digestive", mark: { stomach: "Y", small_intestine: "X", large_intestine: "W" } },
        marks: 3,
        think: [
          "Step 1: X is the long coiled tube after the stomach: the small intestine.",
          "Step 2: Digested food is absorbed into the bloodstream there, to be carried to all parts of the body.",
          "Step 3: W is the wider tube around it: the large intestine, which absorbs water from undigested food.",
          "Step 4: Name each part, then give its function with the keywords."
        ],
        answer: "(a) X is the small intestine. Digested food is absorbed into the bloodstream there and carried to all parts of the body. (b) W, the large intestine, absorbs water from the undigested food."
      },
      tip: "Small intestine: digestion finishes and digested food is absorbed. Large intestine: water is absorbed.",
      try: {
        q: "In which part is NO digestion of food carried out?",
        fig: { type: "organs", system: "digestive", mark: { mouth: "A", gullet: "B", stomach: "C", small_intestine: "D" } },
        o: ["A", "C", "D", "B"],
        a: 3,
        why: "B is the gullet, which only moves food to the stomach. Digestive juices break down food in the mouth (A), stomach (C) and small intestine (D)."
      }
    }
  ],
  mcq: [
    { q: "Which material is most suitable for the base of a cooking pot?", o: ["Hard plastic", "Solid wood", "Stainless steel", "Thick rubber"], a: 2, why: "Stainless steel is a metal and a good conductor of heat, so heat flows quickly to the food. Plastic, wood and rubber are poor conductors of heat.", lvl: 1 },
    { q: "Which of these is transparent?", o: ["Clear glass window", "Frosted glass", "Wooden door", "Tracing paper"], a: 0, why: "Clear glass allows most light to pass through, so it is transparent. Frosted glass and tracing paper are translucent, and wood is opaque.", lvl: 1 },
    { q: "Study the diagram. In which part is digested food absorbed into the bloodstream?", o: ["A", "B", "C", "D"], a: 2, why: "C is the small intestine, where digested food is absorbed into the bloodstream. D, the large intestine, absorbs water.", lvl: 1, fig: { type: "organs", system: "digestive", mark: { gullet: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } } },
    { q: "A metal spoon is put into a bowl of hot soup. In which direction does heat flow?", o: ["From the spoon to the soup", "From the soup to the spoon", "No heat flows", "From the air into the soup only"], a: 1, why: "Heat flows from a hotter object to a colder one, so it flows from the hot soup into the cooler spoon.", lvl: 1 },
    { q: "Study the diagram of a plant. Which part absorbs water and holds the plant firmly in the soil?", o: ["A", "B", "C", "D"], a: 0, why: "A is the roots, which absorb water and mineral salts and hold the plant in the soil. B, the stem, holds the plant upright.", lvl: 1, fig: { type: "plant", mark: { roots: "A", stem: "B", leaf: "C", flower: "D" } } },
    { q: "Which of these is a gas?", o: ["Ice", "Cooking oil", "Sand", "Steam"], a: 3, why: "Steam is water in the gas state. Ice and sand are solids, and cooking oil is a liquid.", lvl: 1 },
    { q: "Which object is attracted by a magnet AND is a good conductor of heat?", o: ["Steel paper clip", "Copper coin", "Plastic ruler", "Glass marble"], a: 0, why: "Steel is magnetic and, like all metals, a good conductor of heat. Copper conducts heat well but is not magnetic.", lvl: 1 },
    { q: "Study the life cycle of a flowering plant. Which stage is missing?", o: ["Fruit", "Seedling", "Flower", "Pupa"], a: 1, why: "A seed germinates into a seedling, which grows into a young plant. Pupa is a stage of some animals, not plants.", lvl: 1, fig: { type: "cycle", stages: ["Seed", "?", "Young plant", "Adult plant"] } },

    { q: "A dented ping pong ball is put into hot water and the dent pops out. Why?", o: ["The plastic contracts.", "The air inside gains heat and expands.", "Hot water enters the ball.", "The air inside loses heat and contracts."], a: 1, why: "Heat flows from the hot water into the ball, so the air inside gains heat, expands and pushes the dent out. No water enters the sealed ball.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Dented ping pong ball", "Cold water", "Dent stays"] }, { label: "B", icon: "beaker", lines: ["Dented ping pong ball", "Hot water", "Dent pops out"] }] } },
    { q: "Study the Venn diagram. Which object has been placed in the WRONG region?", o: ["Copper wire", "Iron nail", "Steel spoon", "Rubber band"], a: 1, why: "An iron nail is attracted by a magnet AND is a good conductor of heat, so it belongs in the overlap, not in ‘good conductor’ only.", lvl: 2, fig: { type: "venn", a: "Good conductor of heat", b: "Attracted by a magnet", onlyA: ["copper wire", "iron nail"], both: ["steel spoon"], onlyB: [], neither: ["glass rod", "rubber band"] } },
    { q: "Why are small gaps left between sections of railway tracks?", o: ["To let rainwater drain away so the rails do not rust", "To save metal so the railway costs less to build", "To make the train quieter as its wheels roll over the rails", "To leave room for the rails to expand when they gain heat"], a: 3, why: "Steel rails gain heat and expand on hot days. Without gaps, they would push against each other and bend.", lvl: 2 },
    { q: "Study the graph of light sensor readings behind four materials. Which material would form the darkest shadow?", o: ["Glass", "Tracing paper", "Frosted plastic", "Cardboard"], a: 3, why: "Cardboard gave a reading of 0, so it blocks all light and forms the darkest shadow. Glass lets most light through and forms almost no shadow.", lvl: 2, fig: { type: "bar", title: "Light passing through materials", xl: "Material", yl: "Light sensor reading (lux)", bars: [["Glass", 900], ["Tracing paper", 400], ["Frosted plastic", 350], ["Cardboard", 0]] } },
    { q: "Hot kopi stays hot longer in a Styrofoam cup than in a metal cup. This is because Styrofoam is…", o: ["a poor conductor of heat, so the kopi loses heat slowly", "a good conductor of heat, so it keeps heat in", "transparent, so it lets heat in", "attracted by a magnet"], a: 0, why: "A poor conductor lets heat flow through slowly, so the kopi loses heat to the surroundings more slowly. A good conductor would let it lose heat quickly.", lvl: 2 },
    { q: "Kumar could not open a tight metal lid on a glass jar. He ran hot water over the lid and it opened easily. Why?", o: ["The glass jar gained heat and contracted, so the lid fit less tightly.", "The metal lid lost heat and contracted, so it became looser.", "The metal lid gained heat and expanded, so it became looser.", "The hot water made the lid lighter, so it was easier to turn."], a: 2, why: "The metal lid gains heat from the hot water and expands, so it fits less tightly. Its mass does not change.", lvl: 2 },
    { q: "Study the diagram. In which part is water absorbed from undigested food?", o: ["P", "Q", "R", "S"], a: 3, why: "S is the large intestine, which absorbs water from undigested food. R, the small intestine, absorbs digested food.", lvl: 2, fig: { type: "organs", system: "digestive", mark: { mouth: "P", stomach: "Q", small_intestine: "R", large_intestine: "S" } } },
    { q: "A green bean seed germinated on moist cotton wool. Before it grew leaves, where did the seedling get its food?", o: ["From food stored in its seed leaves", "From the moist cotton wool it grew on", "From the water that it took in", "From its roots, which took in food"], a: 0, why: "The seed leaves store food, which the seedling uses until its leaves can make food. Cotton wool and water do not provide food.", lvl: 2 },
    { q: "A leafy balsam shoot was left in red-coloured water. When its stem was cut across, red dots were seen. What does this show?", o: ["The stem makes red food.", "The stem stores red water.", "Water travels up the stem.", "The leaves send water down the stem."], a: 2, why: "The red water was taken up and travelled up the stem, staining the parts it passed through. The stem carries water from the bottom of the plant upwards; it does not make food.", lvl: 2 },
    { q: "A sponge can be squeezed into a smaller size, yet it is a solid. What is the best explanation?", o: ["A sponge is a gas, so it can be compressed like air.", "A sponge is a solid with no definite volume, so it can shrink.", "Air is squeezed out of its holes, but the solid part keeps its volume.", "The sponge loses mass when it is squeezed, so it shrinks."], a: 2, why: "A sponge has many holes filled with air. Squeezing pushes the air out, so the solid material itself keeps its definite volume.", lvl: 2 },
    { q: "Water at 80 °C was poured into four cups of the same size. Study the graph of the temperature after 30 minutes. Which cup is made of the best conductor of heat?", o: ["Styrofoam", "Plastic", "Metal", "Glass"], a: 2, why: "The water in the metal cup lost the most heat (it dropped to 42 °C), so heat flowed through metal the fastest. Styrofoam kept the water the warmest.", lvl: 2, fig: { type: "bar", title: "Temperature after 30 minutes", xl: "Material of cup", yl: "Temperature (°C)", bars: [["Metal", 42], ["Glass", 50], ["Plastic", 55], ["Styrofoam", 68]] } },
    { q: "Which material is best for a bathroom window that lets light in but stops people outside from seeing in clearly?", o: ["Clear glass", "Frosted glass", "Wood", "Aluminium"], a: 1, why: "Frosted glass is translucent: it allows some light through but objects behind it look blurred. Clear glass is transparent; wood and aluminium block all light.", lvl: 2 },
    { q: "Why do humans need a digestive system?", o: ["Humans need food for energy and growth, and it must be broken down to be absorbed", "Humans need to respond to changes around them, such as heat, light and sound", "Humans need to reproduce so that more of their kind can survive", "Humans need to take in air so that the body gets enough oxygen"], a: 0, why: "Living things need food for energy and to grow. Digestion breaks food into simpler substances that the body can absorb.", lvl: 2 },
    { q: "A bar of chocolate left in a car on a hot day became soft and runny. Which is the best explanation?", o: ["It lost heat to the hot surroundings and contracted.", "It gained heat from the hot surroundings and melted.", "It absorbed water from the damp air and softened.", "It turned into a gas when the car became hot."], a: 1, why: "Heat flowed from the hot air in the car into the chocolate. The chocolate gained heat and melted from a solid into a liquid.", lvl: 2 },

    { q: "Study the set-ups. Which two should be compared to find out if the material of a spoon affects how fast heat travels to its top end?", o: ["A and C", "B and C", "A and D", "A and B"], a: 3, why: "A and B differ only in the spoon material (metal, plastic). A and C, and B and D, differ in both material and water temperature; A and D differ only in temperature. (C and D would also be a fair pair, but it is not an option.)", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Metal spoon", "Water at 80 °C", "Wax bead on top end"] }, { label: "B", icon: "beaker", lines: ["Plastic spoon", "Water at 80 °C", "Wax bead on top end"] }, { label: "C", icon: "beaker", lines: ["Plastic spoon", "Water at 50 °C", "Wax bead on top end"] }, { label: "D", icon: "beaker", lines: ["Metal spoon", "Water at 50 °C", "Wax bead on top end"] }] } },
    { q: "A thermometer is put into hot water and its liquid rises. Which statements explain this?\nA: The liquid in the thermometer gains heat.\nB: The liquid expands.\nC: The glass tube contracts and squeezes the liquid up.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "The liquid gains heat from the hot water and expands, so it rises up the narrow tube. The glass also gains heat; it does not contract.", lvl: 3 },
    { q: "Study the diagram. A caterpillar ate most of part C of this plant. Which process of the plant is most directly affected?", o: ["Absorbing water", "Holding the plant upright", "Making food", "Holding the plant in the soil"], a: 2, why: "C is a leaf, and leaves make food for the plant. Absorbing water and holding the plant in the soil are done by the roots (A); the stem (B) holds it upright.", lvl: 3, fig: { type: "plant", mark: { roots: "A", stem: "B", leaf: "C", flower: "D" } } },
    { q: "Study the life cycle of a butterfly. At which stage(s) does the organism NOT feed?", o: ["Egg only", "Pupa only", "Egg and pupa only", "Larva and adult only"], a: 2, why: "The egg and the pupa do not feed. The larva (caterpillar) eats leaves and the adult butterfly feeds on nectar.", lvl: 3, fig: { type: "cycle", stages: ["Egg", "Larva", "Pupa", "Adult"] } },
    { q: "Study the graph of light sensor readings behind sheets W, X, Y and Z. Which statement is most likely to be correct?", o: ["X and Y are translucent.", "W forms the darkest shadow.", "Z is transparent.", "Y lets more light through than X."], a: 0, why: "X and Y let some light through (about half of W), so they are likely translucent. W lets the most light through, Z lets none through (opaque, darkest shadow), and Y’s reading (480) is lower than X’s (500).", lvl: 3, fig: { type: "bar", title: "Light passing through sheets", xl: "Sheet", yl: "Light sensor reading (lux)", bars: [["W", 950], ["X", 500], ["Y", 480], ["Z", 0]] } },
    { q: "Study the set-ups. Two identical syringes of air had their nozzles sealed. The plunger of syringe B moved out. Which statement about the air in B is correct?", o: ["Its mass increased.", "Its volume increased but its mass stayed the same.", "Its volume and mass both stayed the same.", "Its volume decreased."], a: 1, why: "The air in B gained heat from the hot water and expanded, so its volume increased. The nozzle was sealed, so no air entered or left and the mass stayed the same.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Sealed syringe of air", "In cold water", "Plunger stays"] }, { label: "B", icon: "beaker", lines: ["Sealed syringe of air", "In hot water", "Plunger moves out"] }] } },
    { q: "Mei ate a plate of chicken rice. In which parts of her digestive system is the food digested?", o: ["Mouth and stomach only", "Stomach and small intestine only", "Mouth, stomach and small intestine", "Gullet, stomach and large intestine"], a: 2, why: "Digestive juices break down food in the mouth, stomach and small intestine. No digestion takes place in the gullet or large intestine.", lvl: 3 },
    { q: "An object is opaque, is NOT attracted by a magnet and is a good conductor of heat. What could it be?", o: ["Glass rod", "Steel spoon", "Aluminium foil", "Wooden stick"], a: 2, why: "Aluminium is opaque, not magnetic and a good conductor of heat. Steel is magnetic, glass lets light through, and wood is a poor conductor.", lvl: 3 },
    { q: "A flask of hot coloured water with a glass tube was left in a room. Study the graph. Why did the water level stop falling at 15 minutes?", o: ["The water froze, so it could no longer move down the glass tube.", "The water reached room temperature, so it stopped losing heat and contracting.", "The glass tube became blocked, so the water level could no longer fall.", "The water started to gain heat from the room and expand again."], a: 1, why: "The water lost heat and contracted until it reached room temperature. After that, there was no more heat loss, so the level stayed the same.", lvl: 3, fig: { type: "line", title: "Height of coloured water in tube", xl: "Time (min)", yl: "Height of water in tube (cm)", pts: [["0", 9.0], ["5", 7.5], ["10", 6.5], ["15", 6.0], ["20", 6.0], ["25", 6.0]] } },
    { q: "Which statements about a flowering plant are correct?\nA: Roots absorb water and mineral salts.\nB: The stem carries only food.\nC: Leaves make food.\nD: Flowers develop into fruits.", o: ["A and C only", "A, C and D only", "B, C and D only", "A, B, C and D"], a: 1, why: "The stem carries both water and food, so B is wrong. A, C and D are correct.", lvl: 3 },
    { q: "Study the classification chart. Which material is at D?", o: ["Frosted glass", "Clear plastic", "Copper", "Rubber"], a: 3, why: "Rubber does not let light through and is a poor conductor of heat, so it ends at D. Copper is at C, clear plastic at A and frosted glass at B.", lvl: 3, fig: { type: "flow", root: "Materials", node: { q: "Lets light through?", yes: { q: "Can see clearly through?", yes: "A", no: "B" }, no: { q: "Good heat conductor?", yes: "C", no: "D" } } } },
    { q: "Which statement is true of BOTH a human and bread mould?", o: ["Both make their own food using light from the Sun.", "Both have a stomach to digest the food they take in.", "Both reproduce from spores that are carried by the wind.", "Neither can make food, so both get it from other things."], a: 3, why: "Humans and fungi such as bread mould cannot make their own food, so they get it from other things. Only mould reproduces from spores, and only humans have a stomach.", lvl: 3 },

    { q: "Kumar’s metal lid is stuck on a glass jar. Which action is most likely to help, and why?", o: ["Run hot water over the lid only: the lid gains heat and expands, loosening it", "Put the jar in the refrigerator: the lid gains heat and expands, loosening it", "Run cold water over the lid: the lid expands and so it becomes looser", "Put ice on the lid: the lid contracts and becomes looser on the jar"], a: 0, why: "Heating only the lid makes the metal expand while the glass under it stays about the same, so the lid loosens. Cooling makes the lid contract and grip even more tightly.", lvl: 4 },
    { q: "Study the set-ups with 10 green bean seeds each. After 5 days, seeds germinated in A and D but not in B or C. Which conclusions are supported?\nA: Seeds need water to germinate.\nB: Seeds need warmth to germinate.\nC: Seeds need light to germinate.", o: ["A and B only", "A only", "B and C only", "A, B and C"], a: 0, why: "A vs C (only water differs): water is needed. A vs B (only temperature differs): warmth is needed. A vs D (only light differs): both germinated, so light is NOT needed.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist cotton wool", "25 °C", "In the dark"] }, { label: "B", icon: "dish", lines: ["Moist cotton wool", "5 °C", "In the dark"] }, { label: "C", icon: "dish", lines: ["Dry cotton wool", "25 °C", "In the dark"] }, { label: "D", icon: "dish", lines: ["Moist cotton wool", "25 °C", "In the light"] }] } },
    { q: "Study the set-ups. A closed plastic bottle of air was moved from a room to a freezer, and its sides dented inwards. Which statements are correct?\nA: The air inside lost heat.\nB: The air inside contracted.\nC: The mass of the air inside decreased.", o: ["A and B only", "B only", "A, B and C", "C only"], a: 0, why: "Heat flowed from the air to the colder freezer, so the air lost heat and contracted, and the sides dented in. The cap was closed, so no air left and its mass stayed the same.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Closed bottle of air", "In a room, 30 °C", "Sides smooth"] }, { label: "B", icon: "box", lines: ["Same bottle", "In a freezer, −5 °C", "Sides dented in"] }] } },
    { q: "Study the diagram. A patient had most of part D removed by an operation. Which is the most likely effect?", o: ["Food could not be chewed into smaller pieces in the mouth.", "Food could not be swallowed and passed down to the stomach.", "No digestion would take place anywhere in the body at all.", "Less digested food would be absorbed into the bloodstream."], a: 3, why: "D is the small intestine, where digested food is absorbed into the blood. Chewing (A) and swallowing (B) are unaffected, and some digestion still happens in the mouth and stomach.", lvl: 4, fig: { type: "organs", system: "digestive", mark: { mouth: "A", gullet: "B", stomach: "C", small_intestine: "D", large_intestine: "E" } } },
    { q: "Study the table. Which material is most suitable for the handle of a pot used over a stove?", o: ["P", "Q", "S", "R"], a: 3, why: "A handle must be a poor conductor of heat so the hand is not burnt, and it must stay hard when hot. R has both. Q is a poor conductor but softens; P and S conduct heat quickly.", lvl: 4, tbl: [["Material", "How fast heat travels through it", "When heated to 150 °C"], ["P", "Fast", "Stays hard"], ["Q", "Slow", "Becomes soft"], ["R", "Slow", "Stays hard"], ["S", "Fast", "Bends easily"]] },
    { q: "Study the graph of the length of a flagpole’s shadow on a sunny day. Which statement is correct?", o: ["The flagpole is translucent.", "The shadow is longest at about noon.", "The shadow length does not depend on the position of the Sun.", "The shadow is shortest at about noon, when the Sun is highest in the sky."], a: 3, why: "The shadow is shortest (1 m) at 12 pm, when the Sun is highest, and longest in the morning and late afternoon when the Sun is low. The opaque pole blocks sunlight to form a shadow.", lvl: 4, fig: { type: "line", title: "Length of a flagpole’s shadow", xl: "Time of day", yl: "Length of shadow (m)", pts: [["8am", 12], ["10am", 5], ["12pm", 1], ["2pm", 5], ["4pm", 12]] } }
  ],
  tf: [
    { s: "Metals are poor conductors of heat.", a: false, why: "Metals such as copper, aluminium and steel are good conductors of heat." },
    { s: "A dented ping pong ball can pop back in hot water because the air inside gains heat and expands.", a: true, why: "The expanding air pushes the dent outwards." },
    { s: "Translucent objects do not form any shadow.", a: false, why: "They block some light and form a faint shadow." },
    { s: "Digested food is absorbed into the bloodstream in the small intestine.", a: true, why: "It is then carried to all parts of the body." },
    { s: "The gullet digests food before it reaches the stomach.", a: false, why: "The gullet only moves food to the stomach; no digestion happens there." },
    { s: "Roots absorb water and mineral salts and hold the plant firmly in the soil.", a: true, why: "These are the two main functions of roots." },
    { s: "When an object gains heat and expands, its mass increases.", a: false, why: "Only the volume increases; the mass stays the same." },
    { s: "A Styrofoam box slows down the melting of ice because Styrofoam is a poor conductor of heat.", a: true, why: "Heat from the surroundings flows into the box slowly." },
    { s: "All metals are attracted by magnets.", a: false, why: "Aluminium and copper are metals but are not magnetic." },
    { s: "Air has mass and occupies space.", a: true, why: "Air is matter, so it has mass and occupies space." },
    { s: "When a seed germinates, the shoot grows out before the root.", a: false, why: "The root grows out first, then the shoot." },
    { s: "The larva of a butterfly feeds on leaves.", a: true, why: "The caterpillar eats leaves and grows quickly." },
    { s: "Heat flows from a cold object to a hot object.", a: false, why: "Heat flows from a hotter object to a colder one." },
    { s: "Clear glass is transparent, so it allows most light to pass through.", a: true, why: "That is why clear glass is used for windows we look through." },
    { s: "The stem carries only water, not food.", a: false, why: "The stem carries water and mineral salts from the roots, and food made in the leaves to other parts of the plant." },
    { s: "A shadow is formed when an opaque object blocks light.", a: true, why: "Light travels in straight lines and cannot pass through the object." },
    { s: "A liquid has a definite shape.", a: false, why: "A liquid has a definite volume but takes the shape of its container." },
    { s: "The large intestine absorbs water from undigested food.", a: true, why: "The remaining undigested food then leaves through the anus." },
    { s: "A thermometer measures the amount of heat in an object.", a: false, why: "A thermometer measures temperature, how hot or cold something is." },
    { s: "Gaps are left on some bridges so that the metal parts can expand on hot days.", a: true, why: "The metal gains heat and expands; the gaps stop it from bending." }
  ],
  sort: [
    {
      title: "Sort these materials by how well they conduct heat.",
      groups: ["Good conductor of heat", "Poor conductor of heat"],
      items: [["Copper", 0], ["Aluminium", 0], ["Steel", 0], ["Iron", 0], ["Wood", 1], ["Plastic", 1], ["Rubber", 1], ["Styrofoam", 1], ["Air", 1]]
    },
    {
      title: "Sort these materials by how much light passes through them.",
      groups: ["Transparent", "Translucent", "Opaque"],
      items: [["Clear glass", 0], ["Clear plastic sheet", 0], ["Tracing paper", 1], ["Frosted glass", 1], ["Wax paper", 1], ["Cardboard", 2], ["Aluminium foil", 2], ["Wooden board", 2]]
    },
    {
      title: "In each case, does the object in brackets GAIN heat or LOSE heat?",
      groups: ["Gains heat", "Loses heat"],
      items: [["Ice cream melting in your hand (the ice cream)", 0], ["Hot soup cooling on a table (the soup)", 1], ["Railway tracks on a sunny day (the tracks)", 0], ["Water put in a freezer (the water)", 1], ["Butter in a hot pan (the butter)", 0], ["Your hand holding an ice cube (your hand)", 1], ["A metal lid under a hot tap (the lid)", 0], ["Hot kopi left in a cold room (the kopi)", 1]]
    }
  ],
  oe: [
    { q: "A cooking pot has a steel base and a plastic handle.\n(a) Why is the base made of steel? [1]\n(b) Why is the handle made of plastic? [2]", marks: 3, kw: [["good conductor"], ["poor conductor"], ["hand", "burn"]], model: "(a) Steel is a good conductor of heat, so heat from the stove flows quickly to the food. (b) Plastic is a poor conductor of heat, so heat flows slowly from the hot pot to the hand, and the hand does not get burnt." },
    { q: "Study the set-ups. A dented ping pong ball was put into hot water and the dent popped out.\n(a) Explain why the dent popped out. [2]\n(b) Predict what would happen to the dent if the ball were put into ice water instead, and explain. [1]", marks: 3, kw: [["gain", "gains heat", "gained heat"], ["expand"], ["contract"]], model: "(a) The air inside the ball gained heat from the hot water and expanded, pushing the dent outwards. (b) The dent would stay or get deeper, because the air inside would lose heat and contract.", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Dented ping pong ball", "Hot water", "Dent pops out"] }, { label: "B", icon: "beaker", lines: ["Dented ping pong ball", "Ice water", "?"] }] } },
    { q: "Small gaps are left between the steel sections of a long bridge.\n(a) Explain why the gaps are needed. [2]\n(b) What might happen on a hot day if there were no gaps? [1]", marks: 3, kw: [["gain", "hot"], ["expand"], ["bend", "buckle", "curve", "push", "crack"]], model: "(a) On hot days, the steel gains heat and expands. The gaps give it space to expand. (b) The steel sections would push against each other and bend." },
    { q: "Many bathroom windows in HDB flats are made of frosted glass.\n(a) Is frosted glass transparent, translucent or opaque? [1]\n(b) Explain why frosted glass is suitable for a bathroom window. [2]", marks: 3, kw: [["translucent"], ["some light", "part of the light", "lets light", "allows light", "light to pass", "bright"], ["cannot see", "not see clearly", "unable to see", "blur", "privacy"]], model: "(a) Translucent. (b) It allows some light to pass through, so the bathroom is bright, but objects behind it look blurred, so people outside cannot see clearly into the bathroom." },
    { q: "Study the diagram of the human digestive system.\n(a) Name part X. [1]\n(b) Digested food is absorbed in part X. Where does it go next? [1]\n(c) State the function of part W. [1]\n(d) Why must food be digested before the body can use it? [1]", marks: 4, kw: [["small intestine"], ["blood"], ["water"], ["simpler", "smaller substances", "absorbed"]], model: "(a) The small intestine. (b) It is absorbed into the bloodstream and carried to all parts of the body. (c) W, the large intestine, absorbs water from undigested food. (d) Food must be broken down into simpler substances so that it can be absorbed into the bloodstream.", fig: { type: "organs", system: "digestive", mark: { gullet: "Z", stomach: "Y", small_intestine: "X", large_intestine: "W" } }, x: 1 },
    { q: "Study the life cycle of a flowering plant.\n(a) Which part grows out first when the seed germinates? [1]\n(b) State one function of this part. [1]\n(c) Before it grows leaves, where does the seedling get its food? [1]", marks: 3, kw: [["root"], ["absorb", "hold"], ["seed leaves", "seed leaf", "stored food", "food stored", "food in the seed"]], model: "(a) The root. (b) It absorbs water from the soil. (c) From the food stored in its seed leaves.", fig: { type: "cycle", stages: ["Seed", "Seedling", "Young plant", "Adult plant"] } },
    { q: "Study the set-up. A white carnation on a stalk was left in red-coloured water for a day. Its petals turned red.\n(a) Which part of the plant carried the coloured water up to the flower? [1]\n(b) Explain why the petals turned red. [1]", marks: 2, kw: [["stem", "stalk"], ["carried", "transported", "travelled", "moved up", "carry"]], model: "(a) The stem. (b) The red water was carried up the stem to the flower, so the petals turned red.", fig: { type: "setups", items: [{ label: "Start", icon: "beaker", lines: ["White carnation", "Red-coloured water", "Day 0"] }, { label: "After", icon: "beaker", lines: ["Petals turned red", "Water level lower", "Day 1"] }] } },
    { q: "Study the classification chart. A recycling centre sorts a steel can, a glass bottle, an aluminium can and a plastic bottle.\n(a) Which object ends at R? [1]\n(b) Explain why the glass bottle ends at Q. [2]", marks: 3, kw: [["aluminium", "aluminum"], ["not attracted", "not magnetic", "non-magnetic", "not a magnetic"], ["light"]], model: "(a) The aluminium can. (b) Glass is not attracted by a magnet, and it allows light to pass through.", fig: { type: "flow", root: "Recyclables", node: { q: "Attracted by a magnet?", yes: "P", no: { q: "Lets light through?", yes: "Q", no: { q: "Good heat conductor?", yes: "R", no: "S" } } } } },
    { q: "Hot kopi at 80 °C was poured into a metal cup and a Styrofoam cup of the same size. Study the table.\n(a) Which cup is better for keeping kopi hot? [1]\n(b) Explain your answer using the data. [2]", marks: 3, kw: [["styrofoam"], ["70", "higher"], ["poor conductor"]], model: "(a) The Styrofoam cup. (b) After 20 minutes, the kopi in the Styrofoam cup was at 70 °C, higher than 45 °C in the metal cup. Styrofoam is a poor conductor of heat, so the kopi lost heat to the surroundings more slowly.", tbl: [["Cup", "Temperature after 20 min (°C)"], ["Metal", "45"], ["Styrofoam", "70"]] },
    { q: "Study the set-ups. Two syringes each held 50 ml, one of air and one of water. Their nozzles were sealed and the plungers pushed hard.\n(a) In which syringe did the plunger move in? [1]\n(b) Explain why. [1]\n(c) Why did the other plunger not move? [1]", marks: 3, kw: [["air"], ["compress"], ["definite volume"]], model: "(a) The syringe of air. (b) Air is a gas and can be compressed. (c) Water is a liquid with a definite volume, so it cannot be compressed.", fig: { type: "setups", items: [{ label: "P", icon: "box", lines: ["50 ml of air", "Nozzle sealed", "Plunger pushed"] }, { label: "Q", icon: "box", lines: ["50 ml of water", "Nozzle sealed", "Plunger pushed"] }] } },
    { q: "Study the graph. Sheets of clear plastic, tracing paper and cardboard were placed in turn between a torch and a light sensor.\n(a) Which sheet forms the darkest shadow? [1]\n(b) Explain your answer. [1]\n(c) Explain why the clear plastic forms almost no shadow. [1]", marks: 3, kw: [["cardboard"], ["opaque", "blocks all", "no light", "0 lux", "reading of 0"], ["transparent", "most light", "most of the light"]], model: "(a) Cardboard. (b) Its reading was 0 lux, so it is opaque and blocks all the light. (c) Clear plastic is transparent and allows most light to pass through, so very little light is blocked.", fig: { type: "bar", title: "Light passing through sheets", xl: "Sheet", yl: "Light sensor reading (lux)", bars: [["Clear plastic", 880], ["Tracing paper", 390], ["Cardboard", 0]] } },
    { q: "A hibiscus plant and a boy both need food.\n(a) In which part does the hibiscus plant make its food? [1]\n(b) The boy cannot make his own food. Explain why he needs a digestive system. [2]", marks: 3, kw: [["leaves", "leaf"], ["break down", "broken down", "breaks down", "digest"], ["absorb"]], model: "(a) In its leaves. (b) His digestive system breaks down the food he eats into simpler substances, so that the digested food can be absorbed into his bloodstream and used by his body." },
    { q: "Kumar ran hot water over a tight metal lid on a glass jar, and it opened easily. After the lid cooled, it became tight again.\n(a) Explain why the lid became loose. [2]\n(b) Explain why it became tight again after cooling. [1]", marks: 3, kw: [["gain", "gains heat", "gained heat"], ["expand"], ["contract"]], model: "(a) The metal lid gained heat from the hot water and expanded, so it became looser. (b) As it cooled, the lid lost heat and contracted, so it fitted tightly again.", x: 1 },
    { q: "Nadia put 10 green bean seeds on moist cotton wool in each of three dishes at different temperatures. Study the table.\n(a) State the variable changed. [1]\n(b) At which temperature did the seeds germinate best? [1]\n(c) Apart from warmth, name one other condition seeds need to germinate. [1]\n(d) Why did she use 10 seeds in each dish instead of 1? [1]", marks: 4, kw: [["temperature"], ["25"], ["water", "air", "moist"], ["reliable"]], model: "(a) The temperature of the surroundings. (b) At 25 °C. (c) Water (or air). (d) To make the results more reliable.", tbl: [["Temperature (°C)", "Number of seeds germinated after 5 days"], ["5", "0"], ["25", "9"], ["35", "8"]], x: 1 }
  ],
  doc: [
    { q: "Why is the handle of a cooking pot made of plastic? [2]", marks: 2, answers: ["Plastic is a poor conductor of heat, so heat flows slowly to the hand and the hand does not get burnt.", "Plastic is strong and light.", "So it will not be hot."], best: 0, why: "Answer 1 gives the property (poor conductor of heat) and its effect on the hand. Answer 2 names the wrong property, and answer 3 is too vague with no keyword." },
    { q: "Explain why a dented ping pong ball pops back in hot water. [2]", marks: 2, answers: ["The ball expands in hot water.", "The hot water pushes the dent out.", "The air inside the ball gains heat and expands, pushing the dent out."], best: 2, why: "Answer 3 names what expands (the air inside) and says it gains heat. Answer 1 does not say the air gains heat and implies the plastic expands, and answer 2 is wrong: the water does not push the dent out." },
    { q: "Why is frosted glass used for bathroom windows? [2]", marks: 2, answers: ["It is translucent: it allows some light through, so the bathroom is bright, but people cannot see in clearly.", "It is transparent so light can pass through.", "It looks nice and is strong."], best: 0, why: "Answer 1 uses ‘translucent’ and gives both reasons: light and privacy. Answer 2 uses the wrong word (transparent), and answer 3 gives no light property." },
    { q: "What happens to digested food in the small intestine? [1]", marks: 1, answers: ["It is broken down.", "It is absorbed into the bloodstream.", "Water is taken out of it."], best: 1, why: "Answer 2 is the key idea: digested food is absorbed into the bloodstream. Answer 1 is only part of the story, and answer 3 describes the large intestine." },
    { q: "Why are gaps left between railway tracks? [2]", marks: 2, answers: ["Because the tracks are hot.", "The steel tracks gain heat and expand on hot days, and the gaps give them room so they do not bend.", "So that the tracks can contract."], best: 1, why: "Answer 2 has both ideas: gains heat and expands, with the gap giving room. Answer 1 has no expansion idea, and answer 3 gets it the wrong way round." }
  ]
};
