window.LBZ = window.LBZ || {};
LBZ["p4-mixed"] = {
  flash: [
    { f: "Define: matter", b: "Anything that has mass and occupies space." },
    { f: "What is the difference between heat and temperature?", b: "Heat is a form of energy that flows from a hotter place to a colder place until both are at the same temperature. Temperature is how hot or cold something is, measured in °C with a thermometer." },
    { f: "Name the magnetic materials.", b: "Iron, steel, nickel and cobalt. Other metals, such as aluminium and copper, are not attracted by magnets." },
    { f: "An object gains heat. State its possible effects.", b: "Its temperature may rise, it expands, and it may change state, e.g. a solid melts. (When it loses heat, its temperature may fall, it contracts, and it may change state.)" },
    { f: "Why does a metal spoon feel colder than a plastic spoon from the same drawer?", b: "Both are at the same temperature, but metal is a better conductor of heat. It conducts heat away from the hand faster, so the hand loses heat faster." },
    { f: "Good conductor vs poor conductor of heat", b: "A good conductor allows heat to flow through it easily (e.g. metals). A poor conductor allows heat to flow through it slowly (e.g. plastic, wood, Styrofoam, air)." },
    { f: "Solid, liquid, gas: shape and volume", b: "Solid: definite shape and definite volume. Liquid: no definite shape but a definite volume. Gas: no definite shape and no definite volume; it can be compressed." },
    { f: "Function of the stomach", b: "Food is mixed with digestive juices and partly digested (broken down into simpler substances)." },
    { f: "Function of the small intestine", b: "Digestive juices complete the digestion of food, and digested food is absorbed into the bloodstream." },
    { f: "Function of the large intestine", b: "Absorbs water from the undigested food." },
    { f: "Function of the stem", b: "Holds the plant upright, and carries water and mineral salts from the roots, and food from the leaves, to other parts of the plant." },
    { f: "Function of the roots", b: "Absorb water and mineral salts from the soil, and hold the plant firmly in the soil." },
    { f: "How is a shadow formed?", b: "Light travels in a straight line. An opaque object blocks the light, so a dark area (the shadow) forms on the side of the object away from the light source." },
    { f: "How do we see a book, which is not a light source?", b: "Light from a light source falls on the book and is reflected by the book into our eyes." },
    { f: "Transparent, translucent, opaque", b: "Transparent: allows most light to pass through. Translucent: allows some light to pass through. Opaque: does not allow light to pass through." }
  ],
  mcq: [
    { q: "Which item at a school canteen stall is the best conductor of heat?", o: ["Plastic tray", "Wooden chopsticks", "Steel ladle", "Paper cup"], a: 2, why: "Steel is a metal, and metals are good conductors of heat. Plastic, wood and paper are poor conductors of heat.", lvl: 1 },
    { q: "Study the diagram. Which part only moves food to the stomach and does NOT digest it?", o: ["A", "B", "C", "D"], a: 1, why: "B is the gullet, which only moves food from the mouth to the stomach. Food is digested in the mouth (A), stomach (C) and small intestine (D).", lvl: 1, fig: { type: "organs", system: "digestive", mark: { mouth: "A", gullet: "B", stomach: "C", small_intestine: "D" } } },
    { q: "Which property do solids, liquids and gases ALL have?", o: ["They have a definite shape", "They have a definite volume", "They have mass", "They cannot be compressed"], a: 2, why: "All matter has mass and occupies space. Only solids have a definite shape, gases have no definite volume, and gases can be compressed.", lvl: 1 },
    { q: "Study the diagram of a plant. Which part contains the seeds?", o: ["P", "Q", "R", "S"], a: 3, why: "S is the fruit, which develops from the flower and contains the seeds. P is the roots, Q the stem and R a leaf.", lvl: 1, fig: { type: "plant", mark: { roots: "P", stem: "Q", leaf: "R", fruit: "S" } } },

    { q: "At a hawker centre, ice is added to a cup of hot teh. Which describes what happens?", o: ["Heat flows from the teh to the ice, and the ice melts.", "Coldness flows from the ice to the teh, and the teh cools.", "Heat flows from the ice to the teh, and the ice melts.", "No heat flows, as the ice and the teh are in one cup."], a: 0, why: "Heat flows from the hotter teh to the colder ice. The ice gains heat and melts, and the teh loses heat and cools. There is no ‘coldness’ that flows.", lvl: 2 },
    { q: "A copper wire was heated, and its increase in length was measured at different temperatures. Study the graph. What is the most likely increase in length at 50 °C, and why does the wire get longer?", o: ["5 mm; it gains heat and expands", "3 mm; it loses heat and contracts", "5 mm; it gains heat and its mass increases", "3 mm; it gains heat and expands"], a: 3, why: "The length increases by 2 mm for every 20 °C, so at 50 °C (halfway between 40 °C and 60 °C) it is about 3 mm. The wire gains heat and expands; its mass does not change.", lvl: 2, fig: { type: "line", title: "Heating a copper wire", xl: "Temperature (°C)", yl: "Increase in length (mm)", pts: [["20", 0], ["40", 2], ["60", 4], ["80", 6]] } },
    { q: "Which of these is NOT a function of the stem of a plant?", o: ["Holding the plant upright", "Carrying water to the leaves", "Absorbing water from the soil", "Carrying food to the roots"], a: 2, why: "The roots absorb water from the soil. The stem holds the plant upright and carries water to the leaves and food to other parts, including the roots.", lvl: 2 },
    { q: "Study the set-ups. Jun wants to find out if the distance between a toy and a torch affects the height of the toy’s shadow on a screen. Which two set-ups should he compare?", o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ only in the distance between the toy and the torch; the toy and the screen distance are the same. Each other pair changes more than one variable, so it is not a fair test.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Toy car", "Toy 10 cm from torch", "Screen 50 cm from torch"] }, { label: "B", icon: "box", lines: ["Toy car", "Toy 20 cm from torch", "Screen 50 cm from torch"] }, { label: "C", icon: "box", lines: ["Toy car", "Toy 20 cm from torch", "Screen 60 cm from torch"] }, { label: "D", icon: "box", lines: ["Toy robot", "Toy 10 cm from torch", "Screen 60 cm from torch"] }] } },
    { q: "The Flower Dome at Gardens by the Bay has a glass roof so that the plants inside get enough light. Which property of glass makes it suitable for this?", o: ["It is opaque and blocks most of the light.", "It is a poor conductor, so heat flows through slowly.", "It is strong and does not break easily.", "It is transparent and allows most light through."], a: 3, why: "Clear glass is transparent, so it allows most light to pass through to the plants. Glass is a poor conductor of heat, but that is not why it lets the plants get light.", lvl: 2 },
    { q: "Study the table. Which correctly identifies substances W, X and Y?", o: ["W: marble, X: cooking oil, Y: air", "W: cooking oil, X: marble, Y: air", "W: air, X: cooking oil, Y: marble", "W: marble, X: air, Y: cooking oil"], a: 0, why: "W has a definite shape and volume, so it is a solid (marble). X has a definite volume but no definite shape, so it is a liquid (cooking oil). Y has neither and can be compressed, so it is a gas (air).", lvl: 2, tbl: [["Substance", "Definite shape?", "Definite volume?", "Can be compressed?"], ["W", "Yes", "Yes", "No"], ["X", "No", "Yes", "No"], ["Y", "No", "No", "Yes"]] },
    { q: "Hana stretched a balloon over the mouth of an empty glass bottle and stood the bottle in a basin of hot water. What is most likely to happen?", o: ["The balloon is pulled in, as the air in the bottle gains heat and contracts.", "The balloon inflates, as hot water enters the bottle and pushes the air out.", "Nothing happens, as air has no mass and cannot gain heat.", "The balloon inflates, as the air in the bottle gains heat and expands."], a: 3, why: "The air in the bottle gains heat from the hot water and expands, so it pushes into the balloon and inflates it. Water cannot enter the sealed bottle, and air is matter that can gain heat.", lvl: 2 },

    { q: "Study the classification chart. Which correctly places a shadow, a lit candle and a steel key?", o: ["A: shadow, B: lit candle, C: steel key", "A: lit candle, B: shadow, C: steel key", "A: shadow, B: steel key, C: lit candle", "D: shadow, B: lit candle, C: steel key"], a: 0, why: "A shadow has no mass and does not occupy space, so it is not matter (A). A lit candle is matter and gives out its own light (B). A steel key is matter, gives out no light and is attracted by a magnet (C).", lvl: 3, fig: { type: "flow", root: "Things", node: { q: "Is it matter?", yes: { q: "Gives out its own light?", yes: "B", no: { q: "Attracted by a magnet?", yes: "C", no: "D" } }, no: "A" } } },
    { q: "Three identical marbles were lowered into a measuring cylinder of water. Study the table. What is the volume of ONE marble, and what does the rise in the water level show?", o: ["12 ml; the marbles occupy space", "4 ml; the marbles occupy space", "4 ml; the marbles have mass", "12 ml; the marbles have mass"], a: 1, why: "The water level rose by 52 − 40 = 12 ml for three marbles, so one marble is 12 ÷ 3 = 4 ml. The water rose because the marbles occupy space and pushed the water up, not because they have mass.", lvl: 3, tbl: [["Measuring cylinder", "Water level (ml)"], ["Water only", "40"], ["After adding 3 identical marbles", "52"]] },
    { q: "During a power cut at night, Siti could not see the words in her book in her HDB bedroom. When the lights came back on, she could read them. Which statements explain this?\nA: Light from the lamp is reflected by the book into her eyes.\nB: The book gives out its own light when the lamp is on.\nC: In the dark, no light is reflected from the book to her eyes.", o: ["A only", "A and B only", "A and C only", "B and C only"], a: 2, why: "We see a book when light from a light source is reflected by it into our eyes (A). In the dark there is no light to reflect, so she cannot see the words (C). A book is not a light source, so B is wrong.", lvl: 3 },
    { q: "An ice kacang stall owner wants to find out if the THICKNESS of a bowl affects how long the ice in it lasts. Study the table. Which two bowls should be compared?", o: ["Q and R", "Q and S", "P and R", "P and Q"], a: 3, why: "P and Q differ only in thickness; the material and the mass of ice are the same. Q and R differ in material, Q and S in mass of ice, and P and R in both material and thickness.", lvl: 3, tbl: [["Bowl", "Material", "Thickness (mm)", "Mass of ice (g)"], ["P", "Plastic", "2", "200"], ["Q", "Plastic", "4", "200"], ["R", "Melamine", "4", "200"], ["S", "Plastic", "4", "300"]] },
    { q: "Study the diagram. Ming ate some fried bee hoon. In which part is the digestion of the food completed, and in which part is water absorbed from the undigested food?", o: ["W; X", "X; Y", "Y; Z", "X; W"], a: 1, why: "Digestion is completed in the small intestine (X), where digested food is absorbed into the bloodstream. The large intestine (Y) absorbs water from the undigested food. W is the stomach and Z the anus.", lvl: 3, fig: { type: "organs", system: "digestive", mark: { stomach: "W", small_intestine: "X", large_intestine: "Y", anus: "Z" } } },
    { q: "Ali shone a torch at a clear glass of water and then at an identical clear glass of milk. Which best describes their shadows on the wall?", o: ["The glass of water forms a darker shadow, as water blocks more light.", "Both shadows are equally dark, as both glasses are made of clear glass.", "The glass of milk forms a darker shadow, as milk blocks more light.", "Neither forms a shadow, as glass and liquids allow all light to pass through."], a: 2, why: "Clear glass and water are transparent and allow most light through, so the glass of water forms only a very faint shadow. Milk blocks much more light, so its shadow is darker.", lvl: 3 },

    { q: "Hot soup at 90 °C was poured into containers of the same size and thickness made of materials W, X, Y and Z, in a room at 25 °C. The temperature of the OUTER surface of each container was measured after 5 minutes. Study the graph. Which material is best for keeping soup hot for the longest time, and which is best for the base of a frying pan?", o: ["Y; Z", "Z; Y", "W; X", "X; W"], a: 1, why: "The best conductor lets heat flow from the soup to its outer surface fastest, so Y (70 °C) is the best conductor and suits a frying pan base. Z (26 °C) conducts heat most slowly, so the soup loses heat slowest in Z. Choosing the hottest surface for keeping soup hot is the trap.", lvl: 4, fig: { type: "bar", title: "Outer surface temperature after 5 min", xl: "Material of container", yl: "Temperature (°C)", bars: [["W", 55], ["X", 30], ["Y", 70], ["Z", 26]] } },
    { q: "Study the set-ups. The nozzles of both syringes were sealed, and both plungers were pushed in hard. Which statements are correct?\nA: In syringe Q, only the air is compressed.\nB: The water in Q can be compressed if the push is hard enough.\nC: The mass of the air in P stays the same as it is compressed.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "Gases can be compressed but liquids cannot, so in Q only the 20 ml of air is squeezed into a smaller space (A true, B false). Compressing air changes its volume, not its mass, because no air escapes from the sealed syringe (C true).", lvl: 4, fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["Syringe P", "40 ml of air", "Nozzle sealed"] }, { label: "Q", icon: "jar", lines: ["Syringe Q", "20 ml water + 20 ml air", "Nozzle sealed"] }] } },
    { q: "Two identical ice cubes from the same freezer were put on a steel tray and on a wooden tray of the same size and thickness, in the same room at 30 °C. Which is most likely to happen?", o: ["The ice on the steel tray melts first, as steel conducts heat from the surroundings to the ice faster.", "The ice on the wooden tray melts first, as wood keeps the ice warmer than steel does.", "The ice on the steel tray melts last, as the coldness of the steel keeps the ice frozen.", "Both melt at the same time, as both trays start at the same room temperature."], a: 0, why: "Both trays start at 30 °C, but steel is a good conductor of heat, so heat flows through it to the ice faster and the ice melts first. Wood is a poor conductor, so the ice on it gains heat more slowly. Steel does not give out ‘coldness’.", lvl: 4 }
  ],
  oe: [
    { q: "Study the table, which shows the properties of four materials P, Q, R and S.\n(a) Which material could be steel? Explain using the table. [2]\n(b) Which material is most suitable for the window of an oven door, so that the cook can see the food? [1]\n(c) Explain why R is more suitable than S for the handle of a frying pan. [1]", marks: 4, kw: [["p"], ["attract", "magnetic"], ["q"], ["poor conductor", "conducts heat poorly", "poorer conductor", "conducts heat slowly"]], model: "(a) P. Steel is a magnetic material, and P is the only material that is attracted by a magnet. (b) Q, because it allows most light to pass through. (c) R is a poor conductor of heat, so heat from the hot pan flows through it to the hand slowly, while S is a good conductor of heat.", tbl: [["Material", "Attracted by a magnet?", "Light that passes through", "How well it conducts heat"], ["P", "Yes", "None", "Good"], ["Q", "No", "Most", "Poor"], ["R", "No", "None", "Poor"], ["S", "No", "None", "Good"]] },
    { q: "Ming lined up three cards, A, B and C, each with a small hole in the middle, between his eye and a lit bulb. He could see the bulb only when the three holes were in a straight line.\n(a) What does this show about light? [1]\n(b) Ming moved card B slightly to one side and could no longer see the bulb. Explain why. [2]\n(c) He then replaced card B with a sheet of clear plastic with no hole. Could he see the bulb? Explain. [1]", marks: 4, kw: [["straight"], ["opaque"], ["block", "stop"], ["transparent", "most light"]], model: "(a) Light travels in a straight line. (b) Card B is opaque, so it blocks the light from the bulb, and the light from the bulb cannot travel in a straight line to his eye. (c) Yes. Clear plastic is transparent, so it allows most light to pass through to his eye.", x: 1 },
    { q: "A metal bench and a wooden bench in a playground had been in the hot afternoon sun for hours, and both were at 45 °C. Sara’s hand was at 36 °C. When she touched the metal bench, it felt much hotter than the wooden bench.\n(a) In which direction did heat flow when she touched the metal bench? [1]\n(b) Explain why the metal bench felt hotter than the wooden bench, although both were at the same temperature. [2]", marks: 3, kw: [["bench to", "from the bench", "from the metal", "to her hand", "to the hand", "into her hand"], ["good conductor", "better conductor", "conducts heat well", "conducts heat better"], ["faster", "more quickly", "quicker"]], model: "(a) Heat flowed from the metal bench to her hand, because the bench was hotter than her hand. (b) Metal is a better conductor of heat than wood, so the metal bench conducted heat to her hand faster. Her hand gained heat faster, so the metal bench felt hotter." },
    { q: "Dinesh recorded the shadow of a lamp post in an HDB carpark on a sunny day. Study the table.\n(a) In which direction was the Sun at 9 am? Explain your answer. [2]\n(b) Why was the shadow shortest at 12 pm? [1]\n(c) Predict how the length of the shadow at 5 pm would compare with its length at 3 pm. [1]", marks: 4, kw: [["east"], ["opposite", "away from", "other side", "block"], ["highest", "overhead", "high in the sky", "above"], ["longer", "more than 6"]], model: "(a) In the east. The opaque lamp post blocks the sunlight, so its shadow forms on the side away from the Sun; the shadow pointed west, so the Sun was in the east. (b) At 12 pm the Sun was highest in the sky, almost overhead. (c) The shadow at 5 pm would be longer than 6 m, as the Sun would be lower in the sky.", tbl: [["Time", "Length of shadow (m)", "Direction the shadow points"], ["9 am", "6", "West"], ["12 pm", "1", "Almost none"], ["3 pm", "6", "East"]] }
  ],
  tf: [
    { s: "An object that is a good conductor of heat must also be attracted by a magnet.", a: false, why: "Copper and aluminium are good conductors of heat but are not attracted by magnets. Only iron, steel, nickel and cobalt are magnetic." },
    { s: "Light travels in a straight line.", a: true, why: "Because light travels in a straight line, it cannot bend around an opaque object, so a shadow forms behind the object." },
    { s: "A shadow forms because light bends around an opaque object.", a: false, why: "Light travels in a straight line and does not bend around the object. The opaque object blocks the light, so a shadow forms behind it." },
    { s: "A steel nail is attracted by a magnet and is also a good conductor of heat.", a: true, why: "Steel is a magnetic material, and like other metals it is a good conductor of heat." },
    { s: "A seed needs light to germinate.", a: false, why: "A seed needs water, air and warmth to germinate. Seeds can germinate in the dark, using food stored inside them." },
    { s: "Undigested food leaves the body through the anus.", a: true, why: "After the large intestine absorbs water from the undigested food, it leaves the body through the anus." },
    { s: "Roots take in food from the soil.", a: false, why: "Roots absorb water and mineral salts, which are not food. The plant makes its own food in its leaves, and the stem carries the food to the roots." },
    { s: "A liquid takes the shape of the part of the container it fills.", a: true, why: "A liquid has no definite shape, so it takes the shape of its container, but its volume stays the same." },
    { s: "When an ice cube melts into water, its mass decreases.", a: false, why: "Melting is a change of state caused by gaining heat. The mass of the water is the same as the mass of the ice." },
    { s: "Glass is a poor conductor of heat.", a: true, why: "Glass lets heat flow through it slowly, which is why a glass rod heated at one end stays cool at the other end for a long time." }
  ],
  sort: [
    { title: "Sort these into solids, liquids and gases.", groups: ["Solid", "Liquid", "Gas"], items: [["Sand", 0], ["Cooking oil", 1], ["Steam", 2], ["Air in a bicycle tyre", 2], ["Sugar", 0], ["Honey", 1], ["Ice cube", 0], ["Milk", 1], ["Bubbles of gas in a fizzy drink", 2], ["Wooden chopsticks", 0]] }
  ]
};
