window.LBY = window.LBY || {};
LBY["p4-mixed"] = {
  lessons: [
    {
      h: "Planning a fair test: aim and variables",
      concept: "Booklet B often asks for the aim, the variable changed, the variable measured and why other things are kept the same. Write the aim as ‘To find out if (or how) [changed variable] affects [measured variable].’ The changed variable is the ONE thing that is different between the set-ups; the measured variable is the result you record; every other variable is kept the same so that any difference in results is due only to the changed variable. That is what makes it a fair test.",
      example: {
        q: "Study the set-ups. Wei poured 200 ml of water at 80 °C into cups of the same size made of different materials. He measured the temperature of the water after 20 minutes.\n(a) State the aim of his experiment. [1]\n(b) State the variable he changed and the variable he measured. [2]\n(c) Why must the volume of water be the same in each cup? [1]",
        fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["Metal cup", "200 ml water, 80 °C", "Temp after 20 min: ?"] }, { label: "B", icon: "pot", lines: ["Plastic cup", "200 ml water, 80 °C", "Temp after 20 min: ?"] }, { label: "C", icon: "pot", lines: ["Styrofoam cup", "200 ml water, 80 °C", "Temp after 20 min: ?"] }] },
        marks: 4,
        think: [
          "Step 1: What is different between A, B and C? Only the material of the cup, so that is the changed variable.",
          "Step 2: What does Wei record? The temperature of the water after 20 minutes: the measured variable.",
          "Step 3: Build the aim from the two: ‘how the material of the cup affects how fast the hot water loses heat’.",
          "Step 4: Kept-the-same answers must say WHY: so that only the changed variable affects the result (a fair test)."
        ],
        answer: "(a) To find out if the material of a cup affects how fast the hot water in it loses heat. (b) Changed: the material of the cup. Measured: the temperature of the water after 20 minutes. (c) So that it is a fair test: only the material of the cup is different, so any difference in temperature is due to the material alone."
      },
      tip: "Aim = ‘how [changed] affects [measured]’. Keep everything else the same, and say it makes the test fair.",
      try: {
        q: "Hui Min wants to find out how the number of sheets of tracing paper affects the amount of light that passes through. Which must she keep the same?",
        o: ["The number of sheets of tracing paper", "The distance from the torch to the sensor", "The reading shown on the light sensor", "The amount of light passing through"],
        a: 1,
        why: "The number of sheets is the changed variable, and the sensor reading (the amount of light passing through) is the measured variable. The distance from the torch to the sensor must be kept the same for a fair test."
      }
    }
  ],
  mcq: [
    { q: "Study the diagram. Two bar magnets are placed end to end on a table. What happens when the facing ends are brought close together?", o: ["They attract each other", "They repel each other", "Nothing happens at all", "They attract, then repel"], a: 1, why: "The right end of A is S and the left end of B is also S. Like poles repel.", lvl: 1, fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "SN" }], between: ["?"] } },
    { q: "Study the diagram. Through which part does undigested food leave the body?", o: ["A", "B", "C", "D"], a: 3, why: "D is the anus, through which undigested food leaves the body. C, the large intestine, absorbs water from it first.", lvl: 1, fig: { type: "organs", system: "digestive", mark: { stomach: "A", small_intestine: "B", large_intestine: "C", anus: "D" } } },
    { q: "Which property does a gas have that a liquid does NOT have?", o: ["It has mass", "It occupies space", "It can be compressed", "It has a definite volume"], a: 2, why: "A gas can be compressed; a liquid cannot. Both have mass and occupy space, and only the liquid has a definite volume.", lvl: 1 },

    { q: "Siti weighed a flat basketball, pumped air into it and weighed it again. Study the table. What does this show?", o: ["Air has mass and was added to the ball.", "Air has no mass but occupies space.", "The rubber gained mass as it stretched.", "Air has a definite shape and volume."], a: 0, why: "Misconception: air has no mass. The mass rose by 5 g because air was pumped in, and air, like all matter, has mass. The rubber itself did not gain any mass.", lvl: 2, tbl: [["Basketball", "Mass (g)"], ["Flat", "600"], ["After pumping in air", "605"]] },
    { q: "Study the diagram. Food made in the leaves is needed by the roots. Which part carries this food to the roots?", o: ["A", "B", "C", "D"], a: 3, why: "D, the stem, carries food made in the leaves (A) to other parts, including the roots (C) and fruits (B). Misconception: roots do not take in food from the soil; they absorb water and mineral salts.", lvl: 2, fig: { type: "plant", mark: { leaf: "A", fruit: "B", roots: "C", stem: "D" } } },
    { q: "A cardboard cone is held between a torch and a screen, with its pointed tip facing the torch and its round base facing the screen. What is the shape of its shadow?", o: ["A triangle", "A square", "A circle", "A semicircle"], a: 2, why: "Light travels in straight lines, so the shadow has the outline of the cone as seen from the torch. From the tip end, the cone’s outline is its round base, so the shadow is a circle.", lvl: 2 },
    { q: "Study the Venn diagram. Which of these belongs in the region marked ‘?’?", o: ["A mirror", "The Moon", "Sunlight", "A lit candle"], a: 3, why: "A lit candle is matter and gives out its own light. Misconception: the Moon only reflects sunlight, so it is matter but not a light source. A mirror only reflects light, and sunlight is light, which is not matter.", lvl: 2, fig: { type: "venn", a: "Matter", b: "Gives out its own light", onlyA: ["rock", "water"], both: ["?"], onlyB: [], neither: ["shadow"] } },
    { q: "Study the set-ups. Jia Hui timed how long each ice cube took to melt completely. Which variable did she change?", o: ["The mass of the ice cube", "The material of the wrapping", "The temperature of the room", "The time taken for ice to melt"], a: 1, why: "Only the wrapping material (cloth or foil) is different. The mass of ice and room temperature are kept the same, and the time taken to melt is what she measured.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["20 g ice cube", "Wrapped in cloth", "Room at 25 °C"] }, { label: "B", icon: "plate", lines: ["20 g ice cube", "Wrapped in foil", "Room at 25 °C"] }] } },
    { q: "Study the classification chart. Which of these belongs at C?", o: ["Mushroom", "Fern", "Moss", "Grasshopper"], a: 3, why: "A grasshopper cannot make its own food and does not reproduce by spores, so it ends at C. The fern and moss make their own food (A); the mushroom reproduces by spores (B).", lvl: 2, fig: { type: "flow", root: "Living things", node: { q: "Makes its own food?", yes: "A", no: { q: "Reproduces by spores?", yes: "B", no: "C" } } } },

    { q: "Rods of the same length and thickness, with pins stuck along them using wax, were heated at one end. Study the graph. Which statements are supported?\nA: Copper conducts heat faster than iron.\nB: Glass and wood are poor conductors of heat.\nC: Wood is a poorer conductor of heat than glass.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Copper dropped more pins (8) than iron (4), so A is supported; glass and wood dropped none, so B is supported. Both dropped 0 pins, so the results cannot show which of them is poorer: C is not supported.", lvl: 3, fig: { type: "bar", title: "Pins dropped after 2 minutes", xl: "Rod", yl: "Number of pins dropped", bars: [["Copper", 8], ["Iron", 4], ["Glass", 0], ["Wood", 0]] } },
    { q: "Study the diagram. Three ring magnets are on a wooden rod. The top face of A is a north pole. B floats above A, and C rests on B, touching it. What poles are on the top faces of B and C?", o: ["B: S, C: S", "B: N, C: S", "B: S, C: N", "B: N, C: N"], a: 0, why: "B floats, so its bottom face must be N to repel A’s top N; its top face is S. C touches B, so C’s bottom face is N (unlike poles attract), and its top face is S.", lvl: 3, fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, false] } },
    { q: "In a room lit by a lamp, Sara sees her friend’s face in a mirror. Which statements are correct?\nA: The mirror reflects light.\nB: Her friend’s face gives out its own light.\nC: Light from the lamp is reflected by her friend’s face, then by the mirror, into Sara’s eyes.", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 2, why: "Misconception: we see things because they give out light. The face is not a light source; it reflects light from the lamp, which the mirror reflects again into Sara’s eyes. So A and C are correct.", lvl: 3 },
    { q: "A bowl of hot soup was placed in a basin of water. Study the table. Which statements are correct?\nA: The soup lost heat to the water.\nB: The water gained heat, so its temperature rose.\nC: At 15 minutes, the soup and the water had the same amount of heat.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "Heat flowed from the hotter soup to the colder water until both were at 45 °C. Misconception: same temperature means same amount of heat. They only reached the same temperature; the amount of heat also depends on how much soup and water there is.", lvl: 3, tbl: [["Time (min)", "0", "5", "10", "15"], ["Soup (°C)", "80", "60", "50", "45"], ["Water in basin (°C)", "25", "35", "40", "45"]] },
    { q: "A leafy shoot was placed in a measuring cylinder of water, and a layer of oil was poured onto the water surface to stop evaporation. Study the graph. Which is the best explanation for the change?", o: ["Water evaporated from the surface in the cylinder.", "Water was turned into food by the stem and stored.", "Water was taken in by the shoot and carried up its stem.", "Water was absorbed into the layer of oil on its surface."], a: 2, why: "The oil stops water evaporating from the cylinder, so the water was taken in by the shoot and carried up the stem to the leaves. The stem carries water; it does not make food.", lvl: 3, fig: { type: "line", title: "Water in a cylinder with a leafy shoot", xl: "Day", yl: "Volume of water (ml)", pts: [["0", 100], ["1", 92], ["2", 84], ["3", 76], ["4", 68]] } },
    { q: "Ben ate a slice of bread. Which statements about the bread are correct?\nA: It is partly broken down in the mouth by saliva.\nB: Digested food from it is absorbed into the bloodstream in the stomach.\nC: Water is absorbed from its undigested remains in the large intestine.\nD: It passes through the gullet without being digested.", o: ["A and C only", "B and D only", "A, C and D only", "A, B, C and D"], a: 2, why: "Saliva starts digestion in the mouth (A), the gullet only moves food (D), and the large intestine absorbs water (C). Digested food is absorbed in the small intestine, not the stomach, so B is wrong.", lvl: 3 },
    { q: "Overhead cables between poles are hung slightly loose instead of being pulled tight. Why?", o: ["On cold days, cables lose heat and contract, so tight cables could snap.", "On hot days, cables lose heat and expand, so tight cables could snap.", "On cold days, cables gain heat and contract, so loose cables are safer.", "On hot days, cables gain heat and contract, so they need extra length."], a: 0, why: "When a cable loses heat it contracts and becomes shorter. A cable that is already tight could be pulled until it snaps. The other options pair heat gain or loss with the wrong change in size.", lvl: 3 },

    { q: "Study the table. A copper rod is stuck tightly inside a steel ring. Which action is most likely to loosen it?", o: ["Heat both the rod and the ring", "Cool both the rod and the ring", "Heat only the copper rod", "Cool only the steel ring"], a: 1, why: "Copper expands and contracts more than steel for the same temperature change. Cooling both makes the rod shrink more than the ring’s hole, so it loosens. Heating both, heating the rod alone or cooling the ring alone all make the fit tighter.", lvl: 4, tbl: [["Metal", "Increase in length of a 1 m rod heated from 25 °C to 100 °C"], ["Copper", "1.3 mm"], ["Steel", "0.9 mm"]] },
    { q: "Sheets of tracing paper were stacked in front of a torch, and a light sensor measured the light passing through. Study the graph. What is most likely when 4 sheets are used?", o: ["About 50 lux, and the shadow is darker than with 3 sheets", "0 lux, and the sheets now form a completely dark shadow", "About 100 lux, and the shadow is as dark as with 3 sheets", "About 50 lux, and the shadow is lighter than with 3 sheets"], a: 0, why: "Each extra sheet halves the reading (800, 400, 200, 100), so 4 sheets give about 50 lux. Less light passes through, so the shadow is darker. Translucent sheets still let some light through, so the reading is not yet 0.", lvl: 4, fig: { type: "bar", title: "Light reaching the sensor", xl: "Sheets of tracing paper", yl: "Light sensor reading (lux)", bars: [["0 sheets", 800], ["1 sheet", 400], ["2 sheets", 200], ["3 sheets", 100]] } },
    { q: "Rice grains store food for the rice plant. Where was this food made, and where is the digested food from the rice absorbed into Dinesh’s bloodstream after he eats it?", o: ["Roots; small intestine", "Leaves; stomach", "Grains; large intestine", "Leaves; small intestine"], a: 3, why: "Leaves make food, and the stem carries it to the grains to be stored. In Dinesh, digested food is absorbed into the bloodstream in the small intestine, not the stomach or large intestine. Roots absorb water and mineral salts, not food.", lvl: 4 },
    { q: "Cups of the same size were filled with ice and left in the same room. Study the table. Which conclusions can be drawn from fair comparisons?\nA: A thicker Styrofoam wall keeps ice longer.\nB: Styrofoam is a poorer conductor of heat than plastic.\nC: A thinner plastic wall keeps ice longer than a thicker one.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "P and Q differ only in thickness, so A is fair. Q and R differ only in material, and the Styrofoam kept ice longer, so B is fair. R and S differ in thickness AND mass of ice, so C cannot be concluded.", lvl: 4, tbl: [["Cup", "Material", "Wall thickness (mm)", "Mass of ice (g)", "Time to melt (min)"], ["P", "Styrofoam", "2", "50", "60"], ["Q", "Styrofoam", "4", "50", "95"], ["R", "Plastic", "4", "50", "70"], ["S", "Plastic", "2", "80", "85"]] }
  ],
  tf: [
    { s: "The Moon is a light source because it shines brightly at night.", a: false, why: "The Moon only reflects light from the Sun; it does not give out its own light." },
    { s: "A liquid keeps the same volume when it is poured into a container of a different shape.", a: true, why: "A liquid has a definite volume; only its shape changes to fit the container." },
    { s: "Food made in the leaves is carried by the stem to other parts of the plant, including the roots.", a: true, why: "The stem carries food from the leaves to all other parts of the plant." },
    { s: "Two objects at the same temperature always contain the same amount of heat.", a: false, why: "Temperature is how hot something is; a pail of warm water has more heat than a cup of water at the same temperature." },
    { s: "Saliva begins the digestion of food in the mouth.", a: true, why: "Saliva is a digestive juice that starts breaking down food into simpler substances." },
    { s: "Using a brighter torch makes the shadow of an object bigger.", a: false, why: "Shadow size depends on the distances between the light source, object and screen, not on how bright the torch is." },
    { s: "A gas spreads out to fill the whole of any closed container it is in.", a: true, why: "A gas has no definite shape or volume, so it takes the shape and volume of its container." },
    { s: "The stomach is the only organ where digestion takes place.", a: false, why: "Food is also digested in the mouth and the small intestine, where digestion is completed." },
    { s: "Bread mould gets its food from the bread it grows on.", a: true, why: "Mould is a fungus; it cannot make its own food, so it feeds on the bread." },
    { s: "A very bright light can pass through an opaque object.", a: false, why: "An opaque object does not allow any light to pass through, however bright the light is." }
  ],
  oe: [
    { q: "Jia Hui wrapped identical ice cubes in different numbers of layers of the same cloth and timed how long each took to melt completely in the same room. Study the graph.\n(a) State the variable she changed. [1]\n(b) Describe the relationship shown in the graph. [1]\n(c) Explain why the ice lasts longer when more layers are used. [2]", marks: 4, kw: [["number of layers", "how many layers"], ["more layers", "the more"], ["poor conductor"], ["slowly", "slower", "more slowly"]], model: "(a) The number of layers of cloth. (b) The more layers of cloth used, the longer the ice took to melt completely. (c) Cloth is a poor conductor of heat, so more layers slow down the flow of heat even more. Heat from the surroundings is conducted to the ice more slowly, so the ice gains heat slowly and melts more slowly.", fig: { type: "line", title: "Ice wrapped in cloth", xl: "Number of layers of cloth", yl: "Time to melt (min)", pts: [["0", 20], ["1", 35], ["2", 48], ["3", 58], ["4", 66]] }, x: 1 },
    { q: "Study the set-ups. A stone was lowered into a measuring cylinder containing 50 ml of water, and the water level rose to 65 ml.\n(a) What is the volume of the stone? [1]\n(b) Explain why the water level rose. [1]\n(c) The stone was taken out and broken into small pieces, and all the pieces were put into 50 ml of water. Predict the new reading and explain your answer. [2]", marks: 4, kw: [["15"], ["occupies space", "occupy space", "takes up space", "take up space"], ["65"], ["same volume", "definite volume"]], model: "(a) 15 ml. (b) The stone occupies space, so it pushed the water up the cylinder. (c) 65 ml. Breaking the stone into pieces does not change the amount of stone, so all the pieces together still have the same volume of 15 ml.", fig: { type: "setups", items: [{ label: "Before", icon: "beaker", lines: ["Measuring cylinder", "50 ml of water"] }, { label: "After", icon: "beaker", lines: ["Stone lowered in", "Reading: 65 ml"] }] } },
    { q: "A flask of coloured water fitted with a glass tube was placed in water baths at different temperatures. The height of the coloured water in the tube was measured each time. Study the table.\n(a) Describe how the height of the coloured water changes as the temperature of the water bath increases. [1]\n(b) Explain this change. [2]\n(c) Predict the height of the coloured water at 60 °C. [1]", marks: 4, kw: [["increase", "higher", "rise", "taller"], ["gain"], ["expand"], ["9.5", "9.5cm", "between 8"]], model: "(a) As the temperature of the water bath increases, the height of the coloured water increases. (b) The coloured water gains heat from the water bath and expands, so it rises up the tube. (c) About 9.5 cm, between 8 cm and 11 cm.", tbl: [["Temperature of water bath (°C)", "Height of coloured water (cm)"], ["30", "5"], ["50", "8"], ["70", "11"], ["90", "14"]] },
    { q: "Study the set-ups. Three identical slices of bread were left for 5 days, and the results were recorded.\n(a) Which two set-ups show that mould needs water to grow? [1]\n(b) What can be concluded from set-ups A and C? [1]\n(c) Bread mould cannot make its own food. How does it get its food? [1]\n(d) Based on these results, suggest one way to keep bread from turning mouldy quickly. [1]", marks: 4, kw: [["a and b", "b and a"], ["warm", "higher temperature", "cold", "low temperature", "lower temperature"], ["from the bread", "feeds on", "feeding on", "gets food from", "gets its food from"], ["keep it dry", "keep the bread dry", "dry place", "in the fridge", "in a fridge", "in the refrigerator", "in a refrigerator", "cool place"]], model: "(a) Set-ups A and B. (b) Mould grows faster in warm conditions than in cold conditions. (c) It feeds on the bread it grows on, getting its food from the bread. (d) Keep the bread dry, or keep it in a refrigerator.", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Moist bread", "Cupboard, 30 °C", "Much mould"] }, { label: "B", icon: "plate", lines: ["Dry bread", "Cupboard, 30 °C", "No mould"] }, { label: "C", icon: "plate", lines: ["Moist bread", "Refrigerator, 5 °C", "Little mould"] }] }, x: 1 },
    { q: "Ravi pumped up his bicycle tyres until they were very hard, then left the bicycle in the hot sun.\n(a) The air in the tyre is matter. Explain why. [1]\n(b) Explain why a very hard tyre may burst after some time in the hot sun. [2]\n(c) Does the mass of the air inside the tyre change as it becomes hotter? Explain. [1]", marks: 4, kw: [["has mass", "occupies space", "takes up space"], ["gain"], ["expand"], ["same", "unchanged", "not change", "doesn't change", "no air"]], model: "(a) It has mass and occupies space. (b) The air inside the tyre gains heat from the hot surroundings and expands. The tyre is already very hard, so the expanding air pushes on it until it may burst. (c) No. The mass of the air stays the same because no air enters or leaves the tyre." },
    { q: "Study the diagram. Three ring magnets A, B and C are placed on a wooden rod. B floats above A, and C floats above B. The top face of A is a north pole.\n(a) Which pole is on the top face of B? [1]\n(b) Explain why B floats above A. [1]\n(c) C is taken off, turned upside down and put back on the rod. Predict what will happen to C. [1]", marks: 3, kw: [["south", "s"], ["repel"], ["attract", "touch", "stick", "rest on"]], model: "(a) S (south pole). (b) The bottom face of B is a north pole, facing the north pole on top of A. Like poles repel, so B is pushed up and floats. (c) C will be attracted to B and move down to touch it, because unlike poles now face each other.", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }], gaps: [true, true] } }
  ],
  doc: [
    { q: "Kumar placed a toy at different distances from a torch and measured the height of its shadow on a screen each time. State the aim of his experiment. [1]", marks: 1, answers: ["To see how big the shadow of the toy is.", "To find out if the distance between the toy and the torch affects the height of its shadow.", "To find out which distance is the best one."], best: 1, why: "Answer 2 names both the changed variable (distance between the toy and the torch) and the measured variable (height of the shadow). Answer 1 names only what is measured, and answer 3 is too vague: it names no variables at all." },
    { q: "Why does bread kept in a refrigerator stay free of mould for longer than bread kept in a warm cupboard? [2]", marks: 2, answers: ["The refrigerator kills all the mould.", "Because it is cold.", "Mould grows best in warm conditions, so the low temperature in the refrigerator slows down its growth."], best: 2, why: "Answer 3 gives both ideas: mould grows best when warm, and the low temperature slows its growth. Answer 1 is wrong (the cold slows mould, it does not kill it), and answer 2 is too vague: it does not say what the cold does to the mould." }
  ]
};
