window.LBU = window.LBU || {};
LBU["p4-mixed"] = {
  glossary: [
    { t: "Mass", d: "The amount of matter in an object. It is measured in grams (g) or kilograms (kg) using a balance, and it stays the same when the object changes shape or state." },
    { t: "Volume", d: "The amount of space that matter occupies. It is measured in millilitres (ml), litres (l) or cubic centimetres (cm³), e.g. using a measuring cylinder." },
    { t: "Can be compressed", d: "Able to be squeezed into a smaller volume. Gases can be compressed; solids and liquids cannot be compressed." },
    { t: "Melting", d: "The change of state from solid to liquid when a substance gains heat, e.g. ice melting into water. The mass of the substance stays the same." },
    { t: "Digestion", d: "The process in which food is broken down into simpler substances so that it can be absorbed into the bloodstream and used by the body." },
    { t: "Digestive juices", d: "Liquids made by the body, such as saliva, that break down food into simpler substances. They act on food in the mouth, stomach and small intestine." },
    { t: "Absorption of digested food", d: "The taking in of digested food from the small intestine into the bloodstream, which then carries it to all parts of the body." },
    { t: "Gullet", d: "The tube that moves food from the mouth to the stomach. No digestion takes place in the gullet." },
    { t: "Mineral salts", d: "Substances in the soil that a plant needs to grow healthily. They dissolve in water, are absorbed by the roots and are carried up the stem." },
    { t: "Light source", d: "An object that gives out its own light, e.g. the Sun, a lit candle and a switched-on torch. The Moon and mirrors are not light sources; they only reflect light." },
    { t: "Reflection of light", d: "Light bouncing off the surface of an object. We see an object when light from a light source is reflected by the object into our eyes." },
    { t: "Shadow", d: "A dark area formed when an opaque or translucent object blocks light. Light travels in a straight line, so it cannot pass round the object to reach the area behind it." }
  ],
  lessons: [
    {
      h: "Explaining why a temperature graph levels off",
      concept: "When a hot or cold object is left in a room, heat flows between it and the surrounding air. Its temperature changes quickly at first, then more slowly as the difference in temperature becomes smaller. When the graph becomes flat, the object has reached the same temperature as its surroundings (room temperature), so there is no more heat flow. Full marks need BOTH ideas – ‘same temperature as the surroundings’ and ‘no more heat flow’ – while ‘it stopped cooling’ only repeats the graph.",
      example: {
        q: "Hot water at 80 °C was poured into a cup and left on a table in a room. Study the graph.\n(a) What was the temperature of the room? [1]\n(b) Explain why the temperature of the water stayed the same after 40 minutes. [2]",
        fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 80], ["10", 55], ["20", 40], ["30", 33], ["40", 30], ["50", 30], ["60", 30]] },
        marks: 3,
        think: [
          "Step 1: Find the flat part of the graph: from 40 minutes onwards, the reading stays at 30 °C.",
          "Step 2: Water left long enough ends up at the temperature of its surroundings, so the room was at 30 °C.",
          "Step 3: Before 40 minutes, heat flowed from the hotter water to the cooler surrounding air, so the water lost heat and its temperature fell.",
          "Step 4: At 30 °C the water and the surrounding air were at the same temperature, so heat no longer flowed from the water to the air. Write both ideas: same temperature AND no more heat flow."
        ],
        answer: "(a) 30 °C. (b) The water lost heat to the cooler surrounding air until it reached room temperature (30 °C). The water and the surrounding air were then at the same temperature, so there was no more heat flow and the temperature of the water stayed the same."
      },
      tip: "Flat line = same temperature as the surroundings = no more heat flow. Write both parts for both marks.",
      try: {
        q: "A metal can of hot water at 70 °C was placed in a basin of water at 25 °C. Study the graph of the temperature of the water in the BASIN. Which is the best explanation for why the basin water stopped getting warmer after 30 minutes?",
        fig: { type: "line", xl: "Time (min)", yl: "Temperature of basin water (°C)", pts: [["0", 25], ["10", 31], ["20", 34], ["30", 35], ["40", 35]] },
        o: ["The basin water had taken in all the coldness from the can of water", "The basin water and the can of water had reached the same temperature", "The metal can had stopped conducting heat after 30 minutes", "The basin water had gained as much heat as water can hold"],
        a: 1,
        why: "Heat flowed from the hotter water in the can to the cooler basin water until both were at the same temperature (35 °C), and then heat stopped flowing between them. ‘Coldness’ does not flow, and the metal can still conducts heat."
      }
    },
    {
      h: "Using test results as evidence for a state of matter",
      concept: "Some questions give the results of tests on an unknown substance and ask you to identify its state. Check three properties: does it have a definite shape, does it have a definite volume, and can it be compressed? A solid has a definite shape and a definite volume; a liquid has a definite volume but takes the shape of its container; a gas has neither and can be compressed. When asked to explain, quote the result from the table AND name the property it shows.",
      example: {
        q: "Mei tested substances X and Y. Study the table.\n(a) State whether X is a solid, a liquid or a gas. [1]\n(b) Using the results, give two reasons for your answer in (a). [2]",
        tbl: [["Test", "Substance X", "Substance Y"], ["Poured from a round bottle into a square box", "Took the shape of the box; its volume stayed at 50 ml", "Spread out to fill the whole box"], ["Pushed hard in a sealed syringe", "Volume stayed at 50 ml", "Volume decreased from 50 ml to 20 ml"]],
        marks: 3,
        think: [
          "Step 1: Read only the column for X. Y is there to distract you in this part.",
          "Step 2: X took the shape of the box, so it has no definite shape. It is not a solid.",
          "Step 3: X kept a volume of 50 ml in the new container and when pushed in the syringe, so it has a definite volume and cannot be compressed. It is not a gas.",
          "Step 4: No definite shape + definite volume = liquid. Each reason = the result from the table + the property it shows."
        ],
        answer: "(a) X is a liquid. (b) X took the shape of the box, so it has no definite shape. Its volume stayed at 50 ml when it was poured into the box and when it was pushed in the syringe, so it has a definite volume and cannot be compressed."
      },
      tip: "Quote the result, then name the property: ‘its volume stayed at 50 ml, so it has a definite volume’.",
      try: {
        q: "Siti tested substance Z. Study the table. Which conclusion is supported by the results?",
        tbl: [["Test", "Result for substance Z"], ["Moved from a small box into a large box", "Kept the same shape and size"], ["Pushed hard in a sealed syringe", "Volume stayed the same"]],
        o: ["Z is a liquid, as it has a definite volume and cannot be compressed", "Z is a solid, as it has a definite shape and a definite volume", "Z is a gas, as it can be moved from one box into another box", "Z is a liquid, as it kept its shape when moved into a larger box"],
        a: 1,
        why: "Z kept the same shape in a bigger box, so it has a definite shape, and its size and volume did not change, so it has a definite volume: it is a solid. A liquid would take the shape of the larger box, and a gas would spread out to fill it."
      }
    }
  ],
  flash: [
    { f: "Why are gaps left between sections of railway tracks?", b: "On hot days the steel tracks gain heat and expand. The gaps give the tracks space to expand, so they do not push against each other and bend." },
    { f: "How does a liquid-in-glass thermometer work?", b: "When the bulb gains heat, the liquid expands and rises up the tube. When it loses heat, the liquid contracts and falls. The scale shows the temperature in °C." },
    { f: "Why can the air in a sealed syringe be compressed, but water cannot?", b: "Air is a gas, which has no definite volume, so it can be pushed into a smaller space. Water is a liquid, which has a definite volume, so it cannot be compressed." },
    { f: "How do you find the volume of a stone using a measuring cylinder of water?", b: "Read the water level, lower the stone in fully, then read the new level. Volume of stone = new level − first level, as the stone occupies space and pushes the water up." },
    { f: "Function of the mouth in digestion", b: "The teeth cut and chew food into smaller pieces. Saliva, a digestive juice, starts to break down food into simpler substances." },
    { f: "Function of the leaves", b: "The leaves make food for the plant. The food is then carried by the stem to other parts of the plant." },
    { f: "Function of the flower", b: "The flower develops into a fruit, which contains seeds. The seeds can grow into new plants." },
    { f: "Why does the shadow of a lamp post change in length during the day?", b: "The position of the Sun in the sky changes. The shadow is long when the Sun is low (morning and evening) and shortest at about noon, when the Sun is high overhead." },
    { f: "How can you make the shadow of a toy on a screen bigger?", b: "Move the toy nearer to the light source, so that it blocks more of the light. Moving the screen further away from the toy also makes the shadow bigger." },
    { f: "Why are the handles of cooking pots made of plastic or wood?", b: "Plastic and wood are poor conductors of heat, so heat from the hot pot flows through the handle to the hand slowly, and the handle does not get too hot to hold." },
    { f: "How can a magnet sort steel cans from aluminium cans?", b: "Steel is a magnetic material, so steel cans are attracted by the magnet and pulled out. Aluminium is not a magnetic material, so aluminium cans are left behind." },
    { f: "A leafy stalk stood in red-coloured water. What do the red dots in its cut stem show?", b: "The stem has tubes that carry water from the roots up to the leaves. The red dots show where the water-carrying tubes are." }
  ],
  mcq: [
    { q: "Study the diagram. In which part is food kept for a few hours while it is mixed with digestive juices and partly digested?", o: ["A", "B", "C", "D"], a: 1, why: "B is the stomach, where food is mixed with digestive juices and partly digested. A is the gullet, which only moves food; C (small intestine) completes digestion; D (large intestine) absorbs water.", lvl: 1, fig: { type: "organs", system: "digestive", mark: { gullet: "A", stomach: "B", small_intestine: "C", large_intestine: "D" } } },
    { q: "Which instrument should Mei use to measure out 80 ml of cooking oil?", o: ["A thermometer", "An electronic balance", "A measuring cylinder", "A measuring tape"], a: 2, why: "Millilitres (ml) are a unit of volume, and a measuring cylinder measures the volume of a liquid. A balance measures mass, and a thermometer measures temperature.", lvl: 1 },
    { q: "When a bar of chocolate melts in the hot sun, it changes from…", o: ["a liquid to a gas", "a solid to a liquid", "a liquid to a solid", "a gas to a liquid"], a: 1, why: "The solid chocolate gains heat from the Sun and melts into a liquid. Melting is the change from solid to liquid.", lvl: 1 },
    { q: "Study the diagram of a plant. Which part develops into a fruit that contains seeds?", o: ["P", "Q", "R", "S"], a: 3, why: "S is the flower, which develops into a fruit containing seeds. P (roots) absorbs water, Q (stem) carries water and food, and R (leaf) makes food.", lvl: 1, fig: { type: "plant", mark: { roots: "P", stem: "Q", leaf: "R", flower: "S" } } },
    { q: "At a chwee kueh stall, the rice batter is steamed in small aluminium cups instead of thick clay cups. Which is the best reason?", o: ["Aluminium is a poor conductor of heat, so it keeps the heat in the batter", "Aluminium is a good conductor of heat, so heat from the steam reaches the batter quickly", "Aluminium gives out its own heat, so the batter cooks without much steam", "Aluminium is a magnetic material, so the cups stay firmly on the steamer tray"], a: 1, why: "Aluminium is a good conductor of heat, so heat from the hot steam flows through the cup to the batter quickly and it cooks faster. Aluminium is not a source of heat and is not a magnetic material.", lvl: 2 },
    { q: "Mrs Tan put a fully blown-up balloon into a refrigerator. After an hour, the balloon looked smaller. Which explains this?", o: ["The air inside gained coldness, so its mass decreased", "The air inside lost heat, so its mass decreased", "The air inside lost heat and contracted", "The rubber gained heat and contracted"], a: 2, why: "The air in the balloon lost heat to the colder air in the refrigerator and contracted, so its volume decreased. Its mass stayed the same, and there is no ‘coldness’ that flows.", lvl: 2 },
    { q: "Which statement about the water in a glass is NOT correct?", o: ["It has mass.", "It has a definite volume.", "It takes the shape of its container.", "It can be compressed easily."], a: 3, why: "Water is a liquid: it has mass, a definite volume and takes the shape of the container it is in, but it cannot be compressed. Only gases can be compressed easily.", lvl: 2 },
    { q: "Study the classification chart of parts of the digestive system. Which correctly names P and R?", o: ["P: small intestine, R: large intestine", "P: stomach, R: large intestine", "P: small intestine, R: gullet", "P: large intestine, R: small intestine"], a: 0, why: "P is a part where digestion takes place and digested food is absorbed: the small intestine. R is a part with no digestion that absorbs water: the large intestine. The stomach digests food but does not absorb digested food (Q), the gullet only moves food (S), and no digestion takes place in the large intestine.", lvl: 2, fig: { type: "flow", root: "Digestive parts", node: { q: "Digestion takes place?", yes: { q: "Absorbs digested food?", yes: "P", no: "Q" }, no: { q: "Absorbs water?", yes: "R", no: "S" } } } },
    { q: "Study the set-ups. Ravi wants to find out if the material of a rod affects how much it expands when it is heated. Which two set-ups should he compare?", o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "A and B differ only in the material of the rod; the length and heating time are the same. A and C differ in length, B and D in heating time, and C and D in material, length and heating time.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Copper rod", "Length: 50 cm", "Heated for 5 min"] }, { label: "B", icon: "box", lines: ["Steel rod", "Length: 50 cm", "Heated for 5 min"] }, { label: "C", icon: "box", lines: ["Copper rod", "Length: 30 cm", "Heated for 5 min"] }, { label: "D", icon: "box", lines: ["Steel rod", "Length: 50 cm", "Heated for 10 min"] }] } },
    { q: "Divers exploring the coral reefs at Pulau Hantu carry small steel tanks that hold a large amount of air. This is possible because air…", o: ["can be compressed", "has no mass", "has a definite volume", "has a definite shape"], a: 0, why: "Air is a gas, and a gas can be compressed, so a large amount of air can be squeezed into a small tank. Air does have mass, and a gas has no definite volume or shape.", lvl: 2 },
    { q: "Which of these can we see only because light from a light source is reflected from them into our eyes?\nA: the Moon at night\nB: a lit candle\nC: a red apple on a table", o: ["A only", "B only", "A and C only", "B and C only"], a: 2, why: "The Moon and the apple do not give out their own light; they reflect light (from the Sun or a lamp) into our eyes. A lit candle is a light source, so its own light enters our eyes.", lvl: 2 },
    { q: "Four syringes P, Q, R and S each started with 50 ml of ONE of these: water, air, cooking oil, or 25 ml of water with 25 ml of air. Each nozzle was sealed and each plunger was pushed in hard with the same force. Study the graph. Which syringe held the mixture of water and air?", o: ["P", "Q", "R", "S"], a: 3, why: "Water and cooking oil cannot be compressed, so P and R stayed at 50 ml. Q, with the most compression, held only air. In S only the 25 ml of air was compressed while the 25 ml of water was not, so its volume fell only to 34 ml.", lvl: 3, fig: { type: "bar", xl: "Syringe", yl: "Volume after pushing (ml)", bars: [["P", 50], ["Q", 18], ["R", 50], ["S", 34]] } },
    { q: "Sugar cane juice from a hawker stall is sweet because the stem of the sugar cane plant stores food. How did this food get into the stem?", o: ["It was made in the leaves and carried to the stem", "It was absorbed from the soil by the roots and carried up", "It was made in the roots and carried up the stem", "It was absorbed from the air by the stem itself"], a: 0, why: "A plant makes its food in its leaves, and the stem carries the food to other parts of the plant, where it can be stored. Roots absorb water and mineral salts, not food.", lvl: 3 },
    { q: "Which statements are true of BOTH the roots of a plant and the small intestine of a human?\nA: They absorb substances that are then carried to other parts of the living thing.\nB: They take in food that is then broken down by digestive juices.\nC: They are the parts where food is made.", o: ["A only", "B only", "A and B only", "A and C only"], a: 0, why: "Roots absorb water and mineral salts, which the stem carries up; the small intestine absorbs digested food, which the blood carries around the body. Roots do not take in or digest food (B), and neither part makes food – leaves do (C).", lvl: 3 },
    { q: "Siti sealed some ice cubes in a plastic bag and weighed it, wiping the outside of the bag dry before each weighing. Study the table. What is the most likely mass of the bag when all the ice has melted?", o: ["Less than 180 g, because water occupies less space than ice", "180 g, because the amount of matter in the bag stays the same", "More than 180 g, because water is heavier than ice", "Less than 180 g, because some of the ice has disappeared"], a: 1, why: "Melting is only a change of state. The bag is sealed, so no matter enters or leaves, and the mass stays at 180 g. A change in volume does not change the mass.", lvl: 3, tbl: [["Time (min)", "What is in the bag", "Mass (g)"], ["0", "Ice cubes", "180"], ["20", "Ice and water", "180"], ["40", "Water only", "?"]] },
    { q: "Siew Ling put a steel spoon at room temperature (30 °C) into a tub of ice cream at −5 °C. Which statements are correct?\nA: Heat flows from the spoon to the ice cream.\nB: The temperature of the spoon falls.\nC: The ice cream touching the spoon may start to melt.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 3, why: "The spoon is hotter, so heat flows from the spoon to the ice cream (A). The spoon loses heat and its temperature falls (B). The ice cream touching it gains heat and may start to melt (C).", lvl: 3 },
    { q: "Kumar moved a toy away from a torch, towards a fixed screen, and measured the height of its shadow on the screen each time. Study the table. Which reading is most likely to be an error?", o: ["At 20 cm", "At 30 cm", "At 40 cm", "At 50 cm"], a: 1, why: "As the toy moves away from the torch, it blocks less of the light, so its shadow should get shorter each time. The reading at 30 cm (14 cm) is taller than the one at 20 cm (12 cm), which breaks the pattern.", lvl: 3, tbl: [["Distance of toy from torch (cm)", "Height of shadow (cm)"], ["10", "24"], ["20", "12"], ["30", "14"], ["40", "6"], ["50", "5"]] },
    { q: "Ali held two sheets, one at a time, between a lit torch and a screen.\nSheet 1: a square of cardboard with a round hole cut in the middle\nSheet 2: a square of frosted plastic with a black circle painted in the middle\nWhich correctly describes the two shadows?", o: ["1: dark square with a bright circle in it; 2: faint square with a dark circle in it", "1: dark square with a bright circle in it; 2: dark square with a faint circle in it", "1: faint square with a bright circle in it; 2: faint square with a dark circle in it", "1: bright square with a dark circle in it; 2: faint square with a bright circle in it"], a: 0, why: "Cardboard is opaque, so it forms a dark square shadow, but light passes straight through the hole, giving a bright circle. Frosted plastic is translucent and lets some light through, so it forms a faint square shadow, while the opaque black paint blocks light and forms a dark circle.", lvl: 4 },
    { q: "Study the set-ups. Thermometers P and Q have bulbs of the same size holding the same amount of the same liquid, but P has a narrower tube than Q. Both are moved from water at 30 °C into water at 60 °C. Which is correct?", o: ["The liquid rises higher in Q, as a wide tube lets the liquid expand more", "The liquid rises equally in both, as both liquids gain heat and expand", "The liquid rises higher in P, as the liquid in P gains more heat than in Q", "The liquid rises higher in P, as the same extra volume fills more of a narrow tube"], a: 3, why: "Both liquids gain the same amount of heat and expand by the same volume. In the narrower tube, the same extra volume of liquid fills a longer part of the tube, so the liquid in P rises higher.", lvl: 4, fig: { type: "setups", items: [{ label: "P", icon: "beaker", lines: ["Same bulb and liquid", "Narrow tube", "30 °C → 60 °C"] }, { label: "Q", icon: "beaker", lines: ["Same bulb and liquid", "Wide tube", "30 °C → 60 °C"] }] } },
    { q: "A metal can of water at 80 °C was placed in a basin holding five times as much water at 20 °C. Study the table. Which statements are correct?\nA: From 0 to 10 minutes, heat flowed from the water in the can to the basin water.\nB: The temperature of the can water fell by more than the temperature of the basin water rose.\nC: After 10 minutes, heat still flowed from the can water to the basin water.", o: ["A only", "B and C only", "A and B only", "A, B and C"], a: 2, why: "A: the can water was hotter, so it lost heat to the basin water. B: the can water fell by 50 °C (80 to 30) while the basin water rose by only 10 °C (20 to 30). C is wrong: from 10 minutes both were at 30 °C, the same temperature, so heat no longer flowed between them.", lvl: 4, tbl: [["Time (min)", "Can water (°C)", "Basin water (°C)"], ["0", "80", "20"], ["2", "62", "23"], ["4", "48", "26"], ["6", "38", "28"], ["10", "30", "30"], ["12", "30", "30"]] }
  ],
  oe: [
    { q: "The diagram shows the parts of a mango plant.\n(a) Which part, W, X, Y or Z, absorbs water and mineral salts from the soil? [1]\n(b) Name the part that carries water from W to Y. [1]\n(c) The mangoes (Z) are sweet because they store food. Where was this food made, and how did it reach Z? [2]", marks: 4, kw: [["w", "root"], ["stem", "x"], ["made in the lea", "made in lea", "made by the lea", "made in y", "leaves make", "leaves made", "leaf make", "leaf made"], ["carried by the stem", "stem carried", "stem carries", "food is carried", "food was carried", "carried the food", "carries the food", "carries food", "carried down", "carried to the fruit", "carried to z", "transported"]], model: "(a) W, the roots. (b) The stem. (c) The food was made in the leaves (Y). The food was carried by the stem to the fruit (Z), where it was stored.", fig: { type: "plant", mark: { roots: "W", stem: "X", leaf: "Y", fruit: "Z" } } },
    { q: "Mdm Tan heated the same amount of bak kut teh soup in a steel pot and in a claypot of the same size and thickness, on identical stoves. Both soups started at room temperature. After 10 minutes, she turned off both stoves. Study the table.\n(a) In which pot did the soup heat up faster? Explain why. [2]\n(b) Explain why the soup in the claypot stayed hot for longer after the stoves were turned off. [1]\n(c) Predict the temperature of both soups after they have been left for several hours. [1]", marks: 4, kw: [["steel"], ["good conductor", "better conductor", "conducts heat well", "conducts heat better", "conducts heat faster", "conducts heat quickly"], ["poor conductor", "poorer conductor", "conducts heat poorly", "conducts heat slowly", "loses heat slowly", "lost heat slowly", "loses heat more slowly", "lost heat more slowly"], ["28", "room temperature"]], model: "(a) The steel pot. Steel is a better conductor of heat than clay, so heat from the stove flowed through the steel pot to the soup faster. (b) Clay is a poorer conductor of heat, so heat from the soup flowed through the claypot to the cooler surroundings more slowly; the soup lost heat slowly. (c) Both soups will be at room temperature, 28 °C, the same temperature as the surroundings.", tbl: [["Pot", "At the start (°C)", "After 10 min of heating (°C)", "30 min after the stove was turned off (°C)"], ["Steel pot", "28", "90", "55"], ["Claypot", "28", "70", "62"]], x: 1 },
    { q: "Mrs Lim sprayed some air freshener in one corner of her HDB living room. A few minutes later, it could be smelt in every part of the room.\n(a) In which state is the air freshener when it spreads through the room? [1]\n(b) Which property of this state explains why it spread to every part of the room? [1]\n(c) Her son then used a hand pump to push a lot of air into a small football. Which property of air makes this possible? [1]", marks: 3, kw: [["gas"], ["no definite volume", "no fixed volume", "fill", "occupy the whole", "occupies the whole", "spread out to occupy"], ["compress"]], model: "(a) It is a gas. (b) A gas has no definite shape and no definite volume, so it spreads out to fill the whole room. (c) Air can be compressed, so a large amount of air can be pushed into the small space inside the football." },
    { q: "Ming placed sheets P, Q and R, one at a time, between a lit torch and a screen. Study the table.\n(a) Which sheet is opaque? Explain using the results. [2]\n(b) What does the result for R show about how much light passes through R? [1]\n(c) Which sheet is most suitable for the cover of a display case in a museum, so that visitors can see the objects inside clearly? [1]", marks: 4, kw: [["q"], ["block", "does not allow", "no light", "not allow"], ["some light", "some of the light", "part of the light", "a little light", "a little of the light"], ["p"]], model: "(a) Q. It formed a dark shadow, so it blocks the light and does not allow light to pass through it. (b) R allows some light to pass through it, so it is translucent. (c) P, because it is transparent and allows most light to pass through, so the objects inside can be seen clearly.", tbl: [["Sheet", "Shadow on the screen"], ["P", "No clear shadow; the screen stayed bright"], ["Q", "Dark shadow"], ["R", "Faint shadow"]] }
  ],
  tf: [
    { s: "Digestion of food takes place in the large intestine.", a: false, why: "Digestion takes place in the mouth, stomach and small intestine. The large intestine only absorbs water from the undigested food." },
    { s: "A plant uses the water absorbed by its roots to make food in its leaves.", a: true, why: "The roots absorb water, the stem carries it up to the leaves, and the leaves use it to make food." },
    { s: "The bigger an opaque object is, the darker its shadow.", a: false, why: "Size changes how big the shadow is, not how dark it is. How dark a shadow is depends on how much light the object allows to pass through." },
    { s: "When a ball of plasticine is pressed flat, its mass and volume stay the same.", a: true, why: "Only its shape changes. No matter is added or removed, and a solid cannot be compressed, so its mass and volume stay the same." },
    { s: "A wooden table feels warmer than a metal chair in the same room because the wood is at a higher temperature.", a: false, why: "Both are at room temperature. Metal is a better conductor of heat and conducts heat away from the hand faster, so it feels colder." },
    { s: "A hot drink left on a table loses heat to the surrounding air until it reaches room temperature.", a: true, why: "Heat flows from the hotter drink to the cooler air until both are at the same temperature; then there is no more heat flow." },
    { s: "Liquids can be compressed as easily as gases.", a: false, why: "A liquid has a definite volume and cannot be compressed. Only gases can be compressed easily." },
    { s: "Digested food is carried by the blood to all parts of the body.", a: true, why: "Digested food is absorbed into the bloodstream in the small intestine, and the blood carries it to all parts of the body." },
    { s: "The leaves of a plant take in water from the air to make food.", a: false, why: "The water a plant uses to make food is absorbed from the soil by the roots and carried up to the leaves by the stem." },
    { s: "A steel spoon left in a pot of hot soup soon becomes hot along its whole length.", a: true, why: "Steel is a good conductor of heat, so heat from the hot soup flows quickly along the spoon to its top end." }
  ]
};
