window.LB = window.LB || {};
LB["p4-skills"] = {
  notes: [
    { h: "Three kinds of variables", t: "In a fair test, the variable changed is the ONE thing you change on purpose. The variable measured is the result you measure, count or observe. The variables kept the same (constant variables) are all the other things that could affect the result. Name every variable in full, e.g. ‘the type of material the cup is made of’, not just ‘cup’.", kw: ["variable changed", "variable measured", "variables kept the same"] },
    { h: "Writing the aim", t: "The aim links the variable changed to the variable measured: ‘To find out if / how [variable changed] affects [variable measured]’. For example, ‘To find out if the type of material of a cup affects how fast hot water in it loses heat.’ A hypothesis is a testable statement you make BEFORE the experiment, e.g. ‘The thicker the cloth, the less light passes through it.’", kw: ["to find out if", "affects", "hypothesis"] },
    { h: "Control set-ups", t: "A control set-up is identical to the experimental set-up EXCEPT for the one variable being tested, which is absent or unchanged. It is used for comparison, to show that any change seen in the experimental set-up is caused by that variable only. E.g. an egg white cube in water is the control for an egg white cube in digestive juice.", kw: ["control", "for comparison", "caused by"] },
    { h: "Fair versus reliable", t: "A test is FAIR when only one variable is changed and all others are kept the same. Results are RELIABLE when they can be trusted because the experiment was repeated (usually 3 times) and the average was taken, or a larger number of things (e.g. 10 plants, not 1) was used. Repeating does NOT make a test fair.", kw: ["fair", "reliable", "repeat the experiment", "average"] },
    { h: "Measuring cylinder", t: "A measuring cylinder measures the volume of a liquid in ml or cm³ (1 ml = 1 cm³). Place it on a flat surface and read with your eye level with the BOTTOM of the curved water surface. To find the volume of an irregular solid such as a stone, lower it fully into water: its volume = rise in water level.", kw: ["volume", "eye level", "bottom of the curved surface", "rise in water level"] },
    { h: "Electronic balance", t: "An electronic balance measures mass in grams (g) or kilograms (kg). Reset it to zero before use. It can show that air has mass: a ball pumped with more air has a greater mass. Mass is the amount of matter in an object; it is not the same as volume or size.", kw: ["mass", "grams", "air has mass"] },
    { h: "Thermometer and temperature sensor", t: "A thermometer or temperature sensor measures temperature in degrees Celsius (°C). Keep the bulb in the liquid without touching the container, wait until the reading stops changing, and read at eye level. Temperature tells how hot or cold something is; it is not the same as the amount of heat.", kw: ["temperature", "degrees Celsius", "bulb"] },
    { h: "Light sensor and datalogger", t: "A light sensor measures the amount of light reaching it. In a test of materials, the higher the light sensor reading, the more light passes through the material. Keep the light source, its distance and the sensor position the same, and change only the material.", kw: ["amount of light", "higher reading", "more light passes through"] },
    { h: "Bar graphs and line graphs", t: "A bar graph compares separate groups, such as types of material or types of cloth. A line graph shows how something changes continuously, such as temperature over time. The variable changed goes on the horizontal (x) axis and the variable measured on the vertical (y) axis. Always read the axis labels and units first.", kw: ["bar graph", "line graph", "x-axis", "y-axis"] },
    { h: "Describing trends", t: "Describe the relationship: ‘As the [variable changed] increases, the [variable measured] increases / decreases.’ A flat part means no change. The steeper the line, the faster the change. Quote numbers with units to support the trend, e.g. ‘from 80 °C to 40 °C in 20 minutes’.", kw: ["as", "increases", "decreases", "steeper", "no change"] },
    { h: "Conclusions stay inside the data", t: "A conclusion answers the aim using ONLY what was tested. If only copper and iron were tested, you cannot conclude about all metals. Predictions far beyond the range tested, or for other conditions, are not supported. One trial on one day cannot tell you what happens every day.", kw: ["only what was tested", "within the range", "not supported"] },
    { h: "Claim, Evidence, Reasoning", t: "A full-mark explanation has three parts. Claim: answer the question directly. Evidence: quote the data with units and a comparison word (more than, the longest, the lowest). Reasoning: link to the science concept using keywords, e.g. ‘wood is a poor conductor of heat, so it conducts heat slowly to the hand’.", kw: ["claim", "evidence", "reasoning", "quote the data"] }
  ],
  traps: [
    "Repeating the experiment makes it fair -> Repeating and averaging makes results RELIABLE; keeping all other variables the same makes it FAIR.",
    "The longest bar is always the ‘best’ -> Read what the bar measures: the rod that takes the SHORTEST time for wax to melt is the best conductor of heat.",
    "Naming a variable vaguely, e.g. ‘the water’ -> Name it in full, e.g. ‘the temperature of the water after 10 minutes’ or ‘the volume of water’.",
    "Reading a measuring cylinder at the top of the curve -> Read at eye level at the BOTTOM of the curved water surface.",
    "A higher light sensor reading means the material blocks more light -> A higher reading means MORE light passes through the material.",
    "The control set-up is the ‘normal’ one with nothing done -> The control is identical except that the variable being tested is absent, and is used for comparison.",
    "‘Copper and iron are good conductors, so all metals are good conductors’ -> Conclude only about what was tested; test more metals before generalising.",
    "Answering a graph question without numbers -> Quote the data with units and a comparison word as your evidence."
  ],
  lessons: [
    {
      h: "Naming the three variables in full",
      concept: "Most lost marks in experiment questions come from vague variables. The variable changed is what differs between set-ups on purpose. The variable measured is what is recorded as the result. Variables kept the same are everything else that could affect the result. Name each one with what it is AND what it belongs to, e.g. ‘the temperature of the water in the cup after 15 minutes’.",
      example: {
        q: "Wei Ming poured 200 ml of hot water at 80 °C into three identical-sized cups made of metal, glass and plastic. After 15 minutes, he measured the temperature of the water in each cup.\n(a) State the variable changed. [1]\n(b) State the variable measured. [1]\n(c) State one variable he must keep the same. [1]",
        fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Metal cup", "200 ml water", "Starts at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Glass cup", "200 ml water", "Starts at 80 °C"] }, { label: "C", icon: "beaker", lines: ["Plastic cup", "200 ml water", "Starts at 80 °C"] }] },
        marks: 3,
        think: [
          "Step 1: Compare the set-ups. Volume (200 ml) and starting temperature (80 °C) are the same. Only the material of the cup differs, so that is the variable changed.",
          "Step 2: Find what is recorded: the temperature of the water after 15 minutes. Saying only ‘temperature’ may lose the mark, so name whose temperature and when.",
          "Step 3: Pick a variable that could affect the result and must stay the same: the volume of water, the starting temperature, the size of the cup or the place.",
          "Step 4: Check that the measured variable could depend on the changed one. Different materials conduct heat differently, so the water cools by different amounts. It makes sense."
        ],
        answer: "(a) The type of material the cup is made of. (b) The temperature of the water in the cup after 15 minutes. (c) The volume of hot water in each cup (or the starting temperature of the water)."
      },
      tip: "Before writing, finish the sentence ‘The ____ of the ____’. If you cannot, your variable is too vague.",
      try: {
        q: "Aisha shone a torch on different sheets of material, one at a time, and recorded the light sensor reading behind each sheet. The torch and sensor stayed in the same places. What is the variable MEASURED?",
        o: ["The type of material of the sheet", "The distance between the torch and the sheet", "The amount of light that passes through each sheet", "The brightness of the torch"],
        a: 2,
        why: "The light sensor reading tells how much light passes through each sheet, so that is what is measured. The type of material is the variable changed; the distance and the torch brightness are kept the same."
      }
    },
    {
      h: "Explaining why a control set-up is needed",
      concept: "Examiners want two ideas: the control is used FOR COMPARISON, and it shows that the result in the experimental set-up is CAUSED BY the variable being tested. A control set-up is identical except that the variable being tested is absent. ‘To make it fair’ or ‘to check’ alone scores nothing.",
      example: {
        q: "Mrs Tan placed a cube of boiled egg white in each test tube. Tube A had 10 ml of digestive juice from the stomach. Tube B had 10 ml of water. Both were kept at 37 °C. After a day, the cube in A was much smaller, while the cube in B did not change. Why was tube B set up? [2]",
        fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Egg white cube", "10 ml digestive juice", "Kept at 37 °C"] }, { label: "B", icon: "jar", lines: ["Egg white cube", "10 ml water", "Kept at 37 °C"] }] },
        marks: 2,
        think: [
          "Step 1: Find the only difference: digestive juice in A, water in B. So B is the control, with the digestive juice absent.",
          "Step 2: Say what B is for: comparison with A.",
          "Step 3: Say what the comparison proves: the cube became smaller in A because of the digestive juice, not because of the water or the temperature.",
          "Step 4: Put both ideas in one clear answer."
        ],
        answer: "Tube B is the control set-up, used for comparison with tube A. It shows that the egg white in A became smaller because it was broken down by the digestive juice, not because of the water or the temperature."
      },
      tip: "Control = ‘for comparison’ + ‘to show that the change is caused by ____ only’.",
      try: {
        q: "Ken wants to show that the digestive juice from the small intestine breaks down cooked rice. Which is the best control set-up?",
        o: ["Cooked rice with more digestive juice", "Cooked rice with the same volume of water, at the same temperature", "Raw rice with digestive juice", "Cooked rice with digestive juice at a lower temperature"],
        a: 1,
        why: "The control must be identical except that the digestive juice is absent, so it uses the same volume of water at the same temperature. The other choices change the amount of juice, the food or the temperature instead."
      }
    },
    {
      h: "Fair versus reliable: say the right word",
      concept: "Two different ideas are often mixed up. FAIR: only one variable is changed and all others are kept the same, so you know what caused the result. RELIABLE: the results can be trusted because the experiment was repeated (e.g. 3 times) and the average taken, or many objects were used. Answer with the word the question asks for, and state HOW.",
      example: {
        q: "Farah placed one green bean seedling in a beaker of 100 ml of water to find out how much water it took in over 3 days. Suggest two ways she can make her results more reliable. [2]",
        marks: 2,
        think: [
          "Step 1: The question asks for RELIABLE, not fair, so do not talk about keeping variables the same.",
          "Step 2: One seedling might be unusual. Using more seedlings evens this out.",
          "Step 3: One trial might have a mistake. Repeating and taking the average evens this out.",
          "Step 4: Write both ways clearly."
        ],
        answer: "She can use more seedlings, for example 10 seedlings, in the set-up instead of one. She can also repeat the experiment 3 times and find the average volume of water taken in."
      },
      tip: "Reliable = repeat + average, or more objects. Fair = one variable changed, others kept the same.",
      try: {
        q: "Which action makes an experiment’s results more RELIABLE?",
        o: ["Using the same volume of water in every set-up each time", "Changing only the type of material and keeping all else the same", "Keeping all set-ups in the same room at the same temperature", "Repeating the experiment three times and finding the average"],
        a: 3,
        why: "Repeating and averaging reduces the effect of a mistake in any one trial, so the results can be trusted more. The other three choices make the test fair, not more reliable."
      }
    },
    {
      h: "Describing a line graph with data",
      concept: "A full answer has the trend AND the data. Write ‘As the ____ increases, the ____ decreases’, then quote readings with units, and mention any change in steepness or flat part. For a cooling line, the temperature drops quickly at first, then more slowly, and stops at room temperature because the water and the surroundings are then at the same temperature.",
      example: {
        q: "Study the graph of the temperature of hot water left in a room. Describe how the temperature changed and explain why it stopped at 30 °C. [2]",
        fig: { type: "line", title: "Temperature of water left in a room", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 80], ["10", 55], ["20", 42], ["30", 35], ["40", 31], ["50", 30], ["60", 30]] },
        marks: 2,
        think: [
          "Step 1: Overall trend: the line goes down, so the temperature decreased with time.",
          "Step 2: Detail: steepest from 0 to 10 min (a drop of 25 °C), gentler later, flat from 50 min.",
          "Step 3: Explain the flat part: the water lost heat to the surroundings until it reached room temperature (30 °C), then there was no more heat loss.",
          "Step 4: Quote the numbers to show you read the graph."
        ],
        answer: "The temperature decreased quickly at first, from 80 °C to 55 °C in the first 10 minutes, then more slowly, and stayed at 30 °C from 50 minutes. The water lost heat to the surroundings until it reached room temperature, 30 °C, so it stopped losing heat."
      },
      tip: "Trend word + numbers with units + reason. A flat line means NO change, not ‘the experiment stopped’.",
      try: {
        q: "Study the graph. What was the room temperature?",
        fig: { type: "line", title: "Temperature of water left in a room", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 70], ["10", 50], ["20", 38], ["30", 31], ["40", 29], ["50", 29]] },
        o: ["70 °C", "29 °C", "38 °C", "0 °C"],
        a: 1,
        why: "The water stops cooling when it reaches the temperature of its surroundings, so the flat part at 29 °C shows the room temperature. 70 °C is only the starting temperature."
      }
    },
    {
      h: "CER answers from a bar graph",
      concept: "‘Which is best? Explain.’ needs three parts. Claim: name the choice. Evidence: quote its value and compare it with the others (the longest, the lowest, more than). Reasoning: the science idea, e.g. ‘poor conductor of heat’ or ‘allows the least light to pass through’. Read the bar’s meaning before choosing: a longer time can mean a POORER conductor.",
      example: {
        q: "Study the graph. It shows the time taken for a wax bead at the end of rods of the same size to melt when the other end is heated. Which material is most suitable for the handle of a cooking pot? Explain using the data. [3]",
        fig: { type: "bar", title: "Time taken for wax to melt", xl: "Material of rod", yl: "Time taken (s)", bars: [["Copper", 30], ["Steel", 90], ["Glass", 240], ["Wood", 600]] },
        marks: 3,
        think: [
          "Step 1: What does a long bar mean? Heat took a long time to travel along the rod, so the material conducts heat slowly.",
          "Step 2: A handle should conduct heat slowly so the hand does not get burnt. Choose the rod with the longest time: wood.",
          "Step 3: Evidence: wood took 600 s, the longest time.",
          "Step 4: Reasoning: wood is the poorest conductor of heat of the four, so little heat reaches the hand."
        ],
        answer: "Wood. The wax on the wood rod took the longest time to melt, 600 s. This shows wood is the poorest conductor of heat, so it conducts heat from the hot pot to the hand the most slowly."
      },
      tip: "Claim + number with a comparison word + ‘good/poor conductor of heat’ (or ‘more/less light passes through’).",
      try: {
        q: "Using the same graph, which material is the best conductor of heat?",
        fig: { type: "bar", title: "Time taken for wax to melt", xl: "Material of rod", yl: "Time taken (s)", bars: [["Copper", 30], ["Steel", 90], ["Glass", 240], ["Wood", 600]] },
        o: ["Copper", "Steel", "Glass", "Wood"],
        a: 0,
        why: "Wax on copper melted in the shortest time (30 s), so heat travelled along copper the fastest. Wood has the tallest bar but that means it is the poorest conductor."
      }
    }
  ],
  mcq: [
    { q: "Study the bar graph of light sensor readings taken behind four sheets. Which sheet allowed the most light to pass through?", o: ["Sheet Q", "Sheet S", "Sheet P", "Sheet R"], a: 2, why: "Sheet P gave the highest reading (820), so the most light passed through it. Sheet S gave 0, so it blocked all the light.", lvl: 1, fig: { type: "bar", title: "Light sensor readings", xl: "Sheet", yl: "Light sensor reading (lux)", bars: [["P", 820], ["Q", 40], ["R", 450], ["S", 0]] } },
    { q: "Which instrument should Ali use to find the mass of a stone?", o: ["Measuring cylinder", "Electronic balance", "Thermometer", "Light sensor"], a: 1, why: "An electronic balance measures mass in grams. A measuring cylinder measures volume, a thermometer temperature and a light sensor the amount of light.", lvl: 1 },
    { q: "Study the line graph. What was the temperature of the water at 6 minutes?", o: ["52 °C", "76 °C", "88 °C", "64 °C"], a: 3, why: "Reading up from 6 min on the x-axis, the line is at 64 °C. 52 °C is at 4 min and 76 °C at 8 min.", lvl: 1, fig: { type: "line", title: "Temperature of water being heated", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 28], ["2", 40], ["4", 52], ["6", 64], ["8", 76], ["10", 88]] } },
    { q: "Which unit is used for the volume of a liquid?", o: ["ml", "g", "°C", "cm"], a: 0, why: "Volume of a liquid is measured in millilitres (ml) or cm³. g is for mass, °C for temperature and cm for length.", lvl: 1 },
    { q: "Study the set-ups. What is the variable changed in this experiment?", o: ["The volume of hot water", "The starting temperature of the water", "The type of material wrapped around the can", "The size of the can"], a: 2, why: "Only the wrapping material differs (cotton, wool, felt). The volume, starting temperature and can size are the same in all three, so they are kept constant.", lvl: 1, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Can wrapped in cotton", "200 ml hot water", "Starts at 80 °C"] }, { label: "B", icon: "jar", lines: ["Can wrapped in wool", "200 ml hot water", "Starts at 80 °C"] }, { label: "C", icon: "jar", lines: ["Can wrapped in felt", "200 ml hot water", "Starts at 80 °C"] }] } },
    { q: "Nora measured the temperature of a cup of water every minute for 10 minutes. Which is the most suitable way to show her results?", o: ["Bar graph", "Line graph", "Venn diagram", "Classification flowchart"], a: 1, why: "A line graph shows how something changes continuously over time. A bar graph is for comparing separate groups, such as types of material.", lvl: 1 },
    { q: "Study the bar graph. In which container did the ice cube take the longest time to melt?", o: ["Metal", "Glass", "Plastic", "Styrofoam"], a: 3, why: "The Styrofoam bar is the tallest (70 min), so the ice cube there took the longest time to melt. The metal container had the shortest time (20 min).", lvl: 1, fig: { type: "bar", title: "Time taken for an ice cube to melt", xl: "Container", yl: "Time taken (min)", bars: [["Metal", 20], ["Glass", 38], ["Plastic", 45], ["Styrofoam", 70]] } },
    { q: "When reading the volume of water in a measuring cylinder, where should Jun’s eye be?", o: ["Level with the bottom of the curved water surface", "Above the water surface, looking down at it", "Below the water surface, looking up at it", "Level with the top rim of the measuring cylinder"], a: 0, why: "The eye must be level with the bottom of the curved surface of the water. Looking from above or below gives a reading that is too high or too low.", lvl: 1 },

    { q: "Study the set-ups. Which two should be compared to find out if the number of leaves on a plant affects the volume of water it takes in?", o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "A and B differ only in the number of leaves (10 and 5). A and C differ in both leaves and volume of water; B and D differ in leaves and place.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["Plant with 10 leaves", "100 ml of water", "Near a window"] }, { label: "B", icon: "pot", lines: ["Plant with 5 leaves", "100 ml of water", "Near a window"] }, { label: "C", icon: "pot", lines: ["Plant with 5 leaves", "200 ml of water", "Near a window"] }, { label: "D", icon: "pot", lines: ["Plant with 10 leaves", "100 ml of water", "In a dark room"] }] } },
    { q: "Study the graph. During which 5 minutes did the temperature of the water drop the fastest?", o: ["0 to 5 min", "5 to 10 min", "10 to 15 min", "20 to 25 min"], a: 0, why: "The line is steepest from 0 to 5 min, a drop of 18 °C (80 to 62 °C). Later drops are 12 °C, 8 °C and only 3 °C.", lvl: 2, fig: { type: "line", title: "Temperature of hot water cooling", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 80], ["5", 62], ["10", 50], ["15", 42], ["20", 37], ["25", 34]] } },
    { q: "Study the table. Hui Min lowered a stone completely into the water in a measuring cylinder. What is the volume of the stone?", o: ["50 cm³", "68 cm³", "118 cm³", "18 cm³"], a: 3, why: "The volume of the stone equals the rise in water level: 68 − 50 = 18 cm³. 68 cm³ is the reading of water and stone together.", lvl: 2, tbl: [["Reading", "Volume (cm³)"], ["Water only", "50"], ["Water and stone", "68"]] },
    { q: "Study the set-ups. Why did Mrs Tan set up tube B?", o: ["To show that egg white dissolves in water without any digestive juice", "As a control, to show any change in A is caused by the digestive juice", "To make the egg white in tube A break down faster than usual", "To test whether a different type of food is also digested"], a: 1, why: "B is identical to A except that the digestive juice is replaced by water, so it is the control used for comparison. It shows that any change in A is due to the digestive juice.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Egg white cube", "10 ml digestive juice", "Kept at 37 °C"] }, { label: "B", icon: "jar", lines: ["Egg white cube", "10 ml water", "Kept at 37 °C"] }] } },
    { q: "Study the graph of light sensor readings at different distances from a torch. Which statement describes the trend?", o: ["As the distance increases, the reading increases.", "The reading stays the same at all distances.", "As the distance increases, the reading decreases.", "The reading decreases, then increases."], a: 2, why: "The reading falls from 900 at 10 cm to 200 at 50 cm, so less light reaches the sensor the further it is from the torch.", lvl: 2, fig: { type: "line", title: "Light reaching the sensor", xl: "Distance from torch (cm)", yl: "Light sensor reading (lux)", pts: [["10", 900], ["20", 600], ["30", 400], ["40", 280], ["50", 200]] } },
    { q: "Siti repeated her experiment three times and found the average of her results. Why?", o: ["To make the test fair", "To have a new variable to test", "To finish the experiment faster", "To make her results more reliable"], a: 3, why: "Repeating and averaging makes results more reliable. It does not make a test fair; fairness comes from changing only one variable.", lvl: 2 },
    { q: "Study the graph. It shows the time taken for a wax bead at one end of each rod to melt when the other end was heated. Which rod is the best conductor of heat?", o: ["Steel", "Iron", "Copper", "Aluminium"], a: 2, why: "Heat travelled along copper the fastest, so its wax melted in the shortest time (25 s). The tallest bar (steel) shows the poorest conductor of the four.", lvl: 2, fig: { type: "bar", title: "Time taken for wax to melt", xl: "Material of rod", yl: "Time taken (s)", bars: [["Copper", 25], ["Aluminium", 35], ["Iron", 60], ["Steel", 80]] } },
    { q: "Leong wants to find out if the material of a cup affects how fast hot water in it cools. Study his set-ups. Which change would make his test fair?", o: ["Use 50 ml of water in cup B", "Use water at 60 °C in cup C", "Use a plastic cup for B", "Measure cup A after 5 minutes only"], a: 0, why: "Cup B has 80 ml while A and C have 50 ml, so the volume is a second variable. Using 50 ml in B leaves only the material different.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Plastic cup", "50 ml water", "Starts at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Metal cup", "80 ml water", "Starts at 80 °C"] }, { label: "C", icon: "beaker", lines: ["Glass cup", "50 ml water", "Starts at 80 °C"] }] } },
    { q: "Study the table. Which conclusion can be drawn from the MASS readings?", o: ["Air has no definite shape.", "Air has mass.", "Air cannot be compressed.", "The ball has no mass."], a: 1, why: "The mass of the ball increased from 400 g to 405 g when air was pumped in, so air has mass. ‘No definite shape’ is true of air but is not shown by mass readings.", lvl: 2, tbl: [["Ball", "Mass (g)"], ["Before pumping in air", "400"], ["After pumping in air", "405"]] },
    { q: "Which is the correct way to measure the temperature of water in a beaker with a thermometer?", o: ["Keep the bulb in the water, away from the beaker, and read once the reading is steady", "Take the thermometer out of the water and then read it quickly at eye level", "Let the bulb rest on the bottom of the beaker and read it as soon as it is in", "Hold the bulb in your hand to warm it first, then put it in the water"], a: 0, why: "The bulb must stay in the water without touching the container, and you read once the reading is steady. Out of the water, the reading changes towards the air temperature.", lvl: 2 },
    { q: "Study the graph. Mrs Lee wants curtains that block the most light for her bedroom. Which cloth should she choose?", o: ["Cloth A", "Cloth C", "Cloth D", "Cloth B"], a: 3, why: "Cloth B gave the lowest light sensor reading (20), so the least light passed through it. Cloth D let the most light through.", lvl: 2, fig: { type: "bar", title: "Light passing through cloths", xl: "Cloth", yl: "Light sensor reading (lux)", bars: [["A", 300], ["B", 20], ["C", 150], ["D", 600]] } },
    { q: "Study the Venn diagram. Where should a steel spoon be placed?", o: ["In circle X only", "In circle Y only", "In the overlap of X and Y", "Outside both circles"], a: 1, why: "Steel is a good conductor of heat but it is opaque, so it belongs in circle Y only. Glass lets light through but is a poor conductor of heat.", lvl: 2, fig: { type: "venn", a: "X: Lets most light through", b: "Y: Good conductor of heat", onlyA: ["glass", "clear plastic"], both: [], onlyB: ["copper", "aluminium"], neither: ["wood", "rubber"] } },
    { q: "Study the set-ups. Siti recorded the time taken for each ice cube to melt completely. What is the aim of her experiment?", o: ["To find out if the temperature of the surroundings affects the time taken for ice to melt", "To find out if the type of container affects the time taken for ice to melt", "To find out if the size of the ice cube affects how fast it melts", "To find out if ice is a solid"], a: 0, why: "Only the place (fridge, classroom, under the sun) differs, and these have different temperatures. The container and ice cube are the same, so they are not being tested.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["1 ice cube, 10 g", "Metal dish", "In a refrigerator"] }, { label: "B", icon: "plate", lines: ["1 ice cube, 10 g", "Metal dish", "In the classroom"] }, { label: "C", icon: "plate", lines: ["1 ice cube, 10 g", "Metal dish", "Under the sun"] }] } },
    { q: "A flask of coloured water with a glass tube was placed in water baths of different temperatures. Study the graph. What is the most likely height of the coloured water at 80 °C?", o: ["7.4 cm", "8.0 cm", "8.6 cm", "6.8 cm"], a: 1, why: "The height rises by 0.6 cm for every 10 °C, so at 80 °C it is about 7.4 + 0.6 = 8.0 cm. 7.4 cm is the reading at 70 °C.", lvl: 2, fig: { type: "line", title: "Height of coloured water in tube", xl: "Temperature of water bath (°C)", yl: "Height of water in tube (cm)", pts: [["30", 5.0], ["40", 5.6], ["50", 6.2], ["60", 6.8], ["70", 7.4]] } },

    { q: "Meiling cut a leafy shoot from a balsam plant and placed the bottom of its stem in red-coloured water. After 3 hours, the leaves had red streaks. Which conclusions are supported by this result?\nA: The stem carries water from its bottom end up to the leaves.\nB: The red colouring lets us see the path taken by the water.\nC: The stem carries food made in the leaves to other parts of the plant.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "The red water travelled up the stem to the leaves, so A is supported, and the dye is what makes the water’s path visible (B). The stem does carry food too, but this experiment only traced water, so C is not shown by the result.", lvl: 3 },
    { q: "Study the graph of the temperature of water in a can left in the sun. Which conclusion is supported by the data?", o: ["The water will reach 50 °C after 70 minutes if left in the sun.", "The temperature of the water rose most quickly in the first 10 minutes.", "The water gained heat at the same rate throughout the 40 minutes.", "The water stopped gaining heat after 20 minutes in the sun."], a: 1, why: "The rise was 6 °C in the first 10 min, then 5, 3, 1 and 0 °C, so the rise was fastest at the start. The line is still rising at 20–40 min, and it levels off at 43 °C, so 50 °C is not supported.", lvl: 3, fig: { type: "line", title: "Water in a can left in the sun", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 28], ["10", 34], ["20", 39], ["30", 42], ["40", 43], ["50", 43]] } },
    { q: "Joe wants to find out if the colour of a can affects how fast the water in it gains heat. Study the set-ups. Which two should he use?", o: ["A and B", "A and D", "B and C", "A and C"], a: 3, why: "A and C differ only in colour. A and B differ in colour and place; A and D differ in volume; B and C differ in place.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Black can", "200 ml water", "In the sun"] }, { label: "B", icon: "jar", lines: ["White can", "200 ml water", "In the shade"] }, { label: "C", icon: "jar", lines: ["White can", "200 ml water", "In the sun"] }, { label: "D", icon: "jar", lines: ["Black can", "100 ml water", "In the sun"] }] } },
    { q: "Water at 80 °C was poured into four cups. Study the graph of the temperature of the water after 20 minutes. How much MORE did the temperature of the water in the metal cup drop than in the Styrofoam cup?", o: ["30 °C", "40 °C", "10 °C", "70 °C"], a: 0, why: "Metal: 80 − 40 = 40 °C drop. Styrofoam: 80 − 70 = 10 °C drop. The difference is 40 − 10 = 30 °C.", lvl: 3, fig: { type: "bar", title: "Temperature after 20 minutes", xl: "Material of cup", yl: "Temperature (°C)", bars: [["Metal", 40], ["Glass", 52], ["Plastic", 58], ["Styrofoam", 70]] } },
    { q: "Bala tested whether seedlings take in more water in the sun or in the shade, using one seedling in each place. Which change would make his results more reliable without making the test unfair?", o: ["Use a bigger seedling in the sun", "Change the volume of water in each set-up as well", "Use 10 similar seedlings in each place and find the average", "Use a different type of plant in each place"], a: 2, why: "More seedlings of the same kind in each place, averaged, give more trustworthy results and keep only one variable (the place) changed. The other choices add a second variable.", lvl: 3 },
    { q: "Study the diagram of the human digestive system. In which of the labelled parts is food digested?", o: ["P and Q only", "Q and R only", "Q, R and S only", "P, Q, R and S"], a: 1, why: "Digestive juices break down food in the stomach (Q) and small intestine (R). The gullet (P) only moves food to the stomach, and the large intestine (S) absorbs water; no digestion takes place there.", lvl: 3, fig: { type: "organs", system: "digestive", mark: { gullet: "P", stomach: "Q", small_intestine: "R", large_intestine: "S" } } },
    { q: "Study the graph of the height of a shadow as an object is moved away from a torch. Which statement is correct?", o: ["The shadow is largest when the object is furthest away from the torch.", "The shadow height decreases by the same amount for every 10 cm moved.", "As the object moves away, the shadow shrinks, but by less with each further 10 cm.", "The shadow would disappear completely once the object reached 60 cm."], a: 2, why: "The height drops 12, 4, 2 and 1 cm for each 10 cm step, so it keeps getting smaller but by less each time. Nothing in the data shows the shadow disappearing.", lvl: 3, fig: { type: "line", title: "Height of shadow on screen", xl: "Distance of object from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 30], ["20", 18], ["30", 14], ["40", 12], ["50", 11]] } },
    { q: "Faizal wants to find out whether the amount of air pumped into a ball affects how high it bounces. Which variable must he keep the same?", o: ["The number of pumps of air", "The height the ball bounces", "The height from which the ball is dropped", "The mass of the ball after pumping"], a: 2, why: "The drop height could affect the bounce, so it must be kept the same. The number of pumps is the variable changed, the bounce height is measured, and the mass changes because air has mass.", lvl: 3 },
    { q: "Study the graph. It shows light sensor readings with 1 to 4 sheets of material P placed in front of a torch. What can be concluded?", o: ["Sheet P is opaque because it blocks some of the light.", "The more sheets of P there are, the less light passes through.", "Five sheets of P will allow no light at all to pass through.", "Sheet P allows all the light from the torch to pass through."], a: 1, why: "The reading falls from 800 to 350 as sheets are added, so less light passes through. Even 4 sheets let light through, so P is not opaque; ‘no light at 5 sheets’ is beyond the data.", lvl: 3, fig: { type: "bar", title: "Light through sheets of P", xl: "Number of sheets", yl: "Light sensor reading (lux)", bars: [["1", 800], ["2", 620], ["3", 480], ["4", 350]] } },
    { q: "Study the table. Ah Hock lowered 5 identical marbles fully into the water in a measuring cylinder. What is the volume of ONE marble?", o: ["15 cm³", "55 cm³", "3 cm³", "11 cm³"], a: 2, why: "The water rose by 55 − 40 = 15 cm³ for 5 marbles, so one marble is 15 ÷ 5 = 3 cm³. 15 cm³ is the volume of all five.", lvl: 3, tbl: [["Reading", "Volume (cm³)"], ["Water only", "40"], ["Water and 5 marbles", "55"]] },
    { q: "To find out if roots are needed for a plant to take in water, Mei set up the containers shown. A layer of oil stops water escaping into the air from the containers. Why was set-up C included?", o: ["To show that plants need roots to take in water from the container", "To show that the layer of oil absorbs water from the container", "To make sure the plants in A and B got enough light to grow", "To show that any drop in the water in A and B was caused by the plants"], a: 3, why: "C has no plant but is otherwise the same, so if its water level stays the same, any drop in A and B must be due to the plants taking in water. It does not by itself show that roots are needed; that comes from comparing A and B.", lvl: 3, fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Plant with roots", "100 ml water", "Layer of oil"] }, { label: "B", icon: "jar", lines: ["Plant, roots cut off", "100 ml water", "Layer of oil"] }, { label: "C", icon: "jar", lines: ["No plant", "100 ml water", "Layer of oil"] }] } },
    { q: "Study the graph of the volume of water absorbed by different numbers of layers of paper towel. Which conclusion is valid?", o: ["For 1 to 5 layers, the more layers there are, the more water is absorbed.", "10 layers of paper towel will absorb 100 ml of water altogether.", "Every extra layer of paper towel absorbs exactly 10 ml more water.", "Paper towel absorbs more water than cloth of the same size."], a: 0, why: "The volume rises from 10 ml to 40 ml as layers go from 1 to 5, within the range tested. The increase gets smaller (9, 8, 7, 6 ml), so ‘exactly 10 ml’ and ‘100 ml at 10 layers’ are wrong, and cloth was not tested.", lvl: 3, fig: { type: "line", title: "Water absorbed by paper towel", xl: "Number of layers", yl: "Volume absorbed (ml)", pts: [["1", 10], ["2", 19], ["3", 27], ["4", 34], ["5", 40]] } },

    { q: "Three identical flasks of coloured water, each fitted with a glass tube, were wrapped in materials X, Y and Z and placed in the same hot water bath. Study the table. Which statements are correct?\nA: Y is the best conductor of heat of the three.\nB: X is the most suitable of the three for lining a cooler bag.\nC: The water in Z gained heat faster than the water in Y.", o: ["A only", "B and C only", "A and B only", "A, B and C"], a: 2, why: "The water in Y rose the most, so heat reached it fastest through Y (best conductor). X let the least heat through, so it is best for keeping a cooler bag cold. Z’s water rose less than Y’s, so C is wrong.", lvl: 4, tbl: [["Wrapping material", "Rise in water level after 5 min (cm)"], ["X", "2"], ["Y", "6"], ["Z", "4"]] },
    { q: "Study the graph of light sensor readings taken in a garden on one day. Which statement is NOT supported by the data?", o: ["The reading was highest at about 1 pm.", "The reading increased from 7 am to 1 pm.", "The reading at 4 pm was probably between 300 and 700.", "The garden is brightest at 1 pm every day."], a: 3, why: "Readings were taken on only one day, so we cannot say what happens every day (cloudy days differ). The other three are read from, or lie between, the plotted points.", lvl: 4, fig: { type: "line", title: "Light in a garden on one day", xl: "Time of day", yl: "Light sensor reading (lux)", pts: [["7am", 100], ["9am", 400], ["11am", 800], ["1pm", 950], ["3pm", 700], ["5pm", 300]] } },
    { q: "Rahim wants to find out if the material of a cup affects how fast hot water in it cools. Study the set-ups. Which statement is correct?", o: ["Only A and C can be compared, as B differs in both material and having no lid.", "A and B can be compared, because they hold the same volume of hot water.", "B and C can be compared, because both are made of poor conductors of heat.", "A, B and C can all be compared, because the water in all starts at 80 °C."], a: 0, why: "A and C differ only in material. B differs from A and from C in material AND in having no lid, and a lid affects heat loss, so B cannot be compared with either.", lvl: 4, fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Metal cup, with lid", "100 ml water", "Starts at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Plastic cup, no lid", "100 ml water", "Starts at 80 °C"] }, { label: "C", icon: "beaker", lines: ["Glass cup, with lid", "100 ml water", "Starts at 80 °C"] }] } },
    { q: "Study the table of light sensor readings for three sheets, each tested three times. Which statement is correct?", o: ["K and L have the same average, but L’s readings vary more, so they are less reliable.", "L lets the most light through because it has the highest single reading.", "M has the highest average reading, so M lets the most light through of all.", "All three sheets have the same average reading, so they are equally reliable."], a: 0, why: "K: (310 + 290 + 300) ÷ 3 = 300. L: (150 + 450 + 300) ÷ 3 = 300. M: 830 ÷ 3 ≈ 277. L’s readings are spread far apart, so they are less reliable, and one high reading does not decide the result.", lvl: 4, tbl: [["Sheet", "Trial 1", "Trial 2", "Trial 3"], ["K", "310", "290", "300"], ["L", "150", "450", "300"], ["M", "280", "300", "250"]] },
    { q: "Study the classification chart. Mei sorted a steel nail, a copper wire, a glass marble, a rubber band and a piece of aluminium foil. Which two objects end up in the same group?", o: ["Steel nail and copper wire", "Glass marble and aluminium foil", "Rubber band and steel nail", "Aluminium foil and copper wire"], a: 3, why: "Aluminium and copper are not magnetic, do not let light through and are good conductors of heat, so both end at C. Steel goes to A, glass to B and rubber to D.", lvl: 4, fig: { type: "flow", root: "Objects", node: { q: "Attracted by a magnet?", yes: "A", no: { q: "Lets most light through?", yes: "B", no: { q: "Good heat conductor?", yes: "C", no: "D" } } } } },
    { q: "Two syringes each held 50 ml: syringe P held air and syringe Q held water. Their nozzles were sealed and the plungers pushed hard. P’s plunger moved to 30 ml; Q’s plunger did not move. Which conclusions are supported?\nA: Air can be compressed.\nB: Water has a definite volume.\nC: Air does not have a definite volume.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "The air was squashed into a smaller volume, so air can be compressed and has no definite volume. The water kept its 50 ml volume, which fits water having a definite volume.", lvl: 4 }
  ],
  tf: [
    { s: "A control set-up is identical to the experimental set-up except for the variable being tested.", a: true, why: "That single difference lets you show the result is caused by that variable." },
    { s: "Repeating an experiment three times makes it a fair test.", a: false, why: "Repeating and averaging makes results reliable; changing only one variable makes a test fair." },
    { s: "A line graph is suitable for showing how the temperature of water changes over time.", a: true, why: "Line graphs show continuous change, such as temperature with time." },
    { s: "A measuring cylinder should be read at the top of the curved water surface.", a: false, why: "Read at eye level at the bottom of the curved surface." },
    { s: "An electronic balance measures mass in grams or kilograms.", a: true, why: "Mass is measured in g or kg." },
    { s: "A light sensor measures how hot a lamp is.", a: false, why: "A light sensor measures the amount of light; a thermometer or temperature sensor measures how hot something is." },
    { s: "Changing two variables at once gives a result that is just as useful, only faster.", a: false, why: "With two variables changed, you cannot tell which one caused the result." },
    { s: "A flat part of a line graph shows that the value measured did not change during that time.", a: true, why: "A horizontal line means no change." },
    { s: "In a wax-melting test on rods, the rod that takes the longest time is the best conductor of heat.", a: false, why: "The best conductor lets heat travel fastest, so its wax melts in the SHORTEST time." },
    { s: "The variable measured is the result that is recorded in the experiment.", a: true, why: "It is what you measure, count or observe." },
    { s: "If copper, iron and aluminium are good conductors of heat, we can conclude that all materials are good conductors.", a: false, why: "Conclusions apply only to what was tested; wood and plastic, for example, are poor conductors." },
    { s: "When measuring the temperature of water, the thermometer bulb should not touch the bottom of the beaker.", a: true, why: "Touching the container may give the container’s temperature instead of the water’s." },
    { s: "A higher light sensor reading behind a sheet means the sheet is more opaque.", a: false, why: "A higher reading means MORE light passes through, so the sheet is less opaque." },
    { s: "Using 10 plants in each set-up instead of 1 makes the results more reliable.", a: true, why: "A larger number evens out one unusual plant." },
    { s: "A hypothesis is the same as a conclusion.", a: false, why: "A hypothesis is a testable statement made before the experiment; the conclusion is drawn from the results." },
    { s: "The steepest part of a line graph shows where the change is fastest.", a: true, why: "A steeper line means a bigger change in the same time." },
    { s: "The volume of an irregular stone can only be found with an electronic balance.", a: false, why: "An electronic balance measures mass. The volume is found from the rise in water level in a measuring cylinder." },
    { s: "When using a thermometer, you should wait until the reading stops changing before reading it.", a: true, why: "The reading is correct only once it is steady." },
    { s: "The variable changed is usually plotted on the vertical (y) axis of a graph.", a: false, why: "The variable changed goes on the horizontal (x) axis; the variable measured goes on the y-axis." },
    { s: "In a CER answer, the evidence should quote the data with units.", a: true, why: "Quoted data with units and a comparison word shows the claim is supported." }
  ],
  sort: [
    {
      title: "Wei Ming tests how fast hot water cools in cups of different materials, measuring the temperature after 15 minutes. Sort each item.",
      groups: ["Variable changed", "Variable measured", "Variable kept the same"],
      items: [["Type of material of the cup", 0], ["Temperature of the water after 15 minutes", 1], ["Volume of hot water", 2], ["Starting temperature of the water", 2], ["Size of the cup", 2], ["Place where the cups are left", 2], ["Time before measuring", 2], ["Drop in temperature of the water", 1]]
    },
    {
      title: "Which instrument would you use to measure each of these?",
      groups: ["Thermometer", "Measuring cylinder", "Electronic balance", "Light sensor"],
      items: [["Temperature of bath water", 0], ["How hot soup is in °C", 0], ["Volume of milk in ml", 1], ["Volume of a stone by displacement", 1], ["Mass of a durian", 2], ["Mass of a football before and after pumping", 2], ["Light passing through tracing paper", 3], ["Brightness in a classroom", 3]]
    },
    {
      title: "Does each action make the test FAIR or the results more RELIABLE?",
      groups: ["Makes the test fair", "Makes results more reliable"],
      items: [["Use the same volume of water in each cup", 0], ["Repeat the experiment 3 times", 1], ["Find the average of the readings", 1], ["Start all cups at the same temperature", 0], ["Use 10 seedlings instead of 1", 1], ["Change only the type of material", 0], ["Keep the torch at the same distance", 0], ["Test several pieces of each material", 1]]
    }
  ],
  oe: [
    { q: "Study the set-ups. Wei Ming measured the temperature of the water in each cup after 15 minutes.\n(a) State the variable changed. [1]\n(b) State the variable measured. [1]\n(c) State one variable he kept the same. [1]", marks: 3, kw: [["material"], ["temperature"], ["volume", "amount of water", "starting temperature", "initial temperature", "size of the cup", "same size", "place", "location"]], model: "(a) The type of material the cup is made of. (b) The temperature of the water in the cup after 15 minutes. (c) The volume of water in each cup.", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Metal cup", "200 ml water", "Starts at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Glass cup", "200 ml water", "Starts at 80 °C"] }, { label: "C", icon: "beaker", lines: ["Plastic cup", "200 ml water", "Starts at 80 °C"] }] } },
    { q: "Mrs Lim shone a torch through four cloths, one at a time, and recorded the light sensor readings shown.\n(a) Which cloth is most suitable for blackout curtains? [1]\n(b) Use the data to explain your answer. [1]\n(c) Why did she keep the torch at the same distance from the sensor each time? [1]", marks: 3, kw: [["felt"], ["lowest", "least", "smallest", "20"], ["fair", "only the type", "only one"]], model: "(a) Felt. (b) Felt gave the lowest reading, 20 lux, so the least light passed through it. (c) To make it a fair test, so that only the type of cloth affects the light sensor reading.", fig: { type: "bar", title: "Light passing through cloths", xl: "Cloth", yl: "Light sensor reading (lux)", bars: [["Lace", 620], ["Satin", 350], ["Canvas", 90], ["Felt", 20]] } },
    { q: "A flask of coloured water fitted with a glass tube was placed in water baths of different temperatures. Study the graph.\n(a) Describe the relationship between the temperature of the water bath and the height of the coloured water. [1]\n(b) Explain why the coloured water rose up the tube. [2]\n(c) Predict the height at 80 °C. [1]", marks: 4, kw: [["increase", "rise", "higher"], ["gain", "gains heat", "gained heat"], ["expand"], ["8.0", "8 cm", "8cm"]], model: "(a) As the temperature of the water bath increases, the height of the coloured water in the tube increases. (b) The coloured water gains heat from the water bath and expands, so it moves up the tube. (c) About 8.0 cm.", fig: { type: "line", title: "Height of coloured water in tube", xl: "Temperature of water bath (°C)", yl: "Height of water in tube (cm)", pts: [["30", 5.0], ["40", 5.6], ["50", 6.2], ["60", 6.8], ["70", 7.4]] }, x: 1 },
    { q: "Farah put one balsam seedling in a beaker of 100 ml of water to find out how much water it takes in over 3 days. Suggest two ways to make her results more reliable. [2]", marks: 2, kw: [["repeat"], ["more seedlings", "more plants", "10 seedlings", "10 plants", "larger number", "greater number", "several seedlings"]], model: "Repeat the experiment 3 times and find the average volume of water taken in. Use more seedlings, for example 10 seedlings, instead of just one." },
    { q: "Study the set-ups. After one day, the egg white cube in tube A was much smaller, while the cube in tube B did not change.\n(a) Why was tube B set up? [1]\n(b) Why were the tubes kept at 37 °C? [1]\n(c) Explain why the cube in tube A became smaller. [2]", marks: 4, kw: [["control", "compar"], ["body temperature", "human body", "inside the body", "temperature of the body"], ["digestive juice"], ["break down", "broken down", "broke down", "breaks down", "digest"]], model: "(a) Tube B is the control, used for comparison to show that the change in A is caused by the digestive juice. (b) 37 °C is the human body temperature, so it is like the conditions inside the body. (c) The digestive juice broke down the egg white into simpler substances, so the cube became smaller.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Egg white cube", "10 ml digestive juice", "Kept at 37 °C"] }, { label: "B", icon: "jar", lines: ["Egg white cube", "10 ml water", "Kept at 37 °C"] }] } },
    { q: "Meiling placed leafy balsam shoot A in red-coloured water and an identical shoot B in plain water. After 3 hours, the leaves of A had red streaks, but the leaves of B did not change.\n(a) Which part of the shoot carried the coloured water up to the leaves? [1]\n(b) Why was red colouring added to the water? [1]\n(c) Why was shoot B set up? [1]", marks: 3, kw: [["stem"], ["see", "seen", "path", "trace", "track", "visible"], ["control", "compar"]], model: "(a) The stem. (b) So that we can see the path the water takes up the stem to the leaves. (c) Shoot B is the control, used for comparison to show that the red streaks in A are caused by the red-coloured water travelling up the stem." },
    { q: "Study the graph of the time taken for a wax bead at the end of each rod to melt when the other end is heated. Which material is the most suitable for the handle of a frying pan? Explain your answer using the data. [3]", marks: 3, kw: [["wood"], ["longest", "most time", "600"], ["poor conductor", "poorest conductor", "slowly", "slowest"]], model: "Wood. The wax on the wood rod took the longest time to melt, 600 s. This shows wood is the poorest conductor of heat, so it conducts heat from the pan to the hand the most slowly.", fig: { type: "bar", title: "Time taken for wax to melt", xl: "Material of rod", yl: "Time taken (s)", bars: [["Copper", 30], ["Steel", 90], ["Glass", 240], ["Wood", 600]] } },
    { q: "A cup of hot water was left on a table. Study the graph.\n(a) Describe how the temperature of the water changed. [1]\n(b) Explain why the temperature dropped. [1]\n(c) Explain why the temperature stayed at 30 °C after 50 minutes. [1]", marks: 3, kw: [["decrease", "drop", "fell", "fall", "lower"], ["lose heat", "loses heat", "lost heat"], ["room temperature", "surrounding"]], model: "(a) The temperature decreased quickly at first, from 80 °C to 55 °C in 10 minutes, then more slowly until it stayed at 30 °C. (b) The water lost heat to the cooler surroundings. (c) The water had reached room temperature, the same temperature as the surroundings, so it stopped losing heat.", fig: { type: "line", title: "Temperature of water on a table", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 80], ["10", 55], ["20", 42], ["30", 35], ["40", 31], ["50", 30], ["60", 30]] } },
    { q: "Study the table. Kumar lowered a key completely into the water in a measuring cylinder.\n(a) What is the volume of the key? [1]\n(b) Why must the key be completely under the water? [1]", marks: 2, kw: [["20"], ["whole", "fully", "completely", "entire", "all of"]], model: "(a) 20 cm³. (b) So that the whole key takes up space in the water and pushes the water up by its full volume.", tbl: [["Reading", "Volume (cm³)"], ["Water only", "45"], ["Water and key", "65"]] },
    { q: "Joe wanted to find out if the colour of a can affects how fast the water in it gains heat. Study his set-ups.\n(a) Explain why his experiment is not a fair test. [1]\n(b) Suggest one change to make it fair. [1]", marks: 2, kw: [["volume", "amount of water"], ["200"]], model: "(a) The volume of water is different as well as the colour of the can, so he cannot tell which one caused the difference. (b) Put 200 ml of water in can B as well.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Black can", "200 ml water", "In the sun"] }, { label: "B", icon: "jar", lines: ["White can", "100 ml water", "In the sun"] }] } },
    { q: "Study the graph. A wooden block was moved away from a torch, and the height of its shadow on a screen was measured.\n(a) Describe the relationship between the distance of the block from the torch and the height of the shadow. [1]\n(b) Explain how the shadow is formed. [2]", marks: 3, kw: [["smaller", "shorter", "decrease"], ["block"], ["straight line"]], model: "(a) As the distance of the block from the torch increases, the height of the shadow decreases. (b) Light travels in straight lines. The wooden block is opaque and blocks the light, so a dark area, the shadow, forms on the screen behind it.", fig: { type: "line", title: "Height of shadow on screen", xl: "Distance of block from torch (cm)", yl: "Height of shadow (cm)", pts: [["10", 30], ["20", 18], ["30", 14], ["40", 12], ["50", 11]] }, x: 1 },
    { q: "Study the graph. A deflated ball was weighed, then air was pumped in and it was weighed again after every 5 pumps.\n(a) What does the result show about air? [1]\n(b) Predict the mass of the ball after 20 pumps. [1]", marks: 2, kw: [["mass"], ["412"]], model: "(a) Air has mass, because the mass of the ball increased as more air was pumped in. (b) 412 g.", fig: { type: "bar", title: "Mass of ball", xl: "Number of pumps", yl: "Mass (g)", bars: [["0", 400], ["5", 403], ["10", 406], ["15", 409]] } },
    { q: "Ravi put the same volume of cold water at 5 °C into three identical containers, each wrapped in a different material, and measured the temperature after 30 minutes. Study the table.\n(a) State the variable changed. [1]\n(b) Name the instrument he used to measure the temperature. [1]\n(c) Which material is best for a cooler bag? [1]\n(d) Explain your answer to (c). [1]", marks: 4, kw: [["material"], ["thermometer", "temperature sensor", "datalogger"], ["felt"], ["least heat", "gained the least", "poorest conductor", "poor conductor", "slowest", "lowest"]], model: "(a) The type of material wrapped around the container. (b) A thermometer. (c) Felt. (d) The water in the felt-wrapped container had the lowest temperature, 12 °C, so it gained the least heat. Felt is the poorest conductor of heat of the three.", tbl: [["Wrapping material", "Temperature after 30 min (°C)"], ["Cotton", "18"], ["Felt", "12"], ["Aluminium foil", "24"]], x: 1 },
    { q: "Siti tested a copper rod and an iron rod and found that both were good conductors of heat. She concluded, ‘All metals are good conductors of heat.’ Explain why her conclusion is not valid and suggest what she should do. [2]", marks: 2, kw: [["only two", "only tested", "only copper", "two metals"], ["more metals", "other metals", "more types", "more kinds", "different metals"]], model: "She only tested two metals, copper and iron, so she cannot conclude about all metals. She should test more types of metals, such as aluminium and steel, before making the conclusion." }
  ],
  doc: [
    { q: "Rani dipped same-sized pieces of cotton, wool and nylon into 100 ml of water and measured the water left after each was removed. State the variable measured. [1]", marks: 1, answers: ["The water.", "The volume of water left in the beaker after each piece is removed.", "The type of material."], best: 1, why: "Answer 2 names the variable in full: what is measured (volume) and of what (water left). Answer 1 is too vague, and answer 3 is the variable changed, not measured." },
    { q: "Why did Siti repeat her experiment three times and take the average? [1]", marks: 1, answers: ["To make it a fair test.", "So that the results are correct.", "To make her results more reliable."], best: 2, why: "Repeating and averaging makes results more reliable. ‘Fair’ is a different idea (one variable changed), and ‘correct’ is too vague to score." },
    { q: "Using the graph of time taken for wax to melt, explain why copper is the best conductor of heat. [2]", marks: 2, answers: ["The wax on the copper rod melted in the shortest time, 30 s, so heat travelled along copper the fastest.", "Copper is a metal, so it is the best.", "Copper had the tallest bar."], best: 0, why: "Answer 1 quotes the data with a comparison word and links it to heat travelling fastest. Answer 2 gives no evidence, and answer 3 is wrong: copper had the SHORTEST bar." },
    { q: "Describe the trend shown in the graph of light sensor reading against distance from a torch. [1]", marks: 1, answers: ["The line goes down.", "As the distance from the torch increases, the light sensor reading decreases.", "The torch is less bright."], best: 1, why: "Answer 2 links both variables in a clear ‘as…, …’ relationship. Answer 1 does not name the variables, and answer 3 is wrong: the torch stays the same; less light reaches the sensor." },
    { q: "Why was tube B, with egg white and water, set up alongside tube A, with egg white and digestive juice? [2]", marks: 2, answers: ["To make the experiment fair.", "To check the result.", "As a control for comparison, to show that the change in A is caused by the digestive juice."], best: 2, why: "Answer 3 has both ideas: ‘for comparison’ and ‘caused by the digestive juice’. Answers 1 and 2 are too vague to score any mark." }
  ]
};
