window.LBZ = window.LBZ || {};
LBZ["p5-cells"] = {
  flash: [
    { f: "Define: cell", b: "The cell is the basic unit of life. All living things are made up of one or more cells." },
    { f: "Function of the cell membrane", b: "It controls the movement of substances into and out of the cell. It is found in both plant and animal cells." },
    { f: "Function of the cell wall", b: "It gives the plant cell its regular shape and support, and protects it. It is found outside the cell membrane, in plant cells only (not in animal cells)." },
    { f: "Function of the nucleus", b: "It controls all the activities of the cell. It contains genetic information, which is needed for the cell to divide." },
    { f: "Function of the cytoplasm", b: "It is the jelly-like substance where most of the activities of the cell take place." },
    { f: "Function of chloroplasts", b: "They contain chlorophyll, which traps light energy to make food for the plant." },
    { f: "Function of the large central vacuole", b: "It stores water and dissolved substances, such as sugars and mineral salts. When full of water, it helps the plant cell stay firm." },
    { f: "Three parts found in plant cells but NOT in animal cells", b: "Cell wall, chloroplasts and a large central vacuole." },
    { f: "Why do root cells have no chloroplasts?", b: "Roots are underground and do not receive light, so root cells do not need chloroplasts to trap light energy to make food." },
    { f: "Why does a plant cell have a regular shape but an animal cell does not?", b: "The plant cell has a cell wall, which gives it a regular shape. The animal cell has no cell wall, so it has an irregular shape." },
    { f: "Define: unicellular organism", b: "An organism made up of only one cell, which carries out all its life processes. Examples: amoeba, yeast, bacteria." },
    { f: "Levels of organisation, from simplest to most complex", b: "Cell → tissue → organ → system → organism." },
    { f: "Tissue vs organ", b: "A tissue is a group of similar cells working together. An organ is made up of different tissues working together to carry out a function." },
    { f: "Total magnification of a microscope", b: "Eyepiece magnification × objective lens magnification, e.g. 10× and 40× gives 400 times. At a higher magnification, cells look bigger and fewer cells are seen." },
    { f: "How do living things grow, in terms of cells?", b: "Cells divide to form new cells, so the number of cells increases. Cell division also replaces damaged or worn-out cells." }
  ],
  mcq: [
    { q: "At a hawker centre, Uncle Tan stir-fries kangkong. The kangkong leaves are green because their cells contain", o: ["a cell wall", "chloroplasts", "a nucleus", "a large vacuole"], a: 1, why: "Chloroplasts contain the green chlorophyll that traps light energy to make food. Every plant cell has a cell wall and a nucleus, including cells that are not green, such as root cells.", lvl: 1 },
    { q: "The diagram shows a plant cell. Which part contains the genetic information needed for the cell to divide?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", vacuole: "B", nucleus: "C", chloroplast: "D" } }, o: ["A", "B", "C", "D"], a: 2, why: "C is the nucleus, which contains genetic information and controls all the activities of the cell. B, the vacuole, stores water and dissolved substances.", lvl: 1 },
    { q: "Ravi has a glass slide of onion skin. On which part of the microscope should he place the slide?", o: ["Eyepiece", "Objective lens", "Focusing knob", "Stage"], a: 3, why: "The slide is placed on the stage. He looks through the eyepiece, and the focusing knob makes the image clear.", lvl: 1 },
    { q: "The bread sold in the school canteen is made using yeast. What is yeast?", o: ["A multicellular fungus", "A unicellular plant", "A unicellular fungus", "A multicellular plant"], a: 2, why: "Yeast is a fungus made up of only one cell. It is not a plant: it has no chloroplasts and cannot make its own food.", lvl: 1 },

    { q: "Which of these parts would you see in a cell from a spinach leaf? A: Cell wall  B: Chloroplasts  C: Nucleus  D: Large central vacuole", o: ["A and C only", "A, B and C only", "B, C and D only", "A, B, C and D"], a: 3, why: "A spinach leaf cell is a plant cell from a green part that receives light, so it has a cell wall, chloroplasts, a nucleus and a large central vacuole.", lvl: 2 },
    { q: "The table shows the parts found in cells X, Y and Z. Which statement is NOT correct?", tbl: [["Cell", "Cell wall", "Chloroplasts", "Nucleus"], ["X", "✓", "✓", "✓"], ["Y", "✓", "✗", "✓"], ["Z", "✗", "✗", "✓"]], o: ["Z has a regular shape.", "X can make food.", "Y could be an onion bulb cell.", "All three cells can divide."], a: 0, why: "Z has no cell wall, so it has an irregular shape – the statement is wrong. X has chloroplasts, Y fits an onion bulb cell (cell wall, no chloroplasts), and all three have a nucleus, so they can divide.", lvl: 2 },
    { q: "Mei Ling looked at a drop of water from a reservoir under a microscope. She saw tiny green organisms, each made up of only one cell with chloroplasts. Which statements about them are correct? A: They are unicellular.  B: They can make their own food.  C: They are made up of tissues.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Each organism is made up of one cell, so it is unicellular (A), and its chloroplasts trap light energy to make food (B). A unicellular organism has no tissues, so C is wrong.", lvl: 2 },
    { q: "Study the Venn diagram. Which of these could be cell X?", fig: { type: "venn", a: "Has a nucleus", b: "Has a cell wall", onlyA: ["cheek cell"], both: ["onion cell", "X"], onlyB: [], neither: ["red blood cell"] }, o: ["Amoeba", "Muscle cell", "Red blood cell", "Yeast cell"], a: 3, why: "X has both a nucleus and a cell wall, so it is a yeast cell. An amoeba and a muscle cell have a nucleus but no cell wall, and a red blood cell has neither.", lvl: 2 },
    { q: "Siti wants to find out if the thickness of the onion skin affects how clearly she can see the cells. Which two set-ups should she compare?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Thin onion skin", "Iodine added", "Viewed at 100×"] }, { label: "B", icon: "plate", lines: ["Thick onion skin", "Iodine added", "Viewed at 100×"] }, { label: "C", icon: "plate", lines: ["Thin onion skin", "No iodine", "Viewed at 100×"] }, { label: "D", icon: "plate", lines: ["Thick onion skin", "Iodine added", "Viewed at 400×"] }] }, o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ only in the thickness of the onion skin. A and C differ in iodine, B and D differ in magnification, and C and D differ in three ways.", lvl: 2 },
    { q: "The table shows four pairs of lenses for a microscope. Which two pairs give the SAME total magnification?", tbl: [["Pair", "Eyepiece", "Objective lens"], ["P", "10×", "40×"], ["Q", "5×", "40×"], ["R", "20×", "10×"], ["S", "10×", "10×"]], o: ["P and Q", "Q and R", "R and S", "P and S"], a: 1, why: "Total magnification = eyepiece × objective lens: P = 400, Q = 200, R = 200 and S = 100 times. Only Q and R are the same. The numbers are multiplied, not added.", lvl: 2 },
    { q: "Which of these is NOT a function of the nucleus?", o: ["Controls all cell activities", "Contains genetic information", "Is needed for cell division", "Controls what enters the cell"], a: 3, why: "Controlling what enters and leaves the cell is the job of the cell membrane. The nucleus controls all the activities of the cell and contains the genetic information needed for cell division.", lvl: 2 },

    { q: "A leaf is an organ. Which statement best explains why?", o: ["It is made up of different tissues working together.", "It is made up of many similar cells of one type.", "It has cells that contain chloroplasts to make food.", "It is the part of the plant where food is made."], a: 0, why: "An organ is made up of different tissues working together. Many similar cells of one type form a tissue, not an organ. The other two are true of a leaf but do not explain why it is an organ.", lvl: 3 },
    { q: "Siti prepared a slide of cheek cells. Which of these steps help her to see the parts of the cells clearly? A: Spread the cells in a thin layer on the slide.  B: Add a drop of iodine to the cells.  C: Turn the focusing knob until the image is clear.  D: Use a hand lens instead of the microscope.", o: ["A and C only", "B and D only", "A, B and C only", "A, B, C and D"], a: 2, why: "A thin layer lets light pass through, iodine stains the parts so they are easier to see, and focusing makes the image clear. A hand lens does not magnify enough to show the parts of a cell, so D is wrong.", lvl: 3 },
    { q: "In the Flower Dome at Gardens by the Bay, Jia En saw a plant with dark red leaves. A guide said that the leaves still make food. Which is the best explanation?", o: ["The red substance in the vacuoles traps light to make food.", "The leaf cells have chloroplasts, but the red colour hides the green.", "The cell walls of the leaf cells trap light energy to make food.", "The leaf cells take in food that is made by the root cells."], a: 1, why: "Red leaves still have chloroplasts with chlorophyll that traps light energy to make food; a red substance simply hides the green colour. Vacuoles and cell walls do not make food, and root cells have no chloroplasts.", lvl: 3 },
    { q: "A packet of chicken rice from a hawker centre was left on a table. The graph shows the number of bacteria on the food. Which statement best explains the change?", fig: { type: "line", xl: "Time (hours)", yl: "Number of bacteria", pts: [["0", 100], ["1", 200], ["2", 400], ["3", 800], ["4", 1600]] }, o: ["Each bacterium divided, so the number doubled every hour.", "Each bacterium grew bigger, so the number went up.", "The bacteria joined together to form a tissue.", "The number of bacteria went up by 100 every hour."], a: 0, why: "Bacteria are unicellular, so each one divides to form two new bacteria, and the number doubles every hour (100, 200, 400…). Growing bigger does not increase the number, and the rise is not a steady 100 an hour.", lvl: 3 },
    { q: "The diagram shows a plant cell. Which statements are correct? A: P is not found in animal cells.  B: Q controls the movement of substances into and out of the cell.  C: Without P, the cell would lose its regular shape.  D: Q is found outside P.", fig: { type: "cell", kind: "plant", mark: { cell_wall: "P", cell_membrane: "Q" } }, o: ["A and B only", "B and D only", "A, B and C only", "A, B, C and D"], a: 2, why: "P is the cell wall, which gives a regular shape and support and is not found in animal cells. Q is the cell membrane, which controls movement of substances. The membrane lies just INSIDE the cell wall, so D is wrong.", lvl: 3 },
    { q: "Study the Venn diagram. Which correctly identifies X and Y?", fig: { type: "venn", a: "Has chloroplasts", b: "Is a whole organism", onlyA: ["leaf cell"], both: ["X"], onlyB: ["Y"], neither: ["cheek cell"] }, o: ["X: green alga, Y: yeast", "X: yeast, Y: green alga", "X: onion cell, Y: amoeba", "X: root hair cell, Y: yeast"], a: 0, why: "X is a whole organism with chloroplasts – a single-celled green alga. Y is a whole organism without chloroplasts – yeast. Onion and root hair cells have no chloroplasts and are only parts of a plant.", lvl: 3 },

    { q: "The table shows the parts of cells K, L, M and N. Which statements are correct? A: K cannot divide.  B: L and M are unicellular organisms.  C: Of the four, only N can make food.  D: L must be a plant cell because it has a cell wall.", tbl: [["Cell", "Cell wall", "Nucleus", "Chloroplasts", "Whole organism"], ["K", "✗", "✗", "✗", "✗"], ["L", "✓", "✓", "✗", "✓"], ["M", "✗", "✓", "✗", "✓"], ["N", "✓", "✓", "✓", "✗"]], o: ["A and B only", "A, B and C only", "B and C only", "A, B, C and D"], a: 1, why: "K has no nucleus, so it cannot divide (A). L and M are each one cell that is a whole organism, so they are unicellular (B). Only N has chloroplasts (C). L fits yeast, which has a cell wall but is not a plant, so D is wrong.", lvl: 4 },
    { q: "Four cells are sorted using the chart: a cheek cell, a yeast cell, a red blood cell and an onion bulb cell. Which group receives TWO of these cells?", fig: { type: "flow", root: "Cells", node: { q: "Has a nucleus?", yes: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "P", no: "Q" }, no: "R" }, no: "S" } }, o: ["P", "R", "S", "Q"], a: 3, why: "The red blood cell has no nucleus (S); the cheek cell has a nucleus but no cell wall (R). The yeast cell and the onion bulb cell both have a nucleus and a cell wall but no chloroplasts, so both go to Q. No cell goes to P.", lvl: 4 },
    { q: "Which statements are correct? A: A leaf and the heart are at the same level of organisation.  B: An amoeba is both a cell and an organism.  C: Muscle tissue is made up of different organs.  D: The circulatory system is made up of organs working together.", o: ["A and D only", "B and C only", "A, B and D only", "A, B, C and D"], a: 2, why: "A leaf and the heart are both organs (A). An amoeba is one cell that is a whole organism (B). Organs work together in a system (D). C is the wrong way round: a tissue is a group of similar cells, and tissues make up organs.", lvl: 4 }
  ],
  oe: [
    { q: "Mei Ling observed two organisms, P and Q, in pond water under a microscope. The table shows her observations. (a) Both organisms are unicellular. What does this mean? (b) Which organism can make its own food? Explain. (c) Q has no cell wall. Predict how the shape of Q is different from that of P. (d) Name the part, found in both P and Q, that controls the movement of substances into and out of the cell.", tbl: [["Organism", "Number of cells", "Chloroplasts", "Cell wall"], ["P", "one", "✓", "✓"], ["Q", "one", "✗", "✗"]], marks: 4, kw: [["one cell", "single cell", "only one cell", "1 cell"], ["chlorophyll", "chloroplast"], ["irregular", "no fixed shape", "not have a fixed shape", "changes shape", "change its shape", "change shape", "not fixed"], ["membrane"]], model: "(a) Each organism is made up of only one cell, which carries out all its life processes. (b) P. It has chloroplasts, which contain chlorophyll that traps light energy to make food. (c) Q has an irregular shape, with no fixed shape, because it has no cell wall to give it a regular shape. (d) The cell membrane." },
    { q: "Hakim kept three potatoes for 7 days: potato A in a dark cupboard, potato B under a lamp, and potato C under the same lamp but wrapped in aluminium foil. He then looked at a thin slice from the surface of each potato under a microscope and counted the cells with chloroplasts in the view. The graph shows his results. (a) Which variable did Hakim change? (b) Explain why only potato B had cells with chloroplasts. (c) Potato C was under the lamp. Explain why it had no cells with chloroplasts.", fig: { type: "bar", xl: "Potato", yl: "Number of cells with chloroplasts", bars: [["A", 0], ["B", 45], ["C", 0]] }, marks: 3, kw: [["amount of light", "whether the potato", "whether it received light", "whether they received light", "exposure to light", "light received", "presence of light", "light or dark", "light and dark", "dark or light"], ["received light", "receives light", "receive light", "exposed to light", "got light", "gets light", "get light", "had light", "in the light", "was in light", "given light"], ["block", "stop", "prevent", "not reach", "not receive light", "not get light", "did not let"]], model: "(a) Whether the potato received light. (b) Potato B received light, so the cells near its surface formed chloroplasts to trap light energy to make food. (c) The aluminium foil blocked the light from reaching the potato, so its cells did not form chloroplasts." },
    { q: "Jun Wei compared a plant cell to his school. (a) The principal controls everything that happens in the school. Which part of the cell is like the principal? (b) The security guard at the gate checks who enters and leaves the school. Which part of the cell is like the guard? (c) The strong fence around the school gives it a fixed shape. Which part of the cell is like the fence? (d) Jun Wei says a model of an animal cell should not have the fence. Explain why he is right.", marks: 4, kw: [["nucleus"], ["membrane"], ["cell wall", "wall"], ["no cell wall", "not have a cell wall", "not have cell wall", "without a cell wall", "lack a cell wall", "lacks a cell wall", "no wall"]], model: "(a) The nucleus, which controls all the activities of the cell. (b) The cell membrane, which controls the movement of substances into and out of the cell. (c) The cell wall, which gives the plant cell its regular shape and support. (d) Animal cells have no cell wall, so they have no fixed shape." },
    { q: "Priya placed beetroot pieces of the same size into beakers of water at different temperatures for 10 minutes. Beetroot cells store a red substance. The graph shows how red the water became (0 = colourless, 10 = very red). (a) Name the part of the beetroot cell that normally stops the red substance from leaving the cell. (b) Using your answer to (a), explain why the water became redder at higher temperatures. (c) Name the part of the cell where the red substance is stored. (d) State one variable Priya kept the same.", fig: { type: "bar", xl: "Temperature of water (°C)", yl: "Redness of water (0–10)", bars: [["20", 1], ["40", 2], ["60", 6], ["80", 9]] }, marks: 4, x: 1, kw: [["membrane"], ["damag", "destroy", "broke", "burst", "no longer control", "could not control", "cannot control", "unable to control", "not control"], ["vacuole"], ["size", "volume of water", "amount of water", "time", "10 minutes", "number of pieces", "number of beetroot"]], model: "(a) The cell membrane. (b) The high temperature damaged the cell membrane, so it could no longer control the movement of substances out of the cell, and more of the red substance leaked into the water. (c) The vacuole. (d) The size of the beetroot pieces." }
  ],
  tf: [
    { s: "Bacteria are unicellular organisms.", a: true, why: "Each bacterium is made up of only one cell, which carries out all its life processes." },
    { s: "A leaf is an organ made up of different tissues working together.", a: true, why: "Different tissues working together form an organ, such as a leaf, the heart or the stomach." },
    { s: "Red leaves cannot make food because their cells have no chloroplasts.", a: false, why: "Red leaves still have chloroplasts with chlorophyll; a red substance only hides the green colour." },
    { s: "An amoeba is both a cell and a whole organism.", a: true, why: "An amoeba is a unicellular organism: its one cell is the whole organism." },
    { s: "The cell membrane stops all substances from entering the cell.", a: false, why: "It CONTROLS the movement of substances: it lets some substances in and out and keeps others out." },
    { s: "A single-celled green alga in a pond can make its own food.", a: true, why: "It has chloroplasts containing chlorophyll, which traps light energy to make food." },
    { s: "A plant cell has a cell wall instead of a cell membrane.", a: false, why: "A plant cell has BOTH: the cell membrane lies just inside the cell wall." },
    { s: "Cell division replaces damaged cells, for example when a cut on the skin heals.", a: true, why: "Cells near the cut divide to form new cells that replace the damaged ones." },
    { s: "The vacuole controls all the activities of a plant cell.", a: false, why: "The nucleus controls all the activities; the vacuole stores water and dissolved substances." },
    { s: "Viewing a slide at a higher magnification makes the cells on it grow bigger.", a: false, why: "The cells only LOOK bigger through the lenses; their real size does not change." }
  ],
  sort: [
    { title: "Does each describe the cell wall only, the cell membrane only, or both?", groups: ["Cell wall only", "Cell membrane only", "Both"], items: [["tough outer layer of a plant cell", 0], ["gives a regular shape and support", 0], ["not found in animal cells", 0], ["controls movement of substances in and out", 1], ["thin layer just inside the cell wall", 1], ["found in a cheek cell", 1], ["found in an onion cell", 2], ["found in a yeast cell", 2], ["found in a root hair cell", 2]] }
  ]
};
