window.LBY = window.LBY || {};
LBY["p5-cells"] = {
  lessons: [
    {
      h: "Cell experiments: aim, variables and conclusion",
      concept: "Booklet B cell questions often describe an experiment with yeast cells, stained slides or a microscope. The aim must name BOTH variables: ‘To find out how [changed variable] affects [measured variable]’. The changed variable is the one thing altered on purpose; the measured variable is what is counted, such as the number of yeast cells. A conclusion states the relationship with both variables and a direction: ‘The higher the temperature (up to 30 °C), the more yeast cells there were.’ Answers like ‘yeast likes warmth’ score nothing.",
      example: {
        q: "Hui Min put 50 yeast cells into each of three flasks with the same volume of sugar solution. She kept them at different temperatures and counted the yeast cells after 6 hours. (a) State the aim of her experiment. (b) State the variable she changed and the variable she measured. (c) What can she conclude?",
        tbl: [["Flask", "Temperature (°C)", "Yeast cells at start", "Yeast cells after 6 h"], ["A", "10", "50", "80"], ["B", "20", "50", "200"], ["C", "30", "50", "500"]],
        marks: 3,
        think: [
          "Step 1: Find what was changed on purpose: the temperature. Everything else (sugar solution, starting number of cells) was kept the same.",
          "Step 2: Find what was counted: the number of yeast cells after 6 hours. The aim links the two: how temperature affects the number of yeast cells.",
          "Step 3: Read the trend: 10 °C → 80, 20 °C → 200, 30 °C → 500. As temperature goes up, the number of cells goes up.",
          "Step 4: Only conclude within the range tested (10 °C to 30 °C). Do not claim that hotter is always better."
        ],
        answer: "(a) To find out how temperature affects the number of yeast cells. (b) She changed the temperature and measured the number of yeast cells after 6 hours. (c) From 10 °C to 30 °C, the higher the temperature, the more yeast cells there were after 6 hours."
      },
      tip: "Aim = ‘how [changed] affects [measured]’. Conclusion = ‘the more/higher [changed], the more/fewer [measured]’ – and stay inside the range tested.",
      try: {
        q: "Ben counted how many onion cells he could see in the view of a microscope at 40×, 100× and 400×. Which is the best aim for his experiment?",
        o: ["To find out how the magnification affects the number of cells seen.", "To find out how many onion cells there are in one whole onion.", "To find out whether the onion cells have chloroplasts in them.", "To find out how the number of cells affects the magnification."],
        a: 0,
        why: "He changed the magnification and counted the cells seen, so the aim links the two in that order. The last option swaps the changed and measured variables; the others do not match what he changed."
      }
    }
  ],
  mcq: [
    { q: "Which of these is an example of a tissue?", o: ["One cheek cell on its own", "A group of similar muscle cells", "The stomach of a cat", "The whole digestive system"], a: 1, why: "A tissue is a group of similar cells. One cell is a cell, the stomach is an organ and the digestive system is a system.", lvl: 1 },
    { q: "Which of these are made up of cells? A: A mushroom  B: A pebble  C: A fern  D: Yeast", o: ["A and C only", "B and D only", "A, B and C only", "A, C and D only"], a: 3, why: "All living things are made up of cells: the mushroom and fern have many cells and yeast has one. A pebble is non-living and is not made up of cells.", lvl: 1 },
    { q: "The diagram shows a plant cell. What does the large part Y store?", fig: { type: "cell", kind: "plant", mark: { vacuole: "Y" } }, o: ["Water and dissolved substances", "Genetic information of the cell", "Chlorophyll to make food", "The cell’s jelly-like cytoplasm"], a: 0, why: "Y is the large central vacuole, which stores water and dissolved substances. Genetic information is in the nucleus and chlorophyll is in the chloroplasts.", lvl: 1 },

    { q: "Which parts are found in BOTH an onion skin cell and a human cheek cell? A: Cell wall  B: Nucleus  C: Cell membrane  D: Cytoplasm", o: ["B and C only", "A, B and C only", "B, C and D only", "A, B, C and D"], a: 2, why: "Both cells have a nucleus, cell membrane and cytoplasm. Only the onion cell has a cell wall.", lvl: 2 },
    { q: "The diagram shows a hydrilla leaf cell. Jun Wei says most of the activities of the cell take place in R. In which part do most of the activities actually take place?", fig: { type: "cell", kind: "plant", mark: { cytoplasm: "P", vacuole: "Q", nucleus: "R", chloroplast: "S" } }, o: ["P", "Q", "R", "S"], a: 0, why: "Misconception: mixing up ‘controls’ and ‘takes place’. R, the nucleus, CONTROLS the activities, but most activities take place in P, the cytoplasm.", lvl: 2 },
    { q: "The Venn diagram groups three cells, P, Q and R. Which correctly identifies them?", fig: { type: "venn", a: "Has a cell wall", b: "Has chloroplasts", onlyA: ["P"], both: ["Q"], onlyB: [], neither: ["R"] }, o: ["P: cheek cell, Q: onion bulb cell, R: leaf cell", "P: leaf cell, Q: onion bulb cell, R: cheek cell", "P: onion bulb cell, Q: cheek cell, R: leaf cell", "P: onion bulb cell, Q: leaf cell, R: cheek cell"], a: 3, why: "P has a cell wall but no chloroplasts (onion bulb cell). Q has both (leaf cell). R has neither (cheek cell).", lvl: 2 },
    { q: "Ali says, “An amoeba has no mouth or stomach, so it cannot feed.” Which is the best reply?", o: ["It does not need food because it is made of only one cell.", "It traps light energy to make food, so it does not need organs.", "Its one cell carries out all its life processes, including feeding.", "It takes in food through its cell wall, which works like an organ."], a: 2, why: "Misconception: every living thing needs organs to feed. A unicellular organism’s one cell carries out all life processes. An amoeba needs food, has no chloroplasts and has no cell wall.", lvl: 2 },
    { q: "Which statements about the cell wall are correct? A: It gives a plant cell its regular shape and support.  B: It controls the movement of substances into and out of the cell.  C: It is found outside the cell membrane.", o: ["A only", "A and C only", "A and B only", "A, B and C"], a: 1, why: "Misconception: the cell wall controls what enters and leaves. That is the job of the cell membrane, so B is wrong. The cell wall gives shape and support and lies outside the membrane.", lvl: 2 },
    { q: "An adult’s hand is much bigger than a baby’s hand. What is the main reason?", o: ["Each cell in the adult’s hand is many times bigger.", "The adult’s hand is made up of many more cells.", "The cells in the adult’s hand have bigger nuclei.", "The cells in the adult’s hand have thicker cell walls."], a: 1, why: "Misconception: bigger organisms have bigger cells. Growth is mainly due to cell division, so the adult’s hand has many more cells. Human cells have no cell walls.", lvl: 2 },

    { q: "Mei Ling wants to find out if adding iodine makes the nucleus of cheek cells easier to see. Which two set-ups should she compare?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Cheek cells", "Iodine added", "Viewed at 100×"] }, { label: "B", icon: "plate", lines: ["Cheek cells", "No iodine", "Viewed at 400×"] }, { label: "C", icon: "plate", lines: ["Onion cells", "No iodine", "Viewed at 100×"] }, { label: "D", icon: "plate", lines: ["Cheek cells", "No iodine", "Viewed at 100×"] }] }, o: ["A and B", "A and C", "B and D", "A and D"], a: 3, why: "A and D differ only in whether iodine was added. A and B also differ in magnification, and A and C use different cells.", lvl: 3 },
    { q: "Hui Min set up two flasks and counted the yeast cells in the same volume of liquid from each. What can she conclude?", tbl: [["Flask", "Contents", "Temperature (°C)", "Yeast cells at start", "Yeast cells after 6 h"], ["P", "Yeast, water and sugar", "30", "100", "800"], ["Q", "Yeast and water only", "30", "100", "100"]], o: ["Yeast cells need food to divide and increase in number.", "Yeast cells need a warm place to divide and increase.", "Yeast cells in flask Q died because there was no sugar.", "Yeast cells in flask P grew bigger but did not divide."], a: 0, why: "Only sugar (food) was different, and only flask P increased in number. Temperature was the same, so no conclusion about warmth; flask Q stayed at 100, so we cannot say the cells died.", lvl: 3 },
    { q: "A cell has a cell wall and a nucleus but no chloroplasts. Which of these could it be? A: Yeast cell  B: Onion bulb cell  C: Cheek cell  D: Root hair cell", o: ["A and B only", "B and D only", "A, B and D only", "A, B, C and D"], a: 2, why: "Yeast, onion bulb and root hair cells all have a cell wall and nucleus but no chloroplasts. A cheek cell has no cell wall.", lvl: 3 },
    { q: "Which statements about a red blood cell are correct? A: It cannot divide to form new cells.  B: It has a cell membrane.  C: It has a cell wall to keep its shape.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "A red blood cell has no nucleus, so it cannot divide, but it has a cell membrane. It is an animal cell, so it has no cell wall.", lvl: 3 },
    { q: "The diagram shows the human circulatory system. Which statements about part X are correct? A: X is an organ.  B: X is made up of only one type of tissue.  C: X works with other parts as a system.", fig: { type: "organs", system: "circulatory", mark: { heart: "X" } }, o: ["A only", "A and B only", "B and C only", "A and C only"], a: 3, why: "X is the heart, an organ made up of different tissues (not one type), working with the blood vessels in the circulatory system.", lvl: 3 },
    { q: "Study the Venn diagram. Which correctly identifies X and Y?", fig: { type: "venn", a: "Has a cell wall", b: "Is a whole organism", onlyA: ["onion cell"], both: ["X"], onlyB: ["Y"], neither: ["cheek cell"] }, o: ["X: amoeba, Y: yeast", "X: root hair cell, Y: amoeba", "X: yeast, Y: amoeba", "X: yeast, Y: leaf cell"], a: 2, why: "X has a cell wall and is a whole organism – yeast. Y is a whole organism without a cell wall – amoeba. Root hair and leaf cells are parts of a plant.", lvl: 3 },
    { q: "The graph shows the number of cells in a bean seedling over 8 days. During this time, the seedling grew taller. Which statement best explains this?", fig: { type: "line", xl: "Day", yl: "Number of cells (thousands)", pts: [["0", 2], ["2", 4], ["4", 8], ["6", 15], ["8", 25]] }, o: ["Its cells divided to form new cells, so it had more cells.", "Its cells joined together to form fewer, larger cells.", "Each cell grew larger, but no new cells were formed.", "Its cells made thicker cell walls without dividing."], a: 0, why: "Misconception: plants grow only because each cell gets bigger. The graph shows the number of cells increasing, so the cells divided to form new cells.", lvl: 3 },

    { q: "Priya observed a sample under a microscope. The table shows her observations. Which statements are most likely correct? A: The sample is yeast.  B: The cells are from a leaf.  C: The cells have nuclei.", tbl: [["Observation", "Result"], ["Cell wall", "✓"], ["Chloroplasts", "✗"], ["Each cell lives on its own", "✓"], ["Number of cells in sugar solution", "increased"]], o: ["A only", "B and C only", "A and B only", "A and C only"], a: 3, why: "Single cells with a cell wall, no chloroplasts, that increase in sugar solution fit yeast. They increased by dividing, which needs a nucleus. Leaf cells have chloroplasts and do not live on their own.", lvl: 4 },
    { q: "Wen Hui saw 8 cheek cells lying in a line across the view of her microscope at 100×. She changed to 400× without moving the slide. About how many cells would now fit across the view?", o: ["32", "2", "8", "4"], a: 1, why: "Misconception: higher magnification shows more cells. At 4 times the magnification each cell looks 4 times longer, so only a quarter as many fit across: 8 ÷ 4 = 2.", lvl: 4 },
    { q: "Study the results. Which statements are correct? A: J and K show that temperature affects how fast yeast cells divide.  B: K and L are a fair test of whether sugar is needed.  C: J and L show that sugar is needed for yeast cells to increase in number.  D: J and M show that temperature affects how fast yeast cells divide.", tbl: [["Flask", "Sugar", "Temperature (°C)", "Yeast cells at start", "Yeast cells after 6 h"], ["J", "✓", "30", "100", "900"], ["K", "✓", "10", "100", "200"], ["L", "✗", "30", "100", "100"], ["M", "✓", "30", "200", "1800"]], o: ["A and C only", "A and D only", "B and C only", "A, C and D only"], a: 0, why: "J and K differ only in temperature; J and L differ only in sugar. K and L differ in both sugar and temperature, so B is not fair. J and M are at the same temperature (they differ in starting number), so D is wrong.", lvl: 4 },
    { q: "Study the classification chart. A cell is taken from a white patch of a money plant leaf. The white patch receives light. Where should the cell be placed?", fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Is a whole organism?", yes: "P", no: { q: "Has chloroplasts?", yes: "Q", no: "R" } }, no: { q: "Has a nucleus?", yes: "S", no: "T" } } }, o: ["P", "Q", "R", "T"], a: 2, why: "Misconception: every leaf cell in light has chloroplasts. White-patch cells have a cell wall and nucleus but no chloroplasts, and they are part of a plant, so they go to R, not Q.", lvl: 4 }
  ],
  oe: [
    { q: "Mei Ling prepared two slides of cheek cells as shown, then counted how many cells in the view had a clearly visible nucleus. (a) State the aim of her experiment. (b) State the variable she changed. (c) State one variable she kept the same to make it a fair test. (d) Slide A had 18 cells with a clear nucleus and slide B had 3. What can she conclude?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Cheek cells", "2 drops of iodine", "Viewed at 100×"] }, { label: "B", icon: "plate", lines: ["Cheek cells", "2 drops of water", "Viewed at 100×"] }] }, marks: 4, kw: [["whether adding iodine", "if adding iodine", "whether iodine", "if iodine", "effect of iodine", "how iodine", "iodine affects"], ["iodine or water", "whether iodine was added", "iodine was added", "added iodine", "type of liquid", "liquid added", "what was added"], ["magnification", "number of drops", "amount of", "type of cell", "kind of cell", "same microscope"], ["easier to see", "more clearly", "clearer", "more visible", "see the nucleus"]], model: "(a) To find out whether adding iodine makes the nucleus of cheek cells easier to see. (b) Whether iodine or water was added to the cells. (c) The magnification used. (d) Adding iodine makes the nucleus of the cells easier to see." },
    { q: "Ravi put the same number of yeast cells into four flasks, each with the same volume of water, and kept them at 30 °C. He added a different mass of sugar to each flask. (a) State the relationship between the mass of sugar and the number of yeast cells after 8 hours. (b) Explain how the number of yeast cells increased. (c) Suggest one way to make his results more reliable. (d) Suggest why flask A was set up.", tbl: [["Flask", "Mass of sugar (g)", "Yeast cells at start", "Yeast cells after 8 h"], ["A", "0", "50", "50"], ["B", "5", "50", "200"], ["C", "10", "50", "400"], ["D", "15", "50", "600"]], marks: 4, kw: [["the more sugar", "more sugar", "greater the mass", "larger the mass", "higher the mass", "bigger the mass"], ["divid", "division"], ["repeat", "more times", "average"], ["compare", "comparison", "control", "without sugar", "sugar is needed", "need sugar", "needs sugar"]], model: "(a) The more sugar added, the more yeast cells there were after 8 hours. (b) The yeast cells divided to form new yeast cells. (c) Repeat the experiment and find the average. (d) It shows what happens to yeast cells without sugar, for comparison with the other flasks." },
    { q: "Kumar put 20 yeast cells into each of five flasks with the same volume of sugar solution. He kept the flasks at different temperatures and counted the yeast cells after 6 hours. The graph shows his results. (a) At which temperature did the number of yeast cells increase the most? (b) Describe what happened to the number of yeast cells at 50 °C. (c) Suggest a reason for your answer to (b). (d) Explain how the yeast cells increased in number.", fig: { type: "bar", xl: "Temperature (°C)", yl: "Number of yeast cells after 6 h", bars: [["10", 40], ["20", 110], ["30", 300], ["40", 220], ["50", 10]] }, marks: 4, x: 1, kw: [["30"], ["decrease", "fewer", "dropped", "went down", "fell", "less than 20", "halved"], ["died", "killed", "kill", "die"], ["divid", "division"]], model: "(a) 30 °C. (b) The number of yeast cells decreased from 20 to 10. (c) The high temperature killed some of the yeast cells. (d) The yeast cells divided to form new yeast cells." },
    { q: "Pei Shan made a model of a root hair cell. She used two sponges of the same size and material. She left sponge A as a block and cut many long, thin strips into sponge B. She dipped each sponge into water for 10 seconds and measured the water it absorbed. (a) Which part of the root hair cell do the thin strips of sponge B represent? (b) Explain why sponge B absorbed more water than sponge A. [2] (c) State one variable she must keep the same to make it a fair test.", tbl: [["Sponge", "Volume of water absorbed in 10 s (ml)"], ["A (block)", "18"], ["B (cut into thin strips)", "31"]], marks: 4, kw: [["root hair"], ["surface area", "larger area", "more area", "bigger area", "greater area"], ["more water", "absorb more", "absorbs more", "absorbed more", "take in more", "takes in more"], ["time", "10 seconds", "amount of water", "volume of water", "size of sponge", "same size", "material", "type of sponge", "temperature"]], model: "(a) The root hair. (b) The thin strips increase the surface area of the sponge in contact with the water, so it can absorb more water. (c) The time the sponge was dipped in the water." },
    { q: "An amoeba was carefully cut into two halves, X and Y. Only half X had the nucleus. Both halves were kept in pond water with food. The table shows the results. (a) What does this experiment show about the job of the nucleus? (b) Half Y still had cytoplasm and a cell membrane but could not divide. Explain why. (c) Why was one amoeba cut into two halves instead of using two different amoebae?", tbl: [["Half", "Has nucleus?", "After 3 days", "After 10 days"], ["X", "✓", "feeding and moving", "divided into two amoebae"], ["Y", "✗", "stopped feeding", "died"]], marks: 3, x: 1, kw: [["control"], ["genetic", "no genetic", "controls cell division", "controls division", "controls the division"], ["only difference", "only one variable", "one variable", "fair", "same amoeba", "only the nucleus"]], model: "(a) The nucleus controls the activities of the cell, such as feeding and dividing. (b) The genetic information needed for cell division is in the nucleus, and half Y had no nucleus. (c) So that the only difference between the two halves was whether they had a nucleus, making it a fair test." },
    { q: "The diagram shows a leaf cell. Jia Hui wrote two statements about it. (a) ‘Part A controls the movement of substances into and out of the cell.’ Explain why she is wrong. (b) ‘Part C makes food for the cell.’ Explain why she is wrong. (c) State how part D helps the plant.", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", cell_membrane: "B", vacuole: "C", chloroplast: "D" } }, marks: 3, kw: [["membrane", "shape", "support"], ["store", "storing"], ["chlorophyll", "trap light", "traps light", "absorb light", "absorbs light"]], model: "(a) Part A is the cell wall, which gives the cell its regular shape and support. It is the cell membrane, part B, that controls the movement of substances. (b) Part C is the vacuole, which stores water and dissolved substances; food is made in the chloroplasts. (c) Part D, the chloroplast, contains chlorophyll, which traps light energy to make food for the plant." }
  ],
  tf: [
    { s: "The largest part of a mature plant cell is usually the nucleus.", a: false, why: "The large central vacuole usually takes up most of the space in a mature plant cell." },
    { s: "Yeast cells have a cell wall even though yeast is not a plant.", a: true, why: "Yeast is a unicellular fungus with a cell wall, so a cell wall alone does not prove a cell is a plant cell." },
    { s: "Adding iodine to cheek cells on a slide makes the nucleus easier to see.", a: true, why: "Iodine stains the cells, so parts such as the nucleus stand out." },
    { s: "A unicellular organism has tissues but no organs.", a: false, why: "It is made up of only one cell, so it has no tissues or organs at all." },
    { s: "The heart is an organ made up of different tissues, including muscle tissue.", a: true, why: "An organ is made up of different tissues working together." },
    { s: "All leaf cells that receive light have chloroplasts, including those in the white patches of a leaf.", a: false, why: "Cells in the white patches of a leaf, such as a money plant’s, have no chloroplasts even in light." },
    { s: "An amoeba feeds, grows and reproduces using just one cell.", a: true, why: "Its one cell carries out all its life processes." },
    { s: "The cytoplasm is just water, and nothing happens inside it.", a: false, why: "Most of the activities of the cell take place in the jelly-like cytoplasm." },
    { s: "Yeast cells increase in number by dividing.", a: true, why: "Each yeast cell can divide to form new yeast cells." },
    { s: "The cell membrane is the tough outer layer that gives a plant cell its regular shape.", a: false, why: "That is the cell wall. The cell membrane is a thin layer inside it that controls the movement of substances." }
  ],
  doc: [
    { q: "Ravi found that flasks with more sugar had more yeast cells after 8 hours. State the relationship shown by his results.", marks: 1, answers: ["The yeast cells increased.", "The more sugar added, the more yeast cells there were after 8 hours.", "Sugar is good for yeast."], best: 1, why: "Answer 2 names both variables (mass of sugar and number of yeast cells) and gives the direction of both. Answer 1 mentions only one variable. Answer 3 is vague and names no measured variable." },
    { q: "An amoeba has no organs. Explain how it is still able to stay alive.", marks: 2, answers: ["It is a unicellular organism, and its one cell carries out all its life processes, such as feeding and reproducing.", "It is very small, so it does not need any organs.", "It has a cell wall that protects it from harm."], best: 0, why: "Answer 1 states that it is made of one cell AND that this cell carries out all life processes. Answer 2 links size to not needing organs, which is not the reason. Answer 3 is wrong – an amoeba has no cell wall." }
  ]
};
