window.LB = window.LB || {};
LB["p5-cells"] = {
  notes: [
    { h: "The cell: basic unit of life", t: "The cell is the basic unit of life. All living things are made up of one or more cells. Some organisms, such as amoeba and yeast, are made up of only one cell, while plants and animals are made up of many cells.", kw: ["basic unit of life", "made up of cells", "one or more cells"] },
    { h: "Why we need a microscope", t: "Most cells are too small to be seen with the naked eye. A microscope magnifies (enlarges) the cells so that we can see them and their parts clearly. A hand lens does not magnify enough to show the parts of a cell.", kw: ["too small to be seen with the naked eye", "microscope", "magnifies"] },
    { h: "Using a microscope", t: "A thin layer of the specimen, such as onion skin or cells scraped from the inside of the cheek, is placed on a glass slide on the stage of the microscope. We look through the eyepiece and turn the focusing knob until the cells are clear. A stain such as iodine is often added so that the parts of the cell, like the nucleus, are easier to see.", kw: ["thin layer", "glass slide", "focusing knob", "stain"] },
    { h: "Cell membrane", t: "The cell membrane is a thin layer that surrounds the cytoplasm. It controls the movement of substances into and out of the cell. Both plant cells and animal cells have a cell membrane.", kw: ["controls the movement of substances into and out of the cell", "plant and animal cells"] },
    { h: "Cytoplasm", t: "The cytoplasm is the jelly-like substance inside the cell membrane. It is where most of the activities of the cell take place. Parts such as the nucleus and chloroplasts are found in the cytoplasm.", kw: ["jelly-like", "most of the activities of the cell take place"] },
    { h: "Nucleus", t: "The nucleus controls all the activities of the cell. It contains genetic information, which is needed for the cell to divide and form new cells. A cell without a nucleus cannot divide.", kw: ["controls all the activities of the cell", "genetic information", "cell division"] },
    { h: "Cell wall (plant cells)", t: "The cell wall is the tough outer layer of a plant cell, found outside the cell membrane. It gives the plant cell its regular shape and support, and protects it. Animal cells do not have a cell wall, so they have no fixed shape.", kw: ["gives the plant cell its regular shape", "support", "protects"] },
    { h: "Chloroplasts (plant cells)", t: "Chloroplasts are found in the cytoplasm of plant cells in the green parts of a plant, such as the leaves. They contain chlorophyll, which traps light energy to make food for the plant. Animal cells do not have chloroplasts, so animals cannot make their own food.", kw: ["chlorophyll", "traps light energy to make food"] },
    { h: "Vacuole", t: "A plant cell has a large central vacuole that stores water and dissolved substances such as sugars and mineral salts. When the vacuole is full of water, it helps the plant cell stay firm. Animal cells do not have a large central vacuole.", kw: ["large central vacuole", "stores water and dissolved substances"] },
    { h: "Plant cell vs animal cell", t: "Both plant and animal cells have a cell membrane, cytoplasm and a nucleus. Plant cells have a cell wall but animal cells do not; plant cells may have chloroplasts but animal cells do not; plant cells have a large central vacuole but animal cells do not. Plant cells have a regular shape while animal cells have an irregular shape.", kw: ["cell wall but animal cells do not", "chloroplasts", "large central vacuole", "regular shape"] },
    { h: "Not all plant cells have chloroplasts", t: "Only plant cells in parts that receive light, such as the leaves and green stems, have chloroplasts. Root cells and the cells of an onion bulb grow underground and do not receive light, so they do not have chloroplasts. They still have a cell wall, cell membrane, cytoplasm, nucleus and a large vacuole.", kw: ["root cells", "do not receive light", "no chloroplasts"] },
    { h: "Unicellular organisms and levels of organisation", t: "A unicellular organism is made up of only one cell, which carries out all the life processes, such as feeding, growing and reproducing. Examples are amoeba, yeast and bacteria. In a multicellular organism, cells of the same type group together to form a tissue, different tissues form an organ, organs work together in a system, and systems make up the organism: cell → tissue → organ → system → organism.", kw: ["unicellular", "only one cell", "cell → tissue → organ → system → organism"] }
  ],
  traps: [
    "All plant cells have chloroplasts -> Root cells and onion bulb cells do not receive light, so they have no chloroplasts.",
    "The cell wall controls what enters and leaves the cell -> The CELL MEMBRANE does that; the cell wall gives shape and support.",
    "Animal cells have a cell wall -> Only the cell membrane surrounds an animal cell, which is why it has an irregular shape.",
    "The nucleus is where most activities take place -> Most activities take place in the CYTOPLASM; the nucleus CONTROLS all the activities.",
    "Chloroplasts make food by themselves -> Say it fully: chloroplasts contain chlorophyll which traps light energy to make food.",
    "A cell with a cell wall must be a plant cell -> Yeast and bacteria also have a cell wall; check for chloroplasts and whether it is a whole organism.",
    "A bigger animal has bigger cells -> A bigger organism mainly has MORE cells, not bigger cells.",
    "An organ is made of one type of cell -> An organ is made up of different tissues working together; a tissue is a group of similar cells."
  ],
  lessons: [
    {
      h: "Naming parts and giving the exact function",
      concept: "Marks are lost when a function is vague, such as ‘it protects the cell’ for the cell membrane. Each part has one standard function phrase that markers look for. Learn the exact wording and always name the part before giving its function.",
      example: {
        q: "The diagram shows a plant cell. (a) Name part A and state its function. (b) State the function of part B.",
        fig: { type: "cell", kind: "plant", mark: { cell_membrane: "A", nucleus: "B" } },
        marks: 3,
        think: [
          "Step 1: A is the thin layer just inside the cell wall, so it is the cell membrane, not the cell wall.",
          "Step 2: Give the standard phrase for the cell membrane: it controls the movement of substances into and out of the cell.",
          "Step 3: B is the nucleus. Its function is to control all the activities of the cell (it also contains genetic information).",
          "Step 4: Check that you did not write ‘protects’ or ‘holds the cell together’, which are too vague."
        ],
        answer: "(a) A is the cell membrane. It controls the movement of substances into and out of the cell. (b) B, the nucleus, controls all the activities of the cell."
      },
      tip: "Membrane = controls movement IN and OUT; wall = shape and support; nucleus = controls ALL activities; cytoplasm = where most activities TAKE PLACE.",
      try: {
        q: "The diagram shows a plant cell. Which part traps light energy to make food?",
        fig: { type: "cell", kind: "plant", mark: { cell_wall: "P", chloroplast: "Q", vacuole: "R", nucleus: "S" } },
        o: ["P", "R", "Q", "S"],
        a: 2,
        why: "Q is a chloroplast, which contains chlorophyll that traps light energy to make food. P is the cell wall (shape and support), R is the vacuole (stores water) and S is the nucleus (controls activities)."
      }
    },
    {
      h: "Stating differences between plant and animal cells",
      concept: "A difference must compare BOTH cells in one sentence: ‘The plant cell has a cell wall but the animal cell does not.’ Writing only ‘the plant cell has a cell wall’ describes one cell and may not score. The three parts only plant cells have are the cell wall, chloroplasts and a large central vacuole.",
      example: {
        q: "State two differences between a plant cell and an animal cell.",
        marks: 2,
        think: [
          "Step 1: List the parts both have: cell membrane, cytoplasm, nucleus. These cannot be differences.",
          "Step 2: List the parts only plant cells have: cell wall, chloroplasts, large central vacuole.",
          "Step 3: Write each difference as a comparison, naming both cells."
        ],
        answer: "The plant cell has a cell wall but the animal cell does not. The plant cell has chloroplasts but the animal cell does not."
      },
      tip: "Use the pattern: ‘X has ___ but Y does not.’",
      try: {
        q: "Which of the following is a correct difference between a plant cell and an animal cell?",
        o: ["The animal cell has a nucleus but the plant cell does not.", "The plant cell has a cell membrane but the animal cell does not.", "The animal cell has cytoplasm but the plant cell does not.", "The plant cell has a large central vacuole but the animal cell does not."],
        a: 3,
        why: "Both cells have a nucleus, a cell membrane and cytoplasm, so A, B and C are wrong. Only the plant cell has a large central vacuole."
      }
    },
    {
      h: "Explaining why some plant cells have no chloroplasts",
      concept: "Chloroplasts are only found in plant cells that receive light. Root cells and onion bulb cells are underground, so they receive no light and do not make food; they have no chloroplasts. A full answer links: underground → no light → no need for chloroplasts to trap light to make food.",
      example: {
        q: "Wei Jie looked at root hair cells under a microscope. He saw a cell wall, a nucleus and a vacuole but no chloroplasts. Explain why the root hair cells have no chloroplasts.",
        marks: 2,
        think: [
          "Step 1: Where are the cells? The roots are in the soil, underground.",
          "Step 2: What does that mean? They do not receive light.",
          "Step 3: Link to function: chloroplasts trap light energy to make food, so without light they are not needed."
        ],
        answer: "The roots are underground and do not receive light. Chloroplasts trap light energy to make food, so root cells do not need chloroplasts."
      },
      tip: "Don’t stop at ‘roots are underground’ – always add ‘do not receive light’.",
      try: {
        q: "Which cell is most likely to have NO chloroplasts?",
        o: ["A cell from the green stem of a balsam plant", "A cell from an onion bulb", "A cell from a spinach leaf", "A cell from a green chilli padi"],
        a: 1,
        why: "The onion bulb grows underground and does not receive light, so its cells have no chloroplasts. The green stem, leaf and green chilli are green parts that receive light."
      }
    },
    {
      h: "Identifying cells from their parts",
      concept: "Work step by step: no cell wall means it is not a plant cell. A cell wall plus chloroplasts points to a plant cell from a green part. A cell wall without chloroplasts could be a root cell, an onion cell or a yeast cell. Whether the cell is a whole organism tells you if it is unicellular.",
      example: {
        q: "Study the classification chart of cells. Suggest what cell B could be and explain.",
        fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "A", no: "B" }, no: "C" } },
        marks: 2,
        think: [
          "Step 1: B has a cell wall, so it is not an animal cell.",
          "Step 2: B has no chloroplasts, so it is not from a green part of a plant that receives light.",
          "Step 3: A root cell fits: it has a cell wall but grows underground with no light."
        ],
        answer: "B could be a root cell. It has a cell wall, but it has no chloroplasts because roots are underground and do not receive light."
      },
      tip: "A cell wall alone does not prove a cell is from a plant – yeast has one too.",
      try: {
        q: "In the chart, which of these could be cell C?",
        fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "A", no: "B" }, no: "C" } },
        o: ["A human cheek cell", "A yeast cell", "A leaf cell", "An onion skin cell"],
        a: 0,
        why: "C has no cell wall, so it cannot be yeast, a leaf cell or an onion cell, which all have cell walls. A cheek cell is an animal cell with no cell wall."
      }
    },
    {
      h: "Levels of organisation",
      concept: "Cells of the same type group together to form a tissue. Different tissues work together to form an organ, such as the heart, stomach or leaf. Organs work together in a system, and systems work together in the organism. A unicellular organism has no tissues or organs – its one cell does everything.",
      example: {
        q: "Arrange these from the simplest to the most complex: stomach, muscle cell, digestive system, muscle tissue. Then explain why the stomach is called an organ.",
        marks: 2,
        think: [
          "Step 1: The smallest unit is the cell: muscle cell.",
          "Step 2: Similar cells form a tissue: muscle tissue. Different tissues form an organ: stomach. Organs form a system: digestive system.",
          "Step 3: The stomach is an organ because it is made of different tissues working together."
        ],
        answer: "Muscle cell → muscle tissue → stomach → digestive system. The stomach is an organ because it is made up of different tissues that work together to carry out a function."
      },
      tip: "Tissue = similar cells; organ = different tissues; system = organs working together.",
      try: {
        q: "Which correctly shows the order from simplest to most complex?",
        o: ["Tissue → cell → organ → system", "Cell → organ → tissue → system", "Cell → tissue → system → organ", "Cell → tissue → organ → system"],
        a: 3,
        why: "Cells form tissues, tissues form organs and organs work together in systems."
      }
    }
  ],
  mcq: [
    { q: "What is the basic unit of life?", o: ["Organ", "Cell", "Tissue", "System"], a: 1, why: "All living things are made of cells; the cell is the basic unit of life. Tissues, organs and systems are made of cells.", lvl: 1 },
    { q: "Why do we need a microscope to observe cells?", o: ["Cells move too fast to be seen.", "Cells are found only inside the body.", "Most cells are too small to be seen with the naked eye.", "Cells are transparent and cannot be seen in light."], a: 2, why: "Most cells are too small to be seen with the naked eye, so a microscope is used to magnify them.", lvl: 1 },
    { q: "The diagram shows a plant cell. What is part X?", fig: { type: "cell", kind: "plant", mark: { chloroplast: "X" } }, o: ["Chloroplast", "Nucleus", "Vacuole", "Cell wall"], a: 0, why: "X is one of the small green bodies in the cytoplasm – a chloroplast. The nucleus is a single larger body.", lvl: 1 },
    { q: "The diagram shows an animal cell. What is the function of part P?", fig: { type: "cell", kind: "animal", mark: { nucleus: "P" } }, o: ["It gives the cell its shape and support.", "It stores water and dissolved substances.", "It traps light energy to make food.", "It controls all the activities of the cell."], a: 3, why: "P is the nucleus, which controls all the activities of the cell. An animal cell has no cell wall or chloroplasts.", lvl: 1 },
    { q: "The diagram shows a plant cell. Which part controls the movement of substances into and out of the cell?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", cell_membrane: "B", cytoplasm: "C", vacuole: "D" } }, o: ["A", "B", "C", "D"], a: 1, why: "B is the cell membrane, which controls what enters and leaves the cell. A, the cell wall, gives shape and support.", lvl: 1 },
    { q: "The diagram shows a plant cell. Part W is NOT found in animal cells. What is W?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "W" } }, o: ["Cytoplasm", "Nucleus", "Cell membrane", "Cell wall"], a: 3, why: "W is the outermost layer of the plant cell, the cell wall. Animal cells have cytoplasm, a nucleus and a cell membrane, but no cell wall.", lvl: 1 },
    { q: "Which of these organisms is unicellular?", o: ["Mushroom", "Fern", "Earthworm", "Yeast"], a: 3, why: "Yeast is made up of only one cell. A mushroom, fern and earthworm are made up of many cells.", lvl: 1 },
    { q: "Which shows the correct order from simplest to most complex?", o: ["Cell → organ → tissue → system", "Tissue → cell → system → organ", "Cell → tissue → organ → system", "Organ → tissue → cell → system"], a: 2, why: "Similar cells form tissues, different tissues form organs and organs work together in systems.", lvl: 1 },

    { q: "The diagram shows a plant cell. Which part gives the cell its regular shape and support?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", cell_membrane: "B", nucleus: "C", vacuole: "D" } }, o: ["A", "B", "C", "D"], a: 0, why: "A is the cell wall, which gives the plant cell its regular shape and support. B is the cell membrane, which controls movement of substances.", lvl: 2 },
    { q: "The diagram shows a plant cell. Which part stores water and dissolved substances?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "P", nucleus: "Q", vacuole: "R", chloroplast: "S" } }, o: ["P", "Q", "R", "S"], a: 2, why: "R is the large central vacuole, which stores water and dissolved substances.", lvl: 2 },
    { q: "The diagram shows an animal cell. In which part do most of the activities of the cell take place?", fig: { type: "cell", kind: "animal", mark: { cell_membrane: "X", cytoplasm: "Y", nucleus: "Z" } }, o: ["X", "Y", "Z", "X and Z"], a: 1, why: "Y is the cytoplasm, where most cell activities take place. Z, the nucleus, controls the activities but they happen in the cytoplasm.", lvl: 2 },
    { q: "Mei Ling observed onion skin cells under a microscope. She saw no chloroplasts. Why?", o: ["The onion bulb grows underground and does not receive light.", "Onion cells have no nucleus.", "Onion cells have a cell wall that hides the chloroplasts.", "The iodine stain destroyed the chloroplasts."], a: 0, why: "The onion bulb grows underground with no light, so its cells do not have chloroplasts.", lvl: 2 },
    { q: "Ravi scraped the inside of his cheek and looked at the cells under a microscope. Which parts would he see?", o: ["Cell wall, cytoplasm and nucleus", "Cell membrane, cytoplasm and chloroplasts", "Cell wall, cell membrane and nucleus", "Cell membrane, cytoplasm and nucleus"], a: 3, why: "A cheek cell is an animal cell, so it has a cell membrane, cytoplasm and nucleus, but no cell wall or chloroplasts.", lvl: 2 },
    { q: "A root hair cell does NOT have which of these parts?", o: ["Chloroplast", "Cell wall", "Nucleus", "Cell membrane"], a: 0, why: "The root is underground and receives no light, so its cells have no chloroplasts. As a plant cell, it still has a cell wall, nucleus and cell membrane.", lvl: 2 },
    { q: "The table shows the parts found in four cells. Which cell is most likely an animal cell?", tbl: [["Cell", "Cell wall", "Chloroplasts", "Nucleus"], ["A", "✓", "✓", "✓"], ["B", "✓", "✗", "✓"], ["C", "✗", "✗", "✓"], ["D", "✓", "✓", "✓"]], o: ["A", "B", "C", "D"], a: 2, why: "C has no cell wall and no chloroplasts, which matches an animal cell. B has a cell wall, so it is likely a plant cell without chloroplasts (such as a root cell).", lvl: 2 },
    { q: "The Venn diagram compares plant and animal cells. Which part should replace X?", fig: { type: "venn", a: "Plant cell", b: "Animal cell", onlyA: ["chloroplast", "X"], both: ["nucleus", "cytoplasm", "cell membrane"], onlyB: [], neither: [] }, o: ["Cell wall", "Cytoplasm", "Nucleus", "Cell membrane"], a: 0, why: "X is found only in plant cells, so it is the cell wall. Cytoplasm, nucleus and cell membrane are in both cells.", lvl: 2 },
    { q: "The diagram shows a plant cell. What does part M contain that helps the plant make food?", fig: { type: "cell", kind: "plant", mark: { chloroplast: "M" } }, o: ["Genetic information", "Chlorophyll", "Water", "Cell sap"], a: 1, why: "M is a chloroplast. It contains chlorophyll, which traps light energy to make food.", lvl: 2 },
    { q: "The diagram shows an animal cell. What does part N contain?", fig: { type: "cell", kind: "animal", mark: { nucleus: "N" } }, o: ["Chlorophyll", "A large vacuole", "Genetic information", "Chloroplasts"], a: 2, why: "N is the nucleus, which contains genetic information. Animal cells have no chlorophyll or chloroplasts.", lvl: 2 },
    { q: "The nucleus of a cell was removed. What would most likely happen to the cell?", o: ["It would make more food as it has more space.", "It would grow a cell wall to protect itself.", "It would divide faster and make more cells.", "It could no longer control its activities or divide."], a: 3, why: "The nucleus controls all the activities of the cell and contains the genetic information needed for cell division.", lvl: 2 },
    { q: "Study the chart. Which of these could be cell B?", fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "A", no: "B" }, no: "C" } }, o: ["A spinach leaf cell", "A root hair cell", "A cheek cell", "A muscle cell"], a: 1, why: "B has a cell wall but no chloroplasts – a root hair cell. A leaf cell has chloroplasts (A); cheek and muscle cells have no cell wall (C).", lvl: 2 },
    { q: "Study the chart. Which of these could be cell A?", fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "A", no: "B" }, no: "C" } }, o: ["A cell from an onion bulb", "A cell from the inside of the cheek", "A cell from a hibiscus leaf", "A root hair cell from a plant"], a: 2, why: "A has a cell wall and chloroplasts – a leaf cell that receives light. Onion bulb and root cells have no chloroplasts; a cheek cell has no cell wall.", lvl: 2 },
    { q: "Which of these can only be seen clearly using a microscope?", o: ["A mosquito", "A grain of rice", "A strand of hair", "A single cheek cell"], a: 3, why: "A single cheek cell is too small to be seen with the naked eye. The others can be seen without a microscope.", lvl: 2 },

    { q: "Which statements are correct? A: All plant cells have chloroplasts. B: Both plant and animal cells have a cell membrane. C: A unicellular organism carries out all its life processes in one cell. D: Animal cells have a regular shape because of the cell wall.", o: ["B and C only", "A and B only", "A, B and C only", "B, C and D only"], a: 0, why: "A is wrong – root and onion bulb cells have no chloroplasts. D is wrong – animal cells have no cell wall and have an irregular shape.", lvl: 3 },
    { q: "The graph shows the number of chloroplasts counted in one cell from each of four parts of a plant. Which part is R most likely from?", fig: { type: "bar", xl: "Part of plant", yl: "Number of chloroplasts in one cell", bars: [["P", 35], ["Q", 12], ["R", 0], ["S", 20]] }, o: ["Leaf", "Green stem", "Root", "Green unripe fruit"], a: 2, why: "R has no chloroplasts, so it does not receive light – the root. The leaf, green stem and green fruit are green and have chloroplasts.", lvl: 3 },
    { q: "A cell from a plant has a cell wall, cell membrane, cytoplasm, nucleus and a large vacuole, but no chloroplasts. Where is it most likely from?", o: ["The underground part of the plant", "A leaf exposed to sunlight", "The green stem", "A young green leaf"], a: 0, why: "Plant cells in parts that receive light have chloroplasts. A plant cell with no chloroplasts is most likely from an underground part such as the root.", lvl: 3 },
    { q: "A plant cell and an animal cell were placed in pure water. Both took in water. The animal cell burst but the plant cell did not. The diagram shows the plant cell. Which part stopped it from bursting?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", cell_membrane: "B", vacuole: "C", nucleus: "D" } }, o: ["D", "C", "B", "A"], a: 3, why: "A is the tough cell wall, which supports the plant cell. The animal cell has no cell wall, so it burst.", lvl: 3 },
    { q: "The diagram shows an amoeba, a unicellular organism. Which statement about it is correct?", fig: { type: "cell", kind: "animal", mark: { cell_membrane: "A", cytoplasm: "B", nucleus: "C" } }, o: ["It is part of a tissue in a larger organism.", "Its one cell carries out all its life processes.", "It makes its own food using the chlorophyll in it.", "Part A is a cell wall that gives it a fixed shape."], a: 1, why: "A unicellular organism carries out all life processes in its one cell. It has no chloroplasts, and A is the cell membrane, not a cell wall, so it has no fixed shape.", lvl: 3 },
    { q: "A yeast cell has a cell wall, cell membrane, cytoplasm and nucleus but no chloroplasts. Which of these is correct about yeast?", o: ["It cannot make its own food.", "It is a plant cell from a root.", "It can trap light energy to make food.", "It is made up of many cells."], a: 0, why: "Without chloroplasts, yeast cannot trap light energy to make food. Yeast is a unicellular fungus, not a plant.", lvl: 3 },
    { q: "Which statement about the stomach is correct?", o: ["It is a tissue made up of only one type of cell.", "It is a system made up of different organs working together.", "It is a single large cell that digests food.", "It is an organ made up of different tissues working together."], a: 3, why: "The stomach is an organ of the digestive system; it is made up of different tissues working together.", lvl: 3 },
    { q: "Siti looked at a thin piece of onion skin through a hand lens but could not see the parts of the cells. What should she do?", o: ["Use a microscope, which magnifies much more.", "Use a thicker piece of onion skin to see more.", "Look at it in a dark room so the cells stand out.", "Use the onion leaves, which have bigger cells."], a: 0, why: "A hand lens does not magnify enough to show the parts of a cell; a microscope does. A thicker specimen would let even less light through.", lvl: 3 },
    { q: "The table shows the parts found in four cells. Which cell is most likely from a leaf?", tbl: [["Cell", "Cell wall", "Chloroplasts", "Large vacuole", "Nucleus"], ["P", "✗", "✗", "✗", "✓"], ["Q", "✓", "✗", "✓", "✓"], ["R", "✓", "✓", "✓", "✓"], ["S", "✗", "✗", "✗", "✓"]], o: ["P", "Q", "R", "S"], a: 2, why: "R has a cell wall, large vacuole and chloroplasts – a plant cell that receives light, such as a leaf cell. Q has no chloroplasts, so it is more likely a root cell.", lvl: 3 },
    { q: "The diagram shows a plant cell. Which part of an animal cell does the same job as part K?", fig: { type: "cell", kind: "plant", mark: { cell_membrane: "K" } }, o: ["Nucleus", "Cytoplasm", "Cell wall", "Cell membrane"], a: 3, why: "K is the cell membrane. Animal cells also have a cell membrane that controls the movement of substances in and out.", lvl: 3 },
    { q: "The diagram shows an animal cell. Part X was damaged, and harmful substances could then enter the cell freely. What is X?", fig: { type: "cell", kind: "animal", mark: { cell_membrane: "X" } }, o: ["Cytoplasm", "Cell membrane", "Nucleus", "Cell wall"], a: 1, why: "The cell membrane controls the movement of substances into and out of the cell. Animal cells have no cell wall.", lvl: 3 },
    { q: "A potted plant was kept in a dark cupboard for a week. Its leaf cells still had chloroplasts, but the plant did not make food. What is the best explanation?", o: ["The chloroplasts had no chlorophyll.", "The leaf cells had lost their cell walls.", "The nucleus stopped storing water.", "There was no light for the chlorophyll to trap."], a: 3, why: "Chlorophyll in the chloroplasts traps light energy to make food; in the dark there is no light to trap.", lvl: 3 },

    { q: "A red blood cell has no nucleus. Which of these can a red blood cell NOT do?", o: ["Divide to form new red blood cells", "Take in substances through its cell membrane", "Carry substances in the blood", "Keep its cytoplasm inside the cell"], a: 0, why: "The nucleus contains the genetic information needed for cell division, so a cell without a nucleus cannot divide. It still has a cell membrane and cytoplasm.", lvl: 4 },
    { q: "A scientist found an organism made of a single cell. It has a cell wall but no chloroplasts. Which organism is it most likely to be?", o: ["Amoeba", "Yeast", "A human cheek cell", "A spinach leaf cell"], a: 1, why: "It is a whole organism, so the cheek cell and leaf cell are out – they are parts of larger organisms. Amoeba has no cell wall. Yeast is unicellular, with a cell wall and no chloroplasts.", lvl: 4 },
    { q: "Study the chart. Which correctly identifies B and C?", fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "A", no: "B" }, no: { q: "Is a whole organism?", yes: "C", no: "D" } } }, o: ["B: yeast, C: cheek cell", "B: leaf cell, C: amoeba", "B: yeast, C: amoeba", "B: amoeba, C: yeast"], a: 2, why: "B has a cell wall but no chloroplasts – yeast fits. C has no cell wall and is a whole organism – amoeba. A cheek cell is not a whole organism (D), and a leaf cell has chloroplasts (A).", lvl: 4 },
    { q: "Organism E is made up of one cell. The table shows its parts. Which of these can be concluded? A: E can make its own food. B: E is a plant. C: E is unicellular.", tbl: [["Part", "Present?"], ["Cell membrane", "✓"], ["Cytoplasm", "✓"], ["Nucleus", "✓"], ["Chloroplasts", "✓"], ["Cell wall", "✗"]], o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 2, why: "E has chloroplasts, so it can trap light to make food (A), and it is made of one cell, so it is unicellular (C). It has no cell wall, so we cannot conclude it is a plant.", lvl: 4 },
    { q: "The nucleus of a cell from plant X (red flowers) was put into a cell from plant Y (white flowers) whose own nucleus had been removed. The new cell grew into a plant with red flowers. What does this show?", o: ["The cytoplasm of the cell decides the colour of the flowers.", "The nucleus contains the genetic information that controls the cell.", "The cell membrane controls what colour the flowers will be.", "Flower colour depends on the amount of light the plant gets."], a: 1, why: "The new plant had the flower colour of the plant that gave the nucleus, even though the cytoplasm and membrane came from plant Y. So the nucleus carries the genetic information that controls the cell.", lvl: 4 },
    { q: "Which statements about a yeast cell and a human cheek cell are correct? A: Both have a nucleus. B: Both have a cell wall. C: The yeast cell is a whole organism but the cheek cell is only part of an organism. D: Neither has chloroplasts.", o: ["A and C only", "A, C and D only", "B and D only", "A, B, C and D"], a: 1, why: "Both have a nucleus (A) and neither has chloroplasts (D). Yeast is unicellular while the cheek cell is part of a human (C). Only yeast has a cell wall, so B is wrong.", lvl: 4 }
  ],
  tf: [
    { s: "The cell is the basic unit of life.", a: true, why: "All living things are made up of one or more cells." },
    { s: "Most cells are large enough to be seen clearly with the naked eye.", a: false, why: "Most cells are too small to be seen with the naked eye; we need a microscope." },
    { s: "All plant cells have chloroplasts.", a: false, why: "Root cells and onion bulb cells receive no light and have no chloroplasts." },
    { s: "Plant cells and animal cells both have a cell membrane, cytoplasm and a nucleus.", a: true, why: "These three parts are common to both." },
    { s: "Animal cells have a cell wall that gives them a regular shape.", a: false, why: "Animal cells have no cell wall, so they have an irregular shape." },
    { s: "The cell membrane controls the movement of substances into and out of the cell.", a: true, why: "This is the function of the cell membrane." },
    { s: "The cell wall controls which substances enter and leave the cell.", a: false, why: "That is the cell membrane; the cell wall gives shape and support." },
    { s: "Chloroplasts contain chlorophyll, which traps light energy to make food.", a: true, why: "This is the function of chloroplasts." },
    { s: "Most of the activities of the cell take place in the nucleus.", a: false, why: "Most activities take place in the cytoplasm; the nucleus controls them." },
    { s: "The nucleus contains genetic information.", a: true, why: "This genetic information is needed for cell division." },
    { s: "A unicellular organism cannot carry out all the life processes on its own.", a: false, why: "Its one cell carries out all the life processes, such as feeding, growing and reproducing." },
    { s: "Yeast is a unicellular organism.", a: true, why: "Yeast is a fungus made up of only one cell." },
    { s: "A mushroom is a unicellular fungus.", a: false, why: "A mushroom is made up of many cells." },
    { s: "Cells of the same type group together to form a tissue.", a: true, why: "A tissue is a group of similar cells." },
    { s: "An organ is made up of only one type of cell.", a: false, why: "An organ is made up of different tissues working together." },
    { s: "The cells of an onion bulb do not have chloroplasts.", a: true, why: "The onion bulb grows underground and does not receive light." },
    { s: "The large vacuole of a plant cell makes food for the plant.", a: false, why: "The vacuole stores water and dissolved substances; chloroplasts trap light to make food." },
    { s: "Plant cells have a more regular shape than animal cells because of the cell wall.", a: true, why: "The cell wall gives the plant cell its regular shape and support." },
    { s: "An elephant is bigger than a mouse mainly because its cells are much bigger.", a: false, why: "A bigger organism mainly has many more cells, not bigger cells." },
    { s: "The cell membrane is found only in animal cells.", a: false, why: "Both plant and animal cells have a cell membrane; in plant cells it is just inside the cell wall." }
  ],
  sort: [
    { title: "Sort each into its level of organisation", groups: ["Cell", "Tissue", "Organ", "System"], items: [["muscle cell", 0], ["red blood cell", 0], ["onion skin cell", 0], ["muscle tissue", 1], ["a group of similar cells working together", 1], ["heart", 2], ["stomach", 2], ["leaf", 2], ["digestive system", 3], ["circulatory system", 3]] },
    { title: "Match each function to the cell part", groups: ["Cell wall", "Cell membrane", "Nucleus", "Chloroplast"], items: [["gives the plant cell its regular shape", 0], ["gives support to the plant cell", 0], ["controls movement of substances in and out", 1], ["thin layer just inside the cell wall", 1], ["controls all activities of the cell", 2], ["contains genetic information", 2], ["contains chlorophyll", 3], ["traps light energy to make food", 3]] },
    { title: "Sort these into unicellular and multicellular organisms", groups: ["Unicellular", "Multicellular"], items: [["amoeba", 0], ["yeast", 0], ["bacteria", 0], ["mushroom", 1], ["fern", 1], ["hibiscus plant", 1], ["grasshopper", 1], ["earthworm", 1], ["human", 1], ["moss", 1]] }
  ],
  oe: [
    { q: "The diagram shows a plant cell. (a) State the function of part A. (b) State the function of part B. (c) Part C is not found in root cells. Explain why.", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", nucleus: "B", chloroplast: "C" } }, marks: 3, kw: [["shape", "support"], ["controls all", "control all", "controls the activities", "controls activities"], ["light", "no sunlight", "not receive sunlight", "not get sunlight", "dark"]], model: "(a) A, the cell wall, gives the plant cell its regular shape and support. (b) B, the nucleus, controls all the activities of the cell. (c) Roots are underground and do not receive light, so root cells do not need chloroplasts to trap light energy to make food." },
    { q: "The diagram shows an animal cell. State the function of part X.", fig: { type: "cell", kind: "animal", mark: { cell_membrane: "X" } }, marks: 1, kw: [["in and out", "into and out", "enter and leave", "movement of substances", "entering and leaving"]], model: "X, the cell membrane, controls the movement of substances into and out of the cell." },
    { q: "Explain why a microscope is used to observe cells.", marks: 2, kw: [["too small", "very small", "tiny"], ["magnif", "enlarge", "bigger", "larger"]], model: "Most cells are too small to be seen with the naked eye. The microscope magnifies the cells so that we can see them and their parts clearly." },
    { q: "The table shows the parts found in cells P, Q, R and S. (a) Which cell is an animal cell? Give a reason. (b) Cell R has a cell wall but no chloroplasts. Suggest which part of a plant it could come from. (c) Explain why cell R has no chloroplasts. (d) Explain how cell Q is able to make food.", tbl: [["Cell", "Cell wall", "Chloroplasts", "Nucleus"], ["P", "✗", "✗", "✓"], ["Q", "✓", "✓", "✓"], ["R", "✓", "✗", "✓"], ["S", "✓", "✓", "✓"]], marks: 4, kw: [["no cell wall", "not have a cell wall", "not have cell wall", "without a cell wall", "lacks a cell wall"], ["root", "underground", "onion"], ["no light", "not receive light", "does not get light", "not get light", "receive no light", "lack of light"], ["chlorophyll", "trap", "absorb"]], model: "(a) P is an animal cell because it has no cell wall and no chloroplasts. (b) It could come from the root. (c) The root is underground and does not receive light, so chloroplasts are not needed there. (d) Q has chloroplasts which contain chlorophyll that traps light energy to make food." },
    { q: "The diagram shows an amoeba. (a) What is meant by a unicellular organism? (b) Other than amoeba, name one unicellular organism.", fig: { type: "cell", kind: "animal", mark: { cell_membrane: "A", cytoplasm: "B", nucleus: "C" } }, marks: 2, kw: [["one cell", "single cell", "1 cell"], ["yeast", "bacteri"]], model: "(a) A unicellular organism is made up of only one cell, which carries out all its life processes. (b) Yeast." },
    { q: "(a) Arrange organ, cell, system and tissue in order from the simplest to the most complex. (b) The stomach is an organ. Explain what makes it an organ. (c) Name the system that the stomach is part of.", marks: 3, kw: [["cell → tissue → organ → system", "cell -> tissue -> organ -> system", "cell, tissue, organ, system", "cells, tissues, organs, systems", "cell tissue organ system", "cell > tissue > organ > system"], ["different tissues", "different types of tissues", "different kinds of tissues", "more than one type of tissue", "different tissue"], ["digestive"]], model: "(a) cell → tissue → organ → system. (b) The stomach is made up of different tissues that work together to carry out a function. (c) The digestive system." },
    { q: "In an experiment, the nucleus of a cell from plant X, which has red flowers, was placed into a cell from plant Y, which has white flowers, after the nucleus of plant Y’s cell had been removed. The new cell grew into a plant with red flowers. (a) What does this show about the nucleus? (b) Predict what would happen to the cell of plant Y if its nucleus were removed and not replaced. (c) Which part of the new cell controls the movement of substances into it?", marks: 3, x: 1, kw: [["genetic", "controls", "control"], ["not divide", "cannot divide", "unable to divide", "stop dividing", "not be able to divide", "die", "cannot control", "not control"], ["cell membrane", "membrane"]], model: "(a) The nucleus contains the genetic information that controls the activities of the cell, so the new plant had the red flowers of plant X. (b) The cell would not be able to divide, because it has no nucleus to control its activities. (c) The cell membrane." },
    { q: "Study the classification chart of cells. (a) Name a plant cell that belongs to group B. (b) Explain why the cell you named in (a) has no chloroplasts. (c) Amoeba belongs to group C. Explain why. (d) Name a unicellular organism that could belong to group B.", fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "A", no: "B" }, no: { q: "Is a whole organism?", yes: "C", no: "D" } } }, marks: 4, x: 1, kw: [["root", "onion"], ["light", "no sunlight", "not receive sunlight", "not get sunlight", "dark"], ["one cell", "single cell", "unicellular", "only one cell"], ["yeast", "bacteri"]], model: "(a) A root hair cell. (b) The root is underground and does not receive light, so it does not need chloroplasts to trap light energy to make food. (c) Amoeba has no cell wall and it is a whole organism made up of only one cell. (d) Yeast." },
    { q: "The graph shows the number of chloroplasts counted in one cell from each of four parts of a plant. (a) Part R has no chloroplasts. Suggest which part of the plant R is from. (b) Explain your answer to (a). (c) Cells from part P have the most chloroplasts. Explain how this is useful to the plant.", fig: { type: "bar", xl: "Part of plant", yl: "Number of chloroplasts in one cell", bars: [["P", 35], ["Q", 12], ["R", 0], ["S", 20]] }, marks: 3, kw: [["root", "underground"], ["no light", "not receive light", "does not get light", "not get light", "receive no light", "without light"], ["more light", "more food", "more chlorophyll"]], model: "(a) The root. (b) The root is underground and does not receive light, so it does not need chloroplasts. (c) More chloroplasts means more chlorophyll to trap more light energy, so part P can make more food for the plant." },
    { q: "Mei Ling observed onion skin cells and cheek cells under a microscope. (a) State one part she would see in the onion cells but not in the cheek cells. (b) She expected to see green chloroplasts in the onion cells but saw none. Explain why. (c) She added a drop of iodine to the cells. Why?", marks: 3, kw: [["cell wall", "vacuole"], ["no light", "not receive light", "does not get light", "not get light", "receive no light", "no sunlight", "dark"], ["clearer", "more clearly", "easier to see", "more visible", "stain", "see the parts", "see the nucleus"]], model: "(a) The cell wall. (b) The onion bulb grows underground and does not receive light, so its cells have no chloroplasts. (c) The iodine stains the cells so that the parts, such as the nucleus, are easier to see." },
    { q: "A plant cell and an animal cell were placed in pure water. Both took in water. The animal cell burst but the plant cell did not. The diagram shows the plant cell. (a) Name part A, which stopped the plant cell from bursting. (b) Name the part, found in both cells, that controls the movement of water into the cell. (c) Name part C, where most of the extra water in the plant cell is stored.", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", cell_membrane: "B", vacuole: "C" } }, marks: 3, kw: [["cell wall"], ["membrane"], ["vacuole"]], model: "(a) The cell wall. (b) The cell membrane. (c) The vacuole." },
    { q: "A red blood cell has no nucleus. Predict one thing that a red blood cell cannot do. Explain your answer.", marks: 2, kw: [["divide", "not divide", "cannot divide", "unable to divide", "not reproduce", "cannot reproduce", "not multiply", "cannot multiply", "not make new", "cannot make new", "not form new", "cannot form new"], ["genetic", "controls", "no genetic", "no nucleus", "without a nucleus", "not have a nucleus", "not have genetic"]], model: "It cannot divide to form new cells, because the nucleus contains the genetic information needed for cell division." },
    { q: "Organism E is made up of only one cell. The table shows its parts. (a) Can E make its own food? Explain. (b) Ali says E must be a plant cell. Using the table, give one reason why he may be wrong. (c) Is E unicellular or multicellular? Give a reason.", tbl: [["Part", "Present?"], ["Cell membrane", "✓"], ["Cytoplasm", "✓"], ["Nucleus", "✓"], ["Chloroplasts", "✓"], ["Cell wall", "✗"]], marks: 3, x: 1, kw: [["chlorophyll", "chloroplast"], ["no cell wall", "not have a cell wall", "not have cell wall", "without a cell wall", "lacks a cell wall"], ["one cell", "single cell", "1 cell"]], model: "(a) Yes. E has chloroplasts which contain chlorophyll to trap light energy to make food. (b) E has no cell wall, but plant cells have a cell wall. (c) Unicellular, because it is made up of only one cell." },
    { q: "The diagram shows an animal cell. (a) Name part X. (b) State the function of part X. (c) State what part X contains that is needed for the cell to divide.", fig: { type: "cell", kind: "animal", mark: { nucleus: "X" } }, marks: 3, kw: [["nucleus"], ["controls all", "control all", "controls the activities", "controls activities"], ["genetic"]], model: "(a) The nucleus. (b) It controls all the activities of the cell. (c) It contains genetic information." }
  ],
  doc: [
    { q: "State the function of the cell membrane.", marks: 1, answers: ["It protects the cell.", "It controls the movement of substances into and out of the cell.", "It lets everything go in and out of the cell."], best: 1, why: "Answer 2 uses the exact function. Answer 1 is too vague (and ‘protects’ is closer to the cell wall). Answer 3 is wrong – the membrane CONTROLS movement; it does not let everything through." },
    { q: "Explain why root cells do not have chloroplasts.", marks: 2, answers: ["Roots do not need them.", "Roots are underground.", "Roots are underground and do not receive light, so they do not need chloroplasts to trap light energy to make food."], best: 2, why: "Answer 3 links underground → no light → no need to trap light to make food. Answer 2 stops before ‘no light’. Answer 1 is a claim with no reason." },
    { q: "Explain why a microscope is needed to observe cells.", marks: 2, answers: ["Cells are too small to be seen with the naked eye, and the microscope magnifies them so that we can see them clearly.", "To see the cells.", "Because cells are invisible."], best: 0, why: "Answer 1 gives both ideas: cells are too small, and the microscope magnifies them. Answer 2 repeats the question. Answer 3 is inaccurate – cells are not invisible, just too small." },
    { q: "Explain why yeast is a unicellular organism.", marks: 1, answers: ["Yeast is a fungus.", "Yeast is very small.", "Yeast is made up of only one cell, which carries out all its life processes."], best: 2, why: "Answer 3 states the key idea: only one cell. Answer 1 is true but does not explain ‘unicellular’. Answer 2 is vague – being small does not mean being made of one cell." },
    { q: "State two differences between a plant cell and an animal cell.", marks: 2, answers: ["Plant cells are green and animal cells are not.", "The plant cell has a cell wall but the animal cell does not. The plant cell has chloroplasts but the animal cell does not.", "The animal cell has a cell membrane but the plant cell does not."], best: 1, why: "Answer 2 gives two correct comparisons naming parts. Answer 1 is inaccurate – not all plant cells are green (e.g. root cells). Answer 3 is wrong – both cells have a cell membrane." }
  ]
};
