window.LB = window.LB || {};
// Crossover 5 — integrated questions across P3–P5 topics
LB["p5-mixed"] = {
  notes: [
    { h: "Evaporation needs heat", t: "Water gains heat from the surroundings and evaporates into water vapour. Evaporation happens at any temperature, at the exposed surface of the water, while boiling happens at 100 °C throughout the water. Water evaporates faster when the surroundings are hotter, there is more wind, the exposed surface area is larger or the air holds less water vapour.", kw: ["gains heat", "evaporates", "any temperature", "exposed surface area"] },
    { h: "Condensation means losing heat", t: "When water vapour comes into contact with a cooler surface, it loses heat to the surface and condenses into water droplets. This is why droplets form on the OUTSIDE of a glass of iced water, or on the outside of a car windscreen when the air-conditioner is on during a humid day. The water comes from the surrounding air, not from inside the glass.", kw: ["water vapour", "loses heat", "cooler surface", "condenses"] },
    { h: "The water cycle is changes of state", t: "Heat from the Sun makes water in seas, rivers and reservoirs evaporate. The water vapour rises, loses heat to the cooler air high up and condenses into tiny water droplets that form clouds. The droplets join and fall as rain, which collects in rivers, seas and reservoirs and the cycle repeats, giving us a continuous supply of fresh water.", kw: ["evaporate", "condenses", "clouds", "fresh water"] },
    { h: "Melting, freezing and boiling", t: "Ice gains heat and melts at 0 °C; water loses heat and freezes at 0 °C. Water gains heat and boils at 100 °C. While ice is melting or water is boiling, it is still gaining heat but its temperature stays the same until the change of state is complete.", kw: ["melting point 0 °C", "boiling point 100 °C", "temperature stays the same"] },
    { h: "Conductors, insulators and circuits", t: "Metals such as copper, steel and aluminium are electrical conductors; plastic, rubber, wood and glass are electrical insulators. Wires are made of copper to conduct electricity and are covered with plastic, an insulator, so that electricity does not pass to the person touching them. A bulb lights up only in a closed circuit.", kw: ["electrical conductor", "electrical insulator", "closed circuit"] },
    { h: "Series and parallel", t: "In series, components are on one path: more batteries make a bulb brighter, more bulbs make each bulb dimmer, and if one bulb fuses the rest go out. In parallel, each bulb has its own path to the batteries, so if one bulb fuses or its switch is opened, the others stay lit.", kw: ["series", "parallel", "own path", "closed circuit"] },
    { h: "Electromagnets link circuits and magnets", t: "A coil of wire wound around an iron nail becomes an electromagnet when electricity flows through the coil in a closed circuit. It attracts magnetic materials (iron, steel, nickel, cobalt) but not copper, aluminium or plastic. It becomes stronger with more coils or more batteries, and loses most of its magnetism when the switch is opened.", kw: ["electromagnet", "closed circuit", "magnetic materials", "more coils", "more batteries"] },
    { h: "Plant parts and the plant transport system", t: "Roots absorb water and mineral salts from the soil. Water-carrying tubes carry water and mineral salts from the roots up the stem to the leaves. Leaves make food, and food-carrying tubes carry the food from the leaves to all other parts, including the roots, flowers and fruits. The food-carrying tubes are near the outer part of the stem.", kw: ["absorb water and mineral salts", "water-carrying tubes", "food-carrying tubes", "leaves make food"] },
    { h: "Human systems work together", t: "The digestive system breaks down food into simpler substances, which are absorbed into the blood in the small intestine. The respiratory system takes in oxygen at the lungs, where oxygen enters the blood and carbon dioxide leaves it. The circulatory system (heart, blood vessels, blood) transports oxygen and digested food to all cells and carries carbon dioxide from the cells to the lungs.", kw: ["absorbed into the blood", "small intestine", "lungs", "heart pumps blood", "transports"] },
    { h: "Taking in oxygen: humans, fish and plants", t: "Humans take in oxygen through the lungs. Fish take in dissolved oxygen from water through their gills, which have many blood vessels. Plants take in and give out gases through tiny openings, mostly on the underside of their leaves. In every case, oxygen is used by cells to release energy from food.", kw: ["lungs", "gills", "tiny openings", "release energy"] },
    { h: "From flower to new plant", t: "Pollination: pollen grains are transferred from the anther to the stigma (by insects, wind or other agents). Fertilisation: the male reproductive cell in the pollen grain fuses with the egg cell in the ovule. The ovule develops into a seed and the ovary develops into a fruit. Seeds are then dispersed, and germinate into new plants.", kw: ["pollination", "fertilisation", "ovule becomes seed", "ovary becomes fruit"] },
    { h: "Fruits are adapted for dispersal", t: "Wind: light, with wing-like parts or feathery hairs (angsana, lalang). Water: fibrous husk that traps air, waterproof skin, so it floats (coconut, sea almond). Animals: juicy and brightly coloured to be eaten, or hooks that cling to fur (rambutan, love grass). Splitting: dry pods that burst and fling seeds out (balsam, rubber). Dispersal reduces overcrowding and competition with the parent plant for water, sunlight, space and mineral salts.", kw: ["wind", "water", "animals", "splitting", "competition"] }
  ],
  traps: [
    "Droplets on the outside of a cold glass came from inside it → they came from water vapour in the surrounding air condensing on the cold surface.",
    "Water evaporates only when it boils → evaporation happens at any temperature; boiling happens at 100 °C.",
    "Condensation happens because the water vapour ‘gains cold’ → the water vapour LOSES HEAT to the cooler surface.",
    "An electromagnet attracts all metals → only magnetic materials (iron, steel, nickel, cobalt); not copper or aluminium.",
    "Removing the outer ring of a stem stops water reaching the leaves → only the food-carrying tubes near the outer part are removed; water still reaches the leaves.",
    "The heart ‘makes oxygen’ or ‘digests food’ → the heart pumps blood that TRANSPORTS oxygen and digested food.",
    "The ovary becomes the seed → the OVULE becomes the seed; the ovary becomes the fruit.",
    "A coconut floats because it is hollow → its fibrous husk traps air, making it light enough to float."
  ],
  lessons: [
    {
      h: "How to link heat to a change of state",
      concept: "Every change of state is caused by a heat change. Evaporation, melting and boiling: water GAINS heat. Condensation and freezing: water LOSES heat. A full-mark answer names where the water came from, the heat change and the process, in that order.",
      example: {
        q: "Siti boiled water in a kettle. She held a cold metal spoon above the spout and water droplets formed on the spoon.\n(a) Name the process by which the water in the kettle became steam. [1]\n(b) Explain how the water droplets formed on the spoon. [2]",
        fig: { type: "setups", items: [ { label: "Kettle", icon: "jar", lines: ["Water at 100 °C", "Steam from spout"] }, { label: "Spoon", icon: "plate", lines: ["Cold metal spoon", "Held above spout"] } ] },
        marks: 3,
        think: [
          "Step 1: In the kettle, water gains heat and changes into water vapour at 100 °C: that is boiling.",
          "Step 2: For the spoon, ask: where did the water come from? From the hot water vapour (steam) coming out of the spout.",
          "Step 3: What heat change? The spoon is cooler, so the water vapour loses heat to the spoon.",
          "Step 4: Name the process: it condenses into water droplets."
        ],
        answer: "(a) Boiling. (b) The hot water vapour from the spout came into contact with the cooler surface of the spoon. It lost heat to the spoon and condensed into water droplets."
      },
      tip: "Source → heat change → process. ‘Water vapour ... lost heat to the cooler spoon ... condensed.’ Missing any one of the three often costs a mark.",
      try: {
        q: "On a humid afternoon, Mr Goh switched on the air-conditioner in his car. Soon, water droplets formed on the windscreen. On which side of the windscreen did they form and why?",
        o: ["Inside, because the cold air blown out by the air-conditioner condensed on the glass", "Outside, because water vapour in the warm outside air lost heat to the cool glass and condensed", "Inside, because the air-conditioner sprays out tiny water droplets onto the glass", "Outside, because rain fell on the car and stuck to the cool glass of the windscreen"],
        a: 1,
        why: "The air-conditioner cools the glass. The warm, humid air OUTSIDE contains a lot of water vapour, which loses heat to the cooler outer surface of the glass and condenses."
      }
    },
    {
      h: "How to explain an electromagnet using circuits and magnets",
      concept: "An electromagnet question joins two topics. From circuits: electricity flows only in a closed circuit. From magnets: a magnet attracts only magnetic materials. Chain them: switch closed → closed circuit → electricity flows through the coil → the iron nail becomes a magnet → it attracts magnetic materials such as steel pins.",
      example: {
        q: "Jun wound a coil of wire around an iron nail and connected it to batteries and a switch, as shown. Steel pins and copper pins were placed near the nail.\n(a) Explain why the steel pins were attracted when the switch was closed. [1]\n(b) Explain why the copper pins were not attracted. [1]\n(c) What happened to the steel pins when the switch was opened? Explain. [1]",
        fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false }, { k: "gap", label: "X", text: "coil on iron nail" } ] },
        marks: 3,
        think: [
          "Step 1: Switch closed → closed circuit → electricity flows through the coil → the iron nail becomes a magnet (electromagnet).",
          "Step 2: Steel is a magnetic material, so it is attracted. Copper is a metal but NOT a magnetic material.",
          "Step 3: Switch opened → open circuit → no electricity flows through the coil → the nail loses most of its magnetism.",
          "Step 4: So the steel pins fall off."
        ],
        answer: "(a) The circuit was closed, so electricity flowed through the coil and the iron nail became a magnet. Steel is a magnetic material, so the pins were attracted. (b) Copper is not a magnetic material. (c) The steel pins fell off, because no electricity flowed through the coil, so the nail lost most of its magnetism."
      },
      tip: "Copper conducts electricity but is NOT magnetic. Many pupils lose marks by mixing up ‘conductor’ and ‘magnetic material’.",
      try: {
        q: "Which object would BOTH light up the bulb when placed across a gap in a circuit AND be attracted by an electromagnet?",
        o: ["Copper wire", "Aluminium foil", "Steel paper clip", "Plastic ruler"],
        a: 2,
        why: "Steel is both an electrical conductor and a magnetic material. Copper and aluminium conduct electricity but are not magnetic; plastic does neither."
      }
    },
    {
      h: "How to connect plant parts to the transport system",
      concept: "Plant questions often join ‘parts and functions’ with ‘transport’. Water travels roots → water-carrying tubes in the stem → leaves. Food travels leaves → food-carrying tubes (near the outer part of the stem) → all other parts, including the roots. Ask: which tubes were damaged, and which part is now cut off from what it needs?",
      example: {
        q: "A rat gnawed away a ring of the outer layer of the stem of a young papaya plant, near the ground, as shown. The leaves stayed green for a few weeks, but then the whole plant died.\n(a) Explain why the leaves stayed green at first. [1]\n(b) Explain why the whole plant later died. [2]",
        fig: { type: "plant", mark: { stem: "Ring removed", leaf: "Leaves", roots: "Roots" } },
        marks: 3,
        think: [
          "Step 1: Which tubes are in the outer layer? The food-carrying tubes. The water-carrying tubes are deeper inside, so they were not damaged.",
          "Step 2: So water could still travel up to the leaves → leaves stayed green at first.",
          "Step 3: Food made in the leaves could not be carried down past the ring to the roots.",
          "Step 4: The roots had no food, so they died and could no longer absorb water; then the whole plant died."
        ],
        answer: "(a) The water-carrying tubes were not removed, so water from the roots could still be transported up the stem to the leaves. (b) The food-carrying tubes in the outer layer were removed, so food made in the leaves could not be transported to the roots. The roots died and could no longer absorb water, so the whole plant died."
      },
      tip: "Always name the tubes: ‘water-carrying tubes’ or ‘food-carrying tubes’. ‘The tubes were cut’ is too vague for the mark.",
      try: {
        q: "The water-carrying tubes in the stem of a balsam plant were blocked. What would happen first?",
        o: ["The roots would stop getting food, because food could not reach them", "The leaves would wilt, because water could not reach them", "The flowers would produce more pollen, because they had less water", "The plant would make more food, to repair the blocked tubes"],
        a: 1,
        why: "Blocking the water-carrying tubes stops water reaching the leaves, so they wilt. The food-carrying tubes are not blocked, so food can still reach the roots for now."
      }
    },
    {
      h: "How to trace a substance through the body systems",
      concept: "Questions about oxygen or digested food reaching a muscle join three systems. Trace the path step by step and name the organ at each stage: digested food is absorbed into the blood in the small intestine; oxygen enters the blood in the lungs; the heart pumps the blood through blood vessels to all cells, where oxygen is used to release energy from food. Carbon dioxide travels back to the lungs.",
      example: {
        q: "Study the diagram. Describe how oxygen from the air reaches the muscles of Amir’s legs when he runs. [3]",
        fig: { type: "organs", system: "circulatory", mark: { heart: "A", lungs: "B", blood_vessels: "C" } },
        marks: 3,
        think: [
          "Step 1: Air is breathed in through the nose and windpipe into the lungs (B).",
          "Step 2: In the lungs, oxygen passes into the blood.",
          "Step 3: The blood goes to the heart (A), which pumps it through the blood vessels (C).",
          "Step 4: The blood transports the oxygen to the muscle cells in the legs."
        ],
        answer: "Air is breathed in and reaches the lungs (B), where oxygen enters the blood. The heart (A) pumps the blood through the blood vessels (C), and the blood transports the oxygen to the cells of the leg muscles."
      },
      tip: "Name the organs in order and use ‘enters the blood’, ‘pumps’ and ‘transports’. The heart pumps blood; it does not make oxygen.",
      try: {
        q: "Which correctly shows the path of digested food from a meal to a muscle cell?",
        o: ["Stomach → lungs → blood → heart → muscle cell", "Small intestine → blood → heart → blood → muscle cell", "Large intestine → heart → lungs → blood → muscle cell", "Mouth → windpipe → lungs → blood → muscle cell"],
        a: 1,
        why: "Digested food is absorbed into the blood in the small intestine, and the heart pumps this blood to all parts of the body, including the muscle cells."
      }
    },
    {
      h: "How to explain seed dispersal from fruit features",
      concept: "A dispersal answer needs three links: the FEATURE of the fruit, HOW the feature helps (e.g. traps air so it floats), and the METHOD of dispersal (water). For 2-3 marks, add WHY dispersal helps: the seedlings grow away from the parent plant, so there is less competition for water, sunlight, space and mineral salts.",
      example: {
        q: "Study the table about fruits J and K.\n(a) Explain how fruit J is dispersed. [1]\n(b) Explain how fruit K is dispersed. [1]\n(c) Why is it important for these seeds to be dispersed away from the parent plant? [1]",
        tbl: [["Fruit", "Features"], ["J", "Fibrous husk, waterproof outer skin"], ["K", "Very light, with feathery hairs"]],
        marks: 3,
        think: [
          "Step 1: J: a fibrous husk traps air → the fruit is light enough to float → dispersed by water.",
          "Step 2: K: very light with feathery hairs → large surface to catch the wind → dispersed by wind.",
          "Step 3: Why disperse? Seeds that grow far from the parent do not have to compete with it.",
          "Step 4: Name the resources they compete for: water, sunlight, space and mineral salts."
        ],
        answer: "(a) J’s fibrous husk traps air, so it can float and is dispersed by water; the waterproof skin stops water getting in. (b) K is very light and its feathery hairs let it be carried by the wind. (c) So that the young plants grow away from the parent plant and do not overcrowd, with less competition for water, sunlight, space and mineral salts."
      },
      tip: "‘It floats’ is only half an answer. Say WHY it floats (fibrous husk traps air) and the method (dispersed by water).",
      try: {
        q: "Fruit L is juicy and brightly coloured, with small hard seeds. How are its seeds most likely dispersed?",
        o: ["By wind, as the fruit is light and is blown far away from the parent plant", "By water, as the fruit floats and is carried away by rivers or the sea", "By animals, which eat the fruit and pass out the seeds in their droppings", "By splitting, as the fruit dries and bursts open to fling out its seeds"],
        a: 2,
        why: "Juicy, brightly coloured fruits attract animals, which eat them. The hard seeds pass through unharmed and are passed out in droppings away from the parent plant."
      }
    }
  ],
  mcq: [
    { q: "Water vapour in the air touches the outside of a glass of iced water and forms droplets. What is this process called?", o: ["Evaporation", "Freezing", "Melting", "Condensation"], a: 3, why: "Water vapour loses heat to the cold glass and condenses into water. Evaporation is the opposite change, from water to water vapour.", lvl: 1 },
    { q: "Study the diagram of the human circulatory system. What is the function of part A?", fig: { type: "organs", system: "circulatory", mark: { heart: "A" } }, o: ["It takes in oxygen from the air.", "It digests food.", "It pumps blood around the body.", "It absorbs digested food."], a: 2, why: "A is the heart, which pumps blood around the body. The lungs take in oxygen and the small intestine absorbs digested food.", lvl: 1 },
    { q: "Electrical wires are usually made of copper covered with plastic. Why is copper used for the inside of the wire?", o: ["Copper is a magnetic material.", "Copper is an electrical insulator.", "Copper is an electrical conductor.", "Copper is waterproof."], a: 2, why: "Copper allows electricity to pass through easily. It is not a magnetic material, and the plastic covering is the insulator.", lvl: 1 },
    { q: "Jun made an electromagnet that picked up some steel pins. What happened to the pins when he opened the switch?", o: ["Most of them fell off", "They were attracted more strongly", "They were repelled away", "They turned into magnets forever"], a: 0, why: "With the switch open, no electricity flows through the coil, so the nail loses most of its magnetism and the pins drop.", lvl: 1 },
    { q: "The fruit of the angsana tree has a flat, wing-like part around the seed. How is it most likely dispersed?", o: ["By water", "By splitting", "By animals", "By wind"], a: 3, why: "A light fruit with a wing-like part is carried by the wind, which spins it away from the parent tree.", lvl: 1 },
    { q: "Study the diagram of a plant. Which part absorbs water and mineral salts from the soil?", fig: { type: "plant", mark: { roots: "A", stem: "B", leaf: "C", flower: "D" } }, o: ["A", "B", "C", "D"], a: 0, why: "A is the roots, which absorb water and mineral salts. The stem (B) contains the tubes that carry them up to the leaves (C).", lvl: 1 },
    { q: "Study the diagram of the digestive system. In which part is most digested food absorbed into the blood?", fig: { type: "organs", system: "digestive", mark: { gullet: "P", stomach: "Q", small_intestine: "R", large_intestine: "S" } }, o: ["P", "Q", "R", "S"], a: 2, why: "R is the small intestine, where digested food is absorbed into the blood. The large intestine (S) mainly absorbs water.", lvl: 1 },
    { q: "In human reproduction, which two cells fuse during fertilisation?", o: ["The pollen grain and the ovule", "The sperm and the egg", "The ovary and the testis", "The womb cell and the egg"], a: 1, why: "Fertilisation in humans is the fusion of the sperm (male reproductive cell) and the egg (female reproductive cell). Pollen and ovules belong to flowering plants.", lvl: 1 },

    { q: "Which statement about evaporation and boiling is correct?", o: ["Water evaporates only at 100 °C, while boiling can happen at any temperature.", "Boiling happens only at the surface, but evaporation happens throughout the water.", "Both evaporation and boiling take place only when water loses heat to its surroundings.", "Evaporation takes place at any temperature, but boiling takes place at 100 °C."], a: 3, why: "A puddle dries at room temperature, so evaporation happens at any temperature, while water boils at 100 °C. Both need water to GAIN heat, and boiling happens throughout the water.", lvl: 2 },
    { q: "Priya placed each object across gap X in the circuit shown: a steel spoon, a rubber band, aluminium foil and a glass rod. For which objects did the bulb light up?", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "object tested" } ] }, o: ["Steel spoon and aluminium foil only", "Steel spoon only", "Rubber band and glass rod only", "All four objects"], a: 0, why: "Steel and aluminium are metals and conduct electricity, closing the circuit. Rubber and glass are electrical insulators.", lvl: 2 },
    { q: "The graph shows how many pins an electromagnet attracted with different numbers of coils of wire. What can be concluded?", fig: { type: "bar", xl: "Number of coils", yl: "Number of pins attracted", bars: [["10", 4], ["20", 8], ["30", 12], ["40", 16]] }, o: ["The fewer the coils, the stronger the electromagnet.", "The number of coils does not affect the electromagnet.", "The electromagnet only works with 40 coils.", "The more coils of wire, the stronger the electromagnet."], a: 3, why: "As the number of coils increased, more pins were attracted, so the electromagnet became stronger. It worked for every number of coils tested.", lvl: 2 },
    { q: "Study the Venn diagram. An object made of which material would both close a circuit AND be attracted by an electromagnet?", fig: { type: "venn", a: "Conducts electricity", b: "Magnetic material", onlyA: ["copper", "aluminium"], both: ["iron", "steel"], onlyB: [], neither: ["plastic", "wood"] }, o: ["Copper", "Iron", "Aluminium", "Plastic"], a: 1, why: "Iron is in the overlap: it conducts electricity AND is a magnetic material. Copper and aluminium conduct but are not magnetic.", lvl: 2 },
    { q: "Study the diagram of the respiratory system. What happens at part X?", fig: { type: "organs", system: "respiratory", mark: { lungs: "X", windpipe: "Y" } }, o: ["Food is digested into simpler substances, which then pass into the blood.", "Air is warmed and cleaned by tiny hairs before it passes on into the windpipe.", "Blood is pumped out to all parts of the body, carrying oxygen and digested food.", "Oxygen moves into the blood, and carbon dioxide moves out of the blood into the air."], a: 3, why: "X is the lungs, where gases are exchanged: oxygen enters the blood and carbon dioxide leaves it. The heart pumps blood; the nose warms and cleans air.", lvl: 2 },
    { q: "Compared with blood going INTO the lungs, blood coming OUT of the lungs has...", o: ["more oxygen and less carbon dioxide", "less oxygen and more carbon dioxide", "more digested food and less oxygen", "the same amount of oxygen and carbon dioxide"], a: 0, why: "In the lungs, the blood takes in oxygen and gives out carbon dioxide. Digested food is absorbed into the blood at the small intestine, not the lungs.", lvl: 2 },
    { q: "The coconut fruit has a thick, fibrous husk. How does this help in its dispersal?", o: ["It makes the fruit juicy and attractive, so animals eat it and spread its seed.", "It dries and splits open, so the seed is flung far away from the parent plant.", "It traps air, making the fruit light enough to float so it is carried by water.", "It acts like wings, helping the fruit spin and be carried away by the wind."], a: 2, why: "The fibrous husk traps air, so the coconut floats and is carried by water to faraway shores.", lvl: 2 },
    { q: "The diagram shows a flower. After fertilisation, which part develops into the fruit?", fig: { type: "flower", mark: { anther: "P", stigma: "Q", ovary: "R", petal: "S" } }, o: ["P", "Q", "S", "R"], a: 3, why: "R is the ovary, which develops into the fruit; the ovules inside it develop into seeds. The anther, stigma and petals usually wither.", lvl: 2 },
    { q: "The diagram shows part of the water cycle. What is stage ‘?’, and how is it formed?", fig: { type: "cycle", stages: ["Water in the sea", "?", "Clouds", "Rain"] }, o: ["Water vapour, formed when water gains heat from the Sun and evaporates", "Ice, formed when water loses heat to the cold air and freezes", "Steam, formed only when the sea gains enough heat from the Sun to boil", "Water droplets, formed when water vapour gains heat and condenses"], a: 0, why: "Sea water gains heat and evaporates into water vapour, which later condenses into clouds. The sea does not boil, and condensation needs water vapour to LOSE heat.", lvl: 2 },
    { q: "The water-carrying tubes in the stem of a plant were blocked. Which would happen first?", o: ["The roots would stop getting food, because food could not reach them.", "The flowers would turn into fruits, because they had no more water.", "The leaves would wilt, because water could not reach them.", "The plant would absorb more water, because the leaves need it."], a: 2, why: "Blocked water-carrying tubes stop water from reaching the leaves, so they wilt. Food-carrying tubes are not affected at first.", lvl: 2 },
    { q: "On a humid day, Mr Goh switched on his car’s air-conditioner. Water droplets appeared on the windscreen. Which statement is correct?", o: ["They formed on the inside, as the cold air blown out by the air-conditioner condensed on the glass.", "They formed on the outside, as water vapour in the warm outside air lost heat to the cool glass and condensed.", "They formed on the inside, as water vapour in the car gained heat from the glass and turned into water.", "They formed on both sides, as the glass itself gave out water when it became cold."], a: 1, why: "The air-conditioner cools the glass. Humid outside air contains a lot of water vapour, which loses heat to the cooler outer surface and condenses. ‘Cold air’ itself does not condense.", lvl: 2 },
    { q: "Study the circuit. Both bulbs are lit. What will happen if bulb A fuses?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false } ], branches: [ [ { k: "bulb", label: "A" } ], [ { k: "bulb", label: "B" } ] ] }, o: ["Bulb B will stay lit.", "Bulb B will also go out.", "Bulb B will light up only if S is opened.", "The batteries will stop working."], a: 0, why: "A and B are in parallel, so B is on its own path to the batteries. There is still a closed circuit through B when A fuses.", lvl: 2 },
    { q: "How does digested food from the small intestine reach the muscles of the legs?", o: ["It travels down the gullet and through the body to the leg muscles.", "It passes through the large intestine, which carries it to the legs.", "It is carried by air from the lungs through the windpipe to the legs.", "It is absorbed into the blood and the heart pumps the blood to the legs."], a: 3, why: "Digested food is absorbed into the blood in the small intestine; the blood, pumped by the heart, transports it to all cells.", lvl: 2 },
    { q: "Seeds of love grass are often found stuck to socks after a walk in a field. Which feature is most likely responsible?", o: ["Tiny hooks or bristles that cling to fur and clothing", "Feathery hairs that catch the wind and carry it away", "A fibrous husk that traps air and lets it float", "A juicy, brightly coloured coat that attracts animals"], a: 0, why: "Hooks cling to animal fur (and clothes), so the seeds are carried away and drop off elsewhere.", lvl: 2 },

    { q: "Study the classification key for fruits. Which fruit is most likely D?", fig: { type: "flow", root: "Fruits", node: { q: "Has wing-like parts?", yes: "A", no: { q: "Has a fibrous husk?", yes: "B", no: { q: "Is it juicy?", yes: "C", no: "D" } } } }, o: ["Angsana, a flat winged fruit", "Coconut, with a fibrous husk", "Rambutan, with juicy flesh", "Balsam, a dry pod that bursts open"], a: 3, why: "Balsam has no wings, no fibrous husk and is not juicy; its dry pod splits to fling the seeds. Angsana is A, coconut is B and rambutan is C.", lvl: 3 },
    { q: "Jun’s electromagnet, shown in the circuit, attracted 12 steel pins. Which change would make it attract MORE pins?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false }, { k: "gap", label: "X", text: "coil on iron nail" } ] }, o: ["Replacing the iron nail with an aluminium rod", "Winding more coils of wire around the iron nail", "Using fewer coils of wire", "Using copper pins instead of steel pins"], a: 1, why: "More coils make a stronger electromagnet. Aluminium is not a magnetic material, so it would weaken it, and copper pins are not attracted at all.", lvl: 3 },
    { q: "Why do clouds form high above the ground?", o: ["Water vapour rises, loses heat to the cooler air high up and condenses into tiny droplets.", "Water vapour rises and gains heat from the Sun high up, so it turns into water droplets.", "The wind carries tiny droplets of sea water straight up into the sky, where they collect.", "Water freezes into ice as soon as it leaves the sea, and the ice floats up into the sky."], a: 0, why: "Air high up is cooler, so the water vapour loses heat and condenses into tiny droplets, which form clouds. Gaining heat would keep it as water vapour.", lvl: 3 },
    { q: "Farmer Tan removed a ring of the outer layer from the trunk of a papaya tree, below all its branches, as shown. What would most likely happen over the next few weeks?", fig: { type: "plant", mark: { stem: "Ring removed", leaf: "Leaves", roots: "Roots" } }, o: ["The roots would not receive food from the leaves and would slowly die.", "The leaves would wilt at once, as water could not reach them.", "The fruits would get bigger, as more water reached them.", "Nothing would happen, as the outer layer has no function."], a: 0, why: "The food-carrying tubes near the outer part of the trunk are removed, so food from the leaves cannot reach the roots. The water-carrying tubes are deeper, so the leaves do not wilt at once.", lvl: 3 },
    { q: "The table shows the relative amounts of oxygen and digested food in blood taken from vessels J, K, L and M. Which vessel carries blood away from the small intestine?", tbl: [["Vessel", "Oxygen", "Digested food"], ["J", "High", "Low"], ["K", "Low", "High"], ["L", "Low", "Low"], ["M", "High", "High"]], o: ["J", "K", "L", "M"], a: 1, why: "Blood leaving the small intestine has just absorbed digested food (high) and has given oxygen to the intestine’s cells (low). J matches blood leaving the lungs.", lvl: 3 },
    { q: "Which statements about electrical wire (copper covered with plastic) are correct?\nI. Copper allows electricity to flow through the wire.\nII. The plastic covering is an electrical insulator, preventing electric shocks.\nIII. Copper is used because it is a magnetic material.\nIV. The plastic lets the electricity flow faster.", o: ["I and II only", "I and III only", "II and IV only", "I, II and III only"], a: 0, why: "Copper is a good electrical conductor and plastic is an insulator. Copper is NOT a magnetic material, and plastic does not speed up electricity.", lvl: 3 },
    { q: "After running, Amir sat in front of a fan and felt cooler. Which statement best explains this?", o: ["The fan blew ice-cold air containing water droplets onto his skin, which cooled him down.", "The sweat on his skin condensed in the moving air, giving out cold to his body.", "The sweat gained heat from his body and evaporated faster in the moving air, so he lost heat.", "The moving air made his heart pump less blood, so his body produced less heat."], a: 2, why: "Sweat takes heat from the skin to evaporate, and moving air makes it evaporate faster. The fan does not produce cold air; it only moves air.", lvl: 3 },
    { q: "Study the circuit. Switch S1 is open and switch S2 is closed. Which bulbs are lit?", fig: { type: "circuit", cells: 2, main: [], branches: [ [ { k: "bulb", label: "A" }, { k: "switch", label: "S1", open: true } ], [ { k: "bulb", label: "B" }, { k: "switch", label: "S2", open: false } ], [ { k: "bulb", label: "C" } ] ] }, o: ["A only", "A, B and C", "B and C only", "C only"], a: 2, why: "The three bulbs are in parallel. S1 opens only A’s path; B’s path (S2 closed) and C’s path are closed circuits, so B and C light up.", lvl: 3 },
    { q: "Ice cubes were heated in a beaker. The graph shows the temperature. Which statement is correct?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 0], ["2", 0], ["4", 0], ["6", 30], ["8", 60], ["10", 90], ["12", 100], ["14", 100]] }, o: ["From 0 to 4 minutes, the ice did not gain any heat, so its temperature stayed at 0 °C.", "From 0 to 4 minutes, the ice was gaining heat and melting, but its temperature stayed at 0 °C.", "From 12 to 14 minutes, the water stopped gaining heat, so its temperature stopped rising.", "Water evaporated only between 12 and 14 minutes, when it was boiling at 100 °C."], a: 1, why: "During melting (0-4 min) and boiling (12-14 min), heat is still gained but the temperature stays the same until the change of state is complete. Water also evaporated earlier, at lower temperatures.", lvl: 3 },
    { q: "A baby has some characteristics of its mother and some of its father. Which statement best explains why?", o: ["The baby gets digested food and genetic information from its mother only.", "The baby copies how its parents look as it grows up inside the mother.", "The father’s blood flows into the baby through the umbilical cord before birth.", "The fertilised egg’s nucleus has genetic information from both the sperm and the egg."], a: 3, why: "At fertilisation the sperm fuses with the egg, so the fertilised egg carries genetic information from both parents in its nucleus. The umbilical cord links the baby to the mother only.", lvl: 3 },
    { q: "On a hot, windy afternoon, a potted plant’s leaves drooped even though the soil was moist. By evening, the leaves were upright again. What is the best explanation?", o: ["The roots stopped absorbing water in the afternoon heat, then started again in the evening.", "The leaves lost water faster than it was transported to them, and recovered when less was lost.", "The food-carrying tubes carried water away from the leaves, then brought it back in the evening.", "The leaves made too much food in the afternoon, which weighed them down until it was used up."], a: 1, why: "Heat and wind make water evaporate from the leaves faster. When the leaves lose water faster than the water-carrying tubes can supply it, they droop; in the cooler evening, they recover.", lvl: 3 },
    { q: "Jun wanted to show that his iron nail had become a magnet when the switch was closed. Which observation is the BEST proof?", fig: { type: "magnets", items: [ { label: "Nail", kind: "bar", text: "iron nail (coil on)" }, { label: "M", poles: "NS" } ], between: ["?"] }, o: ["The nail attracted steel pins.", "The nail attracted one end of bar magnet M.", "The nail became warm.", "The nail repelled one end of bar magnet M."], a: 3, why: "Only a magnet can repel a magnet, so repulsion is proof. A plain iron nail would also be attracted to a magnet, so attraction alone does not prove it is a magnet.", lvl: 3 },

    { q: "Study the circuit. Bulb A and electromagnet X are in parallel and both are working. Bulb A then fuses. What happens to the electromagnet?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false } ], branches: [ [ { k: "bulb", label: "A" } ], [ { k: "gap", label: "X", text: "coil on iron nail" } ] ] }, o: ["It stops attracting pins, as the fused bulb makes the whole circuit open.", "It still attracts pins, as electricity still flows through its own closed path.", "It attracts pins only if switch S is also opened to reset the circuit.", "It attracts copper pins instead of steel pins, as more current flows through it."], a: 1, why: "X has its own path to the batteries, so it is still in a closed circuit. Opening S would stop all current, and an electromagnet never attracts copper.", lvl: 4 },
    { q: "Hot kopi was poured into two identical cups. Cup P was covered with a saucer and cup Q was left uncovered. After 20 minutes, droplets were seen under P’s saucer. Which is correct about the mass of each cup and its contents (including the saucer)?", fig: { type: "setups", items: [ { label: "P", icon: "beaker", lines: ["Hot kopi", "Covered by a saucer"] }, { label: "Q", icon: "beaker", lines: ["Hot kopi", "Not covered"] } ] }, o: ["P decreased more than Q, because the water vapour that condensed on the saucer was lost.", "P decreased much less than Q, because most water vapour condensed on the saucer and stayed in the cup.", "Both stayed exactly the same, because evaporation and condensation do not change the mass.", "Q increased, because its uncovered kopi gained water vapour from the surrounding air."], a: 1, why: "In Q, water vapour escapes into the air, so mass is lost. In P, most water vapour condenses on the cooler saucer and drips back, so very little mass is lost.", lvl: 4 },
    { q: "A mango branch has leaves near its base and a developing fruit at its tip. A ring of the outer layer is removed from the branch between the leaves and the fruit. What will most likely happen to the fruit?", fig: { type: "plant", mark: { leaf: "Leaves", stem: "Ring removed", fruit: "Fruit" } }, o: ["It will stop growing well, as food made in the leaves cannot reach it.", "It will grow bigger, as more water and food reach it from the leaves.", "It will wilt, as water can no longer pass the ring to reach it.", "It will turn back into a flower, as it can no longer grow into a fruit."], a: 0, why: "Food for the growing fruit is made in the leaves and carried by food-carrying tubes in the outer layer. With these removed, food cannot pass the ring to the fruit. The water-carrying tubes inside are intact, so it does not wilt from lack of water.", lvl: 4 },
    { q: "Which sequence correctly shows how energy from a plate of chicken rice ends up being used by Amir’s leg muscles?", o: ["Digested in the lungs → absorbed into the blood in the stomach → carried by the windpipe to the legs → used by muscles to release energy", "Broken down in the large intestine → absorbed into the air in the lungs → carried to the muscle cells → used without oxygen to release energy", "Absorbed into the blood in the mouth → carried to the heart → digested in the heart → pumped to the muscle cells to release energy", "Digested into simpler substances → absorbed into the blood in the small intestine → pumped by the heart to the muscles → used with oxygen to release energy"], a: 3, why: "Food is digested into simpler substances, absorbed into the blood in the small intestine, transported by the circulatory system, and used by cells with oxygen (from the respiratory system) to release energy.", lvl: 4 },
    { q: "Paper model fruits were dropped in front of a fan. Study the results. Which conclusions are correct?\nI. With mass kept the same, wings help the models travel further.\nII. With wings kept the same, lighter models travel further.\nIII. Mass affects the distance only for models with wings.", tbl: [["Model", "Mass (g)", "Wings", "Distance (m)"], ["P", "0.2", "Yes", "3.2"], ["Q", "5", "Yes", "0.9"], ["R", "0.2", "No", "1.1"], ["S", "5", "No", "0.3"]], o: ["I only", "II only", "I and II only", "I, II and III"], a: 2, why: "P vs R and Q vs S show wings help (I). P vs Q and R vs S show lighter models travel further (II). R vs S shows mass also matters without wings, so III is wrong.", lvl: 4 },
    { q: "Two identical glasses of iced water were placed for 10 minutes, one in a dry air-conditioned room and one along a humid corridor. Which is the most likely result?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Iced water", "Dry air-con room"] }, { label: "B", icon: "beaker", lines: ["Iced water", "Humid corridor"] } ] }, o: ["A gains more mass, as the cooler room makes more water vapour condense on the glass.", "Neither gains mass, as water cannot pass through the glass from the inside.", "B gains more mass, as there is more water vapour in the air to condense on the cold glass.", "B loses mass, as its ice melts faster and the water evaporates through the glass."], a: 2, why: "The droplets come from water vapour in the surrounding air. Humid air holds more water vapour, so more condenses on glass B, increasing its mass more.", lvl: 4 }
  ],
  tf: [
    { s: "Water droplets on the outside of a cold can come from water vapour in the surrounding air.", a: true, why: "The water vapour loses heat to the cold surface and condenses." },
    { s: "Water must reach 100 °C before it can evaporate.", a: false, why: "Evaporation happens at any temperature; 100 °C is the boiling point." },
    { s: "During condensation, water vapour gains heat.", a: false, why: "Water vapour LOSES heat to a cooler surface when it condenses." },
    { s: "Copper is an electrical conductor but not a magnetic material.", a: true, why: "It closes a circuit but is not attracted by a magnet or electromagnet." },
    { s: "An electromagnet attracts all metals, including aluminium.", a: false, why: "It attracts only magnetic materials such as iron, steel, nickel and cobalt." },
    { s: "Increasing the number of coils of wire makes an electromagnet stronger.", a: true, why: "More coils means a stronger magnetic effect for the same current." },
    { s: "In a parallel circuit, if one bulb fuses, all the other bulbs go out.", a: false, why: "Each bulb has its own path, so the others remain in closed circuits and stay lit." },
    { s: "Food-carrying tubes carry food made in the leaves to other parts of the plant, including the roots.", a: true, why: "The roots cannot make food, so they depend on food from the leaves." },
    { s: "Removing a ring of the outer layer of a stem immediately stops water from reaching the leaves.", a: false, why: "The water-carrying tubes are deeper inside the stem; mainly the food-carrying tubes are removed." },
    { s: "Digested food is absorbed into the blood mainly in the small intestine.", a: true, why: "The blood then carries it to all cells." },
    { s: "The heart takes in oxygen from the air and sends it to the blood.", a: false, why: "Oxygen enters the blood in the lungs; the heart pumps the blood." },
    { s: "Blood leaving the lungs has more oxygen than blood entering the lungs.", a: true, why: "Oxygen passes from the air in the lungs into the blood." },
    { s: "Fish use their gills to take in oxygen dissolved in water.", a: true, why: "The gills have many blood vessels that take in dissolved oxygen." },
    { s: "After fertilisation, the ovary develops into a seed.", a: false, why: "The ovule develops into a seed; the ovary develops into a fruit." },
    { s: "A coconut floats because its fibrous husk traps air.", a: true, why: "This lets it be dispersed by water." },
    { s: "Fruits dispersed by animals are usually dry, light and winged.", a: false, why: "Animal-dispersed fruits are often juicy and brightly coloured, or have hooks." },
    { s: "Seed dispersal reduces competition between young plants and the parent plant for water, sunlight and space.", a: true, why: "The seedlings grow away from the parent plant." },
    { s: "While ice is melting, it stops gaining heat.", a: false, why: "It keeps gaining heat, but its temperature stays at 0 °C until all of it has melted." },
    { s: "Clouds are made of water vapour.", a: false, why: "Clouds are tiny water droplets formed when water vapour condenses; water vapour itself is invisible." },
    { s: "The plastic covering of an electrical wire protects the user because plastic is an electrical insulator.", a: true, why: "It does not allow electricity to pass through to the person touching it." }
  ],
  sort: [
    { title: "Sort each fruit by its most likely method of seed dispersal.", groups: ["Wind", "Water", "Animals", "Splitting"], items: [["Angsana (flat, wing-like part)", 0], ["Lalang (tiny, with fluffy hairs)", 0], ["Coconut (fibrous husk)", 1], ["Sea almond (fibrous, floats)", 1], ["Rambutan (juicy, brightly coloured)", 2], ["Love grass (tiny hooks)", 2], ["Balsam (dry pod bursts)", 3], ["Rubber (pod splits with a crack)", 3]] },
    { title: "In each example, does the water GAIN heat or LOSE heat?", groups: ["Water gains heat", "Water loses heat"], items: [["A puddle drying up after rain", 0], ["Ice cubes melting in a drink", 0], ["Water boiling in a kettle", 0], ["Wet hair drying under a hair dryer", 0], ["Droplets forming on a cold can", 1], ["Water in an ice tray turning into ice", 1], ["Clouds forming high in the sky", 1], ["Mist forming on a bathroom mirror", 1]] },
    { title: "Which human system does each part or job belong to?", groups: ["Digestive system", "Respiratory system", "Circulatory system"], items: [["Stomach", 0], ["Absorbs digested food into the blood", 0], ["Large intestine", 0], ["Windpipe", 1], ["Nose", 1], ["Takes in oxygen from the air", 1], ["Heart", 2], ["Transports digested food and oxygen to all cells", 2], ["Blood vessels", 2]] }
  ],
  oe: [
    { q: "Mrs Lim hung three identical wet shirts outside, as shown.\n(a) Name the process by which water leaves the wet shirts. [1]\n(b) Shirt A dried faster than shirt C. Explain why. [1]\n(c) Shirt A dried faster than shirt B. Explain why. [1]", fig: { type: "setups", items: [ { label: "A", icon: "plate", lines: ["Shirt spread out", "Under the sun"] }, { label: "B", icon: "plate", lines: ["Shirt folded", "Under the sun"] }, { label: "C", icon: "plate", lines: ["Shirt spread out", "In the shade"] } ] }, marks: 3, kw: [["evaporat"], ["gain", "more heat", "higher temperature", "hotter"], ["exposed surface area", "surface area"]], model: "(a) Evaporation. (b) Shirt A was under the sun, so the water in it gained more heat and evaporated faster than in shirt C in the shade. (c) Shirt A was spread out, so it had a larger exposed surface area than the folded shirt B, and the water evaporated faster." },
    { q: "Jun made an electromagnet by winding a coil of wire around an iron nail and connecting it to a switch and batteries, as shown.\n(a) When switch S was closed, the nail attracted steel pins. Explain why. [1]\n(b) What happened to the pins when switch S was opened? [1]\n(c) Suggest two ways to make the electromagnet attract more pins. [2]", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: true }, { k: "gap", label: "X", text: "coil on iron nail" } ] }, marks: 4, kw: [["magnet"], ["fell", "fall", "drop"], ["more coils", "more turns", "number of coils"], ["more batteries", "number of batteries"]], model: "(a) Closing S made a closed circuit, so electricity flowed through the coil and the iron nail became a magnet, which attracted the steel pins (a magnetic material). (b) Most of the pins fell off. (c) Wind more coils of wire around the nail, and use more batteries." },
    { q: "Study the diagram of the human circulatory system.\n(a) Name part A. [1]\n(b) Describe how oxygen from the air reaches the muscles of the legs. [2]", fig: { type: "organs", system: "circulatory", mark: { heart: "A", lungs: "B", blood_vessels: "C" } }, marks: 3, kw: [["heart"], ["lung"], ["pump", "transport", "carried by the blood"]], model: "(a) The heart. (b) Oxygen in the air breathed in enters the blood in the lungs (B). The heart pumps the blood through the blood vessels, and the blood transports the oxygen to the cells of the leg muscles." },
    { q: "The table shows the relative amounts of substances in blood taken from three blood vessels, Q, Z and J.\n(a) Which vessel carries blood away from the lungs? [1]\n(b) Explain your answer to (a) using the table. [1]\n(c) Blood leaving the muscles has more carbon dioxide than blood entering them. Explain why. [1]\n(d) Explain why a person whose small intestine is damaged may often feel tired. [1]", tbl: [["Vessel", "Oxygen", "Digested food", "Carbon dioxide"], ["Q", "Low", "High", "High"], ["Z", "High", "Low", "Low"], ["J", "Low", "Low", "High"]], marks: 4, x: 1, kw: [["z"], ["most oxygen", "more oxygen", "high oxygen", "high in oxygen", "oxygen is high", "highest oxygen", "high level of oxygen", "a lot of oxygen"], ["produce carbon dioxide", "produces carbon dioxide", "produced carbon dioxide", "give out carbon dioxide", "gives out carbon dioxide", "release carbon dioxide", "releases carbon dioxide", "carbon dioxide as waste"], ["energy"]], model: "(a) Z. (b) Z has the most oxygen and the least carbon dioxide, because the blood has just taken in oxygen and given out carbon dioxide in the lungs. (c) The muscle cells use oxygen to release energy from digested food and produce carbon dioxide as waste, which passes into the blood. (d) Less digested food is absorbed into the blood, so the cells get less food and release less energy." },
    { q: "Study the flower.\n(a) Name part R, which develops into the fruit. [1]\n(b) Name part T, which develops into the seed. [1]\n(c) The fruit of this plant is very light and has feathery hairs. How is it most likely dispersed? [1]\n(d) Why is it important for its seeds to be dispersed away from the parent plant? [1]", fig: { type: "flower", mark: { anther: "P", stigma: "Q", ovary: "R", ovule: "T" } }, marks: 4, kw: [["ovary"], ["ovule"], ["wind"], ["competition", "compete", "overcrowd"]], model: "(a) Ovary. (b) Ovule. (c) By wind. Its light weight and feathery hairs allow it to be carried by the wind. (d) So that the young plants grow away from the parent plant, which reduces overcrowding and competition for water, sunlight, space and mineral salts." },
    { q: "A rat gnawed away a ring of the outer layer of the stem of a young papaya plant near the ground, as shown.\n(a) State the function of the roots. [1]\n(b) The leaves stayed green for a few weeks. Explain why. [1]\n(c) The whole plant later died. Explain why. [1]", fig: { type: "plant", mark: { roots: "Roots", stem: "Ring removed", leaf: "Leaves" } }, marks: 3, kw: [["absorb", "take in"], ["water-carrying", "water carrying"], ["food-carrying", "food carrying", "roots did not get food", "food could not reach"]], model: "(a) The roots absorb water and mineral salts from the soil (and hold the plant firmly in the soil). (b) The water-carrying tubes are deeper inside the stem and were not removed, so water could still be transported up to the leaves. (c) The food-carrying tubes in the outer layer were removed, so food from the leaves could not reach the roots. The roots died and could not absorb water, so the whole plant died." },
    { q: "Study the part of the water cycle shown.\n(a) Name stage P. [1]\n(b) Name the process that changes sea water into P. [1]\n(c) Explain how clouds are formed from P. [1]\n(d) Explain why the water cycle is important for Singapore’s reservoirs. [1]", fig: { type: "cycle", stages: ["Sea water", "P", "Clouds", "Rain"] }, marks: 4, kw: [["water vapour"], ["evaporat"], ["condens"], ["fresh water", "reservoir", "collect"]], model: "(a) Water vapour. (b) Evaporation: the sea water gains heat from the Sun and evaporates. (c) The water vapour rises, loses heat to the cooler air high up and condenses into tiny water droplets, which form clouds. (d) Rain falls and collects in the reservoirs, giving Singapore a continuous supply of fresh water." },
    { q: "Study the circuit. Both switches are closed and bulbs A and B are lit.\n(a) Switch S2 is opened. Which bulb(s) will be lit? [1]\n(b) Explain your answer to (a). [1]\n(c) The switches are covered in plastic. Explain why. [1]", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S1", open: false } ], branches: [ [ { k: "bulb", label: "A" } ], [ { k: "bulb", label: "B" }, { k: "switch", label: "S2", open: false } ] ] }, marks: 3, kw: [["a only", "only a", "only bulb a", "bulb a only"], ["closed circuit", "complete circuit", "own path", "separate path"]  , ["insulator", "does not conduct", "shock"]], model: "(a) Bulb A only. (b) A is on its own separate path, which is still a closed circuit, while opening S2 breaks the circuit through B. (c) Plastic is an electrical insulator, so electricity does not pass to the person touching the switch and prevents an electric shock." },
    { q: "Mei filled a metal cup and a plastic cup of the same size with the same amount of iced water. After 5 minutes, there were more water droplets on the outside of the metal cup.\n(a) Where did the water droplets come from? [1]\n(b) Explain why more droplets formed on the metal cup. [2]\n(c) Mei then filled both cups with hot water at 70 °C. Predict whether water droplets would form on the outside of the cups. [1]", fig: { type: "setups", items: [ { label: "Metal", icon: "beaker", lines: ["Metal cup", "Iced water"] }, { label: "Plastic", icon: "beaker", lines: ["Plastic cup", "Iced water"] } ] }, marks: 4, x: 1, kw: [["water vapour"], ["good conductor", "conductor of heat", "conducts heat"], ["colder", "cooler", "lower temperature"], ["no droplets", "not form", "will not"]], model: "(a) From water vapour in the surrounding air. (b) Metal is a good conductor of heat, so the metal cup lost heat to the iced water quickly and its outer surface became colder than the plastic cup. More water vapour lost heat to the colder surface and condensed. (c) No droplets will form on the outside, because the cups are warmer than the surrounding air, so the water vapour will not lose heat to them and condense." },
    { q: "Study the table of fruits J, K and L.\n(a) State how fruit J is most likely dispersed. [1]\n(b) Explain how the features of fruit K help it to be dispersed. [1]\n(c) Explain how the seeds of fruit L are carried far from the parent plant. [1]", tbl: [["Fruit", "Features"], ["J", "Very light, with feathery hairs"], ["K", "Fibrous husk, waterproof outer skin"], ["L", "Juicy, brightly coloured, hard seeds"]], marks: 3, kw: [["wind"], ["float", "traps air"], ["eaten", "eat", "droppings"]], model: "(a) By wind. (b) The fibrous husk traps air, so the fruit is light enough to float and is carried by water; the waterproof skin stops water from entering. (c) Animals are attracted to eat the juicy, brightly coloured fruit. The hard seeds are passed out in their droppings far from the parent plant." },
    { q: "Ravi wound different numbers of coils of wire around identical iron nails and counted the steel pins each electromagnet attracted. Study the graph.\n(a) Describe the relationship between the number of coils and the number of pins attracted. [1]\n(b) Predict the number of pins attracted with 50 coils. [1]\n(c) Explain why an aluminium rod could not be used in place of the iron nail. [1]", fig: { type: "bar", xl: "Number of coils", yl: "Number of pins attracted", bars: [["10", 4], ["20", 8], ["30", 12], ["40", 16]] }, marks: 3, kw: [["increase", "more pins", "more coils"], ["20"], ["magnetic material", "not magnetic", "non-magnetic", "iron is magnetic"]], model: "(a) As the number of coils increased, the number of pins attracted increased. (b) About 20 pins. (c) Aluminium is not a magnetic material, so it cannot be made into a magnet, while iron is a magnetic material." },
    { q: "Study the diagram. Explain how the digested food from Amir’s lunch reaches the cells in his legs. [2]", fig: { type: "organs", system: "digestive", mark: { stomach: "P", small_intestine: "S" } }, marks: 2, kw: [["small intestine", "absorbed"], ["heart", "blood"]], model: "The digested food is absorbed into the blood in the small intestine (S). The heart pumps the blood through the blood vessels, and the blood transports the digested food to the cells in his legs." },
    { q: "Human reproduction.\n(a) Name the organ where eggs are produced. [1]\n(b) What is fertilisation? [1]\n(c) How does a developing baby in the womb get oxygen and digested food? [1]\n(d) Explain why a baby may have characteristics of both parents. [1]", marks: 4, x: 1, kw: [["ovar"], ["fuse", "fusion", "join"], ["umbilical cord"], ["genetic", "nucleus", "from both"]], model: "(a) The ovary. (b) Fertilisation is the fusion of the sperm (male reproductive cell) with the egg (female reproductive cell). (c) From the mother’s blood, through the umbilical cord. (d) The nucleus of the sperm and the nucleus of the egg each carry genetic information, so the fertilised egg gets genetic information from both parents." },
    { q: "Mr Ong made a solar still to get drinking water from sea water, as shown. After a sunny day, water collected in the cup.\n(a) Explain how water collected in the cup. [1]\n(b) The water in the cup was not salty. Explain why. [1]\n(c) Explain why more water was collected on a sunny day than on a cloudy day. [1]", fig: { type: "setups", items: [ { label: "Basin", icon: "dish", lines: ["Sea water", "Clear plastic cover", "Stone in centre"] }, { label: "Cup", icon: "beaker", lines: ["Under the stone", "Collects water"] } ] }, marks: 3, kw: [["condens"], ["salt does not evaporate", "only water", "salt is left", "salt remains", "salt stays"], ["more heat", "gains more heat", "higher temperature", "hotter"]], model: "(a) The sea water gained heat from the Sun and evaporated. The water vapour touched the cooler plastic cover, lost heat and condensed into droplets, which ran down to the lowest point and dripped into the cup. (b) Only water evaporates; the salt does not evaporate and is left behind in the basin. (c) On a sunny day, the sea water gains more heat, so it evaporates faster and more water vapour condenses." }
  ],
  doc: [
    { q: "Farah’s glass of iced water had water droplets on the outside. Explain how the droplets formed. [2]", marks: 2, answers: ["Water vapour in the surrounding air came into contact with the cold surface of the glass, lost heat and condensed into water droplets.", "The ice melted and the water seeped through the glass.", "The water condensed."], best: 0, why: "Pupil 1 gives the source (water vapour in the air), the heat change (lost heat to the cold glass) and the process (condensed). Pupil 2 thinks the water came through the glass, and Pupil 3 names the process without saying where the water came from or the heat change." },
    { q: "Jun’s electromagnet dropped the steel pins when he opened the switch. Explain why. [1]", marks: 1, answers: ["The battery went flat.", "The magnet repelled the pins.", "The circuit was open, so no electricity flowed through the coil and the iron nail lost most of its magnetism."], best: 2, why: "Pupil 3 links the open circuit to no electricity in the coil and the nail losing magnetism. Pupil 1 invents a fault, and Pupil 2 is wrong: a magnet always attracts steel, never repels it." },
    { q: "Explain how the coconut fruit is dispersed. [2]", marks: 2, answers: ["It floats.", "Its fibrous husk traps air, so the fruit is light enough to float and is carried by water to faraway places.", "It is dispersed by water because it is round and big."], best: 1, why: "Pupil 2 gives the feature, how it helps (traps air → floats) and the method (water). Pupil 1 gives only one idea, and Pupil 3 gives the wrong feature (being round and big does not make it float)." },
    { q: "The water-carrying tubes of a plant’s stem were cut. Explain why the leaves wilted. [2]", marks: 2, answers: ["The plant had no food.", "The leaves died because the stem was cut.", "Water absorbed by the roots could not be transported up the stem to the leaves, so the leaves wilted."], best: 2, why: "Pupil 3 names what could not move (water from the roots), where it could not go (up to the leaves) and the result. Pupil 1 confuses water and food, and Pupil 2 only repeats the question." },
    { q: "Explain why Amir’s pulse rate increased while he was running. [2]", marks: 2, answers: ["The heart beat faster to pump blood faster, so more oxygen and digested food were transported to his muscles to release more energy.", "Because he was tired.", "His heart beat faster."], best: 0, why: "Pupil 1 gives the change (heart beats faster) and the reason (more oxygen and digested food to the muscles for energy). Pupil 2 has no science, and Pupil 3 only restates the observation without the reason." }
  ]
};
