window.LBY = window.LBY || {};
// Crossover 5 — wave 3 pack (integrated P3–P5)
LBY["p5-mixed"] = {
  lessons: [
    {
      h: "How to describe a trend and then explain it",
      concept: "Many Booklet B questions ask you to ‘describe’ a graph and then ‘explain’ it. These are two different jobs. DESCRIBE means saying what the data show: name the variable, give the direction of change and quote numbers from the graph (e.g. ‘increased from 72 to 140 beats per minute’). EXPLAIN means giving the science reason for the pattern, linking the body systems or processes involved. Pupils lose marks by explaining when asked only to describe, or by describing again when asked to explain.",
      example: {
        q: "Amir sat still for 2 minutes, ran on the spot from 2 to 8 minutes, and then rested. The graph shows his heart rate.\n(a) Describe how his heart rate changed from 2 to 6 minutes. [1]\n(b) Explain why his heart rate changed in this way while he was running. [2]",
        fig: { type: "line", xl: "Time (min)", yl: "Heart rate (beats per min)", pts: [["0", 72], ["2", 72], ["4", 110], ["6", 140], ["8", 140], ["10", 100], ["12", 76]] },
        marks: 3,
        think: [
          "Step 1: (a) says ‘describe’, so only read the graph. From 2 to 6 minutes the line goes up.",
          "Step 2: Quote the numbers: from 72 to 140 beats per minute. No reason is needed here.",
          "Step 3: (b) says ‘explain’, so give the science. Running muscles need more energy.",
          "Step 4: Link the systems: the heart beats faster to pump blood faster, so more oxygen and digested food are transported to the muscle cells to release more energy."
        ],
        answer: "(a) His heart rate increased from 72 to 140 beats per minute. (b) While he was running, his leg muscles needed more energy. His heart beat faster to pump blood faster, so that more oxygen and digested food were transported to the muscle cells to release more energy."
      },
      tip: "Describe = direction + numbers (‘increased from … to …’). Explain = the science reason (‘… so that more oxygen is transported …’).",
      try: {
        q: "Study the graph of Mei’s breathing rate at different walking speeds. Which answer best describes AND explains the pattern?",
        fig: { type: "bar", xl: "Walking speed (km/h)", yl: "Breathing rate (breaths per min)", bars: [["2", 18], ["4", 24], ["6", 32], ["8", 42]] },
        o: ["As her speed increased, her breathing rate increased, so more oxygen was taken in for her muscles to release more energy.", "As her speed increased, her breathing rate decreased, so less carbon dioxide was produced by her muscles as waste.", "As her speed increased, her breathing rate increased, so her lungs could pump more blood to her working muscles.", "As her speed increased, her breathing rate stayed about the same, as her muscles used the same oxygen."],
        a: 0,
        why: "The bars rise from 18 to 42 breaths per minute, so the rate increased. Faster breathing takes in more oxygen for the muscles to release more energy. The lungs do not pump blood; the heart does."
      }
    }
  ],
  mcq: [
    { q: "Study the circuit. Why is bulb A not lit?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: true }, { k: "bulb", label: "A" } ] }, o: ["The batteries are facing the wrong way round", "Switch S is open, so the circuit is not closed", "Bulb A needs a third battery to light up", "The wires are made of an electrical insulator"], a: 1, why: "Electricity flows only in a closed circuit. With S open, there is a gap in the circuit, so no electricity flows through A. Wires are made of copper, an electrical conductor.", lvl: 1 },
    { q: "Through which part does a guppy take in the oxygen dissolved in pond water?", o: ["Its fins", "Its scales", "Its gills", "Its lungs"], a: 2, why: "Fish take in dissolved oxygen through their gills, which have many blood vessels. Fish do not have lungs.", lvl: 1 },
    { q: "Which pair of parts BOTH contain female reproductive cells (egg cells)?", o: ["The anther of a flower and the testis of a man", "The stigma of a flower and the womb of a woman", "The pollen grain and the sperm of a man", "The ovule of a flower and the ovary of a woman"], a: 3, why: "The egg cell of a flowering plant is inside the ovule, and a woman’s eggs are produced in her ovaries. The anther, pollen, testis and sperm are male parts; the stigma and womb contain no eggs.", lvl: 1 },

    { q: "Which statements about the cell membrane are correct?\nA: It is found in both plant cells and animal cells.\nB: It controls the movement of substances into and out of the cell.\nC: It gives a plant cell its fixed shape.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "All cells have a cell membrane, which controls what enters and leaves the cell (A, B). The CELL WALL, found only in plant cells, gives a plant cell its fixed shape, so C is wrong.", lvl: 2 },
    { q: "Siti measured how much light passed through four sheets of the same thickness. She needs a material for a bathroom window that lets some light in but stops people outside from seeing in clearly. Study the graph. Which should she choose?", fig: { type: "bar", xl: "Material", yl: "Light passing through (units)", bars: [["Clear glass", 95], ["Frosted glass", 45], ["Plywood", 0], ["Clear plastic", 88]] }, o: ["Clear glass", "Plywood", "Clear plastic", "Frosted glass"], a: 3, why: "Frosted glass lets only some light through (translucent), so the room is bright but people cannot see in clearly. Clear glass and clear plastic let most light through, and plywood blocks all light.", lvl: 2 },
    { q: "Which shows the correct order of events that leads to a new balsam plant?", o: ["Fertilisation → pollination → seed dispersal → germination", "Pollination → seed dispersal → fertilisation → germination", "Pollination → fertilisation → seed dispersal → germination", "Seed dispersal → pollination → fertilisation → germination"], a: 2, why: "Pollen must reach the stigma (pollination) before the male reproductive cell can fuse with the egg cell (fertilisation). The ovule then becomes a seed, which is dispersed and later germinates.", lvl: 2 },
    { q: "Study the circuit. Switch S1 is closed and switch S2 is open. A steel paper clip is placed across gap X. Which bulbs are lit?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S1", open: false }, { k: "bulb", label: "A" } ], branches: [ [ { k: "bulb", label: "B" }, { k: "switch", label: "S2", open: true } ], [ { k: "bulb", label: "C" }, { k: "gap", label: "X", text: "steel paper clip" } ] ] }, o: ["A only", "A and C only", "B and C only", "A, B and C"], a: 1, why: "B’s path is open because S2 is open. C’s path is closed, as steel is an electrical conductor, so electricity flows through A (on the main path) and C.", lvl: 2 },
    { q: "Which statement about how a plant takes in the oxygen it needs is correct?", o: ["It does not need oxygen, because it can make its own food.", "It takes in oxygen only through its roots, from air in the soil.", "It takes in oxygen only through its flowers, when they open.", "It takes in oxygen mostly through tiny openings on its leaves."], a: 3, why: "Misconception: ‘plants make food, so they do not need oxygen’. Like all living things, plants use oxygen to release energy from food. They take in gases mostly through tiny openings on the underside of their leaves.", lvl: 2 },
    { q: "A dented ping-pong ball with no holes was placed in hot water, and the dent popped out. Which statement best explains this?", o: ["The air inside gained heat and expanded, pushing the dent out.", "Hot water entered the ball and pushed the dent out from inside.", "More air entered the ball through the plastic when it was heated.", "The plastic lost heat and contracted, pulling the dent back out."], a: 0, why: "Misconception: ‘more air got into the ball’. The ball is sealed, so the amount of air stays the same; the air gains heat from the hot water and expands, pushing the dent out.", lvl: 2 },

    { q: "A sealed glass tank contains moist soil and small plants. In the evening, when the room became cooler, water droplets formed on the inside of the glass. Which statements are correct?\nA: Some water evaporated from the soil and some was lost through the leaves as water vapour.\nB: The water vapour lost heat to the cooler glass and condensed.\nC: The total mass of the sealed tank and its contents increased.", o: ["A only", "B only", "A and B only", "A, B and C"], a: 2, why: "Water vapour comes from the moist soil and from the leaves (A), and it condenses on the cooler glass (B). The tank is sealed, so no matter enters or leaves and the total mass stays the same (C is wrong).", lvl: 3 },
    { q: "Study the classification key. Which objects could be Q and R?", fig: { type: "flow", root: "Materials", node: { q: "Conducts electricity?", yes: { q: "Attracted by magnet?", yes: "P", no: "Q" }, no: { q: "Lets most light through?", yes: "R", no: "S" } } }, o: ["Q: steel paper clip, R: glass slide", "Q: copper wire, R: plywood board", "Q: aluminium can, R: clear plastic ruler", "Q: rubber band, R: glass marble"], a: 2, why: "Q conducts electricity but is not magnetic (aluminium). R does not conduct electricity and is transparent (clear plastic). Steel is magnetic (P), plywood is opaque (S), and rubber does not conduct electricity.", lvl: 3 },
    { q: "A cup of hot kopi was left on a table in a room. Study the graph. Why did its temperature stay at 30 °C from 25 minutes onwards?", fig: { type: "line", xl: "Time (min)", yl: "Temperature of kopi (°C)", pts: [["0", 80], ["5", 62], ["10", 48], ["15", 38], ["20", 32], ["25", 30], ["30", 30]] }, o: ["All the heat in the kopi had been lost, so it had no heat left.", "The kopi had reached the temperature of the room, so it stopped losing heat.", "Cold from the room had stopped entering the kopi through the cup.", "The kopi had started to freeze, so its temperature stopped changing."], a: 1, why: "Misconception: ‘cold enters’ or ‘all the heat is gone’. Heat flows from a hotter object to cooler surroundings. Once the kopi was at room temperature (30 °C), there was no more heat loss, but it still has heat.", lvl: 3 },
    { q: "The stem of a white flower was split lengthwise into two halves. One half was placed in red-dyed water and the other half in blue-dyed water, as shown. After a day, what was most likely observed?", fig: { type: "setups", items: [ { label: "Left half", icon: "beaker", lines: ["Half of the stem", "Red-dyed water"] }, { label: "Right half", icon: "beaker", lines: ["Other half of stem", "Blue-dyed water"] } ] }, o: ["Some petals turned red and some turned blue.", "All the petals turned purple, as the dyes mixed.", "All the petals stayed white, as dye cannot enter.", "Only the stem turned red, as blue dye stays below."], a: 0, why: "Each half of the stem has its own water-carrying tubes, which carry the dyed water up to the petals on that side. So the petals on one side turn red and those on the other side turn blue.", lvl: 3 },
    { q: "Some kinds of plants have separate male plants and female plants. A single female plant of one such kind grows in a garden far from any other plant of its kind. Insects visit its flowers, but the flowers never develop into fruits. What is the most likely reason?", o: ["Its flowers have no ovaries, so no fruits can ever form.", "The insects eat its ovules, so no seeds can ever develop.", "Its flowers are not pollinated, so fertilisation cannot occur.", "It gets too little water, so its ovaries can never grow."], a: 2, why: "Female flowers have ovaries, but the pollen must come from a male plant of the same kind. With none nearby, the insects carry no suitable pollen, so the flowers are not pollinated and fertilisation cannot take place.", lvl: 3 },
    { q: "Nadia reads a book under a lamp in her room. Which statements are correct?\nA: She sees the book because light from the lamp is reflected by the book into her eyes.\nB: She sees the book because the book gives out its own light.\nC: In a totally dark room with the lamp off, she cannot see the book.", o: ["B only", "A and B only", "B and C only", "A and C only"], a: 3, why: "Misconception: ‘objects give out their own light’ or ‘eyes send out light’. A book is not a light source; we see it only when light reflected from it enters our eyes (A). With no light at all, we cannot see it (C).", lvl: 3 },
    { q: "Ben wants to find out if the amount of water vapour in the air affects how many droplets form on a cold container. All the containers are the same size. Which two set-ups should he compare?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Metal can", "Iced water", "Humid room"] }, { label: "B", icon: "beaker", lines: ["Metal can", "Iced water", "Dry room"] }, { label: "C", icon: "beaker", lines: ["Plastic cup", "Iced water", "Humid room"] }, { label: "D", icon: "beaker", lines: ["Metal can", "Tap water", "Humid room"] } ] }, o: ["A and B", "A and C", "A and D", "B and C"], a: 0, why: "A and B differ only in the room (humid or dry air). A and C differ in the material of the container, A and D in the temperature of the water, and B and C in two variables.", lvl: 3 },

    { q: "Study the circuit. Switch S1 is closed and switch S2 is open. Some steel pins are placed near X. Which statements are correct?\nA: X is now attracting steel pins.\nB: Closing S2 will light bulb A, and X will still attract steel pins.\nC: If bulb B then fuses, X will drop its pins but bulb A can still be lit.", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S1", open: false } ], branches: [ [ { k: "bulb", label: "A" }, { k: "switch", label: "S2", open: true } ], [ { k: "gap", label: "X", text: "coil on iron nail" }, { k: "bulb", label: "B" } ] ] }, o: ["A, B and C", "A only", "A and B only", "B and C only"], a: 0, why: "X’s branch is closed, so X is an electromagnet (A). The branches are in parallel, so closing S2 lights A without affecting X (B). B is in series with X on the same branch, so if B fuses X’s path opens, while A’s path stays closed (C).", lvl: 4 },
    { q: "Four leafy shoots of the same kind were placed in identical cylinders of water, each with a layer of oil on the water surface. Study the results. Which conclusions are supported by a fair comparison?\nA: The more leaves a shoot has, the more water it loses.\nB: A shoot loses more water in a sunny, windy spot than in a shady, still spot.\nC: Comparing R and S alone shows the effect of the number of leaves.", tbl: [["Shoot", "Number of leaves", "Placed in", "Water lost in 6 h (g)"], ["P", "10", "Sunny, windy spot", "30"], ["Q", "10", "Shady, still spot", "10"], ["R", "5", "Sunny, windy spot", "16"], ["S", "0", "Shady, still spot", "1"]], o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "P vs R (and Q vs S) differ only in the number of leaves, supporting A. P vs Q differ only in the spot, supporting B. R and S differ in both the number of leaves and the spot, so C is not a fair comparison.", lvl: 4 },
    { q: "A balloon was fitted tightly over the mouth of an empty flask. The flask was placed in hot water, and then moved into ice water. Which statements are correct?\nA: In hot water, the air in the flask gained heat and expanded.\nB: In hot water, the mass of air in the flask and balloon increased.\nC: In ice water, the air lost heat and contracted.", fig: { type: "setups", items: [ { label: "Step 1", icon: "beaker", lines: ["Flask in hot water", "Balloon inflates"] }, { label: "Step 2", icon: "beaker", lines: ["Same flask", "Moved to ice water", "Balloon goes limp"] } ] }, o: ["A and B only", "B and C only", "A, B and C", "A and C only"], a: 3, why: "Misconception: ‘heating adds more air’. The balloon seals the flask, so the mass of air stays the same (B is wrong). The air gains heat and expands into the balloon (A), then loses heat and contracts (C).", lvl: 4 },
    { q: "The pot and soil of a potted plant were wrapped in plastic, and the whole set-up was weighed every 3 hours from 6 am. Study the graph. During which period did the plant lose water fastest, and why?", fig: { type: "line", xl: "Time", yl: "Mass of set-up (g)", pts: [["6am", 500], ["9am", 494], ["12pm", 482], ["3pm", 464], ["6pm", 456], ["9pm", 454], ["12am", 453]] }, o: ["12 pm to 3 pm, as it was the hottest time, so water evaporated from the leaves fastest", "9 pm to 12 am, as the mass was the lowest then, so the most water had been lost", "6 am to 9 am, as the plant had absorbed the most water during the cool night", "3 pm to 6 pm, as the leaves had stored up the most water by late afternoon"], a: 0, why: "Misconception: reading the lowest VALUE instead of the biggest DROP. The biggest drop in a 3-hour period is 18 g (482 to 464 g), from 12 pm to 3 pm, the hottest part of the day, when water evaporates from the leaves fastest.", lvl: 4 }
  ],
  oe: [
    { q: "Ravi put one ice cube of the same size into each of four cups of the same size and thickness, made of different materials. He placed them side by side on the same table and recorded the time taken for each ice cube to melt completely.\n(a) State the aim of Ravi’s experiment. [1]\n(b) State one other variable he should keep the same to make it a fair test. [1]\n(c) Which material is the poorest conductor of heat? [1]\n(d) Explain your answer to (c) using the results. [1]", tbl: [["Material of cup", "Time for ice to melt (min)"], ["Steel", "18"], ["Glass", "32"], ["Plastic", "45"], ["Foam", "70"]], marks: 4, kw: [["material"], ["room temperature", "same room", "same place", "lid", "cover", "shape of", "temperature of the ice", "starting temperature", "initial temperature", "same freezer"], ["foam"], ["longest", "most time", "slowest", "most slowly"]], model: "(a) To find out if the material of the cup affects how long an ice cube takes to melt completely. (b) The room temperature, by keeping all the cups in the same place. (c) Foam. (d) The ice cube in the foam cup took the longest time to melt, so heat from the surroundings was conducted through the foam to the ice most slowly." },
    { q: "Aisha placed two identical leafy celery stalks in identical beakers of red-dyed water. Stalk P was placed in front of a fan and stalk Q was placed away from the fan, in the same room. She recorded the time taken for the red dye to first appear in the leaves.\n(a) Name the tubes in the stem through which the dyed water travelled. [1]\n(b) State the variable that Aisha changed. [1]\n(c) The dye reached the leaves of P sooner than those of Q. Explain why. [1]\n(d) Suggest one way to make her results more reliable. [1]", fig: { type: "setups", items: [ { label: "P", icon: "beaker", lines: ["Leafy celery stalk", "Red-dyed water", "In front of a fan"] }, { label: "Q", icon: "beaker", lines: ["Leafy celery stalk", "Red-dyed water", "No fan"] } ] }, marks: 4, x: 1, kw: [["water-carrying", "water carrying"], ["wind", "moving air", "fan", "air movement"], ["evaporat", "lost water faster", "loses water faster", "lost more water", "loses more water"], ["repeat", "more stalks", "more celery", "average"]], model: "(a) The water-carrying tubes. (b) Whether there was wind (moving air from a fan) around the stalk. (c) The moving air made water evaporate from the leaves of P faster, so P lost more water and the dyed water was drawn up its water-carrying tubes faster. (d) Repeat the experiment with more stalks in each set-up and compare the average times." },
    { q: "Hui Min connected 1, 2 and then 3 identical bulbs in series with the same 2 batteries. She used a light sensor to measure the brightness of bulb A each time. The diagram shows the circuit with 3 bulbs.\n(a) Describe how the number of bulbs in series affected the brightness of bulb A. [1]\n(b) In the circuit shown, bulb B fused. Explain why bulbs A and C also went out. [1]\n(c) Suggest how she could connect the three bulbs so that each bulb stays lit even if another one fuses. [1]", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false }, { k: "bulb", label: "A" }, { k: "bulb", label: "B" }, { k: "bulb", label: "C" } ] }, tbl: [["Number of bulbs in series", "Brightness reading of bulb A"], ["1", "90"], ["2", "45"], ["3", "30"]], marks: 3, kw: [["dimmer", "less bright", "decrease", "lower", "fell"], ["open circuit", "circuit became open", "circuit is open", "circuit was open", "one path", "single path", "only path", "same path"], ["parallel", "own path", "separate path"]], model: "(a) The more bulbs in series, the dimmer bulb A became: its brightness reading decreased from 90 to 30. (b) The bulbs are in series on one single path, so when B fused the circuit became an open circuit and no electricity could flow through A and C. (c) Connect the three bulbs in parallel, so that each bulb has its own path to the batteries." },
    { q: "Wen placed 20 green bean seeds on moist cotton wool in each of five identical dishes. Each dish was kept in a dark box at a different temperature. The graph shows the number of seeds that had germinated after 5 days.\n(a) State the aim of Wen’s experiment. [1]\n(b) At which temperature did the most seeds germinate? [1]\n(c) State one variable that Wen kept the same. [1]\n(d) The dish at 5 °C was later moved to 25 °C, and most of its seeds then germinated. What does this show about the seeds that had been kept at 5 °C? [1]", fig: { type: "line", xl: "Temperature (°C)", yl: "Seeds germinated after 5 days", pts: [["5", 0], ["15", 8], ["25", 18], ["35", 12], ["45", 0]] }, marks: 4, kw: [["temperature"], ["25"], ["number of seeds", "amount of water", "moist", "type of seed", "kind of seed", "light", "dark", "size of"], ["alive", "too cold", "suitable temperature"]], model: "(a) To find out if temperature affects the number of green bean seeds that germinate. (b) 25 °C. (c) The number of seeds in each dish (20), or the amount of water on the cotton wool. (d) The seeds were still alive. 5 °C was too cold for them to germinate, and they germinated once they had a suitable temperature." },
    { q: "A foetus develops in its mother’s womb and cannot use its own lungs to breathe.\n(a) Name the structure through which the foetus receives oxygen from its mother. [1]\n(b) Describe how oxygen from the air that the mother breathes in reaches her womb. [2]\n(c) Blood going back from the foetus to the mother has more carbon dioxide than blood going to the foetus. Explain why. [1]", marks: 4, x: 1, kw: [["umbilical"], ["lung"], ["heart", "pump"], ["release energy", "releases energy", "released energy", "carbon dioxide as waste", "produce carbon dioxide", "produces carbon dioxide", "give out carbon dioxide", "gives out carbon dioxide"]], model: "(a) The umbilical cord. (b) The oxygen enters her blood in the lungs. The heart pumps the blood through the blood vessels to the womb, where the oxygen passes through the umbilical cord to the foetus. (c) The foetus’s cells use oxygen to release energy from digested food and produce carbon dioxide as waste, which passes into the blood going back to the mother." },
    { q: "Pumpkin flowers are pollinated by insects. Mr Tan covered 10 female pumpkin flower buds with fine netting bags that insects could not pass through (set-up A), and left 10 similar female buds uncovered (set-up B). Air and light could pass through the netting. After three weeks, only the flowers in B had developed into fruits.\n(a) Explain why the flowers in A did not develop into fruits. [1]\n(b) Name the process that must take place after pollination before the ovary can develop into a fruit. [1]\n(c) Explain why Mr Tan used netting that let air and light through. [1]", fig: { type: "setups", items: [ { label: "A", icon: "pot", lines: ["10 female pumpkin buds", "Covered with netting", "Insects kept out"] }, { label: "B", icon: "pot", lines: ["10 female pumpkin buds", "Not covered", "Insects can visit"] } ] }, marks: 3, kw: [["not pollinated", "not be pollinated", "no pollination", "could not reach", "cannot reach", "could not carry"], ["fertilis"], ["fair test", "only variable", "one variable", "only difference"]], model: "(a) Insects could not reach the flowers in A to carry pollen to their stigmas, so the flowers were not pollinated. (b) Fertilisation. (c) So that it is a fair test: whether insects could reach the flowers is the only variable changed, as both set-ups still got air and light." }
  ],
  tf: [
    { s: "Plants do not need to take in oxygen because they can make their own food.", a: false, why: "Plant cells, like all living cells, use oxygen to release energy from food. Plants take in oxygen through tiny openings, mostly on the leaves." },
    { s: "The white mist seen just above the spout of a boiling kettle is water vapour.", a: false, why: "Water vapour is invisible. The mist is tiny water droplets formed when the hot water vapour loses heat to the cooler air and condenses." },
    { s: "In the same room, a metal spoon feels colder than a wooden spoon because the metal spoon is at a lower temperature.", a: false, why: "Both are at room temperature. Metal is a better conductor of heat, so it conducts heat away from your hand faster and feels colder." },
    { s: "Adding more bulbs in series to a circuit makes each bulb brighter.", a: false, why: "With the same batteries, more bulbs in series make each bulb dimmer." },
    { s: "Both sperm and eggs are produced in the womb.", a: false, why: "Sperm are produced in the testes and eggs in the ovaries. The womb is where the fertilised egg develops into a foetus." },
    { s: "A nickel coin can close a circuit and can also be attracted by a magnet.", a: true, why: "Nickel is a metal, so it conducts electricity, and it is also a magnetic material." },
    { s: "The umbilical cord carries oxygen and digested food from the mother’s blood to the foetus.", a: true, why: "It also carries waste such as carbon dioxide from the foetus back to the mother." },
    { s: "A white flower placed in blue-dyed water can turn blue because its water-carrying tubes carry the dyed water up to the petals.", a: true, why: "The dye travels with the water up the stem to the petals." },
    { s: "Sweat on the skin takes in heat from the body as it evaporates, which helps to cool the body.", a: true, why: "Evaporation needs heat, so the skin loses heat to the evaporating sweat." },
    { s: "Fish gills and human lungs both allow oxygen to pass into the blood.", a: true, why: "Both have many blood vessels that take in oxygen: from water for gills, from air for lungs." }
  ],
  doc: [
    { q: "Aunty May stirred hot soup with a steel spoon. Soon, the handle of the spoon became hot. Explain why. [2]", marks: 2, answers: ["The spoon is hot because the soup is hot.", "Steel is a good conductor of heat, so heat from the hot soup was conducted quickly along the spoon to the handle.", "The heat went into the spoon and the cold came out of the handle."], best: 1, why: "Pupil 2 names the property (steel is a good conductor of heat) and describes how heat moved (from the hot soup along the spoon to the handle). Pupil 1 only restates the observation, and Pupil 3 wrongly talks about ‘cold’ moving; only heat moves, from hotter to cooler." },
    { q: "A guppy was taken out of its tank and left on a dry table. Explain why it could not survive for long. [2]", marks: 2, answers: ["It cannot swim on the table.", "It needs water to drink.", "It takes in oxygen dissolved in water through its gills. Out of water, it cannot take in enough oxygen, so its cells cannot release energy."], best: 2, why: "Pupil 3 links gills to taking in dissolved oxygen and explains why the fish needs it (to release energy). Pupil 1 gives no science about survival, and Pupil 2 names the wrong reason; the key need is oxygen from the water." }
  ]
};
