window.LBX = window.LBX || {};
// Crossover 5 extension — wider integrated P3–P5 questions (cells, light, heat, matter, circuits, reproduction)
LBX["p5-mixed"] = {
  notes: [
    { h: "Cells link many topics", t: "All living things are made of cells. Plant and animal cells both have a cell membrane, cytoplasm and a nucleus, which controls the cell’s activities and contains genetic information. Only plant cells have a cell wall, and only cells in parts exposed to light, such as leaf cells, have chloroplasts, which trap light to make food. At fertilisation, the nucleus of the male reproductive cell fuses with the nucleus of the egg cell, so the young gets genetic information from both parents.", kw: ["cell membrane", "nucleus", "genetic information", "chloroplasts", "cell wall"] },
    { h: "One material, many properties", t: "Ask which property a question is testing: conducting heat, conducting electricity, letting light through, or being attracted by a magnet. Metals are good conductors of both heat and electricity, but only iron, steel, nickel and cobalt are magnetic. Light travels in straight lines, so an opaque object blocks light and a shadow forms behind it. Most materials gain heat and expand, and lose heat and contract.", kw: ["good conductor of heat", "electrical conductor", "magnetic material", "opaque", "straight lines", "expand"] },
    { h: "Fair tests work the same way in every topic", t: "To find out how one variable affects a result, change ONLY that variable and keep all the others the same. Seeds need water, air and a suitable temperature to germinate; they do not need light. Electromagnet strength depends on the number of coils and the number of batteries. How fast water evaporates depends on temperature, wind, exposed surface area and how much water vapour is already in the air.", kw: ["change only one variable", "keep all others the same", "water, air and a suitable temperature"] }
  ],
  traps: [
    "All plant cells have chloroplasts → only cells in parts that get light (e.g. leaf cells) have them; root cells do not.",
    "Seeds need light to germinate → germination needs water, air and a suitable temperature; the young plant needs light later to make food.",
    "The mist on a mirror when you breathe on it is saliva → it is water vapour in the exhaled air that loses heat to the cooler mirror and condenses."
  ],
  lessons: [
    {
      h: "How to choose set-ups for a fair test in any topic",
      concept: "Whatever the topic, a fair comparison changes ONLY the variable being tested and keeps every other variable the same. Write down every difference between two set-ups. The correct pair differs in exactly one thing: the variable in the question. A pair that differs in two things cannot tell you which one caused the result.",
      example: {
        q: "Farah poured 50 ml of water into each container and placed them in the same room.\n(a) Which two set-ups should she compare to find out if wind affects how fast water evaporates? [1]\n(b) Which two set-ups should she compare to find out if exposed surface area affects how fast water evaporates? [1]\n(c) Explain why set-ups B and C cannot be compared to test either variable. [1]",
        fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["50 ml water", "Wide dish", "Fan on"] }, { label: "B", icon: "dish", lines: ["50 ml water", "Wide dish", "No fan"] }, { label: "C", icon: "beaker", lines: ["50 ml water", "Narrow beaker", "Fan on"] } ] },
        marks: 3,
        think: [
          "Step 1: List the differences. A vs B: only the fan. A vs C: only the container (exposed surface area). B vs C: the fan AND the container.",
          "Step 2: Wind is tested by the pair that differs only in the fan: A and B.",
          "Step 3: Exposed surface area is tested by the pair that differs only in the container: A and C.",
          "Step 4: B and C differ in two variables, so any difference in results cannot be linked to just one of them."
        ],
        answer: "(a) A and B. (b) A and C. (c) B and C differ in two variables, the wind and the exposed surface area, so she cannot tell which variable caused the difference in how fast the water evaporated."
      },
      tip: "Before choosing a pair, say out loud what is different about it. If you find two differences, it is not a fair test.",
      try: {
        q: "Jun wants to find out if the number of batteries affects the strength of an electromagnet. Which must he keep the same in every set-up?",
        o: ["The number of batteries connected to the coil", "The number of coils and the type of nail used", "The number of pins attracted by the nail", "The strength of the electromagnet each time"],
        a: 1,
        why: "The number of batteries is the variable he changes, and the number of pins attracted is what he measures. The number of coils and the type of nail must stay the same so the test is fair."
      }
    },
    {
      h: "How to explain a mass change using matter and changes of state",
      concept: "Matter has mass. A change of state does not add or remove matter, so in a SEALED container the mass stays the same when ice melts or water evaporates. Mass changes only when matter leaves or enters: water vapour escaping from an open container makes the mass decrease, and water vapour from the air condensing on a cold outer surface makes the mass increase.",
      example: {
        q: "Two identical containers each held 200 g of ice. Container P was sealed and container Q was left open. After two days, all the ice had melted and the water had reached room temperature.\n(a) What was the mass of P’s contents? Explain. [2]\n(b) The mass of Q’s contents decreased. Explain why. [1]",
        fig: { type: "setups", items: [ { label: "P", icon: "jar", lines: ["200 g of ice", "Sealed with a lid"] }, { label: "Q", icon: "jar", lines: ["200 g of ice", "No lid"] } ] },
        marks: 3,
        think: [
          "Step 1: In P, ice melted into water. Melting only changes the state; no matter entered or left the sealed container.",
          "Step 2: So the mass of P’s contents stayed at 200 g.",
          "Step 3: In Q, the water gained heat from the surroundings and evaporated.",
          "Step 4: The water vapour escaped through the open top, so matter left and the mass decreased."
        ],
        answer: "(a) 200 g. Melting only changed the ice into water; no matter entered or left the sealed container, so the mass stayed the same. (b) The water gained heat from the surroundings and evaporated, and the water vapour escaped into the air through the open top, so the mass decreased."
      },
      tip: "For every mass question, ask: did any matter get IN or OUT? If the container is sealed, the answer is no and the mass stays the same.",
      try: {
        q: "A sealed bottle of cold drink was placed on a balance on a humid day. Water droplets soon formed on the outside of the bottle. What happened to the balance reading?",
        o: ["It decreased, as the cold drink evaporated through the bottle", "It stayed the same, as the bottle was sealed tightly", "It increased, as water vapour from the air condensed on it", "It increased, as the cold drink expanded inside the bottle"],
        a: 2,
        why: "Water vapour from the surrounding air lost heat to the cold bottle and condensed on it, adding matter to what is on the balance. Nothing passed through the sealed bottle, and expanding does not change mass."
      }
    }
  ],
  mcq: [
    { q: "Study the plant cell. Which part controls the movement of substances into and out of the cell?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "A", cell_membrane: "B", nucleus: "C", chloroplast: "D" } }, o: ["A", "B", "C", "D"], a: 1, why: "B is the cell membrane, which controls what enters and leaves the cell. The cell wall (A) gives the plant cell its shape and support but lets substances pass through freely.", lvl: 1 },
    { q: "Study the flower. In which part does the male reproductive cell fuse with the egg cell during fertilisation?", fig: { type: "flower", mark: { anther: "P", stigma: "Q", style: "R", ovule: "S" } }, o: ["P", "Q", "R", "S"], a: 3, why: "The egg cell is inside the ovule (S), so fertilisation takes place there. Pollen grains land on the stigma (Q), but fusion does not happen there.", lvl: 1 },
    { q: "Which part is found in a leaf cell but NOT in a human cheek cell?", o: ["Nucleus", "Cytoplasm", "Chloroplast", "Cell membrane"], a: 2, why: "Chloroplasts are found only in plant cells in parts that get light. Both cells have a nucleus, cytoplasm and a cell membrane.", lvl: 1 },
    { q: "The diagram shows the life cycle of a mosquito. What is stage ‘?’ called, and where does it live?", fig: { type: "cycle", stages: ["Egg", "?", "Pupa", "Adult"] }, o: ["Larva, living in water", "Larva, living on leaves", "Nymph, living in water", "Nymph, living on land"], a: 0, why: "A mosquito has a four-stage life cycle. The larva lives in water and comes up to the surface to breathe. Nymphs belong to three-stage life cycles such as the cockroach’s.", lvl: 1 },
    { q: "Which part of a sperm cell carries the genetic information that is passed on to the baby?", o: ["Cell membrane", "Cytoplasm", "Tail", "Nucleus"], a: 3, why: "Genetic information is found in the nucleus. At fertilisation, the nucleus of the sperm fuses with the nucleus of the egg.", lvl: 1 },

    { q: "Study the circuit. All three bulbs were lit. Bulb B then fused. Which bulbs stayed lit?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false }, { k: "bulb", label: "A" }, { k: "bulb", label: "B" }, { k: "bulb", label: "C" } ] }, o: ["None of the bulbs", "Only bulb A", "Bulbs A and C", "Bulbs A, B and C"], a: 0, why: "The bulbs are in series, on one single path. When B fuses, the circuit becomes open, so no electricity flows and all the bulbs go out.", lvl: 2 },
    { q: "Ali shone a torch at a toy and measured the height of its shadow on a screen. Study the graph. At which of the distances tested was the shadow taller than 30 cm?", fig: { type: "line", xl: "Distance of torch from toy (cm)", yl: "Height of shadow (cm)", pts: [["10", 48], ["20", 24], ["30", 16], ["40", 12]] }, o: ["At 10 cm from the toy", "At 20 cm from the toy", "At 30 cm from the toy", "At 40 cm from the toy"], a: 0, why: "The graph shows the shadow was 48 cm tall at 10 cm, and only 24 cm or shorter at the other distances. The closer the torch was to the toy, the taller the shadow.", lvl: 2 },
    { q: "A metal ball could pass through a metal ring. After the ball was heated, it could not pass through. Which statement explains this?", fig: { type: "setups", items: [ { label: "Before", icon: "plate", lines: ["Metal ball", "Room temperature", "Passes through ring"] }, { label: "After", icon: "plate", lines: ["Same ball, heated", "Ring not heated", "Stuck on the ring"] } ] }, o: ["The ball gained heat and expanded, so it became bigger.", "The ball lost heat and contracted, so the ring was too big.", "The ball gained heat and became heavier, so it could not fall.", "The ring gained heat from the ball and contracted around it."], a: 0, why: "Heating makes the ball gain heat and expand, so it no longer fits. Its mass does not change, and a ring that gains heat would expand, not contract.", lvl: 2 },
    { q: "Study the Venn diagram. Sam needs a cover for a switch box so that he can see the switches inside AND will not get an electric shock if he touches the cover. Which material is most suitable?", fig: { type: "venn", a: "Lets most light through", b: "Conducts electricity", onlyA: ["glass", "clear plastic"], both: [], onlyB: ["copper", "steel"], neither: ["wood", "rubber"] }, o: ["Copper", "Clear plastic", "Wood", "Steel"], a: 1, why: "Clear plastic lets most light through (so he can see inside) and does not conduct electricity (so it is safe). Wood is safe but opaque; copper and steel conduct electricity.", lvl: 2 },
    { q: "The same amount of water was spilled on four identical floor tiles, placed as shown in the table. Which tile most likely dried first?", tbl: [["Tile", "Room temperature (°C)", "Fan"], ["P", "25", "Off"], ["Q", "25", "On"], ["R", "32", "On"], ["S", "32", "Off"]], o: ["P", "Q", "R", "S"], a: 2, why: "Water evaporates faster at a higher temperature and when there is wind. Tile R has both the higher temperature and the fan switched on.", lvl: 2 },
    { q: "Study the digestive system. In which parts are digestive juices produced to digest food?", fig: { type: "organs", system: "digestive", mark: { mouth: "A", gullet: "B", stomach: "C", small_intestine: "D", large_intestine: "E" } }, o: ["B, C and E only", "C, D and E only", "A, B and C only", "A, C and D only"], a: 3, why: "Digestive juices are produced in the mouth (A), stomach (C) and small intestine (D). No digestion takes place in the gullet (B) or the large intestine (E).", lvl: 2 },
    { q: "A flower has large, brightly coloured petals, a sweet scent and nectar. How is it most likely pollinated?", o: ["By wind, which blows its light pollen to other flowers", "By insects, which are attracted and carry its pollen", "By water, which carries its pollen to flowers downstream", "By splitting, as its anthers burst and fling pollen away"], a: 1, why: "Bright petals, scent and nectar attract insects, and pollen sticks to their bodies. ‘Splitting’ is a method of seed dispersal, not pollination.", lvl: 2 },
    { q: "Huda breathed onto a cold mirror and it became misty. Which statement best explains this?", o: ["The oxygen in her breath changed into water on the cold mirror.", "Her warm breath made the mirror gain heat and give out water.", "Tiny drops of saliva from her mouth were sprayed onto the mirror.", "Water vapour in her exhaled air lost heat to the mirror and condensed."], a: 3, why: "Exhaled air contains more water vapour than inhaled air. The water vapour loses heat to the cooler mirror and condenses into tiny droplets. Oxygen does not turn into water.", lvl: 2 },

    { q: "Three ring magnets are placed on a rod, as shown. Ring B floats above ring A, and ring C rests on ring B. What are the poles on the upper faces of rings B and C?", fig: { type: "rings", rings: [ { label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" } ], gaps: [true, false] }, o: ["B: N, C: S", "B: S, C: N", "B: S, C: S", "B: N, C: N"], a: 2, why: "B floats, so its lower face repels A’s upper N face: B’s lower face is N and its upper face is S. C touches B, so they attract: C’s lower face is N, making its upper face S.", lvl: 3 },
    { q: "Study the circuit. Switch S1 is closed and switch S2 is open. A plastic ruler is placed across gap X. Which bulb(s) will light up?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S1", open: false } ], branches: [ [ { k: "bulb", label: "A" }, { k: "switch", label: "S2", open: true } ], [ { k: "bulb", label: "B" } ], [ { k: "bulb", label: "C" }, { k: "gap", label: "X", text: "plastic ruler" } ] ] }, o: ["A only", "B only", "B and C only", "A, B and C"], a: 1, why: "The bulbs are in parallel. A’s path is open because S2 is open, and C’s path is open because plastic is an electrical insulator. Only B’s path is a closed circuit.", lvl: 3 },
    { q: "Rods of the same size were heated at one end. The graph shows how long the wax at the other end of each rod took to melt. Which conclusion is correct?", fig: { type: "bar", title: "Time for wax to melt", xl: "Material of rod", yl: "Time (s)", bars: [["Copper", 20], ["Aluminium", 30], ["Steel", 70], ["Glass", 240]] }, o: ["Copper is the best conductor of heat of the four, as its wax melted first.", "Glass is the best conductor of heat of the four, as its wax took the longest.", "Steel conducts heat better than aluminium, as its wax took longer to melt.", "All four conduct heat equally well, as the wax on every rod melted in the end."], a: 0, why: "The shorter the time, the faster heat was conducted along the rod. Copper took the shortest time, so it is the best conductor of heat; glass is the poorest.", lvl: 3 },
    { q: "Mei wants to find out if seeds need light to germinate. Which two set-ups should she compare?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["Moist cotton wool", "In the light", "25 °C"] }, { label: "B", icon: "dish", lines: ["Moist cotton wool", "In the dark", "25 °C"] }, { label: "C", icon: "dish", lines: ["Dry cotton wool", "In the dark", "25 °C"] }, { label: "D", icon: "dish", lines: ["Moist cotton wool", "In the light", "5 °C"] } ] }, o: ["B and C", "A and D", "A and B", "C and D"], a: 2, why: "A and B differ only in light; water and temperature are the same. B and C differ in water, A and D differ in temperature, and C and D differ in three things.", lvl: 3 },
    { q: "Which substance is carried from the foetus to the mother’s blood through the umbilical cord?", o: ["Oxygen, for the foetus’s cells to release energy", "Digested food, for the foetus’s cells to grow", "Waste such as carbon dioxide, for the mother to remove", "Genetic information, so the foetus looks like the mother"], a: 2, why: "Oxygen and digested food pass from the mother to the foetus. Waste such as carbon dioxide passes the other way, from the foetus to the mother’s blood. Genetic information came from the sperm and egg at fertilisation.", lvl: 3 },
    { q: "A dish of salt solution was left in the sun. The graph shows its mass each day. Why did the mass stop decreasing after Day 4?", fig: { type: "line", xl: "Day", yl: "Mass of salt solution (g)", pts: [["0", 100], ["1", 76], ["2", 52], ["3", 28], ["4", 20], ["5", 20], ["6", 20]] }, o: ["The salt absorbed water vapour from the air, keeping the mass the same.", "The water had frozen into ice, so it could no longer evaporate.", "All the water had evaporated, leaving salt, which does not evaporate.", "The Sun stopped giving out heat, so the water no longer evaporated."], a: 2, why: "Only the water evaporates. Once all of it had evaporated, only the salt (20 g) was left, and it does not evaporate, so the mass stayed the same.", lvl: 3 },
    { q: "Study the classification key. Which cell is most likely Q?", fig: { type: "flow", root: "Cells", node: { q: "Has a cell wall?", yes: { q: "Has chloroplasts?", yes: "P", no: "Q" }, no: "R" } }, o: ["Human cheek cell", "Leaf cell of a balsam plant", "Root hair cell of a plant", "Human muscle cell"], a: 2, why: "Q has a cell wall (a plant cell) but no chloroplasts. A root hair cell is underground and has no chloroplasts. A leaf cell would be P, and human cells have no cell wall (R).", lvl: 3 },

    { q: "Study the results of Jun’s electromagnet experiment. Which statements are supported by the results?\nI. More batteries give a stronger electromagnet.\nII. More coils give a stronger electromagnet.\nIII. The material of the core affects the strength of the electromagnet.\nIV. Comparing A and C alone shows the effect of the number of coils.", tbl: [["Set-up", "Batteries", "Coils", "Core", "Pins attracted"], ["A", "1", "20", "Iron", "5"], ["B", "2", "20", "Iron", "10"], ["C", "2", "40", "Iron", "18"], ["D", "2", "40", "Aluminium", "0"]], o: ["I and II only", "II and IV only", "I, II, III and IV", "I, II and III only"], a: 3, why: "A vs B changes only batteries (I), B vs C only coils (II), C vs D only the core (III). A and C differ in both batteries and coils, so that comparison is not a fair test (IV is wrong).", lvl: 4 },
    { q: "Study the circuit. Bulbs A and B are lit and electromagnet X is attracting steel pins. Which ONE fault would make bulbs A and B go out AND make X drop its pins?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S", open: false }, { k: "bulb", label: "A" } ], branches: [ [ { k: "bulb", label: "B" } ], [ { k: "gap", label: "X", text: "coil on iron nail" } ] ] }, o: ["Bulb B fuses", "Bulb A fuses", "The coil of X breaks", "A wire to bulb B breaks"], a: 1, why: "A is on the main path, in series with both branches, so if A fuses no electricity flows anywhere. If B or its wire fails, X still has its own closed path; if the coil breaks, A and B stay lit.", lvl: 4 },
    { q: "Rods P and Q were placed in turn across gap Y in the circuit shown. Each rod was also tested with a magnet. Study the results. Which could rods P and Q be?", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "copper wire" }, { k: "gap", label: "Y", text: "rod tested" } ] }, tbl: [["Rod", "Bulb A", "Attracted by a magnet?"], ["P", "Not lit", "No"], ["Q", "Lit", "Yes"]], o: ["P: aluminium, Q: iron", "P: wood, Q: copper", "P: steel, Q: rubber", "P: glass, Q: steel"], a: 3, why: "P does not conduct electricity and is not magnetic (glass fits). Q conducts electricity and is magnetic (steel fits). Aluminium conducts, copper is not magnetic, and rubber does not conduct.", lvl: 4 },
    { q: "Study Amir’s breathing rate and heart rate before, during and after a run. Which statements are correct?\nI. While running, more oxygen was taken in and transported to his muscles each minute.\nII. At 15 min, his breathing rate was back to its resting value but his heart rate was not.\nIII. While running, his muscles needed less energy than when resting.", tbl: [["Time (min)", "Activity", "Breathing rate (per min)", "Heart rate (per min)"], ["0", "Resting", "16", "72"], ["5", "Running", "40", "150"], ["10", "Resting", "24", "100"], ["15", "Resting", "16", "78"]], o: ["I only", "I and II only", "II and III only", "I, II and III"], a: 1, why: "Both rates rose while running, so more oxygen was taken in and pumped to the muscles (I). At 15 min breathing was 16 (resting value) but heart rate was 78, not 72 (II). Running muscles need MORE energy, so III is wrong.", lvl: 4 }
  ],
  tf: [
    { s: "Plant cells have a cell wall, but animal cells do not.", a: true, why: "The cell wall gives a plant cell its fixed shape and support." },
    { s: "Root cells have chloroplasts, so they can make food in the soil.", a: false, why: "Root cells have no chloroplasts; there is no light underground. They get food from the leaves." },
    { s: "The mist formed when you breathe onto a cold mirror comes from water vapour in your exhaled air.", a: true, why: "The water vapour loses heat to the cooler mirror and condenses." },
    { s: "Steel is a good conductor of heat but does not conduct electricity.", a: false, why: "Steel, like other metals, conducts both heat and electricity." },
    { s: "A shadow forms because light bends around an opaque object.", a: false, why: "Light travels in straight lines, so the opaque object blocks it and a shadow forms behind it." },
    { s: "Seeds need light to germinate.", a: false, why: "Seeds need water, air and a suitable temperature to germinate; seeds can germinate in the dark." },
    { s: "The nucleus of a cell contains genetic information.", a: true, why: "It also controls the activities of the cell." },
    { s: "When ice melts in a sealed container, the total mass stays the same.", a: true, why: "Melting changes the state but no matter enters or leaves the sealed container." },
    { s: "Pollination and fertilisation are two names for the same process.", a: false, why: "Pollination is the transfer of pollen to the stigma; fertilisation is the fusion of the male reproductive cell with the egg cell." },
    { s: "Mosquito larvae live in water but come up to the surface to take in air.", a: true, why: "They breathe air through a tube at the water surface, which is why a layer of oil can kill them." }
  ],
  sort: [
    { title: "Which job does each part do?", groups: ["Reproduction", "Transport", "Taking in or giving out gases"], items: [["Ovary of a flower", 0], ["Anther", 0], ["Testis", 0], ["Heart", 1], ["Food-carrying tubes", 1], ["Blood vessels", 1], ["Gills of a fish", 2], ["Lungs", 2], ["Tiny openings on the underside of leaves", 2]] }
  ],
  oe: [
    { q: "The diagram shows a cell from the leaf of a plant.\n(a) Name part X. [1]\n(b) State the function of part X. [1]\n(c) Cells from the roots of the same plant do not have part X. Suggest why the root cells do not need part X. [1]", fig: { type: "cell", kind: "plant", mark: { chloroplast: "X", cell_wall: "Y", nucleus: "Z" } }, marks: 3, kw: [["chloroplast"], ["trap light", "traps light", "absorb light", "absorbs light", "make food", "makes food"], ["no light", "not receive light", "not get light", "underground", "in the soil", "dark"]], model: "(a) Chloroplast. (b) It contains chlorophyll, which traps light energy so that the plant can make food. (c) The roots are underground in the soil, where there is no light, so chloroplasts in the root cells could not trap light to make food." },
    { q: "An electric kettle has a steel body and a plastic handle.\n(a) Give two reasons why the handle is made of plastic. [2]\n(b) Steam from the spout formed water droplets on the cooler wall tiles nearby. Explain how the droplets formed. [1]", marks: 3, kw: [["poor conductor of heat", "does not conduct heat", "not conduct heat", "insulator of heat", "heat insulator"], ["electrical insulator", "insulator of electricity", "poor conductor of electricity", "not conduct electricity", "shock"], ["condens"]], model: "(a) Plastic is a poor conductor of heat, so the handle does not become too hot to hold. Plastic is also an electrical insulator, so electricity will not pass to the hand, which prevents an electric shock. (b) The hot water vapour touched the cooler tiles, lost heat to them and condensed into water droplets." },
    { q: "Two identical balsam plants were placed as shown for two weeks. Plant A stayed healthy, but plant B became weak and its leaves turned yellow.\n(a) Explain why plant B became weak. [1]\n(b) Ryan wants to cover plant A with a box to keep insects away, while still letting it get as much light as possible. What kind of material should the box be made of? [1]\n(c) Explain your answer to (b). [1]", fig: { type: "setups", items: [ { label: "A", icon: "pot", lines: ["Balsam plant", "Near a window", "Watered daily"] }, { label: "B", icon: "pot", lines: ["Balsam plant", "In a dark cupboard", "Watered daily"] } ] }, marks: 3, kw: [["make food", "making food"], ["transparent"], ["light to pass", "allows light", "allow light", "lets light", "let light", "light can pass", "light through", "most light"]], model: "(a) Plant B received no light, so it could not make food and became weak. (b) A transparent material, such as clear plastic. (c) A transparent material allows most light to pass through, so plant A can still get enough light to make food." },
    { q: "A scrapyard crane uses electromagnet X to separate steel cans from aluminium cans. X is connected in the circuit shown, together with warning bulb L.\n(a) Which cans will X pick up? Explain. [1]\n(b) How can the worker make X drop the cans it is holding? [1]\n(c) Bulb L fuses while X is holding some cans. Predict what happens to the cans and explain why. [1]", fig: { type: "circuit", cells: 3, main: [ { k: "switch", label: "S", open: false }, { k: "bulb", label: "L" }, { k: "gap", label: "X", text: "electromagnet" } ] }, marks: 3, kw: [["magnetic"], ["open the switch", "open switch", "open s", "opening the switch", "switch off", "switching off", "switch is opened"], ["series", "one path", "only path", "same path"]], model: "(a) The steel cans, because steel is a magnetic material and aluminium is not. (b) Open switch S, so that electricity stops flowing through the coil and X loses most of its magnetism. (c) The cans will drop. L and X are in series, on the same single path, so when L fuses the circuit becomes open, no electricity flows through X and it loses most of its magnetism." },
    { q: "The diagram shows a cell from the inside of a human cheek.\n(a) Name part A and state its function. [2]\n(b) Explain why this cell cannot make its own food. [1]\n(c) Apart from your answer to (b), name one part that a plant cell has but this cell does not have. [1]", fig: { type: "cell", kind: "animal", mark: { nucleus: "A", cytoplasm: "B", cell_membrane: "C" } }, marks: 4, kw: [["nucleus"], ["control"], ["chloroplast"], ["cell wall"]], model: "(a) Nucleus. It controls all the activities of the cell and contains genetic information. (b) It has no chloroplasts to trap light to make food. (c) Cell wall." },
    { q: "Mr Lee could not open the tight metal lid of a glass jar of kaya. He held the lid under hot running water for a minute, and then he opened it easily.\n(a) Explain why the lid became easier to open. [2]\n(b) Explain why, in that minute, the metal lid was affected much more than the glass jar. [1]", marks: 3, kw: [["gain"], ["expand"], ["good conductor of heat", "conductor of heat", "conducts heat"]], model: "(a) The metal lid gained heat from the hot water and expanded, so it became slightly bigger and looser around the mouth of the jar. (b) Metal is a good conductor of heat, so the lid gained heat quickly, while glass is a poor conductor of heat and gained heat slowly, so the jar expanded much less." },
    { q: "Study the flower, which is pollinated by insects.\n(a) Name part P. [1]\n(b) Explain how insects help to pollinate this flower. [1]\n(c) A gardener removed part Q from some flowers before they opened. Predict whether these flowers will develop into fruits, and explain why. [2]", fig: { type: "flower", mark: { anther: "P", stigma: "Q", ovary: "R", petal: "S" } }, marks: 4, x: 1, kw: [["anther"], ["stick", "carr", "transfer"], ["not be pollinated", "cannot be pollinated", "pollination cannot", "no pollination", "not pollinated"], ["fertilis"]], model: "(a) Anther. (b) Insects visit the flower for its nectar. Pollen grains from the anther stick to their bodies and are carried to the stigma of the same or another flower. (c) No fruits will develop. Without the stigma, pollen grains have nowhere to land, so the flowers cannot be pollinated. Fertilisation cannot take place, so the ovary will not develop into a fruit." },
    { q: "Three measuring cylinders had the same amount of water, each covered with a layer of oil. A had a leafy shoot, B had a similar shoot with all its leaves removed, and C had no shoot. The graph shows the drop in water level after 2 days.\n(a) Why was a layer of oil added to each cylinder? [1]\n(b) Explain why the water level in A dropped much more than in B. [1]\n(c) Set-up A was then placed in front of a fan. Predict how the drop in water level would change, and explain why. [1]", fig: { type: "bar", title: "Drop in water level after 2 days", xl: "Set-up", yl: "Drop in water level (ml)", bars: [["A", 12], ["B", 3], ["C", 0]] }, marks: 3, x: 1, kw: [["prevent", "stop", "water surface", "surface of the water"], ["tiny openings", "lost through the leaves", "lose water", "loses water", "lost water"], ["greater", "larger", "bigger", "faster", "more quickly", "drop more", "drop even more"]], model: "(a) To prevent the water from evaporating from the water surface, so that any drop in water level is caused by the shoots only. (b) A had leaves. Water taken in by the shoot is lost as water vapour through the tiny openings of the leaves, so A lost much more water than B. (c) The drop would be greater, because the moving air makes the water evaporate faster from the leaves." }
  ],
  doc: [
    { q: "A leaf cell can make food but a root hair cell cannot. Explain why. [1]", marks: 1, answers: ["The root is under the soil.", "The leaf cell has chloroplasts, which trap light to make food, but the root hair cell has no chloroplasts.", "The leaf cell is bigger and greener than the root hair cell."], best: 1, why: "Pupil 2 names the part (chloroplasts), its job (trap light to make food) and that the root hair cell lacks it. Pupil 1 gives a location but does not link it to chloroplasts or light, and Pupil 3 describes looks without any science." },
    { q: "Ali shone a torch at an opaque toy. Explain why a dark shadow formed on the screen behind the toy. [2]", marks: 2, answers: ["The toy is opaque, so it blocks light. Light travels in straight lines, so it cannot reach the part of the screen behind the toy.", "Because the toy is dark in colour.", "The light bends around the toy."], best: 0, why: "Pupil 1 gives both ideas: the opaque toy blocks light, and light travels in straight lines. Pupil 2 thinks colour causes the shadow, and Pupil 3 is wrong because light does not bend around objects." },
    { q: "Seeds placed on dry cotton wool did not germinate, but seeds on moist cotton wool did. Explain why. [1]", marks: 1, answers: ["The seeds needed sunlight.", "The cotton wool was dry.", "Seeds need water to germinate, and the dry cotton wool did not provide any water."], best: 2, why: "Pupil 3 links the condition needed (water) to the result. Pupil 1 names the wrong condition (seeds do not need light to germinate), and Pupil 2 only repeats the question without saying what the seeds need." }
  ]
};
