window.LBZ = window.LBZ || {};
LBZ["p5-mixed"] = {
  flash: [
    { f: "Define: evaporation", b: "The change of state from liquid to gas when a liquid gains heat. It takes place at any temperature, at the exposed surface of the liquid." },
    { f: "Define: condensation", b: "The change of state from gas to liquid when water vapour loses heat, e.g. to a cooler surface, and becomes water droplets." },
    { f: "Evaporation vs boiling", b: "Evaporation: at any temperature, only at the exposed surface, slow. Boiling: only at the boiling point (100 °C for pure water), throughout the liquid, fast, with bubbles." },
    { f: "State the factors that affect the rate of evaporation.", b: "Temperature of the surroundings, the amount of wind (moving air), the humidity (amount of water vapour in the air) and the exposed surface area of the liquid." },
    { f: "Define: pollination", b: "The transfer of pollen grains from the anther to the stigma, by agents such as insects, wind or water." },
    { f: "Define: fertilisation (in flowering plants)", b: "The male reproductive cell from the pollen grain fuses with the female reproductive cell (egg cell) in the ovule." },
    { f: "Function of the nucleus", b: "Controls all the activities of the cell and contains genetic information." },
    { f: "Function of the cell membrane", b: "Controls the movement of substances into and out of the cell." },
    { f: "Function of the chloroplast", b: "Contains chlorophyll, which traps light energy for the plant to make food. Found in plant cells such as leaf cells, but not in animal cells." },
    { f: "Water-carrying tubes vs food-carrying tubes", b: "Water-carrying tubes carry water and mineral salts from the roots to all parts of the plant. Food-carrying tubes carry food from the leaves to all parts of the plant." },
    { f: "Function of the circulatory system", b: "The heart pumps blood around the body. Blood carries oxygen, digested food and water to all parts of the body, and carbon dioxide from the body to the lungs." },
    { f: "What happens to the air in the lungs?", b: "Oxygen in the inhaled air moves into the blood in the lungs. Carbon dioxide moves out of the blood into the air in the lungs and is breathed out." },
    { f: "Series vs parallel: what happens if one bulb fuses?", b: "Series: the circuit becomes open, so all the other bulbs go out. Parallel: the other bulbs stay lit, as each of their branches still forms a closed circuit." },
    { f: "How can an electromagnet be made stronger?", b: "Increase the number of coils of wire around the iron core, or increase the number of batteries connected in series." },
    { f: "Why is seed dispersal important?", b: "It prevents overcrowding, so the young plants do not compete with one another and with the parent plant for water, sunlight, space and mineral salts." }
  ],
  mcq: [
    { q: "Study the plant cell. Which part gives the cell a regular shape and supports it?", o: ["A", "B", "C", "D"], a: 2, why: "C is the cell wall, which gives a plant cell its regular shape and support. A is the nucleus, B is the vacuole and D is a chloroplast.", lvl: 1, fig: { type: "cell", kind: "plant", mark: { nucleus: "A", vacuole: "B", cell_wall: "C", chloroplast: "D" } } },
    { q: "On a hot afternoon at Gardens by the Bay, misting fans spray a fine mist of water near visitors, and they feel cooler. Which process mainly cools them?", o: ["Condensation of water vapour onto their skin", "Evaporation of the tiny water droplets", "Melting of the water in the mist", "Freezing of the water in the air"], a: 1, why: "The tiny droplets evaporate, gaining heat from the skin and the surrounding air, so the visitors feel cooler. Condensation happens when water vapour loses heat; it does not take heat from the skin.", lvl: 1 },
    { q: "Study the flower. Which part produces pollen grains?", o: ["A", "B", "C", "D"], a: 0, why: "A is the anther, which produces pollen grains. B is the stigma, which receives pollen, C is the ovary and D is a petal.", lvl: 1, fig: { type: "flower", mark: { anther: "A", stigma: "B", ovary: "C", petal: "D" } } },
    { q: "The pins of the plug for a fridge in an HDB flat are made of metal, but the casing of the plug is made of plastic. Why is the casing made of plastic?", o: ["Plastic is a good conductor of heat.", "Plastic is attracted by magnets.", "Plastic allows light to pass through.", "Plastic is an electrical insulator."], a: 3, why: "Plastic is an electrical insulator, so electricity cannot flow through the casing to the user’s hand. Plastic is a poor conductor of heat and is not attracted by magnets.", lvl: 1 },

    { q: "Mdm Lee hung a wet towel along her HDB corridor at 9 am and weighed it every hour. Study the graph. How much water had evaporated from the towel by 11 am, and from what time did its mass stop decreasing?", o: ["150 g; from 12 pm", "150 g; from 2 pm", "350 g; from 12 pm", "200 g; from 1 pm"], a: 0, why: "By 11 am the mass fell from 500 g to 350 g, so 150 g of water had evaporated. The mass stayed at 300 g from 12 pm onwards, so the towel was dry and no more water evaporated. 350 g is the mass of the wet towel at 11 am, not the mass of water lost.", lvl: 2, fig: { type: "line", title: "Drying a wet towel", xl: "Time", yl: "Mass of towel (g)", pts: [["9 am", 500], ["10 am", 420], ["11 am", 350], ["12 pm", 300], ["1 pm", 300], ["2 pm", 300]] } },
    { q: "Study the diagram of the circulatory system. Which substance does the blood pick up at B, and where is this blood carried next?", o: ["Carbon dioxide; to A, which pumps it to the rest of the body", "Oxygen; to A, which pumps it to the rest of the body", "Oxygen; to C, which carries it straight back to B", "Digested food; to A, which pumps it to B"], a: 1, why: "B is the lungs, where blood picks up oxygen. This oxygen-rich blood returns to the heart (A), which pumps it to all parts of the body. Blood gives out carbon dioxide at the lungs; it does not pick it up.", lvl: 2, fig: { type: "organs", system: "circulatory", mark: { heart: "A", lungs: "B", blood_vessels: "C" } } },
    { q: "During a long dry spell with hot, sunny days, the water level in MacRitchie Reservoir dropped. Which statement best explains this?", o: ["Water lost heat to the air and condensed, and little rain fell.", "Water lost heat at night and turned into water vapour.", "Water gained heat from the Sun and evaporated, and little rain fell.", "Water gained heat from the Sun and boiled away at 100 °C."], a: 2, why: "Water at the surface gained heat from the Sun and evaporated, and little rain fell to replace it. Water does not need to reach 100 °C to evaporate, and condensation is when water vapour loses heat.", lvl: 2 },
    { q: "Which statement about the nucleus of a cell is NOT correct?", o: ["It controls the activities of the cell.", "It contains genetic information.", "It is found in both plant and animal cells.", "It controls what enters and leaves the cell."], a: 3, why: "The cell membrane, not the nucleus, controls the movement of substances into and out of the cell. The nucleus controls the cell’s activities, contains genetic information and is found in both plant and animal cells.", lvl: 2 },
    { q: "Ming wants to find out if the number of leaves on a shoot affects how much water the shoot loses. Study the set-ups. Which two set-ups should he compare?", o: ["A and B", "A and D", "B and C", "C and D"], a: 2, why: "B and C differ only in the number of leaves; both are away from the fan with 200 ml of water. A and B differ in the fan, while A and D (and C and D) differ in more than one variable.", lvl: 2, fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Shoot with 10 leaves", "Near a fan", "200 ml of water"] }, { label: "B", icon: "beaker", lines: ["Shoot with 10 leaves", "Away from the fan", "200 ml of water"] }, { label: "C", icon: "beaker", lines: ["Shoot with 4 leaves", "Away from the fan", "200 ml of water"] }, { label: "D", icon: "beaker", lines: ["Shoot with 4 leaves", "Near a fan", "100 ml of water"] } ] } },
    { q: "The lights in a school canteen are connected in parallel. What is one advantage of this?", o: ["If one bulb fuses, the other bulbs stay lit.", "If one bulb fuses, all the other bulbs go out.", "Electricity flows through each bulb one after another.", "One switch must always control every bulb at once."], a: 0, why: "In a parallel circuit, each bulb is on its own branch, so when one bulb fuses, the other branches still form closed circuits and their bulbs stay lit. Electricity flowing through each bulb one after another describes a series circuit.", lvl: 2 },
    { q: "In the Venn diagram, X, Y and Z are a root hair cell, a leaf cell and a human cheek cell. Which correctly identifies them?", o: ["X: leaf cell, Y: root hair cell, Z: cheek cell", "X: root hair cell, Y: leaf cell, Z: cheek cell", "X: cheek cell, Y: leaf cell, Z: root hair cell", "X: root hair cell, Y: cheek cell, Z: leaf cell"], a: 1, why: "A root hair cell has a cell wall but no chloroplasts (X). A leaf cell has both (Y). A human cheek cell is an animal cell with neither (Z).", lvl: 2, fig: { type: "venn", a: "Has a cell wall", b: "Has chloroplasts", onlyA: ["X"], both: ["Y"], onlyB: [], neither: ["Z"] } },

    { q: "Study the circuit. Switch S1 is closed, switch S2 is open and a copper wire is placed across gap X. Which statements are correct?\nI. Bulb A is lit.\nII. Bulbs B and C are lit.\nIII. If S1 is opened, all the bulbs go out.\nIV. If the copper wire is replaced with a rubber band, bulb B goes out.", o: ["I and II only", "II and III only", "III and IV only", "I, II and III only"], a: 1, why: "S2 is open, so A’s branch is open and A is not lit. B’s branch and C’s branch (closed by the copper wire, a conductor) are closed, so B and C light. S1 is on the main loop, so opening it turns off every bulb. A rubber band only opens C’s branch, so B stays lit.", lvl: 3, fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S1", open: false } ], branches: [ [ { k: "bulb", label: "A" }, { k: "switch", label: "S2", open: true } ], [ { k: "bulb", label: "B" } ], [ { k: "bulb", label: "C" }, { k: "gap", label: "X", text: "copper wire" } ] ] } },
    { q: "A root hair cell has no chloroplasts and is under the ground. How does it get the food it needs?", o: ["It makes its own food using light that reaches the soil.", "It absorbs food from the soil together with mineral salts.", "Water-carrying tubes bring food to it from the leaves.", "Food-carrying tubes bring food made in the leaves to it."], a: 3, why: "Without chloroplasts the root hair cell cannot make food, so food made in the leaves is carried down to it by the food-carrying tubes. Roots absorb water and mineral salts, not food, and water-carrying tubes carry water upwards.", lvl: 3 },
    { q: "In some countries, large areas of forest are cut down, and the places nearby later receive less rain. Which best explains this?", o: ["Less water evaporates from leaves into the air, so fewer clouds form.", "More water evaporates from the bare soil, so fewer clouds form.", "Water vapour can only condense on the leaves of trees, not in the air.", "The roots of trees used to carry water up into the clouds."], a: 0, why: "Trees take in water through their roots, and much of it evaporates from their leaves into the air. With fewer trees, there is less water vapour to rise, lose heat and condense into clouds, so less rain falls.", lvl: 3 },
    { q: "Two identical beakers of hot water at the same temperature were covered with identical metal plates, as shown. After 2 minutes, the undersides of the plates were checked. Which is most likely?", o: ["Only Q’s plate had droplets, as water vapour gains heat from a cold plate.", "Both plates had the same number of droplets, as the water was equally hot.", "P’s plate had more droplets, as water vapour lost heat to it faster.", "Neither plate had droplets, as metal plates do not allow condensation."], a: 2, why: "P’s plate is colder, so the water vapour from the hot water loses heat to it faster and more of it condenses into droplets. Water vapour loses heat (not gains heat) when it condenses.", lvl: 3, fig: { type: "setups", items: [ { label: "P", icon: "beaker", lines: ["Hot water", "Covered: metal plate", "Plate from the fridge"] }, { label: "Q", icon: "beaker", lines: ["Hot water", "Covered: metal plate", "Plate at room temp."] } ] } },
    { q: "Four dishes each held 200 ml of water in the same room. The table shows how they were placed, and the graph shows the volume of water lost in 3 hours. Which conclusions are correct?\nI. Moving air increases the rate of evaporation.\nII. A larger exposed surface area increases the rate of evaporation.\nIII. Comparing P and R alone shows the effect of exposed surface area.", o: ["I only", "I and II only", "II and III only", "I, II and III"], a: 1, why: "P lost more than Q, and S more than R, so moving air increases evaporation (I). R lost more than Q, and S more than P, so a larger exposed surface area increases evaporation (II). P and R differ in both surface area and the fan, so that comparison is not fair (III is wrong).", lvl: 3, tbl: [["Dish", "Exposed surface area (cm²)", "Placed"], ["P", "50", "In front of a fan"], ["Q", "50", "Away from the fan"], ["R", "100", "Away from the fan"], ["S", "100", "In front of a fan"]], fig: { type: "bar", title: "Water lost in 3 hours", xl: "Dish", yl: "Volume of water lost (ml)", bars: [["P", 14], ["Q", 8], ["R", 15], ["S", 26]] } },
    { q: "A fruit contains 12 seeds. Which statement must be true?", o: ["The flower it came from had exactly 12 ovaries.", "Only 12 pollen grains landed on the stigma.", "12 different flowers were pollinated to form it.", "At least 12 ovules in the ovary were fertilised."], a: 3, why: "Each seed develops from one fertilised ovule, so at least 12 ovules were fertilised. A fruit develops from the ovary of one flower, and many more pollen grains may land on the stigma than are needed.", lvl: 3 },

    { q: "Jun made electromagnets by winding coils of wire around identical iron nails and recorded his results in the table. He forgot to record the result for set-up D. What is the most likely number of steel pins that D attracted?", o: ["3", "4", "8", "20"], a: 2, why: "D has the same number of coils as A but more batteries, so it should attract more than 4 pins. D has the same number of batteries as C but fewer coils, so it should attract fewer than 15 pins. Only 8 fits both comparisons.", lvl: 4, tbl: [["Set-up", "Number of coils", "Number of batteries", "Steel pins attracted"], ["A", "10", "1", "4"], ["B", "20", "1", "8"], ["C", "20", "2", "15"], ["D", "10", "2", "?"]] },
    { q: "On a hot day, water in an unglazed clay pot, which has many tiny holes, stays cooler than water in a glazed pot with no holes. Which explains this?", o: ["Water seeps out through the holes and evaporates, gaining heat from the pot and the water.", "Clay is a good conductor of heat, so heat flows quickly from the water to the air.", "Water vapour from the air condenses on the clay pot, and this cools the water inside.", "The tiny holes let cold air flow into the pot and mix with the water, cooling it."], a: 0, why: "Water seeps to the outer surface of the clay pot and evaporates. Evaporation needs heat, which it gains from the pot and the water inside, so the water cools. Clay is a poor conductor of heat, and condensing water vapour does not cool the water.", lvl: 4 },
    { q: "A glass of iced water was placed on a balance along a humid corridor. Study the graph. Which statement best explains the changes in its mass?", o: ["The ice inside melted and became heavier, then some of the water evaporated.", "Water vapour evaporated onto the glass, and then the droplets froze on the glass.", "Water inside seeped out of the glass, and then water vapour condensed back inside.", "Water vapour condensed on the cold glass; later the glass warmed and the droplets evaporated."], a: 3, why: "At first the glass was cold, so water vapour in the humid air lost heat to it and condensed, adding mass. Once the glass warmed to near room temperature, condensation stopped and the droplets evaporated, so the mass fell. Melting does not change mass.", lvl: 4, fig: { type: "line", title: "Mass of a glass of iced water", xl: "Time (min)", yl: "Mass (g)", pts: [["0", 350], ["5", 353], ["10", 355], ["15", 356], ["20", 356], ["40", 354], ["60", 352]] } }
  ],
  oe: [
    { q: "On a sunny morning, Kai sealed a clear plastic bag around a leafy branch of a potted plant (set-up A). He sealed an identical bag around a similar branch with all its leaves removed (set-up B). After 3 hours, many water droplets had formed on the inside of bag A, but very few in bag B.\n(a) Name the tubes that carried water from the roots to the leaves. [1]\n(b) Explain how the droplets formed on the inside of bag A. [2]\n(c) Explain why very few droplets formed in bag B. [1]", marks: 4, kw: [["water-carrying", "water carrying", "xylem"], ["evaporat"], ["condens"], ["no leaves", "leaves were removed", "leaves removed", "had no leaf", "has no leaf", "no leaf", "without leaves", "fewer leaves"]], model: "(a) Water-carrying tubes. (b) Water from the leaves evaporated into water vapour. The water vapour came into contact with the cooler inner surface of the bag, lost heat and condensed into water droplets. (c) Branch B had no leaves, so very little water evaporated from it into the bag.", x: 1, fig: { type: "setups", items: [ { label: "A", icon: "pot", lines: ["Leafy branch", "In sealed clear bag", "In the sun"] }, { label: "B", icon: "pot", lines: ["Branch, no leaves", "In sealed clear bag", "In the sun"] } ] } },
    { q: "The table shows the percentage of three gases in inhaled air (P) and exhaled air (Q).\n(a) Using the table, state two differences between exhaled air and inhaled air. [2]\n(b) In which organ does oxygen from the inhaled air move into the blood? [1]\n(c) When Amir runs, his breathing rate increases. Explain why. [1]", marks: 4, kw: [["less oxygen", "lower percentage of oxygen", "smaller percentage of oxygen", "16"], ["more carbon dioxide", "higher percentage of carbon dioxide", "greater percentage of carbon dioxide"], ["lung", "air sac"], ["more oxygen", "oxygen faster", "more energy"]], model: "(a) Exhaled air has less oxygen than inhaled air (16% instead of 21%). Exhaled air has more carbon dioxide than inhaled air (4% instead of 0.04%). (b) The lungs. (c) His muscles need more oxygen to release more energy, so he breathes faster to take in more oxygen and remove carbon dioxide faster.", tbl: [["Gas", "Inhaled air P (%)", "Exhaled air Q (%)"], ["Oxygen", "21", "16"], ["Carbon dioxide", "0.04", "4"], ["Nitrogen", "78", "78"]] },
    { q: "Siti made a steady-hand game. A steel loop on a plastic handle is moved along a bare, bent steel wire. If the loop touches the wire, the gap X in the circuit is closed and the bulb lights up.\n(a) Explain why the bulb lights up when the loop touches the wire. [2]\n(b) Explain why the handle is made of plastic. [1]\n(c) Suggest one way to make the bulb light up more brightly. [1]", marks: 4, kw: [["conductor", "conduct electricity", "conducts electricity"], ["closed", "complete"], ["insulator", "does not conduct electricity", "cannot conduct electricity"], ["more batter", "another batter", "extra batter", "more cell", "another cell", "extra cell"]], model: "(a) Steel is an electrical conductor, so when the loop touches the wire, the circuit becomes a closed circuit and electricity flows through the bulb. (b) Plastic is an electrical insulator, so electricity does not flow to the player’s hand. (c) Add another battery in series to the circuit.", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "loop touches wire" } ] } },
    { q: "Cucumber plants have separate male and female flowers, which are pollinated by insects. Mr Lim’s cucumber plants on the rooftop garden of a tall HDB block flowered well, but very few fruits formed because few insects visited.\n(a) Explain why very few fruits formed. [2]\n(b) Mr Lim used a small brush to transfer pollen from the male flowers to the female flowers. Onto which part of the female flower should he brush the pollen? [1]\n(c) Name the part of the female flower that develops into a seed. [1]", marks: 4, kw: [["pollinat"], ["fertilis", "fertiliz"], ["stigma"], ["ovule"]], model: "(a) Few insects carried pollen grains from the anthers of the male flowers to the stigmas of the female flowers, so few flowers were pollinated. Without pollination, fertilisation could not take place, so the ovaries did not develop into fruits. (b) The stigma. (c) The ovule." }
  ],
  tf: [
    { s: "Water evaporates only when the Sun is shining on it.", a: false, why: "Evaporation takes place at any temperature, including at night and indoors, as long as there is exposed liquid. Heat from the Sun only makes it faster." },
    { s: "Water vapour is an invisible gas.", a: true, why: "Water vapour cannot be seen. The mist or clouds we see are tiny water droplets formed when water vapour condenses." },
    { s: "A plant absorbs most of its water through its leaves.", a: false, why: "Water and mineral salts are absorbed by the roots, especially the root hairs, and carried up by the water-carrying tubes." },
    { s: "Each seed in a fruit develops from one fertilised ovule.", a: true, why: "After fertilisation, each ovule develops into a seed, and the ovary develops into the fruit." },
    { s: "The heart is part of the respiratory system.", a: false, why: "The heart is part of the circulatory system; it pumps blood. The respiratory system includes the nose, windpipe and lungs." },
    { s: "Blood carries carbon dioxide from the body cells to the lungs.", a: true, why: "Blood carries carbon dioxide from all parts of the body to the lungs, where it is removed and breathed out." },
    { s: "Pollen grains contain the female reproductive cells of a flower.", a: false, why: "Pollen grains contain the male reproductive cells. The female reproductive cells (egg cells) are in the ovules." },
    { s: "A bulb lights up only when it is part of a closed circuit.", a: true, why: "Electricity flows only through a complete, unbroken path (a closed circuit). An open switch or a gap stops the flow." },
    { s: "Wet clothes dry faster on a humid day than on a dry day.", a: false, why: "Humid air already holds a lot of water vapour, so water evaporates from the clothes more slowly. Clothes dry faster on a dry day." },
    { s: "Connecting more identical bulbs in parallel to the same batteries does not make each bulb dimmer.", a: true, why: "Each bulb in parallel is on its own branch connected across the batteries, so each stays about as bright as one bulb alone. Bulbs added in series become dimmer." }
  ],
  sort: [
    { title: "Sort each object by whether it conducts electricity and whether a magnet attracts it.", groups: ["Conducts electricity AND attracted by a magnet", "Conducts electricity, NOT attracted by a magnet", "Does not conduct electricity"], items: [["Steel paper clip", 0], ["Iron nail", 0], ["Steel pin", 0], ["Copper wire", 1], ["Aluminium foil", 1], ["Gold ring", 1], ["Plastic ruler", 2], ["Rubber band", 2], ["Wooden chopstick", 2], ["Glass marble", 2]] }
  ]
};
