window.LBU = window.LBU || {};
LBU["p5-mixed"] = {
  glossary: [
    { t: "Water cycle", d: "The continuous movement of water between the Earth’s surface and the air through evaporation, condensation and rain. Heat from the Sun drives it." },
    { t: "Cell", d: "The basic unit of life. All living things are made up of one or more cells." },
    { t: "Cell wall", d: "A tough outer layer found in plant cells but not in animal cells. It gives the plant cell a regular shape and supports it." },
    { t: "Cytoplasm", d: "A jelly-like substance inside the cell membrane where most of the cell’s activities take place." },
    { t: "Stomata", d: "Tiny openings, found mostly on the underside of leaves, through which a plant takes in and gives out gases and loses water vapour." },
    { t: "Ovule", d: "The part inside the ovary of a flower that contains the egg cell (female reproductive cell). After fertilisation, it develops into a seed." },
    { t: "Seed dispersal", d: "The spreading of seeds or fruits away from the parent plant by wind, water, animals or by splitting." },
    { t: "Electromagnet", d: "A coil of wire wound around an iron core. It becomes a temporary magnet only when electricity flows through the coil in a closed circuit." },
    { t: "Closed circuit", d: "A complete, unbroken path of electrical conductors through which electricity flows from the batteries, through the components and back." },
    { t: "Parallel circuit", d: "A circuit in which the components are on separate branches, so each has its own path to the batteries." },
    { t: "Umbilical cord", d: "The cord joining the foetus to its mother in the womb. It carries oxygen and digested food from the mother to the foetus, and carbon dioxide and other waste materials from the foetus to the mother." },
    { t: "Gills", d: "The breathing organs of a fish. They have many blood vessels, which take in oxygen dissolved in the water." }
  ],
  lessons: [
    {
      h: "How to decide which bulbs light in a circuit with branches",
      concept: "A bulb lights up only if there is a closed path through it from one end of the batteries back to the other. Trace each bulb’s path: every switch on it must be closed, every gap must be bridged by an electrical conductor, and no bulb on it may be fused. A switch or bulb on the main loop affects every bulb; one on a branch affects only that branch – unless every branch is open, which leaves the main loop open too.",
      example: {
        q: "Study the circuit. Switch S1 is closed and switch S2 is open. A plastic straw is placed across gap X. Which bulb(s) will light up? Explain your answer. [2]",
        fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S1", open: false }, { k: "bulb", label: "A" }], branches: [[{ k: "bulb", label: "B" }, { k: "switch", label: "S2", open: true }], [{ k: "bulb", label: "C" }, { k: "gap", label: "X", text: "plastic straw" }]] },
        marks: 2,
        think: [
          "Step 1: Trace branch B: S2 is open, so this branch is an open circuit and bulb B cannot light.",
          "Step 2: Trace branch C: the plastic straw is an electrical insulator, so this branch is also open and bulb C cannot light.",
          "Step 3: Bulb A is on the main loop. Electricity can only return to the batteries through branch B or branch C, and both are open.",
          "Step 4: So there is no closed circuit at all – even bulb A, with its closed switch S1, stays unlit. Most pupils wrongly answer ‘bulb A only’."
        ],
        answer: "None of the bulbs will light up. S2 is open and the plastic straw is an electrical insulator, so both branches are open. There is no closed circuit, so no electricity flows through bulb A either."
      },
      tip: "Before saying a main-loop bulb is lit, check that at least one branch gives a complete path back to the batteries.",
      try: {
        q: "Study the circuit. Switch S is closed and all three bulbs are lit. Bulb B then fuses. Which bulb(s) stay lit?",
        fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S", open: false }, { k: "bulb", label: "A" }], branches: [[{ k: "bulb", label: "B" }], [{ k: "bulb", label: "C" }]] },
        o: ["C only", "A and C only", "A only", "None of them"],
        a: 1,
        why: "Bulb B’s branch becomes open, but bulb C’s branch still gives a closed path through bulb A on the main loop, so A and C stay lit. ‘C only’ forgets that A is in series with C’s branch."
      }
    },
    {
      h: "How to tell pollination, fertilisation and their results apart",
      concept: "Pollination is the transfer of pollen grains from the anther to the stigma. Fertilisation comes after it: the male reproductive cell from the pollen grain fuses with the egg cell in an ovule. Only a fertilised ovule develops into a seed, and the ovary develops into the fruit. So the number of seeds in a fruit tells you how many ovules were fertilised – not how many pollen grains landed on the stigma.",
      example: {
        q: "Study the flower. Its ovary contains 8 ovules. Many pollen grains landed on part R, but only 5 ovules were fertilised. (a) How many seeds will develop? [1] (b) Name the part that will develop into the fruit. [1] (c) Explain why pollination alone does not make an ovule develop into a seed. [1]",
        fig: { type: "flower", mark: { stigma: "R", ovary: "P", ovule: "Q" } },
        marks: 3,
        think: [
          "Step 1: Each seed comes from ONE fertilised ovule. 5 ovules were fertilised, so 5 seeds develop – the 8 ovules and the many pollen grains are distractors.",
          "Step 2: The ovary (P), which holds the ovules, develops into the fruit.",
          "Step 3: Pollination only puts the pollen on the stigma (R). Name the next step in full: the male reproductive cell must fuse with the egg cell in the ovule.",
          "Step 4: Use the two process words correctly – never write ‘pollination’ when you mean ‘fertilisation’."
        ],
        answer: "(a) 5 seeds. (b) The ovary, part P. (c) After pollination, the male reproductive cell in the pollen grain must still fuse with the egg cell in the ovule (fertilisation). Only a fertilised ovule develops into a seed."
      },
      tip: "Count seeds from fertilised ovules, and always name the parts that fuse: male reproductive cell + egg cell, in the ovule.",
      try: {
        q: "Before a flower opened, Ali cut off its stigma. He did not touch the anthers. What most likely happened later?",
        o: ["No fruit formed, as pollination could not take place.", "A fruit formed, but its ovules did not become seeds.", "Seeds formed, but the ovary did not become a fruit.", "A fruit with seeds formed, as the anthers were kept."],
        a: 0,
        why: "Without a stigma, pollen grains cannot land and be trapped, so there is no pollination, no fertilisation and so no seeds or fruit. Keeping the anthers does not help, because pollen must reach a stigma."
      }
    }
  ],
  flash: [
    { f: "Function of the ovary of a flower", b: "Contains the ovules. After fertilisation, the ovary develops into the fruit." },
    { f: "Function of the stigma", b: "Receives pollen grains during pollination. It is often sticky or feathery to trap the pollen grains." },
    { f: "Function of the testes and the ovaries (humans)", b: "The testes produce sperms, the male reproductive cells. The ovaries produce eggs, the female reproductive cells." },
    { f: "Function of the womb", b: "The fertilised egg develops into a foetus in the womb, where it is protected until the baby is born." },
    { f: "Electrical conductor vs electrical insulator", b: "Conductor: allows electricity to flow through it, e.g. copper, steel, aluminium. Insulator: does not allow electricity to flow through it, e.g. plastic, rubber, wood." },
    { f: "Why is an iron nail used as the core of an electromagnet?", b: "Iron is a magnetic material. It becomes magnetised when electricity flows through the coil, making the electromagnet much stronger. Copper or plastic would not." },
    { f: "Effect of adding more batteries in series on a bulb", b: "More electric current flows through the bulb, so it lights up more brightly." },
    { f: "Function of the respiratory system", b: "Takes in oxygen from the air into the body and removes carbon dioxide from the body. Its parts include the nose, windpipe and lungs." },
    { f: "Function of the vacuole", b: "Contains cell sap. In a plant cell, the large central vacuole stores water, mineral salts and food substances." },
    { f: "How are clouds formed?", b: "Warm water vapour rises, loses heat to the cooler air high above the ground and condenses into tiny water droplets, which form clouds." },
    { f: "Features of an insect-pollinated flower", b: "Large, brightly coloured petals, a sweet scent and nectar to attract insects; sticky or spiky pollen grains that stick to the insects." },
    { f: "Features of a wind-pollinated flower", b: "Small, dull petals with no scent or nectar; large amounts of light, dry pollen; feathery stigmas that hang outside the flower to trap pollen." }
  ],
  mcq: [
    { q: "Study the animal cell. Which correctly names parts A, B and C?", fig: { type: "cell", kind: "animal", mark: { cell_membrane: "A", cytoplasm: "B", nucleus: "C" } }, o: ["A: cell wall, B: cytoplasm, C: nucleus", "A: cell membrane, B: cytoplasm, C: nucleus", "A: cell membrane, B: nucleus, C: cytoplasm", "A: cell wall, B: nucleus, C: cytoplasm"], a: 1, why: "An animal cell has no cell wall, so its outer layer A is the cell membrane. B is the jelly-like cytoplasm and C is the nucleus, which controls the cell’s activities.", lvl: 1 },
    { q: "Which part of the human male reproductive system produces sperms?", o: ["Ovaries", "Womb", "Umbilical cord", "Testes"], a: 3, why: "The testes produce sperms. The ovaries produce eggs, the womb is where the foetus develops, and the umbilical cord joins the foetus to its mother.", lvl: 1 },
    { q: "Study the respiratory system. Through which part does air pass on its way from the nose to the lungs?", fig: { type: "organs", system: "respiratory", mark: { nose: "Q", windpipe: "R", lungs: "P" } }, o: ["P", "Q", "R", "P and Q"], a: 2, why: "Air enters through the nose (Q), passes down the windpipe (R) and reaches the lungs (P). Q is where the air enters, not the part between the nose and the lungs.", lvl: 1 },
    { q: "Which feature is most likely found in a flower that is pollinated by wind?", o: ["Feathery stigmas that hang out", "Large, brightly coloured petals", "A sweet scent and much nectar", "Sticky pollen that clumps together"], a: 0, why: "Feathery stigmas hanging outside the flower trap pollen carried by the wind. Bright petals, scent, nectar and sticky pollen are features of insect-pollinated flowers.", lvl: 1 },
    { q: "Pupils counted how many times insects visited four kinds of flowers, W, X, Y and Z, in the school garden in 30 minutes. Study the graph. Which flower most likely has large, brightly coloured petals, a sweet scent and nectar?", fig: { type: "bar", xl: "Flower", yl: "Number of insect visits in 30 min", bars: [["W", 2], ["X", 15], ["Y", 0], ["Z", 8]] }, o: ["W", "X", "Y", "Z"], a: 1, why: "Bright petals, scent and nectar attract insects, so the flower with the most insect visits, X (15 visits), most likely has these features. Y had no visits at all.", lvl: 2 },
    { q: "Which statement about a plant leaf cell and a human cheek cell is NOT correct?", o: ["Both have a nucleus.", "Both have a cell membrane.", "Both have cytoplasm.", "Both have a cell wall."], a: 3, why: "Only plant cells have a cell wall. Both kinds of cells have a nucleus, a cell membrane and cytoplasm.", lvl: 2 },
    { q: "Hafiz placed a cut balsam stem with leaves in red-dyed water for two hours. He then cut the stem across and looked at the cut surface. Where would he see the red dye?", o: ["In the food-carrying tubes only", "Evenly over the whole cut surface", "In the water-carrying tubes only", "In both kinds of tubes equally"], a: 2, why: "The dyed water is carried up the stem in the water-carrying tubes only, so only these tubes turn red. Food-carrying tubes carry food made in the leaves, not water from the roots.", lvl: 2 },
    { q: "The doorbell of an HDB flat uses an electromagnet. While the button is pressed, the electromagnet attracts a steel striker that hits the bell. Why does the electromagnet stop attracting the striker when the button is released?", o: ["The steel striker becomes a magnet that repels the coil", "The batteries stop storing electrical energy for a while", "The coil of wire changes into an electrical insulator", "The circuit is open, so the electromagnet loses its magnetism"], a: 3, why: "Releasing the button opens the circuit, so no electricity flows through the coil and the electromagnet loses its magnetism. The coil is still copper, a conductor, and the batteries still store energy.", lvl: 2 },
    { q: "Ali wants to find out if the number of batteries affects the strength of an electromagnet. Study the set-ups. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Iron nail", "20 coils", "1 battery"] }, { label: "B", icon: "box", lines: ["Iron nail", "20 coils", "2 batteries"] }, { label: "C", icon: "box", lines: ["Iron nail", "40 coils", "2 batteries"] }, { label: "D", icon: "box", lines: ["Steel rod", "40 coils", "1 battery"] }] }, o: ["A and B", "A and D", "B and C", "C and D"], a: 0, why: "A and B differ ONLY in the number of batteries; the core and number of coils are the same. B and C differ in the number of coils, and A and D differ in both the core and the number of coils.", lvl: 2 },
    { q: "Study the events.\nP: The fertilised egg develops into a foetus in the womb.\nQ: A sperm fuses with an egg.\nR: The testes produce sperms and the ovaries produce eggs.\nS: The baby is born.\nWhich shows the correct order?", o: ["Q → R → P → S", "R → P → Q → S", "R → Q → P → S", "P → R → Q → S"], a: 2, why: "Sperms and eggs must first be produced (R). A sperm then fuses with an egg during fertilisation (Q), the fertilised egg develops into a foetus in the womb (P) and the baby is born (S).", lvl: 2 },
    { q: "Mei made a model of the water cycle, as shown. Water droplets formed under the cold lid and dripped back into the warm water. Which part of the real water cycle does the cold lid represent?", fig: { type: "setups", items: [{ label: "Model", icon: "jar", lines: ["Ice cubes on the lid", "Droplets under the lid", "Warm water at bottom"] }] }, o: ["The heat given out by the Sun", "The cool air high above the ground", "The water in seas and reservoirs", "The rain falling back to Earth"], a: 1, why: "Water vapour from the warm water loses heat to the cold lid and condenses, just as water vapour loses heat to the cool air high above the ground to form clouds. The warm water stands for the seas and reservoirs.", lvl: 2 },
    { q: "On a cool, rainy morning, Mr Lim drove five passengers with all the windows closed and the air-conditioner off. Mist formed on the INSIDE of the windscreen. Which statement best explains this?", o: ["Water vapour outside the car lost heat to the glass and condensed.", "Water vapour inside the car lost heat to the cooler glass and condensed.", "Rainwater seeped through the glass and evaporated on the inside.", "Water vapour inside the car gained heat from the glass and condensed."], a: 1, why: "The passengers’ exhaled air adds warm water vapour inside the car. It touches the glass, which is cooled by the rain outside, loses heat and condenses on the inside. Condensation involves losing heat, not gaining it.", lvl: 3 },
    { q: "Warmer water holds less dissolved oxygen than cooler water. The graph shows how many times a goldfish moved its gills per minute in water at different temperatures. Which statement best explains the trend?", fig: { type: "line", xl: "Water temperature (°C)", yl: "Gill movements per minute", pts: [["20", 40], ["24", 52], ["28", 66], ["32", 80]] }, o: ["Warmer water has more dissolved oxygen, so the fish moves its gills faster to take it all in.", "In warmer water the gills take in water vapour instead of oxygen, so they must move faster.", "In warmer water the fish takes in oxygen from the air above, so its gills move faster.", "Warmer water has less dissolved oxygen, so the fish moves its gills faster to get enough oxygen."], a: 3, why: "As the water gets warmer, it holds less dissolved oxygen, so more water must pass over the gills each minute for the fish to take in enough oxygen. Gills take in oxygen dissolved in water, not water vapour or air.", lvl: 3 },
    { q: "Cell K has a cell wall, a nucleus and a large vacuole, but no chloroplasts. Which of these could cell K come from?\nI. A root hair cell\nII. A white petal\nIII. A green leaf cell that makes food\nIV. The inside of a potato", o: ["I and II only", "I and IV only", "I, II and IV only", "II, III and IV only"], a: 2, why: "The cell wall and large vacuole show it is a plant cell. Root hair cells, white petals and the inside of a potato get no light or are not green, so they lack chloroplasts. A green leaf cell that makes food must have chloroplasts.", lvl: 3 },
    { q: "Mdm Wong hung the same wet towel along her HDB corridor on four days and recorded how long it took to dry. Which two days should she compare to find out if humidity affects the drying time?", tbl: [["Day", "Temperature (°C)", "Humidity", "Wind", "Drying time (h)"], ["1", "31", "Low", "Windy", "2"], ["2", "31", "High", "Windy", "4"], ["3", "27", "High", "Still", "7"], ["4", "31", "High", "Still", "5"]], o: ["Day 1 and Day 2", "Day 2 and Day 3", "Day 1 and Day 4", "Day 3 and Day 4"], a: 0, why: "Days 1 and 2 differ only in humidity; temperature and wind are the same. Days 1 and 4 differ in both humidity and wind, days 3 and 4 differ only in temperature, and days 2 and 3 differ in temperature and wind.", lvl: 3 },
    { q: "Study the flower. After fertilisation, what usually happens to parts P, Q, R and S?", fig: { type: "flower", mark: { petal: "P", anther: "Q", ovary: "R", ovule: "S" } }, o: ["P and R wither; Q becomes the fruit; S becomes the seed", "P and Q wither; S becomes the fruit; R becomes the seed", "Q and S wither; R becomes the fruit; P becomes the seed", "P and Q wither; R becomes the fruit; S becomes the seed"], a: 3, why: "After fertilisation, the petals (P) and anthers (Q) wither. The ovary (R) develops into the fruit and each fertilised ovule (S) develops into a seed. Mixing up ovary and ovule is the commonest error.", lvl: 3 },
    { q: "When one bulb in a string of battery-powered fairy lights at home during Deepavali fused, ALL the bulbs on that string went out. Which statements about this string are correct?\nI. The bulbs are connected in series.\nII. Each bulb has its own path to the batteries.\nIII. Replacing the fused bulb with a working one will make all the bulbs light again.\nIV. Adding more bulbs to the string in series will make each bulb dimmer.", o: ["I and III only", "I, III and IV only", "II, III and IV only", "II and IV only"], a: 1, why: "All the bulbs went out, so they share one path: they are in series (I), not each on its own path (II is wrong). A working bulb closes the circuit again (III), and more bulbs in series make each bulb dimmer (IV).", lvl: 3 },
    { q: "Study the circuit. Switch S1 is closed and switch S2 is open. Which statements are correct?\nI. Bulbs A and B are lit.\nII. If S2 is closed, bulb C also lights up.\nIII. If bulb B fuses, bulb A goes out.\nIV. If bulb A fuses, bulb B stays lit.", fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S1", open: false }, { k: "bulb", label: "A" }], branches: [[{ k: "bulb", label: "B" }], [{ k: "bulb", label: "C" }, { k: "switch", label: "S2", open: true }]] }, o: ["I and II only", "I and III only", "I, II and III only", "II, III and IV only"], a: 2, why: "B’s branch is closed, so A and B are lit (I); closing S2 closes C’s branch (II). With S2 open, B’s branch is the only path back, so if B fuses the whole circuit is open and A goes out (III). A is on the main loop, so if A fuses every bulb goes out (IV is wrong).", lvl: 4 },
    { q: "Which of these contain genetic information from the father?\nI. A sperm\nII. An egg before fertilisation\nIII. A fertilised egg\nIV. A cell in the heart of the foetus", o: ["I, III and IV only", "I and III only", "II, III and IV only", "I, II, III and IV"], a: 0, why: "The sperm carries the father’s genetic information in its nucleus. At fertilisation it fuses with the egg, so the fertilised egg – and every cell of the foetus that develops from it – carries it too. An egg before fertilisation has only the mother’s.", lvl: 4 },
    { q: "Sea water is salty, but rain falling over the sea is not. Which of these statements about the water cycle over the sea are correct?\nI. When sea water evaporates, only the water changes into water vapour; the salt is left behind.\nII. The water vapour condenses into tiny droplets of water that contain no salt.\nIII. The tiny droplets in the clouds join into bigger drops that fall as rain.\nIV. The salt rises with the water vapour but falls out before the clouds form.", o: ["I, II and III only", "I and II only", "II and IV only", "I, III and IV only"], a: 0, why: "Only water evaporates, so salt stays in the sea (I, so IV is wrong) and the clouds and rain are fresh water (II). These salt-free droplets join and fall as rain (III), so the rain is fresh water too.", lvl: 4 }
  ],
  oe: [
    {
      q: "The main door of a condominium is held shut by a magnetic lock. Electromagnet X on the door frame holds a metal plate on the door while switch S is closed. Bulb L lights up to show that the door is locked. Study the circuit.\n(a) Explain why the plate on the door must be made of steel and not aluminium. [1]\n(b) The guard opens switch S. Explain why the door can now be pushed open. [1]\n(c) Suggest one change that would make the lock hold the door more strongly. [1]\n(d) With S closed, bulb L fuses. Will the door stay locked? Explain your answer. [1]",
      fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S", open: false }], branches: [[{ k: "gap", label: "X", text: "coil on iron core" }], [{ k: "bulb", label: "L" }]] },
      marks: 4,
      kw: [["magnetic", "attracted by"], ["open circuit", "circuit is open", "circuit becomes open", "loses its magnetism", "loses magnetism", "loses its magnet", "stops flowing", "no longer flows"], ["more coil", "more turns", "more batter", "another batter", "extra batter", "more cell", "another cell"], ["own branch", "separate branch", "own path", "separate path", "parallel", "still closed", "still a closed"]],
      model: "(a) Steel is a magnetic material, so it is attracted by the electromagnet, but aluminium is not. (b) The circuit becomes open, so electricity stops flowing through the coil and X loses its magnetism. It no longer holds the steel plate. (c) Wind more coils of wire around the iron core of X. (d) Yes. X is in parallel with L, on its own branch, so X’s branch is still a closed circuit and X stays magnetised.",
      x: 1
    },
    {
      q: "Plant M has flowers that are pollinated by insects. Mr Ravi did an experiment on three groups of 10 flower buds of plant M, as shown in the table.\n(a) Explain why no fruits formed in group B. [1]\n(b) What do the results of groups B and C show together? [1]\n(c) Name the part of the flower that developed into the fruit. [1]\n(d) One fruit from group C had 6 seeds. How many of its ovules were fertilised? [1]",
      tbl: [["Group", "What was done", "Fruits formed"], ["A", "Left uncovered", "8"], ["B", "Covered with a fine net bag", "0"], ["C", "Covered with a fine net bag; pollen from another flower brushed onto each stigma", "7"]],
      marks: 4,
      kw: [["stopped insects", "prevented insects", "kept insects", "insects from", "insects could", "pollen could", "not pollinated", "no pollination", "could not be pollinated", "not be pollinated"], ["only when pollen", "pollen is transferred", "pollination is needed", "pollination is necessary", "pollination is required", "needs pollination", "need pollination", "must be pollinated", "netting itself", "net bag itself", "not the net", "need pollen", "needs pollen"], ["ovary"], ["6", "six"]],
      model: "(a) The net bag stopped insects from reaching the flowers, so pollen could not be transferred to the stigma and the flowers were not pollinated. (b) Fruits form only when pollen is transferred to the stigma; the net bag itself did not stop fruits from forming. (c) The ovary. (d) 6 ovules, as each seed develops from one fertilised ovule."
    },
    {
      q: "Amir sat still for 2 minutes, cycled on an exercise bike from 2 to 6 minutes, and then rested. Study the graph of his breathing rate.\n(a) Describe how his breathing rate changed when he started cycling. [1]\n(b) Explain why his body needed a faster breathing rate while he was cycling. [2]\n(c) Name the system that carries oxygen from his lungs to his leg muscles. [1]",
      fig: { type: "line", xl: "Time (min)", yl: "Breaths per minute", pts: [["0", 16], ["2", 16], ["4", 30], ["6", 34], ["8", 22], ["10", 17]] },
      marks: 4,
      kw: [["increase", "faster", "higher", "went up", "rose", "more breaths"], ["more energy"], ["more oxygen", "oxygen faster", "enough oxygen"], ["circulatory"]],
      model: "(a) His breathing rate increased, from 16 to 34 breaths per minute. (b) His leg muscles were working harder and needed more energy. Breathing faster takes in more oxygen, which the cells use to release energy from food, and removes carbon dioxide faster. (c) The circulatory system."
    },
    {
      q: "Three similar potted plants were placed side by side in the sun. Petroleum jelly, which water vapour cannot pass through, was spread on some leaf surfaces, as shown. Each pot was sealed in a plastic bag so that only the leaves could lose water. After 3 days, plant A lost 30 g, plant B lost 26 g and plant C lost 8 g.\n(a) Explain why plant C lost the least mass. [1]\n(b) Why was plant A included in the experiment? [1]\n(c) Name the tubes that carry water from the roots to the leaves. [1]\n(d) Apart from letting water vapour out, state one other use of the tiny openings on leaves. [1]",
      fig: { type: "setups", items: [{ label: "A", icon: "pot", lines: ["No jelly"] }, { label: "B", icon: "pot", lines: ["Jelly on upper", "surfaces of leaves"] }, { label: "C", icon: "pot", lines: ["Jelly on lower", "surfaces of leaves"] }] },
      marks: 4,
      kw: [["most of the tiny openings", "most tiny openings", "most openings", "most of the openings", "more openings", "stomata", "openings are"], ["control", "compare"], ["water-carrying", "water carrying", "xylem"], ["oxygen", "gases", "gas", "carbon dioxide", "air"]],
      model: "(a) Most of the tiny openings are on the lower surfaces of leaves. The jelly covered them, so much less water vapour could escape from plant C’s leaves. (b) As a control, to compare with B and C and show that the jelly caused the smaller loss of water. (c) Water-carrying tubes. (d) To take in and give out gases such as oxygen."
    }
  ],
  tf: [
    { s: "In a flowering plant, fertilisation takes place on the stigma.", a: false, why: "Pollen lands on the stigma during pollination, but fertilisation takes place in the ovule, where the male reproductive cell fuses with the egg cell." },
    { s: "A fertilised egg develops into a foetus in the mother’s womb.", a: true, why: "After fertilisation, the fertilised egg grows into a foetus in the womb, where it is protected until birth." },
    { s: "Only the cells of the lungs use oxygen.", a: false, why: "The lungs take in oxygen, but the blood carries it to ALL body cells, which use it to release energy from food." },
    { s: "Root cells need oxygen, which they take in from the air spaces in the soil.", a: true, why: "All living cells need oxygen to release energy. This is why plants in waterlogged soil can die." },
    { s: "Fish get oxygen by splitting water into oxygen and hydrogen in their gills.", a: false, why: "Fish take in the oxygen that is already DISSOLVED in the water. The water itself is not broken down." },
    { s: "A seed contains a young plant and stored food.", a: true, why: "The stored food supports the young plant during germination until it can make its own food." },
    { s: "Every fruit is juicy and can be eaten.", a: false, why: "Many fruits are dry, such as the winged angsana fruit and the balsam pod. A fruit is the part that develops from the ovary." },
    { s: "When a switch is opened, electricity stops flowing through the path that the switch is on.", a: true, why: "An open switch breaks the path, making that part an open circuit." },
    { s: "Wind-pollinated flowers produce only a small amount of pollen.", a: false, why: "They produce LARGE amounts of light pollen, because most of it is blown away and never reaches a stigma." },
    { s: "In the water cycle, water gains heat when it evaporates and water vapour loses heat when it condenses.", a: true, why: "Evaporation needs heat from the Sun or surroundings; condensation happens when water vapour loses heat to cooler air or surfaces." }
  ]
};
