window.LB = window.LB || {};
// Fair Test HQ 5 — P5 process skills applied to P5 topics
LB["p5-skills"] = {
  notes: [
    { h: "The three kinds of variables", t: "Every fair test has ONE variable changed (what you change on purpose), ONE variable measured (the result you measure, count or observe) and variables kept the same (everything else that could affect the result). Name each one in full, e.g. ‘the exposed surface area of the water’, not ‘the dish’, and ‘the volume of water left after 3 hours’, not ‘the water’.", kw: ["variable changed", "variable measured", "variables kept the same", "name it in full"] },
    { h: "Writing the aim", t: "The aim links the variable changed to the variable measured: ‘To find out how the temperature of the surroundings affects the rate of evaporation of water.’ When a question asks ‘What is Siti trying to find out?’, write it in this ‘how X affects Y’ form.", kw: ["to find out how", "affects", "variable changed", "variable measured"] },
    { h: "What makes a test fair", t: "A test is fair only when the set-ups being compared differ in ONE variable, the one being tested. If two variables are different, we cannot tell which one caused the difference in the results. To choose set-ups to compare, find the pair that is identical except for the variable in the question.", kw: ["only one variable", "cannot tell which variable", "identical except"] },
    { h: "The control set-up", t: "A control set-up is identical to the experimental set-up except that the variable being tested is absent or not changed (for example, a shoot with no leaves, a flower that is not covered, a beaker with no plant). It is used for comparison, to show that the result is due to the variable being tested and not to other factors.", kw: ["for comparison", "identical except", "due to the variable being tested"] },
    { h: "Making results reliable", t: "Repeat the experiment at least three times and find the average, or use more samples in each set-up (e.g. 10 seedlings instead of 1). One odd result then affects the conclusion less, so the results are more reliable. Repeating does NOT make a test fairer; fairness comes from keeping the other variables the same.", kw: ["repeat", "average", "more reliable", "more samples"] },
    { h: "Measuring accurately", t: "Use the right instrument: a measuring cylinder for volume (read at eye level, at the bottom of the curved surface), a thermometer or data logger with a temperature sensor for temperature, a stopwatch for time and an electronic balance for mass. A light sensor measures brightness more accurately than our eyes.", kw: ["measuring cylinder", "eye level", "light sensor", "electronic balance"] },
    { h: "Reading line graphs", t: "Read the title, both axis labels and the units first. A line going down means the value is decreasing; a steeper line means a faster change; a flat line means no change. To compare two lines (or two columns in a table), read both at the SAME value on the x-axis.", kw: ["steeper", "faster change", "flat line", "same value"] },
    { h: "Describing trends and relationships", t: "Use both variables and the direction: ‘As the temperature increases, the time taken for the cloth to dry decreases.’ If the pattern changes part-way, describe each part: ‘...increases until 6 cm, after which it stays about the same.’ ‘The water decreases’ scores nothing because it names only one variable.", kw: ["as", "increases", "decreases", "stays the same"] },
    { h: "Conclusions within the data", t: "A conclusion must only describe what the results show, for the conditions and the range tested. If temperatures from 20 °C to 60 °C were tested, you cannot conclude what happens at 90 °C, and results from one type of plant cannot be claimed for ‘all plants’. Never write what you expected, only what was found.", kw: ["within the range tested", "only what the results show"] },
    { h: "Anomalies", t: "An anomaly is a result that does not follow the pattern of the other results. Possible causes are a measuring mistake or a variable that was not kept the same (e.g. a weaker battery, a windier spot). Identify it, suggest a reason, repeat that reading and leave it out of the average.", kw: ["anomaly", "does not follow the pattern", "repeat that reading"] },
    { h: "Claim, Evidence, Reasoning", t: "Claim: answer the question in one sentence. Evidence: quote the data (numbers, set-up letters, what was observed). Reasoning: use a science concept with its keywords to explain WHY the evidence supports the claim, e.g. ‘water vapour in the surrounding air came into contact with the cold surface, lost heat and condensed’.", kw: ["claim", "evidence", "reasoning", "science concept"] },
    { h: "PSLE answer technique", t: "Look at the marks: 1 mark usually needs one idea, 2 marks usually need a claim and a reason. Name set-ups by letter, compare with ‘more than / faster than’, and answer exactly what is asked (e.g. ‘explain’ needs a reason, ‘describe’ needs what happened). Use the standard keywords such as ‘exposed surface area’, ‘gains heat’, ‘water-carrying tubes’ and ‘closed circuit’.", kw: ["read the marks", "compare", "keywords", "answer what is asked"] }
  ],
  traps: [
    "‘Repeat the experiment to make it fair’ → repeating makes results more RELIABLE; keeping other variables the same makes it FAIR.",
    "Naming a variable as ‘the water’ or ‘the dish’ → name the quantity: ‘the volume of water left’, ‘the exposed surface area of the water’.",
    "‘The control set-up is the one where nothing is done’ → it is identical to the experimental set-up except that the variable tested is absent.",
    "‘The water decreased’ as a trend → name both variables: ‘As time increased, the volume of water left decreased.’",
    "Concluding beyond the data (untested temperatures, ‘all plants’) → only state what the results show for the range tested.",
    "Including an anomaly in the average → identify it, suggest a reason, repeat that reading and leave it out.",
    "Comparing two lines at different times → always read both lines at the same x-value before comparing.",
    "Giving evidence but no reasoning (‘A lost more water’) → add the science reason, e.g. ‘because the fan gave moving air, so water evaporated faster’."
  ],
  lessons: [
    {
      h: "How to name variables precisely",
      concept: "Markers give the mark only when a variable is named as a quantity that can be changed or measured. ‘The dish’ is an object; ‘the exposed surface area of the water’ is a variable. The variable measured should include what is measured and when, e.g. ‘the volume of water left in each container after 2 days’.",
      example: {
        q: "Mei Ling poured 100 ml of water into each of the three containers shown and left them side by side along her HDB corridor. After 2 days, she measured the volume of water left in each container.\n(a) State the variable changed. [1]\n(b) State the variable measured. [1]\n(c) State two variables that she kept the same. [1]",
        fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Mouth: 5 cm wide", "100 ml water"] }, { label: "B", icon: "jar", lines: ["Mouth: 10 cm wide", "100 ml water"] }, { label: "C", icon: "dish", lines: ["Mouth: 20 cm wide", "100 ml water"] } ] },
        marks: 3,
        think: [
          "Step 1: Compare the labels. Only the width of the mouth differs, and a wider mouth means a larger area of water in contact with the air.",
          "Step 2: Name it as a variable, not an object: ‘the exposed surface area of the water’ (not ‘the container’).",
          "Step 3: The result she measures is the water left. Say what AND when: ‘the volume of water left in each container after 2 days’.",
          "Step 4: Kept the same: things that could also change evaporation. The 100 ml of water, the place (same temperature and wind) and the 2 days are all the same."
        ],
        answer: "(a) The exposed surface area of the water. (b) The volume of water left in each container after 2 days. (c) The volume of water at the start (100 ml) and the place where the containers were left (same temperature and amount of wind)."
      },
      tip: "Test your answer: can you put ‘the amount of’, ‘the volume of’ or ‘the number of’ in front of it? If it is just an object (‘the dish’), it is not a variable yet.",
      try: {
        q: "Arif placed identical celery stalks in red-coloured water at 20 °C, 30 °C and 40 °C. After 30 minutes, he measured how far up each stalk the red colour had travelled. What is the variable measured?",
        o: ["The temperature of the red-coloured water in each beaker", "The height the red colour travelled up each stalk after 30 minutes", "The number of celery stalks placed in each beaker", "The volume of red-coloured water in each beaker at the start"],
        a: 1,
        why: "Arif measures how far the colour travelled after 30 minutes, so that is the variable measured. Temperature is the variable changed; the number of stalks and the starting volume of water are kept the same."
      }
    },
    {
      h: "How to explain the purpose of a control set-up",
      concept: "A control set-up is identical to the experimental set-up except that the variable being tested is removed. The full-mark answer names the control, says it is for comparison, and says WHAT it shows: that the result is due to the variable being tested. ‘To make it fair’ scores nothing.",
      example: {
        q: "Ben wanted to find out if leaves are needed for a plant to lose water. He set up A and B as shown and marked the water level. After one day, the water level in A had dropped by 12 ml and in B by 1 ml.\n(a) Explain why set-up B was needed. [1]\n(b) Explain why Ben added a layer of oil to both set-ups. [1]",
        fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Shoot with 8 leaves", "Water + oil layer", "Near a window"] }, { label: "B", icon: "jar", lines: ["Shoot, leaves removed", "Water + oil layer", "Near a window"] } ] },
        marks: 2,
        think: [
          "Step 1: Find the variable tested: whether the shoot has leaves. A has leaves, B does not; everything else is the same, so B is the control set-up.",
          "Step 2: Say what the comparison shows: A lost much more water than B, so the extra water loss is due to the leaves.",
          "Step 3: For the oil, think about where else water could go. Water can evaporate from the exposed water surface. The oil stops this.",
          "Step 4: Finish the link: so any drop in water level is due only to water taken in by the shoot."
        ],
        answer: "(a) B is the control set-up. It is used for comparison, to show that the greater drop in the water level in A is due to the leaves. (b) The oil prevents water from evaporating from the water surface, so any drop in water level is due to water taken in by the shoot."
      },
      tip: "Control answer formula: ‘It is used for comparison, to show that [the result] is due to [the variable tested].’",
      try: {
        q: "Zara placed a steel clip across gap X and the bulb lit up. She wants to show that the bulb lit up BECAUSE of the steel clip. Which is the most suitable control set-up?",
        fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "steel clip" } ] },
        o: ["The same circuit with two steel clips across X", "The same circuit with nothing across X", "A circuit with 3 batteries and a steel clip across X", "The same circuit with a steel clip across X and a second bulb"],
        a: 1,
        why: "The control is identical except that the variable tested (the steel clip) is absent, so it is the same circuit with nothing across X. The other options keep the clip or change a second variable (batteries, bulbs)."
      }
    },
    {
      h: "How to describe a trend and compare two sets of results",
      concept: "A trend statement names both variables and the direction: ‘As [variable changed] increases, [variable measured] decreases.’ When there are two lines or two columns, describe each and then compare them at the same x-values, using numbers as evidence: a faster change shows as a steeper line.",
      example: {
        q: "Jia Hui placed two identical dishes, each with 100 ml of water, in the same room. Dish P was placed in front of a fan; dish Q was not. The table shows the volume of water left.\n(a) Describe how the volume of water left changed with time. [1]\n(b) Compare the results for P and Q and explain the difference. [2]",
        tbl: [["Time (h)", "0", "1", "2", "3", "4"], ["Water left in P (ml)", "100", "80", "60", "40", "20"], ["Water left in Q (ml)", "100", "92", "84", "76", "68"]],
        marks: 3,
        think: [
          "Step 1: Both rows go down as time goes up, so ‘As time increased, the volume of water left in both dishes decreased.’",
          "Step 2: Work out the rates: P loses 20 ml every hour, Q loses 8 ml every hour. P’s line would be steeper.",
          "Step 3: Find the only difference between P and Q: the fan (moving air).",
          "Step 4: Give the reason with keywords: moving air removes water vapour above the dish, so water evaporates faster."
        ],
        answer: "(a) As time increased, the volume of water left in both dishes decreased. (b) The volume of water in P decreased faster (20 ml per hour) than in Q (8 ml per hour). The fan gave moving air over P, which increased the rate of evaporation of the water."
      },
      tip: "Numbers are evidence. ‘P lost 20 ml per hour but Q lost only 8 ml per hour’ is stronger than ‘P lost more’.",
      try: {
        q: "The graph shows how long it took identical wet cloths to dry at different temperatures. Which statement best describes the relationship?",
        fig: { type: "line", xl: "Temperature (°C)", yl: "Time taken to dry (min)", pts: [["20", 80], ["30", 64], ["40", 48], ["50", 32], ["60", 20]] },
        o: ["As time increases, the cloth dries.", "The cloth dries at 60 °C.", "As the temperature increases, the time taken for the cloth to dry decreases.", "As the temperature increases, the time taken for the cloth to dry increases."],
        a: 2,
        why: "The line goes down from left to right: higher temperature, shorter drying time. The first two options name only one variable or give a single fact, and the last one has the direction the wrong way round."
      }
    },
    {
      h: "How to deal with an anomalous result",
      concept: "An anomaly does not fit the pattern of the other results. A full answer (i) identifies it, (ii) suggests a sensible reason linked to the experiment (a measuring mistake, or a variable not kept the same), and (iii) says what to do: repeat that reading and leave it out of the average.",
      example: {
        q: "Nadia connected identical bulbs to 1, 2, 3 and 4 batteries arranged in series. She measured the brightness of the bulb each time with a light sensor. Her results are shown.\n(a) Which result does not follow the pattern? [1]\n(b) Suggest one possible reason for it. [1]\n(c) What should Nadia do about it? [1]",
        tbl: [["Number of batteries", "1", "2", "3", "4"], ["Light sensor reading (lux)", "100", "200", "130", "400"]],
        marks: 3,
        think: [
          "Step 1: Spot the pattern: 100, 200, ?, 400 goes up by about 100 lux for each battery, so 3 batteries should give about 300 lux.",
          "Step 2: 130 lux is far too low, so the 3-battery result is the anomaly.",
          "Step 3: Suggest a reason linked to this experiment: one of the batteries may have been used up (weaker), or the sensor was placed further from the bulb that time.",
          "Step 4: Say what to do: repeat the 3-battery reading and do not use 130 lux in the conclusion or the average."
        ],
        answer: "(a) The result for 3 batteries (130 lux). (b) One of the batteries used may have been weaker (partly used up), or the light sensor was placed further from the bulb. (c) She should repeat the reading for 3 batteries with good batteries, keeping the sensor at the same distance, and leave out the 130 lux result."
      },
      tip: "Your reason must be something that could really happen in THAT experiment. ‘The bulb was lazy’ or ‘science is wrong’ never scores.",
      try: {
        q: "Wen Jie tested how fast 50 ml of water evaporated at different temperatures. He did each temperature only once and got one odd result. Which change would make his results MORE RELIABLE?",
        o: ["Use a different volume of water at each temperature, and time each one", "Repeat the experiment three times at each temperature and find the average", "Test at one temperature only, so that there is less to measure", "Place the dishes in different rooms, so they do not affect each other"],
        a: 1,
        why: "Repeating and averaging means one odd reading affects the result less, so the results are more reliable. Changing the volume or the room would make the test unfair, and testing one temperature cannot show a pattern."
      }
    },
    {
      h: "How to write a Claim-Evidence-Reasoning answer",
      concept: "‘Explain’ questions worth 2 marks need more than an observation. State the claim, point to the evidence from the experiment, then give the scientific reason with the correct keywords. The reasoning is where most marks are lost.",
      example: {
        q: "Ali placed a celery stalk with leaves in blue-coloured water. After 4 hours, the leaves had blue streaks. When he cut across the stalk, he saw blue dots arranged in a ring near the edge. What does this experiment show? Explain your answer. [2]",
        fig: { type: "plant", mark: { stem: "Stalk", leaf: "Leaf" } },
        marks: 2,
        think: [
          "Step 1 (Claim): What does it show? Water is transported from the base of the stalk up to the leaves.",
          "Step 2 (Evidence): The blue dots in the cut stalk and the blue streaks in the leaves.",
          "Step 3 (Reasoning): The dots are the water-carrying tubes. The blue water moved up through these tubes to the leaves.",
          "Step 4: Check the keywords are there: ‘water-carrying tubes’, ‘transported up’, ‘to the leaves’."
        ],
        answer: "It shows that water is transported up the stalk to the leaves. The blue dots in the cut stalk are the water-carrying tubes, which carried the blue-coloured water up the stalk to the leaves, so the leaves had blue streaks."
      },
      tip: "Claim + Evidence alone is often only 1 mark. The Reasoning must contain the science keyword (water-carrying tubes, condenses, gains heat, closed circuit...).",
      try: {
        q: "Farah’s answer to ‘Why did water droplets form on the outside of the cold can?’ was: ‘Water droplets formed on the outside of the can within 5 minutes. Water vapour in the surrounding air came into contact with the cold surface of the can, lost heat and condensed.’ Which part of her answer is the REASONING?",
        o: ["‘Water droplets formed on the outside of the can within 5 minutes’", "‘within 5 minutes’", "‘Why did water droplets form on the outside of the cold can?’", "‘came into contact with the cold surface of the can, lost heat and condensed’"],
        a: 3,
        why: "The reasoning uses the science concept (water vapour loses heat to a cooler surface and condenses) to explain the observation. The first two options are only evidence (what was seen and when), and the third is the question itself."
      }
    }
  ],
  mcq: [
    { q: "Study the set-ups. Siti poured 50 ml of water into each container and left them in the same room for one day. What is the variable changed in her experiment?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Mouth: 4 cm wide", "50 ml water"] }, { label: "B", icon: "dish", lines: ["Mouth: 10 cm wide", "50 ml water"] }, { label: "C", icon: "dish", lines: ["Mouth: 20 cm wide", "50 ml water"] } ] }, o: ["The volume of water in each container at the start", "The exposed surface area of the water", "The volume of water left after one day", "The temperature of the room"], a: 1, why: "Only the width of the mouth differs, which changes the exposed surface area of the water. The 50 ml and the room are kept the same, and the water left is the variable measured.", lvl: 1 },
    { q: "Siti repeated her whole experiment three times and found the average volume of water left. Why did she do this?", o: ["To make the experiment a fair test", "To change the variable being tested", "To make her results more reliable", "To make the water evaporate faster"], a: 2, why: "Repeating and averaging makes the results more reliable. It does not make the test fairer; fairness comes from keeping the other variables the same.", lvl: 1 },
    { q: "What is the purpose of a control set-up in an experiment?", o: ["To show that the result is due to the variable being tested", "To make the results more reliable without repeating the test", "To test a second variable at the same time as the first one", "To make the experiment finish faster, with fewer set-ups"], a: 0, why: "The control set-up is identical except that the variable tested is absent, so comparing with it shows the result is due to that variable. Reliability comes from repeating, not from a control.", lvl: 1 },
    { q: "The graph shows the volume of water that evaporated from identical wet towels in 2 hours at different fan speeds. At which fan speed did the most water evaporate?", fig: { type: "bar", xl: "Fan speed", yl: "Water evaporated (ml)", bars: [["Off", 12], ["Low", 20], ["Medium", 28], ["High", 35]] }, o: ["Off", "Low", "Medium", "High"], a: 3, why: "The tallest bar (35 ml) is for the high fan speed. Faster moving air increases the rate of evaporation.", lvl: 1 },
    { q: "Wei Jie ran on the spot from minute 0 to minute 6 and then rested. The graph shows his pulse rate. What was his pulse rate at minute 4?", fig: { type: "line", xl: "Time (min)", yl: "Pulse rate (beats per min)", pts: [["0", 72], ["2", 98], ["4", 118], ["6", 126], ["8", 104], ["10", 84]] }, o: ["98 beats per minute", "126 beats per minute", "72 beats per minute", "118 beats per minute"], a: 3, why: "Read up from 4 on the x-axis to the line: 118 beats per minute. 126 is at minute 6 and 72 is his resting rate at minute 0.", lvl: 1 },
    { q: "Rahul placed identical celery stalks in coloured water at 20 °C, 30 °C and 40 °C, as shown. After 1 hour, he measured how high the colour had travelled up each stalk. What is the aim of his experiment?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Celery stalk", "Coloured water", "20 °C"] }, { label: "B", icon: "beaker", lines: ["Celery stalk", "Coloured water", "30 °C"] }, { label: "C", icon: "beaker", lines: ["Celery stalk", "Coloured water", "40 °C"] } ] }, o: ["To find out how the temperature of the water affects how fast the celery stalk grows", "To find out how the temperature of the water affects how high the water travels up the stalk", "To find out how the colour of the dye affects how high the water travels up the stalk", "To find out whether celery stalks with more leaves take in more coloured water"], a: 1, why: "The aim links the variable changed (temperature of the water) to the variable measured (how high the coloured water travelled). The colour is the same in all beakers.", lvl: 1 },
    { q: "Nadia measured the brightness of a bulb connected to different numbers of batteries in series. Study her results. Which result does NOT follow the pattern?", tbl: [["Number of batteries", "1", "2", "3", "4"], ["Light sensor reading (lux)", "100", "200", "130", "400"]], o: ["1 battery", "2 batteries", "3 batteries", "4 batteries"], a: 2, why: "The readings rise by about 100 lux per battery, so 3 batteries should give about 300 lux. 130 lux does not fit the pattern.", lvl: 1 },
    { q: "Nurul used a measuring cylinder to measure the volume of water left in her set-up. How should she read it to get an accurate reading?", o: ["At eye level, at the bottom of the curved water surface", "From above, looking down into the cylinder", "At the top edge of the curved water surface while tilting the cylinder", "By holding the cylinder up high and looking up at it"], a: 0, why: "Reading at eye level at the bottom of the curved surface avoids reading too high or too low. Looking from above or below gives a wrong reading.", lvl: 1 },

    { q: "Kumar wants to find out if wind affects the rate of evaporation of water. Which two set-ups should he compare?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["50 ml water", "Fan switched on", "Room at 30 °C"] }, { label: "B", icon: "dish", lines: ["50 ml water", "No fan", "Room at 30 °C"] }, { label: "C", icon: "dish", lines: ["80 ml water", "Fan switched on", "Room at 30 °C"] }, { label: "D", icon: "dish", lines: ["50 ml water", "No fan", "Room at 25 °C"] } ] }, o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "A and B differ only in the fan (wind). A and C differ in volume, B and D differ in temperature, and C and D differ in three variables.", lvl: 2 },
    { q: "Jia Hui placed a celery stalk with leaves in red-coloured water. After 3 hours, the leaves had red streaks and a cut across the stalk showed red dots. Which conclusion is best supported?", fig: { type: "plant", mark: { stem: "Stalk", leaf: "Leaves" } }, o: ["The celery stalk makes red dye in its leaves and stalk.", "Water is carried up the stalk through tubes to the leaves.", "Food is carried down the stalk through tubes to the roots.", "The celery absorbs water only at night, through its leaves."], a: 1, why: "The red dots are the water-carrying tubes and the red leaves show the water reached them. The experiment tells us nothing about food, and it was not done at night.", lvl: 2 },
    { q: "Mr Lim covered flower P on his pumpkin plant with a fine net bag to find out if insects are needed for the pollination of the flower. Which is the most suitable control set-up?", fig: { type: "setups", items: [ { label: "P", icon: "pot", lines: ["Pumpkin plant", "Flower in net bag", "Insects kept out"] }, { label: "Control", icon: "pot", lines: ["Pumpkin plant", "Flower: ?"] } ] }, o: ["A flower on a different kind of plant, covered with a net bag", "A flower on the same plant with its petals removed, covered with a net bag", "A flower on the same plant placed in a dark box", "A similar flower on the same plant, left uncovered"], a: 3, why: "The control is identical except insects CAN reach it, so it is a similar flower on the same plant left uncovered. The other options change a second variable.", lvl: 2 },
    { q: "Priya placed different objects, one at a time, across the gap X in the circuit shown to find out which materials are electrical conductors. What is the variable measured?", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "object tested" } ] }, o: ["The number of batteries", "The type of material across X", "Whether bulb A lights up", "The size of the circuit"], a: 2, why: "She observes whether bulb A lights up; that is what she records. The type of material is the variable changed and the number of batteries is kept the same.", lvl: 2 },
    { q: "The graph shows the time taken for identical wet cloths to dry at different temperatures. Which statement best describes the relationship?", fig: { type: "line", xl: "Temperature (°C)", yl: "Time taken to dry (min)", pts: [["20", 80], ["30", 64], ["40", 48], ["50", 32], ["60", 20]] }, o: ["As the temperature increases, the time taken for the cloth to dry decreases.", "As the temperature increases, the time taken for the cloth to dry increases.", "The temperature does not affect the time taken for the cloth to dry.", "The cloths dry only when the temperature is above 20 °C."], a: 0, why: "The line slopes down: higher temperature, shorter drying time. The cloth also dried at 20 °C, just more slowly, so the last option is wrong.", lvl: 2 },
    { q: "Aisha counted how many times a goldfish’s gill covers opened and closed in one minute at different water temperatures. Study the graph. Which statement is supported by her results?", fig: { type: "line", xl: "Water temperature (°C)", yl: "Gill cover movements per min", pts: [["20", 40], ["25", 60], ["30", 80]] }, o: ["The goldfish will have 100 gill cover movements per minute when the water is at 35 °C.", "As the water temperature increased from 20 °C to 30 °C, the gill covers moved more times per minute.", "The goldfish takes in more oxygen through its lungs as the water becomes warmer.", "Water temperature has no effect on how often the goldfish’s gill covers move."], a: 1, why: "The data only show 20 °C to 30 °C, and the count rises across that range. 35 °C was not tested, and fish take in oxygen through gills, not lungs.", lvl: 2 },
    { q: "Hui Min made paper models of winged fruits with different wing lengths. She dropped each model from a height and timed how long it took to reach the floor. Which variable must she keep the same?", fig: { type: "setups", items: [ { label: "P", icon: "box", lines: ["Wing length: 2 cm"] }, { label: "Q", icon: "box", lines: ["Wing length: 4 cm"] }, { label: "R", icon: "box", lines: ["Wing length: 6 cm"] } ] }, o: ["The wing length of each paper model", "The time taken for each model to reach the floor", "The height from which each model is dropped", "The colour of the floor below the models"], a: 2, why: "The height affects how long the model takes to fall, so it must be the same. Wing length is the variable changed and the time is the variable measured.", lvl: 2 },
    { q: "Ahmad wanted to find out if temperature affects the germination of green bean seeds. He used ONE seed in each set-up. Which change would make his results more reliable?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["1 green bean seed", "Moist cotton wool", "20 °C"] }, { label: "B", icon: "dish", lines: ["1 green bean seed", "Moist cotton wool", "30 °C"] } ] }, o: ["Use a different type of seed in each set-up", "Place the set-ups in different rooms", "Give each set-up a different amount of water", "Use 10 green bean seeds in each set-up"], a: 3, why: "With 10 seeds per set-up, one seed that fails for another reason will not change the conclusion, so the results are more reliable. The other options add a second variable and make the test unfair.", lvl: 2 },
    { q: "Kai looked at a cell under a microscope and drew the diagram shown. He concluded that it is a plant cell. Which labelled part is the best evidence for his conclusion?", fig: { type: "cell", kind: "plant", mark: { cell_wall: "P", nucleus: "Q", cytoplasm: "R", cell_membrane: "S" } }, o: ["P", "Q", "R", "S"], a: 0, why: "P is the cell wall, found in plant cells but not animal cells. The nucleus, cytoplasm and cell membrane are found in both.", lvl: 2 },
    { q: "Lina placed 200 ml of water in each of two identical beakers. One was covered with a lid and one was not. Study the results. Which statement is correct?", tbl: [["Day", "0", "1", "2", "3"], ["Covered beaker (ml)", "200", "200", "199", "199"], ["Uncovered beaker (ml)", "200", "185", "170", "155"]], o: ["Both beakers lost water at the same rate.", "The uncovered beaker lost about 15 ml of water each day.", "The covered beaker lost more water than the uncovered beaker.", "The volume of water in the covered beaker increased."], a: 1, why: "The uncovered beaker went 200 → 185 → 170 → 155, a loss of 15 ml a day. The covered beaker lost only 1 ml in 3 days because the lid trapped the water vapour.", lvl: 2 },
    { q: "Farah took a can of drink from the fridge and placed it on an electronic balance. She placed an identical can at room temperature on another balance. After 10 minutes, only the cold can had increased in mass. What is the variable changed in her experiment?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Can from the fridge", "5 °C at the start", "On a balance"] }, { label: "B", icon: "jar", lines: ["Can at room temp.", "30 °C at the start", "On a balance"] } ] }, o: ["The mass of each can after 10 minutes", "The temperature of the can at the start", "The type of drink in each can", "The time each can was left on the balance"], a: 1, why: "The only difference between A and B is the starting temperature of the can. The mass after 10 minutes is the variable measured; the drink and the time are the same.", lvl: 2 },
    { q: "Mala set up the circuit shown with 1 battery, then 2, then 3, using the same bulb each time, and measured the brightness with a light sensor. Which hypothesis is she testing?", fig: { type: "circuit", cells: 3, main: [ { k: "bulb", label: "A" } ] }, o: ["The more bulbs in a circuit, the dimmer each bulb.", "A switch is needed for a bulb to light up.", "The more batteries arranged in series, the brighter the bulb.", "Longer wires make a bulb brighter."], a: 2, why: "The number of batteries in series is the only thing she changes and brightness is what she measures. She does not change the number of bulbs, switches or wires.", lvl: 2 },
    { q: "Shanti wants to measure her resting pulse rate as reliably as possible. What should she do?", o: ["Count her pulse for 10 seconds, once, while resting, and use that number", "Count her pulse for 1 minute, three times while running, and find the average", "Ask a friend to guess her pulse rate three times and find the average", "Count her pulse for 1 minute, three times while resting, and find the average"], a: 3, why: "Several full-minute counts averaged together reduce the effect of a counting mistake. Counting while running measures her pulse during exercise, not at rest.", lvl: 2 },
    { q: "The graph shows the time taken for 20 ml of water to evaporate at different temperatures. Which conclusion can be drawn from the results?", fig: { type: "line", xl: "Temperature (°C)", yl: "Time for 20 ml to evaporate (min)", pts: [["30", 50], ["40", 40], ["50", 30], ["60", 20]] }, o: ["At 100 °C the water will take 0 minutes to evaporate, as it follows the same pattern.", "Water evaporates only at temperatures above 30 °C, as no lower temperature was tested.", "Water boils at 60 °C, as it took the shortest time to evaporate at 60 °C.", "Between 30 °C and 60 °C, the higher the temperature, the shorter the time taken to evaporate."], a: 3, why: "The conclusion stays within the range tested (30 °C to 60 °C). The data say nothing about 100 °C or below 30 °C, and nothing about boiling.", lvl: 2 },

    { q: "Study the set-ups. Which two set-ups should be compared to find out if the NUMBER OF LEAVES affects the amount of water lost by a shoot?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Shoot with 6 leaves", "Oil layer", "In the light"] }, { label: "B", icon: "jar", lines: ["Shoot with 6 leaves", "Oil layer", "In the dark"] }, { label: "C", icon: "jar", lines: ["Shoot with 3 leaves", "Oil layer", "In the light"] }, { label: "D", icon: "jar", lines: ["Shoot with 3 leaves", "No oil layer", "In the dark"] } ] }, o: ["A and B", "A and C", "B and D", "A and D"], a: 1, why: "A and C differ only in the number of leaves. B and D differ in the number of leaves AND the oil layer, and A and D differ in three variables.", lvl: 3 },
    { q: "Hari set up A and C as shown to find out if the number of leaves affects the amount of water lost by a shoot. Why did he add a layer of oil on top of the water?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Shoot with 6 leaves", "Oil layer", "In the light"] }, { label: "C", icon: "jar", lines: ["Shoot with 3 leaves", "Oil layer", "In the light"] } ] }, o: ["To stop water evaporating from the water surface, so any water lost is taken in by the shoot", "To provide food for the shoot, so it can take in more water through its stem", "To stop the shoot from taking in water through its stem, so only its leaves take in water", "To keep the water warm so that it evaporates faster and the shoot loses more water"], a: 0, why: "Without oil, some water would evaporate straight from the water surface, so we could not tell how much the shoot took in. The shoot still takes in water from below the oil.", lvl: 3 },
    { q: "P and Q ran on the spot from minute 0 to minute 4, then rested. The table shows their pulse rates. Which statement is supported by the data?", tbl: [["Time (min)", "0", "2", "4", "6", "8", "10"], ["P (beats per min)", "70", "110", "140", "100", "75", "70"], ["Q (beats per min)", "80", "120", "150", "135", "120", "105"]], o: ["Q’s pulse rate was lower than P’s throughout the 10 minutes.", "P and Q had the same resting pulse rate before they ran.", "P’s pulse rate returned to its resting rate faster than Q’s.", "P exercised harder than Q, because P’s pulse rate dropped faster."], a: 2, why: "P was back at 70 (resting) by minute 10, while Q was still at 105, far above 80. Q was always higher, their resting rates differ, and the data do not show how hard each exercised.", lvl: 3 },
    { q: "Ben measured the time taken for 100 ml of water to evaporate from dishes with different exposed surface areas. Study his results. What is the most likely reason for the result at 150 cm²?", tbl: [["Exposed surface area (cm²)", "50", "100", "150", "200"], ["Time taken (h)", "20", "10", "14", "5"]], o: ["A larger exposed surface area slows down evaporation, so it took the longest.", "The 150 cm² dish had the largest exposed surface area, so it took the longest.", "Evaporation stops when a dish is too large, so the water took longer to dry up.", "That dish may have been placed in a cooler, less windy spot than the others."], a: 3, why: "The pattern is: larger area, shorter time, so 150 cm² should take less than 10 h. 14 h is an anomaly, likely caused by a variable not kept the same, such as temperature or wind.", lvl: 3 },
    { q: "The diagram shows a flower. Mr Tan removed part P from flowers X and Y before they opened, then covered both with bags. He brushed pollen from another flower onto part Q of flower Y only. Why did he remove part P?", fig: { type: "flower", mark: { anther: "P", stigma: "Q", ovary: "R", petal: "S" } }, o: ["To attract more insects to the flowers, so that more pollen could reach their stigmas", "To stop the flowers’ own pollen reaching their stigmas, so only the added pollen could pollinate them", "To let the pollen reach the ovary faster, so that fertilisation could take place sooner", "To make the petals fall off sooner, so that the stigmas are easier to reach with pollen"], a: 1, why: "P is the anther, which produces pollen. Removing it stops self-pollination, so the only pollen that can reach Q (the stigma) is the pollen Mr Tan adds.", lvl: 3 },
    { q: "Jun is testing how temperature affects the rate of evaporation, using three dishes at each temperature. Which change would make his test FAIRER, rather than more reliable?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["30 °C", "Water: ?"] }, { label: "B", icon: "dish", lines: ["40 °C", "Water: ?"] }, { label: "C", icon: "dish", lines: ["50 °C", "Water: ?"] } ] }, o: ["Repeat the experiment three times", "Find the average of the readings", "Use the same volume of water in every dish", "Set up five dishes for each temperature instead of three"], a: 2, why: "Keeping the volume of water the same removes a second variable, which makes the test fair. Repeating, averaging and using more dishes all make results more reliable, not fairer.", lvl: 3 },
    { q: "Aisha recorded the breathing rate of a goldfish at 20 °C, 22 °C, 24 °C, 26 °C and 28 °C. Which is the most suitable way to present her results?", o: ["A line graph, because both the temperature and the breathing rate are measured numbers", "A bar graph, because temperature is a group like ‘type of fish’ and not a number", "A Venn diagram, because there are two variables that need to be compared", "A classification key, because there are five different temperatures to sort"], a: 0, why: "When the variable changed is a measured quantity (like temperature or time), a line graph shows the trend. Bar graphs suit categories such as types of materials.", lvl: 3 },
    { q: "Kiran placed each object, one at a time, across the gap X in the circuit shown: a copper wire, a steel spoon, aluminium foil and a plastic ruler. The bulb did not light up for ANY of them. Which is the most sensible explanation and next step?", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "B" }, { k: "gap", label: "X", text: "copper wire" } ] }, o: ["Metals are electrical insulators, so he should next test other metal objects to check this.", "The plastic ruler stopped the other objects from conducting, so he should test it last.", "Copper conducts electricity only when it is hot, so he should heat the copper wire first.", "A battery may be used up or the bulb fused, so he should first touch the two clips together to check."], a: 3, why: "Copper, steel and aluminium are conductors, so the bulb should have lit. Something else in the circuit is faulty; touching the clips together checks whether the circuit works without any object.", lvl: 3 },
    { q: "Rui Xin covered two beakers with identical plates with ice cubes on top. More water droplets formed under plate A than under plate B. Which statement best explains this?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Hot water, 70 °C", "Plate with ice on top"] }, { label: "B", icon: "beaker", lines: ["Water at 30 °C", "Plate with ice on top"] } ] }, o: ["Water evaporated faster from the hotter water, so more water vapour lost heat to the cold plate and condensed.", "The ice on plate A melted faster and dripped through the plate, forming droplets under it.", "The plate in A absorbed more water vapour from the air in the room and let it out underneath.", "Hot water does not evaporate, so the droplets came from the ice melting on top of plate A."], a: 0, why: "Hotter water evaporates faster, giving more water vapour to condense on the cold underside of the plate. The plate is not porous, so melted ice cannot drip through it.", lvl: 3 },
    { q: "Hui Min dropped paper models of winged fruits in front of a fan and measured how far each travelled. Which conclusion is supported by the graph?", fig: { type: "bar", xl: "Wing length", yl: "Distance travelled (m)", bars: [["2 cm", 1.5], ["4 cm", 2.8], ["6 cm", 4.1], ["8 cm", 4.2]] }, o: ["The longer the wings, the further the model travels, by the same amount for every 2 cm added.", "Heavier models travel further than lighter models, as the fan cannot push them off course.", "From 2 cm to 6 cm, longer wings meant a longer distance, but from 6 cm to 8 cm there was little change.", "A model with 10 cm wings will travel 5 m, as the distance keeps increasing with wing length."], a: 2, why: "The distance rose by about 1.3 m for each 2 cm up to 6 cm, then by only 0.1 m. Mass was not tested and 10 cm was outside the range tested.", lvl: 3 },
    { q: "Kumar removed a ring of the outer layer from the stem of a plant, as shown. After 3 weeks, the part of the stem just above the ring had swollen. Which conclusion is best supported?", fig: { type: "plant", mark: { stem: "Ring removed", leaf: "Leaves", roots: "Roots" } }, o: ["The water-carrying tubes in the outer layer carry water up from the roots, so water collected above the ring.", "Food-carrying tubes in the outer layer carry food down from the leaves, so food collected above the ring.", "The roots make food and send it up the food-carrying tubes, so food collected above the ring.", "The ring stopped water reaching the leaves, so the stem just above the ring swelled with water."], a: 1, why: "Food made in the leaves is carried down by food-carrying tubes near the outer part of the stem. With these removed, food cannot pass the ring and collects above it. The water-carrying tubes lie deeper, so the leaves still get water.", lvl: 3 },
    { q: "Lina hung one wet towel in her bathroom just after a hot shower, when the air was steamy, and an identical wet towel along the corridor. The corridor towel dried first. She concluded, ‘Temperature affects how fast a towel dries.’ Why is her conclusion NOT valid?", o: ["The towels should have been of different sizes, so that she could compare how fast each dried.", "Wet towels cannot dry in bathrooms, so the bathroom towel should not have been used at all.", "Temperature has no effect on evaporation, so the towels should have dried at the same rate.", "The amount of water vapour in the air and the wind were also different, so she cannot tell what caused it."], a: 3, why: "The steamy bathroom and the corridor differ in temperature, amount of water vapour in the air and wind. With several variables changed, she cannot say temperature caused the result.", lvl: 3 },

    { q: "Study the set-ups and results. Which conclusions can be FAIRLY drawn?\nI. Wind increases the rate of evaporation.\nII. A higher temperature increases the rate of evaporation.\nIII. A larger volume of water increases the rate of evaporation.", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["100 ml water", "Fan on, 30 °C", "Lost: 40 ml in 3 h"] }, { label: "B", icon: "dish", lines: ["100 ml water", "No fan, 30 °C", "Lost: 20 ml in 3 h"] }, { label: "C", icon: "dish", lines: ["100 ml water", "No fan, 40 °C", "Lost: 32 ml in 3 h"] }, { label: "D", icon: "dish", lines: ["50 ml water", "Fan on, 40 °C", "Lost: 38 ml in 3 h"] } ] }, o: ["I only", "I and II only", "II and III only", "I, II and III"], a: 1, why: "A vs B differ only in the fan (A lost more), so I is fair. B vs C differ only in temperature (C lost more), so II is fair. D differs from every other set-up in at least two variables, so no fair comparison exists for volume.", lvl: 4 },
    { q: "Aini placed a dish of water in front of a fan. At one point during the experiment, the fan was switched off. The graph shows the volume of water left. When was the fan most likely switched off?", fig: { type: "line", xl: "Time (h)", yl: "Volume of water left (ml)", pts: [["0", 100], ["1", 88], ["2", 76], ["3", 70], ["4", 64], ["5", 58]] }, o: ["At hour 2", "At hour 1", "At hour 4", "At hour 0"], a: 0, why: "From 0 to 2 h the water dropped 12 ml per hour; after 2 h it dropped only 6 ml per hour. The line became less steep at 2 h, showing slower evaporation once the moving air stopped.", lvl: 4 },
    { q: "Mei set up circuit X: 2 batteries with 2 bulbs in series. She then set up circuit Y, shown in the diagram, with 3 batteries and 2 bulbs in parallel. Each bulb in Y was brighter than each bulb in X, so she concluded that bulbs in parallel are brighter than bulbs in series. What is wrong with her experiment?", fig: { type: "circuit", cells: 3, main: [], branches: [ [ { k: "bulb", label: "P" } ], [ { k: "bulb", label: "Q" } ] ] }, o: ["Bulbs in parallel are never brighter than bulbs in series, so her result must be a mistake in reading.", "Circuit Y should have had its bulbs in series too, so that both circuits were exactly the same.", "She changed the number of batteries too, so she cannot tell if the arrangement or the extra battery caused it.", "She should have used only one bulb in each circuit, so that the bulbs could be compared more easily."], a: 2, why: "Two variables changed (bulb arrangement and number of batteries). Her conclusion happens to be true, but her experiment cannot show it; she must use the same number of batteries in both circuits.", lvl: 4 },
    { q: "Ravi set up A: a celery stalk in 100 ml of water with a layer of oil on top. He wants to show that the drop in water level is due to the celery taking in water. Which is the BEST control set-up?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Celery stalk", "100 ml water", "Oil layer on top"] }, { label: "Control", icon: "beaker", lines: ["?"] } ] }, o: ["A beaker with 100 ml of water and no celery, without an oil layer", "Celery in 50 ml of water with an oil layer", "Celery with its leaves removed in 100 ml of water, without an oil layer", "A beaker with 100 ml of water and an oil layer, but no celery"], a: 3, why: "The control must be identical to A except that the celery is absent. The first option also removes the oil, so two variables differ, and the others still contain celery.", lvl: 4 },
    { q: "Three pupils measured their pulse rates at rest, right after a 3-minute run, and 3 minutes after stopping. Whose pulse rate had come closest to returning to its resting rate 3 minutes after stopping?", tbl: [["Pupil", "At rest", "Right after run", "3 min after"], ["R", "70", "130", "90"], ["S", "80", "160", "110"], ["T", "60", "100", "65"]], o: ["R", "S", "T", "They were all equally close."], a: 2, why: "Compare each pupil’s reading 3 minutes after with their OWN resting rate: R is 20 above, S is 30 above, T is only 5 above. S had the biggest drop (50), but that is not the same as being closest to resting.", lvl: 4 },
    { q: "Limewater turns chalky when carbon dioxide passes through it; the more carbon dioxide, the faster it turns chalky. Study the set-ups and results. Which conclusion is correct?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Limewater", "Breathed-out air", "Chalky after 30 s"] }, { label: "B", icon: "jar", lines: ["Limewater", "Room air pumped in", "Chalky after 10 min"] } ] }, o: ["Breathed-out air contains more carbon dioxide than the air in the room.", "The air in the room contains no carbon dioxide, only oxygen and nitrogen.", "Breathed-out air contains only carbon dioxide and no other gases.", "Limewater turns chalky only when breathed-out air passes through it."], a: 0, why: "A turned chalky much faster, so breathed-out air has more carbon dioxide. B also turned chalky in the end, so room air does contain some carbon dioxide, and breathed-out air also contains other gases such as nitrogen and oxygen.", lvl: 4 }
  ],
  tf: [
    { s: "Repeating an experiment and finding the average makes the results more reliable.", a: true, why: "One odd reading affects an average of several readings less." },
    { s: "Repeating an experiment makes it a fairer test.", a: false, why: "Repeating improves reliability; a test is fair when only one variable is changed." },
    { s: "A control set-up is a set-up in which nothing is done.", a: false, why: "It is identical to the experimental set-up except that the variable being tested is absent or not changed." },
    { s: "In a fair test, only the variable being tested is changed and all other variables are kept the same.", a: true, why: "Otherwise we cannot tell which variable caused the difference." },
    { s: "If Ali measures the volume of water left in a dish, ‘the water’ is a precise enough name for his variable measured.", a: false, why: "He must say ‘the volume of water left in the dish (after a stated time)’." },
    { s: "On a line graph, a steeper line shows a faster change.", a: true, why: "The value changes by more for each step along the x-axis." },
    { s: "If water was found to evaporate faster as the temperature rose from 20 °C to 60 °C, the results show that it will evaporate even faster at 90 °C.", a: false, why: "90 °C was not tested, so the conclusion must stay within 20 °C to 60 °C." },
    { s: "An anomalous result is one that does not follow the pattern of the other results.", a: true, why: "It often comes from a measuring mistake or a variable not kept the same." },
    { s: "An anomalous result should be included when calculating the average.", a: false, why: "It should be repeated and left out, or it will make the average wrong." },
    { s: "In a Claim-Evidence-Reasoning answer, the reasoning uses a science concept to explain why the evidence supports the claim.", a: true, why: "E.g. ‘water vapour lost heat to the cold surface and condensed’." },
    { s: "Using one seed in each set-up gives more reliable results than using ten seeds in each set-up.", a: false, why: "More samples make results more reliable because one unusual seed matters less." },
    { s: "To test if insects are needed to pollinate a flower covered with a net bag, a suitable control is a similar flower on the same plant left uncovered.", a: true, why: "It differs only in whether insects can reach it." },
    { s: "When a fish breathes faster, its gill covers move fewer times per minute.", a: false, why: "Faster breathing means the gill covers open and close MORE times per minute." },
    { s: "A layer of oil on the water in a plant transport experiment prevents water from evaporating from the water surface.", a: true, why: "So any drop in water level is due to water taken in by the plant." },
    { s: "In ‘As the temperature increases, the time taken for the water to evaporate decreases’, the temperature is the variable measured.", a: false, why: "Temperature is the variable changed; the time taken is the variable measured." },
    { s: "A line graph is suitable when the variable changed is a measured quantity such as temperature or time.", a: true, why: "It shows the trend between the measured values; bar graphs suit categories." },
    { s: "If a bulb does not light up when an object is placed across a gap, this always proves the object is an electrical insulator.", a: false, why: "A used-up battery or fused bulb gives the same result, so the circuit should be checked first." },
    { s: "‘The celery leaves turned red’ is an observation, while ‘water travelled up the water-carrying tubes’ is an inference.", a: true, why: "An observation is what is seen; an inference explains it using science knowledge." },
    { s: "A conclusion should state what you expected to happen before the experiment.", a: false, why: "A conclusion states what the results actually show, even if it differs from your prediction." },
    { s: "If set-ups A and B differ in two variables, comparing them can still show which variable caused the difference.", a: false, why: "With two variables changed, we cannot tell which one caused the difference." }
  ],
  sort: [
    { title: "Kelly wants to find out how the exposed surface area of water affects the rate of evaporation. Sort each into the correct kind of variable.", groups: ["Variable changed", "Variable measured", "Kept the same"], items: [["The exposed surface area of the water", 0], ["The volume of water left after 3 hours", 1], ["The volume of water at the start", 2], ["The temperature of the room", 2], ["The amount of wind", 2], ["The time before measuring", 2], ["The type of liquid used", 2], ["The volume of water that evaporated in 3 hours", 1]] },
    { title: "Does each action make an experiment FAIRER or its results MORE RELIABLE?", groups: ["Makes it fairer", "Makes it more reliable"], items: [["Repeat the experiment three times", 1], ["Use the same volume of water in every set-up", 0], ["Find the average of the readings", 1], ["Use 20 seeds instead of 2 in each set-up", 1], ["Place all set-ups in the same room", 0], ["Use identical bulbs in every circuit", 0], ["Use the same type of plant in every set-up", 0], ["Repeat any reading that does not fit the pattern", 1]] },
    { title: "Sort each statement into an observation or an inference.", groups: ["Observation", "Inference"], items: [["The leaves of the celery turned red.", 0], ["Water travelled up the celery through water-carrying tubes.", 1], ["The bulb did not light up.", 0], ["The steel clip is an electrical conductor.", 1], ["Water droplets formed on the outside of the cold can.", 0], ["Water vapour in the air condensed on the cold can.", 1], ["The goldfish’s gill covers moved 80 times in one minute.", 0], ["The goldfish breathed faster in warmer water because it needed more oxygen.", 1]] }
  ],
  oe: [
    { q: "Study the set-ups. Dina placed dish A in the shade and dish B under the sun at the same time on the same day.\n(a) State the variable changed. [1]\n(b) State one variable she should keep the same. [1]\n(c) Predict which dish will have less water left after 3 hours and explain your prediction. [1]", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["100 ml water", "In the shade"] }, { label: "B", icon: "dish", lines: ["100 ml water", "Under the sun"] } ] }, marks: 3, kw: [["amount of sunlight", "sunlight", "whether the dish", "shade or", "temperature of the surroundings"], ["volume of water", "size of the dish", "exposed surface area", "wind", "type of dish"], ["gains more heat", "gain more heat", "more heat", "higher temperature", "warmer"]], model: "(a) The amount of sunlight each dish receives (whether the dish is in the shade or under the sun). (b) The volume of water at the start (100 ml), or the exposed surface area of the water. (c) Dish B. The water in B gains more heat from the sun, so it evaporates faster." },
    { q: "Amir ran on the spot and measured his pulse rate every 2 minutes. Study his results.\n(a) Describe the relationship between the time spent running and his pulse rate. [1]\n(b) Explain why his pulse rate increased while he was running. [2]", tbl: [["Time spent running (min)", "0", "2", "4", "6"], ["Pulse rate (beats per min)", "72", "100", "120", "128"]], marks: 3, kw: [["increase", "higher", "faster", "went up"], ["oxygen"], ["energy"]], model: "(a) As the time spent running increased, his pulse rate increased. (b) His heart beat faster to pump blood faster, so that more oxygen and digested food were transported to his muscles, which needed more energy for running." },
    { q: "Hakim measured the time taken for 50 ml of water to evaporate at different temperatures. Study the graph.\n(a) Describe the relationship between the temperature and the time taken. [1]\n(b) Which result does not follow the pattern? [1]\n(c) Suggest one possible reason for this result. [1]\n(d) What should Hakim do about this result? [1]", fig: { type: "line", xl: "Temperature (°C)", yl: "Time for 50 ml to evaporate (h)", pts: [["20", 60], ["30", 48], ["40", 44], ["50", 24], ["60", 12]] }, marks: 4, kw: [["decrease", "shorter", "less time"], ["40"], ["mistake", "error", "wrong", "not kept", "wind", "fan", "humid", "surface area", "smaller", "cooler", "shade"], ["repeat"]], model: "(a) As the temperature increased, the time taken for 50 ml of water to evaporate decreased. (b) The result at 40 °C (44 hours); it should be about 36 hours. (c) That dish may have been in a less windy spot or had a smaller exposed surface area, or there was a mistake in timing. (d) He should repeat the experiment at 40 °C and leave out the 44-hour result." },
    { q: "Ben set up A, B and C as shown and left them near a window. After one day, the water level had dropped by 12 ml in A, 1 ml in B and 0 ml in C.\n(a) Which two set-ups should be compared to show that leaves are needed for most of the water loss? [1]\n(b) Why was set-up C needed? [1]\n(c) Why was a layer of oil added to every set-up? [1]", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Shoot with 8 leaves", "Water + oil layer"] }, { label: "B", icon: "jar", lines: ["Shoot, leaves removed", "Water + oil layer"] }, { label: "C", icon: "jar", lines: ["No shoot", "Water + oil layer"] } ] }, marks: 3, kw: [["a and b", "b and a"], ["comparison", "compare", "due to the shoot", "taken in by the shoot", "control"], ["evaporat"]], model: "(a) A and B. (b) C is a control set-up used for comparison, to show that the drop in water level in A and B is due to water taken in by the shoot. (c) The oil prevents water from evaporating from the water surface." },
    { q: "Kiran used the circuit shown. He placed a steel spoon, aluminium foil, a rubber band and a wooden stick across the gap X, one at a time. The bulb lit up only for the steel spoon and the aluminium foil.\n(a) What was Kiran trying to find out? [1]\n(b) Before testing, how could Kiran check that the bulb and batteries were working? [1]\n(c) State one variable he must keep the same. [1]", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "B" }, { k: "gap", label: "X", text: "object tested" } ] }, marks: 3, kw: [["conduct", "conductor"], ["touch", "clips together", "connect the two clips", "known conductor"], ["number of batteries", "same batteries", "same bulb", "same circuit", "same wires"]], model: "(a) He was trying to find out which materials are electrical conductors (allow electricity to pass through them). (b) He could touch the two crocodile clips together (or place a known conductor across X) and see if the bulb lights up. (c) The number of batteries, or the same bulb and the same wires in the circuit." },
    { q: "Mr Tan removed part P from flowers X and Y, as shown, before the flowers opened. He then covered both flowers with plastic bags. He brushed pollen from another flower of the same kind onto part Q of flower Y only. After two weeks, only flower Y developed into a fruit.\n(a) Why did he remove part P? [1]\n(b) Why did he cover both flowers with bags? [1]\n(c) What can he conclude from the results? [1]\n(d) Explain what happened inside flower Y after the pollen landed on Q that led to a fruit forming. [1]", fig: { type: "flower", mark: { anther: "P", stigma: "Q", ovary: "R", ovule: "T" } }, marks: 4, x: 1, kw: [["self-pollinat", "own pollen", "its own pollen"], ["insect", "wind", "other pollen", "pollen from other"], ["pollination is needed", "needs pollination", "pollination is necessary", "must be pollinated", "needed for fruit", "needed for the flower"], ["fertilis", "fuse", "fusion"]], model: "(a) P is the anther, which produces pollen. Removing it prevents self-pollination, so the flowers’ own pollen cannot reach their stigmas. (b) To prevent insects or wind from bringing pollen from other flowers to the stigmas. (c) Pollination is needed for the flower to develop into a fruit. (d) The male reproductive cell from the pollen grain fused with the egg cell in the ovule (fertilisation), and the ovary then developed into a fruit." },
    { q: "Hui Min dropped paper models of winged fruits with different wing lengths from the same height and timed how long each took to reach the floor. Study the graph.\n(a) Describe the relationship between wing length and the time taken to reach the floor. [1]\n(b) Explain how longer wings help the plant. [1]\n(c) State one variable she must keep the same. [1]", fig: { type: "line", xl: "Wing length (cm)", yl: "Time to reach floor (s)", pts: [["2", 1.2], ["4", 1.8], ["6", 2.4], ["8", 3.0]] }, marks: 3, kw: [["increase", "longer"], ["competition", "compete", "further away from the parent", "away from the parent"], ["height", "mass", "type of paper", "fan", "wind"]], model: "(a) As the wing length increased, the time taken to reach the floor increased. (b) The fruit stays in the air longer, so the wind can carry it further away from the parent plant. The young plants then have less competition for space, water and sunlight. (c) The height from which the models are dropped, or the mass of the models (same type of paper)." },
    { q: "Nora observed three samples under a microscope. Study her observations.\n(a) Which sample(s) came from a plant? [1]\n(b) Sample R came from a plant but has no chloroplasts. Suggest which part of a plant it could have come from. [1]\n(c) Explain why that part of the plant does not need chloroplasts. [1]", tbl: [["Sample", "Cell wall", "Chloroplasts", "Nucleus"], ["P", "Present", "Present", "Present"], ["Q", "Absent", "Absent", "Present"], ["R", "Present", "Absent", "Present"]], marks: 3, kw: [["p and r", "r and p"], ["root", "bulb", "onion", "underground", "petal"], ["light", "does not make food", "do not make food", "no food"]], model: "(a) P and R, because they have cell walls. (b) The root (or an onion bulb) of a plant. (c) The root is underground and does not receive light, so its cells do not make food and do not need chloroplasts." },
    { q: "Farah placed a can from the fridge (5 °C) and an identical can at room temperature (30 °C) on separate electronic balances in the same room. Study the results.\n(a) Explain why the mass of the cold can increased. [1]\n(b) Suggest why the mass of the cold can stopped increasing after 15 minutes. [1]\n(c) What is the purpose of the can at room temperature? [1]\n(d) Predict how the mass of the cold can would change if the experiment were repeated in a room with more water vapour in the air. Explain. [1]", tbl: [["Time (min)", "0", "5", "10", "15", "20"], ["Cold can (g)", "350", "352", "354", "355", "355"], ["Room-temperature can (g)", "350", "350", "350", "350", "350"]], marks: 4, x: 1, kw: [["condens"], ["gained heat", "gains heat", "gain heat", "warmer", "no longer cold", "room temperature"], ["comparison", "compare", "control"], ["increase more", "increase by more", "more water vapour", "greater", "faster"]], model: "(a) Water vapour in the surrounding air came into contact with the cold surface of the can, lost heat and condensed into water droplets on the can, adding to its mass. (b) The can gained heat from the surroundings and became warmer, so water vapour no longer condensed on it. (c) It is a control set-up used for comparison, to show that the increase in mass is due to the low temperature of the cold can. (d) The mass would increase more, because there is more water vapour in the air to condense on the cold can." },
    { q: "Mala connected an identical bulb to 1, 2 and 3 batteries in series, as shown, and measured its brightness with a light sensor.\n(a) Why did she use a light sensor instead of her eyes? [1]\n(b) Describe the relationship shown by her results. [1]\n(c) State one variable she must keep the same. [1]", fig: { type: "circuit", cells: 3, main: [ { k: "bulb", label: "A" } ] }, tbl: [["Number of batteries", "1", "2", "3"], ["Light sensor reading (lux)", "90", "180", "270"]], marks: 3, kw: [["accurate", "more accurate", "exact", "precise"], ["brighter", "increase"], ["same bulb", "type of bulb", "distance", "same type of batter", "wires", "number of bulbs"]], model: "(a) The light sensor measures the brightness accurately as a number, while our eyes can only guess and cannot tell small differences. (b) As the number of batteries in series increased, the bulb became brighter (the light sensor reading increased). (c) The same bulb, or the distance between the light sensor and the bulb." },
    { q: "Study the set-ups. Wet towel A dried in 40 minutes, but wet towel B took 90 minutes. Explain why towel A dried faster. [2]", fig: { type: "setups", items: [ { label: "A", icon: "plate", lines: ["Wet towel", "Beside a fan", "Room at 30 °C"] }, { label: "B", icon: "plate", lines: ["Wet towel", "No fan", "Room at 30 °C"] } ] }, marks: 2, kw: [["wind", "moving air", "fan"], ["evaporat"]], model: "Towel A was beside a fan, so there was moving air over it. The moving air carried away the water vapour around the towel, so the water in towel A evaporated faster than in towel B." },
    { q: "Rui Xin wanted to find out if the amount of light affects the growth of bean seedlings. She used one seedling in each set-up and measured its height after a week. Suggest two ways to make her results more reliable. [2]", marks: 2, kw: [["repeat"], ["more seedlings", "more plants", "more seeds", "10 seedlings", "ten seedlings", "several seedlings"]], model: "She should repeat the experiment three times and find the average height, and use more seedlings (for example 10 seedlings) in each set-up." },
    { q: "Darren wants to find out if the duration of exercise affects a person’s pulse rate.\n(a) State the variable changed. [1]\n(b) State the variable measured. [1]\n(c) State one variable he must keep the same. [1]\n(d) Suggest how he can make his results reliable. [1]", marks: 4, kw: [["duration", "time spent", "how long"], ["pulse rate", "number of heartbeats", "beats per minute"], ["same person", "type of exercise", "same exercise", "speed", "same pupil"], ["repeat", "average", "more people", "more pupils"]], model: "(a) The duration of exercise (how long the person exercises). (b) The pulse rate (number of beats per minute) right after the exercise. (c) The same person and the same type of exercise at the same speed. (d) Repeat each duration three times, resting between tries, and find the average pulse rate." },
    { q: "Mei set up circuit X with 2 batteries and 2 identical bulbs in series. She then set up circuit Y, shown, with 2 batteries and 2 identical bulbs P and Q in parallel. Each bulb in Y was brighter than each bulb in X.\n(a) State the variable changed in her experiment. [1]\n(b) State one variable she kept the same. [1]\n(c) Predict what will happen to bulb Q if bulb P is removed from circuit Y. [1]\n(d) Explain your prediction in (c). [1]", fig: { type: "circuit", cells: 2, main: [], branches: [ [ { k: "bulb", label: "P" } ], [ { k: "bulb", label: "Q" } ] ] }, marks: 4, x: 1, kw: [["arrangement", "series or parallel", "how the bulbs"], ["number of batteries", "number of bulbs", "type of bulb", "same bulbs"], ["remain lit", "stay lit", "still light", "still lit", "lights up"], ["closed circuit", "complete circuit", "own path", "separate path"]], model: "(a) The arrangement of the bulbs (in series or in parallel). (b) The number of batteries (2), or the number of bulbs and the type of bulb. (c) Bulb Q will remain lit (and stay as bright). (d) Q is on its own separate path to the batteries, so there is still a closed circuit through Q even when P is removed." }
  ],
  doc: [
    { q: "Ali placed a celery stalk in red-coloured water. After 3 hours, its leaves had red streaks. Explain why. [2]", marks: 2, answers: ["Because the celery drank the red water.", "The red-coloured water was carried up the stalk by the water-carrying tubes to the leaves.", "The leaves turned red because they like red colour."], best: 1, why: "Pupil 2 names the transport (carried up the stalk) AND the structure (water-carrying tubes) to the leaves. Pupil 1 uses ‘drank’ and gives no tubes or movement to the leaves; Pupil 3 gives no science at all." },
    { q: "Mei Ling put 100 ml of water in containers with mouths of different widths and measured the water left after 2 days. State the variable changed. [1]", marks: 1, answers: ["The exposed surface area of the water.", "The container.", "The water that evaporated."], best: 0, why: "Pupil 1 names a variable that can be changed. ‘The container’ is an object, not a variable, and ‘the water that evaporated’ is (loosely) the variable measured, not the one changed." },
    { q: "Nadia connected a bulb to 1, 2 and 3 batteries in series. The light sensor readings were 90, 180 and 270 lux. Describe the relationship between the number of batteries and the brightness of the bulb. [1]", marks: 1, answers: ["The bulb is brighter.", "More batteries, brightness.", "As the number of batteries in series increased, the brightness of the bulb increased."], best: 2, why: "Pupil 3 names both variables and the direction of change. Pupil 1 names only one variable; Pupil 2 names both but does not say whether the brightness increases or decreases." },
    { q: "Ben compared shoot A (with leaves) and shoot B (leaves removed) in water with an oil layer. Explain why set-up B was needed. [1]", marks: 1, answers: ["To make the experiment fair.", "B is the control set-up. It is used for comparison, to show that the greater water loss in A is due to the leaves.", "To repeat the experiment so that it is reliable."], best: 1, why: "Pupil 2 says what B is for AND what it shows. ‘To make it fair’ is too vague, and Pupil 3 mixes up a control with repeating the experiment." },
    { q: "Farah took a can of cold drink out of the fridge. After a few minutes, water droplets formed on the outside of the can. Explain why. [2]", marks: 2, answers: ["The water leaked out of the can.", "The can was cold so water came out of it.", "Water vapour in the surrounding air came into contact with the cold surface of the can, lost heat and condensed into water droplets."], best: 2, why: "Pupil 3 names where the water came from (water vapour in the air), the heat change (lost heat to the cold surface) and the process (condensed). Pupils 1 and 2 wrongly think the water came from inside the sealed can." }
  ]
};
