window.LBZ = window.LBZ || {};
LBZ["p5-water"] = {
  flash: [
    { f: "Define: melting", b: "Melting is the change of state from solid to liquid. Ice gains heat and melts into water at 0 °C, its melting point." },
    { f: "Define: freezing", b: "Freezing is the change of state from liquid to solid. Water loses heat and freezes into ice at 0 °C, its freezing point." },
    { f: "Define: evaporation", b: "Evaporation is the change of state from liquid to gas. It takes place at any temperature and only at the exposed surface of the water. Water gains heat." },
    { f: "Define: boiling", b: "Boiling is the change of state from liquid to gas at a fixed temperature, the boiling point (100 °C for pure water). It takes place throughout the water, with bubbles." },
    { f: "Define: condensation", b: "Condensation is the change of state from gas to liquid. Water vapour loses heat to a cooler surface and condenses into water droplets." },
    { f: "Shape and volume of ice, water and water vapour", b: "Ice: definite shape and definite volume. Water: definite volume but no definite shape. Water vapour: no definite shape and no definite volume." },
    { f: "Why does boiling water stay at 100 °C although it is still being heated?", b: "The heat gained is used to change the water into water vapour, so its temperature stays at 100 °C while it boils." },
    { f: "Why does melting ice stay at 0 °C although it is still gaining heat?", b: "The heat gained is used to change the ice into water, so its temperature stays at 0 °C until all the ice has melted." },
    { f: "Four factors that increase the rate of evaporation", b: "A higher temperature of the surroundings, a larger exposed surface area, more wind (moving air), and less humid air (less water vapour in the air)." },
    { f: "Two differences between evaporation and boiling", b: "Evaporation takes place at any temperature and only at the exposed surface. Boiling takes place only at the boiling point and throughout the liquid." },
    { f: "What is the white ‘steam’ seen above a boiling kettle?", b: "Tiny water droplets. Hot water vapour loses heat to the cooler surrounding air and condenses. Water vapour itself is invisible." },
    { f: "How do water droplets form on the outside of a glass of iced water?", b: "Water vapour in the surrounding air comes into contact with the cooler outer surface of the glass, loses heat to it and condenses into water droplets." },
    { f: "Why do we feel cooler when our sweat evaporates?", b: "As the sweat evaporates, it gains heat from our body. Our body loses heat, so we feel cooler." },
    { f: "Why does sitting under a fan make us feel cooler?", b: "The moving air increases the rate of evaporation of sweat. The sweat gains heat from our body faster, so the body loses heat faster." },
    { f: "Why do spectacles mist up when you step out of an air-conditioned room?", b: "The lenses are cooler than the surrounding air. Warm water vapour in the air loses heat to the cooler lenses and condenses into tiny water droplets." }
  ],
  mcq: [
    { q: "Which change of state is the opposite of evaporation?", o: ["Melting", "Freezing", "Condensation", "Boiling"], a: 2, why: "Evaporation changes liquid water into water vapour; condensation changes water vapour back into liquid water. Freezing is the opposite of melting.", lvl: 1 },
    { q: "Water in an ice-cube tray is placed in a freezer and turns into ice. What happens to the water?", o: ["It gains heat and melts.", "It loses heat and freezes.", "It loses heat and condenses.", "It gains heat and freezes."], a: 1, why: "The water loses heat to the colder surroundings in the freezer and freezes into ice. Condensation is gas to liquid, and freezing never involves gaining heat.", lvl: 1 },
    { q: "Which of these is an example of evaporation?", o: ["Wet hair drying under a fan", "Ice cream melting in the sun", "A bathroom mirror misting up", "Water turning into ice in a freezer"], a: 0, why: "The water in wet hair changes into water vapour – evaporation. Ice cream melting is melting, a misty mirror is condensation and water turning into ice is freezing.", lvl: 1 },
    { q: "Water in a kettle was heated steadily. The graph shows its temperature. At what time did the water start to boil?", o: ["2 min", "4 min", "6 min", "8 min"], a: 3, why: "The water reached 100 °C, its boiling point, at 8 min. After that, the temperature stayed at 100 °C while the water boiled.", lvl: 1, fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 20], ["2", 40], ["4", 60], ["6", 80], ["8", 100], ["10", 100], ["12", 100]] } },
    { q: "Which of these is NOT an example of condensation?", o: ["Droplets on the outside of a cup of iced kopi", "Mist on the bathroom mirror after a hot shower", "Wet laundry drying on a bamboo pole at an HDB flat", "Droplets on the inside of a rice cooker lid"], a: 2, why: "Laundry drying is evaporation: liquid water changes into water vapour. In the other three, water vapour loses heat to a cooler surface and condenses into droplets.", lvl: 2 },
    { q: "Ravi wants to find out if the exposed surface area of water affects its rate of evaporation. Study the set-ups. Which two set-ups should he compare?", o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ only in the container (wide or narrow), so only the exposed surface area changes. B and D test the place, while A and C, and C and D, each change more than one thing.", lvl: 2, fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Wide dish", "100 ml of water", "On a sunny ledge"] }, { label: "B", icon: "beaker", lines: ["Narrow beaker", "100 ml of water", "On a sunny ledge"] }, { label: "C", icon: "dish", lines: ["Wide dish", "50 ml of water", "In the shade"] }, { label: "D", icon: "beaker", lines: ["Narrow beaker", "100 ml of water", "In the shade"] }] } },
    { q: "After the cleaners mop the floor of an MRT station, they switch on large standing fans to help the floor dry faster. How do the fans help?", o: ["They blow cold air, which makes the water freeze.", "They make the water vapour condense on the floor.", "They heat the floor so that the water boils away.", "The moving air increases the rate of evaporation."], a: 3, why: "Moving air carries water vapour away from the wet floor, so the water evaporates faster. Fans do not make cold air, and the water does not need to boil to dry.", lvl: 2 },
    { q: "The Venn diagram groups some changes of state of water. Which process should replace ‘?’?", o: ["Freezing", "Boiling", "Condensation", "Evaporation"], a: 1, why: "Boiling takes place at a fixed temperature (100 °C) and water gains heat. Evaporation takes place at any temperature, condensation involves losing heat, and freezing (0 °C) involves losing heat.", lvl: 2, fig: { type: "venn", a: "At a fixed temperature", b: "Water gains heat", onlyA: ["freezing"], both: ["melting", "?"], onlyB: ["evaporation"], neither: ["condensation"] } },
    { q: "Mdm Wong dries laundry on bamboo poles outside her HDB flat. The table shows the weather on four days. On which day would her laundry most likely dry the fastest?", o: ["Monday", "Tuesday", "Wednesday", "Thursday"], a: 3, why: "Thursday has the highest temperature, wind and the least humid air – all three increase the rate of evaporation. Wednesday is as hot and dry but has no wind.", lvl: 2, tbl: [["Day", "Temperature (°C)", "Wind", "Humidity of air"], ["Monday", "27", "Still", "High"], ["Tuesday", "30", "Windy", "High"], ["Wednesday", "33", "Still", "Low"], ["Thursday", "33", "Windy", "Low"]] },
    { q: "An ice cube at −10 °C was taken out of a freezer and left on a plate in a room at 30 °C. Which describes the changes in its temperature?", o: ["It rises to 0 °C, stays at 0 °C while melting, then rises to 30 °C.", "It stays at −10 °C while melting, then rises to 30 °C.", "It rises to 0 °C, then keeps rising steadily to 30 °C.", "It rises to 0 °C, stays at 0 °C, then rises above 30 °C."], a: 0, why: "The ice gains heat and warms to 0 °C, stays at 0 °C while it melts, then the water warms until it reaches room temperature (30 °C). It cannot become hotter than its surroundings.", lvl: 2 },
    { q: "Which of these have a definite volume?\nA: Ice\nB: Water\nC: Water vapour", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Ice and liquid water both have a definite volume. Water vapour, a gas, spreads out to fill its container, so it has no definite volume.", lvl: 2 },
    { q: "At an outdoor food court, misting fans spray a fine mist of water droplets into the air. Diners sitting nearby feel cooler. Why?", o: ["The droplets condense and give out coldness to the air.", "The droplets freeze into ice and lower the temperature.", "The droplets melt and gain heat from the diners’ skin.", "The droplets evaporate and gain heat from the surrounding air."], a: 3, why: "The tiny droplets evaporate quickly. As they evaporate, they gain heat from the surrounding air and the diners’ skin, so the air and skin lose heat and feels cooler. There is no ‘coldness’ given out.", lvl: 3 },
    { q: "At a hawker centre, a 200 g block of ice and 200 g of shaved ice for ice kachang, both at 0 °C, were left on identical plates. The shaved ice melted faster. Why?", o: ["It is colder inside, so it melts at a lower temperature.", "It is made of a different kind of water from the block.", "It has a larger surface in contact with the warm air.", "It contains air, which gives out coldness more slowly."], a: 2, why: "The many small pieces of shaved ice have a larger surface in contact with the warmer air, so they gain heat faster. Both are the same mass and at 0 °C, and ice always melts at 0 °C.", lvl: 3 },
    { q: "Two identical wet sponges were left in the same room for a day, as shown. Which correctly predicts the result?", o: ["Sponge P stays wetter, as water vapour cannot escape from the jar.", "Both sponges dry at the same rate, as the room is the same.", "Sponge P dries faster, as the lid traps heat inside the jar.", "Sponge Q stays wetter, as more air surrounds the sponge."], a: 0, why: "In the sealed jar, the water vapour cannot escape. The air in the jar soon holds so much water vapour that little more water evaporates. In the open dish, the water vapour escapes into the room.", lvl: 3, fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["Wet sponge", "Jar sealed with a lid"] }, { label: "Q", icon: "dish", lines: ["Wet sponge", "Open dish"] }] } },
    { q: "After a morning shower, Siti measured the depth of a puddle on the concrete floor of the school car park. The graph shows her results. During which hour did the puddle lose the most water, and what is the most likely reason?", o: ["8 a.m. to 9 a.m., as the puddle was deepest", "10 a.m. to 11 a.m., as the air was most humid", "11 a.m. to 12 noon, as the surroundings were warmest", "9 a.m. to 10 a.m., as the puddle was still wide"], a: 2, why: "The depth fell by 4 mm from 11 a.m. to 12 noon, the biggest drop. The surroundings get warmer towards noon, so water evaporates faster. Humid air would slow evaporation down.", lvl: 3, fig: { type: "line", xl: "Time", yl: "Depth of water (mm)", pts: [["8am", 12], ["9am", 11], ["10am", 9], ["11am", 6], ["12nn", 2]] } },
    { q: "Mr Rahman collected the water dripping from his bedroom air-conditioner pipe for 1 hour on four days. The settings were the same each day. On which day did the air in the room most likely contain the most water vapour?", o: ["Monday", "Tuesday", "Wednesday", "Thursday"], a: 3, why: "The water comes from water vapour in the air that loses heat to the cold parts of the air-conditioner and condenses. The most water was collected on Thursday, so the air most likely had the most water vapour.", lvl: 3, fig: { type: "bar", xl: "Day", yl: "Volume of water collected (ml)", bars: [["Monday", 180], ["Tuesday", 120], ["Wednesday", 210], ["Thursday", 260]] } },
    { q: "Which of these show the correct direction of heat flow?\nA: Ice melting in a drink – heat flows from the drink to the ice.\nB: Droplets forming on a cold can – heat flows from the can to the water vapour.\nC: Sweat evaporating – heat flows from the skin to the sweat.\nD: Water freezing in a freezer – heat flows from the water to the colder surroundings.", o: ["A and C only", "B and D only", "A, C and D only", "A, B, C and D"], a: 2, why: "Heat flows from the hotter to the colder object. In B, the warmer water vapour loses heat to the cooler can, so heat flows from the water vapour to the can, not the other way.", lvl: 3 },
    { q: "Equal masses of ice at 0 °C and water at 0 °C were added to two identical cups of hot tea at 80 °C. A few minutes later, all the ice had melted. Which is correct at that moment?", o: ["Both cups are at the same temperature, as both were at 0 °C.", "The cup with ice is cooler, as the ice had to gain heat to melt.", "The cup with water is cooler, as water conducts heat better.", "The cup with ice is warmer, as the ice blocked heat from the tea."], a: 1, why: "The ice must first gain heat from the tea to melt, while it stays at 0 °C; only then does the melted water warm up. So the ice takes more heat from the tea, and that cup is cooler.", lvl: 4 },
    { q: "Each set-up held 50 ml of water. Study the table. Which conclusions can be drawn FAIRLY from these results?\nX: Moving air increases the rate of evaporation.\nY: A higher temperature increases the rate of evaporation.\nZ: A larger exposed surface area increases the rate of evaporation.", o: ["X only", "X and Z only", "Y and Z only", "X, Y and Z"], a: 1, why: "A and B differ only in the fan (X). B and D differ only in the container (Z). C is the only set-up at 25 °C, and it differs from every other set-up in more than one way, so Y cannot be concluded fairly.", lvl: 4, tbl: [["Set-up", "Temperature (°C)", "Fan", "Container", "Time to dry (h)"], ["A", "30", "Off", "Wide dish", "6"], ["B", "30", "On", "Wide dish", "4"], ["C", "25", "Off", "Narrow dish", "10"], ["D", "30", "On", "Narrow dish", "7"]] },
    { q: "Dishes X and Y were left side by side on a window ledge. The table shows the volume of water in each. The water in each dish evaporated at a steady rate. Which is correct?", o: ["Dish X dries first; it most likely has a larger exposed surface.", "Dish Y dries first; it has less water left to lose than X.", "Dish Y dries first; it most likely has a larger exposed surface.", "Both dry at the same time, as they are in the same place."], a: 0, why: "X loses 30 ml a day, so its 150 ml lasts 5 days; Y loses 10 ml a day, so its 60 ml lasts 6 days. In the same place, X loses water faster, most likely because it has a larger exposed surface area.", lvl: 4, tbl: [["Day", "Dish X (ml)", "Dish Y (ml)"], ["0", "150", "60"], ["1", "120", "50"], ["2", "90", "40"]] }
  ],
  oe: [
    { q: "Lina soaked three identical towels with the same amount of water and dried them in the same room for 10 minutes, as shown. (a) Which two towels should she compare to find out if the temperature of the air affects the rate of evaporation? (b) Towel A had the most water left and towel C had the least. Using the results, state two factors that increase the rate of evaporation. (c) When Lina dries her own wet hair with the cool setting, her head feels cold. Explain why.", marks: 4, kw: [["b and c", "c and b", "b and towel c", "c and towel b"], ["moving air", "wind", "air movement", "blowing air", "air is moving", "fan"], ["temperature", "hot air", "hotter", "warmer", "warm air"], ["gains heat", "gain heat", "gained heat", "takes heat", "removes heat", "absorbs heat", "draws heat", "heat from her", "loses heat", "lose heat"]], model: "(a) B and C. (b) Moving air (wind) and a higher temperature of the surrounding air. (c) The moving air makes the water in her hair evaporate faster. As the water evaporates, it gains heat from her head, so her head loses heat and feels cold.", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Wet towel", "On a rack", "No hair dryer"] }, { label: "B", icon: "plate", lines: ["Wet towel", "Hair dryer: cool air"] }, { label: "C", icon: "plate", lines: ["Wet towel", "Hair dryer: hot air"] }] } },
    { q: "Kumar dipped a thermometer into a beaker of water at room temperature (30 °C). He took it out and held it in the still air of the classroom. The graph shows the reading. (a) Name the change of state that took place on the bulb. (b) Explain why the reading fell from 0 min to 2 min. (c) Kumar repeats the experiment with a fan blowing air over the bulb. Predict how the lowest reading would compare with 26 °C. (d) Explain your prediction.", marks: 4, kw: [["evaporat"], ["gains heat", "gain heat", "gained heat", "takes heat", "took heat", "removes heat", "absorbs heat", "heat from the bulb", "loses heat", "lost heat"], ["lower", "below 26", "less than 26", "colder", "fall further", "drop further", "smaller"], ["faster", "more quickly", "quicker", "higher rate", "increase"]], model: "(a) Evaporation. (b) The water on the bulb evaporated and gained heat from the bulb, so the bulb lost heat and the reading fell. (c) The lowest reading would be lower than 26 °C. (d) The moving air increases the rate of evaporation, so the water gains heat from the bulb faster and the bulb loses more heat.", fig: { type: "line", xl: "Time (min)", yl: "Thermometer reading (°C)", pts: [["0", 30], ["1", 27], ["2", 26], ["3", 26], ["4", 27], ["5", 29], ["6", 30], ["7", 30]] }, x: 1 },
    { q: "Floating solar panels cover a large part of the water surface of Tengeh Reservoir. Besides producing electricity, they help to reduce the loss of water from the reservoir. (a) Name the process by which water from the reservoir surface changes into water vapour. (b) Explain how covering the water surface reduces this water loss. (c) The panels also shade the water from the Sun. Explain how this reduces water loss.", marks: 3, kw: [["evaporat"], ["surface area", "exposed surface", "less surface", "smaller surface", "less water is exposed", "less of the water is exposed"], ["less heat", "cooler", "lower temperature", "temperature is lower", "not as hot", "colder", "not gain as much heat"]], model: "(a) Evaporation. (b) The panels reduce the exposed surface area of the water, so less water evaporates. (c) The shaded water gains less heat from the Sun and stays cooler, so it evaporates more slowly." },
    { q: "Early one morning, Ali saw water droplets (dew) on the grass in the school field although it had not rained. (a) Name the process that formed the droplets. (b) Explain how the droplets formed on the grass. (c) By 10 a.m., the droplets had disappeared. Explain why.", marks: 3, kw: [["condens"], ["loses heat", "lose heat", "lost heat", "losing heat", "gives off heat", "gave off heat", "gives out heat", "gave out heat"], ["evaporat"]], model: "(a) Condensation. (b) Water vapour in the surrounding air came into contact with the cooler grass, lost heat to it and condensed into water droplets. (c) As the surroundings became warmer, the droplets gained heat and evaporated into water vapour." }
  ],
  tf: [
    { s: "When water evaporates, it loses heat.", a: false, why: "Evaporating water GAINS heat from its surroundings. That is why evaporation of sweat cools our body." },
    { s: "Ice melts in a drink because the ice gives out coldness to the drink.", a: false, why: "There is no such thing as ‘coldness’ flowing. Heat flows from the warmer drink to the ice; the ice gains heat and melts, and the drink loses heat." },
    { s: "A puddle can dry up on a cloudy day.", a: true, why: "Evaporation takes place at any temperature, not only when the Sun is shining. It is just slower on a cool day." },
    { s: "Condensation can take place at room temperature.", a: true, why: "Condensation only needs water vapour to touch a cooler surface, e.g. a mirror misting up after a shower or droplets on a cold can at room temperature." },
    { s: "Ice, water and water vapour are three different substances.", a: false, why: "They are the same substance, water, in three different states: solid, liquid and gas." },
    { s: "Wet clothes dry faster on a windy day because the moving air carries water vapour away from the clothes.", a: true, why: "Wind removes water vapour from around the clothes, so the water evaporates faster." },
    { s: "Melting and dissolving are the same process.", a: false, why: "Melting is a change of state from solid to liquid caused by gaining heat. Dissolving, e.g. sugar in teh, is a substance mixing into a liquid; it is not a change of state." },
    { s: "Freezing is a kind of condensation because both involve water losing heat.", a: false, why: "Both involve losing heat, but freezing is liquid to solid while condensation is gas to liquid. They are different changes of state." },
    { s: "Blowing air across a misty car windscreen can clear it because the droplets evaporate.", a: true, why: "The moving air increases the rate of evaporation, so the tiny water droplets change into water vapour and the windscreen clears." },
    { s: "Water in an open dish can be slightly cooler than the air around it.", a: true, why: "As water evaporates from the surface, it gains heat from the rest of the water, so the water loses heat and can be a little cooler than the room." }
  ],
  sort: [
    { title: "Is each statement true of evaporation only, boiling only, or both?", groups: ["Evaporation only", "Boiling only", "Both"], items: [["takes place at any temperature", 0], ["takes place only at the exposed surface", 0], ["usually slow, with no bubbles", 0], ["takes place at a fixed temperature", 1], ["bubbles of water vapour form throughout the water", 1], ["the water gains heat", 2], ["liquid water changes into water vapour", 2], ["water vapour escapes into the surrounding air", 2]] }
  ]
};
