window.LBY = window.LBY || {};
LBY["p5-water"] = {
  lessons: [
    {
      h: "Conclusions when results show time taken or water left",
      concept: "The rate of evaporation is often measured indirectly: by the TIME TAKEN for the water to dry up, or by the mass or volume of water LEFT. Both go the opposite way to the rate. A shorter drying time, or less water left, means a FASTER rate of evaporation. A full-mark conclusion names both variables and both directions, e.g. ‘The higher the humidity of the air, the longer the time taken for the cloth to dry.’",
      example: {
        q: "Priya hung identical wet cloths in four closed rooms at the same temperature, but with different humidity. Study her results. (a) What is the relationship between the humidity of the air and the time taken for the cloth to dry? (b) In which room was the rate of evaporation the fastest? Explain.",
        tbl: [["Room", "Humidity of the air (%)", "Time taken to dry (min)"], ["P", "50", "40"], ["Q", "60", "55"], ["R", "75", "80"], ["S", "90", "150"]],
        marks: 3,
        think: [
          "Step 1: Name the changed variable (humidity of the air) and the measured variable (time taken to dry).",
          "Step 2: Read the trend: as humidity goes up (50, 60, 75, 90), the time goes up (40, 55, 80, 150).",
          "Step 3: Write it as ‘The higher …, the longer …’ using both variables.",
          "Step 4: Translate: the SHORTEST time means the FASTEST rate, so pick room P and say why."
        ],
        answer: "(a) The higher the humidity of the air, the longer the time taken for the cloth to dry. (b) Room P. The cloth in room P took the shortest time to dry, so the water in it evaporated the fastest."
      },
      tip: "Before you write, translate the measurement: shortest time or least water left = fastest rate. Never pick the tallest bar as ‘fastest’ without checking what the bar measures.",
      try: {
        q: "Identical dishes, each with 100 ml of water, were left for 5 hours in rooms at different temperatures. The graph shows the volume of water LEFT. Which conclusion is correct?",
        fig: { type: "bar", xl: "Room temperature", yl: "Volume of water left (ml)", bars: [["20 °C", 88], ["25 °C", 80], ["30 °C", 70], ["35 °C", 58]] },
        o: ["The higher the temperature, the slower the rate of evaporation.", "The lower the temperature, the less water was left in the dish.", "The higher the temperature, the less water was left in the dish.", "The room temperature did not affect the volume of water left."],
        a: 2,
        why: "As the temperature rose, the volume left fell (88, 80, 70, 58 ml), so more water evaporated. Less water left means a FASTER rate, so ‘slower rate’ gets the direction the wrong way round."
      }
    }
  ],
  mcq: [
    { q: "The table shows the temperatures of three samples of pure water. In which state is each sample?", tbl: [["Sample", "Temperature"], ["A", "−8 °C"], ["B", "45 °C"], ["C", "110 °C"]], o: ["A: solid, B: liquid, C: gas", "A: liquid, B: liquid, C: gas", "A: solid, B: gas, C: gas", "A: solid, B: liquid, C: liquid"], a: 0, why: "Below 0 °C pure water is ice (solid); between 0 °C and 100 °C it is liquid; above 100 °C it is water vapour (gas). B at 45 °C can evaporate, but the sample itself is still a liquid.", lvl: 1 },
    { q: "A hailstone fell onto a hot road and turned into water. What is this change of state called?", o: ["Freezing", "Condensation", "Melting", "Evaporation"], a: 2, why: "A hailstone is ice. Ice gains heat from the hot road and changes from solid to liquid: melting.", lvl: 1 },
    { q: "Which state of water has no definite shape AND no definite volume?", o: ["Ice", "Liquid water", "Both liquid water and ice", "Water vapour"], a: 3, why: "Water vapour spreads out to fill any space, so it has neither a definite shape nor a definite volume. Liquid water has a definite volume; ice has both.", lvl: 1 },

    { q: "Sam heated a beaker of water until it boiled. Which statements are correct? A: The large bubbles in the boiling water contain water vapour. B: The temperature of the water stays at 100 °C while it boils. C: The large bubbles are air pushed out of the water.", o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Misconception targeted: ‘the bubbles are air’. During boiling, water changes into water vapour throughout the liquid, forming bubbles of water vapour. The temperature stays at 100 °C while it boils.", lvl: 2 },
    { q: "Which of these are true of BOTH evaporation and boiling? A: Water gains heat. B: Liquid water changes into water vapour. C: Bubbles form throughout the water. D: It takes place only at a fixed temperature.", o: ["A and B only", "A, B and C only", "C and D only", "B, C and D only"], a: 0, why: "In both, water gains heat and changes into water vapour. Bubbles throughout the liquid and a fixed temperature (100 °C) are true of boiling only.", lvl: 2 },
    { q: "Siti wants to find out if the amount of water affects the time taken for the water in a dish to dry up. Which two set-ups should she use?", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Wide dish", "50 ml water", "Under a fan"] }, { label: "B", icon: "dish", lines: ["Wide dish", "100 ml water", "Under a fan"] }, { label: "C", icon: "beaker", lines: ["Narrow beaker", "100 ml water", "Under a fan"] }, { label: "D", icon: "dish", lines: ["Wide dish", "100 ml water", "No fan"] }] }, o: ["B and C", "C and D", "A and B", "B and D"], a: 2, why: "A and B differ only in the amount of water. B and C change the exposed surface area, B and D change the moving air, and C and D change two things.", lvl: 2 },
    { q: "Kumar sorted some changes of state of water into the Venn diagram. He placed ONE process in the wrong region. Which one?", fig: { type: "venn", a: "Water gains heat", b: "At a fixed temperature", onlyA: [], both: ["melting", "boiling", "evaporation"], onlyB: ["freezing"], neither: ["condensation"] }, o: ["Melting", "Boiling", "Evaporation", "Freezing"], a: 2, why: "Evaporation involves gaining heat but takes place at ANY temperature, so it belongs in ‘Water gains heat’ only. Melting (0 °C) and boiling (100 °C) gain heat at a fixed temperature; freezing loses heat at 0 °C.", lvl: 2 },
    { q: "Water in an electric kettle was heated until it boiled, and then the kettle was switched off. The graph shows the temperature of the water. During which period was the water losing heat?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 30], ["4", 70], ["8", 100], ["12", 100], ["16", 80], ["20", 65]] }, o: ["0 min to 8 min", "8 min to 12 min", "8 min to 20 min", "12 min to 20 min"], a: 3, why: "The temperature falls only after 12 min, when the kettle was off and the water lost heat to the cooler air. From 8 to 12 min the water was boiling and still gaining heat.", lvl: 2 },
    { q: "Mrs Lee hung wet clothes along the corridor at 9 p.m. By 7 a.m., the clothes were almost dry, though there was no sunlight all night. Which statement explains this?", o: ["Water evaporates at any temperature, even at night.", "The clothes dried because the water in them boiled.", "The water in the clothes condensed into the night air.", "Moonlight gave the water enough heat to evaporate."], a: 0, why: "Misconception targeted: ‘evaporation needs the Sun’. Water evaporates at any temperature, gaining heat from the surroundings. The water never reached 100 °C, so it did not boil.", lvl: 2 },

    { q: "Water droplets were seen in each case below. In which cases did the water vapour come from the SURROUNDING AIR? A: On the outside of a glass of iced Milo B: On the underside of the plastic cover of a bowl of hot rice C: On the grass in the early morning D: On the inside of a sealed bag holding a wet cloth", o: ["B and D only", "A, C and D only", "A and C only", "A, B, C and D"], a: 2, why: "In A and C, water vapour in the surrounding air loses heat to a cooler surface and condenses. In B the water vapour comes from the hot rice, and in D from the wet cloth inside the sealed bag.", lvl: 3 },
    { q: "Some water was left in a freezer. The graph shows its temperature. Which statements are correct? A: From 10 min to 20 min, the water was losing heat. B: At 30 min, the water was a solid only. C: The freezing point of water is −10 °C.", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 25], ["5", 12], ["10", 0], ["15", 0], ["20", 0], ["25", -5], ["30", -10]] }, o: ["A only", "B and C only", "A, B and C", "A and B only"], a: 3, why: "From 10 to 20 min the water was freezing at 0 °C and still losing heat. After all of it had frozen, the ice cooled below 0 °C, so at 30 min it was solid only. The freezing point is 0 °C, not −10 °C.", lvl: 3 },
    { q: "Identical wet towels were hung in front of a fan set at different speeds. The graph shows the time each towel took to dry. Which conclusion is correct?", fig: { type: "bar", xl: "Fan speed", yl: "Time taken to dry (h)", bars: [["Off", 6], ["Low", 4], ["Medium", 3], ["High", 2]] }, o: ["The faster the moving air, the more time the towel took to dry.", "The faster the moving air, the less time the towel took to dry.", "The faster the moving air, the slower the rate of evaporation.", "The slower the moving air, the faster the rate of evaporation."], a: 1, why: "Misconception targeted: reading a taller bar as ‘more evaporation’. The bars show TIME taken, so a shorter bar means a faster rate. Faster moving air gave a shorter drying time.", lvl: 3 },
    { q: "A kettle is boiling. Above the spout there is a clear gap, then a white mist, and further up the mist disappears. Why does the mist disappear further up?", o: ["The tiny water droplets evaporate into the surrounding air.", "The tiny water droplets freeze and fall back onto the kettle.", "The water vapour condenses, so it becomes invisible again.", "The tiny water droplets turn into air as they cool down."], a: 0, why: "The white mist is tiny water droplets. As they spread out into the surrounding air, they gain heat and evaporate into invisible water vapour. Condensation would make more droplets, not fewer.", lvl: 3 },
    { q: "When Mdm Siti opened her freezer door in a warm, humid kitchen, a white mist appeared near the door. What is the white mist, and how is it formed?", o: ["Water vapour that escapes from the ice in the cold freezer", "Smoke-like cold air that flows out when the door is opened", "Tiny droplets formed when kitchen water vapour loses heat and condenses", "Tiny droplets formed when kitchen water vapour gains heat and condenses"], a: 2, why: "Misconception targeted: the mist is ‘cold smoke’ or visible water vapour. Water vapour in the warm kitchen air loses heat to the cold air from the freezer and condenses into tiny visible droplets. Water vapour itself is invisible.", lvl: 3 },
    { q: "Four identical glasses of iced water at 2 °C were placed on balances in four rooms, all at 30 °C. The graph shows the mass gained by each glass in 20 minutes. In which room was the air most humid?", fig: { type: "bar", xl: "Room", yl: "Mass gained in 20 min (g)", bars: [["P", 2], ["Q", 6], ["R", 4], ["S", 1]] }, o: ["P", "Q", "R", "S"], a: 1, why: "The mass gained is water from the air that condensed on the cool glass. The temperatures were the same, so the glass in Q gained the most because the air in Q held the most water vapour.", lvl: 3 },
    { q: "Identical wet shirts were hung in the same corridor on four days. Study the table. Which best explains why less water was lost on Tuesday than on Monday?", tbl: [["Day", "Temperature", "Wind", "Water lost in 1 h (g)"], ["Monday", "31 °C", "Still", "40"], ["Tuesday", "31 °C", "Still", "25"], ["Wednesday", "28 °C", "Windy", "45"], ["Thursday", "33 °C", "Windy", "60"]], o: ["The air on Tuesday was hotter, so less water evaporated.", "The air on Tuesday was more humid, so evaporation was slower.", "There was more moving air on Tuesday, so less water was lost.", "The shirts on Tuesday had a larger exposed surface area."], a: 1, why: "Monday and Tuesday had the same temperature and still air, and the shirts were identical. The factor left is humidity: more humid air slows evaporation.", lvl: 3 },

    { q: "A beaker of crushed ice and water was left in a room at 30 °C. For 5 minutes, its temperature stayed at 0 °C. Which statements MUST be true during these 5 minutes? A: Some ice was still present. B: The mixture was gaining heat from the room. C: There was no liquid water in the beaker. D: The ice was melting.", o: ["A and B only", "A, B and D only", "B and C only", "A, C and D only"], a: 1, why: "Misconception targeted: ‘a flat part means no heat is gained’. The warmer room keeps giving heat to the mixture; the temperature stays at 0 °C only because that heat is used to melt the ice that is still present. Water is also present, so C is wrong.", lvl: 4 },
    { q: "An open beaker of water on a balance was heated steadily. The water reached 100 °C at 6 min. The graph shows the mass of the beaker and water. Which best explains the graph?", fig: { type: "line", xl: "Time (min)", yl: "Mass (g)", pts: [["0", 500], ["2", 498], ["4", 495], ["6", 492], ["8", 472], ["10", 452]] }, o: ["Before 6 min no water was lost; after 6 min the water boiled away.", "Before 6 min water boiled slowly; after 6 min it evaporated faster.", "Water was lost at the same rate throughout, as it was heated steadily.", "Before 6 min water evaporated slowly; after 6 min it boiled away faster."], a: 3, why: "The mass fell slightly before 6 min (8 g), because water evaporates below 100 °C. From 6 min the water boiled and changed into water vapour throughout the liquid, so the mass fell much faster (20 g every 2 min).", lvl: 4 },
    { q: "Three set-ups were placed on balances in a classroom at 30 °C for 20 minutes, as shown. Which statements are correct? A: The reading for P stays the same. B: The reading for Q decreases. C: The reading for R increases.", fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["Hot water, 70 °C", "Tightly sealed jar"] }, { label: "Q", icon: "dish", lines: ["Water at 30 °C", "Uncovered dish"] }, { label: "R", icon: "beaker", lines: ["Iced water", "Glass with a lid on"] }] }, o: ["A and B only", "B and C only", "A and C only", "A, B and C"], a: 3, why: "P is sealed, so its water vapour cannot escape and it is not cooler than the air. Q loses water by evaporation. The lid on R does not stop water vapour in the surrounding air from condensing on its cooler OUTER surface, so R gains mass.", lvl: 4 },
    { q: "An uncovered glass of iced water was left on a balance in a classroom at 30 °C. Study the readings. Which best explains why the mass decreased after 30 min?", tbl: [["Time (min)", "0", "15", "30", "60", "90"], ["Mass (g)", "350", "354", "356", "353", "349"]], o: ["The glass warmed up, so condensation stopped and water evaporated from it.", "The ice melted fully, so the water in the glass became lighter than ice.", "More water vapour condensed on the glass, so the mass kept on falling.", "The water inside the glass leaked out through the glass into the air."], a: 0, why: "At first the cold glass gained mass as water vapour condensed on it. Once it had warmed up, it was no longer cooler than the air, so no more water condensed, and the droplets and water evaporated. Melting does not change mass.", lvl: 4 }
  ],
  oe: [
    { q: "Daniel poured 50 ml of water into each of four round dishes of different diameters and placed them side by side on a window ledge. He recorded the time taken for the water in each dish to dry up. Study his results. (a) What variable did Daniel change? (b) What variable did he measure? (c) What is the relationship between the diameter of the dish and the time taken for the water to dry up? (d) State one other variable he kept the same.", tbl: [["Dish", "Diameter (cm)", "Time taken to dry up (h)"], ["W", "8", "30"], ["X", "12", "20"], ["Y", "16", "14"], ["Z", "20", "10"]], marks: 4, kw: [["diameter", "size of the dish", "size of dish", "exposed surface area", "surface area"], ["time"], ["shorter", "less time", "faster", "quicker", "more quickly", "longer", "more time"], ["amount of water", "volume of water", "50 ml", "place", "position", "temperature", "wind", "moving air", "humidity"]], model: "(a) The diameter of the dish, which changes the exposed surface area of the water. (b) The time taken for the water to dry up. (c) The larger the diameter of the dish, the shorter the time taken for the water to dry up. (d) The amount of water in each dish." },
    { q: "Ben wants to find out if the temperature of water affects its rate of evaporation. He placed identical dishes, each with 100 ml of water, on hot plates kept at different temperatures, all below 100 °C, as shown. After 1 hour he measured the volume of water left. (a) Which dish will have the least water left? (b) Explain your answer to (a). (c) Why did Ben keep all the hot plates below 100 °C?", fig: { type: "setups", items: [{ label: "P", icon: "dish", lines: ["100 ml water", "Hot plate at 40 °C"] }, { label: "Q", icon: "dish", lines: ["100 ml water", "Hot plate at 60 °C"] }, { label: "R", icon: "dish", lines: ["100 ml water", "Hot plate at 80 °C"] }] }, marks: 3, kw: [["r", "dish r"], ["faster", "higher rate", "more quickly", "quicker", "greater rate"], ["boil"]], model: "(a) Dish R. (b) The water in dish R is at the highest temperature, so it evaporates faster and more water is lost in the same time. (c) So that the water does not boil. He wanted to study only evaporation, which takes place below the boiling point." },
    { q: "Mei Ling filled four identical metal cups with water at different temperatures and placed them in a room at 30 °C. After 10 minutes, she measured the mass of water droplets on the outer surface of each cup. Study the graph. (a) What is the relationship between the temperature of the water in the cup and the mass of droplets formed? (b) Explain why no droplets formed on the cup of water at 30 °C. [2] (c) Predict the mass of droplets on a cup of water at 5 °C.", fig: { type: "bar", xl: "Temperature of water in cup", yl: "Mass of droplets (g)", bars: [["2 °C", 3], ["10 °C", 1.8], ["20 °C", 0.6], ["30 °C", 0]] }, marks: 4, kw: [["the lower", "the colder", "the cooler", "the higher the temperature of the water, the less", "the higher the temperature of the water, the smaller"], ["same temperature", "not cooler", "as warm as"], ["condens", "lose heat", "lost heat", "loses heat"], ["between 1.8 and 3", "between 1.8 g and 3", "between 3 and 1.8", "about 2", "2.2", "2.4", "2.5", "2.6", "2.7", "2.8"]], model: "(a) The lower the temperature of the water in the cup, the greater the mass of droplets formed. (b) The cup was at the same temperature as the surrounding air, so the water vapour in the air did not lose heat to it and did not condense. (c) Between 1.8 and 3.0 g, for example about 2.5 g.", x: 1 },
    { q: "Farah held two identical metal spoons above a pot of boiling water for 5 seconds, as shown. Spoon P was at room temperature and spoon Q had been taken from a fridge. (a) Which spoon had more water droplets on it? (b) Explain how the droplets formed on the spoons. [2] (c) The spoons were then left on a table and after a few minutes the droplets disappeared. Name the process.", fig: { type: "setups", items: [{ label: "P", icon: "pot", lines: ["Spoon at room temp", "Held over boiling water"] }, { label: "Q", icon: "pot", lines: ["Cold spoon from fridge", "Held over boiling water"] }] }, marks: 4, kw: [["q", "spoon q", "cold spoon", "colder spoon", "spoon from the fridge"], ["lose heat", "loses heat", "lost heat", "cooler"], ["condens"], ["evaporat"]], model: "(a) Spoon Q. (b) Water vapour from the boiling water came into contact with the cooler spoons, lost heat and condensed into water droplets. The colder spoon Q made more water vapour lose heat and condense. (c) Evaporation." },
    { q: "To get drinking water on a hike, Hafiz dug a hole in wet soil, placed a cup in the middle and covered the hole with a plastic sheet. He put a small stone on the sheet just above the cup. After some hours in the sun, water had collected in the cup. (a) What happened to the water in the soil? (b) Explain how water droplets formed on the underside of the sheet. [2] (c) Why was the stone placed just above the cup?", marks: 4, kw: [["evaporat"], ["cooler", "lose heat", "loses heat", "lost heat"], ["condens"], ["lowest", "flow", "slide", "drip", "run down", "roll down", "trickle"]], model: "(a) The water in the soil gained heat and evaporated into water vapour. (b) The water vapour came into contact with the cooler underside of the plastic sheet, lost heat and condensed into water droplets. (c) The stone made the point above the cup the lowest part of the sheet, so the droplets flow down to it and drip into the cup." },
    { q: "After Wen took a hot shower, the bathroom mirror misted up. (a) Explain how the mirror misted up. [2] (b) When the exhaust fan was switched on, the mirror cleared. Name the process that made the mirror clear. (c) Explain why the mirror cleared faster with the exhaust fan on.", marks: 4, kw: [["lose heat", "loses heat", "lost heat", "cooler"], ["condens"], ["evaporat"], ["less humid", "humid air", "removes water vapour", "removed water vapour", "moving air", "drier air", "remov", "blow"]], model: "(a) Water vapour from the hot shower came into contact with the cooler mirror, lost heat and condensed into tiny water droplets. (b) Evaporation. (c) The exhaust fan removed the humid air and caused moving air in the bathroom, so the air became less humid and the rate of evaporation of the droplets increased.", x: 1 }
  ],
  tf: [
    { s: "The large bubbles that form in boiling water are bubbles of air.", a: false, why: "They are bubbles of water vapour, formed as water changes into gas throughout the liquid." },
    { s: "There is water vapour in the air of a classroom at 25 °C.", a: true, why: "Water evaporates at any temperature, so the air always holds some invisible water vapour." },
    { s: "Dew falls from the sky like very light rain at night.", a: false, why: "Dew forms on the spot: water vapour in the air loses heat to cooler grass and leaves and condenses on them." },
    { s: "Ice at −5 °C can gain heat without melting.", a: true, why: "Its temperature first rises to 0 °C; it starts to melt only at 0 °C." },
    { s: "A big block of ice melts at a higher temperature than a small ice cube.", a: false, why: "Ice of any size melts at 0 °C; a bigger block just needs more heat, so it takes longer." },
    { s: "Water at 0 °C may be a solid, a liquid, or both.", a: true, why: "0 °C is the melting and freezing point, so ice, water or a mixture of both can be at 0 °C." },
    { s: "When water evaporates, it disappears and no longer exists.", a: false, why: "It changes into water vapour, an invisible gas that is still in the air." },
    { s: "Water droplets can form on the inner surface of a car window on a cool, rainy day when many people are in the car with the air-conditioner off.", a: true, why: "Water vapour in the warm, humid air inside (from breathing) loses heat to the cooler glass and condenses." },
    { s: "Once ice reaches 0 °C, it melts without needing to gain any more heat.", a: false, why: "Ice at 0 °C must keep gaining heat to melt; the heat is used to change it into water." },
    { s: "Water droplets stop forming on a cold can once it has warmed to the temperature of the surrounding air.", a: true, why: "The can is no longer cooler than the air, so water vapour no longer loses heat to it and condenses." }
  ],
  doc: [
    { q: "Two identical dishes each held 50 ml of water. After one day, the dish in the sun had 5 ml left and the dish in the shade had 20 ml left. Write a conclusion for this experiment.", marks: 2, answers: ["The dish in the sun had less water left than the dish in the shade.", "The higher the temperature of the surroundings, the faster the rate of evaporation of water.", "The Sun made the water in the dish boil away faster."], best: 1, why: "Answer 2 links the changed variable (temperature of the surroundings) to the rate of evaporation, with both directions. Answer 1 only repeats the results; it is an observation, not a conclusion. Answer 3 is wrong — the water never reached 100 °C, so it evaporated, not boiled." },
    { q: "Explain why a puddle dries faster on a windy day than on a still day.", marks: 2, answers: ["The moving air removes the water vapour above the puddle, so the rate of evaporation of the water increases.", "The wind blows the water in the puddle away.", "The wind is cold, so the water in the puddle dries faster."], best: 0, why: "Answer 1 names the moving air AND links it to a faster rate of evaporation. Answer 2 treats evaporation as the water being blown away. Answer 3 gives the wrong reason — a colder surrounding would slow evaporation, not speed it up; it is the moving air that makes the puddle dry faster." }
  ]
};
