window.LBX = window.LBX || {};
LBX["p5-water"] = {
  notes: [
    { h: "Ice can be colder than 0 °C", t: "Ice taken from a freezer is often well below 0 °C (for example −18 °C). When it is heated, its temperature first rises to 0 °C, then stays at 0 °C while it melts, and only rises again once all the ice has melted. A full heating curve from ice to boiling water therefore has two flat parts: one at 0 °C (melting) and one at 100 °C (boiling).", kw: ["below 0 °C", "stays at 0 °C", "two flat parts"] },
    { h: "Changes of state and mass", t: "A change of state does not change the mass of the water: 20 g of ice melts into 20 g of water. The reading on a balance changes only when water enters or leaves the set-up. It decreases when water evaporates and the water vapour escapes into the surrounding air; it increases when water vapour from the surrounding air condenses on a cooler outer surface; it stays the same in a sealed container.", kw: ["mass stays the same", "escapes into the surrounding air", "sealed container"] },
    { h: "Which side of the glass mists up?", t: "Water droplets form on the side of a glass window that is in contact with the warmer, humid air, because that is where the water vapour is. The window of an air-conditioned room mists up on its OUTER surface, as the water vapour in the warm air outside loses heat to the cooler glass and condenses. A bathroom window after a hot shower mists up on its INNER surface, as the water vapour comes from the shower.", kw: ["warmer, humid air", "outer surface", "inner surface", "condenses"] }
  ],
  traps: [
    "Ice from the freezer is always at 0 °C → it can be much colder (e.g. −18 °C); its temperature rises to 0 °C before it starts to melt.",
    "Every flat part on a temperature graph is a change of state → a flat part at ROOM temperature just means the water has reached the temperature of its surroundings.",
    "Ice loses mass when it melts → the mass stays the same; a balance reading changes only if water vapour escapes or condenses on the set-up from the surrounding air."
  ],
  lessons: [
    {
      h: "Reading a full heating curve",
      concept: "When ice from a freezer is heated, the graph has four parts. (1) Sloping up to 0 °C: ice only, warming up. (2) Flat at 0 °C: melting, ice and water together. (3) Sloping up from 0 °C to 100 °C: liquid water only, warming up. (4) Flat at 100 °C: boiling. A sloping part shows ONE state. A flat part shows a change of state, when heat is still gained but is used to change the state.",
      example: {
        q: "Ice from a freezer was heated steadily until the water boiled. Study the graph. (a) What was the temperature of the ice at the start? (b) In which state or states was the water at 4 min? (c) Explain why the temperature did not change from 10 min to 12 min.",
        fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", -10], ["2", 0], ["4", 0], ["6", 0], ["8", 50], ["10", 100], ["12", 100]] },
        marks: 3,
        think: [
          "Step 1: Read the first point: the ice started at −10 °C, below its melting point.",
          "Step 2: At 4 min the line is flat at 0 °C, so the ice is melting: ice and water are both present.",
          "Step 3: The flat part at 100 °C is boiling. The flame is still lit, so the water is still gaining heat.",
          "Step 4: State what the heat is used for: changing liquid water into water vapour."
        ],
        answer: "(a) −10 °C. (b) Solid and liquid (ice and water). (c) The water was boiling. It was still gaining heat, but the heat gained was used to change the water into water vapour, so its temperature stayed at 100 °C."
      },
      tip: "Label the graph yourself before answering: slope = one state, flat at 0 °C = melting, flat at 100 °C = boiling.",
      try: {
        q: "Using the same graph, during which periods was the water gaining heat while its temperature stayed the same?",
        fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", -10], ["2", 0], ["4", 0], ["6", 0], ["8", 50], ["10", 100], ["12", 100]] },
        o: ["2 min to 6 min only", "10 min to 12 min only", "2 min to 6 min and 10 min to 12 min", "0 min to 2 min and 6 min to 10 min"],
        a: 2,
        why: "The two flat parts (melting at 0 °C and boiling at 100 °C) are when heat is gained but used to change the state. From 0 to 2 min and 6 to 10 min the temperature was rising."
      }
    },
    {
      h: "Explaining changes in mass on a balance",
      concept: "When a set-up is on a balance, ask: did water LEAVE or JOIN the set-up? Mass decreases when water evaporates from an open container and the water vapour escapes into the surrounding air. Mass increases when water vapour from the surrounding air condenses on a cooler outer surface. Mass stays the same when the container is sealed, or when water only changes state inside it (melting, freezing, condensing inside a closed lid).",
      example: {
        q: "Three set-ups were placed on balances in a classroom at 30 °C, as shown. Predict whether the reading of each set-up will increase, decrease or stay the same after 30 minutes. Give a reason for each.",
        fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Ice cubes", "Sealed jar"] }, { label: "B", icon: "beaker", lines: ["Iced water", "Uncovered glass"] }, { label: "C", icon: "dish", lines: ["Warm water", "Uncovered dish"] }] },
        marks: 3,
        think: [
          "Step 1: A is sealed. The ice melts, but no water can enter or leave, so the mass stays the same.",
          "Step 2: B is cooler than the air. Water vapour in the surrounding air condenses on its outer surface, so water JOINS the set-up.",
          "Step 3: C is not cooler than the air. Its water evaporates and the water vapour escapes, so water LEAVES the set-up."
        ],
        answer: "A stays the same: the ice melts, but the jar is sealed, so no water enters or leaves. B increases: water vapour in the surrounding air condenses on the cooler outer surface of the glass and adds to its mass. C decreases: the water evaporates and the water vapour escapes into the surrounding air."
      },
      tip: "Never say ice ‘gets lighter’ as it melts. Mass changes only when water vapour escapes or when droplets from the surrounding air are added.",
      try: {
        q: "A cup of hot soup was tightly covered with a lid and placed on a balance. Water droplets formed on the underside of the lid. What happened to the reading?",
        o: ["It increased, as droplets formed on the lid.", "It decreased, as water from the soup evaporated.", "It stayed the same, as no water left or entered.", "It decreased, as the droplets weigh less than soup."],
        a: 2,
        why: "Water evaporated from the soup and condensed on the lid, but it stayed inside the tightly covered cup, so the total mass did not change."
      }
    }
  ],
  mcq: [
    { q: "Mei poured 200 ml of water from a tall beaker into a flat dish. What happened to the volume and the shape of the water?", o: ["Both its volume and its shape stayed the same.", "Its volume stayed the same but its shape changed.", "Its volume changed but its shape stayed the same.", "Both its volume and its shape changed."], a: 1, why: "Liquid water has a definite volume but no definite shape. It takes the shape of its container, but it is still 200 ml.", lvl: 1 },
    { q: "Ice is heated until the water boils. In which order does the water change state?", o: ["Ice → water → water vapour", "Water → ice → water vapour", "Ice → water vapour → water", "Water vapour → water → ice"], a: 0, why: "Ice gains heat and melts into water, and the water gains heat and boils into water vapour.", lvl: 1 },
    { q: "The Venn diagram groups some changes of state of water. Which process could X be?", fig: { type: "venn", a: "Water gains heat", b: "Ends as a gas", onlyA: ["melting"], both: ["X"], onlyB: [], neither: ["freezing", "condensation"] }, o: ["Freezing", "Condensation", "Melting", "Evaporation"], a: 3, why: "X must involve gaining heat AND end as a gas. Evaporation fits. Melting gains heat but ends as a liquid; freezing and condensation involve losing heat.", lvl: 1 },
    { q: "Four identical ice cubes were placed in different places. The graph shows the time each took to melt completely. Which place was the warmest?", fig: { type: "bar", xl: "Place", yl: "Time taken to melt (min)", bars: [["Fridge", 90], ["Air-con room", 40], ["Sunny corridor", 12], ["Classroom", 25]] }, o: ["Fridge", "Air-con room", "Sunny corridor", "Classroom"], a: 2, why: "The ice melted fastest (12 min) in the sunny corridor, so it gained heat fastest there, which means it was the warmest place.", lvl: 1 },
    { q: "Some water was placed in a freezer. The graph shows its temperature. At what time did the water start to freeze?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 30], ["5", 15], ["10", 0], ["15", 0], ["20", 0], ["25", -6]] }, o: ["0 min", "5 min", "10 min", "25 min"], a: 2, why: "The water reached 0 °C at 10 min and the temperature stayed flat while it froze. After all of it had frozen, the ice cooled below 0 °C.", lvl: 1 },

    { q: "Ice from a freezer was heated steadily. The graph shows its temperature. What was happening from 0 min to 4 min?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", -15], ["2", -6], ["4", 0], ["6", 0], ["8", 0], ["10", 12]] }, o: ["The ice was losing heat and its temperature was falling.", "The ice was gaining heat and melting at a fixed temperature.", "The water was losing heat and freezing into more ice.", "The ice was gaining heat and its temperature was rising."], a: 3, why: "The ice started below 0 °C. It gained heat and warmed up to 0 °C; melting only began at 4 min, when the line became flat.", lvl: 2 },
    { q: "A small pipe carries water away from the air-conditioner in Ravi’s bedroom. Where does this water come from?", o: ["Water vapour in the room air that condensed on the cold parts of the unit", "Rainwater that seeped into the unit through the small gaps in its cover", "Water that evaporated from the cold parts of the unit and then melted", "Tap water that the unit takes in to help it cool the air in the room"], a: 0, why: "The parts inside the air-conditioner are very cold. Water vapour in the room air loses heat to them and condenses into water, which is drained away.", lvl: 2 },
    { q: "Water kept in an unglazed clay pot stays cooler than the room. A little water seeps through the pot to its outer surface. Why does the water inside stay cool?", o: ["The water on the outer surface condenses and gives heat to the room.", "The water on the outer surface evaporates and gains heat from the pot.", "The clay pot gains heat from the water and gives it out as water vapour.", "The clay pot lets cold air from outside flow in to cool the water."], a: 1, why: "As the water on the outer surface evaporates, it gains heat from the pot and the water inside, so the water inside loses heat and stays cool.", lvl: 2 },
    { q: "Study the flowchart. Which process is R?", fig: { type: "flow", root: "Changes of state of water", node: { q: "Does water gain heat?", yes: { q: "Does it end as a gas?", yes: "P", no: "Q" }, no: { q: "Does it end as a liquid?", yes: "R", no: "S" } } }, o: ["Evaporation", "Melting", "Freezing", "Condensation"], a: 3, why: "R loses heat and ends as a liquid, so it is gas to liquid: condensation. Freezing (S) also loses heat but ends as a solid.", lvl: 2 },
    { q: "A dish of water was left on a window ledge. The graph shows the volume of water left in it. How much water evaporated from Day 2 to Day 4?", fig: { type: "line", xl: "Day", yl: "Volume of water left (ml)", pts: [["0", 100], ["1", 86], ["2", 72], ["3", 58], ["4", 44], ["5", 30]] }, o: ["14 ml", "28 ml", "44 ml", "72 ml"], a: 1, why: "72 ml was left on Day 2 and 44 ml on Day 4, so 72 − 44 = 28 ml evaporated. 44 ml is the amount left, not the amount lost.", lvl: 2 },
    { q: "After running on a humid afternoon, Jun Wei felt hot and sticky. Why did he not cool down as quickly as he does on a dry day?", o: ["His sweat evaporated more slowly, so less heat was removed from his body.", "His sweat evaporated more quickly, so more heat was given to his body.", "His sweat condensed on his skin, so it took in more heat from the air.", "Water vapour in the humid air gained heat from his body and condensed."], a: 0, why: "Humid air already holds a lot of water vapour, so sweat evaporates more slowly. Less sweat evaporates, so less heat is removed from his body.", lvl: 2 },
    { q: "A 20 g ice cube was sealed in a small jar and left until it had melted completely. What was the mass of the water in the jar?", o: ["Less than 20 g", "About 10 g", "More than 20 g", "20 g"], a: 3, why: "A change of state does not change mass, and nothing could enter or leave the sealed jar, so the water still has a mass of 20 g.", lvl: 2 },
    { q: "Ice cubes were added to a glass of warm lime juice. Why did the juice become colder?", o: ["The ice gave out coldness to the juice as it melted.", "The ice lost heat to the juice as it melted.", "The ice gained heat from the juice as it melted.", "The juice gained heat from the ice as it froze."], a: 2, why: "Heat flows from the warmer juice to the ice. The ice gains heat and melts, so the juice loses heat and becomes colder. There is no such thing as ‘coldness’ flowing.", lvl: 2 },

    { q: "The same amount of water was poured into four trays with different exposed surface areas and left in the same room. The graph shows the time each tray took to dry. Predict the drying time for a tray with an exposed surface area of 30 cm².", fig: { type: "bar", xl: "Exposed surface area", yl: "Time taken to dry (h)", bars: [["10 cm²", 12], ["20 cm²", 6], ["40 cm²", 3], ["80 cm²", 1.5]] }, o: ["More than 12 h", "Between 6 h and 12 h", "Between 3 h and 6 h", "Less than 3 h"], a: 2, why: "The larger the exposed surface area, the shorter the drying time. 30 cm² lies between 20 cm² (6 h) and 40 cm² (3 h), so it takes between 3 h and 6 h.", lvl: 3 },
    { q: "Two identical cans of cold drink were taken out of the same fridge and placed as shown. After 5 minutes, can B had many more water droplets on it than can A. Which best explains this?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Cold can from fridge", "Air-con room, 20 °C", "Dry air"] }, { label: "B", icon: "box", lines: ["Cold can from fridge", "Canteen, 32 °C", "Humid air"] }] }, o: ["The drink in can B seeped out more because the canteen was warmer.", "The air around can B held more water vapour to condense on the can.", "Can A lost more heat to the air, so its droplets froze and fell off.", "The dry air around can A made more water vapour condense on it."], a: 1, why: "The droplets come from water vapour in the surrounding air. The warm, humid canteen air holds more water vapour, so more of it loses heat to the cold can and condenses.", lvl: 3 },
    { q: "Ice was heated steadily until the water boiled. Study the graph. For how long was the ice melting, and for how long was the liquid water heated before it started to boil?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", -20], ["3", 0], ["6", 0], ["9", 50], ["12", 100], ["15", 100], ["18", 100]] }, o: ["Melting: 3 min; heated as liquid: 6 min", "Melting: 6 min; heated as liquid: 3 min", "Melting: 3 min; heated as liquid: 9 min", "Melting: 6 min; heated as liquid: 6 min"], a: 0, why: "The flat part at 0 °C runs from 3 min to 6 min (3 min of melting). The liquid then warmed from 0 °C at 6 min to 100 °C at 12 min, which is 6 min.", lvl: 3 },
    { q: "Lina set up A and B to find out if moving air affects the rate of evaporation. Which of these must she keep the same for both? W: amount of water X: size of the dish Y: temperature of the room Z: whether the fan is on", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Wide dish", "50 ml water", "Fan on"] }, { label: "B", icon: "dish", lines: ["Wide dish", "50 ml water", "Fan off"] }] }, o: ["W and X only", "X, Y and Z only", "W, X, Y and Z", "W, X and Y only"], a: 3, why: "The fan (moving air) is the variable she changes, so Z must be different. The amount of water, the exposed surface area (dish size) and the temperature must be kept the same.", lvl: 3 },
    { q: "Two identical open beakers held the same amount of water at different temperatures on the same bench. Study the table. Which is NOT a correct conclusion?", tbl: [["Beaker", "Starting temperature", "Water lost in 30 min (g)"], ["P", "80 °C", "18"], ["Q", "30 °C", "4"]], o: ["Water evaporated from both beakers.", "Water evaporated faster from beaker P.", "The water in P lost mass as it boiled.", "Water can evaporate below 100 °C."], a: 2, why: "Water boils only at 100 °C, so the water at 80 °C was evaporating, not boiling. It lost more mass because evaporation is faster at a higher temperature.", lvl: 3 },
    { q: "Three identical bottles of water were placed in two rooms, both at 32 °C. The graph shows the temperature of the water in each bottle after 1 hour. Why was the bottle with a wet cloth in the dry room the coolest?", fig: { type: "bar", xl: "Bottle", yl: "Temperature of water (°C)", bars: [["Dry cloth, humid room", 32], ["Wet cloth, humid room", 29], ["Wet cloth, dry room", 25]] }, o: ["Water in its cloth evaporated faster and gained more heat from the bottle.", "Water in its cloth condensed faster and took in more heat from the bottle.", "The dry air in the room was colder, so it cooled the bottle down faster.", "Water vapour in the dry room lost heat to the bottle and so cooled it."], a: 0, why: "Both rooms were at 32 °C. In the less humid air, water in the cloth evaporated faster, so more heat was gained from the bottle in the same time.", lvl: 3 },
    { q: "Which of these show that evaporation can cause cooling? A: Sweat drying on a runner’s arms makes the arms feel cool. B: Water droplets form on a can of cold drink. C: A freshly mopped floor feels cool to bare feet. D: A fine water mist sprayed at a hot bus stop cools the people waiting.", o: ["A and B only", "B, C and D only", "C and D only", "A, C and D only"], a: 3, why: "In A, C and D, water evaporates and gains heat from the skin or floor, which cools them. B is condensation, in which water vapour loses heat.", lvl: 3 },

    { q: "Two identical glasses were covered with glass plates and left in a room at 30 °C, as shown. Where would water droplets be seen after 10 minutes?", fig: { type: "setups", items: [{ label: "X", icon: "beaker", lines: ["Hot water, 70 °C", "Glass plate on top"] }, { label: "Y", icon: "beaker", lines: ["Iced water, 2 °C", "Glass plate on top"] }] }, o: ["X: underside of the plate; Y: outer surface of the glass", "X: outer surface of the glass; Y: underside of the plate", "X: underside of the plate; Y: no droplets form anywhere", "X: no droplets form anywhere; Y: underside of the plate"], a: 0, why: "In X, water vapour from the hot water loses heat to the cooler plate and condenses on its underside. In Y, the glass is cooler than the room, so water vapour in the surrounding air condenses on its outer surface.", lvl: 4 },
    { q: "Crushed ice at 0 °C in beakers P and Q was heated over identical flames. Study the table. Which statement is correct?", tbl: [["Beaker", "Mass of ice", "Time temperature stayed at 0 °C"], ["P", "100 g", "4 min"], ["Q", "200 g", "8 min"]], o: ["Q’s ice melted at a higher temperature, as it had more ice.", "Q needed more heat to melt all its ice, so it stayed at 0 °C longer.", "P gained no heat while its temperature stayed at 0 °C.", "Q stayed at 0 °C longer because it was losing heat to the flame."], a: 1, why: "Both melted at 0 °C; the melting point does not depend on the amount. More ice needs more heat to melt completely, so with the same flame Q stayed at 0 °C for longer.", lvl: 4 },
    { q: "Two identical wet cloths were hung up. Cloth P was in a room at 25 °C with a fan on; cloth Q was in a room at 35 °C with no fan. The graph shows that both took 3 hours to dry. Kai concluded that temperature and moving air do not affect the rate of evaporation. Which is the best comment?", fig: { type: "bar", xl: "Cloth", yl: "Time taken to dry (h)", bars: [["P (25 °C, fan on)", 3], ["Q (35 °C, no fan)", 3]] }, o: ["He is right, as both cloths took the same time to dry.", "He is wrong; cloth Q should have dried faster, as it was warmer.", "He is wrong; two variables changed, so he cannot tell which had an effect.", "He is right, as the fan cooled cloth P to the same temperature as Q."], a: 2, why: "P had moving air but a lower temperature; Q had a higher temperature but no moving air. Each factor can speed up evaporation, so their effects may simply have balanced out. Only one variable should be changed.", lvl: 4 },
    { q: "A beaker of hot water was left on a table in a room. The graph shows its temperature. Which best explains why the temperature stayed at 30 °C from 20 min to 30 min?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 80], ["5", 60], ["10", 45], ["15", 35], ["20", 30], ["25", 30], ["30", 30]] }, o: ["The water was freezing, so its temperature stayed the same.", "The water had cooled to room temperature, so it stopped cooling.", "The water was boiling, so its temperature could not change.", "The heat it lost was used to change the water into water vapour."], a: 1, why: "30 °C is neither 0 °C nor 100 °C, so this flat part is not a change of state. The water had lost heat until it reached the temperature of the room.", lvl: 4 }
  ],
  tf: [
    { s: "Ice taken from a freezer can be colder than 0 °C.", a: true, why: "Freezers are usually well below 0 °C, so the ice cools below its melting point." },
    { s: "An ice cube sealed in a jar loses mass as it melts.", a: false, why: "A change of state does not change mass; nothing leaves the sealed jar." },
    { s: "Water in an unglazed clay pot stays cool because water on the pot’s outer surface evaporates and gains heat from the pot.", a: true, why: "The water inside loses heat to the evaporating water, so it stays cooler than the room." },
    { s: "A flat part on a temperature–time graph of water always means a change of state.", a: false, why: "A flat part at room temperature means the water has reached the temperature of its surroundings." },
    { s: "The droplets under the lid of a pot of boiling water come from water vapour from the boiling water.", a: true, why: "The water vapour loses heat to the cooler lid and condenses." },
    { s: "Putting a lid on a pot makes boiling water reach a higher temperature than 100 °C.", a: false, why: "Boiling water stays at 100 °C; the lid only reduces the water vapour escaping." },
    { s: "The water dripping from an air-conditioner comes from water vapour in the air.", a: true, why: "Water vapour in the air loses heat to the cold parts of the unit and condenses." },
    { s: "On a humid day, sweat evaporates faster than on a dry day.", a: false, why: "Humid air already holds a lot of water vapour, so sweat evaporates more slowly." },
    { s: "Water vapour condenses only when it touches ice or something frozen.", a: false, why: "It condenses on any surface that is cooler than the water vapour, such as a mirror or a pot lid." },
    { s: "Of the three states of water, only ice has a definite shape.", a: true, why: "Liquid water and water vapour take the shape of their container; ice keeps its own shape." }
  ],
  sort: [
    { title: "Which change of state is taking place (or has taken place)?", groups: ["Melting", "Freezing", "Evaporation", "Condensation"], items: [["ice in a cooler box turning into water", 0], ["an ice lolly dripping at a hot bus stop", 0], ["water in an ice-cube tray hardening in the freezer", 1], ["fruit juice in the freezer becoming an ice pop", 1], ["wet footprints on a pool deck disappearing", 2], ["water on the outside of a clay pot drying up", 2], ["a dog’s wet tongue drying as it pants", 2], ["water dripping from an air-conditioner pipe", 3], ["droplets under the cover of a hot bowl of soup", 3], ["cold water pipes ‘sweating’ in a humid kitchen", 3]] }
  ],
  oe: [
    { q: "Ice was heated steadily until the water boiled. The flame was lit throughout. Study the graph. (a) Name the change of state from 4 min to 8 min. (b) Name the change of state from 16 min to 24 min. (c) Explain why the temperature did not rise from 16 min to 24 min.", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", -20], ["4", 0], ["8", 0], ["12", 50], ["16", 100], ["20", 100], ["24", 100]] }, marks: 4, kw: [["melt"], ["boil"], ["gain", "absorb"], ["water vapour", "gas"]], model: "(a) Melting. (b) Boiling. (c) The water was still gaining heat from the flame, but the heat gained was used to change the liquid water into water vapour, so its temperature stayed at 100 °C." },
    { q: "Water kept in an unglazed clay pot stays cooler than the room. A little water seeps through tiny holes in the pot to its outer surface. (a) What happens to the water on the outer surface of the pot? (b) Explain how this keeps the water inside cool. (c) Would the pot keep water cooler on a dry, windy day or on a humid, still day? Give a reason.", marks: 4, kw: [["evaporat"], ["gain", "absorb", "takes heat", "took heat", "removes heat"], ["dry", "windy", "less humid"], ["faster", "higher rate", "increases the rate", "more quickly", "quicker"]], model: "(a) It evaporates. (b) As the water on the outer surface evaporates, it gains heat from the pot and the water inside, so the water inside loses heat and stays cool. (c) On a dry, windy day, because the less humid, moving air increases the rate of evaporation, so heat is removed from the water faster." },
    { q: "Amir wants to find out whether the temperature of the surroundings affects the rate of evaporation. He set up A, B and C as shown. (a) Which two set-ups should he compare? (b) Of these two, which will have less water left after 2 days? Explain why.", fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Wide dish", "100 ml water", "Room at 25 °C"] }, { label: "B", icon: "dish", lines: ["Wide dish", "100 ml water", "Room at 35 °C"] }, { label: "C", icon: "beaker", lines: ["Narrow beaker", "100 ml water", "Room at 35 °C"] }] }, marks: 3, kw: [["a and b", "b and a"], ["set-up b", "setup b", "b will", "b would", "b has", "b because", "b as", "b is"], ["higher temperature", "warmer", "hotter", "35"]], model: "(a) A and B. (b) Set-up B will have less water left. It is in a room with a higher temperature, so the water in it evaporates faster." },
    { q: "Two identical pots each held 500 g of water and were boiled over identical flames for 10 minutes. Only one pot had a lid. The graph shows the mass of water left. (a) What was the temperature of the water in each pot while it was boiling? (b) Explain how the lid reduced the loss of water. (c) The pot with the lid still lost some water. Suggest why.", fig: { type: "bar", xl: "Pot", yl: "Mass of water left (g)", bars: [["With lid", 450], ["Without lid", 380]] }, marks: 4, kw: [["100"], ["condense"], ["drip", "fall back", "flow back", "back into"], ["escape", "gap", "leak", "got out"]], model: "(a) 100 °C in both pots. (b) The water vapour came into contact with the cooler lid, lost heat and condensed into water droplets, which dripped back into the pot. (c) The lid did not seal the pot completely, so some water vapour escaped through the gaps between the lid and the pot.", x: 1 },
    { q: "Mdm Tan’s bedroom is air-conditioned all night. In the morning she sees water droplets on her bedroom window. (a) On which surface of the window do the droplets form? (b) Explain how they are formed. (c) After a hot shower on a cool, rainy morning, droplets form on the bathroom window. On which surface do they form, and where does the water vapour come from?", marks: 4, kw: [["outer surface", "outer side", "outside surface", "outside of the window"], ["condense"], ["inner surface", "inner side", "inside surface", "inside of the window"], ["shower", "bathroom air", "air in the bathroom"]], model: "(a) The outer surface of the window. (b) The glass is cooled by the air-conditioned room. Water vapour in the warm, humid air outside comes into contact with the cooler outer surface, loses heat and condenses into water droplets. (c) The inner surface. The water vapour comes from the hot shower, which makes the air in the bathroom warm and humid.", x: 1 },
    { q: "A wet towel was hung from a balance in a corridor. The graph shows its mass. (a) How much water evaporated in the first 2 hours? (b) The dry towel has a mass of 300 g. How much water did the towel hold at the start? (c) Explain why the mass stopped decreasing after 8 hours.", fig: { type: "line", xl: "Time (h)", yl: "Mass of towel (g)", pts: [["0", 500], ["2", 440], ["4", 380], ["6", 330], ["8", 300], ["10", 300]] }, marks: 3, kw: [["60"], ["200"], ["all the water", "no more water", "no water", "completely dry", "dried completely"]], model: "(a) 60 g. (b) 200 g. (c) By 8 hours all the water in the towel had evaporated, so there was no more water to evaporate and the mass stayed at 300 g, the mass of the dry towel." },
    { q: "Explain why adding ice cubes to a glass of warm lime juice makes the juice colder.", marks: 2, kw: [["gain", "absorb", "took heat", "takes heat"], ["lost heat", "loses heat", "lose heat", "lost its heat"]], model: "The ice cubes gained heat from the juice as they melted, so the juice lost heat and became colder." },
    { q: "On a hot day, a dog pants with its wet tongue hanging out. Explain how this helps the dog to cool down.", marks: 2, kw: [["evaporat"], ["gain", "absorb", "takes heat", "took heat", "removes heat"]], model: "The water on the dog’s tongue evaporates. As it evaporates, it gains heat from the dog’s body, so the dog loses heat and cools down." }
  ],
  doc: [
    { q: "Why does a wet towel placed on the forehead help to cool a person with a fever?", marks: 2, answers: ["The water in the towel evaporates and gains heat from the forehead, so the forehead loses heat.", "The wet towel is cold, so it gives coldness to the forehead.", "The water in the towel evaporates."], best: 0, why: "Answer 1 names evaporation AND says the water gains heat from the forehead. Answer 2 is a misconception — coldness does not flow; heat does. Answer 3 names the process but does not explain how it removes heat from the forehead." },
    { q: "Water drips from the pipe of an air-conditioner in a bedroom. Explain where the water comes from and how it is formed.", marks: 2, answers: ["It is water left over from cooling the air.", "The air-conditioner is cold, so water forms on it.", "Water vapour in the room air loses heat to the cold parts of the air-conditioner and condenses into water."], best: 2, why: "Answer 3 names the source (water vapour in the room air), the heat loss to the cold parts and condensation. Answer 1 is vague and does not say where the water came from. Answer 2 gives no source and no heat loss or condensation." },
    { q: "Ice was heated steadily. Its temperature stayed at 0 °C for 4 minutes and then began to rise. Why did the temperature start to rise?", marks: 2, answers: ["The ice started gaining heat.", "All the ice had melted, so the heat gained was used to raise the temperature of the water.", "The water started to boil."], best: 1, why: "Answer 2 says all the ice had melted AND what the heat was then used for. Answer 1 is wrong — the ice was gaining heat all along, even at 0 °C. Answer 3 is wrong — water boils at 100 °C, not just above 0 °C." }
  ]
};
