window.LBU = window.LBU || {};
LBU["p5-water"] = {
  glossary: [
    { t: "Change of state", d: "A change of a substance from one state to another, e.g. from solid to liquid, caused by gaining or losing heat. The mass of the substance stays the same." },
    { t: "Melting", d: "The process in which a solid gains heat and changes into a liquid. Ice melts into water at 0 °C." },
    { t: "Freezing", d: "The process in which a liquid loses heat and changes into a solid. Water freezes into ice at 0 °C." },
    { t: "Boiling", d: "The process in which a liquid gains heat and changes quickly into a gas throughout the liquid at its boiling point, with bubbles of gas forming inside it." },
    { t: "Evaporation", d: "The process in which a liquid gains heat and slowly changes into a gas at its exposed surface. It can take place at any temperature." },
    { t: "Condensation", d: "The process in which a gas loses heat and changes into a liquid, e.g. water vapour losing heat to a cooler surface and condensing into water droplets." },
    { t: "Water vapour", d: "Water in the gaseous state. It is invisible, has no definite shape and no definite volume, and is always present in the air around us." },
    { t: "Melting point", d: "The fixed temperature at which a solid melts. The melting point of ice is 0 °C, which is the same as the freezing point of water." },
    { t: "Boiling point", d: "The fixed temperature at which a liquid boils. Pure water boils at 100 °C, and its temperature stays at 100 °C while it boils." },
    { t: "Exposed surface area", d: "The area of the surface of a liquid that is in contact with the surrounding air. The larger the exposed surface area, the faster the liquid evaporates." },
    { t: "Humidity", d: "The amount of water vapour in the air. The more humid the air, the more slowly water evaporates, so wet things take longer to dry." },
    { t: "Rate of evaporation", d: "How fast a liquid evaporates, shown by the amount of water lost in a fixed time or by the time taken for the water to dry up." }
  ],
  lessons: [
    {
      h: "Explaining a chain: evaporation, then condensation",
      concept: "Some questions need TWO changes of state explained in order. First say where the liquid water starts, that it gains heat and evaporates into water vapour. Then say where the water vapour goes, the cooler surface it comes into contact with, that it loses heat to that surface and condenses into water droplets. Leaving out either link, or the direction of heat flow, usually costs a mark.",
      example: {
        q: "Wei Jie keeps his fish tank, covered with a glass lid, in an air-conditioned room at 24 °C. A lamp in the tank keeps the water at 28 °C. After a few days, he sees water droplets on the underside of the lid. (a) Name the two changes of state that took place. (b) Explain how the droplets formed on the underside of the lid.",
        marks: 3,
        think: [
          "Step 1: Find where the water starts: liquid water in the tank, kept warm (28 °C) by the lamp.",
          "Step 2: First change: the water gains heat and evaporates at its exposed surface into water vapour, which fills the space under the lid.",
          "Step 3: Second change: the glass lid loses heat to the cooler air-conditioned room, so it is cooler than the water vapour. The water vapour comes into contact with the cooler lid, loses heat to it and condenses into water droplets.",
          "Step 4: Check that both heat directions are stated: the water GAINS heat to evaporate; the water vapour LOSES heat to condense."
        ],
        answer: "(a) Evaporation and condensation. (b) The warm water in the tank gained heat and evaporated into water vapour. The water vapour came into contact with the cooler underside of the glass lid, lost heat to it and condensed into water droplets."
      },
      tip: "Two changes, two heat directions: water gains heat to evaporate; water vapour loses heat to a cooler surface to condense.",
      try: {
        q: "Aunty Mary covered a pot of hot porridge with a cool metal lid. Soon, water droplets formed under the lid and dripped back into the porridge. Which explanation is complete and correct?",
        o: ["Water from the porridge evaporated, then the water vapour lost heat to the cooler lid and condensed.", "Water from the porridge evaporated, then the water vapour gained coldness from the lid and froze.", "Water vapour from the room air lost heat to the cooler lid and condensed on its underside.", "Water from the porridge boiled, then the water vapour gained heat from the lid and condensed."],
        a: 0,
        why: "The water comes from the hot porridge: it gains heat and evaporates, and the water vapour then loses heat to the cooler lid and condenses. Water vapour never gains ‘coldness’ or gains heat to condense, and the lid covers the pot, so the vapour under it comes from the porridge, not the room."
      }
    },
    {
      h: "Writing the aim and naming the variables",
      concept: "Many Booklet B parts ask for the aim, the variable changed, the variable measured or a variable kept the same. The aim links the two variables: ‘To find out if [changed variable] affects [measured variable].’ Name each variable in full – ‘the speed of the fan’, not ‘the fan’; ‘the time taken for the cloth to dry’, not ‘the time’. Variables kept the same are things that could also affect the result, such as the amount of water, the size of the cloth or the temperature of the room.",
      example: {
        q: "Farid soaked three identical cotton cloths in 50 ml of water each. He hung them in the same room at 30 °C in front of a fan set at different speeds and recorded the time each cloth took to dry. Study the table. (a) What was the aim of his experiment? (b) State the variable he changed and the variable he measured. (c) State one variable he kept the same.",
        tbl: [["Fan speed", "Time taken to dry (min)"], ["0 (off)", "150"], ["1", "95"], ["3", "50"]],
        marks: 4,
        think: [
          "Step 1: Find what Farid changed on purpose: the speed of the fan, which changes how fast the air moves.",
          "Step 2: Find what he measured: the time taken for each cloth to dry.",
          "Step 3: Join the two into the aim: ‘To find out if the speed of the fan affects the time taken for a wet cloth to dry.’",
          "Step 4: For a variable kept the same, pick something that could affect drying but did not change: the amount of water in each cloth (50 ml), the size and type of cloth, or the temperature of the room (30 °C)."
        ],
        answer: "(a) To find out if the speed of the fan (moving air) affects the time taken for a wet cloth to dry. (b) Changed: the speed of the fan. Measured: the time taken for each cloth to dry. (c) The amount of water in each cloth."
      },
      tip: "Never write just ‘the fan’ or ‘the time’ – write the full variable: ‘the speed of the fan’, ‘the time taken for the cloth to dry’.",
      try: {
        q: "Identical dishes, each with 100 ml of water, were left for 6 hours in three rooms. Study the table. Which is the best aim for this experiment?",
        tbl: [["Dish", "Temperature of room (°C)", "Volume of water left after 6 h (ml)"], ["A", "24", "82"], ["B", "28", "70"], ["C", "32", "58"]],
        o: ["To find out if the type of dish affects the volume of water left after 6 hours.", "To find out if the temperature of the room affects the volume of water left after 6 hours.", "To find out if the volume of water at the start affects the temperature of the room.", "To find out if the length of time left affects the temperature of the room."],
        a: 1,
        why: "Only the temperature of the room was changed, and the volume of water left after 6 hours was measured, so the aim must link these two. The dishes, starting volume and time were all kept the same, and the temperature of the room was not measured as a result."
      }
    }
  ],
  flash: [
    { f: "Where does the water dripping from an air-conditioner pipe come from?", b: "From water vapour in the room air. It loses heat to the cold parts inside the air-conditioner and condenses into water, which flows out through the pipe." },
    { f: "Why does a spread-out wet cloth dry faster than a folded one?", b: "Spreading it out gives the water a larger exposed surface area, so the rate of evaporation increases and the cloth dries faster." },
    { f: "How does dew form on grass in the early morning?", b: "At night the grass loses heat and becomes cooler than the air. Water vapour in the surrounding air loses heat to the cooler grass and condenses into water droplets." },
    { f: "Why do clothes take longer to dry on a humid day?", b: "Humid air already holds a lot of water vapour, so the water in the clothes evaporates more slowly." },
    { f: "Which side of the window of an air-conditioned room mists up, and why?", b: "The outer surface. Water vapour in the warm, humid air outside loses heat to the cooler glass and condenses into tiny water droplets." },
    { f: "Why does the mass of an uncovered glass of iced water increase?", b: "Water vapour in the surrounding air loses heat to the cooler outer surface of the glass and condenses on it. The droplets add to the mass." },
    { f: "Does the mass change when ice melts in a sealed container?", b: "No. A change of state does not change the mass: 20 g of ice melts into 20 g of water, because no water enters or leaves the container." },
    { f: "What is inside the big bubbles in boiling water?", b: "Water vapour. The water gains heat and changes into water vapour throughout the liquid, forming bubbles that rise and burst at the surface." },
    { f: "Describe the temperature of ice at −18 °C as it is heated until it has all melted.", b: "Its temperature rises to 0 °C, stays at 0 °C while the ice melts, then rises again only after all the ice has melted." },
    { f: "Why does adding ice cubes make a drink colder?", b: "The ice gains heat from the warmer drink to melt. The drink loses heat, so its temperature drops. The ice does not give out ‘coldness’." },
    { f: "Why does the white mist above a kettle disappear further up?", b: "The tiny water droplets in the mist gain heat from the surrounding air and evaporate into water vapour, which is invisible." },
    { f: "Why does the water level in an open fish tank slowly drop?", b: "The water at the exposed surface gains heat from the surroundings and evaporates into water vapour, which escapes into the air." }
  ],
  mcq: [
    { q: "The table shows four changes of state of water. Which row is correct?", tbl: [["Row", "Change of state", "Starting state", "Final state"], ["A", "Melting", "Liquid", "Solid"], ["B", "Condensation", "Gas", "Liquid"], ["C", "Freezing", "Solid", "Liquid"], ["D", "Evaporation", "Gas", "Liquid"]], o: ["A", "B", "C", "D"], a: 1, why: "Condensation is the change from gas to liquid. Melting is solid to liquid, freezing is liquid to solid and evaporation is liquid to gas – rows A, C and D have the states the wrong way round.", lvl: 1 },
    { q: "Ali wants to measure the volume of water left in a dish after one day. Which instrument should he use?", o: ["Thermometer", "Electronic balance", "Measuring cylinder", "Metre rule"], a: 2, why: "A measuring cylinder measures the volume of a liquid. A thermometer measures temperature, a balance measures mass and a metre rule measures length.", lvl: 1 },
    { q: "At a minimart, water droplets form on the outside of the glass door of a drinks chiller. Which process forms these droplets?", o: ["Melting", "Evaporation", "Boiling", "Condensation"], a: 3, why: "Water vapour in the warm air of the shop loses heat to the cooler glass door and condenses into water droplets. Evaporation and boiling change liquid into gas, the opposite direction.", lvl: 1 },
    { q: "In which of these does water GAIN heat?", o: ["Water in an ice tray turning into ice", "Water vapour turning into dew on grass", "Water vapour forming mist on a mirror", "Ice in a drink turning into water"], a: 3, why: "Melting ice gains heat from the warmer drink. Freezing (ice tray) and condensation (dew, misty mirror) are changes in which water loses heat.", lvl: 1 },
    { q: "After a heavy shower, Mr Lee timed how long identical wet patches took to dry at four spots in his school: an open field, a sheltered void deck, a sunny basketball court and a windy rooftop garden. The graph shows his results. Which spot was most likely the sheltered void deck?", fig: { type: "bar", xl: "Spot", yl: "Time taken to dry (min)", bars: [["P", 35], ["Q", 50], ["R", 120], ["S", 40]] }, o: ["P", "Q", "R", "S"], a: 2, why: "The sheltered void deck is shaded (lower temperature) and has little wind, so water evaporates most slowly there and the patch takes the longest time to dry – spot R, 120 min.", lvl: 2 },
    { q: "After the lunch crowd, a cleaner at a hawker centre wants the wet floor to dry quickly. Which of these would NOT help?", o: ["Switching on the large standing fans", "Closing all the shutters so no wind blows in", "Spreading the puddles out thinly with a squeegee", "Opening the shutters to let in the afternoon breeze"], a: 1, why: "Closing the shutters stops the moving air, so evaporation is slower. Fans and the breeze give moving air, and spreading the puddles increases the exposed surface area – all of these increase the rate of evaporation.", lvl: 2 },
    { q: "Jun wants to find out if the temperature of the surroundings affects the time taken for an ice cube to melt completely. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["20 g ice cube", "Metal plate", "Room at 25 °C"] }, { label: "B", icon: "plate", lines: ["20 g ice cube", "Metal plate", "Room at 32 °C"] }, { label: "C", icon: "plate", lines: ["40 g ice cube", "Metal plate", "Room at 32 °C"] }, { label: "D", icon: "plate", lines: ["20 g ice cube", "Plastic plate", "Room at 25 °C"] }] }, o: ["A and B", "A and D", "B and C", "C and D"], a: 0, why: "A and B differ only in the temperature of the room. A and D differ in the plate, B and C in the mass of ice, and C and D in three ways.", lvl: 2 },
    { q: "Which of these observations show that the air around us contains water vapour?\nA: Water drips from the pipe of an air-conditioner.\nB: Droplets form on the outside of a cold can of drink.\nC: Bubbles form in a pot of boiling water.\nD: An ice cube melts on a plate.", o: ["A and B only", "A and C only", "B and D only", "A, B and C only"], a: 0, why: "In A and B, water vapour from the surrounding air loses heat to a cold surface and condenses, so the water must have come from the air. The bubbles in C come from the boiling water itself, and D is ice melting.", lvl: 2 },
    { q: "Wet hands dry faster under the warm-air hand dryer in a shopping mall toilet than when left to dry in still air. Which of these cause this?\nA: The air from the dryer is warmer.\nB: The air from the dryer is moving.\nC: There is more water on the hands.", o: ["A only", "B only", "A and B only", "A, B and C"], a: 2, why: "A higher temperature and moving air both increase the rate of evaporation. More water on the hands would make them take longer to dry, not shorter, and the amount of water is the same in both cases.", lvl: 2 },
    { q: "A wet towel hung in an HDB corridor was weighed every hour. The graph shows its mass. During which hour did water evaporate from the towel the fastest?", fig: { type: "line", xl: "Time", yl: "Mass of towel (g)", pts: [["9 am", 900], ["10 am", 840], ["11 am", 760], ["12 pm", 650], ["1 pm", 480], ["2 pm", 450]] }, o: ["9 am to 10 am", "10 am to 11 am", "11 am to 12 pm", "12 pm to 1 pm"], a: 3, why: "The towel lost 60 g, 80 g, 110 g, 170 g and 30 g in the five hours. The biggest loss, 170 g, was from 12 pm to 1 pm – the steepest part of the graph.", lvl: 2 },
    { q: "Which statement about water vapour is NOT correct?", o: ["It is present in the air around us.", "It has no definite shape or volume.", "It can be seen as a white mist.", "It forms when water evaporates or boils."], a: 2, why: "Water vapour is an invisible gas. The white mist seen above a kettle is made of tiny water droplets formed when water vapour condenses. The other three statements are correct.", lvl: 2 },
    { q: "Study the flowchart. Which processes are Q and T?", fig: { type: "flow", root: "Changes of state of water", node: { q: "Water gains heat?", yes: { q: "Ends as a gas?", yes: { q: "Only at the surface?", yes: "P", no: "Q" }, no: "R" }, no: { q: "Ends as a liquid?", yes: "S", no: "T" } } }, o: ["Q: boiling, T: freezing", "Q: evaporation, T: condensation", "Q: boiling, T: condensation", "Q: melting, T: freezing"], a: 0, why: "Q gains heat, ends as a gas and takes place throughout the liquid, not only at the surface – boiling. T loses heat and does not end as a liquid, so it ends as a solid – freezing. (P is evaporation, R is melting and S is condensation.)", lvl: 3 },
    { q: "A cold can of drink was left on a table, and water droplets formed on its outer surface. Which statements are correct?\nA: Water vapour in the air lost heat to the can.\nB: The can gained heat from the water vapour.\nC: The water droplets came from the drink inside the can.\nD: The mass of the can and the droplets on it increased.", o: ["A and C only", "B and D only", "A, B and D only", "A, C and D only"], a: 2, why: "Water vapour from the surrounding air loses heat to the cooler can (so the can gains heat) and condenses on it, adding to the mass. The drink cannot pass through the can, so C is wrong.", lvl: 3 },
    { q: "On rainy days, Mrs Tan runs a dehumidifier while drying laundry in her HDB flat. Room air passes over cold metal coils inside it, and water collects in its tank. Which statements are correct?\nA: The water in the tank came from water vapour in the room air.\nB: Water vapour loses heat to the cold coils and condenses.\nC: The laundry dries faster because the air becomes less humid.\nD: The dehumidifier boils the water in the laundry.", o: ["A, B and C only", "A and B only", "B and D only", "A, C and D only"], a: 0, why: "Water vapour in the room air loses heat to the cold coils and condenses, and the water drips into the tank. With less water vapour, the air is less humid, so water in the laundry evaporates faster. Nothing is boiled – the laundry dries by evaporation.", lvl: 3 },
    { q: "Ravi recorded the time taken for identical wet cloths to dry in front of a fan at different speeds. Study his results. Which result does not fit the pattern, and what should Ravi do?", tbl: [["Fan speed", "Time taken to dry (min)"], ["0 (off)", "120"], ["1", "90"], ["2", "95"], ["3", "45"], ["4", "30"]], o: ["Speed 1; leave it out and draw a conclusion", "Speed 2; repeat the test at speed 2", "Speed 3; use a bigger cloth at speed 3", "Speed 4; switch the fan off and test again"], a: 1, why: "The time falls as the fan speed increases, except at speed 2, where 95 min is longer than at speed 1. An odd result should be checked by repeating the test, keeping everything else the same; using a bigger cloth would make the test unfair.", lvl: 3 },
    { q: "Equal masses of crushed ice, X at −5 °C and Y at −20 °C, were placed in identical beakers and heated over identical flames. Which statements are correct?\nA: X starts to melt before Y.\nB: Both X and Y melt at 0 °C.\nC: Y melts at a lower temperature than X.", o: ["A and B only", "A only", "B and C only", "A, B and C"], a: 0, why: "Ice always melts at 0 °C, however cold it was at the start, so C is wrong. X has a smaller rise (5 °C) to reach 0 °C than Y (20 °C), so X reaches its melting point and starts to melt first.", lvl: 3 },
    { q: "Beakers P and Q held 200 ml and 400 ml of water at 30 °C and were heated over identical flames. Study the table. Which statement is correct?", tbl: [["Time (min)", "P (°C)", "Q (°C)"], ["0", "30", "30"], ["4", "80", "55"], ["6", "100", "68"], ["10", "100", "90"], ["14", "100", "100"], ["18", "100", "100"]], o: ["Q boils at a higher temperature because it holds more water.", "At 18 min, P is hotter than Q because P has boiled for longer.", "From 6 to 14 min, P gained no heat as its temperature stayed the same.", "Q needed more heat to reach 100 °C, so it started to boil later."], a: 3, why: "Both beakers boil at 100 °C, so at 18 min they are equally hot. Q has more water, so it needs more heat to reach 100 °C and starts to boil later. P was still gaining heat from 6 to 14 min, but the heat was used to change the water into water vapour.", lvl: 3 },
    { q: "Hana wrapped the bulb of a thermometer in a wet cloth and left it in a room at 30 °C. She switched on a fan at 10 min. The graph shows the reading. Which best explains the readings from 40 min to 60 min?", fig: { type: "line", xl: "Time (min)", yl: "Thermometer reading (°C)", pts: [["0", 30], ["10", 28], ["20", 25], ["30", 25], ["40", 25], ["50", 28], ["60", 30]] }, o: ["The fan made the air warmer, so the bulb gained heat from the moving air.", "All the water in the cloth had evaporated, so it stopped removing heat from the bulb.", "The cloth had soaked up more water, so less heat was removed from the bulb.", "The air around the bulb became more humid, so no more water could evaporate."], a: 1, why: "While the cloth was wet, evaporating water gained heat from the bulb, keeping the reading below room temperature. Once the cloth had dried out, nothing removed heat from the bulb, so it gained heat from the air until it reached 30 °C. A fan only moves air at room temperature, and no water was added.", lvl: 4 },
    { q: "Lina set up A, B and C, each with 50 ml of water, and recorded the time taken for the water to dry up. She now wants to find out if moving air affects the rate of evaporation. Which new set-up should she add, to compare with one of hers?", tbl: [["Set-up", "Dish", "Fan", "Room temperature"], ["A", "Wide", "On", "30 °C"], ["B", "Narrow", "On", "30 °C"], ["C", "Narrow", "Off", "25 °C"]], o: ["Wide dish, fan on, 25 °C", "Wide dish, fan off, 25 °C", "Narrow dish, fan off, 32 °C", "Narrow dish, fan off, 30 °C"], a: 3, why: "A narrow dish with the fan off at 30 °C differs from B only in the fan, giving a fair test. Each other new set-up would differ from every existing one in the temperature or the dish, or in more than one variable.", lvl: 4 },
    { q: "Kai placed dishes X and Y side by side on a window ledge. Study the table. Both dishes dried up in exactly 5 hours. Which conclusion is correct?", tbl: [["Dish", "Exposed surface area (cm²)", "Volume at start (ml)", "Time to dry up (h)"], ["X", "80", "100", "5"], ["Y", "20", "25", "5"]], o: ["Both dishes lost water at the same rate, as both dried up in 5 hours.", "X lost water faster, but he cannot tell if this was due to its larger surface area.", "X lost water faster, which proves that a larger surface area increases evaporation.", "Y lost water faster, as it had less water to lose in the same amount of time."], a: 1, why: "X lost 100 ml in 5 h (20 ml per hour) and Y lost 25 ml in 5 h (5 ml per hour), so X lost water faster. But both the surface area and the volume of water were changed, so it is not a fair test and Kai cannot say which variable caused the difference.", lvl: 4 }
  ],
  oe: [
    { q: "At a zi char stall, a fish is steamed on a plate in a covered wok of boiling water. When the cook lifts the metal lid, water droplets drip from its underside. (a) Name the process that formed the droplets on the lid. [1] (b) Where did the water vapour come from? [1] (c) Explain how the droplets formed on the underside of the lid. [1]", marks: 3, kw: [["condens"], ["boiling water", "water in the wok", "the wok", "water below", "hot water"], ["lost heat", "loses heat", "lose heat", "losing heat"]], model: "(a) Condensation. (b) From the boiling water in the wok, which gained heat and changed into water vapour. (c) The hot water vapour came into contact with the cooler underside of the lid, lost heat to it and condensed into water droplets." },
    { q: "Wen placed a test tube of crushed ice at 0 °C into a beaker of warm water at 30 °C. The room was also at 30 °C. She recorded the temperatures shown in the table. (a) In which direction did heat flow from 0 min to 6 min? [1] (b) Explain why the temperature in the test tube stayed at 0 °C from 0 min to 6 min. [1] (c) Why did the temperature in the test tube start to rise after 6 min? [1] (d) Predict what will happen to the two temperatures if the set-up is left for a few hours, and give a reason. [1]", marks: 4, kw: [["from the warm water", "from the water in the beaker", "from the beaker", "beaker water to", "warm water to", "water in the beaker to"], ["used to melt", "melt the ice", "to melt", "change the ice", "changing the ice"], ["all the ice had melted", "all the ice melted", "all of the ice", "ice had melted", "ice has melted", "ice had all melted", "finished melting", "completely melted"], ["same temperature", "room temperature", "equal temperature", "temperature of the room", "same as the room"]], model: "(a) Heat flowed from the warm water in the beaker to the ice in the test tube. (b) The heat gained from the warm water was used to melt the ice, so its temperature stayed at 0 °C. (c) All the ice had melted, so the heat gained then raised the temperature of the water in the test tube. (d) Both will reach the same temperature as the room, 30 °C, because heat keeps flowing from the warmer surroundings until all are at room temperature.", tbl: [["Time (min)", "Test tube (°C)", "Beaker water (°C)"], ["0", "0", "30"], ["2", "0", "26"], ["4", "0", "23"], ["6", "0", "20"], ["8", "5", "18"], ["10", "10", "17"]], x: 1 },
    { q: "Uncle Lim poured 50 ml of hot kopi at 80 °C into a cup and another 50 ml into a wide saucer, and left both on a table in a room at 30 °C. The table shows the temperatures. (a) In which container did the kopi cool faster? [1] (b) Explain, in terms of evaporation, why it cooled faster. [2] (c) Predict the temperature of the kopi in both containers after 2 hours, and give a reason. [1]", marks: 4, kw: [["saucer"], ["larger exposed", "larger surface", "bigger surface", "more surface", "wider surface", "greater surface", "larger area", "bigger area"], ["gains heat from", "gained heat from", "gain heat from", "takes heat", "took heat", "removes heat", "removed heat"], ["30", "room temperature"]], model: "(a) The saucer. (b) The kopi in the saucer had a larger exposed surface area, so water evaporated from it faster. The evaporating water gained heat from the kopi, so the kopi lost heat faster. (c) About 30 °C in both, the same as room temperature, because the kopi stops losing heat once it is at the temperature of its surroundings.", tbl: [["Time (min)", "Cup (°C)", "Saucer (°C)"], ["0", "80", "80"], ["5", "71", "60"], ["10", "64", "48"], ["20", "54", "36"], ["40", "42", "31"]] },
    { q: "In some coastal places, salt is made by letting seawater dry up in large, shallow ponds. Nadia tested this by pouring 500 ml of salty water into trays of different sizes and placing them in the same sunny spot. The graph shows the time each tray took to dry up. (a) Name the process by which the water is removed from the trays. [1] (b) Describe the relationship between the exposed surface area of the water and the time taken to dry up. [1] (c) Explain why salt-makers use shallow, wide ponds rather than deep, narrow ones. [1] (d) Salt-makers work mainly in the dry season. Explain why. [1]", marks: 4, kw: [["evaporat"], ["shorter", "less time", "the smaller the"], ["larger exposed", "larger surface", "bigger surface", "more surface", "greater surface", "wider surface", "larger area", "bigger area"], ["less humid", "less water vapour", "lower humidity", "drier air", "air is drier", "dry air", "less moisture"]], model: "(a) Evaporation. (b) The larger the exposed surface area of the water, the shorter the time taken for it to dry up. (c) Shallow, wide ponds give the seawater a larger exposed surface area, so the water evaporates faster. (d) In the dry season the air is less humid (holds less water vapour) and there is more sunshine, so the water evaporates faster.", fig: { type: "bar", xl: "Exposed surface area of water (cm²)", yl: "Time taken to dry up (h)", bars: [["100", 40], ["200", 21], ["400", 11], ["800", 6]] } }
  ],
  tf: [
    { s: "A larger amount of pure water boils at a higher temperature than a smaller amount.", a: false, why: "Pure water boils at 100 °C whatever the amount. A larger amount only takes longer to reach 100 °C, because it needs more heat." },
    { s: "A puddle in the shade still dries up, but more slowly than an identical puddle in the sun.", a: true, why: "Evaporation takes place at any temperature; the lower temperature in the shade only makes it slower." },
    { s: "When wet clothes dry, the water leaves them as tiny water droplets that are too small to see.", a: false, why: "The water evaporates and leaves as water vapour, a gas. Tiny water droplets are liquid water, as in mist." },
    { s: "Ice cubes in a glass of drink melt faster when the drink is stirred.", a: true, why: "Stirring keeps bringing warmer drink into contact with the ice, so the ice gains heat faster and melts faster." },
    { s: "A wet towel dries faster in still, humid air than in dry, windy air.", a: false, why: "Dry air holds less water vapour and moving air carries the water vapour away, so the towel dries faster in dry, windy air." },
    { s: "Warm water in an open cup evaporates faster than cold water in an identical cup beside it.", a: true, why: "The higher the temperature of the water, the higher the rate of evaporation." },
    { s: "Air and water vapour are the same thing.", a: false, why: "Air is a mixture of gases. Water vapour is only one of the gases in air, and its amount changes from day to day." },
    { s: "The mass of water in a sealed bottle stays the same when the water freezes into ice.", a: true, why: "A change of state does not change the mass, and no water can enter or leave a sealed bottle." },
    { s: "Pouring the same amount of water into a deeper dish increases its exposed surface area.", a: false, why: "A deeper, narrower dish gives the water a SMALLER exposed surface area, so the water evaporates more slowly." },
    { s: "Water droplets can form on the inside of the lid of a covered container of hot food placed in a fridge.", a: true, why: "Water from the hot food evaporates, and the water vapour loses heat to the cooler lid and condenses on its inner surface." }
  ]
};
