window.LB = window.LB || {};
LB["p6-energy"] = {
  notes: [
    { h: "Energy is needed to do work", t: "Energy is the ability to do work. Living things need energy to carry out life processes such as growing, moving and reproducing. Machines such as fans, cars and MRT trains also need energy to work.", kw: ["energy is needed to do work", "living things need energy", "machines need energy"] },
    { h: "The Sun is the main source of energy", t: "The Sun is the main source of energy on Earth; it gives out light and heat energy. Green plants trap light energy from the Sun to make food, and animals get energy by eating plants or other animals that ate plants. So the energy in all food chains comes from the Sun.", kw: ["the sun is the main source of energy", "light energy", "food chain"] },
    { h: "Light, heat, sound and electrical energy", t: "Light energy lets us see and is used by plants to make food. Heat energy flows from a hotter place to a colder place. Sound energy is produced by vibrating objects, and electrical energy is carried by an electric current in a closed circuit.", kw: ["light energy", "heat energy", "sound energy", "electrical energy"] },
    { h: "Kinetic and potential energy", t: "Kinetic energy is the energy of a moving object: the faster it moves, the more kinetic energy it has. Gravitational potential energy is stored in an object because of its height above the ground: the higher and the heavier the object, the more it has. Elastic potential energy is stored in a stretched or compressed object such as a rubber band or spring.", kw: ["kinetic energy", "gravitational potential energy", "elastic potential energy", "higher", "heavier"] },
    { h: "Chemical potential energy", t: "Chemical potential energy is energy stored in food, fuels (such as coal, oil, petrol and natural gas) and batteries. It is released when food is broken down in our bodies, when fuels are burnt, or when a battery is used in a circuit. The energy in food and fuels can be traced back to the Sun, because it was first trapped by plants during photosynthesis.", kw: ["chemical potential energy", "food", "fuels", "batteries", "traced back to the sun"] },
    { h: "Energy conversion", t: "Energy can be converted from one form to another, but it is never used up or destroyed. A torch converts chemical potential energy in the batteries into electrical energy, then into light and heat energy. Some energy is usually converted into heat and sound energy that we do not want, so a bouncing ball bounces lower each time.", kw: ["energy is converted", "cannot be created or destroyed", "heat and sound energy"] },
    { h: "Photosynthesis: the word equation", t: "Photosynthesis is the process by which green plants make their own food. They use light energy, carbon dioxide and water to make sugar and give off oxygen. Word equation: carbon dioxide + water → sugar + oxygen (light energy and chlorophyll are needed).", kw: ["carbon dioxide + water", "sugar + oxygen", "light energy", "chlorophyll"] },
    { h: "Chlorophyll, chloroplasts and raw materials", t: "Chlorophyll is the green substance in chloroplasts that absorbs light energy; most chloroplasts are in the leaf cells. Water is absorbed by the roots and carried up by the water-carrying tubes, while carbon dioxide from the air enters the leaf through tiny openings (stomata). The sugar made is carried to other parts by the food-carrying tubes, and extra sugar is stored as starch.", kw: ["chlorophyll absorbs light energy", "chloroplasts", "stomata", "water-carrying tubes", "food-carrying tubes", "stored as starch"] },
    { h: "Testing a leaf for starch", t: "Starch in a leaf shows that photosynthesis has taken place. Iodine solution is brown; it turns blue-black when starch is present and stays brown when there is no starch. Before an experiment, the plant is destarched by keeping it in the dark for 2 to 3 days, so any starch found later must have been made during the experiment.", kw: ["iodine solution", "blue-black", "remains brown", "destarched", "kept in the dark"] },
    { h: "Classic starch set-ups", t: "Covering part of a leaf with black paper shows that light is needed: only the uncovered part turns blue-black. In a variegated leaf, only the green parts turn blue-black, showing that chlorophyll is needed. A plant sealed in a jar with a substance that absorbs carbon dioxide makes no starch, showing that carbon dioxide is needed.", kw: ["light is needed", "chlorophyll is needed", "carbon dioxide is needed", "substance that absorbs carbon dioxide"] },
    { h: "Rate of photosynthesis and light", t: "A water plant such as Hydrilla gives off bubbles of oxygen in light. The number of bubbles per minute shows the rate of photosynthesis. When the lamp is moved closer, more light reaches the plant, so it photosynthesises faster and gives off more bubbles; only the distance of the lamp should be changed in a fair test.", kw: ["bubbles of oxygen", "rate of photosynthesis", "more light", "number of bubbles per minute"] },
    { h: "Renewable and non-renewable sources", t: "Renewable sources of energy, such as solar, wind and hydro (moving water) energy, will not run out because they are replaced naturally. Non-renewable sources, such as coal, oil and natural gas (fossil fuels), took millions of years to form from the remains of dead plants and animals and will run out once used up. Burning fossil fuels also pollutes the air, so we should use energy wisely.", kw: ["renewable", "will not run out", "non-renewable", "fossil fuels", "millions of years"] }
  ],
  traps: [
    "‘Plants get food from the soil’ → plants MAKE their own food by photosynthesis; the soil gives water and mineral salts, not food.",
    "‘Photosynthesis gives off carbon dioxide’ → photosynthesis takes IN carbon dioxide and gives OFF oxygen.",
    "‘The white part of a variegated leaf has no light’ → it receives light but has NO chlorophyll, so it cannot photosynthesise.",
    "‘Iodine turns starch brown’ → iodine is brown; it turns BLUE-BLACK when starch is present and stays brown when there is none.",
    "‘Destarch a plant by putting it in the Sun’ → destarch by keeping it in the DARK for 2 to 3 days.",
    "‘Energy is used up / lost’ → energy is CONVERTED into other forms, usually heat and sound, never destroyed.",
    "‘An object resting on a high shelf has no energy’ → it has gravitational potential energy because of its height.",
    "‘The energy in a snake comes from the frog it ate’ → ORIGINALLY the energy comes from the Sun, trapped by plants."
  ],
  lessons: [
    {
      h: "Explaining starch results: light and chlorophyll",
      concept: "When a leaf does not turn blue-black, a full answer gives the whole chain: what the part lacked (light or chlorophyll) → so it could not photosynthesise → so no starch was made → so iodine stayed brown. A covered part lacks LIGHT; a white part of a variegated leaf lacks CHLOROPHYLL, even though it receives light. Missing any link usually costs a mark.",
      example: {
        q: "A destarched plant with variegated leaves was placed in sunlight for 6 hours. One leaf was then tested with iodine solution. Parts of the leaf are described in the table. (a) Which part(s) turned blue-black? (b) Explain why part 2 did not turn blue-black.",
        tbl: [["Part", "Colour of part", "Covered with black paper?"], ["1", "Green", "No"], ["2", "White", "No"], ["3", "Green", "Yes"]],
        marks: 3,
        think: [
          "Step 1: A part makes starch only if it has light AND chlorophyll (the plant has water and carbon dioxide).",
          "Step 2: Part 1 is green and uncovered, so it has both: it turns blue-black. Part 3 has chlorophyll but no light. Part 2 has light but no chlorophyll.",
          "Step 3: For (b), name what part 2 lacks (chlorophyll), then link it: no light energy absorbed → no photosynthesis → no starch."
        ],
        answer: "(a) Part 1 only. (b) Part 2 is white, so it has no chlorophyll to absorb light energy. It could not photosynthesise and make food, so no starch was present and the iodine solution remained brown."
      },
      tip: "Name the missing factor, then say ‘could not photosynthesise, so no starch was made’. ‘It is white’ alone scores nothing.",
      try: {
        q: "A destarched plant had part of a leaf covered on both sides with aluminium foil. After 6 hours in sunlight, the leaf was tested with iodine. Why did the covered part stay brown?",
        o: ["It had no chlorophyll, so it could not absorb light to make starch.", "It received no light, so it could not photosynthesise and make starch.", "The foil absorbed all the starch that the covered part had made.", "It received no water, so the starch in that part was washed away."],
        a: 1,
        why: "The covered part still has chlorophyll, but the foil blocks light, so no photosynthesis takes place and no starch is made. The chlorophyll option describes a white part of a variegated leaf, not a covered green part."
      }
    },
    {
      h: "Destarching and the control set-up",
      concept: "A plant is destarched by keeping it in the dark for 2 to 3 days, so it uses up the starch already in its leaves. This makes sure any starch found at the end was made DURING the experiment. A control set-up has everything the plant needs, and is compared with the test set-up so that only one variable is different.",
      example: {
        q: "Before an experiment on photosynthesis, Mei Ling kept a potted plant in a dark cupboard for 3 days. (a) Why did she do this? (b) What would happen to the results if she had not done this?",
        marks: 2,
        think: [
          "Step 1: In the dark, the plant cannot photosynthesise, so it uses up the starch stored in its leaves.",
          "Step 2: The purpose is about the RESULTS: any starch found later must be new starch made during the experiment.",
          "Step 3: Without destarching, old starch could make a leaf turn blue-black even if it could not photosynthesise during the experiment."
        ],
        answer: "(a) To destarch the plant, so the starch already in its leaves is used up and any starch found later must have been made during the experiment. (b) A leaf could turn blue-black because of starch made before the experiment, so the results would not be reliable."
      },
      tip: "Always add the second half: ‘so that any starch found was made during the experiment’.",
      try: {
        q: "Why is a plant kept in the dark for 2 to 3 days before a starch test experiment?",
        o: ["To let the leaves absorb more water so they can make starch faster", "To make more chlorophyll in the leaves so they can absorb more light", "So that it makes extra starch for the test to show up more clearly", "To use up the old starch, so any starch found was made during the experiment"],
        a: 3,
        why: "In the dark the plant cannot photosynthesise and it uses up its stored starch. Keeping it in the dark does not make more starch or chlorophyll."
      }
    },
    {
      h: "The carbon dioxide set-up: picking a fair pair",
      concept: "A substance that absorbs carbon dioxide (placed in a sealed jar) removes the carbon dioxide from the air around the plant, so that plant cannot photosynthesise. To test ONE factor, compare two set-ups that differ ONLY in that factor. To show light is needed, both set-ups must have carbon dioxide; to show carbon dioxide is needed, both must be in light.",
      example: {
        q: "Three destarched plants were set up as shown and left for 6 hours. (a) Which two set-ups should be compared to find out if carbon dioxide is needed for photosynthesis? (b) Which leaves would turn blue-black?",
        fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["In sunlight", "Has substance that", "absorbs carbon dioxide"] }, { label: "Q", icon: "jar", lines: ["In sunlight", "No such substance"] }, { label: "R", icon: "jar", lines: ["In the dark", "No such substance"] }] },
        marks: 2,
        think: [
          "Step 1: List what each has. P: light, no carbon dioxide. Q: light and carbon dioxide. R: carbon dioxide, no light.",
          "Step 2: For carbon dioxide, pick the pair where only carbon dioxide differs and light is the same: P and Q (both in sunlight).",
          "Step 3: Only Q has both light and carbon dioxide, so only Q’s leaves make starch."
        ],
        answer: "(a) P and Q, because both are in sunlight and only the presence of carbon dioxide is different. (b) Only the leaves of Q turn blue-black."
      },
      tip: "Before choosing a pair, write down what each set-up has and lacks. The fair pair differs in exactly one thing.",
      try: {
        q: "Using the same set-ups P, Q and R, which two should be compared to find out if light is needed for photosynthesis?",
        fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["In sunlight", "Has substance that", "absorbs carbon dioxide"] }, { label: "Q", icon: "jar", lines: ["In sunlight", "No such substance"] }, { label: "R", icon: "jar", lines: ["In the dark", "No such substance"] }] },
        o: ["P and Q", "Q and R", "P and R", "P, Q and R"],
        a: 1,
        why: "Q and R both have carbon dioxide and differ only in light. P and R differ in both light and carbon dioxide, so that comparison is not fair."
      }
    },
    {
      h: "Reading bubble graphs",
      concept: "In a water plant experiment, the number of bubbles (oxygen) per minute shows the rate of photosynthesis. Describe the trend using both variables (‘as the distance increases, the number of bubbles per minute decreases’). Then explain it with light: closer lamp → more light reaches the plant → faster photosynthesis → more oxygen given off.",
      example: {
        q: "Study the graph. (a) Describe how the distance of the lamp affects the number of bubbles. (b) Explain the result.",
        fig: { type: "line", title: "Bubbles given off by a water plant", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 42], ["20", 30], ["30", 19], ["40", 11], ["50", 6]] },
        marks: 3,
        think: [
          "Step 1: Read the trend: at 10 cm there are 42 bubbles; at 50 cm only 6. The number falls as distance rises.",
          "Step 2: Link distance to light: the further the lamp, the less light reaches the plant.",
          "Step 3: Link light to the process and the gas: less light → slower photosynthesis → less oxygen given off → fewer bubbles."
        ],
        answer: "(a) As the distance of the lamp from the plant increases, the number of bubbles per minute decreases. (b) The further the lamp, the less light reaches the plant, so the rate of photosynthesis is slower and less oxygen is given off."
      },
      tip: "Say ‘oxygen’, not just ‘gas’, and ‘rate of photosynthesis’, not just ‘the plant grows’.",
      try: {
        q: "Using the graph, about how many bubbles per minute would the plant give off if the lamp were 25 cm away?",
        fig: { type: "line", title: "Bubbles given off by a water plant", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 42], ["20", 30], ["30", 19], ["40", 11], ["50", 6]] },
        o: ["About 11", "About 19", "About 24", "About 36"],
        a: 2,
        why: "25 cm lies between 20 cm (30 bubbles) and 30 cm (19 bubbles), so the value is about halfway, near 24. 19 is the reading for 30 cm."
      }
    },
    {
      h: "Energy conversion chains",
      concept: "Trace energy step by step from where it is stored to where it ends up, naming each form. Height gives gravitational potential energy; movement gives kinetic energy; food, fuels and batteries store chemical potential energy. When a moving object slows down or bounces lower, the energy is not lost: some is converted into heat and sound energy.",
      example: {
        q: "A ball is released from point X at the top of a curved track. It rolls down to Y, the lowest point, and up the other side, stopping at Z, which is lower than X. (a) State the energy conversion as the ball rolls from X to Y. (b) Explain why Z is lower than X.",
        marks: 2,
        think: [
          "Step 1: At X the ball is high and not moving: it has gravitational potential energy.",
          "Step 2: As it rolls down, it loses height and speeds up: gravitational potential energy → kinetic energy.",
          "Step 3: It cannot reach X’s height again because some energy was converted into heat and sound (friction with the track), so less is converted back to gravitational potential energy."
        ],
        answer: "(a) Gravitational potential energy is converted into kinetic energy. (b) As the ball rolls, some energy is converted into heat and sound energy, so there is less energy to be converted back into gravitational potential energy and it cannot rise as high as X."
      },
      tip: "Never write ‘energy is lost’ or ‘used up’. Write ‘converted into heat and sound energy’.",
      try: {
        q: "A boy winds up a toy car and lets it go. Which shows the main energy conversion from the moment the wound-up car is released?",
        o: ["Elastic potential energy → kinetic energy", "Kinetic energy → elastic potential energy", "Chemical potential energy → gravitational potential energy", "Gravitational potential energy → elastic potential energy"],
        a: 0,
        why: "Winding stores elastic potential energy in the spring; when released, the spring unwinds and the car moves, so elastic potential energy becomes kinetic energy."
      }
    }
  ],
  mcq: [
    { q: "What is the main source of energy for living things on Earth?", o: ["The Sun", "Food", "Water", "The wind"], a: 0, lvl: 1, why: "The Sun’s light energy is trapped by plants to make food; food only passes on energy that came from the Sun." },
    { q: "Which gas do green plants take in to make food?", o: ["Oxygen", "Nitrogen", "Carbon dioxide", "Water vapour"], a: 2, lvl: 1, why: "Plants use carbon dioxide and water to make sugar. Oxygen is given OFF during photosynthesis." },
    { q: "Which substance in the leaf absorbs light energy for photosynthesis?", o: ["Starch", "Chlorophyll", "Sugar", "Iodine"], a: 1, lvl: 1, why: "Chlorophyll, the green substance in chloroplasts, absorbs light energy. Starch and sugar are products; iodine is the test chemical." },
    { q: "Which form of energy does a moving bicycle have?", o: ["Elastic potential energy", "Chemical potential energy", "Gravitational potential energy", "Kinetic energy"], a: 3, lvl: 1, why: "Any moving object has kinetic energy." },
    { q: "Iodine solution is added to a slice of potato, which contains starch. What colour will the iodine solution turn?", o: ["Brown", "Green", "Blue-black", "Orange"], a: 2, lvl: 1, why: "Iodine solution is brown and turns blue-black when starch is present. It stays brown if there is no starch." },
    { q: "The diagram shows a plant cell. In which part does photosynthesis take place?", fig: { type: "cell", kind: "plant", mark: { chloroplast: "A", nucleus: "B", vacuole: "C", cell_wall: "D" } }, o: ["A", "B", "C", "D"], a: 0, lvl: 1, why: "A is a chloroplast, which contains chlorophyll to absorb light energy. The nucleus controls cell activities; the cell wall gives shape." },
    { q: "Which of the following is a renewable source of energy?", o: ["Coal", "Natural gas", "Wind", "Oil"], a: 2, lvl: 1, why: "Wind is replaced naturally and will not run out. Coal, oil and natural gas are fossil fuels that will run out." },
    { q: "In which form is energy stored in a battery?", o: ["Kinetic energy", "Elastic potential energy", "Gravitational potential energy", "Chemical potential energy"], a: 3, lvl: 1, why: "Batteries store chemical potential energy, which is converted into electrical energy in a closed circuit." },

    { q: "A destarched plant had part of one leaf covered on both sides with black paper. After 6 hours in sunlight, the leaf was tested with iodine solution. Which correctly describes the result?", o: ["Covered part blue-black, uncovered part brown", "Both parts blue-black", "Covered part brown, uncovered part blue-black", "Both parts brown"], a: 2, lvl: 2, why: "Only the uncovered part received light, photosynthesised and made starch (blue-black). The covered part had no light, so no starch and the iodine stayed brown." },
    { q: "A variegated leaf has green parts and white parts. The plant was destarched and then placed in sunlight for 6 hours. Which parts of the leaf will turn blue-black with iodine solution?", o: ["The green parts only", "The white parts only", "Both the green and white parts", "Neither part"], a: 0, lvl: 2, why: "Only the green parts have chlorophyll to absorb light energy, so only they photosynthesise and make starch. The white parts receive light but have no chlorophyll." },
    { q: "A lamp was placed at different distances from a water plant and the bubbles given off were counted. Study the graph. What does it show?", fig: { type: "line", title: "Bubbles given off by a water plant", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 40], ["20", 28], ["30", 18], ["40", 10], ["50", 5]] }, o: ["The number of bubbles per minute increases as the lamp is moved further away.", "The number of bubbles per minute decreases as the lamp is moved further away.", "The number of bubbles per minute stays the same.", "The plant gives off bubbles only when the lamp is 10 cm away."], a: 1, lvl: 2, why: "The bubbles fall from 40 to 5 per minute as the distance rises from 10 cm to 50 cm. Bubbles are still given off at 50 cm." },
    { q: "The set-ups show a water plant in two beakers with a lamp at different distances. More bubbles are seen in A. Which gas is mainly in the bubbles?", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Water plant", "Lamp 10 cm away"] }, { label: "B", icon: "beaker", lines: ["Water plant", "Lamp 40 cm away"] }] }, o: ["Carbon dioxide", "Water vapour", "Oxygen", "Nitrogen"], a: 2, lvl: 2, why: "During photosynthesis, the plant gives off oxygen. More light in A means faster photosynthesis and more oxygen bubbles." },
    { q: "Which shows the energy conversion in a torch when it is switched on?", o: ["Electrical energy → chemical potential energy → light and heat energy", "Light energy → electrical energy → chemical potential energy", "Chemical potential energy → light energy → electrical energy", "Chemical potential energy → electrical energy → light and heat energy"], a: 3, lvl: 2, why: "The batteries’ chemical potential energy becomes electrical energy in the circuit, which the bulb converts into light and heat energy." },
    { q: "A durian falls from a tree. Which statement about the durian as it falls is correct?", o: ["Its kinetic energy is converted into gravitational potential energy.", "Its gravitational potential energy is converted into kinetic energy.", "Its chemical potential energy is converted into kinetic energy.", "It gains gravitational potential energy."], a: 1, lvl: 2, why: "As it falls it loses height (less gravitational potential energy) and speeds up (more kinetic energy)." },
    { q: "Rahul pulls back the rubber band of a catapult and releases it. A stone flies forward. Which energy conversion happens when the rubber band is released?", o: ["Elastic potential energy → kinetic energy", "Kinetic energy → elastic potential energy", "Gravitational potential energy → elastic potential energy", "Chemical potential energy → elastic potential energy"], a: 0, lvl: 2, why: "The stretched band stores elastic potential energy; on release it is converted into kinetic energy of the band and stone." },
    { q: "Four identical water plants were placed at different distances from the same lamp. The graph shows the number of bubbles each gave off in 5 minutes. Which plant was most likely placed nearest to the lamp?", fig: { type: "bar", xl: "Plant", yl: "Number of bubbles in 5 minutes", bars: [["A", 12], ["B", 45], ["C", 30], ["D", 20]] }, o: ["A", "B", "C", "D"], a: 1, lvl: 2, why: "The nearest plant receives the most light, so it photosynthesises fastest and gives off the most oxygen bubbles: B (45)." },
    { q: "Study the food chain. Where did the energy in the snake originally come from?", fig: { type: "web", links: [["grass", "grasshopper"], ["grasshopper", "frog"], ["frog", "snake"]] }, o: ["The grass", "The frog", "The Sun", "The soil"], a: 2, lvl: 2, why: "The grass trapped light energy from the Sun to make food; this energy was passed along the chain. ‘Originally’ means the very first source, the Sun." },
    { q: "Why are coal, oil and natural gas called non-renewable sources of energy?", o: ["They give off a lot of heat and light energy when they are burnt.", "They are found deep underground and are hard to dig out.", "They are cheap to use and are used by most power stations.", "They take millions of years to form, so they will run out."], a: 3, lvl: 2, why: "Non-renewable means they cannot be replaced quickly. Being found underground or giving off heat does not make a source non-renewable." },
    { q: "Which of the following are needed for photosynthesis?\nA: water\nB: oxygen\nC: carbon dioxide\nD: light", o: ["A and C only", "A, C and D only", "B and D only", "A, B, C and D"], a: 1, lvl: 2, why: "Plants need water, carbon dioxide and light (plus chlorophyll). Oxygen is a product of photosynthesis, not a raw material." },
    { q: "Why is a plant kept in the dark for 2 to 3 days before a starch test experiment?", o: ["So that it makes more starch, which then shows up clearly in the iodine test", "So that its chlorophyll is destroyed and the leaves lose their green colour", "So that its leaves can take in more carbon dioxide once it is put in light", "So that old starch is used up, and any starch found was made during the experiment"], a: 3, lvl: 2, why: "Destarching removes old starch. In the dark the plant cannot make starch, and its chlorophyll is not destroyed." },
    { q: "Two destarched potted plants were set up as shown and left in sunlight for 6 hours. A leaf from each was tested with iodine solution. Which leaf or leaves turned blue-black?", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Sealed jar, sunlight", "Has substance that", "absorbs carbon dioxide"] }, { label: "B", icon: "jar", lines: ["Sealed jar, sunlight", "No such substance"] }] }, o: ["A only", "B only", "Both A and B", "Neither A nor B"], a: 1, lvl: 2, why: "In A, the carbon dioxide was absorbed, so the plant could not photosynthesise. B had carbon dioxide and light, so it made starch." },
    { q: "A calculator has a small solar panel. Which energy conversion takes place in the solar panel?", o: ["Light energy → electrical energy", "Electrical energy → light energy", "Heat energy → chemical potential energy", "Sound energy → electrical energy"], a: 0, lvl: 2, why: "A solar panel converts light energy from the Sun (or a room light) into electrical energy to run the calculator." },

    { q: "Three destarched plants were set up as shown for 6 hours. Neither P nor R made starch. What can be concluded by comparing ONLY set-ups P and R?", fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["In sunlight", "Has substance that", "absorbs carbon dioxide"] }, { label: "R", icon: "jar", lines: ["In the dark", "No such substance"] }, { label: "Q", icon: "jar", lines: ["In sunlight", "No such substance"] }] }, o: ["Light is needed for photosynthesis, as neither P nor R made starch.", "Carbon dioxide is needed for photosynthesis, as neither P nor R made starch.", "Both light and carbon dioxide are needed for photosynthesis to take place.", "Nothing about either factor, as P and R differ in both light and carbon dioxide."], a: 3, lvl: 3, why: "P and R differ in two variables (light and carbon dioxide), so the comparison is not fair and neither factor can be tested. To test light, compare Q and R; to test carbon dioxide, compare P and Q." },
    { q: "Using the same three set-ups P, Q and R, which leaves would turn blue-black when tested with iodine solution?", fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["In sunlight", "Has substance that", "absorbs carbon dioxide"] }, { label: "Q", icon: "jar", lines: ["In sunlight", "No such substance"] }, { label: "R", icon: "jar", lines: ["In the dark", "No such substance"] }] }, o: ["Q only", "P and Q only", "Q and R only", "P, Q and R"], a: 0, lvl: 3, why: "Only Q has both light and carbon dioxide. P has no carbon dioxide and R has no light, so neither can photosynthesise and make starch." },
    { q: "Study the graph from a water plant experiment. Based on the graph, about how many bubbles per minute would be given off if the lamp were 25 cm from the plant?", fig: { type: "line", title: "Bubbles given off by a water plant", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 48], ["20", 36], ["30", 24], ["40", 12], ["50", 6]] }, o: ["18", "24", "30", "42"], a: 2, lvl: 3, why: "25 cm is halfway between 20 cm (36) and 30 cm (24), so the value is about 30. 24 is the reading at 30 cm, not 25 cm." },
    { q: "Jun Wei set up two beakers as shown to find out how the distance of the lamp affects the rate of photosynthesis. To make it a fair test, which must be kept the same?\nA: type of water plant\nB: distance of the lamp\nC: temperature of the water\nD: number of bubbles given off", fig: { type: "setups", items: [{ label: "X", icon: "beaker", lines: ["Water plant", "Lamp 10 cm away"] }, { label: "Y", icon: "beaker", lines: ["Water plant", "Lamp 30 cm away"] }] }, o: ["A and C only", "B and D only", "A, B and C only", "A, C and D only"], a: 0, lvl: 3, why: "The distance is the variable being changed and the number of bubbles is what is measured. The type of plant and water temperature must be kept the same." },
    { q: "Aisha sits on a swing. She is released from X, the highest point on one side, swings down through Y, the lowest point, and up to Z on the other side. At which point does she have the most kinetic energy?", o: ["X", "Z", "Y", "X and Z equally"], a: 2, lvl: 3, why: "At Y she is moving fastest because gravitational potential energy has been converted into kinetic energy. At X and Z she stops for a moment, so her kinetic energy is lowest." },
    { q: "A ball was dropped onto the floor. The graph shows the height it reached after each bounce. Why does the ball bounce lower each time?", fig: { type: "bar", xl: "Bounce", yl: "Height reached (cm)", bars: [["Dropped from", 100], ["Bounce 1", 70], ["Bounce 2", 49], ["Bounce 3", 34]] }, o: ["The ball’s energy is destroyed bit by bit each time it hits the hard floor.", "Gravity becomes stronger after each bounce and pulls the ball down harder.", "The ball gains more gravitational potential energy each time it bounces up.", "Some energy is converted into heat and sound each time the ball hits the floor."], a: 3, lvl: 3, why: "Energy is never destroyed; at each bounce some is converted into heat and sound, so less is converted back into gravitational potential energy." },
    { q: "The flowchart classifies some sources of energy. Which of the following could be A, B and C?", fig: { type: "flow", root: "Energy sources", node: { q: "Renewable?", yes: { q: "Uses moving water?", yes: "A", no: "B" }, no: "C" } }, o: ["A: wind, B: solar, C: coal", "A: hydro, B: coal, C: solar", "A: solar, B: wind, C: natural gas", "A: hydro, B: wind, C: oil"], a: 3, lvl: 3, why: "A must be renewable and use moving water (hydro); B is renewable but not moving water (wind); C is non-renewable (oil). Wind does not use moving water, and coal is not renewable." },
    { q: "A car burns petrol to move. Where did the energy stored in the petrol originally come from?", o: ["Heat from deep inside the Earth", "The Sun", "The car’s battery", "The oil rig that drilled it"], a: 1, lvl: 3, why: "Petrol comes from oil, formed over millions of years from the remains of plants and animals. Their energy came from plants that trapped light energy from the Sun." },
    { q: "Four identical water plants were each placed 20 cm from a different lamp, W, X, Y and Z. All other conditions were the same. Study the graph. Which shows the lamps from the one giving the least light to the one giving the most light?", fig: { type: "bar", xl: "Lamp used", yl: "Bubbles per minute", bars: [["W", 8], ["X", 30], ["Y", 18], ["Z", 42]] }, o: ["Z, X, Y, W", "W, Y, X, Z", "W, X, Y, Z", "Y, W, Z, X"], a: 1, lvl: 3, why: "More light gives a faster rate of photosynthesis and more oxygen bubbles, so the order from fewest bubbles is W (8), Y (18), X (30), Z (42)." },
    { q: "Sam winds the key of a toy car, which tightens a spring inside. He then lets the car go and it moves across the floor. Which shows the energy conversions, starting from Sam’s body?", o: ["Chemical potential energy in Sam’s body → elastic potential energy in the spring → kinetic energy of the car", "Elastic potential energy in Sam’s body → chemical potential energy in the spring → kinetic energy of the car", "Kinetic energy of the car → elastic potential energy in the spring → chemical potential energy in Sam’s body", "Chemical potential energy in Sam’s body → kinetic energy of the car, with no energy stored in between"], a: 0, lvl: 3, why: "Sam uses energy from food (chemical potential) to wind the spring, which stores elastic potential energy. When released, this becomes kinetic energy of the car." },
    { q: "In an experiment, a destarched potted plant was sealed in a glass jar with a dish of a substance that absorbs carbon dioxide. What was the purpose of this substance?", o: ["To give the plant more oxygen for making food", "To keep the air in the jar warm for the plant", "To remove the carbon dioxide from the air in the jar", "To remove the starch from the leaves of the plant"], a: 2, lvl: 3, why: "The substance absorbs carbon dioxide, so the plant has no carbon dioxide for photosynthesis. Destarching is done by keeping the plant in the dark, not by this substance." },
    { q: "A leaf on a destarched variegated plant had some parts covered with aluminium foil. The plant was left in sunlight for 6 hours. Which part(s) of the leaf would turn blue-black?", tbl: [["Part", "Colour", "Covered with foil?"], ["1", "Green", "No"], ["2", "White", "No"], ["3", "Green", "Yes"], ["4", "White", "Yes"]], o: ["1 only", "1 and 2 only", "1 and 3 only", "1, 2 and 3 only"], a: 0, lvl: 3, why: "Only part 1 has both chlorophyll and light. Part 2 has no chlorophyll, part 3 has no light, and part 4 has neither." },

    { q: "A pond plant was kept outdoors and its bubbles were counted at different times of one sunny day. Which statements are correct?\nA: The light was probably brightest at about 1 pm.\nB: At 9 pm the plant was not photosynthesising.\nC: The plant was photosynthesising faster at 3 pm than at 9 am.\nD: The bubbles show that the plant takes in oxygen.", fig: { type: "line", title: "Bubbles from a pond plant", xl: "Time of day", yl: "Bubbles per minute", pts: [["7 am", 4], ["9 am", 18], ["11 am", 34], ["1 pm", 40], ["3 pm", 26], ["5 pm", 12], ["7 pm", 2], ["9 pm", 0]] }, o: ["A and B only", "A and C only", "A, B and C only", "B, C and D only"], a: 2, lvl: 4, why: "The most bubbles (40) at 1 pm point to the brightest light; no bubbles at 9 pm (dark) means no photosynthesis; 26 at 3 pm is more than 18 at 9 am. The bubbles are oxygen being GIVEN OFF, so D is wrong." },
    { q: "Four leaves on the same destarched plant were treated as shown and left in sunlight for 6 hours. Petroleum jelly blocks the tiny openings through which gases enter and leave a leaf, and this plant has openings on both leaf surfaces. Which leaves would contain starch?", fig: { type: "setups", items: [{ label: "W", icon: "plate", lines: ["Nothing applied"] }, { label: "X", icon: "plate", lines: ["Jelly on both surfaces"] }, { label: "Y", icon: "plate", lines: ["Black paper both sides"] }, { label: "Z", icon: "plate", lines: ["Jelly on upper surface", "only"] }] }, o: ["W only", "W and Z only", "W, X and Z only", "X and Y only"], a: 1, lvl: 4, why: "X cannot take in carbon dioxide and Y gets no light, so neither makes starch. Z still takes in carbon dioxide through the openings on its lower surface, so like W it photosynthesises." },
    { q: "A ball is released from rest at P on a track and rolls along it. The table shows the heights of some points on the track. Which point can the ball definitely NOT reach?", tbl: [["Point", "Height above ground (cm)"], ["P (start)", "80"], ["Q", "0"], ["R", "50"], ["S", "75"], ["T", "90"]], o: ["Q", "R", "S", "T"], a: 3, lvl: 4, why: "The ball starts with the gravitational potential energy it has at 80 cm, and some energy is converted into heat and sound as it rolls. It can never gain more gravitational potential energy than it started with, so it cannot rise to 90 cm." },
    { q: "Four destarched plants were set up as shown for 6 hours. Mei concluded that both light and carbon dioxide are needed for photosynthesis. Which two comparisons support her conclusion?", fig: { type: "setups", items: [{ label: "J", icon: "jar", lines: ["In sunlight", "Has substance that", "absorbs carbon dioxide"] }, { label: "K", icon: "jar", lines: ["In sunlight", "No such substance"] }, { label: "L", icon: "jar", lines: ["In the dark", "Has substance that", "absorbs carbon dioxide"] }, { label: "M", icon: "jar", lines: ["In the dark", "No such substance"] }] }, o: ["J with K, and K with M", "J with L, and K with M", "J with K, and L with M", "K with L, and J with M"], a: 0, lvl: 4, why: "Only K makes starch. J vs K changes only carbon dioxide (both in light); K vs M changes only light (both have carbon dioxide). J vs L and L vs M compare two set-ups that both make no starch, and K vs L changes two variables." },
    { q: "A solar-powered pump in a garden shoots a jet of water up into the air. Which shows the main energy conversions, from the sunlight to the water at the top of the jet?", o: ["Light energy → kinetic energy → electrical energy → gravitational potential energy", "Heat energy → electrical energy → gravitational potential energy → kinetic energy", "Light energy → electrical energy → gravitational potential energy → kinetic energy", "Light energy → electrical energy → kinetic energy → gravitational potential energy"], a: 3, lvl: 4, why: "The solar panel converts light into electrical energy, the pump makes the water move (kinetic), and as the water rises it slows down, its kinetic energy becoming gravitational potential energy at the top." },
    { q: "Ravi obtained the results shown. His friend says the extra bubbles might be caused by the heat from the lamp, not the light. Which extra set-up would best test his friend’s idea?", fig: { type: "line", title: "Ravi’s results", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 36], ["20", 25], ["30", 15], ["40", 8]] }, o: ["Repeat the experiment with a different type of water plant and count the bubbles.", "In the dark, give the plant the same heat as the lamp at 10 cm using a heater, and count the bubbles.", "Count the bubbles for 10 minutes instead of 1 minute at each distance from the lamp.", "Use a bigger beaker holding more water, with the lamp at the same distances."], a: 1, lvl: 4, why: "To separate heat from light, give the plant the same heat with no light. If few or no bubbles appear, light (not heat) caused the increase. The other options do not separate heat from light." }
  ],
  tf: [
    { s: "Green plants use light energy to make their own food.", a: true, why: "Chlorophyll absorbs light energy, which is used to make sugar from carbon dioxide and water." },
    { s: "Plants get their food from the soil through their roots.", a: false, why: "Plants make their own food by photosynthesis. Roots absorb water and mineral salts, not food." },
    { s: "During photosynthesis, plants give off carbon dioxide.", a: false, why: "Plants take in carbon dioxide and give off oxygen during photosynthesis." },
    { s: "Chlorophyll is found in the chloroplasts of plant cells.", a: true, why: "Chloroplasts contain chlorophyll, which absorbs light energy." },
    { s: "The white parts of a variegated leaf can make starch because they receive light.", a: false, why: "The white parts have no chlorophyll, so they cannot photosynthesise even in light." },
    { s: "Iodine solution turns blue-black when starch is present.", a: true, why: "Brown iodine solution turns blue-black with starch and stays brown without it." },
    { s: "A plant is destarched by placing it in bright sunlight for two days.", a: false, why: "It is destarched by keeping it in the dark, so it uses up its stored starch." },
    { s: "A stretched rubber band has elastic potential energy.", a: true, why: "Energy is stored in objects that are stretched or compressed." },
    { s: "A book resting on a high shelf has no energy because it is not moving.", a: false, why: "It has no kinetic energy but it has gravitational potential energy because of its height." },
    { s: "The energy stored in coal originally came from the Sun.", a: true, why: "Coal formed from the remains of plants, which had trapped light energy from the Sun." },
    { s: "When a bouncing ball finally stops, its energy has been destroyed.", a: false, why: "Energy cannot be destroyed; it has been converted mainly into heat and sound energy." },
    { s: "A torch converts chemical potential energy into electrical energy, then into light and heat energy.", a: true, why: "The batteries store chemical potential energy; the bulb gives out light and some heat." },
    { s: "Solar energy is a non-renewable source of energy.", a: false, why: "Solar energy is renewable: sunlight reaches Earth every day and will not run out." },
    { s: "Moving a lamp closer to a water plant usually increases the number of bubbles it gives off per minute.", a: true, why: "More light reaches the plant, so the rate of photosynthesis increases and more oxygen is given off." },
    { s: "Animals are food producers because they find food for their young.", a: false, why: "Animals cannot make their own food; they are consumers. Only plants are food producers." },
    { s: "Plants are called food producers because they make their own food.", a: true, why: "Plants make food by photosynthesis, and this food passes along food chains." },
    { s: "Natural gas is a renewable source of energy.", a: false, why: "Natural gas is a fossil fuel that took millions of years to form and will run out." },
    { s: "Water stored high up behind a dam has gravitational potential energy.", a: true, why: "It has energy because of its height; this is converted into kinetic energy as it flows down." },
    { s: "At the same height, a heavier object has less gravitational potential energy than a lighter one.", a: false, why: "At the same height, the heavier object has MORE gravitational potential energy." },
    { s: "Food contains chemical potential energy.", a: true, why: "Energy is stored in food and released when it is broken down in the body." }
  ],
  sort: [
    { title: "Sort these sources of energy into renewable and non-renewable", groups: ["Renewable", "Non-renewable"], items: [["sunlight", 0], ["wind", 0], ["moving water in a river", 0], ["waves at sea", 0], ["coal", 1], ["crude oil", 1], ["natural gas", 1], ["petrol", 1]] },
    { title: "Sort by the main form of energy each has or stores", groups: ["Kinetic", "Gravitational potential", "Elastic potential", "Chemical potential"], items: [["a moving MRT train", 0], ["a rolling ball", 0], ["a rock at the edge of a cliff", 1], ["water in a rooftop tank", 1], ["a stretched rubber band", 2], ["a compressed spring", 2], ["a plate of chicken rice", 3], ["a battery", 3], ["a tank of petrol", 3]] },
    { title: "Photosynthesis: is it needed, produced, or neither?", groups: ["Needed", "Produced", "Neither"], items: [["light energy", 0], ["carbon dioxide", 0], ["water", 0], ["chlorophyll", 0], ["sugar", 1], ["oxygen", 1], ["soil", 2], ["iodine", 2], ["nitrogen", 2]] }
  ],
  oe: [
    { q: "Plants are called food producers. Explain why.", marks: 2, kw: [["make", "produc", "photosynth"], ["light", "sun"]], model: "Plants make their own food by photosynthesis. Their chlorophyll absorbs light energy from the Sun to make sugar from carbon dioxide and water." },
    { q: "A destarched plant had part of one leaf covered on both sides with black paper, as shown. After 6 hours in sunlight, the leaf was tested with iodine solution.\n(a) State the colour of the iodine solution on part X and on part Y. [2]\n(b) Explain the result for part Y. [2]", fig: { type: "setups", items: [{ label: "X", icon: "plate", lines: ["Uncovered part", "of the leaf"] }, { label: "Y", icon: "plate", lines: ["Part covered with", "black paper"] }] }, marks: 4, kw: [["blue"], ["brown"], ["no light", "not receive light", "not get light", "no sunlight", "block", "not reach", "did not receive"], ["no photosynthesis", "not photosynthes", "could not make", "cannot make", "not make", "no starch", "no food", "unable to photosynthes"]], model: "(a) Part X turned blue-black and part Y remained brown. (b) The black paper blocked light, so part Y received no light. It could not photosynthesise and make food, so no starch was made in part Y." },
    { q: "Study the graph from an experiment with a water plant.\n(a) Describe how the distance of the lamp affects the number of bubbles per minute. [1]\n(b) Name the gas in the bubbles. [1]\n(c) Explain why fewer bubbles are given off when the lamp is further away. [2]", fig: { type: "line", title: "Bubbles given off by a water plant", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 44], ["20", 31], ["30", 20], ["40", 12], ["50", 7]] }, marks: 4, kw: [["decrease", "fewer", "less bubbles", "drops", "falls"], ["oxygen"], ["less light", "dimmer", "weaker light", "lower light", "light intensity is lower", "light intensity decreas", "lower intensity"], ["slower", "lower rate", "less photosynthesis", "rate of photosynthesis decreas", "photosynthesises less", "photosynthesise less"]], model: "(a) As the distance of the lamp increases, the number of bubbles per minute decreases. (b) Oxygen. (c) When the lamp is further away, less light reaches the plant, so photosynthesis is slower and less oxygen is given off." },
    { q: "Two destarched potted plants were set up as shown and placed in sunlight for 6 hours. A leaf from each plant was then tested with iodine solution. Only the leaf from B turned blue-black.\n(a) Explain why the leaf from A did not turn blue-black. [2]\n(b) What is the purpose of set-up B? [1]\n(c) What can you conclude from this experiment? [1]", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Sealed jar", "Has substance that", "absorbs carbon dioxide"] }, { label: "B", icon: "jar", lines: ["Sealed jar", "No such substance"] }] }, marks: 4, kw: [["absorb", "remov"], ["could not photosynthes", "cannot photosynthes", "no photosynthesis", "not photosynthes", "unable to photosynthes", "could not make", "cannot make", "not make", "no food", "no starch"], ["compar", "control"], ["carbon dioxide is needed", "carbon dioxide is necessary", "needs carbon dioxide", "need carbon dioxide", "carbon dioxide is required", "requires carbon dioxide"]], model: "(a) The substance absorbed the carbon dioxide in jar A, so the plant had no carbon dioxide. It could not photosynthesise, so no starch was made. (b) It is the control, used to compare with A so that only the presence of carbon dioxide is different. (c) Carbon dioxide is needed for photosynthesis." },
    { q: "A destarched plant with variegated leaves had one leaf partly covered with black paper and was left in sunlight for 6 hours. The table describes three parts of the leaf.\n(a) Which part(s) turned blue-black with iodine solution? [1]\n(b) Which two parts should be compared to show that chlorophyll is needed for photosynthesis? [1]\n(c) What does comparing parts 1 and 3 show? [1]", tbl: [["Part", "Colour of part", "Covered with black paper?"], ["1", "Green", "No"], ["2", "White", "No"], ["3", "Green", "Yes"]], marks: 3, kw: [["only part 1", "part 1 only", "only 1", "1 only"], ["1 and 2", "2 and 1", "part 1 and part 2", "part 2 and part 1"], ["light is needed", "needs light", "need light", "light is necessary", "light is required", "requires light"]], model: "(a) Only part 1. (b) Parts 1 and 2, because they both receive light and differ only in having chlorophyll. (c) It shows that light is needed for photosynthesis." },
    { q: "A ball is released from X at the top of a curved track. It rolls down to Y, the lowest point, and up the other side, stopping at Z, which is lower than X.\n(a) What form of energy does the ball have at X? [1]\n(b) State the energy conversion as the ball rolls from X to Y. [1]\n(c) Explain why the ball stops at Z, lower than X. [1]", marks: 3, kw: [["gravitational"], ["kinetic"], ["heat", "sound", "friction"]], model: "(a) Gravitational potential energy. (b) Its gravitational potential energy is converted into kinetic energy. (c) As it rolls, some of its energy is converted into heat and sound energy, so less energy can be converted back into gravitational potential energy and it cannot rise as high as X." },
    { q: "A hydroelectric power station uses water stored high up behind a dam. The water flows down and turns turbines to produce electricity.\n(a) What form of energy does the stored water have? [1]\n(b) What form of energy is produced by the power station? [1]\n(c) Explain why hydro energy is a renewable source of energy. [1]", marks: 3, kw: [["gravitational"], ["electrical", "electricity"], ["will not run out", "not run out", "replaced", "renewed", "used again", "replenish"]], model: "(a) Gravitational potential energy. (b) Electrical energy. (c) The water is replaced naturally by rain, so the source will not run out." },
    { q: "Mrs Tan cooks noodles on a stove that burns natural gas. Explain how the energy used to cook the noodles can be traced back to the Sun.", marks: 3, x: 1, kw: [["photosynth", "light energy", "make food", "made food", "made their own food"], ["remains", "dead", "died", "buried", "millions of years"], ["heat"]], model: "Long ago, plants used light energy from the Sun to make food by photosynthesis, and animals ate the plants. When they died, their remains were buried and, over millions of years, formed natural gas that stores chemical potential energy. Burning the gas converts this energy into heat energy that cooks the noodles." },
    { q: "Siti placed a water plant under different numbers of identical lamps, all at the same distance. The graph shows her results.\n(a) Describe the relationship between the number of lamps and the number of bubbles. [1]\n(b) Explain this relationship. [2]\n(c) State one variable Siti must keep the same. [1]", fig: { type: "bar", xl: "Number of lamps", yl: "Bubbles per minute", bars: [["1", 10], ["2", 19], ["3", 27], ["4", 33]] }, marks: 4, kw: [["increase", "more"], ["more light", "brighter", "light intensity increas", "higher light", "stronger light"], ["faster", "higher rate", "more photosynthesis", "rate of photosynthesis increas", "photosynthesises more", "photosynthesise more"], ["distance", "type of plant", "same plant", "size of plant", "temperature", "amount of water", "volume of water", "number of leaves"]], model: "(a) As the number of lamps increases, the number of bubbles per minute increases. (b) More lamps give more light to the plant, so it photosynthesises faster and gives off more oxygen. (c) The distance of the lamps from the plant (or the type of plant, or the temperature of the water)." },
    { q: "Study the food chain.\n(a) Which organism is the food producer? Explain why. [2]\n(b) The bird does not eat plants. Explain why the bird still depends on the Sun for its energy. [2]", fig: { type: "web", links: [["grass", "grasshopper"], ["grasshopper", "bird"]] }, marks: 4, kw: [["grass"], ["make", "produc", "photosynth"], ["light", "sun"], ["eat", "feed", "pass"]], model: "(a) The grass, because it makes its own food by photosynthesis. (b) The grass uses light energy from the Sun to make food. The grasshopper eats the grass and the bird eats the grasshopper, so energy from the Sun is passed along the food chain to the bird." },
    { q: "Many HDB blocks in Singapore now have solar panels on their rooftops. Give two advantages of using solar energy instead of burning natural gas to produce electricity.", marks: 2, kw: [["renewable", "will not run out", "not run out"], ["less pollution", "pollut", "no pollution", "fewer harmful", "less harmful", "cleaner"]], model: "Solar energy is renewable and will not run out, while natural gas is non-renewable. Using solar panels also causes less pollution because no fuel is burnt, so fewer harmful gases are released into the air." },
    { q: "Ben wants to show that a leaf needs light to make starch.\n(a) How should he destarch his plant before the experiment? [1]\n(b) Why must the plant be destarched? [1]\n(c) What should he add to the leaf to test for starch? [1]", marks: 3, kw: [["dark"], ["remove", "used up", "use up", "get rid", "during the experiment"], ["iodine"]], model: "(a) Keep the plant in a dark place, such as a cupboard, for 2 to 3 days. (b) To remove the starch already in its leaves, so any starch found must have been made during the experiment. (c) Iodine solution; it turns blue-black if starch is present." },
    { q: "Two leaves on the same destarched plant were treated as shown and left in sunlight for 6 hours. Petroleum jelly blocks the tiny openings on the leaf surface through which gases enter and leave. Only leaf A turned blue-black with iodine solution.\n(a) Leaf B had chlorophyll and received light. Explain why it did not contain starch. [2]\n(b) This plant has tiny openings on both leaf surfaces. Predict the result of the iodine test if petroleum jelly was applied only on the upper surface of a leaf, and explain. [2]", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Nothing applied"] }, { label: "B", icon: "plate", lines: ["Petroleum jelly on", "both surfaces"] }] }, marks: 4, x: 1, kw: [["block", "cannot enter", "could not enter", "unable to enter", "prevent", "not enter"], ["carbon dioxide"], ["blue"], ["lower surface", "underside", "bottom surface", "other surface", "lower"]], model: "(a) The petroleum jelly blocked the tiny openings, so carbon dioxide could not enter the leaf. Without carbon dioxide, the leaf could not photosynthesise and make starch. (b) The leaf would turn blue-black, because carbon dioxide can still enter through the openings on the lower surface, so it can still photosynthesise and make starch." },
    { q: "Ravi obtained the results shown. His friend says the extra bubbles at 10 cm might be caused by the heat from the lamp, not the light.\n(a) Describe an extra set-up Ravi could use to test his friend’s idea. [2]\n(b) What does the number of bubbles per minute measure in this experiment? [1]", fig: { type: "line", title: "Ravi’s results", xl: "Distance of lamp from plant (cm)", yl: "Bubbles per minute", pts: [["10", 36], ["20", 25], ["30", 15], ["40", 8]] }, marks: 3, x: 1, kw: [["heater", "heat source", "same heat", "same amount of heat", "same temperature"], ["dark", "no light"], ["rate of photosynthesis", "how fast", "oxygen"]], model: "(a) Place an identical plant in a dark room with a heater that gives the same amount of heat as the lamp at 10 cm, but no light, and count the bubbles per minute. If there are few or no bubbles, the light, not the heat, caused the extra bubbles. (b) It measures the rate of photosynthesis (how fast oxygen is given off)." }
  ],
  doc: [
    { q: "A leaf was partly covered with black paper. Explain why the covered part did not turn blue-black with iodine solution.", marks: 2, answers: ["Because it was covered.", "The covered part did not receive light, so it could not photosynthesise and make starch.", "The covered part had no chlorophyll, so it could not make food."], best: 1, why: "Answer 2 names the missing factor (light) and links it to no photosynthesis and no starch. Answer 1 only repeats the question. Answer 3 gives the wrong reason: the covered part still has chlorophyll." },
    { q: "Explain why a water plant gives off more bubbles when a lamp is moved closer to it.", marks: 2, answers: ["The lamp is nearer to the plant.", "The plant gets warmer, so it grows faster.", "More light reaches the plant, so its rate of photosynthesis increases and more oxygen is given off."], best: 2, why: "Answer 3 links closer lamp → more light → faster photosynthesis → more oxygen. Answer 1 repeats the question. Answer 2 uses heat and growth instead of light and photosynthesis." },
    { q: "Explain how the energy in a plate of rice can be traced back to the Sun.", marks: 2, answers: ["Rice plants used light energy from the Sun to make food by photosynthesis, and this energy is stored as chemical potential energy in the rice.", "The rice is cooked using heat.", "Plants need the Sun to grow."], best: 0, why: "Answer 1 says the rice plant trapped light energy by photosynthesis and stored it in the rice. Answer 2 is about cooking, not where the energy in the food came from. Answer 3 is too vague: it does not mention light energy or making food." },
    { q: "A ball dropped onto the floor bounces lower each time. Explain why.", marks: 2, answers: ["The ball loses its energy.", "Each time the ball hits the floor, some of its energy is converted into heat and sound energy, so less is converted back into gravitational potential energy.", "The energy is used up."], best: 1, why: "Answer 2 names the forms the energy is converted into and links this to the lower height. Answers 1 and 3 suggest energy disappears, which is wrong: energy is converted, not lost or used up." },
    { q: "Why is coal a non-renewable source of energy?", marks: 2, answers: ["It takes millions of years to form, so it will run out once it is used up.", "It is black and burns easily.", "It pollutes the air when burnt."], best: 0, why: "Answer 1 gives the reason it cannot be replaced (millions of years to form) and the result (it will run out). Answer 2 describes coal but not why it is non-renewable. Answer 3 is true but is a disadvantage, not the meaning of non-renewable." }
  ]
};
