window.LB = window.LB || {};
LB["p6-forces"] = {
  notes: [
    { h: "A force is a push or a pull", t: "A force is a push or a pull. We cannot see a force, but we can see its effects on objects. Pushing a trolley at NTUC, pulling open a drawer and kicking a ball all involve forces.", kw: ["a force is a push or a pull", "effects of a force"] },
    { h: "Effects of a force", t: "A force can move a stationary object, speed up a moving object, slow down a moving object or stop it. A force can also change the direction of a moving object. A force can change the shape of an object, such as when you squeeze a sponge or stretch a rubber band.", kw: ["move a stationary object", "speed up", "slow down", "stop", "change the direction", "change the shape"] },
    { h: "Measuring forces", t: "Forces are measured in newtons (N). A spring balance is used to measure force: the spring inside stretches when a force pulls on the hook, and the pointer shows the size of the force on the scale. The greater the force, the more the spring stretches and the higher the reading.", kw: ["newtons", "spring balance", "the greater the force, the more the spring stretches"] },
    { h: "Gravitational force and weight", t: "Gravitational force is the pull of the Earth on all objects. It pulls objects towards the Earth, which is why a ball thrown upwards slows down, stops and falls back. The weight of an object is the gravitational force acting on it, measured in newtons with a spring balance.", kw: ["gravitational force", "pulls objects towards the earth", "weight is the gravitational force", "newtons"] },
    { h: "Mass and weight are different", t: "Mass is the amount of matter in an object and is measured in grams (g) or kilograms (kg). Weight is a force — the gravitational force on the object — and is measured in newtons (N). An object with a greater mass has a greater weight on Earth.", kw: ["mass is the amount of matter", "grams", "weight is a force", "newtons"] },
    { h: "Frictional force", t: "Frictional force (friction) is a force that opposes motion between two surfaces in contact. It acts in the opposite direction to the way the object is moving (or trying to move). Friction slows down and stops moving objects, such as a ball rolling on a field.", kw: ["opposes motion", "surfaces in contact", "opposite direction"] },
    { h: "Rougher surfaces, more friction", t: "The rougher the surfaces in contact, the greater the friction between them. A toy car rolling off the same ramp travels a shorter distance on carpet than on glass, because the rougher carpet exerts more friction on it. Smoother surfaces such as glass or polished floors exert less friction.", kw: ["rougher surface", "greater the friction", "shorter distance", "smoother surface", "less friction"] },
    { h: "Friction: heat and wear", t: "Friction produces heat: rubbing your palms together makes them warm. Friction also wears away surfaces, so shoe soles, tyres and brake pads become thinner over time. This is why moving parts of machines get hot and wear out.", kw: ["friction produces heat", "wears away surfaces"] },
    { h: "Useful and not useful friction", t: "Friction is useful when it lets us walk without slipping, lets tyres grip the road, helps brakes slow down and stop a bicycle, and lets us write and hold things. Friction is not useful when it wears out moving parts, produces unwanted heat in machines, and makes it harder to move objects so more energy is needed.", kw: ["useful", "grip", "brakes", "wears out", "unwanted heat"] },
    { h: "Increasing and reducing friction", t: "To increase friction: use rougher surfaces, treads on tyres and shoe soles, rubber grips, and sand on slippery paths. To reduce friction: use lubricants such as oil and grease, ball bearings or rollers, wheels, and smooth or polished surfaces. A lubricant forms a layer between the surfaces so they do not rub directly against each other.", kw: ["treads", "rubber grips", "lubricants", "oil", "ball bearings", "polished"] },
    { h: "Elastic spring force", t: "A stretched or compressed spring exerts an elastic spring force that acts to return it to its original length. A stretched spring pulls back, and a compressed spring pushes back. Springs and rubber bands are used in spring balances, mattresses, staplers, pens, trampolines and catapults.", kw: ["elastic spring force", "stretched", "compressed", "original length"] },
    { h: "Extension, graphs and elastic limit", t: "Extension = stretched length − original length. As the load on a spring increases, its extension increases; for many springs the extension increases by the same amount for each equal load added, giving a straight-line graph. If a spring is stretched beyond its elastic limit, it will not return to its original length when the load is removed. Magnetic force and gravitational force can act without contact (non-contact forces), while friction and spring forces need contact.", kw: ["extension", "stretched length", "original length", "elastic limit", "non-contact force"] }
  ],
  traps: [
    "‘Extension is the length of the spring’ → extension = stretched length − ORIGINAL length. A 10 cm spring stretched to 16 cm has an extension of 6 cm, not 16 cm.",
    "‘A moving object stops because its force is used up’ → it stops because FRICTION (an opposing force) acts on it.",
    "‘Weight is measured in kilograms’ → MASS is in g or kg; WEIGHT is a force, measured in newtons (N) with a spring balance.",
    "‘Friction acts in the direction of motion’ → friction always OPPOSES motion, acting in the opposite direction.",
    "‘Friction is always bad’ → friction is useful for walking, gripping, braking and writing; it is only unwanted when it wears parts or wastes energy as heat.",
    "‘Treads reduce friction so the car goes faster’ → treads INCREASE friction so tyres grip the road, especially when wet.",
    "‘Gravity only acts on falling objects’ → gravitational force acts on ALL objects all the time, even one resting on a table or hanging on a spring.",
    "‘A spring always returns to its original length’ → only if it is not stretched beyond its elastic limit."
  ],
  lessons: [
    {
      h: "Spring tables: length vs extension",
      concept: "Many marks are lost by confusing LENGTH with EXTENSION. Extension = stretched length − original length (the length with no load). Always find the original length first (load 0 g), then subtract. On an extension graph, the line starts at 0; on a length graph, it starts at the original length. If equal loads give equal extensions, use that pattern to predict.",
      example: {
        q: "A spring was hung with different loads. The table shows the length of the spring.\n(a) What is the extension when a 150 g load is hung? [1]\n(b) Predict the length of the spring with a 250 g load. [1]",
        tbl: [["Load (g)", "0", "50", "100", "150", "200"], ["Length of spring (cm)", "12", "15", "18", "21", "24"]],
        marks: 2,
        think: [
          "Step 1: Original length (0 g) = 12 cm.",
          "Step 2: (a) Extension with 150 g = 21 − 12 = 9 cm.",
          "Step 3: Each 50 g adds 3 cm. From 200 g to 250 g is one more 50 g, so the length becomes 24 + 3 = 27 cm.",
          "Step 4: Check: extension with 250 g = 5 × 3 = 15 cm, and 12 + 15 = 27 cm."
        ],
        answer: "(a) 9 cm. (b) 27 cm (assuming the spring is not stretched beyond its elastic limit)."
      },
      tip: "Write ‘extension = length − original length’ in your working. Reading 21 cm straight off the table as the extension is the classic mistake.",
      try: {
        q: "The graph shows the extension of a spring with different loads. The spring’s original length is 8 cm. What is the LENGTH of the spring with a 300 g load?",
        fig: { type: "line", title: "Extension of a spring", xl: "Mass of load (g)", yl: "Extension (cm)", pts: [["0", 0], ["100", 2], ["200", 4], ["300", 6], ["400", 8]] },
        o: ["6 cm", "8 cm", "14 cm", "16 cm"],
        a: 2,
        why: "The extension at 300 g is 6 cm, so the length = 8 + 6 = 14 cm. 6 cm is only the extension; 16 cm is the length at 400 g."
      }
    },
    {
      h: "Explaining friction results",
      concept: "When asked why an object travelled a shorter or longer distance on a surface, give the full chain: surface (rougher/smoother) → more/less FRICTION → friction opposes motion and slows the object down more/less → shorter/longer distance. Always use the word ‘friction’ and compare (more/less, greatest/least). ‘The carpet is rough’ alone usually scores zero.",
      example: {
        q: "A toy car was released from the same height on the same ramp onto four different surfaces. The graph shows how far it travelled. Explain why the car travelled the shortest distance on the rubber mat. [2]",
        fig: { type: "bar", title: "Distance travelled by toy car", xl: "Surface", yl: "Distance travelled (cm)", bars: [["Glass", 150], ["Wood", 110], ["Rubber mat", 35], ["Cloth", 70]] },
        marks: 2,
        think: [
          "Step 1: Read the graph: rubber mat gives the shortest distance (35 cm).",
          "Step 2: Shortest distance means the greatest opposing force acted on the car — that is friction.",
          "Step 3: Link it: rubber mat exerted the most friction → slowed the car down the most → stopped soonest."
        ],
        answer: "The rubber mat exerted the greatest frictional force on the car. Friction opposes motion, so the car was slowed down the most and stopped after the shortest distance."
      },
      tip: "Use the comparison words: ‘greatest friction’ → ‘slowed down the most’ → ‘shortest distance’.",
      try: {
        q: "Using the same graph as above, which is the best explanation for why the car travelled the furthest on glass?",
        o: ["Glass is the heaviest surface, so it pulled the car forward the most.", "Glass pushed the car forward with a greater force than the other surfaces.", "Glass is the smoothest, so it exerted the least friction to slow the car down.", "There is no gravitational force on glass, so nothing slowed the car down."],
        a: 2,
        why: "Glass is smoothest → least friction → least slowing → furthest distance. Surfaces do not push cars forward; friction always opposes motion."
      }
    },
    {
      h: "Fair tests with ramps and springs",
      concept: "To test ONE variable (e.g. type of surface), compare set-ups where only that variable is different and everything else is the same: same car, same ramp height, same starting point, same way of releasing. If two things change, you cannot tell which one caused the result. In spring experiments, keep the same spring and change only the load.",
      example: {
        q: "Rahul wants to find out if the height of the ramp affects how far a toy car travels. Which two set-ups should he use? Explain. [2]",
        fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Ramp height: 20 cm", "Surface: carpet", "Car: 100 g"] }, { label: "B", icon: "box", lines: ["Ramp height: 20 cm", "Surface: wood", "Car: 100 g"] }, { label: "C", icon: "box", lines: ["Ramp height: 40 cm", "Surface: wood", "Car: 100 g"] }, { label: "D", icon: "box", lines: ["Ramp height: 40 cm", "Surface: carpet", "Car: 200 g"] }] },
        marks: 2,
        think: [
          "Step 1: The variable to change is ramp height. Look for pairs with different heights.",
          "Step 2: A and D: height, AND car mass differ — not fair. A and C: height AND surface differ — not fair.",
          "Step 3: B and C: only the height differs (both wood, both 100 g) — fair."
        ],
        answer: "B and C. Only the height of the ramp is different; the surface and the mass of the car are kept the same, so any difference in distance is caused by the height."
      },
      tip: "Tick off each variable in a pair. Exactly ONE difference = fair test.",
      try: {
        q: "Using the same set-ups, which two set-ups show whether the type of surface affects the distance travelled?",
        o: ["A and D", "B and D", "A and B", "C and D"],
        a: 2,
        why: "A and B differ only in surface (carpet vs wood); height and car mass are the same. C and D differ in surface AND car mass."
      }
    },
    {
      h: "Naming the forces on an object",
      concept: "Name forces with their full names and directions. Gravitational force acts on every object, pulling it DOWN towards the Earth, even when it is not moving. A stretched spring pulls; a compressed spring pushes. Magnets can attract or repel without touching. Friction acts OPPOSITE to motion. When an object is at rest, the upward force (spring, magnetic) balances the downward gravitational force.",
      example: {
        q: "Ring magnet B floats above ring magnet A on a wooden rod, as shown. Name the two forces acting on ring B and state their directions. [2]",
        fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "S" }], gaps: [true] },
        marks: 2,
        think: [
          "Step 1: The top of A is N; the bottom of B is N (opposite of its top S). Like poles face each other → repel.",
          "Step 2: Repulsion pushes B upwards — magnetic force.",
          "Step 3: The Earth pulls B downwards — gravitational force. B stays still because the two forces balance."
        ],
        answer: "Magnetic force (repulsion from A) acts upwards on B, and gravitational force acts downwards on B."
      },
      tip: "Never write just ‘gravity pushes it’ — gravitational force PULLS objects towards the Earth.",
      try: {
        q: "A bag of rice hangs at rest from a spring balance. Which pair of forces acts on the bag?",
        o: ["Frictional force upwards, gravitational force downwards", "Elastic spring force upwards, gravitational force downwards", "Elastic spring force downwards, magnetic force upwards", "Gravitational force upwards, frictional force downwards"],
        a: 1,
        why: "The stretched spring pulls the bag up; the Earth pulls it down. No surfaces are rubbing, so there is no friction."
      }
    },
    {
      h: "Explaining how to increase or reduce friction",
      concept: "A full answer says WHAT is done, WHAT it does to friction and WHY that helps. Treads/studs/rubber grips → increase friction → better grip, less slipping. Oil/grease → forms a layer between the surfaces → reduces friction → parts move more easily, less wear and heat. Ball bearings → roll instead of rub → reduce friction. Always name the two surfaces in contact.",
      example: {
        q: "A cyclist puts oil on the chain of his bicycle. Explain how this helps. [2]",
        marks: 2,
        think: [
          "Step 1: Oil is a lubricant.",
          "Step 2: It reduces friction between the moving parts of the chain (and gears).",
          "Step 3: So pedalling is easier, and the parts wear out less and produce less heat."
        ],
        answer: "Oil reduces friction between the moving parts of the chain and the gears, so the chain moves more easily and the parts wear out more slowly."
      },
      tip: "‘It makes it smooth’ is too vague. Say ‘reduces friction between ___ and ___, so …’.",
      try: {
        q: "Why do badminton shoes have rubber soles with grooves?",
        o: ["To reduce friction so the player can slide quickly across the court", "To make the shoes lighter so the player can move and jump faster", "To reduce the gravitational force on the player so they jump higher", "To increase friction with the floor so the player does not slip"],
        a: 3,
        why: "Rubber and grooves increase friction between the soles and the court floor, giving grip for quick stops and turns."
      }
    }
  ],
  mcq: [
    { q: "Which of the following best describes a force?", o: ["A form of energy stored in an object", "A push or a pull", "The amount of matter in an object", "How fast an object is moving"], a: 1, why: "A force is a push or a pull. Mass is the amount of matter; energy and speed are different quantities.", lvl: 1 },
    { q: "In which unit is force measured?", o: ["Gram (g)", "Centimetre (cm)", "Kilogram (kg)", "Newton (N)"], a: 3, why: "Force, including weight, is measured in newtons (N). Grams and kilograms are units of mass.", lvl: 1 },
    { q: "Which instrument is used to measure the weight of an object in newtons?", o: ["Spring balance", "Measuring cylinder", "Thermometer", "Metre rule"], a: 0, why: "A spring balance measures force; its spring stretches more with a greater pull.", lvl: 1 },
    { q: "Siti dropped her EZ-Link card and it fell to the floor. Which force made the card fall?", o: ["Frictional force", "Elastic spring force", "Gravitational force", "Magnetic force"], a: 2, why: "Gravitational force pulls all objects towards the Earth.", lvl: 1 },
    { q: "Which statement about frictional force is correct?", o: ["It acts only on objects moving through water.", "It opposes motion between two surfaces in contact.", "It acts only on metal objects.", "It acts in the same direction as the moving object."], a: 1, why: "Friction acts between surfaces in contact and always opposes motion.", lvl: 1 },
    { q: "Which of these REDUCES friction?", o: ["Adding treads to shoe soles", "Sprinkling sand on a slippery path", "Putting oil on a squeaky door hinge", "Using rubber grips on handlebars"], a: 2, why: "Oil is a lubricant that reduces friction. The other three increase friction.", lvl: 1 },
    { q: "Which force can act on an object without touching it?", o: ["Magnetic force", "Frictional force", "Elastic spring force", "The push of a hand"], a: 0, why: "A magnet can attract an iron object from a distance — a non-contact force. Friction, spring forces and pushes need contact.", lvl: 1 },
    { q: "Ali squeezed a ball of plasticine and it became flat. Which effect of a force does this show?", o: ["A force can speed up an object.", "A force can change the direction of an object.", "A force can stop a moving object.", "A force can change the shape of an object."], a: 3, why: "The plasticine did not move off; its shape changed.", lvl: 1 },

    { q: "Meiling released a toy car from the same height on the same ramp onto four different surfaces, P, Q, R and S. The graph shows the distance the car travelled on each surface. Which surface exerted the greatest frictional force on the car?", fig: { type: "bar", title: "Distance travelled by toy car", xl: "Surface", yl: "Distance travelled (cm)", bars: [["P", 85], ["Q", 30], ["R", 120], ["S", 55]] }, o: ["P", "Q", "R", "S"], a: 1, why: "The car travelled the shortest distance on Q, so Q slowed it down the most — Q had the greatest friction. R had the least.", lvl: 2 },
    { q: "The graph shows the extension of a spring when different loads are hung on it. The original length of the spring is 10 cm. What is the extension when a 150 g load is hung?", fig: { type: "line", title: "Extension of a spring", xl: "Mass of load (g)", yl: "Extension (cm)", pts: [["0", 0], ["50", 2], ["100", 4], ["150", 6], ["200", 8], ["250", 10]] }, o: ["3 cm", "6 cm", "8 cm", "16 cm"], a: 1, why: "Read the graph at 150 g: 6 cm. 16 cm would be the LENGTH (10 + 6), not the extension.", lvl: 2 },
    { q: "Jun wants to find out whether the type of surface affects how far a toy car travels after rolling down a ramp. Which two set-ups should he use?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Ramp height: 20 cm", "Surface: carpet", "Car: 100 g"] }, { label: "B", icon: "box", lines: ["Ramp height: 30 cm", "Surface: wood", "Car: 100 g"] }, { label: "C", icon: "box", lines: ["Ramp height: 20 cm", "Surface: wood", "Car: 100 g"] }, { label: "D", icon: "box", lines: ["Ramp height: 20 cm", "Surface: wood", "Car: 200 g"] }] }, o: ["A and B", "B and C", "C and D", "A and C"], a: 3, why: "A and C differ only in the surface. A and B also differ in height; C and D differ in car mass; B and C differ in height.", lvl: 2 },
    { q: "A goalkeeper catches a ball that is flying towards the goal. What effect does the force from his hands have on the ball?", o: ["It stops the moving ball.", "It speeds up the ball.", "It makes a stationary ball move.", "It pulls the ball towards the Earth."], a: 0, why: "The ball was moving and the goalkeeper’s hands brought it to a stop.", lvl: 2 },
    { q: "Why do car tyres have deep treads?", o: ["To reduce friction so the car can move faster", "To make the tyres lighter", "To increase friction so the tyres grip the road better", "To reduce the gravitational force on the car"], a: 2, why: "Treads increase friction between the tyres and the road, so the car grips the road, especially on wet roads.", lvl: 2 },
    { q: "Four objects were hung, one at a time, from the same spring balance. The graph shows the readings. Which object has the greatest weight?", fig: { type: "bar", title: "Spring balance readings", xl: "Object", yl: "Reading (N)", bars: [["P", 3.5], ["Q", 4], ["R", 2], ["S", 6.5]] }, o: ["P", "Q", "R", "S"], a: 3, why: "Weight is the gravitational force on the object, shown by the spring balance reading. S has the highest reading, 6.5 N.", lvl: 2 },
    { q: "On a cold morning, Raju rubs his palms together quickly and they feel warm. Why?", o: ["Friction between his palms produces heat.", "Gravitational force pulls heat into his palms.", "His palms become magnetised.", "Elastic spring force in his skin produces heat."], a: 0, why: "Friction between surfaces rubbing against each other produces heat.", lvl: 2 },
    { q: "Ball bearings are placed between the moving parts of a bicycle wheel. How do they help?", o: ["They make the wheel heavier so that it grips the road more firmly.", "They increase friction between the parts so the wheel can stop faster.", "They reduce friction between the moving parts, so the wheel turns more easily.", "They produce a magnetic force between the parts that turns the wheel."], a: 2, why: "Ball bearings roll between the parts instead of the parts rubbing, which reduces friction.", lvl: 2 },
    { q: "A bag hangs at rest from a spring balance. Which two forces act on the bag?", o: ["Gravitational force downwards and elastic spring force upwards", "Frictional force downwards and gravitational force upwards", "Magnetic force upwards and frictional force downwards", "Elastic spring force downwards and gravitational force upwards"], a: 0, why: "The Earth pulls the bag down; the stretched spring pulls it up. Gravitational force never acts upwards.", lvl: 2 },
    { q: "Different loads were hung on a spring. The table shows the results. What is the extension of the spring when the 200 g load is hung?", tbl: [["Load (g)", "0", "100", "200"], ["Length of spring (cm)", "12", "15", "18"]], o: ["3 cm", "6 cm", "12 cm", "18 cm"], a: 1, why: "Extension = 18 − 12 = 6 cm. 18 cm is the length, and 12 cm is the original length.", lvl: 2 },
    { q: "Ben threw a ball straight up. It slowed down, stopped for a moment and fell back to him. Which force caused the ball to slow down on its way up?", o: ["Elastic spring force", "Magnetic force", "Gravitational force", "The force from Ben’s hand"], a: 2, why: "Gravitational force pulls the ball towards the Earth, so it slows the ball as it rises and then pulls it back down.", lvl: 2 },
    { q: "In which situation is friction NOT useful?", o: ["Brakes slowing down a bicycle", "Shoes gripping the floor as we walk", "A pencil leaving marks on paper", "Moving parts of a machine wearing out"], a: 3, why: "Wearing out machine parts is an unwanted effect of friction. The other three rely on friction.", lvl: 2 },
    { q: "Magnet A and magnet B were placed as shown and they pushed each other apart. Which statement is correct?", fig: { type: "magnets", items: [{ label: "A", poles: "NS" }, { label: "B", poles: "??" }], between: ["repel"] }, o: ["The left end of B is a north pole, and the magnets exert a contact force.", "The left end of B is a south pole, and the magnets exert a non-contact force.", "The left end of B is a south pole, and the magnets exert a contact force.", "The left end of B is a north pole, and the magnets exert a non-contact force."], a: 1, why: "A’s right end is S. Like poles repel, so B’s left end is S. Magnetic force acts across the gap without contact.", lvl: 2 },
    { q: "Blocks fitted with four different shoe soles were pulled across the same wet tiled floor. The graph shows the force needed to start each block moving. Which sole is the best choice for a hawker who works on wet floors?", fig: { type: "bar", title: "Force needed to start the block moving", xl: "Shoe sole", yl: "Force (N)", bars: [["W", 7], ["X", 4], ["Y", 2], ["Z", 5]] }, o: ["W", "X", "Y", "Z"], a: 0, why: "W needed the greatest force, so it has the most friction with the wet floor — it gives the best grip and the wearer is least likely to slip.", lvl: 2 },

    { q: "Study the graph of a spring’s extension. When object Y is hung on the spring, the extension is 7 cm. What is the most likely mass of object Y?", fig: { type: "line", title: "Extension of a spring", xl: "Mass of load (g)", yl: "Extension (cm)", pts: [["0", 0], ["50", 2], ["100", 4], ["150", 6], ["200", 8], ["250", 10]] }, o: ["70 g", "140 g", "175 g", "350 g"], a: 2, why: "The spring extends 2 cm for every 50 g, so 1 cm for every 25 g. 7 cm → 7 × 25 = 175 g, between 150 g and 200 g.", lvl: 3 },
    { q: "A spring of original length 8 cm was loaded and then unloaded. The table shows its length with the load and after the load was removed. When was the spring first stretched beyond its elastic limit?", tbl: [["Load (g)", "100", "200", "300", "400", "500"], ["Length with load (cm)", "10", "12", "14", "17", "21"], ["Length after load removed (cm)", "8", "8", "8", "9", "11"]], o: ["When the 200 g load was hung", "When the 300 g load was hung", "When the 400 g load was hung", "When the 500 g load was hung"], a: 2, why: "Up to 300 g the spring returned to 8 cm. After the 400 g load it stayed at 9 cm, so the 400 g load first stretched it beyond its elastic limit.", lvl: 3 },
    { q: "The same wooden block was pulled at a steady speed across four surfaces using a spring balance. The table shows the readings. Which conclusion is correct?", tbl: [["Surface", "Glass", "Wood", "Sandpaper", "Rubber mat"], ["Reading (N)", "1.5", "3", "6", "5"]], o: ["The block is heaviest on sandpaper.", "Sandpaper exerted the greatest frictional force on the block.", "Glass exerted the greatest frictional force on the block.", "The spring balance measured the mass of the block in grams."], a: 1, why: "A larger pull was needed to overcome the greater friction on sandpaper. The block’s weight is the same on every surface, and the balance reads force in newtons.", lvl: 3 },
    { q: "Which statements about friction are correct?\nA: Friction produces heat.\nB: Friction can wear away surfaces.\nC: Friction acts in the same direction as the motion of an object.\nD: Friction can slow down a moving object.", o: ["A and B only", "A, B and D only", "B and C only", "A, C and D only"], a: 1, why: "Friction produces heat, wears surfaces and slows moving objects. It acts OPPOSITE to motion, so C is wrong.", lvl: 3 },
    { q: "Rahul wants to find out whether the height of a ramp affects how far a toy car travels. Which two set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Ramp height: 20 cm", "Surface: carpet", "Car: 100 g"] }, { label: "B", icon: "box", lines: ["Ramp height: 40 cm", "Surface: carpet", "Car: 100 g"] }, { label: "C", icon: "box", lines: ["Ramp height: 40 cm", "Surface: wood", "Car: 100 g"] }, { label: "D", icon: "box", lines: ["Ramp height: 20 cm", "Surface: wood", "Car: 200 g"] }] }, o: ["A and D", "B and C", "C and D", "A and B"], a: 3, why: "A and B differ only in height. C and D differ in height AND car mass; B and C have the same height.", lvl: 3 },
    { q: "Ring magnets A and B are placed on a wooden rod as shown. Ring B floats above ring A. Which forces act on ring B?", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "S" }], gaps: [true] }, o: ["Only gravitational force, acting downwards", "Magnetic force downwards and frictional force upwards", "Elastic spring force upwards and gravitational force downwards", "Magnetic force upwards and gravitational force downwards"], a: 3, why: "Like poles (N and N) face each other and repel, pushing B up; gravitational force still pulls B down. The two forces balance, so B stays still.", lvl: 3 },
    { q: "A car was driven at the same speed on three roads and braked at the same point. The graph shows the distance it needed to stop. Which statement is supported by the results?", fig: { type: "bar", title: "Stopping distance of a car", xl: "Road surface", yl: "Stopping distance (m)", bars: [["Dry road", 18], ["Wet road", 27], ["Oily road", 41]] }, o: ["There was the most friction between the tyres and the oily road.", "The car stopped in the shortest distance on the road with the least friction.", "Water and oil on the road reduce friction between the tyres and the road.", "The car’s weight was greatest on the dry road."], a: 2, why: "The car needed longer to stop on wet and oily roads, so there was less friction there. The dry road had the most friction and shortest stopping distance.", lvl: 3 },
    { q: "Priya gave a book a push along a table and it slid 30 cm before stopping. She then polished the table and gave the same book the same push. Which correctly predicts and explains the result?", o: ["The book slides a shorter distance because polish increases friction.", "The book slides a longer distance because the smoother surface exerts less friction.", "The book slides the same distance because the push is the same.", "The book slides a longer distance because polish reduces the book’s weight."], a: 1, why: "Polishing makes the surface smoother, so there is less friction to slow the book down. Its weight does not change.", lvl: 3 },
    { q: "A box was hung from a spring balance, then pulled slowly at a steady speed along the floor with the same spring balance, as shown. Which statement is correct?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Box hung from", "spring balance", "Reading: 8 N"] }, { label: "B", icon: "box", lines: ["Box pulled along", "floor, steady speed", "Reading: 3 N"] }] }, o: ["The box’s weight decreased from 8 N to 3 N on the floor.", "The mass of the box is 8 N, as shown when it was hung up.", "The gravitational force on the box is 3 N when it is pulled.", "The frictional force between the box and the floor is about 3 N."], a: 3, why: "At a steady speed, the pull balances the friction, so friction ≈ 3 N. The weight stays 8 N; mass is not measured in newtons.", lvl: 3 },
    { q: "A paper ball was launched with a rubber band stretched by different amounts. The graph shows the results. Which statement best explains the trend?", fig: { type: "line", title: "Rubber band catapult", xl: "How much the band was stretched (cm)", yl: "Distance travelled (cm)", pts: [["2", 60], ["4", 120], ["6", 185], ["8", 240]] }, o: ["The more the band is stretched, the greater the elastic force on the ball, so it travels further.", "The more the band is stretched, the smaller the gravitational force on the ball.", "A stretched rubber band exerts a magnetic force on the ball.", "The ball travels further because the friction on it increases."], a: 0, why: "A rubber band stretched more exerts a greater elastic force, pushing the ball harder so it travels further. Gravity is unchanged and friction would shorten the distance.", lvl: 3 },
    { q: "In a jack-in-the-box toy, a spring is squashed under the lid. When the catch is released, the spring pushes the lid open. Which statement is correct?", o: ["A compressed spring exerts a push, and the more it is compressed, the greater the push.", "A compressed spring exerts a pull on the lid.", "The spring pushes the lid up because gravitational force acts upwards.", "A spring exerts a force only when it is stretched, not when it is compressed."], a: 0, why: "A compressed spring pushes back towards its original length; squashing it more gives a bigger push. Gravitational force acts downwards.", lvl: 3 },
    { q: "The table shows the extension of two springs with the same load. Shanti wants to make a spring balance that shows very small differences in the weights of letters clearly. Which spring should she use, and why?", tbl: [["Load (g)", "0", "100", "200"], ["Extension of red spring (cm)", "0", "2", "4"], ["Extension of blue spring (cm)", "0", "5", "10"]], o: ["Red, because it stretches less for the same load, so it gives more exact readings", "Red, because it is stronger and never reaches its elastic limit with letters", "Blue, because it has a smaller extension for each load, so it is easier to read", "Blue, because it extends more for the same load, so small weight changes are easier to see"], a: 3, why: "The blue spring extends 5 cm per 100 g, more than the red one, so a small change in load gives a bigger, easier-to-read change on the scale.", lvl: 3 },

    { q: "Study the graph of a spring’s extension. Two identical springs of this type are hooked end to end, and a 100 g load is hung from the bottom spring. What is the total extension of the two springs?", fig: { type: "line", title: "Extension of one spring", xl: "Mass of load (g)", yl: "Extension (cm)", pts: [["0", 0], ["50", 2], ["100", 4], ["150", 6], ["200", 8]] }, o: ["2 cm", "4 cm", "8 cm", "16 cm"], a: 2, why: "Each spring carries the full pull of the 100 g load, so each extends 4 cm. Total extension = 4 + 4 = 8 cm.", lvl: 4 },
    { q: "Identical wooden blocks were stacked and pulled at a steady speed across the SAME floor using a spring balance. The graph shows the results. Which conclusion can be drawn?", fig: { type: "bar", title: "Force needed to pull blocks at steady speed", xl: "Number of identical blocks", yl: "Reading (N)", bars: [["1 block", 2], ["2 blocks", 4], ["3 blocks", 6]] }, o: ["The heavier the load pressing on the floor, the greater the friction.", "Rougher floors produce more friction.", "The frictional force is not affected by the weight of the blocks.", "The spring balance reading equals the total weight of the blocks."], a: 0, why: "Only the number (weight) of blocks changed, and the pull needed to overcome friction rose with it. The floor was the same, so nothing can be concluded about roughness; the reading is the friction, not the weight.", lvl: 4 },
    { q: "Tom rolled a toy car down a ramp in four set-ups. Based ONLY on fair comparisons, which conclusion(s) can he draw?\nA: At the same ramp height, the car travels further on wood than on carpet.\nB: On wood, the car travels further when the ramp is higher.\nC: A heavier car travels further on carpet.", tbl: [["Set-up", "Mass of car (g)", "Ramp height (cm)", "Surface", "Distance (cm)"], ["P", "100", "20", "carpet", "40"], ["Q", "100", "20", "wood", "95"], ["R", "200", "30", "carpet", "60"], ["S", "100", "30", "wood", "130"]], o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "P vs Q changes only the surface (A). Q vs S changes only the height (B). R differs from P in both mass AND height, so C cannot be concluded.", lvl: 4 },
    { q: "The graph shows how the extension of a spring changed as loads were added. Which statement is correct?", fig: { type: "line", title: "Extension of a spring", xl: "Mass of load (g)", yl: "Extension (cm)", pts: [["0", 0], ["100", 3], ["200", 6], ["300", 9], ["400", 13], ["500", 19]] }, o: ["Up to 300 g, the extension increases by the same amount for every 100 g added.", "After 300 g, the extension increases by a smaller amount for every 100 g added.", "The extension decreases after 300 g.", "The spring will surely return to its original length after the 500 g load is removed."], a: 0, why: "0→300 g: +3 cm per 100 g. After 300 g the extension increases by MORE (4 cm, then 6 cm), a sign the spring may be stretched beyond its elastic limit, so it may not return to its original length.", lvl: 4 },
    { q: "A magnet hangs from a spring. Different blocks were placed, one at a time, the same distance below it. The table shows the length of the spring. Which could blocks P, Q and R be?", tbl: [["Block below magnet", "None", "P", "Q", "R"], ["Length of spring (cm)", "15", "18", "15", "12"]], o: ["P: magnet, Q: iron, R: plastic", "P: plastic, Q: iron, R: magnet", "P: iron, Q: magnet, R: copper", "P: iron, Q: plastic, R: magnet"], a: 3, why: "P pulled the magnet down (attraction) — iron works. Q had no effect — non-magnetic, e.g. plastic. R pushed the magnet up (spring shorter) — only another magnet can repel. Iron would always be attracted, so Q cannot be iron.", lvl: 4 },
    { q: "A wooden block stays still on a rough wooden slope (set-up A). When the same slope is coated with oil, the block slides down (set-up B). Which statement best explains this?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Rough wooden slope", "Block stays still"] }, { label: "B", icon: "box", lines: ["Same slope, oiled", "Block slides down"] }] }, o: ["There is no gravitational force on the block in set-up A, so the block stays still.", "The oil increases the weight of the block in set-up B, so it slides down the slope.", "In A, friction up the slope holds the block; oil reduces friction, so gravitational force pulls it down.", "In A, friction acts down the slope and pushes the block into the wood, holding it still."], a: 2, why: "Gravitational force pulls the block down the slope in both set-ups. In A, friction opposes this and holds it still; the oil reduces friction so it can no longer hold the block.", lvl: 4 }
  ],
  tf: [
    { s: "A force can change the shape of an object.", a: true, why: "Squeezing a sponge or stretching a rubber band changes its shape." },
    { s: "A rolling ball stops because the force that pushed it is used up.", a: false, why: "The ball stops because friction acts on it, opposing its motion." },
    { s: "The weight of an object is the gravitational force acting on it.", a: true, why: "Weight is a force, measured in newtons." },
    { s: "Mass and weight are both measured in kilograms.", a: false, why: "Mass is measured in g or kg; weight is a force measured in newtons (N)." },
    { s: "Friction between two surfaces produces heat.", a: true, why: "Rubbing your palms together makes them warm." },
    { s: "Friction is always a nuisance and should be removed completely.", a: false, why: "Without friction we could not walk, grip objects or brake." },
    { s: "Rougher surfaces generally produce more friction than smoother ones.", a: true, why: "A toy car travels a shorter distance on carpet than on glass." },
    { s: "Putting oil between moving parts increases friction.", a: false, why: "Oil is a lubricant; it reduces friction." },
    { s: "A stretched spring pulls back, and a compressed spring pushes back.", a: true, why: "Both exert an elastic spring force that acts to return the spring to its original length." },
    { s: "The extension of a spring is the same as its stretched length.", a: false, why: "Extension = stretched length − original length." },
    { s: "Magnetic force and gravitational force can act on objects without touching them.", a: true, why: "Both are non-contact forces." },
    { s: "Gravitational force acts only on objects that are falling.", a: false, why: "It acts on all objects all the time, including a book resting on a table." },
    { s: "Treads on tyres increase the friction between the tyres and the road.", a: true, why: "This gives better grip, especially on wet roads." },
    { s: "Ball bearings are used in machines to increase friction.", a: false, why: "Ball bearings reduce friction so parts turn smoothly." },
    { s: "Friction causes the soles of shoes to wear away over time.", a: true, why: "Friction between the soles and the ground wears away the surface." },
    { s: "A spring stretched beyond its elastic limit will always return to its original length.", a: false, why: "Beyond its elastic limit, a spring stays longer than its original length." },
    { s: "Within the elastic limit, the greater the load hung on a spring, the greater its extension.", a: true, why: "A heavier load pulls harder on the spring, stretching it more." },
    { s: "Friction acts in the same direction as a moving object.", a: false, why: "Friction always opposes motion, so it acts in the opposite direction." },
    { s: "When bicycle brakes are used, the brake pads become warm and slowly wear thin.", a: true, why: "Friction between the pads and the wheel rim produces heat and wears the pads." },
    { s: "A magnet can attract an iron nail only if the magnet touches it.", a: false, why: "Magnetic force is a non-contact force; it acts across a gap." }
  ],
  sort: [
    { title: "Does each action increase or reduce friction?", groups: ["Increases friction", "Reduces friction"], items: [["treads on car tyres", 0], ["studs on football boots", 0], ["sand sprinkled on a slippery path", 0], ["rubber grips on handlebars", 0], ["oil on a bicycle chain", 1], ["ball bearings in a wheel", 1], ["grease on a door hinge", 1], ["polishing a floor", 1], ["putting wheels under a heavy box", 1]] },
    { title: "Is each a contact force or a non-contact force?", groups: ["Contact force", "Non-contact force"], items: [["friction between tyres and road", 0], ["a stretched rubber band pulling back", 0], ["a compressed spring in a stapler", 0], ["a hand pushing a trolley", 0], ["the Earth pulling a falling rambutan", 1], ["a magnet attracting a pin through paper", 1], ["a ring magnet floating above another", 1], ["the Earth pulling a satellite", 1]] },
    { title: "Is friction useful or not useful here?", groups: ["Useful", "Not useful"], items: [["walking without slipping", 0], ["bicycle brakes stopping a wheel", 0], ["writing with a pencil", 0], ["holding a cup firmly", 0], ["car engine parts wearing out", 1], ["shoe soles wearing thin", 1], ["unwanted heat in a machine", 1], ["pushing a heavy cupboard across a floor", 1]] }
  ],
  oe: [
    { q: "State the effect of the force in each case.\n(a) Mei Ling squeezes a sponge. [1]\n(b) Hafiz kicks a football that was resting on the field. [1]", marks: 2, kw: [["shape", "flat", "squash"], ["move", "moving", "motion"]], model: "(a) The force changes the shape of the sponge. (b) The force makes the stationary football move." },
    { q: "A toy car was released from the same height on the same ramp onto four surfaces. The graph shows the results.\n(a) On which surface was the friction greatest? [1]\n(b) Using the graph, explain your answer. [2]", fig: { type: "bar", title: "Distance travelled by toy car", xl: "Surface", yl: "Distance travelled (cm)", bars: [["Glass", 140], ["Wood", 105], ["Towel", 45], ["Carpet", 60]] }, marks: 3, kw: [["towel"], ["shortest", "least distance", "smallest distance", "shorter distance"], ["greatest friction", "most friction", "more friction", "highest friction", "greatest frictional", "most frictional", "more frictional", "largest friction"]], model: "(a) Towel. (b) The car travelled the shortest distance on the towel, because the towel exerted the greatest frictional force on the car, which opposed its motion and slowed it down the most." },
    { q: "Study the graph. The spring has an original length of 10 cm.\n(a) What is the extension of the spring with a 200 g load? [1]\n(b) What is the length of the spring with a 200 g load? [1]\n(c) Describe the relationship between the mass of the load and the extension. [1]\n(d) Assuming the pattern continues, predict the extension with a 300 g load. [1]", fig: { type: "line", title: "Extension of a spring", xl: "Mass of load (g)", yl: "Extension (cm)", pts: [["0", 0], ["50", 2], ["100", 4], ["150", 6], ["200", 8], ["250", 10]] }, marks: 4, kw: [["8"], ["18"], ["increase", "greater", "more", "longer"], ["12"]], model: "(a) 8 cm. (b) 18 cm. (c) As the mass of the load increases, the extension of the spring increases. (d) 12 cm." },
    { q: "A spring of original length 6 cm was tested. Each load was hung on the spring and then removed. The table shows the results.\n(a) Which load first stretched the spring beyond its elastic limit? [1]\n(b) Explain how you know. [1]\n(c) Explain why a spring balance should not be used to weigh objects that stretch its spring beyond its elastic limit. [1]", tbl: [["Load (g)", "50", "100", "150", "200", "250"], ["Length with load (cm)", "8", "10", "12", "15", "19"], ["Length after load removed (cm)", "6", "6", "6", "7", "9"]], marks: 3, x: 1, kw: [["200"], ["not return", "did not go back", "not go back", "7 cm", "longer than", "stayed longer", "not back"], ["inaccurate", "wrong", "not accurate", "incorrect", "not correct", "not start at zero", "not show zero"]], model: "(a) 200 g. (b) After the 200 g load was removed, the spring did not return to its original length of 6 cm; it stayed at 7 cm. (c) The spring would be permanently stretched, so the spring balance would no longer show zero with no load and its readings would be inaccurate." },
    { q: "The same wooden block was pulled across three surfaces at a steady speed using a spring balance, as shown.\n(a) On which surface was the friction greatest? [1]\n(b) State one variable that must be kept the same. [1]\n(c) Explain why the reading was lowest on glass. [2]", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Surface: glass", "Reading: 1 N"] }, { label: "B", icon: "plate", lines: ["Surface: sandpaper", "Reading: 5 N"] }, { label: "C", icon: "plate", lines: ["Surface: wood", "Reading: 3 N"] }] }, marks: 4, kw: [["sandpaper"], ["same block", "mass of the block", "weight of the block", "same mass", "same weight", "same speed", "steady speed", "same spring balance"], ["smooth"], ["least friction", "less friction", "smallest friction", "least frictional", "less frictional", "lowest friction"]], model: "(a) Sandpaper. (b) The same block (same mass) must be used. (c) Glass is the smoothest surface, so it exerted the least friction on the block and the smallest pull was needed to move it." },
    { q: "Explain why oil is put on the chain of a bicycle.", marks: 2, kw: [["reduce friction", "reduces friction", "less friction", "lower friction", "decrease friction", "reduces the friction", "reducing friction", "reduce the friction"], ["wear", "heat", "easier", "easily", "smooth"]], model: "Oil reduces friction between the moving parts of the chain, so the chain turns more easily and wears out less." },
    { q: "Ring magnets A, B and C are placed on a wooden rod as shown. B floats above A, and C rests on B.\n(a) Explain why ring B floats above ring A. [1]\n(b) Which pole is on the top face of ring C? [1]\n(c) Ring C is removed. Predict what happens to ring B and explain why. [2]", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "S" }, { label: "C", top: "?" }], gaps: [true, false] }, marks: 4, x: 1, kw: [["repel"], ["south", "s pole"], ["higher", "rise", "move up", "moves up", "further", "bigger gap", "larger gap", "go up", "goes up"], ["weight", "gravitational", "heavier", "lighter", "less downward"]], model: "(a) The bottom face of B is a north pole, facing the north pole on top of A. Like poles repel, so the magnetic force pushes B upwards. (b) South pole. (c) Ring B will rise higher above A, because the weight of C is no longer pressing down on B, so the magnetic repulsion pushes B further up." },
    { q: "Football boots have studs on their soles. Explain how the studs help the players.", marks: 2, kw: [["increase friction", "more friction", "greater friction", "increases friction", "increases the friction", "increase the friction"], ["slip", "grip"]], model: "The studs increase friction between the boots and the field, so the players can grip the ground better and are less likely to slip." },
    { q: "Kai launched the same paper ball with a rubber band catapult, stretching the band by different amounts. The graph shows the results.\n(a) Describe the relationship shown in the graph. [1]\n(b) Explain why the ball travelled further when the band was stretched more. [1]\n(c) State one variable Kai must keep the same. [1]", fig: { type: "line", title: "Rubber band catapult", xl: "How much the band was stretched (cm)", yl: "Distance travelled (cm)", pts: [["2", 60], ["4", 120], ["6", 185], ["8", 240]] }, marks: 3, kw: [["further", "greater distance", "longer distance", "more distance", "distance increases", "distance travelled increases"], ["greater elastic", "bigger elastic", "larger elastic", "stronger elastic", "more elastic", "greater force", "bigger force", "stronger force", "greater push", "bigger push", "stronger push", "more force"], ["same paper ball", "same ball", "mass of", "same rubber band", "same angle", "same height", "same mass", "size of", "same catapult"]], model: "(a) The more the rubber band is stretched, the further the paper ball travels. (b) A rubber band that is stretched more exerts a greater elastic force on the ball, so the ball is pushed harder. (c) Use the same paper ball (same mass) each time." },
    { q: "The table shows the extension of a red spring and a blue spring with different loads.\n(a) Which spring stretched more with a 100 g load? [1]\n(b) Shanti wants to make a spring balance to weigh very light letters. Which spring should she use? Explain. [2]", tbl: [["Load (g)", "0", "100", "200"], ["Extension of red spring (cm)", "0", "2", "4"], ["Extension of blue spring (cm)", "0", "5", "10"]], marks: 3, kw: [["blue"], ["larger extension", "bigger extension", "greater extension", "extends more", "stretches more", "longer extension", "more extension", "stretch more", "extend more"], ["easier", "small difference", "small change", "accurate", "clearly", "sensitive", "small weight"]], model: "(a) The blue spring. (b) The blue spring, because it has a larger extension for the same load, so even a small difference in weight gives a change on the scale that is easier to see." },
    { q: "The set-ups show four ramps used to study how far a toy car travels.\n(a) Which two set-ups should be used to find out if the height of the ramp affects the distance travelled? [1]\n(b) Explain why set-ups B and D cannot be used to find out if the type of surface affects the distance. [1]\n(c) In which set-up, A or B, will the car travel further? Explain. [1]", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["Ramp height: 20 cm", "Surface: carpet", "Car: 100 g"] }, { label: "B", icon: "box", lines: ["Ramp height: 20 cm", "Surface: wood", "Car: 100 g"] }, { label: "C", icon: "box", lines: ["Ramp height: 30 cm", "Surface: wood", "Car: 100 g"] }, { label: "D", icon: "box", lines: ["Ramp height: 30 cm", "Surface: carpet", "Car: 200 g"] }] }, marks: 3, kw: [["b and c", "c and b"], ["more than one", "two variables", "three variables", "other variables", "height and", "mass and", "not a fair test", "not fair"], ["less friction", "smaller friction", "least friction", "less frictional", "lower friction", "smoother"]], model: "(a) B and C. (b) More than one variable is changed: the height, the surface and the mass of the car are all different, so it is not a fair test. (c) B, because wood is smoother than carpet, so it exerts less friction on the car." },
    { q: "After a long drive on the expressway, the tyres of a car feel hot. Explain why.", marks: 2, kw: [["friction"], ["heat", "hot", "warm"]], model: "There is friction between the tyres and the road, and friction produces heat, so the tyres become hot." },
    { q: "A magnet hangs from a spring. Different blocks were placed, one at a time, the same distance below it. The set-ups show the results.\n(a) Explain why the spring is longer in set-up B than in set-up A. [2]\n(b) Explain why the spring is shorter in set-up D than in set-up A. [1]\n(c) Name the force that stretches the spring in set-up A. [1]", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["No block below", "Spring: 15 cm"] }, { label: "B", icon: "box", lines: ["Block P below", "Spring: 19 cm"] }, { label: "C", icon: "box", lines: ["Block Q below", "Spring: 15 cm"] }, { label: "D", icon: "box", lines: ["Block R below", "Spring: 12 cm"] }] }, marks: 4, x: 1, kw: [["attract"], ["pull", "pulls"], ["repel"], ["gravit", "weight"]], model: "(a) Block P is made of a magnetic material, so it attracts the magnet. The magnetic force pulls the magnet downwards, so the spring stretches more. (b) Block R is a magnet with a like pole facing the hanging magnet, so they repel and the magnet is pushed upwards, so the spring stretches less. (c) Gravitational force (the weight of the magnet)." },
    { q: "A car was driven at the same speed on three roads and braked at the same point. The graph shows the stopping distances.\n(a) On which road was the friction between the tyres and the road the least? [1]\n(b) Explain why drivers should drive more slowly when it rains. [2]", fig: { type: "bar", title: "Stopping distance of a car", xl: "Road surface", yl: "Stopping distance (m)", bars: [["Dry road", 18], ["Wet road", 27], ["Oily road", 41]] }, marks: 3, kw: [["oil"], ["less friction", "lower friction", "reduces friction", "reduce friction", "smaller friction", "less frictional", "reduces the friction"], ["longer", "further", "more distance", "greater distance"]], model: "(a) The oily road. (b) Water on the road reduces friction between the tyres and the road, so the car needs a longer distance to stop and is more likely to skid." }
  ],
  doc: [
    { q: "A toy car travelled a shorter distance on carpet than on wood after rolling down the same ramp. Explain why.", marks: 2, answers: ["Because the carpet is soft.", "The carpet is rougher, so it exerts more friction on the car, slowing it down more.", "The car is heavier on carpet, so it stops faster."], best: 1, why: "Answer 2 compares the surfaces and links rougher → more friction → slowed down more. Answer 1 gives no force at all. Answer 3 is wrong: the car’s weight does not change with the surface." },
    { q: "Explain why oil is put on a squeaky door hinge.", marks: 2, answers: ["Oil reduces friction between the moving parts of the hinge, so the door opens more easily and the parts wear out less.", "To make the door smooth.", "Oil increases friction so the door stays in place."], best: 0, why: "Answer 1 names the effect (reduces friction), the surfaces (moving parts of the hinge) and the benefit. Answer 2 is too vague and never mentions friction. Answer 3 gets the effect the wrong way round." },
    { q: "A ball thrown upwards always falls back down. Explain why.", marks: 1, answers: ["Because the ball is heavy.", "The air pushes it down.", "Gravitational force pulls the ball towards the Earth."], best: 2, why: "Answer 3 names the force and its direction. ‘Heavy’ is not a force, and air does not push the ball down to the ground." },
    { q: "A spring is 10 cm long with no load and 16 cm long with a 300 g load. Tom says the extension is 16 cm. Which is the best correction?", marks: 1, answers: ["The extension is 26 cm because you add both lengths.", "Extension = stretched length − original length = 16 − 10 = 6 cm.", "The extension is 10 cm because that is the spring’s length."], best: 1, why: "Answer 2 uses the correct formula. Answer 1 adds instead of subtracts; Answer 3 gives the original length, not the extension." },
    { q: "Explain why tyres have deep treads.", marks: 2, answers: ["To make the tyres look nice.", "Treads reduce friction so the car moves faster.", "Treads increase friction between the tyres and the road, so the tyres grip the road and the car is less likely to skid."], best: 2, why: "Answer 3 names the effect (increase friction), the surfaces and the benefit (grip, less skidding). Answer 2 has friction the wrong way round; Answer 1 is not science." }
  ]
};
