window.LB = window.LB || {};
LB["p6-impact"] = {
  notes: [
    { h: "Man’s impact can be positive or negative", t: "Humans change the environment to meet their needs for land, food, water, fuels and materials. Some activities harm the environment, such as cutting down forests, polluting air, water and land, overfishing and poaching. Other activities have a positive impact, such as setting up nature reserves, replanting trees and practising the 3Rs.", kw: ["positive impact", "negative impact", "harm the environment"] },
    { h: "Deforestation", t: "Deforestation is the large-scale cutting down or burning of forests. People clear forests to get land for housing, farming (e.g. oil palm plantations) and roads, and to get timber. Because so many trees are removed at once, the forest cannot grow back quickly.", kw: ["deforestation", "land for housing", "farming", "timber"] },
    { h: "Effects of deforestation", t: "Animals lose their habitats, food and shelter, so their populations decrease and some may become extinct. There are fewer plants to take in carbon dioxide during photosynthesis, so more carbon dioxide stays in the air; burning the trees also releases carbon dioxide. Without roots to hold the soil together, rain washes the topsoil away (soil erosion), which can cause landslides and floods.", kw: ["loss of habitats", "fewer plants to take in carbon dioxide", "roots hold the soil", "soil erosion"] },
    { h: "Air pollution and haze", t: "Burning fuels in vehicles, factories and power stations releases harmful gases, smoke and carbon dioxide into the air. Haze is caused mainly by forest fires started to clear land, and it can be blown to Singapore by the wind. Polluted air can cause breathing problems, and haze blocks some sunlight from reaching plants.", kw: ["burning fuels", "harmful gases", "haze", "forest fires", "breathing problems"] },
    { h: "Water pollution", t: "Water is polluted by oil spills from ships, chemicals and waste from factories and farms, sewage and litter. An oil spill forms a layer on the water surface that blocks sunlight, so water plants cannot photosynthesise; oil also coats the feathers of sea birds so they cannot fly or keep warm. Chemicals can poison water organisms, and animals such as turtles may swallow plastic litter and die.", kw: ["oil spills", "chemicals", "blocks sunlight", "cannot photosynthesise", "coats the feathers"] },
    { h: "Land pollution", t: "Land is polluted when people litter, dump rubbish illegally, or use too many chemicals such as pesticides on farms. Many materials, such as plastics, do not decompose easily and remain in the environment for a very long time. Singapore burns most of its rubbish in incineration plants and sends the ash to Semakau Landfill, which will be filled up one day, so we must produce less rubbish.", kw: ["litter", "do not decompose", "landfill", "produce less rubbish"] },
    { h: "Global warming", t: "Carbon dioxide in the air traps heat from the Sun and keeps the Earth warm. Burning fuels and deforestation increase the amount of carbon dioxide in the air, so more heat is trapped and the Earth’s average temperature rises: this is global warming. As a result, ice at the North and South Poles melts, sea levels rise and low-lying land may be flooded.", kw: ["more carbon dioxide", "traps more heat", "temperature rises", "ice melts", "sea levels rise"] },
    { h: "Overfishing and poaching", t: "Overfishing is catching fish faster than they can reproduce, so the fish population keeps decreasing. Poaching is the illegal hunting or collecting of animals and plants, e.g. for ivory, skins or pets. Both can make a species endangered (at risk of becoming extinct) or extinct (no longer exists at all).", kw: ["overfishing", "faster than they can reproduce", "poaching", "endangered", "extinct"] },
    { h: "Effects on food webs and populations", t: "Organisms in a food web depend on one another, so a human activity that affects one population also affects others. If people remove a prey organism, its predators have less food and their population may decrease. If people remove a predator, its prey may increase at first and then eat up more of their own food (e.g. plants).", kw: ["depend on one another", "less food", "population decreases", "population increases"] },
    { h: "Conservation and nature reserves", t: "Conservation means protecting and caring for the environment and the living things in it. Nature reserves such as Bukit Timah Nature Reserve, Central Catchment Nature Reserve and Sungei Buloh Wetland Reserve protect the habitats of many plants and animals so they do not become extinct. Laws against poaching and illegal fishing, and replanting forests and mangroves, also help populations recover.", kw: ["conservation", "nature reserves", "protect the habitats", "replanting", "laws"] },
    { h: "The 3Rs: reduce, reuse, recycle", t: "Reduce means using less, e.g. saying no to plastic bags or printing on both sides of paper. Reuse means using an item again, e.g. using a glass jar as a pencil holder. Recycle means making used materials such as paper, plastic, glass and metal into new products, e.g. recycled paper means fewer trees are cut down.", kw: ["reduce", "reuse", "recycle", "fewer trees are cut down"] },
    { h: "Saving electricity and water", t: "Most electricity in Singapore is generated by burning fuels, so saving electricity means less fuel is burnt and less carbon dioxide is released. We can switch off lights and fans when not in use, and take public transport, walk or cycle instead of driving. Saving water, such as taking shorter showers and turning off the tap while brushing teeth, conserves a limited resource and saves the energy used to treat it.", kw: ["less fuel is burnt", "less carbon dioxide", "switch off", "public transport", "saving water"] }
  ],
  traps: [
    "“Carbon dioxide is poisonous, so that is why it causes global warming” → carbon dioxide causes global warming because it TRAPS HEAT; the problem is too much of it in the air.",
    "“Deforestation causes global warming because trees give out carbon dioxide” → it is because there are FEWER PLANTS TO TAKE IN carbon dioxide during photosynthesis (and burning trees releases carbon dioxide).",
    "“Global warming makes the hole in the ozone layer” → keep them separate; at PSLE level, global warming is caused by more carbon dioxide trapping more heat.",
    "“Recycling and reusing are the same” → reusing uses the SAME item again; recycling turns used material into a NEW product.",
    "“Oil spills kill water plants because oil is heavy” → the oil layer BLOCKS SUNLIGHT, so the water plants cannot photosynthesise and make food.",
    "“Endangered means already extinct” → endangered means AT RISK of becoming extinct; extinct means none are left anywhere.",
    "“Saving electricity at home does not affect the air” → less electricity used means less fuel burnt in power stations, so less carbon dioxide and fewer harmful gases are released.",
    "“Removing a predator is always good for the prey” → the prey population increases at first, but it may then eat up its food and decrease later."
  ],
  lessons: [
    {
      h: "Deforestation and carbon dioxide: the full chain",
      concept: "Markers want the link to PHOTOSYNTHESIS. Deforestation means fewer plants → less carbon dioxide taken in during photosynthesis → more carbon dioxide stays in the air → more heat is trapped → global warming. If the trees are burnt, carbon dioxide is also released. Saying only “trees give us oxygen” or “trees clean the air” scores nothing.",
      example: {
        q: "Large areas of rainforest are cut down and burnt to make space for farms. (a) Give two reasons why this increases the amount of carbon dioxide in the air. (b) Explain how this can cause global warming.",
        marks: 3,
        think: [
          "Step 1: Removing trees means fewer plants carry out photosynthesis, which takes in carbon dioxide.",
          "Step 2: Burning the trees releases carbon dioxide directly into the air.",
          "Step 3: For (b), link more carbon dioxide → traps more heat → Earth’s temperature rises."
        ],
        answer: "(a) There are fewer plants to take in carbon dioxide during photosynthesis. Burning the trees also releases carbon dioxide into the air. (b) More carbon dioxide in the air traps more heat, so the Earth’s average temperature rises."
      },
      tip: "Always name photosynthesis when you explain why losing plants increases carbon dioxide.",
      try: { q: "Which statement best explains why cutting down forests adds to global warming?", o: ["Trees give out carbon dioxide at night, so cutting them down is harmful to the air.", "Fewer plants take in carbon dioxide during photosynthesis, so more of it stays and traps heat.", "Fewer trees give out oxygen, so the air becomes warmer and holds more heat.", "Cutting trees makes the bare soil hotter, which then heats up the air above it."], a: 1, why: "The key link is fewer plants taking in carbon dioxide by photosynthesis, so more carbon dioxide stays in the air and traps more heat. Less oxygen does not cause warming." }
    },
    {
      h: "Human activities and food webs",
      concept: "When people remove one organism (by overfishing, poaching or clearing habitats), trace ONE arrow at a time. Its FOOD (prey) usually increases because fewer are eaten; its PREDATORS usually decrease because they have less food. Always give the reason, e.g. “fewer small fish are eaten”, not just “increases”.",
      example: {
        q: "Study the food web of a coral reef. Fishermen caught large numbers of the grouper. (a) What will happen to the population of the parrotfish at first? Explain. (b) Explain why the population of the shark may decrease.",
        fig: { type: "web", links: [["seaweed", "parrotfish"], ["seaweed", "sea urchin"], ["parrotfish", "grouper"], ["sea urchin", "grouper"], ["grouper", "shark"]] },
        marks: 3,
        think: [
          "Step 1: Find what the grouper eats: parrotfish and sea urchin (arrows point from them to the grouper).",
          "Step 2: With fewer groupers, fewer parrotfish are eaten, so the parrotfish population increases at first.",
          "Step 3: Find what eats the grouper: the shark. The shark has less food, so its population may decrease."
        ],
        answer: "(a) The parrotfish population will increase at first, because there are fewer groupers to eat them. (b) The grouper is the shark’s only food, so the shark has less food and its population may decrease."
      },
      tip: "Arrows point from the food to the eater. Follow them forwards for predators and backwards for food.",
      try: { q: "In a food web, grass is eaten by rabbits and grasshoppers, rabbits are eaten only by eagles, and grasshoppers are eaten by frogs. Eagles eat only rabbits. Poachers hunted most of the eagles. What is most likely to happen to the grass after some time?", o: ["It increases, because more rabbits and grasshoppers survive.", "It stays the same, because eagles do not eat grass.", "It decreases, because more rabbits survive and eat more grass.", "It decreases, because eagles help grass to grow."], a: 2, why: "With fewer eagles, fewer rabbits are eaten. More rabbits eat more grass, so the grass decreases. Eagles do not eat grass, but they affect it through the rabbits." }
    },
    {
      h: "Reading environmental graphs",
      concept: "Describe the TREND first (increases / decreases / stays the same), then quote numbers from the graph, then give the cause using science ideas. When a question asks for a change over a period, subtract carefully and include the unit. Do not claim a cause the data cannot show without the science reason.",
      example: {
        q: "The graph shows the amount of carbon dioxide in the air measured over many years. (a) Describe how the amount of carbon dioxide changed from 1960 to 2020. (b) Suggest one human activity that caused this change and explain how.",
        fig: { type: "line", title: "Carbon dioxide in the air", xl: "Year", yl: "Carbon dioxide (parts per million)", pts: [["1960", 317], ["1980", 339], ["2000", 370], ["2020", 414]] },
        marks: 3,
        think: [
          "Step 1: The line rises the whole time: the amount increased from 317 to 414 parts per million.",
          "Step 2: It rose faster later on (22 from 1960 to 1980, but 44 from 2000 to 2020).",
          "Step 3: Pick a cause and explain it, e.g. burning more fuels releases carbon dioxide."
        ],
        answer: "(a) The amount of carbon dioxide increased steadily from 317 to 414 parts per million, and it increased faster in later years. (b) People burnt more fuels in vehicles, factories and power stations, which releases carbon dioxide into the air."
      },
      tip: "Trend + numbers + science reason = full marks for a graph question.",
      try: { q: "Using the same graph (317, 339, 370, 414 parts per million in 1960, 1980, 2000, 2020), by how much did carbon dioxide increase from 1980 to 2020?", fig: { type: "line", title: "Carbon dioxide in the air", xl: "Year", yl: "Carbon dioxide (parts per million)", pts: [["1960", 317], ["1980", 339], ["2000", 370], ["2020", 414]] }, o: ["31 parts per million", "44 parts per million", "97 parts per million", "75 parts per million"], a: 3, why: "414 − 339 = 75 parts per million. 97 is the rise from 1960, and 44 is only from 2000 to 2020." }
    },
    {
      h: "Explaining the effects of an oil spill",
      concept: "An oil spill harms living things in more than one way, and each needs its own chain. Water plants: oil layer blocks sunlight → cannot photosynthesise → cannot make food → die. Sea birds: oil coats the feathers → cannot fly (or float, or keep warm) → cannot find food. Animals that eat the plants then have less food.",
      example: {
        q: "An oil tanker leaked oil into the sea near a coast with seagrass and sea birds. (a) Explain why the seagrass under the oil died. (b) Explain why sea birds covered in oil may die. (c) Dugongs feed on seagrass. Explain how the oil spill affects the dugong population.",
        marks: 4,
        think: [
          "Step 1: Oil floats and forms a layer that blocks sunlight.",
          "Step 2: Seagrass without light cannot photosynthesise to make food, so it dies.",
          "Step 3: Oil coats feathers, so birds cannot fly to find food.",
          "Step 4: Less seagrass means less food for dugongs, so their population decreases."
        ],
        answer: "(a) The oil layer blocked sunlight, so the seagrass could not photosynthesise to make food and died. (b) The oil coats their feathers, so they cannot fly to find food. (c) There is less seagrass, so the dugongs have less food and their population decreases."
      },
      tip: "Write “blocks sunlight → cannot photosynthesise → cannot make food”. Each arrow is a mark.",
      try: { q: "Which best explains why fish may die after an oil spill kills most water plants?", o: ["The water plants were the only animals that ate fish.", "The fish have less food and fewer places to hide and breed.", "The oil turns into carbon dioxide in the water.", "The fish cannot see the oil."], a: 1, why: "Water plants are food and shelter (habitat) for fish, so losing them affects fish. Plants are not animals, and oil does not turn into carbon dioxide." }
    },
    {
      h: "Linking a caring action to its benefit",
      concept: "Questions like “How does recycling paper / saving electricity help the environment?” need the full link, not “it is good for Earth”. Recycling paper → fewer trees cut down → more habitats kept and more plants take in carbon dioxide. Saving electricity → less fuel burnt in power stations → less carbon dioxide (and fewer harmful gases) released.",
      example: {
        q: "Ali switches off the air-conditioner when he leaves his room and takes the MRT instead of asking his father to drive him. Explain how each action helps to slow down global warming.",
        marks: 3,
        think: [
          "Step 1: Electricity in Singapore is mostly generated by burning fuels in power stations.",
          "Step 2: Switching off saves electricity → less fuel burnt → less carbon dioxide released.",
          "Step 3: MRT carries many people at once → less fuel burnt per person than a car → less carbon dioxide."
        ],
        answer: "Switching off the air-conditioner saves electricity, so less fuel is burnt in power stations and less carbon dioxide is released. Taking the MRT means fewer cars are used, so less fuel is burnt and less carbon dioxide traps heat in the air."
      },
      tip: "Name the middle step: less FUEL BURNT. That is where the carbon dioxide comes from.",
      try: { q: "How does recycling paper help to reduce the amount of carbon dioxide in the air?", o: ["Recycled paper absorbs carbon dioxide from the air around it.", "Recycled paper does not burn, so it gives off no carbon dioxide.", "Recycling paper uses up carbon dioxide in the factory machines.", "Fewer trees are cut down, so more trees remain to take in carbon dioxide."], a: 3, why: "Recycling paper means fewer trees are cut down to make new paper, so more plants remain to take in carbon dioxide. Paper itself does not absorb carbon dioxide." }
    }
  ],
  mcq: [
    { q: "Which human activity is the main cause of the haze that sometimes affects Singapore?", o: ["Burning forests to clear land for farming", "Recycling paper and plastic in factories", "Setting up nature reserves in forests", "Replanting mangrove trees along coasts"], a: 0, why: "Haze comes mainly from forest fires started to clear land, and the smoke is blown by wind. The other options help the environment.", lvl: 1 },
    { q: "Which of the following is an example of REUSING?", o: ["Putting drink cans into a recycling bin", "Buying fewer bottled drinks", "Using an empty glass jar to store buttons", "Burning rubbish in an incineration plant"], a: 2, why: "Reusing means using the same item again. Putting cans in a recycling bin is recycling, and buying fewer is reducing.", lvl: 1 },
    { q: "Which gas, released when fuels such as petrol are burnt, traps heat and adds to global warming?", o: ["Oxygen", "Nitrogen", "Hydrogen", "Carbon dioxide"], a: 3, why: "Burning fuels releases carbon dioxide, which traps heat in the air. Oxygen is used up when fuels burn.", lvl: 1 },
    { q: "Sungei Buloh Wetland Reserve is set aside mainly to", o: ["protect the habitats of plants and animals", "store rubbish from the city in landfills", "grow vegetables and fruits for Singapore", "collect and store rainwater for drinking"], a: 0, why: "Sungei Buloh is a nature reserve that protects wetland habitats, e.g. for migratory birds and mangrove animals.", lvl: 1 },
    { q: "The bar graph shows the mass of paper collected for recycling by four classes in one month. Which class collected the most paper?", fig: { type: "bar", title: "Paper collected for recycling", xl: "Class", yl: "Mass of paper (kg)", bars: [["6A", 12], ["6B", 20], ["6C", 8], ["6D", 15]] }, o: ["6A", "6B", "6C", "6D"], a: 1, why: "The tallest bar is 6B at 20 kg.", lvl: 1 },
    { q: "What does it mean when a species is described as ENDANGERED?", o: ["It is dangerous to humans.", "It has no predators.", "All of its members have died.", "It is at risk of becoming extinct."], a: 3, why: "Endangered means very few are left and the species is at risk of dying out. If none are left, it is extinct.", lvl: 1 },
    { q: "Which of the following helps to save water at home?", o: ["Taking shorter showers", "Leaving the tap running while brushing teeth", "Washing the car with a running hose", "Running the washing machine with only one shirt"], a: 0, why: "Shorter showers use less water. The other actions waste water.", lvl: 1 },
    { q: "The flowchart classifies some human activities. Which activity could be X?", fig: { type: "flow", root: "Human activities", node: { q: "Harms the environment?", yes: { q: "Pollutes the air?", yes: "W", no: "X" }, no: "Y" } }, o: ["Burning rubbish in the open", "Planting trees in a park", "Recycling glass bottles", "Throwing litter into a canal"], a: 3, why: "X harms the environment but does not pollute the air: throwing litter into a canal pollutes water. Burning rubbish pollutes the air (W); planting trees and recycling do not harm the environment (Y).", lvl: 1 },

    { q: "The graph shows the forest area of Country P over 30 years. During which period did the forest area decrease the most?", fig: { type: "line", title: "Forest area of Country P", xl: "Year", yl: "Forest area (thousand km²)", pts: [["1990", 50], ["2000", 42], ["2010", 31], ["2020", 25]] }, o: ["1990 to 2000", "2000 to 2010", "2010 to 2020", "The forest area did not change."], a: 1, why: "The decreases are 8, 11 and 6 thousand km². The biggest drop, 11, was from 2000 to 2010.", lvl: 2 },
    { q: "After a hillside forest was cleared, a lot of soil was washed away by rain. Which statement best explains this?", o: ["There were no plant roots to hold the soil together.", "The soil became heavier without trees to shade it.", "More animals moved in and dug holes in the soil.", "Less rain fell on the hillside after the trees were cut."], a: 0, why: "Plant roots hold the soil together. Without them, rainwater washes away the topsoil (soil erosion).", lvl: 2 },
    { q: "Study the food web. Fishermen caught very large numbers of tuna. Which changes are most likely to happen FIRST to the populations of small fish and shark?", fig: { type: "web", links: [["seaweed", "small fish"], ["small fish", "tuna"], ["small fish", "seabird"], ["tuna", "shark"]] }, o: ["Small fish decrease; shark decreases", "Small fish increase; shark increases", "Small fish decrease; shark increases", "Small fish increase; shark decreases"], a: 3, why: "Fewer tuna eat the small fish, so small fish increase. Tuna is the shark’s only food, so the shark has less food and decreases.", lvl: 2 },
    { q: "After an oil spill, the seaweed under a thick layer of oil died. What is the most likely reason?", o: ["The oil layer took away the water that the seaweed needs to survive.", "The oil layer made the water too cold for the seaweed to survive.", "The oil layer blocked sunlight, so the seaweed could not photosynthesise.", "The oil layer gave the seaweed too much carbon dioxide to take in."], a: 2, why: "Oil floats as a layer that blocks sunlight, so seaweed cannot make food by photosynthesis. The seaweed is still surrounded by water.", lvl: 2 },
    { q: "Which actions reduce the amount of carbon dioxide released into the air?\nA Taking the MRT instead of driving\nB Switching off lights when leaving a room\nC Leaving the air-conditioner on overnight in an empty room\nD Walking to a nearby shop instead of taking a taxi", o: ["A and B only", "B and C only", "A, B and D only", "A, C and D only"], a: 2, why: "A, B and D all mean less fuel is burnt (in vehicles or power stations). C wastes electricity, so more fuel is burnt.", lvl: 2 },
    { q: "The graph shows the mass of carbon dioxide given off for each passenger when travelling 1 km. How much less carbon dioxide does one passenger give off per km by taking the bus instead of the car?", fig: { type: "bar", title: "Carbon dioxide given off per passenger per km", xl: "Way of travelling", yl: "Carbon dioxide (g)", bars: [["Car", 170], ["Bus", 90], ["MRT", 40], ["Bicycle", 0]] }, o: ["80 g", "90 g", "130 g", "170 g"], a: 0, why: "170 g − 90 g = 80 g. 130 g is the difference between car and MRT.", lvl: 2 },
    { q: "Why do sea turtles often die when plastic bags are thrown into the sea?", o: ["The bags make the seawater too salty for the turtles to drink.", "Turtles mistake the bags for jellyfish, eat them and cannot digest them.", "The bags give off heat that harms the turtle eggs on the beach.", "The bags take in all the oxygen in the water, so turtles suffocate."], a: 1, why: "Turtles eat jellyfish and may swallow floating plastic bags, which block their gut. Plastic does not decompose or digest.", lvl: 2 },
    { q: "Which of the following is NOT a benefit of replanting mangrove trees along a coast?", o: ["The roots hold the mud and reduce coastal erosion.", "The trees provide habitats for crabs, fish and birds.", "The trees take in carbon dioxide during photosynthesis.", "The trees increase the amount of carbon dioxide in the air."], a: 3, why: "Growing trees take in carbon dioxide by photosynthesis, so they reduce, not increase, carbon dioxide in the air.", lvl: 2 },
    { q: "Why is global warming a threat to low-lying coastal land?", o: ["Warmer air dries out the soil, so the coastal land sinks into the sea.", "Warmer temperatures melt polar ice, so the sea level rises and floods the land.", "Warmer seas have fewer fish, so the tides become higher and flood the land.", "More rain falls only on coastal land, so the rivers there overflow."], a: 1, why: "Global warming melts ice at the Poles, adding water to the sea, so sea levels rise and low-lying land may be flooded.", lvl: 2 },
    { q: "The graph shows the population of a type of fish in a bay. From 2010 onwards the population increased. Which is the most likely reason?", fig: { type: "line", title: "Fish population in a bay", xl: "Year", yl: "Number of fish", pts: [["2000", 900], ["2004", 620], ["2008", 330], ["2010", 200], ["2014", 460], ["2018", 720]] }, o: ["Fishing in the bay was banned or limited in 2010.", "More fishing boats were sent to the bay in 2010.", "An oil spill happened in the bay in 2010.", "The fish’s food in the bay was all eaten up in 2010."], a: 0, why: "The population recovered after 2010, which fits a fishing ban that let the fish reproduce. The other events would make it decrease further.", lvl: 2 },
    { q: "Mrs Lim buys one big bottle of shampoo instead of several small bottles, so less packaging is thrown away. Which of the 3Rs is she practising?", o: ["Recycle", "Reduce", "Reuse", "None of the 3Rs"], a: 1, why: "She uses less packaging in the first place, which is reducing. She is not using an item again (reuse) or making used material into a new product (recycle).", lvl: 2 },
    { q: "Why are laws against poaching important for animals such as the pangolin?", o: ["They stop pangolins from eating too many ants in the forest.", "They make pangolins reproduce faster so there are more babies.", "They reduce the number of pangolins killed, so numbers can recover.", "They move pangolins to colder countries where they are safer."], a: 2, why: "Poaching kills pangolins faster than they can reproduce. Laws that stop poaching let the population recover and prevent extinction.", lvl: 2 },
    { q: "Pesticide sprayed on a farm was washed by rain into a nearby river. Soon after, many fish in the river died. What type of pollution is this, and how did it harm the fish?", o: ["Air pollution; the pesticide made the air hot.", "Land pollution; the fish ate the soil.", "Water pollution; the pesticide made the air above the river dirty.", "Water pollution; the chemicals poisoned the fish."], a: 3, why: "Chemicals washed into a river pollute the water and can poison the organisms living in it.", lvl: 2 },
    { q: "The set-ups were used to find out if an oil layer on water affects a water plant. Which two set-ups should be compared?", fig: { type: "setups", items: [{ label: "A", icon: "beaker", lines: ["Water plant", "Layer of oil", "In sunlight"] }, { label: "B", icon: "beaker", lines: ["Water plant", "No oil", "In sunlight"] }, { label: "C", icon: "beaker", lines: ["Water plant", "No oil", "In the dark"] }, { label: "D", icon: "beaker", lines: ["No water plant", "Layer of oil", "In sunlight"] }] }, o: ["A and B", "A and C", "B and C", "A and D"], a: 0, why: "Only the oil layer should differ. A and B differ only in the oil; A and C differ in both oil and light; D has no plant.", lvl: 2 },

    { q: "Study the graph of carbon dioxide in the air.\nA The amount of carbon dioxide increased throughout the period.\nB The increase from 2000 to 2020 was greater than the increase from 1960 to 1980.\nC The trend is likely due to more burning of fuels and deforestation.\nWhich statements are correct?", fig: { type: "line", title: "Carbon dioxide in the air", xl: "Year", yl: "Carbon dioxide (parts per million)", pts: [["1960", 317], ["1980", 339], ["2000", 370], ["2020", 414]] }, o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 3, why: "The line rises throughout (A). 414 − 370 = 44 is greater than 339 − 317 = 22 (B). Burning fuels and deforestation raise carbon dioxide (C).", lvl: 3 },
    { q: "Three trays of soil were tilted at the same angle and the same amount of water was poured on each. The graph shows the mass of soil washed off. Which conclusion is best supported?", fig: { type: "bar", title: "Soil washed off each tray", xl: "Tray", yl: "Mass of soil (g)", bars: [["A: grass", 6], ["B: bare soil", 42], ["C: dead leaves", 18]] }, o: ["Plants help to hold the soil and reduce soil erosion.", "Dead leaves protect soil better than living grass.", "Bare soil holds more water than soil with grass.", "Grass makes the soil heavier so it cannot move."], a: 0, why: "The tray with grass lost the least soil, bare soil lost the most. Roots hold soil, and plant cover reduces erosion. Dead leaves lost more soil than grass.", lvl: 3 },
    { q: "Recycling paper helps to slow down global warming. Which statement best explains why?", o: ["Recycled paper takes in carbon dioxide from the air around it.", "Recycled paper does not give off carbon dioxide when burnt.", "Fewer trees are cut down, so more trees remain to take in carbon dioxide.", "Recycled paper decomposes faster in landfills than new paper does."], a: 2, why: "Recycling means fewer trees are cut down for new paper, so more plants take in carbon dioxide. Paper itself does not absorb carbon dioxide.", lvl: 3 },
    { q: "Study the food web. Poachers killed most of the tigers in a forest. Which is most likely to happen to the grass after some time?", fig: { type: "web", links: [["grass", "deer"], ["grass", "rabbit"], ["deer", "tiger"], ["rabbit", "tiger"], ["rabbit", "eagle"]] }, o: ["Increase, because tigers no longer trample and flatten it", "Stay the same, because tigers do not eat grass at all", "Decrease, because more deer and rabbits survive to eat it", "Increase, because more eagles now eat the rabbits"], a: 2, why: "Fewer tigers means fewer deer and rabbits are eaten, so these grass-eaters increase and eat more grass.", lvl: 3 },
    { q: "Fishermen are told to use nets with larger holes. How does this help to keep the fish population from decreasing?", o: ["Larger nets catch more adult fish so there is less competition.", "Young fish can escape, grow into adults and reproduce.", "Larger holes let more oxygen into the water.", "Fish swim more slowly into nets with larger holes."], a: 1, why: "Young fish slip through, survive to become adults and reproduce, so new fish replace those caught.", lvl: 3 },
    { q: "Which is NOT a correct reason why clearing and burning a forest increases the amount of carbon dioxide in the air?", o: ["Burning the trees releases carbon dioxide.", "There are fewer plants to take in carbon dioxide during photosynthesis.", "Trees give out carbon dioxide during photosynthesis, so the forest must be cleared.", "The land that replaces the forest often has fewer plants."], a: 2, why: "Photosynthesis takes IN carbon dioxide; it does not give it out. The other three are correct reasons.", lvl: 3 },
    { q: "The graph shows the number of a type of hornbill in a nature reserve. Nest boxes were put up in the reserve in 2008. Which statement is best supported by the graph?", fig: { type: "bar", title: "Hornbills in a nature reserve", xl: "Year", yl: "Number of hornbills", bars: [["2004", 6], ["2008", 8], ["2012", 21], ["2016", 38]] }, o: ["The nest boxes caused the hornbills to lay more eggs per nest.", "The number of hornbills increased faster after the nest boxes were put up.", "Hornbills stopped being endangered in 2012.", "Hornbills were poached before 2008."], a: 1, why: "The number rose by only 2 from 2004 to 2008 but by 13 and 17 after 2008. The graph does not show eggs per nest, endangered status or poaching.", lvl: 3 },
    { q: "Singapore generates most of its electricity by burning natural gas. When a family uses less electricity, which of the following happen?\nA Less fuel is burnt in power stations.\nB Less carbon dioxide is released.\nC More trees grow in the forests.\nD Fewer harmful gases are released into the air.", o: ["A and B only", "C and D only", "A, B and D only", "A, B, C and D"], a: 2, why: "Less electricity used means less fuel burnt, so less carbon dioxide and fewer harmful gases. It does not directly make more trees grow.", lvl: 3 },
    { q: "Study the food web of a mangrove. The mangrove trees were cleared to build a road. Which organism is likely to be affected LAST?", fig: { type: "web", links: [["mangrove leaves", "crab"], ["mangrove leaves", "snail"], ["crab", "mudskipper"], ["snail", "mudskipper"], ["mudskipper", "heron"]] }, o: ["Crab", "Snail", "Mudskipper", "Heron"], a: 3, why: "Crabs and snails lose their food first, then mudskippers lose their food, and the heron is affected only after the mudskipper decreases.", lvl: 3 },
    { q: "In the Venn diagram, activities are grouped by whether they reduce rubbish and whether they protect habitats. Which activity could be X?", fig: { type: "venn", a: "Reduces rubbish", b: "Protects habitats", onlyA: ["reusing jars"], both: ["X"], onlyB: ["nature reserves"], neither: ["driving a car"] }, o: ["Replanting mangroves", "Using a jam jar as a pen holder", "Recycling used paper", "Setting up a marine park"], a: 2, why: "Recycling paper reduces rubbish AND means fewer trees are cut down, so forest habitats are protected. Replanting mangroves and marine parks protect habitats but do not reduce rubbish; reusing a jar only reduces rubbish.", lvl: 3 },
    { q: "Some rainforest is cleared for an oil palm plantation of the same area. Which statement best explains why many forest animals die out in the area, even though there are still many plants?", o: ["Oil palms give out poisonous gases that kill the animals.", "Only one type of plant grows there, so many animals lose food and shelter.", "Oil palms take in all the oxygen, so the animals cannot breathe.", "The plantation is too cold for the forest animals to live in."], a: 1, why: "A rainforest has many kinds of plants that give different animals food and shelter. A plantation of one plant cannot support them, so habitats are lost.", lvl: 3 },
    { q: "A girl says: “Using a reusable metal straw is better for the environment than using a plastic straw once and recycling it.” Which is the best reason to support her?", o: ["Metal straws can be burnt safely after they are used.", "Recycling a plastic straw uses up no energy at all.", "Plastic straws decompose quickly once they are in the sea.", "Reusing one straw means fewer new straws are made and thrown away."], a: 3, why: "Reusing reduces the number of straws made and the rubbish produced. Recycling still uses energy, and plastic does not decompose quickly.", lvl: 3 },

    { q: "Study the food web. Farmers used a chemical that killed most of the grasshoppers. After some time, the number of snakes decreased only slightly, but the number of frogs decreased sharply. Which statement best explains this?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "mouse"], ["grasshopper", "frog"], ["frog", "snake"], ["mouse", "snake"]] }, o: ["Frogs eat only grasshoppers, but snakes can also eat mice.", "Snakes eat grasshoppers, so they had more food.", "Mice eat frogs, so the frogs decreased.", "The chemical killed the snakes but not the frogs."], a: 0, why: "The grasshopper is the frog’s only food, so frogs decrease sharply. Snakes lose some food (fewer frogs) but can still eat mice.", lvl: 4 },
    { q: "Two sealed glass containers, P and Q, were placed under identical lamps. P contained ordinary air and Q contained air with extra carbon dioxide. After 30 minutes, the thermometer in Q showed a higher temperature. What does this experiment model?", fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["Ordinary air", "Thermometer", "Under lamp"] }, { label: "Q", icon: "jar", lines: ["Extra carbon dioxide", "Thermometer", "Under lamp"] }] }, o: ["Carbon dioxide gives off heat by itself, even without the lamp.", "Air with more carbon dioxide traps more heat, as in global warming.", "The lamp in Q gave out more heat than the lamp in P.", "Carbon dioxide blocks light from the lamp, so Q became warmer."], a: 1, why: "Only the amount of carbon dioxide differed, and Q got warmer, so more carbon dioxide traps more heat, as in global warming. The lamps were identical.", lvl: 4 },
    { q: "The steps below link a family’s use of an air-conditioner to rising sea levels.\nP More carbon dioxide is released.\nQ More fuel is burnt in the power station.\nR Ice at the Poles melts.\nS More heat is trapped and the Earth’s temperature rises.\nWhich is the correct order?", o: ["P, Q, S, R", "Q, S, P, R", "Q, P, S, R", "Q, P, R, S"], a: 2, why: "More electricity → more fuel burnt (Q) → more carbon dioxide (P) → more heat trapped (S) → ice melts, raising sea levels (R).", lvl: 4 },
    { q: "The graph shows the mass of fish caught each year in a sea, even though the number of fishing boats increased every year. What does this suggest about the fish population?", fig: { type: "line", title: "Fish caught each year", xl: "Year", yl: "Mass of fish caught (thousand tonnes)", pts: [["1995", 80], ["2000", 95], ["2005", 88], ["2010", 60], ["2015", 34]] }, o: ["The fish population increased because more boats were used.", "Fish were caught faster than they could reproduce, so the population decreased.", "The fish population stayed the same; the boats were less efficient.", "The fish moved away because the water became colder."], a: 1, why: "More boats but a falling catch after 2000 means fewer fish were left: they were caught faster than they could reproduce (overfishing).", lvl: 4 },
    { q: "Study the food web. People collected large numbers of starfish as souvenirs. Which statements are likely to be true after some time?\nA The number of mussels increases at first.\nB The seaweed may decrease.\nC The number of sea otters is not affected at all.", fig: { type: "web", links: [["seaweed", "sea urchin"], ["plankton", "mussel"], ["mussel", "starfish"], ["sea urchin", "starfish"], ["sea urchin", "sea otter"]] }, o: ["A only", "C only", "B and C only", "A and B only"], a: 3, why: "Fewer starfish eat mussels and sea urchins, so both increase at first (A); more sea urchins eat more seaweed (B). With more sea urchins, sea otters have more food, so they ARE affected (C is wrong).", lvl: 4 },
    { q: "Country R cleared 20 km² of forest and planted 20 km² of young trees elsewhere in the same year. A student says the amount of carbon dioxide taken in by plants in Country R stays the same. Why is the student most likely wrong?", o: ["Young trees have fewer leaves, so they take in much less carbon dioxide than the forest did.", "Young trees do not photosynthesise until they are fully grown.", "Forests take in oxygen, not carbon dioxide, so the amount does not matter.", "Young trees give out more carbon dioxide than they take in during the day."], a: 0, why: "Small young trees have far fewer leaves than a mature forest, so they photosynthesise less and take in much less carbon dioxide for many years. They do photosynthesise, and in the day they take in more carbon dioxide than they give out.", lvl: 4 }
  ],
  tf: [
    { s: "Cutting down forests can cause animals to lose their habitats.", a: true, why: "Forests provide food and shelter for many animals; clearing them removes their habitats." },
    { s: "Deforestation increases carbon dioxide in the air because trees give out carbon dioxide during photosynthesis.", a: false, why: "Photosynthesis takes IN carbon dioxide. With fewer trees, less carbon dioxide is taken in." },
    { s: "Carbon dioxide in the air traps heat.", a: true, why: "That is why more carbon dioxide leads to more heat being trapped and global warming." },
    { s: "Global warming is caused by carbon dioxide being poisonous to plants.", a: false, why: "Plants use carbon dioxide; global warming happens because more carbon dioxide traps more heat." },
    { s: "Putting old newspapers into a recycling bin is an example of reusing.", a: false, why: "The paper will be made into new products, so it is recycling." },
    { s: "An oil spill can stop water plants from photosynthesising.", a: true, why: "The oil layer blocks sunlight from reaching the water plants." },
    { s: "An endangered species is one that no longer exists.", a: false, why: "Endangered means at risk of extinction; a species that no longer exists is extinct." },
    { s: "Plastic takes a very long time to decompose.", a: true, why: "Plastic is not easily broken down by decomposers, so it stays in the environment for many years." },
    { s: "Saving electricity at home has no effect on air pollution because homes do not burn fuels.", a: false, why: "Power stations burn fuels to generate electricity, so saving electricity means less fuel burnt and less pollution." },
    { s: "Plant roots help to hold the soil together and reduce soil erosion.", a: true, why: "Without roots, rainwater easily washes the topsoil away." },
    { s: "Haze in Singapore is mainly caused by cars in Singapore.", a: false, why: "Haze comes mainly from forest fires in the region, blown here by the wind." },
    { s: "Overfishing means catching fish faster than they can reproduce.", a: true, why: "The population cannot replace the fish caught, so it keeps decreasing." },
    { s: "Removing a predator from a food web always makes its prey population increase forever.", a: false, why: "The prey increases at first but may then run out of food and decrease." },
    { s: "Bukit Timah Nature Reserve helps to protect many species of plants and animals.", a: true, why: "Nature reserves protect habitats so the organisms there do not become extinct." },
    { s: "Global warming can cause sea levels to rise.", a: true, why: "Higher temperatures melt ice at the Poles, adding water to the sea." },
    { s: "Planting new trees helps to reduce the amount of carbon dioxide in the air.", a: true, why: "The trees take in carbon dioxide during photosynthesis as they grow." },
    { s: "Poaching is allowed as long as the animals are sold as pets.", a: false, why: "Poaching is illegal hunting or collecting; selling the animals as pets still reduces wild populations." },
    { s: "Human activities only have negative effects on the environment.", a: false, why: "Conservation, replanting, nature reserves and the 3Rs are positive impacts." },
    { s: "Taking public transport instead of driving helps to reduce the carbon dioxide released per person.", a: true, why: "A bus or train carries many people, so less fuel is burnt per person." },
    { s: "Recycling aluminium cans means the cans are washed and used again as the same cans.", a: false, why: "That would be reusing; recycling melts the metal to make new products." }
  ],
  sort: [
    { title: "Sort these human activities by their impact on the environment", groups: ["Positive impact", "Negative impact"], items: [["setting up nature reserves", 0], ["replanting mangroves", 0], ["recycling paper", 0], ["passing laws against poaching", 0], ["burning forests to clear land", 1], ["dumping chemicals into rivers", 1], ["overfishing", 1], ["littering on beaches", 1]] },
    { title: "Sort these actions into reduce, reuse and recycle", groups: ["Reduce", "Reuse", "Recycle"], items: [["buying fewer bottled drinks", 0], ["printing on both sides of paper", 0], ["bringing your own bag instead of taking a plastic bag", 0], ["using a jam jar as a pencil holder", 1], ["giving old clothes to a younger cousin", 1], ["refilling a water bottle", 1], ["putting cans in a recycling bin", 2], ["making new paper from old newspapers", 2], ["melting glass bottles to make new glass", 2]] },
    { title: "Sort these by the main type of pollution they cause", groups: ["Air pollution", "Water pollution", "Land pollution"], items: [["smoke from factory chimneys", 0], ["exhaust fumes from cars", 0], ["forest fires causing haze", 0], ["oil leaking from a tanker", 1], ["factory waste flowing into a river", 1], ["sewage discharged into the sea", 1], ["rubbish dumped in a forest", 2], ["litter left at a park", 2], ["broken glass buried in a field", 2]] }
  ],
  oe: [
    { q: "State two reasons why people cut down forests.", marks: 2, kw: [["housing", "houses", "homes", "build", "land"], ["farm", "timber", "wood", "plantation", "crops"]], model: "People cut down forests to clear land for housing and roads, and to get timber or land for farming." },
    { q: "Explain how deforestation can lead to an increase in the amount of carbon dioxide in the air.", marks: 2, kw: [["fewer plants", "fewer trees", "less plants", "less trees"], ["take in carbon dioxide", "takes in carbon dioxide", "absorb carbon dioxide", "photosynth"]], model: "There are fewer trees to take in carbon dioxide during photosynthesis, so more carbon dioxide remains in the air." },
    { q: "Study the graph of the forest area of Country P.\n(a) Describe how the forest area changed from 1990 to 2020.\n(b) State one effect of this change on the animals in the forest.\n(c) State one effect of this change on the soil.", fig: { type: "line", title: "Forest area of Country P", xl: "Year", yl: "Forest area (thousand km²)", pts: [["1990", 50], ["2000", 42], ["2010", 31], ["2020", 25]] }, marks: 3, kw: [["decrease", "decreased", "fell", "halved"], ["habitat", "shelter", "food"], ["erosion", "washed away", "washes away"]], model: "(a) The forest area decreased from 50 to 25 thousand km². (b) The animals lose their habitats, food and shelter, so their populations decrease. (c) Without roots to hold the soil, the soil is washed away by rain (soil erosion)." },
    { q: "Study the food web. Fishermen caught large numbers of the grouper.\n(a) Predict what will happen to the parrotfish population at first. Explain.\n(b) Explain why the shark population may decrease.", fig: { type: "web", links: [["seaweed", "parrotfish"], ["seaweed", "sea urchin"], ["parrotfish", "grouper"], ["sea urchin", "grouper"], ["grouper", "shark"]] }, marks: 3, kw: [["increase"], ["fewer grouper", "less grouper", "not eaten", "fewer are eaten", "fewer parrotfish are eaten", "less parrotfish are eaten"], ["less food", "only food", "lack of food", "not enough food"]], model: "(a) The parrotfish population will increase at first, because there are fewer groupers, so fewer parrotfish are eaten. (b) The grouper is the shark’s only food, so the shark has less food and may decrease." },
    { q: "An oil tanker leaked oil into the sea.\n(a) Explain why seaweed under the oil died.\n(b) Explain why sea birds covered with oil may die.\n(c) Fish feed on the seaweed. Explain how the fish population is affected.", marks: 4, kw: [["block", "cannot reach", "prevent"], ["photosynth", "make food"], ["feather"], ["less food", "not enough food", "lack of food"]], model: "(a) The oil layer blocks sunlight, so the seaweed cannot photosynthesise to make food and dies. (b) Oil coats their feathers, so they cannot fly to find food. (c) There is less seaweed, so the fish have less food and their population decreases." },
    { q: "Explain how burning fuels in vehicles can lead to global warming.", marks: 2, kw: [["carbon dioxide"], ["trap", "heat"]], model: "Burning fuels releases carbon dioxide into the air. More carbon dioxide traps more heat, so the Earth’s temperature rises." },
    { q: "Study the graph of carbon dioxide in the air.\n(a) By how much did the amount of carbon dioxide increase from 1960 to 2020?\n(b) Explain how this change affects the Earth’s temperature.\n(c) State one effect of the change in (b) on countries on low-lying coasts.", fig: { type: "line", title: "Carbon dioxide in the air", xl: "Year", yl: "Carbon dioxide (parts per million)", pts: [["1960", 317], ["1980", 339], ["2000", 370], ["2020", 414]] }, marks: 3, kw: [["97"], ["trap", "more heat"], ["sea level", "flood"]], model: "(a) 97 parts per million. (b) More carbon dioxide traps more heat, so the Earth’s temperature rises. (c) Ice at the Poles melts, so sea levels rise and low-lying land may be flooded." },
    { q: "Three trays of soil were tilted at the same angle and the same amount of water was poured on each.\n(a) Which tray lost the most soil?\n(b) Explain why tray A lost the least soil.\n(c) Using your answer to (b), explain why cutting down forests on hillsides can be dangerous.", fig: { type: "bar", title: "Soil washed off each tray", xl: "Tray", yl: "Mass of soil (g)", bars: [["A: grass", 6], ["B: bare soil", 42], ["C: dead leaves", 18]] }, marks: 3, kw: [["tray b", "bare"], ["root"], ["landslide", "erosion", "washed away"]], model: "(a) Tray B, the bare soil. (b) The roots of the grass hold the soil together, so less soil is washed away. (c) Without roots to hold the soil, heavy rain washes the soil away, causing soil erosion and landslides." },
    { q: "Nature reserves such as Sungei Buloh Wetland Reserve are protected by law. Explain how this helps endangered species.", marks: 2, kw: [["habitat", "food and shelter"], ["extinct", "survive", "reproduce"]], model: "The reserve protects the habitats where the animals find food and shelter, so they can survive and reproduce and do not become extinct." },
    { q: "Mei Ling switches off the lights and fan whenever she leaves a room.\n(a) Explain how this helps to reduce the amount of carbon dioxide in the air.\n(b) Suggest one other way she can reduce the carbon dioxide released when she travels to school.", marks: 3, kw: [["save electricity", "saves electricity", "less electricity"], ["less fuel", "fewer fuel"], ["public transport", "bus", "mrt", "walk", "cycle", "bicycle"]], model: "(a) She saves electricity, so less fuel is burnt in power stations and less carbon dioxide is released. (b) She can take public transport such as the bus or MRT, or walk or cycle, instead of being driven." },
    { q: "The graph shows the population of a type of fish in a bay. A fishing ban started in 2010.\n(a) Describe how the fish population changed from 2000 to 2010, and suggest why.\n(b) Explain why the population increased after 2010.", fig: { type: "line", title: "Fish population in a bay", xl: "Year", yl: "Number of fish", pts: [["2000", 900], ["2004", 620], ["2008", 330], ["2010", 200], ["2014", 460], ["2018", 720]] }, marks: 3, kw: [["decrease", "decreased", "fell"], ["overfish", "caught faster", "too many fish were caught"], ["reproduce", "breed"]], model: "(a) The population decreased from 900 to 200, because of overfishing: fish were caught faster than they could reproduce. (b) With fewer fish caught, more fish survived to reproduce, so the population increased." },
    { q: "Two sealed containers were set up under identical lamps. P had ordinary air; Q had air with extra carbon dioxide. After 30 minutes, the thermometer in Q showed a higher temperature.\n(a) What was the variable changed in this experiment?\n(b) What conclusion can be drawn?\n(c) Use this conclusion to explain why burning more fuels on Earth may cause the ice at the Poles to melt.", fig: { type: "setups", items: [{ label: "P", icon: "jar", lines: ["Ordinary air", "Thermometer", "Under lamp"] }, { label: "Q", icon: "jar", lines: ["Extra carbon dioxide", "Thermometer", "Under lamp"] }] }, marks: 4, x: 1, kw: [["amount of carbon dioxide"], ["trap", "more heat"], ["releases carbon dioxide", "release carbon dioxide", "more carbon dioxide"], ["temperature rise", "temperature increase", "warmer", "hotter"]], model: "(a) The amount of carbon dioxide in the air. (b) Air with more carbon dioxide traps more heat. (c) Burning fuels releases carbon dioxide, so more carbon dioxide in the air traps more heat. The Earth’s temperature rises and becomes warmer, so the ice melts." },
    { q: "Study the food web. Poachers killed most of the tigers.\n(a) Explain why the grass population may decrease after some time.\n(b) The eagle population increased at first. Explain why.\n(c) Suggest one way to protect the tigers.", fig: { type: "web", links: [["grass", "deer"], ["grass", "rabbit"], ["deer", "tiger"], ["rabbit", "tiger"], ["rabbit", "eagle"]] }, marks: 4, x: 1, kw: [["more deer", "more rabbit", "deer and rabbits increase", "deer and rabbit population increase"], ["eat more grass", "more grass is eaten", "eaten more"], ["more rabbits", "more food", "less competition", "fewer tigers eating rabbits"], ["law", "nature reserve", "ban", "patrol", "protect"]], model: "(a) Fewer deer and rabbits are eaten by tigers, so there are more deer and rabbits, and they eat more grass. (b) With fewer tigers eating rabbits, there are more rabbits, so the eagles have more food. (c) Pass laws against poaching and protect their habitat in a nature reserve." },
    { q: "A company says: “We cut down 20 km² of old forest, but we planted 20 km² of young trees, so there is no harm to the environment.”\n(a) Explain why the young trees take in less carbon dioxide than the old forest did.\n(b) Give one other reason why the forest animals may still be harmed.", marks: 3, x: 1, kw: [["fewer leaves", "less leaves", "smaller", "small"], ["photosynth"], ["habitat", "food and shelter", "different plants", "one type"]], model: "(a) The young trees are small with fewer leaves, so they carry out less photosynthesis and take in less carbon dioxide. (b) The animals lose their habitat: the young trees cannot yet give them the food and shelter that the old forest provided." }
  ],
  doc: [
    { q: "Explain how deforestation leads to more carbon dioxide in the air.", marks: 2, answers: ["Trees give out carbon dioxide, so cutting them down is bad.", "There are fewer trees to take in carbon dioxide during photosynthesis, so more carbon dioxide stays in the air.", "Fewer trees give out oxygen, so the air becomes polluted."], best: 1, why: "Answer 2 links fewer trees to less carbon dioxide taken in by photosynthesis. Answer 1 has the science backwards: photosynthesis takes in carbon dioxide. Answer 3 talks about oxygen and does not answer the question about carbon dioxide." },
    { q: "An oil spill covered the sea surface. Explain why the seagrass below died.", marks: 2, answers: ["The oil layer blocked sunlight, so the seagrass could not photosynthesise to make food.", "The oil was dirty.", "The seagrass could not get water because of the oil."], best: 0, why: "Answer 1 gives the full chain: blocks sunlight → no photosynthesis → no food. Answer 2 is too vague. Answer 3 is wrong: the seagrass is still surrounded by water." },
    { q: "How does switching off lights help to slow down global warming?", marks: 2, answers: ["It saves electricity, which is good for the Earth.", "It makes the room cooler.", "It saves electricity, so less fuel is burnt in power stations and less carbon dioxide is released."], best: 2, why: "Answer 3 names the missing link: less fuel burnt, so less carbon dioxide. Answer 1 is too vague (“good for the Earth”). Answer 2 is about room temperature, not global warming." },
    { q: "In a food web, frogs eat only grasshoppers. Farmers killed most of the grasshoppers with a chemical. Explain what happens to the frogs.", marks: 2, answers: ["The frogs decrease.", "The frogs decrease because they are sad.", "The frog population decreases because the grasshopper is their only food, so they have less food."], best: 2, why: "Answer 3 gives the change and the reason (less food). Answer 1 has no reason. Answer 2 gives a non-scientific reason." },
    { q: "Explain how recycling paper helps the environment.", marks: 2, answers: ["Recycling is good because it saves the Earth.", "Fewer trees are cut down, so animals keep their habitats and more trees take in carbon dioxide.", "Recycled paper is cheaper."], best: 1, why: "Answer 2 links recycling to fewer trees cut down, then to habitats and carbon dioxide. Answer 1 is too vague. Answer 3 is about cost, not the environment." }
  ]
};
