window.LBX = window.LBX || {};
// PSLE Crossover extension — wider integrated P3–P6 questions (light, heat, matter, transport, life cycles, habitats, forces, magnets)
LBX["p6-mixed"] = {
  notes: [
    { h: "Light and heat in everyday objects", t: "Light travels in straight lines. We see an object when light from a light source is reflected off the object and enters our eyes. An opaque object blocks light, so a shadow forms behind it; translucent materials let some light through. Heat flows from a hotter place to a colder place: metals are good conductors of heat, while plastic, wood, felt and trapped air are poor conductors of heat.", kw: ["straight lines", "reflected", "enters our eyes", "opaque", "good conductor of heat", "poor conductor of heat"] },
    { h: "Transport in plants and in humans", t: "In a plant, the water-carrying tubes carry water and mineral salts from the roots up the stem to the leaves, and the food-carrying tubes carry food made in the leaves to all other parts. In humans, digestive juices break down food into simpler substances in the mouth, stomach and small intestine; the digested food is absorbed into the blood in the small intestine. The heart pumps the blood through the blood vessels to transport digested food and oxygen to all cells.", kw: ["water-carrying tubes", "food-carrying tubes", "digestive juices", "simpler substances", "absorbed into the blood"] },
    { h: "Habitats, populations and adaptations", t: "A population is a group of organisms of ONE kind living in the same habitat at the same time; a community is all the populations living together in a habitat. Factors such as light, temperature, water and air affect which organisms can live there. Adaptations help organisms survive: structural adaptations are body features (webbed feet, spines, thick fur), while behavioural adaptations are ways an organism acts (hunting at night, migrating, rolling into a ball).", kw: ["population", "community", "structural adaptation", "behavioural adaptation", "survive"] }
  ],
  traps: [
    "We see a book because light travels from our eyes to the book → light from a light source is reflected off the book and enters our eyes.",
    "A metal spoon feels colder than a plastic spoon because it is at a lower temperature → both are at room temperature; metal is a better conductor of heat, so it conducts heat away from your hand faster.",
    "A population is all the living things in a habitat → that is a community; a population is ONE kind of organism living in the same habitat at the same time."
  ],
  lessons: [
    {
      h: "Heat questions: conductor + direction of heat flow",
      concept: "Heat questions in PSLE often hide inside another topic (melting, cooking, keeping food warm). Always say (1) which way heat flows — from the hotter to the colder object — and (2) whether the material is a good or poor conductor of heat, and so whether heat flows through it quickly or slowly. Then link it to the result: melts faster, stays hot longer, cools down faster.",
      example: {
        q: "Two identical ice cubes are placed on a metal tray and a plastic tray of the same size and thickness in the same room. The ice cube on the metal tray melts first. Explain why. (2m)",
        marks: 2,
        think: ["Both trays are at room temperature, which is higher than the temperature of the ice.", "Heat flows from the warmer tray to the colder ice cube.", "Metal is a good conductor of heat; plastic is a poor conductor of heat.", "So heat is conducted from the metal tray to the ice faster, and the ice gains heat faster and melts first."],
        answer: "Metal is a good conductor of heat but plastic is a poor conductor of heat. Heat from the surroundings is conducted through the metal tray to the ice cube faster, so the ice cube on the metal tray gains heat faster and melts first."
      },
      tip: "Never write ‘metal is colder’ or ‘metal gives out cold’. Cold does not flow — heat flows from hotter to colder.",
      try: {
        q: "Four containers of the same size each hold 200 ml of hot water at 80 °C and are left in the same room. Which one will keep the water hottest after 20 minutes?",
        o: ["A thin steel cup without a lid", "A thick polystyrene cup with a lid", "A thin glass cup with a lid", "A thick steel cup without a lid"],
        a: 1,
        why: "Polystyrene is a poor conductor of heat (it traps air), and the lid reduces heat loss from the water surface, so the water loses heat most slowly. Steel is a good conductor of heat."
      }
    },
    {
      h: "Plant transport: which tubes, which direction",
      concept: "Water and mineral salts travel UP from the roots to the leaves in the water-carrying tubes. Food made in the leaves travels to all other parts (including DOWN to the roots) in the food-carrying tubes. In experiments, a coloured dye shows the path of water; removing a ring of the outer layer of a stem removes the food-carrying tubes and blocks food from travelling downwards past the ring.",
      example: {
        q: "A celery stalk with leaves was placed in a beaker of red-coloured water. After 3 hours, red streaks appeared in the leaves.\n(a) Explain how the red colour reached the leaves. (1m)\n(b) State one use of water in the leaves. (1m)",
        marks: 2,
        think: ["The red water enters the cut end of the stalk.", "It travels up the stalk in the water-carrying tubes, which run all the way to the leaves.", "In the leaves, water is used for photosynthesis to make food (and keeps the cells firm)."],
        answer: "(a) The red-coloured water was carried up the stalk in the water-carrying tubes to the leaves. (b) Water is used by the leaves to make food during photosynthesis."
      },
      tip: "Name the tube AND the direction: ‘water-carrying tubes carry water UP from the roots to the leaves’; ‘food-carrying tubes carry food FROM the leaves to other parts’.",
      try: {
        q: "A ring of the outer layer of a tree’s stem, containing the food-carrying tubes, was removed. Weeks later, a swelling formed just ABOVE the ring. Why?",
        o: ["Food made in the leaves could not be carried down past the ring", "Water from the roots could not be carried up past the ring", "Water from the leaves collected in the stem above the ring", "Mineral salts from the soil were trapped in the stem above the ring"],
        a: 0,
        why: "The food-carrying tubes were removed, so food travelling down from the leaves collected above the ring. The water-carrying tubes are deeper inside and were not removed, so water still moved up."
      }
    }
  ],
  mcq: [
    // ---- lvl 1 (5)
    { q: "Jun holds a piece of cardboard between a lit torch and a wall. A dark shadow forms on the wall. Why?", o: ["The cardboard reflects all the light back onto the wall", "Light travels in straight lines and is blocked by the cardboard", "The torch gives out less light when the card is in front of it", "Light bends around the cardboard and darkens the wall"], a: 1, why: "Light travels in straight lines. The opaque cardboard blocks the light, so an area behind it on the wall receives no light: the shadow.", lvl: 1 },
    { q: "The diagram shows the life cycle of an animal. Which animal has a life cycle with this number of stages?", fig: { type: "cycle", stages: ["Egg", "?", "Adult"] }, o: ["Butterfly", "Mosquito", "Cockroach", "Beetle"], a: 2, why: "The cockroach has a three-stage life cycle: egg, nymph, adult. The butterfly, mosquito and beetle have four stages (with a pupa).", lvl: 1 },
    { q: "Which of the following is NOT an effect a force can have on an object?", o: ["Changing the mass of the object", "Changing the shape of the object", "Changing the direction of a moving object", "Making a stationary object start to move"], a: 0, why: "A force can move a stationary object, change the speed or direction of a moving object, or change its shape. It does not change the amount of matter (mass) in the object.", lvl: 1 },
    { q: "Which material is the best conductor of heat to use for the base of a cooking pot?", o: ["Wood", "Plastic", "Glass", "Copper"], a: 3, why: "Copper is a metal and a good conductor of heat, so heat from the stove is conducted quickly to the food. Wood, plastic and glass are poor conductors of heat.", lvl: 1 },
    { q: "A school pond has 30 guppies, 12 frogs, many water lilies and some dragonfly nymphs. Which of these is a population?", o: ["The guppies and the frogs", "All the living things in the pond", "The pond water and the plants", "The 30 guppies in the pond"], a: 3, why: "A population is a group of ONE kind of organism living in the same place at the same time. All the living things together form a community.", lvl: 1 },

    // ---- lvl 2 (8)
    { q: "Study the circuit. All the bulbs were lit. Then bulb C fused. Which bulb(s) will still light?", fig: { type: "circuit", cells: 2, main: [{ k: "bulb", label: "A" }], branches: [[{ k: "bulb", label: "B" }], [{ k: "bulb", label: "C" }]] }, o: ["A only", "B only", "A and B only", "None of the bulbs"], a: 2, why: "B and C are in parallel, so B still has its own closed path. A is in the main circuit shared by both branches, and the path through A and B is still closed.", lvl: 2 },
    { q: "Hot water at 90 °C was poured into four cups of the same size and thickness, made of different materials, without lids. Study the graph of the water temperature after 10 minutes. Which cup is made of the best conductor of heat?", fig: { type: "bar", xl: "Material of cup", yl: "Temperature after 10 min (°C)", bars: [["Steel", 45], ["Plastic", 62], ["Glass", 55], ["Polystyrene", 72]] }, o: ["Steel", "Plastic", "Glass", "Polystyrene"], a: 0, why: "The water in the steel cup had the lowest temperature, so it lost heat the fastest: steel conducted heat away from the water most quickly.", lvl: 2 },
    { q: "Study the diagram of the human digestive system. In which labelled part does NO digestion of food take place?", fig: { type: "organs", system: "digestive", mark: { mouth: "A", gullet: "B", stomach: "C", small_intestine: "D" } }, o: ["A", "B", "C", "D"], a: 1, why: "B is the gullet, which only moves food from the mouth to the stomach. Digestive juices act in the mouth (A), stomach (C) and small intestine (D).", lvl: 2 },
    { q: "Which statement is true of sexual reproduction in BOTH flowering plants and humans?", o: ["The fertilised egg develops inside a womb", "Fertilisation happens outside the body in water", "The young receives genetic information from one parent", "A male reproductive cell fuses with a female reproductive cell"], a: 3, why: "In both, fertilisation is the fusing of a male reproductive cell with a female reproductive cell (egg cell), so the young gets genetic information from both parents. Plants have no womb.", lvl: 2 },
    { q: "A syringe is filled with air and its nozzle is sealed. The plunger can still be pushed in a little. This shows that air", o: ["has a definite volume", "has no mass", "can be compressed", "has a definite shape"], a: 2, why: "The same amount of air is pushed into a smaller space, so air can be compressed. Gases have no definite volume or shape, and air does have mass.", lvl: 2 },
    { q: "Different loads were hung from a spring and its extension (how much longer it became) was measured. Study the graph. What will the extension be with a 250 g load?", fig: { type: "line", xl: "Load (g)", yl: "Extension of spring (cm)", pts: [["0", 0], ["100", 2], ["200", 4], ["300", 6], ["400", 8]] }, o: ["4 cm", "6 cm", "2.5 cm", "5 cm"], a: 3, why: "The spring stretches 2 cm for every 100 g. 250 g is halfway between 200 g (4 cm) and 300 g (6 cm), so the extension is 5 cm.", lvl: 2 },
    { q: "Which is a BEHAVIOURAL adaptation that helps an animal survive in a hot, dry desert?", o: ["A camel storing fat in the hump on its back", "A desert rat staying in its burrow during the day", "A cactus having sharp spines in place of leaves", "A lizard having thick, scaly skin"], a: 1, why: "Staying in a cool burrow in the hot day is something the rat DOES: a behavioural adaptation. The hump, spines and scaly skin are body features (structural adaptations), and a cactus is not an animal.", lvl: 2 },
    { q: "Study the classification key. Which organisms could be P, Q, R and S?", fig: { type: "flow", root: "Organisms", node: { q: "Makes its own food?", yes: { q: "Has flowers?", yes: "P", no: "Q" }, no: { q: "Reproduces by spores?", yes: "R", no: "S" } } }, o: ["P: hibiscus, Q: fern, R: mushroom, S: cat", "P: fern, Q: hibiscus, R: mushroom, S: cat", "P: hibiscus, Q: moss, R: cat, S: mushroom", "P: mushroom, Q: fern, R: hibiscus, S: cat"], a: 0, why: "Hibiscus makes food and flowers (P); a fern makes food but has no flowers (Q); a mushroom cannot make food and reproduces by spores (R); a cat does neither (S).", lvl: 2 },

    // ---- lvl 3 (7)
    { q: "Study the food web. P is a plant. How many food chains are there, and which organisms are found in ALL of them?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["Q", "S"], ["R", "S"], ["R", "T"], ["S", "U"], ["T", "U"]] }, o: ["4 chains; P and S", "3 chains; R and U", "3 chains; P and U", "4 chains; P only"], a: 2, why: "The chains are P→Q→S→U, P→R→S→U and P→R→T→U. Only P and U appear in all three; R is missing from the first chain and S from the third.", lvl: 3 },
    { q: "A lamp shone on sheets of different materials, and a light sensor behind each sheet measured the light passing through. Study the graph. Which statement is correct?", fig: { type: "bar", xl: "Material", yl: "Light reading (units)", bars: [["Clear plastic", 95], ["Tracing paper", 40], ["Frosted glass", 55], ["Cardboard", 0]] }, o: ["Tracing paper lets more light through than frosted glass", "Cardboard is opaque, so it would cast the darkest shadow", "Clear plastic blocks most of the light shining on it", "Frosted glass is opaque because it lets some light through"], a: 1, why: "No light passed through the cardboard, so it is opaque and casts the darkest shadow. Tracing paper (40) let through less than frosted glass (55); frosted glass is translucent, not opaque.", lvl: 3 },
    { q: "Study the circuit. All three switches are open. Tom wants ONLY bulb B to light. Which switches should he close?", fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S1", open: true }], branches: [[{ k: "bulb", label: "A" }, { k: "switch", label: "S2", open: true }], [{ k: "bulb", label: "B" }, { k: "switch", label: "S3", open: true }]] }, o: ["S3 only", "S2 and S3 only", "S1, S2 and S3", "S1 and S3 only"], a: 3, why: "S1 is in the main circuit shared by both branches, so it must be closed. Closing S3 completes B’s branch; S2 stays open so A’s branch remains an open circuit.", lvl: 3 },
    { q: "Four identical ring magnets are placed on a wooden rod as shown (A at the bottom). The top face of A is an N pole. Which TWO rings have an N pole on their TOP face?", fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }, { label: "D", top: "?" }], gaps: [true, false, true] }, o: ["A and C", "A and D", "B and C", "B and D"], a: 1, why: "B floats, so its bottom is N (repels A’s N top) and its top is S. C touches B, so C’s bottom is N (attracted to S) and its top is S. D floats above C, so D’s bottom is S and its top is N. So A and D.", lvl: 3 },
    { q: "Study the Venn diagram. Which organism has been placed in the WRONG region?", fig: { type: "venn", a: "Breathes with lungs", b: "Lives mainly in water", onlyA: ["cat", "eagle"], both: ["whale", "dolphin", "tadpole"], onlyB: ["guppy", "shark"], neither: ["grasshopper"] }, o: ["Whale", "Dolphin", "Tadpole", "Grasshopper"], a: 2, why: "A tadpole lives in water but breathes with gills, not lungs, so it belongs in ‘Lives mainly in water’ only. Whales and dolphins breathe with lungs; a grasshopper lives on land and has no lungs.", lvl: 3 },
    { q: "Ali’s spectacles fog up as he steps out of an air-conditioned MRT train onto a warm, open-air platform. After a few minutes the fog disappears. Why does the fog disappear?", o: ["The lens gains heat from the warm air, so the water droplets evaporate", "The lens loses heat to the air, so the droplets freeze and fall off", "The water droplets are absorbed into the glass of the lens", "The water vapour in the air condenses faster as the lens warms"], a: 0, why: "The fog is water vapour from the warm air that condensed on the cold lens. As the lens gains heat and warms up, the droplets gain heat and evaporate.", lvl: 3 },
    { q: "A balloon is stretched over the mouth of an empty glass bottle, and the bottle is weighed. It is stood in hot water until the balloon inflates slightly, then taken out, dried and weighed again at once. Which statement is correct?", o: ["The air gains heat and expands, so the total mass increases", "The air takes up less space when hot, so the balloon inflates", "Hot water enters the bottle and pushes the air into the balloon", "The air gains heat and expands, and the total mass stays the same"], a: 3, why: "The air gains heat and expands into the balloon, but no air enters or leaves, so the amount of matter (mass) is unchanged.", lvl: 3 },

    // ---- lvl 4 (4)
    { q: "Aphids feed on the plants in a garden. Ladybirds, which eat aphids, were added at the end of month 2. Study the graph. Which best explains why the aphid numbers stop falling after month 5?", fig: { type: "line", xl: "Month", yl: "Number of aphids", pts: [["0", 100], ["1", 300], ["2", 700], ["3", 500], ["4", 250], ["5", 120], ["6", 110], ["7", 110]] }, o: ["The ladybirds stopped eating aphids as the aphids became poisonous", "The ladybirds had less food, so their numbers fell and fewer aphids were eaten", "The plants stopped making food, so the aphids had nothing left to eat", "The aphids stopped reproducing because they had too much food to eat"], a: 1, why: "As the aphids decreased, the ladybirds had less food and their population fell, so fewer aphids were eaten and the aphid numbers levelled off instead of dropping to zero.", lvl: 4 },
    { q: "Insects pollinate the flowers of a fruit tree in an orchard. A kind of bird there eats ONLY the fruits of this tree. The farmer sprays an insecticide that kills most of the insects. Why is the bird population most likely to decrease?", o: ["The birds eat the poisoned insects, as the insects are their main food", "The trees make less food as the insects no longer help them photosynthesise", "Fewer flowers are pollinated, so fewer fruits form and the birds have less food", "The birds face more competition for fruits from the insects that survive"], a: 2, why: "Without insect pollinators, fewer flowers are pollinated and fertilised, so fewer ovaries develop into fruits: the birds have less food. The birds do not eat insects, and insects do not help photosynthesis.", lvl: 4 },
    { q: "Four identical leafy shoots were placed in tubes of water with a layer of oil on top of the water. Petroleum jelly (waterproof) was spread on some leaf surfaces. Study the table. What can be concluded?", tbl: [["Shoot", "Leaf surface coated with jelly", "Loss in mass after 2 days (g)"], ["A", "None", "21"], ["B", "Upper surface only", "17"], ["C", "Lower surface only", "6"], ["D", "Both surfaces", "2"]], o: ["Most water vapour is lost through the lower surface of the leaves", "Most water vapour is lost through the upper surface of the leaves", "The jelly makes the shoot take in more water through its leaves", "Water vapour is lost equally through both surfaces of the leaves"], a: 0, why: "The oil stops evaporation from the water surface, so the mass lost is water lost from the shoot. Coating the lower surface cut the loss most (21 → 6 g), so most water vapour escapes through the tiny openings on the lower surface.", lvl: 4 },
    { q: "Two identical toy cars were released from the same height on two ramps: ramp X is smooth and ramp Y is covered with a towel. At the bottom, the car on X was moving faster. Which statement is correct?", o: ["On Y, greater friction converts more of its energy into heat, so it has less kinetic energy", "On Y, the car started with less gravitational potential energy, so it has less kinetic energy", "On X, no friction acts on the car, so all its potential energy becomes kinetic energy", "On X, the gravitational force on the car is greater, so more kinetic energy is produced"], a: 0, why: "Both cars start with the same gravitational potential energy and the same gravitational force. The towel gives more friction, which converts more energy into heat, leaving less kinetic energy. Even the smooth ramp has some friction.", lvl: 4 }
  ],
  tf: [
    { s: "We see a book because light from our eyes falls on it.", a: false, why: "Light from a light source is reflected off the book and enters our eyes." },
    { s: "A population is made up of one kind of organism living in the same habitat at the same time.", a: true, why: "All the populations in a habitat together form a community." },
    { s: "The gullet produces digestive juices to break down food.", a: false, why: "The gullet only moves food to the stomach; digestive juices are produced in the mouth, stomach and small intestine (and organs linked to it)." },
    { s: "A metal spoon in an air-conditioned room feels colder than a plastic spoon because it is at a lower temperature.", a: false, why: "Both are at room temperature. Metal is a better conductor of heat, so it conducts heat away from the hand faster." },
    { s: "Air has mass and takes up space.", a: true, why: "Air is matter: a ball pumped with more air becomes heavier, and air in a sealed syringe stops the plunger going all the way in." },
    { s: "The water-carrying tubes carry water and mineral salts from the roots to the leaves.", a: true, why: "Food made in the leaves is carried to other parts by the food-carrying tubes." },
    { s: "A mosquito and a cockroach have the same number of stages in their life cycles.", a: false, why: "A mosquito has four stages (egg, larva, pupa, adult); a cockroach has three (egg, nymph, adult)." },
    { s: "Ferns and mosses reproduce by spores, not seeds.", a: true, why: "Ferns and mosses are plants that do not produce flowers or seeds; they reproduce by spores." },
    { s: "The more a spring is stretched, the greater the elastic spring force it exerts.", a: true, why: "A spring stretched further exerts a greater force, which is why a spring balance can measure force." },
    { s: "A ring magnet floating above another ring magnet on a rod shows that their facing poles attract.", a: false, why: "Floating shows repulsion: the facing poles are like poles." }
  ],
  sort: [
    { title: "Sort each adaptation: is it STRUCTURAL (a body feature) or BEHAVIOURAL (something the organism does)?", groups: ["Structural adaptation", "Behavioural adaptation"], items: [["webbed feet of a duck", 0], ["thick fur of a polar bear", 0], ["spines of a cactus", 0], ["long, sticky tongue of a frog", 0], ["breathing roots of mangrove trees sticking out of the mud", 0], ["owls hunting at night", 1], ["birds migrating to warmer places in winter", 1], ["a pangolin rolling into a ball when attacked", 1], ["a lizard basking in the sun to warm up", 1]] }
  ],
  oe: [
    {
      q: "Study the circuit. Switch S is closed and all three bulbs are lit.\n(a) Bulb Q fuses. Which bulb(s) will still light? (1m)\n(b) Explain your answer to (a). (2m)\n(c) State the energy conversion that takes place in the batteries. (1m)",
      fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S", open: false }], branches: [[{ k: "bulb", label: "P" }], [{ k: "bulb", label: "Q" }, { k: "bulb", label: "R" }]] },
      marks: 4,
      kw: [["p only", "only p", "only bulb p"], ["series", "open circuit", "broken"], ["own path", "separate", "closed circuit"], ["chemical potential"]],
      model: "(a) Bulb P only. (b) Bulb R is in series with Q, so when Q fuses the path through R is broken and that branch becomes an open circuit. Bulb P is on its own path in a separate branch, which is still a closed circuit. (c) Chemical potential energy in the batteries is converted into electrical energy."
    },
    {
      q: "Study the food web of a school pond.\n(a) Name one organism that is both a predator and a prey. (1m)\n(b) The herons are removed and the fish population increases. Explain how this affects the dragonfly nymph population. (2m)\n(c) State the source of energy for this food web and how it enters the food web. (1m)",
      fig: { type: "web", links: [["water plant", "snail"], ["water plant", "tadpole"], ["tadpole", "dragonfly nymph"], ["tadpole", "fish"], ["dragonfly nymph", "fish"], ["fish", "heron"]] },
      marks: 4,
      x: 1,
      kw: [["dragonfly", "fish"], ["decrease"], ["eaten", "more predator", "more fish"], ["sun", "light energy"]],
      model: "(a) The dragonfly nymph, as it eats tadpoles and is eaten by the fish. (b) The dragonfly nymph population will decrease because more fish eat them, so more nymphs are eaten by predators, and the extra fish also eat more tadpoles, leaving less food for the nymphs. (c) The Sun; the water plants absorb light energy to make food by photosynthesis."
    },
    {
      q: "Rina set up four dishes, each with 10 green bean seeds, and recorded the results after 5 days.\n(a) Which two set-ups should she compare to find out if seeds need light to germinate? (1m)\n(b) What do the results of these two set-ups show? (1m)\n(c) Using set-ups C and D, explain why the seeds in D did not germinate. (1m)",
      fig: { type: "setups", items: [{ label: "A", icon: "dish", lines: ["Moist cotton wool", "Near a window", "25 °C", "Germinated"] }, { label: "B", icon: "dish", lines: ["Dry cotton wool", "Near a window", "25 °C", "Did not germinate"] }, { label: "C", icon: "dish", lines: ["Moist cotton wool", "In a dark cupboard", "25 °C", "Germinated"] }, { label: "D", icon: "dish", lines: ["Moist cotton wool", "In a fridge (dark)", "4 °C", "Did not germinate"] }] },
      marks: 3,
      kw: [["a and c", "c and a"], ["dark", "need light", "not needed", "no light", "without light"], ["temperature", "cold"]],
      model: "(a) A and C. (b) The seeds in C germinated in the dark just like the seeds in A, so seeds do not need light to germinate. (c) C and D differ only in temperature. The temperature of 4 °C in D is too cold, and seeds need a suitable temperature (warmth) to germinate."
    },
    {
      q: "Study the diagram of the human digestive system.\n(a) Name part X, where digested food enters the blood. (1m)\n(b) Describe how the digested food then reaches the muscle cells in the leg. (2m)\n(c) State what the muscle cells use the digested food for. (1m)",
      fig: { type: "organs", system: "digestive", mark: { stomach: "W", small_intestine: "X", large_intestine: "Y" } },
      marks: 4,
      kw: [["small intestine"], ["absorbed", "into the blood", "bloodstream"], ["heart", "pump"], ["release energy", "energy"]],
      model: "(a) X is the small intestine. (b) The digested food is absorbed into the blood at the small intestine. The heart pumps the blood through the blood vessels, which transport the digested food to the muscle cells in the leg. (c) The cells use the digested food together with oxygen to release energy."
    },
    {
      q: "A hawker wants to keep takeaway soup hot. Four identical cans of hot water at 90 °C were wrapped in different materials of the same thickness. Study the graph of the temperatures after 30 minutes.\n(a) Which material is the poorest conductor of heat? (1m)\n(b) Explain how the results show this. (1m)\n(c) Suggest why this material is a poor conductor of heat. (1m)\n(d) State one variable that must be kept the same to make this a fair test. (1m)",
      fig: { type: "bar", xl: "Wrapping material", yl: "Temperature after 30 min (°C)", bars: [["No wrapping", 40], ["Cotton", 52], ["Felt", 58], ["Bubble wrap", 65]] },
      marks: 4,
      kw: [["bubble"], ["highest", "hottest", "most slowly", "slowest", "least heat"], ["air"], ["volume", "amount of water", "mass of water", "starting temperature", "initial", "thickness", "size of"]],
      model: "(a) Bubble wrap. (b) The water in the can wrapped with bubble wrap had the highest temperature after 30 minutes, so it lost heat most slowly. (c) Bubble wrap traps air, and air is a poor conductor of heat. (d) The volume of hot water in each can (or its starting temperature) must be kept the same."
    },
    {
      q: "Mr Tan seals an empty plastic bottle, containing only air, in his air-conditioned office and leaves it in his car parked in the hot sun. The bottle becomes hard and bulges.\n(a) Explain why the bottle bulges. (2m)\n(b) Will the mass of the bottle change? Explain. (1m)\n(c) More air can be pumped into a fully inflated bicycle tyre, but no more water can be added to a bottle that is full of water. Explain why. (1m)",
      marks: 4,
      kw: [["gains heat", "gained heat"], ["expand"], ["same", "unchanged", "not change", "no change"], ["compress", "squeez"]],
      model: "(a) The air in the bottle gains heat from the hot car and expands, so it pushes out on the walls of the bottle and makes it bulge. (b) The mass stays the same because no air has entered or left the sealed bottle. (c) Air can be compressed, so more air can be squeezed into the same space in the tyre, but water has a definite volume and cannot be compressed."
    },
    {
      q: "Four identical ring magnets, A, B, C and D, are placed on a wooden rod as shown (A at the bottom). The top face of A is an N pole.\n(a) State the pole on the top face of ring B. (1m)\n(b) Explain why ring C floats above ring B. (1m)\n(c) Ring D is turned upside down and put back on the rod. Describe and explain what happens. (2m)",
      fig: { type: "rings", rings: [{ label: "A", top: "N" }, { label: "B", top: "?" }, { label: "C", top: "?" }, { label: "D", top: "?" }], gaps: [true, true, false] },
      marks: 4,
      x: 1,
      kw: [["s pole", "south"], ["like poles", "same pole", "repel"], ["n pole", "north"], ["float", "gap", "pushed up"]],
      model: "(a) The top face of B is an S pole (south pole). (b) The bottom face of C is an S pole, which faces the S pole on top of B. Like poles repel, so C floats above B. (c) The bottom face of D becomes an N pole (north pole), facing the N pole on top of C. Like poles repel, so D will float above C, leaving a gap between them."
    },
    {
      q: "Singapore collects rainwater in reservoirs such as MacRitchie Reservoir.\n(a) Explain how water in the reservoir can later fall as rain. (2m)\n(b) Explain why it is important not to pollute the water in reservoirs. (1m)",
      marks: 3,
      kw: [["evaporat"], ["condens"], ["harm", "unsafe", "not safe", "kill", "poison", "sick", "die", "disease"]],
      model: "(a) Heat from the Sun makes the water in the reservoir gain heat and evaporate into water vapour. The water vapour rises, loses heat to the cooler air high up and condenses into tiny water droplets that form clouds, which fall as rain. (b) Polluted water is harmful to the organisms living in the reservoir and unsafe for people to use as drinking water."
    }
  ],
  doc: [
    { q: "Explain why the metal handle of a spoon left in hot soup becomes hot, but a wooden handle does not.", marks: 2, answers: ["Metal is hot and wood is cold.", "The metal handle absorbs the hotness of the soup.", "Metal is a good conductor of heat, so heat from the soup is conducted quickly along the metal handle; wood is a poor conductor of heat."], best: 2, why: "Answer 3 compares both materials as conductors of heat and says heat is conducted from the soup along the handle. Answer 1 describes the materials as if they have their own temperature. Answer 2 uses ‘hotness’ instead of heat and does not mention conductors." },
    { q: "A dented ping-pong ball is dropped into hot water and the dent pops out. Explain why.", marks: 2, answers: ["The hot water pushes on the ball from outside and forces the dent back out.", "The air inside the ball gains heat from the hot water and expands, pushing the dented wall back out.", "The ball becomes soft in the hot water, so it goes back to its round shape."], best: 1, why: "Answer 2 gives the direction of heat flow (the air gains heat) and the change (it expands and pushes the wall out). Answer 1 has the push the wrong way: water pressing from outside would push the dent in, not out. Answer 3 misses the air inside gaining heat and expanding." },
    { q: "Explain how hunting at night helps an owl to survive.", marks: 2, answers: ["Owls like the dark.", "Its prey, such as mice, is active at night, so hunting at night helps the owl to catch enough food.", "It is a behavioural adaptation."], best: 1, why: "Answer 2 links the behaviour to getting food, which is how it helps the owl survive. Answer 3 names the type of adaptation but does not explain how it helps. Answer 1 is not a scientific reason." }
  ]
};
