window.LBY = window.LBY || {};
// PSLE Crossover — wave 3 pack (integrated P3–P6)
LBY["p6-mixed"] = {
  lessons: [
    {
      h: "Control set-ups and reliable results: say what each is FOR",
      concept: "PSLE experiment questions often ask ‘Why did he set up B?’ or ‘How can he make his results more reliable?’. These are different questions with different keywords. A CONTROL set-up is identical except that the thing being tested is left out; it lets you show that the result is caused by that one thing and nothing else. RELIABLE results come from repeating the experiment (or using more plants, seeds or animals) and taking the average. A FAIR TEST is about keeping all the other variables the same. Pupils lose marks by writing ‘to make it fair’ for a control, or ‘to make it accurate’ for repeating.",
      example: {
        q: "Ravi wanted to show that a water plant gives out oxygen bubbles in light. He set up P and Q as shown and counted the bubbles in each beaker for 5 minutes.\n(a) What is the purpose of set-up Q? [1]\n(b) Suggest how Ravi can make his results more reliable. [1]",
        fig: { type: "setups", items: [{ label: "P", icon: "beaker", lines: ["Water plant", "Pond water", "Under a lamp"] }, { label: "Q", icon: "beaker", lines: ["No water plant", "Pond water", "Under a lamp"] }] },
        marks: 2,
        think: [
          "Step 1: Spot the only difference between P and Q: Q has no water plant.",
          "Step 2: So Q is the control. If no bubbles form in Q, the bubbles in P did not come from the water or the lamp.",
          "Step 3: Write the purpose as ‘to show that the bubbles were given out by the plant’, not just ‘to make it fair’.",
          "Step 4: For reliability, repeat the experiment (or use more plants) and take the average number of bubbles."
        ],
        answer: "(a) Q is the control. It shows that the bubbles in P were given out by the water plant and not by the pond water or the lamp. (b) Repeat the experiment a few more times and calculate the average number of bubbles."
      },
      tip: "Control → ‘to show that the result is caused by ___ only’. Reliable → ‘repeat and take the average’. Fair test → ‘keep all other variables the same’.",
      try: {
        q: "Wei placed a snail in a sealed tube with a carbon dioxide sensor. He set up an identical sealed tube with a sensor but no snail. What is the purpose of the tube with no snail?",
        o: ["To show that any change in carbon dioxide is caused by the snail", "To give the snail more air to breathe in during the experiment", "To make the experiment faster so the results come out sooner", "To keep the temperature in both of the tubes exactly the same"],
        a: 0,
        why: "The tube without the snail is the control. If its carbon dioxide stays the same, any increase in the other tube must be caused by the snail’s respiration. It does not give the snail air, speed things up or control temperature."
      }
    }
  ],
  mcq: [
    // ---- lvl 1 (3)
    { q: "Which of the following are sources of light?\nA: The Sun\nB: The Moon\nC: A lit candle", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 2, why: "The Sun and a lit candle give out their own light. Misconception: the Moon is NOT a light source; we see it because it reflects light from the Sun.", lvl: 1 },
    { q: "Study the diagram of the human digestive system. In which labelled part is water mainly absorbed from the undigested food?", fig: { type: "organs", system: "digestive", mark: { mouth: "A", gullet: "B", stomach: "C", large_intestine: "D" } }, o: ["A", "B", "C", "D"], a: 3, why: "D is the large intestine, where water is absorbed from the undigested food. Digested food is absorbed mainly in the small intestine.", lvl: 1 },
    { q: "Which of these has elastic potential energy?", o: ["A book resting on the floor", "A stretched rubber band on a catapult", "A toy car rolling on flat ground", "A cup of hot tea on a table"], a: 1, why: "A stretched or compressed object stores elastic potential energy. The rolling car has kinetic energy and the hot tea has heat energy; the book on the floor has no stored elastic energy.", lvl: 1 },

    // ---- lvl 2 (6)
    { q: "Which statements about magnets are correct?\nA: A magnet can attract a steel pin without touching it.\nB: The magnetic force of a bar magnet is strongest at its poles.\nC: A magnet attracts all metals, including copper and aluminium.", o: ["A and B only", "A only", "B and C only", "A, B and C"], a: 0, why: "Magnetic force acts without contact (A) and is strongest at the poles (B). Misconception: not all metals are magnetic; only iron, steel, nickel and cobalt are attracted, so C is wrong.", lvl: 2 },
    { q: "A cup of hot water at 80 °C was left on a table in a room at 30 °C. Study the graph of the water’s temperature. What is the most likely temperature of the water after 2 hours?", fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 80], ["5", 62], ["10", 50], ["15", 42], ["20", 37], ["25", 34]] }, o: ["0 °C", "25 °C", "30 °C", "34 °C"], a: 2, why: "The water loses heat to the cooler surroundings only until it reaches room temperature (30 °C); then there is no more heat flow. Misconception: hot water does not keep cooling to 0 °C or below room temperature.", lvl: 2 },
    { q: "Study the Venn diagram. Which organism could be X?", fig: { type: "venn", a: "Reproduces by spores", b: "Makes its own food", onlyA: ["mushroom", "X"], both: ["fern", "moss"], onlyB: ["hibiscus", "rice plant"], neither: ["cat"] }, o: ["Bread mould", "Balsam plant", "Bird’s nest fern", "Grasshopper"], a: 0, why: "X reproduces by spores but cannot make its own food, so it is a fungus like bread mould. A bird’s nest fern would be in the overlap, a balsam plant with hibiscus, and a grasshopper with the cat.", lvl: 2 },
    { q: "Jia Hui wants to find out if the material of a cup affects how fast hot water in it loses heat. Each cup starts with water at 80 °C. Which TWO set-ups should she compare?", fig: { type: "setups", items: [{ label: "W", icon: "beaker", lines: ["Steel cup", "200 ml hot water", "With a lid"] }, { label: "X", icon: "beaker", lines: ["Plastic cup", "200 ml hot water", "With a lid"] }, { label: "Y", icon: "beaker", lines: ["Steel cup", "100 ml hot water", "No lid"] }, { label: "Z", icon: "beaker", lines: ["Plastic cup", "200 ml hot water", "No lid"] }] }, o: ["X and Z", "Y and Z", "W and Y", "W and X"], a: 3, why: "W and X differ only in the material of the cup; the volume of water and the lid are the same. X and Z differ in the lid, Y and Z in material and volume, W and Y in volume and lid.", lvl: 2 },
    { q: "Study the plant. Cells from which labelled part would have the MOST chloroplasts?", fig: { type: "plant", mark: { roots: "A", stem: "B", leaf: "C", flower: "D" } }, o: ["A", "B", "C", "D"], a: 2, why: "The leaf (C) is the main part that makes food. Its cells are exposed to light and have many chloroplasts. Root cells under the soil receive no light and have none.", lvl: 2 },
    { q: "Study the life cycle of the mosquito. Its eggs, larvae and pupae develop in still water. Which actions will help to reduce the number of adult mosquitoes in an HDB estate?\nA: Turning over pails so that rainwater does not collect in them\nB: Keeping guppies, which eat mosquito larvae, in a garden pond\nC: Covering water tanks so that adult mosquitoes cannot lay eggs on the water", fig: { type: "cycle", stages: ["Egg", "Larva", "Pupa", "Adult"] }, o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 3, why: "All three stop the life cycle before the adult stage: A and C remove places where eggs can be laid and larvae can live, and B lets predators eat the larvae.", lvl: 2 },

    // ---- lvl 3 (7)
    { q: "Study the circuit. Both switches are open. Which statements are correct?\nA: If only S1 is closed, bulb P lights and bulb Q does not.\nB: If only S2 is closed, bulb Q lights and bulb P does not.\nC: If both switches are closed and bulb P then fuses, bulb Q stays lit.", fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S1", open: true }], branches: [[{ k: "bulb", label: "P" }], [{ k: "bulb", label: "Q" }, { k: "switch", label: "S2", open: true }]] }, o: ["A only", "B and C only", "A, B and C", "A and C only"], a: 3, why: "S1 is in the main circuit shared by both branches, so no bulb lights unless S1 is closed (B is wrong). With S1 closed, P’s branch is closed but Q’s needs S2 too (A). Q is on its own path, so it stays lit if P fuses (C).", lvl: 3 },
    { q: "Nadia poured the same volume of water into four dishes with different exposed surface areas and left them in the same room. She measured the mass of water lost after 3 hours. Study the graph. Which correctly names the variables in her experiment?", fig: { type: "bar", xl: "Exposed surface area (cm²)", yl: "Mass of water lost (g)", bars: [["10", 4], ["20", 8], ["40", 15], ["80", 27]] }, o: ["Changed: exposed surface area; Measured: mass of water lost", "Changed: mass of water lost; Measured: exposed surface area", "Changed: volume of water; Measured: exposed surface area", "Changed: exposed surface area; Measured: volume of water at the start"], a: 0, why: "The variable Nadia chose to change is the exposed surface area; the variable she measured is the mass of water lost. The starting volume of water is kept the same. Misconception: the changed and measured variables are often swapped.", lvl: 3 },
    { q: "Study the diagram. P is a bar magnet. Q and R are bars that may or may not be magnets. Q attracts P, and Q repels R. Which statement MUST be true?", fig: { type: "magnets", items: [{ label: "P", poles: "NS" }, { label: "Q", poles: "??" }, { label: "R", poles: "??" }], between: ["attract", "repel"] }, o: ["The left end of R is an S pole", "The right end of Q is an N pole", "Q may be an iron bar, not a magnet", "R may be a steel bar, not a magnet"], a: 0, why: "Only a magnet can repel, so Q and R are both magnets. Q’s left end is attracted to P’s S pole, so it is N and Q’s right end is S. R repels Q’s S pole, so R’s left end is also S.", lvl: 3 },
    { q: "Study the table comparing the air a boy breathes in and breathes out. Which statements are correct?\nA: Exhaled air contains no oxygen.\nB: The body takes in some oxygen and gives out carbon dioxide.\nC: The body does not use the nitrogen that it breathes in.", tbl: [["Gas", "Inhaled air (%)", "Exhaled air (%)"], ["Oxygen", "21", "16"], ["Carbon dioxide", "0.04", "4"], ["Nitrogen", "78", "78"]], o: ["B only", "A and B only", "A, B and C", "B and C only"], a: 3, why: "Oxygen falls from 21% to 16% and carbon dioxide rises (B); nitrogen is unchanged, so it is not used (C). Misconception: exhaled air still contains 16% oxygen, so A is wrong.", lvl: 3 },
    { q: "Study the food web in a rice field. A farmer puts out poison that kills all the rats. Which statements are correct?\nA: The snakes now depend only on the frogs for food.\nB: The frog population is likely to decrease.\nC: The eagle population is likely to increase because the snakes have less food.", fig: { type: "web", links: [["rice plant", "grasshopper"], ["rice plant", "rat"], ["grasshopper", "frog"], ["frog", "snake"], ["rat", "snake"], ["snake", "eagle"]] }, o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "Snakes eat only rats and frogs, so without rats they depend on frogs (A) and eat more of them, so frogs decrease (B). With less food, snakes are likely to decrease, so the eagles have LESS food, not more (C is wrong).", lvl: 3 },
    { q: "Lina placed a torch at different distances from a wooden block. The wall behind the block stayed in the same place. She measured the height of the block’s shadow on the wall. Study the graph. Which statement explains the results?", fig: { type: "bar", xl: "Distance of torch from block (cm)", yl: "Height of shadow (cm)", bars: [["10", 36], ["20", 18], ["30", 12], ["40", 9]] }, o: ["The nearer the torch, the more light the block blocks, so the shadow is larger", "The further the torch, the more light passes through the block, so the shadow is smaller", "The nearer the torch, the brighter the light, so the block reflects a larger shadow", "The further the torch, the more light bends round the block, so the shadow is smaller"], a: 0, why: "Light travels in straight lines. The nearer the opaque block is to the torch, the more light it blocks, so a larger area of the wall receives no light. Misconception: a shadow is not a reflection, and light does not pass through or bend round the opaque block.", lvl: 3 },
    { q: "A metal ball can just pass through a metal ring at room temperature. Which statements are correct?\nA: After only the ball is heated, it may not pass through the ring, as the ball gains heat and expands.\nB: After only the ring is heated, the ball passes through more easily, as the ring expands and its hole becomes bigger.\nC: The heated ball has a greater mass than before because it has gained heat.", o: ["A only", "A and B only", "A and C only", "A, B and C"], a: 1, why: "Heated metal expands: the ball becomes bigger (A) and the whole ring, including its hole, becomes bigger (B). Misconception: gaining heat and expanding does not add matter, so the mass stays the same (C is wrong).", lvl: 3 },

    // ---- lvl 4 (4)
    { q: "A roller-coaster cart is released from rest at the top of a 20 m slope. It rolls down and then up the next slope, reaching a highest point of 16 m. Which statements are correct?\nA: The cart has its greatest kinetic energy at the lowest point of the track.\nB: With less friction, the cart could rise higher than 16 m on the next slope, but never higher than 20 m.\nC: Some energy was destroyed by friction, which is why the cart rose only to 16 m.", o: ["A only", "B only", "A and B only", "A, B and C"], a: 2, why: "Gravitational potential energy is converted into kinetic energy as it falls, so it is fastest at the lowest point (A). Friction converts some energy into heat and sound; less friction leaves more energy to rise, but it can never gain more than it started with (B). Energy is converted, never destroyed (C is wrong).", lvl: 4 },
    { q: "A pond has many water plants and fish. The amount of oxygen dissolved in the water was measured over one day. Study the table. Why is the amount lowest at 06:00?", tbl: [["Time", "Dissolved oxygen (units)"], ["06:00", "3"], ["10:00", "6"], ["14:00", "9"], ["18:00", "8"], ["22:00", "5"], ["02:00", "4"]], o: ["The water plants respire only at night, so they use up the oxygen then", "All night, plants and fish respire, using oxygen, but no photosynthesis gives it out", "The fish are most active in the early morning, so they use up the most oxygen then", "The cool night air takes the oxygen out of the water through the water surface"], a: 1, why: "Plants and fish respire all the time. Through the night there is no light for photosynthesis, so oxygen is used but none is given out, and it is lowest just before sunrise. Misconception: plants respire day AND night, not only at night.", lvl: 4 },
    { q: "A potted plant was placed on a balance, and the WHOLE pot and plant were sealed inside a clear plastic bag. After 6 hours in sunlight, water droplets were seen on the inside of the bag. Which statements are correct?\nA: The water in the droplets was taken in by the roots and carried up the water-carrying tubes.\nB: Water vapour given off by the leaves condensed on the cooler inner surface of the bag.\nC: The balance reading decreased because the plant lost water into the air.", o: ["A only", "B only", "A and B only", "A, B and C"], a: 2, why: "Water from the soil travels up the water-carrying tubes (A), evaporates from the leaves and condenses on the cooler bag (B). The bag is sealed, so no matter leaves and the balance reading stays the same (C is wrong).", lvl: 4 },
    { q: "Study the food web. P and U are plants. A disease kills all of organism R. Which statements are correct?\nA: T will die out because R is its only food.\nB: S will have less food.\nC: U is likely to increase, as no organism in the web now feeds on it.", fig: { type: "web", links: [["U", "R"], ["P", "Q"], ["P", "R"], ["Q", "S"], ["R", "S"], ["R", "T"], ["S", "T"]] }, o: ["A only", "B and C only", "A and C only", "A, B and C"], a: 1, why: "S eats Q and R, so it loses one food source (B). R was the only organism eating U, so U is likely to increase (C). T eats both R and S, so R is not its only food (A is wrong).", lvl: 4 }
  ],
  oe: [
    {
      q: "Mei pulled the same wooden block slowly across four different surfaces using a spring balance. She recorded the reading on the spring balance when the block just started to move. Study the graph.\n(a) State the aim of Mei’s experiment. [1]\n(b) State one variable she must keep the same to make it a fair test. [1]\n(c) On which surface was the friction between the block and the surface the greatest? [1]\n(d) After she pulled the block across the surfaces many times, the bottom of the block felt warm. Explain why. [1]",
      fig: { type: "bar", xl: "Surface", yl: "Spring balance reading (N)", bars: [["Glass", 2], ["Wood", 4], ["Carpet", 7], ["Sandpaper", 9]] },
      marks: 4,
      kw: [["type of surface", "kind of surface", "types of surface", "different surface", "surface affect"], ["same block", "mass of the block", "mass of block", "same mass", "weight of the block", "same spring balance", "speed", "size of the block"], ["sandpaper"], ["heat"]],
      model: "(a) To find out if the type of surface affects the amount of friction acting on the block. (b) The mass of the block (use the same block each time). (c) Sandpaper, as the greatest force (9 N) was needed to move the block. (d) Friction between the block and the surface converted the kinetic energy of the block into heat energy, so the block became warm."
    },
    {
      q: "Hana soaked two identical cloths, A and B, in the same amount of water. She hung A spread out and B folded in half on the same clothes line on a sunny day, and measured their masses every 30 minutes.\n(a) What variable did Hana change? [1]\n(b) Which cloth dried faster? Explain why, using the results. [2]\n(c) Suggest one change to where the cloths are hung that would make BOTH cloths dry faster. [1]",
      tbl: [["Time (min)", "Mass of cloth A, spread out (g)", "Mass of cloth B, folded (g)"], ["0", "150", "150"], ["30", "130", "141"], ["60", "112", "133"], ["90", "100", "126"]],
      marks: 4,
      kw: [["surface area", "exposed surface"], ["larger exposed", "larger surface", "more exposed", "bigger exposed", "greater exposed", "more surface"], ["evaporat"], ["wind", "breez", "fan", "moving air"]],
      model: "(a) The exposed surface area of the cloth (spread out or folded). (b) Cloth A dried faster, as its mass decreased more quickly (to 100 g after 90 minutes, compared with 126 g for B). A had a larger exposed surface area, so the water in it evaporated faster. (c) Hang both cloths in a windy place, as moving air carries the water vapour away so the water evaporates faster."
    },
    {
      q: "Siva set up three identical sealed glass jars, each with a carbon dioxide sensor, and left them for 4 hours. The amount of carbon dioxide in each jar at the start and at the end is shown.\n(a) Explain why the amount of carbon dioxide decreased in jar A. [1]\n(b) Explain why the amount of carbon dioxide increased in jar B. [1]\n(c) Why did Siva set up jar C? [1]\n(d) Suggest one way to make his results more reliable. [1]",
      fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Green plant", "In sunlight", "CO2: 400 → 250"] }, { label: "B", icon: "jar", lines: ["Green plant", "In darkness", "CO2: 400 → 520"] }, { label: "C", icon: "jar", lines: ["No plant", "In sunlight", "CO2: 400 → 400"] }] },
      marks: 4,
      kw: [["photosynthes"], ["respir"], ["control", "caused by the plant", "due to the plant", "because of the plant"], ["repeat", "more plants", "average"]],
      model: "(a) In sunlight, the plant photosynthesised and took in carbon dioxide faster than it gave out carbon dioxide during respiration. (b) In darkness, the plant could not make food, but it continued to respire and gave out carbon dioxide. (c) Jar C is the control. It shows that the changes in carbon dioxide in A and B were caused by the plant and not by the light or the jar. (d) Repeat the experiment with more plants and calculate the average change."
    },
    {
      q: "Lina filled two vacuum flasks with the same number of seeds and placed a thermometer in each. Flask A had germinating seeds. Flask B had germinating seeds that had been boiled and cooled, so they were dead. The results are shown.\n(a) Explain why the temperature in flask A increased. [2]\n(b) Explain why the temperature in flask B did not change. [1]\n(c) Explain why Lina used vacuum flasks instead of glass beakers. [1]",
      fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Vacuum flask", "Germinating seeds", "Start: 28 °C", "After 2 days: 33 °C"] }, { label: "B", icon: "jar", lines: ["Vacuum flask", "Boiled (dead) seeds", "Start: 28 °C", "After 2 days: 28 °C"] }] },
      marks: 4,
      x: 1,
      kw: [["respir"], ["heat"], ["dead", "not alive", "not living", "did not respire", "do not respire", "cannot respire"], ["poor conductor", "heat loss", "losing heat", "lose heat", "loses heat", "lost to the surroundings"]],
      model: "(a) The germinating seeds in A were alive and respired. Respiration released energy from the food stored in the seeds, and some of this energy was given out as heat, so the temperature rose. (b) The seeds in B were dead, so they did not respire and gave out no heat. (c) A vacuum flask is a poor conductor of heat, so it reduces heat loss to the surroundings and keeps in the heat given out by the seeds so that it can be measured."
    },
    {
      q: "Large areas of tropical rainforest in the region are being cut down.\n(a) Describe how water in the soil ends up as water vapour in the air around a tree. [2]\n(b) Scientists found that an area gets less rain after its forest is cut down. Using your answer to (a), explain why. [1]\n(c) State one other harmful effect of cutting down forests on the environment. [1]",
      marks: 4,
      kw: [["water-carrying", "water carrying"], ["evaporat"], ["less water vapour", "fewer clouds", "less clouds", "less water evaporat"], ["habitat", "carbon dioxide", "global warming", "erosion"]],
      model: "(a) Water in the soil is taken in by the roots and carried up the stem to the leaves in the water-carrying tubes. The water then evaporates from the leaves as water vapour into the air. (b) With fewer trees, less water vapour is given off into the air, so less water vapour condenses to form clouds and there is less rain. (c) Animals lose their habitat, and there is more carbon dioxide in the air as fewer trees take it in for photosynthesis, adding to global warming."
    },
    {
      q: "Study the food web in a forest. Fruit bats feed on the nectar of durian flowers.\n(a) Hunters kill most of the fruit bats. Explain how this would affect the number of durian fruits formed. [2]\n(b) Explain how the python population is likely to change at first. [1]\n(c) Some squirrels carry durian fruits away, eat the flesh and drop the seeds. Explain how this helps the durian tree. [1]",
      fig: { type: "web", links: [["durian tree", "fruit bat"], ["durian tree", "squirrel"], ["fruit bat", "python"], ["squirrel", "python"], ["squirrel", "eagle"]] },
      marks: 4,
      x: 1,
      kw: [["pollinat"], ["fewer durian", "fewer fruit", "less fruit"], ["less food", "food source"], ["dispers", "away from the parent", "compet"]],
      model: "(a) Fruit bats pollinate the durian flowers as they feed on the nectar. With fewer fruit bats, fewer flowers are pollinated and fertilised, so fewer durian fruits are formed. (b) The python population is likely to decrease, as the fruit bats are one of its food sources, so it has less food. (c) The seeds are dispersed away from the parent tree, so the seedlings compete less with the parent tree for sunlight, water, space and mineral salts."
    }
  ],
  tf: [
    { s: "A shadow forms because an opaque object reflects light onto the surface behind it.", a: false, why: "Light travels in straight lines. The opaque object blocks the light, so the area behind it receives no light and a shadow forms." },
    { s: "A metal ball that gains heat and expands has the same mass as before.", a: true, why: "It takes up more space, but no matter is added, so its mass is unchanged." },
    { s: "The air we breathe out contains carbon dioxide but no oxygen.", a: false, why: "Exhaled air still contains about 16% oxygen; it has less oxygen and more carbon dioxide than inhaled air." },
    { s: "A cup of hot water left on a table cools down only until it reaches the temperature of the room.", a: true, why: "Heat flows from the hotter water to the cooler surroundings until both are at the same temperature; then there is no more heat flow." },
    { s: "All metals are magnetic materials.", a: false, why: "Only iron, steel, nickel and cobalt are magnetic. Copper and aluminium are metals but are not attracted by magnets." },
    { s: "If a bar repels a magnet, the bar must also be a magnet.", a: true, why: "A magnetic material such as iron can only be attracted. Repulsion happens only between like poles of two magnets." },
    { s: "Gravitational force acts on an object only while it is falling.", a: false, why: "Gravity pulls on every object towards the Earth all the time, including a book resting on a table; this pull is its weight." },
    { s: "Germinating seeds give out heat because they respire.", a: true, why: "Living cells respire to release energy from food, and some of this energy is given out as heat." },
    { s: "A mushroom makes its own food using light energy, like a green plant.", a: false, why: "Fungi have no chlorophyll and cannot make their own food; they get food from dead or decaying matter." },
    { s: "Covering a pot of water with a lid reduces the amount of water lost by evaporation.", a: true, why: "The lid traps the water vapour, which condenses on the lid and drips back, so less water escapes into the air." }
  ],
  doc: [
    { q: "A metal ball could just pass through a metal ring. After the ball was heated, it could not pass through. Explain why.", marks: 2, answers: ["The ball became heavier when it was heated, so it got stuck.", "The ball gained heat and expanded, so it became bigger than the hole in the ring.", "The ball expanded."], best: 1, why: "Answer 2 gives the direction of heat flow (gained heat), the change (expanded) and links it to the hole. Answer 3 says only ‘expanded’ with no heat gain and no link to the ring. Answer 1 is a misconception: heating does not add mass." },
    { q: "Explain why the amount of oxygen dissolved in a pond with many water plants is lowest just before sunrise.", marks: 2, answers: ["All night, the plants and fish respire and use oxygen, but there is no light for photosynthesis, so no oxygen is given out.", "The plants take in oxygen at night.", "It is dark, so there is no oxygen."], best: 0, why: "Answer 1 names both processes: respiration by plants AND fish uses oxygen, while photosynthesis stops without light. Answer 2 names only the plants and suggests they respire only at night. Answer 3 gives no process and wrongly links darkness directly to oxygen." }
  ]
};
