window.LBU = window.LBU || {};
// PSLE Crossover — wave 5 pack
LBU["p6-mixed"] = {
  glossary: [
    { t: "Energy conversion", d: "The change of energy from one form to another, e.g. light energy into chemical potential energy in a leaf. Energy cannot be created or destroyed, only converted." },
    { t: "Chemical potential energy", d: "Energy stored in food, fuels and batteries. It can be converted into other forms, e.g. heat and light energy when a fuel burns." },
    { t: "Kinetic energy", d: "The energy that a moving object has. The faster an object moves, the more kinetic energy it has." },
    { t: "Elastic potential energy", d: "Energy stored in an object that is stretched, compressed, bent or twisted, e.g. a stretched rubber band or a compressed spring." },
    { t: "Frictional force", d: "A contact force that acts between two surfaces and opposes motion. Rougher surfaces in contact produce a greater frictional force." },
    { t: "Closed circuit", d: "A complete, unbroken path of electrical conductors that lets an electric current flow from the batteries, through the bulbs or other parts, and back to the batteries." },
    { t: "Electrical insulator", d: "A material that does not allow an electric current to flow through it easily, e.g. plastic, rubber, wood and glass." },
    { t: "Electromagnet", d: "A coil of wire wound around an iron core. It becomes a magnet only when an electric current flows through the coil." },
    { t: "Evaporation", d: "The change of a liquid into a gas, e.g. water into water vapour, at any temperature. It takes place at the exposed surface of the liquid, which gains heat." },
    { t: "Condensation", d: "The change of water vapour (a gas) into liquid water when it loses heat, e.g. when it touches a cold surface." },
    { t: "Chlorophyll", d: "The green substance in the chloroplasts of plant cells that traps light energy for the plant to make food during photosynthesis." },
    { t: "Pollination", d: "The transfer of pollen grains from the anther to the stigma of a flower, by agents such as insects, wind or birds." }
  ],
  lessons: [
    {
      h: "Adaptation answers: feature → what it does → survival",
      concept: "An ‘explain how this feature helps the organism to survive’ question needs three links: name the FEATURE, state what it DOES, and link it to SURVIVAL in that habitat (getting food, escaping predators, reducing water loss, getting light). Answers such as ‘it helps it to survive’ or ‘it helps it to adapt’ score nothing, because they only repeat the question.",
      example: {
        q: "A cactus grows in a hot, dry desert. Its leaves are thin spines and its stem is thick and fleshy. Explain how EACH feature helps the cactus to survive in the desert. [2]",
        marks: 2,
        think: [
          "Step 1: Name the problem the habitat poses: a hot, dry desert has very little water, so the plant must reduce water loss and store water.",
          "Step 2: Feature 1 – spines: they have a much smaller exposed surface area than broad leaves, so less water is lost from the plant.",
          "Step 3: Feature 2 – thick, fleshy stem: it stores water, so the cactus can survive long periods without rain.",
          "Step 4: Check every sentence has feature + what it does + survival link. ‘The spines help it to survive’ alone scores 0."
        ],
        answer: "The spines have a small exposed surface area, so the cactus loses less water. The thick, fleshy stem stores water, so the cactus can survive long dry periods without rain."
      },
      tip: "Never stop at ‘it helps it to survive’ – say what the feature DOES and why that matters in that habitat.",
      try: {
        q: "Smooth-coated otters in Singapore’s rivers have webbed feet. Which answer to ‘Explain how webbed feet help the otter to survive’ would score full marks?",
        o: ["Webbed feet help the otter to survive well in its habitat.", "Webbed feet help it swim fast, so it can catch fish to eat.", "Webbed feet help the otter to adapt to living in rivers.", "Webbed feet help it walk fast, so it can run on dry land."],
        a: 1,
        why: "Only this answer gives what the feature does (swim fast) AND the survival link (catching fish for food). The first and third answers just repeat the question; the last gives the wrong function, as webbed feet help in water, not on dry land."
      }
    },
    {
      h: "Writing the aim and naming the variables",
      concept: "Booklet B often asks for the aim, the changed variable, the measured variable and the variables kept the same. Write the aim as ‘To find out how the [changed variable] affects the [measured variable]’. Name each variable in full – ‘the speed of the fan’, not ‘fan’; ‘the mass of water lost from the cloth’, not ‘mass’. Variables kept the same are the other things that could affect the result.",
      example: {
        q: "Hana soaked three identical cloths in 50 g of water each and hung them in the same room in front of a fan set at different speeds. She weighed each cloth after 1 hour and worked out the mass of water lost. Study the table.\n(a) State the aim of her experiment. [1]\n(b) State the changed variable and the measured variable. [1]\n(c) State two variables she must keep the same. [1]",
        tbl: [["Fan speed", "Mass of water lost after 1 h (g)"], ["Off", "8"], ["Low", "15"], ["High", "24"]],
        marks: 3,
        think: [
          "Step 1: Find what was changed on purpose: the speed of the fan (off, low, high). This is the changed variable.",
          "Step 2: Find what was recorded in the results: the mass of water lost from the cloth in 1 hour. This is the measured variable – it shows how much water evaporated.",
          "Step 3: Put both into one aim: ‘To find out how the speed of the fan affects the mass of water that evaporates from the cloth.’",
          "Step 4: Variables kept the same are other things that could change the result: size and type of cloth, amount of water at the start, distance from the fan, the room and the time."
        ],
        answer: "(a) To find out how the speed of the fan (moving air) affects the mass of water that evaporates from a wet cloth. (b) Changed variable: the speed of the fan. Measured variable: the mass of water lost from the cloth after 1 hour. (c) The size and type of cloth, and the amount of water soaked into each cloth at the start."
      },
      tip: "Aim = ‘how the changed variable affects the measured variable’ – take both from the set-up and the results table.",
      try: {
        q: "Siti put identical ice cubes into cups made of different materials and recorded how long each ice cube took to melt completely. Which is the best aim for her experiment?",
        o: ["To find out how the time taken to melt affects the material of the cup", "To find out how the size of the ice cube affects the time taken to melt", "To find out how the material of the cup affects the time taken to melt", "To find out how the temperature of the room affects the time taken to melt"],
        a: 2,
        why: "Siti changed the material of the cup and measured the time taken to melt, so the aim links them in that order. The first option reverses the two variables; the size of the ice cube and the room temperature were kept the same."
      }
    }
  ],
  flash: [
    { f: "Function of the small intestine", b: "Digestion of food is completed here by digestive juices. The digested food is then absorbed into the blood through the walls of the small intestine." },
    { f: "Which gases pass through the tiny openings (stomata) of a leaf in sunlight?", b: "Carbon dioxide enters the leaf for photosynthesis. Oxygen and water vapour leave the leaf." },
    { f: "Four factors that make water evaporate faster", b: "A higher temperature of the surroundings, a larger exposed surface area, more wind (moving air) and drier air (lower humidity)." },
    { f: "Two ways to make an electromagnet stronger", b: "Increase the number of coils of wire around the iron core, or increase the number of batteries connected in series in the circuit." },
    { f: "Why are electrical wires coated with plastic?", b: "Plastic is an electrical insulator. It stops the electric current from flowing through our body when we touch the wire, so we do not get an electric shock." },
    { f: "Energy conversions in a wind turbine", b: "Kinetic energy of the moving wind → kinetic energy of the turning blades → electrical energy produced by the generator." },
    { f: "Insect-pollinated vs wind-pollinated flowers", b: "Insect: large, brightly coloured petals, scent, nectar, sticky pollen. Wind: small, dull or no petals, feathery stigmas, anthers hanging out, light and dry pollen." },
    { f: "Compare exhaled air with inhaled air", b: "Exhaled air has less oxygen, more carbon dioxide and more water vapour than inhaled air. The amount of nitrogen stays about the same." },
    { f: "Which materials does a magnet attract?", b: "Magnetic materials: iron, steel, nickel and cobalt. Other metals such as copper, aluminium and brass, and non-metals such as plastic and wood, are not attracted." },
    { f: "How does a periscope let you see over a wall?", b: "Light from the object is reflected by the top mirror down to the bottom mirror, which reflects the light into your eyes." },
    { f: "Function of the cell membrane", b: "It controls the movement of substances into and out of the cell." },
    { f: "Why do bicycle tyres have deep grooves (treads)?", b: "The grooves increase the friction between the tyre and the road, giving a better grip so the bicycle does not skid, especially on wet roads." }
  ],
  mcq: [
    { q: "Study the food chain in a rice field. Which statement is correct?", fig: { type: "web", links: [["Rice plant", "Grasshopper"], ["Grasshopper", "Frog"], ["Frog", "Snake"]] }, o: ["The snake is a prey of the frog.", "The frog is a predator of the grasshopper.", "The grasshopper is a producer.", "The rice plant gets energy from the frog."], a: 1, why: "Arrows point from the food to the eater. The frog eats the grasshopper, so it is the grasshopper’s predator. The snake eats the frog (not the other way round), the grasshopper is a consumer, and the rice plant gets its energy from sunlight.", lvl: 1 },
    { q: "Which part of a plant cell is NOT found in an animal cell?", o: ["Nucleus", "Cytoplasm", "Cell membrane", "Cell wall"], a: 3, why: "Only plant cells have a cell wall, which gives the cell a fixed shape and support. Both plant and animal cells have a nucleus, cytoplasm and a cell membrane.", lvl: 1 },
    { q: "A ceiling fan in a classroom is switched on. What is the main energy conversion in the fan?", o: ["Kinetic energy → electrical energy", "Electrical energy → light energy", "Chemical potential energy → kinetic energy", "Electrical energy → kinetic energy"], a: 3, why: "The fan’s motor converts electrical energy into kinetic energy of the turning blades (with some heat and sound). It runs on mains electricity, not batteries, and it does not give out light.", lvl: 1 },
    { q: "In the water cycle, which process forms the tiny water droplets that make up clouds?", o: ["Evaporation", "Melting", "Condensation", "Freezing"], a: 2, why: "Water vapour rises, loses heat to the cooler air high up and condenses into tiny water droplets that form clouds. Evaporation turns water into water vapour; it does not form droplets.", lvl: 1 },
    { q: "Mdm Tan hung identical wet towels along her HDB corridor on four different days. Study the table. On which day would the towel most likely dry the fastest?", tbl: [["Day", "Weather", "Air temperature (°C)", "Wind"], ["Monday", "Cloudy", "28", "Strong"], ["Tuesday", "Sunny", "33", "Strong"], ["Wednesday", "Sunny", "33", "None"], ["Thursday", "Rainy", "26", "None"]], o: ["Monday", "Tuesday", "Wednesday", "Thursday"], a: 1, why: "Water evaporates fastest when the air is hot and windy. Tuesday is both the hottest (33 °C) and windy. Wednesday is as hot but has no wind to carry the moist air away from the towel.", lvl: 2 },
    { q: "Study the circuit. When switch S is closed, bulbs P and Q both light. Bulb P is then unscrewed and removed from its holder. What will happen to bulb Q?", fig: { type: "circuit", cells: 2, main: [{ k: "bulb", label: "P" }, { k: "bulb", label: "Q" }, { k: "switch", label: "S", open: false }] }, o: ["It stays lit at the same brightness, as switch S is still closed.", "It goes out, as the circuit is now open and no current flows.", "It becomes brighter, as it no longer shares the current with P.", "It stays lit but becomes dimmer, as less current now reaches it."], a: 1, why: "P and Q are in series, so there is only one path for the current. Removing P breaks that path, the circuit becomes open and no current flows, so Q goes out even though S is closed.", lvl: 2 },
    { q: "Ahmad wants to find out if the number of coils of wire affects the strength of an electromagnet. Study the set-ups. Which TWO set-ups should he compare?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["20 coils", "1 battery", "Iron nail core"] }, { label: "B", icon: "box", lines: ["40 coils", "1 battery", "Iron nail core"] }, { label: "C", icon: "box", lines: ["40 coils", "2 batteries", "Iron nail core"] }, { label: "D", icon: "box", lines: ["40 coils", "1 battery", "Wooden rod core"] }] }, o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "Only the number of coils should differ. A and B differ only in coils (20 and 40). A and C also differ in batteries, C and D differ in batteries and core, and B and D differ only in the core, which tests a different variable.", lvl: 2 },
    { q: "The giant water lily in the ponds at the Singapore Botanic Gardens has very large, flat leaves that float on the water. How does this feature help the plant to survive?", o: ["The leaves can trap more light to make more food.", "The leaves can take in more water from the pond.", "The leaves can stop fish from eating its roots.", "The leaves can take in more oxygen to make food."], a: 0, why: "Large, flat leaves spread out on the water surface receive plenty of sunlight, so the plant can trap more light to make more food. Plants make food from carbon dioxide and water, not oxygen.", lvl: 2 },
    { q: "Kumar released a toy car from different heights on a ramp and measured how far it travelled along the same floor. Study the graph. If he releases the car from a height of 25 cm, how far will it most likely travel?", fig: { type: "bar", xl: "Height of release (cm)", yl: "Distance travelled (cm)", bars: [["10", 40], ["20", 80], ["30", 120], ["40", 160]] }, o: ["About 25 cm", "About 90 cm", "About 100 cm", "About 120 cm"], a: 2, why: "The distance goes up by 40 cm for every 10 cm of height, so 25 cm gives about halfway between 80 cm and 120 cm: about 100 cm. A greater height gives more gravitational potential energy, converted into more kinetic energy.", lvl: 2 },
    { q: "Which of the following is NOT a function of the stem of a plant?", o: ["It holds the plant upright.", "It carries water to the leaves.", "It carries food to other parts.", "It takes in water from the soil."], a: 3, why: "The roots take in water and mineral salts from the soil. The stem holds the plant upright, carries water up to the leaves and carries food made in the leaves to other parts.", lvl: 2 },
    { q: "A dented ping-pong ball was placed in a bowl of hot water. After a while, the dent popped out. Why?", o: ["The air inside lost heat and expanded.", "Hot water entered the ball and pushed it out.", "The plastic gained heat and contracted.", "The air inside gained heat and expanded."], a: 3, why: "The air inside gained heat from the hot water and expanded, pushing the dented plastic back out. Water cannot enter the sealed ball, and air expands when it gains heat, not when it loses heat.", lvl: 2 },
    { q: "Mei placed a sheet of each material, all of the same thickness, between a magnet and a pile of steel pins, and counted the pins the magnet attracted. Study the graph. Which statements are correct?\nA: The magnetic force can pass through paper, plastic and aluminium.\nB: The steel sheet reduced the number of pins attracted, as steel is a magnetic material.\nC: The thicker a sheet is, the fewer pins the magnet attracts.", fig: { type: "bar", xl: "Sheet between magnet and pins", yl: "Number of pins attracted", bars: [["None", 15], ["Paper", 15], ["Plastic", 15], ["Aluminium", 15], ["Steel", 3]] }, o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "With paper, plastic or aluminium the magnet attracted as many pins as with no sheet, so its force passed through them (A). Steel is magnetic and cut the number to 3 (B). All the sheets had the same thickness, so C was never tested.", lvl: 3 },
    { q: "Study the food web of a pond. Which statements are correct?\nA: The fish is both a predator and a prey.\nB: There are four food chains in this food web.\nC: If all the water beetles die, the fish still has other food.", fig: { type: "web", links: [["Algae", "Snail"], ["Algae", "Tadpole"], ["Tadpole", "Water beetle"], ["Tadpole", "Fish"], ["Water beetle", "Fish"], ["Snail", "Fish"], ["Fish", "Kingfisher"]] }, o: ["A and C only", "A only", "B and C only", "A, B and C"], a: 0, why: "The fish eats snails, tadpoles and water beetles and is eaten by the kingfisher (A). There are only 3 chains: algae→snail→fish→kingfisher, algae→tadpole→fish→kingfisher and algae→tadpole→water beetle→fish→kingfisher (B is wrong). The fish still eats snails and tadpoles (C).", lvl: 3 },
    { q: "On a hot afternoon, Siti noticed that the windows of an air-conditioned public bus were misty. Where did the mist form, and why?", o: ["Outside surface – warm water vapour in the air lost heat to the cool glass and condensed.", "Inside surface – cool water vapour in the bus gained heat from the warm glass and condensed.", "Outside surface – cool air from inside the bus seeped through the glass and condensed.", "Inside surface – water from the air-conditioner evaporated onto the glass and froze."], a: 0, why: "The air-conditioning cools the glass. Warm water vapour in the outside air touches the cool outer surface, loses heat and condenses into tiny droplets. Water vapour condenses when it LOSES heat, and air cannot pass through glass.", lvl: 3 },
    { q: "Jia Hui took a leaf with green parts and white parts from a plant that had been in sunlight all day. She tested both parts for starch with iodine solution, which turns dark blue when starch is present. Study the table. What can she conclude?", tbl: [["Part of leaf", "Colour of part", "Colour after adding iodine"], ["X", "Green", "Dark blue"], ["Y", "White", "Brown (no change)"]], o: ["Chlorophyll is needed for photosynthesis to take place.", "Light is needed for photosynthesis to take place.", "Carbon dioxide is needed for photosynthesis to take place.", "Water is needed for photosynthesis to take place."], a: 0, why: "Both parts were on the same leaf, so they received the same light, water and carbon dioxide. Only the green part, which has chlorophyll, made food (starch), so chlorophyll is needed for photosynthesis.", lvl: 3 },
    { q: "Blood samples P, Q and R were taken from blood vessels carrying blood away from the lungs, the small intestine and the leg muscles, in some order, soon after a meal. Study the table. Which correctly identifies where each sample came from?", tbl: [["Sample", "Oxygen", "Carbon dioxide", "Digested food"], ["P", "High", "Low", "Low"], ["Q", "Low", "High", "High"], ["R", "Low", "High", "Low"]], o: ["P: lungs; Q: small intestine; R: leg muscles", "P: small intestine; Q: lungs; R: leg muscles", "P: leg muscles; Q: small intestine; R: lungs", "P: lungs; Q: leg muscles; R: small intestine"], a: 0, why: "Blood leaving the lungs has picked up oxygen and given up carbon dioxide (P). Blood leaving the small intestine carries the digested food absorbed there (Q). Blood leaving the leg muscles has given oxygen and food to the cells and carries away carbon dioxide (R).", lvl: 3 },
    { q: "During Earth Hour, many buildings around Marina Bay switch off their lights for one hour. Most of Singapore’s electricity is produced by burning natural gas in power stations. Which statements are correct?\nA: Less natural gas needs to be burnt to produce electricity.\nB: Less carbon dioxide is released into the air.\nC: The lights give out less carbon dioxide while they are switched off.", o: ["A only", "B and C only", "A and B only", "A, B and C"], a: 2, why: "Using less electricity means less natural gas is burnt in the power stations (A), so less carbon dioxide is released (B). Lights do not give out carbon dioxide themselves – it comes from burning fuel at the power station, so C is wrong.", lvl: 3 },
    { q: "Study the circuit. With switch S open, bulbs P and Q light. Which statements are correct?\nA: Material X is an electrical conductor.\nB: If bulb P fuses, bulbs Q and R cannot light even when S is closed.\nC: If S is closed and bulb Q then fuses, bulbs P and R stay lit.\nD: If X is replaced with a rubber band while S is open, bulb P stays lit.", fig: { type: "circuit", cells: 2, main: [{ k: "bulb", label: "P" }], branches: [[{ k: "bulb", label: "Q" }, { k: "gap", label: "X", text: "material X" }], [{ k: "bulb", label: "R" }, { k: "switch", label: "S", open: true }]] }, o: ["A and B only", "A and C only", "A, B and C only", "A, B, C and D"], a: 2, why: "Q lights, so its branch is closed and X conducts electricity (A). P is on the main path shared by both branches, so if P fuses nothing lights (B). Q and R are in parallel, so R’s branch still works if Q fuses (C). With a rubber band at X and S open, both branches are open, so P goes out (D is wrong).", lvl: 4 },
    { q: "Wei released a toy car from different heights on a ramp onto two kinds of floor and measured how far it travelled. Study the table. Which statements are correct?\nA: Comparing P and Q shows that the car travels a shorter distance on a rougher surface.\nB: Comparing Q and S shows how the height of release affects the distance travelled.\nC: Comparing Q and R shows that, from a greater height, the car has more kinetic energy at the bottom of the ramp.", tbl: [["Set-up", "Height of release (cm)", "Floor surface", "Distance travelled (cm)"], ["P", "20", "Smooth tiles", "150"], ["Q", "20", "Carpet", "60"], ["R", "40", "Carpet", "115"], ["S", "40", "Smooth tiles", "290"]], o: ["A and B only", "B and C only", "A, B and C", "A and C only"], a: 3, why: "A fair comparison changes only one variable. P and Q differ only in the surface (A). Q and R differ only in height, and from 40 cm the car went further on the same carpet, so it had more kinetic energy at the bottom (C). Q and S differ in BOTH height and surface, so B is not a fair comparison.", lvl: 4 },
    { q: "The flowers of a plant are pollinated by insects. Before four of its flowers opened, Mr Lim treated them as shown in the table. A bag of fine netting keeps out both insects and pollen. Which statements are supported by the results?\nA: A fruit can form from pollen brought from other flowers.\nB: The stigma is needed for a fruit to form.\nC: Fertilisation can take place without pollination.", tbl: [["Flower", "Treatment", "Fruit formed?"], ["W", "Covered with a netting bag", "No"], ["X", "Anthers removed, not covered", "Yes"], ["Y", "Stigma removed, not covered", "No"], ["Z", "Anthers removed, covered with a netting bag", "No"]], o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "X had no anthers of its own yet formed a fruit, so pollen from other flowers can lead to a fruit (A). Y had no stigma to receive pollen and formed no fruit (B). Z received no pollen at all and formed no fruit, so fertilisation needs pollination first (C is wrong).", lvl: 4 }
  ],
  oe: [
    { q: "Some HDB multi-storey car parks in Singapore have rooftop gardens. Mr Ong measured the surface temperature of two identical concrete roofs on a sunny day: roof P was bare, and roof Q was covered with plants growing in soil. Study the table.\n(a) Which roof had the lower surface temperature at 1 pm? [1]\n(b) Explain why the plants keep the roof surface cooler. [1]\n(c) Besides cooling, explain how the rooftop garden helps to reduce the amount of carbon dioxide in the air. [1]", tbl: [["Time", "Roof P – bare (°C)", "Roof Q – plants (°C)"], ["9 am", "30", "29"], ["11 am", "41", "31"], ["1 pm", "50", "33"], ["3 pm", "46", "32"]], marks: 3, kw: [["roof q", "q", "covered with plants", "with plants", "the garden", "green roof"], ["block", "shade", "less heat", "less light", "less sunlight", "prevent", "stop the sunlight", "stops the sunlight"], ["take in carbon dioxide", "takes in carbon dioxide", "taking in carbon dioxide", "absorb carbon dioxide", "absorbs carbon dioxide", "use carbon dioxide", "uses carbon dioxide", "photosynth"]], model: "(a) Roof Q, the roof covered with plants. (b) The plants block the sunlight from reaching the roof, so the roof surface gains less heat from the Sun. (c) The plants take in carbon dioxide from the air to make food during photosynthesis." },
    { q: "For Deepavali, Mr Raj connected three bulbs, A, B and C, to light up his doorway as shown. When switch S was closed, all three bulbs lit. Then bulb B fused, and bulbs A and C went out too.\n(a) Explain why bulbs A and C went out when bulb B fused. [1]\n(b) Suggest how Mr Raj should connect the bulbs so that the others stay lit when one bulb fuses. [1]\n(c) State the energy conversion that takes place in the batteries when the circuit is closed. [1]", fig: { type: "circuit", cells: 2, main: [{ k: "bulb", label: "A" }, { k: "bulb", label: "B" }, { k: "bulb", label: "C" }, { k: "switch", label: "S", open: false }] }, marks: 3, kw: [["open circuit", "circuit is open", "circuit was open", "circuit became open", "circuit is broken", "circuit was broken", "broken", "incomplete", "break in the circuit", "no current", "no electric current"], ["parallel", "separate path", "own path", "different path", "own branch", "separate branch", "different branch"], ["chemical potential energy to electrical", "chemical potential energy into electrical", "chemical potential energy is converted into electrical", "chemical potential energy electrical", "chemical energy to electrical", "chemical energy into electrical", "chemical energy electrical"]], model: "(a) The bulbs are connected in series, so there is only one path for the current. When bulb B fused, the circuit became open and no electric current flowed through bulbs A and C. (b) Connect the bulbs in parallel, so that each bulb is on its own path. (c) Chemical potential energy is converted into electrical energy." },
    { q: "Ali built a solar still at East Coast Park to get drinking water from seawater. Seawater was placed in a black tray covered with a sloping clear plastic sheet. Water droplets formed on the underside of the sheet, ran down and dripped into a cup. Study the graph of the total volume of water collected.\n(a) Explain how water from the seawater ended up in the cup. [2]\n(b) Explain why the water collected in the cup is not salty. [1]\n(c) The volume collected increased most quickly between 12 pm and 2 pm. Explain why. [1]", fig: { type: "line", xl: "Time of day", yl: "Total volume of water collected (ml)", pts: [["8 am", 0], ["10 am", 30], ["12 pm", 100], ["2 pm", 190], ["4 pm", 250], ["6 pm", 270]] }, marks: 4, kw: [["evaporat"], ["condens"], ["salt is left", "salt was left", "salt remains", "salt stays", "salt does not evaporate", "salt doesn't evaporate", "salt cannot evaporate", "only water evaporates", "only the water evaporates", "only water evaporated", "only the water evaporated"], ["hottest", "highest temperature", "higher temperature", "hotter", "more heat", "most heat", "strongest"]], model: "(a) The seawater gained heat from the Sun and evaporated into water vapour. The water vapour touched the cooler plastic sheet, lost heat and condensed into water droplets, which ran down into the cup. (b) Only the water evaporates; the salt is left behind in the tray. (c) Around midday the Sun is strongest, so the seawater gains the most heat and evaporates fastest.", x: 1 },
    { q: "Pitcher plants grow in some nature reserves in Singapore, in soil that has very little mineral salts. They have green leaves, and some leaves form a pitcher with a slippery rim and a pool of digestive juices inside. Insects attracted by its nectar fall in and are digested.\n(a) The pitcher plant is a producer. Explain why. [1]\n(b) Explain how trapping insects helps the pitcher plant to survive in this soil. [1]\n(c) Explain how the slippery rim helps the pitcher plant to trap insects. [1]", marks: 3, kw: [["makes its own food", "make its own food", "makes food", "make food", "photosynth"], ["mineral salt", "nutrient", "nitrogen"], ["slip", "slide"]], model: "(a) It has green leaves with chlorophyll, so it makes its own food by photosynthesis. (b) The digested insects give the plant the mineral salts that it cannot get enough of from the poor soil, so it can grow healthily. (c) Insects that land on the rim slip and fall into the pitcher, where they are trapped and digested." }
  ],
  tf: [
    { s: "A bigger magnet is always stronger than a smaller magnet.", a: false, why: "The strength of a magnet does not depend on its size; a small magnet can attract more pins than a bigger one. Test strength by counting the pins or clips each magnet attracts." },
    { s: "Light from the Sun can travel through space to reach the Earth.", a: true, why: "Light does not need air or any other material to travel through, so it can travel through space from the Sun to the Earth." },
    { s: "Digestion of food begins in the stomach.", a: false, why: "Digestion begins in the mouth: the teeth break food into smaller pieces and saliva starts to digest it. The stomach continues the digestion." },
    { s: "Digestion of food is completed in the small intestine.", a: true, why: "Digestive juices in the small intestine complete the digestion of food, and the digested food is absorbed into the blood there." },
    { s: "Seeds need light to germinate.", a: false, why: "Seeds need water, air and warmth to germinate, and they can germinate in the dark. The young seedling needs light later to make its own food." },
    { s: "The seeds of the balsam plant are dispersed when its ripe fruit splits open.", a: true, why: "The ripe balsam fruit splits open suddenly and flings its seeds away from the parent plant." },
    { s: "Friction acts only between rough surfaces.", a: false, why: "Friction acts between any two surfaces in contact, even smooth ones. Smoother surfaces just produce less friction." },
    { s: "A green plant can use some of the oxygen it makes during photosynthesis for its own respiration.", a: true, why: "A plant respires all the time, so its cells can use some of the oxygen made during photosynthesis; the extra oxygen is given out." },
    { s: "All good conductors of electricity are metals.", a: false, why: "Most metals are good conductors of electricity, but some non-metals also conduct electricity, such as graphite (pencil lead)." },
    { s: "Both the water cycle and the food chains on Earth depend on energy from the Sun.", a: true, why: "Heat from the Sun makes water evaporate, and plants use light from the Sun to make food, which starts every food chain." }
  ]
};
