window.LBZ = window.LBZ || {};
LBZ["p6-mixed"] = {
  flash: [
    { f: "Define: photosynthesis", b: "The process in which green plants use light energy, trapped by chlorophyll, to make food (sugar) from carbon dioxide and water. Oxygen is given out." },
    { f: "Define: respiration", b: "The process in which living cells break down food, using oxygen, to release energy. Carbon dioxide and water are given out. It takes place in all living things, day and night." },
    { f: "Define: producer", b: "An organism that makes its own food, e.g. a green plant. It is always the first organism in a food chain." },
    { f: "Role of decomposers (e.g. bacteria and fungi)", b: "They break down dead plants and animals into simpler substances, returning nutrients (mineral salts) to the soil for plants to use." },
    { f: "Define: community", b: "All the populations of different kinds of organisms living and interacting together in the same habitat." },
    { f: "Define: adaptation", b: "A structural or behavioural characteristic that helps an organism to survive in its environment." },
    { f: "What do the arrows in a food chain show?", b: "The direction in which energy (food) flows: from the organism that is eaten to the organism that eats it." },
    { f: "Define: fertilisation (in flowering plants)", b: "The fusing of the male reproductive cell from the pollen grain with the female reproductive cell in the ovule. The ovule then develops into a seed and the ovary into a fruit." },
    { f: "Function of the heart", b: "Pumps blood around the body, so that oxygen and digested food are carried to all the cells, and carbon dioxide is carried away to the lungs." },
    { f: "What does the gravitational potential energy of an object depend on?", b: "Its mass and its height above the ground. The heavier the object, or the higher it is, the more gravitational potential energy it has." },
    { f: "Effects of friction", b: "Friction opposes motion between two surfaces in contact. It slows down or stops moving objects, produces heat and causes wear and tear." },
    { f: "Series vs parallel: what happens when one bulb fuses?", b: "Series: the circuit is broken (open), so all the bulbs go out. Parallel: each bulb is on its own path, so the other bulbs are still in a closed circuit and stay lit." },
    { f: "Explain how water droplets form on a cold surface.", b: "Warm water vapour in the surrounding air comes into contact with the cooler surface, loses heat and condenses into water droplets." },
    { f: "How do burning fuels and cutting down forests cause global warming?", b: "Burning releases carbon dioxide, and fewer trees take in carbon dioxide for photosynthesis. More carbon dioxide traps more heat, so the Earth becomes warmer." },
    { f: "Energy conversions when a ball is dropped and bounces lower each time", b: "Gravitational potential energy → kinetic energy as it falls. At each bounce, some energy is converted into heat and sound energy, so it has less energy to rise as high." }
  ],
  mcq: [
    { q: "Which of these organisms is a decomposer?", o: ["Hibiscus plant", "Bread mould", "Caterpillar", "Spider"], a: 1, why: "Bread mould is a fungus that breaks down dead matter (the bread) and returns nutrients to the environment. The hibiscus is a producer; the caterpillar and spider are consumers.", lvl: 1 },
    { q: "Study the plant cell. Which part controls all the activities of the cell?", o: ["P", "Q", "R", "S"], a: 2, why: "R is the nucleus, which controls all the activities of the cell. P is the cell wall (gives shape and support), Q is the cell membrane (controls what enters and leaves) and S is the vacuole.", lvl: 1, fig: { type: "cell", kind: "plant", mark: { cell_wall: "P", cell_membrane: "Q", nucleus: "R", vacuole: "S" } } },
    { q: "An electric kettle is used to boil water at a school canteen stall. What is the main energy conversion in the kettle?", o: ["Electrical energy → heat energy", "Heat energy → electrical energy", "Chemical potential energy → heat energy", "Kinetic energy → electrical energy"], a: 0, why: "The kettle converts electrical energy from the mains supply into heat energy, which the water gains. No fuel is burnt, so the input is not chemical potential energy.", lvl: 1 },
    { q: "Which of these forces can act on an object WITHOUT touching it?", o: ["Friction", "Air resistance", "Elastic spring force", "Gravitational force"], a: 3, why: "Gravitational force (gravity) pulls objects towards the Earth without contact. Friction, air resistance and elastic spring force act only when surfaces are in contact.", lvl: 1 },

    { q: "Study the food web of a pond. Which statement is NOT correct?", o: ["The algae are the only producer.", "The small fish is both a predator and a prey.", "The kingfisher is found in every food chain.", "The dragonfly nymph feeds on the algae."], a: 3, why: "The arrow into the dragonfly nymph comes from the tadpole, not the algae, so it feeds on tadpoles. All three food chains start with algae and end with the kingfisher, and the small fish both eats and is eaten.", lvl: 2, fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water flea", "small fish"], ["tadpole", "small fish"], ["tadpole", "dragonfly nymph"], ["dragonfly nymph", "small fish"], ["small fish", "kingfisher"]] } },
    { q: "Study the circuit. Which of these objects, placed across gap X, will make bulb L light up?\nA: copper wire\nB: rubber band\nC: pencil lead (graphite)\nD: steel key", o: ["A and B only", "A, C and D only", "B and C only", "B, C and D only"], a: 1, why: "Copper, graphite and steel are electrical conductors, so they close the circuit. Rubber is an electrical insulator, so the circuit stays open.", lvl: 2, fig: { type: "circuit", cells: 2, main: [{ k: "bulb", label: "L" }, { k: "gap", label: "X", text: "?" }] } },
    { q: "Hui Min’s pulse rate was measured before and after the 2.4 km run during her school’s fitness test. Study the table. Why was her pulse rate higher right after the run?", o: ["Her lungs pumped blood faster to remove more oxygen", "Her muscles needed less energy, so blood flowed faster", "Her heart pumped faster to carry more oxygen to the muscles", "Her blood carried more digested food back to the stomach"], a: 2, why: "During the run her muscle cells needed more energy, so they respired faster. The heart beat faster to carry more oxygen and digested food to them and remove more carbon dioxide. The lungs do not pump blood.", lvl: 2, tbl: [["When measured", "Pulse rate (beats per minute)"], ["Before the run", "75"], ["Right after the run", "135"], ["After resting for 5 minutes", "96"]] },
    { q: "Ravi wants to find out if seeds need air to germinate. Study the set-ups. Which TWO set-ups should he compare?", o: ["W and Y", "X and Z", "W and X", "Y and Z"], a: 2, why: "W and X both give the seeds water and keep them in the dark; the key difference is air, as boiled water with a layer of oil keeps air out of X. X and Z differ only in light, so they would test the need for light instead.", lvl: 2, fig: { type: "setups", items: [{ label: "W", icon: "dish", lines: ["10 bean seeds", "Wet cotton wool", "Open to the air", "Dark cupboard"] }, { label: "X", icon: "beaker", lines: ["10 bean seeds", "Boiled, cooled water", "Layer of oil on top", "Dark cupboard"] }, { label: "Y", icon: "dish", lines: ["10 bean seeds", "Dry cotton wool", "Open to the air", "Window sill"] }, { label: "Z", icon: "beaker", lines: ["10 bean seeds", "Boiled, cooled water", "Layer of oil on top", "Window sill"] }] } },
    { q: "A lift in an HDB block carries Mr Lee from level 1 up to level 12. What happens to his gravitational potential energy, and what supplies this energy?", o: ["It increases; electrical energy used by the lift motor", "It decreases; electrical energy used by the lift motor", "It increases; chemical potential energy in his muscles", "It stays the same, as the lift moves at a steady speed"], a: 0, why: "He is higher above the ground, so his gravitational potential energy increases. The lift motor converts electrical energy to lift him; he does not use his own muscles.", lvl: 2 },
    { q: "Which pair correctly matches a part of a flower with its function?", o: ["Stigma — produces the ovules", "Ovary — produces pollen grains", "Petal — receives pollen grains", "Anther — produces pollen grains"], a: 3, why: "The anther produces pollen grains. The stigma receives pollen grains, the ovary contains the ovules, and brightly coloured petals attract insects.", lvl: 2 },
    { q: "Wire is coiled around an iron nail and connected to a battery to make an electromagnet. Which statements are correct?\nA: It is magnetic only when an electric current flows through the coil.\nB: It can be made stronger by adding more coils of wire.\nC: It can attract a copper wire if enough batteries are used.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "An electromagnet is a temporary magnet that works only while current flows, and more coils make it stronger. Copper is not a magnetic material, so no electromagnet can attract it.", lvl: 2 },

    { q: "A ball was dropped from a height of 2 m onto four different floor surfaces, and the height of its first bounce was measured. Study the graph. Which conclusion is correct?", o: ["On carpet, the most energy was converted into heat and sound", "On concrete, the ball gained extra energy from the floor", "On the rubber mat, the ball hit the floor with the most energy", "On every floor, the ball kept all of its original energy"], a: 0, why: "The ball hit every floor with the same energy, as it fell from the same height. It bounced lowest on carpet, so the least energy was left as kinetic energy and the most was converted into heat and sound. No ball rose to 2 m, so energy was not kept or gained.", lvl: 3, fig: { type: "bar", xl: "Floor surface", yl: "Height of first bounce (m)", bars: [["Concrete", 1.4], ["Wood", 1.1], ["Rubber mat", 0.6], ["Carpet", 0.3]] } },
    { q: "Study the circuit. The batteries and both bulbs are working. Materials X and Y are placed across the gaps. Only bulb P lights up. What can you conclude about X and Y?", o: ["X and Y are both electrical conductors", "X is a conductor and Y is an insulator", "X is an insulator and Y is a conductor", "X and Y are both electrical insulators"], a: 1, why: "X is on the main path, so it must conduct for P to light. Q is on a separate path with Y, and Q does not light, so Y must be an electrical insulator that leaves Q’s path open.", lvl: 3, fig: { type: "circuit", cells: 2, main: [{ k: "gap", label: "X", text: "?" }], branches: [[{ k: "bulb", label: "P" }], [{ k: "bulb", label: "Q" }, { k: "gap", label: "Y", text: "?" }]] } },
    { q: "Floating solar panels cover part of Tengeh Reservoir in Singapore. Which statements about them are correct?\nA: They convert light energy into electrical energy.\nB: They reduce evaporation from the covered part of the reservoir.\nC: They produce electricity without giving out carbon dioxide while working.\nD: They increase photosynthesis by water plants under them.", o: ["A and B only", "B and D only", "A, B and C only", "A, C and D only"], a: 2, why: "Solar panels convert light energy into electrical energy without burning fuel, and the cover reduces evaporation from the water below. They block light, so water plants under them photosynthesise LESS, not more.", lvl: 3 },
    { q: "Cells P, Q and R were taken from a green leaf, the skin of an onion bulb and the inside of a human cheek, in some order. Study the table. Which correctly identifies the cells?", o: ["P: onion skin, Q: leaf, R: cheek", "P: leaf, Q: onion skin, R: cheek", "P: cheek, Q: onion skin, R: leaf", "P: leaf, Q: cheek, R: onion skin"], a: 1, why: "Only plant cells have a cell wall, so R (no cell wall) is the cheek cell. The onion bulb grows underground and is not green, so its cells have no chloroplasts (Q); the leaf cell has chloroplasts (P).", lvl: 3, tbl: [["Cell", "Cell wall", "Chloroplasts", "Nucleus"], ["P", "Yes", "Yes", "Yes"], ["Q", "Yes", "No", "Yes"], ["R", "No", "No", "Yes"]] },
    { q: "At Sungei Buloh Wetland Reserve, mangrove plants grow in soft, salty, waterlogged mud. Which of these is NOT an adaptation that helps them survive there?", o: ["Breathing roots that grow up out of the mud", "Prop roots that support the plant in soft mud", "Seeds that start to germinate on the parent tree", "Large, thin leaves that lose water quickly"], a: 3, why: "Losing water quickly would not help a plant that must save fresh water in a salty habitat; mangrove leaves are thick and waxy. Breathing roots take in air, prop roots give support, and seedlings that start growing on the tree can take root quickly in mud.", lvl: 3 },
    { q: "Study the graph of the length of a lamp post’s shadow in a school field on a sunny day. What is the most likely length of the shadow at 3 pm, and why?", o: ["About 4.5 m; the Sun is lower in the sky", "About 1.5 m; the Sun is higher in the sky", "About 4.5 m; the Sun is higher in the sky", "About 1.5 m; the Sun is lower in the sky"], a: 0, why: "3 pm is between 2 pm (3 m) and 4 pm (6 m), so the shadow is about 4.5 m. In the afternoon the Sun sinks lower in the sky, so the lamp post blocks light over a longer area.", lvl: 3, fig: { type: "line", xl: "Time of day", yl: "Length of shadow (m)", pts: [["8 am", 6], ["10 am", 3], ["12 pm", 1], ["2 pm", 3], ["4 pm", 6]] } },

    { q: "Study the food web. P is a plant. A disease kills all of organism R. Which statements are most likely correct?\nA: Q will increase at first, as more P is left for it to eat.\nB: S will decrease, as U now feeds only on S.\nC: V will die out, as it depends on R for its food.", o: ["A only", "B and C only", "A and B only", "A, B and C"], a: 2, why: "R no longer eats P, so Q has more food and increases. U has lost R as food, so it eats more S and S decreases. V does not eat R; it still has T and U to eat, so it will not die out.", lvl: 4, fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["Q", "S"], ["Q", "T"], ["S", "U"], ["R", "U"], ["T", "V"], ["U", "V"]] } },
    { q: "A sealed glass bottle garden with soil, small plants and tiny soil animals is kept near a classroom window. It stays healthy for months without being opened or watered. Which statements are correct?\nA: Water vapour from the soil and plants condenses on the cooler inner wall and drips back into the soil.\nB: The plants use carbon dioxide given out by the living things in the bottle to photosynthesise.\nC: The plants do not need oxygen, as they make their own food.\nD: The total mass of the bottle and its contents stays about the same.", o: ["A and D only", "A, B and D only", "B and C only", "A, B, C and D"], a: 1, why: "Water is recycled by evaporation and condensation, and carbon dioxide from respiration is used for photosynthesis. Nothing enters or leaves the sealed bottle, so its mass stays about the same. C is wrong: plant cells respire all the time and need oxygen.", lvl: 4 },
    { q: "At a hawker centre where the air is at 32 °C, equal amounts of ice at 0 °C are put into a steel cup and a plastic cup of the same size and thickness. Which statements are correct?\nA: The ice in the steel cup melts faster, as steel conducts heat from the surroundings to the ice faster.\nB: Water droplets form faster on the outside of the steel cup, as its outer surface becomes colder.\nC: The plastic cup keeps the ice from melting quickly because plastic gives out coldness slowly.", o: ["A only", "B only", "A and C only", "A and B only"], a: 3, why: "Steel is a better conductor of heat, so heat flows through it to the ice faster, and its outer surface quickly becomes cold enough for water vapour in the air to condense on it. ‘Coldness’ does not flow; plastic simply conducts heat to the ice slowly.", lvl: 4 }
  ],
  oe: [
    { q: "Study the circuit of a torch with two bulbs, A and B. Switch S is closed and both bulbs are lit.\n(a) Bulb A fuses. Will bulb B still light? Explain your answer. [2]\n(b) Besides heat, what useful form of energy do the bulbs give out? [1]\n(c) After many hours of use, both bulbs become dim. Suggest why. [1]", marks: 4, kw: [["yes", "still light", "will light", "stays lit", "remains lit"], ["own path", "separate path", "different path", "still a closed circuit", "still in a closed circuit"], ["light energy"], ["chemical potential energy", "used up", "run down", "running out", "run out", "weaker", "less energy"]], model: "(a) Yes, bulb B will still light. The bulbs are connected in parallel, so bulb B is on its own separate path, which is still a closed circuit. (b) Light energy. (c) The batteries have used up most of their chemical potential energy, so less electrical energy flows to the bulbs.", fig: { type: "circuit", cells: 2, main: [{ k: "switch", label: "S", open: false }], branches: [[{ k: "bulb", label: "A" }], [{ k: "bulb", label: "B" }]] } },
    { q: "Jun pulled back the rubber band of a catapult by different distances and launched the same paper ball each time. Study the table.\n(a) What is the relationship between how far the rubber band is pulled back and the distance travelled by the ball? [1]\n(b) Using ideas about energy, explain this relationship. [2]\n(c) State one variable Jun must keep the same to make this a fair test. [1]", marks: 4, kw: [["further", "farther", "greater distance", "longer distance", "travels more"], ["elastic potential"], ["kinetic"], ["same rubber band", "same paper ball", "same ball", "same catapult", "same angle", "same height", "same direction"]], model: "(a) The further the rubber band is pulled back, the further the ball travels. (b) A rubber band that is stretched more has more elastic potential energy. More of it is converted into kinetic energy of the ball, so the ball moves faster and travels a greater distance. (c) He must use the same rubber band (and launch at the same angle).", tbl: [["Distance rubber band is pulled back (cm)", "Distance travelled by paper ball (m)"], ["5", "2.0"], ["10", "4.1"], ["15", "5.9"]] },
    { q: "Singapore plants many trees along its roads and park connectors.\n(a) Explain how planting more trees helps to reduce the amount of carbon dioxide in the air. [2]\n(b) The pavement under a large tree feels cooler on a sunny afternoon. Explain why. [1]\n(c) A forest is cleared to build a new road. State one way this may harm the animals living there. [1]", marks: 4, kw: [["photosynth", "make food", "makes food"], ["take in carbon dioxide", "takes in carbon dioxide", "use carbon dioxide", "uses carbon dioxide", "absorb carbon dioxide", "absorbs carbon dioxide", "taking in carbon dioxide"], ["block", "shade", "shadow"], ["habitat", "home", "shelter", "food"]], model: "(a) Trees photosynthesise in sunlight to make food. They take in carbon dioxide from the air to do so, so more trees remove more carbon dioxide. (b) The leaves of the tree block the sunlight, so less heat from the Sun reaches the pavement in the shadow. (c) The animals lose their habitat, so they have less food and shelter and may die." },
    { q: "In an electric doorbell, pressing the button closes the circuit. An electromagnet then pulls a metal striker, which hits a bell. When the button is released, a spring pulls the striker back.\n(a) Explain why the striker must be made of iron and not aluminium. [1]\n(b) Explain why the striker moves back when the button is released. [2]\n(c) The moving striker hits the bell and the bell rings. State the energy conversion in the doorbell, starting with electrical energy. [1]", marks: 4, kw: [["magnetic material", "iron is magnetic", "attracted", "attract"], ["open circuit", "circuit is open", "circuit is broken", "no current", "no electric current", "current stops", "stops flowing"], ["loses its magnetism", "lose its magnetism", "loses magnetism", "no longer a magnet", "not a magnet", "no magnetism", "stops being a magnet"], ["kinetic"]], model: "(a) Iron is a magnetic material, so it is attracted by the electromagnet, but aluminium is not. (b) The circuit is open, so no electric current flows through the coil. The electromagnet loses its magnetism and no longer attracts the striker, so the spring force pulls it back. (c) Electrical energy → kinetic energy (of the striker) → sound energy.", x: 1 }
  ],
  tf: [
    { s: "Without decomposers, nutrients in dead plants and animals would not be returned to the soil.", a: true, why: "Decomposers such as bacteria and fungi break down dead matter and return mineral salts to the soil for plants to use." },
    { s: "Gravitational force acts only on heavy objects.", a: false, why: "Gravity pulls on every object that has mass, light or heavy — a feather and a pencil are both pulled towards the Earth." },
    { s: "Friction acts only when an object is already moving.", a: false, why: "Friction can also stop a still object from starting to move, e.g. it keeps a book on a slightly tilted table from sliding down." },
    { s: "Adding more bulbs in series in a circuit makes each bulb dimmer.", a: true, why: "With more bulbs in series, less electric current flows through the circuit, so each bulb is dimmer." },
    { s: "The food-carrying tubes carry food made in the leaves to other parts of the plant.", a: true, why: "Food made in the leaves by photosynthesis is carried by the food-carrying tubes to all parts, including the roots and fruits." },
    { s: "An object that is not moving has no energy.", a: false, why: "A still object can have stored energy, e.g. a book on a high shelf has gravitational potential energy and a battery has chemical potential energy." },
    { s: "The white mist seen just above the spout of a boiling kettle is steam.", a: false, why: "Steam (water vapour) is invisible. The white mist is tiny water droplets formed when the steam loses heat to the cooler air and condenses." },
    { s: "Fertilisation must take place before a fruit containing seeds can form.", a: true, why: "After fertilisation, the ovule develops into a seed and the ovary develops into a fruit." },
    { s: "Burning fossil fuels in power stations increases the amount of carbon dioxide in the air.", a: true, why: "Burning fuels such as natural gas releases carbon dioxide, which adds to global warming." },
    { s: "A heavier object always has more gravitational potential energy than a lighter object.", a: false, why: "Gravitational potential energy depends on height as well as mass, so a light object high up can have more than a heavy object on the ground." }
  ],
  sort: [
    { title: "Sort each device by the MAIN useful form of energy it gives out.", groups: ["Light energy", "Kinetic energy", "Heat energy", "Sound energy"], items: [["LED torch", 0], ["Solar garden lamp at night", 0], ["Electric fan", 1], ["Wind-up toy car", 1], ["MRT train motor", 1], ["Rice cooker", 2], ["Electric iron", 2], ["School bell", 3], ["Radio", 3], ["Doorbell", 3]] }
  ]
};
