window.LB = window.LB || {};
// PSLE Technique — P6 process skills and answer technique across all P3–P6 topics
LB["p6-skills"] = {
  notes: [
    { h: "Three kinds of variables", t: "The variable changed is what you change on purpose; the variable measured is the result you measure, count or observe; the variables kept the same (constant) are everything else that could affect the result. Name each variable in full, e.g. ‘the distance of the lamp from the water plant’, not ‘the lamp’, and ‘the number of bubbles given off in 5 minutes’, not ‘the bubbles’.", kw: ["variable changed", "variable measured", "variables kept the same", "name it in full"] },
    { h: "Writing the aim", t: "The aim links the variable changed to the variable measured: ‘To find out how the height of the ramp affects the distance travelled by the toy car.’ When PSLE asks ‘What is Ben trying to find out?’, write it in this ‘how X affects Y’ form. A hypothesis is a testable prediction of the same link, e.g. ‘The higher the ramp, the further the car travels.’", kw: ["to find out how", "affects", "hypothesis"] },
    { h: "Fair tests and choosing set-ups", t: "A test is fair only when the set-ups being compared differ in ONE variable, the one being tested. If two variables differ, we cannot tell which one caused the difference in the results. To answer ‘Which two set-ups should be compared?’, find the pair that is identical except for the variable named in the question.", kw: ["only one variable", "cannot tell which variable", "identical except"] },
    { h: "The control set-up", t: "A control set-up is identical to the experimental set-up except that the variable being tested is absent or unchanged (a shoot without leaves, a dish without fertiliser, a circuit with the clips touching). It is used for comparison, to show that the result is due to the variable being tested and not to other factors.", kw: ["for comparison", "identical except", "due to the variable being tested"] },
    { h: "Reliability and accuracy", t: "Repeat the experiment at least three times and find the average, or use more samples (20 seeds instead of 2), so one odd result affects the conclusion less and the results are more reliable. Accuracy comes from the right instrument used correctly: a thermometer or temperature sensor, a light sensor with a data logger, a measuring cylinder read at eye level. Repeating does NOT make a test fairer.", kw: ["repeat", "average", "more reliable", "more samples", "data logger"] },
    { h: "Reading graphs and tables", t: "Read the title, both axis labels (or column headings) and the units before looking at the numbers. On a line graph, a steeper line means a faster change and a flat line means no change; check that the x-axis steps are equal before judging steepness. In a table with two measured columns, compare them at the SAME value of the variable changed.", kw: ["steeper", "faster change", "flat line", "same value", "units"] },
    { h: "Describing relationships", t: "Name both variables and the direction: ‘As the temperature of the water increased, the time taken for the ice to melt decreased.’ If the pattern changes, describe each part with the value where it changes: ‘...increased until 30 °C, then decreased.’ ‘The time decreased’ scores nothing because it names only one variable.", kw: ["as", "increased", "decreased", "both variables", "then"] },
    { h: "Predicting and inferring", t: "To predict, continue the pattern in the data (e.g. the spring stretches 2 cm more for every extra 20 g) and give a value with its unit. An observation is what you see or measure; an inference is a conclusion you draw from it using science ideas. Label clearly which is which when a question asks for either.", kw: ["continue the pattern", "observation", "inference", "unit"] },
    { h: "Unexpected results and improvements", t: "An unexpected result (anomaly) does not follow the pattern. Explain it with a possible cause: a mistake in measuring, or a variable not kept the same (a bigger ice cube, a draughty spot, a weaker battery). To improve an experiment, state the exact change AND why it helps: ‘Use a light sensor instead of our eyes, so that the brightness is measured more accurately.’", kw: ["anomaly", "does not follow the pattern", "variable not kept the same", "state the change and why"] },
    { h: "Evaluating conclusions", t: "A conclusion is valid only if the test was fair and the data actually shows it. It must stay within the range tested (20–60 °C tells you nothing about 90 °C) and within what was tested (one type of plant cannot prove ‘all plants’). Words like ‘of the temperatures tested’ or ‘for this plant’ keep a conclusion accurate.", kw: ["fair", "data supports", "within the range tested", "all plants"] },
    { h: "Claim, Evidence, Reasoning (CER)", t: "Claim: answer the question directly (‘Material A is the better heat insulator.’). Evidence: quote the data with numbers or set-up letters (‘the water in A was 62 °C after 20 minutes, compared with 45 °C in B’). Reasoning: link the evidence to a science concept with its keywords (‘A is a poorer conductor of heat, so less heat was lost from the water to the surroundings’).", kw: ["claim", "evidence", "reasoning", "quote the data"] },
    { h: "State, describe, explain: precise answers", t: "State or name: a short fact, no reason needed. Describe: say what happens or the pattern, using the data. Explain: give the reason, the ‘because’ and the science. Use PSLE keywords exactly (‘gains heat’, ‘closed circuit’, ‘poor conductor of heat’, ‘makes food’), compare with ‘more / faster than’, and look at the marks: 2 marks usually means two ideas.", kw: ["state", "describe", "explain", "because", "keywords"] }
  ],
  traps: [
    "‘Repeat the experiment to make it fair’ -> repeating makes results more RELIABLE; keeping other variables the same makes a test FAIR.",
    "‘The variable changed is the pot’ -> name a variable, not an object: ‘the amount of water given to the plant each day’.",
    "‘The height increases’ for a relationship -> name BOTH variables: ‘As the amount of light increases, the height of the plant increases.’",
    "Choosing set-ups that differ in two things -> the pair you compare must be identical except for the ONE variable being tested.",
    "Answering an ‘explain’ question with only what was seen -> add the reason and the science concept (the ‘because’).",
    "Judging steepness on a graph with uneven steps (0, 2, 4, 8, 16) -> work out the change per minute before deciding which part is fastest.",
    "‘Seeds grow best at 30 °C’ from tests at 10, 20, 30 and 40 °C -> say ‘of the temperatures tested, most seeds germinated at 30 °C’.",
    "‘Be more careful’ or ‘use better things’ as an improvement -> give an exact change and say what it improves (e.g. use a thermometer, repeat and average)."
  ],
  lessons: [
    {
      h: "Picking the pair of set-ups for a fair test",
      concept: "PSLE often shows three or four set-ups and asks which two should be compared to test one variable. List every difference between each pair. The correct pair differs ONLY in the variable named in the question; every other condition, including amounts, place and time, must be the same. If a pair differs in two things, any difference in results cannot be linked to one variable.",
      example: {
        q: "Jia Hui let the same toy car roll down ramps. Study the set-ups. Which two set-ups should she compare to find out how the height of the ramp affects the distance the car travels? Explain your choice.",
        fig: { type: "setups", items: [ { label: "P", icon: "box", lines: ["Ramp 20 cm high", "Wooden surface"] }, { label: "Q", icon: "box", lines: ["Ramp 20 cm high", "Carpet surface"] }, { label: "R", icon: "box", lines: ["Ramp 30 cm high", "Carpet surface"] }, { label: "S", icon: "box", lines: ["Ramp 30 cm high", "Glass surface"] } ] },
        marks: 2,
        think: [
          "Step 1: The variable to be tested is the height of the ramp, so the two set-ups must have different heights.",
          "Step 2: Pairs with different heights: P and R (surface also differs), P and S (surface also differs), Q and R (same carpet), Q and S (surface also differs).",
          "Step 3: Only Q and R differ in height alone. Write the pair and say what is kept the same."
        ],
        answer: "Q and R. They differ only in the height of the ramp (20 cm and 30 cm), while the type of surface (carpet) is the same, so any difference in the distance travelled is due to the height of the ramp."
      },
      tip: "Tick off each variable for both set-ups; the right pair has exactly ONE row that differs.",
      try: {
        q: "Farid wants to find out whether the exposed surface area of water affects how fast it evaporates. Study the set-ups. Which two should he compare?",
        fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["100 ml water", "Wide dish", "Under a fan"] }, { label: "B", icon: "beaker", lines: ["100 ml water", "Narrow beaker", "Under a fan"] }, { label: "C", icon: "beaker", lines: ["100 ml water", "Narrow beaker", "No fan"] }, { label: "D", icon: "dish", lines: ["50 ml water", "Wide dish", "No fan"] } ] },
        o: ["A and D", "B and C", "C and D", "A and B"],
        a: 3,
        why: "A and B both hold 100 ml and are both under a fan; only the shape of the container, and so the exposed surface area, differs. C and D also differ in the volume of water, B and C differ only in the wind, and A and D differ in volume and wind."
      }
    },
    {
      h: "Describing a relationship from a graph",
      concept: "A relationship answer needs both variables and the direction of change: ‘As X increases, Y increases / decreases.’ Look along the whole line first. If the line changes shape (rises then flattens, rises then falls), describe each part and name the value where it changes. Quote a number or two if the question says ‘use the data’.",
      example: {
        q: "Ravi heated a beaker of water and recorded its temperature every 2 minutes. Study the graph. Describe how the temperature of the water changed during the 12 minutes.",
        fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 28], ["2", 46], ["4", 64], ["6", 82], ["8", 100], ["10", 100], ["12", 100]] },
        marks: 2,
        think: [
          "Step 1: Read the axes: time (min) and temperature of water (°C).",
          "Step 2: From 0 to 8 minutes the line rises steadily from 28 °C to 100 °C.",
          "Step 3: From 8 to 12 minutes the line is flat at 100 °C: the water is boiling and the temperature stays the same.",
          "Step 4: Two marks = two parts. Describe both, with the time where the pattern changes."
        ],
        answer: "As the time of heating increased, the temperature of the water increased steadily from 28 °C to 100 °C in the first 8 minutes. After 8 minutes, the temperature stayed the same at 100 °C."
      },
      tip: "A flat part of the graph is worth a mark of its own; never describe only the rising part.",
      try: {
        q: "Study the graph of the height of a plant. Which is the best description of the results?",
        fig: { type: "line", xl: "Week", yl: "Height of plant (cm)", pts: [["0", 2], ["1", 5], ["2", 9], ["3", 14], ["4", 17], ["5", 17], ["6", 17]] },
        o: ["The plant grew taller every week, reaching 17 cm by week 6.", "The height increased from week 0 to week 4, then stayed at 17 cm until week 6.", "The plant grew by 17 cm every week from week 0 to week 6.", "The height of the plant increased until week 4, then decreased until week 6."],
        a: 1,
        why: "It names both variables, the direction and the change at week 4. ‘Grew taller every week’ misses the flat part, 17 cm is the final height, not weekly growth, and the height never decreased."
      }
    },
    {
      h: "CER: putting the data into your answer",
      concept: "When a question says ‘Explain using the results’ or ‘Use the data’, the marker is looking for three things: a clear claim, evidence quoted from the graph or table (numbers with units, or set-up letters), and reasoning with the science keyword. Answers that only give the claim, or only the science, lose marks.",
      example: {
        q: "Ling wrapped four identical cans, each with 200 ml of water at 80 °C, in different materials and measured the temperature of the water after 20 minutes. Study the graph. Which material is the best heat insulator? Explain using the results.",
        fig: { type: "bar", xl: "Material", yl: "Temperature after 20 min (°C)", bars: [["Cotton", 52], ["Foil", 44], ["Felt", 63], ["Paper", 49]] },
        marks: 2,
        think: [
          "Step 1 (Claim): The best insulator lets the least heat escape, so its water stays hottest: felt.",
          "Step 2 (Evidence): Quote it. Felt: 63 °C, the highest; foil only 44 °C.",
          "Step 3 (Reasoning): Felt is the poorest conductor of heat, so the water lost heat to the surroundings most slowly."
        ],
        answer: "Felt. The water wrapped in felt was still at 63 °C after 20 minutes, the highest of the four (foil was only 44 °C). Felt is the poorest conductor of heat, so the least heat was lost from the hot water to the cooler surroundings."
      },
      tip: "Say ‘loses heat to the surroundings’, never ‘keeps the heat in’ or ‘traps coldness’.",
      try: {
        q: "Using the same graph of the four materials, which answer is the best explanation of why foil is the poorest heat insulator?",
        fig: { type: "bar", xl: "Material", yl: "Temperature after 20 min (°C)", bars: [["Cotton", 52], ["Foil", 44], ["Felt", 63], ["Paper", 49]] },
        o: ["Foil is shiny and thin, so it is the worst of the four materials at keeping the water in the can hot.", "Foil is a metal and metals are good, so foil did not keep the water as hot as the other three materials.", "Water in foil was coolest, at 44 °C. Foil is a good conductor of heat, so the water lost heat to the surroundings fastest.", "Foil lets the coldness from the surroundings into the can, so the water in foil became cold the fastest."],
        a: 2,
        why: "It gives the claim, quotes the evidence (44 °C, the lowest) and the reasoning (good conductor of heat, heat lost to the surroundings fastest). The others have no data, vague science, or the misconception that coldness moves."
      }
    },
    {
      h: "Unexpected results and improving the experiment",
      concept: "First spot the result that breaks the pattern. Then give a SPECIFIC possible cause (a measuring mistake, or one variable that may not have been kept the same) and a specific fix (repeat that reading and leave the odd value out of the average). For improvements, name the change and say what it improves: fairness, reliability or accuracy.",
      example: {
        q: "Aisyah counted the bubbles given off by a water plant in 5 minutes with a lamp at different distances. Study the graph. (a) Which result does not follow the pattern? (b) Suggest one possible reason for it. (c) What should she do about it?",
        fig: { type: "line", xl: "Distance of lamp (cm)", yl: "Bubbles in 5 min", pts: [["10", 48], ["20", 36], ["30", 40], ["40", 12], ["50", 6]] },
        marks: 3,
        think: [
          "Step 1: The pattern: as the distance increases, the number of bubbles decreases.",
          "Step 2: At 30 cm there are 40 bubbles, more than at 20 cm. That breaks the pattern; about 24 would be expected.",
          "Step 3: A possible cause: a variable not kept the same (e.g. extra sunlight from a window reached the plant) or a counting mistake.",
          "Step 4: Fix: repeat the reading at 30 cm and leave the odd result out."
        ],
        answer: "(a) The result at 30 cm (40 bubbles). (b) The plant may have received extra light from the window during that reading, or she may have counted wrongly. (c) She should repeat the experiment at 30 cm and leave out the odd result when she draws her conclusion."
      },
      tip: "‘Human error’ alone is too vague; say WHAT went wrong (counted wrongly, bigger ice cube, extra light).",
      try: {
        q: "Aisyah wants her results to be more reliable. Study her set-ups. Which change should she make?",
        fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Water plant", "Lamp 10 cm away"] }, { label: "B", icon: "beaker", lines: ["Water plant", "Lamp 30 cm away"] }, { label: "C", icon: "beaker", lines: ["Water plant", "Lamp 50 cm away"] } ] },
        o: ["Repeat the count three times at each distance and find the average.", "Use a different type of water plant at each distance.", "Count for 1 minute at 10 cm but for 5 minutes at 50 cm.", "Move the lamp closer during each count."],
        a: 0,
        why: "Repeating and averaging reduces the effect of one odd count, so the results are more reliable. The other changes bring in a second difference between the readings, which makes the test unfair."
      }
    },
    {
      h: "State, describe or explain?",
      concept: "The command word decides what earns the mark. ‘State’ or ‘Name’: one short, precise fact. ‘Describe’: what happened or the pattern, with data if given, but no reason needed. ‘Explain’: the reason, with the science keyword. Giving a description to an ‘explain’ question is the most common way strong pupils lose marks.",
      example: {
        q: "Two identical ice cubes were put in a metal cup and a plastic cup in the same room. Study the set-ups. (a) State which ice cube melted first. (b) Describe what was seen in cup B after 10 minutes. (c) Explain why the ice in A melted first.",
        fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Metal cup", "1 ice cube", "Melted in 12 min"] }, { label: "B", icon: "beaker", lines: ["Plastic cup", "1 ice cube", "Melted in 25 min"] } ] },
        marks: 3,
        think: [
          "Step 1 (State): One fact only: the ice cube in cup A.",
          "Step 2 (Describe): What was seen: after 10 minutes the ice cube in B was still partly solid, with some water around it.",
          "Step 3 (Explain): The reason: metal is a good conductor of heat, so the ice in A gained heat from the warmer surroundings faster."
        ],
        answer: "(a) The ice cube in cup A. (b) The ice cube in cup B was still partly solid, with a little water at the bottom of the cup. (c) Metal is a good conductor of heat, so heat from the warmer surroundings was conducted through cup A to the ice faster than through the plastic cup, and the ice in A gained heat and melted faster."
      },
      tip: "Underline the command word before you write. ‘Explain’ answers almost always contain ‘because’ or ‘so’.",
      try: {
        q: "A question asks: ‘Explain why the bulb in the circuit did not light up.’ A plastic ruler was placed across gap X, as shown. Which answer would score full marks?",
        fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "plastic ruler" } ] },
        o: ["The bulb in the circuit did not light up when the plastic ruler was put across gap X.", "The ruler across gap X is made of plastic, not metal, like the wires.", "Because of the plastic ruler across gap X, the bulb could not light up at all.", "Plastic is an electrical insulator, so there was no closed circuit and no current flowed."],
        a: 3,
        why: "Only this answer gives the reason with the keywords (electrical insulator, no closed circuit, current cannot flow). The first repeats the observation, the second states a fact with no link, and the third is too vague."
      }
    }
  ],
  mcq: [
    { q: "Study the set-ups. Jun Wei gave three identical balsam seedlings different volumes of water each day and measured their heights after 2 weeks. What is the variable changed?", fig: { type: "setups", items: [ { label: "A", icon: "pot", lines: ["50 ml water daily", "Near the window"] }, { label: "B", icon: "pot", lines: ["100 ml water daily", "Near the window"] }, { label: "C", icon: "pot", lines: ["150 ml water daily", "Near the window"] } ] }, o: ["The height of the seedlings after 2 weeks", "The volume of water given each day", "The type of seedling", "The amount of sunlight"], a: 1, why: "The only thing Jun Wei changes on purpose is the volume of water. The height is the variable measured; the type of seedling and the sunlight are kept the same.", lvl: 1 },
    { q: "Study the graph. Ravi heated some water and recorded its temperature. What was the temperature of the water at 6 minutes?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 30], ["2", 42], ["4", 54], ["6", 66], ["8", 78], ["10", 90]] }, o: ["54 °C", "60 °C", "78 °C", "66 °C"], a: 3, why: "Read up from 6 minutes to the line, then across: 66 °C. 54 °C is at 4 minutes and 78 °C at 8 minutes.", lvl: 1 },
    { q: "Sarah wrapped four identical cans of water at 80 °C in different materials and recorded the temperature after 20 minutes. Study the graph. Which material is the best heat insulator?", fig: { type: "bar", xl: "Material", yl: "Temperature after 20 min (°C)", bars: [["Cotton", 52], ["Foil", 45], ["Felt", 64], ["Paper", 58]] }, o: ["Felt", "Foil", "Cotton", "Paper"], a: 0, why: "The best heat insulator lets the least heat be lost, so its water stays the hottest: felt at 64 °C. Foil, with the lowest temperature, is the poorest insulator.", lvl: 1 },
    { q: "Which of the following makes the results of an experiment more reliable?", o: ["Changing two variables at the same time", "Using a different amount of water in each set-up", "Repeating the experiment and finding the average", "Writing the results in a table"], a: 2, why: "Repeating and averaging reduces the effect of one odd result. Changing two variables or different amounts of water makes the test unfair, and a table only organises the results.", lvl: 1 },
    { q: "Ahmad uses the circuit shown to find out how the number of batteries affects the brightness of the bulb. Which is the most accurate way to measure the brightness?", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "switch", label: "S", open: false } ] }, o: ["Look at the bulb and describe it as dim or bright", "Touch the bulb to feel how hot it is", "Place a thermometer next to the bulb", "Use a light sensor connected to a data logger"], a: 3, why: "A light sensor gives a number for the brightness, which is more accurate than judging with our eyes. Touching the bulb or using a thermometer measures heat, not brightness.", lvl: 1 },
    { q: "Study the food web. Which organism is a producer?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["frog", "snake"], ["rabbit", "snake"]] }, o: ["snake", "frog", "grass", "rabbit"], a: 2, why: "A producer makes its own food. In a food web, it is the organism with arrows only going out of it: grass. The rest are consumers.", lvl: 1 },
    { q: "Kumar wants to find out whether a fertiliser affects the growth of a plant. Study the set-ups. What is the purpose of set-up B?", fig: { type: "setups", items: [ { label: "A", icon: "pot", lines: ["Balsam plant", "Soil + fertiliser", "Near the window"] }, { label: "B", icon: "pot", lines: ["Balsam plant", "Soil, no fertiliser", "Near the window"] } ] }, o: ["For comparison, to show any difference in growth is due to the fertiliser", "To make the results more reliable by repeating the experiment", "To make sure the plant gets enough water and sunlight to grow", "To test a second variable at the same time as the fertiliser"], a: 0, why: "B is the control: identical except that it has no fertiliser, so it is used for comparison. Repeating (not a control) makes results reliable, and a fair test tests only one variable.", lvl: 1 },
    { q: "Which command word in a question tells you that you must give a reason in your answer?", o: ["Explain", "State", "Name", "Describe"], a: 0, why: "‘Explain’ needs the reason, the ‘because’. ‘State’ and ‘Name’ need a short fact, and ‘Describe’ needs what happened or the pattern.", lvl: 1 },

    { q: "Study the set-ups. Which two set-ups should Mei compare to find out whether water is needed for seeds to germinate?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["Moist cotton wool", "In the light", "25 °C"] }, { label: "B", icon: "dish", lines: ["Dry cotton wool", "In the light", "25 °C"] }, { label: "C", icon: "dish", lines: ["Moist cotton wool", "In the dark", "25 °C"] }, { label: "D", icon: "dish", lines: ["Dry cotton wool", "In the dark", "10 °C"] } ] }, o: ["A and B", "A and C", "B and D", "C and D"], a: 0, why: "A and B differ only in whether the cotton wool is moist. A and C differ in light; B and D differ in light and temperature; C and D differ in water and temperature.", lvl: 2 },
    { q: "Nadia hung wet cloths in front of a fan set at different speeds. Study the graph. Which statement best describes the relationship?", fig: { type: "line", xl: "Fan speed setting", yl: "Time for cloth to dry (min)", pts: [["1", 80], ["2", 64], ["3", 50], ["4", 38]] }, o: ["The cloth dried in 38 minutes.", "As the time taken for the cloth to dry increases, the fan becomes faster.", "The speed of the fan does not affect the time taken for the cloth to dry.", "As the fan speed increases, the time taken for the cloth to dry decreases."], a: 3, why: "A relationship names both variables with the direction of change, the variable changed first. The first option gives one reading, and the second has the variables the wrong way round.", lvl: 2 },
    { q: "Study the graph of the length of a spring with different masses hung on it. If the spring is not overstretched, predict its length when 80 g is hung on it.", fig: { type: "line", xl: "Mass hung (g)", yl: "Length of spring (cm)", pts: [["0", 8], ["20", 10], ["40", 12], ["60", 14]] }, o: ["16 cm", "15 cm", "18 cm", "20 cm"], a: 0, why: "The spring lengthens by 2 cm for every 20 g, so 80 g gives 14 + 2 = 16 cm. 18 cm would need 100 g.", lvl: 2 },
    { q: "Study the Venn diagram. Which statement is supported by the diagram?", fig: { type: "venn", a: "Conducts electricity", b: "Attracted by magnet", onlyA: ["copper", "aluminium"], both: ["iron", "steel"], onlyB: [], neither: ["plastic", "glass"] }, o: ["All the materials that conduct electricity are attracted by a magnet.", "Glass conducts electricity but is not attracted by a magnet.", "All the materials in the diagram that are attracted by a magnet conduct electricity.", "Copper is attracted by a magnet."], a: 2, why: "The ‘attracted by magnet’ circle holds only iron and steel, and both are also in the ‘conducts electricity’ circle. Copper and aluminium conduct but are not attracted, and glass is outside both circles.", lvl: 2 },
    { q: "Study the classification key. Which animal could be B?", fig: { type: "flow", root: "Animals", node: { q: "Has feathers?", yes: "A", no: { q: "Has 6 legs?", yes: "B", no: { q: "Lives in water?", yes: "C", no: "D" } } } }, o: ["sparrow", "guppy", "ant", "cat"], a: 2, why: "B has no feathers and 6 legs: an insect such as an ant. A sparrow would be A, a guppy C and a cat D.", lvl: 2 },
    { q: "Hui Ling tested which cup kept water hot longest by touching the water with her finger every 10 minutes. Which change would best improve the accuracy of her results?", o: ["Touch the water for a longer time each round", "Ask a friend to touch the water as well", "Use more hot water in each of the cups", "Measure the water temperature with a thermometer"], a: 3, why: "A thermometer or temperature sensor gives an actual reading instead of a feeling, so the measurement is more accurate. The other changes still rely on touch or change a variable.", lvl: 2 },
    { q: "A toy car was released from the same point on a ramp onto different surfaces. Study the graph of the distance it travelled. Which conclusion is supported by the results?", fig: { type: "bar", xl: "Surface", yl: "Distance travelled (cm)", bars: [["Glass", 120], ["Wood", 90], ["Carpet", 40], ["Sandpaper", 25]] }, o: ["There was the most friction between the car and the glass.", "There was the most friction between the car and the sandpaper.", "The car travelled 25 cm further on carpet than on sandpaper.", "The type of surface did not affect the distance travelled."], a: 1, why: "Friction opposes motion, so the surface where the car stopped soonest (sandpaper, 25 cm) had the most friction. On carpet it went 40 − 25 = 15 cm further, not 25 cm.", lvl: 2 },
    { q: "In the same toy-car experiment on different surfaces, which variable must be kept the same for a fair test?", fig: { type: "bar", xl: "Surface", yl: "Distance travelled (cm)", bars: [["Glass", 120], ["Wood", 90], ["Carpet", 40], ["Sandpaper", 25]] }, o: ["The type of surface", "The distance travelled", "The height of the ramp", "The friction on each surface"], a: 2, why: "The height of the ramp could affect the distance, so it must be the same. The surface is the variable changed, the distance is the variable measured and friction depends on the surface.", lvl: 2 },
    { q: "Two identical ice cubes were placed in cups A and B in the same room. After 10 minutes, there was more water in cup A. Study the set-ups. Which statement is an inference?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Metal cup", "1 ice cube"] }, { label: "B", icon: "beaker", lines: ["Plastic cup", "1 ice cube"] } ] }, o: ["Cup A had more water in it than cup B after 10 minutes.", "The ice cube in cup B was still partly solid after 10 minutes had passed.", "Both cups started with identical ice cubes in the same room.", "Metal conducts heat better than plastic, so the ice in A gained heat faster."], a: 3, why: "An inference explains an observation using science ideas. The other three are things that can be seen or were set up, so they are observations or facts.", lvl: 2 },
    { q: "Study the set-ups. Why did Yan Ting put 10 seeds in each dish instead of 1?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["10 green bean seeds", "Moist cotton wool", "25 °C"] }, { label: "B", icon: "dish", lines: ["10 green bean seeds", "Moist cotton wool", "10 °C"] } ] }, o: ["So that the results are more reliable, in case one seed does not germinate", "So that the test is fair, as each dish is treated the same", "So that the seeds germinate faster by keeping one another warm", "So that the seeds absorb more water from the cotton wool"], a: 0, why: "Using more seeds means one faulty seed affects the result less, so the results are more reliable. Fairness comes from keeping the other variables the same.", lvl: 2 },
    { q: "Study the graph of the height of a plant over 5 weeks. Between which weeks did the plant grow the fastest?", fig: { type: "line", xl: "Week", yl: "Height of plant (cm)", pts: [["0", 2], ["1", 3], ["2", 5], ["3", 10], ["4", 12], ["5", 13]] }, o: ["Week 0 to week 1", "Week 1 to week 2", "Week 4 to week 5", "Week 2 to week 3"], a: 3, why: "From week 2 to week 3 the plant grew 5 cm, the steepest part of the line. The other weeks show growth of 1–2 cm.", lvl: 2 },
    { q: "Sam places different objects, one at a time, across gap X in the circuit shown and observes the bulb. What is the aim of his experiment?", fig: { type: "circuit", cells: 1, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "object" } ] }, o: ["To find out which objects are magnetic", "To find out which objects are electrical conductors", "To find out how the number of batteries affects brightness", "To find out which bulb is the brightest"], a: 1, why: "The bulb lights up only when the object across X is an electrical conductor that closes the circuit. Nothing about magnets, batteries or different bulbs is changed.", lvl: 2 },
    { q: "Study the set-ups. Each beaker holds the same type of water plant, and Priya counts the bubbles it gives off in 5 minutes. Which hypothesis is she testing?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Water plant", "Lamp 10 cm away"] }, { label: "B", icon: "beaker", lines: ["Water plant", "Lamp 30 cm away"] }, { label: "C", icon: "beaker", lines: ["Water plant", "Lamp 50 cm away"] } ] }, o: ["The more water in the beaker, the more bubbles are given off.", "The bigger the beaker, the faster the plant grows.", "The plant needs carbon dioxide to make food.", "The nearer the lamp is to the plant, the more bubbles the plant gives off."], a: 3, why: "Only the distance of the lamp is changed, and the bubbles are counted, so the hypothesis must link these two variables.", lvl: 2 },
    { q: "Rina put 100 ml of water into containers with different-sized openings and left them in the same room for 3 hours. Study the set-ups. What is the variable measured?", fig: { type: "setups", items: [ { label: "A", icon: "dish", lines: ["100 ml water", "Wide opening"] }, { label: "B", icon: "beaker", lines: ["100 ml water", "Medium opening"] }, { label: "C", icon: "jar", lines: ["100 ml water", "Narrow opening"] } ] }, o: ["The size of the opening of the container", "The volume of water at the start", "The volume of water left after 3 hours", "The temperature of the room"], a: 2, why: "The variable measured is the result: the volume of water left. The size of the opening is changed; the starting volume and room temperature are kept the same.", lvl: 2 },

    { q: "Lina wants to find out whether a fertiliser makes a plant grow taller. Study her set-ups. Why can she NOT conclude that the fertiliser made plant A grow taller?", fig: { type: "setups", items: [ { label: "A", icon: "pot", lines: ["Balsam plant", "Fertiliser added", "Near the window"] }, { label: "B", icon: "pot", lines: ["Money plant", "No fertiliser", "Near the window"] } ] }, o: ["She did not use a measuring tape to measure height.", "Both set-ups were placed near the same window.", "The plant type and fertiliser were both different.", "Set-up B had no plant growing in it."], a: 2, why: "Two variables were changed, so any difference in height could be due to the type of plant OR the fertiliser. Both being near the window is correct, as the place is kept the same.", lvl: 3 },
    { q: "A beaker of crushed ice was left in a warm room and its temperature was recorded. Study the graph. Which statement best describes the results?", fig: { type: "line", xl: "Time (min)", yl: "Temperature (°C)", pts: [["0", 0], ["2", 0], ["4", 0], ["6", 4], ["8", 10], ["10", 16]] }, o: ["The temperature stayed at 0 °C for 4 minutes, then increased.", "The temperature increased steadily from the very start.", "The temperature decreased after the first 4 minutes.", "The temperature stayed at 0 °C for the whole time."], a: 0, why: "The line is flat at 0 °C from 0 to 4 minutes (the ice was melting) and then rises. A full description names both parts.", lvl: 3 },
    { q: "Study the food web. A disease kills most of the frogs. What will most likely happen to the number of grasshoppers at first?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "caterpillar"], ["grasshopper", "bird"], ["caterpillar", "bird"], ["grasshopper", "frog"], ["frog", "snake"], ["bird", "snake"]] }, o: ["It will increase, because fewer grasshoppers are eaten by frogs.", "It will decrease, because snakes will eat the grasshoppers.", "It will decrease, because there will be less grass.", "It will stay the same, because frogs do not eat grasshoppers."], a: 0, why: "Frogs eat grasshoppers, so with fewer frogs, fewer grasshoppers are eaten at first. Snakes do not eat grasshoppers in this web, and nothing has reduced the grass.", lvl: 3 },
    { q: "Aisyah counted the bubbles given off by a water plant in 5 minutes with a lamp at different distances. Study the graph. Which result does not follow the pattern, and what should she do?", fig: { type: "line", xl: "Distance of lamp (cm)", yl: "Bubbles in 5 min", pts: [["10", 40], ["20", 30], ["30", 34], ["40", 12], ["50", 6]] }, o: ["20 cm; she should ignore all the results", "30 cm; she should repeat the reading at 30 cm", "40 cm; she should use a brighter lamp", "50 cm; she should change the water plant"], a: 1, why: "The bubbles fall as the lamp moves away, except at 30 cm, where 34 is more than at 20 cm. She should repeat that reading, not throw away all results or change the set-up.", lvl: 3 },
    { q: "Ben grew balsam plants with different hours of light each day. Study the graph. He concluded: ‘All plants grow taller when they get more light.’ Why is his conclusion NOT valid?", fig: { type: "bar", xl: "Hours of light each day", yl: "Height after 3 weeks (cm)", bars: [["2 h", 6], ["4 h", 10], ["6 h", 15], ["8 h", 19]] }, o: ["The heights did not increase when the plants got more light.", "He should have shown the results in a line graph.", "Plants do not need any light at all to grow taller.", "He tested only balsam plants, so he cannot say this for all plants."], a: 3, why: "The data does show taller balsam plants with more light, but only one type of plant was tested, so the conclusion must be limited to balsam plants.", lvl: 3 },
    { q: "Joel wants to find out how the number of sheets of paper between a magnet and a pile of steel clips affects the number of clips the magnet attracts. Study the set-ups. Which two should he compare?", fig: { type: "setups", items: [ { label: "A", icon: "box", lines: ["Magnet X", "2 sheets of paper", "Small steel clips"] }, { label: "B", icon: "box", lines: ["Magnet X", "4 sheets of paper", "Large steel clips"] }, { label: "C", icon: "box", lines: ["Magnet Y", "4 sheets of paper", "Small steel clips"] }, { label: "D", icon: "box", lines: ["Magnet X", "4 sheets of paper", "Small steel clips"] } ] }, o: ["A and B", "A and D", "B and D", "C and D"], a: 1, why: "A and D differ only in the number of sheets of paper; the magnet and the clips are the same. A and B also differ in the size of clips, B and D differ only in the clips, and C and D differ only in the magnet.", lvl: 3 },
    { q: "Study the circuit. All the bulbs and batteries are identical. Daniel says bulb A will be brighter than bulb B. Is he correct?", fig: { type: "circuit", cells: 2, branches: [ [ { k: "bulb", label: "A" } ], [ { k: "bulb", label: "B" }, { k: "bulb", label: "C" } ] ] }, o: ["Yes, because A is alone in its branch, so more current flows through it than B.", "No, because all bulbs in the same circuit are always equally bright.", "No, because B is nearer to the batteries, so it gets current first.", "Yes, because bulb A is labelled first, so it gets current first."], a: 0, why: "A has its own branch, while B shares its branch with C in series, so less current flows through B and it is dimmer. The position in the diagram or the label does not matter.", lvl: 3 },
    { q: "Hana hung different loads on springs P and Q and measured how much each spring extended. Study the table. Which statement is correct?", tbl: [["Load (g)", "Extension of spring P (cm)", "Extension of spring Q (cm)"], ["0", "0", "0"], ["50", "2", "4"], ["100", "4", "8"], ["150", "6", "12"]], o: ["Spring P extends more than spring Q for the same load.", "Spring Q extends 12 cm with a load of 100 g.", "For the same load, spring Q extends twice as much as spring P.", "The extension of each spring does not depend on the load."], a: 2, why: "At every load Q’s extension is double P’s (4 and 2, 8 and 4, 12 and 6). Q extends 8 cm, not 12 cm, at 100 g, and both springs extend more as the load increases.", lvl: 3 },
    { q: "Wei Ming placed 20 seeds in each of four dishes at different temperatures. Study the graph. Which is the best conclusion?", fig: { type: "bar", xl: "Temperature (°C)", yl: "Seeds germinated (%)", bars: [["10", 20], ["20", 60], ["30", 90], ["40", 40]] }, o: ["Seeds germinate best at exactly 30 °C.", "Seeds cannot germinate at 40 °C.", "The higher the temperature, the more seeds germinate.", "Of the temperatures tested, the most seeds germinated at 30 °C."], a: 3, why: "Only four temperatures were tested, so the best temperature could lie between 20 °C and 40 °C. 40% did germinate at 40 °C, and the percentage fell after 30 °C.", lvl: 3 },
    { q: "Two identical ice cubes were wrapped in felt and in foil. The ice in felt took 50 minutes to melt; the ice in foil took 20 minutes. Which answer is the best explanation?", fig: { type: "bar", xl: "Wrapping", yl: "Time for ice to melt (min)", bars: [["Felt", 50], ["Foil", 20]] }, o: ["Felt keeps the coldness in, so the ice in felt melted more slowly, taking 50 minutes instead of 20.", "The ice in felt took 30 minutes longer to melt. Felt is a poor conductor of heat, so the ice gained heat more slowly.", "Felt is thick and soft, so the ice in felt melted faster than the ice that was wrapped in foil.", "Foil is shiny, so it melted the ice in only 20 minutes, which is 30 minutes faster than felt."], a: 1, why: "It gives the claim, evidence with numbers and reasoning with the correct concept (poor conductor, ice gains heat from the surroundings). ‘Keeps coldness in’ is a misconception, and the others give no correct science.", lvl: 3 },
    { q: "Study the set-ups. As the lamp is moved nearer, the water in the beaker also becomes warmer. Which change would let Priya be sure that differences in the number of bubbles are due to the light only?", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Water plant", "Lamp 10 cm away"] }, { label: "B", icon: "beaker", lines: ["Water plant", "Lamp 30 cm away"] }, { label: "C", icon: "beaker", lines: ["Water plant", "Lamp 50 cm away"] } ] }, o: ["Use a bigger beaker with more water for set-up A than for the others.", "Count the bubbles for 1 minute instead of 5 minutes in every set-up.", "Use a thermometer and keep the water at the same temperature in every set-up.", "Use a brighter lamp in set-up C so there are more bubbles to count."], a: 2, why: "Temperature changes along with the distance, so it must be checked and kept the same. The other changes either add a new difference between set-ups or make counting less accurate.", lvl: 3 },
    { q: "Study the set-ups. Tom measured how much water each shoot took in over 2 days. Why did he add a layer of oil on the water in both set-ups?", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Shoot with leaves", "Layer of oil", "200 ml water"] }, { label: "B", icon: "jar", lines: ["Shoot, no leaves", "Layer of oil", "200 ml water"] } ] }, o: ["To give the shoots food so that they take in more water", "To keep the water warm so that the shoots take in more", "To make the results more reliable, just like repeating the experiment", "To stop water evaporating, so any water lost was taken in by the shoot"], a: 3, why: "Oil stops evaporation from the water surface, so the drop in water level is due only to the shoot. It does not feed the plant or make results more reliable.", lvl: 3 },

    { q: "Study the graph. Faizal recorded the total volume of water lost by a leafy shoot. Note the times on the x-axis. During which period was the RATE of water loss the greatest?", fig: { type: "line", xl: "Time (min)", yl: "Total water lost (ml)", pts: [["0", 0], ["2", 10], ["4", 16], ["8", 28], ["16", 44]] }, o: ["0 to 2 min", "2 to 4 min", "4 to 8 min", "8 to 16 min"], a: 0, why: "Work out ml per minute: 10 ÷ 2 = 5, 6 ÷ 2 = 3, 12 ÷ 4 = 3, 16 ÷ 8 = 2. The rate was greatest from 0 to 2 min. The line only looks steepest from 8 to 16 min because the time steps are not equal.", lvl: 4 },
    { q: "Study the table. Which of these conclusions can be made from fair comparisons?\nA: Water is needed for the seeds to germinate.\nB: Fewer seeds germinate at 5 °C than at 25 °C when there is water.\nC: Comparing Q and R shows that temperature affects germination.", tbl: [["Set-up", "Cotton wool", "Temperature (°C)", "Seeds germinated (%)"], ["P", "Moist", "25", "90"], ["Q", "Dry", "25", "0"], ["R", "Moist", "5", "10"], ["S", "Dry", "5", "0"]], o: ["A only", "A and B only", "B and C only", "A, B and C"], a: 1, why: "A is supported by P and Q (and R and S), which differ only in water. B is supported by P and R, which differ only in temperature. Q and R differ in both water and temperature, so C is not a fair comparison.", lvl: 4 },
    { q: "Study the food web. Which statement must be true?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["Q", "S"], ["R", "S"], ["S", "T"], ["R", "T"]] }, o: ["S is a prey of R in this food web.", "T gets energy from P only through S.", "If all of R die out, T still has a food source.", "Q and R are both predators of S in the web."], a: 2, why: "T eats S and R. If R dies out, T can still eat S, which still eats Q. The arrows show S eats R (S is not R’s prey), T also gets energy from P through R, and Q and R are prey of S.", lvl: 4 },
    { q: "Study the circuit. Switch S1 is closed and switch S2 is open. Which statement is correct?", fig: { type: "circuit", cells: 2, main: [ { k: "switch", label: "S1", open: false } ], branches: [ [ { k: "bulb", label: "A" }, { k: "switch", label: "S2", open: true } ], [ { k: "bulb", label: "B" } ], [ { k: "bulb", label: "C" }, { k: "bulb", label: "D" } ] ] }, o: ["Only B lights up, because C and D must share the current.", "B, C and D light up, but A does not.", "All four bulbs light up, because S1 is closed.", "No bulbs light up, because S2 is open."], a: 1, why: "S1 in the main circuit is closed, so every branch with no break forms a closed circuit: B, C and D light up. S2 breaks only A’s branch. C and D share a branch, so they are dimmer, but they still light.", lvl: 4 },
    { q: "Study the graph. Jia En counted the bubbles given off by a water plant at different water temperatures. She concluded: ‘The higher the temperature, the more bubbles the plant gives off.’ Which is the best evaluation?", fig: { type: "bar", xl: "Water temperature (°C)", yl: "Bubbles in 5 min", bars: [["15", 12], ["25", 30], ["35", 45], ["45", 20]] }, o: ["Correct, because the number of bubbles increased each time the temperature was increased.", "Not fully correct: the bubbles increased from 15 °C to 35 °C but fell at 45 °C, so it holds only up to 35 °C.", "Incorrect, because temperature does not affect how many bubbles a plant gives off.", "Incorrect, because the number of bubbles decreased at every temperature that was tested."], a: 1, why: "The data supports the pattern only from 15 °C to 35 °C; at 45 °C the bubbles fell to 20. A good evaluation says which part of the conclusion the data supports and which part it does not.", lvl: 4 },
    { q: "Kai measured the volume of water lost in 2 hours from dishes with different exposed surface areas. Study the table. Assume the pattern continues and each dish loses water at a steady rate. A dish with an exposed surface area of 50 cm² starts with 100 ml of water. How much water will be LEFT after 4 hours?", tbl: [["Exposed surface area (cm²)", "20", "40", "60"], ["Volume of water lost in 2 hours (ml)", "6", "12", "18"]], o: ["85 ml", "70 ml", "30 ml", "15 ml"], a: 1, why: "The loss is 3 ml for every 10 cm², so 50 cm² loses 15 ml in 2 hours and 30 ml in 4 hours. 100 − 30 = 70 ml left. 85 ml uses 2 hours only, and 30 ml is the water lost, not left.", lvl: 4 }
  ],
  tf: [
    { s: "Repeating an experiment makes it a fairer test.", a: false, why: "Repeating makes results more reliable; keeping the other variables the same makes a test fair." },
    { s: "A control set-up is identical to the experimental set-up except for the variable being tested.", a: true, why: "That is what lets it be used for comparison." },
    { s: "‘The water decreased’ is a complete description of a relationship.", a: false, why: "A relationship must name both variables and the direction, e.g. ‘As the temperature increased, the volume of water decreased.’" },
    { s: "The variable measured is the result that you measure, count or observe.", a: true, why: "For example, the number of bubbles in 5 minutes or the temperature after 20 minutes." },
    { s: "If two variables are changed at once, you cannot tell which one caused the difference in the results.", a: true, why: "That is why a fair test changes only one variable." },
    { s: "If temperatures from 20 °C to 60 °C were tested, you can conclude what happens at 90 °C.", a: false, why: "A conclusion must stay within the range tested." },
    { s: "A result that does not follow the pattern should be included when calculating the average.", a: false, why: "An anomaly should be repeated and left out of the average." },
    { s: "An ‘explain’ question needs a reason, not just what was observed.", a: true, why: "Explain = give the ‘because’ with the science keyword." },
    { s: "On a line graph with equal steps, a steeper line shows a slower change.", a: false, why: "A steeper line shows a faster change." },
    { s: "Using 20 seeds instead of 2 in each dish makes the results more reliable.", a: true, why: "One faulty seed then affects the result much less." },
    { s: "A hypothesis is only useful if the experiment proves it correct.", a: false, why: "A hypothesis is a testable prediction; results may support it or show it is wrong." },
    { s: "An inference is exactly what you see during the experiment.", a: false, why: "What you see is an observation; an inference is a conclusion drawn from it." },
    { s: "In a food web, each arrow points from the food to the organism that eats it.", a: true, why: "The arrow shows the direction in which energy flows." },
    { s: "A temperature sensor with a data logger measures temperature more accurately than touching the water.", a: true, why: "It gives an actual reading instead of a feeling." },
    { s: "A ‘describe’ question asks you to give the reason for the results.", a: false, why: "Describe = say what happened or the pattern; explain = give the reason." },
    { s: "In CER, the evidence should quote numbers or set-up letters from the data.", a: true, why: "Evidence is the data that supports the claim." },
    { s: "A flat part on a graph of plant height against time shows the plant growing fastest.", a: false, why: "A flat line shows no change: the plant stopped growing." },
    { s: "Results from balsam plants alone show that all plants behave in the same way.", a: false, why: "The conclusion is valid only for the type of plant tested." },
    { s: "When a question asks ‘Which set-up...? Explain using the results’, you should name the set-up and quote data to support it.", a: true, why: "Naming it earns the claim; quoting the data earns the evidence mark." },
    { s: "‘The plant grows better’ is a precise enough answer at PSLE.", a: false, why: "Say exactly what changed and how, e.g. ‘the plant grew taller’ or ‘the plant made more food’." }
  ],
  sort: [
    { title: "Does each action make an experiment FAIRER, its results MORE RELIABLE, or its measurements MORE ACCURATE?", groups: ["Fairer", "More reliable", "More accurate"], items: [["Use the same volume of water in every set-up", 0], ["Repeat the experiment three times and find the average", 1], ["Use a measuring cylinder instead of a cup", 2], ["Use the same type of plant in every set-up", 0], ["Use 20 seeds instead of 2 in each dish", 1], ["Read the measuring cylinder at eye level", 2], ["Place all the set-ups in the same room", 0], ["Use a light sensor instead of our eyes", 2], ["Repeat the reading that does not fit the pattern", 1]] },
    { title: "Which kind of question does each answer suit best?", groups: ["State", "Describe", "Explain"], items: [["Set-up B.", 0], ["As the temperature increased, the time taken for the ice to melt decreased.", 1], ["Metal is a good conductor of heat, so it conducted heat away from the hand quickly.", 2], ["The volume of water.", 0], ["The brightness increased from 1 to 3 batteries, then stayed the same.", 1], ["Without light the plant could not make food, so it died.", 2], ["Frog.", 0], ["The water level in beaker A dropped by 20 ml over 3 days.", 1]] },
    { title: "Sort each sentence into Claim, Evidence or Reasoning.", groups: ["Claim", "Evidence", "Reasoning"], items: [["Cup A is the better heat insulator.", 0], ["The water in cup A was 62 °C after 20 minutes, but only 45 °C in cup B.", 1], ["Cup A is a poorer conductor of heat, so less heat was lost to the surroundings.", 2], ["Magnet X is stronger than magnet Y.", 0], ["Magnet X attracted 15 clips, while magnet Y attracted 6.", 1], ["A stronger magnet has a stronger magnetic force, so it attracts more steel clips.", 2], ["Water is needed for the seeds to germinate.", 0], ["9 out of 10 seeds germinated on moist cotton wool, but none on dry cotton wool.", 1], ["The two dishes differed only in water, so the difference in germination must be due to water.", 2]] }
  ],
  oe: [
    { q: "Priya put the same type of water plant in three beakers and placed a lamp at different distances. She counted the bubbles given off by each plant in 5 minutes. Study the set-ups.\n(a) What is the aim of her experiment? [1]\n(b) State one variable she must keep the same. [1]\n(c) Predict whether the plant in C gives off more or fewer bubbles than the plant in A, and explain your prediction. [2]", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Water plant", "Lamp 10 cm away"] }, { label: "B", icon: "beaker", lines: ["Water plant", "Lamp 30 cm away"] }, { label: "C", icon: "beaker", lines: ["Water plant", "Lamp 50 cm away"] } ] }, marks: 4, kw: [["distance"], ["size of", "type of", "amount of water", "volume of water", "temperature", "same lamp", "brightness of", "number of leaves", "duration", "time"], ["fewer", "less bubbles", "less oxygen"], ["less light", "dimmer", "less bright", "further from the lamp", "further away"]], model: "(a) To find out how the distance of the lamp from the water plant affects the number of bubbles given off in 5 minutes. (b) The size of the water plant (or the volume of water, or the temperature of the water). (c) Fewer bubbles. The plant in C is further from the lamp, so it receives less light and makes less food, giving off less oxygen." },
    { q: "Farah left a cup of hot water on a table and recorded its temperature every 5 minutes. Study the graph.\n(a) Describe how the temperature of the water changed over the 30 minutes. [1]\n(b) Predict the temperature of the water at 40 minutes. [1]\n(c) Explain your prediction in (b). [1]", fig: { type: "line", xl: "Time (min)", yl: "Temperature of water (°C)", pts: [["0", 80], ["5", 60], ["10", 46], ["15", 36], ["20", 30], ["25", 28], ["30", 28]] }, marks: 3, kw: [["decrease", "dropped", "fell", "went down"], ["28"], ["surroundings", "room temperature"]], model: "(a) The temperature of the water decreased quickly at first, then more slowly, and stayed the same at 28 °C from 25 to 30 minutes. (b) 28 °C. (c) The water had cooled to the temperature of the surroundings, so it no longer loses heat and its temperature stays the same." },
    { q: "Ethan released the same toy car from the same point on a ramp onto different surfaces and measured the distance it travelled. Study the graph.\n(a) On which surface was the friction between the car and the surface the greatest? [1]\n(b) Explain your answer to (a) using the results. [2]\n(c) Suggest one way to make his results more reliable. [1]", fig: { type: "bar", xl: "Surface", yl: "Distance travelled (cm)", bars: [["Glass", 120], ["Wood", 90], ["Carpet", 40], ["Sandpaper", 25]] }, marks: 4, kw: [["sandpaper"], ["25", "shortest"], ["oppos", "slow"], ["repeat"]], model: "(a) Sandpaper. (b) The car travelled the shortest distance on sandpaper, only 25 cm. Friction opposes motion, so the greater the friction, the more the car is slowed down and the sooner it stops. (c) Repeat the experiment three times for each surface and find the average distance." },
    { q: "Tom placed a shoot with leaves in jar A and a shoot with its leaves removed in jar B, and measured the water left after 2 days. Study the set-ups.\n(a) Why did he add a layer of oil to the water in both jars? [1]\n(b) What is the purpose of set-up B? [1]", fig: { type: "setups", items: [ { label: "A", icon: "jar", lines: ["Shoot with leaves", "Layer of oil", "200 ml water"] }, { label: "B", icon: "jar", lines: ["Shoot, no leaves", "Layer of oil", "200 ml water"] } ] }, marks: 2, kw: [["evaporat"], ["comparison", "compare"]], model: "(a) To prevent water from evaporating from the water surface, so that any water lost was taken in by the shoot. (b) B is the control set-up. It is used for comparison, to show that the greater loss of water in A is due to the leaves." },
    { q: "Ravi used the circuit shown, with 1, 2 and then 3 batteries, to find out how the number of batteries affects the brightness of the bulb. A light sensor gave readings of 60, 120 and 180 units.\n(a) State the variable changed. [1]\n(b) Describe the relationship shown by his results. [1]\n(c) Why did Ravi use a light sensor instead of his eyes? [1]", fig: { type: "circuit", cells: 3, main: [ { k: "bulb", label: "A" }, { k: "switch", label: "S", open: false } ] }, marks: 3, kw: [["number of batteries"], ["increase", "brighter"], ["accurate"]], model: "(a) The number of batteries in the circuit. (b) As the number of batteries increased, the brightness of the bulb increased. (c) The light sensor measures the brightness more accurately, as a reading, than judging with our eyes." },
    { q: "Study the food web.\n(a) A disease kills most of the frogs. State how the number of grasshoppers will change at first, and explain why. [2]\n(b) Predict how the number of rabbits may change after the frogs die, and explain your prediction. [2]", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"]] }, marks: 4, kw: [["increase"], ["fewer grasshoppers are eaten", "eaten by fewer", "fewer frogs", "fewer predators"], ["decrease"], ["more rabbits", "eat more rabbit", "rabbits are eaten", "less grass", "less food"]], model: "(a) The number of grasshoppers will increase at first, because fewer frogs are left to eat them, so fewer grasshoppers are eaten. (b) The number of rabbits may decrease. The snakes have fewer frogs to feed on, so they will eat more rabbits.", x: 1 },
    { q: "Ahmad put ice cubes into water at different temperatures and timed how long they took to melt. Study the graph.\n(a) Which result does not follow the pattern? [1]\n(b) Suggest one possible reason for this result. [1]\n(c) What should Ahmad do about this result? [1]", fig: { type: "line", xl: "Water temperature (°C)", yl: "Time for ice to melt (min)", pts: [["20", 12], ["30", 9], ["40", 6], ["50", 8], ["60", 3]] }, marks: 3, kw: [["50"], ["bigger", "larger", "size", "mistake", "error", "wrong", "cooled", "colder"], ["repeat"]], model: "(a) The result at 50 °C (8 minutes); it should be about 4 or 5 minutes. (b) The ice cubes used at 50 °C may have been bigger, or the water may have cooled before the ice was added, or there was a mistake in timing. (c) He should repeat the experiment at 50 °C and leave out the odd result." },
    { q: "Wei Ming placed 20 seeds on moist cotton wool in each of four dishes at different temperatures. Study the graph. He concluded that 30 °C is the best temperature for these seeds to germinate.\n(a) Explain why he cannot be sure that 30 °C is the best temperature. [1]\n(b) Suggest how he could find the best temperature more precisely. [1]\n(c) Why did he use 20 seeds in each dish instead of 1? [1]", fig: { type: "bar", xl: "Temperature (°C)", yl: "Seeds germinated (%)", bars: [["10", 20], ["20", 60], ["30", 90], ["40", 40]] }, marks: 3, kw: [["between", "only tested", "in between"], ["25", "35", "more temperatures", "smaller"], ["reliable"]], model: "(a) He only tested four temperatures, 10 °C apart, so the best temperature could be between 20 °C and 40 °C, for example 35 °C. (b) Test more temperatures between 20 °C and 40 °C, such as 25 °C, 30 °C and 35 °C, in smaller steps. (c) So that the results are more reliable, as one seed might not germinate even under good conditions." },
    { q: "Siti wanted to find out which material is the better heat insulator. She wrapped four cans of hot water as shown and measured the temperature of the water after 20 minutes.\n(a) Which two set-ups can be compared fairly? [1]\n(b) Explain why set-up B cannot be compared fairly with set-up A. [1]\n(c) The water in A was 55 °C and in D was 40 °C after 20 minutes. Which material is the better heat insulator? Explain using the results. [2]", fig: { type: "setups", items: [ { label: "A", icon: "beaker", lines: ["Wrapped in cotton", "200 ml water", "Water at 80 °C"] }, { label: "B", icon: "beaker", lines: ["Wrapped in wool", "150 ml water", "Water at 80 °C"] }, { label: "C", icon: "beaker", lines: ["Wrapped in felt", "200 ml water", "Water at 60 °C"] }, { label: "D", icon: "beaker", lines: ["Wrapped in foil", "200 ml water", "Water at 80 °C"] } ] }, marks: 4, kw: [["a and d", "d and a"], ["volume", "150"], ["cotton"], ["poor conductor", "poorer conductor", "less heat", "lost heat more slowly", "slower"]], model: "(a) A and D. (b) Both the material and the volume of water (150 ml in B, 200 ml in A) are different, so we cannot tell which variable caused any difference. (c) Cotton. The water wrapped in cotton was 55 °C after 20 minutes, higher than 40 °C in foil. Cotton is a poorer conductor of heat, so less heat was lost from the water to the surroundings.", x: 1 },
    { q: "Study the graph of the height of a plant. Describe how the height of the plant changed from week 0 to week 6. [2]", fig: { type: "line", xl: "Week", yl: "Height of plant (cm)", pts: [["0", 2], ["1", 5], ["2", 9], ["3", 14], ["4", 17], ["5", 17], ["6", 17]] }, marks: 2, kw: [["increase", "grew", "taller"], ["stayed the same", "remained", "no change", "constant", "stopped"]], model: "The height of the plant increased from 2 cm to 17 cm from week 0 to week 4. From week 4 to week 6, the height stayed the same at 17 cm." },
    { q: "Study the Venn diagram.\n(a) A guppy lives in water, breathes with gills and gives birth to live young. In which region of the diagram should it be placed? [1]\n(b) Explain your answer to (a). [2]", fig: { type: "venn", a: "Breathes with lungs", b: "Lays eggs", onlyA: ["dog", "whale"], both: ["chicken", "crocodile"], onlyB: ["goldfish", "butterfly"], neither: [] }, marks: 3, kw: [["neither", "outside"], ["gills"], ["live young", "gives birth"]], model: "(a) Outside both circles (neither region). (b) The guppy breathes with gills, not lungs, and it gives birth to live young instead of laying eggs, so it belongs to neither group." },
    { q: "Study Ann’s classification key.\n(a) State one property that iron and copper both have. [1]\n(b) Aluminium conducts electricity and is not attracted by a magnet. Which material in the key is it grouped with? [1]\n(c) Explain your answer to (b). [1]", fig: { type: "flow", root: "Materials", node: { q: "Conducts electricity?", yes: { q: "Attracted to magnet?", yes: "iron", no: "copper" }, no: { q: "Allows light through?", yes: "glass", no: "wood" } } }, marks: 3, kw: [["conduct"], ["copper"], ["not attracted", "not magnetic", "non-magnetic"]], model: "(a) Both conduct electricity. (b) Copper. (c) Like copper, aluminium conducts electricity but is not attracted by a magnet, so it takes the same path in the key." },
    { q: "Nina hung two identical wet cloths in the same room, one in front of a fan and one without a fan, and recorded the time each took to dry. Study the set-ups.\n(a) Which cloth dried faster? [1]\n(b) Use the data to support your answer. [1]\n(c) Explain why this cloth dried faster. [1]", fig: { type: "setups", items: [ { label: "A", icon: "plate", lines: ["Wet cloth", "No fan", "Dried in 60 min"] }, { label: "B", icon: "plate", lines: ["Wet cloth", "In front of a fan", "Dried in 35 min"] } ] }, marks: 3, kw: [["cloth b", "set-up b"], ["35"], ["moving air", "wind", "carried the water vapour", "carries the water vapour", "evaporat"]], model: "(a) Cloth B. (b) Cloth B dried in 35 minutes, 25 minutes faster than cloth A, which took 60 minutes. (c) The moving air from the fan carried the water vapour away from the cloth, so the water in cloth B evaporated faster." },
    { q: "Siti placed different objects, one at a time, across gap X in the circuit shown. The bulb lit up with a steel clip, a copper wire and aluminium foil, but not with a plastic ruler.\n(a) Siti concluded: ‘All metals conduct electricity.’ Why is this conclusion not fully supported by her results? [1]\n(b) Explain why the bulb did not light up with the plastic ruler. [1]\n(c) Before testing, she touched the two clips together to check that the bulb lit up. Why was this important? [1]", fig: { type: "circuit", cells: 2, main: [ { k: "bulb", label: "A" }, { k: "gap", label: "X", text: "object" } ] }, marks: 3, kw: [["only", "three", "3", "few"], ["insulator"], ["working", "works", "faulty"]], model: "(a) She only tested three metals, so she cannot say that all metals conduct electricity. (b) Plastic is an electrical insulator, so there was no closed circuit and no electric current flowed through the bulb. (c) To check that the circuit and the bulb were working, so that a bulb that did not light up was due to the object and not a faulty bulb or battery.", x: 1 }
  ],
  doc: [
    { q: "Study the results. Describe the relationship between the temperature of the water and the time taken for a sugar cube to dissolve. [1] (Temperature: 20, 40, 60, 80 °C; time: 90, 60, 35, 15 s)", marks: 1, answers: ["The sugar dissolved faster.", "Temperature and time are related.", "As the temperature of the water increased, the time taken for the sugar cube to dissolve decreased."], best: 2, why: "Pupil 3 names both variables and the direction of change. Pupil 1 names only one variable, and Pupil 2 names both but never says whether the time goes up or down." },
    { q: "Two identical ice cubes were put in a metal cup and a plastic cup. The ice in the metal cup melted first. Explain why. [2]", answers: ["Metal is a good conductor of heat, so the ice in the metal cup gained heat from the warmer surroundings faster and melted first.", "The ice in the metal cup melted first because it melted faster.", "The metal cup is colder, so the ice melted faster."], marks: 2, best: 0, why: "Pupil 1 names the property (good conductor of heat) AND links it to the ice gaining heat faster. Pupil 2 only repeats the observation, and Pupil 3 is wrong science: a colder cup would not melt ice faster." },
    { q: "Ben grew balsam plants with 2, 4, 6 and 8 hours of light a day; the taller plants had more light. He concluded: ‘All plants grow taller with more light.’ Is his conclusion valid? Explain. [1]", marks: 1, answers: ["Yes, because the plants with more light grew taller.", "No. He tested only balsam plants, so he can only conclude this for balsam plants, for 2 to 8 hours of light.", "No, because plants need water too."], best: 1, why: "Pupil 2 spots that the conclusion goes beyond what was tested (one type of plant, one range). Pupil 1 accepts an over-general claim, and Pupil 3 brings in an idea that was not tested." },
    { q: "Mei measured the temperature of water by feeling it with her hand. Suggest one improvement to her experiment and explain how it helps. [2]", marks: 2, answers: ["Be more careful when measuring.", "Use better equipment.", "Use a thermometer or temperature sensor, so that the temperature is measured more accurately as a reading instead of a feeling."], best: 2, why: "Pupil 3 gives the exact change and says what it improves (accuracy). ‘Be more careful’ and ‘better equipment’ are too vague to earn marks." },
    { q: "Cloth A dried in 60 minutes with no fan; cloth B dried in 35 minutes in front of a fan. Which cloth dried faster? Explain using the data. [2]", marks: 2, answers: ["Cloth B, because of the fan.", "Cloth B. It dried in 35 minutes, 25 minutes faster than cloth A. The moving air from the fan carried water vapour away, so the water evaporated faster.", "Cloth B dried faster because the fan made it dry."], best: 1, why: "Pupil 2 gives claim, evidence (35 vs 60 minutes) and reasoning (moving air, evaporated faster). Pupils 1 and 3 give no data and no science concept: ‘the fan made it dry’ just repeats the observation." }
  ]
};
