window.LB = window.LB || {};
LB["p6-webs"] = {
  notes: [
    { h: "What a food chain shows", t: "A food chain shows the food relationship between organisms: who eats whom. It always begins with a producer (a green plant or algae). Each arrow points from the food to the organism that eats it, so the arrow shows the direction in which energy flows.", kw: ["food relationship", "begins with a producer", "direction in which energy flows"] },
    { h: "Reading the arrow", t: "Read an arrow as ‘is eaten by’: grass → grasshopper means the grass is eaten by the grasshopper. A common mistake is to draw the arrow from the eater to its food. The arrow never points back to the producer.", kw: ["is eaten by", "arrow points to the eater"] },
    { h: "Producers", t: "Green plants are producers because they make their own food by photosynthesis, using light energy from the Sun. Algae and water plants are the producers in ponds and the sea. Every food chain starts with a producer, because no other organism can trap the Sun’s energy to make food.", kw: ["producers", "make their own food", "light energy", "photosynthesis"] },
    { h: "Consumers: herbivores, carnivores, omnivores", t: "Consumers cannot make their own food, so they eat other organisms. Herbivores eat only plants (e.g. goats, caterpillars), carnivores eat only animals (e.g. eagles, snakes) and omnivores eat both plants and animals (e.g. humans, ducks, chickens).", kw: ["consumers", "cannot make their own food", "herbivores", "carnivores", "omnivores"] },
    { h: "Prey and predators", t: "A predator is an animal that hunts and eats other animals; the animal that is eaten is its prey. An animal can be both a predator and a prey, e.g. a frog eats grasshoppers but is eaten by snakes. A herbivore that eats plants is a prey but not a predator.", kw: ["predator", "prey", "both a predator and a prey"] },
    { h: "Food webs", t: "A food web is made up of two or more food chains that are linked. Most animals eat more than one kind of food and are eaten by more than one kind of animal. An animal with several food sources can survive better if one of its foods decreases.", kw: ["food web", "linked food chains", "more than one kind of food"] },
    { h: "Counting food chains in a web", t: "Start at each producer and follow every possible path of arrows until you reach an organism that is not eaten by anything. Each complete path from a producer to the end is one food chain. Work organism by organism and tick off paths so none is missed or counted twice.", kw: ["start at each producer", "follow every path", "complete path"] },
    { h: "The Sun: source of energy", t: "The Sun is the source of energy for all food chains. Plants absorb light energy to make food; the energy is stored in the food and passed on to each animal that eats the plant, and then to the animals that eat those animals. So even an eagle’s energy came from the Sun.", kw: ["the sun is the source of energy", "absorb light energy", "energy is passed on"] },
    { h: "Decomposers", t: "Decomposers such as fungi (mushrooms, moulds) and bacteria break down dead plants and animals and their waste. This returns nutrients (mineral salts) to the soil, which plants absorb to grow. Without decomposers, dead matter would pile up and plants would lack nutrients.", kw: ["decomposers", "fungi", "bacteria", "break down dead plants and animals", "return nutrients to the soil"] },
    { h: "Populations and communities", t: "A population is a group of organisms of the same kind living in the same place at the same time. The different populations living and interacting in a habitat make up a community. A change in one population in a food web can affect many others.", kw: ["population", "same kind", "community"] },
    { h: "When a population changes", t: "If a prey population decreases, its predators have less food and may decrease. If a predator population decreases, fewer of its prey are eaten, so the prey may increase. An animal that loses its ONLY food will decrease; one that has other food may be less affected but will eat more of its other food.", kw: ["less food", "fewer are eaten", "only food", "eat more of its other food"] },
    { h: "Writing effect answers (PSLE)", t: "State the change (increase or decrease) and give the reason using the feeding link, e.g. ‘The frogs will increase because fewer frogs are eaten by snakes.’ Name the organisms. When an organism has more than one link, say ‘may’ and explain which link you are using.", kw: ["increase because fewer are eaten", "decrease because less food", "name the organisms"] }
  ],
  traps: [
    "The arrow means ‘eats’ → WRONG. It means ‘is eaten by’ and points from the food to the eater (the direction of energy flow).",
    "A rabbit is a predator because it eats grass → WRONG. A predator hunts and eats other ANIMALS; a herbivore is a prey only.",
    "Mushrooms are producers because they grow in soil → WRONG. Fungi have no chlorophyll; they are decomposers.",
    "Green plants are the source of energy for food chains → the SUN is the source; plants trap its light energy.",
    "If a predator’s one food decreases, it will surely die out → not if it has other food; it will eat more of its other food instead.",
    "Counting food chains: only counting paths from one producer → start from EVERY producer and follow every path to the end.",
    "‘The frogs will increase.’ with no reason → PSLE needs the reason: ‘…because fewer frogs are eaten by snakes.’",
    "Decomposers appear at the start of the food chain → they are not usually drawn in the chain; they break down dead organisms from every level."
  ],
  lessons: [
    {
      h: "Turning words into a food chain",
      concept: "Change every ‘X eats Y’ into an arrow Y → X (food → eater). Find the producer first: it is the only one that eats nothing. Then chain the eaters in order until you reach the organism that nothing eats.",
      example: {
        q: "In a school garden, mynahs eat grasshoppers, praying mantises eat grasshoppers, grasshoppers eat lalang, and mynahs eat praying mantises. Draw the longest food chain.",
        marks: 1,
        think: [
          "Step 1: The producer is lalang (a green plant that eats nothing).",
          "Step 2: Write each clue as food → eater: lalang → grasshopper, grasshopper → mantis, grasshopper → mynah, mantis → mynah.",
          "Step 3: The longest path from lalang to the end is lalang → grasshopper → praying mantis → mynah."
        ],
        answer: "lalang → grasshopper → praying mantis → mynah"
      },
      tip: "Say ‘is eaten by’ out loud for every arrow you draw. If the sentence sounds wrong, your arrow is backwards.",
      try: {
        q: "Caterpillars eat hibiscus leaves. Birds eat caterpillars. Cats eat birds. Which food chain is correct?",
        o: ["cat → bird → caterpillar → hibiscus", "hibiscus → caterpillar → bird → cat", "hibiscus → bird → caterpillar → cat", "caterpillar → hibiscus → bird → cat"],
        a: 1,
        why: "The chain must start with the producer (hibiscus) and every arrow must point to the eater. The first option has all the arrows reversed."
      }
    },
    {
      h: "Counting food chains without missing any",
      concept: "Start at each producer. From it, follow one arrow at a time; whenever an organism has two or more arrows leaving it, the path splits. Count a chain only when you reach an organism with no arrow leaving it. List the chains so you can check none is repeated.",
      example: {
        q: "The diagram shows a food web. A and B are plants. How many food chains are there in this food web?",
        fig: { type: "web", links: [["A", "C"], ["B", "C"], ["B", "D"], ["C", "E"], ["D", "E"], ["D", "F"], ["E", "G"], ["F", "G"]] },
        marks: 1,
        think: [
          "Step 1: There are two producers, A and B, so start from each one.",
          "Step 2: From A: A → C → E → G. That is 1 chain.",
          "Step 3: From B: B → C → E → G; B → D → E → G; B → D → F → G. That is 3 chains.",
          "Step 4: Total = 1 + 3 = 4 food chains."
        ],
        answer: "4 food chains"
      },
      tip: "Write each chain down as you find it. Pupils usually lose the mark by forgetting the second producer.",
      try: {
        q: "The diagram shows a food web in a school garden. How many food chains are there?",
        fig: { type: "web", links: [["lalang", "grasshopper"], ["chilli plant", "aphid"], ["aphid", "ladybird"], ["grasshopper", "mynah"], ["grasshopper", "praying mantis"], ["praying mantis", "mynah"], ["ladybird", "mynah"]] },
        o: ["2", "3", "4", "5"],
        a: 1,
        why: "lalang → grasshopper → mynah; lalang → grasshopper → praying mantis → mynah; chilli plant → aphid → ladybird → mynah. That is 3."
      }
    },
    {
      h: "Predicting what happens when a population changes",
      concept: "Look only at the arrows touching the changed organism. Its PREY (arrows coming in) are eaten less, so they may increase. Its PREDATORS (arrows going out) have less food, so they may decrease — sharply if it was their only food. Always give the change AND the feeding reason.",
      example: {
        q: "The diagram shows a food web. All the snakes are caught. (a) What would happen to the rabbit population? (b) Explain your answer.",
        fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] },
        marks: 2,
        think: [
          "Step 1: Find the arrows from rabbit: rabbit → snake only. So the snake is the rabbit’s only predator.",
          "Step 2: With no snakes, fewer rabbits are eaten.",
          "Step 3: So the rabbit population would increase (at first)."
        ],
        answer: "(a) The rabbit population would increase. (b) The snake is the only animal that eats rabbits, so fewer rabbits would be eaten."
      },
      tip: "Two parts every time: the change + ‘because fewer ___ are eaten by ___’ or ‘because ___ has less food’.",
      try: {
        q: "In the pond food web shown, all the ducks die. What would most likely happen to the snail population at first?",
        fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water plant", "snail"], ["water plant", "duck"], ["water flea", "small fish"], ["tadpole", "small fish"], ["snail", "duck"], ["small fish", "duck"], ["small fish", "kingfisher"]] },
        o: ["It would decrease, because the snails would have less food.", "It would stay the same, because snails do not eat ducks.", "It would decrease, because the small fish would eat more snails.", "It would increase, because fewer snails would be eaten."],
        a: 3,
        why: "The duck is the only animal that eats snails, so fewer snails are eaten. Small fish do not eat snails, and the snails’ food (water plant) is not reduced."
      }
    },
    {
      h: "Producer, herbivore, carnivore, omnivore, predator, prey",
      concept: "Look at what goes INTO an organism. Nothing in → producer. Only plants in → herbivore (prey only, never a predator). Only animals in → carnivore. Plants AND animals in → omnivore. Then look at what goes OUT: if an animal eats animals AND is eaten, it is both a predator and a prey.",
      example: {
        q: "The diagram shows a food web. K is a green plant. Explain why N is an omnivore.",
        fig: { type: "web", links: [["K", "L"], ["K", "M"], ["K", "N"], ["L", "N"], ["M", "N"], ["N", "O"]] },
        marks: 2,
        think: [
          "Step 1: Find the arrows pointing INTO N: from K, L and M.",
          "Step 2: K is a plant. L and M eat K, so they are animals.",
          "Step 3: N eats both a plant and animals, so N is an omnivore."
        ],
        answer: "N eats K, which is a plant, and it also eats L and M, which are animals. So N eats both plants and animals."
      },
      tip: "A herbivore is never a predator. ‘Predator’ only applies to animals that eat animals.",
      try: {
        q: "The diagram shows a garden food web. Which organisms are herbivores?",
        fig: { type: "web", links: [["hibiscus", "caterpillar"], ["hibiscus", "aphid"], ["aphid", "ladybird"], ["caterpillar", "bird"], ["ladybird", "bird"], ["bird", "cat"]] },
        o: ["ladybird and bird", "hibiscus and aphid", "caterpillar and aphid", "caterpillar and ladybird"],
        a: 2,
        why: "The caterpillar and the aphid eat only the hibiscus plant. The ladybird eats aphids (animals), so it is not a herbivore; the hibiscus is a producer."
      }
    },
    {
      h: "Energy from the Sun and the job of decomposers",
      concept: "For ‘where does the energy come from’, trace it back: the animal ate another animal, which ate a plant, and the plant absorbed LIGHT ENERGY from the Sun to make food. For decomposers, give both parts of their job: break down dead matter AND return nutrients to the soil for plants.",
      example: {
        q: "Explain why the energy that a snake uses to move comes from the Sun. The food chain is grass → grasshopper → frog → snake.",
        fig: { type: "web", links: [["grass", "grasshopper"], ["grasshopper", "frog"], ["frog", "snake"]] },
        marks: 2,
        think: [
          "Step 1: Start at the producer: grass absorbs light energy from the Sun to make food by photosynthesis.",
          "Step 2: The energy is stored in the food and passed on when the grasshopper eats the grass.",
          "Step 3: It is passed to the frog and then to the snake when each one is eaten."
        ],
        answer: "The grass absorbs light energy from the Sun to make food. The energy is passed to the grasshopper that eats the grass, then to the frog, and then to the snake that eats the frog."
      },
      tip: "Decomposer answers need two ideas: ‘break down dead plants and animals’ + ‘return nutrients to the soil’.",
      try: {
        q: "Which of the following best describes the role of decomposers such as fungi and bacteria?",
        o: ["They break down dead plants and animals and return nutrients to the soil.", "They make food for animals using light energy from the Sun.", "They eat living plants and are then eaten by predators.", "They kill harmful animals living in the soil to protect plants."],
        a: 0,
        why: "Decomposers break down dead matter so that nutrients go back into the soil for plants to use. They have no chlorophyll, so they cannot make food using light energy."
      }
    }
  ],
  mcq: [
    { q: "Study the food chain shown. Which organism is the producer?", fig: { type: "web", links: [["grass", "grasshopper"], ["grasshopper", "frog"], ["frog", "snake"]] }, o: ["grass", "grasshopper", "frog", "snake"], a: 0, why: "Grass is a green plant that makes its own food using light energy, and the chain starts with it. The others are consumers.", lvl: 1 },
    { q: "In a food chain, what does each arrow show?", o: ["The size of each organism, from small to big", "Which organism is stronger than the other", "The direction of energy flow, from the food to its eater", "The direction in which each organism moves to find food"], a: 2, why: "The arrow means ‘is eaten by’ and shows energy flowing from the food to the eater. It says nothing about size, strength or movement.", lvl: 1 },
    { q: "What is the source of energy for all food chains?", o: ["The soil", "Water", "Green plants", "The Sun"], a: 3, why: "Green plants trap light energy from the Sun to make food, so the Sun is the source. The plants are the first link, not the source.", lvl: 1 },
    { q: "Which pair of organisms are both decomposers?", o: ["Moss and fern", "Mushroom and bacteria", "Earthworm and snail", "Algae and bacteria"], a: 1, why: "Fungi such as mushrooms and bacteria are decomposers. Moss, fern and algae are producers; earthworms and snails are animals.", lvl: 1 },
    { q: "Which of the following is a herbivore?", o: ["An animal that eats both plants and animals", "An organism that makes its own food", "An animal that eats only other animals", "An animal that eats only plants"], a: 3, why: "A herbivore eats only plants. An omnivore eats both, a carnivore eats only animals, and a producer makes its own food.", lvl: 1 },
    { q: "Study the food web shown. Which organism is a prey but NOT a predator?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["frog", "snake", "eagle", "rabbit"], a: 3, why: "The rabbit eats only grass (a plant) and is eaten by the snake, so it is a prey only. The frog and snake eat animals, and the eagle is not eaten.", lvl: 1 },
    { q: "Why are green plants called producers?", o: ["They produce seeds that grow into new plants.", "They make their own food using light energy.", "They produce oxygen for animals to breathe.", "They are eaten by many different animals."], a: 1, why: "Producers make their own food by photosynthesis. Plants do give off oxygen and seeds, but that is not why they are called producers.", lvl: 1 },
    { q: "Study the food web shown. P is a green plant. Which organism is not eaten by any other organism in this food web?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["Q", "S"], ["R", "S"], ["R", "T"], ["S", "U"], ["T", "U"]] }, o: ["P", "S", "U", "T"], a: 2, why: "No arrow leaves U, so nothing eats it. S and T both have arrows pointing to U, and P is eaten by Q and R.", lvl: 1 },

    { q: "Study the food web shown. How many food chains are there?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["3", "4", "5", "6"], a: 1, why: "grass → grasshopper → frog → snake → eagle; grass → grasshopper → bird → snake → eagle; grass → grasshopper → bird → eagle; grass → rabbit → snake → eagle. That is 4.", lvl: 2 },
    { q: "Study the food web shown. Which organism is both a predator and a prey?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["grass", "rabbit", "bird", "eagle"], a: 2, why: "The bird eats grasshoppers (animals) and is eaten by snakes and eagles. The rabbit eats only a plant, so it is not a predator; the eagle is not eaten.", lvl: 2 },
    { q: "Study the food web shown. P is a green plant. How many food chains are there?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["Q", "S"], ["R", "S"], ["R", "T"], ["S", "U"], ["T", "U"]] }, o: ["3", "4", "5", "6"], a: 0, why: "P → Q → S → U; P → R → S → U; P → R → T → U. That is 3.", lvl: 2 },
    { q: "Study the pond food web shown. Which organism is an omnivore?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water plant", "snail"], ["water plant", "duck"], ["water flea", "small fish"], ["tadpole", "small fish"], ["snail", "duck"], ["small fish", "duck"], ["small fish", "kingfisher"]] }, o: ["small fish", "kingfisher", "duck", "snail"], a: 2, why: "The duck eats a water plant as well as snails and small fish, so it eats both plants and animals. The small fish and kingfisher eat only animals; the snail eats only plants.", lvl: 2 },
    { q: "Study the pond food web shown. Which organisms are the producers?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water plant", "snail"], ["water plant", "duck"], ["water flea", "small fish"], ["tadpole", "small fish"], ["snail", "duck"], ["small fish", "duck"], ["small fish", "kingfisher"]] }, o: ["algae only", "algae and water plant", "water plant and snail", "algae, water flea and water plant"], a: 1, why: "Algae and the water plant have no arrows pointing into them; they make their own food. Snails and water fleas are consumers.", lvl: 2 },
    { q: "Study the food web shown. All the grasshoppers died. Which population would decrease because it has lost its ONLY source of food?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["grass", "rabbit", "frog", "snake"], a: 2, why: "The only arrow into the frog comes from the grasshopper. The snake still has rabbits and birds, and the grass is eaten less.", lvl: 2 },
    { q: "The diagram shows a food web in a mangrove swamp at Sungei Buloh. Which organisms are eaten by BOTH the heron and the monitor lizard?", fig: { type: "web", links: [["mangrove leaves", "crab"], ["mangrove leaves", "insect"], ["insect", "mudskipper"], ["crab", "heron"], ["crab", "monitor lizard"], ["mudskipper", "heron"], ["mudskipper", "monitor lizard"]] }, o: ["crab only", "mudskipper only", "crab and mudskipper", "insect and crab"], a: 2, why: "Both the crab and the mudskipper have arrows to the heron and to the monitor lizard. The insect is eaten only by the mudskipper.", lvl: 2 },
    { q: "Study the food chain shown. W is a green plant. Which of the following describes Y correctly?", fig: { type: "web", links: [["W", "X"], ["X", "Y"], ["Y", "Z"]] }, o: ["It is a producer that makes food.", "It is a prey only, not a predator.", "It is a predator only, not a prey.", "It is both a predator and a prey."], a: 3, why: "Y eats X, an animal (X eats the plant W), so Y is a predator. Y is eaten by Z, so it is also a prey.", lvl: 2 },
    { q: "The bar graph shows how many kinds of organisms each of four organisms, W, X, Y and Z, eats in a food web. Which one is most likely the producer?", fig: { type: "bar", xl: "Organism", yl: "Number of kinds of organisms it eats", bars: [["W", 0], ["X", 1], ["Y", 3], ["Z", 2]] }, o: ["W", "X", "Y", "Z"], a: 0, why: "A producer makes its own food and does not eat any other organism, so it eats 0 kinds. X, Y and Z all eat other organisms, so they are consumers.", lvl: 2 },
    { q: "In a field, the food chain is grass → grasshopper → frog. An insecticide that killed most of the grasshoppers was sprayed in April. The graph shows the number of frogs counted. Which best explains the change after April?", fig: { type: "bar", xl: "Month", yl: "Number of frogs", bars: [["Jan", 40], ["Mar", 38], ["May", 12], ["Jul", 8]] }, o: ["The frogs ate the grass instead of the grasshoppers.", "The frogs had less food, as there were fewer grasshoppers.", "More frogs were eaten by the grasshoppers in the field.", "The grass population decreased, so there was less shelter."], a: 1, why: "The grasshoppers are the frogs’ food, so fewer grasshoppers meant less food and fewer frogs. Frogs do not eat grass, and with fewer grasshoppers the grass would be eaten less, not more.", lvl: 2 },
    { q: "Study the food web shown. A and B are green plants. How many food chains include organism C?", fig: { type: "web", links: [["A", "C"], ["B", "C"], ["B", "D"], ["C", "E"], ["D", "E"], ["D", "F"], ["E", "G"], ["F", "G"]] }, o: ["1", "2", "3", "4"], a: 1, why: "A → C → E → G and B → C → E → G. The other two chains go through D instead of C.", lvl: 2 },
    { q: "Study the food web shown. K is a green plant. Which organism is an omnivore?", fig: { type: "web", links: [["K", "L"], ["K", "M"], ["K", "N"], ["L", "N"], ["M", "N"], ["N", "O"]] }, o: ["K", "L", "N", "O"], a: 2, why: "N eats the plant K and the animals L and M. L eats only the plant (herbivore), and O eats only N (carnivore).", lvl: 2 },
    { q: "At Pulau Ubin, a pupil wrote: ‘Otters eat fish. Fish eat water fleas. Water fleas eat algae.’ Which food chain is correct?", o: ["otter → fish → water flea → algae", "algae → fish → water flea → otter", "water flea → algae → fish → otter", "algae → water flea → fish → otter"], a: 3, why: "The chain starts with the producer (algae) and each arrow points to the eater. The first option has every arrow reversed.", lvl: 2 },
    { q: "A mushroom grows on a fallen tree trunk in MacRitchie forest. Why is it NOT a producer?", o: ["It has no chlorophyll, so it cannot make its own food.", "It does not grow in soil, so it gets no water.", "It does not reproduce by seeds like green plants.", "It is eaten by animals such as snails and slugs."], a: 0, why: "Producers make their own food using light energy absorbed by chlorophyll. A mushroom has no chlorophyll; it is a decomposer that feeds on dead matter.", lvl: 2 },

    { q: "Study the food web shown. All the snakes are caught. Which populations would most likely increase at first because the snake was their ONLY predator?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["frog and rabbit only", "bird and eagle only", "grass and eagle only", "frog, rabbit and eagle only"], a: 0, why: "The snake is the only predator of the frog and the rabbit, so fewer of them are eaten. The bird is also eaten by eagles, and the eagle loses one of its foods, so it would not increase.", lvl: 3 },
    { q: "Study the food web shown. All the eagles are removed. Which shows the most likely changes in the snake and rabbit populations?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["Snake: decrease; Rabbit: increase", "Snake: decrease; Rabbit: decrease", "Snake: increase; Rabbit: increase", "Snake: increase; Rabbit: decrease"], a: 3, why: "The eagle is the snake’s only predator, so the snakes increase. More snakes then eat more rabbits, so the rabbits decrease.", lvl: 3 },
    { q: "Study the food web shown. A and B are green plants. All of organism D die. Which organism would decrease because it has lost its ONLY food?", fig: { type: "web", links: [["A", "C"], ["B", "C"], ["B", "D"], ["C", "E"], ["D", "E"], ["D", "F"], ["E", "G"], ["F", "G"]] }, o: ["F", "B", "E", "G"], a: 0, why: "The only arrow into F comes from D. E can still eat C, G can still eat E, and B is a plant that would be eaten less.", lvl: 3 },
    { q: "Study the food web shown. P is a green plant. How many food chains are there?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["P", "S"], ["Q", "T"], ["Q", "V"], ["R", "T"], ["R", "U"], ["S", "U"], ["T", "V"], ["U", "V"]] }, o: ["2", "3", "4", "5"], a: 3, why: "P → Q → V; P → Q → T → V; P → R → T → V; P → R → U → V; P → S → U → V. The short chain P → Q → V is the one most often missed.", lvl: 3 },
    { q: "The diagram shows a food web in a rice field. How many food chains include the frog?", fig: { type: "web", links: [["rice plant", "grasshopper"], ["rice plant", "rat"], ["grasshopper", "frog"], ["grasshopper", "spider"], ["spider", "frog"], ["frog", "snake"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, o: ["2", "3", "4", "5"], a: 0, why: "rice plant → grasshopper → frog → snake → owl, and rice plant → grasshopper → spider → frog → snake → owl. The two chains through the rat do not include the frog.", lvl: 3 },
    { q: "Study the food web shown. K is a green plant. Which statement is NOT correct?", fig: { type: "web", links: [["K", "L"], ["K", "M"], ["K", "N"], ["L", "N"], ["M", "N"], ["N", "O"]] }, o: ["L and M are herbivores.", "N is an omnivore.", "O is a prey.", "There are three food chains."], a: 2, why: "No arrow leaves O, so nothing eats O and it is not a prey. The chains are K → L → N → O, K → M → N → O and K → N → O.", lvl: 3 },
    { q: "In a field, the food chain is grass → grasshopper → bird. Many birds were caught by poachers in Year 2. The graph shows the grasshopper population. Which best explains the change in Year 3?", fig: { type: "bar", xl: "Year", yl: "Number of grasshoppers", bars: [["Year 1", 200], ["Year 2", 210], ["Year 3", 420]] }, o: ["There was less grass for the grasshoppers.", "Fewer grasshoppers were eaten by birds.", "More grasshoppers were eaten by birds.", "The grasshoppers ate the birds’ eggs."], a: 1, why: "With fewer birds, fewer grasshoppers were eaten, so the grasshoppers increased. Less grass would have caused a decrease, not a rise.", lvl: 3 },
    { q: "Two jars were set up as shown. The soil in jar B was heated strongly and cooled before the leaves were added. After four weeks, the leaves in jar A had broken down but the leaves in jar B had not. What can be concluded?", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Dead leaves", "Garden soil", "Sealed, 25 °C"] }, { label: "B", icon: "jar", lines: ["Dead leaves", "Heated garden soil", "Sealed, 25 °C"] }] }, o: ["Heat is needed for dead leaves in the soil to break down quickly.", "Dead leaves break down only in sealed jars without any air.", "Soil must be dry for dead leaves in it to break down over time.", "Living things in the soil, such as bacteria and fungi, break down dead leaves."], a: 3, why: "Heating killed the decomposers in the soil of B, and only A still had them. Both jars were at the same temperature, so heat was not the variable tested.", lvl: 3 },
    { q: "Study the garden food web shown. Which organisms are both a predator and a prey?", fig: { type: "web", links: [["hibiscus", "caterpillar"], ["hibiscus", "aphid"], ["aphid", "ladybird"], ["caterpillar", "bird"], ["ladybird", "bird"], ["bird", "cat"]] }, o: ["aphid only", "cat only", "ladybird and bird", "caterpillar and bird"], a: 2, why: "The ladybird eats aphids and is eaten by birds; the bird eats caterpillars and ladybirds and is eaten by cats. The caterpillar eats only a plant, so it is not a predator.", lvl: 3 },
    { q: "Study the mangrove food web shown. Many herons were hunted. Which of the following would most likely happen? 1: The crabs increase. 2: The mudskippers increase. 3: The insects decrease. 4: The monitor lizards decrease.", fig: { type: "web", links: [["mangrove leaves", "crab"], ["mangrove leaves", "insect"], ["insect", "mudskipper"], ["crab", "heron"], ["crab", "monitor lizard"], ["mudskipper", "heron"], ["mudskipper", "monitor lizard"]] }, o: ["1 and 2 only", "1, 2 and 3 only", "3 and 4 only", "1, 2, 3 and 4"], a: 1, why: "Fewer crabs and mudskippers are eaten, so both increase, and more mudskippers eat more insects. The monitor lizard has MORE food, so it would not decrease.", lvl: 3 },
    { q: "Study the pond food web shown. All the kingfishers fly away. Which change would most likely happen first?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water plant", "snail"], ["water plant", "duck"], ["water flea", "small fish"], ["tadpole", "small fish"], ["snail", "duck"], ["small fish", "duck"], ["small fish", "kingfisher"]] }, o: ["The small fish would increase.", "The water fleas would increase.", "The ducks would decrease.", "The algae would decrease."], a: 0, why: "Kingfishers eat only small fish, so fewer small fish are eaten. More small fish would then eat more water fleas, so water fleas would decrease, not increase.", lvl: 3 },
    { q: "Study the pond food web shown. How many food chains are there?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water plant", "snail"], ["water plant", "duck"], ["water flea", "small fish"], ["tadpole", "small fish"], ["snail", "duck"], ["small fish", "duck"], ["small fish", "kingfisher"]] }, o: ["3", "4", "5", "6"], a: 3, why: "From algae: via water flea or tadpole to small fish, then to duck or kingfisher = 4. From water plant: → snail → duck and → duck = 2. Total 6.", lvl: 3 },

    { q: "In a forest, organism P makes its own food. Q and R eat only P. S eats Q and R. T eats R and S. Nothing eats T. How many food chains are there?", o: ["2", "3", "4", "5"], a: 1, why: "P → Q → S → T, P → R → S → T and P → R → T. Q is not eaten by T, so there is no P → Q → T chain.", lvl: 4 },
    { q: "Study the food web shown. A and B are green plants. A disease kills all of organism E. Which statements are most likely true at first? 1: C would increase. 2: G would eat more F, so F would decrease. 3: G would die out. 4: D would decrease.", fig: { type: "web", links: [["A", "C"], ["B", "C"], ["B", "D"], ["C", "E"], ["D", "E"], ["D", "F"], ["E", "G"], ["F", "G"]] }, o: ["1 and 2 only", "1 and 3 only", "2 and 4 only", "1, 2 and 4 only"], a: 0, why: "E is C’s only predator, so C increases. G still has F to eat, so it survives but eats more F. D loses a predator (E) and F decreases, so D would not decrease.", lvl: 4 },
    { q: "The diagram shows a food chain. A is a green plant. The table shows each population before and one month after a change. Which change most likely caused these results?", fig: { type: "web", links: [["A", "B"], ["B", "C"], ["C", "D"]] }, tbl: [["Organism", "Before", "One month after"], ["A", "500", "800"], ["B", "200", "90"], ["C", "40", "70"], ["D", "10", "2"]], o: ["More of plant A grew.", "A disease killed many of C.", "Many of B moved into the area.", "Many of D were hunted."], a: 3, why: "Fewer D → fewer C eaten, so C rises → more B eaten, so B falls → less A eaten, so A rises. This matches every row. A disease in C would make C fall, not rise.", lvl: 4 },
    { q: "Study the rice-field food web shown. A pesticide kills most of the grasshoppers. Which statements are most likely true? 1: The spiders would decrease. 2: The frogs would decrease. 3: The owls would die out.", fig: { type: "web", links: [["rice plant", "grasshopper"], ["rice plant", "rat"], ["grasshopper", "frog"], ["grasshopper", "spider"], ["spider", "frog"], ["frog", "snake"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, o: ["1 only", "1 and 2 only", "2 and 3 only", "1, 2 and 3"], a: 1, why: "Grasshoppers are the spiders’ only food, and both of the frogs’ foods (grasshoppers and spiders) fall. The owls still have rats to eat, so they would not die out.", lvl: 4 },
    { q: "Study the food web shown. P is a green plant. How many organisms in this food web are both a predator and a prey?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["P", "S"], ["Q", "T"], ["Q", "V"], ["R", "T"], ["R", "U"], ["S", "U"], ["T", "V"], ["U", "V"]] }, o: ["0", "1", "2", "5"], a: 2, why: "Only T and U eat animals and are also eaten. Q, R and S eat only the plant P, so they are prey but not predators. V is not eaten.", lvl: 4 },
    { q: "Study the food web shown. A disease killed most of the rabbits, but the snake population stayed about the same. Which of the following best explains this, and what would most likely happen next?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, o: ["The snakes ate more frogs and birds, so the frogs and birds would decrease.", "The snakes ate more grass, so the grass would decrease.", "The eagles ate fewer snakes, so the eagles would increase.", "The snakes ate more grasshoppers, so the grasshoppers would decrease."], a: 0, why: "The snake’s other foods are frogs and birds, so it eats more of them and they decrease. Snakes do not eat grass or grasshoppers in this web.", lvl: 4 }
  ],
  tf: [
    { s: "In a food chain, the arrow points from the organism that is eaten to the organism that eats it.", a: true, why: "The arrow means ‘is eaten by’ and shows the direction of energy flow." },
    { s: "The arrow in grass → goat means ‘the grass eats the goat’.", a: false, why: "It means the grass is eaten by the goat." },
    { s: "Every food chain begins with a producer.", a: true, why: "Only producers can make food using light energy, so energy enters the chain through them." },
    { s: "Mushrooms are producers because they grow on the ground like plants.", a: false, why: "Mushrooms are fungi with no chlorophyll; they are decomposers." },
    { s: "Decomposers break down dead plants and animals and return nutrients to the soil.", a: true, why: "Plants then absorb these nutrients through their roots." },
    { s: "A rabbit is a predator because it eats grass.", a: false, why: "A predator eats other animals. The rabbit is a herbivore and a prey." },
    { s: "An animal can be both a predator and a prey.", a: true, why: "A frog eats insects and is eaten by snakes." },
    { s: "Omnivores eat only animals.", a: false, why: "Omnivores eat both plants and animals; carnivores eat only animals." },
    { s: "The Sun is the source of energy for all food chains.", a: true, why: "Plants absorb its light energy to make food, which passes along the chain." },
    { s: "Green plants get their food from the soil.", a: false, why: "Plants make their own food by photosynthesis; they take in water and mineral salts from the soil, not food." },
    { s: "A food web is made up of two or more food chains that are linked.", a: true, why: "Organisms in a web share food sources and predators." },
    { s: "If a predator dies out, all its prey will die out too.", a: false, why: "Its prey are eaten less, so they may increase." },
    { s: "An animal that eats many kinds of food is usually less affected when one of its foods decreases.", a: true, why: "It can eat more of its other foods." },
    { s: "Algae are producers.", a: true, why: "Algae contain chlorophyll and make their own food; they start many pond and sea food chains." },
    { s: "Decomposers are always drawn at the start of a food chain.", a: false, why: "Food chains start with a producer; decomposers are usually not shown in the chain." },
    { s: "Some bacteria are decomposers.", a: true, why: "Bacteria and fungi break down dead matter." },
    { s: "The organism at the end of a food chain is always the largest animal.", a: false, why: "It is simply the one not eaten by others in that chain; size does not decide this." },
    { s: "Energy is passed along a food chain when one organism eats another.", a: true, why: "The energy stored in food moves to the eater." },
    { s: "A population is a group of different kinds of organisms living in the same place.", a: false, why: "A population is one kind of organism; many populations together form a community." },
    { s: "Removing an organism from a food web affects only the organisms that eat it or are eaten by it.", a: false, why: "Effects can spread further, e.g. fewer eagles → more snakes → fewer rabbits." }
  ],
  sort: [
    { title: "Sort these organisms by how they get their food.", groups: ["Producer", "Herbivore", "Carnivore", "Omnivore"], items: [["rice plant", 0], ["algae", 0], ["cow", 1], ["caterpillar", 1], ["grasshopper", 1], ["eagle", 2], ["snake", 2], ["frog", 2], ["human", 3], ["chicken", 3]] },
    { title: "Is each one a producer, a consumer or a decomposer?", groups: ["Producer", "Consumer", "Decomposer"], items: [["mango tree", 0], ["moss", 0], ["fern", 0], ["goat", 1], ["mosquito", 1], ["monkey", 1], ["mushroom", 2], ["bread mould", 2], ["bacteria in the soil", 2]] },
    { title: "Read each clue. Is the animal a prey only, a predator only, or both?", groups: ["Prey only", "Predator only", "Both predator and prey"], items: [["a rabbit that eats grass and is eaten by snakes", 0], ["a grasshopper that eats grass and is eaten by birds", 0], ["a caterpillar that eats leaves and is eaten by birds", 0], ["an eagle that eats snakes and is not eaten", 1], ["a tiger that eats deer and is not eaten", 1], ["an owl that eats rats and is not eaten", 1], ["a snake that eats frogs and is eaten by eagles", 2], ["a spider that eats flies and is eaten by frogs", 2], ["a ladybird that eats aphids and is eaten by birds", 2]] }
  ],
  oe: [
    { q: "Study the food web shown. (a) Name the producer. (b) Name one organism that is both a predator and a prey. (c) How many food chains are there in this food web?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, marks: 3, kw: [["grass"], ["bird", "frog", "snake"], ["4", "four"]], model: "(a) Grass. (b) The frog: it eats grasshoppers and is eaten by snakes. (c) There are 4 food chains." },
    { q: "Study the food web shown. All the snakes were caught. (a) What would happen to the frog population? Explain. (b) What would happen to the eagle population? Explain.", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, marks: 4, kw: [["increase"], ["fewer frogs", "fewer of them", "less frogs", "eaten less"], ["decrease"], ["less food", "fewer food", "lost a food", "loses a food", "less to eat"]], model: "(a) The frog population would increase because fewer frogs would be eaten, as the snake is the only animal that eats frogs. (b) The eagle population may decrease because it has less food, as the snakes that it eats are gone." },
    { q: "Study the food web shown. P is a green plant. (a) Give two reasons from the food web and your knowledge why P is the producer. (b) How many food chains include organism S?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["Q", "S"], ["R", "S"], ["R", "T"], ["S", "U"], ["T", "U"]] }, marks: 3, kw: [["no arrow", "does not eat", "doesn't eat", "not eat", "eats nothing"], ["own food", "makes food", "make food", "photosynthes"], ["2", "two"]], model: "(a) No arrow points to P, so P does not eat any other organism. As a green plant, P makes its own food using light energy. (b) 2 food chains." },
    { q: "Fungi and bacteria are found in the soil of a forest. (a) Name the group of organisms that fungi and bacteria belong to, based on their role. (b) Explain the role of these organisms in the forest. (c) Suggest what would happen to the plants in the forest if these organisms were absent.", marks: 4, kw: [["decomposer"], ["break down", "breaks down", "broken down"], ["nutrients", "mineral"], ["grow poorly", "not grow well", "not have enough nutrients", "lack nutrients", "less nutrients", "fewer nutrients", "die"]], model: "(a) They are decomposers. (b) They break down dead plants and animals and return nutrients to the soil. (c) The plants would lack nutrients from the soil and grow poorly, and dead matter would pile up." },
    { q: "Study the food chain shown. (a) Where does the grass get its energy from, and how does it use it? (b) Explain how the snake gets energy from this source.", fig: { type: "web", links: [["grass", "grasshopper"], ["grasshopper", "frog"], ["frog", "snake"]] }, marks: 3, kw: [["light energy", "sun"], ["make food", "makes food", "make its own food", "makes its own food", "photosynthes"], ["eat", "eats", "eaten"]], model: "(a) The grass absorbs light energy from the Sun and uses it to make its own food. (b) The energy is stored in the food and is passed on when the grasshopper eats the grass, the frog eats the grasshopper and the snake eats the frog." },
    { q: "Study the pond food web shown. A chemical that leaked into the pond killed most of the small fish. (a) Predict what would happen to the water flea population. Explain. (b) Predict what would happen to the kingfisher population. Explain.", fig: { type: "web", links: [["algae", "water flea"], ["algae", "tadpole"], ["water plant", "snail"], ["water plant", "duck"], ["water flea", "small fish"], ["tadpole", "small fish"], ["snail", "duck"], ["small fish", "duck"], ["small fish", "kingfisher"]] }, marks: 4, kw: [["increase"], ["fewer water fleas", "fewer of them", "eaten less", "less water fleas"], ["decrease"], ["only food", "only source", "only eats", "only one food", "no other food"]], model: "(a) The water flea population would increase because fewer water fleas would be eaten by small fish. (b) The kingfisher population would decrease because small fish are its only food, so it would have less to eat.", x: 1 },
    { q: "Study the rice-field food web shown. A farmer sprays a pesticide that kills most of the grasshoppers. (a) Name two animals whose populations would decrease because they have less food. (b) Explain why the rice plants may increase.", fig: { type: "web", links: [["rice plant", "grasshopper"], ["rice plant", "rat"], ["grasshopper", "frog"], ["grasshopper", "spider"], ["spider", "frog"], ["frog", "snake"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, marks: 4, kw: [["spider"], ["frog"], ["fewer grasshoppers", "less grasshoppers", "grasshoppers are killed", "grasshoppers decrease"], ["eaten", "eat"]], model: "(a) The spider and the frog. (b) There are fewer grasshoppers, so fewer rice plants are eaten. Also, with fewer frogs the snakes eat more rats, so the rats eat fewer rice plants.", x: 1 },
    { q: "Study the mangrove food web shown. Many herons were hunted. (a) What would happen to the crab population at first? Explain. (b) Explain why the insect population may decrease.", fig: { type: "web", links: [["mangrove leaves", "crab"], ["mangrove leaves", "insect"], ["insect", "mudskipper"], ["crab", "heron"], ["crab", "monitor lizard"], ["mudskipper", "heron"], ["mudskipper", "monitor lizard"]] }, marks: 4, kw: [["increase"], ["fewer crabs", "fewer of them", "eaten less", "less crabs"], ["more mudskippers", "mudskippers increase", "mudskipper population increase", "mudskippers would increase"], ["more insects", "eat more"]], model: "(a) The crab population would increase because fewer crabs would be eaten by herons. (b) Fewer mudskippers would be eaten by herons, so there would be more mudskippers. More mudskippers would eat more insects." },
    { q: "Study the food web shown. K is a green plant. Explain why N is an omnivore.", fig: { type: "web", links: [["K", "L"], ["K", "M"], ["K", "N"], ["L", "N"], ["M", "N"], ["N", "O"]] }, marks: 2, kw: [["plant", "producer"], ["animal"]], model: "N eats K, which is a plant, and it also eats L and M, which are animals." },
    { q: "Study the garden food web shown. A gardener sprays a chemical that kills all the aphids. (a) What would happen to the ladybird population? Explain. (b) Explain why the bird population may not decrease much.", fig: { type: "web", links: [["hibiscus", "caterpillar"], ["hibiscus", "aphid"], ["aphid", "ladybird"], ["caterpillar", "bird"], ["ladybird", "bird"], ["bird", "cat"]] }, marks: 3, kw: [["decrease", "die out"], ["only food", "only source", "only eats"], ["caterpillar"]], model: "(a) The ladybird population would decrease because aphids are its only food. (b) The bird can still eat caterpillars, so it still has food." },
    { q: "In a field, grasshoppers are eaten by frogs and frogs are eaten by snakes. Many snakes were caught in February. The graph shows the populations in January and June. (a) Describe what happened to the frog population and explain why. (b) Predict what would happen to the grasshopper population after June. Explain.", fig: { type: "bar", xl: "Population and month", yl: "Number counted", bars: [["Frogs, Jan", 40], ["Frogs, Jun", 90], ["Snakes, Jan", 12], ["Snakes, Jun", 3]] }, marks: 4, kw: [["increase"], ["fewer frogs", "fewer of them", "eaten less", "less frogs"], ["decrease"], ["more frogs", "more grasshoppers"]], model: "(a) The frog population increased because there were fewer snakes, so fewer frogs were eaten. (b) The grasshopper population would decrease because there are more frogs, so more grasshoppers would be eaten." },
    { q: "Study the food web shown. A disease killed all the rabbits, but the snakes survived. Explain why.", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "snake"], ["bird", "eagle"], ["snake", "eagle"]] }, marks: 2, kw: [["frog", "bird"], ["other food", "another food", "other source", "another source", "still eat", "also eat"]], model: "The snake can still eat other food, such as frogs and birds, so it does not depend only on rabbits." },
    { q: "Study the food web shown. P is a green plant. A pupil said, ‘Q, R, S, T and U are all both predators and prey.’ (a) Explain why Q is NOT a predator. (b) Which organisms are both predators and prey?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["P", "S"], ["Q", "T"], ["Q", "V"], ["R", "T"], ["R", "U"], ["S", "U"], ["T", "V"], ["U", "V"]] }, marks: 3, kw: [["plant", "producer"], ["animal"], ["t and u", "u and t", "t, u", "u, t", "t & u"]], model: "(a) Q eats only P, which is a plant, while a predator is an animal that eats other animals. (b) T and U.", x: 1 },
    { q: "Two jars were set up as shown. The soil in jar B was heated strongly and then cooled before the dead leaves were added. (a) Why was the soil in jar B heated? (b) After four weeks, what would be observed in jar A? Explain.", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Dead leaves", "Garden soil", "Sealed, 25 °C"] }, { label: "B", icon: "jar", lines: ["Dead leaves", "Heated garden soil", "Sealed, 25 °C"] }] }, marks: 3, kw: [["kill"], ["broken down", "break down", "broke down", "decay", "rot"], ["bacteria", "fungi", "decomposer", "microorganism"]], model: "(a) To kill the decomposers in the soil. (b) The dead leaves in jar A would be broken down, because the bacteria and fungi in the garden soil break down dead matter." }
  ],
  doc: [
    { q: "In a food web, snakes are the only animals that eat frogs. If all the snakes died, what would happen to the frog population? Explain.", marks: 2, answers: ["The frogs would increase.", "The frog population would increase because fewer frogs would be eaten by snakes.", "The frogs would increase because they have more food."], best: 1, why: "Answer 2 gives the change and the correct feeding link. Answer 1 has no reason. Answer 3 gives a wrong reason: the snakes are the frogs’ predators, not their food." },
    { q: "In the food chain grass → goat, what does the arrow show?", marks: 1, answers: ["Energy flows from the grass to the goat when the goat eats the grass.", "The goat eats the grass.", "The grass goes to the goat."], best: 0, why: "Answer 1 uses the keyword ‘energy flows’ from the food to the eater. Answer 2 only describes feeding, and answer 3 is too vague." },
    { q: "Why is grass called a producer?", marks: 1, answers: ["It produces oxygen.", "It is green.", "It makes its own food using light energy from the Sun."], best: 2, why: "Producers make their own food. Grass does give off oxygen, but that is not why it is a producer; ‘it is green’ gives no reason." },
    { q: "Explain the role of decomposers in a forest.", marks: 2, answers: ["They break down dead plants and animals and return nutrients to the soil for plants to use.", "They eat dead things.", "They make the soil rotten."], best: 0, why: "Answer 1 has both ideas: break down dead matter and return nutrients to the soil. Answer 2 is vague and misses the nutrients; answer 3 is incorrect." },
    { q: "In a food web, snakes eat rabbits, frogs and birds. Explain why the snake population did not fall much when the rabbits died out.", marks: 2, answers: ["Snakes are predators.", "Snakes can live without food.", "Snakes can still eat other food, such as frogs and birds."], best: 2, why: "Answer 3 names the other food sources. Answer 1 does not explain anything, and answer 2 is wrong: snakes still need food." }
  ]
};
