window.LBY = window.LBY || {};
LBY["p6-webs"] = {
  lessons: [
    {
      h: "Decomposer experiments: aim, fair test and conclusion",
      concept: "Booklet B often tests decomposers with an experiment: dead leaves or bread kept in different conditions, then the mass left or the amount of mould is measured. The aim names BOTH variables: ‘To find out how [changed variable] affects [measured variable]’. A fair test changes only ONE variable; everything else (mass of leaves, type of soil, place, time) is kept the same. Remember that LESS mass left means MORE breaking down by decomposers. The conclusion states the relationship with a direction.",
      example: {
        q: "Aisha put 20 g of dead leaves on garden soil in each of two trays. She watered tray A every day and kept tray B dry. Both trays were placed in the same shady corner of the school garden. After 4 weeks she weighed the leaves left. (a) State the aim of her experiment. (b) Name two variables she kept the same. (c) What can she conclude?",
        tbl: [["Tray", "Soil", "Mass of leaves at start (g)", "Mass left after 4 weeks (g)"], ["A", "watered daily (moist)", "20", "12"], ["B", "kept dry", "20", "19"]],
        marks: 3,
        think: [
          "Step 1: The only thing she changed on purpose is whether the soil is moist or dry. She measured the mass of leaves left.",
          "Step 2: Aim = how moisture affects how fast dead leaves are broken down (measured by the mass left).",
          "Step 3: Kept the same: the starting mass of leaves (20 g), the type of soil, the place (same shady corner) and the time (4 weeks).",
          "Step 4: Read carefully: tray A had LESS mass left (12 g), so MORE of its leaves were broken down by decomposers."
        ],
        answer: "(a) To find out how the moisture of the soil affects how fast dead leaves are broken down. (b) The mass of dead leaves at the start and the place where the trays were kept. (c) Dead leaves are broken down faster on moist soil than on dry soil, because decomposers such as bacteria and fungi need water to grow and break down dead matter."
      },
      tip: "Less mass left = more decomposition. Do not write ‘tray A broke down less because it has less mass’ — that reads the data backwards.",
      try: {
        q: "Which change would make Aisha’s results more reliable?",
        o: ["Put 30 g of leaves in tray A and 20 g in tray B.", "Set up more trays for each condition and find the average.", "Move tray B to a sunnier spot so it dries faster.", "Weigh only the leaves in tray A at the end of the test."],
        a: 1,
        why: "Repeating the set-up and averaging makes the results more reliable. Changing the mass of leaves or the place would add a second changed variable and make the test unfair."
      }
    }
  ],
  mcq: [
    { q: "Study the food chain shown. Which organism does the frog eat?", fig: { type: "web", links: [["rice plant", "grasshopper"], ["grasshopper", "frog"], ["frog", "snake"]] }, o: ["rice plant", "grasshopper", "snake", "rice plant and grasshopper"], a: 1, why: "The arrow into the frog comes from the grasshopper, so the frog eats the grasshopper. The arrow from the frog to the snake means the frog is eaten by the snake.", lvl: 1 },
    { q: "Which of the following is NOT a decomposer?", o: ["bread mould", "bacteria in the soil", "bracket fungus on a log", "fern growing on a log"], a: 3, why: "Misconception: anything growing on a dead log is a decomposer. A fern is a green plant that makes its own food, so it is a producer. Moulds, bracket fungi and many bacteria are decomposers.", lvl: 1 },
    { q: "What does a food web show that a single food chain does not show?", o: ["Some organisms eat more than one kind of food.", "Energy flows from the food to the eater.", "A food chain begins with a producer.", "Some animals eat other animals for food."], a: 0, why: "A food web links many chains, so it shows that organisms have several foods and several predators. A single chain already shows energy flow, the producer and predators.", lvl: 1 },

    { q: "The diagram shows a food web in a grassland at a nature park. How many food chains are there?", fig: { type: "web", links: [["lalang", "grasshopper"], ["lalang", "rat"], ["grasshopper", "lizard"], ["grasshopper", "mynah"], ["lizard", "snake"], ["mynah", "owl"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, o: ["2", "3", "4", "5"], a: 2, why: "lalang → grasshopper → lizard → snake → owl; lalang → grasshopper → mynah → owl; lalang → rat → snake → owl; lalang → rat → owl. That is 4.", lvl: 2 },
    { q: "Study the grassland food web shown. Which organism is eaten by BOTH the snake and the owl?", fig: { type: "web", links: [["lalang", "grasshopper"], ["lalang", "rat"], ["grasshopper", "lizard"], ["grasshopper", "mynah"], ["lizard", "snake"], ["mynah", "owl"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, o: ["lizard", "rat", "mynah", "grasshopper"], a: 1, why: "The rat has one arrow to the snake and one to the owl. The lizard is eaten only by the snake and the mynah only by the owl.", lvl: 2 },
    { q: "Study the grassland food web shown. Which of these statements are correct? A: The owl is a predator only. B: The mynah is both a predator and a prey. C: The lizard is a prey only.", fig: { type: "web", links: [["lalang", "grasshopper"], ["lalang", "rat"], ["grasshopper", "lizard"], ["grasshopper", "mynah"], ["lizard", "snake"], ["mynah", "owl"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "Nothing eats the owl, so it is a predator only. The mynah eats grasshoppers and is eaten by owls. The lizard eats grasshoppers (animals), so it is a predator as well as a prey, and C is wrong.", lvl: 2 },
    { q: "Study the food web shown. K is a green plant. Which organism has the MOST kinds of predators?", fig: { type: "web", links: [["K", "Y"], ["K", "Z"], ["Y", "S"], ["Y", "T"], ["Y", "V"], ["Z", "V"], ["S", "V"], ["T", "V"]] }, o: ["V", "S", "Z", "Y"], a: 3, why: "Misconception: the organism with the most arrows pointing IN has the most predators. Arrows into V show its four FOODS. Arrows going OUT show predators: Y is eaten by S, T and V, so Y has 3 kinds of predators.", lvl: 2 },
    { q: "Wei Ming set up four slices of bread as shown. Which two set-ups should he compare to find out whether moisture affects how fast mould grows on bread?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Dry bread", "Warm cupboard", "Covered"] }, { label: "B", icon: "plate", lines: ["Moist bread", "Warm cupboard", "Covered"] }, { label: "C", icon: "plate", lines: ["Moist bread", "Refrigerator", "Covered"] }, { label: "D", icon: "plate", lines: ["Dry bread", "Refrigerator", "Uncovered"] }] }, o: ["A and C", "B and D", "A and B", "C and D"], a: 2, why: "A and B differ only in moisture. A and C also differ in temperature, while B and D and C and D also differ in whether the bread is covered, so they are not fair tests.", lvl: 2 },
    { q: "The table shows what four animals in a garden eat. Which animal is an omnivore?", tbl: [["Animal", "What it eats"], ["caterpillar", "papaya leaves"], ["bulbul", "papaya fruit, caterpillars"], ["spider", "caterpillars"], ["gecko", "spiders, caterpillars"]], o: ["caterpillar", "bulbul", "spider", "gecko"], a: 1, why: "The bulbul eats papaya fruit (part of a plant) and caterpillars (animals). The caterpillar is a herbivore, and the spider and gecko eat only animals.", lvl: 2 },

    { q: "The diagram shows a food web on a rocky shore at Changi. Which of these statements are correct? A: The crab is an omnivore. B: The starfish is a predator only. C: If all the crabs died, 3 food chains would be broken.", fig: { type: "web", links: [["seaweed", "sea snail"], ["seaweed", "sea urchin"], ["seaweed", "crab"], ["sea snail", "crab"], ["sea snail", "starfish"], ["sea urchin", "starfish"], ["crab", "octopus"], ["crab", "otter"], ["octopus", "otter"]] }, o: ["A only", "B and C only", "A, B and C", "A and B only"], a: 3, why: "The crab eats seaweed and sea snails, so it is an omnivore. The starfish eats animals and nothing eats it. The crab is in 4 chains (2 from seaweed directly, 2 through the sea snail), not 3.", lvl: 3 },
    { q: "Study the rocky-shore food web shown. How many food chains include the sea snail?", fig: { type: "web", links: [["seaweed", "sea snail"], ["seaweed", "sea urchin"], ["seaweed", "crab"], ["sea snail", "crab"], ["sea snail", "starfish"], ["sea urchin", "starfish"], ["crab", "octopus"], ["crab", "otter"], ["octopus", "otter"]] }, o: ["1", "2", "3", "4"], a: 2, why: "seaweed → sea snail → crab → octopus → otter; seaweed → sea snail → crab → otter; seaweed → sea snail → starfish. That is 3.", lvl: 3 },
    { q: "The diagram shows a food web in a pond at Bishan Park. How many food chains include the guppy?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "mosquito larva"], ["water flea", "guppy"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "dragonfly nymph"], ["water plant", "snail"], ["water plant", "terrapin"], ["snail", "terrapin"], ["dragonfly nymph", "kingfisher"], ["guppy", "kingfisher"]] }, o: ["2", "3", "4", "5"], a: 2, why: "There are 2 paths into the guppy (via water flea or mosquito larva) and 2 paths out (to the kingfisher directly, or via the dragonfly nymph). 2 × 2 = 4.", lvl: 3 },
    { q: "Dead leaves (50 g in each jar) were kept on moist garden soil at different temperatures. The graph shows the mass of leaves left after 4 weeks. Which conclusion is correct?", fig: { type: "bar", xl: "Temperature (°C)", yl: "Mass of leaves left (g)", bars: [["5", 48], ["15", 40], ["25", 22], ["35", 12]] }, o: ["From 5 °C to 35 °C, the higher the temperature, the faster the leaves were broken down.", "From 5 °C to 35 °C, the higher the temperature, the slower the leaves were broken down.", "The leaves were broken down only when the temperature was 25 °C or higher.", "The temperature did not affect how fast the dead leaves were broken down."], a: 0, why: "Misconception: less mass left means less breaking down. In fact less mass left means MORE of the leaves were broken down by decomposers, and the mass left fell as the temperature rose. At 15 °C the leaves had already lost 10 g.", lvl: 3 },
    { q: "Study the pond food web shown. Which organisms are prey but NOT predators?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "mosquito larva"], ["water flea", "guppy"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "dragonfly nymph"], ["water plant", "snail"], ["water plant", "terrapin"], ["snail", "terrapin"], ["dragonfly nymph", "kingfisher"], ["guppy", "kingfisher"]] }, o: ["water flea, snail and guppy", "mosquito larva, guppy and snail", "water flea, mosquito larva and terrapin", "water flea, mosquito larva and snail"], a: 3, why: "Misconception: every animal that is eaten is also a predator. The water flea, mosquito larva and snail eat only producers, so they are prey only. The guppy eats animals, and nothing eats the terrapin.", lvl: 3 },
    { q: "Study the grassland food web shown. All the rats are killed by poison. Which of the following would most likely happen at first?", fig: { type: "web", links: [["lalang", "grasshopper"], ["lalang", "rat"], ["grasshopper", "lizard"], ["grasshopper", "mynah"], ["lizard", "snake"], ["mynah", "owl"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, o: ["The lalang would decrease.", "The owls would eat more mynahs.", "The lizards would increase.", "The owls would die out."], a: 1, why: "Misconception: losing one food makes a predator die out. The owl still eats mynahs and snakes, so it eats more of them. The snake eats more lizards, so lizards decrease, and the lalang is eaten less.", lvl: 3 },
    { q: "Which of these statements about decomposers are correct? A: Some bacteria are decomposers. B: Decomposers break down animal waste as well as dead organisms. C: Mushrooms are producers because they grow out of the ground.", o: ["A and B only", "A and C only", "B and C only", "A, B and C"], a: 0, why: "Bacteria and fungi break down dead organisms and waste, returning nutrients to the soil. Mushrooms have no chlorophyll and cannot make food, so C is wrong.", lvl: 3 },

    { q: "Study the food web shown. J and K are green plants. Which ONE organism, if it died out, would break the greatest number of food chains?", fig: { type: "web", links: [["J", "L"], ["J", "M"], ["K", "M"], ["K", "N"], ["L", "P"], ["M", "P"], ["M", "Q"], ["N", "Q"], ["P", "R"], ["Q", "R"]] }, o: ["L", "M", "P", "Q"], a: 1, why: "There are 6 chains. M is in 4 of them (J → M → P → R, J → M → Q → R, K → M → P → R, K → M → Q → R). P and Q are each in 3, and L is in only 1.", lvl: 4 },
    { q: "Study the pond food web shown. All the guppies are removed. Which statements are most likely true at first? A: The water fleas would increase. B: The kingfishers would eat more dragonfly nymphs. C: The terrapins would decrease.", fig: { type: "web", links: [["algae", "water flea"], ["algae", "mosquito larva"], ["water flea", "guppy"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "dragonfly nymph"], ["water plant", "snail"], ["water plant", "terrapin"], ["snail", "terrapin"], ["dragonfly nymph", "kingfisher"], ["guppy", "kingfisher"]] }, o: ["A only", "B and C only", "A and B only", "A, B and C"], a: 2, why: "The guppy is the water flea’s only predator, so water fleas increase. The kingfisher’s only other food is the dragonfly nymph, so it eats more of them. The terrapin has no link to the guppy, so C is not supported.", lvl: 4 },
    { q: "Study the rocky-shore food web shown. Most of the starfish are removed. Which statements are most likely true at first? A: The sea urchins would increase. B: The otters would decrease. C: More sea snails would be left for the crabs to eat.", fig: { type: "web", links: [["seaweed", "sea snail"], ["seaweed", "sea urchin"], ["seaweed", "crab"], ["sea snail", "crab"], ["sea snail", "starfish"], ["sea urchin", "starfish"], ["crab", "octopus"], ["crab", "otter"], ["octopus", "otter"]] }, o: ["A only", "B and C only", "A, B and C", "A and C only"], a: 3, why: "The starfish is the sea urchin’s only predator, so urchins increase. Fewer sea snails are eaten by starfish, so crabs have more snails to eat. The otter does not eat starfish, and its food (crabs) may even increase, so B is wrong.", lvl: 4 },
    { q: "Study the grassland food web shown. The table shows some populations before and two months after a change. Which change most likely caused these results?", fig: { type: "web", links: [["lalang", "grasshopper"], ["lalang", "rat"], ["grasshopper", "lizard"], ["grasshopper", "mynah"], ["lizard", "snake"], ["mynah", "owl"], ["rat", "snake"], ["rat", "owl"], ["snake", "owl"]] }, tbl: [["Organism", "Before", "Two months after"], ["grasshopper", "300", "450"], ["lizard", "40", "5"], ["mynah", "30", "45"], ["rat", "100", "60"]], o: ["A disease killed most of the lizards.", "Many of the snakes were caught.", "Many of the owls were hunted.", "More lalang grew in the grassland."], a: 0, why: "Fewer lizards → fewer grasshoppers eaten, so grasshoppers rise → more food for mynahs, so mynahs rise. The snake loses the lizard and eats more rats, so rats fall. Removing snakes or owls would make rats increase, and more lalang would make all rise.", lvl: 4 }
  ],
  tf: [
    { s: "Decomposers are found only in the soil.", a: false, why: "Decomposers such as bacteria and moulds are also found in water, on food and in the air as spores." },
    { s: "An eagle’s energy does not come from the Sun because an eagle does not eat plants.", a: false, why: "The energy in the eagle’s prey came from plants that absorbed light energy from the Sun." },
    { s: "If all decomposers disappeared, dead plants and animals would break down faster.", a: false, why: "Without decomposers, dead matter would hardly break down and would pile up." },
    { s: "A carnivore can never be a prey.", a: false, why: "A snake eats frogs (a carnivore) and is eaten by eagles, so it is also a prey." },
    { s: "Bread mould grows faster in a dry, cold place than in a warm, moist place.", a: false, why: "Moulds need water and grow faster in warm conditions." },
    { s: "An organism that is eaten by two different animals in a food web is found in at least two food chains.", a: true, why: "Each of its predators leads to a different path, so there are at least two chains through it." },
    { s: "Plants grow well partly because decomposers return nutrients to the soil.", a: true, why: "Plants absorb these mineral salts through their roots." },
    { s: "Removing a producer from a food web can affect animals that never eat that producer.", a: true, why: "The effect spreads along the feeding links, e.g. to the predators of the herbivores that eat it." },
    { s: "Fungi such as moulds get their food from dead or decaying matter instead of making their own food.", a: true, why: "Fungi have no chlorophyll, so they cannot make food using light energy." },
    { s: "An omnivore can be both a predator and a prey.", a: true, why: "A bulbul eats fruit and caterpillars (so it is a predator) and can be eaten by a hawk-eagle." }
  ],
  oe: [
    { q: "Wei Ming placed three similar slices of bread as shown. After 5 days, bread A had a lot of mould, bread B had no mould and bread C had a little mould. (a) Which two set-ups should he compare to find out if moisture affects the growth of mould? (b) State one variable, other than those shown, that he should keep the same. (c) What can he conclude from set-ups A and C?", fig: { type: "setups", items: [{ label: "A", icon: "plate", lines: ["Moist bread", "Warm cupboard", "Covered"] }, { label: "B", icon: "plate", lines: ["Dry bread", "Warm cupboard", "Covered"] }, { label: "C", icon: "plate", lines: ["Moist bread", "Refrigerator", "Covered"] }] }, marks: 3, kw: [["a and b", "b and a", "a & b"], ["size of", "type of bread", "kind of bread", "same bread", "amount of", "mass of", "number of days", "same container", "thickness"], ["warm place", "warmer", "higher temperature", "faster in the warm", "more in the warm", "more mould in the warm", "in a warm"]], model: "(a) A and B. (b) The type of bread used. (c) Mould grows faster in a warm place than in a cold place." },
    { q: "Dead leaves (50 g in each jar) were kept on moist garden soil at different temperatures. The graph shows the mass of leaves left after 4 weeks. (a) State the aim of the experiment. (b) Describe the relationship shown by the results. (c) Explain why the mass of the leaves decreased. (d) Suggest one way to make the results more reliable.", fig: { type: "bar", xl: "Temperature (°C)", yl: "Mass of leaves left (g)", bars: [["5", 48], ["15", 40], ["25", 22], ["35", 12]] }, marks: 4, x: 1, kw: [["how temperature affect", "how the temperature affect", "effect of temperature", "whether temperature", "how does temperature", "how does the temperature"], ["higher the temperature", "as the temperature increase", "as temperature increase", "temperature increased", "temperature increases", "warmer it is"], ["decomposer", "bacteria", "fungi", "microorganism", "microbe"], ["repeat", "more jars", "more sets", "average", "more set-ups", "more setups"]], model: "(a) To find out how temperature affects how fast dead leaves are broken down. (b) From 5 °C to 35 °C, the higher the temperature, the less mass of leaves was left, so the faster the leaves were broken down. (c) Decomposers such as bacteria and fungi in the soil broke down the dead leaves. (d) Repeat the experiment with more jars at each temperature and find the average mass left." },
    { q: "Nurul put 100 mosquito larvae into each of four tanks with the same volume of pond water. She added a different number of guppies to each tank and counted the larvae left after one day. (a) State the aim of her experiment. (b) Name one variable she kept the same. (c) What can she conclude from the results? (d) Explain how keeping guppies in ponds can help to reduce the number of mosquitoes.", tbl: [["Tank", "Number of guppies", "Larvae at start", "Larvae left after 1 day"], ["A", "0", "100", "100"], ["B", "2", "100", "70"], ["C", "4", "100", "40"], ["D", "6", "100", "12"]], marks: 4, kw: [["how the number of guppies", "how number of guppies", "effect of the number of guppies", "effect of number of guppies", "whether the number of guppies"], ["number of larvae at the start", "number of mosquito larvae at the start", "larvae at the start", "volume of", "amount of water", "size of the tank", "size of tank", "same tank"], ["more guppies", "greater the number of guppies", "number of guppies increase", "as the number of guppies"], ["eat the", "eat mosquito", "eat larvae", "eats the", "feed on", "adult"]], model: "(a) To find out how the number of guppies affects the number of mosquito larvae left. (b) The volume of pond water in each tank. (c) The more guppies there are, the fewer mosquito larvae are left after one day. (d) The guppies eat the mosquito larvae, so fewer larvae grow into adult mosquitoes." },
    { q: "Two trays of dead leaves were set up as shown. The soil in tray B was mixed with a chemical that kills fungi but does not harm plants or animals. After 6 weeks, most of the leaves in tray A had broken down, but most of the leaves in tray B had not. (a) What variable was changed in this experiment? (b) Why was the same amount of water added to both trays? (c) What can be concluded from the results?", fig: { type: "setups", items: [{ label: "A", icon: "box", lines: ["30 g dead leaves", "Garden soil", "50 ml water daily"] }, { label: "B", icon: "box", lines: ["30 g dead leaves", "Soil + chemical", "50 ml water daily"] }] }, marks: 3, kw: [["whether fungi", "if fungi", "presence of fungi", "fungi were present", "fungi are present", "chemical was added", "chemical added", "whether the chemical", "whether chemical", "if the chemical", "if chemical"], ["fair", "only one variable", "one variable", "only the fungi", "only difference"], ["fungi break down", "fungi help to break down", "fungi helped to break down", "fungi broke down", "fungi are needed"]], model: "(a) Whether fungi were present in the soil. (b) To make it a fair test, so that the only difference between the trays is whether fungi were present. (c) Fungi break down dead leaves." },
    { q: "Study the food web shown. J and K are green plants. (a) How many food chains are there? (b) How many food chains include M? (c) All of M die. Explain why the population of Q may decrease.", fig: { type: "web", links: [["J", "L"], ["J", "M"], ["K", "M"], ["K", "N"], ["L", "P"], ["M", "P"], ["M", "Q"], ["N", "Q"], ["P", "R"], ["Q", "R"]] }, marks: 3, x: 1, kw: [["6", "six"], ["4", "four"], ["less food", "lost one of its food", "loses one of its food", "fewer food", "less to eat", "lost a food", "loses a food"]], model: "(a) 6 food chains. (b) 4 food chains. (c) Q eats M, so Q would have less food. Q can still eat N, so it may decrease but not die out." },
    { q: "Study the pond food web shown. (a) Name the omnivore. (b) All the guppies are removed. Predict what would happen to the water flea population, and explain why. (c) Explain why the kingfisher population may not decrease much when the guppies are removed.", fig: { type: "web", links: [["algae", "water flea"], ["algae", "mosquito larva"], ["water flea", "guppy"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "dragonfly nymph"], ["water plant", "snail"], ["water plant", "terrapin"], ["snail", "terrapin"], ["dragonfly nymph", "kingfisher"], ["guppy", "kingfisher"]] }, marks: 4, kw: [["terrapin"], ["increase"], ["fewer water flea", "fewer of them", "eaten less", "less water flea", "only predator", "nothing eats", "fewer are eaten", "fewer will be eaten", "fewer would be eaten"], ["dragonfly"]], model: "(a) The terrapin. (b) The water flea population would increase, because the guppy is its only predator, so fewer water fleas would be eaten. (c) The kingfisher can still eat dragonfly nymphs, so it still has food." }
  ],
  doc: [
    { q: "Bread in a warm cupboard grew much more mould than bread in a refrigerator. Explain why.", marks: 2, answers: ["Mould likes warm places.", "Mould is a fungus that grows faster in warm conditions, so it grew and broke down the bread faster in the cupboard.", "The cold in the refrigerator killed all the mould on the bread."], best: 1, why: "Answer 2 names the mould as a fungus and links warmth to faster growth. Answer 1 is vague (‘likes’) with no scientific reason. Answer 3 is wrong: the bread in the refrigerator still grew a little mould, because cold slows fungi down rather than killing them." },
    { q: "In a pond food web, guppies eat water fleas and mosquito larvae, and are eaten by dragonfly nymphs and kingfishers. Explain why the guppy is both a predator and a prey.", marks: 2, answers: ["Guppies are small fish.", "Guppies eat and are eaten.", "Guppies eat water fleas and mosquito larvae, which are animals, and they are eaten by dragonfly nymphs and kingfishers."], best: 2, why: "Answer 3 names the animals the guppy eats (predator) and the animals that eat it (prey). Answer 2 has the right idea but names no organisms and does not say it eats ANIMALS. Answer 1 gives no feeding link." }
  ]
};
