window.LBX = window.LBX || {};
LBX["p6-webs"] = {
  notes: [
    { h: "One organism, many chains", t: "In a food web, one organism can be part of several food chains, and it can be at a different position in each one. For example, a bulbul may be the second organism in one chain and the fourth in another. To find how many chains include an organism, count only the complete paths from a producer to the end that pass through it. If that organism dies out, all of those chains are broken.", kw: ["part of several food chains", "complete paths", "chains are broken"] },
    { h: "Predator and prey numbers over time", t: "When a prey population increases, its predators have more food, so the predator population increases a while later. More predators then eat more prey, so the prey population decreases. With less food, the predator population later decreases too. On a table or graph, the change in the predator usually comes AFTER the change in its prey.", kw: ["more food", "more prey are eaten", "less food", "comes after"] },
    { h: "People and food webs", t: "Human activities such as spraying pesticides, overfishing, hunting and clearing forests remove organisms from a food web, and the effect spreads along the feeding links to other populations. People can also use feeding relationships on purpose: guppies are kept in ponds to eat mosquito larvae, and barn owls are encouraged in plantations to eat rats.", kw: ["remove organisms", "effect spreads", "eat mosquito larvae"] }
  ],
  traps: [
    "The more arrows point INTO an animal, the more predators it has -> WRONG. Arrows coming in show its FOODS; arrows going out show what eats it.",
    "If all the producers die, only the herbivores are affected -> WRONG. Every consumer in the web gets its energy from the producers, so ALL of them are affected in the end.",
    "When the prey increases, the predator increases at the very same time -> The predator usually rises a little LATER, after it has had more food to eat."
  ],
  lessons: [
    {
      h: "Reading predator–prey data",
      concept: "When a table or graph shows a predator and its prey, match every change to a feeding reason. Prey up → the predator has more food → the predator rises a little later. Predator up → more prey are eaten → the prey falls. Prey down → the predator has less food → the predator falls later. Quote the numbers you are using.",
      example: {
        q: "On a vegetable farm in Lim Chu Kang, ladybirds eat aphids. The table shows their numbers over five months. (a) Explain why the ladybird population increased from March to April. (b) Explain why the aphid population decreased from April to May.",
        tbl: [["Month", "Aphids", "Ladybirds"], ["Feb", "800", "30"], ["Mar", "1500", "40"], ["Apr", "900", "110"], ["May", "300", "90"], ["Jun", "500", "35"]],
        marks: 2,
        think: [
          "Step 1: Identify the predator (ladybird) and the prey (aphid).",
          "Step 2: (a) Look one step back: in March the aphids rose to 1500, so the ladybirds had more food and increased by April.",
          "Step 3: (b) In April there were 110 ladybirds, the most in the table, so more aphids were eaten and the aphids fell by May.",
          "Step 4: Give the change AND the feeding reason in each part."
        ],
        answer: "(a) The aphids increased to 1500 in March, so the ladybirds had more food and their population increased. (b) There were many more ladybirds in April, so more aphids were eaten by the ladybirds."
      },
      tip: "Look one step BACK in time: the predator’s change is usually explained by the prey number just before it.",
      try: {
        q: "Using the same table, which best explains why the ladybird population fell from April to June?",
        tbl: [["Month", "Aphids", "Ladybirds"], ["Feb", "800", "30"], ["Mar", "1500", "40"], ["Apr", "900", "110"], ["May", "300", "90"], ["Jun", "500", "35"]],
        o: ["The aphids increased, so the ladybirds had more food.", "More ladybirds were eaten by the aphids after April.", "The aphids decreased, so the ladybirds had less food.", "The aphids decreased, so the ladybirds had more food."],
        a: 2,
        why: "The aphids fell from 1500 to 300 by May, so the ladybirds had less food and decreased. Aphids do not eat ladybirds; the arrow goes from aphid to ladybird."
      }
    },
    {
      h: "Chains through one organism, and chains left after a removal",
      concept: "List every chain first. To count the chains THROUGH an organism, tick the ones that include it. If that organism dies out, every chain that included it is broken, so chains left = total chains − chains through that organism. Check every producer, because some chains may not pass through the organism at all.",
      example: {
        q: "The diagram shows a food web. J and K are green plants. (a) How many food chains include L? (b) If all of L die, how many food chains are left?",
        fig: { type: "web", links: [["J", "L"], ["K", "L"], ["K", "M"], ["L", "N"], ["M", "N"], ["M", "O"], ["N", "O"], ["L", "O"]] },
        marks: 2,
        think: [
          "Step 1: From J: J → L → N → O and J → L → O (2 chains).",
          "Step 2: From K: K → L → N → O, K → L → O, K → M → N → O and K → M → O (4 chains). Total = 6.",
          "Step 3: Chains with L: both chains from J and the two K → L chains = 4.",
          "Step 4: Chains left if L dies out = 6 − 4 = 2."
        ],
        answer: "(a) 4 food chains. (b) 2 food chains are left: K → M → N → O and K → M → O."
      },
      tip: "Chains left = total − chains through the organism. Write the chains down so you can cross out the broken ones.",
      try: {
        q: "The diagram shows a food web. G is a green plant. All of organism J die. How many food chains are left?",
        fig: { type: "web", links: [["G", "H"], ["G", "I"], ["H", "J"], ["I", "J"], ["I", "K"], ["J", "L"], ["K", "L"]] },
        o: ["0", "1", "2", "3"],
        a: 1,
        why: "There were 3 chains: G → H → J → L, G → I → J → L and G → I → K → L. The two chains with J are broken, so only G → I → K → L is left."
      }
    }
  ],
  mcq: [
    { q: "The diagram shows a food web in the sea near Sisters’ Islands. Which organism is the producer?", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, o: ["shrimp", "algae", "crab", "squid"], a: 1, why: "No arrow points into the algae; algae make their own food using light energy. The shrimp, crab and squid all eat other organisms.", lvl: 1 },
    { q: "What is the name for all the different populations of organisms living and interacting together in a habitat?", o: ["a population", "a food web", "a community", "a food chain"], a: 2, why: "A community is made up of many populations of different kinds. A population is only one kind of organism.", lvl: 1 },
    { q: "Study the sea food web shown. Which organisms does the shark eat?", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, o: ["squid and octopus", "small fish and squid", "crab and octopus", "octopus only"], a: 0, why: "The two arrows pointing INTO the shark come from the squid and the octopus. The shark does not eat small fish or crabs directly in this web.", lvl: 1 },
    { q: "The diagram shows a food web on a vegetable farm. Which organism eats the snail?", fig: { type: "web", links: [["cabbage", "caterpillar"], ["cabbage", "snail"], ["caterpillar", "bird"], ["snail", "bird"], ["caterpillar", "toad"], ["toad", "snake"], ["bird", "snake"], ["bird", "cat"]] }, o: ["cabbage", "caterpillar", "cat", "bird"], a: 3, why: "The only arrow leaving the snail points to the bird, so the snail is eaten by the bird. The cabbage is the snail’s food.", lvl: 1 },
    { q: "In the food chain seaweed → sea snail → crab, which organism is the herbivore?", o: ["seaweed", "sea snail", "crab", "none of them"], a: 1, why: "The sea snail eats only the seaweed, a producer. The crab eats an animal, and the seaweed makes its own food.", lvl: 1 },

    { q: "Study the farm food web shown. How many food chains are there?", fig: { type: "web", links: [["cabbage", "caterpillar"], ["cabbage", "snail"], ["caterpillar", "bird"], ["snail", "bird"], ["caterpillar", "toad"], ["toad", "snake"], ["bird", "snake"], ["bird", "cat"]] }, o: ["2", "3", "4", "5"], a: 3, why: "cabbage → caterpillar → bird → snake; → caterpillar → bird → cat; → caterpillar → toad → snake; → snail → bird → snake; → snail → bird → cat. That is 5.", lvl: 2 },
    { q: "Study the sea food web shown. Which organism is an omnivore?", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, o: ["shrimp", "small fish", "octopus", "shark"], a: 1, why: "The small fish eats algae (a producer) and shrimp (an animal). The shrimp eats only algae, and the octopus and shark eat only animals.", lvl: 2 },
    { q: "The diagram shows a food web in a reservoir. Which organism is found in EVERY food chain of this web?", fig: { type: "web", links: [["algae", "mosquito larva"], ["water plant", "snail"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "catfish"], ["dragonfly nymph", "catfish"], ["snail", "catfish"], ["catfish", "otter"], ["guppy", "otter"]] }, o: ["catfish", "guppy", "mosquito larva", "otter"], a: 3, why: "All 4 chains end at the otter. The chain algae → mosquito larva → guppy → otter misses the catfish, and the chain from the water plant misses the guppy and the larva.", lvl: 2 },
    { q: "The table shows what each animal in a field eats. How many food chains can be formed from this information?", tbl: [["Animal", "What it eats"], ["grasshopper", "lalang"], ["spider", "grasshopper"], ["lizard", "grasshopper, spider"], ["snake", "lizard"]], o: ["1", "2", "3", "4"], a: 1, why: "lalang → grasshopper → lizard → snake and lalang → grasshopper → spider → lizard → snake. The spider is not eaten by the snake, so no chain ends at the spider.", lvl: 2 },
    { q: "The diagram shows a food web in a forest at Bukit Timah. Which organism is a herbivore?", fig: { type: "web", links: [["fig tree", "caterpillar"], ["fig tree", "bulbul"], ["fig tree", "macaque"], ["caterpillar", "bulbul"], ["caterpillar", "spider"], ["spider", "bulbul"], ["caterpillar", "macaque"], ["bulbul", "python"], ["macaque", "python"], ["bulbul", "hawk-eagle"]] }, o: ["caterpillar", "bulbul", "macaque", "spider"], a: 0, why: "The caterpillar eats only the fig tree. The bulbul and macaque eat the fig tree AND animals (omnivores), and the spider eats caterpillars.", lvl: 2 },
    { q: "Guppies eat mosquito larvae. Guppies were added to a pond at the end of Week 2. The graph shows the number of mosquito larvae in the pond. Which best explains the change after Week 2?", fig: { type: "line", xl: "Week", yl: "Number of mosquito larvae", pts: [["0", 300], ["1", 320], ["2", 310], ["3", 170], ["4", 90], ["5", 60], ["6", 50]] }, o: ["More algae were eaten by the mosquito larvae.", "Fewer mosquito larvae were eaten by the guppies.", "Fewer algae were left over for the guppies to eat.", "More mosquito larvae were eaten by the guppies."], a: 3, why: "The guppies are predators of the larvae, so after they were added more larvae were eaten and the number fell. Larvae eating more algae would help them increase, not decrease.", lvl: 2 },
    { q: "Study the sea food web shown. Which food chain can be found in this food web?", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, o: ["algae → shrimp → small fish → octopus → shark", "algae → small fish → shrimp → squid → shark", "algae → shrimp → crab → octopus → shark", "algae → shrimp → crab → squid → shark"], a: 2, why: "Each arrow in this chain is in the web: shrimp eat algae, crabs eat shrimp, octopuses eat crabs and sharks eat octopuses. The octopus does not eat small fish, and the squid does not eat crabs.", lvl: 2 },
    { q: "A pupil counted 35 mudskippers living on one mudflat at Sungei Buloh on the same morning. What did she count?", o: ["a community", "a population", "a food web", "a habitat"], a: 1, why: "Organisms of the same kind living in the same place at the same time form a population. A community would include all the different kinds of organisms there.", lvl: 2 },

    { q: "Study the food web shown. A is a green plant. Which organisms are both a predator and a prey?", fig: { type: "web", links: [["A", "B"], ["A", "C"], ["A", "D"], ["B", "E"], ["C", "E"], ["C", "F"], ["D", "F"], ["E", "G"], ["F", "G"], ["D", "G"]] }, o: ["E and F only", "B, C and D only", "E, F and G only", "D, E and F only"], a: 0, why: "E and F eat animals and are eaten by G. B, C and D eat only the plant A, so they are not predators. G eats animals but nothing eats G.", lvl: 3 },
    { q: "Study the farm food web shown. A disease kills all the birds. Which statements are most likely true at first? 1: The snails would increase. 2: The cats would decrease. 3: The snakes would eat more toads. 4: The cabbages would increase.", fig: { type: "web", links: [["cabbage", "caterpillar"], ["cabbage", "snail"], ["caterpillar", "bird"], ["snail", "bird"], ["caterpillar", "toad"], ["toad", "snake"], ["bird", "snake"], ["bird", "cat"]] }, o: ["1, 2 and 3 only", "1 and 2 only", "2, 3 and 4 only", "1, 3 and 4 only"], a: 0, why: "The bird is the snail’s only predator and the cat’s only food; the snake’s only other food is the toad. With more snails and caterpillars, MORE cabbage is eaten, so 4 is wrong.", lvl: 3 },
    { q: "Study the reservoir food web shown. All the snails die. Which of the following would most likely happen?", fig: { type: "web", links: [["algae", "mosquito larva"], ["water plant", "snail"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "catfish"], ["dragonfly nymph", "catfish"], ["snail", "catfish"], ["catfish", "otter"], ["guppy", "otter"]] }, o: ["The catfish would die out, as it has lost its only food.", "The water plant would decrease, as more of it is eaten.", "The catfish would eat more guppies and dragonfly nymphs.", "The otters would die out, as they have lost all their food."], a: 2, why: "The catfish still has guppies and dragonfly nymphs to eat, so it eats more of them. The water plant is eaten LESS, and the otters still have catfish and guppies.", lvl: 3 },
    { q: "Study the forest food web shown. How many food chains include the spider?", fig: { type: "web", links: [["fig tree", "caterpillar"], ["fig tree", "bulbul"], ["fig tree", "macaque"], ["caterpillar", "bulbul"], ["caterpillar", "spider"], ["spider", "bulbul"], ["caterpillar", "macaque"], ["bulbul", "python"], ["macaque", "python"], ["bulbul", "hawk-eagle"]] }, o: ["2", "3", "4", "5"], a: 0, why: "fig tree → caterpillar → spider → bulbul → python and fig tree → caterpillar → spider → bulbul → hawk-eagle. The path splits only after the bulbul.", lvl: 3 },
    { q: "Lizards eat grasshoppers. The table shows the numbers of grasshoppers and lizards in a field over five years. Which best explains the fall in the lizard population in Year 4?", tbl: [["Year", "Grasshoppers", "Lizards"], ["1", "400", "20"], ["2", "600", "26"], ["3", "300", "45"], ["4", "150", "30"], ["5", "350", "18"]], o: ["The lizards had less food, as there were fewer grasshoppers.", "The lizards had more food, as there were more grasshoppers.", "The grasshoppers had less food, as there were more lizards.", "The grasshoppers ate more of the lizards’ food in Year 3."], a: 0, why: "The grasshoppers fell from 600 to 300 and then 150, so the lizards had less food and decreased a year later. The lizards and grasshoppers do not compete for the same food.", lvl: 3 },
    { q: "Study the sea food web shown. Overfishing removes most of the squid. Which statements are most likely true? 1: The small fish would increase. 2: The sharks would eat more octopuses. 3: The shrimps would decrease.", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, o: ["1 only", "1 and 2 only", "2 and 3 only", "1, 2 and 3"], a: 3, why: "The squid is the small fish’s only predator, so small fish increase and eat more shrimps. The shark’s only other food is the octopus, so it eats more octopuses.", lvl: 3 },
    { q: "Study the food web shown. P and Q are green plants. How many food chains include S?", fig: { type: "web", links: [["P", "R"], ["P", "S"], ["Q", "S"], ["Q", "T"], ["R", "U"], ["S", "U"], ["S", "V"], ["T", "V"], ["U", "W"], ["V", "W"], ["T", "W"]] }, o: ["2", "3", "4", "5"], a: 2, why: "P → S → U → W, P → S → V → W, Q → S → U → W and Q → S → V → W. S is eaten by two animals and eats two plants, so 2 × 2 = 4.", lvl: 3 },

    { q: "Study the forest food web shown. How many food chains are there?", fig: { type: "web", links: [["fig tree", "caterpillar"], ["fig tree", "bulbul"], ["fig tree", "macaque"], ["caterpillar", "bulbul"], ["caterpillar", "spider"], ["spider", "bulbul"], ["caterpillar", "macaque"], ["bulbul", "python"], ["macaque", "python"], ["bulbul", "hawk-eagle"]] }, o: ["5", "6", "7", "8"], a: 3, why: "There are 3 paths to the bulbul (direct, via caterpillar, via caterpillar and spider), each ending at the python or hawk-eagle = 6, plus 2 paths to the macaque ending at the python = 8.", lvl: 4 },
    { q: "Study the forest food web shown. Which statement is NOT correct?", fig: { type: "web", links: [["fig tree", "caterpillar"], ["fig tree", "bulbul"], ["fig tree", "macaque"], ["caterpillar", "bulbul"], ["caterpillar", "spider"], ["spider", "bulbul"], ["caterpillar", "macaque"], ["bulbul", "python"], ["macaque", "python"], ["bulbul", "hawk-eagle"]] }, o: ["The macaque is an omnivore.", "The spider is both a predator and a prey.", "Three food chains include the macaque.", "Five food chains include the caterpillar."], a: 2, why: "Only 2 chains include the macaque: fig tree → macaque → python and fig tree → caterpillar → macaque → python. The caterpillar is in 5 chains (4 through the bulbul and 1 through the macaque).", lvl: 4 },
    { q: "Study the food web shown. P and Q are green plants. A disease kills all of T. Which statements are correct? 1: V would eat more of S. 2: W would die out. 3: The number of food chains would fall from 7 to 5.", fig: { type: "web", links: [["P", "R"], ["P", "S"], ["Q", "S"], ["Q", "T"], ["R", "U"], ["S", "U"], ["S", "V"], ["T", "V"], ["U", "W"], ["V", "W"], ["T", "W"]] }, o: ["1 only", "1 and 3 only", "2 and 3 only", "1, 2 and 3"], a: 1, why: "V still has S to eat, so it eats more S. W still eats U and V, so it does not die out. T is in 2 of the 7 chains (Q → T → V → W and Q → T → W), so 5 are left.", lvl: 4 },
    { q: "Study the food web shown. P and Q are green plants. If all of S die out, how many food chains would be left?", fig: { type: "web", links: [["P", "R"], ["P", "S"], ["Q", "S"], ["Q", "T"], ["R", "U"], ["S", "U"], ["S", "V"], ["T", "V"], ["U", "W"], ["V", "W"], ["T", "W"]] }, o: ["1", "2", "3", "4"], a: 2, why: "There are 7 chains and 4 pass through S, so 3 are left: P → R → U → W, Q → T → V → W and Q → T → W.", lvl: 4 }
  ],
  tf: [
    { s: "An organism can belong to more than one food chain in a food web.", a: true, why: "In a web, an organism may eat several foods or be eaten by several animals, so it appears in many chains." },
    { s: "The number of arrows pointing into an animal shows how many kinds of predators it has.", a: false, why: "Arrows coming in show its kinds of FOOD; arrows going out show its predators." },
    { s: "All the plants and animals living in a pond form a community.", a: true, why: "A community is all the different populations living together in one habitat." },
    { s: "If all the producers in a food web died, only the herbivores would be affected.", a: false, why: "All consumers depend on the producers for energy, so carnivores and omnivores would be affected too." },
    { s: "An omnivore eats at least one kind of plant as well as animals.", a: true, why: "Omnivores eat both plants and animals." },
    { s: "Guppies can help to control mosquitoes in ponds because they eat mosquito larvae.", a: true, why: "Fewer larvae survive to grow into adult mosquitoes." },
    { s: "When the prey population increases, the predator population always decreases.", a: false, why: "More prey means more food for the predator, so the predator population usually increases later." },
    { s: "Energy flows in one direction in a food chain, from the producer to the consumers.", a: true, why: "Energy passes to each eater along the arrows; it is not passed back to the plant." },
    { s: "Every food chain must have at least four organisms.", a: false, why: "A food chain can be short, e.g. grass → goat has only two organisms." },
    { s: "A herbivore that eats many kinds of plants is a predator.", a: false, why: "A predator eats other animals. A herbivore eats only plants, however many kinds." }
  ],
  sort: [
    { title: "Is each group a population, a community, or neither?", groups: ["Population", "Community", "Neither"], items: [["all the mynahs in Bishan Park on one morning", 0], ["all the guppies in a pond", 0], ["all the rain trees along one road", 0], ["all the plants and animals in a pond", 1], ["the fish, crabs, seaweed and corals on a reef", 1], ["every kind of organism in Sungei Buloh", 1], ["one mynah sitting on a tree", 2], ["the stones and water in a pond", 2]] }
  ],
  oe: [
    { q: "Study the farm food web shown. (a) Name one organism that is both a predator and a prey. (b) How many food chains are there in this food web? (c) Name the organism that eats both the toad and the bird.", fig: { type: "web", links: [["cabbage", "caterpillar"], ["cabbage", "snail"], ["caterpillar", "bird"], ["snail", "bird"], ["caterpillar", "toad"], ["toad", "snake"], ["bird", "snake"], ["bird", "cat"]] }, marks: 3, kw: [["bird", "toad"], ["5", "five"], ["snake"]], model: "(a) The toad: it eats caterpillars and is eaten by snakes. (b) There are 5 food chains. (c) The snake." },
    { q: "Study the reservoir food web shown. To reduce mosquitoes, guppies were added to a pond with this food web. (a) Explain how adding guppies can reduce the number of mosquitoes. (b) Suggest why the catfish population may increase after the guppies are added.", fig: { type: "web", links: [["algae", "mosquito larva"], ["water plant", "snail"], ["mosquito larva", "guppy"], ["mosquito larva", "dragonfly nymph"], ["guppy", "catfish"], ["dragonfly nymph", "catfish"], ["snail", "catfish"], ["catfish", "otter"], ["guppy", "otter"]] }, marks: 3, kw: [["eat mosquito larva", "eat the mosquito larva", "eats mosquito larva", "eats the mosquito larva", "larvae are eaten", "larva are eaten", "eat the larva", "eat larva"], ["fewer", "less"], ["more food", "more guppies", "more to eat"]], model: "(a) The guppies eat mosquito larvae, so fewer larvae grow into adult mosquitoes. (b) The catfish eat guppies, so with more guppies the catfish have more food." },
    { q: "Study the sea food web shown. Overfishing removes most of the sharks. (a) What would happen to the squid population? Explain. (b) Explain why the crab population may decrease.", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, marks: 4, kw: [["squid would increase", "squid will increase", "squid population would increase", "squid population will increase", "squid population increase", "squids increase", "squid increase", "squids would increase", "squids will increase", "increase in squid", "more squid", "it would increase", "it will increase", "it increase"], ["fewer squid", "fewer of them", "eaten less", "less squid"], ["more octopus", "octopuses increase", "octopus population increase", "octopuses would increase"], ["eat more crab", "more crabs are eaten", "more crabs would be eaten", "more crabs eaten", "eat more of the crab"]], model: "(a) The squid population would increase because fewer squid would be eaten, as the shark is the squid’s only predator. (b) Fewer octopuses would be eaten by sharks, so there would be more octopuses. More octopuses would eat more crabs, so the crabs may decrease.", x: 1 },
    { q: "In an oil palm plantation, rats eat the oil palm fruits and barn owls eat rats. Farmers put up nest boxes for barn owls in Year 1. The table shows the numbers counted. (a) Describe what happened to the rat population from Year 2 to Year 4 and explain why. (b) Suggest why the barn owl population fell in Year 5.", tbl: [["Year", "Barn owls", "Rats"], ["1", "10", "900"], ["2", "25", "880"], ["3", "60", "500"], ["4", "70", "200"], ["5", "40", "180"]], marks: 3, kw: [["decrease", "fell", "fall", "dropped"], ["more rats were eaten", "more rats are eaten", "more rats eaten", "eaten by more owls", "eaten by more barn owls", "more owls eat", "more barn owls eat", "more owls ate", "more barn owls ate"], ["fewer rats", "less rats", "less food", "not enough food"]], model: "(a) The rat population decreased because there were more barn owls, so more rats were eaten. (b) There were fewer rats, so the barn owls had less food." },
    { q: "Study the food web shown. A is a green plant. (a) Name all the herbivores. (b) All of G are removed. Explain why D may increase. (c) Explain why C may decrease after G is removed.", fig: { type: "web", links: [["A", "B"], ["A", "C"], ["A", "D"], ["B", "E"], ["C", "E"], ["C", "F"], ["D", "F"], ["E", "G"], ["F", "G"], ["D", "G"]] }, marks: 4, kw: [["b, c and d", "b, c, d", "b,c,d", "b c d", "b, c & d", "b c and d", "b,c and d", "b, c, and d"], ["fewer d are", "fewer d is", "fewer d will", "fewer d would", "fewer d get", "fewer of d", "d is eaten less", "d are eaten less", "d is not eaten", "less d is", "less of d"], ["more e and f", "more e and more f", "e and f increase", "e and f would increase", "e and f will increase", "more of e", "more of f"], ["eat more c", "more c are eaten", "more c is eaten", "c is eaten more", "more of c"]], model: "(a) B, C and D. (b) G eats D, so when G is removed, fewer D are eaten. (c) Fewer E and F are eaten by G, so there are more E and F. More E and F eat more C, so C may decrease.", x: 1 },
    { q: "Study the forest food web shown. (a) Explain why the macaque is an omnivore. (b) Name the organism in this web that eats three different kinds of organisms.", fig: { type: "web", links: [["fig tree", "caterpillar"], ["fig tree", "bulbul"], ["fig tree", "macaque"], ["caterpillar", "bulbul"], ["caterpillar", "spider"], ["spider", "bulbul"], ["caterpillar", "macaque"], ["bulbul", "python"], ["macaque", "python"], ["bulbul", "hawk-eagle"]] }, marks: 3, kw: [["plant", "producer", "fig tree"], ["animal", "caterpillar", "insect"], ["bulbul"]], model: "(a) The macaque eats the fig tree, which is a plant, and also eats caterpillars, which are animals. (b) The bulbul, which eats the fig tree, caterpillars and spiders." },
    { q: "Explain why every food chain starts with a producer.", marks: 2, kw: [["make its own food", "makes its own food", "make their own food", "make food", "makes food", "produce food", "produce its own food"], ["light energy", "sun"]], model: "Only a producer can make its own food, using light energy from the Sun. All other organisms get their energy by eating other organisms, so energy enters the food chain through the producer." },
    { q: "Study the sea food web shown. A pupil said, ‘The small fish is a carnivore.’ Explain why the pupil is wrong.", fig: { type: "web", links: [["algae", "shrimp"], ["algae", "small fish"], ["shrimp", "small fish"], ["shrimp", "crab"], ["small fish", "squid"], ["crab", "octopus"], ["squid", "shark"], ["octopus", "shark"]] }, marks: 2, kw: [["algae", "plant", "producer"], ["omnivore", "both plants and animals", "plants and animals"]], model: "The small fish eats algae, which is a producer, as well as shrimps, which are animals. It eats both plants and animals, so it is an omnivore, not a carnivore." }
  ],
  doc: [
    { q: "Guppies eat mosquito larvae. Explain why keeping guppies in a pond can reduce the number of mosquitoes.", marks: 2, answers: ["Guppies eat mosquitoes.", "Guppies eat the mosquito larvae, so fewer larvae grow into adult mosquitoes.", "Guppies keep the water clean, so mosquitoes cannot live there."], best: 1, why: "Answer 2 names the larvae as the guppies’ food and links it to fewer adult mosquitoes. Answer 1 is inaccurate (guppies eat the larvae in the water, not flying mosquitoes), and answer 3 gives a wrong reason with no feeding link." },
    { q: "What is a community?", marks: 1, answers: ["All the populations of different organisms living together in a habitat.", "A group of organisms of the same kind living in one place.", "A place where many plants and animals live."], best: 0, why: "Answer 1 has the key idea of different populations living together. Answer 2 describes a population, and answer 3 describes a habitat." },
    { q: "Barn owls eat rats and snakes. Most of the snakes were killed, but the barn owl population did not decrease much. Explain why.", marks: 2, answers: ["The barn owls did not need snakes.", "The barn owls are strong and can survive.", "The barn owls could still eat rats, their other food."], best: 2, why: "Answer 3 names the other food source. Answer 1 is vague and wrong (snakes were one of its foods), and answer 2 gives no feeding reason at all." }
  ]
};
