window.LBZ = window.LBZ || {};
LBZ["p6-webs"] = {
  flash: [
    { f: "Define: food chain", b: "A food chain shows the food relationships between organisms (who eats whom). It starts with a producer, and each arrow points from the food to the organism that eats it." },
    { f: "Define: food web", b: "A food web is made up of two or more food chains that are linked together." },
    { f: "What does the arrow in a food chain show?", b: "It means ‘is eaten by’. It points from the food to the eater and shows the direction in which energy flows." },
    { f: "Define: producer", b: "An organism that makes its own food by photosynthesis, using light energy from the Sun, e.g. green plants and algae." },
    { f: "Define: consumer", b: "An organism that cannot make its own food, so it gets its energy by eating other organisms." },
    { f: "Herbivore, carnivore and omnivore", b: "A herbivore eats only plants. A carnivore eats only animals. An omnivore eats both plants and animals." },
    { f: "Define: predator and prey", b: "A predator is an animal that hunts and eats other animals. The animal that is hunted and eaten is its prey." },
    { f: "Define: decomposer", b: "An organism, such as fungi and some bacteria, that breaks down dead plants, dead animals and their waste, returning nutrients to the soil." },
    { f: "Define: population", b: "A group of organisms of the same kind living in the same place at the same time." },
    { f: "Define: community", b: "All the different populations of organisms living and interacting together in the same habitat." },
    { f: "Why does every food chain start with a producer?", b: "Only producers can make their own food using light energy from the Sun. All consumers get their energy, directly or indirectly, from producers." },
    { f: "Why does an eagle’s energy come from the Sun?", b: "Plants absorb light energy to make food. The energy is passed to the animals that eat the plants, then along the food chain to the eagle." },
    { f: "An animal’s only predator is removed. What happens to the animal’s population?", b: "It increases at first because fewer of the animals are eaten. Later it may decrease because there is not enough food for the larger population." },
    { f: "Why is an animal with many food sources less affected when one food decreases?", b: "It can eat more of its other foods, so it still has enough food to survive." },
    { f: "What would happen if there were no decomposers?", b: "Dead matter would pile up, and nutrients would not be returned to the soil, so plants would not grow well." }
  ],
  mcq: [
    { q: "The diagram shows a food chain in a pond. Which organism traps light energy from the Sun to make food?", fig: { type: "web", links: [["hydrilla", "snail"], ["snail", "small fish"], ["small fish", "heron"]] }, o: ["snail", "heron", "hydrilla", "small fish"], a: 2, why: "Hydrilla is a water plant. It is the producer, so it absorbs light energy to make food by photosynthesis. The snail, small fish and heron are consumers that get energy by eating.", lvl: 1 },
    { q: "At a hawker centre, Ravi eats chicken rice. The chicken had been fed on corn. Which food chain is correct?", o: ["corn → chicken → Ravi", "Ravi → chicken → corn", "chicken → corn → Ravi", "corn → Ravi → chicken"], a: 0, why: "A food chain starts with the producer (corn), and each arrow points from the food to its eater: corn is eaten by the chicken, and the chicken is eaten by Ravi.", lvl: 1 },
    { q: "A pupil wrote this food chain: Sun → grass → cow. What is wrong with it?", o: ["The arrows should point from the cow back to the grass.", "A cow is an omnivore, so it cannot follow the grass.", "A food chain must always end with a carnivore.", "The Sun is not an organism, so it is not part of the chain."], a: 3, why: "A food chain shows only organisms and who eats whom, so it starts with the producer (grass). The Sun is the source of energy but is not an organism. The arrows here are the right way round, and a cow is a herbivore.", lvl: 1 },
    { q: "Study the food web shown. How many kinds of organisms eat the grasshopper?", fig: { type: "web", links: [["grass", "grasshopper"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["grasshopper", "lizard"], ["frog", "snake"], ["lizard", "snake"]] }, o: ["1", "2", "3", "4"], a: 2, why: "Three arrows point away from the grasshopper: to the frog, the bird and the lizard. The arrow from the grass points INTO the grasshopper, which shows its food, not its predator.", lvl: 1 },

    { q: "The diagram shows a food web in a field at Punggol. How many food chains are there?", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rat"], ["grasshopper", "mynah"], ["grasshopper", "lizard"], ["lizard", "snake"], ["rat", "snake"], ["mynah", "snake"]] }, o: ["2", "3", "4", "5"], a: 1, why: "Start at the grass and follow every path to the snake: grass → grasshopper → mynah → snake; grass → grasshopper → lizard → snake; grass → rat → snake. That is 3 food chains.", lvl: 2 },
    { q: "Some vegetable farms in Kranji release ladybirds onto their crops to control aphids instead of spraying pesticide. Why does this protect the crops?", o: ["Ladybirds are predators that eat the aphids feeding on the crops.", "Ladybirds are producers that make extra food for the crops.", "Ladybirds are decomposers that return nutrients to the soil.", "Ladybirds are prey that draw birds away from the crops."], a: 0, why: "Ladybirds eat aphids, so fewer aphids are left to feed on the crops. Ladybirds are animals, so they cannot make food, and they are not decomposers.", lvl: 2 },
    { q: "The diagram shows a food web on the shore of Pulau Semakau. Which food chain is NOT found in this food web?", fig: { type: "web", links: [["seaweed", "sea snail"], ["seaweed", "sea urchin"], ["sea snail", "crab"], ["sea urchin", "crab"], ["crab", "octopus"], ["sea snail", "fish"], ["fish", "octopus"]] }, o: ["seaweed → sea snail → crab → octopus", "seaweed → sea urchin → crab → octopus", "seaweed → sea snail → fish → octopus", "seaweed → sea urchin → fish → octopus"], a: 3, why: "The sea urchin is eaten only by the crab; there is no arrow from the sea urchin to the fish. The other three paths all follow arrows in the web.", lvl: 2 },
    { q: "The table shows what some animals in a forest eat. Which animal is a predator but NOT a prey?", tbl: [["Animal", "Food it eats"], ["mouse", "seeds, insects"], ["frog", "insects"], ["snake", "mouse, frog"], ["owl", "mouse, snake"]], o: ["owl", "mouse", "frog", "snake"], a: 0, why: "No animal in the table eats the owl, and it eats other animals, so it is a predator only. The mouse and frog eat insects but are eaten by the snake; the snake is eaten by the owl.", lvl: 2 },
    { q: "Jia Hui wants to find out whether temperature affects how fast dead leaves are broken down. Each set-up has 30 g of the same dead leaves. Which two set-ups should she compare?", fig: { type: "setups", items: [{ label: "A", icon: "jar", lines: ["Moist soil", "30 °C", "Kept for 3 weeks"] }, { label: "B", icon: "jar", lines: ["Dry soil", "30 °C", "Kept for 3 weeks"] }, { label: "C", icon: "jar", lines: ["Moist soil", "10 °C", "Kept for 3 weeks"] }, { label: "D", icon: "jar", lines: ["Dry soil", "10 °C", "Kept for 2 weeks"] }] }, o: ["A and B", "A and C", "B and D", "C and D"], a: 1, why: "A and C differ ONLY in temperature. A and B, and C and D, differ in moisture instead. B and D differ in both temperature and time, so that test is not fair.", lvl: 2 },
    { q: "Study the food chain shown. Which statements are correct? A: The caterpillar is a prey. B: The bulbul is both a predator and a prey. C: The cat is a herbivore.", fig: { type: "web", links: [["mango leaf", "caterpillar"], ["caterpillar", "bulbul"], ["bulbul", "cat"]] }, o: ["A only", "B only", "A and C only", "A and B only"], a: 3, why: "The caterpillar is eaten by the bulbul (prey). The bulbul eats the caterpillar and is eaten by the cat (both). The cat eats an animal, so it is a carnivore, not a herbivore.", lvl: 2 },
    { q: "House lizards in an HDB flat eat mosquitoes, moths and ants. The family sprays an insecticide that kills most of the insects in the flat. What would most likely happen to the house lizards?", o: ["They would increase because they have fewer predators.", "They would decrease or leave because they have less food.", "They would stay the same because they make their own food.", "They would increase because there is more space for them."], a: 1, why: "The insects are the lizards’ food. With most insects killed, the lizards have less food, so they decrease or move away. Lizards are consumers and cannot make their own food.", lvl: 2 },

    { q: "Study the food web shown. P and Q are green plants. How many food chains are there, and how many of them include V?", fig: { type: "web", links: [["P", "R"], ["P", "S"], ["Q", "S"], ["Q", "T"], ["R", "U"], ["S", "U"], ["S", "V"], ["T", "V"], ["U", "W"], ["V", "W"]] }, o: ["5 food chains; 3 include V", "6 food chains; 3 include V", "6 food chains; 4 include V", "7 food chains; 3 include V"], a: 1, why: "From P: P-R-U-W, P-S-U-W, P-S-V-W. From Q: Q-S-U-W, Q-S-V-W, Q-T-V-W. That is 6 chains, and 3 of them (P-S-V-W, Q-S-V-W, Q-T-V-W) pass through V.", lvl: 3 },
    { q: "Study the food web shown. K is a green plant. All of M are removed. Which statements are most likely true at first? 1: O would decrease. 2: N would eat more of L. 3: K would increase.", fig: { type: "web", links: [["K", "L"], ["K", "M"], ["L", "N"], ["M", "N"], ["M", "O"], ["N", "P"], ["O", "P"]] }, o: ["1 and 2 only", "1 and 3 only", "2 and 3 only", "1, 2 and 3"], a: 3, why: "O eats only M, so O loses its only food and decreases. N loses one food, so it eats more of its other food, L. With M gone, fewer K are eaten, so K increases. All three are likely.", lvl: 3 },
    { q: "In a greenhouse at Gardens by the Bay, spider mites feed on the plants. Gardeners released predatory mites, which eat spider mites, in Week 1. The table shows the numbers counted. Which best explains the change in predatory mites from Week 3 to Week 5?", tbl: [["Week", "Spider mites", "Predatory mites"], ["1", "800", "50"], ["2", "500", "120"], ["3", "200", "200"], ["4", "100", "150"], ["5", "120", "60"]], o: ["They had less food because few spider mites were left to eat.", "They were eaten by the spider mites, which had increased.", "They had more food because the plants had grown larger.", "They were replaced by spider mites eating the same food."], a: 0, why: "The predatory mites ate so many spider mites that few were left (200 → 100 → 120). With less food, the predatory mites fell from 200 to 60. Spider mites eat plants, not predatory mites.", lvl: 3 },
    { q: "In a pond at Bishan Park, tadpoles and snails eat water plants. Dragonfly nymphs eat tadpoles. Fish eat dragonfly nymphs and snails. Herons eat fish and tadpoles. How many food chains are there?", o: ["1", "2", "3", "4"], a: 2, why: "Water plant → tadpole → dragonfly nymph → fish → heron; water plant → tadpole → heron; water plant → snail → fish → heron. That is 3 food chains. Do not forget that herons eat tadpoles directly.", lvl: 3 },
    { q: "The diagram shows a food web in a reservoir. A pesticide washed into the reservoir and killed most of the water fleas. Which change would most likely happen at first?", fig: { type: "web", links: [["algae", "water flea"], ["algae", "snail"], ["water flea", "small fish"], ["snail", "small fish"], ["small fish", "snakehead"], ["small fish", "heron"]] }, o: ["The algae would increase.", "The snakeheads would increase.", "The herons would increase.", "The small fish would increase."], a: 0, why: "Fewer water fleas eat the algae, so the algae increase. The small fish lose one of their foods, so they will not increase, and so the snakeheads and herons will not gain more food either.", lvl: 3 },
    { q: "Bats roost in a dark cave where no green plants grow. At night, they fly out to eat insects that feed on plants. Cave beetles inside feed on the bats’ droppings. Where did the energy in the cave beetles come from at first?", o: ["The warm rocks of the cave, which give off heat energy", "The bats’ droppings, which make food from the cave air", "The Sun, through the plants eaten by the insects outside", "The fungi in the cave, which are the producers there"], a: 2, why: "The plants outside absorbed light energy to make food. The insects ate the plants, the bats ate the insects, and the beetles feed on the bats’ droppings, so the energy came from the Sun. Droppings and fungi cannot make food.", lvl: 3 },

    { q: "Study the food web shown. A and B are green plants. Which organism, if it died out, would leave exactly 3 food chains in the web?", fig: { type: "web", links: [["A", "C"], ["A", "D"], ["B", "D"], ["B", "E"], ["C", "F"], ["D", "F"], ["D", "G"], ["E", "G"], ["F", "H"], ["G", "H"], ["E", "H"]] }, o: ["C", "D", "E", "F"], a: 1, why: "There are 7 chains: A-C-F-H, A-D-F-H, A-D-G-H, B-D-F-H, B-D-G-H, B-E-G-H, B-E-H. D is in 4 of them, so removing D leaves 3. Removing C leaves 6, E leaves 5, and F leaves 5 (A-C becomes a new chain because nothing then eats C).", lvl: 4 },
    { q: "Study the food web shown. All the frogs die. Which statements are most likely true at first? 1: The snakes would eat more rabbits. 2: The grasshoppers may increase. 3: The hawks would lose their only food. 4: The birds may have more food.", fig: { type: "web", links: [["grass", "grasshopper"], ["grass", "rabbit"], ["grass", "bird"], ["grasshopper", "frog"], ["grasshopper", "bird"], ["frog", "snake"], ["rabbit", "snake"], ["bird", "hawk"], ["snake", "hawk"]] }, o: ["1 and 2 only", "2, 3 and 4 only", "1, 3 and 4 only", "1, 2 and 4 only"], a: 3, why: "The snakes lose the frogs, so they eat more rabbits (1). Fewer grasshoppers are eaten, so they may increase (2), giving the birds more food (4). The hawks still eat birds and snakes, so 3 is wrong.", lvl: 4 },
    { q: "Study the food web shown. P is a green plant. All of T die. How many food chains are left in the web?", fig: { type: "web", links: [["P", "Q"], ["P", "R"], ["P", "S"], ["Q", "T"], ["R", "T"], ["R", "U"], ["S", "U"], ["T", "U"]] }, o: ["1", "2", "3", "4"], a: 2, why: "Before: P-Q-T-U, P-R-T-U, P-R-U, P-S-U. Without T, nothing eats Q, so P → Q becomes a complete chain. The chains left are P-Q, P-R-U and P-S-U: 3, not 2.", lvl: 4 }
  ],
  oe: [
    { q: "Study the food web shown. All the snakes were caught. (a) Predict what would happen to the rabbit population at first, and explain why. [2] (b) Explain why the grasshopper population may decrease. [1] (c) Explain why the rabbit population may decrease some time later. [1]", fig: { type: "web", links: [["grass", "rabbit"], ["grass", "grasshopper"], ["grasshopper", "bird"], ["rabbit", "snake"], ["bird", "snake"]] }, marks: 4, kw: [["increase"], ["fewer rabbits are eaten", "fewer rabbits eaten", "fewer rabbits would be eaten", "not eaten", "not be eaten", "no longer eaten", "no predator", "nothing eats", "no snakes to eat", "no more snakes"], ["more birds", "birds increase", "bird population increase", "birds would increase", "eaten by more birds"], ["less grass", "not enough grass", "not enough food", "less food", "grass decrease", "run out of grass", "run out of food", "lack of food"]], model: "(a) The rabbit population would increase at first, because fewer rabbits are eaten as there are no snakes. (b) No snakes eat the birds, so there would be more birds, and more grasshoppers are eaten by the birds. (c) There are now more rabbits eating the grass, so there is less grass and the rabbits do not have enough food." },
    { q: "On a vegetable farm in Kranji, frogs eat the insect pests that feed on the crops. Many frogs were caught for sale in Year 2, and the frogs were protected from Year 4. The table shows the numbers counted. (a) Describe what happened to the insect pests from Year 1 to Year 3, and explain why. [2] (b) Explain why the insect pests decreased from Year 3 to Year 5. [1] (c) In which year were the crops most likely damaged the most? Explain. [1]", tbl: [["Year", "Insect pests", "Frogs"], ["1", "500", "40"], ["2", "600", "15"], ["3", "900", "10"], ["4", "650", "30"], ["5", "450", "45"]], marks: 4, kw: [["increase", "rose", "went up"], ["fewer frogs", "less frogs", "frogs decrease", "frog population decrease", "frogs were caught", "fewer insect pests were eaten", "fewer insects were eaten", "fewer pests were eaten", "fewer of them were eaten"], ["more frogs", "frogs increase", "frog population increase", "number of frogs increase"], ["most insect", "most pests", "largest number of", "greatest number of", "highest number of", "most number of", "more insect pests feeding", "more insects feeding"]], model: "(a) The insect pests increased from 500 to 900, because there were fewer frogs, so fewer insect pests were eaten. (b) There were more frogs, so more insect pests were eaten. (c) Year 3, because there were the most insect pests feeding on the crops." },
    { q: "Farmers can control aphids on their vegetables by spraying a pesticide or by releasing ladybirds, which eat aphids. (a) Explain how releasing ladybirds can reduce the damage to the vegetables. [2] (b) The pesticide also kills many other insects. Explain why the population of birds that eat insects on the farm may decrease. [1] (c) State where the energy used by the ladybirds came from at first. [1]", marks: 4, kw: [["eat the aphid", "eat aphid", "eats aphid", "eats the aphid", "feed on aphid", "feed on the aphid", "prey on", "aphids are eaten"], ["fewer aphids", "less aphids", "aphids decrease", "aphid population decrease", "number of aphids decrease"], ["less food", "lesser food", "not enough food", "food decrease", "fewer insects to eat", "run out of food", "lose their food", "lost their food"], ["sun"]], model: "(a) The ladybirds eat the aphids, so there are fewer aphids to feed on the vegetables. (b) The birds have less food because many of the insects they eat are killed. (c) The Sun. The vegetables absorbed light energy to make food, which passed to the aphids and then to the ladybirds." },
    { q: "Study the food web shown. (a) How many food chains are there? [1] (b) All the mantises die. Which organism, other than the bird, would then not be eaten by any organism in this web? [1] (c) Explain why the bird population may not die out after the mantises die. [1] (d) Explain why the lizard population may decrease after the mantises die. [1]", fig: { type: "web", links: [["lalang", "grasshopper"], ["lalang", "caterpillar"], ["grasshopper", "mantis"], ["caterpillar", "mantis"], ["caterpillar", "lizard"], ["mantis", "bird"], ["lizard", "bird"]] }, marks: 4, x: 1, kw: [["3", "three"], ["grasshopper"], ["other food", "another food", "still has", "still eat", "other source", "another source", "still feed", "other kind of food", "can eat the lizard", "can eat lizard"], ["eat more lizard", "eat more of the lizard", "more lizards are eaten", "more lizards eaten", "more lizards would be eaten", "birds eat more", "bird eats more", "feed more on lizard"]], model: "(a) 3. (b) The grasshopper. (c) The bird still has the lizard as another source of food. (d) The bird has lost the mantis as food, so the birds eat more lizards and more lizards are eaten." }
  ],
  tf: [
    { s: "A predator is always bigger than its prey.", a: false, why: "Size does not decide it. A spider can eat a large moth, and ants working together can kill animals bigger than themselves; a predator is any animal that hunts and eats other animals." },
    { s: "A herbivore is always the second organism in a food chain.", a: true, why: "A herbivore eats plants, so it always comes straight after the producer." },
    { s: "Plants in a food web are not affected when a carnivore is removed, because carnivores do not eat plants.", a: false, why: "Removing a carnivore can let herbivores increase, and more herbivores eat more plants, so the plants can decrease." },
    { s: "A food chain can have only two organisms, such as algae → snail.", a: true, why: "Any complete path from a producer to an organism that is not eaten is a food chain, however short." },
    { s: "When a snake dies, decomposers return its energy to the grass so that the grass can make food.", a: false, why: "Decomposers return nutrients (mineral salts) to the soil, not energy. Plants get their energy only from sunlight." },
    { s: "The energy decomposers get from dead organisms first came from the Sun.", a: true, why: "Dead organisms got their energy from food that started with a producer, which trapped light energy from the Sun." },
    { s: "An omnivore must always be at the end of a food chain.", a: false, why: "An omnivore can be eaten too. For example, a chicken eats grain and worms but is eaten by a python." },
    { s: "A pesticide sprayed on crops can affect animals that never eat the crops.", a: true, why: "It can kill the insects that birds or frogs eat, so these animals have less food. Changes spread along feeding links." },
    { s: "An animal that eats only one kind of food is less likely to be affected when that food decreases.", a: false, why: "It is MORE likely to be affected, because it has no other food to turn to when its only food decreases." },
    { s: "Humans are omnivores and can be part of many food chains.", a: true, why: "Humans eat both plants (rice, vegetables) and animals (fish, chicken), so they appear in many food chains." }
  ],
  sort: [
    { title: "In the food chain grass → grasshopper → frog → snake, would the frog population most likely increase or decrease at first?", groups: ["Frogs likely increase", "Frogs likely decrease"], items: [["many snakes are caught", 0], ["a disease kills most of the snakes", 0], ["grass grows well after heavy rain", 0], ["many more grasshoppers hatch", 0], ["a pesticide kills most of the grasshoppers", 1], ["more snakes are released into the field", 1], ["a long drought kills most of the grass", 1], ["the field is cleared to build a road", 1]] }
  ]
};
