/* Field Guide collectible cards: e = picture, n = name, t = type, f = fact, r = rarity (1 common, 2 uncommon, 3 rare) */
const CARDS = [
  {e:"🐙", n:"Octopus", t:"Animal", r:2, f:"An octopus has three hearts and blue blood."},
  {e:"🦒", n:"Giraffe", t:"Animal", r:1, f:"A giraffe’s long neck has just seven bones, the same number as yours."},
  {e:"🐧", n:"Penguin", t:"Animal", r:1, f:"Penguins are birds that cannot fly. They use their wings as flippers to swim."},
  {e:"🦇", n:"Bat", t:"Animal", r:2, f:"Bats are the only mammals that can truly fly."},
  {e:"🐋", n:"Blue Whale", t:"Animal", r:3, f:"The blue whale is the largest animal known to have lived. It is a mammal and breathes air with its lungs."},
  {e:"🐝", n:"Honeybee", t:"Animal", r:1, f:"Bees carry pollen from flower to flower, which helps plants make fruits and seeds."},
  {e:"🦋", n:"Butterfly", t:"Animal", r:2, f:"Butterflies taste with their feet. Its young, the caterpillar, looks nothing like the adult."},
  {e:"🐸", n:"Frog", t:"Animal", r:1, f:"Many frogs can take in air through their moist skin as well as their lungs."},
  {e:"🦈", n:"Shark", t:"Animal", r:2, f:"A shark is a fish whose skeleton is made of cartilage, the bendy material in your ears, not bone."},
  {e:"🐌", n:"Snail", t:"Animal", r:1, f:"A snail is not an insect. It has no legs and moves on one muscular foot."},
  {e:"🐢", n:"Sea Turtle", t:"Animal", r:1, f:"Sea turtles are reptiles. They live in the sea but come onto beaches to lay their eggs."},
  {e:"🦎", n:"Chameleon", t:"Animal", r:2, f:"A chameleon’s tongue can be longer than its whole body."},
  {e:"🦉", n:"Owl", t:"Animal", r:2, f:"An owl cannot move its eyes, so it turns its head, about three-quarters of the way round."},
  {e:"🐜", n:"Ant", t:"Animal", r:1, f:"An ant can carry objects many times heavier than its own body."},
  {e:"🐬", n:"Dolphin", t:"Animal", r:1, f:"Dolphins are mammals. They breathe air through a blowhole on top of the head."},
  {e:"🦜", n:"Parrot", t:"Animal", r:1, f:"Some parrots can copy human words and other sounds they hear."},
  {e:"🐍", n:"Snake", t:"Animal", r:1, f:"A snake flicks its tongue to pick up smells from the air."},
  {e:"🦀", n:"Crab", t:"Animal", r:1, f:"A crab has ten legs, counting its two claws, so it is not an insect."},
  {e:"🦟", n:"Mosquito", t:"Animal", r:2, f:"Only female mosquitoes bite. They need blood to make their eggs."},
  {e:"🐞", n:"Ladybird", t:"Animal", r:1, f:"A ladybird is a beetle. It eats tiny insects called aphids that harm plants."},
  {e:"🪱", n:"Earthworm", t:"Animal", r:2, f:"An earthworm has no lungs. It takes in air through its moist skin."},
  {e:"🕷️", n:"Spider", t:"Animal", r:2, f:"A spider has eight legs and two body parts, so it is not an insect."},
  {e:"🐘", n:"Elephant", t:"Animal", r:3, f:"Elephants are the largest land animals. A baby elephant grows inside its mother for almost two years."},
  {e:"🦩", n:"Flamingo", t:"Animal", r:2, f:"Flamingos get their pink colour from the food they eat."},
  {e:"🌻", n:"Sunflower", t:"Plant", r:2, f:"The head of a sunflower is made of hundreds of tiny flowers packed together."},
  {e:"🌵", n:"Cactus", t:"Plant", r:2, f:"A cactus’s spines are its leaves. Being so thin, they lose very little water."},
  {e:"🌿", n:"Fern", t:"Plant", r:1, f:"Ferns do not make flowers or seeds. They reproduce by spores found under their leaves."},
  {e:"🌲", n:"Pine Tree", t:"Plant", r:1, f:"A pine tree never makes flowers. Its seeds grow inside cones."},
  {e:"🥥", n:"Coconut", t:"Plant", r:2, f:"A coconut fruit is light and waterproof, so it can float across the sea to a new place to grow."},
  {e:"🌾", n:"Rice", t:"Plant", r:1, f:"Rice is a flowering plant in the grass family. It is the main food of billions of people."},
  {e:"🌱", n:"Touch-me-not", t:"Plant", r:2, f:"The leaves of the Mimosa plant fold up quickly when you touch them. Plants respond to changes too."},
  {e:"🌺", n:"Rafflesia", t:"Plant", r:3, f:"Rafflesia has the biggest single flower in the world, and it smells like rotting meat to attract flies."},
  {e:"🍌", n:"Banana Plant", t:"Plant", r:2, f:"A banana plant is not a tree. Its ‘trunk’ is made of tightly rolled leaf stalks."},
  {e:"🌳", n:"Tree", t:"Plant", r:1, f:"In sunlight, trees take in carbon dioxide and give out oxygen while making food."},
  {e:"🍄", n:"Mushroom", t:"Fungus", r:1, f:"A mushroom is a fungus, not a plant. It cannot make its own food."},
  {e:"🍞", n:"Yeast", t:"Fungus", r:2, f:"Yeast is a tiny fungus. It gives off carbon dioxide gas, which makes bread dough rise."},
  {e:"🦠", n:"Gut Bacteria", t:"Microbe", r:1, f:"Trillions of helpful bacteria live in your intestines and help your body deal with food."},
  {e:"🪸", n:"Coral", t:"Animal", r:3, f:"Coral reefs are built by tiny animals called polyps, not plants or rocks."},
  {e:"🫀", n:"Heart", t:"Body", r:2, f:"Your heart beats about 100,000 times a day, pumping blood all around your body."},
  {e:"🫁", n:"Lungs", t:"Body", r:2, f:"Your right lung is a little bigger than your left, leaving room for your heart."},
  {e:"🦷", n:"Tooth", t:"Body", r:1, f:"The enamel on your teeth is the hardest material in your body."},
  {e:"🧠", n:"Brain", t:"Body", r:2, f:"Your brain uses about one-fifth of all the energy your body uses."},
  {e:"🦴", n:"Skeleton", t:"Body", r:1, f:"An adult has 206 bones. A baby is born with more, and some join together as it grows."},
  {e:"🧬", n:"DNA", t:"Body", r:3, f:"Your cells carry instructions called DNA. Half came from your mother and half from your father."},
  {e:"🧲", n:"Magnet", t:"Matter", r:2, f:"The Earth acts like a giant magnet. That is why a compass needle points north."},
  {e:"💎", n:"Diamond", t:"Matter", r:3, f:"Diamond is the hardest natural material. It is made of carbon, like pencil ‘lead’."},
  {e:"🧊", n:"Ice", t:"Matter", r:1, f:"Water expands when it freezes, so ice is lighter for its size than water and floats."},
  {e:"⚡", n:"Lightning", t:"Energy", r:2, f:"A lightning bolt is several times hotter than the surface of the Sun."},
  {e:"🌈", n:"Rainbow", t:"Energy", r:1, f:"A rainbow forms when raindrops split sunlight into its colours."},
  {e:"🔦", n:"Light", t:"Energy", r:2, f:"Light travels about 300,000 km every second, the fastest anything can go."},
  {e:"🔔", n:"Sound", t:"Energy", r:2, f:"Sound needs something to travel through, like air or water, so space is silent."},
  {e:"🔋", n:"Battery", t:"Energy", r:1, f:"A battery stores chemical potential energy, which changes into electrical energy in a closed circuit."},
  {e:"🌬️", n:"Wind Turbine", t:"Energy", r:2, f:"A wind turbine changes the kinetic energy of moving air into electrical energy."},
  {e:"☀️", n:"The Sun", t:"Space", r:2, f:"The Sun is a star. Its light takes about 8 minutes to reach the Earth."},
  {e:"🌙", n:"The Moon", t:"Space", r:1, f:"The Moon does not give out its own light. It reflects light from the Sun."},
  {e:"🪐", n:"Saturn", t:"Space", r:3, f:"Saturn is so light for its size that it would float in a big enough bath of water."},
  {e:"🌍", n:"Earth", t:"Space", r:1, f:"About 70% of the Earth’s surface is covered by water, but most of it is salty sea."}
];
